### DISCUSSION TITLE
Steps Template

### DISCUSSION THREAD

**Discussion by itayvolo** [argoproj/argo-workflows#10035] [Q&A]
Hey,
Im trying to get the step name by templating it in as an env variable inside a container (helm chart):

![image](https://user-images.githubusercontent.com/72027444/201934533-2523fb0a-8d68-42f5-8f01-a074bbf8a5c3.png)

and im getting this error which says it cant resolve it:
![image](https://user-images.githubusercontent.com/72027444/201934908-27eae59a-e5c0-48b6-8789-c191b0665163.png)

Doc example for steps.name :
![image](https://user-images.githubusercontent.com/72027444/201935075-f382067b-af53-413c-85a1-bfde9fe557ad.png)

https://argoproj.github.io/argo-workflows/variables/

**Comment by wesleyscholl** [comment]
@itayvolo 

The `steps.name` variable must be passed in as an input parameter. Directly passing `steps.name` as an env doesn't work, I attempted multiple times. 

```yaml
metadata:
  name: step-name-variable
  namespace: argo
spec:
  templates:
    - name: main
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: step-one
            template: template-one
            arguments: {}
    - name: template-one
      inputs:
        parameters:
          - name: step-name
            value: '{{steps.name}}' # Pass in steps.name variable as an input parameter
      outputs: {}
      metadata: {}
      container:
        name: main
        image: alpine:latest
        command:
          - /bin/sh
        args:
          - '-c'
          - |
            echo "Step Name: $stepname"  # Print the environment variable
        env:
          - name: stepname
            value: '{{inputs.parameters.step-name}}' # Set the steps.name env
        resources: {}
  entrypoint: main
  arguments: {}
```

Resources:

- https://argo-workflows.readthedocs.io/en/latest/variables/
- https://github.com/argoproj/argo-workflows/issues/7698
