### DISCUSSION TITLE
Argo Workflow: "Bad Request: json: cannot unmarshal string into Go struct field"

### DISCUSSION THREAD

**Discussion by johnlinp** [argoproj/argo-workflows#10041] [Q&A]
I have a Argo WorkflowTemplate that looks like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-container-command-env
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
        - name: command
        - name: env
    container:
      image: alpine:latest
      command: "{{ inputs.parameters.command }}"
      env: "{{ inputs.parameters.env }}"
```

What I want to do is to create a WorkflowTemplate that can execute an arbitrary command specified by the input parameter `command`, with a list of arbitrary environment variables specified by the input parameter `env`. That way, users of this WorkflowTemplate can supply the parameter `command` with an array of strings and `env` with an array of environment variables, and then execute it like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-run-
spec:
  workflowTemplateRef:
    name: test-container-command-env
  entrypoint: main
  arguments:
    parameters:
    - name: command
      value:
        - curl
        - "-O"
        - https://example.com/
    - name: env
      value:
        - name: HTTPS_PROXY
          value: myproxy:5566
```

However, when I try to save this WorkflowTemplate, the Argo server gave me this error message:

```
Bad Request: json: cannot unmarshal string into Go struct field Container.workflow.spec.templates.container.command of type []string
```

It seems that Argo expects the field `.spec.templates.container.command` to be an array of strings, but it treat `"{{ inputs.parameters.command }}"` as a string, even though I'm trying to supply the parameter `command` with an array of strings. Another issue is about `.spec.templates.container.env`. When I temporarily remove `command`, similar error about `env` will show:

```
Bad Request: json: cannot unmarshal string into Go struct field Container.template.spec.templates.container.env of type []v1.EnvVar
```

Is there any way to achieve what I was trying to do as the WorkflowTemplate `test-container-command-env`, i.e. provide a WorkflowTemplate for the user to execute arbitrary commands with arbitrary environment variables?
