### DISCUSSION TITLE
Argo workflows - Workflow variable Invalid Json format

### DISCUSSION THREAD

**Discussion by sharadhirao** [argoproj/argo-workflows#10082] [Q&A]
Hi Team, 

I was trying to get the {{workflow.failures}} variable. When I output it Its giving me invalid json format. What I am doing is :
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-workflow-
  namespace: argo-workflows
spec:
  entrypoint: Argo-Config-Checkout
  onExit: exit-handler
  serviceAccountName: workflow
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: Argo-Config-Checkout
    dag:
      tasks:   
      - name: check-env
        template: check-env
        arguments:
          parameters:
            - name: branch
              value: argo

  
  - name: check-env
    inputs:
      parameters:
      - name: branch
    container:
      image: ubuntu
      command: [sh, -c]
      args: ["echo {{inputs.parameters.branch}} | tr /- _; exit 1"]   
  - name: exit-handler
    steps:
    - - name: celebrate
        template: celebrate
  - name: celebrate
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{workflow.failures}}"]
```

By doing this I am trying to capture the workflow failure details, But I am getting this as output, 

```
[{"displayName":"argo-workflow-gjjns","message":"","templateName":"Argo-Config-Checkout","phase":"Failed","podName":"argo-workflow-g
jjns","finishedAt":"2022-11-21T15:43:25Z"},{"displayName":"check-env","message":"Error (exit code 1)","templateName":"check-env","ph
ase":"Failed","podName":"argo-workflow-gjjns-2534872201","finishedAt":"2022-11-21T15:43:20Z"}]
```
When I try to expand this I get this, and you can see after the pod name it went to next line.
```
[
  {
    "displayName":"argo-workflow-gjjns",
    "message":"",
    "templateName":"Argo-Config-Checkout",
    "phase":"Failed",
    "podName":"argo-workflow-g
jjns",
"finishedAt":"2022-11-21T15:43:25Z"
},
{"displayName":"check-env",
"message":"Error (exit code 1)",
"templateName":"check-env","ph
ase":"Failed",
"podName":"argo-workflow-gjjns-2534872201",
"finishedAt":"2022-11-21T15:43:20Z"
}
]
```
If you see the format is only wrong. I want to send this data to a notification channel, But I am getting the error as invalid json format. I guess this is issue from argocd. If not please tell me how to do it? @alexec 

Thank you.

**Comment by wesleyscholl** [comment]
@sharadhirao 

According to the Argo Workflows documentation, the output JSON is correct.

| **Variable**         | **Description**                                                                                                                      |
|-----------------------|--------------------------------------------------------------------------------------------------------------------------------------|
| `workflow.failures`   | A list of JSON objects with details about nodes that failed or errored. Available fields: `displayName`, `message`, `templateName`, `phase`, `podName`, and `finishedAt`. |


When running this workflow, this is the output I get from the exit handler:

```shell
[{"displayName":"argo-workflow-jvhpb","message":"","templateName":"Argo-Config-Checkout","phase":"Failed","podName":"argo-workflow-jvhpb","finishedAt":"2024-12-02T15:28:13Z"},{"displayName":"check-env","message":"Error (exit code 1)","templateName":"check-env","phase":"Failed","podName":"argo-workflow-jvhpb-check-env-4255976317","finishedAt":"2024-12-02T15:28:04Z"}]
time="2024-12-02T15:28:20 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
```

To convert to valid JSON, you could use either of these methods:

```yaml
# Using toJson() built in Argo Workflows function
args: ["echo '{{=toJson(workflow.failures)}}'"] # converts to JSON

# Using tr
args: ["echo '{{workflow.failures}}' | tr -d '\\n'"] # Removes new lines
```

Outputs:

```shell
# toJson() output

"[{\"displayName\":\"argo-workflow-pm2dr\",\"message\":\"\",\"templateName\":\"Argo-Config-Checkout\",\"phase\":\"Failed\",\"podName\":\"argo-workflow-pm2dr\",\"finishedAt\":\"2024-12-02T15:50:20Z\"},{\"displayName\":\"check-env\",\"message\":\"Error (exit code 1)\",\"templateName\":\"check-env\",\"phase\":\"Failed\",\"podName\":\"argo-workflow-pm2dr-check-env-76813750\",\"finishedAt\":\"2024-12-02T15:50:18Z\"}]"

# tr output

"\"[{\\\"displayName\\\":\\\"check-env\\\",\\\"message\\\":\\\"Error (exit code 1)\\\",\\\"templateName\\\":\\\"check-env\\\",\\\"phase\\\":\\\"Failed\\\",\\\"podName\\\":\\\"argo-workflow-4j5fh-check-env-3055544644\\\",\\\"finishedAt\\\":\\\"2024-12-02T15:37:48Z\\\"},{\\\"displayName\\\":\\\"argo-workflow-4j5fh\\\",\\\"message\\\":\\\"\\\",\\\"templateName\\\":\\\"Argo-Config-Checkout\\\",\\\"phase\\\":\\\"Failed\\\",\\\"podName\\\":\\\"argo-workflow-4j5fh\\\",\\\"finishedAt\\\":\\\"2024-12-02T15:37:51Z\\\"}]\""
```

**Resources**

- https://argo-workflows.readthedocs.io/en/latest/variables/#exit-handler
- https://argo-workflows.readthedocs.io/en/latest/variables/#expression
