### DISCUSSION TITLE
Question on Exit Handlers

### DISCUSSION THREAD

**Discussion by ghost** [argoproj/argo-workflows#10190] [Q&A]
I want to use a template as an exit handler, but it requires an email parameter

There is an entrypoint while executing the workflow (Consider this as a workflow template ), which implies that we cannot set the global parameter while starting it from the UI

Is there any workaround for this?

``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  
metadata:
  name: test5    
spec:
  entrypoint: etp         
  onExit: exit-handler
  templates:
    - name: etp
      steps:
      - - name: hello           
          template: whalesay

    - name: exit-handler
      steps:
      - - name: exit-handler
          arguments:
            parameters:
              - name: name
                value: '{{workflow.name}}'
              - name: recipient
                value: 'avinash.nadendla@system73.com' #Email needs to be passsed form the UI
          when: "{{workflow.status}} != Succeeded"
          templateRef:
              name: email-sender
              clusterScope: true
              template: email-exit-handler

    - name: whalesay 
      container:
        image: docker/whalesay
        command: [ cowsa ]
        args: [ "hello world" ]

```

**Comment by wesleyscholl** [comment]
@avinashnadendla 

Add a workflow input parameter:

```yaml
metadata:
  name: test5
...
    - name: exit-handler
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: exit-handler-step
            arguments:
              parameters:
                - name: name
                  value: '{{workflow.name}}'
                - name: recipient
                  value: '{{workflow.parameters.recipient}}' # Pass the workflow input parameter
            templateRef:
              name: email-sender
              template: email-exit-handler
            when: '{{workflow.status}} != Succeeded'
    ...
  arguments:
    parameters:
      - name: recipient # UI input parameter
        value: default@example.com # UI input value
  onExit: exit-handler

```

The recipient parameter will be passed to the `templateRef` workflow.

Resources:

- https://github.com/argoproj/argo-workflows/blob/97b94f0f67714beacd7b6f2ef086d13f09cd158f/examples/workflow-template/hello-world.yaml
- https://github.com/argoproj/argo-workflows/blob/main/examples/workflow-template/steps.yaml
