### DISCUSSION TITLE
argo-workflows/walk-through/exit-handlers/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#10216] [General]
# argo-workflows/walk-through/exit-handlers/

https://argoproj.github.io/argo-workflows/walk-through/exit-handlers/

**Comment by Paritosh-Anand** [comment]
Will this also work with `WorkflowTemplate` and `ClusterWorkflowTemplate` ?

* kind: WorkflowTemplate
* kind: ClusterWorkflowTemplate

**Reply by Paritosh-Anand** [reply]
Ignore the question :) 
I was able to use hooks for my use case.

**Reply by enrico-spadaTR** [reply]
@Paritosh-Anand exploring how to implement Slack Alerts in WorkflowTemplate:
1. why you did not implement it using exit-handler?
2. could you please elaborate a bit better how / what hook you used to setup slack alerts?

**Reply by Paritosh-Anand** [reply]
Your use case seems very similar to mine i.e. for github & slack notifications.

I used hooks with steps in my template to call cluster workflow template which holds the logic to send these notifications or alerts.

Sharing a sample workflow template below (hope it helps)

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

templates:
  - name: java
    steps:
      - - name: build
          template: maven-build
          hooks:
            failed:
              expression: steps["maven-build"].status == "Failed"
              arguments:
                parameters:
                  - name: state
                    value: failure
                  - name: context
                    value: "maven-build"
              templateRef:
                name: slack
                template: alert
                clusterScope: true

```
