### DISCUSSION TITLE
Internal Server Error: xxx only valid in container/script templates

### DISCUSSION THREAD

**Discussion by jinyunshaobing** [argoproj/argo-workflows#10239] [Q&A]
I'm new in argo-workflows and when i try to create a ClusterWorkflowTemplate,an error accurred.

`Internal Server Error: templates.main templates.main.inputs.artifacts.src.path only valid in container/script templates`

What's wrong with it? Can someone help me?

```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: kaniko1
  uid: d3f10b5e-479a-40ec-af9c-c570a9964158
  generation: 6
  creationTimestamp: '2022-03-22T05:05:51Z'
  labels:
    app.kubernetes.io/instance: argo-pipelines
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: context
          - name: dockerfile
            value: ./Dockerfile
          - name: image
          - name: version
          - name: extra_args
          - name: image-tag-joiner
            value: .
        artifacts:
          - name: src
            path: /src/
          - name: docker-config
            path: /kaniko/.docker/
      outputs:
        parameters:
          - name: image-tag-simple
            valueFrom:
              parameter: '{{steps.tag.outputs.parameters.image-tag-simple}}'
          - name: image-tag-full
            valueFrom:
              parameter: '{{steps.tag.outputs.parameters.image-tag-full}}'
      metadata: {}
      steps:
        - - name: tag
            template: tag
            arguments:
              parameters:
                - name: image-tag-full
                  value: >-
                    {{inputs.parameters.version}}{{inputs.parameters.image-tag-joiner}}{{=sprig.date('20060102150405',workflow.creationTimestamp)}}
                - name: image-tag-simple
                  value: '{{inputs.parameters.version}}'
        - - name: build
            template: build
            arguments:
              parameters:
                - name: context
                  value: '{{inputs.parameters.context}}'
                - name: dockerfile
                  value: '{{inputs.parameters.dockerfile}}'
                - name: image
                  value: '{{inputs.parameters.image}}'
                - name: version
                  value: '{{inputs.parameters.version}}'
                - name: extra_args
                  value: '{{inputs.parameters.extra_args}}'
                - name: tag-full
                  value: '{{steps.tag.outputs.parameters.image-tag-full}}'
                - name: tag-simple
                  value: '{{steps.tag.outputs.parameters.image-tag-simple}}'
              artifacts:
                - name: src
                  from: '{{inputs.artifacts.src}}'
                - name: docker-config
                  from: '{{inputs.artifacts.docker-config}}'
    - name: tag
      inputs:
        parameters:
          - name: image-tag-full
          - name: image-tag-simple
      outputs:
        parameters:
          - name: image-tag-full
            valueFrom:
              path: /tmp/image-tag-full
          - name: image-tag-simple
            valueFrom:
              path: /tmp/image-tag-simple
      metadata: {}
      container:
        name: ''
        image: alpine:latest
        command:
          - sh
          - '-xc'
        args:
          - |
            echo "{{inputs.parameters.image-tag-full}}" > tmp/image-tag-full &&
            echo "{{inputs.parameters.image-tag-simple}}" > tmp/image-tag-simple
        resources: {}
    - name: build
      inputs:
        parameters:
          - name: context
          - name: dockerfile
          - name: image
          - name: version
          - name: extra_args
          - name: tag-full
          - name: tag-simple
        artifacts:
          - name: src
            path: /src/
          - name: docker-config
            path: /kaniko/.docker/
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: >-
          registry-vpc.cn-hangzhou.aliyuncs.com/chohotech-public/kaniko_executor:v1.9.1
        command:
          - /kaniko/executor
        resources: {}
      retryStrategy:
        limit: 3
      podSpecPatch: >-
        {"containers":[{"name":"main", "args":[{{inputs.parameters.extra_args}},
        "--dockerfile={{inputs.parameters.dockerfile}}",
        "--context=/src/{{inputs.parameters.context}}",
        "--destination={{inputs.parameters.image}}:{{inputs.parameters.tag-simple}}",
        "--destination={{inputs.parameters.image}}:{{inputs.parameters.tag-full}}"]}]}
  arguments: {}
```
