### DISCUSSION TITLE
Argo Workflows Ingress not working after passing tls

### DISCUSSION THREAD

**Discussion by sharadhirao** [argoproj/argo-workflows#10240] [Q&A]
Hi team, I have installed argo workflow through helm. This is my values.yaml file

```
server:
  enabled: true
  baseHref: /
  serviceType: LoadBalancer
  servicePort: 443
  loadBalancerIP: <myip>
  secure: true

  extraArgs:
  - --auth-mode=sso

  ingress:
    enabled: true

    annotations: { 
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS",
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true",
      # nginx.ingress.kubernetes.io/rewrite-target: "/",
    }

    labels: {}
    ingressClassName: "nginx"
    hosts: 
      - argo-workflow.url.net
    paths:
      - /

    pathType: Prefix
    tls:
      - hosts:
          -  argo-workflow.url.net
        secretName: argoworkflows-example-tls
    

  volumeMounts:
  - name: certificate
    mountPath: /etc/ssl/certs/rootCA.crt
    subPath: ca-cert

  volumes: 
  - name: certificate
    configMap:
      name: custom-root-cert

      
  sso: 
    issuer: https://name.okta.com
    clientId:
      name: argo-server-sso
      key: client-id

    clientSecret:
      name: argo-server-sso
      key: client-secret

    redirectUrl: https://argo-workflow.url.net/api/oauth2/callback
    rbac:
      enabled: true
    scopes:
    - groups
    customGroupClaimName: admin
```

argoworkflows-example-tls contains tls secret (tls.crt and tls.key). When I try to use this, The tls is not getting applied. still argo workflow tries to generate self signed cert by argoproj. I checked pod logs there is no error. Is it a bug?

Could anyone please me on this?

Thanks in advance
