### DISCUSSION TITLE
[archived] "`argo submit` CLI" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#10260] [General]
# en/latest/cli/argo_submit/

https://argo-workflows.readthedocs.io/en/latest/cli/argo_submit/

**Comment by i540608** [comment]
Hi, 
how could find a list of available `kind`s or kind of specific workflow when executing `argo submit --from`?

I would like to submit a workflow from existing workflow, not cronWorkflow as the example
I tried to execute ` argo submit --from wf/upgrade-smvr-workflow --watch` but it does not work.
And i did not find the `kind` from the output of `argo get <workflow-name>` either;

**Reply by kevin-zhou-dev** [reply]
to be confirmed. It seems to be short name of the ressources : 
`kubectl -n <YOUR_NAMESPACE> api-resources | grep argoproj.io`

For instance: 
* `cronworkflows` is `cronwf`
*  `workflowtemplates` is `wftmpl`

**Comment by DominHa** [comment]
Would it be possible to have something similar to `--exit-code-from` in Docker Compose?

**Comment by manju-rn** [comment]
How to use the workflow template in the `argo submit` command?  I mean there should be a way to use the workflow template since in UI it allows to use the template to create the workflow. And I assume in CLI, is should also be possible

**Reply by agilgur5** [reply]
```sh
argo submit --from wftmpl/my-wftmpl
```

**Comment by manju-rn** [comment]
> ```shell
> argo submit --from wftmpl/my-wftmpl
> ```
Thanks. And if this needs to be implemented in the workflow and workflow template
```yaml
  templates:
  - name: build-steps
    steps:
    - - name: step1        
        templateRef: # Reference to other WorkflowTemplate (it is different from template, which is a task) defined in the same namespace
          name: my-container-template # Name of the Workflow template
          template: my-container # Reference to the actual template
```
Workflow Template
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-container-template
  namespace: argo-events
spec:
  templates:
  - name: my-container
    container:
      image: python
```
Source: https://argoproj.github.io/argo-workflows/fields/#templateref
