### DISCUSSION TITLE
argo-workflows/metrics/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#10319] [General]
# argo-workflows/metrics/

https://argoproj.github.io/argo-workflows/metrics/

**Comment by rubaiat-hossain** [comment]
I've deployed Argo inside a local kind cluster with -

```bash
kubectl create namespace argo

kubectl create \
  --filename https://github.com/argoproj/argo-workflows/releases/download/v3.4.4/namespace-install.yaml \
  --namespace argo

kubectl wait deployment workflow-controller \
  --for condition=Available \
  --namespace argo

kubectl create rolebinding default-admin \
  --clusterrole cluster-admin \
  --namespace argo \
  --serviceaccount=argo:default
```

However, when I want to label the `workflow-controller-metrics` service for Prometheus to scrape, it returns `Error from server (NotFound): services workflow-controller-metrics not found`

Here's the output of `kubectl get svc --namespace argo`

```bash
NAME          TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
argo-server   ClusterIP   10.96.45.141   <none>        2746/TCP   20m
```

Is my argo installation faulty? Why can't kubectl find the `workflow-controller-metrics` service?

**Reply by nicolas-vivot** [reply]
Looks like you actually have to deploy the service yourself. This service should point to the metric port of the `workflow-controller`, by default `9090` unless you changed it in the controller configuration.

Example:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflow-controller
  name: workflow-controller-metrics
  namespace: argo
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: workflow-controller
```
