### DISCUSSION TITLE
argo-workflows/argo-server-sso-azuread-401

### DISCUSSION THREAD

**Discussion by JunaidChaudry** [argoproj/argo-workflows#10336] [Q&A]
I am trying to set up `--auth-mode=server` with sso using AzureAD. I have already set up the azure app registration with the correct permissions, and stored and provided the client-id and client-secret following https://argoproj.github.io/argo-workflows/argo-server-sso/ . 

However when I try to login, and the application redirects back from azure sso to the workflow UI, it returns a 401 with "This page isn’t working right now". The server logs simply say the following without any other context:

``` 
time="2023-01-05T15:58:01.338Z" level=info duration="64.201µs" method=GET path=/oauth2/redirect size=298 status=302
time="2023-01-05T15:58:13.496Z" level=info duration="134.375µs" method=GET path=index.html size=473 status=0
time="2023-01-05T15:58:18.128Z" level=info duration=853.317986ms method=GET path=/oauth2/callback size=0 status=401
```

Does anyone have any ideas on what might be wrong here / what I might be missing? 

_ The issue is also briefly by @AndriySidliarskiy in https://github.com/argoproj/argo-workflows/discussions/8578#discussioncomment-4199024_ , but no resolution there either. 

Argo Workflow Version v3.4.4

**Comment by yriveiro** [comment]
I didn't manage to configure either, I used Dex as a proxy to do the auth :/

**Reply by JunaidChaudry** [reply]
following this documentation? https://argoproj.github.io/argo-workflows/argo-server-sso-argocd/#use-argo-cd-dex-for-authentication

**Reply by JunaidChaudry** [reply]
By going through that documentation, it seems like it requires dex to be enabled on argocd first. But what is I want to use dex on argo workflows alone?

**Reply by yriveiro** [reply]
I deployed Dex with an helm chart and configured it to use the AAD, after that configured argo workflows to use Dex. You don't need ArgoCD

**Reply by yriveiro** [reply]
I have not access to the system right now. I will try to copy the configurations I have as soon I can access it.

**Reply by yriveiro** [reply]
This is the `values.yaml` configuration I have in the Dex helm chart

```yaml
config:
  issuer: https://dex.[your domain here]/dex
  logger:
    level: debug
  connectors:
    - type: microsoft
      id: microsoft
      name: Microsoft
      config:
        redirectURI: https://dex.[your domain here]/dex/callback
  storage:
    type: kubernetes
    config:
      inCluster: true
  staticClients:
    - name: 'Argo workflow'
      redirectURIs:
        - https://[argo workflows domain here]/oauth2/callback
  enablePasswordDB: false
  ```
  
  This is what I have on Argo Workflows helm chart values for SSO:
  
  ```yaml
    sso:
    issuer: https://dex.[dex domain here]/dex
    clientId:
      name: argo-wf-sso-secret
      key: client-id-key
    clientSecret:
      name: argo-wf-sso-secret
      key: client-secret-key
    redirectUrl: https://[argo workflows domain here]/oauth2/callback
    rbac: 
      enabled: true
    scopes:
      - email
  ```
  
Don't forget you need to create an Enterprise Application with the homepage URL with the Argo workflow domain and configure also the App Registration's secret related to that Enterprise Application in a K8S secret, In my case is the `argo-wf-sso-secret`
