### DISCUSSION TITLE
Use parameters to build jsonpath dynamically

### DISCUSSION THREAD

**Discussion by emaincourt** [argoproj/argo-workflows#10400] [Q&A]
Hi,

I've been trying to get the following workflow run in many ways but still can't figure out how to use workflow input variables to build a proper json path:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
  namespace: argo
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: items
        value: |
          {
            "a": {
              "host": "host-a"
            },
            "b": {
              "host": "host-b"
            }
          }
      - name: operations
        value: |
          [
            {
              "source": "a",
              "destination": "b"
            }
          ]
  templates:
  - name: main
    steps:
      - - name: run
          template: run
          arguments:
            parameters:
              - name: name
                value: "{{item.source}}"
              - name: jsonpath
                value: "{{=sprig.nospace(sprig.cat('$.', item.source, '.host'))}}"
              - name: items
                value: "{{workflow.parameters.items}}"
              - name: raw
                value: "{{=jsonpath(workflow.parameters.items, '$.a.host')}}"
              - name: with_jsonpath
                value: "{{=jsonpath(workflow.parameters.items, sprig.nospace(sprig.cat('$.', item.source, '.host')))}}" // Fails to run
              - name: without_jsonpath
                value: "{{=workflow.parameters.items[item.source].host}}" // Fails to run
          withParam: "{{workflow.parameters.operations}}"
  - name: run
    inputs:
      parameters:
      - name: name
      - name: jsonpath
      - name: items
      - name: raw
      - name: with_jsonpath
      - name: without_jsonpath
    container:
      image: alpine
      command:
        - /bin/sh
        - -c
      args:
        - |
          echo '{{inputs.parameters.name}}'
          echo '{{inputs.parameters.jsonpath}}'
          echo '{{inputs.parameters.items}}'
          echo '{{inputs.parameters.raw}}'
          echo '{{inputs.parameters.with_jsonpath}}'
          echo '{{inputs.parameters.without_jsonpath}}'

```

Basically both `with_jsonpath` and `without_jsonpath` make the workflow fail. However, if I remove them, run the workflow and get the values of the other parameters, I end up with:
- `sprig.nospace(sprig.cat('$.', item.source, '.host'))` == `$.a.host`
- `jsonpath(workflow.parameters.items, '$.a.host')` == `host-a`

I would assume that concatenating the two expressions would work: `jsonpath(workflow.parameters.items, sprig.nospace(sprig.cat('$.', item.source, '.host')))`. But apparently not.

There might be a better option for achieving my goal.

Do you have any idea how I could make it work ?

Thanks in advance.

Argo version: v3.4.4
