### DISCUSSION TITLE
Unable to access argo workflow behind custom URI

### DISCUSSION THREAD

**Discussion by GauJosh** [argoproj/argo-workflows#10492] [Q&A]
Hi everyone, I am trying to setup custom URI for argo-workflows.
I am using helm with below setting in my values.yaml:
```yaml
  baseHref: /workflows/
```
I am using Istio virtual service to access argo workflows.
Below is my virtual service for workflows:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-vs
  namespace: argocd
spec:
  gateways:
  - host-test-gateway
  hosts:
  - host.test.com
  http:
  - match:
    - uri:
        prefix: "/workflows/"
    route:
    - destination:
        host: argo-workflows-server.argocd.svc.cluster.local
        port:
          number: 2746
```
I also tried with using rewrite and rewriting "/workflows/" to "/" but didn't work.
```yaml
    rewrite:
        uri: "/"
```

It works if I set baseHref to just "/" and keep prefix in istio virtualservice to "/". However, I want to access workflows UI behind custom base bath.
Any help here is greatly appreciated.
