### DISCUSSION TITLE
argo-workflows/variables/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#10525] [General]
# argo-workflows/variables/

https://argoproj.github.io/argo-workflows/variables/

**Comment by vorkos** [comment]
Is it possible to filter input parameters? 
I'm trying to do so with 
```yaml        
         env:
          - name: FILTER
            value: '{{=filter(inputs.parameters, { #.value == "test" }) }}'
          - name: PARAMS
            value: '{{inputs.parameters}}'
```

`echo $PARAMS` gives json string as expected, but `echo $FILTER` gives only expression, but not any kind of result.

**Comment by Jooong** [comment]
It seems that hyperlink does not work anymore - [Learn about the expression syntax.](https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md)

**Reply by agilgur5** [reply]
It was down for a bit (see this [recent discussion](https://github.com/argoproj/argo-workflows/discussions/11964)), it's back up now

**Reply by antonmedv** [reply]
Website with Expr Language Definition is [here](https://expr.medv.io/docs/Language-Definition).

**Comment by ybhaw** [comment]
Had a scenario where I had to convert one json input into another format. Spent a lot of time on it, so sharing it here in case it helps someone:

Example of parsing a json string and mapping it:
Input String: `[{"name": "name1", "value": "value1"}, {"name": "name2", "value": "value2"}]`
Output String: `"name1": "value1", "name2": "value2"`

Code: 
```
{{= sprig.trimAll("]", sprig.trimAll("[", string(map(sprig.mustFromJson(workflow.parameters.env_vars), { '"' + #.name + '": "' + #.value + '",'})) )) }}
```

Explanation (sort of):

```
{{=   -- Indicates it is expression
        sprig.trim("]", sprig.trim("[",  -- Remove  [ and ] from start and end
                string(map(    -- expr map to transform list of struct
                        sprig.mustFromJson(   -- convert to json
                                workflow.parameters.some_variable
                        ),
                        { '"' + #.name + '": "' + #.value + '",'}))  -- transformation
                ))
        ))
}}
```

I tried join from both expr and sprig, both did not work for me. Did not find an example of what synatx to use for them online, so maybe my syntax was wrong.

**Reply by vorkos** [reply]
I think it's easier to do so in the shell script with `jq` and pass out the result to the next step. 
ArgoWF renders json from '{{=toJson(inputs.parameters)}}' and "{{=toJson(inputs.parameters)}}" differently - that took some time for me.

**Reply by antonmedv** [reply]
Expr has a lot of [built-in](https://expr.medv.io/docs/Language-Definition) function. Simple use `fromPairs`:

```
workflow.parameters.some_variable | map([.name, .value]) | fromPairs()
```

**Comment by ShyunnY** [comment]
I have a question:  
Why does the following error occur when I use workflow global parameters in container.args?

Partial configuration:
```yaml
# ...
    - name: build
      inputs:
        parameters:
          - name: msg
      outputs:
        parameters:
          - name: build-output
            value: "output-val"
      container:
        image: bash:latest
        command:
          - sh
        args:
          - -c
          - |
            echo {{inputs.parameters.msg}}
            echo {{workflow.mainEntrypoint}}
# ...
```
error message:
```shell
$ argo submit var.yaml 
FATA[2023-10-15T13:38:44.581Z] Failed to submit workflow: rpc error: code = InvalidArgument desc = templates.var-entrypoint.steps[0].build templates.build: failed to resolve {{workflow.mainEntrypoint}}
```

According to the doc description, the workflow.mainEntrypoint parameter seems to be a global parameter. 
Why does a parsing error occur here? :thinking:
