### DISCUSSION TITLE
How can fields on steps dynamically created using `withParam` be accessed from lifecycle hooks?

### DISCUSSION THREAD

**Discussion by iainlane** [argoproj/argo-workflows#10573] [Q&A]
It doesn't seem possible - or I can't find out how - to have an expression which refers to steps created from `withParam`.

In the example below I'm attaching lifecycle hooks to a step which is expanded with `withParam`. I'd like `XXX` to be an expression which runs the hook if the step failed (without `withParam` it would be `steps["..."].status == "Failed"`). But I can't know the step name, it is an opaque string in the `withParam` case.

Similarly for `YYY` I'd like to access the outputs of the step, in this case to print `echome`, but I can't for the same reason.

Is it possible to do this currently? If not, maybe we could inject a special variable into the context for lifecycle hooks attached to steps, something like `current_step`. In that case I'd convert this into an issue and I'd be happy to try to work on it.

I know that for many usecases we could create templates and use `when` within those. But lifecycle hooks are very convenient, particularly we find in failure cases to post nice status messages out.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: with-param
  namespace: playground-cd
spec:
  activeDeadlineSeconds: 172800
  entrypoint: main
  imagePullSecrets:
  - name: gcr
  podGC:
    strategy: OnWorkflowCompletion
  templateDefaults:
    serviceAccountName: argo-workflow
  templates:
  - container:
      command:
      - /bin/sh
      - -c
      - echo "hello from output-template"
      image: alpine:3.17.2
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
    name: output-template
    outputs:
      parameters:
      - name: foo
        value: bar
    serviceAccountName: argo-workflow
  - container:
      command:
      - /bin/sh
      - -c
      - 'echo "input: {{inputs.parameters.echome}}"'
      image: alpine:3.17.2
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
    inputs:
      parameters:
      - name: echome
    name: echo-input
    serviceAccountName: argo-workflow
  - name: main
    serviceAccountName: argo-workflow
    steps:
    - - arguments:
          parameters: []
        hooks:
          failure:
            arguments:
              parameters:
              - name: echome
                value: YYY
            expression: XXX
            template: echo-input
        name: output-template
        template: output-template
        withParam: '{{=toJson(filter([1, 2, 3], {# > 1}))}}'
  ttlStrategy:
    secondsAfterCompletion: 604800
  workflowMetadata:
    labels:
      team: release
```
