### DISCUSSION TITLE
Postgres idle connections are not being closed

### DISCUSSION THREAD

**Discussion by rconjaerts** [argoproj/argo-workflows#10577] [Q&A] [answered]
Hi all,

We [archive workflows](https://argoproj.github.io/argo-workflows/workflow-archive/) to keep them for a longer time, but we are running into issues since we've updated argo-workflows to v3.4.5.

Idle connections to postgres are not being closed anymore. We are using the [helm-charts](https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows) from the argo-helm projects to deploy it.

I don't think there's an issue with these helm charts because when I look into the configmap of my workflow-server it seems that everything is correct.
```
persistence:
  archive: true
  archiveTTL: 180d
  connectionPool:
    maxIdleConns: 25
    maxOpenConns: 0
  nodeStatusOffLoad: true
  postgresql:
    database: argo
    host: xx.xx.xxx.xxx
    passwordSecret:
      key: x
      name: x
    port: 5432
    tableName: workflows
    userNameSecret:
      key: username
      name: argo-postgres-config
```

So now argo keeps creating new connections, not deleting idle ones and hogging our database which results in our application not working since our backend can't make a connection to it. Am I missing something here? Because the configmap looks the same as before.
