### DISCUSSION TITLE
[archived] "Scripts and Results" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#10570] [General]
# argo-workflows/walk-through/scripts-and-results/

https://argoproj.github.io/argo-workflows/walk-through/scripts-and-results/

**Comment by catchsvix** [comment]
Script workflows seem to always echo the entire contents of the script to stdout (shows up in the logs of a workflow). Is there a way to disable that?

**Comment by freegroup** [comment]
the execution of the workflow ends with an error message

```
Error (exit code 1): pods "scripts-bash-lrqvs-gen-random-int-bash-2523361756" is forbidden: User "system:serviceaccount:default:default" cannot patch resource "pods" in API group "" in the namespace "default"
```

**Reply by r0cheny** [reply]
Hi, the service account you use for running your workflow does not have enough privileges you can either:

1. create a service account with enough privileges. Then run your workflow with either:
```yaml
spec: 
    serviceAccountName: <your-service-account>
```
2. or:
```sh
argo submit your-workflow.yaml --serviceaccount your-serviceaccount
```

3. alternatively you can give your default service account admin [privileges](https://argoproj.github.io/argo-workflows/service-accounts/):

```sh
kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default -n default
```

**Reply by ajayjupyter001** [reply]
1. create role 
    ```yaml
    kind: Role
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
       namespace: <your_namespace>
       name: own-role
    rules:
      - apiGroups: [""]
         resources: ["pods"]
          verbs: ["patch"]
   ```

2. apply the above role

3. Then finally create rolebinding to bind the above role with default service account
    ```sh
    kubectl create rolebinding my-role-binder  --role=own-role --serviceaccount=default:default --namespace=<your_namespace>
    ```
