### DISCUSSION TITLE
how to mount ConfigMap into argo pod?

### DISCUSSION THREAD

**Discussion by leveryd** [argoproj/argo-workflows#10580] [Q&A] [answered]
i have try to test like https://github.com/argoproj/argo-workflows/issues/4038, but it does not work

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: my-task
spec:
  entrypoint:   entrypoint
  templates:
  - name:   entrypoint
    steps:
    - - name: do
        template: do
  - name: do
    # not quite sure of the syntax
    volumes:
     - name: my-scripts
        path: /tmp/scripts/
        configMap:
          name: my-script-cm
    script:
      image: debian:9.4
      command: [bash]
      source: |
        /tmp/scripts/run-my-long-script
```

**Comment by leveryd** [comment, marked as answer]
i got it, something like below

```
spec:
  volumes:
    - name: logstash-config-map
      configMap:
        name: logstash
  templates:
    - name: logstash
      inputs:
        artifacts:
          - name: http-result
            path: /tmp/http.csv
      script:
        image: logstash:7.17.3
        command:
          - 'sh'
        source: |
          cat /tmp/http.csv | logstash -f /tmp/logstash/httpx.conf
        volumeMounts:
          - name: logstash-config-map
            mountPath: /tmp/logstash
```
