### DISCUSSION TITLE
How to clone github repo as artifact by using HTTPS & Token ?

### DISCUSSION THREAD

**Discussion by michael-riha** [argoproj/argo-workflows#10614] [Q&A]
I play now already around for some time, but I am not able to figure it out.

1. Do I use Artifacts to even clone a git Repository?
    [I am asking because a lot of guys build workflows with containers on their own. ](https://github.com/pipekit/argo-workflows-ci-example/blob/main/bootstrap/workflow-templates/git-checkout-pr.yml)
   
2. When I am correct and Artifacts are the way to go, I fail ... **like a lot**

### WHY?

```
Error (exit code 1): artifact argo-source failed to load: failed to clone "https://oauth2:TOKEN@https://github.com/my_repo_url.git": authentication required
```
<br>

## I failed now using two methods

<br>
1. providing the Credentials from GitHub via `Secret`

`gh-secret.yaml`
```
apiVersion: v1
kind: Secret
metadata:  
  name: github-secret
stringData:
  username: ""
  password: github_pat_TOKEN
```
👆 tried the same ofc also with `base64`-encoded `data`-credentials, same.
And yes, they are in the same `namespace`!

`workflow.yaml`
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: git-artifact-workflow
spec:
  entrypoint: git-clone
  templates:
  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: /src
        git:
          repo: https://github.com/my_repo_url.git
          revision: "123abcd"
          depth: 1
          singleBranch: true
          branch: main
          depth: 1
          singleBranch: true
          branch: main
          usernameSecret:
            name: github-secret
            key: username
          passwordSecret:
            name: github-secret
            key: password
            ....
```
copied from, https://github.com/argoproj/argo-workflows/blob/master/examples/input-artifact-git.yaml

2. Next, I tried to use the Basic Auth with the tokens
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  # generateName: input-artifact-git- # https://github.com/kubernetes-sigs/kustomize/issues/641
  name: git-artifact-workflow
spec:
  entrypoint: git-clone
  templates:
  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: /src
        git:
          # https://linuxhint.com/github-clone-with-oauth-access-token/
          repo: https://oauth2:TOKEN@github.com/my_repo_ur.git
          revision: "123abcd"
          depth: 1
          singleBranch: true
          branch: main
          ...
``` 

Same Result always 🤯 

The token works as I use it with ArgoCD without any issues ever.

What am I missing, because it feels like a tiny, stupid mistake?
