### DISCUSSION TITLE
[archived] "Argo Server Auth Mode" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#10627] [General]
# en/latest/argo-server-auth-mode/

https://argo-workflows.readthedocs.io/en/latest/argo-server-auth-mode/

**Comment by Adam-D-Lewis** [comment]
> this will use the same service account as per "server" for RBAC. We expect to change this in the future so that the OAuth claims are mapped to service accounts.

I believe that's out of date since https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac seems to describe how to map OIDC groups to service accounts.

**Reply by agilgur5** [reply]
Indeed, I updated this in #13137. PRs always welcome!

**Comment by shubhendu1982** [comment]
Hi All,

Right now we are in EKS 1.22 and argocd we are using 2.4.20. We are planning to use EKS 1.25 what is version of argocd is recommended.

Regards,
Shubhendu

**Comment by edalonso** [comment]
I'm trying to configure kong as ingress with:

```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "308"
    konghq.com/strip-path: "true"
  name: argo-server-ingress
  namespace: cicd
spec:
  ingressClassName: kong
  rules:
  - host: www.example.com
    http:
      paths:
      - backend:
          service:
            name: argo-server
            port:
              number: 2746
        path: /argo
        pathType: ImplementationSpecific
```

In argo server I configure:

```yml
        env:
          - name: BASE_HREF
            value: /argo/
```

and not work.
Do you know which is the problem?
