### DISCUSSION TITLE
Dynamic DAG fails with `Bad Request: json: cannot unmarshal object into Go struct field DAGTemplate.workflow.spec.templates.dag.tasks of type []v1alpha1.DAGTask`

### DISCUSSION THREAD

**Discussion by hach-que** [argoproj/argo-workflows#10699] [Q&A]
I have the following workflow:

```yaml
metadata:
  name: test-dynamic
  namespace: default
spec:
  entrypoint: run-graph
  templates:
    - name: run-graph
      steps:
        - - name: generate-graph
            template: generate-graph
        - - name: execute-graph
            template: execute-graph
            arguments:
              parameters:
                - name: dag
                  value: "{{steps.generate-graph.outputs.dag}}"
    - name: generate-graph
      script:
        image: ubuntu:22.04
        command: [bash]
        source: |
          cat >/tmp/output.json <<EOF
          [
            {
              "name": "A",
              "dependencies": [],
              "template": "node"
            },
            {
              "name": "B",
              "dependencies": ["A"],
              "template": "node"
            },
            {
              "name": "C",
              "dependencies": ["A"],
              "template": "node"
            },
            {
              "name": "D",
              "dependencies": ["B", "C"],
              "template": "node"
            }
          ]
          EOF
      outputs:
        parameters:
          - name: dag
            fromValue:
              path: /tmp/output.json
    - name: execute-graph
      inputs:
        parameters:
          - name: dag
      dag:
        tasks: {{inputs.parameters.dag}}
    - name: node
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["sleep 1"]
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

Upon submission I get `Bad Request: json: cannot unmarshal object into Go struct field DAGTemplate.workflow.spec.templates.dag.tasks of type []v1alpha1.DAGTask`, which to me implies that it's trying to evaluate the input parameter too early.

I don't want to use "Workflow in Workflows" because it results in the bulk of the work being disconnected from the initiating workflow in the Argo UI.

How can I pass a dynamic DAG from a previous step?
