### DISCUSSION TITLE
How can I write the Http template output to file and/or artifact?

### DISCUSSION THREAD

**Discussion by egze** [argoproj/argo-workflows#10829] [Q&A]
Considering this simple example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-outputs-
spec:
  entrypoint: main
  templates: 
    - name: main
      dag:
        tasks:
          - name: http
            template: http
            arguments:
              parameters:
                - name: url
                  value: >-
                    https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json
    - name: http
      inputs:
        parameters:
          - name: url
      http:
        url: '{{inputs.parameters.url}}'
```

How can I save the file as an artifact? Ideally it should be done in the same task.

**Comment by wesleyscholl** [comment]
@egze 

The http template doesn't currently support artifact outputs.

- https://argo-workflows.readthedocs.io/en/latest/http-template/
- https://argo-workflows.readthedocs.io/en/latest/fields/#http

However, you could accomplish the same thing using the http input artifact:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-artifact-example-
spec:
  entrypoint: download-http-artifact
  templates:            
    - name: download-http-artifact
      inputs:
        artifacts:
          - name: sample-text
            path: /tmp/sample.txt
            mode: 0644
            http:
              url: https://raw.githubusercontent.com/argoproj/argo-workflows/refs/heads/main/README.md
      container:
        image: alpine:3.14
        command: [sh, -c]
        args:
          - |
            echo "Contents of the downloaded file:"
            cat /tmp/sample.txt
            echo "File size:"
            wc -c /tmp/sample.txt
```
Reference:
https://github.com/argoproj/argo-workflows/blob/main/examples/input-artifact-http.yaml
