### DISCUSSION TITLE
how to trigger template with input file argument directly?

### DISCUSSION THREAD

**Discussion by leveryd** [argoproj/argo-workflows#10839] [Q&A]
```
metadata:
  name: test
spec:
  templates:
    - name: test
      inputs:
        artifacts:
          - name: urls
            path: /tmp/urls.txt
      script:
        name: ''
        image: ubuntu:lunar-20221207
        command:
          - sh
        resources: {}
        source: |
          wc -l /tmp/urls.txt
```

![image](https://user-images.githubusercontent.com/1846319/230373508-15b6f39f-8802-45d9-9be8-15cc0ade1da3.png)

Is it possible to trigger "test" template on argo-ui or argo-cli directly?
