### DISCUSSION TITLE
How to input multi line argument in suspend template?

### DISCUSSION THREAD

**Discussion by leveryd** [argoproj/argo-workflows#10848] [Q&A]
I have suspend template below

```
    - name: x-approve
      suspend: {}
      inputs:
        parameters:
          - name: approve
            default: 'NO'
            enum:
              - 'YES'
              - 'NO'
          - name: org
            default: ""
          - name: sld
            default: ""
      outputs:
        parameters:
          - name: approve
            valueFrom:
              supplied: {}
          - name: org
            valueFrom:
              supplied: {}
          - name: sld
            valueFrom:
              supplied: {}
```

I want to input multi line sld, like below
```
www.google.com
www.twitter.com
``` 

But it seems like sld is "input" type, not "textarea" type, so i can not input multi line

<img width="934" alt="image" src="https://user-images.githubusercontent.com/1846319/230623713-03f609ee-fd26-4c42-aa51-557537554a17.png">
