### DISCUSSION TITLE
Is it possible to run pods in a namespace created by argo?

### DISCUSSION THREAD

**Discussion by TylerMizuyabu** [argoproj/argo-workflows#10847] [Q&A]
Hello,
So I have a use case where we want to submit a workflow where argo will create a new namespace using a ResourceTemplate, then in any following templates we would like to have all the pods run in that namespace. I know I can achieve this with workflow-of-workflows with a template like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
spec:
  entrypoint: main
  templates:
    - name: main
       steps:
       - - name: create-namespace
            inline:
              resource:
                action: 'create'
                manifest: 'some manifest.....'
       - - name: child-workflow
            template: triggerWorkflow
            arguments:
              parameters:
                - name: namespace
                  value: 'namespace-name'
    - name: triggerWorkflow
      inputs:
        parameters:
          - name: namespace
      resource:
        action: create
        manifest: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
               generatedName: child-workflow-
               namespace: {{inputs.parameters.namespace}}
            spec:
               workflowTemplateRef:
                 name: someTemplate
      successCondition: status.phase == Succeeded
      failureCondition: status.phase in (Failed, Error)
```

but we would prefer it if we could have this done all in one workflow. I looked over the field references and I couldn't find an option that would let one change the namespace of a steps pod to be different from the one the workflow is running in.
