### DISCUSSION TITLE
Is it possible to create K8s resources via container or script template?

### DISCUSSION THREAD

**Discussion by maxsxu** [argoproj/argo-workflows#10885] [Q&A] [answered]
Currently, it seems only the `resource` template can perform operations on cluster resources directly.

Wondering would it possible to achieve this goal by `container` or `script` template like below:

```yaml
  - name: create-resources-via-script-template
    script:
      image: bitnami/kubectl:latest
      command: [ sh ]
      source: |
        kubectl create ns argo
```

**Comment by terrytangyuan** [comment, marked as answer]
Yes you can run a script with `kubectl create` and `kubectl wait`.

**Reply by maxsxu** [reply]
@terrytangyuan Thanks for your confirmation!

However, occurred below errors while running a sample workflow:

```
create-resources-via-container-template: error: failed to create serviceaccount: Post "http://localhost:8080/api/v1/namespaces/default/serviceaccounts?fieldManager=kubectl-create&fieldValidation=Strict": dia
l tcp 127.0.0.1:8080: connect: connection refused
```

Here is the sample workflow:

```yaml
metadata:
  name: create-resources-via-container-template
  namespace: argo
spec:
  executor:
    serviceAccountName: argo-executor
  serviceAccountName: argo-workflow
  automountServiceAccountToken: false
  entrypoint: main
  templates:
    - name: main
      container:
        name: main
        image: bitnami/kubectl
        command:
          - sh
        args:
          - -c
          - |
           kubectl create sa test
```

**Reply by maxsxu** [reply]
Not sure whether it is a bug or not.

Because the below workflow can work (without `spec.automountServiceAccountToken` and `spec.executor.serviceAccountName`):

```yaml
metadata:
  name: create-resources-via-container-template
  namespace: argo
spec:
  serviceAccountName: argo-workflow
  entrypoint: main
  templates:
    - name: main
      container:
        name: main
        image: bitnami/kubectl
        command:
          - sh
        args:
          - -c
          - |
           kubectl create sa test
```
