### DISCUSSION TITLE
Retrieve numeric value from jsonpath (if condition)

### DISCUSSION THREAD

**Discussion by rbushri** [argoproj/argo-workflows#10901] [Q&A] [answered]
Hi,

I have JSON parameters  (testResources, prodResources) and I want to use those parameters in my "if condition" the final value should be numeric.

So I tried this:
```
 {{=inputs.parameters.env=='test'?jsonpath(inputs.parameters.testResources,'$.driver-core'):jsonpath(inputs.parameters.prodResources,'$.driver-core')}}
```
but I got the error:
```
 Internal Server Error: templates.general-template templates.general-template.resource.manifest must be a valid yaml
```
so I tried this condition, and it works fine:
```
 {{=inputs.parameters.env=='test'?jsonpath(inputs.parameters.testResources,'$.driver-core'):4}}
```
so my question is what did I do wrong?

The WF yml:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: general-template-workflow
spec:
  templates:
    - name: general-template
      inputs:
        parameters:
          - name: app
          - name: env
          - name: testResources
            default: |
              {
                  "driver-pool": "main",
                  "driver-core": 2,
                  "driver-memory": "4g",
                  "executor-pool": "main",
                  "executor-core": 2,
                  "executor-memory": "4g",
                  "fix": 1 
               }
          - name: prodResources
            default: |
              {
                "driver-pool": "main",
                "driver-core": 4,
                "driver-memory": "8g",
                "executor-pool": "main",
                "executor-core": 4,
                "executor-memory": "8g",
                "fix": 1 
              }
      resource:
        action: create
        manifest: |
          apiVersion: "sparkoperator.k8s.io/v1beta2"
          kind: SparkApplication
          metadata:
            generateName: {{workflow.name}}-{{inputs.parameters.app}}-
          spec:
            type: Scala
            mode: cluster
            ...
            driver:
              cores: {{=inputs.parameters.env=='test'?jsonpath(inputs.parameters.testResources,'$.driver-core'):jsonpath(inputs.parameters.prodResources,'$.driver-core')}}
            ...
```
