### DISCUSSION TITLE
Can't get artifact gc working

### DISCUSSION THREAD

**Discussion by static-moonlight** [argoproj/argo-workflows#10939] [General]
I just can't get the artifact gc feature (introduced with 3.4) working. Not only are the artifacts not being deleted, the workflows itself can't be removed as usual, because the finalizer is stuck or whatever.

The truth is, I have no idea what the status of these finalizers is. I don't know where to look. Are there any logs somewhere?

I am using a MinIO bucket as artifact repository. Besides the artifact gc issue, the workflow is working fine. I have a specific service account with a role that contains the required permissions (as desribed [here](https://argoproj.github.io/argo-workflows/walk-through/artifacts/#service-accounts-and-annotations)). I don't see any pods named `<wfName>-artgc-*` (as described [here](https://argoproj.github.io/argo-workflows/walk-through/artifacts/#what-happens-if-garbage-collection-fails)).

I have no idea why it's not working? I don't know how to find out? I can't find anything in the manual that helps me. Missing permissions? Configuration error? bug? Something else? Did I missed something important in the manual or in the examples?

I really want this to work and I really need some help to get there.

```
apiVersion: "argoproj.io/v1alpha1"
kind: "WorkflowTemplate"
metadata:
  name: "example"
spec:
  entrypoint: "start"
  artifactRepositoryRef:
    configMap: "artifact-repository"
    key: "example"
  artifactGC:
    serviceAccountName: "example"
    strategy: "OnWorkflowDeletion"
  [...]
  templates:
    - name: "start"
      serviceAccountName: "example"
      dag:
        [...]
```
```
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "example"
secrets:
  - name: "example-token"
```
```
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "example-token"
  annotations:
    kubernetes.io/service-account.name: "example"
type: "kubernetes.io/service-account-token"
```
```
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: "example"
rules:
  # See https://argoproj.github.io/argo-workflows/workflow-rbac/
  - apiGroups:
      - "argoproj.io"
    resources:
      - "workflowtaskresults"
    verbs:
      - "create"
      - "patch"
  - apiGroups:
      - "argoproj.io"
    resources:
      - "workflows"
    verbs:
      # Permissions to submit a workflow
      - "list"
      - "create"
      # Permissions to resubmit, retry, resume, suspend a workflow
      - "get"
      - "update"
  # See https://argoproj.github.io/argo-workflows/walk-through/artifacts/#service-accounts-and-annotations
  - apiGroups:
      - "argoproj.io"
    resources:
      - "workflowartifactgctasks"
    verbs:
      - "list"
      - "watch"
  # See https://argoproj.github.io/argo-workflows/walk-through/artifacts/#service-accounts-and-annotations
  - apiGroups:
      - "argoproj.io"
    resources:
      - "workflowartifactgctasks/status"
    verbs:
      - "patch"
```
