### DISCUSSION TITLE
Help in getting a conditional step with specific exit handler to work

### DISCUSSION THREAD

**Discussion by ni-todo-spot** [argoproj/argo-workflows#10948] [General]
Hello,

I'm trying to use the following [example](https://github.com/argoproj/argo-workflows/blob/master/examples/exit-handler-with-param.yaml) for my project's purposes:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ni-exit-handler-with-param-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: check
            template: should-skip
        - - name: step-1
            when: "{{steps.check.outputs.result}} != SKIP"
            template: output
            hooks:
              exit:
                template: exit
                arguments:
                  parameters:
                    - name: stat
                      value: "{{steps.step-1.status}}"

    - name: should-skip
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import random
          result = "SKIP" if random.randint(0,1) == 0 else "CONTINUE"
          print(result)

    - name: output
      container:
        image: python:alpine3.6
        command: [ python ]
        source: |
          import sys
          print("Do some work")
          sys.exit(0)

    - name: exit
      inputs:
        parameters:
          - name: stat
      steps:
      - - name: slack-notify-success
          template: slack-notify-success
          when: "'{{inputs.parameters.stat}}' == Succeeded"
        - name: slack-notify-error
          template: slack-notify-error
          when: "'{{inputs.parameters.stat}}' != Succeeded"

    - name: slack-notify-success  # called when step-1 completed with no errors
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          print("sending SUCCESS status in slack...")

    - name: slack-notify-error  # called when step-1 completed errors
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          print("sending ERROR status in slack...")
```

So, if a certain predicate evaluates to true then I'd like to skip the rest of the workflow and if not continue with it and assign it an exit handler.

Problem I'm encountering is that the `stat` param is not passed correctly into the `exit` template, so the `when` part of the success is never used. 

I'm using argo v3.2.9 on GKE

Can anyone please help me getting this to work?
