### DISCUSSION TITLE
[archived] "Synchronization" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#10949] [General]
# argo-workflows/synchronization/

https://argoproj.github.io/argo-workflows/synchronization/

**Comment by ni-todo-spot** [comment]
Can I condition the assignment of a mutex over a template, based on a workflow argument?

I'm looking for something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
spec:
  arguments:
    parameters:
    - name: mutex_
      value: "no"

  entrypoint: synchronization-tmpl-level-mutex-example

  templates:
  - name: synchronization-tmpl-level-mutex-example
    steps:
    - - name: synchronization-acquire-lock
        template: acquire-lock


  - name: acquire-lock
    # Ideally something like:    
    # synchronization: {"mutex": {"name": "welcome"}} if mutex_ == yes else {}
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["sleep 20; echo acquired lock"]
```
