### DISCUSSION TITLE
How to make args in “podSpecPatch” merge with “container.args”?

### DISCUSSION THREAD

**Discussion by guvmao** [argoproj/argo-workflows#10983] [Q&A]
I used the way [here](https://github.com/argoproj/argo-workflows/issues/3191#issuecomment-641630979), but when I add "container.args" is ignored.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-params-
spec:
  entrypoint: test
  templates:
  - name: test
    steps:
    - - name: first-step
        template: echo-args
        arguments:
          parameters:
          - name: args
            value: '["1", "2", "3"]'
    # - - name: second-step
    #     template: echo-args
    #     arguments:
    #       parameters:
    #       - name: args
    #         value: '["a", "b", "c", "d"]'
  - name: echo-args
    inputs:
      parameters:
      - name: args
    podSpecPatch: '{"containers":[{"name":"main", "args":{{inputs.parameters.args}}}]}'
    container:
      image: alpine
      command: [echo]
      args: [aa, bb]

```
