### DISCUSSION TITLE
The "default" property of a parameter does not work as expected?

### DISCUSSION THREAD

**Discussion by sylock** [argoproj/argo-workflows#10991] [Q&A]
I don't understand the behavior of the "default" property. When doing this:

```
  arguments:
    parameters:
    - name: awx_server
      default: my_url
```
The value my_url is not set for the variable awx_server

But when doing this:
```
  arguments:
    parameters:
    - name: awx_server
      value: my_url

```
it does work.

The documentation is not clear about the "default" : https://argoproj.github.io/argo-workflows/fields/#parameter
"Default is the default value to use for an input parameter if a value was not supplied".

**Comment by pchar** [comment]
same for me it seams not working or ignored and bug report on this topic have been all closed

**Comment by wesleyscholl** [comment]
@sylock @pchar 

It's possible this was fixed in more recent versions of Argo Workflows. The following scenarios are working as expected.

`default` without the `value` field:
```yaml
arguments:
    parameters:
      - name: message
        default: default
```

Results in `default`:

<img height="250" alt="Screenshot 2024-11-20 at 3 29 13 PM" src="https://github.com/user-attachments/assets/692af4b3-4978-4687-80b9-96d786f678c2">



`default` and the `value` field defined:
```yaml
arguments:
    parameters:
      - name: message
        default: default
        value: value
```

Results in `value`:

<img width="250" alt="Screenshot 2024-11-20 at 3 33 37 PM" src="https://github.com/user-attachments/assets/91e00ff4-ae8d-4633-8bf5-d24a1aceaf0a">

`default` and the `value` field with an empty value:
```yaml
arguments:
    parameters:
      - name: message
        default: default
        value: ''
```



Results in ` `:

<img width="250" alt="Screenshot 2024-11-20 at 3 34 05 PM" src="https://github.com/user-attachments/assets/3c6c7ec3-7577-417c-8471-d6794aea47a3">
