### DISCUSSION TITLE
Webhook error

### DISCUSSION THREAD

**Discussion by gastonborba** [argoproj/argo-workflows#11080] [Q&A]
Hello, 
My GitLab webhook returns an error:

Hook executed successfully but returned HTTP 500 {"code":13,"message":"failed to dispatch event: [malformed workflow template parameter \"context_git\": valueFrom is nil]"}

How can I pass a string value to the WorkflowTemplate from the WorkflowEventBinding?

My WorkflowEventBinding is:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-consumer
spec:
  event:
    # metadata header name must be lowercase to match in selector
    selector: discriminator == "albums"
  submit:
    workflowTemplateRef:
      name: build-workflow-template
    arguments:
      parameters:
      - name: context_git
        value: "gitlab.com/albums1/albums-code.git"
      - name: container_image      
        value: "harbor.borbit.rocks/albums/borbit-test-albums-backend"
      - name: container_tag
        valueFrom:
          event: payload.after[0:8]
```

My WorkflowTemplate is:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-workflow-template
spec:
  entrypoint: build-kaniko-git
  templates:
    - name: build-kaniko-git
      inputs:
        parameters:
          - name: context_git
          - name: container_image
          - name: container_tag
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: [/kaniko/executor]
        args: ["--context=git://{{inputs.parameters.context_git}}",
               "--destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}",
               "--destination={{inputs.parameters.container_image}}:latest"]
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitlab-credentials
              key: username
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
             name: gitlab-credentials
             key: password
      volumes:
        - name: kaniko-secret
          secret:
            secretName: harbor-credentials
            items:
              - key: .dockerconfigjson
                path: config.json
```
