### DISCUSSION TITLE
Executor `securityContext.capabilities` not overriding defaults

### DISCUSSION THREAD

**Discussion by rwong2888** [argoproj/argo-workflows#11127] [Q&A] [answered]
I have the below controller configmap on v3.4.7.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce
  mainContainer: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 8737
      runAsGroup: 8737
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  executor: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 8737
      runAsGroup: 8737
      privileged: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  workflowDefaults: |
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 8737
        runAsGroup: 8737
```

I am trying to remove `securityContext.capabilities.drop` from the `main` container in a containerset.

I've tried setting capabilities to `null` or `{}` on my main container.

I've tried setting drop to `null` or `[]` on my main container.

e.g.

```yaml
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              capabilities: null
```

```yaml
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              capabilities: {}
```

But when I check the yaml of my pod, the container's securityContext capabilities is still drop all.

Referencing @alexec 's blog post

* https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce

And helm's deleting a default key

* https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key
