### DISCUSSION TITLE
How do you list the contents of an artifact directory?

### DISCUSSION THREAD

**Discussion by mmlngl** [argoproj/argo-workflows#11220] [Q&A] [answered]
Loving Argo 🙏 .

Seem plenty of examples of "generating artifacts in step 1, processing it in step 2".

But it's unclear to me how to trigger a workflow that operates on an **existing** artifact in step 1 and process it in step 2.

## Scenario I'm trying to create

1. Pass a parameter to the workflow called `artifact-key`.
1. Use this parameter to list the contents of the parent directory of `artifact-key`

Any pointers? Thank you!

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/blob/master/docs/data-sourcing-and-transformation.md

**Reply by mmlngl** [reply]
Thanks for the speedy response.

This helps.

Looks like I should try writing a transformation expression to loop over everything and find the one thing that matches the input parameter. It'll return an array of 0 or 1 items.

I'm also going to experiment with specifying the key when I add s3 artifactPaths.

**Comment by mmlngl** [comment]
My latest attempt looks like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: optimise
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: fetch-workspace
            template: fetch-workspace
            arguments:
              artifacts:
                - name: workspace
                  s3:
                    key: "test/"        
    - name: fetch-workspace
      inputs:
        artifacts:
          - name: workspace
            path: "/message"
      container:
        image: alpine:latest
        command: [ls]
        args: ["/message"]
```

It run successfully byt the output confused me.

**Expected**
`ls` to list the contents of the artifact directory (3 files already in the s3 bucket)

**Actual**
`/message` is outputted. Like the `ls` cmd is actually running `echo`.

Anyone else running into this problem?
