### DISCUSSION TITLE
SSL Cert error for SSO

### DISCUSSION THREAD

**Discussion by thowd22** [argoproj/argo-workflows#11314] [Q&A]
Im trying to setup SSO to our gitea instance. Im deploying argo workflows from the helm chart and ive mounted our internal CA chain to the server and controller, but im getting x509 errors. Im mounting like this.

``` 
 volumeMounts:
  - mountPath: /etc/ssl/certs/ca.crt
    name: argo-company-ca-chain
    subPath: ca-cert
  
  volumes:
  - name: argo-company-ca-chain
    configMap:
      name: argo-company-ca-chain
```

However im still getting the x509 error. What format does the CA chain need to be in?
