### DISCUSSION TITLE
Workflow fails with dash ("-") in the conditional `when` statement

### DISCUSSION THREAD

**Discussion by tcherokee** [argoproj/argo-workflows#11331] [Q&A] [answered]
Hi guys,

I have been having some issues getting my workflow, being triggered by argo-events, to run when my worflow.parameters has a "-" in it. Here is the original code in question

```yaml
- name: build-image-push
  dependencies: [clone-repo]
  when: "{{workflow.parameters.repo_name}} == games-api-example"
  templateRef:
    name: clone-build-push
    template: build-image-from-repo
    clusterScope: true
```

I came across this issue https://github.com/argoproj/argo-workflows/issues/3611 and updated my code to this 

```yaml
- name: build-image-push
  dependencies: [clone-repo]
  when: "{{workflow.parameters.repo_name}} == \"games-api-example\""
  templateRef:
    name: clone-build-push
    template: build-image-from-repo
    clusterScope: true
```

but it also does not seem to work either.

when I check the workflow logs, I find this error.

```
Failed to evaluate 'when' expresion 'games-api-example == "games-api-example"': Value 'games' cannot be used with the modifier '-', it is not a number
```

I am not exactly sure what I am doing wrong. I hope someone can give me some guidance
