### DISCUSSION TITLE
Is it possible to store an artifact of an http template response?

### DISCUSSION THREAD

**Discussion by aguerrero232** [argoproj/argo-workflows#11383] [Q&A]
Something like this?

```yaml
    - name: http-get
      inputs:
        parameters:
          - name: url
      http:
        method: GET
        url: '{{inputs.parameters.url}}'
      outputs:
        # ? store the response in an artifact to be used by other steps
        artifacts:
          - name: response
            path: /tmp/response.json
```

**Comment by wesleyscholl** [comment]
@aguerrero232 

The `http` template response doesn't currently support artifact outputs. 

- https://argo-workflows.readthedocs.io/en/latest/http-template/
- https://argo-workflows.readthedocs.io/en/latest/fields/#http

However, this is possible using the http input artifact. This is a basic functional workflow demonstrating http input artifact usage:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-artifact-example-
spec:
  entrypoint: download-http-artifact
  templates:            
    - name: download-http-artifact
      inputs:
        artifacts:
          - name: readme-text
            path: /tmp/readme.txt
            mode: 0644
            http:
              url: https://raw.githubusercontent.com/argoproj/argo-workflows/refs/heads/main/README.md
      container:
        image: alpine:3.14
        command: [sh, -c]
        args:
          - |
            echo "Contents of the downloaded file:"
            cat /tmp/readme.txt
            echo "File size:"
            wc -c /tmp/readme.txt
```

Reference:
- https://github.com/argoproj/argo-workflows/blob/main/examples/input-artifact-http.yaml
