### DISCUSSION TITLE
Task containers have `runAsUser: 12345` in Openshift?

### DISCUSSION THREAD

**Discussion by vitalyrychkov** [argoproj/argo-workflows#11458] [Q&A] [answered]
Our customer deployed Argo Workflows 3.4.0 in Openshift
When we try to submit any workflow, Argo Workflows starts task init, main and wait containers with `runAsUser: 12345` which is not in the UID range assigned to the namespace where the pod is supposed to be started. Any ideas why the UID of the task pod is set to 12345? Also the GUID is set to 12345:

```yaml
    securityContext:
      capabilities:
        drop:
        - ALL
        - MKNOD
      runAsGroup: 12345
      runAsNonRoot: true
      runAsUser: 12345
```
