### DISCUSSION TITLE
templating metrics with Helm

### DISCUSSION THREAD

**Discussion by sabreensalama** [argoproj/argo-workflows#11539] [Q&A] [answered]
Hi, I have many argo-workflow templates and I need to define a custom metrics to monitor  the duration of each workflow, but everytime I got this error
```
at <duration>: wrong number of args for duration: want 1 got 0
Use --debug flag to render out invalid YAML
```
 although I make sure that  the template is correct, here is the template-file, is there any help?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wft-cassandra-e2e
spec:
  entrypoint: cassandra-e2e

  templates:
  - name: cassandra-e2e
    metrics:
     prometheus:
      - name: exec_duration_gauge
        labels:
          - key: name
            value: wft-cassandra-e2e
        help: "Duration gauge by name"
        gauge:
          realtime: true
          value: {{ duration }}
    dag:
      tasks:
      - name:  load
        templateRef:
          name: load
          template:load
      - name: load-2
        depends: load
        templateRef:
          name: load-2
          template: load-2
```

**Comment by agilgur5** [comment]
I think you meant to use `"{{ workflow.duration }}"`. 
Your Workflow has plain `{{ duration }}`, which seems to be being interpreted as a function.

See also [the example in the docs](https://argoproj.github.io/argo-workflows/metrics/#metric-spec):
```yaml
# ...
        gauge:
          value: "{{ workflow.duration }}"
```

**EDIT**:  `{{ duration }}` is also [valid](https://argoproj.github.io/argo-workflows/metrics/#real-time-metrics). Per [the answer](https://github.com/argoproj/argo-workflows/discussions/11539#discussioncomment-6668907), OP was using Helm and didn't escape the expression syntax -- the error was from Helm, not Argo.

**Reply by sabreensalama** [reply]
I tried it with  `{{ workflow.duration }}` but i got an `error : function "workflow" not defined`

**Reply by agilgur5** [reply, marked as answer]
It sounds like you're trying to put the resource through Helm?
You did not mention that in your question, but that is a very important detail 😕 That would explain why it interpreted [`duration` as a function](https://helm.sh/docs/chart_template_guide/function_list/#duration), despite not using an [Argo expression](https://argoproj.github.io/argo-workflows/variables/#template-tag-kinds). And `workflow` is indeed not a Helm function, it is an Argo variable.
I thought the error sounded off initially, but did not think Helm were being used without mention...

If you're using Helm templating, you need to escape Argo's own templating. https://github.com/helm/helm/issues/2798 lists several ways of doing so. The one I am most familiar with is "Option 1" from this [SO answer](https://stackoverflow.com/a/64805238/3431180) (written by [an Argo CD maintainer and Workflows contributor](https://github.com/argoproj/argoproj/blob/8d3793efb7ad73d07dbf9f5e3954ac952a263369/MAINTAINERS.md?plain=1#L22)).
Here's how you could use that for your template:
```yaml
# ...
        gauge:
          value: "{{`{{ workflow.duration }}`}}"
```
The links above describe how this works in detail, but basically the backticks tell Helm to render the inner string as-is as a literal. That makes Helm render the Argo syntax out properly.
