### DISCUSSION TITLE
`workflowStepRef` not working with Output Parameter

### DISCUSSION THREAD

**Discussion by pravinparab** [argoproj/argo-workflows#11548] [Q&A] [answered]
Hi Team,

I am using argo workflow v3.4.8

I am executing below output parameter workflow , so there i am getting below issue 

```
Bad Request: templates.main.steps[1].step-b templates.step-b-template inputs.parameters.output-value was not supplied
```

![image](https://github.com/argoproj/argo-workflows/assets/67361822/f5d87546-06d3-46ae-8770-be2cb7a1e703)

workflow 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: local-storage-example-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: step-a
            template: step-a-template
        - - name: step-b
            template: step-b-template
            arguments:
              parameters:
                - name: output-value
                  valueFrom:
                    workflowStepRef:
                      name: step-a
                      outputName: output-parameter-example-step-a

    - name: step-a-template
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo 'Hello from Step A' > /tmp/output.txt"]
      outputs:
        parameters:
          - name: output-parameter-example-step-a
            valueFrom:
              path: /tmp/output.txt

    - name: step-b-template
      inputs:
        parameters:
          - name: output-value
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["cat /tmp/output-value.txt"]
```

**Comment by agilgur5** [comment, marked as answer]
[`valueFrom`](https://argoproj.github.io/argo-workflows/fields/#valuefrom) does not seem to have a field named `workflowStepRef`. Was there an example you borrowed the syntax from?

An equivalent way of retrieving that value would be to use an expression. Following [this example](https://github.com/argoproj/argo-workflows/blob/19674de8fa6be8cd5e8213062c8531bfd94e5a75/examples/output-parameter.yaml#L29), you could do:
```yaml
# ...
        arguments:
          parameters:
          - name: output-value
            value: "{{steps.step-a.outputs.parameters.output-parameter-example-step-a}}"
```
