### DISCUSSION TITLE
`'workflow.duration'` or `duration` `is not available as a real time metric`

### DISCUSSION THREAD

**Discussion by sabreensalama** [argoproj/argo-workflows#11551] [Q&A]
Hi, I am trying to create  define metrics but I got this issue  `'workflow.duration' is not available as a real time metric` even if I used duration too ,  also  If I define real time with true value or if I not defined it, also I defined the metrics section inside the template got the same issue  here is a sample of code , and I am using helm and tried to see the metric in the controller endpoint but I can't see it, any help

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wft-cassandra-data-importerv2-e2e
spec:
  entrypoint: cassandra-data-loadv2-e2e
  serviceAccountName: argo-workflows-cassandra
  metrics:
        prometheus:
        - name: exec_duration_gauge
          labels:
              - key: name
                value: cassandra_data_loadv2
          help: "Duration gauge by name"
          gauge:
                realtime: true
                value: "{{`{{workflow.duration}}`}}"

  activeDeadlineSeconds: {{ .Values.cassandra.dataImporterv2.activeDeadlineSeconds }}
  ttlStrategy:
    secondsAfterCompletion: {{ .Values.cassandra.dataImporterv2.secondsAfterCompletion }}

  templates:
  - name: cassandra-data-loadv2-e2e
    dag:
      tasks:
      - name: cassandra-1
        templateRef:
          name: cassandra-1
          template: cassandra-1
      - name: cassandra-2
        templateRef:
          name: cassandra-2
          template: cassandra-2
```
