### DISCUSSION TITLE
MetricsError: real time metrics can only be used with metric variable

### DISCUSSION THREAD

**Discussion by sabreensalama** [argoproj/argo-workflows#11573] [Q&A]
I got this issue although in the documentation it says that real time supported for `workflow.duration` and `duration` https://argoproj.github.io/argo-workflows/variables/#real-time-metrics, could you help me
```yaml
  - name: cassandra-data-loadv2-e2e
    metrics:
        prometheus:
        - name: exec_duration_gauge
          labels:
              - key: name
                value: cassandra_data_loadv2
          help: "Duration gauge by name"
          gauge:
                realtime: true
                value: "{{`{{workflow.duration}}`}}"
```
