### DISCUSSION TITLE
[archived] "Windows" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#11606] [General]
# argo-workflows/windows/

https://argoproj.github.io/argo-workflows/windows/

**Comment by jxlwqq** [comment]
argoexec  init container is not support windows hostprogress container mode: https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/

**Comment by jxlwqq** [comment]
And If you want to use `script` type with `powershell`, you can write like this:

```yaml
script:
  image: mcr.microsoft.com/powershell:lts-nanoserver-1809
  command: ["cmd", "/c", "pwsh", "<"]
  source: |
    Write-Host "Hello World!"
```
