### DISCUSSION TITLE
Keep Getting Error: "invalid client_secret on token request for client: argo-workflows-sso"

### DISCUSSION THREAD

**Discussion by allidoisace** [argoproj/argo-workflows#11647] [Q&A]
When attempting to login via Microsoft connector with ArgoCD Dex, I keep receiving this error in the Dex logs:
`"invalid client_secret on token request for client: argo-workflows-sso"`
I know for a fact that my staticClient id matches the argo-workflows-sso and I have followed the documentation to use the client-secret in a Sealed Secret.

Here is my Dex deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-cd-dex
spec:
  template:
    spec:
      containers:
        - name: dex
          env:
            - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: argo-cd-secret
                  key: client-secret
```

Here is my Dex configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-cd-config
  namespace: argo-cd
data:
  admin.enabled: "false"
  url: https://argo-cd.mydomain.com
  dex.config: |
    connectors:
    - type: microsoft
      id: microsoft
      name: My Name
      config:
        clientID: $MICROSOFT_APP_ID
        clientSecret: $MICROSOFT_APP_SECRET
        redirectURI: https://argo-cd.mydomain.com/api/dex/callback
        tenant: $MICROSOFT_TENANT
    staticClients:
      - id: argo-workflows-sso
        name: Argo Workflows
        redirectURIs:
          - https://argo-workflows.mydomain.com/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```

Here is my ArgoCD Secret
```
apiVersion: v1
kind: Secret
metadata:
  name: argo-cd-secret
  namespace: argo-cd
  labels:
    app.kubernetes.io/name: argo-cd-secret
    app.kubernetes.io/part-of: argo-cd
type: Opaque
data:
  server.secretkey: <random key b64 encoded>
  client-id: <argo-workflows-sso b64 encoded>
  client-secret: <random key b64 encoded>
  MICROSOFT_APP_ID: ...
  MICROSOFT_APP_SECRET: ...
  MICROSOFT_TENANT: ...
```
