### DISCUSSION TITLE
init container failed to start when pod run on edge node (KubeEdge)

### DISCUSSION THREAD

**Discussion by Jackie-Haiyu** [argoproj/argo-workflows#11666] [Q&A] [answered]
Background:

1. intall argo workflow refers https://github.com/argoproj/argo-workflows/releases/tag/v3.4.10
 `kubectl create namespace argo`
   `kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.4.10/install.yaml`
2. add a IPC (Industrial Personal Computer) by KubeEdge to K8s cluster.  
-     could get the node by: kubectl get node
![image](https://github.com/argoproj/argo-workflows/assets/313204/99a8b5c6-76ed-4e78-bdc2-2593bbaab1ed)

-     could deploy deployment, pod and job and run on the edge node by set nodeSelector.
![image](https://github.com/argoproj/argo-workflows/assets/313204/14476d83-af23-4284-aebb-4e1c5fdac61a)
3. submit a workflow from UI
![image](https://github.com/argoproj/argo-workflows/assets/313204/5f21ee17-f4c8-40d7-9aca-764f8fc53289)
4. workflow failed with below error messages.

> Error (exit code 2): invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

![image](https://github.com/argoproj/argo-workflows/assets/313204/edfc77e2-d5fa-4aa1-bf86-95eb81cbc8b6)

But I do not know what is the root cause and how to fix it.

**Comment by Jackie-Haiyu** [comment]
init container failed with below message:
![image](https://github.com/argoproj/argo-workflows/assets/313204/8aa7ad59-04ad-4398-a3d4-da0075a583f8)

**Comment by wesleyhaws** [comment]
I'm experiencing the same issue but with simply trying to have a workflow deploy a kubernetes job. I get the exact same error:
```
Error (exit code 2): invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
Reading around has lead me to nothing really helpful. So hopefully this conversation will lead to some good findings.

**Reply by wesleyhaws** [reply]
Does anyone know on the above? I have been battling with this for the past 9 hours now.

**Reply by agilgur5** [reply]
The error sounds like the kubeconfig is not properly configured.

Why it's not configured correctly though, I don't know

**Reply by wesleyhaws** [reply]
But this is already inside of kubernetes, that doesn't make a lot of sense to me....

**Reply by agilgur5** [reply]
Given your [answer](https://github.com/argoproj/argo-workflows/discussions/11666#discussioncomment-6876927) below regarding `automountServiceAccountToken`, that adds up, as the [SA mount](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting) is what lets a Pod connect to the k8s API. With no SA and no alternative kubeconfig, such an error would be expected.

**Comment by terrytangyuan** [comment]
What happens when you create that Job without Argo?

**Reply by wesleyhaws** [reply]
When I run the `kubectl apply -f ....` it is deployed properly. This is deploying a job manifest file. I copied that manifest out of the `manifest` key and ran the apply as stated above and it is sitting out there now.

Now just need to figure out why workflows is complaining.

**Reply by wesleyhaws** [reply]
Here is what I'm trying to deploy:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: scripts-testing
spec:
  entrypoint: failure
  arguments:
    parameters:
      - name: workflow_id
        value: 0
      - name: app_name
        value: ""
  templates:
    - name: failure
      serviceAccountName: argo-workflows-testing
      inputs:
        parameters:
          - name: workflow_id
          - name: app_name
      resource:
        action: create
        setOwnerReference: true
        manifest: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: "testing-notify-failure"
            annotations:
              argocd.argoproj.io/hook: SyncFail
              argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
          spec:
            template:
              spec:
                serviceAccountName: argo-workflows-testing
                containers:
                - name: failed-notification
                  image: curlimages/curl
                  command:
                    - "sh"
                    - "-c"
                    - >
                      ...
                      ... NOTE: "{{ `{{inputs.parameters.workflow_id}}` }}" exists in here....
                      ...
                restartPolicy: Never
            backoffLimit: 2
```
Then I issue this PUT curl command to trigger it for testing:
```
curl -X 'PUT' \
  'https://{endpoint}/api/v1/workflows/{namespace}/testing-failure-notification/resubmit' \
  -H 'accept: application/json' \
  -H "Authorization: Bearer ${ARGO_TOKEN}" \
  -H 'Content-Type: application/json' \
  -d '{
        "dryrun": true,
        "parameters": [
            "workflow_id=0",
            "app_name=sample"
        ],
        "name": "testing-failure-notification"
}'
```

**Reply by wesleyhaws** [reply]
Is there like some permission that the workflow service account needs in order to access kubernetes in some way?

**Reply by terrytangyuan** [reply]
Can you run a container template instead of a resource template?

**Reply by wesleyhaws** [reply]
Sure if I can run this set of code after a post sync failed or success from argocd. Do you have a link to an example I can look at?

**Reply by wesleyhaws** [reply]
I think I put something together base on the docs here: https://argoproj.github.io/argo-workflows/container-set-template/

It starts up throws the same error and launches my container which endlessly runs in a `Pending` state. I notice there is an "initContainer" with:
```
Init Containers:
  init:
   ....
    Image:         quay.io/argoproj/argoexec:v3.4.4
```
Even though I didn't specify one in my definition. Is there a universal init container that is started unless I specify some sort of annotation to prevent that or is this something that is required under the hood?

**Reply by wesleyhaws** [reply]
Note: The above mentioned container is where this error is coming from....

**Reply by agilgur5** [reply]
> Is there like some permission that the workflow service account needs in order to access kubernetes in some way?

Your template's SA will need to have RBAC to `create` a `Job` in your case.
Docs: https://argoproj.github.io/argo-workflows/service-accounts/

**Reply by wesleyhaws** [reply]
I have this permission already:
```
jobs.batch                               []                 []              [list watch create update patch get delete]
```

**Reply by wesleyhaws** [reply]
I'm getting this stack trace from the init container I mentioned above. Seems like an argo thing to me.
```
W
time="2023-08-30T18:50:11.181Z" level=info msg="Starting Workflow Executor" version=v3.4.4
panic: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
goroutine 1 [running]:
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.checkErr({0x2b71bc0, 0xc0005922e8})
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/root.go:147 +0x6b
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.initExecutor()
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/root.go:83 +0x1a5
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.loadArtifacts({0x2b90ee0, 0xc00013a000})
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/init.go:27 +0x58
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.NewInitCommand.func1(0xc0001aec80?, {0x260d32f?, 0x4?, 0x4?})
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/init.go:17 +0x27
github.com/spf13/cobra.(*Command).execute(0xc0001aec80, {0xc000464f00, 0x4, 0x4})
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ca3680)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/main.go:16 +0x25
        ```

**Reply by wesleyhaws** [reply]
Here is the config map that was asked for on slack: https://app.slack.com/client/T08PSQ7BQ/C01QW9QSSSK/thread/C01QW9QSSSK-1693416866.758019

```yaml
apiVersion: v1
data:
  config: |
    artifactRepository:
      archiveLogs: true
      s3:
        bucket: {s3_bucket_name}
        endpoint: s3.amazonaws.com
        insecure: 
        region: {region}
        roleARN: {aws_role_arn}
    metricsConfig:
      enabled: true
      path: /metrics
      port: 9090
      ignoreErrors: false
      secure: false
    workflowDefaults:
      spec:
        activeDeadlineSeconds: 7200
        ttlStrategy:
          secondsAfterCompletion: 172800
    sso:
      issuer: {issuer}
      clientId:
        name: argo-workflows-sso
        key: client-id
      clientSecret:
        name: argo-workflows-sso
        key: client-secret
      redirectUrl: {oauth_callback}
      rbac:
        enabled: true
      scopes: 
        - profile
        - groups
        - email
    nodeEvents:
      enabled: true
kind: ConfigMap
metadata:
  {...I removed this section as deemed no necessary...}
  creationTimestamp: '2023-06-09T22:41:12Z'
  labels:
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-0-33-1-cm
    app.kubernetes.io/part-of: argo-workflows
    argocd.argoproj.io/instance: argo-workflows
    helm.sh/chart: argo-workflows-0-33-1-0.33.1
  name: argo-workflows-workflow-controller-configmap
  namespace: argo-workflows
  resourceVersion: '1234375504'
```

**Reply by agilgur5** [reply]
> I'm getting this stack trace from the init container I mentioned above. Seems like an argo thing to me.

As I mentioned in the other thread [above](https://github.com/argoproj/argo-workflows/discussions/11666#discussioncomment-6867445), that is a k8s credentials error. It's coming from the k8s [client initialization](https://github.com/argoproj/argo-workflows/blob/f5e31f8f36b32883087f783cb1227490bbe36bbd/cmd/argoexec/commands/root.go#L81).

That adds up with your current [answer](https://github.com/argoproj/argo-workflows/discussions/11666#discussioncomment-6876927) regarding `automountServiceAccountToken`.

**Comment by wesleyhaws** [comment, marked as answer]
@Jackie-Haiyu A solution was posted on the slack channel , I tried it and it worked!!! 

Simply remove the following from your ServiceAccount:
```yaml
automountServiceAccountToken: false
```

As soon as I remove that one line it deployed successfully.

**Reply by agilgur5** [reply]
The SA mount gives a Pod credentials to the k8s API, so that adds up. See also the k8s docs on this: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting

**Comment by hmz-walter** [comment]
I have removed the line from `quick-start-minimal.yaml`：
```yaml
automountServiceAccountToken: false
```
and I grant `argo、argo-server、admin` `ServiceAccount` admin privileges:
```

kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=argo:default -n argo

kubectl create rolebinding argo-admin --clusterrole=admin --serviceaccount=argo:argo -n argo

kubectl create rolebinding argo-server-admin --clusterrole=admin --serviceaccount=argo:argo-server -n argo

```
But I cann't run my pod in **kubeEdge cluster**,here is the mistake:
```

Error (exit code 2): invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
the `yaml` file :
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-parameter-
spec:
  entrypoint: output-parameter
  templates:
  - name: output-parameter
    steps:
    - - name: generate-parameter
        template: nginx
    - - name: consume-parameter
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate-parameter.outputs.parameters.nginx-index}}"
  - name: nginx
    nodeSelector:
      kubernetes.io/hostname: "edge1"
    container:
      image: docker.m.daocloud.io/nginx:latest
      command: [sh, -c]
      args: ["sleep 1; cat /usr/share/nginx/html/index.html"]
    outputs:
      parameters:
      - name: nginx-index
        valueFrom:
          default: "Foobar"
          path: /usr/share/nginx/html/index.html
  - name: print-message
    nodeSelector:
      kubernetes.io/hostname: "edge1"
    inputs:
      parameters:
      - name: message
    container:
      image: docker.m.daocloud.io/alpine:latest
      command: [echo]
      args: ["{{inputs.parameters.message}}"]
```
Any helps would be appreciated.
