### DISCUSSION TITLE
Inconsistent Listing of Workflows

### DISCUSSION THREAD

**Discussion by om3171991** [argoproj/argo-workflows#11671] [Q&A] [answered]
Hi Team,

We are facing a weird issue where listing of workflow is inconsistent which mean sometime its show few workflow and sometime not. For example 

In screenshot1, We tried to list all workflow with label "ProjectName=Build" but its only show few workflow. Like in screenshot2, workflow name which has "gitops" are not coming in the list though same label is used. Also if we removed all filters from Argo Workflow dashboard, then as well can't see all workflow. Can you please suggest what I am doing wrong here?
<img width="1661" alt="image" src="https://github.com/argoproj/argo-workflows/assets/86664910/f628c0ff-a502-4194-92d1-e13d684afa95">
<img width="1471" alt="image" src="https://github.com/argoproj/argo-workflows/assets/86664910/f3d64338-9412-4837-855f-536098f523bf">

**Comment by agilgur5** [comment]
Pagination with sorting will show a [warning](https://github.com/argoproj/argo-workflows/blob/f5e31f8f36b32883087f783cb1227490bbe36bbd/ui/src/app/shared/components/pagination-panel.tsx#L28), which might be related. Does the problem persist without pagination?

Also there is a possible regression around the UI list: https://github.com/argoproj/argo-workflows/issues/9696. Is it inconsistent with the same filters when using the CLI?

**Reply by om3171991** [reply]
Dont see this warning in argo-server logs. Not tried with CLI to list workflows.

**Reply by agilgur5** [reply]
The warning is in the UI, not the logs. Does the problem persist without pagination?

**Reply by agilgur5** [reply]
> Also if we removed all filters from Argo Workflow dashboard, then as well can't see all workflow.

This one I believe I just fixed in #11792 as part of [investigation](https://github.com/argoproj/argo-workflows/issues/9696#issuecomment-1712706021) into #9696. Removing date filters would break the list.

> Not tried with CLI to list workflows.

It would be a very helpful point of comparison if you could try that. If the CLI is correct while the UI is incorrect, then it is potentially a UI bug. If both are incorrect, then it is potentially an API bug.

#9909 also had a fix that was released in 3.4.4 for the UI. What version of Workflows are you using?

**Reply by om3171991** [reply]
We are running with **v3.4.5** version Argo UI. 

I tried to list workflow with CLI but didn't able to get list. 

➜  ~ argo -v -n argo-events --gloglevel 9 --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --argo-server argo-dev.dev.k8s.xxxxxxx:443 --argo-base-href "/workflow" -e --argo-http1  list
DEBU[2023-09-13T15:29:35.417Z] CLI version                                   version="{v3.4.11+ee939bb.dirty 2023-09-08T00:47:28Z ee939bbd2d8950a2fa1badd7cfad3b88c039da26 v3.4.11 dirty go1.21.1 gc darwin/arm64}"
DEBU[2023-09-13T15:29:35.417Z] Client options                                opts="(argoServerOpts=(url=argo-dev.dev.k8s.xxxxxxx:443,path=/workflow,secure=true,insecureSkipVerify=false,http=true),instanceID=)"
DEBU[2023-09-13T15:29:35.417Z]                                               listOpts="&ListOptions{LabelSelector:,FieldSelector:,Watch:false,ResourceVersion:,TimeoutSeconds:nil,Limit:0,Continue:,AllowWatchBookmarks:false,ResourceVersionMatch:,}"
DEBU[2023-09-13T15:29:35.417Z] curl -X GET -H 'Authorization: ******' -d '' 'https://argo-dev.dev.k8s.xxxxxxx:443/workflow/api/v1/workflows/argo-events?fields=metadata%2Citems.metadata%2Citems.spec%2Citems.status.phase%2Citems.status.message%2Citems.status.finishedAt%2Citems.status.startedAt%2Citems.status.estimatedDuration%2Citems.status.progress' 
**FATA[2023-09-13T15:29:36.296Z] invalid character '<' looking for beginning of value**

**Reply by agilgur5** [reply]
> FATA[2023-09-13T15:29:36.296Z] invalid character '<' looking for beginning of value

That type of parse error means a server returned an HTML page (instead of, say, JSON). The `<` is at the beginning of HTML.

Not sure if your Ingress rewrites are correctly set

**Reply by om3171991** [reply]
We are not using any ingress rewrite… I tried with k8 load balancer service and still getting same error msg. Any example or doc I can follow for cli ?

**Reply by agilgur5** [reply]
> We are not using any ingress rewrite…

You're trying to host the Server on a subpath though, `/workflow/`. That requires an Ingress rewrite as of current time. See #7767 for a feature request to not require an Ingress rewrite.

If the Server is hosted at root, that will work fine.

> Any example or doc I can follow for cli ?

The HTML parse error you got is not a CLI error, it's an Ingress configuration issue

**Reply by om3171991** [reply]
Finally able to run CLI. Issue was with my command. I was using **--argo-base-href "/workflow"**  which caused this issue. 

I tried to fetch last 6 hours workflows via CLI and its result is coming out correct as compared to UI.

CLI result:

<img width="1545" alt="image" src="https://github.com/argoproj/argo-workflows/assets/86664910/97c68167-a0af-452d-8146-4bebb6265a96">


UI result:
![image](https://github.com/argoproj/argo-workflows/assets/86664910/7c5d1608-8ae9-4113-8279-e8814849a913)

**Reply by om3171991** [reply]
Both screenshots are taken will 10-15 seconds delay. CLI shows 5-6 workflows are running where as UI show only 2.

**Reply by agilgur5** [reply]
Thanks for providing those, that's useful debugging info. So the UI is only ignoring `Running` Workflows then? That would suggest they might be missing a `status.startedAt`, but that [shouldn't ever happen](https://github.com/argoproj/argo-workflows/blob/7aedf973356c8b57510a554b6b759f2684f88839/workflow/controller/operator.go#L2228) 🤔 

If you're able to reliably reproduce this, could you provide the k8s object for one of the Workflows that is in the CLI and not the UI? `status.phase`, `status.startedAt`, and `metadata.creationTimestamp` fields specifically are useful, though the whole Workflow object might have some more debugging info.

This does look like the same issue as #9696 then if the CLI is correct. I am planning on making another change to the UI to make the two have equivalent output. The basic difference though is that `--since` tracks `metadata.creationTimestamp` while the UI uses `status.startedAt`.
The UI currently only shows Workflows with no `status.startedAt` [if they are `Pending`](https://github.com/argoproj/argo-workflows/blob/7aedf973356c8b57510a554b6b759f2684f88839/ui/src/app/workflows/components/workflows-list/workflows-list.tsx#L263). This potentially means that the Workflow got into a `Running` state without its `status.startedAt` getting set -- which would be a bug. That or potentially a flawed network request somewhere

**Reply by om3171991** [reply]
So the UI is only ignoring Running Workflows then ?
I don't think so, other workflow are missing as well. Check in below screenshot. No last 6hrs workflow is coming in UI whether completed, running or pending etc
<img width="1545" alt="image" src="https://github.com/argoproj/argo-workflows/assets/86664910/5a756f43-ca85-4800-a58a-3b6f2c891147">
<img width="1554" alt="image" src="https://github.com/argoproj/argo-workflows/assets/86664910/3cf749d8-090d-4dc6-8348-eb0c99d3c068">

could you provide the k8s object 
I have removed org specific details from below K8 Object but this  not visible in UI.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    workflows.argoproj.io/pod-name-format: v2
  creationTimestamp: "2023-09-15T06:08:58Z"
  generateName: website-monorepo-1a-695e8a1-
  generation: 5
  labels:
    ProjectName: website-monorepo
    Team: UI
    events.argoproj.io/action-timestamp: "1694758138353"
    events.argoproj.io/sensor: website-monorepo-1-sensor-pr-update
    events.argoproj.io/trigger: tm-website-pr-updated-trigger
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Succeeded
  name: website-monorepo-1a-695e8a1-jfxkp
  namespace: argo-events
spec:
  entrypoint: dag
  securityContext:
    runAsNonRoot: true
    runAsUser: 10000
  templates:
  - dag:
      tasks:
      - arguments: {}
        name: npm
        template: npm
    inputs: {}
    metadata: {}
    name: dag
    outputs: {}
  - name: npm
    metadata: {}
    outputs: {}
    script:
      command:
      - bash
      image: ubuntu:22.04
      name: ""
      resources: {}
      source: |
        #!/bin/sh
        echo "-----------------------------"
        echo "      STARTING PIPELINE      "
        echo "-----------------------------"
        echo "      PIPELINE RUNNING     "
        echo "-----------------------------"
        echo "     PIPELINE COMPLETED      "
        echo "-----------------------------"
      volumeMounts:
      - mountPath: /workspace
        name: output
      workingDir: /workspace/src
  volumeClaimGC:
    strategy: OnWorkflowCompletion
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: workspace
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 25Gi
    status: {}
  volumes:
  - name: output
    persistentVolumeClaim:
      claimName: website-monorepo-1a-695e8a1-jfxkp-workspace
status:
  conditions:
  - status: "False"
    type: PodRunning
  - status: "True"
    type: Completed
  finishedAt: "2023-09-15T06:16:03Z"
  nodes:
    website-monorepo-1a-695e8a1-jfxkp:
      children:
      - website-monorepo-1a-695e8a1-jfxkp-1649639236
      displayName: website-monorepo-1a-695e8a1-jfxkp
      finishedAt: "2023-09-15T06:16:03Z"
      id: website-monorepo-1a-695e8a1-jfxkp
      name: website-monorepo-1a-695e8a1-jfxkp
      outboundNodes:
      - website-monorepo-1a-695e8a1-jfxkp-1649639236
      phase: Succeeded
      progress: 1/1
      resourcesDuration:
        cpu: 648
        memory: 648
      startedAt: "2023-09-15T06:08:58Z"
      templateName: dag
      templateScope: local/website-monorepo-1a-695e8a1-jfxkp
      type: DAG
    website-monorepo-1a-695e8a1-jfxkp-1649639236:
      boundaryID: website-monorepo-1a-695e8a1-jfxkp
      displayName: npm
      finishedAt: "2023-09-15T06:15:53Z"
      hostNodeName: ip-10-90-111-126.ec2.internal
      id: website-monorepo-1a-695e8a1-jfxkp-1649639236
      name: website-monorepo-1a-695e8a1-jfxkp.npm
      phase: Succeeded
      progress: 1/1
      resourcesDuration:
        cpu: 648
        memory: 648
      startedAt: "2023-09-15T06:08:58Z"
      templateName: npm
      templateScope: local/website-monorepo-1a-695e8a1-jfxkp
      type: Pod
  phase: Succeeded
  progress: 1/1
  resourcesDuration:
    cpu: 648
    memory: 648
  startedAt: "2023-09-15T06:08:58Z"
```

`--since` This is used to get limited data else cli list command is timing out.
