### DISCUSSION TITLE
Is it possible to reference an artifact which was created in a loop task ?

### DISCUSSION THREAD

**Discussion by stefankuksenko** [argoproj/argo-workflows#11720] [Q&A]
There are two parallel tasks "generate-artifact" for each language "en" and "fr" which produce some artifacts. In the next two parallel tasks "consume-artifact" I want to consume artifacts related to the same languages. 

When I run this example I get the error:
```
Unable to resolve: "tasks.generate-artifact.outputs.artifacts.hello-art"
```
obviously, because there is another structure of "tasks" due to parallel jobs with the same name. 
Is it even possible to refer to a specific job created via loop? Something like `tasks.generate-artifact['en'].outputs.artifacts.hello-art`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: artifact-passing
spec:
  entrypoint: artifact-example
  templates:
    - name: artifact-example
      inputs:
        parameters:
          - name: languages
            value: '["en", "fr"]'
      dag:
        tasks:
          - name: generate-artifact
            template: whalesay
            arguments:
              parameters:
                - name: language
                  value: {{item}}
            withParam: "{{inputs.parameters.languages}}"

          - name: consume-artifact
            template: print-message
            dependencies:
              - generate-artifact
            arguments:
              artifacts:
                - name: message
                  from: "{{tasks.generate-artifact.outputs.artifacts.hello-art}}"
            withParam: "{{inputs.parameters.languages}}"

    - name: whalesay
      inputs:
        parameters:
          - enum:
              - fr
              - en
            name: language
      container:
        image: docker/whalesay:latest
        command: [ sh, -c ]
        args: [ "echo the lang is {{inputs.parameters.language}} | tee /tmp/hello_world.txt" ]
      outputs:
        artifacts:
          # generate hello-art artifact from /tmp/hello_world.txt
          # artifacts can be directories as well as files
          - name: hello-art
            path: /tmp/hello_world.txt

    - name: print-message
      inputs:
        artifacts:
          # unpack the message input artifact
          # and put it at /tmp/message
          - name: message
            path: /tmp/message
      container:
        image: alpine:latest
        command: [ sh, -c ]
        args: [ "echo $(cat /tmp/message)" ]
```
