### DISCUSSION TITLE
Issue with Server Args after passing certificate authority

### DISCUSSION THREAD

**Discussion by ncoyne** [argoproj/argo-workflows#11813] [Q&A]
Hello team,

After upgrading Argo Workflows from 3.2.6 to 3.4.10 we are seeing an issue with our argo-worklows-server deployment.  At first we were seeing this in the workflow-server logs after upgrading from:

```
argo-server time="2023-09-13T17:23:43.374Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode" argo-server Error: issuer empty
```

So we changed our args to this: 
```yaml   
    spec:
      containers:
      - args:
        - server
        - --configmap=argo-workflows-workflow-controller-configmap
        - --auth-mode=sso
        - --auth-mode=client
        - --secure=true
        - --certificate-authority=/etc/ssl/certs/
        - --loglevel
        - debug
        - --gloglevel
        - "0"
        - --log-format
        - text
        - v
```

Now we are seeing the following error which leads me to believe their is an error in the above configuration but I cannot find it:
```
argo-server Error: invalid configuration: default cluster has no server defined
```

Any help would be appreciated.
