### DISCUSSION TITLE
Unable to create a workflowtemplate using API via Postman

### DISCUSSION THREAD

**Discussion by ashokdonepudi** [argoproj/argo-workflows#11821] [Q&A] [answered]
I am using Http POST method to create a argo workflow template , but i am getting invalid character response .  I could not able to find proper documentation related to it . Can you please help me in how to create workflow template via HTTP request call .  I tried content-type as both JSON and YAML . 

Note: If I am using the same template data via argo cli I could able to create it successfully.

POST URL : https://localhost:2746/api/v1/workflow-templates/argo

 Template data : 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command:
          - cowsay
        args:
          - "{{inputs.parameters.message}}"
```

Screenshot : 
![image](https://github.com/argoproj/argo-workflows/assets/65293362/d645e433-9014-49c0-a6a3-eec9631e3747)
