### DISCUSSION TITLE
Problem creating ingress for Server

### DISCUSSION THREAD

**Discussion by mwoodpatrick** [argoproj/argo-workflows#11878] [Q&A]
I'm using k3d with an nginx ingress controller and trying to setup an ingress for argo workflows.

I applied the ingress below:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  name: argo-workflows-ingress
  namespace: argo
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - argo.westie.dev.to
    secretName: argo-ingress-tls
  rules:
    - host: argo.westie.dev.to
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argo-server
              port:
                number: 2746
```
                
 When I describe the created ingress I get:
 

```
k -n argo describe ing argo-workflows-ingress
Name:             argo-workflows-ingress
Labels:           <none>
Namespace:        argo
Address:          172.19.0.3,172.19.0.4,172.19.0.5,172.19.0.6
Ingress Class:    nginx
Default backend:  <default>
TLS:
  argo-ingress-tls terminates argo.westie.dev.to
Rules:
  Host                Path  Backends
  ----                ----  --------
  argo.westie.dev.to
                      /   argo-server:2746 (10.42.1.235:2746)
Annotations:          cert-manager.io/cluster-issuer: selfsigned-issuer
                      ingress.kubernetes.io/ssl-redirect: false
Events:
  Type    Reason             Age                  From                       Message
  ----    ------             ----                 ----                       -------
  Normal  CreateCertificate  5m9s                 cert-manager-ingress-shim  Successfully created Certificate "argo-ingress-tls"
  Normal  Sync               5m1s (x2 over 5m9s)  nginx-ingress-controller   Scheduled for sync
```

However when I access the location:

`https://argo.westie.dev.to/`

I get a 502 bad gateway error.

I have several other apps deployed on this cluster with very similar ingress specifications which work perfectly well.

I can access using a port-forward 

Any suggestions as to what I'm doing wrong or best way to debug would be most appreciated.

**Comment by cyberslot** [comment]
I confronted with the same problem (on GKE) and after some extensive research realized that a lot of people struggled with that topic. So I decided to give a try to Gateway API instead (NGINX Gateway Fabric) and after countless of attempts/permutations I still have no working solution on the table, in contrast to ArgoCD, where both Ingress and Gateway API implementations are achievable with ease.

**Reply by agilgur5** [reply]
There's lots of users of the Workflows Server with an Ingress working (including me at my previous job) and the Helm Charts [include an Ingress](https://github.com/argoproj/argo-helm/blob/85121e84515910947759fd91fa7c0ae6bec1df58/charts/argo-workflows/templates/server/server-ingress.yaml) too.

I'm not really sure why this config isn't working, but if the Server Deployment is up and the Service reachable internally, then it's an Ingress issue that is out of Argo's scope to solve.

**Reply by vaboston** [reply]
+1, i used helm chart to install argo-workflows instead quick-start-minimal.yaml manifest, and it works.

**Reply by ognyan-lazarov-cloudoffice** [reply]
Guys, thanks for your replies, even an year later, it's appreciated!
But now, as I mentioned, after a whole year, at least for me, the question has to be why are we still talking about Ingresses when the Gateway API has been in GA for almost exactly one year (October 31, 2023) - a technology that is completely standardized and much more advanced than the messy Ingress Controller?
And why in the documentation of two of the most prominent and utilized products of the Argo stack - Argo CD and Argo Workflows, there is not a word (at least I am not able to find one, correct me if I am missing something) about this way of service exposure?
Sorry, but that doesn't strike me as something that demonstrates an innovative mentality.

**Reply by agilgur5** [reply]
@ognyan-lazarov-cloudoffice The question is about an Ingress and so the answer is too. The `Ingress` resource also isn't deprecated.

> Sorry, but that doesn't strike me as something that demonstrates an innovative mentality.

No reason to make abusive, disparaging comments my dude.

> And why in the documentation

There is no `Ingress` in the base manifests at all since it is entirely optional and depends on your set-up whether you want or need one. The docs have a [single reference](https://argo-workflows.readthedocs.io/en/release-3.5/argo-server/#ingress) to `Ingress` that dates back years and primarily serves to instruct on usage with `BASE_HREF` (not relevant to this discussion).
This is also open source, anyone can contribute a `Gateway` resource to the Helm Charts or an example in the docs, including yourself.

Helping the community by contributing is a lot more productive than making unrelated, abusive comments on a support discussion.

**Reply by agilgur5** [reply]
> +1, i used helm chart to install argo-workflows instead quick-start-minimal.yaml manifest, and it works.

@vaboston the only diff I'm really seeing that is perhaps relevant is the `Service`'s [port `name`](https://github.com/argoproj/argo-workflows/blob/1017c1dbe2ccf3f0a59ae68f04d954dd92e69673/manifests/base/argo-server/argo-server-service.yaml#L9) being different in [the default](https://github.com/argoproj/argo-helm/blob/85121e84515910947759fd91fa7c0ae6bec1df58/charts/argo-workflows/values.yaml#L498) chart install? Maybe that's the issue here?

Specifically the base manifests use `web` for both the `Service` port name and the [`container` port name](https://github.com/argoproj/argo-workflows/blob/1017c1dbe2ccf3f0a59ae68f04d954dd92e69673/manifests/base/argo-server/argo-server-deployment.yaml#L28), whereas the chart [only sets](https://github.com/argoproj/argo-helm/blob/85121e84515910947759fd91fa7c0ae6bec1df58/charts/argo-workflows/templates/server/server-deployment.yaml#L77) the `container` port name by default. The `number`s are all equivalent at `2746` though 🤔

**Reply by ognyan-lazarov-cloudoffice** [reply]
@agilgur5 Abusive comments?! Really?!
And what was abusive exactly, my friend? If my intention was to be abusive, I wouldn't start my comment with gratitude, don't you think?
Nevermind... Sorry to leave you feeling offended. Again - such a goal never even crossed my mind. 
Apparently the sensitivity threshold for that has dropped a lot lately...

**Reply by vaboston** [reply]
I noticed some differences on the Server `Deployment` server file:
- environment variable `BASE_HREF: /`
- container args different

I haven't tested to make sure because it works with helm

**Reply by agilgur5** [reply]
> * environment variable `BASE_HREF: /`

That's the default, so that has no semantic difference 

> * container args different

Because they're configurable in Helm, so that is expected too

**Reply by terrytangyuan** [reply]
Hi @ognyan-lazarov-cloudoffice,

I'd like to apologize on behalf of the Argo project for the accusation made against you in this thread. I do not agree with the accusation or the way it has been handled.

I will hide the accusation on this thread now to keep it on topic.

**Reply by ognyan-lazarov-cloudoffice** [reply]
> Hi @ognyan-lazarov-cloudoffice,
> 
> I'd like to apologize on behalf of the Argo project for the accusation made against you in this thread. I do not agree with the accusation or the way it has been handled.
> 
> I will hide the accusation on this thread now to keep it on topic.

Thanks for that, but you have nothing to apologize for!
Argo project is a great initiative and you all guys are doing really fantastic job!
Keep going in that way.

**Comment by vaboston** [comment]
up

**Comment by ghost** [comment]
Just deployed Argo Workflows in Kubernetes using [argo-workflows](https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows) helm chart and used regular settings for [OAuth2-Proxy](https://github.com/oauth2-proxy/oauth2-proxy)
```yaml
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
      nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
    - hosts:
      - ${hostname}
      secretName: ${hostname}-tls
    hosts:
    - ${hostname}
    paths: ["/"]
    pathType: Prefix
```

And got **502 Bad Gateway** after OAuth2-Proxy authentications passed.

1. **Checked Ingress logs** and observer that it is communicating with the Argo server via **`HTTPS`**.

2. **Looking at the docs** - https://argo-workflows.readthedocs.io/en/latest/argo-server
   > Since v3.0 the Argo Server listens for HTTPS requests, rather than HTTP.

3. **Checking the Argo server**
   ```
   kubectl get pod argo-workflows-server-785699d947-gtqxm -n argo -o=jsonpath='{.spec.containers[].args}'
   ```
   ```
   ["server","--configmap=argo-workflows-controller-configmap","--auth-mode=server","--secure=false","--loglevel","info","--gloglevel","0","--log-format","text"]%                                                       ~ $
   ```
   **`"--secure=false"`**

4. **Updated Ingress annotations to use `HTTP`** - [Backend Protocol](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#backend-protocol)
   ```yaml
   ingress:
     annotations:
       nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
   ```

   All started to work as expected.

5. Updated charts values
   ```yaml
   server:
     secure: true
     ingress:
       annotations:
       nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
   ```

Now, all works as expected using HTTPS for backend communication.

<hr>

I would assume that the whole story is started because we expect that Argo Server is listening on `HTTPS`, but [chart default value is set to `false`](https://github.com/argoproj/argo-helm/blob/b0578c400163e9c65f90b3918a7b97ac50e3ac46/charts/argo-workflows/values.yaml#L596-L599
)
```yaml
  # -- Run the argo server in "secure" mode. Configure this value instead of `--secure` in extraArgs.
  ## See the following documentation for more details on secure mode:
  ## https://argo-workflows.readthedocs.io/en/stable/tls/
  secure: false
```

At the same time, [Ingress documentation](https://argo-workflows.readthedocs.io/en/latest/argo-server/#ingress) point us to use `HTTPS`, which is default in v3
> If TLS is enabled (default in v3.0 and after), the ingress controller must be told that the backend uses HTTPS.
