### DISCUSSION TITLE
Enhanced Depends Logic for the whole dags tasks failure

### DISCUSSION THREAD

**Discussion by sabreensalama** [argoproj/argo-workflows#11893] [Q&A]
Hello  All,
I have a  case that I need to upload all artifact files  to the S3 in case of failure of any dags task, I added it as below  
```
- name: pvc-s3-data-load
   depends: "pg-extract-sbc-wrapper.Skipped || pg-extract-sbc-wrapper.Daemoned || pg-extract-sbc-wrapper.Failed || pg-extract-props-goals.Succeeded || wft-pg-extract-mobile-dialer.Failed || wft-pg-extract-nba-edwh.Failed || pg-extract-ih-data.Failed || pg-extract-camp-metadata.Failed || pg-extract-camp-rundata.Failed || pg-extract-ref-data.Failed || pg-extract-props-goals.Failed"
   templateRef:
          name: wft-pg-pvc-s3-data-exporter
          template: pg-pvc-s3-data-exporter
````
, Is there any way to improve it to be like giving a name to the dags section like dags-tasks and put condition to any task failed under the dags-tasks, as below
```
dag:
     name: dags-tasks
      tasks:
      - name: pg-extract-sbc-wrapper
         templateRef:
            name: wft-pg-extract-sbc-wrapper
      - name: pvc-s3-data-load
         depends: "dag-tasks.AnyFailed"
         templateRef:
                name: wft-pg-pvc-s3-data-exporter
                template: pg-pvc-s3-data-exporter
````
