### DISCUSSION TITLE
workflowDefaults not applied

### DISCUSSION THREAD

**Discussion by georak** [argoproj/argo-workflows#11952] [Q&A]
Hi everyone, little help needed here, any idea why the following configuration not applied in my workflows? Do I missing something? 
argo-workflows version 3.4.11

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argo
  name: workflow-controller-configmap
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: argo
      endpoint: argo-artifacts.default.svc.cluster.local:9000
      insecure: true
      accessKeySecret:
        name: argo-artifacts
        key: accesskey
      secretKeySecret:
        name: argo-artifacts
        key: secretkey
      useSDKCreds: true
  resourceRateLimit: |
    limit: 40
    burst: 1
  mainContainer: |
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.1
        memory: 64Mi
      limits:
        cpu: 0.5
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
  executor: |
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.1
        memory: 64Mi
      limits:
        cpu: 0.5
        memory: 128Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  workflowDefaults: |
    spec:
      executor:
        serviceAccountName: argo-workflow
      serviceAccountName: argo-workflow
      automountServiceAccountToken: false
      ttlStrategy:
        secondsAfterCompletion: 600
        secondsAfterSuccess: 10
        secondsAfterFailure: 86400
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
```
