### DISCUSSION TITLE
Adding metricsTTL with finegrained selectable metrics

### DISCUSSION THREAD

**Discussion by ShyunnY** [argoproj/argo-workflows#12021] [Ideas]
When monitoring the workflow, I may want to automatically delete metrics when they expire given a TTL. But there are also some metrics that I hope not to delete. Can be saved forever.

Currently in `controller-cm`, only TTL settings for all metrics are supported.

```yaml
 # ...
  metricsConfig: |
    metricsTTL: "10m"
  # ...
```
