### DISCUSSION TITLE
Using artifact contents with a conditional (when) in steps workflow

### DISCUSSION THREAD

**Discussion by woutvanhauwermeiren** [argoproj/argo-workflows#12073] [Q&A]
I can't find how to do this. I want to use the output of an artifact in steps and continue based on the contents of that artifact. So far I couldn't get it working in a simple way. Am I missing something or is this an unsupported feature?

I updated the [flip coin example](https://github.com/argoproj/argo-workflows/blob/master/examples/coinflip.yaml) to include artifacts
``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-parameter-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      Conditional parameters provide a way to choose the output parameters based on expression.

      In this example the step template has two steps which will run conditionally on `when`.

      Based on that condition, one of step will not be executed. The step template's output parameter will be
      set from the executed step's output.
    workflows.argoproj.io/version: '>= 3.1.0'
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: flip-coin
            template: flip-coin
        - - name: heads
            template: heads
            when: '"{{steps.flip-coin.outputs.parameters.stepresult}}" == "heads"'
          - name: tails
            template: tails
            when: '"{{steps.flip-coin.outputs.parameters.stepresult}}" == "tails"'
    - name: flip-coin
      steps:
        - - name: flip-coin-actual
            template: flip-coin-actual
      outputs:
        parameters:
          - name: stepresult
            valueFrom:
              parameter: "{{steps.flip-coin-actual.outputs.artifacts.file}}"
    - name: flip-coin-actual
      outputs:
        artifacts:
          - name: file
            path: file.txt
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          import random
          with open("file.txt", "w") as file: 
            file.write("heads" if random.randint(0,1) == 0 else "tails")

    - name: heads
      outputs:
        artifacts:
          - name: file
            path: file.txt
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          with open("file.txt", "w") as file: file.write("heads")

    - name: tails
      outputs:
        artifacts:
          - name: file
            path: file.txt
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          with open("file.txt", "w") as file: file.write("tails")
  ttlStrategy:
    secondsAfterSuccess: 604800     # 7 days
    secondsAfterFailure:  604800    # 7 days

```

I get the following "stepresult" of flip-coin, as a consequence the Workflow executes neither heads or tails.
```
{file file.txt <nil> {<nil> &S3Artifact{S3Bucket:S3Bucket{Endpoint:,Bucket:,Region:,Insecure:nil,AccessKeySecret:nil,SecretKeySecret:nil,RoleARN:,UseSDKCreds:false,CreateBucketIfNotPresent:nil,EncryptionOptions:nil,},Key:my-artifacts/2023/10/24/conditional-parameter-np6zd/conditional-parameter-np6zd-flip-coin-actual-808394057/file.tgz,} nil nil nil nil nil nil nil nil} nil false false nil false}
```

As a work around, what I can do is execute a script that reads the artifact in another step and save check the results of that step. This works, but is cumborsome as it adds an additional pod. The reason why I want to include the artifact is because in one project the stdout is polluted with other text.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-parameter-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      Conditional parameters provide a way to choose the output parameters based on expression.

      In this example the step template has two steps which will run conditionally on `when`.

      Based on that condition, one of step will not be executed. The step template's output parameter will be
      set from the executed step's output.
    workflows.argoproj.io/version: '>= 3.1.0'
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: flip-coin
            template: flip-coin
        - - name: read-artifact
            template: read-artifact
            arguments:
              artifacts:
                - name: file
                  from: "{{steps.flip-coin.outputs.artifacts.file}}"
        - - name: heads
            template: heads
            when: '"{{steps.read-artifact.outputs.result}}" == "heads"'
        - - name: tails
            template: tails
            when: '"{{steps.read-artifact.outputs.result}}" == "tails"'
    - name: flip-coin
      outputs:
        artifacts:
          - name: file
            path: file.txt
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          import random
          with open("file.txt", "w") as file: 
            file.write("heads" if random.randint(0,1) == 0 else "tails")
    - name: read-artifact
      inputs:
        artifacts:
          - name: file
            path: file.txt
      script:
        image: alpine
        command: [ sh ]
        source: |
          cat file.txt
    - name: heads
      outputs:
        artifacts:
          - name: file
            path: file.txt
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          with open("file.txt", "w") as file: file.write("heads")

    - name: tails
      outputs:
        artifacts:
          - name: file
            path: file.txt
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          with open("file.txt", "w") as file: file.write("tails")
  ttlStrategy:
    secondsAfterSuccess: 604800     # 7 days
    secondsAfterFailure:  604800    # 7 days
```
