### DISCUSSION TITLE
[archived] "Manually Create ServiceAccount Secrets" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#12074] [General]
# argo-workflows/manually-create-secrets/

https://argoproj.github.io/argo-workflows/manually-create-secrets/

**Comment by SebastianGoeb** [comment]
The generated pod specs already have a projected token mount in them:
```yaml
  volumes:
    # ...
    - name: kube-api-access-58ntg
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          # ...
```
which seems to be the official way forward, if I understand K8s correctly. Apparently, we should all be using these projected volumes, whereby the token is taken directly from the API server and also rotated, instead of being persisted in a long-lived `Secret` and mounted from there.

However, if I specify a `serviceAccountName` and `executor.serviceAccountName` (which we need to do in order to authorize **only** the `main` container as a specific identity), then the pod spec also includes an "old fashioned" mount for `exec-sa-token`. Is that really necessary? I would have assumed that all ServiceAccount tokens can be handled via projected volume instead of secret mount.
