### DISCUSSION TITLE
workflows deleted immediately after completion due to `retentionPolicy`

### DISCUSSION THREAD

**Discussion by devstewart** [argoproj/argo-workflows#12082] [Q&A] [answered]
Running into an issue where unsuccessful wokflows are deleted immediately following completion.  I can't figure out what is causing this.  Is there anything in my `workflow-controller-configmap` which might be causing this to occur.  We recently upgraded to **v3.5.0**.

Any help is greatly appreciated.

Thanks

``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  artifactRepository: |-
    archiveLogs: true

    s3:
      endpoint: minio-endpoint.default
      bucket: prod
      insecure: false
      keyFormat: stage\
        /{{workflow.creationTimestamp.Y}}\
        /{{workflow.creationTimestamp.m}}\
        /{{workflow.creationTimestamp.d}}\
        /{{workflow.name}}\
        /{{pod.name}}"
      accessKeySecret:
        name: argo-minio-credentials
        key: accessKey
      secretKeySecret:
        name: argo-minio-credentials
        key: secretKey
  executor: |-
    imagePullPolicy: IfNotPresent
    image: cr/user/argoexec:3.5.0.282
  retentionPolicy: |-
    completed: 400
  workflowDefaults: |-
    spec:
      activeDeadlineSeconds: 86400
      podGC:
        strategy: OnPodSuccess

```
