### DISCUSSION TITLE
Access workflow template parameters from child resource

### DISCUSSION THREAD

**Discussion by brunocascio** [argoproj/argo-workflows#12177] [Q&A] [answered]
Hey everybody!

I'm working on an implementation where I have the following architecture:

```
Bitbucket Server --(webhook)--> WorkflowEventBinding --(invoke with event arguments)--> WorkflowTemplate --(create workflow from)<-- HTTP .argo-workflow.yml path (stored at bitbucket as well)
```

So the code is:

WorflowEventBinding:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: bitbucket-event-consumer
spec:
  event:
    selector: discriminator == "bitbucket-webhook"
  submit:
    metadata:
      generateName: "payload.repository.slug + '-' + first(payload.changes).ref.displayId + '-'"
      annotations:
        repo-url: "first(payload.repository.links.self).href"
        commit: "first(payload.changes).toHash"
      labels:
        initiator: "'true'"
        ref: "first(payload.changes).ref.displayId"
        repo-slug: "payload.repository.slug"
        project-key: "payload.repository.project.key"
    workflowTemplateRef:
      name: ci-workflow-template
    arguments:
      parameters:
        - name: repo_slug
          valueFrom:
            event: "payload.repository.slug"
        - name: project_key
          valueFrom:
            event: "payload.repository.project.key"
        - name: ref
          valueFrom:
            event: "first(payload.changes).ref.displayId"
        - name: repo_url
          valueFrom:
            event: "'https://bitbucket.example.com/scm/' + payload.repository.project.key + '/' + payload.repository.slug + '.git'"
        - name: commit
          valueFrom:
            event: "first(payload.changes).toHash"
        - name: previous_commit
          valueFrom:
            event: "first(payload.changes).fromHash"
        - name: workflow_http_uri
          valueFrom:
            event: "'https://bitbucket.example.com/projects/' + payload.repository.project.key + '/repos/' + payload.repository.slug + '/raw/.argo-workflow.yml?at=' + first(payload.changes).ref.displayId"
```

The WorkflowTemplate:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-workflow-template
spec:
  entrypoint: main
  templates:
    - name: main
      serviceAccountName: bitbucket
      inputs:
        parameters:
          - name: test
        artifacts:
          - name: workflow-definition
            path: ".argo-workflow.yml"
            http:
              url: "{{ workflow.parameters.workflow_http_uri }}"
              auth:
                basicAuth:
                  usernameSecret:
                    name: bitbucketserver-access
                    key: username
                  passwordSecret:
                    name: bitbucketserver-access
                    key: token
      resource:
        action: create
        manifestFrom:
          artifact:
            name: workflow-definition
```

And finally the .argo-workflow.yml file

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: "my-workflow-"
spec:
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      dag:
        tasks:
          - name: debug
            inline: 
              container:
                image: busybox
                command: ["echo"]
                args: ["{{workflow.parameters.commit}}"]
```

The problem here is the workflow failing to resolve "workflow.parameters.commit"

Is there any way to get this working? If I use `manifest` instead of `manifestFrom` and move the content of .argo-workflows.yml within the `manifest:` it works, but I would like to know if it's an known "issue", something by design or something that should be an issue.

Thanks in advance

**Comment by agilgur5** [comment, marked as answer]
> And finally the .argo-workflow.yml file

So this is the exact resource that gets created in Kubernetes. This resource has no `commit` argument, so the error is correct.

This is an independent resource, it does not know about another resource that happened to create it.
That's not an Argo behavior, that's a Kubernetes behavior.

**Reply by brunocascio** [reply]
So, how this task can be accomplished then?

**Reply by agilgur5** [reply]
If this is a common task, I would convert the `.argo-workflows.yml` into a `WorkflowTemplate` and then you can in-line a `Workflow` resource that references it.

You could also `submit` the Workflow to the Argo API, where you can add additional arguments separately ([example 1](https://argoproj.github.io/argo-workflows/workflow-submitting-workflow/), [example 2](https://github.com/argoproj/argo-workflows/discussions/8709#discussioncomment-5464505))

**Reply by brunocascio** [reply]
It's not "common" since every team will add its own ".argo-workflow.yml" file within the repo. Similar to github actions.

Due to the the limitation with http artifacts, I've switched to submit the workflow as following
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-workflow-template
spec:
  entrypoint: main
  templates:
    - name: main
      serviceAccountName: bitbucket
      volumes:
        - name: temp-data
          emptyDir: {}
      inputs:
        artifacts:
          - name: workflow-definition
            path: "/.argo-workflow.yml"
            http:
              url: "{{ workflow.parameters.workflow_http_uri }}"
              auth:
                basicAuth:
                  usernameSecret:
                    name: bitbucketserver-access
                    key: username
                  passwordSecret:
                    name: bitbucketserver-access
                    key: token
      container:
        image: argoproj/argocli:v3.5.1
        args:
          - submit
          - --strict=false
          - --labels=repo={{ workflow.parameters.repo_slug }},project={{ workflow.parameters.project_key }}
          - --parameter-file=/tmp/data/parameters.yml
          - /.argo-workflow.yml
        volumeMounts:
          - mountPath: /tmp/data
            name: temp-data
      initContainers:
        - name: parameters
          image: my-image/jqyq
          command: ["sh", "-c"]
          args:
            - |
              echo '{{ workflow.parameters.json }}' | jq -r 'map({(.name): .value}) | add' | yq e -P - | tee /tmp/data/parameters.yml
          mirrorVolumeMounts: true
      # resource:
      #   action: create
      #   manifestFrom:
      #     artifact:
      #       name: workflow-definition
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: bitbucket-event-consumer
spec:
  event:
    selector: discriminator == "bitbucket-webhook"
  submit:
    metadata:
      generateName: "payload.repository.slug + '-' + first(payload.changes).ref.displayId + '-'"
      annotations:
        repo-url: "first(payload.repository.links.self).href"
        commit: "first(payload.changes).toHash"
        ref: "first(payload.changes).ref.displayId"
        repo-slug: "payload.repository.slug"
        project-key: "payload.repository.project.key"
      labels:
        initiator: "'true'"
    workflowTemplateRef:
      name: ci-workflow-template
    arguments:
      parameters:
        - name: repo_slug
          valueFrom:
            event: "payload.repository.slug"
        - name: project_key
          valueFrom:
            event: "payload.repository.project.key"
        - name: ref
          valueFrom:
            event: "first(payload.changes).ref.displayId"
        - name: repo_url
          valueFrom:
            event: "'https://bitbucket.example.com/scm/' + payload.repository.project.key + '/' + payload.repository.slug + '.git'"
        - name: commit
          valueFrom:
            event: "first(payload.changes).toHash"
        - name: previous_commit
          valueFrom:
            event: "first(payload.changes).fromHash"
        - name: workflow_http_uri
          valueFrom:
            event: "'https://bitbucket.example.com/projects/' + payload.repository.project.key + '/repos/' + payload.repository.slug + '/raw/.argo-workflow.yml?at=' + first(payload.changes).ref.displayId"
```

but now I have a problem submitting the worklow, because the workflow itself reference some templates defined at `workflowDefaults.templates`Tried with `--strict=false` argument on `argo submit` but does not work either

**Reply by brunocascio** [reply]
Seting up templates within a `WorkflowTemplate` resource make the validations pass and it works. The only difference, the teams have to use this notation

```yaml
templateRef:
   template: my-template
   name: common-templates
```

instead of 

```yaml
template: my-template
```
