### DISCUSSION TITLE
output artifacts to wrong location

### DISCUSSION THREAD

**Discussion by aixi** [argoproj/argo-workflows#12240] [Q&A]
I have a yaml, works fine for me

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-map-reduce-
  namespace: maxcompute
  annotations:
    workflows.argoproj.io/description: |
    workflows.argoproj.io/version: '>= 3.0.0'
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: pdfBookObjKey
      value: "home/aixi/ebook/pdf_samples/test.pdf"
  templates:
  - name: main
    dag:
      tasks:
      - name: split-pdf
        template: split
        arguments:
          artifacts:
          - name: pdfBook
            oss:
              key: "{{workflow.parameters.pdfBookObjKey}}"
  - name: split
    inputs:
      artifacts:
      - name: pdfBook
        path: "/home/admin/data/book.pdf"
    outputs:
      artifacts:
      - name: pdfParts
        path: /mnt/out
        archive:
          none: {}
        oss:
          key: "home/aixi/argo_test/{{workflow.name}}/parts"
    container:
      image: my-registry/infly/pdf_functions:0.1
      command: [ "python3" ]
      args: ["argo_functions.py", "/home/admin/data/book.pdf"]
```
But if i move `oss` `key` field to main template, it's not working
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-map-reduce-
  namespace: maxcompute
  annotations:
    workflows.argoproj.io/description: |
    workflows.argoproj.io/version: '>= 3.0.0'
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: pdfBookObjKey
      value: "home/aixi/ebook/pdf_samples/test.pdf"
  templates:
  - name: main
    dag:
      tasks:
      - name: split-pdf
        template: split
        arguments:
          artifacts:
          - name: pdfBook
            oss:
              key: "{{workflow.parameters.pdfBookObjKey}}"
          - name: pdfParts
            oss:
              key: "home/aixi/argo_test/{{workflow.name}}/parts"
  - name: split
    inputs:
      artifacts:
      - name: pdfBook
        path: "/home/admin/data/book.pdf"
    outputs:
      artifacts:
      - name: pdfParts
        path: /mnt/out
        archive:
          none: {}
    container:
      image: my-private-registry/pdf_functions:0.1
      command: [ "python3" ]
      args: ["argo_functions.py", "/home/admin/data/book.pdf"]
```
the later yaml will send output to wrong location, not specify key
