### DISCUSSION TITLE
argo-events sensor fails to retry a workflow using workflow labels

### DISCUSSION THREAD

**Discussion by Nadine-H** [argoproj/argo-workflows#12289] [Q&A]
I'd like to use argo-events to retry a failed workflow. We already have an argo-events pipeline (source, event bus, sensor) to trigger workflows, and now I want to add the capability to retry a workflow using that pipeline.

Here's the portion of the sensor that is invoking the retry operation:

```yaml
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: retry
          args:
            - --selector
            - wf-id=test
            - -n
            - mynamespace
```

I'd like to use the workflow labels to identify the workflow (which is supported by the argo cli retry command). However, when the sensor receives the argo event, it complains: `failed to execute trigger, failed after retries: failed to execute the workflow retry operation, no name is given`. I thought the retry operation mirrors the argo cli retry, is that not the case? Or is something missing from my sensor?
