### DISCUSSION TITLE
Retrieve ENV values from container as Output params

### DISCUSSION THREAD

**Discussion by manju-rn** [argoproj/argo-workflows#12416] [Q&A] [answered]
As per the below, we can get the data of the file within the container as Output params.  **Can we also get the data of the ENV values which are in the container?**

```yaml
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["echo -n hello world > /tmp/hello_world.txt"]  # generate the content of hello_world.txt
    outputs:
      parameters:
      - name: hello-param  # name of output parameter
        valueFrom:
          path: /tmp/hello_world.txt 
```
