### DISCUSSION TITLE
Set label with day the workflow started

### DISCUSSION THREAD

**Discussion by jacek-jablonski** [argoproj/argo-workflows#12495] [Q&A] [answered]
Hi,
Is it possible to set the day that workflows started in workflow labels? F.e.: `workflowStartedAt: "2024-01-10"?

I was thinking about using `LabelValueFrom`: https://argo-workflows.readthedocs.io/en/latest/fields/#labelvaluefrom
But how to use it to set the date?

**Comment by agilgur5** [comment]
Modifying [the example](https://github.com/argoproj/argo-workflows/blob/a15587755e250fbbe3b9538b1c15ae581a108f0c/examples/label-value-from-workflow.yaml#L16) a bit with a different [variable](https://argo-workflows.readthedocs.io/en/latest/variables/#global):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: label-value-from-
spec:
  workflowMetadata:
    labelsFrom:
      workflowStartedAt:
        expression: workflow.creationTimestamp
# ...
```

**Comment by jacek-jablonski** [comment, marked as answer]
I finally did something like:
```yaml
  workflowMetadata:
    labelsFrom:
      started-at-epoch:
        expression: '{{= sprig.quote(sprig.unixEpoch(sprig.now())) }}'
```

Now, I'm able to filter by starting time using labels.
