### DISCUSSION TITLE
Error using Artifacts field functionality

### DISCUSSION THREAD

**Discussion by googs1025** [argoproj/argo-workflows#12576] [Q&A]
[doc](https://argo-workflows.readthedocs.io/en/latest/walk-through/artifacts/)

Hello everyone, I followed the documentation. The yaml file is as follows, but an error occurred. Can anyone know where the problem is?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
    - name: artifact-example
      steps:
        - - name: generate-artifact
            template: whalesay
        - - name: consume-artifact
            template: print-message
            arguments:
              artifacts:
                # bind message to the hello-art artifact
                # generated by the generate-artifact step
                - name: message
                  from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [sh, -c]
        args: ["cowsay hello world | tee /tmp/hello_world.txt"]
      outputs:
        artifacts:
          # generate hello-art artifact from /tmp/hello_world.txt
          # artifacts can be directories as well as files
          - name: hello-art
            path: /tmp/hello_world.txt

    - name: print-message
      inputs:
        artifacts:
          # unpack the message input artifact
          # and put it at /tmp/message
          - name: message
            path: /tmp/message
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["cat /tmp/message"]
```

```bash
[root@VM-0-13-centos argo-workflow]# argo list -nargo | grep pass
[root@VM-0-13-centos argo-workflow]# argo submit example-artifact.yaml -nargo
Name:                artifact-passing-pxtk4
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Pending
Created:             Fri Jan 26 10:08:05 +0800 (now)
Progress:
[root@VM-0-13-centos argo-workflow]# argo list -nargo | grep pass
artifact-passing-pxtk4    Running     3s    3s         0
[root@VM-0-13-centos argo-workflow]# kubectl get pods -nargo | grep pass
artifact-passing-pxtk4-whalesay-4125037285   0/2     Completed   0          19s
[root@VM-0-13-centos argo-workflow]# argo list -nargo | grep pass
artifact-passing-pxtk4    Failed      24s   10s        0          child 'artifact-passing-pxtk4-4125037285' failed

[root@VM-0-13-centos argo-workflow]# kubectl logs artifact-passing-pxtk4-whalesay-4125037285 -nargo
 _____________
< hello world >
 -------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
time="2024-01-26T02:08:13.391Z" level=info msg="sub-process exited" argo=true error="<nil>"
time="2024-01-26T02:08:13.391Z" level=info msg="/tmp/hello_world.txt -> /var/run/argo/outputs/artifacts/tmp/hello_world.txt.tgz" argo=true
time="2024-01-26T02:08:13.391Z" level=info msg="Taring /tmp/hello_world.txt"
```

Why doesn't workflow complete all steps?
