### DISCUSSION TITLE
Escape GO template when creating using the Workflow of workflow patterns

### DISCUSSION THREAD

**Discussion by fmbahrt** [argoproj/argo-workflows#12584] [Q&A]
Consider the following:

```
  - name: pull-request-template-callback
    inputs:
      parameters:
        - name: github-app-token
        - name: github-repo-url
        - name: github-repo-branch
        - name: workflowtemplatename
        - name: workflowtemplatetemplate
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: github-pr-callback-
        spec:
          podGc:
            strategy: OnPodSuccess
            deleteDelayDuration: 60s
          serviceAccountName: argo-workflow-vuln
          entrypoint: pr-callback
          templates:
            - name: pr-callback
              steps:
                - - name: clone-branch
                    templateRef:
                      name: github
                      template: clone-with-token
                    arguments:
                      parameters:
                        - name: app-token
                          value: "{{inputs.parameters.github-app-token}}"
                        - name: repo-url
                          value: "{{inputs.parameters.github-repo-url}}"
                        - name: repo-branch
                          value: "{{inputs.parameters.github-repo-branch}}"
                        - name: repo-path
                          value: "workflows"
                        - name: repo-depth
                          value: "1"
                - - name: do-callback-work
                    templateRef:
                      name: "{{ inputs.parameters.workflowtemplatename }}"
                      template: "{{ inputs.parameters.workflowtemplatetemplate }}"
                    arguments:
                      artifacts:
                        - name: workdir
                          from: "{{ {{ steps.clone-branch.outputs.artifacts.repo }} }}"
```

How do I properly escape the Go Template `{{ {{ steps.clone-branch.outputs.artifacts.repo }} }}` such that workflows doesnt try to resolve `steps.clone-branch.outputs.artifacts.repo` when applyting the template `pull-request-template-callback`?
