### DISCUSSION TITLE
Can I change the key of key only artifact in step instead of template?

### DISCUSSION THREAD

**Discussion by link89** [argoproj/argo-workflows#12606] [Q&A]
I am building a workflow have the form of  A -> B -> A -> B -> A -> B

What I hope is,  the first time I run step B its output artifact should use the key steps/b/iters/0, 
and the second time it should become steps/b/iters/1 and so on.

An idea way is all step B can share the same template and set their own artifact key. 
But I am not sure if it is possbile to do so as I don't see any example to config output artifact in Step

**Comment by agilgur5** [comment]
I mentioned in your [other discussion](https://github.com/argoproj/argo-workflows/discussions/12608#discussioncomment-8350639) but an example Workflow is really useful when asking questions. The issue templates require one, but unfortunately GitHub does not have discussion templates 😕

> An idea way is all step B can share the same template and set their own artifact key.

This sounds like a prime use-case for [parametrizing](https://argo-workflows.readthedocs.io/en/latest/walk-through/parameters/) your template. For instance, you could use `key` as an input parameter and then have your template use `{{inputs.parameters.key}}`.

**Comment by link89** [comment]
I am not sure if `parameterizing` is the right anwser. Here is an example, there are two steps using the same template, what I want is to put the file generated by the two steps to different key. 
 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: key-only-artifacts-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:

        - name: generate
          template: generate
          arguments:
            artifacts:
              - name: file
                s3:
                  key: my-file-01

        - name: generate
          template: generate
          arguments:
            artifacts:
              - name: file
                s3:
                  key: my-file-02

    - name: generate
      container:
        image: argoproj/argosay:v2
        args: [ echo, hello, /mnt/file ]
      outputs:
        artifacts:
          - name: file
            path: /mnt/file

```
