### DISCUSSION TITLE
Setting executor (wait) container resources in the WorkflowTemplate is counterintuitive/undocumented

### DISCUSSION THREAD

**Discussion by diversario** [argoproj/argo-workflows#12729] [Q&A] [answered]
I want to configure the default `wait` container to be very small, and adjust its resources, if necessary, from the WorkflowTemplates.

I have tried these approaches, after reading the docs:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
spec:
  podSpecPatch: |-
    {"containers": [{"name": "wait", "resources": {"requests": {"cpu": "51m", "memory": "128Mi"}, "limits": {"cpu": "51m", "memory": "128Mi"}}}]}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
spec:
  podSpecPatch: |-
    containers:
    - name: wait
      resources:
        requests:
          cpu: "51m"
          memory: "128Mi"
        limits:
          cpu: "51m"
          memory: "128Mi"
```

but the `wait` container was unaffected. The `wait` container is not defined in the workflow template, so the spec-level `podSpecPatch` seems to be the only place for the patch, but this worked:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
spec:
  templates:
  - name: image
    podSpecPatch: |
      initContainers:
      - name: init
        resources:
          requests:
            cpu: "53m"
            memory: "128Mi"
          limits:
            cpu: "54m"
            memory: "128Mi"
      containers:
      - name: wait
        resources:
          requests:
            cpu: "55m"
            memory: "129Mi"
          limits:
            cpu: "56m"
            memory: "129Mi"
    container:
      image: moby/buildkit:v0.11.6-rootless
    # the rest of the template
```

even though according to the [documentation](https://argo-workflows.readthedocs.io/en/latest/fields/#workflowspec), the correct place is `.spec.podSpecPatch` at the root of the WFT.

**Comment by jswxstw** [comment]
> even though according to the [documentation](https://argo-workflows.readthedocs.io/en/latest/fields/#workflowspec), the correct place is .spec.podSpecPatch at the root of the WFT.

`.spec.podSpecPatch` in the documentation is actually workflow-level `podSpecPatch`
`.spec.templates[0].podSpecPatch` is template-level `podSpecPatch`
https://github.com/argoproj/argo-workflows/blob/7286d499a60e38e226365ac0300571963379e00c/workflow/controller/workflowpod.go#L362-L383
Unfortunately, workflow-level `podSpecPatch` in `WorkflowTemplate` can not take effect.

**Reply by diversario** [reply]
Ah, I see. And, seems like it's the first WF in the WFT that should have the `podSpecPatch` for those default (`init`, `wait`) containers?..

**Reply by jswxstw** [reply]
Are you using `workflowTemplateRef` submitting WFT with workflow-level `podSpecPatch`?

**Reply by diversario** [reply]
Yes, these WFTs are used by the argo events sensors like:
```yaml
triggers:
- template:
    argoWorkflow:
      operation: submit
      source:
        resource:
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          spec:
            workflowTemplateRef:
              name: stuff
```
