### DISCUSSION TITLE
What conditions does `{{workflow.status}}` in ExitHandler use to determine success or failure?

### DISCUSSION THREAD

**Discussion by panicboat** [argoproj/argo-workflows#12768] [Q&A] [answered]
📝 https://argo-workflows.readthedocs.io/en/latest/variables/#exit-handler

Perform the following steps in the ExitHandler, and if one of the steps fails, the Workflow itself marks it as failed, but a successful step returns success.
Shouldn't the success or failure of the workflow itself be expected in the ExitHandler?

![image](https://github.com/argoproj/argo-workflows/assets/4182311/2457f593-807b-429a-904a-d3cf4aadc155)
![image](https://github.com/argoproj/argo-workflows/assets/4182311/433f62a5-3897-4b30-9380-cd116ead735f)
![image](https://github.com/argoproj/argo-workflows/assets/4182311/a5b15112-028a-4a48-9c02-5ddc262ef621)

```yaml
metadata:
  name: lovely-poochenheimer
  namespace: default
  labels:
    example: 'true'
spec:
  onExit: exit-handler
  entrypoint: argosay
  templates:
    - name: argosay
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - 'hello argo'
    - name: exit-handler
      steps:
      - - name: success
          template: success
        - name: failure
          template: failure
    - name: success
      steps:
      - - name: python-on-success
          inline:
            container:
              name: main
              image: public.ecr.aws/docker/library/python:alpine3.16
              command: ["python", -c]
              args: ["import random; import sys; exit_code = random.choice([0]); sys.exit(exit_code)"]
        - name: cowsay
          inline:
            container:
              name: main
              image: docker/whalesay
              command:
                - cowsay
              args:
                - "{{workflow.status}}"
    - name: failure
      steps:
      - - name: python-on-failure
          inline:
            container:
              name: main
              image: public.ecr.aws/docker/library/python:alpine3.16
              command: ["python", -c]
              args: ["import random; import sys; exit_code = random.choice([1]); sys.exit(exit_code)"]
```
