### DISCUSSION TITLE
How to treat `OCI runtime create failed` as a transient error

### DISCUSSION THREAD

**Discussion by panicboat** [argoproj/argo-workflows#12769] [Q&A] [answered]
We are using EKS + Karpenter.
In rare cases, I get the following error and the step fails
I set `TRANSIENT_ERROR_PATTERN` to `"(OCI runtime create failed)"` but it did not retry.
(I think the cause of the error is a bug in containerd, so I won't mention it.)
Is there any way to treat this error as OnTransientError and retry?

```console
StartError (exit code 128): failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/0/ns/ipc: no such file or directory: unknown
```

```console
StartError (exit code 128): failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: unable to freeze: unknown
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: argo
spec:
  template:
    spec:
      containers:
      - name: workflow-controller
        env:
        - name: TRANSIENT_ERROR_PATTERN
          value: "(OCI runtime create failed)"
```
