### DISCUSSION TITLE
[archived] "Hello World" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#12767] [General]
# en/latest/walk-through/hello-world/

https://argo-workflows.readthedocs.io/en/latest/walk-through/hello-world/

**Comment by worldsayshi** [comment]
Unfortunately docker/whalesay seems to be deprecated. I get this error when trying this Workflow:
```
Failed to pull image "docker/whalesay": [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/docker/whalesay:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```

**Reply by agilgur5** [reply]
Oh that must be a recent change in Docker; I ran this image yesterday.

It looks like it's indeed quite dated, last publish 9 years ago: https://hub.docker.com/r/docker/whalesay

Looks like there's an issue for this already: https://github.com/docker/whalesay/issues/6

**Reply by agilgur5** [reply]
Follow-up issue: #13388

**Comment by worldsayshi** [comment]
I found an alternative config that (sort of) works:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: argosay          # invoke the whalesay template
  templates:
    - name: argosay              # name of the template
      container:
        container:
        image: argoproj/argosay:v2
        args: [ echo, "hello" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
```

The created pod completes successfully and prints the message but I get this error on the Workflow:
```
Error node hello-world-dbrfg: Error (exit code 1): pods "hello-world-dbrfg" is forbidden: User "system:serviceaccount:default:default" cannot patch resource "pods" in API group "" in the namespace "default"
```
So it looks like this issue: https://github.com/argoproj/argo-workflows/issues/12733
