### DISCUSSION TITLE
How to set frequency for successCondition or failureCondition check?

### DISCUSSION THREAD

**Discussion by berna396** [argoproj/argo-workflows#12782] [Q&A]
Hi! 
I am trying to create a platform using EMR on EKS for computing and Argo Workflows as orchestrator. 

The connection is ok and the spark jobs work correctly, but when setting up a workflow that runs long sequential jobs the pod that argo creates ends up failing because it exceeds the rate limit of requests to the EMR API. 

Is there any way to modify the default frequency of the requests made with successCondition and failureCondition so that they are made every more time and thus not exceed the rate limit of EMR?

**Comment by agilgur5** [comment]
Can you provide a minimal Workflow as an example? `successCondition` and `failureCondition` can apply to various templates, so it's not clear what you're asking about. Did you mean an `http` template?

As far as I know, these conditions do not poll, they are only evaluated when there is a response to evaluate

**Comment by terrytangyuan** [comment]
Set the environment variable RESOURCE_STATE_CHECK_INTERVAL

**Reply by agilgur5** [reply]
Oh, for `resource` templates (if that is what OP is referring to), I thought it would do a `watch`, not a poll, but I guess not.

For reference, `RESOURCE_STATE_CHECK` is an [env var of the Executor](https://argo-workflows.readthedocs.io/en/latest/environment-variables/#executor)

**Reply by berna396** [reply]
I am using the helm chart and I modified the variables as follows to include that environment variable in the executor, but the poll is still done every 5s, is there something wrong?

```yaml
chart: argo-workflows
repoURL: 'https://argoproj.github.io/argo-helm'
targetRevision: 0.40.10
helm:
  releaseName: argo-workflows
  valuesObject:
    server:
      serviceType: ClusterIP
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    controller:
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    executor:
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: RESOURCE_STATE_CHECK_INTERVAL
          value: 20s
```
