### DISCUSSION TITLE
Using `withParam` with expressions

### DISCUSSION THREAD

**Discussion by omerlh** [argoproj/argo-workflows#12801] [Q&A]
Is it possible to use `withParam` with expressions?

Take this workflow for example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    name: testme
spec:
    entrypoint: javascript-script-example
    serviceAccountName: argo-workflow
    templates:
        - name: javascript-script-example
          steps:
              - - name: generate
                  template: gen-random-int
              - - name: print
                  template: print-message
                  arguments:
                      parameters:
                          - name: message
                            value: '{{item}}'
                  withParam: '{{=jsonpath(steps.generate.outputs.result, $..lines[*])}}'

        - name: gen-random-int
          script:
              image: node:20-alpine
              command: [node]
              source: |
                  const fs = require('fs');
                  const path = require('path');

                  console.log(JSON.stringify([{"lines": ["some-file.json"]}]))

        - name: print-message
          inputs:
              parameters:
                  - name: message
          container:
              image: alpine:latest
              command: [sh, -c]
              args: ['echo result was: {{inputs.parameters.message}}']
```

When running it I am getting the following error and I am not sure why:

```
withParam value could not be parsed as a JSON list: {{=jsonpath(steps.generate.outputs.result, $..lines[*])}}: invalid character '{' looking for beginning of object key string
```

Any pointers to how I can solve it?
