### DISCUSSION TITLE
en/latest/walk-through/sidecars/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#12826] [General]
# en/latest/walk-through/sidecars/

https://argo-workflows.readthedocs.io/en/latest/walk-through/sidecars/

**Comment by DominHa** [comment]
Does `command` always need to be passed in for sidecars? I am using a distroless nodejs image as a sidecar in a workflow and it doesn't come with a shell, can argo make the sidecar use the default entrypoint?

**Reply by agilgur5** [reply]
> Does `command` always need to be passed in for sidecars?

Why not try it out?

> I am using a distroless nodejs image as a sidecar in a workflow and it doesn't come with a shell

You don't need a shell to use `command`.
Also note that Argo itself uses distroless images.

**Reply by DominHa** [reply]
If I omit `command` for the sidecar I run into: `failed to look-up entrypoint/cmd for image "<image-name>", you must either explicitly specify the command, or list the image's command in the index`. If I add `command` back in, and just try to specify the same .js executable as in the Dockerfile (such as in the [official NodeJS distroless example](https://github.com/GoogleContainerTools/distroless/blob/main/examples/nodejs/Dockerfile)), then I run into `Error: failed to start command: fork/exec <executable>.js`. Is there a working example of how to do this properly with Argo workflows with a Dockerfile and matching Argo workflow yaml?

**Reply by agilgur5** [reply]
> If I omit `command` for the sidecar I run into:

Ok that's expected if it can't look up the Docker `ENTRYPOINT` -- in this case I believe it's in the base image.

> If I add `command` back in, and just try to specify the same .js executable as in the Dockerfile (such as in the [official NodeJS distroless example](https://github.com/GoogleContainerTools/distroless/blob/main/examples/nodejs/Dockerfile))

Perhaps a common point of confusion here with containers -- Docker's `ENTRYPOINT` is equivalent to k8s's `command` (and Docker `CMD` to k8s `args`). See also this [SO answer](https://stackoverflow.com/a/49658246/3431180) on the confusing terminology.

The [entrypoint of that image](https://github.com/GoogleContainerTools/distroless/tree/main/nodejs#usage) is `node`, so your k8s `command` should be `node` too.

> then I run into `Error: failed to start command: fork/exec <executable>.js`

Without `node` in front this error makes sense too.

**Comment by ktns** [comment]
Is there any way to make a side container in KEP753 style?

**Reply by agilgur5** [reply]
You might have to use `podSpecPatch` to specify an `initContainer`

**Reply by ktns** [reply]
Ah, I see. I'll give it a try, thanks!

**Reply by ktns** [reply]
It turned out it doesn't work at least with argo 3.4.5...

```
spec.initContainers[1].readinessProbe: Forbidden: may not be set for init containers without restartPolicy=Always
```

**Reply by agilgur5** [reply]
You didn't list what you tried or why you believe that's an Argo issue, but KEP753 sidecars [require](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/753-sidecar-containers/README.md#use-always-vs-new-enum-value) `restartPolicy: Always`, so that error sounds correct if you didn't set it.

**Reply by ktns** [reply]
I wrote a wf like this and got that error.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-kep753-pod-spec-patch
spec:
  entrypoint: main
  templates:
  - container:
      args:
      - "sleep 5"
      command:
      - sh
      - -c
      image: busybox
    initContainers:
    - image: cr.fluentbit.io/fluent/fluent-bit:2.1.8
      name: fluent-bit
      resources: {}
      volumeMounts:
      - mountPath: /fluent-bit/etc/
        name: fluent-bit-conf
    inputs: {}
    name: main
    podSpecPatch: |
      initContainers:
      - name: fluent-bit
        restartPolicy: Always
        readinessProbe:
          failureThreshold: 10
          periodSeconds: 1
          tcpSocket:
            port: 24224
    volumes:
    - configMap:
        items:
        - key: fluent-bit.conf
          path: fluent-bit.conf
        name: 'fluent-bit-config'
      name: fluent-bit-conf
```

I don't know it's an Argo issue or a k8s issue, but I wish a straight forward way to make KEP753 sidecars in argo API.
