### DISCUSSION TITLE
Is there a recommended way to use the suffix configMapGenerator name?

### DISCUSSION THREAD

**Discussion by panicboat** [argoproj/argo-workflows#12968] [Q&A]
## Assumptions

Argo Workflows manifests are kustomized and applied.

## What we want to do

I want to use the ConfigMap generated by `disableNameSuffixHash: false` in ConfigMapGenerator for each workflow.

## Things we are considering

https://github.com/kubernetes-sigs/kustomize/issues/2524
I'm considering the method in this Issue, but it doesn't seem to cover all use cases.

## Question

Is there a recommended way to write kustomization.yaml when using ConfigMap generated by ConfigMapGenerator?

**Comment by wesleyscholl** [comment]
@panicboat 

This is how we use the `ConfigMapGenerator` and `kustomization.yaml` in production with no issues to date. I created this example template for our engineering team.

```yaml
resources:
  - ./../base # Base manifest directory

patches:
  - path: patch-config.yaml # Patch files to be applied
  - path: patch-config-cron.yaml

namePrefix: production- # Prepends the name of the template with 'production-' in the prod environment

# If using containers or scripts
images:
  - name: container-image # Replace with your image name
    newName: abcxyz.azurecr.io/container-image # <image-url>/<container-image-name>
    newTag: latest-production # Tag to be applied

# If using ConfigMaps
configMapGenerator:
  - name: configmap-name # Replace with your configmap name
    literals:
      - val=1 # Replace with your key-value pair

generatorOptions:
  disableNameSuffixHash: true # Disables the hash suffix in the template name
```

References:
https://kubectl.docs.kubernetes.io/guides/config_management/secrets_configmaps/#configmapsgenerator
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/generatorOptions.md
https://pauldally.medium.com/kustomize-best-practices-part-2-c560f1fa1409
https://pauldally.medium.com/kustomize-best-practices-part-4-1ddf24e88c41
