### DISCUSSION TITLE
I want to use parameter with default value.

### DISCUSSION THREAD

**Discussion by jeongsik-woo** [argoproj/argo-workflows#12981] [Q&A] [answered]
Hi

I am beginner of argo workflow.

I created yaml like this.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: batch-dev
spec:
  workflowMetadata:
    labels:
      name: batch-dev
      stage: dev
  schedule: "0 */6 * * *"
  concurrencyPolicy: "Forbid"
  arguments:
    parameters:
      - name: forceGenerateCreatives
        value: false
      - name: uid
        value: ''
  workflowSpec:
    serviceAccountName: admin
    entrypoint: batch
    templates:
    - name: batch
      retryStrategy:
        limit: "2"
        retryPolicy: "Always"
      container:
        image: 'image_url'
        args: ["{{workflow.parameters.forceGenerateCreatives}}", "{{workflow.paramters.uid}}"]
```

and I try to start cron workflow on web-ui.

But it failed.  
![스크린샷 2024-04-25 오전 8 32 33](https://github.com/argoproj/argo-workflows/assets/121911412/9957dc1f-f944-4681-8ae8-a0acbe4ef3f1)

Can you figure out why this happened?

Also, I'm wondering if it's correct to always write the value of the parameter when submitting in web-ui, even though I set the default value in yaml.

And how can I set null for the default value?

**Comment by wesleyscholl** [comment, marked as answer]
@jeongsik-woo 

`arguments` and `parameters` are not in the `CronWorkflowSpec`.

https://argo-workflows.readthedocs.io/en/latest/fields/#cronworkflowspec

However, moving `arguments` and `parameters` inside `workflowSpec` and separating the `arguments` would work.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: batch-dev
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    serviceAccountName: admin
    entrypoint: batch
    arguments:
      parameters:
        - name: forceGenerateCreatives
          value: "false"
        - name: uid
          value: ""
    templates:
      - name: batch
        retryStrategy:
          limit: "2"
          retryPolicy: "Always"
        container:
          image: 'image_url'
          args:
            - "{{workflow.parameters.forceGenerateCreatives}}"
            - "{{workflow.parameters.uid}}"
```
https://argo-workflows.readthedocs.io/en/latest/fields/#workflowspec
