### DISCUSSION TITLE
withParams and artifacts passing

### DISCUSSION THREAD

**Discussion by 8th-block** [argoproj/argo-workflows#13008] [Q&A]
What is the best way to pass artifacts in the loop workflow?

```
          /--> parseFile1 ---> vectorizeFile1 --> ...
getFiles -
          \--> parseFile2 ---> vectorizeFile2 --> ...
```

I have no problem passing parameters in but when it comes to artifacts that does not work. The docs are sadly and I could not locate good samples for my use-case.

Error
unable to resolve references: Unable to resolve: "steps.parse-file.outputs.artifacts.parsed-file"

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: file-processing-
  namespace: jobs
spec:
  entrypoint: flow
  serviceAccountName: argo-workflow
  arguments:
    parameters:
    - name: files
      value: |
       [
        "sample_file_5MB.bin",
        "sample_file.bin"
       ]
  templates:
  - name: flow
    inputs:
      parameters:
      - name: files
    steps:
    - - name: parse-file
        template: parse-file
        arguments:
          parameters:
            - name: file
              value: "{{item}}"
        withParam: "{{inputs.parameters.files}}"
    - - name: vectorize-file
        template: vectorize-file
        arguments:
          artifacts:
            - name: file
              from: "{{steps.parse-file.outputs.artifacts.parsed-file}}"
          parameters:
            - name: file
              value: "{{item}}"
        withParam: "{{steps.parse-file.outputs.result}}"
  - name: parse-file
    inputs:
      parameters:
        - name: file
      artifacts:
        - name: file
          path: /tmp/files/{{inputs.parameters.file}}
          gcs:
            bucket: shr-docs
            key: "{{inputs.parameters.file}}"
    outputs:
        artifacts:
          - name: parsed-file
            path: /tmp/files/{{inputs.parameters.file}}
    container:
      image: debian
      command: [sh, -c]
      args:
        - |
          echo '"{{inputs.parameters.file}}"'
  - name: vectorize-file
    inputs:
      parameters:
        - name: file
      artifacts:
        - name: file
          path: /tmp/files/{{inputs.parameters.file}}
    outputs:
        artifacts:
          - name: processed-file
            path: /tmp/files/{{inputs.parameters.file}}
    container:
      image: debian
      command: [sh, -c]
      args:
        - |
          ls -a /tmp/files
```

Any pointers would be greatly appreciated
Cheers
Dmitry

<img width="1361" alt="Screenshot 2024-05-04 at 2 15 31 PM" src="https://github.com/argoproj/argo-workflows/assets/129127811/b9cbb85a-2064-4e27-8bd5-b22e777fedc7">
