### DISCUSSION TITLE
Overwrite Env vars for templateRef

### DISCUSSION THREAD

**Discussion by mohamed-atef2022** [argoproj/argo-workflows#13071] [Q&A]
i have a workflow called cleaner. Inside it i have env var `ENABLECLEANUP` with values ("Y" or "N")
i have another workflow (E2E) that have DAG which call the cleaner workflow 
my case that i need from UI when i try to run the E2E flow i can overwrite the env var in cleaner workflow so i can make the env var Y or N 

here is some content from Cleaner:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wft-pg-extract-cleaner

- name: ENABLECLEANUP
       #   value: "{{ .Values.postgres.dataExporter.envsInjection.enableCleanUp}}"
```

 here is the big workflow E2E:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wft-pg-data-exporter-cleaner-e2e
spec:
  entrypoint: pg-data-exporter-cleaner-e2e
  arguments:
    parameters:
    - name: ENABLECLEANUP
      value: "N"
dag:
      tasks:
      - name: pg-extract-cleaner
        templateRef:
          name: wft-pg-extract-cleaner
          template: pg-extract-cleaner
          arguments:
          parameters:
          - name: ENABLECLEANUP
            value: "{{`{{`}}workflow.parameters.ENABLECLEANUP{{`}}`}}"
```

!!! i tried to use the arguments & parameters is show in UI but it doesnt overwrite the env var
