### DISCUSSION TITLE
WorkflowTemplate main template arguments passing when using as templateRef

### DISCUSSION THREAD

**Discussion by paulfouquet** [argoproj/argo-workflows#13075] [Q&A]
Having this `WorkflowTemplate`:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wf-template-example
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: my_param
        value: 'default value'
  templates:
    - name: main
      dag:
        tasks:
          - name: my-task
            template: my-inner-template
    - name: my-inner-template
      container:
        image: 'my-image'
        command: [node, /app/index.js]
        args:
          [
            'my-command',
            '--param',
            '{{workflow.parameters.my_param}}',
          ]
```
It needs to be able to be called using the Argo web UI but also from another workflow as a `templateRef`:
```yaml
- name: my-template
  templateRef:
    name: wf-template-example
    template: main
  arguments:
    parameters:
      - name: my_param
        value: "my value"
```
The current implementation does not allow to pass the parameters from another workflow using it as `templateRef`.
The solution is to modify this workflow to add the parameter in the `main` template and passing them into the task `my-task`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wf-template-example
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: my_param
        value: 'default value'
  templates:
    - name: main
      inputs:
        parameters:
          - name: my_param
            value: '{{workflow.parameters.my_param}}'
      dag:
        tasks:
          - name: my-task
            template: my-inner-template
            arguments:
              parameters:
                - name: my_param
                  value: '{{inputs.parameters.my_param}}'
    - name: my-inner-template
      inputs:
        parameters:
          - name: my_param
      container:
        image: 'my-image'
        command: [node, /app/index.js]
        args:
          [
            'my-command',
            '--param',
            '{{inputs.parameters.my_param}}',
          ]
```
As you can see `my_param` has to be duplicated at several places now. I was wondering if this was the right solution?

Thank you
