### DISCUSSION TITLE
expressions and labels

### DISCUSSION THREAD

**Discussion by static-moonlight** [argoproj/argo-workflows#13121] [Q&A] [answered]
I don't know how this is supposed to be used. Kubernetes labels usually have the format `x/y=value`, with x often being a fq domain name.

An then there are the [workflow variables](https://argo-workflows.readthedocs.io/en/stable/variables/#global) `workflow.labels.<NAME>` and `workflow.labels.json`.

They don't seem to mix very well. How on earth is this supposed to be used to end up with a valid expression? The closest I got to work was this:

```yaml
- when: "{{ workflow.labels.x/y }} == 'value'"
```

And this only works when that label exists. If it doesn't exist (which in my case can happen):

```
 Bad Request: templates.my-workflow.tasks.my-task failed to resolve {{ workflow.labels.x/y )}}
```

or

```
Invalid 'when' expression [...]: Invalid token: '{{=' (hint: try wrapping the affected expression in quotes ("))
```

I also tried these:

- `when: "{{ workflow.labels['x/y'] )}} == 'value'"` (this should be possible, according to the [Argo documentation](https://argo-workflows.readthedocs.io/en/stable/variables/#expression))
- `when: "{{ workflow.labels.['x/y'] }} == 'value'"`
- `when: "{{ workflow.labels?.x/y}} == 'value'"`
- `when: "{{=jsonpath(workflow.labels, '$.x/y')}} == 'value'"`
- ... and lots of others ... (in brute force mode ... pure desperation/frustration ...)

So, how do I build a condition using `when` which checks if a Kubernetes label, which may or may not exists, has a specific value?

**Comment by agilgur5** [comment]
> `when: "{{ workflow.labels['x/y'] )}} == 'value'"` (this should be possible, according to the [Argo documentation](https://argo-workflows.readthedocs.io/en/stable/variables/#expression))

You're missing an equals sign -- try `when: "{{=workflow.labels['x/y'] == 'value'}}"`

No equals sign in `when` uses the legacy `govaluate` syntax, which does not work with the brackets, which are an `expr` syntax. See also #7831 and #7576. Per my last comment there (https://github.com/argoproj/argo-workflows/issues/7576#issuecomment-1728725234), would like to deprecate it, but there's several steps involved in that since it would break existing conditionals.

> * `when: "{{ workflow.labels?.x/y}} == 'value'"`
> * `when: "{{=jsonpath(workflow.labels, '$.x/y')}} == 'value'"`

This one is pretty confusing, detailed in https://github.com/argoproj/argo-workflows/issues/11549#issuecomment-1784882494. Basically Workflows often replaces the full, primitive variable and there are no data structures with "nested variables" -- i.e. I'm not sure if `workflow.labels` would even work, it may just replace `workflow.labels.mylabel`. Or it might work with `workflow.labels` as that's an array, but not with `workflow`, for instance.
I believe we can make this work with `expr` these days though; I think that logic predates `expr`'s usage. Also requires a non-trivial refactor.

**Reply by static-moonlight** [reply]
> You're missing an equals sign -- try when: "{{=workflow.labels['x/y'] == 'value'}}"

Thank you. I missed that one.

I got a little bit further, but not much. What I am trying to do is this:

```yaml
  metrics:
    prometheus:
      - name: status_warning
        help: workflow warnings
        when: "{{=workflow.labels['something/status']}} == warning"
        labels:
          - key: name
            value: some-name
        counter:
          value: "1"
```

Within my workflow there are multiple (dag) tasks, gathering data. Some of them can fail because the data is just not there, and nobody can do anything about it. It's considered to be a soft error, more like a warning. One part of making that visible, would be to just count them.

The easiest thing would be if I could just access the exit code of those (dag) task directly within the metrics `when` expression. But I don't see a way to actually to that here. So I am currently trying to just set a label to the workflow (basically flagging it into the warning state) and then check in the expression for the metric, if the counter needs to be updated or not.

However, the workflow controller still don't like that expression:

```
[...] level=error msg="unable to substitute parameters for metric 'result': failed to evaluate expression \"workflow.labels['something/status']\"" namespace=[...] workflow=[...]
```

What am I missing? do I still have some syntax error in here?

EDIT:

Alternatively, I was playing around with this:

```yaml
      - name: result
        help: workflow result
        labels:
          - key: name
            value: some-name
          - key: status
            value: "{{=workflow.labels['something/status']}} == 'warning' ? 'warning' : {{=lower(workflow.status)}}"
```

But again, the workflow controller doesn't like the expression `{{=workflow.labels['something/status']}}`

EDIT2: I think the expression, even if correct syntax-wise, fails when the label doesn't exit.

**Reply by agilgur5** [reply]
> ```yaml
>         when: "{{=workflow.labels['something/status']}} == warning"
> ```

Note that this is not quite the same as what I wrote; I wrapped the _entire_ expression in braces. That way it uses `expr` entirely. Whereas your variant uses _both_ `expr` _and_ legacy `govaluate`.

The way I wrote it was:
```yaml
when: "{{=workflow.labels['something/status'] == warning}}"
```

That might work better when the label doesn't exist, although I'm not 100% sure.




> The easiest thing would be if I could just access the exit code of those (dag) task directly within the metrics `when` expression.

Metrics do have [an `exitCode` variable](https://argo-workflows.readthedocs.io/en/latest/variables/#metrics). You didn't post your full Workflow though so I'm not sure if there's some other missing context

**Reply by static-moonlight** [reply]
> Note that this is not quite the same as what I wrote; I wrapped the _entire_ expression in braces. That way it uses `expr` entirely. Whereas your variant uses _both_ `expr` _and_ legacy `govaluate`.
> 
> The way I wrote it was:
> 
> ```yaml
> when: "{{=workflow.labels['something/status'] == warning}}"
> ```

Oh, right. I kind of missed that. I will try that.

> Metrics do have [an exitCode variable](https://argo-workflows.readthedocs.io/en/latest/variables/#metrics). You didn't post your full Workflow though so I'm not sure if there's some other missing context

That's true, for template-level metrics.

Technically I could implement that on template-level. However, the more global logic would be to either report the workflow as warning, or use the standard argo results (like "Succeeded" or "Failure"). That means, to avoid reporting a workflow twice (as warning on template level and error on workflow level) I still need the information about missing data for the workflow level metric (something like: "if task x reported missing data, then increase warning counter, otherwise increase <workflow.status> counter"). And there I can't seem to access the tasks exit code. That's why I'm using Kubernetes labels as a global variable to make that info available where I need it. I admit, it's hacky, and not entirely clean, it's pure desperation.

**Reply by agilgur5** [reply, marked as answer]
> That's why I'm using Kubernetes labels as a global variable to make that info available where I need it. I admit, it's hacky, and not entirely clean, it's pure desperation.

IMO, I would just report both and then do subtraction in your metrics queries if you really need to. That would be substantially less hacky and would make sense for metrics; they're all counters and some overlap

**Reply by static-moonlight** [reply]
In the end I did exactly that. It comes with a small inconvenience though. Since the missing-data metric is reported early, sometimes I end up with negative (-1) "other" failure causes. Not a big deal, but maybe I find a way to fix that.

![image](https://github.com/argoproj/argo-workflows/assets/107991124/4feb5d26-18c7-41d4-b2d5-e097a21e3513)

However, there is still a lot of inconsistency with expressions. Sometime they work. And when you put them somewhere else is suddenly does not.

Examples:

1. I couldn't get this to work for a task parameter in an exit handler:

```
{{=jsonpath(workflow.failures, '$.message')}}
```

... it just wasn't resolved at all. I just wanted to know if there a failures which indicate missing data. In the end I did this, because I could find a cleaner way to do it. Handling `workflow.failures` as json was just not possible.

```yaml
        tasks:
          - name: flag-missing-data
            templateRef:
              name: workflow-templates
              template: flag-missing-data
            arguments:
              parameters:
            when: "{{workflow.status}} in (Failed, Error) && {{=sprig.contains('exit code 123',workflow.failures)}} == true"
```

(even finding out how to use `sprig.contains` correctly was challenging)

2. Expressions in sensors behave completely different. In a sensor I can do this:

```yaml
            - dest: metadata.generateName
              src:
                dependencyName: my-dependency
                dataTemplate: 'create-{{ .Input.body.data.key | replace "." "-" }}-'
```

I don't understand why I don't need to use `{{=` here and apparently piping is working here as well. If I try to do that in Argo workflows I get some error.

I had a lot of wtf-moments with Argo expressions lately. Plus the documentation is often not helping. Enough to really get frustrated and trying to avoid expressions as best as possible. In some cases I even used workflow tasks to do little string manipulations and export the results as output parameters, because the expressions let me down.

**Generally speaking: I really wish the expressions would be more consistent across the board.**
