### DISCUSSION TITLE
custom metric with labels

### DISCUSSION THREAD

**Discussion by michal-sha** [argoproj/argo-workflows#13125] [Q&A]
Im trying to create a custom metric with 2 labels. The value for the labels should be taken from an output parameter.
The value of the metric should also taken from an output parameter.
I want to have 1 metric with all the combinations of both of the 2 labels.
For example,
```yaml
        - name: hana_defrag_nodes_drain_nodes_total
          help: "hana_defrag_nodes_drain_nodes_total help"
          labels:
            - key: zone
              value: {{`{{outputs.parameters.zone}}` | quote }}
            - key: group
              value: {{`{{outputs.parameters.group}}` | quote }}
          gauge:
            realtime: true
            value: {{`{{outputs.parameters.counter}}` | quote }}
```

Zone can have values like A, B ...
Group can have values like AA, BB...
            
I want to get a metric :
```
my_custom_metric{zone="A",group="AA"} 2
my_custom_metric{zone="A",group="BB"} 2
my_custom_metric{zone="B",group="AA"} 2
my_custom_metric{zone="B",group="BB"} 2
```
            
How should I do it?
What should be the format of the output parameter for label? txt, csv, json?
What should be the format of the output parameter for the metric value? txt, csv, json?
Is it possible to implement?

**Comment by static-moonlight** [comment]
Yes, that should be possible. I'm doing something similar. I also recommend, to keep the expressions as simple as possible. Only make them more complex if you really really have to.

```yaml
        - name: hana_defrag_nodes_drain_nodes_total
          help: "hana_defrag_nodes_drain_nodes_total help"
          labels:
            - key: zone
              value: "{{outputs.parameters.zone}}"
            - key: group
              value: "{{outputs.parameters.group}}"
          gauge:
            realtime: true
            value: "{{outputs.parameters.counter}}"
```

If possible, the output parameters could be simple values, like this:

- `outputs.parameters.zone` = `A`
- `outputs.parameters.group` = `AA`
- `outputs.parameters.counter` = `123`

Simple values makes everything easier. But in case you can't avoid having your task outputting a json structure ... lets assume with the name `outputs.parameters.json` and the following structure:

```json
{
  "zone": "A",
  "group": "AA",
  "counter": 123
}
```

... your metric could look like this:

```yaml
        - name: hana_defrag_nodes_drain_nodes_total
          help: "hana_defrag_nodes_drain_nodes_total help"
          labels:
            - key: zone
              value: "{{=jsonpath(outputs.parameters.json, '$.zone')}}"
            - key: group
              value: "{{=jsonpath(outputs.parameters.json, '$.group')}}"
          gauge:
            realtime: true
            value: "{{=jsonpath(outputs.parameters.json, '$.counter')}}"
```

Haven't tested this though, but it should work.
