### DISCUSSION TITLE
task `exitCode` variable not evaluated in loop

### DISCUSSION THREAD

**Discussion by almirmcunhajr** [argoproj/argo-workflows#13129] [Q&A]
**Argo Workflows version:** v3.5.7
 
Hi,
 
I am attempting to control the flow in a DAG based on the exit code of a task. However, it appears that the expressions are being evaluated incorrectly. Upon examining the logs of the workflow controller, I’ve noticed that the ExitCode in the Outputs of WorkflowTaskResult is consistently `nil`, regardless of the task:

```
workflow-controller-5ddc64df85-bvlfp workflow-controller time="2024-05-31T10:58:59.082Z" level=debug msg="task result:\n&WorkflowTaskResult{ObjectMeta:{actions-playground-cd-pqxcw-1791449257  argo-workflows  4cac5a5d-589c-4724-9eb1-b77822f5494a 1901039485 2 2024-05-31 10:58:30 +0000 UTC <nil> <nil> map[workflows.argoproj.io/report-outputs-completed:true workflows.argoproj.io/workflow:actions-playground-cd-pqxcw] map[] [{argoproj.io/v1alpha1 Workflow actions-playground-cd-pqxcw 2f60d1f0-3fe8-42ca-ab78-6d3e205f34c9 <nil> <nil>}] []  [{argoexec Update argoproj.io/v1alpha1 2024-05-31 10:58:37 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/report-outputs-completed\":{},\"f:workflows.argoproj.io/workflow\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"2f60d1f0-3fe8-42ca-ab78-6d3e205f34c9\\\"}\":{}}},\"f:outputs\":{}} }]},NodeResult:NodeResult{Phase:,Message:,Outputs:&Outputs{Parameters:[]Parameter{},Artifacts:[]Artifact{},Result:nil,ExitCode:nil,},Progress:,},}" namespace=argo-workflows workflow=actions-playground-cd-pqxcw
workflow-controller-5ddc64df85-bvlfp workflow-controller time="2024-05-31T10:58:59.082Z" level=debug msg="task result name:\nactions-playground-cd-pqxcw-1791449257" namespace=argo-workflows workflow=actions-playground-cd-pqxcw
workflow-controller-5ddc64df85-bvlfp workflow-controller time="2024-05-31T10:58:59.082Z" level=debug msg="Marking task result complete actions-playground-cd-pqxcw-1791449257" namespace=argo-workflows workflow=actions-playground-cd-pqxcw
workflow-controller-5ddc64df85-bvlfp workflow-controller time="2024-05-31T10:58:59.082Z" level=info msg="task-result changed" namespace=argo-workflows nodeID=actions-playground-cd-pqxcw-1791449257 workflow=actions-playground-cd-pqxcw
```

Also, it appears that the variable value is not being evaluated when it’s passed as a parameter:

```
❯ k logs actions-playground-cd-pqxcw-echo-container-139407922 
Exit code was: {{tasks.sync.exitCode}}
time="2024-05-31T10:58:51.501Z" level=debug msg="ignore signal child exited" argo=true
time="2024-05-31T10:58:52.501Z" level=info msg="sub-process exited" argo=true error="<nil>
```

These are the tasks that are being executed:
```yaml
- name: sync
  dependencies: 
    - wait-deploy-approval
  when: "'{{tasks.wait-deploy-approval.outputs.parameters.status}}' == 'merged'"
  continueOn:
    failed: true
  templateRef:
    name: argocd
    template: sync
  arguments:
    parameters:
      - name: application
        value: '{{workflow.parameters.application}}'
      - name: argocd-instance
        value: '{{item}}'
  withParam: '{{inputs.parameters.argocd-instances}}'
- name: echo-container
  dependencies:
    - sync
  template: echo-container
  arguments:
    parameters:
      - name: exitCode
        value: "{{tasks.sync.exitCode}}"
- name: notify-deploy-success
  dependencies: 
    - notify-deploy-init
    - sync
  when: "'{{tasks.sync.exitCode}}' == 0"
  templateRef:
    name: slack
    template: notify-deploy-phase
  arguments:
    parameters:
      - name: phase
        value: success
      - name: environment
        value: '{{inputs.parameters.environment}}'
      - name: version
        value: '{{workflow.parameters.version}}'
      - name: application
        value: '{{ workflow.parameters.application }}'
      - name: git-repo
        value: '{{workflow.parameters.git-repo}}'
      - name: channel
        value: '{{workflow.parameters.slack-channel}}'
      - name: approval-pr-number
        value: '{{tasks.promote-overlays.outputs.parameters.pr-number}}'
      - name: thread-ts
        value: '{{tasks.notify-deploy-init.outputs.parameters.thread-ts}}'
- name: revert
  dependencies: 
    - notify-deploy-init
    - sync
  when: "'{{tasks.sync.exitCode}}' != 0"
  template: revert
  arguments:
    parameters:
      - name: environment
        value: '{{inputs.parameters.environment}}'
      - name: commit-sha
        value: '{{tasks.promote-overlays.outputs.parameters.commit-sha}}'
      - name: pr-number
        value: '{{tasks.promote-overlays.outputs.parameters.pr-number}}'
      - name: argocd-instances
        value: '{{inputs.parameters.argocd-instances}}'
      - name: thread-ts
        value: '{{tasks.notify-deploy-init.outputs.parameters.thread-ts}}'
    artifacts:
      - name: src
        from: '{{inputs.artifacts.src}}'
```
