### DISCUSSION TITLE
Windows daemon container support

### DISCUSSION THREAD

**Discussion by jrbe228** [argoproj/argo-workflows#13146] [Q&A] [answered]
I'm able to run workflows with Linux [daemon ](https://argo-workflows.readthedocs.io/en/latest/walk-through/daemon-containers/)containers. However I'm struggling to run very similar Windows daemon containers. The only changes are nodeSelector, image, command, and path format for artifacts. 

Here is the sequence I see with Linux daemons: 
- Init container completes. 
- Wait and main (server) containers start. 
- Wait and main (server) containers terminate when the parent Workflow's client container has completed pinging the main (server) container. 

Using Windows containers, the wait and main containers remain stuck in Running: 
![image](https://github.com/argoproj/argo-workflows/assets/88258057/153a14b5-21d6-49ae-996d-c454ffbc263d)

Worse yet, deleting the workflow from Argo fails to remove the daemon's pod. The pod can only be removed by `kubectl -n argo delete pod mc-component-n28d7-mc-server-2163633914 --grace-period=0 --force`

Before going through the formal process of filing an Issue, is anyone aware of a working example of a Windows daemon container? Ideally a Windows test case should have been included when daemon container support was introduced to Argo.

**Comment by agilgur5** [comment]
> Ideally a Windows test case should have been included when daemon container support was introduced to Argo.

Other way around, daemon containers predate Windows support, which landed in #2747.
Windows doesn't have that many tests in general though, c.f. #12011 et al for unit tests. E2E tests would require being able to run Windows containers in CI as well.

Also Windows support was pretty much entirely contributed by @lippertmarkus and @mweibel, who may or may not be able to help.

I also just went through a bunch of PRs and issues to add a new [`area/windows` label](https://github.com/argoproj/argo-workflows/issues?q=label%3Aarea%2Fwindows) to help filter those.

**Comment by jrbe228** [comment]
Here is a reproducible example. The commented Linux nginx-daemon cleans up as expected. However the Windows nginx-daemon continues to run after workflow completion. Deleting the workflow from Argo *does* remove the daemon's pod in this case, but I'm not as lucky with some of our company's proprietary Windows daemons. Those pods fail to remove from k8s on workflow deletion. I imagine if all pods were properly terminated when the workflow completes, then Argo would have a better chance of removing them on workflow deletion. 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sidecar-nginx-
spec:
  entrypoint: sidecar-nginx-example
  templates:
  - name: sidecar-nginx-example
    steps:
      - - name: start-nginx
          template: nginx-daemon
      - - name: curl-nginx
          template: curl-container
          arguments:
            parameters:
              - name: nginx-ip
                value: "{{steps.start-nginx.ip}}"

#  - name: nginx-daemon
#    daemon: true
#    retryStrategy:
#      limit: 3
#    container:
#      name: nginx
#      image: nginx:1.13
#      command: [nginx, -g, "daemon off;"]
#    nodeSelector:
#      kubernetes.io/os: linux

  - name: nginx-daemon
    daemon: true
    retryStrategy:
      limit: 3
    container:
      name: nginx
      image: claudiubelu/nginx:1.15-1-windows-amd64-ltsc2022
      #image: claudiubelu/nginx:1.15-1-windows-amd64-1809
      #command: ["nginx", "-g", "daemon off;"]
    nodeSelector:
      kubernetes.io/os: windows

  - name: curl-container
    inputs:
      parameters:
        - name: nginx-ip
    container:
      image: appropriate/curl
      command: [sh, -c]
      args: ["until `curl -G 'http://{{inputs.parameters.nginx-ip}}/' >& /tmp/out`; do echo sleep && sleep 1; done && cat /tmp/out"]
    nodeSelector:
      kubernetes.io/os: linux
```

I may convert this Discussion to an Issue soon for better visibility.

**Reply by jrbe228** [reply]
A related problem - pending resolution of this issue, it would be extremely helpful to have a [workaround](https://stackoverflow.com/questions/78596030/how-to-access-pod-metadata-in-a-later-step-without-using-the-argo-daemon-contain). So far I've been unable to find one. 

Update - using this cleanup [workflow ](https://github.com/argoproj/argo-workflows/pull/13156)for now.

**Reply by jrbe228** [reply]
Separate topic. It appears there is another bug related to Argo Windows support. It became apparent during further testing of daemon containers, although the bug affects non-daemon containers also. For certain hybrid OS clusters, any workflow with artifacts becomes stuck during garbage collection and can't be deleted from the UI. 

Here is the sequence where I see the bug. 
1. Create k8s cluster (AKS v1.27.9) with 2 nodes:
UbuntuLinux, Standard_D8ads_v5
Windows2019, Standard_D8ads_v5
2. Install Argo Workflows
3. Run the below example `git-clone-and-share`
4. Attempt to delete workflow, triggering garbage collection
5. Observe a GC pod created. Its name includes the string `artgc-wfdel`. The GC pod is scheduled on a Windows node, due to the Linux node being a controller host. The Windows node is a pure worker node, therefore I assume preferred for scheduling tasks like GC. 
6. Pod image is `quay.io/argoproj/argoexec`, which is a multiplatform image. However it remains permanently stuck in ContainerCreating status with this message: 
```
MountVolume.SetUp failed for volume "kube-api-access-856sr" : chown
  c:\var\lib\kubelet\pods\1b542574-99e0-4507-88f4-ce5d0cf04704\volumes\kubernetes.io~projected\kube-api-access-856sr\..2024_06_09_19_27_11.2944197906\token:
  not supported by windows
```
 
 Here is the reproducible example: 
 ```yaml
 apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: git-clone-and-share
spec:
  entrypoint: main
  nodeSelector:
    kubernetes.io/os: linux
  artifactGC:
    strategy: OnWorkflowDeletion
  templates:
    - name: main
      steps:
        - - name: clone-repo
            template: git-clone
        - - name: use-repo
            template: process-repo
            arguments:
              artifacts:
                - name: repo
                  from: "{{steps.clone-repo.outputs.artifacts.repo}}"

    - name: git-clone
      script:
        image: alpine/git
        command: [sh]
        source: |
          git clone https://github.com/kilimchoi/engineering-blogs.git /workspace/repo
      outputs:
        artifacts:
          - name: repo
            path: /workspace/repo
      nodeSelector:
        kubernetes.io/os: linux

    - name: process-repo
      inputs:
        artifacts:
          - name: repo
            path: /workspace/repo
      script:
        image: alpine:latest
        command: [sh]
        source: |
          cd /workspace/repo
          # Perform actions on the cloned repo
          ls -la
      nodeSelector:
        kubernetes.io/os: linux
```
The `nodeSelector` is ignored for the GC pod, in spite of being repeated at Template and Workflow levels. 

Because the GC pod is permanently stuck, deleting the parent workflow fails to remove it. I once again find `kubectl delete --force ...` the workaround. For convenience, I'm using the same [script ](https://github.com/argoproj/argo-workflows/pull/13156)developed to workaround the Windows daemon bug above.

**Reply by agilgur5** [reply]
You can use `podSpecPatch` under `artifactGC` to set a `nodeSelector` (see also #12393)

**Reply by jrbe228** [reply]
Any tips on the syntax? I've tried the following: 
```yaml
  artifactGC:
    strategy: OnWorkflowDeletion
#    podSpecPatch: |
#      nodeSelector:
#        kubernetes.io/os: linux
#    podSpecPatch: |
#      {
#        "nodeSelector": {
#          "kubernetes.io/os": "linux"
#        }
#      }
#    podSpec:
#      nodeSelector:
#        kubernetes.io/os: linux
```
