### DISCUSSION TITLE
how to disable liveness probe for the argo controller?

### DISCUSSION THREAD

**Discussion by zhucan** [argoproj/argo-workflows#13179] [Q&A] [answered]
```yaml
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 6060
        scheme: HTTP
      initialDelaySeconds: 90
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 30
```
