### DISCUSSION TITLE
How to use volumes in WorkflowTemplate?

### DISCUSSION THREAD

**Discussion by zim32** [argoproj/argo-workflows#13192] [Q&A]
When I submit this WorkflowTemplate I got error `volume 'workspace' not found in workflow spec`:

```yaml
spec:
  templates:
    - name: entrypoint
      inputs:
        parameters:
          - name: image
        artifacts:
          - name: repo
            path: /home/container/workspace/repo
      outputs: {}
      metadata: {}
      containerSet:
        containers:
          - name: main
            image: '{{ inputs.parameters.image }}'
            command:
              - ls
            args:
              - '-la'
              - /home/container/workspace/repo
            resources: {}
          - name: composer-install
            image: '{{ inputs.parameters.image }}'
            command:
              - composer
            args:
              - install
            workingDir: /home/container/workspace/repo
            resources: {}
            securityContext:
              runAsUser: 8737
              runAsNonRoot: true
            dependencies:
              - main
        volumeMounts:
          - name: workspace
            mountPath: /home/container/workspace
  entrypoint: entrypoint
  arguments:
    parameters:
      - name: image
  serviceAccountName: argo
  volumes:
    - name: workspace
      emptyDir: {}
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

Is it possible to specify volumes in WorkflowTemplate? If not, what is the solution to this problem?
