### DISCUSSION TITLE
volumeClaimTemplates reference volume name as argument

### DISCUSSION THREAD

**Discussion by andrew-aiken** [argoproj/argo-workflows#13204] [Q&A]
Is there a way to reference the name of the PVC created with volumeClaimTemplates?

I'm looking to be able to pass it into a tasks (`{{volume.source-code.name}}`)
Preferably I would like to avoid having to create the PVC like shown in [this](https://argo-workflows.readthedocs.io/en/latest/walk-through/volumes/) (last example)

```yaml
spec:
  volumeClaimTemplates:
    - metadata:
        name: source-code
      spec:
        accessModes: ["ReadWriteOnce"]
        persistentVolumeReclaimPolicy: Delete
        storageClassName: gp2
        resources:
          requests:
            storage: 1Gi
```
