### DISCUSSION TITLE
Configuring SSO using Federated identity token

### DISCUSSION THREAD

**Discussion by tanvish-MS** [argoproj/argo-workflows#13218] [Q&A]
Hi all,
While configuring SSO on Argo server We need generally specify client id and client secret as shown below
```yaml
sso:  |
    issuer: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0
    issuerAlias: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0
    sessionExpiry: 5h
    clientId:
      name: client-cred
      key: client-id
    clientSecret:
      name: client-cred
      key: client-secret
    redirectUrl: https://azconductor-eval.southcentralus.cloudapp.azure.com/syseval/oauth2/callback
    scopes: []
    rbac:
      enabled: true
```
      
   Now instead of using client-secret to authorize to the service principal used for SSO. I need to use something else such as 
   - Certificate or
   - Federated Identity Credential
   
   How is it possible to do so ?
