### DISCUSSION TITLE
Can a WorkflowTemplate reference another WorkflowTemplate?

### DISCUSSION THREAD

**Discussion by almirmcunhajr** [argoproj/argo-workflows#13221] [Q&A]
I’ve tried to create a WorkflowTemplate that references another WorkflowTemplate, but it doesn’t seem to work.  When I submit it, It fails requiring me to provide an entrypoint. However, the cd WorkflowTemplate has an entrypoint configured.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: actions-playground-cd
spec:
  workflowTemplateRef:
    name: cd
  arguments:
    parameters:
      - name: slack-channel
        value: ""
```

**Comment by jorgelon** [comment]
can you paste the cd workflowtemplate?

**Reply by Joibel** [reply]
`WorkflowTemplateRef` only actually works from a Workflow or CronWorkflow as far as I know.

https://github.com/argoproj/argo-workflows/blob/main/docs/fields.md doesn't actually state this.

**Reply by almirmcunhajr** [reply]
Do you have any suggestions on how to reuse a WorkflowTemplate within another WorkflowTemplate? I prefer not to refer directly to a template within the WorkflowTemplate because I want to reuse specific workflow-level configurations, such as the exit handler. Additionally, I cannot grant the actions-playground-cd's service account permission to create Kubernetes resources, which means I can't create a Workflow resource that references the CD WorkflowTemplate.

**Comment by wesleyscholl** [comment]
@almirmcunhajr 

`workflowTemplateRef` only accepts the following fields:

| **Field Name**   | **Field Type** | **Description**                                                                 |
|-------------------|----------------|---------------------------------------------------------------------------------|
| `clusterScope`    | boolean        | Indicates the referred template is cluster scoped (i.e., a ClusterWorkflowTemplate). |
| `name`            | string         | The resource name of the workflow template.                                     |


However, `templateRef` can be used within `steps` or a `dag` to reference another `WorkflowTemplate`, specify the `entrypoint` and pass parameters. 

**Updated version of your `WorkflowTemplate`**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: actions-playground-cd
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
      - - name: cd-step
          templateRef:
            name: cd # Other WorkflowTemplate name
            template: main # Other WorkflowTemplate entrypoint
          arguments:
            parameters:
            - name: slack-channel
              value: ""
```

**Other `WorkflowTemplate` to call**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cd
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: slack-channel
      value: ""
  templates:
  - name: main
    inputs:
      parameters:
      - name: slack-channel
    container:
      image: busybox
      command: [echo]
      args: ["{{inputs.parameters.slack-channel}}"] 
```

**Resources**

- https://argo-workflows.readthedocs.io/en/latest/workflow-templates/#referencing-other-workflowtemplates
- https://argo-workflows.readthedocs.io/en/latest/fields/#templateref
- https://github.com/argoproj/argo-workflows/blob/main/examples/workflow-template/hello-world.yaml
- https://argo-workflows.readthedocs.io/en/latest/fields/#workflowtemplateref
