### DISCUSSION TITLE
Can you see workflowDefaults in the workflow runs?

### DISCUSSION THREAD

**Discussion by murraj** [argoproj/argo-workflows#13243] [Q&A] [answered]
I set up some defaults using workflowDefaults and they seem to be working.  When I kick off a workflow and then view the definition, the items set in workflowDefaults are not displayed as part of the workflow definition. Am I missing something? Seems like you would want to see the default values being used by a given workflow.

For example, here is the service account name default:

```yaml
workflowDefaults:
  spec:
    serviceAccountName: argo-argo-workflows-workflow-controller
```     

However, after kicking off a workflow and checking the workflow "definition", I don't see serviceAccountName:

```yaml
name: etl-test
inputs: {}
outputs: {}
metadata: {}
container:
  name: ''
  image: mytest.azurecr.io/etl/test:latest
  command:
    - python3
  args:
    - src/test.py
  resources: {}
```
