### DISCUSSION TITLE
inconsistent(?) metrics: `argo_workflows_count`

### DISCUSSION THREAD

**Discussion by static-moonlight** [argoproj/argo-workflows#13249] [Q&A]
The metric `argo_workflows_count`, provided by the `/metrics` endpoint is not consistent with the current state of my Argo Workflows instance and what the user interface shows:

```
# HELP argo_workflows_count Number of Workflows currently accessible by the controller by status (refreshed every 15s)
# TYPE argo_workflows_count gauge
argo_workflows_count{status="Error"} 1
argo_workflows_count{status="Failed"} 47
argo_workflows_count{status="Pending"} 0
argo_workflows_count{status="Running"} 6
argo_workflows_count{status="Succeeded"} 1059
```

![image](https://github.com/argoproj/argo-workflows/assets/107991124/678fa8ab-3c91-4885-bfee-f9f25eb0de09)

I would expect that the metrics and the values in the user interface are identical (aside from a 15 sec delay). Technically speaking: that the values come from the same origin.

relevant part of my config:

```yaml
metricsConfig:
  enabled: true
  path: /metrics
  port: 9090
persistence:
  archive: false
  connectionPool:
    maxIdleConns: 100
    maxOpenConns: 0
    connMaxLifetime: 0s
  nodeStatusOffLoad: true
  postgresql:
    host: database.argo
    port: 5432
    database: argo
    [...]
artifactRepository:
  s3:
    [...]
workflowDefaults:
  spec:
    ttlStrategy:
      [...]
```

What am I missing?
