### DISCUSSION TITLE
Fetching id in dex config for `staticClients` from ENV (as Secrets)

### DISCUSSION THREAD

**Discussion by sahil-sharma** [argoproj/argo-workflows#13247] [Q&A]
We are aware that the `id` in dex config for `staticClients` would be the actual client-ID from OIDC provider in plain-text format (in `XXXXX..apps.googleusercontent.com` format). The code block would look like this ([link](https://argo-workflows.readthedocs.io/en/stable/argo-server-sso-argocd/#example-helm-chart-configuration-for-authenticating-against-argo-cds-dex) to official doc):
```yaml
    dex.config: |
       staticClients:
       - id: XXXXX..apps.googleusercontent.com
        name: Argo Workflow
        redirectURIs:
        - https://argo-workflows.mydomain.com/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```
We tried to fetch this `id` from an ENV (mounted as a secret using External Secret) in the below format but it failed:
```yaml
     dex.config: |
       staticClients:
       - id: $argo-workflows-sso:client-id
        name: Argo Workflow
        redirectURIs:
        - https://argo-workflows.mydomain.com/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```
ExternalSecret is defined as:
```yaml
<redacted-code-block>

    data:
        client-id: '{{ index . "CLIENT-ID" }}'

<redacted-code-block>

 data:
    - secretKey: CLIENT-ID
      remoteRef:
        key: "arn:aws:secretsmanager:eu-west-1:XXXXXXXX:secret:production/argo-workflows/dex-token-abcABC"
        property: client-id
```

Is there any way to get this value instead of hardcoding it in the code and pushing it to the GH?

Any hints/suggestions would be highly appreciated!

**Comment by agilgur5** [comment]
This sounds like a pure Dex question rather than an Argo question.

You need to create another environment variable that holds your client ID.

The configuration already has:
```yaml
     dex:
       env:
         - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
           valueFrom:
             secretKeyRef:
               name: argo-workflows-sso
               key: client-secret
```

you can add _another_ environment variable to represent your client ID:
```yaml
         - name: ARGO_WORKFLOWS_SSO_CLIENT_ID
           valueFrom:
             secretKeyRef:
               name: argo-workflows-sso
               key: client-id
```

and then you can use it within your config:
```yaml
     dex.config: |
       staticClients:
       - id: $ARGO_WORKFLOWS_SSO_CLIENT_ID
        name: Argo Workflow
        redirectURIs:
        - https://argo-workflows.mydomain.com/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```

with [`$` reading from the environment variables](https://github.com/dexidp/dex/blob/17a9c1c2429901ce962ce6dda3711e35ab33bdf0/examples/config-dev.yaml#L145) as you seem to be aware of already
