### DISCUSSION TITLE
Access token/Security Docs do not provide working example for API access

### DISCUSSION THREAD

**Discussion by jamiro24** [argoproj/argo-workflows#13257] [Q&A] [answered]
Hi all,

I've been trying to get any kind of API access using a service account token on my local k3d cluster. I installed v3.5.8 of argo workflows and
I have been following the [Access token](https://argo-workflows.readthedocs.io/en/latest/access-token/) and [Security](https://argo-workflows.readthedocs.io/en/latest/security/) section in the docs, but following these did not lead to working results.

My goal was to access the following API endpoint: `https://localhost:2746/api/v1/workflows/dev` using a service account's secret token.

I've set up the service account using the following script:
```shell
kubectl create namespace dev
kubectl create sa -n dev tb
kubectl apply -n dev -f argo-role.yaml
kubectl create rolebinding argo --serviceaccount dev:tb --role argo
kubectl apply -n dev -f token.yaml
kubectl get secret -n dev tb.service-account-token -o=jsonpath='{.data.token}' | base64 --decode
```

argo-role.yaml
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo
rules:
  # k8s standard APIs
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  # Argo APIs. See also https://github.com/argoproj/argo-workflows/blob/main/manifests/cluster-install/workflow-controller-rbac/workflow-aggregate-roles.yaml#L4
  - apiGroups:
      - argoproj.io
    resources:
      - eventsources
      - sensors
      - workflows
      - workfloweventbindings
      - workflowtemplates
      - clusterworkflowtemplates
      - cronworkflows
      - cronworkflows
      - workflowtaskresults
    verbs:
      - get
      - list
      - watch
```
role-binding.yaml
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: transformation-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo
subjects:
- kind: ServiceAccount
  name: tb
  namespace: dev
```

token.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: tb.service-account-token
  annotations:
    kubernetes.io/service-account.name: tb
type: kubernetes.io/service-account-token
```

Then when I try to access the aforementioned endpoint using the token obtained by the script I get the following response:

```
{
    "code": 7,
    "message": "Permission denied, you are not allowed to list workflows in namespace \"dev\". Maybe you want to specify a namespace with query parameter `.namespace=dev`?"
}
```

This response was not helpful at all, however after downgrading argo workflows to v3.5.4 and sending the same request I got the following response

```
{
    "code": 7,
    "message": "workflows.argoproj.io is forbidden: User \"system:serviceaccount:dev:tb\" cannot list resource \"workflows\" in API group \"argoproj.io\" in the namespace \"dev\": RBAC: role.rbac.authorization.k8s.io \"dev:argo\" not found"
}
```

This lead me to change the role the following (Only changing metadata.name to `dev:argo` instead of `argo`) and suddenly
my API calls were accepted.
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev:argo
rules:
  # k8s standard APIs
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  # Argo APIs. See also https://github.com/argoproj/argo-workflows/blob/main/manifests/cluster-install/workflow-controller-rbac/workflow-aggregate-roles.yaml#L4
  - apiGroups:
      - argoproj.io
    resources:
      - eventsources
      - sensors
      - workflows
      - workfloweventbindings
      - workflowtemplates
      - clusterworkflowtemplates
      - cronworkflows
      - cronworkflows
      - workflowtaskresults
    verbs:
      - get
      - list
      - watch
```
```shell
kubectl create namespace dev
kubectl create sa -n dev tb
kubectl apply -n dev -f argo-role.yaml
kubectl create rolebinding argo --serviceaccount dev:tb --role dev:argo
kubectl apply -n dev -f token.yaml
kubectl get secret -n dev tb.service-account-token -o=jsonpath='{.data.token}' | base64 --decode
```

I wanted to report this because this has been an extremely painful experience that cost me a lot of time. 
I believe the docs are lacking clarity on how to set up API access. Both the api/accces token and security sections of the docs provide examples that do not produce working results and the errors I got in the latest published version did not help either.

I still do not understand why I had to prepend my role's name with `dev:` for it to work as I cannot find any mention of this in the docs.

I think the examples in the docs should be improved. Given that I am a new user of this project I do not know whether the error message I got on v3.5.8 is intended, but the error message I got in v3.5.4 was much clearer and actually led to me solving my issue.
