### DISCUSSION TITLE
How to reset exit handler after retry?

### DISCUSSION THREAD

**Discussion by vsernatsky-h1** [argoproj/argo-workflows#13264] [Q&A]
We have a workflow template for testing purposes, so it fails a lot and we actively use `argo retry`. This template also has a `spec.onExit` handler to notify its state (we also tried `spec.hooks.exit`). The problem is that retry doesn't reset this handler, it is triggered only after the first run (fail or success) and remains successfully finished each retry. We tried retrying it using `--node-field-selector` but it triggers the handler immediately.

Argo version is v3.4.1

The template is something like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
spec:
  templates:
    - name: main
      dag:
        tasks: ...
    - name: finish-job
      steps:
        - - name: send-notification
            arguments:
              parameters: ...
            templateRef:
              name: send-slack
              template: send-completion
  entrypoint: main
  arguments: ...
  onExit: finish-job
```
