### DISCUSSION TITLE
Docker Entrypoint overridden by k8s `command`

### DISCUSSION THREAD

**Discussion by Nataliia5722** [argoproj/argo-workflows#13298] [Q&A] [answered]
Hi Team!

Could you, please, advise? Is there any way to not duplicate the entrypoint that was specified in Dockerfile. 

Sample example of Dockerfile:

```dockerfile
FROM ubuntu:14.04

ENTRYPOINT ["echo", "Hello"]
```

Sample workflow:

```yaml
metadata:
  name: test
  namespace: argo-workflows
spec:
  entrypoint: test
  templates:
    - name: test
      container:
        name: main
        image: <custom_image>
        command:
          - "World"
```

Getting the error:
```
Error (exit code 64): failed to find name in PATH: exec: "World": executable file not found in $PATH
```

Why it's not recognizing the "echo", "Hello" entrypoint from Docker image? What can be done to make it work?

**Comment by agilgur5** [comment, marked as answer]
I think you've fallen into a common misunderstanding of the Docker vs. k8s terminology. [Docker's `ENTRYPOINT` is equivalent to k8s's `command`](https://stackoverflow.com/a/49658246/3431180), and Docker's `CMD` is equivalent to k8s's `args`.

The terminology is unfortunately pretty confusing so this happens quite often.
To be explicit, that's not an Argo error or specific to Argo, that's just Kubernetes functionality. If you run a plain `Pod` in Kubernetes with that image and that `command`, you'll get the same error

So your `command: - "World"` is actually _overriding_ your `ENTRYPOINT ["echo", "Hello"]`. If you want to print "Hello World", you probably want to use `args` and _not_ `command`:
```yaml
        args:
          - "World"
```

**Reply by Nataliia5722** [reply]
Thanks a lot!
Yes, was setting as `args` first, but as a `command` is required, what value should be set to not override the `ENTRYPOINT ["echo", "Hello"] `?

**Reply by agilgur5** [reply]
`command` [shouldn't be required](https://argo-workflows.readthedocs.io/en/release-3.5/workflow-executors/#image-indexcache) if you have an `ENTRYPOINT` and are using an up-to-date image manifest (v2).
Are you getting an Emissary error without `command`? If the `docker image inspect` command on [this doc page](https://argo-workflows.readthedocs.io/en/release-3.5/workflow-executors/#emissary-emissary) can get the entrypoint, then you should have an up-to-date manifest. (v1 is pretty old at this point, so if all your tools are up-to-date, they should create v2 manifests by default)

But to answer the question, you'd set the `command` to be equivalent to `ENTRYPOINT` then, i.e.:
```yaml
        command:
          - echo
          - "Hello"
        args:
          - "World"
```
You'd still be overriding it, to be clear, just with the same value.
