### DISCUSSION TITLE
mark a workflow run as `Succeeded` even if task fails

### DISCUSSION THREAD

**Discussion by PerfiX** [argoproj/argo-workflows#13300] [Q&A]
Is there a way to mark a workflow run as "Succeeded", even if a step in the workflow has failed?

I use a dag workflow that executes different steps depending on the exit code (like `when: "{{tasks.step3-dump.exitCode}} == 11"`). 
The behavior is absolutely correct. However, the entire workflow is always displayed as "Failed".

Because I use `depends` to control the workflow, I cannot use `continueOn`.

Does anyone have an idea?

**Comment by Joibel** [comment]
Can you use [enhanced depends](https://argo-workflows.readthedocs.io/en/stable/enhanced-depends-logic/) along with `continueOn` to do what you want?

**Comment by PerfiX** [comment]
Thanks for your quick reply!

Unfortunately this does not work for me. I have a step that returns exit code 11 every now and then, which is correct.

From your link: 
> `dag.task.continueOn` is not available when using `depends`; instead you can specify `.Failed`.


Here is a small excerpt from the workflow:
```yaml
         - name: step3-dump
          depends: step1-prepare
          templateRef:
            name: dump-template
            template: dump
        - name: handle-exit-code
          depends: step3-dump.Failed
          templateRef:
            name: handle-exit-code-template
            template: handle-exit-code
          when: "{{tasks.step3-dump.exitCode}} == 11"
        - name: step4-rsync
          depends: "step3-dump"
          templateRef:
            name: rsync-template
            template: rsync
            when: "{{tasks.step3-dump.exitCode}} == 0"
```

The last step is "Succeeded" and the workflow is running perfectly. 

But unfortunately the workflow is always displayed as failed.

![image](https://github.com/argoproj/argo-workflows/assets/124691032/44aadedb-67cf-4edc-b45f-43745678734e)
