### DISCUSSION TITLE
Add prefix to workflow pod names for filtering metrics

### DISCUSSION THREAD

**Discussion by ecurbelo** [argoproj/argo-workflows#13323] [Q&A]
Summary
---
Can we add a prefix to the pods names launched by the Workflows?

We tried to set some extra configuration on a custom [workflow-controller-configmap ](https://github.com/argoproj/argo-workflows/blob/a514a42/test/e2e/manifests/mixins/workflow-controller-configmap.yaml), trying for example to use `podSpecPatch` in `workflowDefaults` , but with unsuccessful results.

Motivation
---
The workflow pods finish in a Failed state in different situations, e.g. an error on the `WorkflowTemplate` manifest. We want to exclude these pods from the [KubePodNotReady](https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubepodnotready/) Prometheus Alert that we have in place. So, our first approach is adding a prefix on the pods names.

Our second approach could be maybe launching these pods in another namespace, but this is a "migration" task that we would like to avoid.

Also, we would want to avoid passing labels to the prometheus metrics to control our cardinality.

Extra notes
---
We also added the Role and RoleBinding needed to patch the pods:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-patch-role
  namespace: argo
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-patch-rolebinding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
roleRef:
  kind: Role
  name: argo-patch-role
  apiGroup: rbac.authorization.k8s.io
```

kube-prometheus-stack KubePodNotReady expression:
```
sum by (namespace, pod, cluster) (max by (namespace, pod, cluster) (kube_pod_status_phase{job="kube-state-metrics",namespace=~".*",phase=~"Pending|Unknown|Failed"}) * on (namespace, pod, cluster) group_left (owner_kind) topk by (namespace, pod, cluster) (1, max by (namespace, pod, owner_kind, cluster) (kube_pod_owner{owner_kind!="Job"}))) > 0
```

Thanks!
