### DISCUSSION TITLE
Using expressions in `workflowMetadata.labelsFrom` value

### DISCUSSION THREAD

**Discussion by ni-todo-spot** [argoproj/argo-workflows#13357] [Q&A] [answered]
Hey all!,

Based on this example: https://github.com/argoproj/argo-workflows/blob/main/examples/label-value-from-workflow.yaml
I was wondering if I can mutate the expression being used as value for the label.

Example: WF parameter was "hello\world". running the WF with such value will cause an error.
So instead, I'd like to use template functions to adjust the original value to a valid one so eventually I'd be able to set a label for "hello-world".

Anyway I can achieve such thing? if no - Can we open a feature request for it?

Thanks in advance!

**Comment by agilgur5** [comment, marked as answer]
Yes, the `expression` field supports all functions available to [Argo expressions](https://argo-workflows.readthedocs.io/en/release-3.5/variables/#expression).

**Reply by ni-todo-spot** [reply]
@agilgur5 thx for your reply!
I've tried using this workflow and could not make it work:

```yaml

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: label-value-from-
spec:
  arguments:
    parameters:
      - name: foo
        value: bar/baz
  workflowMetadata:
    labelsFrom:
      foo:
        expression: 'replace(workflow.parameters.foo, "//", "__")'
  entrypoint: main
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2

```

Can u please tell me what did I do worng?

Thanks 🙏
