### DISCUSSION TITLE
Access workflow parameters inside JavaScript code

### DISCUSSION THREAD

**Discussion by anup-krai** [argoproj/argo-workflows#13427] [Q&A]
Hi,

I am trying to access Workflow parameters inside a Javascript file like below -

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-parameter-
spec:
  arguments:
    parameters:
      - name: app_name
        value: applicationName
      - name: item_name
        value: 'name of the item'

  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 64Mi

  entrypoint: execute
  templates:
    - name: execute
      steps:
      - - name: execute
          template: execute

    - name: execute
      container:
        image: node:9.1-alpine
        workingDir: /src
        command: [sh, -c]
        args: [ "node ./inputparameters.js {{workflow.parameters.json}}" ]
        volumeMounts:
        - name: work
          mountPath: /src
```
Below is the JS code (inputparameters.js) -

```js
const { argv } = require('node:process');

console.log("process.argv -", argv)
console.log("JSON argv -",JSON.parse(argv))
```
I am getting below output -
```
process.argv - [
  '/usr/local/bin/node',
  '/src/inputparameters.js',
  '[{name:app_name,value:applicationName},{name:item_name,value:name of the item}]'
]

SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
```
Here first console log is printing the output with three parameters which is correct and the workflow parameters are coming as string in the 3rd parameter. When I trying to parse it to JSON its throwing errors because its not correctly formatted. Name and values are without quotes.

Is there a better way to access the variables inside the code for example like below -
`var app_name = process.env.app_name`
