### DISCUSSION TITLE
Problems with using ingress as an ssl offloader

### DISCUSSION THREAD

**Discussion by ForcemCS** [argoproj/argo-workflows#13432] [Q&A]
I am in the process of deploying Argo workflow and my resources are listed below. When I visit https://workflow.threshold.com/ in my browser there is no response
```yaml
# root@master01:~/v1.30/11-argo/argo-workflows# kubectl -n workflow  get deployments.apps  argo-workflows-server -o yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
...
    spec:
      containers:
      - args:
        - server
        - --configmap=argo-workflows-workflow-controller-configmap
        - --secure=false
        - --loglevel
        - info
        - --gloglevel
        - "0"
        - --log-format
        - text
        env:
        - name: IN_CLUSTER
          value: "true"
        - name: ARGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: BASE_HREF
          value: /
        image: quay.io/argoproj/argocli:v3.5.10
        imagePullPolicy: Always
...
```
My ingress is as follows (vault self-signed certificate)
```yaml
# root@master01:~/v1.30/11-argo/argo-workflows# kubectl   -n workflow  get  ingress  argo-workflows-server -oyaml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  name: argo-workflows-server
  namespace: workflow

spec:
  ingressClassName: nginx
  rules:
  - host: workflow.threshold.com
    http:
      paths:
      - backend:
          service:
            name: argo-workflows-server
            port:
              number: 2746
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - workflow.threshold.com
    secretName: workflow-threshold-com
```
