### DISCUSSION TITLE
`Failed to connect to MSI, check your managed service identity id.` error when trying to use Microsoft Entra Workload ID in Workflow

### DISCUSSION THREAD

**Discussion by gunjansawhney** [argoproj/argo-workflows#13434] [Q&A] [answered]
Seeking guidance on how to use Microsoft Entra Workload ID with Argo Workflows. Specifically, I want to allow pods created in the Argo Workflow steps to authenticate with Azure using a workload identity. I have tried using service accounts and creating secret from it, but it seems to be failing. Below is the workflow template I am using. Could someone please assist me or share their experience if they have worked on this issue?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: managed-identity-workflow-
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: managed-identity-account-test
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: run
        template: azure-step

  - name: azure-step
    container:
      image: mcr.microsoft.com/azure-cli
      command: ["/bin/sh", "-c"]
      args: ["sleep 10 && echo $AZURE_CLIENT_ID && sleep 300 && az login --identity --username $AZURE_CLIENT_ID && az group list"]
      env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-managed-identity-new
              key: client-id
```

**Comment by Dhruvin4530** [comment]
I am getting the same error, any resolution yet?

**Comment by agilgur5** [comment, marked as answer]
@tico24 responded to this [on Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1722861605449639?thread_ts=1722848053.655599&cid=C01QW9QSSSK) before it was made into a Discussion. Also no response from OP there:

> I know absolutely nothing about Azure Workload identities
>
> But I'm guessing the label `azure.workload.identity/use: "true"` needs to be on the pods in order for it to work? You'll probably see that it's not.
> 
> You'll probably want to add that to your workflowDefaults so that each step gets the label, or add it to the task(s) you want the label on.

Putting that into the context of this template, you can do:
```yaml
  - name: azure-step
    metadata:
      labels:
        azure.workload.identity/use: "true"
    container:
      image: mcr.microsoft.com/azure-cli
      command: ["/bin/sh", "-c"]
      args: ["sleep 10 && echo $AZURE_CLIENT_ID && sleep 300 && az login --identity --username $AZURE_CLIENT_ID && az group list"]
      env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-managed-identity-new
              key: client-id
```
