### DISCUSSION TITLE
Custom labels lost when submitting a WorkflowTemplate

### DISCUSSION THREAD

**Discussion by kellyyke** [argoproj/argo-workflows#13475] [Q&A] [answered]
I've added custom labels to a WorkflowTemplate:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow
  labels:
    myCustomLabel: labelValue
```

However, when I use the `+ Submit` button to submit a workflow from this template in the UI, I can see that there is a `Labels` field, but it's not pre-populated with the custom label, hence anything submitted from the UI no longer has the correct labels
![image](https://github.com/user-attachments/assets/80d376b8-04b3-4c31-8c44-975ec90639d9)

Is there a workaround to make sure submitting from the UI "inherits" the workflowTemplate's existing custom labels?
