### DISCUSSION TITLE
How can I pass a list to child via Workflow of Workflows?

### DISCUSSION THREAD

**Discussion by maccluu** [argoproj/argo-workflows#13478] [Q&A] [answered]
I'm currently thinking of utilizing the workflow of workflow pattern for a design of a workflow that takes a list, batches that list and submits each batch to a generated workflow, so a list of lists that is then looped over to each generated workflow - idea is I can finely control the level of parallelism and success/failure conditions between workflows.

I'm at the point where I'm submitting the list as an argument with the resource template pointed at a WorkflowTemplate that should be taking that list and then using withParam to run with it, however the input param is coming up null

I've confirmed this using the example from the Workflow of Workflows pattern doc - the input parameter message will be null (not the default value) in the generated workflows

Is this expected? Is my design not ideal?
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  entrypoint: whalesay-template
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
---
# This template demonstrates a workflow of workflows.
# Workflow triggers one or more workflows and manages them.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-of-workflows-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: workflow2
            template: resource-with-argument
            arguments:
              parameters:
                - name: workflowtemplate
                  value: "workflow-template-submittable"
                - name: message
                  value: |
                    [
                      { "image": "debian", "tag": "9.1" },
                      { "image": "debian", "tag": "8.9" },
                      { "image": "alpine", "tag": "3.6" },
                      { "image": "ubuntu", "tag": "17.10" }
                    ]
    - name: resource-with-argument
      inputs:
        parameters:
          - name: workflowtemplate
          - name: message
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: workflow-of-workflows-2-
          spec:
            arguments:
              parameters:
              - name: message
                value: {{inputs.parameters.message}}
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
 ```

**Comment by maccluu** [comment, marked as answer]
I was attempting to submit a JSON obj rather than a JSON encoded string, the corrected piece 🤦🏻 :
```yaml
# ... 
    resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: workflow-of-workflows-2-
          spec:
            arguments:
              parameters:
              - name: message
                value: {{=toJSON(inputs.parameters.message)}}
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
```
