### DISCUSSION TITLE
`argo lint` error: parameter `was not supplied`

### DISCUSSION THREAD

**Discussion by gabriel-suela** [argoproj/argo-workflows#13527] [Q&A]
Im trying to pass parameters from my CronWorkflow into a WorkflowTemplate via templateRef, but in the image field, its seems that nothing works

WorkflowTemplate:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: v2-runner
  namespace: icv-legacy
spec:
  serviceAccountName: argo-workflow
  entrypoint: v2-runner
  arguments:
    parameters:
      - name: image
        value: 'gcr.io/xxxxx-2019/xxxxxx:latest'
      - name: sh-script
        value: |
          #!/usr/bin/env sh
          node --version
          ls -la
  templates:
    - name: v2-runner
      inputs:
        parameters:
          - name: image
          - name: sh-script
      container:
        imagePullPolicy: Always
        image: '{{inputs.parameters.image}}'
        env:
          - name: LB_DB_CONNECT_TIMEOUT
            value: '10000000'
          - name: LB_DB_ACQUIRETIMEOUT
            value: '10000000'
          - name: LB_DB_CONNECTION_LIMIT
            value: '10'
        envFrom:
          - configMapRef:
              name: icv-prod
        command: [sh, -c]
        args:
          - '{{inputs.parameters.sh-script}}'
```

CronWorkflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: batches-runner-template
  namespace: icv-legacy
spec:
  # schedule: '10 10 * * *'
  timezone: UTC
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 30
  failedJobsHistoryLimit: 10
  workflowSpec:
    parallelism: 2
    serviceAccountName: argo-workflow
    entrypoint: entrypoint
    templates:
      - name: entrypoint
        steps:
          - - name: generate-validation-rules
              templateRef:
                name: v2-runner
                template: v2-runner
              arguments:
                parameters:
                  - name: image
                    value: 'gcr.io/xxxxx-2019/xxxxxx:latest'
                  - name: sh-script
                    value: |
                      cat << EOF > ./server/bin/get-validations.js
                      const fs = require('fs')
                      const args = require('args')

                      args.option('query', 'provide query to run', '').option('output', 'output file for result', '')

                      const flags = args.parse(process.argv)
                      if (!flags.output || !flags.query) {
                        console.error(`Provide query and output`)
                        process.exit(1)
                      }

                      main(flags.query).then(r => {
                          fs.writeFileSync(flags.output, JSON.stringify(r))
                          process.exit(0)
                        })
                        .catch(e => {
                          console.error(e)
                          process.exit(1)
                        })

                      async function main(query) {
                        const app = require('./initScript')
                        const { BaseModel } = app.models
                        return await BaseModel.findBySql(query)
                      }
                      EOF
                      node ./server/bin/get-validations.js
          - - name: batches-runner
              templateRef:
                name: batches-runner-template
                template: batches-runner
              arguments:
                parameters:
                  - name: validation-rules-list
                    value: '{{steps.generate-validation-rules.outputs.result}}'
```

`argo lint` output: 

`> in "batches-runner-template" (WorkflowTemplate): rpc error: code = InvalidArgument desc = templates.batches-runner.steps[0].process-ids-batch templates.id-processing-workflow.tasks.createBatches templates.batch-command-runner.steps[0].v2-runner templates.v2-runner inputs.parameters.image was not supplied
`
