### DISCUSSION TITLE
How to capture error message/failure reason on task level in argo workflows

### DISCUSSION THREAD

**Discussion by agrawalsonam680** [argoproj/argo-workflows#13520] [Show and tell]
Hello There,
I want to capture error message/failure reason on task level in argo workflow. 
I have checked here https://argo-workflows.readthedocs.io/en/latest/variables/ but nothing has been specify for error message on task level.
Here is my case-

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: exit-handler-with-param-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      onExitTemplate enables workflow to pass the arguments (parameters/Artifacts) to exit handler template.
    workflows.argoproj.io/version: ">= 3.1.0"
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: task-1
            template: output
            hooks:
              exit:
                template: exit
                arguments:
                  parameters:
                    - name: error_message
                      value: "{{tasks.task-1.error_message}}" # Need error message on task level
    
    - name: output
      container:
        image: python:alpine3.6
        command: [sh, -c]
        args: ["echo -n hello world > /tmp/hello_world.txt"]
      outputs:
        parameters:
          - name: result
            valueFrom:
              default: "Foobar"  
              path: /tmp/hello_world.txt
    
    - name: exit
      inputs:
        parameters:
          - name: error_message
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          print("{{inputs.parameters.error_message}}")
```
