### DISCUSSION TITLE
WF cant access PVC

### DISCUSSION THREAD

**Discussion by mohamed-atef2022** [argoproj/argo-workflows#13528] [Q&A]
i am trying to run jmeter on argo WF 
so i run job at first to load some data then i run argo work flow template that containg some dags
the. issue here that after thw pvc created and bound by the job and WF template 
one of the template try to write on the pvc here is the code 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wft-jmeter
spec:
  entrypoint: jmeter-test-run-e2e
  onExit: exit-handler
  serviceAccountName: jmeter
  
  volumeClaimTemplates:
    - metadata:
        name: jmeter-data-dir-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  templates:
    - name: jmeter-test-run-e2e
      dag:
        tasks:
          - name: load-scenarios
            template: load-scenarios

          - name: jmeter
            dependencies: [msteams-jmeter-start]
            template: jmeter-test-execution

          - name: jmeter-master
            template: create-jmeter-master
          - name: jmeter-slave
            template: create-jmeter-slave
    - name: load-scenarios
      inputs:
        parameters:
          - name: jmximage
          - name: jmxfile
      outputs:
        artifacts:
          - name: jmx
            path: '/mnt/out/'
            archive:
              none: {}
      container:
        image: '{{ "{{" }}inputs.parameters.jmximage{{ "}}" }}'
        imagePullPolicy: Always
        # command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        command: ["sh", "-c" ]
        args: ["cp -R /scenario/* /mnt/out/"]
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      volumes:
        - name: out
          emptyDir: {}
    - name: create-jmeter-master
      resource:
        action: create
        manifest: |-
          {{- .Files.Get "assets/jmeter-master.yaml" | nindent 10 }}
    - name: create-jmeter-slave
      resource:
        action: create
        manifest: |-
          {{ .Files.Get "assets/jmeter-slave.yaml" | nindent 10 }}
    - name: jmeter-test-execution
      inputs:
        parameters:
          - name: environment
          - name: jmxfile
          - name: properties
          - name: namespace
          - name: threads
          - name: duration
          - name: rampup
          - name: timeout-connect
          - name: timeout-response
          - name: nb_injectors
          - name: msteamschannel
        artifacts:
          - name: jmx
            path: /scenario/
            mode: 0755
            recurseMode: true
      outputs:
        artifacts:
          - name: reports
            path: '/report/'
            s3:
              key: '{{ "{{" }}workflow.name{{ "}}" }}/report.tar.gz'
          - name: all-reports
            path: '/report/'
            s3:
              key: 'report'
              archive:
                none: {}
      volumes:
        - name: vault
          secret:
            secretName: jmeter-vault
        - name: jmeter-data-dir
          persistentVolumeClaim:
            claimName: '{{`{{`}}workflow.name{{`}}`}}-jmeter-data-dir-pvc'
      script:
        image: "{{ .Values.kubectl.image}}:{{ .Values.kubectl.tag}}"
        command: ["/bin/bash"]
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
        env: []
        volumeMounts:
          - name: jmeter-data-dir
            mountPath: /report
            readOnly: true
          - name: vault
            mountPath: /secret
            readOnly: true
        source: |-
          {{- .Files.Get "assets/start_test.sh" | nindent 10 }}
```
and here is the issue , although the pvc attached and bound and /report is exist 

```
ava.lang.IllegalArgumentException: Cannot write to '/report/report-zuhauseplus_debug_test.jmx' as folder does not exist and parent folder is not writable
        at org.apache.jorphan.util.JOrphanUtils.canSafelyWriteToFolder(JOrphanUtils.java:672) ~[jorphan.jar:5.6.3]
```
