### DISCUSSION TITLE
CronWorkflow submit error

### DISCUSSION THREAD

**Discussion by sidify** [argoproj/argo-workflows#13538] [Q&A]
I'm attempting to create a simple CronWorkflow, similar to the examples provided in Argo's [documentation](https://github.com/argoproj/argo-workflows/blob/main/examples/cron-workflow.yaml). However, I encounter an error when trying to submit it via the web UI.

```
Error: Bad Request: spec.entrypoint is required
```

Here’s the workflow I am trying to submit:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "* * * * *"  # Every minute
  timezone: "America/Los_Angeles"  # Default to local timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"  # Default to "Allow"
  successfulJobsHistoryLimit: 4   # Default is 3
  failedJobsHistoryLimit: 4        # Default is 1
  suspend: false                   # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: hello-world-with-time
    templates:
      - name: hello-world-with-time
        container:
          image: busybox
          command: [ "echo" ]
          args: [ "🕓 Hello, world! Scheduled on: {{workflow.scheduledTime}}" ]
```

Do you have any insights on what might be causing this issue? I also attempted to delete workflowSpec and move everything up one level, which resolved the UI error; however, I did not see the job being triggered according to the Cron expression.
