### DISCUSSION TITLE
artifact output condition

### DISCUSSION THREAD

**Discussion by mohamed-atef2022** [argoproj/argo-workflows#13554] [Q&A]
if i have an argo wf template that run some flow inside it
and they run by sequence can i make the flow number 3 make create artifcat to s3 but when the flow number 5 finish because it depend on value that flow number 5 will create is that applicable
here is the code 
i need to extract output from the step of jmeter master but after the step of jmeter execution finish 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wft-jmeter
spec:
  entrypoint: jmeter-test-run-e2e
  onExit: exit-handler
  serviceAccountName: jmeter
  
    - name: load-scenarios
      inputs:
        parameters:
          - name: jmximage
          - name: jmxfile
      outputs:
        artifacts:
          - name: jmx
            path: '/mnt/out/'
            archive:
              none: {}
      container:
        image: '{{ "{{" }}inputs.parameters.jmximage{{ "}}" }}'
        imagePullPolicy: Always
        # command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        command: ["sh", "-c" ]
        args: ["cp -R /scenario/* /mnt/out/"]
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      volumes:
        - name: out
          emptyDir: {}
    - name: create-jmeter-master
      resource:
        action: create
        manifest: |-
          {{- .Files.Get "assets/jmeter-master.yaml" | nindent 10 }}
      outputs:
        artifacts:
          - name: reports
            path: '/report/'
            s3:
              key: '{{ "{{" }}workflow.name{{ "}}" }}/report.tar.gz'
          - name: all-reports
            path: '/report/'
            s3:
              key: 'report'
              archive:
                none: {}
    - name: create-jmeter-slave
      resource:
        action: create
        manifest: |-
          {{ .Files.Get "assets/jmeter-slave.yaml" | nindent 10 }}
    - name: jmeter-test-execution
      inputs:
        artifacts:
          - name: jmx
            path: /scenario/
            mode: 0755
            recurseMode: true
  
      volumes:
        - name: vault
          secret:
            secretName: jmeter-vault
        - name: jmeter-data-dir
          persistentVolumeClaim:
            claimName: "{{`{{`}}workflow.name{{`}}`}}-jmeter-data-dir-pvc"
      script:
        image: "{{ .Values.kubectl.image}}:{{ .Values.kubectl.tag}}"
        command: ["/bin/bash"]
        securityContext:
          runAsNonRoot: false
          runAsUser: 1001
          allowPrivilegeEscalation: true
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
        env: []
        volumeMounts:
          - name: jmeter-data-dir-pvc
            mountPath: /report
            readOnly: false
          - name: vault
            mountPath: /secret
            readOnly: true
        source: |-
          {{- .Files.Get "assets/start_test.sh" | nindent 10 }}
 ```
