### DISCUSSION TITLE
Splitting Strings

### DISCUSSION THREAD

**Discussion by jrussell9000** [argoproj/argo-workflows#13592] [Q&A] [answered]
Say I have a string parameter, "foo_bar". What's the simplest way that I can _split_ that string according to the underscore delimiter? My method right now is to run separate script tasks to grab the first, then second part of the string. I'm not sure how I can get a single script task to output two results (and then be able to use then in subsequent steps).  Either way, this seems a bit clunky.... Is there a jsonPath/expr solution for this? Or something easier?

**Comment by jswxstw** [comment, marked as answer]
Here is an example with `expr`:
```YAML
metadata:
  name: test-split
  namespace: argo
spec:
  arguments:
    parameters:
      - name: message
        value: foo_bar
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: first
            value: '{{=split(workflow.parameters.message, "_")[0]}}'
          - name: second
            value: '{{=split(workflow.parameters.message, "_")[1]}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.first}} {{inputs.parameters.second}}'
```
