### DISCUSSION TITLE
how to parameterize a single template's priority?

### DISCUSSION THREAD

**Discussion by ni-todo-spot** [argoproj/argo-workflows#13612] [Q&A] [answered]
Hey All!

The next snippet does not work:
```yaml

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: arguments-parameters-
spec:
  entrypoint: print-message
  arguments:
    parameters:
    - name: priority
      value: ''

  templates:
  - name: print-message
    priority: "{{=asInt(workflow.parameters.priority)}}"
    container:
      image: busybox
      command: [echo]
      args: ["hello world"]

```

When trying to create such wft I get this error:
``` Bad Request: json: cannot unmarshal string into Go struct field Template.template.spec.templates.priority of type int32```

clearly I'm doing something wrong. Can u please help me understand what and how to fix?

Thanks in advance?

**Comment by NI1993** [comment]
I had a similar problem last week & could not figure it out :\

**Comment by jswxstw** [comment]
I think you should use [priorityClassName](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass) instead since it is string type and setting priority in pod spec is no longer allowed in the latest version of k8s.

Here is an example:
```YAML
metadata:
  name: priority-example
  namespace: argo
spec:
  arguments:
    parameters:
      - name: priorityClassName
        value: 'system-node-critical'
  entrypoint: argosay
  templates:
    - name: argosay
      priorityClassName: "{{workflow.parameters.priorityClassName}}"
      container:
        name: main
        image: argoproj/argosay:v2
        args: ["echo", "hello"]
```
