### DISCUSSION TITLE
Set max step duration dynamically?

### DISCUSSION THREAD

**Discussion by comtihon** [argoproj/argo-workflows#13651] [Q&A] [answered]
I have a step (gsutil rsync) which sometimes hangs forever. I know the amount of files to be synced before, so I'd like to set up a timeout for rsync step based on it.
How can I do it?
I've tried with both activeDeadlineSeconds and maxDuration but they seem to be static (I can't reference them via one step's output goes to this step input).
If I do it in the template level via jinja template `activeDeadlineSeconds: "{{workflow.parameters.number_of_photos | int * 2}}"` it also fails to resolve it.

**Comment by agilgur5** [comment]
> If I do it in the template level via jinja template `activeDeadlineSeconds: "{{workflow.parameters.number_of_photos | int * 2}}"` it also fails to resolve it.

Templating isn't done via Jinja and doesn't follow the syntax you used here. Please see [the "Expression" docs](https://argo-workflows.readthedocs.io/en/release-3.5/variables/#template-tag-kinds).

I'm not sure if `activeDeadlineSeconds` is templatable, but you'd need the proper syntax either way.
If it isn't, you should be able to workaround it with `podSpecPatch`

**Reply by comtihon** [reply]
Thank you. I found the way how to make activeDeadlineSeconds dynamic via podSpecPatch.

**Comment by comtihon** [comment, marked as answer]
I found the solution via `podSpecPatch`. It's the only option `activeDeadlineSeconds` can get the dynamic value.
the full example is here:
```yaml
metadata:
  name: test-deadline
  namespace: argo-events
  labels:
    example: 'true'
spec:
  entrypoint: example

  templates:
    - name: example
      dag:
        tasks:
          - name: generate-value
            template: generate-value
          - name: obtain
            template: obtain
            arguments:
              parameters:
                - name: timeout
                  value: "{{tasks.generate-value.outputs.parameters.value}}"

    - name: generate-value
      script:
        image: alpine:3.7
        command: [sh]
        source: |
          echo 10 > /tmp/output.txt
      outputs:
        parameters:
          - name: value
            valueFrom:
              path: /tmp/output.txt
    - name: obtain
      inputs:
        parameters:
          - name: timeout
      podSpecPatch: '{"activeDeadlineSeconds":{{inputs.parameters.timeout}}}'
      script:
          image: alpine:3.7
          command: [sh]
          source: |
              echo "Simulating task for {{inputs.parameters.timeout}} seconds."
              sleep 20
```
