### DISCUSSION TITLE
Timeout in exit handler

### DISCUSSION THREAD

**Discussion by sonamdolphin9192** [argoproj/argo-workflows#13657] [Q&A] [answered]
Hi,
I want to timeout the exit handler workflow in argo workflow.
Here is the case-

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: exit-handler-with-param-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      onExitTemplate enables workflow to pass the arguments (parameters/Artifacts) to exit handler template.
    workflows.argoproj.io/version: ">= 3.1.0"
spec:
  entrypoint: main
  onExit: workflow-level-exit-hanlder
  templates:
    - name: main
      dag:
        tasks:
          - name: task-1
            template: output
            hooks:
              exit:
                template: exit
                arguments:
                  parameters:
                    - name: message
                      value: "{{tasks.task-1.message}}" 
    
    - name: output
      container:
        image: python:alpine3.6
        command: [sh, -c]
        args: ["echo -n hello world > /tmp/hello_world.txt"]
      outputs:
        parameters:
          - name: result
            valueFrom:
              default: "Foobar"  
              path: /tmp/hello_world.txt
    
    - name: exit
      inputs:
        parameters:
          - name: error_message
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          print("{{inputs.parameters.error_message}}")

    - name: workflow-level-exit-hanlder
      dag:
        tasks:
          - name: exite-handler-at-workflow
            arguments:
              parameters:
                 name: workflow_status
                 value: "{{ `{{ workflow.status }}` }}"`
```
