### DISCUSSION TITLE
Use `templateRef` in WorkflowTemplate

### DISCUSSION THREAD

**Discussion by frucht-salat** [argoproj/argo-workflows#13727] [Q&A] [answered]
Hi ArgoWorkflows community,

I would like to use a WorkflowTemplate in another WorkflowTemplate.
E.g.

default wft
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: default-wft
spec:
  entrypoint: run-task
  arguments:
    parameters:
    - name: task_image
      value: ""
  templates:
  - name: run-task
    container:
      image: "{{workflow.parameters.task_image}}"
      env:
      - name: DB_HOST
        value: <host>
      command: [<someCommand>]
      args: ["{{workflow.parameters.task_args}}"] 
```

set image and define task_args with test_param
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: task-wft
spec:
  entrypoint: run-task-wft
  arguments:
    parameters:
      - name: test_param
        value: some_param
  templates:
  - name: run-task-wft
    templateRef:
      name: default-wft
      template: run-task
    arguments:
      parameters:
        - name: task_image
          value: <the correct image>
        - name: task_args
          value: |
            {
              "params": {
                "test_param": "{{workflow.parameters.test_param}}"
              },
            }
```

use that "task-wft" in a workflow.

Is that possible? The documentation states that templateRef must be in steps: but a WorkflowTemplate does not have steps afaik. Therefore this is probably not possible, but maybe in another way?

**Comment by frucht-salat** [comment, marked as answer]
You can use steps in WorkflowTemplates!

Use 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: task-wft
spec:
  entrypoint: run-task-wft
  arguments:
    parameters:
      - name: test_param
        value: some_param
  templates:
  - name: run-task-wft
    steps:
    - - name: default-template
         templateRef:
           name: default-wft
           template: run-task
        arguments:
          parameters:
          - name: task_image
            value: <the correct image>
          - name: task_args
            value: |
            {
              "params": {
                "test_param": "{{workflow.parameters.test_param}}"
              },
            }
```
This works
