### DISCUSSION TITLE
Filtering groups (`filterGroupsRegex`) and RBAC

### DISCUSSION THREAD

**Discussion by gauravluckme** [argoproj/argo-workflows#13721] [Q&A] [answered]
Hi - We've configured SSO and trying to restrict access using [Filtering groups (`filterGroupsRegex`)](https://argo-workflows.readthedocs.io/en/release-3.5/argo-server-sso/#filtering-groups). However it's not working as expected, is it we need to always enable RBAC to use it or we are missing some configuration?

**Comment by agilgur5** [comment]
Looking at the code of https://github.com/argoproj/argo-workflows/pull/11774, specifically this block: https://github.com/argoproj/argo-workflows/blob/bf7760a46e29bf2571bd3e9d852220b44339bb60/server/auth/sso/sso.go#L300

it doesn't seem like it should be RBAC specific.

I would double-check that your Argo version is compatible.
You didn't provide any config or any other information so it's pretty hard to help otherwise.

**Reply by gauravluckme** [reply]
We're using Argo Workflows version - v3.5.7 (helm version 0.41.7)

The below configuration are configured (we fetch the groups from `customGroupClaimName`):

```yaml
sso:
      issuer: https://example.com/oauth/token
      clientId:
        name: example-sso-secret
        key: sso.clientId
      clientSecret:
        name: example-sso-secret
        key: sso.clientSecret
      redirectUrl: ""
      rbac:
        enabled: false
      scopes:
        - openid
        - profile
        - email
        - roles
      customGroupClaimName: roles
      filterGroupsRegex:
        - ^GR_example-group.*
```
