### DISCUSSION TITLE
schedule templates at different times within 1 cron workflow?

### DISCUSSION THREAD

**Discussion by fel-este** [argoproj/argo-workflows#13725] [Q&A] [answered]
I have a cron workflow that runs 1 template at a certain time:

```yaml
kind: CronWorkflow
spec:
  schedule: '0 0 * * *'
  workflowSpec:
    entrypoint: A
    templates:
    - name: A
```

I now also want to schedule a different job (template B) to run at a different schedule. Is it possible I can extend the workflow template to do this? Or will I have to create another CronWorkflow file to do this? Can I supply multiple `schedules` for different `templates`?
