### DISCUSSION TITLE
How can I use a when statement to check for a field that may or may not exist in a JSON object?

### DISCUSSION THREAD

**Discussion by mio4kon** [argoproj/argo-workflows#13732] [Q&A] [answered]
```yaml
spec:
  arguments:
    parameters:
      - name: metaData
        value: |
          {
            "basic": {
              "serverEnv": "pre"
            },
            "repoInfo": {
              "branch": "release/new-feature"
            },
            "mrInfo": {
              "title": "title",
              "mrLabels": []
            }
          }
```
How can I check if the iid field exists in the `mrInfo` object (which may or may not have this field) using the when statement? I tried using the `?` operator, but it still throws an error.

`when: "{{=jsonpath(workflow.parameters.metaData, '$.mrInfo?.iid') == nil }}"`

![image](https://github.com/user-attachments/assets/7232b613-8b52-4294-ab4d-acb35ee08587)

**Comment by jswxstw** [comment, marked as answer]
You may use `fromJSON` instead, here is an example:
```YAML
metadata:
  name: demo
  namespace: argo
spec:
  arguments:
    parameters:
      - name: metaData
        value: |
          {
            "basic": {
              "serverEnv": "pre"
            }
          }
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: argosay
            template: argosay
            when: "{{=fromJSON(workflow.parameters.metaData).basic?.env == nil}}"
    - name: argosay
      container:
        name: main
        image: argoproj/argosay:v2
        command: [/argosay]
        args: [echo, hello]
```
