### DISCUSSION TITLE
Template WorkflowTemplate conditionally

### DISCUSSION THREAD

**Discussion by frucht-salat** [argoproj/argo-workflows#13791] [Q&A] [answered]
Hi ArgoWorkflows community,

I have this ClusterWorkflowTemplate:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: default-wft
spec:
  templates:
  - name: run-task
    inputs:
      parameters:
      - name: task_image
      - name: execution_environment
    container:
      image: "{{inputs.parameters.task_image}}"
      env:
      - name: DB_HOST
        value: ${DB_HOST}
      command: ["python", "-m", "software"]
      args: ["{{inputs.parameters.execution_environment}}"]
```

And I want it to only include DB_HOST if I set a environment.   
Do I have to create an extra template for this? Or is it possible to change WorkflowTemplates dynamically somehow?
