### DISCUSSION TITLE
Lint fails on global output parameter in wft

### DISCUSSION THREAD

**Discussion by Gilwyad** [argoproj/argo-workflows#13870] [General]
`argo lint` fails on a workflow template that I am able to `kubectl apply` and is working in a workflow! Reproducible wft:

```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-with-global-output-parameter-lint-fails
spec:
  templates:
    - name: test-one
      steps:
        - - name: hello-test-1
            template: hello1
          - name: hello-test-2
            template: hello2
            when: '{{workflow.outputs.parameters.variable}} == true'

    - name: hello1
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo hello test 1"]

    - name: hello2
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo hello test 2"]

```

The error:

```
argo-bug/global-output-parameter-in-wft-lint-fails.yaml:
   ✖ in "workflow-template-with-global-output-parameter-lint-fails" (WorkflowTemplate): rpc error: code = InvalidArgument desc = templates.test-one templates.test-one.steps failed to resolve {{workflow.outputs.parameters.variable}}
```

I found a way to work around this issue by using an input parameter that has the default value of the output parameter:

```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-with-global-output-parameter-lint-passes
spec:
  templates:
    - name: test-one
      inputs:
        parameters:
          - name: variable
            value: '{{workflow.outputs.parameters.variable}}'
      steps:
        - - name: hello-test-1
            template: hello1
          - name: hello-test-2
            template: hello2
            when: '{{inputs.parameters.variable}} == true'

    - name: hello1
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo hello test 1"]

    - name: hello2
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo hello test 2"]

```

Meaning that the same output parameter is not recognized in the `when` field, but is recognized in the `value` field. And even when it complains, the workflow is actually working fine! Looks like a bug to me, what do you think?

Using Argo 3.5.10

I found this related issue: https://github.com/argoproj/argo-workflows/issues/2590

It seems to be the same problem. Maybe it was fixed so the workflows are working as expected but the linter was not corrected?
