### DISCUSSION TITLE
Using `when` expression to parse result leads to error

### DISCUSSION THREAD

**Discussion by frucht-salat** [argoproj/argo-workflows#13880] [Q&A] [answered]
Hello, I would like to parse a JSON that I wrote to a file as an output, then evaluate a parameter of that JSON for a `when` condition.  

Seeminly this should work: https://github.com/argoproj/argo-workflows/discussions/7413  
But my case is a bit different:

Output of `step-first`:
<img width="412" alt="argo-workflow-output" src="https://github.com/user-attachments/assets/b97e3faa-25e4-439c-b04d-aef4f65164da">

Now with this output:
```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: $TASK_NAME-conditional-wft
spec:
  arguments:
    parameters:
    - name: test_param
    - name: myjson
      value: '{"key1": 100}'
  templates:
  - name: main
    steps:
    - - name: step-first
        template: write-to-output
        when: "{{workflow.parameters.test_param}} == 'test'"
    - - name: step-if-one
        template: success
        when: "1 > {{steps.step-first.outputs.parameters.result}}"
    - - name: step-if-zero
        template: success
        when:  "1 > {{=jsonpath(workflow.parameters.myjson, '$.key1')}}"
  - name: write-to-output
    serviceAccountName: $ARGO_SA
    script:
      image: python:3.10
      command: [python]
      source: |
        import json
        import random
        from pathlib import Path
        result = random.randint(1, 2)
        Path("/tmp").mkdir(exist_ok=True)
        Path("/tmp/result.json").touch()
        Path("/tmp/result.json").write_text(
            json.dumps({"result": result})
        )
    outputs:
      parameters:
      - name: result
        valueFrom:
          path: /tmp/result.json
  - name: success
    serviceAccountName: $ARGO_SA
    script:
      image: python:$PYTHON_VER
      command: [python]
      source: |
        print("success")
```

The condition of `step-if-zero` works as explained here: https://github.com/argoproj/argo-workflows/discussions/7413#discussioncomment-2282076

But my expression gets the error:
```
Invalid 'when' expression '1 > {"result": 2}': Invalid token: '{' (hint: try wrapping the affected expression in quotes ("))
```

What I tried:
```
when: "1 > {{=jsonpath(steps.step-first.outputs.parameters.result, '$.result')}}"
```
-> `Invalid 'when' expression '1 > {{=jsonpath(steps.step-first.outputs.parameters.result, '$.result')}}': Invalid token: '{{=' (hint: try wrapping the affected expression in quotes ("))`

As I understand, _if_ the condition would be true, it would execute correctly.   
Can someone help me fix the when condition as it seems I am parsing the result incorrectly?

**Comment by jswxstw** [comment, marked as answer]
Note: a dash in the name requires the use of brackets and quotes for expr to handle.
```YAML
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: wft-if-else
spec:
  templates:
  - name: run-task-wft
    steps:
    - - name: step-first   # <- this writes the aforementioned output
    - - name: step-if-one
        when: "1 == {{=jsonpath(steps['step-first'].outputs.parameters.result, '$.result')}}"
    - - name: step-if-zero
        when: "0 == {{=jsonpath(steps['step-first'].outputs.parameters.result, '$.result')}}"
```
