### DISCUSSION TITLE
How can I use a hardwired artifact when called from a Sensor?

### DISCUSSION THREAD

**Discussion by framegrace** [argoproj/argo-workflows#13897] [Q&A]
I am creating a hardwired git artifact on a workflowTemplate based on  URL and reviision parameters  that need to  be provided 
Here the workflowtemplate in question:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-and-push-image
  generateName: input-artifact-git-
  namespace: argo
spec:
  arguments:
    parameters:
      - name: git-repo-url
      - name: git-revision
  entrypoint: Sequence
  templates:
  - name: Sequence
    steps:
    - - name: git-clone
        template: git-clone-template
    - - name: build-and-push
        template: kaniko
        arguments:
          artifacts:
          - name: source
            from: "{{steps.git-clone.outputs.artifacts.src}}"

  - name: git-clone-template
    inputs:
      artifacts:
      - name: argo-clone
        path: /src
        git:
          repo: '{{workflow.parameters.git-repo-url}}'
          revision: '{{workflow.parameters.git-revision}}'
          usernameSecret:
            name: gitlab-access
            key: username
          passwordSecret:
            name: gitlab-access
            key: token
          depth: 1
    container:
      image: golang:1.10
      command: [sh, -c]
      args: ["git status && ls"]
      workingDir: /src
    outputs:
      artifacts:
      - name: src
        path: /src

  - name: kaniko
    dependecies:
      - git-clone-template
    inputs:
      artifacts:
      - name: source
        path: /src
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=/src/Dockerfile"
        - "--ignore-path=/product_uuid"
        - "--context=/src"
        - "--destination=docker.clockin.here/project:{{workflow.parameters.git-revision}}"
        - "--insecure"
        - "--insecure-registry=docker.clockin.here"
```

When run on workflows, (on the UI, for example) I set the parameters, submit and everything goes fine.
Whem I try to call it from a Sensor, which defines the repo and revision parameters, seems is not enough because the git-clone step shows this error when executed from the sensor:
```
Error (exit code 1): required artifact 'argo-clone' not supplied

```
Tried:
  - make it optional: Then is simply ignored and the git clone is not performed
  - Define the hardwired artifact on the Event's workflow definition arguments :  I also get "argo-clone" not supplied error

How should I define the argo-clone on the Sensor workflow definition?
 
This is my current sensor.
```
kind: Sensor
metadata:
  name: gitlab-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: gitlab-dep
      eventSourceName: frontend-event-source
      eventName: frontend
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          namespace: argo
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: input-artifact-git-
                namespace: argo
              spec:
                workflowTemplateRef:
                  name: build-and-push-image
                arguments:
                  parameters:
                    - name: git-repo-url
                      value: ""
                    - name: git-revision
                      value: ""
      parameters:
        - src:
            dependencyName: gitlab-dep
            dataKey: body.project.git_http_url
          dest: spec.arguments.parameters.0.value
        - src:
            dependencyName: gitlab-dep
            dataKey: body.checkout_sha
          dest: spec.arguments.parameters.1.value 
```
