### DISCUSSION TITLE
Mutex wildcards and "don't run this WF at the same time as mutex X"

### DISCUSSION THREAD

**Discussion by winterrobert** [argoproj/argo-workflows#13906] [Q&A]
Is there a way to:

1. Use wildcards or regex in mutexes or achieve the same results using some other means?
2. Specify that one workflow shouldn't run at the same time as another set of workflows (without placing a lock itself)?

We have:

- A: a job that syncs data for a specific tenant that runs from time to time during the day (trigged by the tenants) -- we only want one of these jobs to run at the same time for each individual tenant. Currently we give that job a mutex ingest.{{tenantid}}
- B: a batch job that syncs data for all tenants

We don't want any job like A to run at the same time as B and vice versa.
I image we could achieve that if there exists something like this:
Job A:
```
synchronization:
    mutexes:
      - name:  `ingest.`{{inputs.parameters.tenantid}}``
   dontRunAtTheSameTimeAs:
      - name:  `ingest`
```
Job B:
```
synchronization:
    mutexes:
      - name:  `ingest`
   dontRunAtTheSameTimeAs:
      - name:  `ingest.*`
```

Is something like this possible to achieve with Argo Workflows? Can it be done by using some smart combination of semaphores and mutexes?
