### DISCUSSION TITLE
Getting results of a `step` in a nested WorkflowTemplate structure

### DISCUSSION THREAD

**Discussion by frucht-salat** [argoproj/argo-workflows#13905] [Q&A] [answered]
My problem is, that I need the output.parameter to use it in the input of the next step in a `precise-template`.

I have three different templates:
- `default-template`
- `specific-template`s (2)
  - defining one step
- `precise-template`
  - Defining many steps

In this structure, the `specific-template` uses the `default-template`. The `precise-template` uses many `specific-templates`. Looking like this:

`default-template`
```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: output-default-wft
spec:
  templates:
  - name: run-task-output-first
    inputs:
      parameters:
      - name: download_url
    script:
      image: python:3.10
      command: [python]
      source: |
        import json
        from pathlib import Path
        print("download_url: ", {{inputs.parameters.download_url}})
        result = {{inputs.parameters.download_url}}
        # Write the result to the output file
        Path("/tmp").mkdir(exist_ok=True)
        Path("/tmp/result.json").write_text(
            json.dumps({"download_url": result[0]})
        )
    outputs:
      parameters:
      - name: result
        valueFrom:
          path: /tmp/result.json
  - name: run-task-output-last
    inputs:
      parameters:
      - name: execution_environment
    container:
      image: python:3.10
      command: [python]
      args: ["-c", "print(str({{inputs.parameters.execution_environment}}))"]
```
`specific-template-first`:
```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: output-first-wft
spec:
  templates:
  - name: run-task-wft
    inputs:
      parameters:
      - name: download_url
    steps:
    - - name: step-first
        templateRef: 
          name: output-default-wft
          template: run-task-output-first
          clusterScope: true
        arguments:
          parameters:
          - name: download_url
            value: "{{inputs.parameters.download_url}}"
```
`specific-template-last`
```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: output-last-wft
spec:
  templates:
  - name: run-task-wft
    inputs:
      parameters:
      - name: download_url
    steps:
    - - name: step-end
        templateRef: 
          name: output-default-wft
          template: run-task-output-last
          clusterScope: true
        arguments:
          parameters:
          - name: execution_environment
            value: |
              {
                "context": { 
                  "download_url": "{{inputs.parameters.download_url}}"
                }
              }
```
`precise-template` using the `specific-template`s:
```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: output-wft
spec:
  templates:
  - name: output
    inputs:
      parameters:
      - name: download_url
    steps:
    - - name: first
        templateRef:
          name: output-first-wft
          template: run-task-wft
          clusterScope: true
        arguments:
          parameters:
          - name: download_url
            value: "{{inputs.parameters.download_url}}"
    - - name: last
        templateRef:
          name: output-last-wft
          template: run-task-wft
          clusterScope: true
        arguments:
          parameters:
          - name: download_url
            value: "{{=jsonpath(steps['step-first'].outputs.parameters.result, '$.download_url')}}"
```
Here the error appears, because the download_url is given as "{{=jsonpath(steps['step-first'].outputs.parameters.result, '$.download_url')}}" and not evaluated -> as is the case if the `precise-template` directly uses the `default-template` without the extra `step` definition in the `specific-template`s.  
The problem is, that I need the `specific-template`s to be executable themselves but also be usable in steps of other WorkflowTemplates.  

By the way: The structure works, only the result access is not correct.

The `workflow`:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-wf-
spec:
  entrypoint: output
  arguments:
    parameters:
    - name: download_url
      value: |
        [
          "file:///test_image"
        ]
  workflowTemplateRef:
    name: output-wft
    clusterScope: true 
```

**Comment by frucht-salat** [comment, marked as answer]
After trial and error: You can actually solve this, via the propagation of outputs.

Adapting the `specific-template-first` like this:

```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: output-first-wft
spec:
  templates:
  - name: run-task-wft
    inputs:
      parameters:
      - name: download_url
    steps:
    - - name: step-first
        templateRef: 
          name: output-default-wft
          template: run-task-output-first
          clusterScope: true
        arguments:
          parameters:
          - name: download_url
            value: "{{inputs.parameters.download_url}}"
  outputs:
    parameters:
    - name: task_result
      valueFrom:
        parameter: "{{steps.step-first.outputs.parameters.result}}"
```
You can access the parameter `task_result` in the `precise-template`
```
    - - name: last
        templateRef:
          name: output-last-wft
          template: run-task-wft
          clusterScope: true
        arguments:
          parameters:
          - name: download_url
            value: "{{=jsonpath(steps['step-first'].outputs.parameters.task_result, '$.download_url')}}"
```
