### DISCUSSION TITLE
podSpecPatch configuration not passed down to Workflow Steps/DAG Tasks

### DISCUSSION THREAD

**Discussion by cossentinoCS** [argoproj/argo-workflows#13910] [Q&A]
I am intending to apply a podSpecPatch to a template that has two Workflow Steps that each run a "base" script template which I use across many workflows

However, the patch seems to be ignored unless I apply the patch directly to the base template. 

My workaround has been to duplicate the "base" template with different podSpecPatches depending on the use case, but results in lots of duplicate code in order to apply a single configuration change.

1) Is this a bug, misconfiguration, or simply not part of Argo's inheritance pattern? 

2) Is there a one place reference to understand how configuration is inherited across argo workflow resources?

```
    - name: llm
      ## this podSpecPatch is not applied to the steps. the base template otherwise has no patch.
      podSpecPatch: 
        <patch content>
      steps:
        - - name: a
            template: base
            when: "{{workflow.parameters.pipeline_name}} == production_a"
            arguments:
              parameters:
                - name: kedro_cli_params
                  value: "--to-outputs=ensemble_preds"
        - - name: b
            template: base
            when: "{{workflow.parameters.pipeline_name}} == production_b"
            arguments:
              parameters:
                - name: kedro_cli_params
                  value: "--to-outputs=ensemble_b_preds"
```
