### DISCUSSION TITLE
Exit code 4 occurs intermittently in Workflow.

### DISCUSSION THREAD

**Discussion by kworkbee** [argoproj/argo-workflows#13928] [Q&A]
I don't think it's the code that Argo Workflow defines, but this code seems to be obscure. Does anyone know what this code means?

**Comment by kworkbee** [comment]
<img width="949" alt="스크린샷 2024-11-22 17 28 00" src="https://github.com/user-attachments/assets/5b7a1cfb-fcfd-41bb-b1cd-bae021b704b5">

**Comment by MasonM** [comment]
That means the container/process being executed by the workflow exited with status 4, which is a problem with the container/process, not Argo Workflows. You can reproduce this with the following workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test
spec:
  entrypoint: argosay
  templates:
    - name: argosay
      container:
        name: main
        image: argoproj/argosay:v2
        command: ['/bin/sh', '-c']
        args: ["exit 4"]
```
