### DISCUSSION TITLE
Azure SSO Redirect Not Working

### DISCUSSION THREAD

**Discussion by andrewmetcalfbede** [argoproj/argo-workflows#13938] [Q&A]
Unable to get Azure SSO working in Argo Workflows.

Error in the UI
```
error_description: AADSTS650053: The application 'argocd-test' asked for scope 'groups' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor. 
```

Error in the logs:
```
time="2024-11-25T18:53:48.850Z" level=error msg="failed to get oauth2Token by using code from the oauth2 server" error="oauth2: \"invalid_request\" \"AADSTS900144: The request body must contain the following parameter: 'code'. Trace ID: 529c7438-e07c-41f0-bbbf-22224a3f3600 Correlation ID: 2cc4133d-f61d-4b98-8ab0-c4e56976f1f3 Timestamp: 2024-11-25 18:53:48Z\" \"https://login.microsoftonline.com/error?code=900144\""
```

As far as I can tell I have things set up correctly, I'm using the same app registration for Argo CD and it works as expected.   The error suggests the `groups` scope is missing but it clearly isn't.

```
k get configmap/workflow-controller-configmap -o jsonpath={'.data.sso'} | grep -v '^#'
issuer: https://login.microsoftonline.com/<tenant-id>/v2.0
sessionExpiry: 240h
clientId:
  name: client-id-secret
  key: client-id-key
clientSecret:
  name: client-secret-secret
  key: client-secret-key
redirectUrl: https://<internal-address>/oauth2/callback
scopes:
 - groups
 - email
 - profile
rbac:
  enabled: true
insecureSkipVerify: false
```

```
k get deployment/argo-server -o jsonpath='{.spec.template.spec.containers[].args}'
["server","--namespaced","--auth-mode=client","--auth-mode=sso"]
```

Client ID and secret are valid:
```
 ➜  ~ clientId=$(k get secret client-id-secret -o jsonpath='{.data.client-id-key}' | base64 --decode)
 ➜  ~ clientSecret=$(k get secret client-secret-secret -o jsonpath='{.data.client-secret-key}' | base64 --decode)
 ➜  ~ az login --service-principal \
    --username $clientId \
    --password $clientSecret \
    --tenant $tenantId
No subscriptions found for <clientId>
```

![api_perms](https://github.com/user-attachments/assets/2b771b4f-9af3-4457-aea2-db8b06a5c01b)
![authentication](https://github.com/user-attachments/assets/b37df853-0ed4-4d59-bf04-032d463263c7)
![group_scope](https://github.com/user-attachments/assets/b2a835ce-d6ce-4a41-86a8-4010de8fd34f)
