### DISCUSSION TITLE
Wait container tries to pull Linux image on Windows k8s node

### DISCUSSION THREAD

**Discussion by ilbatin** [argoproj/argo-workflows#13941] [Q&A] [answered]
Hello!
I’ve encountered an issue when trying to use Windows nodes for running Windows images in Argo Workflows.

The problem is that the wait container attempts to pull quay.io/argoproj/argoexec:v3.5.5 on a Windows machine, even though I specified the node selector `kubernetes.io/os=windows`.

The documentation says that `The Argo server and the workflow controller currently only run on Linux. The workflow executor however also runs on Windows nodes, meaning you can use Windows containers inside your workflows!`. 
But how exactly do you achieve this? The argoexec image is specified in the controller configuration. Do I need to run two controllers—one for Linux and another for Windows?

Additional debug info:

Workflow config:
```
spec:
  templates:
    - name: windows-workflows
      inputs: {}
      outputs: {}
      nodeSelector:
        kubernetes.io/os: windows
      metadata: {}
      container:
        name: windows
        image: >-
          docker-registry/windows-workflows:0.0.1 # our custom image
        command:
          - powershell.exe
          - '-command'
          - echo test
        resources: {}
```

Error message:
```
Back-off pulling image "quay.io/argoproj/argoexec:v3.5.5"
Pulling image "quay.io/argoproj/argoexec:v3.5.5"
Error: ErrImagePull
```

K8S GKE cluster version: 1.30.5-gke.1443001
My workflow controller version is `workflow-controller:v3.6.0`
