### DISCUSSION TITLE
Can I set the name of a workflow started from a WorkflowTemplate to a parameter

### DISCUSSION THREAD

**Discussion by seyhbold** [argoproj/argo-workflows#13989] [Q&A] [answered]
Hi,

I have a WorkflowTemplate that is used from an argo-events sensor triggered after a S3 bucket notification. Now I have trouble to find the workflows when I search for an object key. 

Is there any way to set the title or description of a Workflow containing a parameter passed to the WorkflowTemplate?

Thank you very much

**Comment by jswxstw** [comment]
You can directly obtain the workflow name from the environment variable: `ARGO_WORKFLOW_NAME` without any additional changes.

**Reply by seyhbold** [reply]
Hi @jswxstw, sorry that I answer that late (.. next year) 

Thank you, but I think my problem is the other way round.
I pass a parameter when creating a workflow from a workflowTemplate.

i.e.

OBJECT_KEY: `s3://bucket/incoming/sku_3772821.xml`

Now I want to set a label or an annotation on the created workflow containing the object key so that I can search the workflow by using the key in the argo workflows server ui.

Is this possible?

**Reply by jswxstw** [reply]
You can add labels/annotations to Workflows with [workflowMetadata](https://argo-workflows.readthedocs.io/en/latest/workflow-templates/#adding-labelsannotations-to-workflows-with-workflowmetadata).

But it is important to note that, `s3://bucket/incoming/sku_3772821.xml` does not meet the format requirements for labels.

**Comment by seyhbold** [comment]
Thank you very much,

I tried:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-global-arg
spec:
  workflowMetadata:
    annotations:
      workflows.argoproj.io/description: "{{inputs.parameters.msg}}"

  arguments:
    parameters:
      - name: msg

  entrypoint: hello-world

  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: ""
      container:
        image: busybox
        command: [echo]
        args: ["{{inputs.parameters.msg}}"]
```
invoked it from the UI.

and got:
![grafik](https://github.com/user-attachments/assets/965f694c-de88-44e7-9570-dda5f556cd4b)

I was hoping to see the message in the UI

And `{{inputs.parameters.msg}}` doesn't meet the requirements for labels as well.
Is there any way to add parameters to either labels or annotations?
