### DISCUSSION TITLE
Access generateName inside workflow template

### DISCUSSION THREAD

**Discussion by samad568** [argoproj/argo-workflows#14005] [Q&A]
Hello,
I want to modify the workflow Template in such a way that it accesses generateName given in a workflow and applies the value to a workflow parameter. How can this be done?

Currently what I am doing is: -

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hc01-236670-
  labels:
    issue: "{{workflow.name}}"
spec:
  entrypoint: xyz
  arguments:                   
    parameters:
    - name: issue
      value: "{{workflow.name}}" 

But i want to avoid even mentioning the parameter 'issue' in the workflow.

**Comment by wesleyscholl** [comment]
@samad568 

Use the Global Workflow Variable `{{workflow.name}}`. This value can be referenced directly or optionally passed as an parameter.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hc01-236670-
spec:
  entrypoint: xyz
  templates:
  - name: xyz
    container:
      image: busybox
      command: [sh, -c]
      args:
        - echo "Workflow name: {{workflow.name}}" # Global Workflow Variables like `{{workflow.name}}` can be
                                                  # accessed anywhere in the workflow without defining parameters.
```

**Output:**
```shell
Workflow name: hc01-236670-z4ssl
time="2024-12-16T14:28:05 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
```

**Resources:**
- https://argo-workflows.readthedocs.io/en/latest/variables/
