### DISCUSSION TITLE
Passing artifacts from nested template in a ClusterWorkflowTemplate

### DISCUSSION THREAD

**Discussion by danieljamesscott** [argoproj/argo-workflows#14023] [General]
Hi,

I am trying to figure out whether it's possible to pass artifacts from a nested template in a ClusterWorkflowTemplate. I'm still trying to get my head around the syntax, and can't get it to work.

I have a ClusterWorkflowTemplate:

```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: test-artifact
  namespace: argo
spec:
  entrypoint: artifact
  templates:
    - name: artifact-nested
      steps:
        - - name: step
            template: artifact-direct
# Error: Failed to submit workflow: rpc error: code = InvalidArgument desc = templates.test.steps[0].generate-artifact templates.artifact-nested.outputs.artifacts.artifact_output.path only valid in container/script templates
#      outputs:
#        artifacts:
#          - name: artifact_output
#            path: /etc/hostname

    - name: artifact-direct
      container:
        image: busybox
        command: [ echo ]
        args: [ "hello world" ]
      outputs:
        artifacts:
          - name: artifact_output
            path: /etc/hostname
```

Which is called from my Workflow:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
  namespace: argo
spec:
  entrypoint: test
  templates:
    - name: test
      steps:

        - - name: "generate-artifact"
            templateRef:
              name: test-artifact
              template: artifact-nested
              clusterScope: true

        - - name: "use-artifact"
            template: catfile
            arguments:
              artifacts:
                - name: artifact
                  from: "{{steps.generate-artifact.outputs.artifacts.artifact_output}}"

    - name: catfile
      inputs:
        artifacts:
          - name: artifact
            path: /artifact
      container:
        image: busybox
        command: [ cat ]
        args: [ "/artifact" ]
```

I can successfully create the ClusterWorkflowTemplate, but when I try to submit the workflow, I receive:

```
Error: Failed to submit workflow: rpc error: code = InvalidArgument desc = templates.test.steps failed to resolve {{steps.generate-artifact.outputs.artifacts.artifact_output}}
```

When I attempt to resolve this by defining an output artifact on `artifact-nested`, I get:

```
# Error: Failed to submit workflow: rpc error: code = InvalidArgument desc = templates.test.steps[0].generate-artifact templates.artifact-nested.outputs.artifacts.artifact_output.path only valid in container/script templates
```

If I switch the referenced template in my workflow to `artifact-direct`, then it works as expected. Should I be able to reference a nested artifact from a workflowtemplate? Or are workflow templates supposed to be used as single (non-step) entities?

Thanks,

**Comment by danieljamesscott** [comment]
Oh, I think I have it:

```
      outputs:
        artifacts:
          - name: artifact_output
            from: "{{steps.step.outputs.artifacts.artifact_output}}"
```

Getting mixed up with the output definition vs passing it in to the next step!
