### DISCUSSION TITLE
Using Expr Lang to pass Spring Batch JobParameters to `.spec.templates[*].container.args`

### DISCUSSION THREAD

**Discussion by kworkbee** [argoproj/argo-workflows#14068] [Q&A]
Hello, I'm configuring a WorkflowTemplate that delivers JobParameters as arguments to Spring Batch application

```yaml
kind: WorkflowTemplate
spec:
  templates:
    - container:
        name: ''
        image: '{{inputs.parameters.image}}'
        args:
          - '--job.name={{inputs.parameters.jobname}}' # Will be placed by Configuration Property `spring.batch.job.name=${}`
          - '{{inputs.parameters.additionalArgs}}' # **A problematic part**
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: '{{inputs.parameters.profile}}'
          - name: JAVA_TOOL_OPTIONS
            value: '{{inputs.parameters.javaOption}}'
          - name: TZ
            value: '{{inputs.parameters.timezone}}'
```

JobParameters as below

`startDate=2024-12-31,java.lang.String endDate=2025-12-31,java.lang.String`

I want to bind to individual items in args when there are multiple items. (by splitting `inputs.parameters.additionalArgs` by whitespace) If it goes into a single item, there is a problem that only the first item is recognized by the actual application based on whitespace, so it does not work normally.

I need your help!

**Comment by MasonM** [comment]
Parameters can only be passed as strings. You could use a shell script to handle splitting the items, e.g.:
```
spec:
  arguments:
    parameters:
      - name: custom_arguments
        default: "--batch=1 --ckpt=another_value"
  templates:
    - name: main
      container:
        command: ["sh", "-c"]
        args: ["main.py {{workflow.parameters.custom_arguments}}"]
```

**Reply by kworkbee** [reply]
I can't solve it directly, but I have to deal with it indirectly, right? Thank you for your answer.

**Comment by jswxstw** [comment]
Maybe, you can try using [expr](https://argo-workflows.readthedocs.io/en/latest/variables/#expression) to generate args.

**Reply by kworkbee** [reply]
I don't think this is going to be splitted into individual elements of the args array like using Go Template on the Helm chart.

**Reply by jswxstw** [reply]
If the number of elements in additionalArgs is fixed, you can directly use `split` to achieve this. Here is an example:
```YAML
metadata:
  name: expr-demo
spec:
  arguments:
    parameters:
      - name: shell
        value: "echo hello"
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: shell
            value: "{{workflow.parameters.shell}}"
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - "{{=split(inputs.parameters.shell,' ')[0]}}"
          - "{{=split(inputs.parameters.shell,' ')[1]}}"
```
