### DISCUSSION TITLE
Retry failure on failed workflow.

### DISCUSSION THREAD

**Discussion by zela-boya** [argoproj/argo-workflows#14078] [Q&A] [answered]
I ran a parallel workflow using withParam configuration. When a node fails, the overall status of the workflow is marked as failed. However, the phase field of this node remains 'Running'. It also triggers the hook that gets called when the workflow fails. When I try to retry it from the UI, it tells me that the node's state is 'Running', so it cannot be retry.
Argo Workflow: v3.5.11
Kubernetes: v1.25.16

```
        - - name: check-node
            templateRef:
              name: drain
              template: check-node
              clusterScope: true
            arguments:
              parameters:
                - name: type
                  value: "{{`{{item}}`}}"
                - name: token
                  value: "{{`{{steps.get-token.outputs.parameters.token}}`}}"             
            withParam: '["NetworkUnavailable","MemoryPressure","DiskPressure","PIDPressure","Ready"]'
```
