### DISCUSSION TITLE
Different behavior on output artifact between Argo v3.4 and Argo 3.6

### DISCUSSION THREAD

**Discussion by carolkao** [argoproj/argo-workflows#14082] [Q&A]
Hi team,

I'd like to consult a different behavior between Argo workflow v3.4 and v3.6. I'd like to know what is your expected behavior.

I have a workflowtemplate - `script-executor` with an optional artifact
```yaml
piVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: script-executor
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: script
        artifacts:
          - name: inputFile
            optional: true
            path: /tmp/inputFile
      outputs:
        artifacts:
          - name: resultFile
            optional: true
            path: '{{inputs.parameters.outputArtifactResultFilePath}}'
      script:
        image: 'debian:9.4'
        command: [ 'bash' ]
        source: '{{inputs.parameters.script}}'
```
I have an workflow - `randomly-output-artifact` reference it, and define an output artifact without `optional` property :
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: randomly-output-artifact
spec:
  templates:
    - name: main
      outputs:
        artifacts:
          - name: result
            from: "{{steps.run.outputs.artifacts.resultFile}}"
      steps:
        - - name: run
            templateRef:
              name: script-executor
              template: main
            arguments:
              parameters:
                - name: script
                  value: |
                    if [ "$((RANDOM % 2))" == "0" ]; then
                      echo "put 'hello' to output file"
                      echo "hello" > /tmp/output
                    else
                      echo "just echo hello"
                      echo "hello"
                    fi
```
The `run` step will sometimes have no output artifact.

In v3.4, no matter the `run` step produce output artifact or not, the `randomly-output-artifact` workflow can completed successfully (with or without output artifact). But in v3.6, it encounter error `Unable to resolve: "steps.run.outputs.artifacts.resultFile"`

Looks like in the old version, the `optional: true` characteristic will be auto propagate to the caller Workflow / WorkflowTemplate, but this feature is gone in the new version.

I'd like to know what is your expectation of such behavior.
