### DISCUSSION TITLE
Accessing the exit code of a template step in retryStrategy?

### DISCUSSION THREAD

**Discussion by kevinc3n** [argoproj/argo-workflows#14158] [Q&A] [answered]
I would like retryStrategy to only execute if a specific step returned an exitCode of 137. However, when I try to do it the way below, I get 
`unknown name steps (1:1) | steps['run-container-step'].exitCode == '137' | ^`.

Am I not accessing the exit code correctly?

```yaml
  - name: oom-example
    steps:
      - - name: compute-memory-step
          template: compute-memory
          arguments:
            parameters:
              - name: current-retry-value
                value: "{{retries}}"
      - - name: run-container-step
          template: run-container
          arguments:
            parameters:
              - name: memory
                value: "{{steps.compute-memory-step.outputs.result}}"
    retryStrategy:
      limit: "3"
      expression: "steps['run-container-step'].exitCode == '137'"
```
