### DISCUSSION TITLE
workflow template does not working

### DISCUSSION THREAD

**Discussion by beztebya666** [argoproj/argo-workflows#14177] [Q&A]
i have argo events which are triggering creating workflow thing which includes canary argo rollout (update service in k8s)

and in workflow template i have a such step:

```
    - container:
        args:
          - set
          - image
          - >-
            example=example.binary.org/example:0.0.2
          - '-n'
          - example
        command:
          - kubectl argo rollouts
        image: example.binary.org/argoproj/argo-rollouts:v1.8.0
      name: update-rollout
```

error: unknown command "argo" for "kubectl"

i tried already a lot of things, but cant win this error
