### DISCUSSION TITLE
workflow template does not working

### DISCUSSION THREAD

**Discussion by beztebya666** [argoproj/argo-workflows#14178] [Q&A]
i have argo events which are triggering creating workflow thing which includes canary argo rollout (update service in k8s)

and in workflow template i have a such step:

```
    - container:
        args:
          - set
          - image
          - >-
            example=example.binary.org/example:0.0.2
          - '-n'
          - example
        command:
          - kubectl argo rollouts
        image: example.binary.org/argoproj/argo-rollouts:v1.8.0
      name: update-rollout
```

error: unknown command "argo" for "kubectl"

or

Error (exit code 64): failed to find name in PATH: exec: "kubectl argo rollouts": executable file not found in $PATH

i tried already a lot of things, but cant win this error

**Comment by jalkjaer** [comment]
Split your command to an array instead of a single string
```
command:
          - kubectl
          - argo
          - rollouts
```
or 
```
command: ["kubect","argo", "rollouts"]
```
or 
move `argo` and `rollouts` to the `args` array, and just have `kubectl` as command

**Reply by static-moonlight** [reply]
... or use `script` instead of `container`:

```yaml
    - name: update-rollout
      script:
        image: example.binary.org/argoproj/argo-rollouts:v1.8.0
        command: [sh]
        source: kubectl argo rollouts [...]
```

I find that often easier to read an to maintain. The only requirement is that the image has a shell you can execute. This usually doesn't work with from-scratch images.
