### DISCUSSION TITLE
Git artifact - How to pass depth (int64) as input parameter

### DISCUSSION THREAD

**Discussion by bygui86** [argoproj/argo-workflows#14187] [Q&A]
Hi guys

I have an issue with the [git artifact](https://github.com/argoproj/argo-workflows/blob/main/examples/input-artifact-git.yaml).

I can't parameterise the `depth` with a value from `inputs.parameters`. So I don't know how to make work the example below:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: git-clone
spec:
  templates:
    - name: git-clone
      inputs:
        parameters:
          - name: path
          - name: repo_url
          - name: repo_revision
          - name: git_depth
        artifacts:
          - name: code
            path: "{{inputs.parameters.path}}"
            git:
              repo: "{{inputs.parameters.repo_url}}"
              revision: "{{inputs.parameters.repo_revision}}"
              usernameSecret:
                name: git-creds
                key: username
              passwordSecret:
                name: git-creds
                key: password
              depth: {{inputs.parameters.git_depth}}   # ERROR
      script:
        image: ubuntu
        command: [bash]
        source: |
          cd {{inputs.parameters.path}}
          git status
          ls -lh
        volumeMounts:
          - name: workdir
            mountPath: "{{inputs.parameters.path}}"
```

How can I pass an int/int64 as input parameter?

I googled around and someone was pointing to [this example](https://github.com/argoproj/argo-workflows/blob/main/examples/pod-spec-from-previous-step.yaml) but `podSpecPatch` is a string, not a structure.

Thanks a lot in advance for any help
