### DISCUSSION TITLE
Suspend & Timeout functionality in WorkflowTemplates currently incompatible?

### DISCUSSION THREAD

**Discussion by BenjaminCaffrey** [argoproj/argo-workflows#14193] [Q&A]
Hi everyone! We use Argo Workflows and utilize a Suspend + Resume pattern. We successfully followed the documentation for [Suspending](https://argo-workflows.readthedocs.io/en/latest/walk-through/suspending/) and that worked well:
```
templates:
  ...
  - name: this-is-my-suspend-template
    suspend: {}
 ```
We suspend until we programmatically call argo resume. We want to combine it with a timeout and followed the [Timeouts](https://argo-workflows.readthedocs.io/en/latest/walk-through/timeouts/) documentation to attempt to fail / abort a step created from this-is-my-suspend-template if it hasn't been programmatically resumed after a certain time:
```
templates:
  ...
  - name: this-is-my-suspend-template
    suspend: {}
    activeDeadlineSeconds: 10
 ```
This doesn't seem to work. Does this feel like an issue? Is there any documentation that states these two concepts are incompatible? Seems like there is a workaround [here](https://github.com/argoproj/argo-workflows/discussions/8365), I'm wondering if it's natively supported. Thank you!
