### DISCUSSION TITLE
Modify Running Workflow/Retry with Revisions

### DISCUSSION THREAD

**Discussion by jrussell9000** [argoproj/argo-workflows#14251] [General]
I feel like I'm missing something very obvious here but...

Given that failed workflows can be restarted from individual nodes, is it possible to _modify_ the templates for those nodes without restarting the entire workflow? For example, if a node step in my workflow fails because I'm a terrible coder who makes lots of mistakes, is it possible to modify the code (i.e., template) for the failed node and then try to restart it (versus the entire workflow?  I don't see a way to do this in the UI, and if I simply update the a workflow template using the CLI, it doesn't seem to change the failed workflow if I try to restart it.  Thoughts???

**Comment by static-moonlight** [comment]
If you define everything within the workflow itself, this is the behavior I would expect. Then you would need to resubmit it. However, there is a way to kind of support what you want.

So, instead of doing this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow
  namespace: my-namespace
spec:
  entrypoint: my-entrypoint
  [...]
  templates:
    - name: my-entrypoint
      dag:
        tasks:
          - name: do-something
            template: do-something
    - name: do-something
      script:
        image: docker.io/busybox:latest
        command: [sh]
        source: echo "whatever"
```

... you can define the workflow steps in a separate template, and reference them like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-templates
  namespace: my-namespace
spec:
  templates:
    - name: do-something
      script:
        image: docker.io/busybox:latest
        command: [sh]
        source: echo "whatever"
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow
  namespace: my-namespace
spec:
  entrypoint: my-entrypoint
  [...]
  templates:
    - name: my-entrypoint
      dag:
        tasks:
          - name: do-something
            templateRef:
              name: my-templates
              template: do-something
```

`my-templates` acts as a library. If you change whatever `do-something` is doing and redeploy `my-templates`, I found that it has immediate effect to existing workflows like `my-workflow`. Then a retry of a failed `do-something` should use the updated template definition. This is limited to the internal details of `do-something` though. If you change its interface, like adding another input parameter, then strange things might happen and you need to resubmit the entire workflow anyway.
