### DISCUSSION TITLE
argo workflow Cannot transition token types from UNKNOWN [<nil>] to COMPARATOR [!=]

### DISCUSSION THREAD

**Discussion by nmingmei** [argoproj/argo-workflows#14272] [General]
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: exit-handlers
spec:
  entrypoint: exit-handler
  templates:
  - name: exit-handler
    steps:
    - - name: update-db-upon-failure
        template: update-db-upon-failure
        when: ' {{ printf "%s" "{{" }}workflow.status}} != Succeeded '
  - name: update-db-upon-failure
    container:
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      command: [ "python", "-u", "-c" ]
      args:
        - 'training.argo.run_db.py {{ printf "%s" "{{" }}run_id}} {{ printf "%s" "{{" }}user_id}}'
```

full error: Invalid 'when' expression ' != Succeeded ': Cannot transition token types from UNKNOWN [<nil>] to COMPARATOR [!=]

i tried when: '{{workflow.status}} != Succeeded'
i tried using double quotes, single quotes, removing the printf etc, nothing works.
Removing the printf results in it not finding "workflow"

**Comment by nmingmei** [comment]
if I try with 
when: '{{workflow.status}} != Succeeded'

(with either double or single quotes)

this happens: 

Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template 890-fix --namespace 890-fix --kube-version 1.28 --values /tmp/2aa609d9-aaca-476a-bf6a-61561452313c <api versions removed> --include-crds` failed exit status 1: Error: parse error at (svc/templates/argo_exit_handler.yaml:12): function "workflow" not defined Use --debug flag to render out invalid YAML

**Comment by static-moonlight** [comment]
Honestly, this looks crazy :D

```yaml
when: ' {{ printf "%s" "{{" }}workflow.status}} != Succeeded '
```

I'm not sure what the `printf` is for. Maybe you want to try to simplify your expression. In one of my workflows I'm doing this, and it's working fine:

```yaml
    - name: exit-handler
      dag:
        tasks:
          - name: do-something
            when: "{{ workflow.status }} == Succeeded"
            [...]
```

**Comment by static-moonlight** [comment]
Oh, I might see the problem.

The workflow variable `workflow.status` is only available for the exit handler, see the [documentation](https://argo-workflows.readthedocs.io/en/latest/variables/#exit-handler). Your task template `exit-handler` is used as `entrypoint`. Despite the name, it's just a task template like any other. So you need to define something else as `entrypoint`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: exit-handlers
spec:
  entrypoint: do-something
  onExit: exit-handler
  [...]
```
