### DISCUSSION TITLE
Unable to convert   /tmp to  PersistentVolumeClaim  as tmp-dir-argo is already defined. It becomes empty folder volume

### DISCUSSION THREAD

**Discussion by energgumeno** [argoproj/argo-workflows#14294] [Q&A]
Hello!

I have this workflow that it is supposed to mount a persistent volume to /temp folder but it does not:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scale-pods-to-0-by-tag
spec:
  entrypoint: scale-pods

  volumes:
    - name: tmp-dir-argo
      persistentVolumeClaim:
        claimName: results-volume  

  templates:
    - name: scale-pods
      steps:
        - - name: get-pods
            template: get-pods
        - - name: scale-pods-step
            template: scale-pods-action
            arguments:
              parameters:
                - name: pod-list
                  value: "{{steps.get-pods.outputs.result}}"

    - name: get-pods
      script:
        image: bitnami/kubectl:latest
        command: ["/bin/sh"]
        source: |
          #!/bin/sh
          echo "hello"

    - name: scale-pods-action
      inputs:
        parameters:
          - name: pod-list
      script:
        image: bitnami/kubectl:latest
        command: ["/bin/sh"]
        source: |
          #!/bin/sh
          pwd
          mkdir -p /tmp/results
          output_file="/tmp/results/pods_scaled_to_0_$(date +\%d_\%m_\%Y_\%H_\%M_\%S).tx
	  echo "..." >> $output_file
      volumeMounts:
        - name: tmp-dir-argo
          mountPath: /tmp  
```

But for some reason (I suppose the template) the workflow is creating these volumes and forcing the /temp folder to be an empty volume.  I would like to save the output of the workflow to a persistent volume but I dont see any way to do it _as the image is too safe to mount a volume in any other folder_ XD

```
Volumes:
  var-run-argo:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tmp-dir-argo:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  my-minio-cred:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  my-minio-cred
    Optional:    false
  argo-staging:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
```

Is there any way to override this tmp-dir-argo volume property?  maybe there is a folder that I can mount and is be RW for this proposes or a workaround?
thanks in advanced!

**Comment by static-moonlight** [comment]
Can't you just pick a different name, other than `tmp-dir-argo`?

**Reply by energgumeno** [reply]
Hello @static-moonlight ,
Thanks, but the problem is that tmp-dir-argo declared in the template overrides the volumes I create for tmp, I suppose to not modify the pod state in every execution. I tried with different names but with no luck.

**Reply by static-moonlight** [reply]
I noticed, that your `volumes` and `volumeMounts` definitions seems to be in a strange spot. Here an example from one of my workflows:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-templates
spec:
  templates:
    - name: import-data
      container:
        image: my-image
        command: [import]
        volumeMounts:
          - name: data
            mountPath: /tmp/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
```

- `volumes` is defined on the same level as `container` (or `script`)
- `volumeMounts` is defined inside the `container` (or `script`) block
