### DISCUSSION TITLE
ArgoCD Auth + Argo Workflows SSO Returning 404

### DISCUSSION THREAD

**Discussion by SomniVertix** [argoproj/argo-workflows#14310] [Q&A]
Im trying to set up argo workflows to work with arogcd and I get a 404 not found when argo workflows tries to redirect me to argo. I tried following this guide:
https://argo-workflows.readthedocs.io/en/latest/argo-server-sso-argocd/#example-helm-chart-configuration-for-authenticating-against-argo-cds-dex
But im not sure whats possibly incorrectly set in my argocd values

```
      dex.config: |
        connectors:
          - name: oidc
            type: oidc
            id: oidc
            config:
              issuer: < redacted >
              clientID: argocd.east.high
              clientSecret: < redacted >
              insecureEnableGroups: true
              scopes:
                - openid
                - profile
                - email
              getUserInfo: true
        staticClients:
        # This is the OIDC client ID in plaintext
        - id: argo-workflows-sso
          name: Argo Workflow
          redirectURIs:
            - < redacted >/oauth2/callback
          secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```

The URL that I get redirected to from workflows is this: `https://<argocd url>/api/dex/<argo workflows url>/oauth2/callback` which is weird...

Any help here?
