### DISCUSSION TITLE
No custom metrics for Workflows ending in "error" status

### DISCUSSION THREAD

**Discussion by JeanRev** [argoproj/argo-workflows#14332] [Q&A]
Hi there,

We use cusom-metrics to detect the termination status of workflows. For the moment, we are limiting ourselves to the workflow statuses “Succeeded” and “Failed”, which works quite well. However, we have noticed that workflows with an "error" status do not seem to produce custom metrics. We are currently using the following setup(which is very similar to the example referenced in the issue https://github.com/argoproj/argo-workflows/issues/10662):
```yaml
metrics:
        prometheus:
          - name: failed_gauge
            labels:
              - key: namespace
                value: "{{ workflow.namespace }}"
              - key: workflow
                value: "{{ workflow.labels.app.kubernetes.io/name }}"
            help: Failed gauge for individual workflows
            when: "{{ status  }} == Failed || {{ status }} == Error"
```

We have tested this by creating an invalid configuration that does not allow the creation of init/main containers.
![image](https://github.com/user-attachments/assets/313cff60-b2cd-4523-a14a-e881761b2b58)

There must certainly be situations where an erroneous workflow cannot generate metrics (in the event of a major problem with the workflow controller, for example). But in this example, I would still expect the gauge to be updated.

Or I am missing something ?
