### DISCUSSION TITLE
Is it possible to retry a node and override its parameters ?

### DISCUSSION THREAD

**Discussion by k3rnL** [argoproj/argo-workflows#14351] [Q&A]
Hello !

In my workflow I would have a big DAG, and because the world isnt everyday great, some node may fail.
In such case I would need to retry a node and I may want to override one of the parameter that was given to it from upper nodes.

In this image it shows a successful node, but it does not matter, the override window does not propose te retry the last node with any other parameter.
![image](https://github.com/user-attachments/assets/19607e14-f117-4df8-ac13-3ad69783c9ab)

I would expect "hello2a" to be overridden with another "message"

I know that I can add a workflow parameter, and then use `{{workflow.parameters.message}}`, but that is irrelevent inmy use case as make jobs shares the same parameter name with different value. And also some parameters are generated from intermediary steps.

Is that an expected behavior ? Or am I doing something wrong ?

Thanks

```
spec:
  templates:
    - name: hello-hello-hello
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: make-json
            template: make-json
            arguments: {}
        - - name: hello2a
            template: print-message
            arguments:
              parameters:
                - name: message
                  value: "{{=default(jsonpath(steps['make-json'].outputs.parameters.json,'$.test-\
                    nope'), '')}}"
    - name: print-message
      inputs:
        parameters:
          - name: message
            default: DEFAULT_VAL
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: busybox
        command:
          - echo
        args:
          - "{{inputs.parameters.message}}"
        resources: {}
    - name: make-json
      inputs: {}
      outputs:
        parameters:
          - name: json
            valueFrom:
              path: /tmp/output
      metadata: {}
      script:
        name: ""
        image: ubuntu:latest
        command:
          - bash
        resources: {}
        source: |
          echo '{"test": 123, "test-nope":1}' > /tmp/output
  entrypoint: hello-hello-hello
```
