### DISCUSSION TITLE
Output gets archived despite `archive: none` configuration

### DISCUSSION THREAD

**Discussion by subesokun** [argoproj/argo-workflows#14370] [Q&A]
I'm trying to upload workflow output directly to Azure Blob Storage without archiving it first. I've configured my `outputs` section with `archive: none`, but the logs still indicate that Argo is attempting to tar and archive the output directory.  What am I missing in my configuration?

Docs: https://github.com/argoproj/argo-workflows/blob/8793d8893b68ca81800ff9c3512780636ed733cd/docs/artifact-visualization.md?plain=1#L37

```yaml
outputs:
  artifacts:
    - name: outputblob
      path: /output/myfolder
      archive:
        none: {}
      azure:
        endpoint: https://mystorage.blob.core.windows.net
        container: argo-artifactory
        blob: "{{workflow.name}}/artifacts/myfolder/"
        accountKeySecret:
          name: azure-user
          key: azure-user-key
```

Here are the relevant log entries showing the archiving behavior:

```
time="2025-04-10T07:15:03.694Z" level=info msg="/output/myfolder -> /var/run/argo/outputs/artifacts/output/myfolder.tgz" argo=true
time="2025-04-10T07:15:03.694Z" level=info msg="Taring /output/myfolder"
time="2025-04-10T07:17:12.305Z" level=info msg="archived 841 files/dirs in /output/myfolder"
```
