### DISCUSSION TITLE
How can I pass 1st step output in 2nd step in json

### DISCUSSION THREAD

**Discussion by sonamdolphin9192** [argoproj/argo-workflows#14402] [Q&A]
How can I pass 1st step multiple output in 2nd step in json:
How can I pass 1st step output in 2nd step input? 
Getting error while reading metadata.

```
 - name: select-inputs
      arguments:
        parameters:
          - name: target-cluster
            value: "<value>"
          - name: target-chart-path
            value: "<value>"
          - name: argo-values-target-environment-new-name
            value: "optional(mandatory for new environment)"
      templateRef:
        name: tempalte_name
        template: any_template
        
    - name: update-analytics-workflow-upsert
      templateRef:
  name: geme-v2-analytics-templates
  template: analytics-workflow-upsert
arguments:
  parameters:
    - name: workflow-status
      value: "In progress"
    - name: metadata
        value: '{{`{"target-cluster": "{{ default "NA" .tasks.select-inputs.outputs.parameters.target-cluster }}", "region": "{{ default "NA" .tasks.select-inputs.outputs.parameters.target-chart-path}}"} `}}'
depends: select-inputs.Succeeded
```
