### DISCUSSION TITLE
How to hide secret values in Inputs and Outputs parameters shown on UI in Argo Workflows ?

### DISCUSSION THREAD

**Discussion by sukhbir-singh** [argoproj/argo-workflows#14438] [General]
My requirements is that I am taking some secrets as inputs from user, that can be access-token or api-key for an example. Now as soon as we take an input and pass it in next step as input, it will be shown in plain text in the UI. I wanted to hide the secrets from input and output parameters for each of the pods shown in the workflow. How can I do it?

I went through the docs and various tutorials but could not find any such reference for doing it. If someone having some idea how to solve and can help, then that would be great.

By hiding the secret, I mean not even showing in UI even through the secret parameters are getting passed as inputs Or other way could be to write SECURE instead. Anything is fine by mean, I just do not want to show to secret to user.

As an example, In below template, I want to hide the api-key parameter from input and output of each pods.

Argo Workflow Example:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-hello-world-
spec:
  entrypoint: hello-world
  ttlStrategy:
    secondsAfterCompletion: 72000  # Pods will be deleted 20 hours after workflow completion
  templates:
  - name: hello-world
    steps:
      - - name: task-ask-whale
          template: whale-say
          arguments:
            parameters:
            - name: message
              value: "hello world"
            - name: api-key
              value: "{{workflow.parameters.api-key}}"
  
  - name: whale-say
    inputs:
      parameters:
        - name: message
        - name: api-key
    container:
      image: docker/whalesay:latest
      command: ["cowsay"]
      args: ["echo", "{{inputs.parameters.message}}"]
```
