### DISCUSSION TITLE
Get secret mounted as env variable in http template

### DISCUSSION THREAD

**Discussion by m-kay** [argoproj/argo-workflows#14469] [Q&A] [answered]
Is it somehow possible to get a secret mounted as env variable when using the http template? I would like to use that to pass a token into the Authorization header. I have already tried to use `podSpecPatch` as follows: 
```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-wft
spec:
  entrypoint: start
  templates:
    - name: start
      podSpecPatch: |
        containers:
          - name: main
            env:
              - name: "PAT"
                valueFrom:
                  secretKeyRef:
                    name: service-user
                    key: pat
      steps:
        - - name: call-api
            template: http
    - name: http
      http:
        url: http://myhost/api
        body: '{ "message": "Hello World!" }'
        headers:
          - name: Authorization
            value: Bearer {{sprig.env("PAT")}}
          - name: Content-Type
            value: application/json
        method: POST
        successCondition: response.statusCode == 200
```

Unfortunately the patch seems not to be applied for agent pods created for the http template.

The only solution I found so far is to use `valueFrom` in the headers, as mentioned in #9369. However this requires the secret to also contain the Bearer prefix, which is not the case for me.

Any other idea how to achieve that? Thanks already for your answers.

**Comment by jswxstw** [comment, marked as answer]
Only workflow-level `podSpecPatch` can be applied to the agent pod, however, header value cannot support expression, so `Bearer {{sprig.env("PAT")}}` will not work.
I think currently the only way to meet your needs is to directly create a secret containing `Bearer ${token}`.

**Reply by m-kay** [reply]
Hmm I think expressions work on header value because I'm also using this which works perfectly fine:
```
      http:
        url: http://some-host/api
        headers:
          - name: X-Idempotency-Key
            value: '{{=sprig.uuidv4()}}'
```
