### DISCUSSION TITLE
Use local registry (HTTP)  with ArgoWrokflows

### DISCUSSION THREAD

**Discussion by philippeflorent** [argoproj/argo-workflows#14650] [General]
[sorry not a bug, more of a question]

Hi,

I try to use one of my docker image on my custom registry and I get this error

```
https://argo-workflows.readthedocs.io/en/latest/workflow-executors/#emissary-emissary: 
Get "https://mycluster-registry:5000/v2/": dial tcp 127.0.0.1:5000: 
connect: connection refused
```

So I added the host alias to the workflow-controller deployment 

```
kubectl -n argo edit deployment workflow-controller
```

```
    hostAliases:
      - hostnames:
        - mycluster-registry
        ip: [REDACTED (my pc local ip)]
```

but now I get this

```
https://argo-workflows.readthedocs.io/en/latest/workflow-executors/#emissary-emissary: 
Get "https://mycluster-registry:5000/v2/": 
http: server gave HTTP response to HTTPS client
```

**So I need to have the workflow-controller use my local registry in HTTP, how can I do this ?**

here is the workflow I try to use (I tried to add mycluster-registry 172.17.0.2 to the emissary pod)

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
spec:
  entrypoint: workflow-and-generate-signal-files
  serviceAccountName: argo-workflow-sa

  templates:
  - name: workflow-and-generate-signal-files
    dag:
      tasks:
      - name: app1-workflow-py--1-2
        template: app1-workflow-py-tpl--1-2

  - name: app1-workflow-py-tpl--1-2
    container:
      image: mycluster-registry:5000/workflow:latest
```

I create my registry like this
```
docker run -d -p 5000:5000 --name mycluster-registry --restart=always -v registry-data:/var/lib/registry registry:2
kubectl apply -f registry-service.yaml
```

registry-service.yaml
```
apiVersion: v1
kind: Endpoints
metadata:
  name: mycluster-registry
subsets:
  - addresses:
      - ip: [REDACTED (my pc local ip)]
    ports:
      - port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mycluster-registry
spec:
  ports:
    - port: 5000
      targetPort: 5000
```

Here is how I start my minikube
```
cmd.exe /c minikube start --driver=docker --container-runtime=containerd --insecure-registry=mycluster-registry:5000
```

### Version(s)

latest

no logs available the worlkflow does not even start
