### DISCUSSION TITLE
"parallelism" field can't be added in templates referenced inside a dag

### DISCUSSION THREAD

**Discussion by d-e-solutions** [argoproj/argo-workflows#4713] [Q&A] [answered]
## Summary 

I am trying to create a workflow using a DAG template referencing other templates. 

```yaml
spec:  
  entrypoint: dag-template
  templates:
    - name: task-1-template
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: task-2-template
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: dag-template
      dag:
        tasks:
          - name: task-1
            template: task-1-template
          - name: task-2
            template: task-2-template
            dependencies:
              - task-1
```

In this workflow, I need to have a task (let's say task-1) that is parallelized with max 5 tasks at the same time, while another needs to be parallelized with max 10 tasks at the same time.

When I try to add `parallelism` field inside `task-1-template`, I get the following error:
```
Internal Server Error: templates.dag-template.tasks.task-1 templates.task-1-template.parallelism is only valid for steps and dag templates
```

When looking at the [documentation](https://argoproj.github.io/argo/fields/#templateref), `parallelism` is an attribute of a template object. Furthermore, it is called from a dag, and so fits with the `dag template` description. I would then expect that my use case is possible.

## Diagnostics

What Kubernetes provider are you using? Rancher (k8s v1.16.8)

What version of Argo Workflows are you running? v2.11.6

To reproduce the behavior : 

```yaml
spec:  
  entrypoint: dag-template
  templates:
    - name: task-1-template
      parallelism: 1
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: task-2-template
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: dag-template
      dag:
        tasks:
          - name: task-1
            template: task-1-template
          - name: task-2
            template: task-2-template
            dependencies:
              - task-1
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
try:

```yaml
spec:  
  parallelism: 1
  entrypoint: dag-template
```

**Comment by d-e-solutions** [comment]
This doesn't match my use case. I would like to have different parallelism values for the 2 tasks. For now I didn't find a way to have that.

Example:

```
spec:  
  entrypoint: dag-template
  templates:
    - name: task-1-template
      parallelism: 1
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: task-2-template
      parallelism: 10
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: dag-template
      dag:
        tasks:
          - name: task-1
            template: task-1-template
          - name: task-2
            template: task-2-template
            dependencies:
              - task-1
```

**Comment by jessesuen** [comment, marked as answer]
```yaml
  templates:
    - name: task-1-template
      parallelism: 1
      container:
        image: 'python:alpine3.6'
```

As the error message indicates, parallelism is valid on dag or steps. You are attempting to put it on a single container template which by definition, cannot have parallelism.

I think you want this:

```yaml
    - name: dag-template
      dag:
        parallelism: 10
        tasks:
          - name: task-1
            template: task-1-template
          - name: task-2
            template: task-2-template
            dependencies:
              - task-1
```

**Comment by d-e-solutions** [comment]
Thank you for your answer. 

Ok so I suppose my use case is impossible with Argo then. I think it is valid because you could have steps that require really different amount of resources from the cluster : 
- a small step that you want to parallelize as much as you can
- a resource intensive step that you want to run with a smaller parallelism

In that case, the whole DAG would be run with the maximum of the two, that will not match the requirements of the 2nd type of step.

I will create a feature request on Monday for this.

**Reply by jessesuen** [reply]
I think you misunderstand some of the template concepts. A container step is a leaf, and is not possible to expand. Thus, it is not possible to parallelize this. We have two levels of parallelism inside a workflow spec:

1. workflow level (`spec.parallelism`)
2. dag or steps level (`spec.templates.TEMPLATENAME.parallelism`)

Your use case should be possible to be handled by controlling parallelism at a dag or steps level. But to attempt to apply a parallelism on a *container* template, just doesn't make sense since by definition there is only one.

**Reply by d-e-solutions** [reply]
Ok thanks for the precisions, I was indeed confused with the concept of template. But then what about this ? 

```
spec:  
  entrypoint: dag-template
  templates:
    - name: task-1-template
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: task-2-template
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: dag-template
      dag:
        tasks:
          - name: task-1
            parallelism: 1
            template: task-1-template
            # parallelized with `withItems` or `withParam`
          - name: task-2
            parallelism: 10
            template: task-2-template
            # parallelized with `withItems` or `withParam`
            dependencies:
              - task-1
```

Tasks can be parallelized, so I think I should be able to parallelize them differently, considering how I want to scale each task.

Now, I simply can't do that because `parallelism` would be put at dag level and all the tasks would inherit from it.

**Reply by jessesuen** [reply]
> Now, I simply can't do that because parallelism would be put at dag level and all the tasks would inherit from it.

In order to accomplish your use case, you will need to have the DAG call another DAG, which only contained the `withItems` that you allow to run in parallel.

```yaml
  templates:
    - name: task-1-template
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: task-2-template
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: dag-template
      dag:
        tasks:
          - name: child-1
            template: child-1-template
          - name: child-2
            template: child-2-template
            dependencies:
              - child-1
    - name: child-1-template
      dag:
        parallelism: 1
        tasks:
          - name: task-1
            template: task-1-template
            # parallelized with `withItems` or `withParam`
    - name: child-2-template
      dag:
        parallelism: 10
        tasks:
          - name: task-2
            template: task-2-template
            # parallelized with `withItems` or `withParam`
```

**Reply by ognjen-it** [reply]
I think you have a typo. parallelism should be in the same line with dag

```
    - name: child-2-template
      dag:
        parallelism: 10
        tasks:
          - name: task-2
            template: task-2-template
            # parallelized with `withItems` or `withParam`
```

```
    - name: child-2-template
       parallelism: 10
       dag:
         tasks:
          - name: task-2
            template: task-2-template
            # parallelized with `withItems` or `withParam`
```
