### DISCUSSION TITLE
Workflows not deleted even though TTL is set?

### DISCUSSION THREAD

**Discussion by simonfrey** [argoproj/argo-workflows#4788] [Q&A]
Even though I set `secondsAfterCompletion` in the workflow-controller-configmap to `5` I still end up with piles of workflows:
```yaml
workflowDefaults:
  spec:
    activeDeadlineSeconds: 28800
    ttlStrategy:
      secondsAfterCompletion: 5
    podGC:
      strategy: OnWorkflowSuccess
```
After applying the config map with these defaults, I did run a workflow and it is not getting removed :/ 
```
> argo --namespace argo list 
NAME                            STATUS   AGE   DURATION   PRIORITY
by-name-dpx2q             Failed   5m    46s        0
subworkflow-5ks97   Failed   5m    26s        0
```

Anyone any idea, what the problem here could be? When I manually remove the workflows with `argo --namespace argo delete --older 5m` it works.
