### DISCUSSION TITLE
From the same workflow definition get a dynamic value depending on the argo environment

### DISCUSSION THREAD

**Discussion by sylock** [argoproj/argo-workflows#4932] [Q&A]
Hi,

I have 2 argo environments : dev and prod, installed on separated clusters. I would like to get the value "PROD" or "DEV" depending on my environment as an argument parameter for one of my cluster workflow. I don't know how to do this. Where and how should I store that value? (artifact, configmap, env ...) and how can I retrieve it from a clusterWorfklow?

Thank you,

**Comment by alexec** [comment]
I think you could just have this is a config map?

**Comment by sylock** [comment]
Yes but a config map is namespace isolated. I run the workflows on multiple namespaces (it's a report cluster-workflow). I would like to find a "cluster-wide" place where to store the value (from any namespace). Or an environment variable set for any pod run by argo. Or any other solution I don't see.
In the contrary, I will need to maintain the same key/value consistent across multiple namespaces/configmap. Which have a probability to become inconsistent with time.
ps: I'm asking for a best practice or something usually seen or used.

**Comment by alexec** [comment]
Ah. So you want every pod to know it is in production or dev. An env variable would work well. This is a great idea! Would you like to raise a PR to add this feature?

**Comment by alexec** [comment]
@sarabala1979 suggests this:

Use workflow defaults to set an envvar for all main pods.

```yaml
workflowDefaultSpec: |
  spec:
    podSpecPatch: |
       spec:
         containers:
           - name: main
              env:
                -  name: ENVIRONMENT 
                   value: production
```

Or something like that.

**Comment by sylock** [comment]
It looks like a very good idea but:
* I tried and it doesn't work
* It is undocumented (I see an announce on 2.4 release, but cannot see any information about workflowDefaultSpec or podSpecPatch in the doc)

Here is the piece of code:

I added the piece of code just below the "workflowDefaults" that was already configured:

```
kind: ConfigMap
metadata:
apiVersion: v1
data:
  name: workflow-controller-configmap
    workflowDefaults: |
      spec:
        ttlStrategy:
          secondsAfterCompletion: 1800
    workflowDefaultSpec: |
      spec:
        podSpecPatch: |
          spec:
            containers:
            - name: main
                env:
                - name: MYENV
                  value: MYVALUE
```

A mini workflow to test:

```
metadata:
  name: check-env-wf
spec:
  templates:
    - name: check-env
      container:
        name: main
        image: 'alpine:3.12'
        command:
          - env
  entrypoint: check-env
```

**Comment by softwarebloat** [comment]
@alexec I'm also interested in doing something similar!
that's what i tried:

ConfigMap:
```yaml
apiVersion: v1
data:
  mykey: myval
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-13T10:10:11Z"
  name: test-map
  namespace: data
  resourceVersion: "183589566"
  selfLink: /api/v1/namespaces/data/configmaps/test-map
  uid: dea5b366-fc90-4f4e-bb9b-3cf1e2b7abe5
```

Workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: configmap-test-
spec:
  entrypoint: whalesay
  serviceAccountName: argo-workflow
  arguments:
      parameters:
      - name: configmap
        value:
          configMapKeyRef:
            name: test-map
            key: mykey
  templates:
  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{workflow.parameters.configmap}}"]
 ```

But this doesn't work. The template prints an empty string. I guess it's because `configMapKeyRef` is supported only in `valueFrom` field

EDIT:
I saw this [closed PR](https://github.com/argoproj/argo-workflows/pull/4427). i'm pretty new to the project and never coded in Go. anyone wants to continue the work on that PR together? :smiley:
