### DISCUSSION TITLE
What's the difference between `inputs` and `arguments`?

### DISCUSSION THREAD

**Discussion by sylock** [argoproj/argo-workflows#4995] [Q&A] [answered]
I don't understand the difference between both and I don't see any discussion about it in the documentation.
Can you explain the functional difference and if there is a best practice?

**Comment by agilgur5** [comment, marked as answer]
Got linked to this [from Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1723646127184599?thread_ts=1723633650.106499&cid=C01QW9QSSSK).

For expressions, `inputs` are for template-level parameters. `arguments` are for Workflow-level parameters.
That's why you reference them as the [variables](https://argo-workflows.readthedocs.io/en/release-3.5/variables/) `inputs.parameters.myparameter` and `workflow.parameters.myparameter`.

For the field names themselves, the ["Parameters" docs page](https://argo-workflows.readthedocs.io/en/release-3.5/walk-through/parameters/) describes it:
```yaml
  templates:
  - name: print-message
    inputs:
      parameters:
      - name: message       # parameter declaration
```
The field `templates[0].inputs.parameters` is a declaration, whereas `arguments.parameters` is the actual usage:
```yaml
  arguments:
    parameters:
    - name: message
      value: hello world
```

This follows function naming in programming, see also [MDN: "Parameters vs Arguments"](https://developer.mozilla.org/en-US/docs/Glossary/Parameter#parameters_versus_arguments) and the [Wikipedia article on it](https://en.m.wikipedia.org/wiki/Parameter_(computer_programming)#Parameters_and_arguments), as well as various SO questions for various languages and language-agnostic variations of the sams question.

Argo also has `artifacts` that can appear at the same level as `parameters` to be distinguished against.
