### DISCUSSION TITLE
X509 certificates with SSO issuer

### DISCUSSION THREAD

**Discussion by LeJav** [argoproj/argo-workflows#5079] [Q&A] [answered]
Hello,

I am using argo workflow with SSO and OpenId Connect (implemented with keycloak).
It is working fine when everything is http.
But when going with https I have a problem with issuer.
server crashes because keycloak certificate authority is not known:
```
 msg="Get https://xxxxxxxxx/auth/realms/master/.well-known/openid-configuration: x509: certificate signed by unknown authority"
```

How to solve it?
I have not found any option in order to ignore SSL verification.
Will it work if I set the CA cert in configmap and mount it under `/etc/ssl/certs`?

Thanks for your advices.

**Comment by LeJav** [comment, marked as answer]
For those who have the same problem, I have solved it by setting the ca cert in a configmap and mounting it in a file under ```/etc/ssl/certs```

**Reply by yogendramummaneni** [reply]
I am also seeing the same issue even after following the below steps:

1. Added a configmap
2. Updated the values.yaml with below and tried to install the helm chart and pod is going into `CrashLoopBackOff` state, logs are below:
```yaml
  volumeMounts:
     - name: certificate
       mountPath: /etc/ssl/certs/rootCA.crt # your self-signed CA part inside the secret
       #subPath: ca.crt
  volumes:
     - name: certificate
       configMap:
          name: configcert
```

```
kubectl logs -f argo-keyclock-argo-workflows-server-66d6b99ffc-n7rn2 -n argo
time="2022-07-13T15:34:32.128Z" level=info msg="config map" name=argo-keyclock-argo-workflows-workflow-controller-configmap
Error: Get "https://keycloak.xxx-xxxx.com/auth/realms/argocd/.well-known/openid-configuration": x509: certificate signed by unknown authority
Usage:
  argo server [flags]

Examples:
See https://argoproj.github.io/argo-workflows/argo-server/
```

Any idea what mistake I am doing here? 

Thanks inadvance.

**Reply by LeJav** [reply]
How is your configmap?
On my side I have a key for the crt and I have set subPath.

**Reply by yogendramummaneni** [reply]
@LeJav Thanks for the reply!

Now I created a key using this command: 
```
kubectl -n argo create configmap custom-root-cert --from-file=ca-cert=/home/dell/dev-vm/certs/rootCA.crt
```

and mounting like this inside values.yaml
```yaml
  volumeMounts:
    - name: certificate
      mountPath: /etc/ssl/certs/rootCA.crt # your self-signed CA part inside the secret
      subPath: ca-cert

  volumes:
    - name: certificate
      configMap:
        name: custom-root-cert
```

Still unable to mount the certificate under `/etc/ssl/certs/rootCA.crt`. The file `rootCA.crt` is being created as empty. I have checked on the overlay file system.

```
root@kube-cp01:~# cd /var/lib/docker/overlay2/067e664b1eba818203e95bd3a70097ed156899fd7215ec4e666133ca9262d34c/merged
root@kube-cp01:/var/lib/docker/overlay2/067e664b1eba818203e95bd3a70097ed156899fd7215ec4e666133ca9262d34c/merged# ls
bin  dev  etc  home  proc  sys  tmp  var
root@kube-cp01:/var/lib/docker/overlay2/067e664b1eba818203e95bd3a70097ed156899fd7215ec4e666133ca9262d34c/merged# cd etc/ssl/certs/
root@kube-cp01:/var/lib/docker/overlay2/067e664b1eba818203e95bd3a70097ed156899fd7215ec4e666133ca9262d34c/merged/etc/ssl/certs# ls
ca-certificates.crt  rootCA.crt
root@kube-cp01:/var/lib/docker/overlay2/067e664b1eba818203e95bd3a70097ed156899fd7215ec4e666133ca9262d34c/merged/etc/ssl/certs# more rootCA.crt
root@kube-cp01:/var/lib/docker/overlay2/067e664b1eba818203e95bd3a70097ed156899fd7215ec4e666133ca9262d34c/merged/etc/ssl/certs#
```

Any ideas what could be the wrong here?

**Reply by LeJav** [reply]
Hello,
Your configuration seems correct.
It is normal that you do not see it when looking into `/var/lib/docker/overlay2/...` as it is mounted.
Can you check inside the pod? `kubectl exec -it .... -- sh` and check if you see your certificate under `/etc/ssl/certs`

**Comment by sarabala1979** [comment]
Fixed in https://github.com/argoproj/argo-workflows/commit/ae7eeeb50dd0b7640913e7b30d1fe612c7e0ee4c
I am releasing 3.1.10 today

**Comment by peteroruba** [comment]
@sarabala1979 thanks for your response, however, I deleted my question, because it turned out I used the wrong certificate. With the correct one the procedure as explained by @LeJav worked for me as well.

**Reply by chenbr** [reply]
did you change the deployment to use the configmap? do you have an example?

**Comment by LeJav** [comment]
I have currently no access to my configuration.
I will describe next week the modifications I have done to the Helm chart in order to mount the cert configmap in the pod.

**Comment by sharadhirao** [comment]
Hi @LeJav 
I have created config map as: 
``` kubectl -n argo create configmap custom-root-cert --from-file=ca-cert=rootCA.crt ```

and my values.yal for volume looks like this:
```yaml
volumeMounts:
- name: certificate
  mountPath: /etc/ssl/certs/rootCA.crt # your self-signed CA part inside the secret
  subPath: ca-cert

volumes:
- name: certificate
  configMap:
    name: custom-root-cert
```

still I am facing the issue of 509 error. Can you help where I am going wrong?

**Comment by xmsanchez** [comment]
I got the same issue. I got this working in another environment and mounting the certs in `/etc/ssl/certs` is working there. I don't undertstand why it doesn't work in the new environment.

```
Error: Get "https://dex.pre.example.com/.well-known/openid-configuration": x509: certificate signed by unknown authority
```

I double checked the CA certificates, in fact I can spin up a curl container and it works perfectly with the same CAs when querying the SSO endpoint.

Any idea on how to debug this further? Log level in debug mode and enabling --verbose does not help at all.

**Reply by xmsanchez** [reply]
I fixed it. In the end it was an issue with my CA bundle. I updated it properly and it works.

As suggested in the accepted answer you must mount it at `/etc/ssl/certs`

**Reply by Jaydee94** [reply]
Hey @xmsanchez,

I have the same issue with my Argo workflows setup. How did you fix your ca bundle?

I've created a configmap with my custom ca in pem format and mounted it into /etc/ssl/certs/ca.crt

After a pod restart I still get the x509 certificate is signed by a unknown authority error.

Any ideas?

**Reply by Jaydee94** [reply]
Never mind. My ca bundle was also broken. The pem format was incorrect.
Works fine now.

**Reply by afer4152** [reply]
> ed a configmap with my custom ca in pem format and mounted it into /etc/ssl/certs/

@Jaydee94 Did you got fix this out?

**Comment by LeJav** [comment]
I am sorry but I am not working any more with the configuration with the certificates mounted in the pod.
I am really sorry but I cannot test and help...

**Comment by aydinseven7** [comment]
Another reminder since I had to debug a bit to get it to work:

- add the full chain
- mount it to `/etc/ssl/certs/`, don't add specific cert name

inside values.yaml:
```yaml
server:
  volumeMounts:
  - name: intermediate-ca
    mountPath: /etc/ssl/certs/
  volumes:
  - name: intermediate-ca
    secret:
      secretName: intermediate-ca
```

ca-secret.yaml:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: intermediate-ca
  namespace: argo
stringData:
  root-ca.crt: |
    CERT1
  intermediate-ca.crt: |
    CERT2
type: Opaque
```

**Reply by afer4152** [reply]
@aydinseven7 Could you please clarify on this. what would be the `CERT1` and `CERT2`? 
Are those from SSL certificate issue side values or something else?

**Reply by aydinseven7** [reply]
CERT1 and CERT2 are just the certificates in PEM format (if I remember correctly), copied directly from their respective .crt file for the IAM provider

**Reply by afer4152** [reply]
@aydinseven7 Yes, they are in `.pem` format. If that SSL certificate was issued by digicert, are those the values ​​you meant above by `Intermediate certificate` = `CERT2` and `Root certificate` = `CERT1` ?

Just want to clarify.

**Reply by aydinseven7** [reply]
Yes, it doesn't matter in what order they are though, the CERT1 and CERT2 names are completely arbitrary.

**Reply by afer4152** [reply]
Thanks a lot, but still getting same error `x509: certificate signed by unknown authority`. Not sure what's wrong with that.

**Reply by aydinseven7** [reply]
Just to be sure, have you added the secret with the certs into the correct namespace, then added the volume and volumemount for the secret into the values.yaml and then restarted the pod?  

I specifically have not added the final cert of Keycloak into the secret, just the root and intermediate certs and it works...

**Reply by afer4152** [reply]
Yes, created secret `intermediate-ca` and applied helm values file as below

![image](https://github.com/user-attachments/assets/3d16c29a-c31a-4d88-a821-47f78ab7546e)

```
argo-workflows:
  sso:
   enabled: true
.
.
.
.
.
    volumeMounts:
    - name: intermediate-ca
      mountPath: /etc/ssl/certs/
    volumes:
    - name: intermediate-ca
      secret:
        secretName: intermediate-ca
 ```

**Reply by aydinseven7** [reply]
Just to check...is the indentation in the values.yaml correct? Because in your reply it looks wrong, maybe check with a describe on the workflows server pod whether the secret actually is mounted

**Reply by afer4152** [reply]
@aydinseven7 This is current override `values.yaml` and indentation seems correct. Seems Volume and Volume mount reflected correctly to workflows server pod.

```
argo-workflows:
  sso:
   enabled: true
  images:
    pullSecrets:
    - name: <PULL_SECRET>
  server:
    extraArgs:
      - --auth-mode=sso
    serviceAccount:
      annotations:
        workflows.argoproj.io/rbac-rule: "'<ORG>:<GROUP' in groups"
        workflows.argoproj.io/rbac-rule-precedence: "1"

    volumeMounts:
    - name: intermediate-ca
      mountPath: /etc/ssl/certs/
    volumes:
    - name: intermediate-ca
      secret:
        secretName: intermediate-ca

    ingress:
     ingressClassName: "internal"
     enabled: true
     hosts:
       - <ARGO_WORKFLOW_URL>
    sso:
      clientId:
        name: dex-static-client-credentials
        key: <CLIENT_ID>
      clientSecret:
        name: dex-static-client-credentials
        key: <CLIENT_SECRET>
      scopes:
        - groups 
      rbac:
        enabled: true
      issuer: https://<https://DEX_URL>
      redirectUrl: https://<ARGO_WORKFLOW_URL>/oauth2/callback
```
**Secret**
![image](https://github.com/user-attachments/assets/f5f89073-699b-4c26-9d21-819f42fd762f)

**Pod describe**
```
kubectl describe pod -n argo argo-workflows-server-cc45d796f-q74f4

Name:         argo-workflows-server-cc45d796f-q74f4
Namespace:    argo
Priority:     0
Node:         ip-10-132-81-40.ec2.internal/10.132.81.40
Start Time:   Tue, 25 Feb 2025 18:03:24 +0200
Labels:       app.kubernetes.io/component=server
              app.kubernetes.io/instance=argo-workflows
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=argo-workflows-server
              app.kubernetes.io/part-of=argo-workflows
              app.kubernetes.io/version=v3.2.6
              helm.sh/chart=argo-workflows-0.10.0
Annotations:  kubectl.kubernetes.io/restartedAt: 2023-07-26T11:27:43Z
Status:       Running
IP:           100.68.43.55
IPs:
  IP:           100.68.43.55
Controlled By:  ReplicaSet/argo-workflows-server-cc45d796f
Containers:
  argo-server:
    Container ID:  containerd://1fbd60e35b7f465aff133d15352d752e82fddaf4b8974ca2a0effb5c86de2f31
    Image:         quay.io/argoproj/argocli:v3.2.6
    Image ID:      quay.io/argoproj/argocli@sha256:3f7f3ad7f8e8605393e552dc1a72912b2900e02e85c1a1dc65727d104ec2d0e0
    Port:          2746/TCP
    Host Port:     0/TCP
    Args:
      server
      --configmap=argo-workflows-workflow-controller-configmap
      --auth-mode=sso
      --secure=false
    State:          Running
      Started:      Tue, 25 Feb 2025 18:04:09 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 25 Feb 2025 18:03:40 +0200
      Finished:     Tue, 25 Feb 2025 18:03:40 +0200
    Ready:          False
    Restart Count:  3
    Requests:
      cpu:      100m
      memory:   100Mi
    Readiness:  http-get http://:2746/ delay=10s timeout=1s period=20s #success=1 #failure=3
    Environment:
      IN_CLUSTER:      true
      ARGO_NAMESPACE:  argo (v1:metadata.namespace)
      BASE_HREF:       /
    Mounts:
      /etc/ssl/certs/ from intermediate-ca (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dq9zw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  intermediate-ca:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  intermediate-ca
    Optional:    false
  kube-api-access-dq9zw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
```

**Reply by aydinseven7** [reply]
First of all, I guess you are using the argo-cd Helm Chart, second I see sso.enabled=true twice. For the Argo Workflows Helm Chart, I have configured it this way:
```
server:
  extraEnv:
    - name: SSO_DELEGATE_RBAC_TO_NAMESPACE
      value: "true"
  authModes: 
    - sso
  sso:
    enabled: true
    issuer: https://keycloak.domain.com/realms/REALM
    clientId:
      name: argo-workflows-oidc-creds
      key: client-id
    clientSecret:
      name: argo-workflows-oidc-creds
      key: client-secret
    redirectUrl: https://workflows.domain.com/oauth2/callback
    scopes:
      - groups
  
  volumeMounts:
  - name: intermediate-ca
    mountPath: /etc/ssl/certs/
  volumes:
  - name: intermediate-ca
    secret:
      secretName: intermediate-ca
```

`server` is at root level, then there are fields `server.extraEnv`,`server.authModes`,`server.sso`,`server.volumeMounts` and `server.volumes`. authMode has been deprecated, authModes is the correct way to enable that correctly. I have also added the same volume and volumeMounts to controller, although that should not make any difference since the controller does not call for SSO, only server does.

Using describe, my volumeMounts look exactly the same as yours as well. Hope this somehow helps
