### DISCUSSION TITLE
How can I properly provision a volume in argo?

### DISCUSSION THREAD

**Discussion by Montana** [argoproj/argo-workflows#5117] [Q&A]
I have a persistent volume running in the correct namespace:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: raw-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath: 
    path: /data
  storageClassName: storage
```

I would like to run a workflow that contains a volume claim template, for obvious reasons:

```yaml
  volumeClaimTemplates:
  - metadata:
      name: raw-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
```

I am receiving/getting the following error:

```
Unschedulable: 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims
```

I thought this might be a RBAC issue. I made sure my account has read/write access to the volumes in question. I'm wondering if I should start my Argo workflow over, and see if that solves the problem. Thoughts? Thank you everyone. 

-Montana Mendy
