### DISCUSSION TITLE
Format for dates in historical backfill

### DISCUSSION THREAD

**Discussion by saranyaeu2987** [argoproj/argo-workflows#5163] [Q&A]
Using this https://github.com/argoproj/argo-workflows/blob/master/examples/cron-backfill.yaml as a reference for historical backfill, what will be format placeholder for entire date.

Is withSequence even applicable for below dates?

for example:
```    
  withSequence:
       start: "2019-01-01"
       end:  "2020-01-01"
       format: "What will be the placeholder here
```

@sarabala1979
