### DISCUSSION TITLE
Linter failing on TemplateRef for WorkflowTemplate

### DISCUSSION THREAD

**Discussion by bmaggi** [argoproj/argo-workflows#5171] [Q&A] [answered]
Hi, 

I got a "_template reference not found_" when using the linter on the following example.

Did I missed something ? Is there an issue in the linter ? 

Notes : 
* I transformed one of the official example from kind Workflow to kind : WorkflowTemplate
(Should be correct according to [Workflow template Spec](https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-templates.md#workflowtemplate-spec))
* I checked the discussions around "templateRef" and from my understanding the use cas inside a step is still valid. 

Example : 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate # used to be Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:                              # You should only reference external "templates" in a "steps" or "dag" "template".
        - - name: call-whalesay-template
            templateRef:                  # You can reference a "template" from another "WorkflowTemplate" using this field
              name: workflow-template-1   # This is the name of the "WorkflowTemplate" CRD that contains the "template" you want
              template: whalesay-template # This is the name of the "template" you want to reference
            arguments:                    # You can pass in arguments as normal
              parameters:
                - name: message
                  value: "hello world"

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-1
spec:
  entrypoint: whalesay-template     # Fields other than "arguments" and "templates" not supported in v2.4 - v2.6
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]

```

```cmd
λ argo-windows-amd64-2.12.9.exe -v
time="2021-02-23T15:16:34.878Z" level=debug msg="CLI version" version="{v2.12.9 2021-02-16T22:46:55Z 737905345d70ba1ebd566ce1230e4f971993dfd0 v2.12.9 clean go1.13 gc windows/amd64}"

λ argo-windows-amd64-2.12.9.exe template lint ref-example.yaml
time="2021-02-23T15:40:54.449Z" level=error msg="templates.whalesay.steps[0].call-whalesay-template template reference workflow-template-1.whalesay-template not found"
time="2021-02-23T15:40:54.492Z" level=fatal msg="Errors encountered in validation"
```
