### DISCUSSION TITLE
get status during onExit

### DISCUSSION THREAD

**Discussion by itajaja** [argoproj/argo-workflows#5248] [Q&A] [answered]
what's the best way of getting the workflow status (whether it succeeded or failed) in the workflow onExit hook?

**Comment by sarabala1979** [comment, marked as answer]
you use variables ```{{workflow.status}}```

https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md

**Reply by itajaja** [reply]
thanks!!

**Reply by itajaja** [reply]
... actually, what about the step's onExit? there is no `step.status` which corresponds to the step's status, there is only `steps.<STEPNAME>.status`, but I am not sure how the step name can be passed. A solution would be to have a separate onExit for each step, but that feels hawkward...

**Reply by terrytangyuan** [reply]
There's support for template-level exit handler if that's what you need. Here's an example: https://github.com/argoproj/argo-workflows/blob/master/examples/template-on-exit.yaml

**Reply by itajaja** [reply]
yes, my question is how do I reference the status of the container that triggered the onexit? so, taking the example you posted, what if instead of saying "goodbye world" I wanted to say `"godbye <STATUS>"` where status is the status of the step (stepA or stepB)?

**Reply by LingClassmate** [reply]
@itajaja @terrytangyuan 
Yes, I also have such questions as' @itajaja '. Have you solved them?

**Reply by LingClassmate** [reply]
@terrytangyuan I wanted to use onExit to get the status of each of the Steps tasks.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: container-on-exit-
spec:
  entrypoint: step-template
  templates:
    - name: step-template
      steps:
        - - name: stepA
            onExit: exitContainer1
            template: echo1
        - - name: stepB
            onExit: exitContainer2
            template: echo1
    - name: echo1
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"it was heads\""]
    - name: exitContainer1
      container:
        image: alpine:3.15
        command: [sh, -c]
        args: ["echo  {{steps.stepA.status}}"]
    - name: exitContainer2
      container:
        image: alpine:3.15
        command: [sh, -c]
        args: ["echo  {{steps.stepB.status}}"]
```
