### DISCUSSION TITLE
Was anyone able to set-up SSO RBAC based on groups with Google Cloud?

### DISCUSSION THREAD

**Discussion by jacek-jablonski** [argoproj/argo-workflows#5303] [Q&A]
Hi,
I have working SSO with Google OAuth. I would like to set-up RBAC based on groups (as in docs). This is my current config:
```
sso: |
    issuer: https://accounts.google.com
    clientId:
      name: argo-oauth-credentials-secret
      key: CLIENT_ID
    clientSecret:
      name: argo-oauth-credentials-secret
      key: CLIENT_SECRET
    redirectUrl: https://xxx/oauth2/callback
    scopes:
    - https://www.googleapis.com/auth/userinfo.email
```

However I am unable to see any of my groups:
![ss](https://user-images.githubusercontent.com/35669512/110037756-21e50180-7d3f-11eb-9a00-676bb26faf33.png)

Was anyone able to set it up on Google Cloud?
