### DISCUSSION TITLE
Suspend duration as a parameter

### DISCUSSION THREAD

**Discussion by chiranthans23** [argoproj/argo-workflows#5339] [Q&A]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: somename
spec:
  arguments:
    parameters:
    - name: message
      value: "1m"
  entrypoint: suspend
  templates:
  - name: suspend
    steps:
    - - name: build
        template: whalesay
    - - name: delay
        template: delay
    - - name: release
        template: whalesay
  - name: approve
    suspend:
      duration: "3"
  - name: delay
    suspend:
      duration: "{{'arguments.parameters.message'}}"
  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
```
    
Hi All,
I am trying to see if there is a way I can suspend a workflow based on parameter rather than directly giving the string, as stated in the [doc](https://github.com/argoproj/argo-workflows/blob/master/examples/suspend-template.yaml) ?
Thank you

**Comment by wesleyscholl** [comment]
@chiranthans23 

The ability to parameterize the `suspend` template `duration` field was introduced in Argo Workflows version 3.5. This allows expressions like `duration: "{{workflow.parameters.duration}}"`.

```yaml
suspend:
  duration: "{{workflow.parameters.duration}}" # Could be "10s", "2m", "6h", or "10" ("10" defaults to seconds)
```

This enhancement enables dynamic suspension durations based on workflow parameters. 

Functional example using a workflow parameter:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: suspend-duration-parameter
  namespace: argo
spec:
  templates:
    - name: suspend-workflow
      steps:
        - - name: suspend-step
            template: suspend-template
    - name: suspend-template
      suspend: # suspend template
        duration: "{{workflow.parameters.duration}}" # Variable duration value based on workflow parameter
  entrypoint: suspend-workflow
  arguments:
    parameters:
      - name: duration # Workflow duration parameter
        value: 10s # Passing a Duration value as a workflow parameter
```

**Resources:**

- https://argo-workflows.readthedocs.io/en/latest/walk-through/suspending/
- https://terrytangyuan.github.io/2023/08/14/argo-workflows-v3.5/
- https://argo-workflows.readthedocs.io/en/latest/fields/#suspendtemplate
- https://github.com/argoproj/argo-workflows/commit/6e9d42aed1623e215a04c98cf1632f08f79a45cb#diff-61fda723b78af51f8393e7df0a5e25a64d0eb54ba9fd5e5473e9931244615fd3R6
- https://github.com/argoproj/argo-workflows/blob/main/CHANGELOG.md
- https://argo-workflows.readthedocs.io/en/latest/intermediate-inputs/#intermediate-parameters-approval-example
