### DISCUSSION TITLE
Referencing output of previous step fails - why?

### DISCUSSION THREAD

**Discussion by ghost** [argoproj/argo-workflows#5342] [Q&A]
Hello,

I'd like to reference the output of a previous step. But for some reason I get an error:

`2021/03/09 16:39:35 Failed to create workflow template: templates.main.steps[1].s2 templates.s2-tmp: failed to resolve {{steps.s1.outputs.parameters.param}}`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-wf
  namespace: argo
spec:
  entrypoint: main
  templates:
  - name: s1-tmp
    script:
      image: alpine:latest
      command: [sh]
      source: |
        echo "s1-tmp"
    outputs:
      parameters:
      - name: param
        value: "param-value"

  - name: s2-tmp
    container:
      image: alpine:latest
      command: [echo, "{{steps.s1.outputs.parameters.param}}"]

  - name: main
    steps:
    - - name: s1
        template: s1-tmp
    - - name: s2
        template: s2-tmp
```
Any ideas?

Overall the setup works. If I echo a static string in step 2 the Wf is successfully executed - step 1 echos and step 2 echos. But I cannot reference the output of the previous step :/

**Comment by ghost** [comment]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-wf
  namespace: argo
spec:
  entrypoint: main
  templates:
  - name: s1-tmp
    script:
      image: alpine:latest
      command: [sh]
      source: |
        echo "s1-tmp"
    outputs:
      parameters:
      - name: param
        value: "param-value"

  - name: s2-tmp
    inputs:
      parameters:
      - name: param
    container:
      image: alpine:latest
      command: [echo, "{{inputs.parameters.param}}"]

  - name: main
    steps:
    - - name: s1
        template: s1-tmp
    - - name: s2
        template: s2-tmp
        arguments:
          parameters:
          - name: param
            value: "{{steps.s1.outputs.parameters.param}}"
```
