### DISCUSSION TITLE
Argo workflow conditionally pass command parameter

### DISCUSSION THREAD

**Discussion by kkozmic** [argoproj/argo-workflows#5444] [Q&A] [answered]
I have a workflow with a step that calls a python script through something like:

```yaml
      command:
      - poetry
      - run
      - python
      - my_script.py
      - --force
      - --input-file
      - /tmp/metrics.json
      - --output-folder
      - /tmp
```

I also have an input parameter like
```yaml
    inputs:
      parameters:
      - name: force
        value: "true"
```

I want to include the `--force` flag when invoking my _command_ only when the `force` _parameter_ is `true` and ommit it otherwise, but I can't for the life of me figure out how to do it.

I'm sure it must be possible, so any help would be greatly appreciated.
