### DISCUSSION TITLE
Permission Denied: Container unable to write to files

### DISCUSSION THREAD

**Discussion by MuhammadZeeshan34** [argoproj/argo-workflows#5517] [Q&A]
I deployed Argo server and workflow controller in a name spaced kubernetes cluster. 
I am using kubelet executor. 
Any workflow run perfectly fine if they are not doing any writing operation. Container seems to be not allowed to write anywhere inside its own space. 

This is the workflow 

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scripts-python-map-
spec:
  serviceAccountName: workflow
  podSecurityContext:
    runAsUser: 1000
    runAsGroup:: 1000
    fsGroup: 1000
    runAsNonRoot: true    
  volumes:
  - name: data-vol
    persistentVolumeClaim:
      claimName: data-pvc   
  entrypoint: python-script-example
  imagePullSecrets:
      - name: artifactory.test.secret   
  templates:
  - name: python-script-example
    steps:
    - - name: generate
        template: run-script
  - name: run-script
    script:
      image: artifactory-image:latest
      command: [python]
      source: |
          import dal
          print(dal.__version__)
      volumeMounts:
      - name: data-vol
        mountPath: /in/data1
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup:: 1000
        fsGroup: 1000
```

These are the 3 service accounts, roles and bindings I am using to deploy Argo workflow controller and server. 

```
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: argo
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: argo-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
rules:
# pod get/watch is used to identify the container IDs of the current pod
# pod patch is used to annotate the step's outputs back to controller (e.g. artifact location)
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
# logs get/watch are used to get the pods logs for script outputs, and for log archival
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-role
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets 
  - configmaps
  - nodes 
  - nodes/proxy 
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - create
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  - workflowtemplates/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - argoproj.io
  resources:
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - extensions
  resourceNames:
  - argo-workflow
  resources:
  - podsecuritypolicies
  verbs:
  - use  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-server-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list #added
  - get
  - create
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - watch
  - create
  - patch
  - list 
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - argoproj.io
  resources:
  - eventsources
  - sensors
  - workflows
  - workfloweventbindings
  - workflowtemplates
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  resourceNames:
  - argo-workflow
  resources:
  - podsecuritypolicies
  verbs:
  - use    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-role
subjects:
- kind: ServiceAccount
  name: workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: argo-binding
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-role
subjects: 
- kind: ServiceAccount
  name: argo
  namespace: namespace-name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: argo-server-binding
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-server-role
subjects: 
- kind: ServiceAccount
  name: argo-server
  namespace: namespace-name
```

ps aux inisde the container shows the permissions for user 1000

![image](https://user-images.githubusercontent.com/18715291/112637545-309e7000-8e36-11eb-96b3-3a82b6947d70.png)

No permissions to create or write to files
![image](https://user-images.githubusercontent.com/18715291/112637645-4875f400-8e36-11eb-8280-0aab71a1cbbb.png)

No privileges to change the ownership
![image](https://user-images.githubusercontent.com/18715291/112637728-5deb1e00-8e36-11eb-8614-99dd36216253.png)

Can anyone help me why the container does not have permissions to write. It says permission denied.
