### DISCUSSION TITLE
Can argo worklow serve business workflow?

### DISCUSSION THREAD

**Discussion by thanhpd-teko** [argoproj/argo-workflows#5588] [Q&A] [answered]
Hi, I'm using both argo workflow an argo events, and the are really great.
However, I wonder can argo serve some workflow for each user. For example
- When user A completed action 1 and action 2 then send email to them? 
Thanks.

**Comment by terrytangyuan** [comment, marked as answer]
You can do that via specifying dependencies in a DAG: https://argoproj.github.io/argo-workflows/workflow-concepts/#dag

```
    dag:
      tasks:
      - name: action1
        template: action1
      - name: action2
        template: action2
      - name: send-email
        dependencies: [action1, action2]
```

Is this what you need/meant?
