### DISCUSSION TITLE
Why the condition can only skip the current step and not all subsequent step ?

### DISCUSSION THREAD

**Discussion by yq688** [argoproj/argo-workflows#5597] [Q&A]
![image](https://user-images.githubusercontent.com/82009358/113651265-42003b80-96c4-11eb-97ec-9f79650cb6ca.png)

**Comment by wesleyscholl** [comment]
@yq688 

In Argo Workflows, conditional execution is managed using the `when` field within steps. This field allows you to specify conditions under which a particular step should be executed. However, it's important to note that the when condition applies only to the specific step it's associated with; it does not inherently affect subsequent steps. This design ensures that each step's execution is controlled independently, providing granular control over the workflow's behavior.

**Understanding Conditional Execution:**

The `when` field utilizes expressions to determine whether a step should run. These expressions can evaluate parameters, outputs from previous steps, or other contextual data.

```yaml
- name: example-step
  template: example-template
  when: "{{steps.previous-step.outputs.result}} == 'success'" # Only executes when the previous step is successful
```

In the above example, `example-step` will execute only if previous-step has an output result of 'success'. This mechanism allows for dynamic and flexible workflow definitions.

**Controlling Subsequent Steps:**

To influence the execution of subsequent steps based on a condition, workflows must include conditional checks at each step. For more information, see the examples and resources below.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-workflow-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: step-1
            template: step-template
        - - name: step-2
            template: step-template
            when: "{{steps.step-1.outputs.result}} == 'success'" # Executes if step-1 is successful
        - - name: step-3
            template: step-template
            when: "{{steps.step-2.outputs.result}} == 'success'" # Executes if step-2 is successful
```

**Resources:**
- https://argo-workflows.readthedocs.io/en/latest/walk-through/conditionals/
- https://argo-workflows.readthedocs.io/en/latest/walk-through/recursion/
- https://github.com/argoproj/argo-workflows/blob/main/examples/conditionals.yaml
- https://github.com/argoproj/argo-workflows/blob/main/examples/status-reference.yaml
- https://github.com/argoproj/argo-workflows/blob/main/examples/exit-handlers.yaml
- https://github.com/argoproj/argo-workflows/blob/main/examples/coinflip.yaml
- https://argo-workflows.readthedocs.io/en/latest/variables/
