### DISCUSSION TITLE
Issues with PodSpecPatch -- invalid JSON

### DISCUSSION THREAD

**Discussion by NikeNano** [argoproj/argo-workflows#5616] [Q&A] [answered]
I have issues with the following workflow that is successfully linted but fails during execution:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-first-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.5.0-rc.2, pipelines.kubeflow.org/pipeline_compilation_time: '2021-04-07T21:59:43.991160',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A hello world pipeline.",
      "inputs": [{"default": "100Mi", "name": "memory_request", "optional": true,
      "type": "String"}, {"default": "100m", "name": "cpu_request", "optional": true,
      "type": "String"}], "name": "My first pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.5.0-rc.2}
spec:
  entrypoint: my-first-pipeline
  templates:
  - name: echo
    container:
      args: [echo "hello world"]
      command: [sh, -c]
      image: library/bash:4.4.23
    inputs:
      parameters:
      - {name: cpu_request}
      - {name: memory_request}
    podSpecPatch: '{"containers":[{"name":"main", "resources":{"limits":{"memory":
      {{inputs.parameters.memory_request}}" }}, "cpu": "{{inputs.parameters.cpu_request}}"
      }}}]}'
  - name: my-first-pipeline
    inputs:
      parameters:
      - {name: cpu_request}
      - {name: memory_request}
    dag:
      tasks:
      - name: echo
        template: echo
        arguments:
          parameters:
          - {name: cpu_request, value: '{{inputs.parameters.cpu_request}}'}
          - {name: memory_request, value: '{{inputs.parameters.memory_request}}'}
  arguments:
    parameters:
    - {name: memory_request, value: 100Mi}
    - {name: cpu_request, value: 100m}
  serviceAccountName: pipeline-runner
```

kubectl gives the following description:

```
Name:         my-first-pipeline-v9xwt
Namespace:    kubeflow
Labels:       pipelines.kubeflow.org/kfp_sdk_version=1.5.0-rc.2
              workflows.argoproj.io/completed=true
              workflows.argoproj.io/phase=Error
Annotations:  pipelines.kubeflow.org/kfp_sdk_version: 1.5.0-rc.2
              pipelines.kubeflow.org/pipeline_compilation_time: 2021-04-07T21:59:43.991160
              pipelines.kubeflow.org/pipeline_spec:
                {"description": "A hello world pipeline.", "inputs": [{"default": "100Mi", "name": "memory_request", "optional": true, "type": "String"}, ...
API Version:  argoproj.io/v1alpha1
Kind:         Workflow
Metadata:
  Creation Timestamp:  2021-04-07T20:13:02Z
  Generate Name:       my-first-pipeline-
  Generation:          2
  Managed Fields:
    API Version:  argoproj.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:pipelines.kubeflow.org/kfp_sdk_version:
          f:pipelines.kubeflow.org/pipeline_compilation_time:
          f:pipelines.kubeflow.org/pipeline_spec:
        f:generateName:
        f:labels:
          .:
          f:pipelines.kubeflow.org/kfp_sdk_version:
      f:spec:
        .:
        f:arguments:
          .:
          f:parameters:
        f:entrypoint:
        f:serviceAccountName:
      f:status:
    Manager:      argo
    Operation:    Update
    Time:         2021-04-07T20:13:02Z
    API Version:  argoproj.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:workflows.argoproj.io/completed:
          f:workflows.argoproj.io/phase:
      f:spec:
        f:templates:
      f:status:
        f:conditions:
        f:finishedAt:
        f:nodes:
          .:
          f:my-first-pipeline-v9xwt:
            .:
            f:children:
            f:displayName:
            f:finishedAt:
            f:id:
            f:inputs:
              .:
              f:parameters:
            f:name:
            f:outboundNodes:
            f:phase:
            f:progress:
            f:startedAt:
            f:templateName:
            f:templateScope:
            f:type:
          f:my-first-pipeline-v9xwt-3952033295:
            .:
            f:boundaryID:
            f:displayName:
            f:finishedAt:
            f:id:
            f:inputs:
              .:
              f:parameters:
            f:message:
            f:name:
            f:phase:
            f:progress:
            f:startedAt:
            f:templateName:
            f:templateScope:
            f:type:
        f:phase:
        f:progress:
        f:startedAt:
    Manager:         workflow-controller
    Operation:       Update
    Time:            2021-04-07T20:13:02Z
  Resource Version:  118949
  Self Link:         /apis/argoproj.io/v1alpha1/namespaces/kubeflow/workflows/my-first-pipeline-v9xwt
  UID:               fd164f30-fa09-4402-b858-dc9180b1585c
Spec:
  Arguments:
    Parameters:
      Name:              memory_request
      Value:             100Mi
      Name:              cpu_request
      Value:             100m
  Entrypoint:            my-first-pipeline
  Service Account Name:  pipeline-runner
  Templates:
    Arguments:
    Container:
      Args:
        echo "hello world"
      Command:
        sh
        -c
      Image:  library/bash:4.4.23
      Name:
      Resources:
    Inputs:
      Parameters:
        Name:  cpu_request
        Name:  memory_request
    Metadata:
    Name:  echo
    Outputs:
    Pod Spec Patch:  {"containers":[{"name":"main", "resources":{"limits":{"memory": {{inputs.parameters.memory_request}}" }}, "cpu": "{{inputs.parameters.cpu_request}}" }}}]}
    Arguments:
    Dag:
      Tasks:
        Arguments:
          Parameters:
            Name:   cpu_request
            Value:  {{inputs.parameters.cpu_request}}
            Name:   memory_request
            Value:  {{inputs.parameters.memory_request}}
        Name:       echo
        Template:   echo
    Inputs:
      Parameters:
        Name:  cpu_request
        Name:  memory_request
    Metadata:
    Name:  my-first-pipeline
    Outputs:
Status:
  Conditions:
    Status:     True
    Type:       Completed
  Finished At:  2021-04-07T20:13:02Z
  Nodes:
    my-first-pipeline-v9xwt:
      Children:
        my-first-pipeline-v9xwt-3952033295
      Display Name:  my-first-pipeline-v9xwt
      Finished At:   2021-04-07T20:13:02Z
      Id:            my-first-pipeline-v9xwt
      Inputs:
        Parameters:
          Name:   cpu_request
          Value:  100m
          Name:   memory_request
          Value:  100Mi
      Name:       my-first-pipeline-v9xwt
      Outbound Nodes:
        my-first-pipeline-v9xwt-3952033295
      Phase:           Error
      Progress:        1/1
      Started At:      2021-04-07T20:13:02Z
      Template Name:   my-first-pipeline
      Template Scope:  local/my-first-pipeline-v9xwt
      Type:            DAG
    my-first-pipeline-v9xwt-3952033295:
      Boundary ID:   my-first-pipeline-v9xwt
      Display Name:  echo
      Finished At:   2021-04-07T20:13:02Z
      Id:            my-first-pipeline-v9xwt-3952033295
      Inputs:
        Parameters:
          Name:        cpu_request
          Value:       100m
          Name:        memory_request
          Value:       100Mi
      Message:         task 'my-first-pipeline-v9xwt.echo' errored
      Name:            my-first-pipeline-v9xwt.echo
      Phase:           Error
      Progress:        1/1
      Started At:      2021-04-07T20:13:02Z
      Template Name:   echo
      Template Scope:  local/my-first-pipeline-v9xwt
      Type:            Pod
  Phase:               Error
  Progress:            1/1
  Started At:          2021-04-07T20:13:02Z
Events:
  Type     Reason             Age   From                 Message
  ----     ------             ----  ----                 -------
  Normal   WorkflowRunning    3m4s  workflow-controller  Workflow Running
  Warning  WorkflowNodeError  3m4s  workflow-controller  Error node my-first-pipeline-v9xwt.echo: Invalid PodSpecPatch String
  Warning  WorkflowNodeError  3m4s  workflow-controller  Error node my-first-pipeline-v9xwt.echo: task 'my-first-pipeline-v9xwt.echo' errored
  Warning  WorkflowNodeError  3m4s  workflow-controller  Error node my-first-pipeline-v9xwt
  Warning  WorkflowFailed     3m4s  workflow-controller
```

argo version 2.12.10
