### DISCUSSION TITLE
Conditional steps parameters and govaluate data typers

### DISCUSSION THREAD

**Discussion by ghost** [argoproj/argo-workflows#5637] [Q&A]
Hey! I've got some questions on parametrization and govaluate data types...
I am trying to detect GitLab branch creation using an Argo Events EventSource and Sensor:

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gitlab-project-render
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: gitlab-hook
      eventSourceName: gitlab
      eventName: repo-push
  triggers:
    - template:
        name: gitlab-workflow-render-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: gitlab-workflow-render-
                labels:
                  workflows.argoproj.io/controller-instanceid: system-controller
#                  workflows.argoproj.io/archive-strategy: "always"
              spec:
                entrypoint: infra-handler
                arguments:
                  parameters:
                  - name: ref
                    value: parametrizedref
                  - name: sha-before
                    value: parametrizedbefore
                  - name: sha-after
                    value: parametrizedafter
                templates:
                - name: infra-handler
                  serviceAccountName: argo-events-sa
                  inputs:
                    parameters:
                    - name: sha-before
                    - name: sha-after
                  steps:
                  - - name: create-on-branch-commence
                      template: infra-generator
                      when: "{{inputs.parameters.sha-before}} == 0000000000000000000000000000000000000000 && {{inputs.parameters.sha-after}} != 0000000000000000000000000000000000000000"
                  - - name: destroy-on-branch-remove
                      template: infra-destroyer
                      when: "{{inputs.parameters.sha-before}} != 0000000000000000000000000000000000000000 && {{inputs.parameters.sha-after}} == 0000000000000000000000000000000000000000"
                - name: infra-generator
                  serviceAccountName: argo-events-sa
                  inputs:
                    parameters:
                    - name: ref
                  container:
                    image: argoproj/argosay:v2
                    args: ["echo", "branch created= {{inputs.parameters.ref}}"]
                - name: infra-destroyer
                  serviceAccountName: argo-events-sa
                  inputs:
                    parameters:
                    - name: ref
                  container:
                    image: agoproj/argosay:v2
                    args: ["echo", "branch deleted= {{inputs.parameters.ref}}"]
          parameters:
          - src:
              dependencyName: gitlab-hook
              dataKey: body.ref
            dest: spec.arguments.parameters.0.value
          - src:
              dependencyName: gitlab-hook
              dataKey: body.before
            dest: spec.arguments.parameters.1.value
          - src:
              dependencyName: gitlab-hook
              dataKey: body.after
            dest: spec.arguments.parameters.2.value

```
First, when I try to run it I get an error like:

> invalid spec: templates.infra-handler.steps[0].create-on-branch-commence templates.infra-generator inputs.parameters.ref was not supplied

which is strange, as ref parameter is declared above and it should be replaced with parameters from hook.

Second, I've tried to remove this variable and test it "as is", but now I get a new error:

>   Warning  WorkflowNodeError   4s    workflow-controller  Error node gitlab-workflow-render-chsrh[0]: Invalid 'when' expression '5d1ca167fd6272d60bbf69f49f0a0ca502765081 == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081 != 0000000000000000000000000000000000000000': Cannot transition token types from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]
>   Warning  WorkflowNodeFailed  4s    workflow-controller  Failed node gitlab-workflow-render-chsrh: Invalid 'when' expression '5d1ca167fd6272d60bbf69f49f0a0ca502765081 == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081 != 0000000000000000000000000000000000000000': Cannot transition token types from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]
>   Warning  WorkflowFailed      4s    workflow-controller  Invalid 'when' expression '5d1ca167fd6272d60bbf69f49f0a0ca502765081 == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081 != 0000000000000000000000000000000000000000': Cannot transition token types from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]

  
Is there any way to compare git hashes in govaluate? Any help is appreciated

**Comment by ghost** [comment]
I've managed to solve my parametrization question with additional arguments inside steps block, but govaluate problem is still there...

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gitlab-project-render
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: gitlab-hook
      eventSourceName: gitlab
      eventName: repo-push
  triggers:
    - template:
        name: gitlab-workflow-render-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: gitlab-workflow-render-
                labels:
                  workflows.argoproj.io/controller-instanceid: system-controller
#                  workflows.argoproj.io/archive-strategy: "always"
              spec:
                entrypoint: infra-handler
                arguments:
                  parameters:
                  - name: ref
                    value: parametrizedref
                  - name: sha-before
                    value: parametrizedbefore
                  - name: sha-after
                    value: parametrizedafter
                templates:
                - name: infra-handler
                  serviceAccountName: argo-events-sa
                  inputs:
                    parameters:
                    - name: sha-before
                    - name: sha-after
                  steps:
                  - - name: create-on-branch-commence
                      template: infra-generator
                      arguments:
                        parameters:
                         - name: ref
                           value: "{{workflow.parameters.ref}}"
                      when: "{{inputs.parameters.sha-before}} == 0000000000000000000000000000000000000000 && {{inputs.parameters.sha-after}} != 0000000000000000000000000000000000000000"
                    - name: destroy-on-branch-abstand
                      template: infra-destroyer
                      arguments:
                        parameters:
                         - name: ref
                           value: "{{workflow.parameters.ref}}"
                      when: "{{inputs.parameters.sha-before}} != 0000000000000000000000000000000000000000 && {{inputs.parameters.sha-after}} == 0000000000000000000000000000000000000000"
                - name: infra-generator
                  serviceAccountName: argo-events-sa
                  inputs:
                    parameters:
                    - name: ref
                  container:
                    image: argoproj/argosay:v2
                    args: ["echo", "branch created= {{inputs.parameters.ref}}"]
                - name: infra-destroyer
                  serviceAccountName: argo-events-sa
                  inputs:
                    parameters:
                    - name: ref
                  container:
                    image: argoproj/argosay:v2
                    args: ["echo", "branch deleted= {{inputs.parameters.ref}}"]
          parameters:
          - src:
              dependencyName: gitlab-hook
              dataTemplate: "{{.Input.body.ref | base}}"
            dest: spec.arguments.parameters.0.value
          - src:
              dependencyName: gitlab-hook
              dataKey: body.before
            dest: spec.arguments.parameters.1.value
          - src:
              dependencyName: gitlab-hook
              dataKey: body.after
            dest: spec.arguments.parameters.2.value

```
