### DISCUSSION TITLE
Access to a workflow artifact

### DISCUSSION THREAD

**Discussion by laymain** [argoproj/argo-workflows#5654] [Q&A] [answered]
Hello, I'm struggling to access a workflow artifact, I'm trying to achieve something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-test-
spec:
  arguments:
    artifacts:
    - name: content
      globalName: content
      raw:
        data: |
          content of my file
  entrypoint: start
  templates:
  - name: start
    steps:
    - - name: dump
        template: dump-artifact
        arguments:
          artifacts:
          - name: content
            from: "{{workflow.inputs.artifacts.content}}"
  - name: dump-artifact
    inputs:
      parameters:
      - name: args
      artifacts:
      - name: content
        path: /etc/file
    container:
      image: alpine
      command: [cat]
      args: [/etc/file]
```

I tried with multiple references as listed in https://argoproj.github.io/argo-workflows/fields/#artifact or https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md#global :
* `{{workflow.inputs.artifacts.<NAME>}}`
* `{{workflow.outputs.artifacts.<NAME>}}`
* `{{io.argoproj.workflow.v1alpha1.outputs.artifacts.<NAME>}}`
* `{{workflow.status.outputs.artifacts.<NAME>}}` _(I think the status is a typo in the documentation)_

I always get a `failed to resolve {{XXX}}` error.

Is there a way to achieve this?

**Comment by wesleyscholl** [comment, marked as answer]
@laymain 

In the workflow above, the intention is to pass a raw artifact defined at the workflow level to a template. However, referencing artifacts at the workflow level directly within templates using expressions like `{{workflow.inputs.artifacts.content}}` isn't supported. Instead, define the artifact at the workflow level and pass it explicitly to the template using arguments.

Functional workflow example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-test-
spec:
  entrypoint: start
  templates:
    - name: start
      inputs: 
        artifacts:
          - name: content # Input artifact
            path: /etc/file # Artifact path
            raw: # The artifact is created using raw data 
              data: | # File contents
                content of my file 
      container:
        image: alpine
        command: [cat]
        args: [/etc/file] # Output the file contents
```

In this configuration:

- The `start` template defines an input artifact named `content`. The data is directly specified under `raw`.
- The artifact is assigned the path `/etc/file` which is mounted in the container.
- The `cat` command outputs the contents of the file at the `/etc/file` path.

This setup ensures that the raw artifact is correctly passed to the template and can be accessed within the container.

**Resources:**

- https://github.com/argoproj/argo-workflows/blob/main/examples/input-artifact-raw.yaml
- https://argo-workflows.readthedocs.io/en/latest/fields/#rawartifact
- https://github.com/argoproj/argo-workflows/blob/main/examples/artifact-path-placeholders.yaml
- https://argo-workflows.readthedocs.io/en/latest/walk-through/artifacts/
- #648
