### DISCUSSION TITLE
Image Pull Back Off for images being passed as spec.container.args

### DISCUSSION THREAD

**Discussion by MuhammadZeeshan34** [argoproj/argo-workflows#5688] [Q&A] [answered]
spec.imagePullSecrets works for Argo workflow controller image as it is being passed as spec.containers.image but they are somehow not working for executor image which is being passed as arguments to spec.containers.

```
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: workflow-controller
spec: 
  selector: 
    matchLabels: 
      app: workflow-controller
  template: 
    metadata: 
      labels: 
        app: workflow-controller
    spec:
      imagePullSecrets:
        - name: artifactory.test.secret         
      containers: 
      - args: 
        - --configmap
        - workflow-controller-configmap
        - --configmap
        - artifact-repositories          
        - --executor-image
        - artifactory-private.com/argoproj/argoexec:v2.12.10
        - --namespaced
        command: 
        - workflow-controller
        env:
        - name: LEADER_ELECTION_IDENTITY
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: artifactory-private.com/workflow-controller:v2.12.10
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 30
        name: workflow-controller
        ports:
        - containerPort: 9090
          name: metrics
      serviceAccountName: argo
```

Any idea how can imagePullSecrets can be passed for argoexec image? Thanks

**Comment by alexec** [comment]
Have you checked the config map? I think there is an `executor` option.

**Reply by MuhammadZeeshan34** [reply]
Do you mean I need to add imagePullSecrets inside this configMap?

```
apiVersion: v1
data:
  containerRuntimeExecutor: k8sapi
  artifactRepository: |
    archiveLogs: true
    s3: 
      bucket: bucket-name
      endpoint: https://endpoint.com
      keyFormat: "{{workflow.name}}/{{pod.name}}"
      insecure: true
      accessKeySecret:
        name: aws-s3-dev
        key: aws_access_key_id
      secretKeySecret:
        name: aws-s3-dev
        key: aws_secret_access_key

  containerRuntimeExecutors: |
    - name: k8sapi
      selector:
        matchLabels:
          workflows.argoproj.io/container-runtime-executor: k8sapi
  executor: |
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
  links: |
    - name: Workflow Link
      scope: workflow
      url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
    - name: Pod Link
      scope: pod
      url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
    - name: Pod Logs Link
      scope: pod-logs
      url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
    - name: Event Source Logs Link
      scope: event-source-logs
      url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
    - name: Sensor Logs Link
      scope: sensor-logs
      url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
  metricsConfig: |
    disableLegacy: true
    enabled: true
    path: /metrics
    port: 9090

kind: ConfigMap
metadata:
  name: workflow-controller-configmap
---
```


Probably something like this?  

```
  executor: |
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
    imagePullSecrets:
      - name: artifactory.test.secret   
```
