### DISCUSSION TITLE
ExitHandler as WorkflowTemplate

### DISCUSSION THREAD

**Discussion by Mista-C** [argoproj/argo-workflows#5774] [Q&A] [answered]
Hi, 
I want to create an exit handler WorkflowTemplate which will be used in some workflows. Currently I am not sure how it is possible to include the reference to the workflow, I always get the error `Internal Server Error: template 'exit-handler' type is unknown`? I dont want to use it as a default becuase on other workflows this exit handler should not run.  
How could I solve this?

**Comment by Mista-C** [comment, marked as answer]
Got an answer in slack, in can be done easily the following way define your `WorkflowTemplate` and use it in the `Workflow` like:
```
- name: exit-handler
      steps:
        - - name: exit
            templateRef:
              name: workflow-template-whalesay-template
              template: exit-handler
```
