### DISCUSSION TITLE
Sharing properties between templates

### DISCUSSION THREAD

**Discussion by christopheblin** [argoproj/argo-workflows#5809] [Q&A] [answered]
Hi,

In my workflows, but I suspect this is something that happens very often, I often repeat the same properties between multiple templates

Here is a relevant subset. As you can see, I must put the same labels on every template as well as same way to set the environment from a secret+workflow arguments and as well as same volumes (we use the volume with azurefile to share intermediate data instead of artifacts)

Is there some way to declare them only once ?

The main benefit we are looking for is readability

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dataset
spec:
  serviceAccountName: argo  
  entrypoint: main
  arguments:
    parameters:
    - name: coverage
      value: "xxx"
    - name: dataset
      value: "zzz"
  
  templates:
  - name: main
    steps:
    - - name: download
        template: dataset-download
    - - name: unzip
        template: dataset-unzip
        
  - name: dataset-download
    metadata:
      labels:
        coverage: "{{workflow.parameters.coverage}}"
        dataset: "{{workflow.parameters.dataset}}"
    container:
      image: <removed>
      workingDir: /dataset
      command: 
        - "/bin/sh"
      args:
        - "-c"
        - "<removed>"
      envFrom:
        - secretRef:
            name: dataset-secret
      env:
        - name: COVERAGE
          value: "{{workflow.parameters.coverage}}"
        - name: DATASET
          value: "{{workflow.parameters.dataset}}"      
      volumeMounts:
        - mountPath: /dataset
          name: my-volume
    volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-share

  - name: dataset-unzip
    metadata:
      labels:
        coverage: "{{workflow.parameters.coverage}}"
        dataset: "{{workflow.parameters.dataset}}"
    container:
      image: <removed>
      workingDir: /dataset
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "<removed>"
      envFrom:
        - secretRef:
            name: dataset-secret
      env:
        - name: COVERAGE
          value: "{{workflow.parameters.coverage}}"
        - name: DATASET
          value: "{{workflow.parameters.dataset}}"
      volumeMounts:
        - mountPath: /dataset
          name: my-volume
    volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-share
```

**Comment by christopheblin** [comment]
An example of what I am looking for:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dataset
spec:
  serviceAccountName: argo  
  entrypoint: main
  arguments:
    parameters:
    - name: coverage
      value: "xxx"
    - name: dataset
      value: "zzz"

templates:
  - name: main
    steps:
    - - name: download
        template: dataset-download
    - - name: unzip
        template: dataset-unzip
        
  - name: dataset-download
    metadata: 
      template: default      
    container:
       template: image1
       command: 
        - "/bin/sh"
       args:
         - "-c"
         - "<removed>"

  - name: dataset-unzip
    metadata: 
      template: default      
    container:
       template: image1
       command: 
        - "/bin/sh"
       args:
         - "-c"
         - "<removed>"

metadataTemplates:
   - name: default
   labels:
        coverage: "{{workflow.parameters.coverage}}"
        dataset: "{{workflow.parameters.dataset}}"

containerTemplates:
    - name: image1
    image: <removed>
    workingDir: /dataset
    envFrom
     - secretRef:
            name: dataset-secret
      env:
        - name: COVERAGE
          value: "{{workflow.parameters.coverage}}"
        - name: DATASET
          value: "{{workflow.parameters.dataset}}"
      volumeMounts:
        - mountPath: /dataset
          name: my-volume
    volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-share 
```
