### DISCUSSION TITLE
nginx ingress seems not working with server

### DISCUSSION THREAD

**Discussion by huytn1219** [argoproj/argo-workflows#5822] [Q&A]
Hi, 

I have been struggling to figure out how to get Nginx Ingress working with Argo Workflow. I'm able to set up ArgoCD and Argo Event with Nginx Ingress in GKE but I'm hitting the wall with Argo Workflow.

Here is my Argo Workflow Ingress configuration:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo-workflow-ingress
  namespace: argo
  annotations:
     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - xxx.xxx.xxx.io
    secretName: argo-workflow-tls
  rules:
  - host: xxx.xxx.xxx.io
    http:
      paths:
      - backend:
          serviceName: argo-server
          servicePort: 2746
        path: /
```
And this is part of my Argo Workflow deployment:
```yaml
    spec:
      containers:
      - args:
        - server
        - --namespaced
        - --auth-mode
        - server
        - --auth-mode
        - client
        image: argoproj/argocli:v3.0.2
        imagePullPolicy: IfNotPresent
        name: argo-server
        ports:
        - containerPort: 2746
          name: web
          protocol: TCP
```

I can port-forward Argo Workflow to my local and access the service with https://localhost:2746.
However, when I applied the Ingress and tried to access it from the browser, I hit `502 Bad Gateway`.
Here is my Nginx Ingress log

```
failed (104: Connection reset by peer) while reading response header from upstream, client: xx.xx.xx.xx, server: xxx.xxx.xxx.io, request: "GET / HTTP/1.1", upstream: "http://172.20.0.107:2746/", host: "xxx.xxx.xxxx.io"
```
Am I missing anything?
