### DISCUSSION TITLE
Getting a sub field from a step with a file based output parameter

### DISCUSSION THREAD

**Discussion by justinmchase** [argoproj/argo-workflows#5840] [Q&A] [answered]
Suppose I have one step with an output parameter like so:
```yaml
outputs:
  parameters:
  - name: command
    valueFrom:
      path: /tmp/get-command.json
```

In my code I am getting the command and the just writing it to the file as json
```ts
await write('/tmp/get-command.json', JSON.stringify(command))
```

Now in a subsequent step I would like to only pass some subset of the data down to the next step. So for example if the output parameter now contained:
```json
{"_id":"123","data":{"foo": true,"bar":false}}
```

What I want to do is this:
```yaml
arguments:
  parameters:
  - name: data
    value: "{{steps.get.outputs.parameters.command.data}}"
```

Where I can just drill down from the command output parameter into the inner field by just doing `.data` and would receive the input `{"foo":true,"bar":false}`.

But it doesn't seem to be working, rather than getting the data at that path I am getting the literal template string. If I remove the `.data` then it indeed sends me in the entire file.

 How can I get the sub-field from a file based output parameter?

**Comment by terrytangyuan** [comment, marked as answer]
Have you tried the new expression template tags? Some references:
- https://argoproj.github.io/argo-workflows/variables/#expression
- https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md
- https://blog.argoproj.io/argo-workflows-v3-1-is-coming-1fb1c1091324

**Reply by justinmchase** [reply]
I've been trying to make it work but can't seem to figure it out...

For example I have this step:
```yaml
    - - name: create
        template: create-node
        arguments:
          parameters:
          - name: data
            value: "{{=jsonpath(steps.get-command.outputs.parameters.command, '$.data')}}"
```

And then for the template:
```yaml
  - name: create-node
    inputs:
      parameters:
        - name: data
    container:
      # ...
      args: ["{{inputs.parameters.data}}"]
```
But its not working, it returns the expression itself as the input rather than doing the evaluation I would expect.

So if on my argument parameter value I have a simple expression such as `"{{steps.get-command.outputs.parameters.command}}"` then it works, but of course its the wrong object. With the complex expression it, instead of the result of evaluating the expression, returns the expression verbatim as the input itself.

![image](https://user-images.githubusercontent.com/10974/117319746-36ce3600-ae51-11eb-9815-14364a61ccee.png)

I'm just basically using this to install argo:
```sh
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/install.yaml
```

**Reply by justinmchase** [reply]
Ok so it looks like the current version that that installs is `v3.0.2` but based on that blog post (written yesterday) that feature is only available in v3.1... So what you're saying is I have to get the future version somehow 🤔

**Reply by justinmchase** [reply]
Well sadly the version tagged as "latest" doesn't seem to work at all, the server is returning a 401 for everything no matter what I do. And its not set in auth-mode so it doesn't seem like there is any way to actually auth.

But oh well, I guess I'll look at that when 3.1 gets pinned and I'll make some hacky script based mapping function for now.

**Reply by justinmchase** [reply]
Ok so the expressions don't seem like they're available yet but this did act as a workaround for me in the meantime:
```yaml
  - name: map-field
    inputs:
      parameters:
      - name: data
      - name: path
    script:
      image: stedolan/jq
      command: [ bash ]
      source: |
         echo '{{inputs.parameters.data}}' | jq -r '{{inputs.parameters.path}}'
```
