### DISCUSSION TITLE
Support workflow parameters as a value for  "artifactRepositoryRef.key"

### DISCUSSION THREAD

**Discussion by kulinskyvs** [argoproj/argo-workflows#5885] [Ideas]
# Summary

Could it be possible to add support of workflow parameters as a value of "[artifactRepositoryRef.key](https://argoproj.github.io/argo-workflows/artifact-repository-ref/)" for workflows/workflowTemplates?

# Use Cases

I have a ConfigMap with several supported Artifact Repositories.
```yaml
apiVersion: v1
kind: ConfigMap
name: artifact-repositories
data:
  aws-s3: |
    s3:
      bucket: bucketname
      accessKeySecret:
        name: s3-secret
        key: accesskey
      secretKeySecret:
        name: s3-secret
        key: secretkey
  minio: |
    s3:
      bucket: bucketname
      insecure: true
      accessKeySecret:
        name: minio-secret
        key: accesskey
      secretKeySecret:
        name: minio-secret
        key: secretkey
      endpoint: minio:9000
```

Would be great to have the ability to set which artifact repository is supposed to be used by a workflow when submitting it from a workflow template through the workflow input parameters.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow-template
spec:
  arguments:
    parameters:
      - name: artifactRepository
        value: "aws-s3"
  artifactRepositoryRef:
    key: "{{workflow.parameters.artifactRepository}}"
  templates:
  .........
```
