### DISCUSSION TITLE
Support workflow parameters in workflow metadata

### DISCUSSION THREAD

**Discussion by kulinskyvs** [argoproj/argo-workflows#5888] [Ideas]
# Summary

Motivated by #5885, could it be possible to add support of workflow parameters for `workflowMetadata` on the workflow template level? 

# Use case

I have a reusable workflow with some `workflowMetadata` defined - I would like to refer to workflow input parameters from `workflowMetadata` section (use these values when building the labels for example).

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow-template
spec:
  arguments:
    parameters:
      - name: env
        value: "prod"
      - name: platform
         value: my-platform
  workflowMetadata:
    labels:
      enviroment: "{{ workflow.parameters.env }}"
      platform: "{{ workflow.parameters.platform }}"
  templates:
  .........
```

Supporting workflow parameters inside the `workflowMetadata` section (labels, for example) can increase its reusability and makes the workflows submitted from this template more consistent and discoverable (labeling is done regardless of the labels provided when submitting the workflow through UI or argocli).
