### DISCUSSION TITLE
Argo Workflow error when using envFrom field

### DISCUSSION THREAD

**Discussion by boonware** [argoproj/argo-workflows#5902] [Q&A] [answered]
Cross-post from StackOverflow: https://stackoverflow.com/questions/67518394/argo-workflow-error-when-using-envfrom-field

In the event that there is an underlying bug, or someone else encounters a similar problem, I felt it was best to post here too.

 Argo version: 2.12.11

Workflow:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-workflow-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: configmap
        value: my-configmap
      - name: secret
        value: my-secret
  templates:
    - name: main
      steps:
        - - name: main
            templateRef:
              name: my-template
              template: main
            arguments:
              parameters:
                - name: configmap
                  value: "{{workflow.parameters.configmap}}"
                - name: secret
                  value: "{{workflow.parameters.secret}}"
```

Template:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-template
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: configmap
        parameters:
          - name: secret
      container:
        image: my-image:1.2.3
        envFrom:
          - configMapRef:
            name: "{{inputs.parameters.configmap}}"
          - secretRef:
            name: "{{inputs.parameters.secret}}"
```

When deployed through the Argo UI I receive the following error from Kubernetes when starting the pod:

```
spec.containers[1].envFrom: Invalid value: \"\": must specify one of: `configMapRef` or `secretRef`
```

Using `envFrom` is supported and documented in the Argo documentation: https://argoproj.github.io/argo-workflows/fields/. Why is Kubernetes complaining here?

**Comment by terrytangyuan** [comment, marked as answer]
`name` is a sub-item in `configMapRef` so you would need two additional spaces before `name`, e.g. try the following:
```
      container:
        image: my-image:1.2.3
        envFrom:
          - configMapRef:
              name: "{{inputs.parameters.configmap}}"
          - secretRef:
              name: "{{inputs.parameters.secret}}"
```
