### DISCUSSION TITLE
`function "inputs" not defined` when templating manifests with Skaffold/Helm/etc

### DISCUSSION THREAD

**Discussion by kerthcet** [argoproj/argo-workflows#6067] [Q&A] [answered]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: hello world
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message       # parameter declaration
    container:
      # run cowsay with that message input parameter as args
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

I deployed an official demo, but print error `function "inputs" not defined`, can someone help pointing out the reason. My argo version is v3.0.5.
