### DISCUSSION TITLE
Support for feather or parquet format?

### DISCUSSION THREAD

**Discussion by lambertsbennett** [argoproj/argo-workflows#6155] [Q&A] [answered]
Currently we are evaluating using Argo Workflows to carry out ETL operations at my company. We are using pandas to manipulate tabular data and when I tried to create an output artifact by running `df.to_feather('/tmp/df.feather')`  I received an error that the path/file was not in the artifact store. When I switch the code to output JSON files everything runs smoothly. Does Argo Workflows not support formats like parquet and feather? For our applications the write time to a feather file is incredibly fast and it would be ideal to be able to use feather file artifacts. 
I'm relatively new to Argo Workflows, so I don't know if it doesn't support these formats or if I am fundamentally doing something wrong.

Thanks for the help.

**Comment by terrytangyuan** [comment, marked as answer]
I don't think Argo Workflows has any limitations on the file format. As long as the file is in the artifact storage, it should be able to retrieve the files. Is it possible that you specified the wrong key/path?

**Reply by terrytangyuan** [reply]
@lambertsbennett Do you have any reproducible example that could illustrate the behavior?

**Reply by lambertsbennett** [reply]
This is embarrassing, but in trying to recreate the problem I made an image, script, and template to reproduce the problem but it works. So now I need to understand what was wrong in my original setup. Thanks for the help.

**Reply by lambertsbennett** [reply]
Just for closure here is the script, dockerfile, and template that works.
```python
import argparse
import pandas as pd

parser = argparse.ArgumentParser()

parser.add_argument("--name", action='store', dest='name', help='filename')

df_dict = {
    "Timestamp": ["2021-15-6T00:00:00Z", "2021-15-6T00:05:00Z", "2021-15-6T00:10:00Z", "2021-15-6T00:15:00Z", "2021-15-6T00:20:00Z"],
    "SensorValue": [1,2,3,4,5]
}

df = pd.DataFrame.from_dict(df_dict)

if __name__ == '__main__':
    args = parser.parse_args()
    df.to_feather(args.name)
```
```dockerfile
#syntax=docker/dockerfile:1.2
FROM python:3.8.10-slim-buster
COPY ./requirements.txt ./requirements.txt
RUN --mount=type=secret,id=proxy,dst=proxy pip install -r requirements.txt --proxy $(cat proxy)
COPY ./feather_test.py ./feather_test.py
ENTRYPOINT ["python", "./feather_test.py"]
```
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: feather-test-

spec:
  entrypoint: dag-template
  arguments:
    parameters:
    - name: filepath
      value: /tmp/test.feather
    
  templates:
  - name: dag-template
    inputs:
      parameters:
      - name: filepath
    dag:
      tasks:
      - name: feather-save-template
        template: feather-save-template
        arguments:
          parameters:
          - name: filepath
            value: "{{inputs.parameters.filepath}}"
  
  - name: feather-save-template
    inputs:
      parameters:
      - name: filepath
    container:
      image: lambertsbennett/feathertest
      args: ["--name", "{{inputs.parameters.filepath}}"]
    outputs:
      artifacts:
      - name: featherfile
        path: /tmp/test.feather
```
and the requirements.txt
```
pandas==1.1.4
pyarrow
```
