### DISCUSSION TITLE
Is it possible to get the last (successful) workflow run as an input variable?

### DISCUSSION THREAD

**Discussion by chgl** [argoproj/argo-workflows#6186] [Q&A]
Is it possible to get the date of the last successful workflow run as an input variable? I'm looking at doing something like the cron-backfill example (https://github.com/argoproj/argo-workflows/blob/master/examples/cron-backfill.yaml), where a workflow is run multiple times a day and receives a timestamp range of data to process for the current day.

I'm currently running the following every hour, processing changed data of the current day multiple times:

```yaml
              arguments:
                parameters:
                  - name: BEGIN_DATE
                    value: "{{ workflow.creationTimestamp.Y }}-{{ workflow.creationTimestamp.m }}-{{ workflow.creationTimestamp.d }}"
                  - name: END_DATE
                    value: "9999-12-31"
``` 

It would of course be cleaner to just process the data since the last successful run (in case it keeps failing throughout one or more days). Is something like `workflow.lastSuccessfulRun` possible, or is there a better pattern?
