### DISCUSSION TITLE
Read value from json in workflow template without loop

### DISCUSSION THREAD

**Discussion by bmacera** [argoproj/argo-workflows#6278] [Q&A] [answered]
Hi,

I'm trying to read parameters from json in a workflow template. What I mean :

- I have a short template which just produces a json with year and year-1 as shown above
```yaml
- name: t-get-prev-year
    inputs:
      parameters:
      - name: year
    script:
      image: my-python-docker
      command: [python]
      source: |
        import json
        import sys
        json.dump([{"year": {{inputs.parameters.year}}, "prev-year": ({{inputs.parameters.year}}-1)}], open("/outputdir/years.json", "w"))

    outputs:
      parameters:
      - name: years-json
        valueFrom:
          path: /outputdir/years.json
```

- Then I want to use year and prev-year in my workflow template. It's possible to do it using loop mechanism by doing something like above
```yaml
        - name: select-features
          template: t-select-features
          withParam: "{{steps.get-prev-year.outputs.parameters.years-json}}"
          arguments:
            parameters:
              - name: year
                value: "{{item.year}}"
              - name: prev-year
                value: "{{item.prev-year}}"
```
It works but then if I want to use the outputs artefact (like with `from: "{{step.select-features.outputs.artifacts.features}}"`) or parameters (like with `withParam: "{{steps.select-features-s2.outputs.parameters.month-json}}"`) it won't be possible because my template is run in a loop, even if it is a loop of only one iteration.

Instead of running my template in a loop to read the json values I tried to use the builtin function `jsonpath` without success. I tryed directly `value:  "{{=jsonpath(steps.get-prev-year.outputs.parameters.years-json, '$.year')}}"` and then by passing the json as input `{{=jsonpath(inputs.parameters.year-json, '$.year')}}`.
I did it based on https://argoproj.github.io/argo-workflows/conditional-artifacts-parameters/#built-in-functions and https://argoproj.github.io/argo-workflows/variables/#examples.

Maybe there is something I missunderstood in the jsonpath syntax or another way to read json value that I didn't found. I'm working with `apiVersion: argoproj.io/v1alpha1`
