### DISCUSSION TITLE
How to manually release a lock due to synchronization

### DISCUSSION THREAD

**Discussion by saranyaeu2987** [argoproj/argo-workflows#6332] [Q&A] [answered]
Hi, I have set synchronization to **1** for a cronworkflow.  I deleted a running workflow of that cron but it didnt release a lock. Now the workflow of that cron is in pending state

```
❯ p argo list                                          
NAME                                              STATUS      AGE    DURATION   PRIORITY
wf-joe-v-cost-p8ndp                               Pending     5m     0s         0
```

If I check controller logs, this is what I see

```
time="2021-07-13T14:34:32Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/wf-joe-v-cost-p8ndp message="Waiting for argo/ConfigMap/wf-joe-v-cost-config-map/workflow lock. Lock status: 1/1 "
time="2021-07-13T14:34:32Z" level=info msg="Workflow update successful" namespace=argo phase= resourceVersion=60118989 workflow=wf-joe-v-cost-p8ndp
```

**yaml file**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: wf-joe-v-cost
  namespace: argo
spec:
  schedule: '{{ .Values.schedule }}'
  timezone: "America/Chicago"
  workflowSpec:
    entrypoint: wf-joe-v-cost-steps
    synchronization:
      semaphore:
        configMapKeyRef:
          name: wf-joe-v-cost-config-map
          key: workflow
    serviceAccountName: argo-s3-service-account
    templates:
# ...
```

How to manually release a lock without restarting the controller?
