### DISCUSSION TITLE
The keyFormat config in workflow-controller-configmap not working

### DISCUSSION THREAD

**Discussion by gwind** [argoproj/argo-workflows#6412] [Q&A]
```yaml
---
apiVersion: v1
data:
  default-v1: |
    archiveLogs: true
    s3:
      bucket: c80
      keyFormat: "{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
  empty: ""
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1
  name: artifact-repositories
---
apiVersion: v1
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: c80
      endpoint: minio:9000
      keyPrefix: argo-artifacts
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
  containerRuntimeExecutor: kubelet
  # ...
```

If `keyFormat` set in workflow-controller-configmap, restart workflow-controller pod would not working. But in artifact-repositories is ok.

https://github.com/argoproj/argo-workflows/blob/c80f4bc7322b1397c68c6cc14072bbb69c727496/docs/workflow-controller-configmap.yaml#L101
