### DISCUSSION TITLE
How can I specify global exit handler?

### DISCUSSION THREAD

**Discussion by minty99** [argoproj/argo-workflows#6473] [Q&A] [answered]
I want to specify a global exit handler: when all workflows ends, the exit handler should be executed.

I read this doc: https://argoproj.github.io/argo-workflows/default-workflow-specs/
However, when I add global exit handler like this into configmap:

```yaml
  workflowDefaults: |
    spec:
      onExit: exit-handler
    templates:
    - name: exit-handler
      steps:
      - - name: job-success
          template: send-ok-noti
          when: "{{workflow.status}} == Succeeded"
        - name: job-fail
          template: send-fail-noti
          when: "{{workflow.status}} != Succeeded"
    - name: send-ok-noti
      container:
        image: 'some_image'
        env:
        - name: MESSAGE
          value: "{{workflow.name}} succeeded!"
    - name: send-fail-noti
      container:
        image: 'some_image'
        env:
        - name: MESSAGE
          value: "{{workflow.name}} failed!"
```

An error like `exit-handler not found` occurs because `templates` section is replaced by own `templates` section of my workflows.

How can I do this? I think this may be possible because https://argoproj.github.io/argo-workflows/workflow-notifications/ mentions about this.

**Comment by minty99** [comment, marked as answer]
I asked this in Slack, 'Hong Wang' gave me good answer.
I should place `templates` section nested into `spec`.
```yaml
  workflowDefaults: |
    spec:
      onExit: exit-handler
      templates:
      - name: exit-handler
        steps:
        - - name: job-success
            template: send-ok-noti
            when: "{{workflow.status}} == Succeeded"
          - name: job-fail
            template: send-fail-noti
            when: "{{workflow.status}} != Succeeded"
      - name: send-ok-noti
        container:
          image: 'some_image'
          env:
          - name: MESSAGE
            value: "{{workflow.name}} succeeded!"
      - name: send-fail-noti
        container:
          image: 'some_image'
          env:
          - name: MESSAGE
            value: "{{workflow.name}} failed!"
```
