### DISCUSSION TITLE
using python script plus shell to install dependencies

### DISCUSSION THREAD

**Discussion by EBallou** [argoproj/argo-workflows#6552] [Q&A] [answered]
The script example is a bit simplistic - I'm curious of recommendations where I need to modify the OS and the Python libraries before the script is executed.  Below is a snippet of my attempt as an example, but it doesn't seem to take in the actual 'source'.  What would be better approach?

(I've also posted this in [slack argo-workflows](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1629208620014000?thread_ts=1629208620.014000&cid=C01QW9QSSSK).)

```yaml
      script:
        name: main
        image: 'python:3'
        command:
          - sh
          - '-c'
        args:
          - >-
            apk add git gcc libc-dev && python -m pip install -r /work/requirements.txt && python
        source: |
           import os

           key = 'MY_ENV_VAR'
           value1 = os.getEnv(key)

           print( "Got my env: ", value
```
