### DISCUSSION TITLE
Unacceptable slowness

### DISCUSSION THREAD

**Discussion by sheepdragon** [argoproj/argo-workflows#6633] [Q&A]
![image](https://user-images.githubusercontent.com/4659052/131519948-d7e0656b-c5b6-4b7c-b197-cf9a44eb5e52.png)
![image](https://user-images.githubusercontent.com/4659052/131521662-fc36924d-7833-4f43-985e-a68739876337.png)

The following workflow executes a diamond workflow
 
```yaml
# The following workflow executes a diamond workflow
# 
#   A
#  / \
# B   C
#  \ /
#   D
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        depends: "A"
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        depends: "A"
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        depends: "B && C"
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      imagePullPolicy: IfNotPresent
      command: [echo, "{{inputs.parameters.message}}"]
```

In this example, no time-consuming operation is actually done. In theory, it should be finished very quickly. Why is the operation so slow and even slower after adding the actual logic

**Comment by sheepdragon** [comment]
![image](https://user-images.githubusercontent.com/4659052/132951845-c09087c3-e33e-456a-a281-e9f588add852.png)

Time is consumed in this place.

Why is it so slow？

**Reply by sarabala1979** [reply]
It looks like Pod creation and pod completions are taking time. Can you check K8s API server timing(POD events)?

**Reply by sheepdragon** [reply]
![133174661-ea73f938-28ae-4bac-b1d7-b08147e5e8a8](https://user-images.githubusercontent.com/4659052/133175136-ae841c29-35bb-42df-b722-a0ee4a1e701f.png)

Is it reasonable to consume this time?
Whether this function is as slow as I use it under normal circumstances, I always doubt that I use it incorrectly.

**Comment by sheepdragon** [comment]
![image](https://user-images.githubusercontent.com/4659052/133179062-3bc16939-c85f-417c-9414-0fbe4dba3210.png)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-coinflip-
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
      - name: B
        depends: "A"
        template: echo

  - name: echo
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo 123"]
```
This is a simple example. Both sides are executed, eliminating the time-consuming of image pulling. Is time spent on k8s scheduling? Is it my k8s configuration?
