### DISCUSSION TITLE
Define K8s resources on template call, not template definition

### DISCUSSION THREAD

**Discussion by keshamin** [argoproj/argo-workflows#6709] [Q&A] [answered]
K8s resources are specified as a part of `ContainerTemplate`/`ScriptTemplate`/... 
To make resource requests/limits dynamic and provided by caller (user of defined template) I make pretty dirty constructions like:
```
script:
  image: busybox
  command: [ sh ]
  source: ls
  resources:
    requests:
      memory: {{inputs.parameters.memory_request}}
      cpu: {{inputs.parameters.cpu_request}}
    limits:
      memory: {{inputs.parameters.memory_limit}}
      cpu: {{inputs.parameters.cpu_limit}}
```

It brings 4 more parameters (more if gpu or other resources needed). 
Is there a better way to pass resources to template as a single object?
