### DISCUSSION TITLE
Is there any way to use HTTP, not HTTPS on v3?

### DISCUSSION THREAD

**Discussion by ryoohw-swk** [argoproj/argo-workflows#6836] [Q&A] [answered]
Since v3.0 the Argo Server listens for HTTPS requests.

But I want to use HTTP like on v2 in a private network. 

I set arguments like below.

```yaml
    spec:
      containers:
      - args:
        - server
        - --secure
        - 'false'
        - --auth-mode
        - server
```

I can't find to find disable TLS in the documentation.

Any help would be grateful, thanks.

**Comment by ryoohw-swk** [comment]
`--secure=false` is working.

But 
```yaml
--secure 
'false'
```
and
```yaml
env:
  - name: ARGO_SECURE
    value: 'false'
```
are not working.

**Reply by tczhao** [reply]
the env should work, maybe the deployment yaml was setup incorrectly,
If you don't use `--secure` argument, it will default to load value from env (`ARGO_SECURE`)

**Reply by ryoohw-swk** [reply]
Thanks, I'll check it out again.

**Reply by ryoohw-swk** [reply]
@tczhao 
It didn't work.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
  namespace: argo
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - args:
        - server
        - --auth-mode
        - server
        image: docker.io/argoproj/argocli:v3.1.12
        name: argo-server
        env:
          - name: ARGO_SECURE
            value: 'false'
        ports:
        - containerPort: 2746
          name: web
        readinessProbe:
          httpGet:
            path: /
            port: 2746
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 20
        securityContext:
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        resources:
          requests:
            cpu: 900m
            memory: 2Gi
          limits:
            cpu: 900m
            memory: 2Gi
      nodeSelector:
        kubernetes.io/os: linux
        env: kube-system
      securityContext:
        runAsNonRoot: true
      serviceAccountName: argo-server
      volumes:
      - emptyDir: {}
        name: tmp
```
logs
```
time="2021-10-04T22:51:31.471Z" level=info authModes="[server]" baseHRef=/ managedNamespace= namespace=argo secure=true
time="2021-10-04T22:51:31.471Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode"
time="2021-10-04T22:51:31.480Z" level=warning msg="You are running without client authentication. Learn how to enable client authentication: https://argoproj.github.io/argo-workflows/argo-server-auth-mode/"
time="2021-10-04T22:51:31.480Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-10-04T22:51:31.480Z" level=info msg="SSO disabled"
time="2021-10-04T22:51:31.491Z" level=info msg="Starting Argo Server" instanceID= version=v3.1.12
time="2021-10-04T22:51:31.492Z" level=info msg="Creating DB session"
time="2021-10-04T22:51:31.519Z" level=info msg="Node status offloading config" ttl=5m0s
time="2021-10-04T22:51:31.519Z" level=info msg="Creating event controller" operationQueueSize=16 workerCount=4
time="2021-10-04T22:51:31.522Z" level=info msg="Argo Server started successfully on https://localhost:2746"
```

When runs `kubectl describe`

```
Containers:
  argo-server:
    Container ID:  docker://88aae33ca54c497cf2702fd9b2cfbf0be5f532f4a18a840e60f1ce1628979140
    Image:         docker.io/argoproj/argocli:v3.1.12
    Image ID:      docker-pullable://argoproj/argocli@sha256:0b9a84afe4ccd8f6bcf0da950c7c0fc44413efb718a446c58c538433b85917b5
    Port:          2746/TCP
    Host Port:     0/TCP
    Args:
      server
      --auth-mode
      server
    State:          Running
      Started:      Tue, 05 Oct 2021 07:51:31 +0900
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     900m
      memory:  2Gi
    Requests:
      cpu:      900m
      memory:   2Gi
    Readiness:  http-get https://:2746/ delay=10s timeout=1s period=20s #success=1 #failure=3
    Environment:
      ARGO_SECURE:  false
    Mounts:
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from argo-server-token-d5mll (ro)
```

**Reply by ryoohw-swk** [reply]
@tczhao 
It worked(never mind readiness probe)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
  namespace: argo
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - args:
        - server
        - --auth-mode
        - server
        - --secure=false
        image: docker.io/argoproj/argocli:v3.1.12
        name: argo-server
        ports:
        - containerPort: 2746
          name: web
        readinessProbe:
          httpGet:
            path: /
            port: 2746
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 20
        securityContext:
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        resources:
          requests:
            cpu: 900m
            memory: 2Gi
          limits:
            cpu: 900m
            memory: 2Gi
      nodeSelector:
        kubernetes.io/os: linux
        env: kube-system
      securityContext:
        runAsNonRoot: true
      serviceAccountName: argo-server
      volumes:
      - emptyDir: {}
        name: tmp
```
logs
```
time="2021-10-04T23:01:59.637Z" level=info authModes="[server]" baseHRef=/ managedNamespace= namespace=argo secure=false
time="2021-10-04T23:01:59.637Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo-workflows/tls/"
time="2021-10-04T23:01:59.637Z" level=warning msg="You are running without client authentication. Learn how to enable client authentication: https://argoproj.github.io/argo-workflows/argo-server-auth-mode/"
time="2021-10-04T23:01:59.637Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-10-04T23:01:59.637Z" level=info msg="SSO disabled"
time="2021-10-04T23:01:59.648Z" level=info msg="Starting Argo Server" instanceID= version=v3.1.12
time="2021-10-04T23:01:59.648Z" level=info msg="Creating DB session"
time="2021-10-04T23:01:59.670Z" level=info msg="Node status offloading config" ttl=5m0s
time="2021-10-04T23:01:59.670Z" level=info msg="Creating event controller" operationQueueSize=16 workerCount=4
time="2021-10-04T23:01:59.677Z" level=info msg="Argo Server started successfully on http://localhost:2746"
```
When runs `kubectl describe`
```
Containers:
  argo-server:
    Container ID:  docker://d4567b3e268925a08917cc701089589119218ab37031cde272168f3110ccaced
    Image:         docker.io/argoproj/argocli:v3.1.12
    Image ID:      docker-pullable://argoproj/argocli@sha256:0b9a84afe4ccd8f6bcf0da950c7c0fc44413efb718a446c58c538433b85917b5
    Port:          2746/TCP
    Host Port:     0/TCP
    Args:
      server
      --auth-mode
      server
      --secure=false
    State:          Running
      Started:      Tue, 05 Oct 2021 08:01:59 +0900
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     900m
      memory:  2Gi
    Requests:
      cpu:        900m
      memory:     2Gi
    Readiness:    http-get https://:2746/ delay=10s timeout=1s period=20s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from argo-server-token-d5mll (ro)
```

**Comment by grid-dev** [comment, marked as answer]
I patched the config using kustomize and got it working

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
  - argo-workflows-ns.yaml
  - https://raw.githubusercontent.com/argoproj/argo-workflows/v3.2.8/manifests/install.yaml

patchesStrategicMerge:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argo-server
    spec:
      template:
        spec:
          containers:
            - name: argo-server
              args:
                - server
                - "--secure=false"
              readinessProbe:
                httpGet:
                  scheme: HTTP

```

**Comment by ebuildy** [comment]
My quick start setup:

```yaml
# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/common-name: workflows.xxx
spec:
  rules:
  - host: workflows.xxx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-server
            port:
              number: 2746
  tls:
  - hosts:
    - workflows.xxx
    secretName: server-ingress
```


```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
  - ingress.yaml
  - argo-workflows-ns.yaml
  - https://github.com/argoproj/argo-workflows/releases/download/v3.4.5/install.yaml
patches:
- target:
    kind: Deployment
    name: argo-server
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argo-server
    spec:
      template:
        spec:
          containers:
            - name: argo-server
              args:
                - server
                - "--secure=false"
                - "--auth-mode=server"
              readinessProbe:
                httpGet:
                  scheme: HTTP
```
