### DISCUSSION TITLE
How to use resume on selected node feature

### DISCUSSION THREAD

**Discussion by daniel-winter** [argoproj/argo-workflows#6938] [Q&A]
Hello together, with this merged PR https://github.com/argoproj/argo-workflows/pull/6885 its now possible to use resume on selected nodes. Unfortunately, I can't found any documentation/code example how to use it now, see question marks in the code. I am not sure whats needed (parameter etc.) to trigger a specific node?

```
templates:
    - name: build-and-test
      dag:
              tasks:
                - name: approve
                  template: approve
                - name: approve1
                  template: approve1
                - name: wait-for-approve
                   dependencies: [approve]
                   template: wait-for-approve
                - name: wait-for-approve1
                   dependencies: [approve1]
                   template: wait-for-approve1
    - name: approve
      suspend: {}
      ???
    - name: approve1
      suspend: {}
      ????
     ....
```
We have already upgraded argo-workflows to v3.2.0 but the resume button for the node is missing in the sidebar, see screenshot below: 
![Bildschirmfoto 2021-10-14 um 11 53 12](https://user-images.githubusercontent.com/33256696/137453563-7b345f1f-aac7-44ba-900f-3b39c836d9fd.png)

Can somebody please help me out here?
