### DISCUSSION TITLE
How to trigger a workflow from UI?

### DISCUSSION THREAD

**Discussion by bygui86** [argoproj/argo-workflows#7038] [Q&A] [answered]
Hi guys,

apart from cli, I would like to trigger a workflow (ClusterWorkflowTemplate) from the UI... but how can I do it?

when I select the workflow and click on `Submit` I see no parameters:

![Screenshot 2021-10-22 at 17 03 07](https://user-images.githubusercontent.com/22518997/138477838-7a75afad-e9b5-457d-8b9a-7c61753fe208.png)

but actually I specified some parameters:

```yaml
...
spec:
  templates:
    - name: go-pipeline-tmpl
      inputs:
        parameters:
          - name: repo_url
          - name: context_path
          - name: base_path
          - name: revision
          - name: checkout_sha
          - name: dockerfile_path
          - name: container_image_registry
          - name: container_image_tag_revision
...
```

thanks in advance for any help or tip!

**Comment by sarabala1979** [comment]
you can use `submit` button in clustertemplate page

![image](https://user-images.githubusercontent.com/33908564/138485134-4bd83c31-72ed-4718-be48-a12f11533672.png)

**Comment by bygui86** [comment]
@sarabala1979 thanks, but as I mentioned in the question I don't see any parameter I specified in the workflow definition.
Please have a look again at my original question for screenshot and yaml.

**Comment by bygui86** [comment]
Sorry I forgot to mention the version of argo workflows I run:   3.1.3

**Comment by sarabala1979** [comment, marked as answer]
Only Spec level (global) parameters will be displayed in UI.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: cluster-workflow-template-submittable
spec:
  entryPoint: whalesay-template
  arguments:
    parameters:
      - name: message
        value: hello world
```
![image](https://user-images.githubusercontent.com/33908564/138745250-944d8ef7-4c42-4fdc-a736-6af86ebf84b9.png)

**Reply by bygui86** [reply]
@sarabala1979 I will try to find a compromise and let you know
meanwhile thanks for your help!

**Reply by bygui86** [reply]
@sarabala1979 thanks for explanation and your help!! Now I get it, so here the working ClusterWorkflowTemplate:

```yaml
...
spec:
  arguments:
      parameters:
        - name: repo_url
        - name: context_path
        - name: base_path
        - name: revision
        - name: checkout_sha
        - name: dockerfile_path
        - name: container_image_registry
        - name: container_image_tag_revision
  templates:
    - name: go-pipeline-tmpl
      inputs:
        parameters:
          - name: repo_url
          - name: context_path
          - name: base_path
          - name: revision
          - name: checkout_sha
          - name: dockerfile_path
          - name: container_image_registry
          - name: container_image_tag_revision
...
```
