### DISCUSSION TITLE
Query API for parent/child workflow relationships

### DISCUSSION THREAD

**Discussion by pboone** [argoproj/argo-workflows#7123] [Q&A]
I have a Workflow of Workflows. I would like to query the Kubernetes API or the Argo API to determine which workflows were triggered by the parent Workflow of Workflows. However, I don't see any metadata in the Workflow object that would give me this information. Is this possible?

**Comment by sarabala1979** [comment]
you can add labels to child workflow

```yaml
            labels:
              parent-workflow: "{{workflow.name}}"
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-of-workflows-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: workflow1
            template: triggerWorkflowUsingResourceWithoutArgument
            arguments:
              parameters:
              - name: workflowtemplate
                value: "workflow-template-submittable"
        - - name: workflow2
            template: triggerWorkflowUsingResourceWithArgument
            arguments:
              parameters:
              - name: workflowtemplate
                value: "workflow-template-submittable"
              - name: message
                value: "Welcome Argo"

    - name: triggerWorkflowUsingResourceWithoutArgument
      inputs:
        parameters:
          - name: workflowtemplate
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: workflow-of-workflows-1-
            labels:
              parent-workflow: "{{workflow.name}}"
          spec:
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
    - name: triggerWorkflowUsingResourceWithArgument
      inputs:
        parameters:
          - name: workflowtemplate
          - name: message
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: workflow-of-workflows-2-
            labels:
              parent-workflow: "{{workflow.name}}"
          spec:
            arguments:
              parameters:
              - name: message
                value: {{inputs.parameters.message}}
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
```
