### DISCUSSION TITLE
Failed to create workflow template: Post EOF

### DISCUSSION THREAD

**Discussion by carter115** [argoproj/argo-workflows#7174] [Q&A]
##  Message

Failed to create workflow template: Post "http://localhost:2746/api/v1/workflow-templates/default?": EOF

## main.go

```
var (
	ns       = "argo"
	argoAddr string
)

func getAuth() func() string {
	return func() string {
		return "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlRWb0dvYmdpMEVzeU5XOGlJY19KWmN0bHRKQm11X21RQ3ZRZHBZX0d0SFUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImNpY2QtdG9rZW4tODV0cmoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiY2ljZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQ3NTc0MDA1LWYxOWYtNGViNC1hNmMzLTY1MDEwNzlhZTZmOSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmNpY2QifQ.LmiTyZp0SiAWk8zfUkGJ3etVR58J9--12IUKid8ikMnaM6eb2sMRnCEmO0As9MWd0x87zm6zxgeYIWWVLE9OniDAJJyE4HfiOt3wqoiMuPPnvwUsa4etaADXIwFUPkqKoOF5sBC7KZO2HmYxvBkZu8nc5qgR-VEOaS9LMz8MzSyFHWcUPnZIBt4dvSzMxOzicmDDQAIrhCXTwrvddaUxg9gQ0HurMfmaCns_plFM2_ONNWC9QLKAdSD2qHRNtiTtUYFv7Sdo7aVLS2yUKF4kOSbaB7tSBvVxRbtY9G1uidj1l6m4E9NkA9fJ****"
	}
}

func main() {
	opts := apiclient.Opts{
		ArgoServerOpts: apiclient.ArgoServerOpts{
			URL:                argoAddr,
			Secure:             false,
			//InsecureSkipVerify: true,
			HTTP1:              true,
		},
		AuthSupplier:         getAuth(),
		ClientConfigSupplier: func() clientcmd.ClientConfig { return client.GetConfig() },
		Offline:              false,
		Context:              context.Background(),
	}
	ctx, cli, err := apiclient.NewClientFromOpts(opts)
	checkErr(err)
	fmt.Println("context:", ctx)

	info, err := cli.NewInfoServiceClient()
	checkErr(err)
	fmt.Printf("info: %+v\n", info)

	wft, err := cli.NewWorkflowTemplateServiceClient()
	checkErr(err)

	fileContents, err := util.ReadManifest("./yamls/a.yaml")
	if err != nil {
		log.Fatal(err)
	}

	var workflowTemplates []wfv1.WorkflowTemplate
	for _, body := range fileContents {
		wftmpls := unmarshalWorkflowTemplates(body, false)
		workflowTemplates = append(workflowTemplates, wftmpls...)
	}

	if len(workflowTemplates) == 0 {
		log.Println("No workflow template found in given files")
		os.Exit(1)
	}

	for _, wftmpl := range workflowTemplates {
		if wftmpl.Namespace == "" {
			wftmpl.Namespace = client.Namespace()
		}
		created, err := wft.CreateWorkflowTemplate(ctx, &workflowtemplate.WorkflowTemplateCreateRequest{
			Namespace: wftmpl.Namespace,
			Template:  &wftmpl,
		})
		if err != nil {
			log.Fatalf("Failed to create workflow template: %v", err)
		}
		fmt.Println("created:", created)
	}
}
```

## Output:

```
address: localhost:2746
context: context.Background
info: {baseUrl:http://localhost:2746 authorization:Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlRWb0dvYmdpMEVzeU5XOGlJY19KWmN0bHRKQm11X21RQ3ZRZHBZX0d0SFUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImNpY2QtdG9rZW4tODV0cmoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiY2ljZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQ3NTc0MDA1LWYxOWYtNGViNC1hNmMzLTY1MDEwNzlhZTZmOSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmNpY2QifQ.LmiTyZp0SiAWk8zfUkGJ3etVR58J9--12IUKid8ikMnaM6eb2sMRnCEmO0As9MWd0x87zm6zxgeYIWWVLE9OniDAJJyE4HfiOt3wqoiMuPPnvwUsa4etaADXIwFUPkqKoOF5sBC7KZO2HmYxvBkZu8nc5qgR-VEOaS9LMz8MzSyFHWcUPnZIBt4dvSzMxOzicmDDQAIrhCXTwrvddaUxg9gQ0HurMfmaCns_plFM2_ONNWC9QLKAdSD2qHRNtiTtUYFv7Sdo7aVLS2yUKF4kOSbaB7tSBvVxRbtY9G1uidj1l6m4E9NkA9fJ****** insecureSkipVerify:false}
2021/11/05 17:11:09 Failed to create workflow template: Post "http://localhost:2746/api/v1/workflow-templates/default?": EOF

```

a.yaml

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-random-fail-template
spec:
  templates:
    - name: random-fail-template
      retryStrategy:
        limit: 10
      container:
        image: python:alpine3.6
        command: [python, -c]
        # fail with a 66% probability
        args: ["import random; import sys; exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)"]
---
```
