### DISCUSSION TITLE
Can't find logs of java container

### DISCUSSION THREAD

**Discussion by naveenc** [argoproj/argo-workflows#7264] [Q&A] [answered]
Hi ,
I need some help to find the java logs 
I created a java project which just has a main method and which prints an message. 

```java
public static void main(String[] args) throws IOException {
            System.out.println("*****************Hello world ******************");
    }
```

Created the docket image and deployed as a Cron workflow using below template.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: example
    templates:
    - name: example
      container:
        image: docker-java:1.0
        command: [sh, -c]
        args: ["date; sleep 9"]
```

The workflow is triggered and running successfully But i am not able to figure out the message 
"*****************Hello world ******************"

Could you please help where do i find this . I verified in main,init and wait logs

Actually my use-case is using cron worklow i will ready the nats message and push to time series DB
