### DISCUSSION TITLE
How can I get Http template output?

### DISCUSSION THREAD

**Discussion by polarbear567** [argoproj/argo-workflows#7376] [Q&A] [answered]
Now we just can get the http template output by file? or there has any other ways?

**Comment by terrytangyuan** [comment, marked as answer]
You can access the following available variables:
```
        # Available variables:
        #  request.body: string, the response body
        #  request.headers: map[string][]string, the response headers
        #  response.url: string, the request url
        #  response.method: string, the request method
        #  response.statusCode: int, the response status code
        #  response.body: string, the response body
        #  response.headers: map[string][]string, the response headers
```

**Reply by polarbear567** [reply]
Hi @terrytangyuan 
Thank you for your reply.
Could u pls give me an example? I want to use the http template output for other tasks.
I find this issue: https://github.com/argoproj/argo-workflows/issues/7199
The yaml file contained in this scenario is my current usage scenario.

**Reply by terrytangyuan** [reply]
Here's an example: https://github.com/argoproj/argo-workflows/blob/master/examples/http-success-condition.yaml

**Reply by polarbear567** [reply]
Hi @terrytangyuan 
I don't think your example is my scenario. In your example, it's just used in http template, but I want to use the http template output in another dag task.
Thanks again.

**Reply by terrytangyuan** [reply]
I believe you can write the output to a file or just echo it out and then reference it via `{{tasks.http.outputs.result}}`. An example:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-outputs-
spec:
  entrypoint: main
  templates: 
    - name: main
      dag:
        tasks:
          - name: http
            template: http
            arguments:
              parameters:
                - name: url
                  value: >-
                    https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json
          - name: echo
            template: echo
            arguments:
              parameters:
                - name: msg
                  value: '{{tasks.http.outputs.result}}'
            dependencies:
              - http
    - name: http
      inputs:
        parameters:
          - name: url
      http:
        url: '{{inputs.parameters.url}}'
    - name: echo
      inputs:
        parameters:
          - name: msg
      container:
        image: 'argoproj/argosay:v2'
        args:
          - echo
          - '{{inputs.parameters.msg}}'

```
