### DISCUSSION TITLE
is there any way to check a global parameter is set or not?

### DISCUSSION THREAD

**Discussion by liuzqt** [argoproj/argo-workflows#7401] [Q&A] [answered]
The title said it.  I have several conditional executions in my dag, so some global output parameters might not be set if some previous tasks are skipped.

**Comment by thegreymatter** [comment]
I solution that I found out to be working is to start by setting them up to some "empty" or "null" equivalent result and then override them with the conditional task. it's not very neat, but if you can define a null result, it might work for you.

**Comment by terrytangyuan** [comment, marked as answer]
You can assign a default value in `valueFrom.default` and then check whether your parameter value is the default.
```
      parameters:
      - name: hello-param
        valueFrom:
          default: "Foobar"
          path: /tmp/hello_world.txt

```
