### DISCUSSION TITLE
Can I access workflow metadata within the template?

### DISCUSSION THREAD

**Discussion by liuzqt** [argoproj/argo-workflows#7410] [Q&A] [answered]
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-pipeline
spec:
  workflowMetadata:
    annotations:
      myanno: hello
  entrypoint: main
  arguments:
    parameters: []
  templates:
    - name: main
      dag:
        tasks:
          - name: dummy
            inline:
              container:
                image: docker/whalesay:latest
                command: [sh, -c]
                args: ["echo {{workflow.metadata.annotations.myanno}}"]

```

for example, I declare some annotations in the `workflowMetadata`, how can I access these variable within the template? I've tried `{{workflow.metadata.annotations.myanno}}` but no luck
