### DISCUSSION TITLE
how to use `jsonpath` in `when` condition

### DISCUSSION THREAD

**Discussion by liuzqt** [argoproj/argo-workflows#7413] [Q&A] [answered]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-pipeline
spec:
  entrypoint: main
  arguments:
    parameters: 
      - name: myjson
         value: '{"key1": 100}'
  templates:
    - name: main
      dag:
        tasks:
          - name: dummy
            when: "1 < {{jsonpath(workflow.parameters.myjson), '$.key1')}}"
            inline:
              container:
                image: docker/whalesay:latest
                command: [sh, -c]
                args: ["echo {{workflow.parameters.myjson}}"]
```

I was trying to access the json value in `when` condition using 
```yaml
when: "1 < {{jsonpath(workflow.parameters.myjson), '$.key1')}}"
```
but got this error:
```
Invalid 'when' expression '1 < {{jsonpath(workflow.parameters.myjson), '$.key1')}}': Invalid token: '{{' (hint: try wrapping the affected expression in quotes ("))
```

**Comment by thegreymatter** [comment]
I believe you are missing  `=`  to mark it as an expression and not a template 

```yaml
when: "1 < {{jsonpath(workflow.parameters.myjson), '$.key1')}}"
```
should turn to 
```yaml
when: "1 < {{=jsonpath(workflow.parameters.myjson), '$.key1')}}"
```

**Reply by liuzqt** [reply]
tried that, but no luck, got another error:
```
Invalid 'when' expression '1 < {{=jsonpath(workflow.parameters.myjson), '$.key1')}}': Invalid token: '{{=' (hint: try wrapping the affected expression in quotes ("))
```

reproducing template:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-pipeline
spec:
  entrypoint: main
  arguments:
    parameters: 
      - name: myjson
        value: '{"key1": 100}'
  templates:
    - name: main
      dag:
        tasks:
          - name: dummy
            when: "1 < {{=jsonpath(workflow.parameters.myjson), '$.key1')}}"
            inline:
              container:
                image: docker/whalesay:latest
                command: [sh, -c]
                args: ["echo {{workflow.parameters.myjson}}"]
```

**Reply by thegreymatter** [reply]
whitespace is required after {{=

**Reply by liuzqt** [reply]
Hi @thegreymatter I've tried adding whitespace but still not working 
```yaml
when: "1 < {{= jsonpath(workflow.parameters.myjson), '$.key1')}}"
```
and the error msg is the same 
```
Invalid 'when' expression '1 < {{= jsonpath(workflow.parameters.myjson), '$.key1')}}': Invalid token: '{{=' (hint: try wrapping the affected expression in quotes ("))
```

Am I doing something wrong?

**Reply by agilgur5** [reply]
As the below [comment](https://github.com/argoproj/argo-workflows/discussions/7413#discussioncomment-2282076) says, your `jsonpath` has an extra closing parenthesis. Fixing that makes it work:

```yaml
when: "1 < {{=jsonpath(workflow.parameters.myjson, '$.key1')}}"
```

**Comment by EzrealK** [comment]
I got the same problem, how to solve that?

**Comment by alexec** [comment]
`when` conditions do not support `{{=`, you cannot do this I'm afraid

**Reply by liuzqt** [reply]
@alexec  thanks. Is there any workaround to evaluate json object from workflow parameters in `when` condition?

**Reply by alexec** [reply]
AFAIK no

**Reply by liuzqt** [reply]
got it, thanks

**Comment by crenshaw-dev** [comment, marked as answer]
Just [abuse a bug](https://github.com/argoproj/argo-workflows/issues/7576) to make it work.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: my-pipeline
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: myjson
        value: '{"key1": 100}'
  templates:
    - name: main
      dag:
        tasks:
          - name: dummy
            when: "1 < {{=jsonpath(workflow.parameters.myjson, '$.key1')}}"
            inline:
              container:
                image: docker/whalesay:latest
                command: [sh, -c]
                args: ["echo {{workflow.parameters.myjson}}"]
```

```
 $ argo submit -n argo test.yaml --log
Name:                my-pipeline
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Wed Mar 02 12:15:17 -0500 (now)
Progress:            
Parameters:          
  myjson:            {"key1": 100}

This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
```

The part of Argo Workflows that shouts at you for using expressions in `when` fields only _sees_ the `{{=` if there's an error in the expression (and it therefore doesn't get replaced with some other value). If you fix the typo (the extra `)` after `workflow.parameters.myjson`), the expression evaluates to `true` before the shouty code sees it.

It's a bit like drinking your Coca-Cola _before_ going through airport security. You're moving the same stuff, but now it's allowed.

(I can't think of a good metaphor for the expression failing to execute... you try to drink the Coke, but the lid is too tight? idk. Anyway, you gotta drink the Coke, or you're not getting through security.)
