### DISCUSSION TITLE
Unable resolve `pod.name` in withItems loop

### DISCUSSION THREAD

**Discussion by Rayer** [argoproj/argo-workflows#7447] [Q&A]
Version: Argo 3.2.4
Issue: Can't resolve {{ pod.name }} when this template using `withValue` loop
Error message : `failed to resolve {{ pod.name }}`

```
      - name: long_training
        inputs:
          parameters:
            - name: site_memory_req
            - name: site_cpu_req
            - name: training_date
        outputs: {}
        metadata: {}
        steps:
          - - name: training
              arguments:
                parameters:
                  - name: required_mem
                    value: '{{ inputs.parameters.site_memory_req }}Gi'
                  - name: required_cpu
                    value: '{{ inputs.parameters.site_cpu_req }}'
                  - name: job
                    value: demo_job
                  - name: job_args
                    value: >-
                      -c
                      /etc/config_dev.yaml
                      --argo_pod {{ pod.name }} --argo_uid {{ workflow.uid }}
                      --date_str {{ inputs.parameters.date }}
                      --value {{ item }}
              templateRef:
                name: demo
                template: default-step
              withItems:
                - 1
                - 2
                - 3
                - 4
```

if I use `pod_name_ph` to take place  `{{ pod.name }}`, everything will be fine. For other non-loop templates, `pod.name` can be resolved without any problem. Can anyone shed a light how to get pod name in loop case? thanks~
