### DISCUSSION TITLE
Links variables value manipulation

### DISCUSSION THREAD

**Discussion by ryhorB-epam** [argoproj/argo-workflows#7487] [Q&A] [answered]
Is it possible to add the ability to manipulate variables in references, for example, to use string functions. Now there are several variables `${status.startedAt}` `${workflow....}` but unlike variables `{{}}` there is no example of manipulation with the value of variables in `${}`.
For example: 
```yaml
links: |
- name: Workflow link
  scope: workflow
  url: https://logs-storage/${status.startedAt.Y}/${status.startedAt.m}/${status.startedAt.d}
```
is converted to `https://logs-storage/null/null/null` and I would like to `https://logs-storage/2022/01/03`. It is possible to use the sprig functions, but it is not yet clear how.
