### DISCUSSION TITLE
Use ArgoCD Dex for authentication

### DISCUSSION THREAD

**Discussion by nishit93-hub** [argoproj/argo-workflows#7499] [General]
Hi There,

I am using ArgoCD Dex for Argo workflow authentication. I am following this link `https://argoproj.github.io/argo-workflows/argo-server-sso-argocd/`

However, while adding  In ArgoCD, add an environment variable to Dex deployment and configuration. 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
        - name: dex
          env:
            - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: argo-workflows-sso
                  key: client-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Kustomize sees the value of dex.config as a single string instead of yaml. It will not merge
  # Dex settings, but instead it will replace the entire configuration with the settings below,
  # so add these to the existing config instead of setting them in a separate file
  dex.config: |
    # Setting staticClients allows ArgoWorkflows to use ArgoCD's Dex installation for authentication
    staticClients:
      - id: argo-workflows-sso
        name: Argo Workflow
        redirectURIs:
          - https://argo-workflows.mydomain.com/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET


```

I am getting this error `error: error validating "manifest-for-authenticating-againt-dex-server.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by ttalal** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-dex-server

  template:
    spec:
      containers:
        - name: dex
          env:
            - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: argo-workflows-sso
                  key: client-secret
```
