### DISCUSSION TITLE
Sequential withParam

### DISCUSSION THREAD

**Discussion by ctgschollar** [argoproj/argo-workflows#7663] [Q&A] [answered]
I am trying to create a workflow that can perform arbitrary steps based on a parameter which lists the name of each step. I have found the withParams field to loop over my steps, however withParams launches steps in parallel. I need the steps to be run sequentially in order as each step depends on the result of the previous step.

Is there a way to run a loop where each step runs sequentially rather than in parallel? 

I have a simple example workflow below where I run whalesay. I launch this with eg.

argo submit --watch -n argo steps_example.yml -p messages=[\"1\",\"2\",\"3\"]

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: steps
  securityContext:
    runAsUser: 1000
  arguments:
    parameters:
    - name: messages
      value:
        - blah
  templates:
  - name: steps
    steps:
    - - name: step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withParam: "{{workflow.parameters.messages}}"
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

**Comment by terrytangyuan** [comment, marked as answer]
You can use `parallelism` at either workflow or template-level to limit the max total parallel pods that can execute at the same time. Is that what you need?

**Reply by ctgschollar** [reply]
Yes, this works perfectly for my needs. The only issue is that the UI displays the steps as parallel, but not a reason I can't use this.
![image](https://user-images.githubusercontent.com/1866355/151379270-b1787e5b-8e32-460c-b939-f907facb4e28.png)

Below is an updated workflow with your suggestion.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: steps
  securityContext:
    runAsUser: 1000
  arguments:
    parameters:
    - name: messages
      value:
        - blah
  templates:
  - name: steps
    parallelism: 1
    steps:
    - - name: step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withParam: "{{workflow.parameters.messages}}"
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```
