### DISCUSSION TITLE
How to access server API when auth mode is set to "sso"?

### DISCUSSION THREAD

**Discussion by paeblits** [argoproj/argo-workflows#7668] [Q&A] [answered]
The documentation says that for automation we need to generate a token to access the server REST API, which does not work if auth mode is set to "sso".  I receive the response:
`{
    "code": 16,
    "message": "token not valid for running mode"
}`

I cannot find any documentation on doing automation when the server is in this mode.

How do I access the the REST API when auth mode is set to "sso"? Or, how can we do automation when using this auth mode?

**Comment by paeblits** [comment, marked as answer]
One way I found to do this is to have an Identity and Access Management solution like Keycloak be able to exchange user credentials for a token using a client configured for OIDC. Then, in the request in my code I added the token to the **cookie** header field in my requests, not the authorization header field. 

Edit: Changed "my client" to "the request in my code" for clarity.

**Reply by johnDorian** [reply]
I'm glad to hear you managed to get this working, and thanks for providing an answer to your own question. I have a few questions about your setup. Could you provide more information about the format of your token you are using?
Currently I have argo server (version 3.2.6) setup with the following
```bash
 --auth-mode=sso
 --auth-mode=client
```

```yaml
      sso:
        issuer: https://XXX/auth/realms/XXX
        clientId:
          name: 
          key: client-id
        clientSecret:
          name: 
          key: client-secret
        redirectUrl: https://XXX/oauth2/callback
 ```
When I login to the server UI using oauth I get a cookie from `authorization="Bearer v2:XXX"`
 
 
 Could you describe the workflow for a user to programatically get a token and access the argo API?
