### DISCUSSION TITLE
Init and Wait containers Readonly file system and volume mount

### DISCUSSION THREAD

**Discussion by obanby** [argoproj/argo-workflows#7677] [Q&A] [answered]
Hi team, 

I am currently running my workflow executor with a read-only file system regulated by Open Policy Agent (OPA).
I want to know if there is a way I can mount a volume to both the `init` and `wait` containers so I can utilize log archiving and such. 

My executor configs look like this
```yaml
executor:
    resources:
      limits:
        memory: 250M
        cpu: 0.5
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsGroup: 1000
      runAsUser: 1000
```

When running with the above configurations, I get an error
> Error (exit code 1): mkdir /tmp/argo: read-only file system

Here is what I  have tried:
* I tried to add a volume and volume mount to my `main` container, but the `wait` container doesn't inherit the volume
* I checked the source code for a way to change the `tempOutArtDir` property, but couldn't find any
* Tried to define a volume under `workflowDefaults` in my helm chart, but no luck either. 

I would appreciate your help.
