### DISCUSSION TITLE
How to manage and reference multiple artifact repositories ?

### DISCUSSION THREAD

**Discussion by EzrealK** [argoproj/argo-workflows#7902] [Q&A]
I have multiple artifact repositories and have them configured in the configMap, like:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
data:
  bucket1: |
    s3:
      endpoint: ...
      bucket: bucket1
      accessKeySecret:
        ...
      secretKeySecret:
        ...

  bucket2: |
    s3:
      endpoint: ...
      bucket: bucket2
      accessKeySecret:
        ...
      secretKeySecret:
        ...
```

Then, I want to reference them in a key-only way in the same workflow ：

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-
spec:
  entrypoint: main

  artifactRepositoryRef:
    configMap: artifact-repositories
    key: bucket1

  templates:
  - name: main
    steps:
    - - name: step1
        template: step1
    - - name: step2
        template: step2

  - name: step1
    container:
      ...
    outputs:
      artifacts:
        - name: art-output
          path: /tmp/s1.txt 
          s3:   # use bucket1 through artifactRepositoryRef
            key: argo/s1.txt


  - name: step2
    container:
      ...
    outputs:
      artifacts:
        - name: art-output
          path: /tmp/s2.txt 
          s3:
            # how to use bucket2 in a key-only way
            key: argo/s2.txt  

```

`artifactRepositoryRef` can only reference one artifact repository,  how to reference another artifact repository in a concise way ?
