### DISCUSSION TITLE
supplied ValueFrom is ignoring default

### DISCUSSION THREAD

**Discussion by CodingOrca** [argoproj/argo-workflows#7905] [Q&A] [answered]
I try to implement an approve - release workflow, have a timeout on the approve step and be able to react if the timeout has expired.

The documentation of the SupppliedValueFrom:
https://argoproj.github.io/argo-workflows/fields/#suppliedvaluefrom
shows an example without a duration:
https://github.com/argoproj/argo-workflows/blob/master/examples/suspend-template-outputs.yaml

Is is working, but it is not of practical use if I have no duration set on the  suspend Template. So I have modified it according to the documentation found here:
https://argoproj.github.io/argo-workflows/executor_swagger/#valuefrom

This is only the changed part of the example:
```
- name: approve
    suspend:
      duration: "60"
    outputs:
      parameters:
        - name: message
          valueFrom:
            default: "some default value"
            supplied: {}
```
If I run the workflow, and do not supply a value from outside, after 60 seconds the output printed by the "release" step is:
`{{steps.approve.outputs.parameters.message}}`

But I am expecting the "release" step to print:
`some default value`

If I feed a value to the parameter per REST API, and set it to e.g. "AP has approved this!", and then I resume the workflow - also per REST API in my case - the "release" step is, indeed, printing the value which have passed:
`AP has have approved this!`

What am I doing wrong?
I am using argo workflows v3.2.4
