### DISCUSSION TITLE
How to wait for resource creation to complete or set a timeout

### DISCUSSION THREAD

**Discussion by EzrealK** [argoproj/argo-workflows#7943] [Q&A]
I want to create pv and pvc through resource template, like:
```
  - name: create-pv
    resource:
      action: create
      successCondition: status.succeeded > 0
      failureCondition: status.failed > 3
      manifest: |
        apiVersion: v1
        kind: PersistentVolume
        metadata:
          finalizers:
            - kubernetes.io/pv-protection
          name:fs-argo-{{workflow.name}}
        spec:
          accessModes:
            - ReadWriteMany
            - ReadOnlyMany
          capacity:
            storage: 1000Gi
          csi:
            driver: ...
            volumeAttributes:
              path: /argo-{{workflow.name}}
              server: ...
            volumeHandle: fs-argo
          persistentVolumeReclaimPolicy: Retain
          volumeMode: Filesystem
```
Since the creation of the PV takes a little time, I always get the error with status.checked. How to solve this problem ?
