### DISCUSSION TITLE
Workflow intermittently succeeding

### DISCUSSION THREAD

**Discussion by mattharrigan** [argoproj/argo-workflows#7948] [Q&A] [answered]
Hello. I'm brand new to argo but like it very much so far. I am trying to run `argosay` but with istio sidecars. It succeeds intermittently. I suspect there is a race condition for the istio sidecar to be ready before the wait container timeouts. The error I sometimes get is below. I am using the `k8sapi` executor. My hunch is that there is some config to extend this timeout but I haven't found it in the docs yet. Not sure if this is an issue or not so I thought I would start here. How can I make this succeed reliably?

```
Error (exit code 1): failed to wait for main container to complete: timed out waiting for the condition: failed to establish pod watch: Get "https://172.30.0.1:443/api/v1/namespaces/rotorcraft-digital-twin/pods?fieldSelector=metadata.name%3Dsparkly-dragon-zxtpx&watch=true": dial tcp 172.30.0.1:443: connect: connection refused
```
The workflow template spec is
```
spec:
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      outputs: {}
      metadata: {}
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
        resources: {}
  entrypoint: argosay
  arguments:
    parameters:
      - name: message
        value: hello argo
  serviceAccountName: argo-workflow
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnWorkflowSuccess
  podMetadata:
    annotations:
      sidecar.istio.io/inject: 'true'
      sidecar.istio.io/proxyCPU: 50m
      sidecar.istio.io/proxyCPULimit: 200m
      sidecar.istio.io/proxyMemory: 64Mi
      sidecar.istio.io/proxyMemoryLimit: 256Mi
      sidecar.istio.io/rewriteAppHTTPProbers: 'true'
      workflows.argoproj.io/kill-cmd-istio-proxy: '["pilot-agent", "request", "POST", "quitquitquit"]'
  workflowMetadata:
    creationTimestamp: null
    labels:
      example: 'true'
```

The `serviceAccountName` can get, watch, and list pods, and create pod/logs:
```apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
```
Thank you very much for a great tool.
