### DISCUSSION TITLE
Argo Workflow SSO redirect_url from OIDC returns blank page

### DISCUSSION THREAD

**Discussion by amitjainr** [argoproj/argo-workflows#8067] [Q&A]
Hi,

We have configured our Argo workflow to authenticate with OIDC but after OIDC authentication it lands into blank page and then we have to click Workflows page to start seeing workflows.

Going through Argo workflow docs, it says the redirect_url format has be to be `https://<argo-workflows-server>/oauth2/callback`. 

```
https://argoproj.github.io/argo-workflows/workflow-controller-configmap.yaml

   # This is the redirect URL supplied to the provider (optional). It must
    # be in the form <argo-server-root-url>/oauth2/callback. It must be
    # browser-accessible. If omitted, will be automatically generated.
    redirectUrl: https://argo-server/oauth2/callback
```

Is there a way we can customise this and modify redirect_url to point to workflows page. Below is our configmap:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  sso: |
      issuer: https://oidc.provider/<token>/v2.0
      sessionExpiry: 10h
      clientId:
        name: argo-sso
        key: client-id
      clientSecret:
        name: argo-sso
        key: client-secret
      redirectUrl: https://<argo-workflow-server>/oauth2/callback
      scopes:
        - email
        - profile
      rbac:
        enabled: true
```

Thanks
Amit
