### DISCUSSION TITLE
How to pass individual resource limits to workflowtemplate.

### DISCUSSION THREAD

**Discussion by nfoerster** [argoproj/argo-workflows#8231] [Q&A] [answered]
I have a workflowtemplate and want to pass the resource limits to the template from the workflow. This is because the container has several different commands and not all have the same resource requirements. However, I also want not to copy&paste the template just to set different resource limits. I prepared a testworkflow, but, as far as I have seen the regex evaluation fails in the template. Did anyone had the same problem and knows to solve it?

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-spec-patch-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: cpu-limit
        value: 500m
  templates:
  - name: whalesay
    inputs:
      parameters:
        - name: cpu-limit
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
      resources:
          requests:
            cpu: "{{inputs.parameters.cpu-limit}}"
```

Resulting error:
` Failed: cannot unmarshall spec: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'`
