### DISCUSSION TITLE
How to input custom parameters in specific step while the workflow has already been running ?

### DISCUSSION THREAD

**Discussion by Colstuwjx** [argoproj/argo-workflows#8278] [Q&A]
For instance, I've ran a workflow below:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: hello world

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

The question is that may I fillout the `message` variable only when it comes to run the step X, rather than preparing this param at the beginning? Could I override the workflow params while it's already ran, or is there any way to do it?

Thanks.
