### DISCUSSION TITLE
Submit parameterized workflow template using REST api in python

### DISCUSSION THREAD

**Discussion by ni-todo-spot** [argoproj/argo-workflows#8319] [Q&A] [answered]
Hey all!

I'm trying to submit a new workflow out from a given workflow template using the REST api via python.

I am using  the swagger api described [here](https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/openapi-spec/swagger.json)

My aim is to submit the workflow with new arguments - supplied in the request payload.

When trying the setup below - I successfully triggered an execution though the `message` parameter value could not be modified.

Attaching the tested setup:

```yaml
# In argo server created:
metadata:
  name: ni-tmp
  namespace: argo
  labels:
    example: 'true'
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
spec:
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      outputs: {}
      metadata: {}
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
        resources: {}
  entrypoint: argosay
  arguments:
    parameters:
      - name: message
        value: hello argo
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
  workflowMetadata:
    labels:
      example: 'true'
```

Then tried to run the following python snippet:
```python
import requests

argo_token = ""
namespace = "argo"
template_name = "ni-tmp"
workflow_name = "test"

headers = {"Authorization": f"{argo_token}"}

js = {
    "resourceKind": "WorkflowTemplate",
    "namespace": namespace,
    "resourceName": template_name,
    "submitOptions": {
        "labels": f"workflows.argoproj.io/workflow-template={template_name}",
        "name": workflow_name,
    },
    "arguments": {"parameters": [{"name": "message", "value": "Cheers mate"}]},
    # Tried more inputs but same result:
    # "parameters": [{"name": "message", "value": "Cheers mate"}],
    # "parameters": ["Cheers mate"],
    # "arguments": ["Cheers mate"],

}

response = requests.post(
    "https://localhost:2746/api/v1/workflows/argo/submit",
    headers=headers,
    json=js,
    verify=False,
)

print(response.json()["spec"]["arguments"])
# Returns an empty dict -> {}
```

Just for the protocol - here the argo server version being used:
```python
import requests
print(requests.get("https://localhost:2746/api/v1/version", verify=False).text)
# Output is:
# {
#  "version":"untagged",
#  "buildDate":"2022-04-04T22:15:41Z",
#  "gitCommit":"8c6b9faf517692eb2c696efb3779502ced029790",
#  "gitTag":"untagged",
#  "gitTreeState":"clean",
#  "goVersion":"go1.17.8",
#  "compiler":"gc",
#  "platform":"linux/amd64"
#}
 ```

Can someone please help me understand what am I doing wrong and perhaps suggest a solution?

Thanks in advance!
