### DISCUSSION TITLE
Ask for help! I want to get the state of each step using hooks onExit.

### DISCUSSION THREAD

**Discussion by LingClassmate** [argoproj/argo-workflows#8321] [Q&A]
Ask for help! I want to get the status of each step using the hooks configuration as follows:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: container-on-exit-
spec:
  entrypoint: step-template
  templates:
    - name: step-template
      steps:
        - - name: stepA
            template: echo1
            hooks: 
              exit:
                template: exitContainer
                arguments:
                    parameters:
                      - name: Containerstatus
                        value: "{{steps.stepA.status}}"
        - - name: stepB
            template: echo2
            hooks: 
              exit:
                template: exitContainer
                arguments:
                    parameters:
                      - name: Containerstatus
                        value: "{{steps.stepB.status}}"
            
    - name: echo1
      container:
        image: alpine:3.15
        command: [sh, -c]
        args: ["echo \"stepA\""]
    - name: echo2
      container:
        image: alpine:3.15
        command: [sh, -c]
        args: ["echo \"stepB\" ;exit 1"]

    - name: exitContainer
      inputs:
        parameters:
          - name: Containerstatus
      container:
        image: alpine:3.15
        command: [sh, -c]
        args: ["echo  ContainerStatus: {{inputs.parameters.Containerstatus}}"]
```

OnExit output:
```
ContainerStatus: {{steps.stepA.status}}
ContainerStatus: {{steps.stepB.status}}
```
But I can't get the step state, I can only get the strings, is there any other way to solve my problem?

**Comment by wesleyscholl** [comment]
@LingClassmate 

The original workflow produced the following error:

```bash
MESSAGE
Pod "container-on-exit-phftp-exitContainer-1772040650" is invalid: metadata.name: Invalid value: 
"container-on-exit-phftp-exitContainer-1772040650": a lowercase RFC 1123 subdomain must consist of 
lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character 
(e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

After updating all template names and parameters to lowercase, the workflow executed successfully:

<div style="display: flex;">
  <img src="https://github.com/user-attachments/assets/5fd593da-e23d-41b3-b58f-7ec6a955ba65" width=420/>
  <img src="https://github.com/user-attachments/assets/1ebf4767-b740-4445-af29-65fd1edcabe8" width=420/>
</div>


Updated `Workflow`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: container-on-exit-
  namespace: argo
  templates:
    - name: step-template
      steps:
        - - name: stepA
            template: echo1
            hooks:
              exit:
                template: exit-container # Updated to lowercase
                arguments:
                  parameters:
                    - name: container-status # Updated to lowercase
                      value: "{{steps.stepA.status}}"
        - - name: stepB
            template: echo2
            hooks:
              exit:
                template: exit-container # Updated to lowercase
                arguments:
                  parameters:
                    - name: container-status # Updated to lowercase
                      value: "{{steps.stepB.status}}"
    - name: echo1
      container:
        name: ""
        image: alpine:3.15
        command:
          - sh
          - "-c"
        args:
          - echo "stepA"
    - name: echo2
      container:
        name: ""
        image: alpine:3.15
        command:
          - sh
          - "-c"
        args:
          - echo "stepB" ;exit 1
    - name: exit-container # Updated to lowercase
      inputs:
        parameters:
          - name: container-status # Updated to lowercase
      container:
        name: ""
        image: alpine:3.15
        command:
          - sh
          - "-c"
        args:
          - "echo  Container Status: {{inputs.parameters.container-status}}" # Updated to lowercase
  entrypoint: step-template
```

**Resources**:

- https://github.com/argoproj/argo-workflows/blob/main/examples/exit-handler-with-param.yaml
- https://argo-workflows.readthedocs.io/en/latest/fields/#lifecyclehook
