### DISCUSSION TITLE
cannot change `executor-image` `argoproj/argoexec:v2.3.0` -- misconfiguration, 2 controllers

### DISCUSSION THREAD

**Discussion by zhangchao** [argoproj/argo-workflows#8323] [Q&A] [answered]
Hello, team!  we try to use argo workflow in private cluster (private docker hub: `artifactory.chao.com/argoproj/v331`) .  when we submit simple workflow, we found that wait container always use `argoproj/argoexec:v2.3.0`.  failure because we cannot connect to public docker hub.

* controller
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - "artifactory.chao.com/argoproj/v331/argoexec:v3.3.1"
```

* workflow       
```yaml        
Status:         Pending
IP:
Controlled By:  Workflow/chao-demo-mc2q8
Containers:
  wait:
    Container ID:
    Image:         argoproj/argoexec:v2.3.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      ARGO_POD_NAME:                    chao-demo-mc2q8 (v1:metadata.name)
      ARGO_CONTAINER_RUNTIME_EXECUTOR:  k8sapi
    Mounts:
      /argo/podmetadata from podmetadata (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-drrmm (ro)
  main:
    Container ID:
    Image:         artifactory.chao.com/argoproj/v331/python:alpine3.6
    Image ID:
    Port:          <none>
```

we set configmap . and `kubectl apply`, it looks has same issue

* configmap
```yaml
  executor: |
    image: artifactory.chao.com/argoproj/v331/argoexec:v3.3.1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
```

* log 
```bash

time="2022-04-06T11:55:52.621Z" level=info msg="Get configmaps 200"
time="2022-04-06T11:55:52.632Z" level=info msg="Configuration:\nartifactRepository:\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: my-minio-cred\n    bucket: my-bucket\n    endpoint: minio:9000\n    insecure: true\n    secretKeySecret:\n      key: secretkey\n      name: my-minio-cred\ncontainerRuntimeExecutors:\n- name: emissary\n  selector:\n    matchLabels:\n      workflows.argoproj.io/container-runtime-executor: emissary\n- name: pns\n  selector:\n    matchLabels:\n      workflows.argoproj.io/container-runtime-executor: pns\nexecutor:\n  image: artifactory.chao.com/argoproj/v331/argoexec:v3.3.1\n  imagePullPolicy: Always\n  name: \"\

{\"image\":\"argoproj/argoexec:v2.3.0\",\"imageID\":\"\",\"lastState\":{},\"name\":\"wait\",\"ready\":false,\"restartCount\":0,\"started\":false,\"state\":{\"waiting\":{\"reason\":\"ContainerCreating\"}}}]}}
```

**Comment by terrytangyuan** [comment]
We currently only match the version of the executor image with controllers but not the registry. https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/config.go#L96

cc @alexec Should we expose a `executorImageRegistry`?

**Comment by alexec** [comment, marked as answer]
This is probably misconfiguration of some kind. Are there two installations in your cluster? One v3.3.1 and one v2.3.0?

**Reply by terrytangyuan** [reply]
The problem is that we hard-code `quay.io` as the executor image registry (see [my comment above](https://github.com/argoproj/argo-workflows/discussions/8323#discussioncomment-2515790)) but the user wants to use a different registry `artifactory.chao.com`.

**Reply by zhangchao** [reply]
@terrytangyuan I think that it should be override, `--executor-image "artifactory.chao.com/argoproj/v331/argoexec:v3.3.1"`

@alexec   yes , we have two projects, one project install kubeflow , and another one just instal argoworkflow 3.3.1 .. but I think that it should use different configmap

```go
func (wfc *WorkflowController) executorImage() string {
	if wfc.cliExecutorImage != "" {
		return wfc.cliExecutorImage
	}
	if v := wfc.Config.GetExecutor().Image; v != "" {
		return v
	}
	return fmt.Sprintf("quay.io/argoproj/argoexec:" + argo.ImageTag())
}
```

**Reply by alexec** [reply]
User should still be able to specify the executor, as per the code block above.

**Reply by terrytangyuan** [reply]
Oh I misread the code. @alexec is right that you should be able to specify it. The last line only applies if you don't specify the image explicitly.

**Reply by agilgur5** [reply]
It was confirmed to be this problem exactly [below](https://github.com/argoproj/argo-workflows/discussions/8323#discussioncomment-2528520)

**Comment by zhangchao** [comment]
@alexec   @terrytangyuan   I guess that it is bug , the problems was caused by  argoworkflow 3.3.1 and kubeflow's argo 2.3.0 
although they are different namespace , but it looks that two controllers are both watch  same event  and run.. not sure why

**Reply by agilgur5** [reply]
You probably installed both Controllers [at cluster-scope](https://argo-workflows.readthedocs.io/en/latest/installation/#installation-options) or have them otherwise watching the same namespaces, so indeed that would result in a conflict like that

**Comment by rupert648** [comment]
Would it be possible to expand the documentation surrounding specifiying custom image locations for the argo server install? I feel the use case is common but the solution is difficult to discover

**Comment by venushka** [comment]
For setting the image repository, adding this to the ~~configmap~~ _Helm overrides_ worked for me.
```yaml
executor:
  image:
    registry: quay-proxy.mydomain.foo
```

This ends up being `--executor-image` in the controller deployment
```yaml
    spec:
      containers:
      - args:
        - --executor-image
        - quay-proxy.mydomain.foo/argoproj/argoexec:v3.5.7
```
