### DISCUSSION TITLE
Argo workflow server AWS Load Balancer controller deployment issue

### DISCUSSION THREAD

**Discussion by dhrsoni19** [argoproj/argo-workflows#8334] [Q&A]
Trying to deploy Argo workflow in a EKS V1.19.eks.7 cluster running  AWS Load Balancer controller V2.1.3.
We're having an issue with the application load balancer target group health check.
AWS Load Balancer controller is able to reconcile and configure a load balancer forward traffic to argo workflow server. However, Argo server is not returning any response back the health check.

 Here are the helm chart Ingress configs we tried.
 
```
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/group.name: internal
      alb.ingress.kubernetes.io/healthcheck-path: /argo
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
      alb.ingress.kubernetes.io/load-balancer-name: internal
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/tags: EKS=True
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol-version: HTTP2

    hosts:
      - argo.example.com
    paths:
      - /*
    pathType: Prefix
```
Here are helm chart config for deployment
```
server:
  secure: true
  enabled: true
  baseHref: /argo/
  serviceType: ClusterIP
  servicePort: 80
  servicePortName: "http"
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::REDACTED
```
<img width="1505" alt="Screen Shot 2022-04-07 at 19 16 56" src="https://user-images.githubusercontent.com/54118074/162328778-02cffcb6-ab72-46c7-a847-e80e1918d467.png">
