### DISCUSSION TITLE
Argo workflow suspend timeout if not approved and abort the workflow

### DISCUSSION THREAD

**Discussion by tiwarisanjay** [argoproj/argo-workflows#8365] [Q&A] [answered]
Hello, 
I would like to suspend a argo workflow and would like to abort it, if not approved manually by user after a given period of time. 
We trigger 100s of workflows and would like to approve some of those and not all. So rest should timeout and abort rest of the steps. 
Something like following : 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: suspend-template-
spec:
  entrypoint: suspend
  templates:
  - name: suspend
    steps:
    - - name: build
        template: whalesay
    - - name: approve
        template: approve
    - - name: release
        template: whalesay

  - name: approve
    suspend: 
       timeout: "1h" 
       abort: yes

  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
```
Can someone please help me with the same ?

**Comment by katylava** [comment]
Were you able to find a work around for this?

**Comment by SandipKumar05** [comment, marked as answer]
@katylava 
I find out a workaround for my workflow. 
whenever someone approves the workflow, it provides input `approve` as `YES`. suspend step wait for 1 hour if no one provides the approval it process with a default value as `NO`
The next step purely depends on the output of this step. if it is `NO` then abort job will run, it will fail the workflow with an error message.
If someone provides `YES` then will go as expected. 

```yaml
    - name: approval
      suspend:
        duration: "1h"
      inputs:
        parameters:
          - name: approve
            description: "The options to show on the dropdown in Argo UI."
            default: "NO"
            enum:
              - "YES"
              - "NO"
      outputs:
        parameters:
          - name: approve
            valueFrom:
              supplied: {}
```
Failure step.

```yaml
        - name: fail-workflow
          dependencies:
            - approval
          when: >-
            ( '{{tasks.approval.outputs.parameters.approve}}' != 'YES' )
```
