### DISCUSSION TITLE
How to get parameters from Workflow to individual steps in a WorkflowTemplate

### DISCUSSION THREAD

**Discussion by crb-66** [argoproj/argo-workflows#8442] [Q&A]
I'm new to Argo and trying to implement a "wrapper" Workflow that has multiple steps and calls the same WorkflowTemplate several times, once in each step, and passes different parameter values with each step/invocation of the WorkflowTemplate.  It works in a simple POC Workflow/WorkflowTemplate combo but does not work with my more complex version.

**WORKING VERSION**

Workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: messaging-test
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: awesome-rhino
              template: argosay
            arguments:
              parameters:
                - name: message
                  value: foo!
        - - name: hello-again
            templateRef:
              name: awesome-rhino
              template: argosay
            arguments:
              parameters:
                - name: message
                  value: bar!        
```

WorkflowTemplate:
```
metadata:
  name: awesome-rhino
  namespace: argo
spec:
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      outputs: {}
      metadata: {}
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
        resources: {}
  entrypoint: argosay
  arguments: {}
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
  workflowMetadata:
    labels:
      example: 'true'
```

Output:
- step 1 (hello-world):  foo!
- step 2 (hello-again):  bar!

**NOT WORKING VERSION**
Workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: main-
spec:
  serviceAccountName: sa
  entrypoint: whole-enchilada
  podGC:
   strategy: OnPodSuccess
  volumes:
	. . .
  arguments:
    parameters:
    - name: aws_region
      value: "us-west-2"
  templates:
    - name: whole-enchilada
      steps:
        - - name: step-1
            templateRef:
              name: my-template
              template: startup
            arguments:
              parameters:
              - name: param-1
                value: 'param-1-step-1-value'
              - name: param-2
                value: 'param-2-step-1-value'
        - - name: step-2
            templateRef:
              name: my-template
              template: startup
            arguments:
              parameters:
              - name: param-1
                value: 'param-1-step-2-value'
              - name: param-2
                value: ''param-2-step-2-value''
```

WorkflowTemplate:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-template
  generateName: my-proc-
spec:
  arguments:
    parameters:
              - name: param-1			          # <------ have to enter 'placeholder' values here but they don't get used;
                value: 'param-1-step-1-value'     # <------ if not entered here then I get a 'inputs.parameters.param-1 was not supplied' error
              - name: param-2
                value: 'param-2-step-1-value'
  onExit: exit-handler
  templates:
  - name: startup
    steps:
    - - name: prep-cluster
        template: prep-cluster
    - - name: template-step-1
        template: template-step-1
        arguments:
          parameters:
          - name: param-1
            value: "{{workflow.parameters.param-1}}"
    - - name: template-step-2
        template: template-step-2
        arguments:
          parameters:
          - name: param-1
            value: "{{workflow.parameters.param-1}}"
          - name: param-2
            value: "{{workflow.parameters.param-2}}"
		. . .
  - name: template-step-1
    inputs:
      parameters:
      - name: param-1		# <------ workflow param-1 referenced here
    outputs:
		. . .
    volumes:
		. . .
    initContainers:
      - name: init0
        image: . . .
    script:
      image: . . .
      imagePullPolicy: Always
      env:
        - name: AWS_METADATA_SERVICE_TIMEOUT
          value: '30'
			. . .
      resources: 
        limits:
          memory: 2Gi
          cpu: 2000m
        requests:
          memory: 1Gi
          cpu: 1000m
      volumeMounts:
		. . .
      command: [python]
      source: |
		. . .
		my_json='{{inputs.parameters.param-1}}'		# <------- step input param-1 used here
		. . .
  - name: template-step-2
	. . .
  - name: exit-handler
    steps:
    - - name: shutdown
        template: shutdown-all-clusters
			. . .
  - name: shutdown-all-clusters
    volumes:
		. . .
```

Result (on linting when creating the workflow in the ArgoUI):  
Unsuccessful HTTP response: templates.whole-enchilada.steps[0].step-1 templates.startup.steps failed to resolve {{workflow.parameters.param-1}}
    

Also noteworthy:
* I can get past the error noted if I enter a value for the parameter at the top of the Workflow, e.g.
```
	apiVersion: argoproj.io/v1alpha1
	kind: Workflow
	metadata:
	  generateName: main-
	spec:
		. . .
	  arguments:
		parameters:
		- name: aws_region
		  value: "us-west-2"
		- name: param-1			# <------ enter param-1 here
		  value: 'param-1-step-1-value'
```
but it ends up using that value for all steps in the WorkflowTemplate and defeats the purpose of having step-specific values.

* If I don't enter the parameters in the header of the WorkflowTemplate, I get a different error when adding the template:
	'inputs.parameters.param-1 was not supplied' 
Any values entered there are not used however.
