### DISCUSSION TITLE
How do I pass withSequence `{{ item }}` into an expression?

### DISCUSSION THREAD

**Discussion by rkt2spc** [argoproj/argo-workflows#8485] [Q&A]
How do I pass **withSequence** `{{ item }}` into an expression?

```
  templates:
    - name: entrypoint
      parallelism: 4
      steps:
        - - name: merge
            template: merge-loop
            arguments:
              parameters:
                - name: is_last
                  value: "{{= asInt(item) == 2 ? 'true' : 'false' }}"
            withSequence:
              count: "3"
```
