### DISCUSSION TITLE
Using `sprig.replace`

### DISCUSSION THREAD

**Discussion by MarahAbu** [argoproj/argo-workflows#8499] [Q&A] [answered]
Hi, I'm using Argo Workflows v3.2.9, I want to use the creator-email label but the '@' is replaced by '.at.' so i'm trying to replace it back, but not getting the result i want.
for example:
![image](https://user-images.githubusercontent.com/45389267/165495608-8ffc4791-e16d-48dd-9a7b-bf62a2f4b626.png)
I get this result 
![image](https://user-images.githubusercontent.com/45389267/165495798-9bdacd18-ae76-4f71-a233-f9f1db4cd949.png)
also tried like this 
![image](https://user-images.githubusercontent.com/45389267/165496602-9c45e2a2-29db-4919-80e3-e021849bbeec.png)
tried many things but unfortunately nothing is working.
Anyone came across this issue and may have a solution that could help?

thanks in advance!

**Comment by XaviusB** [comment, marked as answer]
I agree that the document is not perfect about replace function

Just put the two last parameters in first position

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sprig
spec:
  entrypoint: main
  serviceAccountName: operate-workflow-sa
  templates:
    - name: main
      dag:
        failFast: true
        tasks:
          - name: generate-it-now
            template: generate-that
          - name: sprigit
            dependencies: [generate-it-now]
            template: sprigit
            arguments:
              parameters:
                - name: release-version
                  value: 'v{{=sprig.regexFind("[0-9]+.[0-9]+",tasks["generate-it-now"].outputs.parameters["result-version"])}}'
          - name: replace
            dependencies: [generate-it-now]
            template: sprigit
            arguments:
              parameters:
                - name: release-version
                  value: '{{=sprig.replace(".","-",tasks["generate-it-now"].outputs.parameters["result-version"])}}'

    - name: generate-that
      outputs:
        parameters:
          - name: result-version
            valueFrom:
              path: /tmp/result.txt
      script:
        image: alpine
        command: [ sh ]
        source: |
          echo "release-2.64.32-01A1DA56FG1R5E" > /tmp/result.txt

    - name: sprigit
      inputs:
        parameters:
          - name: release-version
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: hello-
          spec:
            arguments:
              parameters:
                - name: message
                  value: '{{inputs.parameters.release-version}}'
            workflowTemplateRef:
              name: hello
              clusterScope: false
```
