### DISCUSSION TITLE
Argo workflow - SSO integration with Azure AD SSO : Invalid client-id

### DISCUSSION THREAD

**Discussion by tiwarisanjay** [argoproj/argo-workflows#8503] [Q&A]
Hi All, 
I am trying to get the Argo workflow working with AzureAD. 
1. Direct integration does not work if I use Azure AD as a issuer. 
2. Trying to get it work with ArgoCD dex. 
    I have ArgoCD working with AzureAD and seems to be good but now I am using following document to integrate argo workflow 
    and keep on getting `invalid client-id("my-azure-ad-client-id")` error. Same client-id is used for ArgoCD and working fine.  
    There is a discussion on Slack chaneel as well but no one replied.
    https://cloud-native.slack.com/archives/C01QW9QSSSK/p1621013198199300  

Following following document to integrate : 
https://argoproj.github.io/argo-workflows/argo-server-sso-argocd/

**Comment by tiwarisanjay** [comment]
Found the solution:: 
In following code where it says `id: argo-workflows-sso` it should be your actual client-id from OIDC provider. So let me rewrite the documentation part where we have this client id : 
Argo workflow secret : 
```
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
data:
  # client-id is 'my-client-id-1234-1234'
  client-id: bXktY2xpZW50LWlkLTEyMzQtMTIzNAo=
  # client-secret is 'my-client-secret-very-secret'
  client-secret: bXktY2xpZW50LXNlY3JldC12ZXJ5LXNlY3JldAo=
```
Following code should be 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Kustomize sees the value of dex.config as a single string instead of yaml. It will not merge
  # Dex settings, but instead it will replace the entire configuration with the settings below,
  # so add these to the existing config instead of setting them in a separate file
  dex.config: |
    # Setting staticClients allows ArgoWorkflows to use ArgoCD's Dex installation for authentication
    staticClients:
      - id: my-client-id-1234-1234
        name: Argo Workflow
        redirectURIs:
          - https://argo-workflows.mydomain.com/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```
Thats where documentation sucks as they are using argo-workflows-sso as a client-id too 

Also DEX documentation helped it to understand : 

https://dexidp.io/docs/using-dex/ 

https://dexidp.io/docs/using-dex/#:~:text=of%20the%20client.-,ClientID,-%3A%20%20%20%20%20%22example%2Dapp%22%2C%0A%20%20%20%20ClientSecret
