### DISCUSSION TITLE
`no matches for kind "CronWorkflow" in version "argoproj.io/v1alpha1"` upon first apply

### DISCUSSION THREAD

**Discussion by stianlagstad** [argoproj/argo-workflows#8540] [Q&A] [answered]
I use [kustomize](https://kustomize.io/) to create a single YAML for everything, which I then apply. Like this: `kustomize build environments/staging | kubectl apply -f -`.

In the YAML that kustomize creates is both the CRDs for everything that's argo workflows, and my own use of those CRDs. Example:
```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cronworkflows.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: CronWorkflow
...
```
and then later in the same YAML file:
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: my-cron-job-name
  namespace: workflows
spec:
  concurrencyPolicy: Replace
  schedule: '*/3 * * * *'
...
```

When I apply this on a new cluster (I use minikube locally), I get this error:
```
error: unable to recognize "STDIN": no matches for kind "CronWorkflow" in version "argoproj.io/v1alpha1"
```

If I immediately retry the apply-command, then it works. My thinking is that I can't use the CRD that's `CronWorkflow` before it's "ready". Is that so? If so, what are the best practices for deploying argo workflows **and** workflows at the same time?

Thanks for reading!
