### DISCUSSION TITLE
argo-workflows/argo-server-sso-argocd/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#8578] [General]
# argo-workflows/argo-server-sso-argocd/

https://argoproj.github.io/argo-workflows/argo-server-sso-argocd/

**Comment by tiwarisanjay** [comment]
Can you change following example as it confuses us to use secret name as a OIDC ID, which is actually a OIDC ClientID not a secret name. There are number of people in slack chat and github discussion facing invalid client id issue because of this: 
```yaml
           staticClients:
           - id: argo-workflows-sso [This is actually a OIDC ClientID not a secret or name ]
             name: Argo Workflow
             redirectURIs:
               - https://argo-workflows.mydomain.com/oauth2/callback
             secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```

**Reply by fedeagstni** [reply]
@tiwarisanjay Could you please share how we should configure the staticClients ?

**Reply by tiwarisanjay** [reply]
@fedeagstni  https://www.youtube.com/watch?v=4HTFGlAEqJg 

https://medium.com/@tiwarisan/argo-workflow-dex-integration-without-argocd-dex-844a017ad558

I have staticClient written with it

**Reply by fedeagstni** [reply]
Thank you @tiwarisanjay. I've actually solved combining staticClient and connector. But the problem now is that the helm chart doesn't create all the roles Argo Workflows needs and the logged user never get its permissions

**Reply by tiwarisanjay** [reply]
@fedeagstni you can use the chart directly and add the required bindings.

**Reply by fedeagstni** [reply]
I always get this error:
```
level=error msg="failed to perform RBAC authorization" error="no service account rule matches"
level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = not allowed" grpc.code=PermissionDenied grpc.method=CollectEvent grpc.service=info.InfoService grpc.start_time="2022-07-27T18:15:43Z" grpc.time_ms=2.235 span.kind=server system=grpc
```

**Reply by tiwarisanjay** [reply]
@fedeagstni Do you need RBAC? If no please disable and it will work. If you enable for AzureAD you need to create group and assign permissions.

**Reply by bdashrad** [reply]
Even with your comment this tripped us up! Thanks for the pointer though

**Reply by JunaidChaudry** [reply]
@tiwarisanjay I tried with your helm chart, and also manually installing dex and argo workflow, but after the microsoft AD logs me in, and redirects me to argo workflow, I keep getting a 401, even with `sso.rbac.enabled: false`. 

In the workflow logs, all I see is 
```
time="2023-01-24T15:23:19.799Z" level=info duration="40.682µs" method=GET path=/oauth2/redirect size=257 status=302
time="2023-01-24T15:23:33.734Z" level=info duration="91.996µs" method=GET path=index.html size=473 status=0
time="2023-01-24T15:23:44.949Z" level=info duration=65.110083ms method=GET path=/oauth2/callback size=0 status=401
```
And I end up getting a page saying "This page isn’t working right nowIf the problem continues, contact the site owner. HTTP ERROR 401".
![Screen Shot 2023-01-24 at 10 29 10 AM](https://user-images.githubusercontent.com/49313431/214377510-252c99c3-3036-4cd4-9789-727c8667268e.png)


Any pointers on what might be going wrong?

**Reply by tiwarisanjay** [reply]
You are using Azure OIDC ?

**Reply by JunaidChaudry** [reply]
yes

**Comment by RossComputerGuy** [comment]
With Terraform and Helm, I get `invalid oidc config: error converting YAML to JSON: yaml: did not find expected key` and `malformed Dex configuration found` errors. [Here is my configuration](https://github.com/RossComputerGuy/kluster/blob/4f12209c8d7f3bc2965bcc8a69b42bdab0557266/main.tf#L93-L124).

**Comment by sravani-goriparthi-sp** [comment]
How do we add multiple groups to rbac. Is the below example valid?

`workflows.argoproj.io/rbac-rule: "'argo_admins','argo_readonly' in groups"`

**Reply by tooptoop4** [reply]
try              `'argo_admins' in groups || 'argo_readonly' in groups`

**Reply by wsams** [reply]
You can also use expressions like `{{ join " or " .Values.rbacRules | quote }}` where `.Values.rbacRules` is a list of rules like this (may need to work out the quotes),
```yaml
rbacRules:
- "argo_admins in groups"
- "argo_readonly in groups"
```

**Reply by gabriel-suela** [reply]
where did u find `.Values.rbacRules`? i could not find in the charts neither in templates

**Reply by agilgur5** [reply]
`.Values.rbacRules` is just an example the above commenter used. They defined it themselves in the comment.

**Comment by gyanprakash48** [comment]
I am getting below error when setting auth mode sso. error is `Error: 404 Not Found`. What not found is not clear, possible to help here ? 

```
time="2022-09-04T11:52:08.535Z" level=info msg="not enabling pprof debug endpoints"
time="2022-09-04T11:52:08.536Z" level=info authModes="[sso]" baseHRef=/ managedNamespace= namespace=argo secure=true
time="2022-09-04T11:52:08.536Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode"
time="2022-09-04T11:52:08.536Z" level=info msg="config map" name=workflow-controller-configmap
Error: 404 Not Found:
Usage:
  argo server [flags]
```

**Reply by potatokat** [reply]
During my testing, at this point, argo-server is trying to contact your issuer endpoint. Please verify that the issuer URL exists/is accessible.

**Reply by tiwarisanjay** [reply]
@potatokat  Which OIDC provider you are using ?

**Reply by gyanprakash48** [reply]
Azure AD

**Reply by gyanprakash48** [reply]
Looks like Argo server sso not supporting azure AD and complaing  (404 Not Found)  as when i am using  it with dex it's  working fine

**Reply by tiwarisanjay** [reply]
@gyanprakash48 yes it does not support it directly. You will have to use dex.

**Reply by sudeshjethoe** [reply]
That is not correct, it does support it directly and we are using AAD without dex, what you need to do is create an Azure AD App Registration and then give this app registration "Admin Consent" to allow it to read user properties (see also: https://learn.microsoft.com/en-us/graph/permissions-reference#microsoft-graph-permission-names)

Following, you can mount the app registrations client_id and client_secret as a kubernetes secret within your argo workflow configmap

https://github.com/argoproj/argo-workflows/blob/93c11a24ff06049c2197149acd787f702e5c1f9b/docs/workflow-controller-configmap.yaml#L310

If you do not complete the app registration properly this might give you issues

**Reply by gyanprakash48** [reply]
@sudeshjethoe  do you mean below permisson 
![image](https://user-images.githubusercontent.com/109652198/194918083-da101642-a1ca-458b-b845-ac46be0cd346.png)

**Reply by gyanprakash48** [reply]
@sudeshjethoe  thanks indeed it works, now i can get rid of dex setup . Thanks for sharing it

**Reply by sudeshjethoe** [reply]
You need the User.Read permissions, glad to hear that it's working

**Reply by gyanprakash48** [reply]
Thanks so much , do you also know how to enable  scope  -groups , in order to enforce rbac . I tried this and getting some error , I am sure it must be some permisson issue, just in case you have done such implmenetaion alredy

**Reply by ragnaros2046** [reply]
@sudeshjethoe  same here, the application argoworkflow asked for scope groups that doesnt exist on the resource Microsoft Graph Contact the app vendor. I already give app User.Read permissions(Delegated and Application). Is there any other permission I need?

**Reply by bnbrijesh** [reply]
Dex is not required by to make OIDC work OOB in Azure, just use the right issueer url and as provide User.Read permission it should work .

**Reply by AndriySidliarskiy** [reply]
I have 401 error with login, maybe someone have solution how fix this?

**Reply by gyanprakash48** [reply]
401 is un-authorized right ? then should be credntials issue, unless you have more detail to share , i guess

**Reply by AndriySidliarskiy** [reply]
I created secret with the identical value from azure application cred, and I check in k8s he exists but when trying login from sso i have 401 error. In the application sso login i have succeeded attempt.

**Reply by JunaidChaudry** [reply]
I am getting the same issue as @AndriySidliarskiy. All that @sudeshjethoe mentioned has been set up. The app redirects to Azure for login, but when being returned to oauth2/callback, I end up getting the 401 with "This page isn’t working right now". The server logs simply say the following without any other context: 
``` 
time="2023-01-05T15:58:01.338Z" level=info duration="64.201µs" method=GET path=/oauth2/redirect size=298 status=302
time="2023-01-05T15:58:13.496Z" level=info duration="134.375µs" method=GET path=index.html size=473 status=0
time="2023-01-05T15:58:18.128Z" level=info duration=853.317986ms method=GET path=/oauth2/callback size=0 status=401
```

**Reply by JunaidChaudry** [reply]
@AndriySidliarskiy did you ever find the issue?

**Comment by AndriySidliarskiy** [comment]
Maybe you have example how i can put issuer url for config because now i use https://sts.windows.net/{tenant-id}/

**Reply by gyanprakash48** [reply]
if you are using azure AD then issuer url looks like this https://login.microsoftonline.com/{tenant-id}/v2.0

**Comment by liuyix** [comment]
Does Argo supports CAS (Central Authentication Service) auth method ?

**Comment by AndriySidliarskiy** [comment]
How i can specify rule only for specific group about azure active directory sso?

**Reply by bnbrijesh** [reply]
I am not sure the Azure OpenID  supports  group scope, to enable rbac like mentioned in docs. You can check supported scope using link like this https://login.microsoftonline.com/<tenantID>/v2.0/.well-known/openid-configuration. I had requested an update on this here:[https://github.com/argoproj/argo-workflows/issues/3525](https://github.com/argoproj/argo-workflows/issues/3525).
Casbin is complex enough for them to support everything, however argoproj argocd did a better job with this. If you really need group mappings I think then you need Dex and SAML setup, somethings like this is your playground [https://medium.com/everything-full-stack/how-we-moved-from-rundeck-to-argo-workflows-f700b03c0fab](https://medium.com/everything-full-stack/how-we-moved-from-rundeck-to-argo-workflows-f700b03c0fab ). SAML setup will be similar to you Argocd SSO setup: [https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/)

**Reply by gyanprakash48** [reply]
it does support group scope , you can  simply configure group claim in token configuration . And then it exactly work as described in documentation of argo   https://argoproj.github.io/argo-workflows/argo-server-sso/

**Reply by bnbrijesh** [reply]
On Azure openID ? This is what I see in well my known config for the my tenant . Is there something I am missing. How did you match the groups ? It will amazing if you can brief please

"scopes_supported":["openid","profile","email","offline_access"]

**Reply by bnbrijesh** [reply]
Sorry, for spam this is what I got from Azure Support team :https://learn.microsoft.com/en-us/answers/questions/880369/change-the-scopes-supported-in-the-discovery-endpo.html

**Reply by gyanprakash48** [reply]
true,  https://login.microsoftonline.com//v2.0/.well-known/openid-configuration  does not list group scope , but still you can claim group scope in token addtional claim 
![image](https://user-images.githubusercontent.com/109652198/207017366-327f90d4-1637-40b0-aedd-af437660abc2.png)

**Reply by gyanprakash48** [reply]
once you add this claim, you can see  groups detail in token, and then argo documentiaon explain the rest  https://argoproj.github.io/argo-workflows/argo-server-sso/

**Reply by bnbrijesh** [reply]
This is cool, this was instantly picked up by Argo-WF open ID . Thank you so much , means a lot.

**Reply by AndriySidliarskiy** [reply]
Yes but how I can right provide group id workflows.argoproj.io/rbac-rule: "'admin' in groups" in rule for one group use one sa etc. Do it's possible?

**Reply by gyanprakash48** [reply]
yes, so in above example, use  AD group id , in place of admin

**Comment by assortedjellybean** [comment]
Does argo-workflows support SSO with SAML 2.0 assertion as opposed to just OIDC?

**Comment by aaron-arellano** [comment]
Could sso support SubjectAccessReview instead of the need to create additional claims in OIDC. This can add a lot of work to the team that owns argo-server creating and managing claims. We feel it would be easier if SAR was integrated to this validation per namespace since it is a k8s concept. We use SAR for other services in a similar manner to this.

**Comment by wsams** [comment]
Does anyone know how to skip the sign on screen when using SSO? When I click a link while signed out, I expect to be automatically redirected to my SSO provider, not Argo which requires an additional Sign In click. Does anyone know if it's possible to automatically redirect to the SSO?

**Comment by mmisztal1980** [comment]
My server deployment fails to become "ready". The logs indicate there's an RBAC problem. 

```
E0312 00:22:57.729113       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.ServiceAccount: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:argocd:workflows-argo-workflows-server" cannot list resource "serviceaccounts" in API group "" at the cluster scope
```

Anyone else run into this?

**Reply by leszekkoc** [reply]
If you are using HELM then:
`server:sso:rbac:enabled: true`

If don't, add this to server role:
```yaml
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
```

**Comment by ArjunDandagi** [comment]
We are trying to implement SSO (using AzureAD) with argocd , i want to understand if we can skip creating users in AzureAD and create the group internally within the configmap , as in . we just want the user to login but the group get assigned when they login . and so the permissions  . we want to avoid creating the AzureAD groups in portal (or using terraform to manage this).

**Comment by TapTap21** [comment]
I've successfully implemented SSO using Argo-cd dex and GitHub as the provider. I can log in to argo-workflows, but I'm presented with the following error message in the UI and logs: 
` {"code":7,"message":"not allowed"}: not allowed`

The user is bound to the server-admin user so should be able to do anything. What is the cause of this issue?

**Reply by Rosyya** [reply]
I got same error, any solution please?

**Reply by ciipher3** [reply]
did you work this out? Having the same issue

**Reply by avosepp** [reply]
https://argo-workflows.readthedocs.io/en/latest/service-account-secrets/

Did you do this step?

**Comment by purduemike** [comment]
I'm using SAML with Okta and Dex. Okta doesn't provide any client-id for this setup. How am I suppose to configure argo-workflows to use argo-cd's dex server?

**Comment by leszekkoc** [comment]
I am using Azure AD as identity provider.
I have setup app registration to include groups (+ Add group claims).
During login I got error:

```
AADSTS650053: The application 'my-app-registration' asked for scope 'groups' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor.
```

The sso Argo server settings:
```yaml
  sso: 
    issuer: https://login.microsoftonline.com/86xxxx7c-xxxx-xxxx-xxxx-35b1xxxxb98/v2.0
    clientId:
      name: argo-server-sso
      key: client-id
    clientSecret:
      name: argo-server-sso
      key: client-secret
    redirectUrl: https://argo-lab.my-company.com/oauth2/callback
    rbac:
      enabled: true
    scopes:
    - groups
```

What is the cause of this issue?

**Reply by SelisNic** [reply]
Hi, I managed to get this working by passing the `userInfoGroupsField`:

```yaml
rbac:
  enabled: true
scopes:
- email
userInfoGroupsField: memberOf
```

**Comment by jmccrumm** [comment]
How would I get this to work with FreeIPA?

**Comment by ryhorB-epam** [comment]
About a year ago, my SSO configuration worked fine with groups. The other day I decided to deploy it in another cluster and I get these messages:
```
 level=info msg="selected SSO RBAC service account for user" email=*HIDDEN* loginServiceAccount=argo-workflows-admin serviceAccount=argo-workflows-admin sso │
│ Delegated=false ssoDelegationAllowed=false subject=*HIDDEN*
│ time="*HIDDEN*" level=error msg="failed to perform RBAC authorization" error="failed to get service account secret: secrets \"argo-workflows-admin.service-account-token\" not found"       │
│ time="*HIDDEN*" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = not allowed" grpc.code=PermissionDenied grpc.method=Lis │
│ tWorkflows grpc.service=workflow.WorkflowService grpc.start_time="*HIDDEN*" grpc.time_ms=*HIDDEN* span.kind=server system=grpc
```
I used this annotation to check rules without conditions
annotations:
```yaml
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
```
I tried to use the service default account as well, but the message also just cannot find the secret for the default account

**Reply by leszekkoc** [reply]
There is a change in Kubernetes, that the token is no longer deployed with the service account.
If you updated the k8s version in between that could be the issue.

**Reply by ryhorB-epam** [reply]
Thanks for the quick response)
That's what I thought, but I was sure the argo team would see it coming. What should I do now?

**Reply by leszekkoc** [reply]
It has nothing to do with Argo itself. The default k8s behavior has changed. Fix it.
```yaml
{{- if and .Values.server.sso .Values.server.sso.rbac}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "argo-workflows.fullname" $ }}-server-rbac-admin
  labels:
    {{- include "argo-workflows.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
  {{- with .Values.server.serviceAccount.labels  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    workflows.argoproj.io/rbac-rule: "'admin' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "5"
  {{- with .Values.server.serviceAccount.annotations  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ template "argo-workflows.fullname" $ }}-server-rbac-admin-token

---

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ template "argo-workflows.fullname" $ }}-server-rbac-admin-token
  labels:
    {{- include "argo-workflows.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
  {{- with .Values.server.serviceAccount.labels  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/service-account.name: "{{ template "argo-workflows.fullname" $ }}-server-rbac-admin" 

{{- end -}}
```

**Reply by ryhorB-epam** [reply]
Thank you! This helped me and I moved on) I can already enter the user information.
But this message appeared in the logs and I can't view the workflow
```
time="*HIDDEN*" level=info msg="selected SSO RBAC service account for user" email=*HIDDEN* loginServiceAccount=argo-workflows-admin serviceAccount=argo-workflows-admin ssoDele
gated=false ssoDelegationAllowed=false subject=*HIDDEN*                                                                                                                           
time="*HIDDEN*" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = workflows.argoproj.io is forbidden: User \"system:anonymous
\" cannot list resource \"workflows\" in API group \"argoproj.io\" in the namespace \"*HIDDEN*\"" grpc.code=PermissionDenied grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.s
tart_time="*HIDDEN*" grpc.time_ms=*HIDDEN* span.kind=server system=grpc 
```
I saw somewhere people faced this problem and it seems that it should have been fixed in version 3.5, but the latest available is 3.4.8

**Comment by jiaflu** [comment]
I used the token generated by sa argo-server-admin, and called argo server with this token like this:
```
➜  ~ curl --request PUT https://argo.int.infra.abx.com/api/v1/workflows/change-notification-pipeline/change-notification-pipeline-2s56j/stop -H "Authorization: $ARGO_TOKEN"
{"code":7,"message":"workflows.argoproj.io \"change-notification-pipeline-2s56j\" is forbidden: User \"system:serviceaccount:argoproj:argo-server-readonly\" cannot patch resource \"workflows\" in API group \"argoproj.io\" in the namespace \"change-notification-pipeline\""}%
```

why still use sa argo-server-readonly which is defined in argoproj server

**Comment by pbichinepally-sunpower** [comment]
I see only 1 namespace in the Argo Workflow UI, I can see the correct user info but need the ability to switch the namespace from UI. I mentioned all the required namespaces in the `workflowNamespaces` spec while starting the argo server. Please suggest

**Comment by lzecca78** [comment]
Hi, I already have a Pomerium setup running in the cluster, already used by all the other services. Is there any way to  use it instead of Dex?

**Comment by Justin-DynamicD** [comment]
Instructions are a bit unclear.

Under [SSO RBAC](https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac) it says the service account must exist in the same namespace as the argo server, yet under [SSO RBAC namespace delegation](https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac-namespace-delegation) it states you can place the service account in the target namespace.

I can only make the former work via testing, it doesn't seem to pick up any annotated service accounts in any other namespaces. For my test I'm using 3 SA accounts:

argo-workflow:
- user-default-login (0, as listed)
- user-admin-login (10, filtered by group)

other-namespace:
- user-login (5, filtered by group)

My login will NEVER match with the user-login sa unless I create it in the argo-workflow namespace. I'd prefer to keep service accounts in their respective namespaces, but documentation is a bit contradictory.

**Reply by Justin-DynamicD** [reply]
Scratch the above, turns out I simply had `SSO_DELEGATE_RBAC_TO_NAMESPACE` set in the wrong place (as an argument instead of env var)

**Comment by mfmessaoudi** [comment]
Hello,
Could you please help with the argocd-dex-server deployment.
I'm having the error: 

```
failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/shared/argocd-dex": permission denied: unknown
```

using this deploy config from argocd site:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/part-of: argocd
  name: argocd-dex-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-dex-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/part-of: argocd
              topologyKey: kubernetes.io/hostname
            weight: 5
      containers:
      - command:
        - /shared/argocd-dex
        - rundex
        env:
        - name: ARGOCD_DEX_SERVER_DISABLE_TLS
          valueFrom:
            configMapKeyRef:
              key: dexserver.disable.tls
              name: argocd-cmd-params-cm
              optional: true
        image: ghcr.io/dexidp/dex:v2.37.0
        imagePullPolicy: Always
        name: dex
        ports:
        - containerPort: 5556
        - containerPort: 5557
        - containerPort: 5558
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          #runAsNonRoot: true
          runAsUser: 0
          runAsGroup: 0
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /shared
          name: static-files
        - mountPath: /tmp
          name: dexconfig
        - mountPath: /tls
          name: argocd-dex-server-tls
      initContainers:
      - command:
        - cp
        - -n
        - /usr/local/bin/argocd
        - /shared/argocd-dex
        image: quay.io/argoproj/argocd:v2.9.2
        imagePullPolicy: Always
        name: copyutil
        securityContext:
          #allowPrivilegeEscalation: false
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          #runAsNonRoot: false
          runAsUser: 0
          runAsGroup: 0
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /shared
          name: static-files
        - mountPath: /tmp
          name: dexconfig
      serviceAccountName: argocd-dex-server
      volumes:
      - emptyDir: {}
        name: static-files
      - emptyDir: {}
        name: dexconfig
      - name: argocd-dex-server-tls
        secret:
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          - key: ca.crt
            path: ca.crt
          optional: true
          secretName: argocd-dex-server-tls
```
