### DISCUSSION TITLE
How to render retryPolicy from inputs parameters?

### DISCUSSION THREAD

**Discussion by rkt2spc** [argoproj/argo-workflows#8651] [Q&A]
As titled

```yaml
templates:
  - name: my-template
     inputs:
       parameters:
         - name: retry_policy
           enum: ["Always", "OnFailure", "OnError", "OnTransientError"]
           default: "OnError"
     retryStrategy:
       limit: 1
       retryPolicy: "{{ inputs.parameters.retry_policy }}"
```

I got this error while trying to submit the workflow template

> (WorkflowTemplate): templates.my-template {{ inputs.parameters.retry_policy }} is not a valid RetryPolicy
