### DISCUSSION TITLE
`Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.`

### DISCUSSION THREAD

**Discussion by nishit93-hub** [argoproj/argo-workflows#8663] [Q&A]
Hi There,
I am getting this error  when i try to see workflow logs argo UI after the workflow completed. However when the workflow running then can i see the logs, i don’t see below error
`Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.`

**Comment by liujiong1982** [comment]
i met the issue in argo 3.0 too, any solution?

**Reply by gyanprakash48** [reply]
setting
```sh
argo-server --access-control-allow-origin=* 
```
fixed it  for me

**Reply by kvk24680** [reply]
> setting argo-server --access-control-allow-origin=* fixed it for me

Hi Gyan. Can you please tell, where we are supposed to change this

**Reply by chanhz** [reply]
> > setting argo-server --access-control-allow-origin=* fixed it for me
> 
> Hi Gyan. Can you please tell, where we are supposed to change this

Actually, argocd-server set this header by default. see https://github.com/argoproj/argo-cd/pull/5395 .
I set an annotation to ingress then fixed for me.
```
nginx.ingress.kubernetes.io/cors-expose-headers: "*, X-CustomResponseHeader"
```

**Reply by gyanprakash48** [reply]
i set this in deployment args of argo server (and worked for me)

```yaml
spec:
      containers:
      - args:
        - server
        - --auth-mode=sso
        - --access-control-allow-origin=*
        env: []
        image: quay.io/argoproj/argocli:v3.4.3
        name: argo-server
        ports:
        - containerPort: 2746
 ```
