### DISCUSSION TITLE
Pulling docker Image from AWS ECR ImagePullBackOff Error.

### DISCUSSION THREAD

**Discussion by mohsin-ashraf** [argoproj/argo-workflows#8701] [Q&A] [answered]
**Need help pulling ECR image from AWS**

Hi team, I am trying to run a PoC on minikube with argoFlow.
I have a minikube cluster up and running where I have a namespace for argo where the argo is running.
Now for the argo workflow I would require to pull images from private ECR repository. I am getting `no basic auth credentials` error when it comes to pull the image. Following is the YAML I am using.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: multistep-
  namespace: argo
spec:
  entrypoint: workflow
  imagePullSecrets:
  - name: ecr-secret
  templates:
  - name: vehicle-detection
    container:
      image: ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/IMAGE:latest
      imagePullPolicy: Always
      command: ["python", "app.py"]
  - name: lane-dectection
    container:
      image: ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/IMAGE:latest
      imagePullPolicy: Always
      command: ["python", "app.py"]
  - name: workflow
    steps:
    - - name: get-vehicle-detection
        template: vehicle-detection
      - name: get-lane-dectection
        template: lane-dectection
```

the ecr-secret contains the AWS access and private keys.

Can anyone help me get unstuck from this point.
