### DISCUSSION TITLE
[archived] "One Workflow Submitting Another" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#8709] [General]
# argo-workflows/workflow-submitting-workflow/

https://argoproj.github.io/argo-workflows/workflow-submitting-workflow/

**Comment by wuhuizuo** [comment]
why not using the [http](https://argoproj.github.io/argo-workflows/http-template/) template

**Reply by agilgur5** [reply]
This doc is v2.8 or after, whereas `http` templates are v3.2 and after. So this predates `http` templates.

But you can definitely use `http` template for this as well! There's several ways of doing it, this is just one example.

**Comment by anish749** [comment]
Another option is to use argo cli container to submit / wait for a workflow. i found that easier without having to manage tokens and a json string in a yaml!

**Reply by everestas** [reply]
How do you use Argo CLI in a task? What image is being used?

**Reply by anish749** [reply]
something like this:
```yaml
    - name: template-name
      container:
        image: argoproj/argocli:v3.4.4
        args: 
          - submit
          - --wait
          - --namespace=...
          - --from=wftmpl/...
```
