### DISCUSSION TITLE
Input Parameter Confusion and Differences Between WorkflowTemplate and Workflows

### DISCUSSION THREAD

**Discussion by luke-hemisphere** [argoproj/argo-workflows#8711] [Q&A]
## Summary

**What happened?**
Trying to submit a workflow template results in an error. The equivalent non-template workflow succeeds

```
argo -n argo template delete broken-template-inputs
> WorkflowTemplate 'broken-template-inputs' deleted

argo -n argo template create broken-template-inputs.yml
> Name:                broken-template-inputs
Namespace:           argo
Created:             Wed May 11 18:39:42 +1000 (now)

argo -n argo submit --from workflowtemplate/broken-template-inputs --watch 
> Failed to submit workflow: templates.main.tasks.A templates. inputs.parameters.px was not supplied`  
```

**What version are you running?** 
3.3.2

## Diagnostics

The following workflows are equivalent - one is a template and one is not.  
running the template version will fail  
running the non-template version will succeed  

### Template Version
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: broken-template-inputs
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: p1
        value: "1"
      - name: p2
        value: "2"
  templates:
    - name: main
      inputs:
        parameters:
          - name: p1
          - name: p2
      dag:
        tasks:
          - name: B
            arguments:
              parameters:
              - name: px
                value: "4"
            inline:
              inputs:
                parameters:
                  - name: px
              container:
                image: alpine:3.7
                command:
                  - sh
                  - -c
                  - exit 0
                
          - name: A
            arguments:
              parameters:
                - name: p1
                  value: "{{ inputs.parameters.p1 }}"
                - name: p2
                  value: "{{ inputs.parameters.p2 }}"
            inline:
              inputs:
                parameters:
                  - name: p1
                  - name: p2
              container:
                image: alpine:3.7
                command:
                  - sh
                  - -c
                  - exit 0
```

### Workflow Version
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: broken-template-inputs-
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: p1
        value: "1"
      - name: p2
        value: "2"
  templates:
    - name: main
      inputs:
        parameters:
          - name: p1
          - name: p2
      dag:
        tasks:
          - name: B
            arguments:
              parameters:
              - name: px
                value: "4"
            inline:
              inputs:
                parameters:
                  - name: px
              container:
                image: alpine:3.7
                command:
                  - sh
                  - -c
                  - exit 0
                
          - name: A
            arguments:
              parameters:
                - name: p1
                  value: "{{ inputs.parameters.p1 }}"
                - name: p2
                  value: "{{ inputs.parameters.p2 }}"
            inline:
              inputs:
                parameters:
                  - name: p1
                  - name: p2
              container:
                image: alpine:3.7
                command:
                  - sh
                  - -c
                  - exit 0
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Please check out some relevant documentation on WorkflowTemplate and parameters here: https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-templates.md#working-with-parameters

**Reply by ezk84** [reply]
What's curious is, if I submit that illustrative example without supplying the values at the WorkflowTemplate's template level, it submits fine:

```yaml wft.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-local-arg
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
```
```yaml wf.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-local-arg-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template-local-arg
              template: hello-world
            arguments:
              parameters:
                - name: msg
                  value: hola mundo
```
```sh
$ argo template create wft.yaml
Name:                hello-world-template-local-arg
Namespace:           argo
Created:             Thu May 12 11:11:33 +1000 (now)
$ argo submit wf.yaml 
Name:                hello-world-local-arg-25jmt
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Pending
Created:             Thu May 12 11:11:51 +1000 (now)
Progress:
```

Seems counterintuitive and counter to the idea of reusability if the argument values must be given at the WorkflowTemplate level instead of when that WorkflowTemplate's template is actually being used/called from a Workflow (as a utility function as it were). Am I misunderstanding the usage of WorkflowTemplates?
