### DISCUSSION TITLE
Need help with WorkflowTemplates from a DAG

### DISCUSSION THREAD

**Discussion by alexrosenfeld10** [argoproj/argo-workflows#8753] [Q&A] [answered]
I have a `WorkflowTemplate` that defines _most_ of what my job needs to do, but I'd like to execute it from a DAG where I can preface it with some preparatory step. Something like this:

```yaml
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        dag:
          tasks:
            - name: setup
              template: setup-template
            - name: domains
              depends: setup.Succeeded
              templateRef:
                name: domain-templates # This is a WorkflowTemplate
                template: domain-main
              arguments:
                parameters:
                  - name: domain
                    value: "{{item}}"
              withParam: |
                ["foo", "bar"]
      - name: setup-template
        script:
          image: python:alpine3.6
          command: [python]
          source: |
            print('running setup step')
```

The problem here is I'm invoking the `domain-templates` as a `templateRef`, instead of a `workflowTemplateRef`. As a result, I'm unable to use any of the nice things that `WorkflowTemplate`s offer - I can't use `{{workflow.parameters.<name>}}`, it is always unresolved because I'm not instantiating it via a `workflowTemplateRef`.

Is it just not possible to instantiate a whole `WorkflowTemplate` from a `dag.task`?

**Comment by terrytangyuan** [comment]
It's working for me. Try again?

Edit: apologies. I replied to the wrong issue.

**Reply by alexrosenfeld10** [reply]
Thank you for your reply! Here are more details.

If I do this in the `WorkflowTemplate` and try to use a template level arg:

```yaml
spec:
  arguments:
    parameters:
      - name: template-arg
  templates:
    - name: domain-main
      inputs:
        parameters:
          - name: domain
      dag:
        tasks:
          - name: run-private
            template: run-private-template
            arguments:
              parameters:
                - name: domain
                  value: "{{inputs.parameters.domain}}"
                - name: template-arg
                  value: "{{workflow.parameters.template-arg}}" # This errors out
```

The error is:

```
cannot validate Workflow: templates.main.tasks.domains templates.domain-main.tasks.run-private templates.run-private-template: failed to resolve {{workflow.parameters.template-arg}}
```

**Reply by alexrosenfeld10** [reply]
btw, the error happens whether I use `"{{workflow.parameters.template-arg}}"` in the _input_ to the `run-private-template` as well as if I use it in the `run-private-template` directly itself.

**Reply by alexrosenfeld10** [reply]
Ideally, I'd like to do something like this:

```yaml
      - name: main
        dag:
          tasks:
            - name: setup
              template: setup-template
            - name: domains
              depends: setup.Succeeded
              workflowTemplateRef: # This is the thing that seems like it's not possible, for some reason
                name: domain-templates
              arguments:
                parameters:
                  - name: domain
                    value: "{{item}}"
              withParam: |
                ["foo", "bar"]
```
