### DISCUSSION TITLE
how to inject gerrit refspec for git artifacts

### DISCUSSION THREAD

**Discussion by larrycai** [argoproj/argo-workflows#8880] [Q&A] [answered]
how to checkout gerrit changes?

see example https://review.opendev.org/c/x/tobiko/+/842634, normally I do it in console like below

````

git clone https://review.opendev.org/x/tobiko
cd tobiko
git fetch https://review.opendev.org/x/tobiko refs/changes/34/842634/6 && git checkout FETCH_HEAD
````

I checked https://github.com/argoproj/argo-workflows/blob/master/examples/input-artifact-git.yaml and read the git.go source code, no clue how to fix it

````
  - name: checkout
    inputs:
      artifacts:
      - name: code
        path: /workspace/tobiko
        git:
          repo: https://review.opendev.org/x/tobiko
          fetch: "refs/changes/34/842634/6"  ??
````

@terrytangyuan  can you help to check for this?

**Comment by larrycai** [comment, marked as answer]
After several tries, i made it work

````
  arguments:
    parameters: # These are the list of parameters that can be used throughout the workflow
    - name: ref
      value: "refs/changes/34/842634/6"
...
  - name: checkout
    inputs:
      artifacts:
      - name: code
        path: /workspace/tobiko
        git:
          repo: https://review.opendev.org/x/tobiko  
        fetch: 
        - "{{workflow.parameters.ref}}:{{workflow.parameters.ref}}"
        revision: "{{workflow.parameters.ref}}"
````

Hopefully it can be improved to make it more straighforward

also https://github.com/argoproj/argo-workflows/blob/master/examples/input-artifact-git.yaml#L49 has wrong format, it needs array
