### DISCUSSION TITLE
How to use `jsonpath` to get JSON object?

### DISCUSSION THREAD

**Discussion by DiegoFlop** [argoproj/argo-workflows#8930] [Q&A] [answered]
I have a JSON file in a git repository.
When I execute a workflow, I get this repository and read the next JSON file

```json
{
    "steps": {
        "test_!": {
            "skip": "false",
            "resources": {
                "requests": {
                    "cpu": "100m",
                    "memory": "512Mi"
                },
                "limits": {
                    "cpu": "200m"
                    "memory": "1024Mi"
                }
            }
        },
        "test_2": {
            "resources": {
                "requests": {
                    "cpu": "100m"
                },
                "limits": {
                    "cpu": "200m",
                    "memory": "512Mi"
                }
            }
        }
    }
}
```

I'm using `"{{= jsonpath(tasks.checkout.outputs.parameters.custom_config, '$.steps.test_1.resources') }}"` on a value field of inputs parameters
But I need get resources objecto, however jsonpath function return `map[limits:map[cpu:200m memory:1024Mi] requests:map[cpu:100m memory:512Mi]]` when I expected `"resources": {"requests": {"cpu": "100m","memory": "512Mi"},"limits": {"cpu": "200m""memory": "1024Mi"}}` for overwrite container resource with podSpecPatch.

Someone how I can solve this problem?

Thanks

**Comment by wesleyscholl** [comment]
Please advise if there is a solution for this, thanks.

**Reply by agilgur5** [reply]
You mean you want to convert the Go map to a JSON string? In 3.4 you can try [`asStr(v)`](https://github.com/argoproj/pkg/blob/287850b17c0ff8c1cc8840dad1674f9d4158d269/expr/function.go#L21), or in 3.5 you can try [`string(v)`](https://expr.medv.io/docs/v1.14/Language-Definition#stringv) or perhaps [`toJSON(v)`](https://expr.medv.io/docs/v1.14/Language-Definition#tojsonv)

**Reply by jheilgeist** [reply]
Note that with 3.4.10, we had to use the Argo-provided core function [`toJson(v)`](https://argo-workflows.readthedocs.io/en/release-3.4/variables/) instead of expr's `toJSON(v)`.

Full example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: foobar-wf-
spec:
  entrypoint: entry
  arguments:
    parameters:
      - name: my-config
        value: |
          {
            "my-list": [
              {
                "foo": 1,
                "bar": "value-1"
              },
              {
                "foo": 2,
                "bar": "value-2"
              }
            ]
          }
  templates:
    - name: entry
      steps:
        - - name: loop
            template: just-echo
            arguments:
              parameters:
                - name: message
                  value: "{{item}}"
            withParam: "{{=toJson(jsonpath(workflow.parameters['my-config'], '$.my-list'))}}"
    - name: just-echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine
        command: ["sh","-c"]
        args: ['echo "{{inputs.parameters.message}}"']
```
