### DISCUSSION TITLE
How to get sub workflow output in parent workflow?

### DISCUSSION THREAD

**Discussion by polarbear567** [argoproj/argo-workflows#8943] [Q&A]
Now my parent workflow is this:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: render-output
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: test
            template: service-template
            arguments:
              parameters:
              - name: param
                value: readInput
          - name: trigger
            depends: test.Succeeded
            template: triggerWorkflowUsingResourceWithArgument
            arguments:
              parameters:
              - name: workflowtemplate
                value: "execution"
              - name: context
                value: testvalue
          - name: echo-after-trigger
            depends: trigger.Succeeded
            template: echo
            arguments:
              parameters:
              - name: result
                value: "{{tasks.trigger.outputs.result}}"
    - name: triggerWorkflowUsingResourceWithArgument
      inputs:
        parameters:
          - name: workflowtemplate
          - name: context
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: execute-
          spec:
            arguments:
              parameters:
              - name: context
                value: {{inputs.parameters.context}}
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
    - name: service-template
      inputs:
        parameters:
          - name: param
      script:
        image: test/service-cmd:latest
        imagePullPolicy: Never
        command: [sh]
        source: |
          ./service-cmd {{inputs.parameters.param}}
    - name: echo
      inputs:
        parameters:
          - name: result
      container:
        image: alpine:latest
        command: [sh, -c]
        args: [ "echo {{inputs.parameters.result}}" ]
```
And my sub workflow is this one:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: execution
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: context
    dag:
      tasks:
        - name: sub-test
          template: service-template
          arguments:
            parameters:
            - name: param
              value: subtestvalue
  - name: service-template
    inputs:
      parameters:
        - name: param
    script:
      image: test/service-cmd:latest
      imagePullPolicy: Never
      command: [sh]
      source: |
        ./service-cmd {{inputs.parameters.param}}
```

First, I put the sub workflow yaml to argo server,  but when I put the parent yaml file, it told me: 

> Internal Server Error: templates.main.tasks.echo-after-ref failed to resolve {{tasks.echo-ref.outputs.result}}

So How can I do that I can get the sub workflow output in parent workflow? @terrytangyuan @alexec 

Update:
Output parameters is good for templateRef, but it seems not good for resource template, even I use the global output.
