### DISCUSSION TITLE
Not being able to make sso service account work properly

### DISCUSSION THREAD

**Discussion by spothound** [argoproj/argo-workflows#8971] [Q&A] [answered]
Hello there,

I have just set up argo workflows with sso access. Configured a read-only service account and bound it to it a role that is supposed to grant only read permissions for everything related to argo workflows, this SA seems to be assigned to users when they log in to argo workflows but **they are still able to create workflows and others resources using the GUI**.

 I am not able to see what did I do wrong, any help would be appreciated.

![image](https://user-images.githubusercontent.com/15269938/173840692-f5cf433c-5b58-4a46-89cf-a2bed48dc90d.png)

This is the role that I created:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-readonly-role
  namespace: argo
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - eventsources
  - sensors
  - workflows
  - workfloweventbindings
  - workflowtemplates
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - get
  - list
  - watch
```

The sa:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
  name: read-only
  namespace: argo
secrets:
- name: argo-token-qq97d
- name: read-only-token-qh72k
```

And the role binding:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-binding-readonly
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-readonly-role
subjects:
- kind: ServiceAccount
  name: read-only
  namespace: argo
```

An interesting issue that I have found is that, if (after logged and with this read-only service account assigned) I go to the Pipelines view in the GUI I see this error message:

```
 Forbidden: pipelines.dataflow.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "pipelines" in API group "dataflow.argoproj.io" in the namespace "argo"
```

![image](https://user-images.githubusercontent.com/15269938/173841387-db49e5aa-d789-4f58-b0cd-fd3bf7295bf9.png)

This doesn't make too much sense to me because it should be applying the serviceaccount:read-only as shown in the other screenshot, on the user login page.

Any ideas? thanks for your help in advice!
