### DISCUSSION TITLE
Is it possible to start a workflow after another workflow ends?

### DISCUSSION THREAD

**Discussion by simper66** [argoproj/argo-workflows#8980] [Ideas]
Like a CronWorkflow based on parent intead of schedule

Something like this:

```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cwf1
spec:
  schedule: "0 19 0 0 0"
  workflowSpec:
    entrypoint: start
    templates:
      - name: start
        steps:
          ..................


apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cwf2
spec:
  parent:
    cwfRef:
      name: cwf1
  workflowSpec:
    entrypoint: start
    templates:
      - name: start
        steps:
          ..................
```

**Comment by simper66** [comment]
This is somehow related to #https://github.com/argoproj/argo-workflows/discussions/5154

It could be interesting also an argo event whose source was a "workflow ends" and "workflow error"

**Comment by terrytangyuan** [comment]
Use resource templates where each template is a workflow resource. You can then create a DAG of workflows and specify the dependency relationship.

**Reply by simper66** [reply]
Yes, but i dont want/can to create the "parent" workflow. Actually, it is managed by another team. 

I mean a "mechanism" to trigger a workflow when another workflow ends. Something like:

```
metadata:
  name: wf2
spec:
  parent:
    cwfRef:
      name: cwf1
```

Right now, the only way is to ask the other team to generate an event (sqs, rabbitmq, etc) and run my workflow programmatically.
