### DISCUSSION TITLE
can we support variables in workflow templateRef name?

### DISCUSSION THREAD

**Discussion by larrycai** [argoproj/argo-workflows#8995] [Ideas]
it could be quite big topic to see whether workflowtemplate can support version like github actions (it needs to involve argocd as well), but start small one

# Whether we can have variables in workflow templateRef name?

Like the `$wftversion` in `templateRef`

# Use case 

* deployed workflow template in different versions, needs to switch fast by global variables
* it can be used during debug as well, since product flow points to latest stable one

see code sample

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-at-v0.1.0
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-at-master
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-local-arg-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: wftversion
        value: master
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-at-${wftversion}
              template: hello-world
```
