### DISCUSSION TITLE
Use step output as file.

### DISCUSSION THREAD

**Discussion by driv** [argoproj/argo-workflows#9043] [Q&A]
I'm trying to do something relatively simple in 2 steps:
- execute a `aws-cli` command
- convert the `aws-cli` json output with `jq`.

This is a simplified example:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: myworkflow
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - template: aws
        name: get-data
    - - template: jq
        name: extract-values
        arguments:
          artifacts:
            - name: data
              raw:
                data: "{{steps.get-data.outputs.result}}"
  - name: aws
    container:
      command:
      - aws
      image: amazon/aws-cli
      args: 
        - arg1
        - arg2
  - name: jq
    inputs:
      artifacts:
        - name: data
          path: /tmp/data.json
    container:
      image: stedolan/jq
      command:
        - jq
      args:
        - -j
        - "."
        - "{{inputs.artifacts.data.path}}"
```

The problem I'm facing is that I'm not able to use the `steps.get-data.outputs.result` as input file for the `jq` step because when I execute I'm getting `metadata.annotations: Too long: must have at most 262144 bytes`. 

Is there any way to pass the output of a step as a file to another one instead of it being included in an annotation?

In this case I would need to convert `command` to `script` and redirect the output to a file since both `aws` and `jq` can't write to a file; define the file as an output and use it from the next step.

Am I missing something or is it not possible at all to directly use the output as file?
