### DISCUSSION TITLE
Reference output artifacts from a referenced workflow template

### DISCUSSION THREAD

**Discussion by spothound** [argoproj/argo-workflows#9076] [Q&A]
Hello there,

I am struggling to get this working:

I have defined some simple-generic workflow templates in my argo-workflwos environment and now I want to create more complex ones using those simple templates as a base.

To do this, I am using templateRef, like in this example:

```
- - name: generate-required-data
        templateRef:
          name: get-latest-data
          template: main
```

But then, when I try to use the data generated by this workflow in other workflow, using a syntax like this one:

```
    - - name: push-data
        template: push
        arguments:
          artifacts:
          - name: data
            from: "{{steps.generate-required-data.outputs.artifacts.aws_data}}"
```

I got:

```
 Internal Server Error: templates.main.steps failed to resolve {{steps.generate-required-data.outputs.artifacts.aws_data}}
```

I wonder if, as it is a referenced template, I need to do some extra step to make this output available. I did some tests but none of them works.

Any help?
