### DISCUSSION TITLE
en/latest/artifact-repository-ref/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#9081] [General]
# en/latest/artifact-repository-ref/

https://argo-workflows.readthedocs.io/en/latest/artifact-repository-ref/

**Comment by hxlee309** [comment]
Hi, when I run the first workflow, it keeps running without returning any log, what might be the possible reason?

**Reply by makzzz1986** [reply]
Check if you have any output directly from Kubernetes

**Comment by nagesh1977** [comment]
i am new to the argo workflow, facing  problem where my workflow keeps running without returning any log.please suggest...

**Reply by OneCricketeer** [reply]
Does the image that is ran produce logs to stdout, or only to some file within the container?

**Comment by Hanliber** [comment]
hi,when I submit workflow to another namespace, minio can not work ,what might be the possible reason?
error message:You need to configure artifact storage. More information on how to do this can be found in the docs: https://argoproj.github.io/argo-workflows/configure-artifact-repository/

**Reply by OneCricketeer** [reply]
You'll need to share your configuration setup for more details... What's unclear from that link? Do the docs need updated?

**Reply by agilgur5** [reply]
Have you created a suitable `ConfigMap` in the other namespace or in the managed namespace?

As it says at the top of this page, you must have:
> a suitable config map in either (a) your workflows namespace or (b) in the managed namespace

**Comment by parasappafluke** [comment]
Hi,
Is there way we can override artifact repository kepformat at workflow level?
thanks

**Reply by agilgur5** [reply]
Yes, at the bottom of this page it says you can do so by setting `artifactRepositoryRef` on your `Workflow` `spec`:

> ```yaml
> spec:
>  artifactRepositoryRef:
>    configMap: my-artifact-repository # default is "artifact-repositories"
>    key: v2-s3-artifact-repository # default can be set by the `workflows.argoproj.io/default-artifact-repository` annotation in config map.
> ```

**Comment by milosbackonja** [comment]
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1-s3-artifact-repository
  name: artifact-repositories
  namespace: argo-workflows
data:
  default-v1-s3-artifact-repository: |
    archiveLogs: true
    s3:
      bucket: my-bucket-name
      endpoint: s3.amazonaws.com
      keyFormat: workflow-artifacts/
      region: region
      useSDKCreds: true
```

Should this work with serviceAccount and IRSA? I want to avoid defining credentials in configuration, but also want to avoid granting access for workflow service accounts by defining default repository?
