### DISCUSSION TITLE
failFast in dag logic does not work

### DISCUSSION THREAD

**Discussion by ksudate** [argoproj/argo-workflows#9084] [Q&A]
Hi,I have tried the failfast feature of the DAG logic with the following manifest.

ref. https://github.com/argoproj/argo-workflows/blob/master/examples/dag-disable-failFast.yaml

<details>
<summary>sample code</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-primay-branch-
spec:
  entrypoint: statis
  templates:
  - name: a
    container:
      image:  docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
  - name: b
    retryStrategy:
      limit: "2"
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["sleep 30; echo haha"]
  - name: c
    retryStrategy:
      limit: "3"
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 2"]
  - name: d
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
  - name: statis
    dag:
      tasks:
      - name: A
        template: a
      - name: B
        depends: "A"
        template: b
      - name: C
        depends: "A"
        template: c
      - name: D
        depends: "B"
        template: d
      - name: E
        depends: "D"
        template: d
```
</details>

The expected behavior when **failFast is true** is that Steps after B do not execute because C failed.

However, in fact, all steps were executed and succeeded.
<img width="444" alt="スクリーンショット 2022-06-30 12 39 10" src="https://user-images.githubusercontent.com/33239455/176587714-f7a9e16b-30ae-4b2e-88fc-a0924288a7b8.png">

Is this the intended behavior?
