### DISCUSSION TITLE
argo-workflows/walk-through/artifacts/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#9114] [General]
# argo-workflows/walk-through/artifacts/

https://argoproj.github.io/argo-workflows/walk-through/artifacts/

**Comment by baguasquirrel** [comment]
How would you timestamp the keys of artifacts that you e.g. upload to S3, and then only keep the last 10?

**Reply by baguasquirrel** [reply]
Okay, I think I might have answered my own question. You can access various time variables from the [workflow variables](https://argoproj.github.io/argo-workflows/variables/). A TTL for the objects can be set on the S3 bucket.

**Comment by aguerrero232** [comment]
Is it possible to store an artifact of an http template response?

Something like this?
```yaml
    - name: http-get
      inputs:
        parameters:
          - name: url
      http:
        method: GET
        url: '{{inputs.parameters.url}}'
      outputs:
        # ? store the response in an artifact to be used by other steps
        artifacts:
          - name: response
            path: /tmp/response.json
```

**Reply by artemklevtsov** [reply]
This should works:

```yaml
    - name: example
      inputs:
        artifacts:
          - name: input-data
            path: /data.csv
            mode: 644
            http:
              url: "{{ workflow.parameters.url }}"
      outputs:
        artifacts:
          - name: output-data
            path: /data.csv
```
