### DISCUSSION TITLE
[archived] "Configure Artifact Repository" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#9124] [General]
# argo-workflows/configure-artifact-repository/

https://argoproj.github.io/argo-workflows/configure-artifact-repository/

**Comment by potatokat** [comment]
Is it possible to upload artifacts to S3 though proxy?

**Comment by marloflores** [comment]
Does Argo support server-side encrypted S3 bucket?

**Comment by FeddeX99** [comment]
When i run: 
```sh
helm install argo-artifacts minio/minio --set service.type=LoadBalancer --set fullnameOverride=argo-artifacts
```

I am getting: 
```sh
helm install argo-artifacts minio/minio --set service.type=LoadBalancer --set fullnameOverride=argo-artifacts
```

I have been trying to install minio as an artifact repository for days (with many different methods), but nothing works. Any help would be greatly appreciated!

**Comment by ls84** [comment]
For version 3.4
Configuring OSS Artifact Repository
k8s secret should be created using [stringData field](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/) and **NOT** base64 encoded:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifact
  namespace: default
type: Opaque
stringData:
  accessKey: DO NOT BASE64 ENCODE THIS
  secretKey: DO NOT BASE64 ENCODE THIS
```
using data field and base64 encoded value, Will get you an invalid header value for Authorization key.
