### DISCUSSION TITLE
[archived] "Workflow Creator" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#9125] [General]
# argo-workflows/workflow-creator/

https://argoproj.github.io/argo-workflows/workflow-creator/

**Comment by makzzz1986** [comment]
Does workflow have a variable for it? Would be nice to use it in a template for logging or log it on DB.

**Reply by terrytangyuan** [reply]
Yes, `workflow.labels.<NAME>`. Reference: https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md#global

**Reply by makzzz1986** [reply]
Thank you! It was a great point, it helped me a lot. After some experiments I've made this dirty hack:
```yaml
# ***
       env:
          - name: USER
            value: '{{=sprig.get(workflow.labels.workflows.argoproj, "io/creator")}}'
# ***
        args:
           - [ "${USER}" != "" ] && echo "$(echo ${USER}|base64 -d 2>/dev/null)" || echo "CronWorkflow job, without the creator label"
# ***
```
