### DISCUSSION TITLE
how to set credentials to clone github private repo in argo workflow manifest file?

### DISCUSSION THREAD

**Discussion by vaporpin** [argoproj/argo-workflows#9177] [Q&A] [answered]
Hi,
I would like to build an image of codes residing in a private github repo. 

The examples on the site are on public github repo. 

Does anyone have any example or any link to this? Thank you.

**Comment by terrytangyuan** [comment, marked as answer]
Use usernameSecret and passwordSecret in your Git artifact.

**Reply by vaporpin** [reply]
Thank you. Any reference i can refer to? As in a manifest file. With the secrets and doing cloning of repo or building of image.

**Reply by DiegoFlop** [reply]
I use this manifest configuration on inputs section:

```
artifacts:
  - name: git-clone
    path: "/workspace/project"
    git:
      revision: "{{inputs.parameters.BRANCH}}"
      repo: "{{inputs.parameters.git_ssh_url}}"
      singleBranch: false
      sshPrivateKeySecret:
        name: gitlab
        key: id_rsa
      insecureIgnoreHostKey: true
```

if you use your own repository you need enable insecureIgnoreHostKey param
