### DISCUSSION TITLE
Unable to Authenticate using an Argo Ingress URL

### DISCUSSION THREAD

**Discussion by devstewart** [argoproj/argo-workflows#9183] [Q&A]
## Summary 
We are trying to enable token-based authentication, but we are running into issues.

## Problem
I don't understand why but if I run Argo in Kubernetes using `server --namespaced --auth-mode=client`, I am able to list, submit, and otherwise interact with Argo as expected using the Argo cli.  For example `argo submit hello.yml -n argo --watch --token xxx --server https://xxx` works fine.

However, when I use Bearer token auth in my request header using the ingress endpoint with the same Kubernetes token I get the error `HTTP response body: {"code":16,"message":"token not valid for running mode"`  I also get a Not Authorized response when I use the same token which is what I get form `argo auth token`

## What I've tried
Reinstalled Argo in one cluster and nothing changed.

## Version
3.1.8

## Question
I believe this issue is somehow related to our K8s clusters because I have two clusters exhibiting the same problematic behavior and two clusters which work as expected.  We are running Argo namespaced now, but we were running clustered previously, could this my an RBAC issue brought on by not cleanly uninstalling the clustered Argo deployment?  What resources in the cluster are should I look at?

## Supporting Configs
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: argo-ingress
  namespace: argo
spec:
  rules:
  - host: argo.example.com
    http:
      paths:
      - backend:
          service:
            name: argo-server
            port:
              number: 2746
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - argo.example.com
```
