### DISCUSSION TITLE
Running Spring Boot App

### DISCUSSION THREAD

**Discussion by ca2so4u** [argoproj/argo-workflows#9188] [Q&A] [answered]
Hi folks,
I have a simple Spring Boot app and created a Docker Image "student-kubernetes-demo" with:
```
FROM openjdk:11
ADD ./target/student-kubernetes-demo-0.0.1-SNAPSHOT.jar student-kubernetes-demo-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/student-kubernetes-demo-0.0.1-SNAPSHOT.jar"]
```

Now I want to run this app in a workflow. How does that work? I created a template:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: student-test
spec:
  entrypoint: student

  templates:
  - name: student
    inputs:    
    container:
      image: student-kubernetes-demo
```
But i got this error message:

failed to look-up entrypoint/cmd for image "student-kubernetes-demo", you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary: GET https://index.docker.io/v2/library/student-kubernetes-demo/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/student-kubernetes-demo Type:repository]]
