### DISCUSSION TITLE
`podSpecPatch` for `init` container

### DISCUSSION THREAD

**Discussion by BhavikaSharma** [argoproj/argo-workflows#9203] [Q&A] [answered]
Hi, I am trying to understand how to use `podSpecPatch` for `init` containers to manipulate resource requirements.

When submitting:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-spec-patch-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: cpu-limit
        value: 100m
  templates:
  - name: whalesay
    podSpecPatch: '{"containers":[{"name":"init", "resources":{"limits":{"cpu": "{{workflow.parameters.cpu-limit}}" }}}]}'
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
```

I'm seeing the error:

```
container "init" in template "whalesay", does not have the command specified: when using the emissary executor you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary
```

I would assume that a `command` wouldn't be explicitly required for `init` but did also try with this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-spec-patch-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: cpu-limit
        value: 100m
  templates:
  - name: whalesay
    podSpecPatch: '{"containers":[{"name":"init",  "image":<ARGOEXEC_IMAGE>, "command": ["init"], "resources":{"limits":{"cpu": "{{workflow.parameters.cpu-limit}}" }}}]}'
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
```

and got the error:

```
Pod "pod-spec-patch-v4cn6" is invalid: spec.initContainers[0].name: Duplicate value: "init"
```

I was wondering how to use `podSpecPatch` for init containers. The first Workflow succeeds if `init` is changed to `main` or `wait`. My ultimate goal is to increase resource limits due to this issue: https://github.com/argoproj/argo-workflows/issues/1322 where the latest suggestion was to use `podSpecPatch` but please let me know if there's another path that could be explored. Thanks.

**Comment by BhavikaSharma** [comment, marked as answer]
Init container live under `initContainers` not `containers`.

Working spec:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-spec-patch-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: cpu-limit
        value: 100m
  templates:
  - name: whalesay
    podSpecPatch: '{"initContainers":[{"name":"init", "resources":{"limits":{"cpu": "{{workflow.parameters.cpu-limit}}" }}}]}'
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
```
