### DISCUSSION TITLE
Executor Plugin error

### DISCUSSION THREAD

**Discussion by raosharadhi** [argoproj/argo-workflows#9230] [Q&A]
Hi Team,
I wanted to explore the plugin part in argo workflows.

- Installed argo workflows (v3.3.8) into the Minikube cluster.
- Added env in workflow controllers and set Argo Executor plugins value as true.
- Cloned the hello-world plugin from the official GitHub link in the documentation and ran these commands.
```sh
argo executor-plugin build .
kubectl -n argo apply -f hello-executor-plugin-configmap.yaml
```

- I Can see the plugin installed in the logs of the workflow controller.

```
time="2022-07-26T06:33:34.492Z" level=info msg=Plugins executorPlugins=true
time="2022-07-26T06:33:34.520Z" level=info msg="Executor plugin added" name=hello-executor-plugin 
```

workflow code:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-
spec:
  entrypoint: main
  templates:
    - name: main
      plugin:
        hello: { }
```

But when copy and run the same workflow it shows an error like this.
 ```
Failed: invalid spec: template 'main' type is unknown
```

For Screenshots please go here: https://dev.to/sharadhi/argo-workflow-executor-plugins-2imm

Can anyone help me to solve this issue?

The links I referred are: https://github.com/argoproj-labs/argo-workflows-hello-executor-plugin
https://argoproj.github.io/argo-workflows/executor_plugins/

**Comment by terrytangyuan** [comment]
@alexec Could you take a look?

**Comment by alexec** [comment]
Can you check that your `argo` cli is up to date?

**Reply by raosharadhi** [reply]
Yes This is the version I am using.
<img width="409" alt="Screenshot 2022-07-26 at 8 31 30 PM" src="https://user-images.githubusercontent.com/93312164/181041707-0b7a2b95-fe2b-4708-ac41-6c884448d2eb.png">

**Comment by alexec** [comment]
I've not been able to reproduce this locally. The workflow runs successfully. This hints to a user error.

Could you try `kubectl -n argo create -f hello-example-workflow.yaml`?

**Reply by raosharadhi** [reply]
Now If I ran from UI I get this same error as template unknown and As you suggested If I ran that command. The pod is in a pending state as you can see in second workflow.
<img width="1063" alt="Screenshot 2022-07-26 at 9 04 20 PM" src="https://user-images.githubusercontent.com/93312164/181048457-4581847f-cd5b-4775-aaeb-eceea5480779.png">

I installed Argo workflow using these commands. @alexec Can you please once check Is it because of this?
```
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.3.8/install.yaml 
kubectl -n argo create rolebinding default-admin --clusterrole=admin --serviceaccount=argo:default 
```

**Reply by maxisam** [reply]
I just wanna say I have exactly the same issue. I installed through helm chart v3.3.9. I have RBAC enabled but I am fine to run normal workflow. I can see the plugin got added from the logs as well. I can't see any plugin from the UI

**Reply by lijiaonothing** [reply]
I use the CLI in 'Kubernetes API Mode (default)', The workflow runs successfully.
when I use CLI in 'Argo Server HTTP1 Mode', it shows an error like this: 'Failed: invalid spec: template 'main' type is unknown'

**Comment by alexec** [comment]
Can you check the logs of the agent and of the controller to find where that error occurs please?

**Reply by raosharadhi** [reply]
to check the agent pod, the agent pod is not creating itself. It's deleting by itself.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/93312164/181754769-88de86d9-635b-4bef-b46e-15107c44274e.png">

**Comment by alexec** [comment]
Can you check the image the agent pod is the same version as the controller.

**Reply by raosharadhi** [reply]
Hi @alexec , For now, I did cluster install through kustomize. Now plugin I am able to see, but I am getting this error now in agentpod.
```
time="2022-08-01T11:43:35.308Z" level=warning msg="Non-transient error: workflowtasksets.argoproj.io \"hello-example-s7rsd\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot patch resource \"workflowtasksets/status\" in API group \"argoproj.io\" in the namespace \"argo\""
time="2022-08-01T11:43:35.308Z" level=error msg="TaskSet Patch Failed" error="workflowtasksets.argoproj.io \"hello-example-s7rsd\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot patch resource \"workflowtasksets/status\" in API group \"argoproj.io\" in the namespace \"argo\"" workflow=hello-example-s7rsd
```
The pod is running successfully 2/2 and I have also added workflowtaskset/status role in the aggregator file.

<img width="657" alt="Screenshot 2022-08-01 at 5 15 50 PM" src="https://user-images.githubusercontent.com/93312164/182141073-616723fc-6c9c-421f-b257-b719294de075.png">
<img width="657" alt="Screenshot 2022-08-01 at 5 16 26 PM" src="https://user-images.githubusercontent.com/93312164/182141168-2131f7e8-5cbc-4a61-a703-f49454424e72.png">

Can you please look into this?
I used this command
```
argo submit  hello-example-workflow.yaml --serviceaccount argo -n argo
```

**Comment by chaudharirohit2810** [comment]
Has anyone found solution for this? Currently we are facing exact same issue

**Reply by sumeet-baghel** [reply]
I don't know if my answer is relevant to this specific issue but I observed the same error today while creating a `ClusterWorkflowTemplate` for DIND use case.

**dind-template**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: dind-template
spec:
  templates:
    - name: docker-sidecar
      sidecars:
      - name: dind
        image: docker:24.0.6-dind # Official docker dind image
        command: [dockerd-entrypoint.sh]
        env:
          - name: DOCKER_TLS_CERTDIR # Docker TLS env config
            value: ""
        securityContext:
          privileged: true # the Docker daemon can only run in a privileged container

        # mirrorVolumeMounts will mount the same volumes specified in the main container
        # to the sidecar (including artifacts), at the same mountPaths. This enables
        # dind daemon to (partially) see the same filesystem as the main container in
        # order to use features such as docker volume binding.
        mirrorVolumeMounts: true
```

**Error while applying**

> [!NOTE] 
> I observed the same error when I applied it directly via kubectl and used it in a workflow

```console
$ argo cluster-template create dind_template.yml
2023/10/06 09:18:29 Failed to create cluster workflow template: dind-template,  rpc error: code = InvalidArgument desc = templates.docker-sidecar template 'docker-sidecar' type is unknown
```

I was able to resolve the error by adding the `container` field to the template spec as follows.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: dind-template
spec:
  templates:
    - name: docker-sidecar
      container:
        image: "repo/image"
        command: ["/bin/sh", "-c"]
        args: ["ls -l"]
      sidecars:
      - name: dind
        image: docker:24.0.6-dind # Official docker dind image
        command: [dockerd-entrypoint.sh]
        env:
          - name: DOCKER_TLS_CERTDIR # Docker TLS env config
            value: ""
        ...
```

I'm guessing the `container` field is required and that's the reason argo is throwing a cryptic error 🤷🏻‍♂️
