### DISCUSSION TITLE
Is it possible to ignore error when archiving log

### DISCUSSION THREAD

**Discussion by carolkao** [argoproj/argo-workflows#9231] [Q&A]
Hi,
I've turned on **archiveLogs** to save the main log into OSS in a config map.
```
artifactRepository: |
    archiveLogs: true
    oss:
      endpoint: https://xxx.oss-us-east-1-internal.aliyuncs.com
```

However, sometime the service failed to communicate with OSS due to some network issue. Then I'll get the error like:
```
Error (exit code 1): Put "https://xxx.oss-us-east-1-internal.aliyuncs.com/xxxxxxxmain.log": dial tcp: i/o timeout
```
and the pod finally go into failed state.

I'm wondering if there exists any way to ignore the error from archiving logs, and the pod can complete successfully. Thanks.
