### DISCUSSION TITLE
`artifact not found` message for artifact API

### DISCUSSION THREAD

**Discussion by noahingh** [argoproj/argo-workflows#9236] [Q&A] [answered]
Hi, all 

Only a 500 error and "artifact not found" message is output when accessing the artifact API to receive archived logs. However, the artifact is precisely located in the S3 bucket when I checked, and Workflow Logs are being uploaded normally.

<details>

```
curl -H "Authorization: $ARGO_TOKEN" -v http://localhost:2746/artifacts/argo-workflows/hello-world-cd4pm/hello-world-cd4pm/main-logs

< HTTP/1.1 500 Internal Server Error
< Date: Wed, 27 Jul 2022 03:36:46 GMT
< Content-Length: 18
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
artifact not found* Closing connection 0
```

</details>

Permissions for S3 use the EKS IRSA method, and the artifact repository settings are as follows. What should I check here? 

<details>
<summary> values.yaml of Helm chart</summary>

```yaml
workflow:
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/argo-workflows

controller:
  workflowNamespaces:
    - argo-workflows

server:
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/argo-workflows

# Archive logs to S3
# https://argoproj.github.io/argo-workflows/configure-archive-logs/
useDefaultArtifactRepo: true
useStaticCredentials: false
artifactRepository:
  archiveLogs: true
  s3:
    endpoint: s3.amazonaws.com
    bucket: argo.buzzvil-internal.com
    keyFormat: dev/{{workflow.creationTimestamp.Y}}/{{workflow.name}}/{{pod.name}}
    region: ap-northeast-1
    insecure: false
    useSDKCreds: true
```

</details>
