### DISCUSSION TITLE
How to do "if" statement in resource template?

### DISCUSSION THREAD

**Discussion by CRASH-Tech** [argoproj/argo-workflows#9256] [Q&A]
Like this

```
resource:
  action: apply
  successCondition: status.sync.status == Synced
  manifest: |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      labels:
        project: test
        {{ if inputs.parameters.protocol == 'http' }}
        some: label
        {{ end }}
```
