### DISCUSSION TITLE
Why does port-forward fail when started with --secure=false?

### DISCUSSION THREAD

**Discussion by ken-sayama** [argoproj/argo-workflows#9272] [Q&A]
Hi guys

I'm trying to launch argo workflow with `--secure=false` but can't open http://localhost:2746

First, I installed argo workflow using the manifest in the cluster-install directory
https://github.com/argoproj/argo-workflows/tree/master/manifests/cluster-install

And changed the argo-server-deployment.yaml in the base directory as below
https://github.com/argoproj/argo-workflows/blob/master/manifests/base/argo-server/argo-server-deployment.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      serviceAccountName: argo-server
      containers:
        - name: argo-server
          image: quay.io/argoproj/argocli:latest
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args: [ 'server', '--secure=false', '--auth-mode=server']
          ports:
            - name: web
              containerPort: 2746
          readinessProbe:
            httpGet:
              port: 2746
              scheme: HTTP
              path: /
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: tmp
          emptyDir: { }
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
```
After that run "kubectl -n argo port-forward deploy/argo-server 2746:2746" and open http://localhost:2746 in my browser.
but it seems to succeed and fails
this is the log at that time
```
Forwarding from 127.0.0.1:2746 -> 2746
Forwarding from [::1]:2746 -> 2746
Handling connection for 2746
Handling connection for 2746
Handling connection for 2746
Handling connection for 2746
Handling connection for 2746
E0802 19:20:08.207019   98328 portforward.go:406] an error occurred forwarding 2746 -> 2746: error forwarding port 2746 to pod 10e99ccbfa64029f061c96c692d74f4b7a5a421f30158d86840a1b7956c8aaf7, uid : exit status 1: 2022/08/02 10:20:08 socat[754917] E write(5, 0xaaaacf126eb0, 7): Broken pipe
Handling connection for 2746
Handling connection for 2746
Handling connection for 2746
Handling connection for 2746
E0802 19:20:38.211115   98328 portforward.go:368] error creating forwarding stream for port 2746 -> 2746: Timeout occurred
E0802 19:20:38.488115   98328 portforward.go:234] lost connection to pod
```

am i doing something wrong?
