### DISCUSSION TITLE
argoWorkflow in Events Sensor uses workflowTemplateRef, can't use volumes?

### DISCUSSION THREAD

**Discussion by luthes** [argoproj/argo-workflows#9300] [Q&A]
I guess the title might not explain it very well. Essentially I have a Sensor that watches for Github events, that creates Workflows using `argoWorkflows` trigger. That trigger calls a ClusterWorkflowTemplate which is defined as part of my workspaces deployment. Inside of that cluster workflow template I have multiple templates and a dag calling all of the templates, they all share a volume for some logs that I output to Slack/PR Comment at the end. I can't seem to get the volumes to mount, mabye I have them in the wrong place, I'm not sure.

tl;dr can't call ClusterWorkflowTemplates from ClusterWorkflow Templates and still mount volumes.

Code:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: github
      eventSourceName: github
      eventName: github-repos
  triggers:
    - template:
        name: cwft-tests
        argoWorkflow:
          parameters:
            - src:
                dependencyName: github
                dataKey: body.pull_request.action
              dest: spec.arguments.parameters.0.value
          resource: Workflow
          operation: submit
          metadata:
            generateName: cwft-test-submittable-
            namespace: argo-worklfows
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: trigger-test-workflow-
              spec:
                arguments:
                  parameters:
                    - name: html_url
                serviceAccountName: argo-events-sa
                entrypoint: workflow-dag
                workflowTemplateRef:
                  name: cwft-test-submittable
                  clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: >-
      This template runs our test suite and posts to Github/Slack
    workflows.argoproj.io/maintainer: '@luthes'
    workflows.argoproj.io/tags: test-pipeline
  name: cwft-test-submittable
  namespace: argo-workflows
spec:
  entrypoint: workflow-dag
  volumeClaimTemplates:
    - metadata:
        name: workdir
        namepsace: argo-events
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  templates:
    # I want to use another ClusterWorkflowTemplate here, defined below.
    - name: echo-template-ref
      workflowTemplateRef:
        name: cwft-echo-template
        clusterScope: true # I have workflows and events in separate namespaces
      arguments:
        parameters:
          - name: text
            value: '{{inputs.parameters.text}}'
    # Currently, I have this commented out block, but I want to remove it to a
    # template. 
    #- name: echo-file
    #  inputs:
    #    parameters:
    #      - name: text
    #  volumes:
    #    - name: workdir
    #      emptyDir: { }
    #  container:
    #    image: alpine:3.7
    #    command: [echo, '{{inputs.parameters.text}}']
    #    volumeMounts:
    #      - name: workdir
    #        mountPath: /tmp
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: >-
      A template for echoing text
    workflows.argoproj.io/maintainer: '@luthes'
    workflows.argoproj.io/tags: echo
  name: cwft-echo-template
spec:
  entrypoint: git-pr-clone
  arguments:
    - name: text
  templates:
    - name: echo-file
      inputs:
        parameters:
          - name: text
      volumes:
        - name: workdir
          emptyDir: { }
      container:
        image: alpine:3.7
        command: [echo, '{{inputs.parameters.text}}']
        volumeMounts:
          - name: workdir
            mountPath: /tmp

```
