### DISCUSSION TITLE
How to supply a secret in the http template?

### DISCUSSION THREAD

**Discussion by jackivanov** [argoproj/argo-workflows#9369] [Q&A] [answered]
https://argoproj.github.io/argo-workflows/http-template/

The endpoint requires basic auth, how do I supply a secret to the template? This is not something documented

**Comment by gunsha** [comment]
having the same issue, @jackivanov did you manage to solve it?

**Comment by duizabojul** [comment, marked as answer]
According to fields reference, you can do it like this:

```yaml
http:
  headers:
    - name: Authorization
      valueFrom:
        secretKeyRef:
          key: token
          name: my-secret
```
