### DISCUSSION TITLE
explicitly specify the command

### DISCUSSION THREAD

**Discussion by wekinu** [argoproj/argo-workflows#9452] [Q&A] [answered]
Updated from ver 3.2 to 3.3 workflow template error occurred.
this is workflow template .
```yaml
    - name: create-postgres
      daemon: true
      container:
        image: postgres
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - exec pg_isready -h 127.0.0.1 -p 5432
```

error : 
```
task 'full-wsc86.create-postgres' errored: container "main" in template "create-postgres", does not have the command specified: when using the emissary executor you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary
```

```yaml
 arguments:
    parameters:
    - name: postgres-ip
      value: "{{tasks.create-postgres.ip}}"
```

In this next step, the sql ip address was taken.
As you can see, I want a postgresql  ip address.
Please give me some ideas.
