### DISCUSSION TITLE
[archived] "Resource Template" docs discussion

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#9453] [General]
# argo-workflows/walk-through/kubernetes-resources/

https://argoproj.github.io/argo-workflows/walk-through/kubernetes-resources/

**Comment by b-luu** [comment]
Is it possible to pass the manifest via an input artifact?

**Reply by terrytangyuan** [reply]
Yes, use `manifestFrom` instead of `manifest`.

**Reply by ONGmartino** [reply]
@terrytangyuan could you please provide an example?

**Reply by ciiiii** [reply]
@ONGmartino FYI
```yaml
- name: apply
  inputs:
   artifacts:
   - name: manifest
     path: /tmp/manifest    
  resource:
    action: apply
    manifestFrom:
      artifact:
        name: manifest
```

**Comment by mikekantzer-drizly** [comment]
Is it possible to get the generated name of a resource?

**Reply by mikekantzer-drizly** [reply]
Never mind: just saw the link to https://github.com/argoproj/argo-workflows/blob/83501a46fed675e9d41905560d450e4a821618a1/examples/k8s-jobs.yaml#L44-L50

**Reply by ShantanuKumar** [reply]
Running these kubectl command gives me error about `sh` not found on the $PATH.

**Comment by robingedda** [comment]
Is it possible to access input artifacts from created resources? I'm creating a spark job and would like to access the input artifact instead writing code to download it from s3

**Reply by agilgur5** [reply]
It works like any other template, so you do have access to [Workflow Variables](https://argoproj.github.io/argo-workflows/variables/).

**Comment by ebuildy** [comment]
What about the crucial information => Which service-account is used here?

**Reply by agilgur5** [reply]
Same as other template types, whichever SA you've assigned to the template or Workflow. So make sure your SA has proper RBAC for your resource's `kind` and `action`

**Comment by KingsonKai** [comment]
how to use complex condition in the successCondition, like below, it can't work
```yaml
      resource:
        action: create
        failureCondition: status.status == failed
        successCondition: status.phase == recover && status.status == success
```

**Reply by KingsonKai** [reply]
I have get my answer:
```yaml
      resource:
        action: create
        failureCondition: status.status == failed
        successCondition: status.phase == recover,status.status == success
```

**Comment by yingzhe-qu** [comment]
is it possible to  get the outputs artifacts , eg  manifest contents is  tfjob

**Reply by yingzhe-qu** [reply]
```yaml
  - name: train
    outputs:
      artifacts:
        - name: step4-code
          path: /usr/local/code
    resource: 
      action: create
      setOwnerReference: true
      failureCondition: status.replicaStatuses.Worker.failed > 0
      successCondition: status.replicaStatuses.Worker.succeeded = 2
      manifest: |
        apiVersion: kubeflow.org/v1
        kind: TFJob
        metadata:
          name: tfjob-enti-test1
          namespace: kubeflow
        spec:
          tfReplicaSpecs:
          # ...
```
and then ,
i can not get the outputs artifacts  step4-code
