### DISCUSSION TITLE
Way to decrease total execution time of a job?

### DISCUSSION THREAD

**Discussion by simper66** [argoproj/argo-workflows#9473] [Q&A]
Hi,

Is there any tip to decrease the total execution time of a Job?

For a job that does "nothing" it use to last 10s. 

Around 3s before my code starts and 7s after my code ends.

I have been playing in the controller with things like `CRON_SYNC_PERIOD = 1s`, `imagePullPolicy= IfNotPresent`, etc, but seems to not help.

Any advise?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
        - name: workflow-controller
          image: quay.io/argoproj/workflow-controller:v3.3.9
          command:
            - workflow-controller
          args:
            - '--configmap'
            - workflow-controller-configmap
            - '--executor-image'
            - quay.io/argoproj/argoexec:v3.3.9
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - containerPort: 6060
              protocol: TCP
          env:
            - name: LEADER_ELECTION_IDENTITY
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            **- name: CRON_SYNC_PERIOD
              value: 1s
            - name: DEFAULT_REQUEUE_TIME
              value: 1s**
          resources: {}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6060
              scheme: HTTP
            initialDelaySeconds: 90
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          **imagePullPolicy: IfNotPresent**
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: argo
      serviceAccount: argo
      securityContext:
        runAsNonRoot: true
      schedulerName: default-scheduler
      priorityClassName: workflow-controller
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

```
LAST SEEN   TYPE     REASON                  OBJECT                          SUBOBJECT                   SOURCE                                                               MESSAGE                 
15s         Normal   WorkflowRunning         workflow/nrt-argo-cowsayzkl7d                               workflow-controller                                                  Workflow Running                                                                                        15s          1       nrt-argo-cowsayzkl7d.17103bd1ada49b3e
14s         Normal   Scheduled               pod/nrt-argo-cowsayzkl7d                                    default-scheduler, default-scheduler-control-plane-c897df54b-bx9mm   Successfully assigned nrt-argo/nrt-argo-cowsayzkl7d to edc-nrt-platform-k8s-default-75abd5gd6a20488b8   14s          1       nrt-argo-cowsayzkl7d.17103bd1b0c0ab02
14s         Normal   Pulled                  pod/nrt-argo-cowsayzkl7d        spec.initContainers{init}   kubelet, edc-nrt-platform-k8s-default-75abd5gd6a20488b8              Container image "quay.io/argoproj/argoexec:v3.3.9" already present on machine                           14s          1       nrt-argo-cowsayzkl7d.17103bd1e3d449c7
14s         Normal   Created                 pod/nrt-argo-cowsayzkl7d        spec.initContainers{init}   kubelet, edc-nrt-platform-k8s-default-75abd5gd6a20488b8              Created container init                                                                                  14s          1       nrt-argo-cowsayzkl7d.17103bd1e5dbc878
14s         Normal   Started                 pod/nrt-argo-cowsayzkl7d        spec.initContainers{init}   kubelet, edc-nrt-platform-k8s-default-75abd5gd6a20488b8              Started container init                                                                                  14s          1       nrt-argo-cowsayzkl7d.17103bd1eb603663
13s         Normal   Pulled                  pod/nrt-argo-cowsayzkl7d        spec.containers{wait}       kubelet, edc-nrt-platform-k8s-default-75abd5gd6a20488b8              Container image "quay.io/argoproj/argoexec:v3.3.9" already present on machine                           13s          1       nrt-argo-cowsayzkl7d.17103bd22f1619b8
13s         Normal   Started                 pod/nrt-argo-cowsayzkl7d        spec.containers{main}       kubelet, edc-nrt-platform-k8s-default-75abd5gd6a20488b8              Started container main                                                                                  13s          1       nrt-argo-cowsayzkl7d.17103bd23ccfe0f2
13s         Normal   Started                 pod/nrt-argo-cowsayzkl7d        spec.containers{wait}       kubelet, edc-nrt-platform-k8s-default-75abd5gd6a20488b8              Started container wait                                                                                  13s          1       nrt-argo-cowsayzkl7d.17103bd235fe6d69
13s         Normal   Pulled                  pod/nrt-argo-cowsayzkl7d        spec.containers{main}       kubelet, edc-nrt-platform-k8s-default-75abd5gd6a20488b8              Container image "qa.tf-hyr.wer.qw2ed/nrt-test/job-cowsay:latest" already present on machine             13s          1       nrt-argo-cowsayzkl7d.17103bd2360a729c
13s         Normal   Created                 pod/nrt-argo-cowsayzkl7d        spec.containers{main}       kubelet, edc-nrt-platform-k8s-default-75abd5gd6a20488b8              Created container main                                                                                  13s          1       nrt-argo-cowsayzkl7d.17103bd237eb188b
13s         Normal   Created                 pod/nrt-argo-cowsayzkl7d        spec.containers{wait}       kubelet, edc-nrt-platform-k8s-default-75abd5gd6a20488b8              Created container wait                                                                                  13s          1       nrt-argo-cowsayzkl7d.17103bd23142bdc9
12s         Normal   WorkflowNodeRunning     workflow/nrt-argo-cowsayzkl7d                               workflow-controller                                                  Running node nrt-argo-cowsayzkl7d                                                                       12s          1       nrt-argo-cowsayzkl7d.17103bd2797a0478
5s          Normal   WorkflowNodeSucceeded   workflow/nrt-argo-cowsayzkl7d                               workflow-controller                                                  Succeeded node nrt-argo-cowsayzkl7d                                                                     5s           1       nrt-argo-cowsayzkl7d.17103bd368f2251f
5s          Normal   WorkflowSucceeded       workflow/nrt-argo-cowsayzkl7d                               workflow-controller                                                  Workflow completed                                                                                      5s           1       nrt-argo-cowsayzkl7d.17103bd367f3f1c7
```

The biggest problem is the 7s between my code ends and argo see it as completed
