### DISCUSSION TITLE
en/latest/walk-through/output-parameters/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#9476] [General]
# en/latest/walk-through/output-parameters/

https://argo-workflows.readthedocs.io/en/latest/walk-through/output-parameters/

**Comment by hxlee309** [comment]
I am getting the following error for submitting this workflow, any help would be appreciated

```
Name:                output-parameter-bm5vq
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Failed
Message:             child 'output-parameter-bm5vq-3466363855' failed
Conditions:          
 PodRunning          False
 Completed           True
Created:             Wed Aug 31 00:54:19 -0700 (20 seconds ago)
Started:             Wed Aug 31 00:54:19 -0700 (20 seconds ago)
Finished:            Wed Aug 31 00:54:39 -0700 (now)
Duration:            20 seconds
Progress:            0/1
ResourcesDuration:   4s*(1 cpu),4s*(100Mi memory)

STEP                       TEMPLATE          PODNAME                            DURATION  MESSAGE
 ✖ output-parameter-bm5vq  output-parameter                                               child 'output-parameter-bm5vq-3466363855' failed                                                                                                                                            
 └───⚠ generate-parameter  whalesay          output-parameter-bm5vq-3466363855  5s        Error (exit code 1): pods "output-parameter-bm5vq-3466363855" is forbidden: User "system:serviceaccount:argo:default" cannot patch resource "pods" in API group "" in the namespace "argo"  

This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
```

**Reply by jatinkumarg** [reply]
Follow [this](https://argoproj.github.io/argo-workflows/service-accounts/) and run below to setup rolebinding:

```
kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=argo:default -n argo
```

**Reply by hxlee309** [reply]
Thank you, it works!

**Reply by ehonsey** [reply]
A more secure way to do that is 
```sh
argo submit -n argo --watch https://raw.githubusercontent.com/argoproj/argo-workflows/main/examples/hello-world.yaml --serviceaccount argo
```

**Reply by ehonsey** [reply]
The above is meant to say use the `--serviceaccount argo` flag when submitting workflows

**Reply by ehonsey** [reply]
Never mind, I gave the line from @jatinkumarg more than a passing glance. Setting the argo namespace to the default admin role of the cluster is a persistent solution. Note that `argo` CLI commands may give a false impression of the service account used in the workflow, e.g. `ServiceAccount: unset (will run with the default ServiceAccount)`

**Reply by agilgur5** [reply]
For the minimal RBAC needed for Workflow pods, see https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/

**Comment by alramdein** [comment]
What if the value of the parameter is an object? How to automatically mapping all the fields in the object? 
```yaml
inputs:
   parameters:
      - name: message
      - value: {
              name: "Alif",
              age: "2"
         }
```
How to access it like this?
```
{{inputs.paramters.message.name}}
```
Because originally it will generate error

**Reply by OneCricketeer** [reply]
Haven't tried these, but some options

1) YAML hash

```yml
- value:
     name: "Alif"
     age: "2"
```

2) encode a JSON string since it'll be passed as stdin plaintext to your downstream process (then parse it there)

```yml
- value: "{\"name\": \"Alif\", \"age\": \"2\"}"
```

3) Use parameters for both `name` and `age` rather than `message`

**Reply by agilgur5** [reply]
2 and 3 would both work

**Comment by d-scott-mmath** [comment]
Hi,

Is there a simple way to save all parameters in workflow.parameters into a txt file for audit purposes?

**Reply by agilgur5** [reply]
They should be saved on the Workflow resource itself. If you use Archived Workflows, then they should be saved in the archive DB. I believe that should suffice for audit purposes.

You could write a script to extract just the parameters.

**Comment by munir131** [comment]
I am getting below error when running workflow using above template
```
output-parameter-9bw7w-77skb-whalesay-3372222235: time="2023-08-24T07:02:00 UTC" level=error msg="executor error: pods \"output-parameter-9bw7w-77skb-whalesay-3372222235\" is forbid
den: User \"system:serviceaccount:argo:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"argo\""
```

**Reply by shivani446** [reply]
Did u made a service account which has enough permissions?
@munir131

**Reply by agilgur5** [reply]
There is a page in the docs on [Workflow RBAC](https://argoproj.github.io/argo-workflows/workflow-rbac/).
If your Workflow Pods (which is where the Executor runs) don't have `create` and `patch` RBAC on `workflowtaskresults`, then the Executor will fallback to try `patch` on `pods`.

In this case, both failed and hence the error message, which says what RBAC is needed. The fallback should also be mentioned in the logs just above this message.

**Reply by munir131** [reply]
Sorry for late update. It was permission issue for that service account. I solved that but forgot to mention the update here.

**Comment by phoebelilius** [comment]
Is there a way to pass secrets between two steps? For example, step 1 creates an user with password and step 2 sends it to the end user. How would you pass the password between the two steps without exposing it?

**Reply by agilgur5** [reply]
The recommended way [to use secrets](https://argoproj.github.io/argo-workflows/walk-through/secrets/) is to use the k8s Secret resource.

You could have step 1 create a new k8s Secret and then step 2 mounts that Secret or uses it as an environment variable.

**Reply by hesse-nina** [reply]
Hi, @agilgur5 is this still the recommended path? Or is there some way to secure pass the credentials directly to the next step?

**Comment by egondragon** [comment]
I have an tricky use case with outputs: 

I am using a argo manifest with a sparkoperator section, and a json in the raw form to submit a simple python script as a task

In this Python file I launch, can I access the outputs parameters files ?

I mean can I write in the /tmp/response.txt from my prog.py, or is outputs an argo concept ?

========================================================================
find here the argo manifest template section:

```yaml
    - name: spark-main-app-template
      inputs:
        parameters:
          - name: my-user
          - name: my-password
          - name: my-namespace
          - name: my-app-name
        artifacts:
          - name: sparkapp
            path: /tmp/spark-app.json
            raw:
              data: |
                {
                  "apiVersion": "sparkoperator.k8s.io/v1beta2",
                  "kind": "SparkApplication",
                  "metadata": {
                    "name": "my-main-python",
                    "namespace": "ns2023"
                  },
                  "spec": {
                    "type": "Python",
                    "mode": "cluster",
                    "image": "repo-0.repos.corp.com/my-user/my-img:0.0",
                    "imagePullSecrets": "docker-secret"
                    "imagePullPolicy": "Always",
                    "mainApplicationFile": "local:///opt/spark/workdir/scripts/prog.py",
                    "sparkVersion": "3.4",
                    "restartPolicy": {
                      "type": "Never"
                    },
                    "driver": {
                      "cores": 1,
                      "coreLimit": "1200m",
                      "memory": "512m",
                      "labels": {
                        "version": "3.4"
                      },
                      "env": [
                        {
                          "name": "AWS_ACCESS_KEY_ID",
                          "valueFrom": {
                            "secretKeyRef": {
                              "name": "secret-s3",
                              "key": "aws-access-key-id"
                            }
                          }
                        },
                        {
                          "name": "AWS_SECRET_ACCESS_KEY",
                          "valueFrom": {
                            "secretKeyRef": {
                              "name": "secret-s3",
                              "key": "aws-secret-access-key"
                            }
                          }
                        }
                      ]
                    },
                    "executor": {
                      "cores": 1,
                      "coreLimit": "1200m",
                      "instances": 1,
                      "memory": "512m",
                      "labels": {
                        "version": "3.4"
                      },
                      "env": [
                        {
                          "name": "AWS_ACCESS_KEY_ID",
                          "valueFrom": {
                            "secretKeyRef": {
                              "name": "secret-s3",
                              "key": "aws-access-key-id"
                            }
                          }
                        },
                        {
                          "name": "AWS_SECRET_ACCESS_KEY",
                          "valueFrom": {
                            "secretKeyRef": {
                              "name": "secret-s3",
                              "key": "aws-secret-access-key"
                            }
                          }
                        }
                      ]
                    },
                    "arguments": [
                      "> /tmp/resp_status_code.txt"
                    ],
                    "hadoopConf": {
                      "fs.s3a.endpoint": "s3.endpoint.mycorp.com",
                      "fs.defaultFS": "s3a://my-bucket"
                    },
                    "sparkConf": {
                      "spark.ui.view.acls": "acl0"
                    }
                  }
                }
      outputs:
          parameters:
              - name: response-http-status-code
                valueFrom:
                  path: /tmp/response_status_code.txt
      container:
        image: repo.repos.mycorp.com/submit-spark-app-image:1.1.0
        command:
          - python3
```

**Reply by agilgur5** [reply]
You can use [Argo variables](https://argoproj.github.io/argo-workflows/variables/) to access output parameters.
One thing to note is that in-line Python scripts specifically may need some formatting efforts as per https://github.com/argoproj/argo-workflows/issues/11131#issuecomment-1720141570. This may not apply to you though since you're using a single parameter and not an in-line script.

Personally, I've just used a [resource template](https://argoproj.github.io/argo-workflows/walk-through/kubernetes-resources/) to submit `SparkApplications` in the same cluster.

**Reply by egondragon** [reply]
Ok, that's an idea, but how can I use resource template to submit a Python script ?
This Python script also needs some AWS keys to execute, how can I pass it this informations.
Any example would be great.

**Reply by agilgur5** [reply]
Your Python script with AWS keys is inside of the `SparkApplication` so that would work as is.

Otherwise you'd either use a container template or a script template for a regular script, not a resource template. You can pass keys [through Secrets in Argo](https://argoproj.github.io/argo-workflows/walk-through/secrets/), same as any other k8s container.

**Comment by manju-rn** [comment]
How to retrieve ENV values from container as Output params?
Say the Image has ENV values and some defaults are already set. How can I retrieve in the Output params?

**Reply by agilgur5** [reply]
Your container step would have to output them somewhere. Either to a file or stdout for example. Then they can be used as output parameters.

**Reply by manju-rn** [reply]
Thanks. Another linked question to this - Can we not access the path / file from the base image?
I have created an issue <https://github.com/argoproj/argo-workflows/issues/12418>

**Reply by agilgur5** [reply]
I'll take a look and respond there.

**Reply by manju-rn** [reply]
thanks for your response, believe you closed that. However, just 1 last question to clarify my doubts
You indicated that the /config/configuration file is not present in the image. Yes, however, the the configuration.yaml with the defaults gets created when the container starts. The point now is when i give the image in workflow, does argo workflow not run the container? 
```yaml
spec:
  templates:
  - name: ha-container
    container:
      image: homeassistant/home-assistant:latest
```
