### DISCUSSION TITLE
${metadata.name} not substituted in links

### DISCUSSION THREAD

**Discussion by bkanuka** [argoproj/argo-workflows#9653] [Q&A]
I have the following `workflow-controller-configmap`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  links: |
    # Adds a button next to the pod.  E.g. linking to you logging facility but for the pod only.
    - name: Try getting logs directly from GCP
      scope: pod-logs
      url: https://console.cloud.google.com/kubernetes/pod/[region]/[project]/${metadata.namespace}/${metadata.name}/logs?project=[project]
```
The `[region]` and `[project]` are filled in with my actual (unchanging) values.

However, the link in the UI for pod logs is always:
`https://console.cloud.google.com/kubernetes/pod/[region]/[project]/$%7Bmetadata.namespace%7D/$%7Bmetadata.name%7D/logs?project=[project]` 

This link obviously doesn't work - so I'm a bit at a loss.  I suspect this is a bug, but I don't currently have the time to reproduce on a clean install :(
