### DISCUSSION TITLE
Accessing single file form git artifact to apply Kubernetes resource

### DISCUSSION THREAD

**Discussion by adammw** [argoproj/argo-workflows#9703] [Q&A]
Hi,

I'm looking to have a workflow pull a single file from a private git repository then apply it to the Kubernetes cluster, however git artifacts appear to only be able to pull the entire git repo, and the resource template step only allows a single artifact name as input.

I have tried something like the following but keep getting an error that the templates.main.inputs.artifacts.manifest was not supplied when trying to create the workflow.

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
spec:
  arguments:
    parameters:
      - name: branch
        value: master
      - name: cluster
        value: sandbox
      - name: name
        value: api
  entrypoint: main
  templates:
    - name: main
      inputs:
        artifacts:
          # Check out the master branch of the argo repo and place it at /src
          # revision can be anything that git checkout accepts: branch, commit, tag, etc.
          - name: repo
            path: /src
            git:
              repo: https://github.com/foo/bar.git
              revision: "{{workflow.parameters.branch}}"
              usernameSecret:
                name: github-pat
                key: username
              passwordSecret:
                name: github-pat
                key: token
          - name: manifest
            path: >
              /src/generated/{{workflow.parameters.cluster}}/{{workflow.parameters.name}}.yml
            archive:
              none: {}
        parameters:
          - name: branch
          - name: cluster
          - name: name
      resource:
        action: apply
        manifestFrom:
          artifact:
            name:manifest
```

**Comment by pitwegner** [comment]
I solved this using an additional step. Not beautiful but works. The reason why e.g. subpath doesn't work is that the [method is not implemented](https://github.com/argoproj/argo-workflows/blob/6f76934c3210724ea1081efdd5d15f1447d13797/pkg/apis/workflow/v1alpha1/workflow_types.go#L2425).
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  entrypoint: main
  templates:
  - name: get-manifest
    inputs:
      artifacts:
      - name: git
        path: /git
    container:
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args: ["echo 'Useless step.'"]
    outputs:
      artifacts:
      - name: manifest
        path: "/git/manifest.yaml"
  - name: apply-manifest
    inputs:
      artifacts:
      - name: manifest
        path: /manifest.yaml
    resource:
      action: create
      manifestFrom:
        artifact:
          name: manifest
  - name: main
    inputs:
      artifacts:
      - name: "git"
        git:
          repo: "https://github.com/foo/bar.git"
          revision: "somerev"
          usernameSecret:
            name: git-secret
            key: username
          passwordSecret:
            name: git-secret
            key: password
    steps:
    - - name: get-manifest
        template: get-manifest
        arguments:
          artifacts:
            - name: git
              from: "{{inputs.artifacts.git}}"
    - - name: apply-manifest
        template: apply-manifest
        arguments:
          artifacts:
            - name: manifest
              from: "{{steps.get-manifest.outputs.artifacts.manifest}}"
            - name: git
              from: "{{inputs.artifacts.git}}"
```
