### DISCUSSION TITLE
Question: how can I populate this field?

### DISCUSSION THREAD

**Discussion by ls84** [argoproj/argo-workflows#9707] [Q&A] [answered]
I suppose this field is what we get from stdout? but when I tested, nothing shows up.

![Screen Shot 2022-09-29 at 11 58 36](https://user-images.githubusercontent.com/7627744/192935794-95b86010-c011-49d7-a8b5-a9640518bf91.png)

here is my workflow spec:
```
spec:
  templates:
    - name: test
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: docker/whalesay:latest
        command:
          - sh
          - '-c'
        args:
          - echo -n hello world
        resources: {}
      serviceAccountName: workflow-dev
  entrypoint: test
  arguments: {}
```
