### DISCUSSION TITLE
VolumeClaimTemplate - configurable Size

### DISCUSSION THREAD

**Discussion by fhochleitner** [argoproj/argo-workflows#9738] [Q&A] [answered]
Hi all, 

I have a quick question: is there any possibility to make the size of a `volumeClaimTemplate` configurable via parameters? 

e.g. if we have the following ClusterWorkflowTemplate: 
```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: workflow-snippet
spec:
  arguments:
    parameters:
      - name: workspaceSize
        default: 1Gi <-- this would be nice if it would work with the option to override from calling template. 
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: "{{ inputs.parameters.workspaceSize }}"
        storageClassName: your-SC-here 
```

the regex matcher complains due to `"` getting added around the value. Use case is the following: we are providing standard workflows to different projects and teams for handling all their build and deployment needs. Some projects require a bigger workspace than others but due to limitations on our customers clusters we don't want to extend workspace size for all projects to e.g. 10Gi. 

any help would be appreciated. thank you 

edit: formatting
