### DISCUSSION TITLE
sso rbac-rule on subject (user name)

### DISCUSSION THREAD

**Discussion by bbusioc** [argoproj/argo-workflows#9747] [Q&A] [answered]
Hello,

I'm trying to test SSO RBAC Namespace Delegation, but instead of configuring an rbac rule on a group, I would like to create it on subject, so it will apply for a single user.

I'm installing argo workflows using the helm charts, with a quite basic custom values file:
```yaml
server:
  ingress:
    enabled: true
    hosts:
      - myhost.mydomain
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: myhost.mydomain-tls
        hosts:
          - myhost.mydomain

  sso:
    enabled: true
    issuer: "https://myIDP"
    clientId:
      name: "client-id-secret"
      key: "client-id-key"
    clientSecret:
      name: "client-secret-secret"
      key: "client-secret-key"
    redirectUrl: "https://myhost.mydomain/oauth2/callback"
    rbac:
      enabled: true
      secretWhitelist: []
    scopes:
    - sub

  extraEnv:
    - name: SSO_DELEGATE_RBAC_TO_NAMESPACE
      value: "true"

  extraArgs:
    - --auth-mode=sso
```

I have configured a default login service account in argo namespace like:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-default-login
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
```

and a service account in the namespace where I want to restrict access like:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-namespace-read-write-user
  namespace: my-namespace
  annotations:
    workflows.argoproj.io/rbac-rule: "'myusername' in sub"
    workflows.argoproj.io/rbac-rule-precedence: "1"
```

But the rbac rule doesn't seem to be evaluated, in the pod server logs I can see:
```
time="2022-10-04T11:44:30.859Z" level=info msg="selected SSO RBAC service account for user" email= loginServiceAccount=user-default-login serviceAccount=user-default-login ssoDelegated=false ssoDelegationAllowed=false subject=myusername
```

To quickly test that it's a problem with the rbac rule, I just changed the service account from the target namespace like:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-namespace-read-write-user
  namespace: my-namespace
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "1"
```

This time in the logs I can see:
```
time="2022-10-04T11:49:04.172Z" level=info msg="selected SSO RBAC service account for user" email= loginServiceAccount=user-default-login serviceAccount=data-processing-test-ns-read-write-user ssoDelegated=true ssoDelegationAllowed=true subject=myusername
```

I would like to test rbac rules based on the user name/subject because for the moment the OIDC that we are using does not have group information.
In order to progress we were thinking to create a machine account per project (namespace) and all the users in that project to use it.
I know it's not an ideal use case, but we are forced to use that OIDC provider and they don't have yet an estimation date when groups will be added.

So my question is: why rbac rules are not working on subject? is my rule not correctly written? rbac rules are supposed to work only with groups? am I missing some configuration?

Any suggestion/idea would be highly appreciated.

Thanks,
Bogdan
