### DISCUSSION TITLE
Argo workflow When condition:  Cannot transition token types

### DISCUSSION THREAD

**Discussion by sharadhirao** [argoproj/argo-workflows#9754] [Q&A]
Hi Team, 
I was looking into dag conditional flow. I have a requirement that, i should have regular expression in when. 

You can recreate the issue using this file:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-conditional-parameter-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      Conditional parameters provide a way to choose the output parameters based on expression.

      In this example DAG template has two task which will run conditionally based on `when`.

      Based on this condition one of task may not execute. The template's output parameter will be set to the
      executed taks's output result.
    workflows.argoproj.io/version: '>= 3.1.0'
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: flip-coin
            template: flip-coin
            
          - name: heads
            dependencies: [flip-coin]
            template: heads
            when: "{{tasks.flip-coin.outputs.result}} =~ '^Passed'"


          - name: tails
            dependencies: [flip-coin]
            template: tails
            when: "{{tasks.flip-coin.outputs.result}} == Failed"
    
    - name: flip-coin
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          print("Passed in project level but Skipped:  sonarqube")
   
    - name: heads
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          print("heads")
    
    - name: tails
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          print("tails")
```

When I run this workflow i am getting error as:

```
Invalid 'when' expression 'Passed in project level but Skipped: sonarqube =~ '^Passed'': Cannot transition token types from VARIABLE [project] to VARIABLE [level]
```

I want to run workflow when anything started with passed is printed. 

Can please anyone look into this and provide solution? Its urgent
