### DISCUSSION TITLE
Change stage color for warnings

### DISCUSSION THREAD

**Discussion by sharadhirao** [argoproj/argo-workflows#9765] [Q&A]
Hi Team, 

I have a requirement that whenever we have output as passed/failed/warning, the argo step color should change. 
Like say some test passed with warnings, argo workflows should change color of stage output or the name of the next step.
As for developers, they need to login and see logs, I thought of this approach.

Is this possible in argo-workflows?
Any help would be appreciated, thanks.

**Comment by sharadhirao** [comment]
Hi Team, 
Any suggestion on this?
Or Can I change the dag task name according to previous step output?
@alexec @whynowy 

Thanks in advance.

**Reply by sharadhirao** [reply]
I want to implement something like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: stage-name-check-
  labels:
    workflows.argoproj.io/test: "true"
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: flip-coin
            template: flip-coin

          - name: {{tasks.flip-coin.outputs.result}}
            dependencies: [flip-coin]
            template: heads
            when: "{{tasks.flip-coin.outputs.result}} == heads"

          - name: tails
            dependencies: [flip-coin]
            template: tails
    
    - name: flip-coin
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          print("heads")
   
    - name: heads
      inputs:
        parameters:
          - name: message
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          print("heads")
    
    - name: tails
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          print("tails")
```

I know this will show error as task name should be string. But I am looking something like this. Changing stage name according to output.
@alexec any help in this would be helpful on this? 

Thanks in advance
