### DISCUSSION TITLE
How to deal with datetime format?

### DISCUSSION THREAD

**Discussion by Tan-JiaLiang** [argoproj/argo-workflows#9856] [Q&A]
the cron workflow demo
```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: print-date
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: alpine:3.6
          command: [sh, -c]
          args: ["echo '{{workflow.scheduledTime}}'"]
```
the demo result
```text
print-date-1666093560: 2022-10-18T11:46:00Z
print-date-1666093560: time="2022-10-18T11:46:02.858Z" level=info msg="sub-process exited" argo=true error="<nil>"
```

Hi guys,
I wanted to print the {{workflow.scheduledTime}} with datetime format. For example, like "2022-10-18 11:46:00" or only it's day like "18" or it's hour like "11". For another, I wanted to print the {{workflow.scheduledTime}} - 1h time, can argo workflow has some tips to do that? like the [dolphinscheduler](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/parameter/built-in.html).

It is very useful in ETL scene, for example, i statistics a partition table's row count every day, like this
```sql
SELECT COUNT(*) 
FROM student 
WHERE dt='{{=toDay(modifyTime(workflow.scheduledTime, "-1d"))}}' AND '{{=toHour(modifyTime(workflow.scheduledTime, "-1d"))}}';
```
it automic to replace the time in date format when workflow schedule, like this
```sql
SELECT COUNT(*) 
FROM student 
WHERE dt='18' and hr='11';
```
