### DISCUSSION TITLE
Issues in exit-handler

### DISCUSSION THREAD

**Discussion by yay14** [argoproj/argo-workflows#9881] [Q&A]
So, my use case is to capture failures in argo-workflows and identify how many of those were actually because of a pod/step failure and how many were false alarms (someone suspends/stops workflow from UI, or eg we have a step in argo which calls the argo stop API to cancel stale executions for a commit etc). So, these failures are not the actual failures.

Solution:
1. If there are hooks in argo which run when argo stop/terminate is called (which gives a message "Shutdown with strategy: stop"), can utilize those to update metrics. From my understanding exit-handler solves the purpose stand-alone.
2. But I am not able to extract the failure information neatly i.e failures are filtered but in success cases, I get an error saying {{workflow.failures}} is nil.
3. Also when I try to set the failure through a template which is called from exit-handler, I am not able to do the same also.

Can someone please help me around these issues, if I am missing something. Posting sample code for better context.
```

    - name: exit-handler
      steps:
        - - name: post-failure-message
            template: post-failure-message
            when: '[[workflow.status]] != Succeeded'
        - - name: post-github-comment
            templateRef:
              name: '{{ .Values.templateReference.common.postGithubComment }}'
              template: post-github-comment
              clusterScope: false
            arguments:
              parameters:
                - name: commit_id
                  value: '[[workflow.parameters.commit_id]]'
                - name: repository_name
                  value: '[[workflow.parameters.repository_name]]'
                - name: pr_number
                  value: '[[workflow.outputs.parameters.pr_number]]'
      outputs:
        parameters:
          - name: error
            valueFrom:
              expression: "jsonpath([[ workflow.failures ]],'$.message')"
    
    - name: post-failure-message
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          print("Workflow failed", [[ workflow.failures[0].message]])
      outputs:
        parameters:
          - name: error
            valueFrom:
              expression:  "jsonpath([[ workflow.failures ]],'$.message')"
```
