### DISCUSSION TITLE
argo-workflows/retries/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#9923] [General]
# argo-workflows/retries/

https://argoproj.github.io/argo-workflows/retries/

**Comment by tahasharif2000** [comment]
How to access retries variable into the container ? I tried the code https://github.com/argoproj/argo-workflows/blob/master/examples/retry-with-steps.yaml#L24 but it is giving error saying `function "retries" not defined`
Do we need to pass it as parameter into the step or it will be available by itself ?

**Reply by tahasharif2000** [reply]
This got resolved after adding below lines:

```yaml
        inputs:
          parameters:
            - name: retries
              value: "{{`{{retries}}`}}"
```
