### DISCUSSION TITLE
en/latest/configure-archive-logs/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj/argo-workflows#9970] [General]
# en/latest/configure-archive-logs/

https://argo-workflows.readthedocs.io/en/latest/configure-archive-logs/

**Comment by gyanprakash48** [comment]
I set artifact repository as below in `workflow-controller-configmap`, but when trying to run a workflow with  `archiveLogs: true`, it's throwing error `You need to configure artifact storage. More information on how to do this can be found in the docs: https://argoproj.github.io/argo-workflows/configure-artifact-repository/`.  Also tried with creating a config  `artifact-repositories`.  Any suggestion what else i need to do ? 

```yaml
artifactRepository: |
    azure:
      endpoint: https://argodat3o77q.blob.core.windows.net
      container: artifacts
      blob: {{workflow.name}}/{{pod.name}}
      accountKeySecret:
        name: argo-artifcats-storage-credentials
        key: account-access-key
```

**Reply by gyanprakash48** [reply]
@brianloss if you could possibly help ?

**Reply by brianloss** [reply]
@gyanprakash48 Have you verified you're using at least v3.4.0, and also that your `accountKeySecret` exists? It looks like what you pasted shows `argo-artifcats-storage-credentials`. Note that it says `artifcats` and not `artifacts`.

**Reply by gyanprakash48** [reply]
@brianloss , thanks for response. Yes i am using  v3.4.3 . Yes i see  , i spell incorrectly, but everwhere. So credentilas does exists. I  also tried with `useSDKCreds: true` but still same error

**Reply by gyanprakash48** [reply]
i also tried alternative approach, but still same situation

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: argo
  annotations:
    workflows.argoproj.io/default-artifact-repository: log-artifact-repository
data:
  log-artifact-repository: |
    archiveLogs: true
    azure:
      endpoint: https://argodat3o77q.blob.core.windows.net
      container: artifacts
      blob: logs
      useSDKCreds: true
```

**Reply by brianloss** [reply]
@gyanprakash48 Oh, I see now. There are a couple problems... First, you've defined `blob` in your artifact repository. That is for individual artifacts, and not an artifact repository. If you're trying to override how artifacts are placed in the container, you want `blobNameFormat` instead (see https://argoproj.github.io/argo-workflows/fields/#azureartifactrepository). Second, the value of that key needs to be quoted. That is, you need `blobNameFormat: "{{workflow.name}}/{{pod.name}}"` and not `blobNameFormat: {{workflow.name}}/{{pod.name}}`.

If you're defining the configmap artifact-repositories, you'll need an annotation to specify which is default, or use an artifactRepositoryRef in your workflow. Have a look at https://argoproj.github.io/argo-workflows/artifact-repository-ref/.

Aside from that, you can have a look at the pod logs for the workflow. Check logs for all of the containers in the pod. You should get a more specific error message in there somewhere.

**Reply by gyanprakash48** [reply]
Many thanks for helping out. I tried all these things. Just to follow your instruction, i did fresh test again
1. Dropped  configmap `artifact-repositories`
2. update artifact repository in `workflow-controller-configmap` as below (i corrected spell issue in my secret and recreatded):

```yaml
artifactRepository: |
    archiveLogs: true
    azure:
      endpoint: https://argodat3o77q.blob.core.windows.net
      container: artifacts
      blobNameFormat: "{{workflow.name}}/{{pod.name}}"
      accountKeySecret:
       name: argo-artifacts-storage-credentials
       key: account-access-key
```

3. refreshed workflow controller deployement  but still no luck and stuck with same error 

5. Pod i am running is a hello world and its logs says all good:
```
time="2022-11-07T17:22:31.230Z" level=info msg="capturing logs" argo=true
 _____________
< hello world >
 -------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
time="2022-11-07T17:22:32.235Z" level=info msg="sub-process exited" argo=true error="<nil>"
````

6. workflow controller logs message says what i  have reported in first place, same is appering in UI

```
time="2022-11-07T17:22:45.230Z" level=info msg="Processing workflow" namespace=argo workflow=test-archive-log-2-tkb4r
time="2022-11-07T17:22:45.230Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=test-archive-log-2-tkb4r
time="2022-11-07T17:22:45.230Z" level=info msg="node changed" namespace=argo new.message="Error (exit code 1): You need to configure artifact storage. More information on how to do this can be found in the docs: https://argoproj.github.io/argo-workflows/configure-artifact-repository/" new.phase=Error new.progress=0/1 nodeID=test-archive-log-2-tkb4r old.message= old.phase=Running old.progress=0/1 workflow=test-archive-log-2-tkb4r
time="2022-11-07T17:22:45.231Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=test-archive-log-2-tkb4r
time="2022-11-07T17:22:45.231Z" level=info msg=reconcileAgentPod namespace=argo workflow=test-archive-log-2-tkb4r
```

@brianloss

**Reply by gyanprakash48** [reply]
Anything else that should i watch in my setup ? @brianloss  , many thanks in advance!

**Reply by brianloss** [reply]
@gyanprakash48 Did you install Argo with Helm? There's a known issue where Helm does not handle CRDs reasonably for upgrades, only for initial install. Therefore, if you had installed an Argo version prior to 3.4 with Helm and upgraded to 3.4, you won't actually have the latest CRDs installed. You can try `kubectl apply -f kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-workflows/release-3.4/manifests/base/crds/minimal/argoproj.io_workflowtaskresults.yaml` to apply the new workflowtaskresults CRD, and try again.

**Reply by gyanprakash48** [reply]
no, i did not  install using helm. I am using quick start postgress. I also manually checkd crds  and i could see  azure  segment exists there.  below is snippet from crds

```yaml
azure:
                      properties:
                        accountKeySecret:
                          properties:
                            key:
                              type: string
                            name:
                              type: string
                            optional:
                              type: boolean
                          required:
                          - key
                          type: object
                        blob:
                          type: string
                        container:
                          type: string
                        endpoint:
                          type: string
                        useSDKCreds:
                          type: boolean
                      required:
                      - blob
                      - container
                      - endpoint
                      type: object
                    deleted:
                      type: boolean
```

**Reply by gyanprakash48** [reply]
But i still  appled  crds you mentioned again(`kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-workflows/release-3.4/manifests/base/crds/minimal/argoproj.io_workflowtaskresults.yaml`)
, refresh everything and tried. Still no luck and same error

**Reply by brianloss** [reply]
@gyanprakash48 Did you check the logs for all containers in the pod? In particular, when artifacts are uploaded after a pod is run, that happens in the wait container. I ran your sample locally against Azurite (I do have a slight difference in that I specified the artifact repo configmap and key using an artifact ref, but I have used the configmap before too and that works fine). In my case, the pod that ran was archive-location-5t9dv. If I look at the wait container logs with `kubectl logs archive-location-5t9dv -c wait`, I see the following in there:
```
time="2022-11-07T16:26:01.154Z" level=info msg="No output parameters"
time="2022-11-07T16:26:01.154Z" level=info msg="No output artifacts"
time="2022-11-07T16:26:01.154Z" level=info msg="Saving to Azure Blob Storage" blob=archive-location-5t9dv/archive-location-5t9dv/main.log container=my-container endpoint="http://azurite:10000/azurite"
time="2022-11-07T16:26:01.245Z" level=info msg="Save artifact" artifactName=main-logs duration=91.006875ms error="<nil>" key=archive-location-5t9dv/archive-location-5t9dv/main.log
```
You should see something similar, or an error if uploading fails.

**Reply by gyanprakash48** [reply]
`kubectl logs -n argo test-archive-log-2-xnzbn -c wait` logs output is below 

```
time="2022-11-07T18:01:04.352Z" level=info msg="Starting Workflow Executor" executorType= version=v3.3.9
time="2022-11-07T18:01:04.425Z" level=info msg="Creating a  executor"
time="2022-11-07T18:01:04.425Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-11-07T18:01:04.425Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo podName=test-archive-log-2-xnzbn template="{\"name\":\"whalesay\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"docker/whalesay:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"cowsay hello world | tee /tmp/hello_world.txt\"],\"resources\":{}},\"archiveLocation\":{\"archiveLogs\":true}}" version="&Version{Version:v3.3.9,BuildDate:2022-08-09T23:59:38Z,GitCommit:5db53aa0ca54e51ca69053e1d3272e37064559d7,GitTag:v3.3.9,GitTreeState:clean,GoVersion:go1.17.13,Compiler:gc,Platform:linux/amd64,}"
time="2022-11-07T18:01:04.425Z" level=info msg="Starting deadline monitor"
time="2022-11-07T18:01:06.426Z" level=info msg="Main container completed"
time="2022-11-07T18:01:06.426Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2022-11-07T18:01:06.426Z" level=info msg="Saving logs"
time="2022-11-07T18:01:06.426Z" level=error msg="executor error: You need to configure artifact storage. More information on how to do this can be found in the docs: https://argoproj.github.io/argo-workflows/configure-artifact-repository/"
time="2022-11-07T18:01:06.426Z" level=info msg="No output parameters"
time="2022-11-07T18:01:06.426Z" level=info msg="No output artifacts"
time="2022-11-07T18:01:06.426Z" level=info msg="Killing sidecars []"
time="2022-11-07T18:01:06.426Z" level=info msg="Alloc=5730 TotalAlloc=11564 Sys=23762 NumGC=4 Goroutines=6"
time="2022-11-07T18:01:06.427Z" level=fatal msg="You need to configure artifact storage. More information on how to do this can be found in the docs: https://argoproj.github.io/argo-workflows/configure-artifact-repository/"
```

**Reply by gyanprakash48** [reply]
i noticed you mentioned 'Azurite ' ,  could  this  be reason ?  Azurite is emulator from azure blob?

**Reply by brianloss** [reply]
@gyanprakash48 No, Azurite has no bearing--it's just an emulator that makes it quick to test. I get the same behavior on a regular storage account.
Something is definitely wrong with your setup (I don't think whatever is wrong is azure-specific, either), but I cannot tell you what at this point. I know that the "Executor initialized" line in your log doesn't show the full archive location. For my test, I get this:
```
time="2022-11-07T16:25:52.150Z" level=info msg="Executor initialized" deadline="2022-11-07 16:30:46 +0000 UTC" includeScriptOutput=false namespace=argo podName=archive-location-5t9dv template="{\"name\":\"whalesay\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"docker/whalesay:latest\",\"command\":[\"cowsay\"],\"args\":[\"hello world\"],\"resources\":{}},\"archiveLocation\":{\"archiveLogs\":true,\"azure\":{\"endpoint\":\"http://azurite:10000/azurite\",\"container\":\"my-container\",\"accountKeySecret\":{\"name\":\"azurite-credentials\",\"key\":\"account-access-key\"},\"blob\":\"archive-location-5t9dv/archive-location-5t9dv\"}}}" version="&Version{Version:v3.4.3,BuildDate:2022-10-31T05:42:11Z,GitCommit:eddb1b78407adc72c08b4ed6be8f52f2a1f1316a,GitTag:v3.4.3,GitTreeState:clean,GoVersion:go1.18.7,Compiler:gc,Platform:linux/arm64,}"
```
Note how mine has details about the connection and yours just has the archiveLogs true.

For comparison (though we way you are setting it up should work). I have a configmap called azure-artifact-repositories with the following content:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-artifact-repositories
data:
  azure-v1: |
    archiveLogs: true
    azure:
      endpoint: http://azurite:10000/azurite
      container: my-container
      blobNameFormat: "{{workflow.name}}/{{pod.name}}"
      accountKeySecret:
        name: azurite-credentials
        key: account-access-key
```

Then, the sample workflow I ran was this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: archive-location-
spec:
  artifactRepositoryRef:
    configMap: azure-artifact-repositories
    key: azure-v1
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
    archiveLocation:
      archiveLogs: true
```

**Reply by gyanprakash48** [reply]
ok, i will do a fresh installtaion  and try again. Will keep you posted . Many thank  for all the inputs

**Reply by gyanprakash48** [reply]
@brianloss , A fresh installation indeed working fine. Many thanks. Though i have one last struggle. It is working fine with secrets  , but when i am trying to use managed identitiy  `useSDKCreds: true`, its complaing with below error. (Managed identiy is assigned to aks pool , and overall access does work(we tested it for other task), Any hint what i need to do to fix it .?

Logs 

```
time="2022-11-08T13:32:10.448Z" level=info msg="Save artifact" artifactName=main-logs duration=11.364627ms error="unable to upload file /tmp/argo/outputs/logs/main.log to Azure: ===== INTERNAL ERROR =====\nDefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential: missing environment variable AZURE_TENANT_ID\n\tManagedIdentityCredential: no default identity is assigned to this resource\n\tAzureCLICredential: fork/exec /bin/sh: no such file or directory" key=test-archive-log-2-j462k/test-archive-log-2-j462k/main.log
time="2022-11-08T13:32:10.448Z" level=error msg="executor error: unable to upload file /tmp/argo/outputs/logs/main.log to Azure: ===== INTERNAL ERROR =====\nDefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential: missing environment variable AZURE_TENANT_ID\n\tManagedIdentityCredential: no default identity is assigned to this resource\n\tAzureCLICredential: fork/exec /bin/sh: no such file or directory"
time="2022-11-08T13:32:10.448Z" level=info msg="Deadline monitor stopped"
time="2022-11-08T13:32:10.449Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-11-08T13:32:10.449Z" level=info msg="Alloc=7102 TotalAlloc=12383 Sys=25554 NumGC=3 Goroutines=9"
time="2022-11-08T13:32:10.449Z" level=fatal msg="unable to upload file /tmp/argo/outputs/logs/main.log to Azure: ===== INTERNAL ERROR =====\nDefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential: missing environment variable AZURE_TENANT_ID\n\tManagedIdentityCredential: no default identity is assigned to this resource\n\tAzureCLICredential: fork/exec /bin/sh: no such file or directory"
```

**Reply by brianloss** [reply]
@gyanprakash48 it looks from the error like maybe there are multiple identities assigned to the VM and the go library doesn't know which one to use. You might be able to set the `AZURE_CLIENT_ID` environment variable to the client ID of the managed identity you want it to use and see if that takes care of the issue (see [here](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash#-option-2-use-a-managed-identity)). I've only really tested that by using the AAD Pod Identity add-on for AKS (workload identity federation didn't support managed identities at the time I last tested, but it does now), and it works fine with that (though if you're spinning up tons of tasks, you may hit throttling of all the metadata requests).

**Reply by gyanprakash48** [reply]
yes , indeed! It has more than one identities .Great, Many thanks once again!

**Reply by brianloss** [reply]
Sure, you're welcome!

**Reply by monaka** [reply]
As you might know, AAD Pod Identity is at sunset. You can use Azure Workload Identity instead.
I checked and confirmed workflow-server (v3.4.11) works with Workload Identity.

Additional code to values.yaml is like this:

```yaml
server:
  podLabels:
    azure.workload.identity/use: "true"
  serviceAccount:
    annotations:
      azure.workload.identity/client-id: <<your client-id>>
```

**Reply by Borrelworst** [reply]
Hi Monaka,

I am trying to get it working in a slightly different way, but so far so good. What I have done:

- Created the service account
- Created the federation identity
- It is all linked together

If I try to manually query the storage account from within the pod it works fine. However, if I run the workflow I get the following error:

```
Error (exit code 1): unable to upload file /tmp/argo/outputs/logs/main.log to Azure: ===== INTERNAL ERROR ===== DefaultAzureCredential: failed to acquire a token. Attempted credentials: EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set ManagedIdentityCredential: IMDS token request timed out AzureCLICredential: fork/exec /bin/sh: no such file or directory
```

In the pod, this works fine:
```sh
:$ which /bin/sh
/bin/sh
```

So what is missing?

**Reply by Borrelworst** [reply]
After some debugging, it looks like using workload-identity does not work when AAD Pod Identity is installed as well. When AAD Pod Identity is installed, it takes precedence of workload-identity, causing it to fail. Is there an option to specify what identity type needs to be used ?

**Reply by monaka** [reply]
Workload Identity is a new replacement for AAD Pod Identity.
So I suppose there is no way to make them coexist.

AAD Pod Identity is deprecated. https://github.com/Azure/aad-pod-identity#-announcement
And the AKS Managed add-on also will be deprecated in Sept. 2024.

**Comment by alejoGT1202** [comment]
Hello is there a way I can the path where I would like to save my logs in the s3 bucket?

**Reply by Paritosh-Anand** [reply]
Yes, there is a way to specify prefix path

```
keyFormat: prefix/in/bucket     #optional
```

It is mentioned here as well [s3-compatible-artifact-repository-bucket-such-as-aws-gcs-minio-and-alibaba-cloud-oss](https://argoproj.github.io/argo-workflows/configure-artifact-repository/#s3-compatible-artifact-repository-bucket-such-as-aws-gcs-minio-and-alibaba-cloud-oss)

**Comment by skight-shen** [comment]
I've configured with mysql as the manul. Tables are created in the databases as metioned in the manul. However, it didn't archive the workflow. I'can see any workflow in UI and in the database. Can anyone help? The workflow run in a customized namesapce which is different from the default "argo".  Any suggestions?

**Reply by skight-shen** [reply]
`achive: true` has setted in the config.

**Reply by skight-shen** [reply]
fixed. It mismatched the labels.

**Reply by nicolas-vivot** [reply]
@skight-shen
Can you please give some details about what was wrong and what you have fixed ?
I am in the same situation, did not have a deep look at it yet.

**Reply by nicolas-vivot** [reply]
Got it. There is a default configuration to archive workflows matching label selector. Did not pay attention too.

**Reply by skight-shen** [reply]
It seems to be not stable. Have you met this issue?

**Comment by ericsgagnon** [comment]
Any way to change postgres schema? We're a small group and I prefer to colocate these types of logs. The ability to use a schema like argo would be great.

**Reply by nirdz** [reply]
I agree with the question. It seems that Argo creates the necessary tables under the default "public" scheme and I have not found a way to configure the schema.

**Comment by panicboat** [comment]
Hello.

I would like to see archived workflow logs in the GUI.

When I set it up as following, I get an error with the message `step group deemed errored due to child steps[0].hello1 error: failed to resolve {{steps.name}}` and cannot start the workflow.
For dag, the error message is `task 'artifact-repository-s3-workflow.start' errored: failed to resolve {{tasks.name}}`.

Is there a recommended keyFormat for storing multi-step and DAG logs?

MultiStep
```yaml
data:
  multi-step-repository: |
    s3:
      endpoint: s3.amazonaws.com
      bucket: xxxx-xxxx-workflow-artifacts
      region: ap-northeast-1
      keyFormat: {{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{workflow.name}}/{{steps.name}}/{{workflow.creationTimestamp}}
```

DAG
```yaml
  dag-repository: |
    s3:
      endpoint: s3.amazonaws.com
      bucket: xxxx-xxxx-workflow-artifacts
      region: ap-northeast-1
      keyFormat: {{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{workflow.name}}/{{tasks.name}}/{{workflow.creationTimestamp}}
```
