### ISSUE TITLE
Malformed WorkflowTemplate and Workflow crashes related UI again

### ISSUE THREAD

**Issue by pockyhe** [argoproj/argo-workflows#10001]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I post a debug issue before about  malformed workflow crashes related UI https://github.com/argoproj/argo-workflows/issues/9947. Thank @terrytangyuan advice about updating the latest version. 
However, another malformed workflow caused crashed workflow UI in Argo UI.
![image](https://user-images.githubusercontent.com/64390829/200720910-d4a2bae3-aa31-41b5-aad2-cf4dc23ad4cb.png)

I found this crash comes from first step in steps. I just used "-" istead of "- - ". workflow controller cannot identify it and caused error
![image](https://user-images.githubusercontent.com/64390829/200763719-fe47b434-bd73-4024-bc6f-1aef9d3447c3.png)

Do you have any idea about recovering it with keeping all history? Every time, I have to redeploy it which will clean all history such as existed workflow template and workflow history. Seems that because I have to delete related crd such as deleting workflows.argoproj.io

### Version

v3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
  entrypoint: sync-check
  templates:
    - name: sync-check
      inputs:
        parameters:
          - name: scenario-id
      steps:
        - name: sync-check
          templateRef: 
            name: sync-check-template
            template: sync-check-template
```

### Logs from the workflow controller

E1108 07:51:55.126026 1 leaderelection.go:330] error retrieving resource lock argo/workflow-controller: leases.coordination.k8s.io "workflow-controller" is forbidden: User "system:serviceaccount:argo:argo" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "argo"

### Logs from in your workflow's wait container

kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
