### ISSUE TITLE
Manual retries do not trigger exit handlers

### ISSUE THREAD

**Issue by pquadri** [argoproj/argo-workflows#10003]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When defining a workflow that has an exit handler (either with handlers or lifecycle hooks) a manual retry of the workflow does not trigger a rerun of the handler unless the handler himself fails, while in the code there is a comment that clearly states that the handler should always be executed.
I will soon test it on the latest version, but the code that causes the problem hasn't changed recently. 

### Version

3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-script-
spec:
  entrypoint: retry-script
  hooks:
    exit:
      template: handler
      arguments:
        parameters:
          - name: message
            value: "{{ workflow.status }}"

  templates:
  - name: retry-script
    script:
      image: python:alpine3.6
      command: ["python"]
      source: |
        import random;
        import sys; 
        exit_code = 1; 
        sys.exit(exit_code)
  - name: handler
    inputs: 
      parameters: 
        - name: message 
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.message}}"]
```

### Logs from the workflow controller

--- 

### Logs from in your workflow's wait container

---
