### ISSUE TITLE
Event viewer UI not showing events for retriable worksteps

### ISSUE THREAD

**Issue by fsiegmund** [argoproj/argo-workflows#10051]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

No events are shown when viewing events for a retriable workstep. Expected to see events.

Wrong query is submitted:

http://localhost:2746/api/v1/workflow-events/eesy-hello-world-evd-l7hr6?listOptions.fieldSelector=metadata.namespace=eesy-hello-world-evd-l7hr6,metadata.name=hello-world-evd-l7hr6

Should be: 

http://localhost:2746/api/v1/workflow-events/eesy-hello-world-evd-l7hr6?listOptions.fieldSelector=metadata.namespace=eesy-hello-world-evd-l7hr6,metadata.name=hello-world-evd-r2gmf-whalesay-541665272

Bug in ui/src/app/workflows/components/workflow-details/workflow-details.tsx, line 478:

{parsedSidePanel.type === 'events' && <EventsPanel namespace={namespace} kind='Pod' name={parsedSidePanel.nodeId} />}

Should be:

{parsedSidePanel.type === 'events' && <EventsPanel namespace={namespace} kind='Pod' name={podName} />}

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
entrypoint: whalesay
templates:
- name: whalesay
  retryStrategy:
    limit: 10
  container:
    image: docker/whalesay:latest
    command: [cowsay]
    args: ["hello world"]
```

### Logs from the workflow controller

UI

### Logs from in your workflow's wait container

UI
