### ISSUE TITLE
HTTP template does not respect podMetadata nor podSpecPatch

### ISSUE THREAD

**Issue by leshcat** [argoproj/argo-workflows#10062]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

`podMetadata` nor `podSpecPatch` are not respected by HTTP template that uses the Argo Agent.

In my particular case, i need to setup network policy labels that will allow pod's egress network communication.

Expected result:
Labels are set, pod can communicate with outside world.

Factual result:
Labels are ignored, pod can't communicate.

### Version

v3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-template-
spec:
  entrypoint: main
  podMetadata:
    labels:
      foo: "from podMetadata"
  podSpecPatch: |
    metadata:
      labels:
        bar: "from podSpecPatch"
  templates:
    - name: main
      steps:
        - - name: get-google-homepage
            template: http
            arguments:
              parameters: [{name: url, value: "https://www.google.com"}]
    - name: http
      inputs:
        parameters:
          - name: url
      http:
        url: "{{inputs.parameters.url}}"
        method: "GET"
        successCondition: "response.body contains \"google\""
```

### Logs from the workflow controller

time="2022-11-18T14:51:03.563Z" level=info msg="Processing workflow" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:03.574Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:03.574Z" level=info msg="Steps node http-template-gck68 initialized Running" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:03.574Z" level=info msg="StepGroup node http-template-gck68-1997246444 initialized Running" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:03.574Z" level=info msg="HTTP node http-template-gck68-2131965265 initialized Pending" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:03.574Z" level=info msg="Workflow step group node http-template-gck68-1997246444 not yet completed" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:03.574Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:03.574Z" level=info msg="Creating TaskSet" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:03.588Z" level=info msg=reconcileAgentPod namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:03.636Z" level=info msg="Created Agent pod" namespace=argo podName=http-template-gck68-1340600742-agent workflow=http-template-gck68
time="2022-11-18T14:51:03.636Z" level=info msg=updateAgentPodStatus namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:03.636Z" level=info msg=assessAgentPodStatus namespace=argo podName=http-template-gck68-1340600742-agent
time="2022-11-18T14:51:03.651Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=42621885 workflow=http-template-gck68
time="2022-11-18T14:51:13.635Z" level=info msg="Processing workflow" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:13.636Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=http-template-gck68
time="2022-11-18T14:51:13.636Z" level=info msg=updateAgentPodStatus namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:13.636Z" level=info msg=assessAgentPodStatus namespace=argo podName=http-template-gck68-1340600742-agent
time="2022-11-18T14:51:13.636Z" level=info msg="Workflow step group node http-template-gck68-1997246444 not yet completed" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:13.636Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=http-template-gck68
time="2022-11-18T14:51:13.636Z" level=info msg=reconcileAgentPod namespace=argo workflow=http-template-gck68

### Logs from in your workflow's wait container

N/A, Argo Agent is used.
