### ISSUE TITLE
Pod hangs when container in ContainerSet is OOM Killed

### ISSUE THREAD

**Issue by rajaie-sg** [argoproj/argo-workflows#10063]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I have a containerSet with 2 containers. The first container runs a script that results in it being OOM Killed. I expect the Pod and Workflow to fail at that point, but they just hang in the "Running" state until they reach their timeoutSeconds deadline.

I found this related issue https://github.com/argoproj/argo-workflows/issues/8680 but I am on 3.4.3 and still running into it.

I am using the emissary executor

### Version

v3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: example
  namespace: argo
  labels:
spec:
  automountServiceAccountToken: false
  dnsConfig:
    nameservers:
      - 10.33.0.2 # AWS VPC Default
      - 1.1.1.1 # CloudFlare
      - 8.8.8.8 # Google
  executor:
    serviceAccountName: "argo-workflow"
  templates:
    - name: entrypoint
      # max workflow duration https://argoproj.github.io/argo-workflows/fields/#workflowspec
      retryStrategy: # https://argoproj.github.io/argo-workflows/retries/
        limit: "3"
        retryPolicy: "OnTransientError"
      metadata:
      containerSet:
        containers:
          - name: one
            imagePullPolicy: Always
            resources:
              requests:
                memory: "50Mi"
                cpu: "50m"
              limits:
                memory: "50Mi"
            image: "ubuntu"
            command:
              - bash
              - '-c'
            args:
              - |
                /bin/bash <<'EOF'
                echo "hello one"
                apt update -y
                apt install stress -y
                echo 'stress --vm 1 --vm-bytes 512M --vm-hang 100' > abc.sh
                bash abc.sh
                EOF
          - name: two # if changing, update 'eks.amazonaws.com/skip-containers'
            imagePullPolicy: Always
            resources:
              requests:
                memory: "150Mi"
                cpu: "50m"
              limits:
                memory: "250Mi"
            image: "ubuntu"
            command:
              - bash
              - '-c'
            args:
              - |
                /bin/bash <<'EOF'
                echo "hello world"
                EOF
            dependencies:
              - one
  entrypoint: entrypoint
```
```


### Logs from the workflow controller

n/a

### Logs from in your workflow's wait container

time="2022-11-18T17:07:11.708Z" level=info msg="Starting Workflow Executor" version=v3.4.3
time="2022-11-18T17:07:11.711Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-11-18T17:07:11.711Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo podName=postman-test-fxd4q-entrypoint-1784721547 template="templatehere"
time="2022-11-18T17:07:11.712Z" level=info msg="Starting deadline monitor"
```
