### ISSUE TITLE
`outputs.result` not working with jsonpath

### ISSUE THREAD

**Issue by Digtiq** [argoproj/argo-workflows#10076]
### Pre-requisites

- [X] I have double-checked my configuration
- [x] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

hello,
I have already tried many things but am in despair. Simple jsonpath doesn't work if I want to use the output from the step before. then the `{{}}` are just ignored and `test:{{=jsonpath(tasks.dummy0.outputs.result, '$.test')}}` is output which I think is a bug.

if i use the `myjson` parameter then everything works correctly. 

### Version

3.3.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
spec:
  templates:
    - name: main
      dag:
        tasks:
          - name: dummy0
            
            inline:
              container:
                image: docker/whalesay:latest
                command:
                  - sh
                  - '-c'
                args:
                  - echo "{{workflow.parameters.myjson}}"
              
          - name: dummy
            depends: "dummy0"

            arguments:
              parameters:
                - name: json
                  value: "{{tasks.dummy0.outputs.result}}"
        
            inline:
              inputs:
                parameters:
                  - name: json
              container:
                image: docker/whalesay:latest
                command:
                  - sh
                  - '-c'
                args:
                  #- echo 'test:{{=jsonpath(workflow.parameters.myjson, '$.test')}}' # working
                  - echo 'test:{{=jsonpath(tasks.dummy0.outputs.result, '$.test')}}' # not working

  entrypoint: main
  arguments:
    parameters:
      - name: myjson
        value: >-
          {"test": "0"}
```

### Logs from the workflow controller

```
my-test-pkdgf--910287825: time="2022-11-19T11:30:43.113Z" level=info msg="capturing logs" argo=true
my-test-pkdgf--910287825: {test: 0}
my-test-pkdgf--910287825: time="2022-11-19T11:30:44.127Z" level=info msg="sub-process exited" argo=true error="<nil>"
my-test-pkdgf--1925477307: test:0
```

### Logs from in your workflow's wait container

```
my-test2-frgg8--3934791511: test:{{=jsonpath(tasks.dummy0.outputs.result, $.test)}}
```

**Comment by juliev0** [comment]
can you see if this is working on latest (3.4.3)?

**Comment by Digtiq** [comment]
same problem
output is:
test:{{=jsonpath(tasks.dummy0.outputs.result, $.test)}}

**Comment by juliev0** [comment]
okay, thanks for checking!

**Comment by neWs1587** [comment]
same problem！

**Comment by agilgur5** [comment]
We may want to retry this since https://github.com/argoproj/pkg/pull/486 / #11704 updated to a newer and more comprehensive JSONPath library. That was released in 3.5.0-rc2

**Comment by agilgur5** [comment]
Oh, wait a minute.

> ```yaml
>                   #- echo 'test:{{=jsonpath(workflow.parameters.myjson, '$.test')}}' # working
>                   - echo 'test:{{=jsonpath(tasks.dummy0.outputs.result, '$.test')}}' # not working
> ```

That might be because `tasks.dummy0.outputs.result` is a JSON _string_, not a deserialized map. You might be able to workaround this with [`fromJSON`](https://expr.medv.io/docs/v1.14/Language-Definition#fromjsonv) which recently became available as a new built-in function in `expr` 1.14. That new `expr` version is included in Argo 3.5.0-rc2 as well

**Comment by miltalex** [comment]
I still get the issue, I will have a look into this when I manage to find a bit of time.

**Comment by miltalex** [comment]
I've analyzed the logs from the controller that helped pinpoint the issue:
```
time="2024-07-22T10:35:18.124Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=,name=)" tmpl="*v1alpha1.DAGTask inlined"
time="2024-07-22T10:35:18.124Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=,name=)" tmpl="*v1alpha1.DAGTask inlined"
time="2024-07-22T10:35:18.125Z" level=debug msg="Result and error are unresolved" error="invalid character 't' looking for beginning of object key string (1:1)\n | jsonpath(tasks.dummy0.outputs.result, '$.test')\n | ^"
```

After testing all paths in the `expressionReplace` function, I identified the root cause. The problem lies in how a valid JSON input is defined for the echo command. In the current template, during the 'dummy' step where echo is executed, the quotes aren't preserved. This results in an output of `{test: 0}` (and the corresponding value `outputs:map[result:{test: 0}` in the Go struct), which isn't valid JSON.

Since the output is not valid JSON, the `expr.Compile` will call `jsonPath` function, and that fails to process it, with or without the handlers `fromJson`, `toJSON` since both of them rely on valid JSON string/value.

To resolve this issue, we need to properly maintain the double quotes during the echo command to achieve a result of `{"test": "0"}`, which is valid for `expr` and will allow the next step to succeed and echo the correct value.

During my tests, I found that providing the following input was sufficient `'{\"test\": \"0\"}'`. Alternatively, you can use this format in the arguments:
```
arguments:
    parameters:
      - name: myjson
        value: '{"test": "0"}'
 ```
Either of these approaches will ensure that the JSON structure is preserved and can be correctly processed by the subsequent steps. Apart from that any bash script that produces a valid JSON output will also work
 
 @agilgur5 I would propose to close this issue since it was a matter of wrongly defined user input.
