### ISSUE TITLE
Delay memoization cache hit check until actual step execution

### ISSUE THREAD

**Issue by avasiliev** [argoproj/argo-workflows#10109]
# Summary

Don't check memoization cache hits on workflow startup, because delaying this check may save some computational resources.

# Use Cases

I would like to save some cluster resources not only when some work is already done and the artifacts are ready, but even when multiple jobs are trying to do the same task simultaneously.

Here is a simplified example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: memoized-workflow-test-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: run-1
        template: run
        arguments:
          parameters:
          - name: id
            value: 1
          - name: cache-key
            value: the-same-in-all-runs
      - name: run-2
        template: run
        arguments:
          parameters:
          - name: id
            value: 2
          - name: cache-key
            value: the-same-in-all-runs
  - name: run
    inputs:
      parameters:
      - name: id
      - name: cache-key
    script:
      image: ubuntu:22.04
      command: [bash]
      source: |
        sleep 30
        echo result: {{inputs.parameters.id}}
    memoize:
      key: "{{inputs.parameters.cache-key}}"
      cache:
        configMap:
          name: some-test-cache
    synchronization:
      mutex:
        name: 'memoized-workflow-test-run-{{inputs.parameters.cache-key}}'
```

Here I have two steps which do the same job (and that is reflected in the fact that they have the same cache key). These steps in theory may run in parallel, but I introduced the mutex, which is unique for each possible cache key. 

As a result I would expect that actual useful job is done exactly once: by the step which managed to acquire the mutex first. But unfortunately, the status of cache hit is checked only at workflow startup, so the job is done twice and some computational resources are wasted.

That's a simplified example, and of course this semantics is [also] needed to save resources across different workflows.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
