### ISSUE TITLE
Allow for markdown in workflow title/description in UI

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argo-workflows#10126]
# Summary

Allow for markdown in title or description on workflows list in UI.  #6529 introduced the title and description text via annotations.  This is a quick follow and will allow markdown.

```yaml
spec:
  annotations:
    workflows.argoproj.io/title: '**Build and test**'
    workflows.argoproj.io/description: '`SuperDuperProject` PR #6529: Implement frobbing (aff39ee)'

```

Results in:

> **Build and test**
> `SuperDuperProject` PR #6529: Implement frobbing (aff39ee)

# Motivation
This will allow markup and linking to occur on the UI title and/or description

# Use Cases

Example: linking back to the GitHub PR that issued the workflow in a CI example

# Note

@jmeridth (author of #9805 - title/description PR) experienced javascript errors when trying to introduce markdown (via `react-markdown` library).  Example error [here](https://github.com/argoproj/argo-workflows/pull/9805#issuecomment-1276907504)

Based on [this open issue](https://github.com/swagger-api/swagger-ui/issues/8062) in swagger-ui repo that shows the same error, there might be a conflict with react-markdown and swagger-ui.  Upgrading webpack did not work previously.

# Kudos

Kudos to @atombender for the original issue and idea for this feature

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
