### ISSUE TITLE
envFrom in script template does not add env vars when there is a podSpecPatch with envFrom

### ISSUE THREAD

**Issue by RoryDoherty** [argoproj/argo-workflows#10149]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When there is an envFrom specified in podSpecPatch under templateDefaults and an envFrom specified in a template the two are not merged. I only get the environment variables from the podSpecPatch, the template envFrom is not used.

When I remove the podSpecPatch and only use envFrom under the template then the variables exist properly

### Version

v3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
spec:
  entrypoint: run-test
  templateDefaults:
    podSpecPatch: |-
      containers:
        - name: main
          envFrom:
            - secretRef: 
                name: some-secret-in-cluster
  templates:
    - name: run-test
      script:
        image: ubuntu:18.04
        imagePullPolicy: Always
        command: [bash]
        workingDir: "/src"
        envFrom:
          - secretRef:
              name: another-secret-in-cluster
        source: |
          env
```

### Logs from the workflow controller

```text
time="2022-12-01T15:22:11.366Z" level=info msg="Processing workflow" namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:11.373Z" level=info msg="Updated phase  -> Running" namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:11.373Z" level=info msg="Pod node demo-26g62 initialized Pending" namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:11.397Z" level=info msg="Created pod: demo-26g62 (demo-26g62)" namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:11.397Z" level=info msg="TaskSet Reconciliation" namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:11.397Z" level=info msg=reconcileAgentPod namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:11.411Z" level=info msg="Workflow update successful" namespace=argoci phase=Running resourceVersion=744368912 workflow=demo-26g62
time="2022-12-01T15:22:21.398Z" level=info msg="Processing workflow" namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:21.398Z" level=info msg="Task-result reconciliation" namespace=argoci numObjs=1 workflow=demo-26g62
time="2022-12-01T15:22:21.398Z" level=info msg="task-result changed" namespace=argoci nodeID=demo-26g62 workflow=demo-26g62
time="2022-12-01T15:22:21.399Z" level=info msg="node changed" namespace=argoci new.message= new.phase=Succeeded new.progress=0/1 nodeID=demo-26g62 old.message= old.phase=Pending old.progress=0/1 workflow=demo-26g62
time="2022-12-01T15:22:21.399Z" level=info msg="TaskSet Reconciliation" namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:21.399Z" level=info msg=reconcileAgentPod namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:21.399Z" level=info msg="Updated phase Running -> Succeeded" namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:21.399Z" level=info msg="Marking workflow completed" namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:21.399Z" level=info msg="Marking workflow as pending archiving" namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:21.399Z" level=info msg="Checking daemoned children of " namespace=argoci workflow=demo-26g62
time="2022-12-01T15:22:21.405Z" level=info msg="cleaning up pod" action=deletePod key=argoci/demo-26g62-1340600742-agent/deletePod
time="2022-12-01T15:22:21.413Z" level=info msg="Workflow update successful" namespace=argoci phase=Succeeded resourceVersion=744369121 workflow=demo-26g62
time="2022-12-01T15:22:21.445Z" level=info msg="archiving workflow" namespace=argoci uid=9790629f-15c2-44e2-88d8-dcf8b06a2552 workflow=demo-26g62
time="2022-12-01T15:22:21.485Z" level=info msg="Queueing Succeeded workflow argoci/demo-26g62 for delete in 168h0m0s due to TTL"
time="2022-12-01T15:22:26.445Z" level=info msg="cleaning up pod" action=deletePod key=argoci/demo-26g62/deletePod
```

### Logs from in your workflow's wait container

```text
time="2022-12-01T15:22:16.100Z" level=info msg="No output parameters"
time="2022-12-01T15:22:16.100Z" level=info msg="No output artifacts"
time="2022-12-01T15:22:16.101Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: demo-26g62/demo-26g62/main.log"
time="2022-12-01T15:22:16.101Z" level=info msg="Creating minio client using static credentials" endpoint=storage.googleapis.com
time="2022-12-01T15:22:16.115Z" level=info msg="Saving file to s3" bucket=argoci-artifacts endpoint=storage.googleapis.com key=demo-26g62/demo-26g62/main.log path=/tmp/argo/outputs/logs/main.log
time="2022-12-01T15:22:16.312Z" level=info msg="Save artifact" artifactName=main-logs duration=210.643591ms error="<nil>" key=demo-26g62/demo-26g62/main.log
time="2022-12-01T15:22:16.312Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2022-12-01T15:22:16.312Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2022-12-01T15:22:16.324Z" level=info msg="Create workflowtaskresults 201"
time="2022-12-01T15:22:16.325Z" level=info msg="Alloc=7954 TotalAlloc=16350 Sys=23762 NumGC=5 Goroutines=11"
```
