### ISSUE TITLE
UI not showing logs of ContainerSet containers

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-workflows#10157]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I'm running a workflow with a ContainerSet. When I want to see the logs of the containers I click on one container, then click on LOGS in sidebar menu. The logs window for all containers is empty but the main container.

I use `archiveLogs: true` in the workflow manifests, so I can also see the workflow in **Archived Workflows** tab. There, the logs are visible for each container.

### Version

v3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
  namespace: argo
spec:
  archiveLogs: true
  activeDeadlineSeconds: 1200
  entrypoint: main
  serviceAccountName: workflow
  templates:
  - name: main
    metadata:
      labels:
        app: app
    containerSet:
      containers:
      - name: echo
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "echo"
      - name: main
        dependencies:
        - echo
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "main"
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
