### ISSUE TITLE
Support default value for jsonpath

### ISSUE THREAD

**Issue by johnlinp** [argoproj/argo-workflows#10172]
# Summary

I would use `jsonpath()` to extract values from a JSON string. However, sometimes the value is not present in the JSON string. I would like to pass a default value to `jsonpath()` in case that the desired value is not there.

# Use Cases

For example, I would like to see something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: john-test
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
        - name: fruits
          default: |
            {
              "apple": 3,
              "banana": 5
            }
    container:
      image: alpine:latest
      command: ["sh", "-c"]
      args:
        - |
          echo "ENV1: ${ENV1}"
          echo "ENV2: ${ENV2}"
      env:
        - name: ENV1
          value: "{{=jsonpath(inputs.parameters.fruits, '$.apple', '0')}}"
        - name: ENV2
          value: "{{=jsonpath(inputs.parameters.fruits, '$.orange', '0')}}"

```

Since the value from the path `$.apple` is 3, the variable `ENV1` would be populated as 3. However, the value is not present in `$.orange`, so it will fall back to the specified default value, 0. Therefore, The desired outputs will be:

```
ENV1: 3
ENV2: 0
```

Thank you.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by jomach** [comment]
use sprig.default

**Comment by johnlinp** [comment]
Hi @jomach,

Thank you for the suggestion. However, when I apply `sprig.default` in my workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: john-test
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
        - name: fruits
          default: |
            {
              "apple": 3,
              "banana": 5
            }
    container:
      image: alpine:latest
      command: ["sh", "-c"]
      args:
        - |
          echo "ENV1: ${ENV1}"
          echo "ENV2: ${ENV2}"
      env:
        - name: ENV1
          value: "{{=sprig.default(jsonpath(inputs.parameters.fruits, '$.apple'), 0)}}"
        - name: ENV2
          value: "{{=sprig.default(jsonpath(inputs.parameters.fruits, '$.orange'), 0)}}"
```

The outputs are:

```
ENV1: 3
ENV2: {{=sprig.default(jsonpath(inputs.parameters.fruits, '$.orange'), 0)}}
```

It's not quite what I wanted. Did I miss something? Thank you.
