### ISSUE TITLE
withParams processed even when task/step Skipped

### ISSUE THREAD

**Issue by elauqsap** [argoproj/argo-workflows#10173]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

It seems `withParam` is still processed even if the `when` condition of a task or step is evaluated as false. This causes the task or step to show its Phase as `Error`. Since there is no need to expand the task/step if the `when` condition evaluates false I would expect the end result to be `Type: Skipped` and ` Phase: Omitted`.

**Type: Pod Phase: Succeeded**
```bash
argo submit gh-issue.yaml --watch -p filter=data
```

**Type: Skipped Phase: Error**
```bash
argo submit gh-issue.yaml --watch -p filter=none
```

### Version

v3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: withparams-issue
  namespace:  argo-events
spec:
  entrypoint: withParams-issue
  arguments:
    parameters:
      - name: filter
  templates:
  - name: withParams-issue
    dag:
      tasks:
        - name: generate
          template: generate

        - name: filter
          arguments:
            parameters:
              - name: filter
                value: >-
                  {{ workflow.parameters.filter }}
              - name: result
                value: >-
                    {{ tasks.generate.outputs.result }}
          template: filter
          depends: "generate.Succeeded"

        - name: print
          arguments:
            parameters:
              - name: result
                value: >-
                    {{ item }}
          template: print
          depends: "filter.Succeeded"
          withParam: >-
            {{ tasks.filter.outputs.result }}
          when: >-
            {{ tasks.filter.outputs.result }} != 'skip'

  - name: generate
    script:
      image: python:3.9
      command:
        - /usr/bin/python3
      source: |
        from json import dumps
        print(dumps({
          'data': [{
            '1': True,
            '2': 'string',
            '3': 3 
          }]
        }))

  - name: filter
    inputs:
      parameters:
        - name: result
        - name: filter
    script:
      image: python:3.9
      command:
        - /usr/bin/python3
      source: |
        from json import dumps, loads
        result = loads('{{ inputs.parameters.result }}')
        filter = '{{ inputs.parameters.filter }}'
        if result.get(filter):
          print(dumps(result.get(filter)))
        else:
          print('skip')

  - name: print
    inputs:
      parameters:
        - name: result
    script:
      image: python:3.9
      command:
        - /usr/bin/python3
      source: |
        print('{{ inputs.parameters.result }}')
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
