### ISSUE TITLE
No logs accessible in the UI on workflows that went from Pending to Running

### ISSUE THREAD

**Issue by fdebuire** [argoproj/argo-workflows#10178]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Argo Workflows controller is configured with `parallelism: 10`. 

Workflows that are created in pending, because too many workflows are already running, will not have the annotation `workflows.argoproj.io/pod-name-format: v2` associated to them, therefore logs will not be able to be viewed using the UI.

It can be reproduced using the attached workflow and the command:
```
for i in {1..20}; do kubectl create -f test.yaml; done
```

It seems to happen because the annotation is only set here:
https://github.com/argoproj/argo-workflows/blob/2eb871bf2f1bd9008ab09995b560600e5c594153/workflow/controller/operator.go#L271

but not here: https://github.com/argoproj/argo-workflows/blob/2eb871bf2f1bd9008ab09995b560600e5c594153/workflow/controller/operator.go#L251

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-logs-
spec:
  entrypoint: test-dag
  templates:
  - name: echo
    container:
      image: alpine:3.7
      command: [echo, "OK!"]
  - dag:
      tasks:
      - name: test
        template: test
    name: test-dag
  - dag:
      tasks:
      - name: 'echo-1'
        template: echo
      - depends: echo-1
        name: 'echo-2'
        template: echo
    name: test
```

### Logs from the workflow controller

```text
time="2022-12-05T09:14:17.554Z" level=info msg="Workflow processing has been postponed due to max parallelism limit" key=cloud-workflows/test-logs-54tz6
time="2022-12-05T09:14:17.554Z" level=info msg="Updated phase  -> Pending" namespace=cloud-workflows workflow=test-logs-54tz6
time="2022-12-05T09:14:17.554Z" level=info msg="Updated message  -> Workflow processing has been postponed because too many workflows are already running" namespace=cloud-workflows workflow=test-log>
time="2022-12-05T09:14:17.555Z" level=info msg="Workflow to be dehydrated" Workflow Size=652
time="2022-12-05T09:14:17.653Z" level=info msg="Update workflows 200"
time="2022-12-05T09:14:17.654Z" level=info msg="Workflow update successful" namespace=cloud-workflows phase=Pending resourceVersion=276945745 workflow=test-logs-54tz6
...
time="2022-12-05T09:14:58.332Z" level=info msg="Processing workflow" namespace=cloud-workflows workflow=test-logs-54tz6
time="2022-12-05T09:14:58.340Z" level=info msg="Task-result reconciliation" namespace=cloud-workflows numObjs=0 workflow=test-logs-54tz6
time="2022-12-05T09:14:58.340Z" level=info msg="Updated phase Pending -> Running" namespace=cloud-workflows workflow=test-logs-54tz6
```

### Logs from in your workflow's wait container

```text
N/A
```
