### ISSUE TITLE
The name of the pod adds taskname, but when I describe the workflow, in the nodes of the status, the ID of the node is not the name of the pod

### ISSUE THREAD

**Issue by LittleMcdull** [argoproj/argo-workflows#10181]
# What happened
workflow-controller: v3.4.4

workflow **pod's name** add **taskname** now, like this
```
NAME                                              READY      STATUS        RESTARTS       AGE
pipeline-jndha0-scacfg-main-2-2237629385           0/2      Completed          0          5h34m
pipeline-jndha0-scacfg-main-3-2220851766           0/2      Completed          0          5h34m
pipeline-jndha0-scacfg-main-1-3132648502           0/2      Completed          0          5h34m
```

but when i describe workflow , **status node id dosn't hive taskname**
```
...
status:
  nodes:
    pipeline-jndha0-scacfg-2220851766:
      boundaryID: pipeline-jndha0-scacfg
      children:
      - pipeline-jndha0-scacfg-2237629385
      displayName: main-3
      finishedAt: "2022-12-06T03:00:50Z"
      hostNodeName: metaai-test-node3
      id: pipeline-jndha0-scacfg-2220851766
      name: pipeline-jndha0-scacfg.main-3
      ...
      type: Pod
    pipeline-jndha0-scacfg-2237629385:
      boundaryID: pipeline-jndha0-scacfg
      children:
      - pipeline-jndha0-scacfg-2254407004
      displayName: main-2
      finishedAt: "2022-12-06T03:01:00Z"
      hostNodeName: metaai-test-node3
      id: pipeline-jndha0-scacfg-2237629385
      name: pipeline-jndha0-scacfg.main-2
      ...
      type: Pod
    pipeline-jndha0-scacfg-3132648502:
      boundaryID: pipeline-jndha0-scacfg
      children:
      - pipeline-jndha0-scacfg-2220851766
      displayName: main-1
      finishedAt: "2022-12-06T03:00:41Z"
      hostNodeName: metaai-test-node3
      id: pipeline-jndha0-scacfg-3132648502
      name: pipeline-jndha0-scacfg.main
      type: Pod
      ...
...
```
