### ISSUE TITLE
Config map updates are not picked up by controller without bouncing the controller

### ISSUE THREAD

**Issue by agarwalankitnyu** [argoproj/argo-workflows#10187]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I updated the config map parallelism setting, but the changes were not reflected until I redeployed the controller. Auto config map read was added as a feature in the past. Look at this [issue](https://github.com/argoproj/argo-workflows/issues/9123). But looks like the feature was removed as part of this refactor [commit](https://github.com/mcgrawia/argo-workflows/commit/f00ec49d695bdad108000abcdfd0f82f6af9ca6c).

 

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "hello world" ]
        resources:
          limits:
            memory: 32Mi
            cpu: 100m
```

### Logs from the workflow controller

```text
//
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

//
```
