### ISSUE TITLE
Unable to use script tag inside containerset

### ISSUE THREAD

**Issue by MaheshChandrra** [argoproj/argo-workflows#10197]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hi Team

I would like to execute a python script using script tag inside a container of container set template.
But when I do it, while running the values of image, args and command are read as empty strings as all the values are defined in script tag.

Can you please let me know how to use script tag along with containers in container set template.

Thanks
Mahesh 

### Version

>= 3.1.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: container-set-template-
spec:
  entrypoint: main
  templates:
    - name: main
      volumes:
        - name: workspace
          emptyDir: { }
      containerSet:
        volumeMounts:
          - mountPath: /workspace
            name: workspace
        containers:
          - name: a
            script:
              image: python:alpine3.6
              command: [python]
              source: |
                import random
                i = random.randint(1, 100)
                print(i)
          - name: b
            image: argoproj/argosay:v2
          - name: main
            image: argoproj/argosay:v2
            dependencies:
              - a
              - b
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
