### ISSUE TITLE
Cronworkflow's archived workflow did not support retry or resubmit when cronworkflow deleted

### ISSUE THREAD

**Issue by Tan-JiaLiang** [argoproj/argo-workflows#10215]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When i tried to retry or resubmit a archived workflow, which scheduled by an deleted cronworkflow, the retry or resubmit RESTFUL api return 200, but it not found in workflow list. Did it support retry or resubmit when a cronworkflow deleted? May be it should not return 200?
![image](https://user-images.githubusercontent.com/55388933/207061337-1f7ecae7-9b5b-4606-a2ea-dce36cb0cf07.png)

### Version

v3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: whalesay
    templates:
    - name: whalesay
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["date; sleep 90"]
```

### Logs from the workflow controller

```text
nothing
```

### Logs from in your workflow's wait container

```text
nothing
```
