### ISSUE TITLE
hostPID support

### ISSUE THREAD

**Issue by marinoborges** [argoproj/argo-workflows#10217]
# Summary

As already mentioned in #6279, **hostPID** field is not available in Argo Workflow. Since **hostPID** field is supported by native Kubernetes pods and cronjobs, it should be supported in Argo Workflows too.

# Use Cases

When trying to create an Argo Workflow for kube-bench (security benchmark tool), I'm unable to set **hostPID** parameter which is needed because kube-bench needs to be able to _ps_ and see processes on the host node. [Job reference](https://github.com/aquasecurity/kube-bench/blob/main/job.yaml#L12).

I got the following WorkflowTemplate:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kube-bench
spec:
  automountServiceAccountToken: true
  entrypoint: kube-bench-template
  templates:
    - name: kube-bench-template
      serviceAccountName: kube-bench
      hostPID: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      initContainers:
        - name: kube-bench
          image: aquasec/kube-bench:latest
          command: ["/bin/sh"]
          args: ["-c", "kube-bench run --targets master,node,etcd,policies | tee /export/kube-bench/report.txt"]
```
However, when applied the **hostPID** is not present in the live manifest and is causing kube-bench to fail a few reports that demand this level of access.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
