### ISSUE TITLE
resoure duration metrics are mssing when adding retryStrategy

### ISSUE THREAD

**Issue by huzhenwei7z** [argoproj/argo-workflows#10222]
### Pre-requisites

- [X] I have double-checked my configuration
- [ ] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When I add retryStrategy configuration to my argo workflow, the `resourceDuration` metrics are missing. Their values are 0 when I check on Prometheus. I am sure it works when retryStrategy is not set.

### Version

v3.3.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  serviceAccountName: argo-workflow
  templates:
  - name: whalesay
    metrics:
      prometheus:
      - counter:
          value: '{{ resourcesDuration.memory }}'
        labels:
        - key: workflow_template
          value: hello-world
        - key: template
          value: hello
        - key: resource
          value: memory
        - key: unit
          value: '1'
        name: resources_duration_seconds_counter
        help: resources_duration_seconds_counter
      - counter:
          value: '{{ resourcesDuration.cpu }}'
        labels:
        - key: workflow_template
          value: hello-world
        - key: template
          value: hello
        - key: resource
          value: cpu
        - key: unit
          value: '1'
        name: resources_duration_seconds_counter
        help: resources_duration_seconds_counter
    container:
      image: docker/whalesay:latest
      command: [exit]
      args: ["1"]
    retryStrategy:
      limit: 1
      retryPolicy: Always
      backoff:
        duration: '2'
        factor: '2'
```
```


### Logs from the workflow controller

```text
❯ k logs -n dev --context gz deploy/workflow-controller | grep hello
Found 2 pods, using pod/workflow-controller-86dbc65c4-s5vqc
time="2022-12-13T07:53:41.246Z" level=info msg="Queueing Failed workflow dev/hello-world-smjrv for delete in 23h24m57s due to TTL"
time="2022-12-13T07:53:41.248Z" level=info msg="Queueing Failed workflow dev/hello-world-q4wkb for delete in 23h48m11s due to TTL"
```

### Logs from in your workflow's wait container

```text
not related
```
