### ISSUE TITLE
Git artifacts: 'reference delta not found' clone problem 

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-workflows#10225]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Looks like the library 'go-git' that you are using for cloning git repositories has a problem "reference delta not found" on the git.PlainClone function.

<img width="1499" alt="Screenshot 2022-12-13 at 10 42 39" src="https://user-images.githubusercontent.com/66973520/207268399-1234555b-b32f-4c75-95f1-d2ec17e4d592.png">

https://github.com/go-git/go-git/issues?q=is%3Aissue+reference+delta+not+found

Looks like in the latest version the problem is fixed. I think that a version update on your side will fix the problem. 
Thank you!

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
artifacts:
          - name: repo
            path: /src
            git:
              repo: "{{workflow.parameters.repo}}"
              revision: "{{workflow.parameters.revision}}"
              disableSubmodules: true
              usernameSecret:
                name: "{{workflow.parameters.secretName}}"
                key: username
              passwordSecret:
                name: "{{workflow.parameters.secretName}}"
                key: password
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

ERRO[2022-12-13T10:08:07.481Z] container "main" in pod "create-flz2c-retrieve-changed-markdown-files-4256658970" is terminated  namespace=argo podName=create-flz2c-retrieve-changed-markdown-files-4256658970 workflow=create-flz2c
```

### Logs from in your workflow's wait container

```text
There are no logs
```
