### ISSUE TITLE
soft links are now being removed in artifact passing

### ISSUE THREAD

**Issue by leojeb** [argoproj/argo-workflows#10238]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

#### what happened:
The wf generates artifact in the first step and it creates a soft link with the command:
   "ln -s /tmp/hello_world.txt /tmp/ttt/hello_world.txt" .

The artifact did exist in my artifact-repo and I even downloaded and unzipped it, which did include the soft link I created. Later I got into the second running step and the soft link was deleted. 
I tried the same wf for version 3.2.0, which produced the result I want. But as I said, it didn't work with version 3.4.3 . 

#### what I expected to happen:
the soft link file /tmp/ttt/hello_world.txt should appear in the container in the second step.

### Version

v3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  name: artifact-passing
  namespace: argo
spec:
  templates:
    - name: artifact-example
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: generate-artifact
            template: whalesay
            arguments:{}   
        - - name: consume-artifact
            template: print-message
            arguments:
              artifacts:
                - name: message
                  from: '{{steps.generate-artifact.outputs.artifacts.hello-art}}'
    - name: whalesay
      inputs:
        parameters:
          - name: id
      outputs:
        artifacts:
          - name: hello-art
            path: /tmp
      metadata: {}
      container:
        name: ''
        image: alpine:latest
        command:
          - sh
          - '-c'
        args:
          - >-
            echo 'hello_world.txt' >> /tmp/hello_world.txt &&  mkdir /tmp/ttt &&
            ln -s /tmp/hello_world.txt /tmp/ttt/hello_world.txt; ls -l /tmp ; ls
            -l /tmp/ttt
        resources: {}
    - name: print-message
      inputs:
        artifacts:
          - name: message
            path: /tmp/
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: alpine:latest
        command:
          - sh
          - '-c'
        args:
          - sleep 10000;cat /tmp/ttt/1
        resources: {}
  entrypoint: artifact-example
  arguments: {}
```

### Logs from the workflow controller

```text
no logs
```

### Logs from in your workflow's wait container

```text
no logs
```
