### ISSUE TITLE
argo3.3.10 termante workflow then retry meet error: Workflow operation error

### ISSUE THREAD

**Issue by yeicandoit** [argoproj/argo-workflows#10285]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

https://user-images.githubusercontent.com/22470950/209812826-6c417bff-ad4d-41a0-88af-f30a9d512834.mp4

when the workflow is running, stop/terminate it, then retry it. the workflow will meet issue: Workflow operation error.
I except the workflow to re-run correctly

### Version

v3.3.10

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: dag-diamond-1
spec:
  entrypoint: diamond
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [sleep, "600s"]
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [B, C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}]
```

### Logs from the workflow controller

```text
time="2022-12-28T10:37:43.765Z" level=info msg="Create pods 201"
time="2022-12-28T10:37:43.766Z" level=info msg="Created pod: dag-diamond-1-lkhtv.A (dag-diamond-1-lkhtv-1695834569)" namespace=enos workflow=dag-diamond-1-lkhtv
time="2022-12-28T10:37:43.766Z" level=error msg="Recovered from panic" namespace=enos r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 154 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:194 +0xd4\npanic({0x1d506c0, 0x3432820})\n\t/usr/local/go/src/runtime/panic.go:1047 +0x266\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc0009f86c0, {0x2339ae8, 0xc00005a018}, {0xc00106a480, 0x15}, {0x231a750, 0xc000b2c5a0}, 0x0, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1965 +0x32c5\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc0009f86c0, {0x2339ae8, 0xc00005a018}, 0xc000441880, {0xc000d22841, 0x1})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:513 +0x1888\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc0009f86c0, {0x2339ae8, 0xc00005a018}, 0xc000441880, {0xc000f84661, 0x1})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:438 +0x1f25\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc0009f86c0, {0x2339ae8, 0xc00005a018}, 0xc000441880, {0x33da960, 0x1})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:438 +0x1f25\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc0009f86c0, {0x2339ae8, 0xc00005a018}, {0xc00106a0c0, 0x6561393034313600}, 0xc000be0c40, {0xc0003759a0, 0x19}, 0xc00103a480, {0x231b9e0, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x433\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc0009f86c0, {0x2339ae8, 0xc00005a018}, {0xc00106a0c0, 0x13}, {0x231b9e0, 0xc0009f8780}, 0xc000be0c00, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1906 +0x232c\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc0009f86c0, {0x2339ae8, 0xc00005a018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:350 +0x16a8\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0004ea400, {0x2339ae8, 0xc00005a018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:756 +0x8ee\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0x0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:678 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f630fcd7730)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:155 +0x67\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x22f6ee0, 0xc000346840}, 0x1, 0xc000099500)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:294 +0x1a6c\n" workflow=dag-diamond-1-lkhtv
time="2022-12-28T10:37:43.766Z" level=info msg="Updated phase Running -> Error" namespace=enos workflow=dag-diamond-1-lkhtv
time="2022-12-28T10:37:43.766Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=enos workflow=dag-diamond-1-lkhtv
time="2022-12-28T10:37:43.766Z" level=info msg="Marking workflow completed" namespace=enos workflow=dag-diamond-1-lkhtv
time="2022-12-28T10:37:43.766Z" level=info msg="Checking daemoned children of " namespace=enos workflow=dag-diamond-1-lkhtv
```

### Logs from in your workflow's wait container

```text
retry failed, so no wait log
```
