### ISSUE TITLE
Two workflows are running at the same time despite of semaphore

### ISSUE THREAD

**Issue by yaaraze** [argoproj/argo-workflows#10286]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hi, we’re using argo-workflows for two years now and recently we’ve experienced several times now that **two workflows are running at the same time even though they use the same semaphore**. 
Last time it just happened in the middle of the run after a few hours. No weird logs were shown, it looked like the second workflow was waiting on the semaphore and then just started running. Simultaneously we have other workflows running with other semaphores.

The only thing I can think of that we’ve changed recently is that we started using exit handlers.

Attaching the workflow file (I removed any env/args/labels/artifacts that I can't share).
Obviously this is a statistical bug so I can't reproduce it, but it happened three in the last two months (that I could notice) so I think it's pretty severe.

### Version

v3.2.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "Workflow",
  "metadata": {
    "generateName": "argo-tenant-0x2-",
    "namespace": "argo"
  },
  "spec": {
    "onExit": "exit-handler",
    "ttlStrategy": {
      "secondsAfterSuccess": 1209600,
      "secondsAfterFailure": 1209600
    },
    "entrypoint": "main",
    "synchronization": {
      "semaphore": {
        "configMapKeyRef": {
          "name": "tenant-2-workflow-semaphore",
          "key": "workflow"
        }
      }
    },
    "templates": [
      {
        "name": "main",
        "steps": [
          [
            {
              "name": "wrapper-start-step",
              "template": "wrapper-start-template"
            }
          ],
          [
            {
              "name": "rabbitmq",
              "template": "rabbitmq-template"
            }
          ],
          [
            {
              "name": "first-step-initiator-step",
              "template": "first-step-initiator-template"
            }
          ],
          [
            {
              "name": "first-step-monitor-step",
              "template": "first-step-monitor-template"
            },
            {
              "name": "first-step-worker-step",
              "template": "first-step-worker-template",
              "withSequence": {
                "count": "5"
              }
            }
          ],
          [
            {
              "name": "wrapper-finish-step",
              "template": "wrapper-finish-template"
            }
          ]
        ]
      },
      {
        "name": "exit-handler",
        "steps": [
          [
            {
              "name": "wrapper-fail-step",
              "template": "wrapper-fail-template",
              "when": "{{workflow.status}} != Succeeded"
            }
          ]
        ]
      },
      {
        "name": "wrapper-start-template",
        "container": {
          "image": "hidden/wrapper:latest",
          "imagePullPolicy": "IfNotPresent",
          "command": ["python", "-m", "wrapper"],
          "args": ["--run-phase", "start"]
        },
        "serviceAccountName": "hidden-service-account"
      },
      {
        "name": "wrapper-fail-template",
        "container": {
          "image": "hidden/wrapper:latest",
          "imagePullPolicy": "IfNotPresent",
          "command": ["python", "-m", "wrapper"],
          "args": ["--run-phase", "fail"]
        },
        "serviceAccountName": "hidden-service-account"
      },
      {
        "name": "first-step-initiator-template",
        "container": {
          "image": "hidden/first-step:latest",
          "imagePullPolicy": "IfNotPresent",
          "command": ["python", "-m", "first-step"],
          "args": ["--runner", "initiator"]
        },
        "serviceAccountName": "hidden-service-account"
      },
      {
        "name": "first-step-worker-template",
        "container": {
          "image": "hidden/first-step:latest",
          "imagePullPolicy": "IfNotPresent",
          "command": ["python", "-m", "first-step"],
          "args": ["--runner", "worker"]
        },
        "serviceAccountName": "hidden-service-account",
        "retryStrategy": {
          "limit": "3"
        }
      },
      {
        "name": "first-step-monitor-template",
        "container": {
          "image": "hidden/first-step:latest",
          "imagePullPolicy": "IfNotPresent",
          "command": ["python", "-m", "first-step"],
          "args": ["--runner", "monitor"]
        },
        "serviceAccountName": "hidden-service-account"
      },
      {
        "name": "rabbitmq-template",
        "container": {
          "image": "rabbitmq:3.11.2-alpine",
          "name": "rabbitmq",
          "ports": [
            {
              "containerPort": 5672
            }
          ]
        },
        "daemon": true
      },
      {
        "name": "wrapper-finish-template",
        "container": {
          "image": "hidden/wrapper:latest",
          "imagePullPolicy": "IfNotPresent",
          "command": ["python", "-m", "wrapper"],
          "args": ["--run-phase", "finish"]
        },
        "serviceAccountName": "hidden-service-account"
      }
    ]
  }
}
```

### Logs from the workflow controller

```text
.
```

### Logs from in your workflow's wait container

```text
.
```
