### ISSUE TITLE
argo-server: Blank page

### ISSUE THREAD

**Issue by dgouju** [argoproj/argo-workflows#10290]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When I connect to the Ingress controller LB, I get a blank page named Argo. Page code is the following:
`<!doctype html><html lang="en"><head><meta charset="UTF-8"><title>Argo</title><base href="/argo/"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><link rel="icon" type="image/png" href="assets/favicon/favicon-32x32.png" sizes="32x32"><link rel="icon" type="image/png" href="assets/favicon/favicon-16x16.png" sizes="16x16"></head><body><div id="app"></div><script src="main.70d70011b11b3fd4e4a1.js"></script></body></html>`
main.js is properly downloaded as you can see in those screenshots.
![Screenshot 2022-12-29 10 19 04](https://user-images.githubusercontent.com/16699383/209931425-3265679f-d167-4982-a6fa-c69a66b8bc64.png)
![Screenshot 2022-12-29 10 19 27](https://user-images.githubusercontent.com/16699383/209931441-a0ee621c-008b-47d3-ad0b-33637fe54df2.png)

Am I missing something?

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
- I deployed a fresh install using Quickstart https://argoproj.github.io/argo-workflows/quick-start/#install-argo-workflows , including patching argo-server auth.
- Configured Ingress controller as per documentation https://argoproj.github.io/argo-workflows/argo-server/#ingress
- Disabled TLS https://argoproj.github.io/argo-workflows/tls/#plain-text and patched argo-server deployment to replace HTTPS with HTTP
```

### Logs from the workflow controller

```text
From argo-server instead (doing multiple refreshes):
kubectl -n argo logs argo-server-5f56d69559-gjt4v
time="2022-12-29T09:17:07.135Z" level=info duration="16.58µs" method=GET path=index.html size=0 status=304
time="2022-12-29T09:17:07.393Z" level=info duration="9.81µs" method=GET path=index.html size=0 status=304
time="2022-12-29T09:17:07.537Z" level=info duration="5.86µs" method=GET path=index.html size=0 status=304
time="2022-12-29T09:17:07.721Z" level=info duration="10.61µs" method=GET path=index.html size=0 status=304
time="2022-12-29T09:17:07.887Z" level=info duration="9.38µs" method=GET path=index.html size=0 status=304
time="2022-12-29T09:17:08.047Z" level=info duration="9.83µs" method=GET path=index.html size=0 status=304
time="2022-12-29T09:17:08.250Z" level=info duration="10.12µs" method=GET path=index.html size=0 status=304
time="2022-12-29T09:17:08.365Z" level=info duration="9.47µs" method=GET path=index.html size=0 status=304
time="2022-12-29T09:17:08.546Z" level=info duration="9.3µs" method=GET path=index.html size=0 status=304
time="2022-12-29T09:17:08.711Z" level=info duration="9.77µs" method=GET path=index.html size=0 status=304
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by pedrovillanuevapena** [comment]
@dgouju , how did you solve this problem?  I am facing it now

**Comment by tbernacchi** [comment]
same here

**Comment by tbernacchi** [comment]
same here `v3.5.8`

```
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.8/install.yaml
kubectl set env deployment/argo-server -n argo BASE_HREF=/argo/
```

When I curl it gives `200`, but when I try to open in a Browser it gives me a blank page with `Uncaught SyntaxError: Unexpected number`.

<img width="1312" alt="Screenshot 2024-07-27 at 7 22 08 pm" src="https://github.com/user-attachments/assets/ebc6749e-388e-4b65-9f38-6cb93128fd36">


My ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: self-signed
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: argo-server
  namespace: argo
spec:
  ingressClassName: nginx
  rules:
  - host: mykubernetes.com
    http:
      paths:
      - backend:
          service:
            name: argo-server
            port:
              number: 2746
        path: /argo(/|$)(.*)
        pathType: ImplementationSpecific
```

IDK where to look at it anymore.
