### ISSUE TITLE
The argo agent will request two plugin interfaces at the same time for the same task

### ISSUE THREAD

**Issue by GhangZh** [argoproj/argo-workflows#10304]
If I have two plugins set up at the same time, on ports 4355 and 5678, then the argo agent pod will request the interface of each of these two containers for each task. Is there any way to circumvent this?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-wf-argo-plugin
  namespace: argo
spec:
  arguments: {}
  entrypoint: hello
  podGC:
    strategy: OnPodCompletion
  serviceAccountName: argo
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: taskName
            value: "aaa"
        name: task-packing
        template: test-plugin-one
      - arguments:
          parameters:
          - name: args
            value: "aaa"
        name: async-job-a
        template: test-plugin-two
    inputs: {}
    metadata: {}
    name: hello
    outputs: {}
  - inputs:
      parameters:
      - name: taskName
    metadata: {}
    name: test-plugin-one
    outputs: {}
    plugin:
      test-plugin-one:
        taskName: '{{inputs.parameters.taskName}}'
  - inputs:
      parameters:
      - name: args
    metadata: {}
    name: test-plugin-two
    outputs: {}
    plugin:
      test-plugin-two:
        args: '{{inputs.parameters.args}}'
```
test-plugin-two was listening on port 6789, but instead he requested 4355
![image](https://user-images.githubusercontent.com/92301646/210356631-660370ca-3efb-4e6f-ac7a-fae918229810.png)

**Comment by sarabala1979** [comment]
@GhangZh Did you configure your plugin port on `ExecutorPlugin` `6789`?
https://github.com/argoproj/argo-workflows/blob/master/docs/executor_plugins.md

**Comment by GhangZh** [comment]
> @GhangZh Did you configure your plugin port on `ExecutorPlugin` `6789`? https://github.com/argoproj/argo-workflows/blob/master/docs/executor_plugins.md

Yes, I'm sure, and the plugin works.
```yaml
apiVersion: v1
data:
  sidecar.automountServiceAccountToken: "false"
  sidecar.container: |
    args:
    - test_plugin_two.py
    image: docker.xxx.com/argo-plugins:2023-01-03-16-18
    name: test-plugin-two-plugin
    ports:
    - containerPort: 6789
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 64Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
kind: ConfigMap
metadata:
  labels:
    workflows.argoproj.io/configmap-type: ExecutorPlugin
  name: test-plugin-two-plugin
  namespace: argo
```
argo-agent pod
![image](https://user-images.githubusercontent.com/92301646/210514396-78339d9c-a797-4fa6-87ba-15ba754c8a77.png)
