### ISSUE TITLE
Hope "data-sourcing-and-transformation" accept more inputs type

### ISSUE THREAD

**Issue by leveryd** [argoproj/argo-workflows#10301]
# Summary

from https://argoproj.github.io/argo-workflows/data-sourcing-and-transformation/ ,it seems likes "data-sourcing-and-transformation" can only handle artifacts input.  i hope it can support  parameter input?

# Use Cases

In my case, i want to add prefix to "url" parameter, like below
```
if url.startswith("http") is False:
    url = "http://" + url
```

```
- name: katana-binary-from-one-url  # attention: url must starts with http:// or https://
  inputs:
    parameters:
      - name: url
        valueFrom:
          expression: "inputs.parameters.url"
  container:
    image: xxxxx:v0.0.2
    args:
      - '-v'
      - '-u'
      - {{inputs.parameters.url}}
```

i know i can use a script container to do that, but i think it is too heavy. i just want to evaluate an expression.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
