### ISSUE TITLE
Kubernetes Objects are not deleted

### ISSUE THREAD

**Issue by jomach** [argoproj/argo-workflows#10342]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

We are running argo workflows 3.4.1 and we have following config: 

```
...
     persistence:
      archive: true
      archiveLabelSelector:
        matchLabels:
          workflows.argoproj.io/archive-strategy: always
      archiveTTL: 1d
      connectionPool:
        maxIdleConns: 20
        maxOpenConns: 0
      nodeStatusOffLoad: true
      postgresql:
        database: someDb
        host: #####.rds.amazon.com
        passwordSecret:
          key: POSTGRES_PWD
          name: someName
        port: 5432
        tableName: argo_workflows
        userNameSecret:
          key: POSTGRES_USER
          name: someName
     ttlStrategy:
        secondsAfterCompletion: 86400 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
        secondsAfterSuccess: 86400     # Time to live after workflow is successful
        secondsAfterFailure: 86400     # Time to live after workflow fails
...
```
The persistence and archiving seems to work as I see proper logging messages from the functions archivedWorkflowGarbageCollector and workflowGarbageCollector. 

I think what is not implemented is that argo deletes the workflows objects. 
So when I do `kubectl get wf`  I get workflows with more the 28 Days. 

I think this is a bug.

### Version

3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
None, config
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
