### ISSUE TITLE
Support to set the generateName workflow from WorkflowEventBinding

### ISSUE THREAD

**Issue by LinuxSuRen** [argoproj/argo-workflows#10365]
# Summary

As I mentioned in the title. I wish the workflow name could be more readable.

# Use Cases

I'm using `WorkflowEventBinding` to trigger the `Workflowing` runing when there is a pull-request was created. The event manifest looks like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: my-project
  namespace: default
spec:
  event:
    selector: payload.event_type == "merge_request" && payload.project.name == "my-project" && payload.object_attributes.state == "opened"
  submit:
    workflowTemplateRef:
      name: my-project
    metadata:
      generateName: my-project-{{payload.object_attributes.iid}}
    arguments:
      parameters:
      - name: branch
        valueFrom:
          event: payload.object_attributes.source_branch
      - name: pr
        valueFrom:
          event: payload.object_attributes.iid
```

I found out the controller just discard `generateName`. So all the workflows name look like `my-project-7kc37`.

I perfer the name to be `my-project-pr-123`. A simple solution is to add this feature in [here](https://github.com/argoproj/argo-workflows/blob/1ba8d317113509c48d9a7959f2bee6ee2e812802/server/event/dispatch/operation.go#L143). I'd like to do it if someone believes it's suitable.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
