### ISSUE TITLE
Documentation is not clear about maxDuration in backoffStrategy

### ISSUE THREAD

**Issue by matjanos** [argoproj/argo-workflows#10368]
# Summary

The [documentation about `maxDuration` for `backoffStrategy`](https://www.conventionalcommits.org/en/v1.0.0/) 
is misleading and can be understood as the maximum waiting time between retries.  

Currently documentation says:
```
MaxDuration is the maximum amount of time allowed for the backoff strategy
```

# Use Cases

Some other retrying tools like [Polly](https://github.com/Polly-Contrib/Polly.Contrib.WaitAndRetry#using-the-new-jitter-formula-with-a-large-number-of-retries) uses a parameter `maxDelay` which is similar but means the maximum waiting time between retries regardless of other parameters.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by mayankagarwal2402** [comment]
I had the same confusion, until I learnt it the hard way. The documentation is insufficient and unclear.

Agreed with the `maxDelay` suggestion from @matjanos.
In fact maxDuration would make much more sense if it was moved alongside `limit` as a direct property of `retryStrategy`, and should best work with or without the `backoff` directive, like so:
```yaml
retryStrategy:
  limit: '10'
  maxDuration: 10m
  backoff:
    duration: 10s
    factor: 2
    maxDelay: 1m # good to have
```
and
```yaml
retryStrategy:
  limit: '10'
  maxDuration: 10m
```
