### ISSUE TITLE
Can't use workflow parameters inside `podSpecPatch` resources request with `retryStrategy`

### ISSUE THREAD

**Issue by yonirab** [argoproj/argo-workflows#10362]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Based on the example [here](https://github.com/argoproj/argo-workflows/issues/5471#issuecomment-803729050), I am trying to implement exponentially increasing memory resource requests on retries.
In my case, I need to pass the `quantity` used to specify the resource request as parameters, and to be able to multiply the numeric part of the quantity on each retry. 
So for an initial memory resource request of `100Mi`, I set parameter `memreqnum` to `100`, and parameter `memrequnit` to `Mi`.
Then I thought the following should work:
```yaml
podSpecPatch: '{"containers":[{"name":"main", "resources":{"requests":{"memory": "{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}{{workflow.parameters.memrequnit}}" }}}]}'
```

Unfortunately, this returns the following error:
```
"invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default nodeName="pod-spec-patch-7ccfj(0)"
```

I have dozens of attempts to work around this, but to no avail.
It seems to me that the crux of the problem is that `workflow.parameters.memreqnum` refuses to get cast to an int value.
I have tried with `asInt`, `sprig.int` and `sprig.atoi` - with no success.

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-spec-patch-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: memreqnum
        value: 100
      - name: memrequnit
        value: Mi  
  templates:
  - name: whalesay
    retryStrategy:
      limit: 5
      retryPolicy: Always
    podSpecPatch: '{"containers":[{"name":"main", "resources":{"requests":{"memory": "{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}{{workflow.parameters.memrequnit}}" }}}]}'
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

time="2023-01-16T06:05:36.603Z" level=info msg="Processing workflow" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.607Z" level=info msg="Updated phase  -> Running" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.607Z" level=info msg="Retry node pod-spec-patch-7ccfj initialized Running" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.607Z" level=info msg="Pod node pod-spec-patch-7ccfj-2724657108 initialized Pending" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.608Z" level=error msg="Mark error node" error="invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default nodeName="pod-spec-patch-7ccfj(0)" workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.608Z" level=info msg="node pod-spec-patch-7ccfj-2724657108 phase Pending -> Error" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.608Z" level=info msg="node pod-spec-patch-7ccfj-2724657108 message: invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.608Z" level=info msg="node pod-spec-patch-7ccfj-2724657108 finished: 
2023-01-16 06:05:36.608437542 +0000 UTC" namespace=default workflow=pod-spec-patch-7ccfj       
time="2023-01-16T06:05:36.608Z" level=info msg="1 child nodes of pod-spec-patch-7ccfj failed. Trying again..." namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.608Z" level=info msg="Pod node pod-spec-patch-7ccfj-2120515729 initialized Pending" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.609Z" level=error msg="Mark error node" error="invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default nodeName="pod-spec-patch-7ccfj(1)" workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.609Z" level=info msg="node pod-spec-patch-7ccfj-2120515729 phase Pending -> Error" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.609Z" level=info msg="node pod-spec-patch-7ccfj-2120515729 message: invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.609Z" level=info msg="node pod-spec-patch-7ccfj-2120515729 finished: 
2023-01-16 06:05:36.609705202 +0000 UTC" namespace=default workflow=pod-spec-patch-7ccfj       
time="2023-01-16T06:05:36.609Z" level=info msg="2 child nodes of pod-spec-patch-7ccfj failed. Trying again..." namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.610Z" level=info msg="Pod node pod-spec-patch-7ccfj-2254589586 initialized Pending" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.610Z" level=error msg="Mark error node" error="invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default nodeName="pod-spec-patch-7ccfj(2)" workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.610Z" level=info msg="node pod-spec-patch-7ccfj-2254589586 phase Pending -> Error" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.610Z" level=info msg="node pod-spec-patch-7ccfj-2254589586 message: invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.610Z" level=info msg="node pod-spec-patch-7ccfj-2254589586 finished: 
2023-01-16 06:05:36.610709661 +0000 UTC" namespace=default workflow=pod-spec-patch-7ccfj       
time="2023-01-16T06:05:36.610Z" level=info msg="3 child nodes of pod-spec-patch-7ccfj failed. Trying again..." namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.610Z" level=info msg="Pod node pod-spec-patch-7ccfj-576680591 initialized Pending" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.611Z" level=error msg="Mark error node" error="invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default nodeName="pod-spec-patch-7ccfj(3)" workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.611Z" level=info msg="node pod-spec-patch-7ccfj-576680591 phase Pending -> Error" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.611Z" level=info msg="node pod-spec-patch-7ccfj-576680591 message: invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.611Z" level=info msg="node pod-spec-patch-7ccfj-576680591 finished: 2023-01-16 06:05:36.611524891 +0000 UTC" namespace=default workflow=pod-spec-patch-7ccfj        
time="2023-01-16T06:05:36.611Z" level=info msg="4 child nodes of pod-spec-patch-7ccfj failed. Trying again..." namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.611Z" level=info msg="Pod node pod-spec-patch-7ccfj-4200396032 initialized Pending" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.612Z" level=error msg="Mark error node" error="invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default nodeName="pod-spec-patch-7ccfj(4)" workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.612Z" level=info msg="node pod-spec-patch-7ccfj-4200396032 phase Pending -> Error" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.612Z" level=info msg="node pod-spec-patch-7ccfj-4200396032 message: invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.612Z" level=info msg="node pod-spec-patch-7ccfj-4200396032 finished: 
2023-01-16 06:05:36.612364211 +0000 UTC" namespace=default workflow=pod-spec-patch-7ccfj       
time="2023-01-16T06:05:36.612Z" level=info msg="5 child nodes of pod-spec-patch-7ccfj failed. Trying again..." namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.612Z" level=info msg="Pod node pod-spec-patch-7ccfj-643496877 initialized Pending" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=error msg="Mark error node" error="invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default nodeName="pod-spec-patch-7ccfj(5)" workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="node pod-spec-patch-7ccfj-643496877 phase Pending -> Error" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="node pod-spec-patch-7ccfj-643496877 message: invalid podSpecPatch \"{\\\"containers\\\":[{\\\"name\\\":\\\"main\\\",\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"{{=(2 ** asInt(retries)) * asInt(workflow.parameters.memreqnum)}}Mi\\\"}}}]}\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="node pod-spec-patch-7ccfj-643496877 finished: 2023-01-16 06:05:36.613369581 +0000 UTC" namespace=default workflow=pod-spec-patch-7ccfj        
time="2023-01-16T06:05:36.613Z" level=info msg="No more retries left. Failing..." namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="node pod-spec-patch-7ccfj phase Running -> Error" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="node pod-spec-patch-7ccfj message: No more retries left" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="node pod-spec-patch-7ccfj finished: 2023-01-16 
06:05:36.613613061 +0000 UTC" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg=reconcileAgentPod namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="Updated message  -> No more retries left" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="Marking workflow completed" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="Marking workflow as pending archiving" namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.613Z" level=info msg="Checking daemoned children of " namespace=default workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.619Z" level=info msg="cleaning up pod" action=deletePod key=default/pod-spec-patch-7ccfj-1340600742-agent/deletePod
time="2023-01-16T06:05:36.622Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=585790368 workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.651Z" level=info msg="archiving workflow" namespace=default uid=9a070604-c9ce-45ce-b7d2-67281cef20d0 workflow=pod-spec-patch-7ccfj
time="2023-01-16T06:05:36.676Z" level=info msg="Queueing Error workflow default/pod-spec-patch-7ccfj for delete in 10h0m0s due to TTL"
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

No resources found in argo namespace.
```

**Comment by eduardodbr** [comment]
Hi @yonirab 

there are two issues here:

first, you should use `int()` to convert a string to an integer, as shown here: https://expr-lang.org/docs/language-definition#int

```
podSpecPatch: '{"containers":[{"name":"main", "resources":{"requests":{"memory": "{{=(2 ** int(retries)) * int(workflow.parameters.memreqnum)}}{{workflow.parameters.memrequnit}}" }}}]}'
```

however, that doesn't not seem to work because when the parameters  are substituted the `retry` value isn't available and when the `retry` is injected the `workflow.parameters` are not available. I can try to fix this.

**Comment by yonirab** [comment]
Wow, thanks so much @eduardodbr and @agilgur5 !
I'm definitely looking forward to trying this out!

**Comment by agilgur5** [comment]
all credit to @eduardodbr, he made reviewing it pretty easy 🙂

**Comment by EladProject** [comment]
Hi @eduardodbr 
This doesn't seem to work when I use "inputs.parameters.memreqnum" instead of "workflow.parameters.memreqnum".

**Comment by yonirab** [comment]
@eduardodbr @agilgur5  As mentioned by @EladProject , this only seems to work if the memory request is passed as a workflow parameter via `workflow.parameters.memreqnum`. 
But to be of use in a workflow with multiple steps, it is necessary to be able to calculate the memory request based on an expression that involves both {{retries}} and `inputs.parameters.memreqnum` too, and that does not seem to be working.

Any chance there might be some workaround / simple fix to enable that?

**Comment by eduardodbr** [comment]
input.parameters should be a global param as well as workflow.parameter, can you give me an example demonstrating the issue please?

**Comment by EladProject** [comment]
Sure,

This works:    `memory: "{{= (sprig.int(retries)+1)* sprig.int(workflow.parameters.memreqnum)}}Gi"`
This doesn't: `memory: "{{= (sprig.int(retries)+1)* sprig.int(inputs.parameters.memreqnum)}}Gi"`
(the error is "Error applying PodSpecPatch")

And just to verify that inputs.parameters.memreqnum is defined correctly,
This also works: `memory: "{{= 1* sprig.int(inputs.parameters.memreqnum)}}Gi"`

**Comment by yonirab** [comment]
@eduardodbr Here is a workflow that demonstrates the problem. This fails immediately with message: `Error applying PodSpecPatch`:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-
spec:
  entrypoint: wf
  templates:
  - name: wf
    steps:

    - - name: run-task1
        template: run-task
        arguments:
          parameters:
            - name: memreqnum
              value: '25'
            - name: memrequnit
              value: Mi
            - name: message
              value: "hello from run-task1"

      - name: run-task2
        template: run-task
        arguments:
          parameters:
            - name: memreqnum
              value: '300'
            - name: memrequnit
              value: Mi
            - name: message
              value: "hello from run-task2"
 

  - name: run-task
    inputs:
      parameters:
        - name: memreqnum
        - name: memrequnit
        - name: message
    retryStrategy:
      limit: "2"
      retryPolicy: "Always"
      expression: 'lastRetry.status == "Error" or (lastRetry.status == "Failed" and asInt(lastRetry.exitCode) not in [1,2,127])'
    podSpecPatch: |
      containers:
      - name: main
        resources:
          requests:
            memory: "{{= (sprig.int(retries)+1)* sprig.int(inputs.parameters.memreqnum)}}{{inputs.parameters.memrequnit}}"
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]

```
