### ISSUE TITLE
add GCS service account permissions needed for Configuring an Artifact Repository on Google Cloud

### ISSUE THREAD

**Issue by rupert648** [argoproj/argo-workflows#10369]
# Summary

Add documentation listing the service account permissions needed by the argo workflow in order to upload and pull artifacts to and from GCS.

Currently the easiest way I could find to discover the permissions necessary was through educated guess work and trial and error. Explicit permissions in the documentation could help make this easier.

# Use Cases

When would you use this?

For example, in the following artifact configuration
```yaml
artifacts:
  - name: message
    path: /tmp/message
    gcs:
      bucket: my-bucket-name
      key: path/in/bucket
      # serviceAccountKeySecret is a secret selector.
      # It references the k8s secret named 'my-gcs-credentials'.
      # This secret is expected to have have the key 'serviceAccountKey',
      # containing the base64 encoded credentials
      # to the bucket.
      #
      # If it's running on GKE and Workload Identity is used,
      # serviceAccountKeySecret is not needed.
      serviceAccountKeySecret:
        name: my-gcs-credentials
        key: serviceAccountKey
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
