### ISSUE TITLE
GET /api/v1/cron-workflows/{namespace} "items" property could be null

### ISSUE THREAD

**Issue by imjulioc** [argoproj/argo-workflows#10376]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

The [swagger definition](https://github.com/argoproj/argo-workflows/blob/1ba8d317113509c48d9a7959f2bee6ee2e812802/api/jsonschema/schema.json#L4446) for /api/v1/cron-workflows/{namespace} mentions that "items" is an array but it also can be "null" using the query "listOptions.labelSelector".

![image](https://user-images.githubusercontent.com/63888039/213585155-2e3c098b-3729-4f48-bbca-53e4660c68a7.png)
![Screenshot from 2023-01-19 17-25-43](https://user-images.githubusercontent.com/63888039/213585071-e7f7ee78-e47c-4b6e-8eba-a2d97ccebf7b.png)

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
{
    "apiVersion": "argoproj.io/v1alpha1",
    "kind": "Workflow",
    "metadata": {
      "generateName": "hello-world-",
      "labels": {
        "workflows.argoproj.io/archive-strategy": "false"
      }
    },
    "spec": {
      "entrypoint": "whalesay",
      "templates": [
        {
          "container": {
            "args": [
              "echo 'hello world'"
            ],
            "command": [
              "ash",
              "-c"
            ],
            "image": "alpine:3.15",
            "imagePullPolicy": "IfNotPresent"
          },
          "name": "whalesay"
        }
      ]
    }
  }
```

### Logs from the workflow controller

```text
No required
```

### Logs from in your workflow's wait container

```text
No required
```
