### ISSUE TITLE
Output artifact compressed even when `archive: none: {}`

### ISSUE THREAD

**Issue by casperakos** [argoproj/argo-workflows#10394]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When I'm using `archive: none {}`, this setting is not respected and the output still getting compressed.

### Version

3.3.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
kind: Workflow
metadata:
  generateName: artifact-disable-archive-
spec:
  entrypoint: artifact-disable-archive
  templates:
  - name: artifact-disable-archive
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          - name: etc
            from: "{{steps.generate-artifact.outputs.artifacts.etc}}"
          - name: hello-txt
            from: "{{steps.generate-artifact.outputs.artifacts.hello-txt}}"
          - name: hello-txt-nc
            from: "{{steps.generate-artifact.outputs.artifacts.hello-txt-nc}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt | tee /tmp/hello_world_nc.txt ; sleep 1"]
    outputs:
      artifacts:
      - name: etc
        path: /etc
        archive:
          none: {}
      - name: hello-txt
        path: /tmp/hello_world.txt
        archive:
          none: {}
      - name: hello-txt-nc
        path: /tmp/hello_world_nc.txt
        archive:
          tar:
            # no compression (also accepts the standard gzip 1 to 9 values)
            compressionLevel: 0

  - name: print-message
    inputs:
      artifacts:
      - name: etc
        path: /tmp/etc
      - name: hello-txt
        path: /tmp/hello.txt
      - name: hello-txt-nc
        path: /tmp/hello_nc.txt
    container:
      image: alpine:latest
      command: [sh, -c]
      args:
      - cat /tmp/hello.txt && cat /tmp/hello_nc.txt && cd /tmp/etc && find .
```

### Logs from the workflow controller

```text
time="2023-01-24T09:53:24.054Z" level=info msg="sub-process exited" argo=true error="<nil>"
time="2023-01-24T09:53:24.054Z" level=info msg="/etc -> /var/run/argo/outputs/artifacts/etc.tgz" argo=true
time="2023-01-24T09:53:24.055Z" level=info msg="Taring /etc"
time="2023-01-24T09:53:24.118Z" level=info msg="archived 1093 files/dirs in /etc"
time="2023-01-24T09:53:24.119Z" level=info msg="/tmp/hello_world.txt -> /var/run/argo/outputs/artifacts/tmp/hello_world.txt.tgz" argo=true
time="2023-01-24T09:53:24.119Z" level=info msg="Taring /tmp/hello_world.txt"
time="2023-01-24T09:53:24.120Z" level=info msg="/tmp/hello_world_nc.txt -> /var/run/argo/outputs/artifacts/tmp/hello_world_nc.txt.tgz" argo=true
time="2023-01-24T09:53:24.120Z" level=info msg="Taring /tmp/hello_world_nc.txt"
```

The /etc folder is also being archived where it should not.
