### ISSUE TITLE
Allow setting namespace when submitting a ClusteWorkflowTemplate from the UI

### ISSUE THREAD

**Issue by igorcalabria** [argoproj/argo-workflows#10398]
# Summary

Currently, there's no way (or I haven't found one) to set the workflow namespace when submitting a `ClusterWorkflowTemplate` from the UI.

# Use Cases

A template may be submitted in different namespaces depending on which team/access/whatever is needed for that template. This is equivalent of doing 

```
argo submit --from clusterworkflowtemplate/my-template -n my-choosen-namespace
```
Current workaround is creating a WorkflowTemplate in each namespace, but that's really clunky.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by sahil-sharma** [comment]
This could be useful when you a common workflow for different teams like regular data backup scripts where they have to simply select the `service_name` as namespace and the workflow would get executed in the selected `service_namespace`.
I tried something like this but everytime it is being deployed in `default` namespace.
```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: my-cluster-workflow-template
spec:
  entrypoint: my-job-template
  templates:
    - name: my-job-template
      inputs:
        parameters:
          - name: namespace
            description: "This is where the workflow will get executed."
            default: "backend"
            enum:
              - "serviceA"
              - "serviceB"
              - "serviceC"
            valueFrom:
              supplied: {}
          - name: message
            value: "Hello, World!"
      script:
        image: alpine:latest
        command: ["sh"]
        source: |
          "echo {{inputs.parameters.message}} from selected {{inputs.parameters.namespace}}."
      namespace: "demo-{{inputs.parameters.namespace}}"
ttlStrategy:
  secondsAfterCompletion: 300
podGC:
  strategy: OnPodCompletion
```
Can someone reproduce this? There is no specific ClusterRole(or RoleBindings) were created. Going with the default helm set-up.
