### ISSUE TITLE
Error to update - Argo-Workflow V3.4.4

### ISSUE THREAD

**Issue by paologodinho** [argoproj/argo-workflows#10428]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I was trying to update my Argo-Workflow from V3.0.2 to 3.4.4 but I'm facing a lot of issues.

$ kubectl get pod -n argo

NAME                                                                                                   READY   STATUS                    RESTARTS   AGE
argo-prod-argo-workflows-server-85689949c8-n8dk5                         0/1       CrashLoopBackOff   13             42m
argo-prod-argo-workflows-workflow-controller-6668cdf444-9wgg8   0/1       CrashLoopBackOff   13         -  42m

I'm receiving the follow error:

kubectl logs -n argo argo-xxx-argo-workflows-server-xxxxxxxx  -f
time="2023-01-30T15:33:03.528Z" level=info msg="not enabling pprof debug endpoints"
time="2023-01-30T15:33:03.529Z" level=info authModes="[client]" baseHRef=/ managedNamespace=argo namespace=argo secure=true ssoNamespace=argo
time="2023-01-30T15:33:03.529Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode"
time="2023-01-30T15:33:03.529Z" level=info msg="SSO disabled"
time="2023-01-30T15:33:03.540Z" level=fatal msg="error unmarshaling JSON: while decoding JSON: json: unknown field \"containerRuntimeExecutor\""

I revolved this issue commenting:

the lines on my workflow-controller-config-map.yaml:

#containerRuntimeExecutor: {{ .Values.controller.containerRuntimeExecutor }}
#{{- with .Values.controller.containerRuntimeExecutors }}
#containerRuntimeExecutors:
#{{- toYaml . | nindent 6 }}
#{{- end }}

But now, we are receiving other error:

$ kubectl logs -n argo argo-prod-argo-workflows-server-85689949c8-n8dk5  -f
time="2023-01-30T15:54:35.533Z" level=info msg="not enabling pprof debug endpoints"
time="2023-01-30T15:54:35.533Z" level=info authModes="[client]" baseHRef=/ managedNamespace=argo namespace=argo secure=true ssoNamespace=argo
time="2023-01-30T15:54:35.533Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode"
time="2023-01-30T15:54:35.534Z" level=info msg="SSO disabled"
time="2023-01-30T15:54:35.637Z" level=fatal msg="error unmarshaling JSON: while decoding JSON: json: unknown field \"portName\""

### Version

3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
controller:
  image:
    registry: quay.io
    repository: argoproj/workflow-controller
    tag: v3.4.4
  parallelism:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  podLabels: {}
  podSecurityContext: {}
  # podPortName: http
  metricsConfig:
    enabled: true
    path: /metrics
    port: 9090
    servicePort: 8080
    servicePortName: metrics
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  persistence:
  # connectionPool:
  #   maxIdleConns: 100
  #   maxOpenConns: 0
  # nodeStatusOffLoad: false
    archive: true
  # DEFINED IN THE SECRETS.YAML FILE  
  # postgresql:
  #   host: localhost
  #   port: 5432
  #   database: postgres
  #   tableName: argo_workflows
  #   # the database secrets must be in the same namespace of the controller
  #   userNameSecret:
  #     name: argo-postgres-config
  #     key: username
  #   passwordSecret:
  #     name: argo-postgres-config
  #     key: password
  workflowDefaults: {} # Only valid for 2.7+
  #  spec:
  #    ttlStrategy:
  #      secondsAfterCompletion: 84600
  # workflowWorkers: 32
  # podWorkers: 32
  workflowRestrictions: {} # Only valid for 2.9+
  #  templateReferencing: Strict|Secure
  telemetryConfig:
    enabled: false
    path: /telemetry
    port: 8081
    servicePort: 8081
    servicePortName: telemetry
  serviceMonitor:
    enabled: false
    additionalLabels: {}
  serviceAccount:
    create: true
    name: argo
    # Annotations applied to created service account
    annotations: {}
  name: workflow-controller
  workflowNamespaces:
    - argo
  containerRuntimeExecutor: docker
  instanceID:
    # `instanceID.enabled` configures the controller to filter workflow submissions
    # to only those which have a matching instanceID attribute.
    enabled: false
    # NOTE: If `instanceID.enabled` is set to `true` then either `instanceID.userReleaseName`
    # or `instanceID.explicitID` must be defined.
    # useReleaseName: true
    # explicitID: unique-argo-controller-identifier
  logging:
    level: info
    globallevel: "0"
  serviceType: ClusterIP
  # Annotations to be applied to the controller Service
  serviceAnnotations: {}
  # Optional labels to add to the controller Service
  serviceLabels: {}
  # Source ranges to allow access to service from. Only applies to
  # service type `LoadBalancer`
  loadBalancerSourceRanges: []
  resources:
    limits:
      cpu: 256m
      memory: 512Mi

  ## Extra environment variables to provide to the controller container
  ## extraEnv:
  ##   - name: FOO
  ##     value: "bar"
  extraEnv: []

  # Extra arguments to be added to the controller
  extraArgs: []
  replicas: 1
  pdb:
    enabled: false
    # minAvailable: 1
    # maxUnavailable: 1
  ## Node selectors and tolerations for server scheduling to nodes with taints
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Leverage a PriorityClass to ensure your pods survive resource shortages
  # ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
  # PriorityClass: system-cluster-critical
  priorityClassName: cluster-runtime
  # https://argoproj.github.io/argo-workflows/links/
  links: []
  clusterWorkflowTemplates:
    # Create a ClusterRole and CRB for the controller to access ClusterWorkflowTemplates.
    enabled: true
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

kubectl logs -n argo argo-xxx-argo-workflows-workflow-controller-xxxxxxxxx-xxxx  -f
time="2023-01-30T16:26:08Z" level=info msg="index config" indexWorkflowSemaphoreKeys=true
time="2023-01-30T16:26:08Z" level=info msg="cron config" cronSyncPeriod=10s
time="2023-01-30T16:26:08Z" level=info msg="Memoization caches will be garbage-collected if they have not been hit after" gcAfterNotHitDuration=30s
time="2023-01-30T16:26:08.330Z" level=info msg="not enabling pprof debug endpoints"
time="2023-01-30T16:26:08.338Z" level=info msg="Get configmaps 200"
time="2023-01-30T16:26:08.341Z" level=fatal msg="Failed to register watch for controller config map: error unmarshaling JSON: while decoding JSON: json: unknown field \"portName\""
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
