### ISSUE TITLE
failed to parse private key: asn1: syntax error: sequence truncated

### ISSUE THREAD

**Issue by yktakaha4** [argoproj/argo-workflows#10420]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Thanks for the great software.

After reading [this document](https://argoproj.github.io/argo-workflows/argo-server-sso/#to-start-argo-server-with-sso), I have defined a Secret named `sso` to provide the values of `client-id-secret` and `client-secret-secret` in a single Secret, which caused the following error when installing argo-workflows.

```
$ kubectl logs -n argo deploy/argo-workflows-server
time="2023-01-29T16:14:56.538Z" level=info msg="not enabling pprof debug endpoints"
time="2023-01-29T16:14:56.538Z" level=info authModes="[sso]" baseHRef=/ managedNamespace= namespace=argo secure=false ssoNamespace=argo
time="2023-01-29T16:14:56.538Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo-workflows/tls/"
Error: failed to parse private key: asn1: syntax error: sequence truncated
failed to parse private key: asn1: syntax error: sequence truncated
```

Part of argo-workflows definition (with helmfile)

```bash
kubectl create secret -n argo generic sso \
    --from-literal=github-client-id=$GITHUB_CLIENT_ID \
    --from-literal=github-client-secret=$GITHUB_CLIENT_SECRET
```

```yaml
  - name: argo-workflows
    namespace: argo
    chart: argo/argo-workflows
    version: 0.22.8
    values:
    - images:
        tag: v3.4.4
    - workflow:
        serviceAccount:
          create: true
          name: argo-workflow-default-sa
          annotations:
            workflows.argoproj.io/rbac-rule: "true"
            workflows.argoproj.io/rbac-rule-precedence: "0"
        rbac:
          create: true
    - server:
        extraArgs:
        - --auth-mode=sso
        sso:
          issuer: http://dex.argo.svc.cluster.local:5556
          clientId:
            name: sso
            key: github-client-id
          clientSecret:
            name: sso
            key: github-client-secret
          redirectUrl: http://localhost:2746/oauth2/callback
          rbac:
            enabled: true
```

I believe it would be better to provide a more clear message to users.
I would like to create a PR.

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
None
```

### Logs from the workflow controller

```text
None
```

### Logs from in your workflow's wait container

```text
None
```
