### ISSUE TITLE
Customizable Argo UI (navigation links, custom columns)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#10447]
# Summary

Many users use Argo Workflows for their CI or other application purposes (AI/ML). However, the UI does not lend itself to any specific application use case. It is a generic UI that allows you to do very generic things: filter on labels, namespace, etc... However, end users who might be visiting the Argo Workflows UI may not know where to start or how to use the UI to get to the filtered or curated view they are looking for.

This enhancement proposal is to allow **_workflow administrators_** to customize the UI in a couple of ways:
* providing tabs/links at the top of the interface which makes it obvious for their own users to navigate to curated/filtered views
* allowing the workflow administrator to customize the **_columns_** shown on the list view so that users can discern different workflow categories, e.g. by labels

# Use Cases

When would you use this?

For someone using workflows as CI, they could create various navigation links with predefined filters for their users, e.g.
* `Guestbook Builds`
* `Sockshop Builds`

These links would be predefined with filters based on labels that they choose in their environment. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by jessesuen** [comment]
Spoke with @alexec yesterday and he was supportive of the feature. @rbreeze and @jiachengxu will find time to work on this in the coming weeks.

**Comment by jessesuen** [comment]
@jiachengxu - can you comment on this issue so I can add you as an assignee?

**Comment by jiachengxu** [comment]
@jessesuen thank you! Looking forward to working on it!

**Comment by rbreeze** [comment]
Proposed CM settings structure:

```yaml
# These will be exposed as buttons in the top bar of the UI
customLinks:
  - url: http://localhost:8080/workflows?label=my.custom.label%foo
    name: My Custom Label

# These will be exposed as columns in the Workflow List View
exposeColumns:
  - key: my.custom.label
    name: Custom Label
```
