### ISSUE TITLE
Get s3 folder recursively 

### ISSUE THREAD

**Issue by jamborta** [argoproj/argo-workflows#1045]
Hi,

I am trying to use the `artifacts` feature to download a folder from an s3 bucket, specified as follows:

```
    inputs:
      artifacts:
      - name: model-artifacts
        path: /s3/
        archive:
          none: {}
        s3:
          endpoint: s3.amazonaws.com
          bucket: "{{workflow.parameters.s3-bucket}}"
          key: "{{workflow.parameters.s3-key-model}}/model-train-j7r7b/"
          accessKeySecret:
            name: aws-credentials
            key: accessKey
          secretKeySecret:
            name: aws-credentials
            key: secretKey
```

This code runs, but it creates an empty file in the container:

```
/ # ls -alh /s3
-rw-------    1 root     root           0 Oct 15 11:04 /s3
```

Not sure if it is a bug, or the config file is not correct, as it only works if I point it to a `tar.gz` file.
