### ISSUE TITLE
Please provide a way to define constants

### ISSUE THREAD

**Issue by johnlinp** [argoproj/argo-workflows#10455]
# Summary

I wish that Argo Workflow provides a way to define constants, so I can use it across the whole Workflow/WorkflowTemplate.

# Use Cases

Take this WorkflowTemplate as an example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: process-data
spec:
  templates:
    - name: main
      inputs:
        artifacts:
          - name: inputDataFile
      outputs:
        artifacts:
          - name: outputDataFile
            from: "{{steps.write-data-step.outputs.artifacts.destinationDataFile}}"
      steps:
        - - name: load-data-step
            templateRef:
              name: data-utils
              template: load-data
            arguments:
              parameters:
                - name: destinationDatabaseConnectInfo
                  value:
                    host: database.example.com
                    port: 5566
                    vendor: postgresql
                    username: postgres
                    password: somepass
              artifacts:
                - name: sourceDataFile
                   from: "{{inputs.artifacts.inputDataFile}}"
        - - name: clean-data-step
            templateRef:
              name: data-utils
              template: clean-data
            arguments:
              parameters:
                - name: databaseConnectInfo
                  value:
                    host: database.example.com
                    port: 5566
                    vendor: postgresql
                    username: postgres
                    password: somepass
        - - name: convert-data-step
            templateRef:
              name: data-utils
              template: convert-data
            arguments:
              parameters:
                - name: databaseConnectInfo
                  value:
                    host: database.example.com
                    port: 5566
                    vendor: postgresql
                    username: postgres
                    password: somepass
        - - name: write-data-step
            templateRef:
              name: data-utils
              template: write-data
            arguments:
              parameters:
                - name: sourceDatabaseConnectInfo
                  value:
                    host: database.example.com
                    port: 5566
                    vendor: postgresql
                    username: postgres
                    password: somepass
  ...
  entrypoint: main
```

In the above example, the input parameter of database connection information (as `databaseConnectInfo`, `destinationDatabaseConnectInfo`, `sourceDatabaseConnectInfo`) are all the same and repeating multiple times. I wish I can define it as a constant only once and use it everywhere, like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: process-data
spec:
  constants:
    parameters:
      databaseConnectInfo:
        value:
          host: database.example.com
          port: 5566
          vendor: postgresql
          username: postgres
          password: somepass
  templates:
    - name: main
      inputs:
        artifacts:
          - name: inputDataFile
      outputs:
        artifacts:
          - name: outputDataFile
            from: "{{steps.write-data-step.outputs.artifacts.destinationDataFile}}"
      steps:
        - - name: load-data-step
            templateRef:
              name: data-utils
              template: load-data
            arguments:
              parameters:
                - name: destinationDatabaseConnectInfo
                  value: "{{constants.parameters.databaseConnectInfo}}"
              artifacts:
                - name: sourceDataFile
                   from: "{{inputs.artifacts.inputDataFile}}"
        - - name: clean-data-step
            templateRef:
              name: data-utils
              template: clean-data
            arguments:
              parameters:
                - name: databaseConnectInfo
                  value: "{{constants.parameters.databaseConnectInfo}}"
        - - name: convert-data-step
            templateRef:
              name: data-utils
              template: convert-data
            arguments:
              parameters:
                - name: databaseConnectInfo
                  value: "{{constants.parameters.databaseConnectInfo}}"
        - - name: write-data-step
            templateRef:
              name: data-utils
              template: write-data
            arguments:
              parameters:
                - name: sourceDatabaseConnectInfo
                  value: "{{constants.parameters.databaseConnectInfo}}"
  ...
  entrypoint: main
```

I know that I can define it as an input with a default value and reference it like it's a constant. However, it would make the caller of the WorkflowTemplate able to change it. I want to keep the database connect info as an internal implementation detail and don't want the caller to touch it.

Please let me know if there's a better way to do it. Thank you.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
