### ISSUE TITLE
failed to resolve parameters in `withParam` expression

### ISSUE THREAD

**Issue by Nizar-opt** [argoproj/argo-workflows#10462]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I wanted to use `withParam` but with a generated JSON with the help of expression & sprig functions. The below example works as expected.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  arguments:
    parameters:
      - name: chunk
        value: 20
  templates:
  - name: loop-example
    steps:
    - - name: print-message
        template: whalesay
        arguments:
          parameters:
          - name: start
            value: "{{item.start}}"
          - name: end
            value: "{{item.end}}"
        withParam: >-
          {{=
            toJson(
              map(sprig.untilStep(0,100,20), { {start: #, end: # + 20 } })
            )
            }}

  - name: whalesay
    inputs:
      parameters:
      - name: start
      - name: end
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["start: ","{{inputs.parameters.start}}", " | end: ", "{{inputs.parameters.end}}"]

```

But..
when I started to parametrize it by replacing `sprig.untilStep(0,100,20)` with `sprig.untilStep(0,100,workflow.parameters.chunk)`, It always failed with the following error:

```
withParam value could not be parsed as a JSON list: {{= toJson( map(sprig.untilStep(0,100,workflow.parameters.chunk), { {start: #, end: # + 20 } }) ) }}: invalid character '{' looking for beginning of object key string
```
as you can see, it does not resolve the parameter `workflow.parameters.chunk`. I also tried `inputs.parameters` & `steps.**.outputs.result`

Here is an example that would fail.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  arguments:
    parameters:
      - name: chunk
        value: 20
  templates:
  - name: loop-example
    steps:
    - - name: print-message
        template: whalesay
        arguments:
          parameters:
          - name: start
            value: "{{item.start}}"
          - name: end
            value: "{{item.end}}"
        withParam: >-
          {{=
            toJson(
              map(sprig.untilStep(0,100,workflow.parameters.chunk), { {start: #, end: # + 20 } })
            )
            }}

  - name: whalesay
    inputs:
      parameters:
      - name: start
      - name: end
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["start: ","{{inputs.parameters.start}}", " | end: ", "{{inputs.parameters.end}}"]

```

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  arguments:
    parameters:
      - name: chunk
        value: 20
  templates:
  - name: loop-example
    steps:
    - - name: print-message
        template: whalesay
        arguments:
          parameters:
          - name: start
            value: "{{item.start}}"
          - name: end
            value: "{{item.end}}"
        withParam: >-
          {{=
            toJson(
              map(sprig.untilStep(0,100,workflow.parameters.chunk), { {start: #, end: # + 20 } })
            )
            }}

  - name: whalesay
    inputs:
      parameters:
      - name: start
      - name: end
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["start: ","{{inputs.parameters.start}}", " | end: ", "{{inputs.parameters.end}}"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

Found 3 pods, using pod/workflow-controller-6c4d6fbd5f-nkqk2

> the workflow fails right away, hence no logs.
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

No resources found in argo namespace.

> the workflow fails right away, hence no logs.
```
