### ISSUE TITLE
Archvie logs in artifact repository (Minio)

### ISSUE THREAD

**Issue by atropos112** [argoproj/argo-workflows#10472]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I recently decided to use minio to store my logs from tasks and potentially artifacts (haven't used it for artifacts just yet). I have noticed in minio in the bucket i provided and the key format there is a file called `main.log` but it only has log from one task not all somehow... (where are all the logs ???)

In addition when i check logs on tasks they are now frequently providing logs of different task, often losing the actual logs of the task (rendering this change net negative for me by far). 

For clarity i am using helm chart for argo workflows and the settings to connect to minio are:
```
  useDefaultArtifactRepo: true
  artifactRepository:
    archiveLogs: true
    s3:
      keyFormat: somename
      accessKeySecret:
        name: awfartifacts
        key: accesskey
      secretKeySecret:
        name: awfartifacts
        key: secretkey
      endpoint: minio.pipelines:9000        #AWS => s3.amazonaws.com; GCS => storage.googleapis.com
      insecure: true         
      bucket: awf
```

i have noticed that this "switch" between logs happens when tasks run in parallel, is it to do with writing to that one log file in parallel that screws things up ? Still baffled as to where the actual logs are kept...  sure as hell not in the minio file...

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
whatever workflow you want, it really isn't workflow dependent. I reproduced it with whalesay example.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```
nothing appears there... other than 
```
level=info msg="Enforcing history limit for 'someworkflow'" namespace=pipelines workflow=someworkflow
```

doubt thats relevant here.

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
The pod (if it still exists) provides correct logs. But thats obviously not the point, I want to be able to delete the pod and still have the logs stashed away in minio.
