### ISSUE TITLE
Wait container failing: 'level=info msg="stopping progress monitor (context done)" error="context canceled"'

### ISSUE THREAD

**Issue by lvijnck** [argoproj/argo-workflows#10490]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I am trying to implement a mechanism to clone a repository and pass it downstream. This has been failing due to the "unable to resolve delta" that was happening in 3.4.4. I just updated to argo v3.4.5.

I am now getting errors on Argo's "wait" container. I performed several tests and concluded the following:

- The repo is succesfully cloned, as the status is correctly displayed
- Error does not happen when I omit the output artifact
- Error does _not_ happen for public repositories (even with output artifact defined)

### Version

v.3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-clone-repo
spec:
  entrypoint: run
  templates:
    - name: run
      inputs:
        parameters:
          artifacts:
          - name: repo-artifact
            path: /src
            git:
              repo: "https://gitlab.com/url"
              revision: "main"
              usernameSecret:
                name: argo-git-creds
                key: username
              passwordSecret:
                name: argo-git-creds
                key: token
      container:
        image: "python:3.9-buster"
        command: [ sh, -c ]
        args: [ "git status && ls && pwd" ]
        workingDir: /src
      outputs:
        artifacts:
          - name: repo-artifact
            path: /src
```

### Logs from the workflow controller

```text
time="2023-02-08T19:14:09.342Z" level=info msg="Processing workflow" namespace=fix-arg-workflows workflow=test-clone-repo-drqpb                                                                                                  │
│ time="2023-02-08T19:14:09.342Z" level=info msg="Task-result reconciliation" namespace=fix-arg-workflows numObjs=0 workflow=test-clone-repo-drqpb                                                                                 │
│ time="2023-02-08T19:14:09.342Z" level=info msg="Pod failed: Error (exit code 2)" displayName=test-clone-repo-drqpb namespace=fix-arg-workflows pod=test-clone-repo-drqpb templateName=run workflow=test-clone-repo-drqpb         │
│ time="2023-02-08T19:14:09.342Z" level=info msg="node changed" namespace=fix-arg-workflows new.message="Error (exit code 2)" new.phase=Error new.progress=0/1 nodeID=test-clone-repo-drqpb old.message= old.phase=Running old.pro │
│ time="2023-02-08T19:14:09.342Z" level=info msg="TaskSet Reconciliation" namespace=fix-arg-workflows workflow=test-clone-repo-drqpb                                                                                               │
│ time="2023-02-08T19:14:09.342Z" level=info msg=reconcileAgentPod namespace=fix-arg-workflows workflow=test-clone-repo-drqpb                                                                                                      │
│ time="2023-02-08T19:14:09.342Z" level=info msg="Updated phase Running -> Error" namespace=fix-arg-workflows workflow=test-clone-repo-drqpb                                                                                       │
│ time="2023-02-08T19:14:09.342Z" level=info msg="Updated message  -> Error (exit code 2)" namespace=fix-arg-workflows workflow=test-clone-repo-drqpb                                                                              │
│ time="2023-02-08T19:14:09.342Z" level=info msg="Marking workflow completed" namespace=fix-arg-workflows workflow=test-clone-repo-drqpb                                                                                           │
│ time="2023-02-08T19:14:09.342Z" level=info msg="Marking workflow as pending archiving" namespace=fix-arg-workflows workflow=test-clone-repo-drqpb                                                                                │
│ time="2023-02-08T19:14:09.342Z" level=info msg="Checking daemoned children of " namespace=fix-arg-workflows workflow=test-clone-repo-drqpb                                                                                       │
│ time="2023-02-08T19:14:09.342Z" level=info msg="Workflow to be dehydrated" Workflow Size=2398                                                                                                                                    │
│ time="2023-02-08T19:14:09.348Z" level=info msg="cleaning up pod" action=deletePod key=fix-arg-workflows/test-clone-repo-drqpb-1340600742-agent/deletePod                                                                         │
│ time="2023-02-08T19:14:09.352Z" level=info msg="Delete pods 404"                                                                                                                                                                 │
│ time="2023-02-08T19:14:09.359Z" level=info msg="Update workflows 200"                                                                                                                                                            │
│ time="2023-02-08T19:14:09.359Z" level=info msg="Workflow update successful" namespace=fix-arg-workflows phase=Error resourceVersion=80452200 workflow=test-clone-repo-drqpb                                                      │
│ time="2023-02-08T19:14:09.359Z" level=info msg="Create events 201"                                                                                                                                                               │
│ time="2023-02-08T19:14:09.371Z" level=info msg="DeleteCollection workflowtaskresults 200"                                                                                                                                        │
│ time="2023-02-08T19:14:09.371Z" level=info msg="Create events 201"                                                                                                                                                               │
│ time="2023-02-08T19:14:09.371Z" level=info msg="archiving workflow" namespace=fix-arg-workflows uid=4621fee1-4e34-46a5-a718-a955b880a4e2 workflow=test-clone-repo-drqpb                                                          │
│ time="2023-02-08T19:14:09.377Z" level=info msg="cleaning up pod" action=labelPodCompleted key=fix-arg-workflows/test-clone-repo-drqpb/labelPodCompleted                                                                          │
│ time="2023-02-08T19:14:09.394Z" level=info msg="Patch pods 200"                                                                                                                                                                  │
│ time="2023-02-08T19:14:09.424Z" level=info msg="Patch workflows 200"                                                                                                                                                             │
│ time="2023-02-08T19:14:12.044Z" level=info msg="Get leases 200"                                                                                                                                                                  │
│ time="2023-02-08T19:14:12.051Z" level=info msg="Update leases 200"                                                                                                                                                               │
│ time="2023-02-08T19:14:17.059Z" level=info msg="Get leases 200"                                                                                                                                                                  │
│ time="2023-02-08T19:14:17.068Z" level=info msg="Update leases 200"                                                                                                                                                               │
│ time="2023-02-08T19:14:18.099Z" level=info msg="Watch workflows 200"                                                                                                                                                             │
│                   
│ time="2023-02-08T19:14:21.086Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=                              │
│ time="2023-02-08T19:14:22.076Z" level=info msg="Get leases 200"                                                                                                                                                                  │
│ time="2023-02-08T19:14:22.083Z" level=info msg="Update leases 200"                                                                                                                                                               │
│ time="2023-02-08T19:14:27.090Z" level=info msg="Get leases 200"                                                                                                                                                                  │
│ time="2023-02-08T19:14:27.096Z" level=info msg="Update leases 200"                                                                                                                                                               │
│ time="2023-02-08T19:14:27.303Z" level=info msg="cleaning up pod" action=killContainers key=fix-arg-workflows/test-clone-repo-drqpb/killContainers                                                                                │
│ time="2023-02-08T19:14:32.111Z" level=info msg="Get leases 200"                                                                                                                                                                  │
│ time="2023-02-08T19:14:32.119Z" level=info msg="Update leases 200"                                                                                                                                                               │
│
```

### Logs from in your workflow's wait container

```text
time="2023-02-08T18:56:22.825Z" level=info msg="Starting Workflow Executor" version=v3.4.5                                                                                                                                       │
│ time="2023-02-08T18:56:22.827Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5                                                                                                         │
│ time="2023-02-08T18:56:22.827Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=fix-arg-workflows podName=test-clone-repo-8nnkq template="{\"name\":\"run\",\ │
│ time="2023-02-08T18:56:22.828Z" level=info msg="Starting deadline monitor"                                                                                                                                                       │
│ time="2023-02-08T18:56:35.829Z" level=info msg="Main container completed" error="<nil>"                                                                                                                                          │
│ time="2023-02-08T18:56:35.829Z" level=info msg="Deadline monitor stopped"                                                                                                                                                        │
│ time="2023-02-08T18:56:35.829Z" level=info msg="stopping progress monitor (context done)" error="context canceled"                                                                                                               │
│ time="2023-02-08T18:56:35.829Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"                                                                                                         │
│ time="2023-02-08T18:56:35.829Z" level=info msg="No output parameters"                                                                                                                                                            │
│ time="2023-02-08T18:56:35.829Z" level=info msg="Saving output artifacts"                                                                                                                                                         │
│ time="2023-02-08T18:56:35.829Z" level=info msg="Staging artifact: repo-artifact"                                                                                                                                                 │
│ time="2023-02-08T18:56:35.829Z" level=info msg="Staging /src from mirrored volume mount /mainctrfs/src"                                                                                                                          │
│ time="2023-02-08T18:56:35.829Z" level=info msg="Taring /mainctrfs/src"                                                                                                                                                           │
│ time="2023-02-08T18:56:46.803Z" level=info msg="archived 651 files/dirs in /mainctrfs/src"                                                                                                                                       │
│ time="2023-02-08T18:56:46.803Z" level=info msg="Successfully staged /src from mirrored volume mount /mainctrfs/src"                                                                                                              │
│ time="2023-02-08T18:56:46.803Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/repo-artifact.tgz, key: fix-arg-workflows/test-clone-repo-8nnkq/test-clone-repo-8nnkq/repo-artifact.tgz"                               │
│ time="2023-02-08T18:56:46.803Z" level=info msg="Creating minio client using IAM role"                                                                                                                                            │
│ time="2023-02-08T18:56:46.811Z" level=info msg="Saving file to s3" bucket=bla-k8s endpoint=s3.amazonaws.com key=fix-arg-workflows/test-clone-repo-8nnkq/test-clone-repo-8nnkq/repo-artifact.tgz path=/tmp/argo/outputs/artifact │
│
```

**Comment by tooptoop4** [comment]
i am getting several "Error (exit code 2)" on v3.4.5 too, but this never happened on v3.4.4

**Comment by lvijnck** [comment]
This is actually not related to the repo artifact, but it seems to be related to artifact passing. I am also getting this on other stuff I am passing through workflows.

How can such big regression come from a new update?

**Comment by sxllwx** [comment]
- #10140 does place constraints on context scope. But I don't think it is caused by this modification.

> `stopping progress monitor (context done)`
- This log is as expected. Happens in this [code snippet](https://github.com/argoproj/argo-workflows/blob/ab178bb0b36a5ce34b4c1302cf4855879a0e8cf5/workflow/executor/executor.go#L1096) whenever wait-container receives `SIGTERM` (kubelet stops pod's Sometimes it will try to send this signal to the container in the Pod https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination ) will trigger.

I think we should pay more attention to the `"unable to resolve delta"` error. We may need the following information to help troubleshoot the problem (information can be desensitized):

- Provide full log of main-container
- Provide the complete yaml of the failed workflow (if it can be reproduced, it will speed up troubleshooting).
- Check whether the configmap of workflow-controller contains `ActiveDeadlineSeconds` related settings,
- Try to rule out whether it is caused by a git server error.

**Comment by tooptoop4** [comment]
@sxllwx i don't have any "unable to resolve delta" messages

**Comment by sxllwx** [comment]
> i am getting several "Error (exit code 2)" on v3.4.5 too (nothing special about the workflows but seems to affect the shorter running ones ie < 30 seconds long, reading inline source artifact i guess s3, not git), but this never happened on v3.4.4
> 
> can see the spike of 100s of instances (appearance of "Error (exit code 2)" in controller logs) of this after upgrading (the 2 bars on right are after upgrade, whereas in 30 days before that only happened 4 times):

> emmm... I'm answering lvijnck's question. 😅

For your case, you can provide the following information for troubleshooting:

1. The log of workflow-controller.
2. (init, main, wait) container related logs.
3. The manifest of the workflow.

**Comment by lvijnck** [comment]
@sxllwx Thanks for the response! Briefly updated the original post. The "unable to resolve reference delta" was in Argo v3.4.4, hence why I updated to 3.4.5. As a current workaround, I have setup a custom template where I implement the cloning myself. 

As soon as I did set this up, my pipeline continued to crash signalling the exit 2 above. Some additional observations:

1. It's not related to the Git input artifact, i.e.,
      - I was successfully able to swap out my repository for another private one
      - I was able to clone any other public repo, e.g., the argo workflows repo and pass it as an artifact
2. It seems to be related to output artifacts
      - When I omit the output artifact I no longer get the error
      - The error is also happening for other steps in my pipeline with output artifacts

I ended up downgrading to v.3.4.4. and the issue was no longer present.

The only log notifications that resembles an error is the following:

```
│ time="2023-02-08T18:56:35.829Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
```

Follow-ups:
  - Workflow above contains full example (only secrets to repo are omitted)
  - Adding the Helm deployment below

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.22.10
    helm:
      releaseName: argo-workflows
      values: |
        server:
          baseHref: /
          extraArgs:
            - --auth-mode=server
        useDefaultArtifactRepo: true
        useStaticCredentials: false
        artifactRepository:
          archiveLogs: true
          s3:
            insecure: false
            bucket: blabla-k8s
            endpoint: s3.amazonaws.com
            region: us-east-2
            keyFormat: "{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
        controller:
          persistence:
            connectionPool:
              maxIdleConns: 100
              maxOpenConns: 0
            nodeStatusOffLoad: true
            # enable archiving of old workflows
            archive: true
            archiveTTL: 90d
            postgresql:
              host: host
              port: 5432
              database: postgres
              tableName: argo_workflows
              # the database secrets must be in the same namespace of the controller
              userNameSecret:
                name: argo-db-creds
                key: username
              passwordSecret:
                name: argo-db-creds
                key: password
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        factor: 2
```
