### ISSUE TITLE
Workflow Archive database connections are not closed

### ISSUE THREAD

**Issue by n1klasD** [argoproj/argo-workflows#10498]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

About two days after upgrading Argo to v3.4.5, my team noticed, that workflows are not archived anymore. 
We are using a Postgres database manged by Azure to archive workflows. 

When digging into the error, we noticed that the number of active connections to our database only increases over time, and eventually hits the limit of active connections. This then results in workflows not being archived anymore.

We did a manual restart of the argo workflows controller, which then closes the connections as expected. 
This was the initial configuration in our configmap that caused the issues: 

``` yaml
persistence:
    archive: true
    nodeStatusOffLoad: true
    postgresql:
      database: argo
      host: ***
      passwordSecret:
        key: ***
        name: ***
      port: ***
      ssl: true
      sslMode: require
      tableName: argo_workflows
```

To resolve the issues, we tried to add the `connectionPool` setting as seen below, but that did not change anything.

``` yaml
persistence:
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
    archive: true
    nodeStatusOffLoad: true
    postgresql:
      database: argo
      host: ***
      passwordSecret:
        key: ***
        name: ***
      port: ***
      ssl: true
      sslMode: require
      tableName: argo_workflows
```

For now we had to revert to argo workflows v3.4.4, and the issue was gone. 

### Version

v.3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Applies to all of our workflows
```

### Logs from the workflow controller

```text
time="2023-02-10T08:50:22.633Z" level=info msg="Enforcing history limit for 'WORKFLOW1'" namespace=NAMESPACE1 workflow=WORKFLOW1
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW2'" namespace=NAMESPACE2 workflow=WORKFLOW2
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW3'" namespace=NAMESPACE3 workflow=WORKFLOW3
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW4'" namespace=NAMESPACE4 workflow=WORKFLOW4
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW5'" namespace=NAMESPACE3 workflow=WORKFLOW5
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW6'" namespace=NAMESPACE2 workflow=WORKFLOW6
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW7'" namespace=NAMESPACE2 workflow=WORKFLOW7
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW8'" namespace=NAMESPACE2 workflow=WORKFLOW8
time="2023-02-10T08:50:22.634Z" level=info msg="Enforcing history limit for 'WORKFLOW9'" namespace=NAMESPACE4 workflow=WORKFLOW9
time="2023-02-10T08:50:25.013Z" level=info msg="Get leases 200"
time="2023-02-10T08:50:25.025Z" level=info msg="Update leases 200"
time="2023-02-10T08:50:27.417Z" level=info msg="Watch configmaps 200"
time="2023-02-10T08:50:29.709Z" level=info msg="List workflows 200"
time="2023-02-10T08:50:30.037Z" level=info msg="Get leases 200"
time="2023-02-10T08:50:30.048Z" level=info msg="Update leases 200"
time="2023-02-10T08:50:32.638Z" level=info msg="Enforcing history limit for 'WORKFLOW1'" namespace=NAMESPACE1 workflow=WORKFLOW1
time="2023-02-10T08:50:32.638Z" level=info msg="Enforcing history limit for 'WORKFLOW2'" namespace=NAMESPACE2 workflow=WORKFLOW2
time="2023-02-10T08:50:32.638Z" level=info msg="Enforcing history limit for 'WORKFLOW3'" namespace=NAMESPACE3 workflow=WORKFLOW3
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW4'" namespace=NAMESPACE4 workflow=WORKFLOW4
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW5'" namespace=NAMESPACE3 workflow=WORKFLOW5
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW6'" namespace=NAMESPACE2 workflow=WORKFLOW6
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW7'" namespace=NAMESPACE2 workflow=WORKFLOW7
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW8'" namespace=NAMESPACE2 workflow=WORKFLOW8
time="2023-02-10T08:50:32.639Z" level=info msg="Enforcing history limit for 'WORKFLOW9'" namespace=NAMESPACE4 workflow=WORKFLOW9
time="2023-02-10T08:50:34.618Z" level=info msg="Watch pods 200"
time="2023-02-10T08:50:35.056Z" level=info msg="Get leases 200"
time="2023-02-10T08:50:35.070Z" level=info msg="Update leases 200"
time="2023-02-10T08:50:35.421Z" level=info msg="Watch workflowtasksets 200"
time="2023-02-10T08:50:40.082Z" level=info msg="Get leases 200"
```

### Logs from in your workflow's wait container

```text
-
```
