### ISSUE TITLE
stages with  Error (exit code 2)

### ISSUE THREAD

**Issue by Guillermogsjc** [argoproj/argo-workflows#10526]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

when upgrading from v3.4.4 to v3.4.5, there are plenty of pods that perform python commands, that fail with exit code 2.

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

an example of a template always failing after the update is

```YAML 
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-backend-task-from-system
  namespace: argo
spec:
  podDisruptionBudget:
    maxUnavailable: 0
  entrypoint: create-backend-task-from-system
  templates:
    - name: create-backend-task-from-system
      nodeSelector:
        kubernetes.io/arch: amd64
      metadata:
        labels:
          workflow-name: "{{workflow.name}}"
          stage-name: "create-backend-task-from-system"
      container:
        image: "{{workflow.parameters.AUXILIAR_CONTAINER_URI}}"
        imagePullPolicy: "{{workflow.parameters.IMAGE_PULL_POLICY}}"
        command: [ python ]
        args: [ "create_backend_task.py",
                "--workflow-name", "{{workflow.name}}",
                "--dataset-id", "{{workflow.parameters.DATASET_ID}}",
                "--backend-task-uuid", "{{workflow.parameters.BACKEND_TASK_UUID}}"
        ]
        envFrom:
          - secretRef:
              name: "{{workflow.parameters.MONGO_DB_SECRET}}"
```

### Logs from the workflow controller

```text
fast rolled back no logs
```

### Logs from in your workflow's wait container

```text
fast rolled back no logs
```

**Comment by darklore** [comment]
I've experienced same error (exit code 2)
In my case the error came from `wait` container of argo workflow.

Here is an extract of a pod status of failed workflow.
```
  - containerID: docker://0cfdc6c085a15931714c56fe4e2fc090dcb80a5996392714935b5d38c08b0ad6
    image: quay.io/argoproj/argoexec:v3.4.5
    imageID: docker-pullable://quay.io/argoproj/argoexec@sha256:3f2ba3b355eccc61ec0e3b5c9fc547f4e9ff5821bf6f08485a6a5fc99bf7731b
    lastState: {}
    name: wait
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://0cfdc6c085a15931714c56fe4e2fc090dcb80a5996392714935b5d38c08b0ad6
        exitCode: 2
        finishedAt: "2023-02-15T11:01:19Z"
        reason: Error
        startedAt: "2023-02-15T11:00:52Z"
```

**Comment by aaaaahaaaaa** [comment]
Same here, we've started to experience the same kind of issue with the latest update. We have several CronWorkflows running daily which contains between 100 and 150 nodes, and everyday a couple of them keep failing. `Exit code 2`, while the Python script running in the container seems to execute successfully.

**Comment by Nizar-opt** [comment]
We have experienced same issue after upgrading to v3.4.5. It happens every now and then on multiple workflows, particularly on git clone step with `Error (exit code 2)`

**Comment by sahoev** [comment]
I found the same after upgrade from v3.4.4 to v3.4.5 the logging/feedback is not helpful. 
I found the following line which might be of interest: `time="2023-02-20T13:28:22.784Z" level=info msg="sub-process exited" argo=true error="<nil>"`

**Comment by Guillermogsjc** [comment]
I guess it has to do with some update at the recover of the args done by the Emissary executor, that encapsulates `command`and `args` in such a way the logs are processed without kube api burden

**Comment by CiprianAnton** [comment]
We were also able to reproduce this issue in v3.4.4, but not that often. With v3.4.5 the issue reproduces more often.

**Comment by JPZ13** [comment]
Hey @Guillermogsjc - we think this will be resolved by #10523, but we're not sure. Can you and @CiprianAnton check that PR out and see if you're still running into the issue?

**Comment by Guillermogsjc** [comment]
Hi,  sure, just to confirm, to test it can be reached by changing as alexec says here right? https://github.com/argoproj/argo-workflows/pull/10523#issuecomment-1427322477

**Comment by Guillermogsjc** [comment]
well, changing  the workflow-controller Deployment args so it looks like

```yaml
name: workflow-controller
image: quay.io/argoproj/workflow-controller:v3.4.4
command:
  - workflow-controller
args:
  - '--executor-image'
  - quay.io/argoproj/argoexec:dev-sigterm
```

and launching the same workflows that were failing constantly with this exit 2, now everything works fine.

At least experimentally for the kind of workflows that we have it is solved.
Kind regards.
