### ISSUE TITLE
Bad Request: template 'clone' type is unknown

### ISSUE THREAD

**Issue by shuhaib3** [argoproj/argo-workflows#10535]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hi, I am new to Argo workflow and created a workflow template, but submitting a workflow gives me an error. 
can anyone help here?

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cicd-workflow-template
  namespace: argo
spec:
  arguments:
    parameters:
      - name: branch
        value: master
      - name: dockerRepo
        value: ***

  entrypoint: clone

  podGC:
    strategy: OnPodSuccess

  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 64Mi

  templates:
    - name: clone
      inputs:
        artifacts:
        - name: argo-source
          path: /src
          git:
            repo: ********
            usernameSecret:
              name: bitbucket-creds
              key: username
            passwordSecret:
              name: bitbucket-creds
              key: password
            singleBranch: true
            branch: "master"

    - name: docker-build
      volumes:
        - name: docker-config
          secret:
            secretName: registrykey
      container:
        image: moby/buildkit:v0.9.3-rootless
        volumeMounts:
          - mountPath: /go/src/github.com/go-api
            name: work
            subPath: src
          - name: docker-config
            mountPath: /.docker
        workingDir: /go/src/github.com/go-api
        env:
          - name: BUILDKITD_FLAGS
            value: --oci-worker-no-process-sandbox
          - name: DOCKER_CONFIG
            value: /.docker
        command:
          - buildctl-daemonless.sh
        args:
          - build
          - --frontend
          - dockerfile.v0
          - --local
          - context=.
          - --local
          - dockerfile=docker/
          - --output
          - type=image,name={{workflow.parameters.dockerRepo}},push=true
        securityContext:
          privileged: true
```

### Logs from the workflow controller

```text
me="2023-02-15T20:28:54.728Z" level=info msg="Update leases 200"
time="2023-02-15T20:28:59.734Z" level=info msg="Get leases 200"
time="2023-02-15T20:28:59.740Z" level=info msg="Update leases 200"
time="2023-02-15T20:29:00.461Z" level=info msg="List workflows 200"
time="2023-02-15T20:29:00.461Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=
time="2023-02-15T20:29:04.745Z" level=info msg="Get leases 200"
time="2023-02-15T20:29:04.757Z" level=info msg="Update leases 200"
time="2023-02-15T20:29:09.762Z" level=info msg="Get leases 200"
time="2023-02-15T20:29:09.778Z" level=info msg="Update leases 200"
time="2023-02-15T20:29:14.785Z" level=info msg="Get leases 200"
time="2023-02-15T20:29:14.791Z" level=info msg="Update leases 200"
time="2023-02-15T20:29:19.800Z" level=info msg="Get leases 200"
time="2023-02-15T20:29:19.807Z" level=info msg="Update leases 200"
time="2023-02-15T20:29:24.813Z" level=info msg="Get leases 200"
```

### Logs from in your workflow's wait container

```text
me="2023-02-15T20:28:54.728Z" level=info msg="Update leases 200"
time="2023-02-15T20:28:59.734Z" level=info msg="Get leases 200"
time="2023-02-15T20:28:59.740Z" level=info msg="Update leases 200"
time="2023-02-15T20:29:00.461Z" level=info msg="List workflows 200"
time="2023-02-15T20:29:00.461Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=
time="2023-02-15T20:29:04.745Z" level=info msg="Get leases 200"
time="2023-02-15T20:29:04.757Z" level=info msg="Update leases 200"
time="2023-02-15T20:29:09.762Z" level=info msg="Get leases 200"
time="2023-02-15T20:29:09.778Z" level=info msg="Update leases 200"
time="2023-02-15T20:29:14.785Z" level=info msg="Get leases 200"
time="2023-02-15T20:29:14.791Z" level=info msg="Update leases 200"
time="2023-02-15T20:29:19.800Z" level=info msg="Get leases 200"
time="2023-02-15T20:29:19.807Z" level=info msg="Update leases 200"
time="2023-02-15T20:29:24.813Z" level=info msg="Get leases 200"
```
