### ISSUE TITLE
SIdecar fails step because of code 143

### ISSUE THREAD

**Issue by andreimc** [argoproj/argo-workflows#1053]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
**What happened**:
When running elasticsearch as a sidecar, on termination elastic throws a 143 exit code. And the whole workflow fails since elastic fails.
**What you expected to happen**:

Workflow to pass.

**How to reproduce it (as minimally and precisely as possible)**:

Run a task with an elasticsearch sidecar.

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.2.1
```
2.2.1
```
- Kubernetes version :
```
1.11
```

**Comment by andreimc** [comment]
https://github.com/elastic/elasticsearch/issues/31847 on this issue 143 is an okay code

**Comment by andreimc** [comment]
@WeiTang114 thanks for that i also added https://github.com/argoproj/argo/pull/1052/files#diff-fcb04129f1d32e69cca32631c6586587R737 to ignore 143 since it's a common java normal exit

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo/pull/1052

**Comment by highb** [comment]
For whatever reason, my Argo instance (v3.5.6) isn't hitting the special case handled above. I worked around it by passing the `-e 143` flag to [tini](https://github.com/krallin/tini).

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
...
spec:
  templates:
  - name: test-workflow
    container: ...
    sidecars:
    - name: elasticsearch
      image: elasticsearch:8.1.0
      # Remap Java exit 143 to 0 https://github.com/krallin/tini?tab=readme-ov-file#remapping-exit-codes
      command: ["/bin/tini","-e","143","--","/usr/local/bin/docker-entrypoint.sh"]
      args: []
      resources:
        limits:
          cpu: "4"
          memory: "4Gi"
        requests:
          cpu: "2"
          memory: "2Gi"
```
