### ISSUE TITLE
Lint error: exit handler - failed to resolve {{workflow.labels.workflows.argoproj.io/creator-preferred-username}}

### ISSUE THREAD

**Issue by lstolcman** [argoproj/argo-workflows#10554]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hi

Argo lint has a bug - I cannot pass linting step of working workflow script:

```
(base) ➜  ./argo-linux-amd64 version
argo: v3.4.5
  BuildDate: 2023-02-07T13:22:11Z
  GitCommit: 1253f443baa8ad1610d2e62ec26ecdc85fe1b837
  GitTreeState: clean
  GitTag: v3.4.5
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
(base) ➜  ./argo-linux-amd64 lint test.yaml
api.yaml:
   ✖ in "test-exit-handler-" (WorkflowTemplate): rpc error: code = InvalidArgument desc = templates.main-exit-handler: failed to resolve {{workflow.labels.workflows.argoproj.io/creator-preferred-username}}

```

What I would like to achieve: to get a workflow creator name in exit handler (from metadata):
![obraz](https://user-images.githubusercontent.com/4583553/220102832-5cc093ae-611b-45cd-b34f-59d744d90c2f.png)

I got the value I wanted, when executing a workflow:

![obraz](https://user-images.githubusercontent.com/4583553/220103880-06805014-e99d-46f8-9b14-984a30174ee3.png)

Unfortunately, linting fails. A small workflow pasted below reproduces the case.

It is slightly connected with the issues https://github.com/argoproj/argo-workflows/issues/3448 https://github.com/argoproj/argo-workflows/issues/6036

### Version

3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: test-exit-handler-

spec:
  entrypoint: runner
  onExit: main-exit-handler

  templates:
    - name: runner
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["runner"]
        resources:
          limits:
            memory: 32Mi
            cpu: 100m

    - name: main-exit-handler
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{workflow.labels.workflows.argoproj.io/creator-preferred-username}}"]
        resources:
          limits:
            memory: 32Mi
            cpu: 100m

  imagePullSecrets:
    - name: registry-int-peakdata-ch
    - name: docker-hub
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by lstolcman** [comment]
The issue got a workaround quickly by a colleague ;)

To pass the linter, the workflow needs to contain `label` part, and the value will be replaced by argo afterwards. At least the linter won't thow errors:


```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: test-exit-handler-
  labels:
    # we need to put dummy variable which will be replaced by argo later on
    # fixes a bug: https://github.com/argoproj/argo-workflows/issues/10554
    workflows.argoproj.io/creator-preferred-username: dummy

spec:
  entrypoint: runner

[...]
```

**Comment by sylock** [comment]
I'm also affected by this bug. The workaround is working but not serious when you have to manage a lot of workflows with templatesRef and templates written by diverse peoples -> they need to use a snippet, and they'll endup with this linter issue if they forgot to put a dummy label.

**Comment by sylock** [comment]
For my use case I found a better workaround. But it's much more slow (~40 sec of execution time) instead of accessing a context variable (instant). This workaround has the advantage that there is no need of a dummy label in the original code which is difficult in my context to handle.

```yaml
- name: get-workflow-template
  outputs:
    parameters:
      - name: workflow-template
        valueFrom:
          jsonPath: '{.metadata.labels.workflows\.argoproj\.io/workflow-template}'
  resource:
    action: get
    manifest: |
      kind: Workflow
      apiVersion: argoproj.io/v1alpha1
      metadata:
        name: "{{workflow.name}}"
        namespace: "{{workflow.namespace}}"
```
