### ISSUE TITLE
Incorrectly compressed output artifact on Windows

### ISSUE THREAD

**Issue by kalb1** [argoproj/argo-workflows#10562]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Output archive artifact compress folder incorrectly in case of windows image. Instead of keeping the folder structure, it puts all files in the root folder and appends the folder names to the file names, e.g structure: 
argo_test/
|----- test.txt

In the compressed artifact, there will be the empty argo_test folder and the file called argo_test\test.txt
The problem does not persist on Linux pods.

I assume this should be a 7zip misconfiguration.

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: hello-win
        template: hello-win

  - name: hello-win
    nodeSelector:
          kubernetes.io/os: windows
    container:
      image: mcr.microsoft.com/windows/nanoserver:1809
      command: ["cmd", "/c"]
      args: ["mkdir argo-test && echo Welcome from windows container! > argo-test/test.txt"]
    outputs:
      artifacts:
      - name: hello-win
        path: /argo-test
        archive:
          tar:
            compressionLevel: 0
```

### Logs from the workflow controller

```text
-
```

### Logs from in your workflow's wait container

```text
-
```
