### ISSUE TITLE
Sprig function not working with hyphen in parameters

### ISSUE THREAD

**Issue by philippeboyd** [argoproj/argo-workflows#10567]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

We're able to use `{{inputs.parameters.message-test}}` for accessing variables but `sprig` function does not work with the same variable (containing a hyphen)

```bash
echo "message-test = {{inputs.parameters.message-test}}"
echo "UPPER message-test = {{=sprig.upper(inputs.parameters.message-test)}}"
```

will output

```
message-test = hello argo
UPPER message-test = {{=sprig.upper(inputs.parameters.message-test)}}
```

instead of 

```
message-test = hello argo
UPPER message-test = HELLO ARGO
```

### Version

latest (v3.4.5)

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  name: omniscient-whale
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
          - name: message-test
            value: '{{workflow.parameters.message}}'
          - name: message_test
            value: '{{workflow.parameters.message}}'
      script:
        name: main
        image: bash
        command:
          - bash
        source: |
          echo "message = {{inputs.parameters.message}}"
          echo "message-test = {{inputs.parameters.message-test}}"
          echo "message_test = {{inputs.parameters.message_test}}"

          echo "UPPER message = {{=sprig.upper(inputs.parameters.message)}}"
          echo "UPPER message-test = {{=sprig.upper(inputs.parameters.message-test)}}"
          echo "UPPER message_test = {{=sprig.upper(inputs.parameters.message_test)}}"
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
message = hello argo
message-test = hello argo
message_test = hello argo
UPPER message = HELLO ARGO
UPPER message-test = {{=sprig.upper(inputs.parameters.message-test)}}
UPPER message_test = HELLO ARGO
```

### Logs from in your workflow's wait container

```text
N/A
```
