### ISSUE TITLE
When I use aa-1 as the name of steps, an error is reported for the next step

### ISSUE THREAD

**Issue by qzytwway** [argoproj/argo-workflows#10578]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I want aa to be effective and aa-1 to be effective. Or he should have given me a grammar hint in the first place

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
**when i use follow workflow**

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-steps-
spec:
  entrypoint: test
  templates:
  - name: test
    steps:
    - - name: aa
        template: aa
    - - name: bb
        template: bb
        when: "{{=jsonpath(steps.aa.outputs.result, '$.hello') == 'world'}}"

  - name: aa
    container:
      image: debian
      command:
      - bash
      - -c
      - 'echo {\"hello\": \"world\"}'

  - name: bb
    container:
      image: debian
      command:
      - bash
      - -c
      - echo hi

**it's work**

when i use follow workflow

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-steps-
spec:
  entrypoint: test
  templates:
  - name: test
    steps:
    - - name: aa-1
        template: aa
    - - name: bb
        template: bb
        when: "{{=jsonpath(steps.aa-1.outputs.result, '$.hello') == 'world'}}"

  - name: aa
    container:
      image: debian
      command:
      - bash
      - -c
      - 'echo {\"hello\": \"world\"}'

  - name: bb
    container:
      image: debian
      command:
      - bash
      - -c
      - echo hi

It reported an error
The task can be committed either way, but the following one will result in an error
```

### Logs from the workflow controller

```text
Invalid 'when' expression '{{=jsonpath(steps.aa-1.outputs.result, '$.hello') == 'world'}}': Invalid token: '{{=' (hint: try wrapping the affected expression in quotes ("))
```

### Logs from in your workflow's wait container

```text
It's easy to reproduce
```
