### ISSUE TITLE
Cluster scope failure and successed condition 

### ISSUE THREAD

**Issue by AndriySidliarskiy** [argoproj/argo-workflows#10595]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

https://github.com/argoproj/argo-workflows/issues/9320 i have the same issue with the cluster workflow template into v3.4.5 argowf. But it`s maybe related to a failure condition. 
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/62854979/221537577-f5d2aa52-c8e1-465e-a62c-68ad7c0c9e71.png">

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: manage-fsx-lustre-pvcs
spec:
  # ttlStrategy:
  #   secondsAfterSuccess: 60     # Time to live after workflow is successful
  #   secondsAfterFailure: 180
  serviceAccountName: argowf-sa
  entrypoint: workload
  arguments:
    parameters:
      - name: pvc-name
      - name: pvc-size
      - name: namespace
  templates:
  - name: workload
    inputs: 
      parameters:
        - name: create-pvc-reference
          value: false
    dag:
      tasks:
      - name: create-pvc
        template: create-pvc
      - name: create-pvc-reference
        arguments:
          parameters:
          - name: pv-reference-name
            value: 'dev-processing-reference'
        when: "{{inputs.parameters.create-pvc-reference}} == true"
        template: create-pvc-reference
  - name: create-pvc
    resource:
      action: apply
      setOwnerReference: true
      successCondition: "status.phase == Bound"
      failureCondition: "status.phase == Failed"
      manifest: |               #put your kubernetes spec here
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: '{{workflow.parameters.pvc-name}}'
          namespace: '{{workflow.parameters.namespace}}'
        spec:
          accessModes: [ "ReadWriteMany" ]
          resources:
            requests:
              storage: '{{workflow.parameters.pvc-size}}'
          storageClassName: lustre-persistent1-sc
    outputs:
      parameters:
        - name: status
          valueFrom:
            jsonPath: '{.status.phase}'
  - name: create-pvc-reference
    inputs:
      parameters:
      - name: pv-reference-name
    resource:
      action: apply
      setOwnerReference: true
      successCondition: "status.phase == Bound"
      failureCondition: "status.phase == Failed"
      manifest: |               #put your kubernetes spec here
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: '{{workflow.parameters.pvc-name}}-reference'
          namespace: '{{workflow.parameters.namespace}}'
        spec:
          accessModes: [ "ReadWriteMany" ]
          resources:
            requests:
              storage: '{{workflow.parameters.pvc-size}}'
          storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
          volumeName: {{inputs.parameters.pv-reference-name}}
    outputs:
      parameters:
        - name: status
          valueFrom:
            jsonPath: '{.status.phase}'
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

W
\"successCondition\":\"status.phase == Bound\",\"failureCondition\":\"status.phase == Failed\"}}" version="&Version{Version:v3.4.5,B
uildDate:2023-02-07T12:34:55Z,GitCommit:1253f443baa8ad1610d2e62ec26ecdc85fe1b837,GitTag:v3.4.5,GitTreeState:clean,GoVersion:go1.18.1
0,Compiler:gc,Platform:linux/amd64,}"
time="2023-02-27T10:10:07 UTC" level=info msg="Loading manifest to /tmp/manifest.yaml"
time="2023-02-27T10:10:07 UTC" level=info msg="kubectl apply -f /tmp/manifest.yaml -o json"
time="2023-02-27T10:10:07 UTC" level=info msg="Resource: default/persistentvolumeclaim./test. SelfLink: api/v1/namespaces/default/pe
rsistentvolumeclaims/test"
time="2023-02-27T10:10:07 UTC" level=info msg="Waiting for conditions: status.phase==Bound"
time="2023-02-27T10:10:07 UTC" level=info msg="Failing for conditions: status.phase==Failed"
time="2023-02-27T10:10:07 UTC" level=info msg="Get persistentvolumeclaims 200"
time="2023-02-27T10:10:07 UTC" level=info msg="failure condition '{status.phase == [Failed]}' evaluated false"
time="2023-02-27T10:10:07 UTC" level=info msg="success condition '{status.phase == [Bound]}' evaluated false"
time="2023-02-27T10:10:07 UTC" level=info msg="0/1 success conditions matched"
time="2023-02-27T10:10:07 UTC" level=info msg="Waiting for resource persistentvolumeclaim./test in namespace default resulted in ret
ryable error: Neither success condition nor the failure condition has been matched. Retrying..."
time="2023-02-27T10:10:12 UTC" level=info msg="Get persistentvolumeclaims 404"
time="2023-02-27T10:10:12 UTC" level=warning msg="Non-transient error: The resource has been deleted while its status was still bein
g checked. Will not be retried: persistentvolumeclaims \"test\" not found"
time="2023-02-27T10:10:12 UTC" level=warning msg="Waiting for resource persistentvolumeclaim./test in namespace default resulted in
non-retryable error: The resource has been deleted while its status was still being checked. Will not be retried: persistentvolumecl
aims \"test\" not found"
time="2023-02-27T10:10:12 UTC" level=warning msg="Waiting for resource persistentvolumeclaim./test resulted in error The resource ha
s been deleted while its status was still being checked. Will not be retried: persistentvolumeclaims \"test\" not found"
time="2023-02-27T10:10:12 UTC" level=error msg="executor error: The resource has been deleted while its status was still being check
ed. Will not be retried: persistentvolumeclaims \"test\" not found"
time="2023-02-27T10:10:12 UTC" level=fatal msg="The resource has been deleted while its status was still being checked. Will not be
retried: persistentvolumeclaims \"test\" not found"
time="2023-02-27T10:10:13 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```
