### ISSUE TITLE
Linter fails if objects are not sorted in order of import

### ISSUE THREAD

**Issue by chtcvl** [argoproj/argo-workflows#10608]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

**What happened:**
We are using `argo lint` in CI pipeline to verify that workflows generated by kustomize have valid syntax. This works well with small projects with few WorkflowTemplates. However on larger projects it starts returning linting errors, e.g.:
```bash
$ argo lint --offline --kinds=workflows,workflowtemplates,cronworkflows filename.yaml
/home/user/filename.yaml:
   ✖ in "hello-world" (CronWorkflow): cannot validate Workflow: templates.run-all.tasks.run-all couldn't find workflow template "hello-world" in namespace "user1"

✖ 1 linting errors found!
```
Once I sort input with yq by Kind - in order to make WorkflowTemplate precede CronWorkflow, error gets resolved:
```bash
$ yq ea '[.] | sort_by(.kind)  | reverse |  .[] | splitDoc' filename.yaml >  filename2.yaml
$ argo lint --offline --kinds=workflows,workflowtemplates,cronworkflows filename2.yaml
✔ no linting errors found!
```
However in case we have `WorkflowTemplate` that is referencing another `WorkflowTemplate` - linter return similar error and sorting becomes more tricky. I observe the same behaviour in both recent offline linter and and default (non-offline).

**What was expected:**
linter returns error only if template is missing in whole input, rather than only checking in files it have read before.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
  namespace: user1
spec:
  schedule: "* * * * *"
  timezone: "America/Los_Angeles"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: run-all
    templates:
      - name: run-all
        dag:
          failFast: false
          tasks:
          - name: run-all
            templateRef:
              name: hello-world
              template: whalesay

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world
  namespace: user1
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
