### ISSUE TITLE
azure devops git repo unable to use git artifact 

### ISSUE THREAD

**Issue by kmcrawford** [argoproj/argo-workflows#10600]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I am testing a private azure git artifact utilizing the information from the clone screen on azure devops:

![image](https://user-images.githubusercontent.com/40531/221639264-810ffbaf-880d-499e-8cee-2ac85b56172d.png)

I have created the `ado-creds` with the correct information.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-git-
spec:
  entrypoint: git-clone
  templates:
    - name: git-clone
      inputs:
        artifacts:
          - name: argo-source
            path: /src
            git:
              repo: https://xxxxx.visualstudio.com/My%20Agile%20Projects/_git/My_Repo
              branch: master
              usernameSecret:
                 name: ado-creds
                 key: username
              passwordSecret:
                 name: ado-creds
                 key: password
      container:
        image: golang:1.10
        command: [sh, -c]
        args: ["git status && ls && cat VERSION"]
        workingDir: /src
  ```

Logs init:  (real repo replaced with:`https://xxxxx.visualstudio.com/My%20Agile%20Projects/_git/My_Repo` )

```
input-artifact-git-7n5nk: time="2023-02-27T17:27:58.632Z" level=info msg="Start loading input artifacts..."
input-artifact-git-7n5nk: time="2023-02-27T17:27:58.632Z" level=info msg="Downloading artifact: argo-source"
input-artifact-git-7n5nk: time="2023-02-27T17:27:58.992Z" level=info msg="Load artifact" artifactName=argo-source duration=359.334293ms error="failed to clo
ne \"https://xxxxx.visualstudio.com/My%20Agile%20Projects/_git/My_Repo\": unexpected client error: unexpected requesting \"https://xxxxx.visualstudio.com/My%20Agile%20Projects/_git/My_Repo/git-upload-pack\" status code: 400" key=
input-artifact-git-7n5nk: time="2023-02-27T17:27:58.992Z" level=error msg="executor error: artifact argo-source failed to load: failed to clone \"https://xxxxx.visualstudio.com/My%20Agile%20Projects/_git/My_Repo\": unexpected client error: unexpected requesting \"https://xxxxx.visualstudio.com/My%20Agile%20Projects/_git/My_Repo/git-upload-pack\" status code: 400"
input-artifact-git-7n5nk: time="2023-02-27T17:27:58.992Z" level=info msg="Alloc=9612 TotalAlloc=15528 Sys=22994 NumGC=4 Goroutines=3"
input-artifact-git-7n5nk: time="2023-02-27T17:27:58.992Z" level=fatal msg="artifact argo-source failed to load: failed to clone \"https://xxxxx.visualstudio.com/My%20Agile%20Projects/_git/My_Repo\": unexpected client error: unexpected requesting \"https://xxxxx.visualstudio.com/My%20Agile%20Projects/_git/My_Repo/git-upload-pack\" status code: 400"
```

### Version

v3.4.5, v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-git-
spec:
  entrypoint: git-clone
  templates:
    - name: git-clone
      inputs:
        artifacts:
          - name: argo-source
            path: /src
            git:
              repo: https://xxxxx.visualstudio.com/My%20Agile%20Projects/_git/My_Repo
              branch: master
              usernameSecret:
                 name: ado-creds
                 key: username
              passwordSecret:
                 name: ado-creds
                 key: password
      container:
        image: golang:1.10
        command: [sh, -c]
        args: ["git status && ls && cat VERSION"]
        workingDir: /src
```

### Logs from the workflow controller

```text
empty
```

### Logs from in your workflow's wait container

```text
empty
```
