### ISSUE TITLE
Artifact visualization not working for Artifactory artifacts

### ISSUE THREAD

**Issue by caelan-io** [argoproj/argo-workflows#10619]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

set the `artifactory.url` on an output artifact, disabled archiving with `archive: none: {}`, turned on the toggle artifacts button in the UI, and ran the workflow. It still doesn’t show anything in the UI

See thread in CNCF Slack: https://cloud-native.slack.com/archives/C01QW9QSSSK/p1677530562373419

### Version

v3.4.X

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
add workflow here
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by caelan-io** [comment]
Resolved: `pod patch` was changed in v3.3 and the service account wasn't updated to account for this, thus disabling the feature. User needs to add `workflowtaskresults` and then the artifact viz feature should work.

**Comment by ejsuncy** [comment]
Here's a sample workflow that demonstrates the bug:

```yaml
# sample-workflow.yaml

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sample-workflow
  namespace: argo
spec:
  entrypoint: start
  templates:
    - name: start
      dag:
        tasks:
          - name: produce-artifact
            template: produce-artifact
    - name: produce-artifact
      container:
        image: alpine:latest
        command:
          - sh
          - -c
        args:
          - |
            mkdir -p /tmp/results && \
            echo "<html><p>Hello World! Here's a link to <a href="http://google.com">Google</a></p></html>" | tee /tmp/results/index.html
      outputs:
        artifacts:
          - name: hello-world-html
            path: /tmp/results/index.html
            artifactory:
              url: artifactory/generic-local/my-argo/workflows/sample/helloworld.html
            archive:
              none: {}
```

And here is the `artifacts-repositories` ConfigMap:

```yaml
# artifacts-repositories.yaml

apiVersion: v1
data:
  default-v1: |
    archiveLogs: true
    artifactory:
      # I'm using jfrog's helm charts to start up artifactory in a minkube namespace
      repoURL: http://artifactory-artifactory-nginx.artifactory/artifactory/generic-local
      usernameSecret:
        name: argo-artifacts-creds
        key: username
      passwordSecret:
        name: argo-artifacts-creds
        key: token
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1
  name: artifact-repositories
  namespace: argo

```

And here is a sample `argo-artifacts-creds` secret:

```yaml
# argo-artifacts-creds.yaml

apiVersion: v1
data:
  token: <b64-encoded artifactory api token>
  username: <b64-encoded artifactory username>
kind: Secret
metadata:
  name: argo-artifacts-creds
  namespace: argo
type: Opaque
```

---
Argo UI showing artifact in inputs/outputs tab:

<img width="457" alt="Argo UI showing artifact in inputs/outputs tab" src="https://user-images.githubusercontent.com/5944767/223270127-96368c68-28ab-4114-a172-3783c79c8181.png">

---
Artifactory UI showing artifact successfully uploaded:

<img width="998" alt="Artifactory UI showing artifact successfully uploaded" src="https://user-images.githubusercontent.com/5944767/223270710-8071c260-1044-44bf-b405-fd0a6f205a48.png">

---
Argo UI showing toggle artifacts button activated but no artifact visualization:

<img width="814" alt="Argo UI showing toggle artifacts button activated but no artifact visualization" src="https://user-images.githubusercontent.com/5944767/223271239-6061f5ba-ffa2-4476-8067-ef3048f3e6f4.png">

---
Here are the `wait` container logs:

```txt
time="2023-03-06T22:27:15.087Z" level=info msg="Starting Workflow Executor" version=v3.4.4
time="2023-03-06T22:27:15.090Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-03-06T22:27:15.090Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo po
dName=sample-workflow-xnkkv-produce-artifact-341383435 template="{\"name\":\"produce-artifact\",\"inputs\":{},\"outputs\":{\"artifacts\":[{\"name\":\"hell
o-world-html\",\"path\":\"/tmp/results/index.html\",\"artifactory\":{\"url\":\"artifactory/generic-local/my-argo/workflows/sample/helloworld.html\"},\"arc
hive\":{\"none\":{}}}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"mkdir -p /tmp/res
ults \\u0026\\u0026 \\\\\\necho \\\"\\u003chtml\\u003e\\u003cp\\u003eHello World! Here's a link to \\u003ca href=\\\"http://google.com\\\"\\u003eGoogle\\u
003c/a\\u003e\\u003c/p\\u003e\\u003c/html\\u003e\\\" | tee /tmp/results/index.html\\n\"],\"resources\":{}},\"archiveLocation\":{\"archiveLogs\":true,\"art
ifactory\":{\"url\":\"http://artifactory-artifactory-nginx.artifactory/artifactory/generic-local/sample-workflow-xnkkv/sample-workflow-xnkkv-produce-artif
act-341383435\",\"usernameSecret\":{\"name\":\"argo-artifacts-creds\",\"key\":\"username\"},\"passwordSecret\":{\"name\":\"argo-artifacts-creds\",\"key\":
\"token\"}}}}" version="&Version{Version:v3.4.4,BuildDate:2022-11-29T16:55:08Z,GitCommit:3b2626ff900aff2424c086a51af5929fb0b2d7e5,GitTag:v3.4.4,GitTreeSta
te:clean,GoVersion:go1.18.8,Compiler:gc,Platform:linux/arm64,}"
time="2023-03-06T22:27:15.090Z" level=info msg="Starting deadline monitor"
time="2023-03-06T22:27:18.093Z" level=info msg="Main container completed" error="<nil>"
time="2023-03-06T22:27:18.093Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-03-06T22:27:18.093Z" level=info msg="No output parameters"
time="2023-03-06T22:27:18.093Z" level=info msg="Saving output artifacts"
time="2023-03-06T22:27:18.093Z" level=info msg="Staging artifact: hello-world-html"
time="2023-03-06T22:27:18.093Z" level=info msg="Copying /tmp/results/index.html from container base image layer to /tmp/argo/outputs/artifacts/hello-world
-html.tgz"
time="2023-03-06T22:27:18.093Z" level=info msg="/var/run/argo/outputs/artifacts/tmp/results/index.html.tgz -> /tmp/argo/outputs/artifacts/hello-world-html
.tgz"
time="2023-03-06T22:27:18.093Z" level=info msg="Untaring /tmp/argo/outputs/artifacts/hello-world-html.tgz archive before upload"
time="2023-03-06T22:27:18.152Z" level=info msg="Save artifact" artifactName=hello-world-html duration=57.730125ms error="<nil>" key=/artifactory/generic-l
ocal/my-argo/workflows/sample/helloworld.html
time="2023-03-06T22:27:18.152Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/artifacts/index.html
time="2023-03-06T22:27:18.152Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/index.html"
time="2023-03-06T22:27:18.172Z" level=info msg="Save artifact" artifactName=main-logs duration=19.475625ms error="<nil>" key=/artifactory/generic-local/sa
mple-workflow-xnkkv/sample-workflow-xnkkv-produce-artifact-341383435/main.log
time="2023-03-06T22:27:18.172Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2023-03-06T22:27:18.172Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2023-03-06T22:27:18.183Z" level=info msg="Create workflowtaskresults 201"
time="2023-03-06T22:27:18.185Z" level=info msg="Deadline monitor stopped"
time="2023-03-06T22:27:18.185Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2023-03-06T22:27:18.185Z" level=info msg="Alloc=10994 TotalAlloc=16899 Sys=22994 NumGC=5 Goroutines=7"
```
