### ISSUE TITLE
When multiple Workflows use the same realtime metric, deleting one Workflow causes the metric to be deleted altogether 

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-workflows#10629]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

What happened:
Workflow has a realtime metric. If 2 Workflows (such as 2 Workflows evoked from the same CronWorkflow) use that metric, then once one is deleted the metric is removed from memory altogether.
That is because of [this](https://github.com/argoproj/argo-workflows/blob/master/workflow/metrics/metrics.go#L147) line. 

What I expected:
`delete(m.customMetrics, metric)` would only be called if the metric weren't present in any existing Workflows 

The net effect in the CronWorkflow example below is that the metric is deleted right around the same time that the new metric is created:
```

t     | WF 1 started |  
t+~10 | WF 1 completed |  
t+60  | WF 2 started |  
t+~70 | WF 2 completed | <- this adds to m.customMetrics
t+~70 | WF 1 deleted | <- this deletes from m.customMetrics


```

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  annotations:
    description: This cron workflow creates canaries which we monitor
  labels:
    canary: "true"
  name: canary
  namespace: argo
spec:
  schedule: '* * * * *'
  workflowMetadata:
    labels:
      monitoring: "true"
  workflowSpec:
    activeDeadlineSeconds: 30
    entrypoint: whalesay
    metrics:
      prometheus:
      - gauge:
          realtime: true
          value: '{{workflow.duration}}'
        help: Duration of canary
        name: canary_duration
    podDisruptionBudget:
      minAvailable: 1
    podGC:
      strategy: OnPodCompletion
    serviceAccountName: argo
    templates:
    - container:
        args:
        - ok
        command:
        - echo
        image: docker.intuit.com/dev/containers/argo/service/argoexec:v2.6.3
        name: main
      name: whalesay
    ttlStrategy:
      secondsAfterCompletion: 60
      secondsAfterFailure: 60
      secondsAfterSuccess: 60
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by juliev0** [comment]
Actually, this may not be a bug. Digging deeper, I think this may be what was intended: that a metric would only be for a single Workflow at a given time. I see in the documentation [here](https://argoproj.github.io/argo-workflows/metrics/) it explicitly says "Now, whenever we run our first workflow that validates 'Model A' a metric with the amount of time it took it to do so will be created and emitted. For each subsequent time that this happens, no new metrics will be emitted and the same metric will be updated with the new value." So, maybe one Workflow should ever use a metric at a given time, and therefore the metric should be deleted when that one Workflow dies?

I found if I add a label for `{{workflow.name}}` to the metric than each labeled metric is unique, and at least one of them is always present in the system.
```
 - gauge:
          realtime: true
          value: '{{workflow.duration}}'
        help: Duration of canary
        name: canary_duration
        labels:
          - key: workflow
            value: "{{workflow.name}}"
```
