### ISSUE TITLE
Allow fallback value for remote input artifacts

### ISSUE THREAD

**Issue by dillonstreator** [argoproj/argo-workflows#10631]
# Summary

Allow defining remote input artifacts with a default value if the remote key does not exist.

```yaml
      inputs:
        artifacts:
          - name: next
            path: /tmp/next
            raw:
              data: '[]'
            gcs:
              bucket: ele-qa-sftp
              key: '{{workflow.parameters.artifact-path}}/next.json'
```

Which would give precedence to `gcs` unless an error is encountered in which case fallback to `raw`.

Another option would be to extend the `gcs` field spec directly with a `default`.

```yaml
      inputs:
        artifacts:
          - name: next
            path: /tmp/next
            gcs:
              bucket: ele-qa-sftp
              key: '{{workflow.parameters.artifact-path}}/next.json'
              default: '[]'
```

# Use Cases

List processing where successfully processed items need to be captured as well as errored items. Errored items should become the input on retry and successful items should be merged with the retried group of successful items.

Heres a trimmed down example spec that i'm shooting for:
```yaml
spec:
    templates:
      - name: main
        dag:
          tasks:
            - name: process
              template: process
      - name: process
        inputs:
          artifacts:
            - name: initial
              path: /tmp/initial
              gcs:
                bucket: ele-qa-sftp
                key: '{{workflow.parameters.artifact-path}}/initial.json'
            - name: next
              path: /tmp/next
              raw:
                data: '[]'
              gcs:
                bucket: ele-qa-sftp
                key: '{{workflow.parameters.artifact-path}}/next.json'
        outputs:
          artifacts:
            - name: initial
              path: /tmp/initial
              gcs:
                bucket: ele-qa-sftp
                key: '{{workflow.parameters.artifact-path}}/initial.json'
              archive:
                none: {}
            - name: next
              path: /tmp/next
              gcs:
                bucket: ele-qa-sftp
                key: '{{workflow.parameters.artifact-path}}/next.json'
              archive:
                none: {}
        script:
          image: python:alpine3.6
          command:
            - python
          source: |
            import json
            import random
  
            erroredItems = []
            with open("{{inputs.artifacts.initial.path}}", "r") as f:
              initial = json.loads(f.read())
  
            with open("{{inputs.artifacts.next.path}}", "r") as f:
              next = json.loads(f.read())
  
            for item in initial:
              if random.randint(0,1) == 0:
                print('error {0}'.format(item["identifier"]))
                erroredItems.append(item)
              else:
                print('success {0}'.format(item["identifier"]))
                next.append(item)
  
            with open("{{inputs.artifacts.initial.path}}", 'w') as f:
              json.dump(erroredItems, f, ensure_ascii=False)
  
            with open("{{inputs.artifacts.next.path}}", 'w') as f:
              json.dump(next, f, ensure_ascii=False)
  
            if len(erroredItems) > 0:
              exit(1)

```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
