### ISSUE TITLE
`Invalid 'when' expression` gives no help on what went wrong 

### ISSUE THREAD

**Issue by Joibel** [argoproj/argo-workflows#10630]
# Summary

`Invalid 'when' expression` gives no help on what went wrong 

# Use Cases

I would use invalid when expressions when I mess up making a valid when expression.

Invalid 'when' expression will always say `Invalid token: '<first token here>' (hint: try wrapping the affected expression in quotes ("))` even when the expression makes sense and the token is completely valid and the expression is correctly quoted.

For example if a reference to a parameter is incorrect, it does not tell you that.

Example workflow with invalid parameter
```yaml
metadata:
  generateName: awesome-python
  namespace: ci
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: foo
        value: bar
  templates:
    - name: main
      dag:
        tasks:
          - name: A
            template: argosay
            arguments:
              parameters:
                - name: message
                  value: "hi"
            when: '{{workflow.parameters.flobble}} != bar'

    - name: argosay
      inputs:
        parameters:
          - name: message
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

I propose that something more useful or a less specific error message is given.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
