### ISSUE TITLE
The pipeline always runs on the same node

### ISSUE THREAD

**Issue by woxiehaode** [argoproj/argo-workflows#10652]
I was testing the pipeline, but found that it was always scheduled to run on the same node.

Node affinity has been tried, but the result is the same.

Is there any way to schedule to different nodes.
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
    - name: whalesay              # name of the template
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "hello world" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
```
<img width="643" alt="image" src="https://user-images.githubusercontent.com/13175712/223665789-7f496b9e-e69f-4bdf-bcc2-2359c2026988.png">

<img width="854" alt="image" src="https://user-images.githubusercontent.com/13175712/223665686-9f198a3f-9340-4ecf-a138-b953e9019698.png">
