### ISSUE TITLE
Auto update workflow controller configmap doesn't work

### ISSUE THREAD

**Issue by jdmaguire** [argoproj/argo-workflows#10659]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When I update the configmap for workflowDefaults, I expect the controller to pick up the change and start using it. What I see is that it knows there is an update but still uses the old values

Reproduction steps:

1. `kind create cluster --name reproduction` 
2. Install argo workflows w/ helm `helm install argo-workflows argo/argo-workflows --set controller.workflowDefaults.metadata.labels.simple=1 --version 0.22.13` (the 0.22.13 chart is using Argo Workflows v3.4.5)
3. I deploy a workflow. I see that it does set the label value.
4. I upgrade the default `helm install argo-workflows argo/argo-workflows --set controller.workflowDefaults.metadata.labels.simple=2 --version 0.22.13`
5. I verify in the configmap that the value has changed.
6. I deploy a workflow. I see that it sets the label to the original value (simple: 1), not the new value.
7. When I look at the logs for the argo-workflows-controller, I see it knows there is an update but I see it print out the old version of the configmap (logs below)

The most relevant PR in this area I could find is https://github.com/argoproj/argo-workflows/pull/10218, and that was included in the 3.4.5 release. Yet this doesn't work.

Note: if I restart the pod, it does pick up the proper values.

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
    - name: whalesay              # name of the template
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "hello world" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
```

### Logs from the workflow controller

```text
time="2023-03-10T04:31:32.538Z" level=info msg="Received Workflow Controller config map default/argo-workflows-workflow-controller-configmap update"
time="2023-03-10T04:31:32.539Z" level=info msg="Configuration:\nartifactRepository: {}\ninitialDelay: 0s\nmetricsConfig: {}\nnodeEvents:\n  enabled: true\npodSpecLogStrategy: {}\nsso:\n  clientId:\n    key: \"\"\n  clientSecret:\n    key: \"\"\n  issuer: \"\"\n  redirectUrl: \"\"\n  sessionExpiry: 0s\ntelemetryConfig: {}\nworkflowDefaults:\n  metadata:\n    creationTimestamp: null\n    labels:\n      simple: \"1\"\n  spec:\n    arguments: {}\n  status:\n    finishedAt: null\n    startedAt: null\n"
time="2023-03-10T04:31:32.539Z" level=info msg="Persistence configuration disabled"
time="2023-03-10T04:31:32.539Z" level=info executorImage="quay.io/argoproj/argoexec:v3.4.5" executorImagePullPolicy= managedNamespace=
time="2023-03-10T04:31:32.539Z" level=info msg="Successfully Workflow Controller config map default/argo-workflows-workflow-controller-configmap updated"
```

### Logs from in your workflow's wait container

```text
<Not relevant>
```
