### ISSUE TITLE
Argo Workflow with AWS Load Balancer Controller

### ISSUE THREAD

**Issue by hitsub2** [argoproj/argo-workflows#10657]
# Summary

The argo workflow with aws load balancer controller is not working as expected.
EKS Version: 1.24
Argo Workflow: v3.4.5

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-app-new
  namespace: argo
  annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /argo/
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
      alb.ingress.kubernetes.io/load-balancer-name: argo-ingress
      alb.ingress.kubernetes.io/scheme: internet-facing
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/target-type: ip
      ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
    - http:
        paths:
          - backend:
              service:
                name: argo-server
                port:
                  number: 2746
            path: /*
            pathType: ImplementationSpecific
---
---
apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: argo
spec:
  ports:
  - name: web
    port: 2746
    targetPort: 2746
  selector:
    app: argo-server
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: workflow-controller
value: 1000000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
  namespace: argo
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - args:
        - server
        env:
          - name: BASE_HREF
            value: /argo/
        image: quay.io/argoproj/argocli:v3.4.5
        name: argo-server
        ports:
        - containerPort: 2746
          name: web
        readinessProbe:
          httpGet:
            path: /
            port: 2746
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 20
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: argo-server
      volumes:
      - emptyDir: {}
        name: tmp

```

The web browser got blank pages. And an error comes up with the following:

```json
main.11e1de70aced411abdc2.js:1 Uncaught SyntaxError: Unexpected token '<' (at main.11e1de70aced411abdc2.js:1:1)
```

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
