### ISSUE TITLE
Running Pods do not scale up, even with available memory and CPU

### ISSUE THREAD

**Issue by oppie-kyndryl** [argoproj/argo-workflows#10654]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I am currently stress testing the performance of argo workflows deployed on a k8s cluster consisting of 3 VMs with 4 vCPU and 16 GiB of memory each. The test scenario I'm running executes the same workflow template with a single step that echos a "hello world" message to the console. Executed in isolation (as the only workflow running at a given time), this takes ~10 seconds. The performance tests submits request to run this workflow template, ramping up from 0-200 requests over 2 minutes, staying steady at 200 rpm for 1 minute, then linearly ramping down to 100 rpm for 1 minute. All in all, around 600 requests are submitted over a 4 minute period. 

Initially, default settings were resulting in workflow execution averaging around 6 minutes. Changing the `workflow-workers` and `workflow-ttl-workers` arguments into the workflow controller had no effect by themselves in a number of iterations. Increasing `resourceRateLimit.limit` to `200` and `resourceRateLimit.burst` to `100` itself didn't seem to have an effect, until setting parallelism to `50`. This reduced average execution time to  under 40 seconds, and further dropping parallelism to `10` got the average execution time back down to around 10 seconds, however, it took over 16 minutes to work through the requests. 

What I've noticed across all the scenarios is that, despite the cluster having available CPU and memory, the number of pods actively running jobs stays fairly low (typically less than 20 at a time). I would have expected the number of pods running a job to increase as workflows continue to get submitted until it reaches the `resrourceRateLimit.limit` + `resourceRateLimit.boost`. Instead, the pending workflows gauge keeps growing and the number of running pods remains low. Is there a setting to allow more pods to run simultaneously, or is this a bug? Below outlines details about each testing scenario

## Scenario 1 (default settings)

workflow-controller-config-map.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  workflowDefaults: |
    metadata:
      namespace: argo
    spec:
      ttlStrategy:
        secondsAfterSuccess: 3600
```

### Results

*Total Requests*: 597
*Total Duration*: ~ 10 minutes
*Avg. Workflow Execution Duration*: 5m 16s

#### Argo Metrics

![Argo Load Testing Stress 3](https://user-images.githubusercontent.com/127260652/223783659-f1c6349b-85e5-46fd-b0f1-acaffd63f4f5.png)

## Scenario 2:

workflow-controller-config-map.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  parallelism: "50"
  resourceRateLimit: |
    limit: 200
    burst: 100
  workflowDefaults: |
    metadata:
      namespace: argo
    spec:
      ttlStrategy:
        secondsAfterSuccess: 3600
```

workflow-controller.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: argo
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
    spec:
      containers:
        - args:
          - '--workflow-workers'
          - '256'
          - '--workflow-ttl-workers'
          - '16'
          command:
          - workflow-controller
          env:
          - name: LEADER_ELECTION_IDENTITY
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          image: quay.io/argoproj/workflow-controller:v3.4.5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 6060
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 30
          name: workflow-controller
          ports:
          - containerPort: 9090
            name: metrics
            protocol: TCP
          - containerPort: 6060
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              memory: 1Gi
              cpu: 700m
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: workflow-controller
      securityContext:
        runAsNonRoot: true
      serviceAccountName: argo
```
### Results

*Total Requests*: 596
*Total Duration*: ~8 minutes
*Avg. Workflow Execution Duration*: 37.85 s

#### Argo Metrics

![Argo Load Testing 11](https://user-images.githubusercontent.com/127260652/223785271-d95e75e4-c5a8-40b1-a9d5-310e4049b1ec.png)

### Cluster CPU & Memory Usage

![Screenshot 2023-03-07 at 3 38 17 PM](https://user-images.githubusercontent.com/127260652/223786617-def1c2ac-554c-4011-b3cc-d3052af80dbf.png)

## Scenario 3: 

workflow-controller-config-map.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  parallelism: "10"
  resourceRateLimit: |
    limit: 200
    burst: 100
  workflowDefaults: |
    metadata:
      namespace: argo
    spec:
      ttlStrategy:
        secondsAfterSuccess: 10
```

workflow-controller.yaml (same as scenario 2)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: argo
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
    spec:
      containers:
        - args:
          - '--workflow-workers'
          - '256'
          - '--workflow-ttl-workers'
          - '16'
          command:
          - workflow-controller
          env:
          - name: LEADER_ELECTION_IDENTITY
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          image: quay.io/argoproj/workflow-controller:v3.4.5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 6060
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 30
          name: workflow-controller
          ports:
          - containerPort: 9090
            name: metrics
            protocol: TCP
          - containerPort: 6060
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              memory: 1Gi
              cpu: 700m
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: workflow-controller
      securityContext:
        runAsNonRoot: true
      serviceAccountName: argo
```

### Results

*Total Requests*: 599
*Total Duration*: ~21 minutes
*Avg. Workflow Execution Duration*: 10.54 seconds

#### Argo Metrics

![Argo Load Testing 12](https://user-images.githubusercontent.com/127260652/223787489-72ced3b4-e87d-4b3f-83cb-c1318403553c.png)

#### Cluster CPU & Memory Usage

![Screenshot 2023-03-08 at 10 34 12 AM](https://user-images.githubusercontent.com/127260652/223787447-0704869d-7abc-4063-ba16-f42ee00f6dd1.png)

#### Workflow Logs

[echo-logs.txt](https://github.com/argoproj/argo-workflows/files/10923301/echo-logs.txt)

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Workflow template used in tests: 


metadata:
  name: echo
  namespace: argo
  uid: 8262f61e-0dbd-43f2-8d55-261fb17921e9
  resourceVersion: '992882'
  generation: 3
  creationTimestamp: '2023-03-01T18:05:55Z'
  labels:
    example: 'true'
    workflows.argoproj.io/creator: system-serviceaccount-argo-ui
  managedFields:
    - manager: argo
      operation: Update
      apiVersion: argoproj.io/v1alpha1
      time: '2023-03-06T23:13:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:example: {}
            f:workflows.argoproj.io/creator: {}
        f:spec: {}
spec:
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      outputs: {}
      metadata: {}
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
  entrypoint: argosay
  arguments:
    parameters:
      - name: message
        value: hello argo
  ttlStrategy:
    secondsAfterCompletion: 1800
  podGC:
    strategy: OnPodCompletion
  metrics:
    prometheus:
      - name: exec_duration_gauge
        help: Duration guage by name
        gauge:
          value: '{{workflow.duration}}'
          realtime: null
  workflowMetadata:
    labels:
      example: 'true'
```

### Logs from the workflow controller

```text
(see attached echo-logs.txt file)
```

### Logs from in your workflow's wait container

```text
N/A
```
