### ISSUE TITLE
Allow to access metric value on custom metrics

### ISSUE THREAD

**Issue by eduardodbr** [argoproj/argo-workflows#10662]
# Summary

What change needs making?

I want to be able to access the value of a custom gauge metric and increase or decrease it based on certain conditions.

# Use Cases

When would you use this?

I want to count how many times a certain workflow type for a certain ID (defined as a label) failed consecutively, and alert if that ID failed more than X times consecutively. 
I'd like to be able to do something similar to:

```
metrics:
  prometheus:
  - name: status_failed
    help: If the latest workflow failed
    when: '{{workflow.status}} == Failed || {{workflow.status}} == Error'
    gauge:
      value: {{metric.status_failed}} + 1 # this is the new feature
    labels:
    - key: workflow_type
      value: wf-type-1
    - key: id
      value: '{{workflow.parameters.id}}'
  - name: status_failed
    when: '{{workflow.status}} == Succeeded'
    help: If the latest workflow failed
    gauge:
      value: '0'
    labels:
    - key: workflow_type
      value: wf-type-1
    - key: tenant_id
      value: '{{workflow.parameters.id}}'
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by eduardodbr** [comment]
Hi,
I am willing to contribute with a PR to implement this, but first I'd like to know your thoughts on my approach.

After seeing the Prometheus gauge interface:

```
type Gauge interface {
	Metric
	Collector

	// Set sets the Gauge to an arbitrary value.
	Set(float64)
	// Inc increments the Gauge by 1. Use Add to increment it by arbitrary
	// values.
	Inc()
	// Dec decrements the Gauge by 1. Use Sub to decrement it by arbitrary
	// values.
	Dec()
	// Add adds the given value to the Gauge. (The value can be negative,
	// resulting in a decrease of the Gauge.)
	Add(float64)
	// Sub subtracts the given value from the Gauge. (The value can be
	// negative, resulting in an increase of the Gauge.)
	Sub(float64)

	// SetToCurrentTime sets the Gauge to the current Unix time in seconds.
	SetToCurrentTime()
}
```

I think it could make sense to change the argo gauge spec to have an `operation` field:

```
// Gauge is a Gauge prometheus metric
type Gauge struct {
	// Value is the value of the metric
	Value string `json:"value" protobuf:"bytes,1,opt,name=value"`
	// Realtime emits this metric in real time if applicable
	Realtime *bool `json:"realtime" protobuf:"varint,2,opt,name=realtime"`
	// Operation
	Operation string `json:"operation" protobuf:"bytes,1,opt,name=operation"`
}
```

. By default, this field would be set to `Set` to avoid breaking changes, but now it would be possible also to configure `Add` or `Sub`. The metric definition could be something like:

```
metrics:
    prometheus:
      - name: status_failed
        labels:
          - key: id
            value:  '1234'
        help: If the latest workflow failed
        when: '{{workflow.status}} == Failed || {{workflow.status}} == Error'
        gauge:
          operation: add
          value: '10'
```

would this be a good contribution?
