### ISSUE TITLE
WorkflowTemplate top-level parameters

### ISSUE THREAD

**Issue by yefen123** [argoproj/argo-workflows#10682]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

my yaml file context as follow:

**example1:**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: init-template
spec:
  arguments:
    parameters:
      - name: image
        value: "k8s-image:1.0"
  templates:

    - name: init-params-k8s
      container:
        image: "{{workflow.parameters.image}}"
        workingDir: /workspace-dir
        volumeMounts:
          - name: workspace-volume
            mountPath: /workspace-dir
          - name: tmp-volume
            mountPath: /tmp-dir
          - name: netrc-volume
            mountPath: /root
          - name: kube-credentials
            mountPath: /root/.kube
        command: ["sh", "-c"]
        args:
          - |
            # Create work directories
            mkdir -p ./{{workflow.name}}
```

**example2:**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: init-template
spec:
  entrypoint: init-params-k8s
  arguments:
    parameters:
      - name: image
        value: "k8s-image:1.0"
  templates:

    - name: init-params-k8s
      inputs:
        parameters:
          - name: image
      outputs:
        parameters:
          - name: source_vars
            valueFrom:
              path: /tmp-dir/{{workflow.name}}_source_vars.txt
            globalName: source_vars
      container:
        image: "{{inputs.parameters.image}}"
        workingDir: /workspace-dir
        volumeMounts:
          - name: workspace-volume
            mountPath: /workspace-dir
          - name: tmp-volume
            mountPath: /tmp-dir
          - name: netrc-volume
            mountPath: /root
          - name: kube-credentials
            mountPath: /root/.kube
        command: ["sh", "-c"]
        args:
          - |
            # Create work directories
            mkdir -p ./{{workflow.name}}
```

**example3:**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: init-template
spec:
  entrypoint: init-params-k8s
  arguments:
    parameters:
      - name: image
        value: "k8s-image:1.0"
  templates:

    - name: init-params-k8s
      inputs:
        parameters:
          - name: image
            value: "{{workflow.parameters.image}}"
      outputs:
        parameters:
          - name: source_vars
            valueFrom:
              path: /tmp-dir/{{workflow.name}}_source_vars.txt
            globalName: source_vars
      container:
        image: "{{inputs.parameters.image}}"
        workingDir: /workspace-dir
        volumeMounts:
          - name: workspace-volume
            mountPath: /workspace-dir
          - name: tmp-volume
            mountPath: /tmp-dir
          - name: netrc-volume
            mountPath: /root
          - name: kube-credentials
            mountPath: /root/.kube
        command: ["sh", "-c"]
        args:
          - |
            # Create work directories
            mkdir -p ./{{workflow.name}}
```

I got the error info: `InvalidImageName: Failed to apply default image tag "{{workflow.parameters.image}}": couldn't parse image reference "{{workflow.parameters.image}}": invalid reference format`
I hope I can get the value of parameters: "image", what should I do?

### Version

v3.3.6

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
my workflow yaml:
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    docklin/vbfDisplayName: compile
spec:
  entrypoint: main

  templates:
  - name: main
    steps:
    - - name: init-params-k8s
        templateRef:
          name: init-template
          template: init-params-k8s
```

### Logs from the workflow controller

```text
MESSAGE
workflow shutdown with strategy:  Stop
```

### Logs from in your workflow's wait container

```text
container wasn't running because of not getting the image
```
