### ISSUE TITLE
Allow "dag" to accept dynamic task listing

### ISSUE THREAD

**Issue by hach-que** [argoproj/argo-workflows#10718]
# Summary

DAG steps should be able to accept a list of steps from an artifact, something like this:

```yaml
    - name: generate-graph
      script:
        image: ubuntu:22.04
        command: [bash]
        source: |
          cat >/tmp/output.json <<EOF
          [
            [{
              "name": "A",
              "dependencies": [],
              "template": "node"
            }],
            [{
              "name": "B",
              "dependencies": ["A"],
              "template": "node"
            }],
            [{
              "name": "C",
              "dependencies": ["A"],
              "template": "node"
            }],
            [{
              "name": "D",
              "dependencies": ["B", "C"],
              "template": "node"
            }]
          ]
          EOF
      outputs:
        parameters:
          - name: dag
            valueFrom:
              path: /tmp/output.json
    - name: execute-graph
      inputs:
        parameters:
          - name: dag
      dag:
        tasksFrom:
          artifact: dag
```

# Use Cases

Right now the only way to dynamically generate DAGs is to use the "Workflow from Workflow" pattern. But the problem is that the spawned workflow appears separately in the Argo UI; it isn't connected to the main workflow that spawned it. So as a user I end up having to click through to a different workflow once I know the generated one has been started (and that's the one I actually care about).

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
