### ISSUE TITLE
Changes in docker image entrypoint are ignored

### ISSUE THREAD

**Issue by mrksngl** [argoproj/argo-workflows#10729]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I used a docker image in a template, without specifying a `command`.
The field reference documentation says:
> The docker image's ENTRYPOINT is used if this is not provided.

And that worked when running the image for the first time.

Now I made some changes to the image, especially I changed its `ENTRYPOINT`. Everything else is as before; especially the image was pushed under the same tag.
I use `imagePullPolicy: Always`, so I expect the new image to run.
Inspecting the generated pod, I can see that the new image was indeed pulled from the registry (it matches the sha256 sum).

However, also in the generated pod, I can still see the old entrypoint:
```yaml
  command:
    - /var/run/argo/argoexec
    - emissary
    - --loglevel
    - info
    - --log-format
    - text
    - --
    - OLD_ENTRY_POINT
 ```

I have no idea where it came from, but as this `command` is supposedly generated by argo, I guess it caches this information somewhere.
It works when I restart the workflow controller.

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  name: test
  namespace: default
spec:
  templates:
    - name: test
      container:
        name: test
        image: docker.io/busybox:latest # well, you likely need a private repo here and some meaningful image to test changes
        args:
          - 'ls'
          - '/'
  entrypoint: test
```

### Logs from the workflow controller

```text
not applicable
```

### Logs from in your workflow's wait container

```text
not applicable
```
