### ISSUE TITLE
Should be able to use `<<: *alias` to improve configuration re-use within workflows via argo cli

### ISSUE THREAD

**Issue by djmcgreal-cc** [argoproj/argo-workflows#10721]
### Pre-requisites

- [X] I have double-checked my configuration
- ~[ ] I can confirm the issues exists when I tested with `:latest`~ (cli issue)
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When trying to re-use and override configuration with YAML map alias merging, one gets:
> INFO[2023-03-21T08:58:25.880Z] No Workflow found in given files

I expect Argo CLI to find workflows with such merges.

It works via `kubectl create` so server-side is fine.

### Version

v3.4.5+1253f44.dirty

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: whalesay
  templates:
  - name: template
    container: &container
      image: grycap/cowsay
      command: [cowsay]
      args: ["hello world"]
  - name: whalesay
    container:
      <<: *container
      image: docker/whalesay:latest
```
```


### Logs from the workflow controller

```text
N/A, it never gets to the server.
```

### Logs from in your workflow's wait container

```text
N/A, it never gets to the server.
```
