### ISSUE TITLE
git or http input artifact hangs in pending state when invalid repo/branch or url

### ISSUE THREAD

**Issue by anasrallah** [argoproj/argo-workflows#10725]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hello team, I have a workflow using a git repo as an artifact. Problem I'm having is if the input artifact is not a valid git url/branch the workflow hangs in pending state eventhou the wf container recognizes that repo is invalid.
Ideally the step and workflow should fail in such scenario. I tried setting activeDeadlineSeconds but this didn't help. is there any workaround/fix?same thing I also noticed on an http artifactI simplified my example to the following:  

![argowfissue](https://user-images.githubusercontent.com/10229174/226698009-1eb72e71-1c23-4eb7-8075-31ec7acc845a.png)

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
- name: execute-script
      artifacts:
      - name: repo
        path: /source/
        mode: 0777
        git:
          repo: '{{workflow.parameters.git-repo}}'
          depth: 1
          singleBranch: true
          branch: 'notvalidbranch'
          usernameSecret:
            name: gitcreds
            key: username
          passwordSecret:
            name: gitcreds
            key: password
    container:
      image: python:alpine3.6
      command: ["python", "/source/script.py"]
```

### Logs from the workflow controller

```text
...
time="2023-03-21T17:48:28.430Z" level=info msg="Get leases 200"
time="2023-03-21T17:48:37.454Z" level=info msg="Get leases 200"
time="2023-03-21T17:48:46.679Z" level=info msg="Get leases 200"
time="2023-03-21T17:48:50.313Z" level=info msg="List workflows 200"
time="2023-03-21T17:48:50.313Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=argo-workflows
time="2023-03-21T17:48:55.652Z" level=info msg="Get leases 200"
time="2023-03-21T17:49:03.108Z" level=info msg="Get leases 200"
time="2023-03-21T17:49:08.689Z" level=info msg="Alloc=4706 TotalAlloc=14158956 Sys=20561 NumGC=36190 Goroutines=15"
time="2023-03-21T17:49:11.229Z" level=info msg="Get leases 200"
time="2023-03-21T17:49:17.779Z" level=info msg="Get leases 200"
time="2023-03-21T17:49:27.502Z" level=info msg="Get leases 200"
time="2023-03-21T17:49:35.284Z" level=info msg="Get leases 200"
time="2023-03-21T17:49:41.071Z" level=info msg="Get leases 200"
time="2023-03-21T17:49:50.314Z" level=info msg="List workflows 200"
time="2023-03-21T17:49:50.314Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=argo-workflows
time="2023-03-21T17:49:50.355Z" level=info msg="Get leases 200"
time="2023-03-21T17:50:01.240Z" level=info msg="Get leases 200"
time="2023-03-21T17:50:09.270Z" level=info msg="Get leases 200"
time="2023-03-21T17:50:14.629Z" level=info msg="Get leases 200"
time="2023-03-21T17:50:23.744Z" level=info msg="Get leases 200"
time="2023-03-21T17:50:30.688Z" level=info msg="Get leases 200"
time="2023-03-21T17:50:36.759Z" level=info msg="Get leases 200"
time="2023-03-21T17:50:44.325Z" level=info msg="Get leases 200"
time="2023-03-21T17:50:50.313Z" level=info msg="List workflows 200"
time="2023-03-21T17:50:50.313Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=argo-workflows
time="2023-03-21T17:50:53.141Z" level=info msg="Get leases 200"
time="2023-03-21T17:50:59.253Z" level=info msg="Get leases 200"
time="2023-03-21T17:51:05.102Z" level=info msg="Get leases 200"
time="2023-03-21T17:51:15.623Z" level=info msg="Get leases 200"
time="2023-03-21T17:51:23.700Z" level=info msg="Get leases 200"
time="2023-03-21T17:51:29.266Z" level=info msg="Get leases 200"
time="2023-03-21T17:51:34.544Z" level=info msg="Get leases 200"
time="2023-03-21T17:51:39.914Z" level=info msg="Get leases 200"
time="2023-03-21T17:51:46.773Z" level=info msg="Get leases 200"
time="2023-03-21T17:51:50.315Z" level=info msg="List workflows 200"
time="2023-03-21T17:51:50.315Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=argo-workflows
time="2023-03-21T17:51:54.268Z" level=info msg="Get leases 200"
```

### Logs from in your workflow's wait container

```text
Failed to load logs: container "wait" in pod "perf-testing-95gm4-get-abcd-3390977405" is waiting to start: PodInitializingReason: BadRequest (400)
```
