### ISSUE TITLE
inline templates not executed correctly

### ISSUE THREAD

**Issue by shota-takehara** [argoproj/argo-workflows#10737]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When there are two or more inline templates in a workflowtemplate that is called from a workflow, the content of the first executed inline templates is replaced by the content of the subsequent inline script and then executed.

### Version

v3.4.5 

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-test-
spec:
  entrypoint: hello-hello
  templates:
    - name: hello-hello
      steps:
        - - name: start
            templateRef:
              name: template-hello
              template: main

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-hello
spec:
  templates:
    - name: main
      steps:
        - - name: hello1
            inline:
              script:
                image: alpine:3.7
                command: [ sh ]
                source: |
                  echo "hello1"
        - - name: hello2
            inline:
              script:
                image: alpine:3.7
                command: [ sh ]
                source: |
                  echo "hello2"
```

### Logs from the workflow controller

```text
workflow-hello-xd4px--1205290903: time="2023-03-19T06:35:30.018Z" level=info msg="capturing logs" argo=true
workflow-hello-xd4px--1205290903: hello1
workflow-hello-xd4px--1205290903: time="2023-03-19T06:35:31.025Z" level=info msg="sub-process exited" argo=true error="<nil>"
workflow-hello-xd4px--3965209339: time="2023-03-19T06:35:41.045Z" level=info msg="capturing logs" argo=true
workflow-hello-xd4px--3965209339: hello1
workflow-hello-xd4px--3965209339: time="2023-03-19T06:35:42.069Z" level=info msg="sub-process exited" argo=true error="<nil>"
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by tico24** [comment]
The same happens if you use tasks instead of steps:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-hello
spec:
  templates:
    - name: main
      dag:
        tasks:
          - name: hello1
            inline:
              script:
                image: alpine:3.7
                command: [ sh ]
                source: |
                  echo "hello1"
          - name: hello2
            inline:
              script:
                image: alpine:3.7
                command: [ sh ]
                source: |
                  echo "hello2"
            dependencies: [hello1]
```

**Comment by terrytangyuan** [comment]
Yes that looks like a bug.

**Comment by Joibel** [comment]
But this doesn't occur with a straightforward Workflow.
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-hello-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: hello1
            inline:
              script:
                image: alpine:3.7
                command: [ sh ]
                source: |
                  echo "hello1"
          - name: hello2
            inline:
              script:
                image: alpine:3.7
                command: [ sh ]
                source: |
                  echo "hello2"
            dependencies: [hello1]
```
I'll take a look into it, I have an idea where it could be.
