### ISSUE TITLE
argo-server doesn't start with secure postgres setup

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-workflows#10731]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Testing out #10300, we encountered an issue whereby the argo-server pod doesn't start. It throws the error
`mkdir /home/argo/pgcerts: read only filesystem`.

Simply apply the config to connect your controller with a secure Postgres database, restart the controller and then restart the argo-server. The argo server will not start up.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

Not a workflow, an addition to the wf controller configmap:
```YAML
  persistence: |
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
      connMaxLifetime: 0s
    nodeStatusOffLoad: true
    archive: true
    archiveTTL: 14d
    postgresql:
      host: <redacted>
      ssl: true
      sslMode: require
      port: 5432
      database: argo
      tableName: argo_workflows
      userNameSecret:
        name: argo-postgres-config
        key: username
      passwordSecret:
        name: argo-postgres-config
        key: password
```
