### ISSUE TITLE
`argo lint`: `failed to resolve {{workflow.labels.workflows.argoproj.io/workflow-template}}` but works when applied and ran

### ISSUE THREAD

**Issue by yay14** [argoproj/argo-workflows#10748]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When we run argo lint, using some variables like `workflow.namespace`, `workflow.labels.workflows.argoproj.io/workflow-template` gives the below error

` in "test-argo-lint" (WorkflowTemplate): templates.test-argo-lint templates.test-argo-lint: failed to resolve {{workflow.labels.workflows.argoproj.io/workflow-template}}`

Even though the templates get applied correctly, and run successfully, the argo lint gives this error? Is it expected or it's a bug on the argo lint side.

The command used to run argo lint. We run a post-renderer script just to convert to valid argo helm template
 `helm template . --post-renderer ./../../post-render.sh > out.yaml && argo lint out.yaml`

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "test-argo-lint"
  namespace: "argo-workflows-test"
spec:
  templates:
  - name: test-argo-lint
    metrics:
      prometheus:
      - name: step_status_total
        help: "Count of step execution by step name and result status"
        labels:
        - key: name
          value: test-argo-lint
        - key: workflow_template
          value: "[[workflow.labels.workflows.argoproj.io/workflow-template]]"
        - key: status
          value: "[[status]]"
        - key: namespace
          value: "[[workflow.namespace]]"
        counter:
          value: "1"
      - name: step_duration_seconds
        help: "Duration of step execution by step name and workflow template"
        labels:
        - key: name
          value: test-argo-lint
        - key: workflow_template
          value: "[[workflow.labels.workflows.argoproj.io/workflow-template]]"
        - key: namespace
          value: '[[workflow.namespace]]'
        histogram:
          buckets:
          - 60
          - 120
          - 240
          - 480
          - 720
          - 960
          - 1200
          - 1440
          - 1680
          - 1800
          - 2400
          - 4800
          value: "[[duration]]"
    container:
      image: python:alpine3.6
      command: [python, -c]
      # fail with a 66% probability
      args: ["import random; import sys; exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

- Logs are not required since it's a lint issue
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
