### ISSUE TITLE
Resource template in a workflow doesn't work if readOnlyRootFileSystem is enforced to the workflow

### ISSUE THREAD

**Issue by sujaykulkarn** [argoproj/argo-workflows#10787]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hi, 

Argo workflow chart configurations:
For Controller, the main container, and wait container(executor) we are enforcing readOnlyRootFileSystem flag for security context. Other sample workflows which have container, and script template all worked fine. Only the Resource template is failing with the below logs.
```
time="2023-03-29T10:41:13.128Z" level=error msg="executor error: open /tmp/manifest.yaml: read-only file system"
 time="2023-03-29T10:41:13.128Z" level=fatal msg="open /tmp/manifest.yaml: read-only file system"
```
Workflow - https://github.com/argoproj/argo-workflows/blob/master/examples/k8s-owner-reference.yaml ) 
Reference - https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce 

Is there any workaround to make resource template work when allowPrivilegeEscalation when set to false. Thanks

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: k8s-owner-reference-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      This example creates a Kubernetes resource that will be deleted
      when the workflow is deleted via Kubernetes GC.

      A workflow is used for this example, but the same approach would apply
      to other resource types.

      https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
spec:
  entrypoint: main
  templates:
    - name: main
      resource:
        action: create
        setOwnerReference: true
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: owned-eg-
          spec:
            entrypoint: main
            templates:
              - name: main
                container:
                  image: argoproj/argosay:v2
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
time="2023-03-29T10:41:13.128Z" level=error msg="executor error: open /tmp/manifest.yaml: read-only file system"
 time="2023-03-29T10:41:13.128Z" level=fatal msg="open /tmp/manifest.yaml: read-only file system"
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

time="2023-03-29T10:41:13.128Z" level=error msg="executor error: open /tmp/manifest.yaml: read-only file system"
 time="2023-03-29T10:41:13.128Z" level=fatal msg="open /tmp/manifest.yaml: read-only file system"
```

**Comment by tico24** [comment]
The path in the logs is defined here: https://github.com/argoproj/argo-workflows/blob/master/workflow/common/common.go#L112

It looks like the manifest is written to a file before being kubectl apply'd to the cluster. I'm not useful at a code level so can't provide a fix, but hopefully this comment helps whoever picks it up.

**Comment by poornachandratejasvi** [comment]
any solutions to this problem that don't involve altering the flag readOnlyRootFileSystem ?

**Comment by agilgur5** [comment]
Ah I mentioned this scenario in #10233 too!

`podSpecPatch` may be a workaround for this -- would need to mount an `emptyDir` as a replacement for the root FS write.

**Comment by ramanNarasimhan77** [comment]
Ran into this issue today and noticed that if I specify an emptyDir volume in Workflow's spec.volumes and use it in podSpecPatch it does not work. The generated podSpec does not have the new volume added.

To circumvent above issue, I added volume also in podSpecPatch and was able to get it to work.

`podSpecPatch: '{"initContainers":[{"name":"init","volumeMounts":[{"name":"init-temp-dir","mountPath":"/tmp"}]}],"volumes":[{"name":"init-temp-dir","emptyDir":{"sizeLimit":"50Mi"}}]}'`

**Comment by agilgur5** [comment]
I think the fix to this should be to just use an `emptyDir` volume for `resource` templates instead of requiring the ability to write to the root FS.

There actually already is an `emptyDir` volume created for Workflow Pods, but that one seems to have [a `subPath`](https://github.com/argoproj/argo-workflows/blob/b4af68bdd48c41bcf75ba433357c9b9b01a0e0c1/workflow/controller/workflowpod.go#L402). We should re-use that one if possible

**Comment by ramanNarasimhan77** [comment]
In our Kubernetes clusters, recently we have introduced [Validating Admission Policies](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/). One of the policies, stops the submission of a Workflow if it contains a `podSpecPatch` because a malicious user can inject any container which can be used to trigger attacks like `reverse-shell`, `host-takeover` etc provided the workflow is running with a service account having many privileges.

As a result, currently we are unable to use Manifest submission via Workflows as `readOnlyRootFileSystem` is also enforced for all pods via a securityContext.

So, we are waiting for this fix to be done so that we can resume using Manifest submission via workflows.

> I think the fix to this should be to just use an `emptyDir` volume for `resource` templates instead of requiring the ability to write to the root FS.

**Comment by agilgur5** [comment]
> One of the policies, stops the submission of a Workflow if it contains a `podSpecPatch` because a malicious user can inject any container which can be used to trigger attacks like `reverse-shell`, `host-takeover` etc

If the user has RBAC to `create` Workflows or `create` Pods, they can already write any malicious logic directly and would not need `podSpecPatch` to do so. Without more context, that policy rationale sounds inherently flawed

**Comment by divramod** [comment]
so is the resource template definition not working currently?

**Comment by agilgur5** [comment]
No, this issue does not say that (and has been open for 1.5 years) and it works fine. As the issue says, certain policies may disallow its usage without some of the workarounds mentioned above.

**Comment by demarna1** [comment]
Hi @agilgur5, we are running into this issue as well. The above podSpecPatch workaround doesn't work for us because we are using Kubeflow and we would need to change the way Kubeflow compiles the DAG into an Argo Workflow.

I suppose I could hack something together like a Kyverno policy to inject the podSpecPatch, but just wondering if there's been any headway on this fix you mentioned:

> I think the fix to this should be to just use an emptyDir volume for resource templates instead of requiring the ability to write to the root FS.

We are hoping that this can be fixed in the controller.

**Comment by b0ch3nski** [comment]
Anybody lurking there using OpenShift, the solution from @ramanNarasimhan77 https://github.com/argoproj/argo-workflows/issues/10787#issuecomment-2056664894 indeed works ;)

**Comment by markcheret** [comment]
I stumbled upon this issue over the weekend while I was doing some security hardening for a new component.
Apart from this being open for a while and the advised security configuration for this overall topic only clear when digging deep through the docs I believe the `non-root` container and all the caveats that come with it should be a first class citizen for configuration at least. If not even the default.
To give this some momentum I'm commenting here as my organization has a need to get this sorted out. For now I'll live with the following configuration:

```
# Executor configuration - sets the executor image and security context
executor:
  image:
    # Use the non-root executor image tag matching the controller version
    tag: "v3.7.1-nonroot"
  # Security context for the executor (wait) container
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737
    runAsGroup: 8737
    privileged: false
    allowPrivilegeEscalation: false
    # Would love to set this to true. But executions will fail otherwise even for /tmp
    # https://github.com/argoproj/argo-workflows/issues/10787 is open to address this. Little community movement, though
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL
```
