### ISSUE TITLE
Cannot use workflows resource create on ARM

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-workflows#10789]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

It seems that the resource creation step requires an AMD64 node to run from. It shouldn't do.

So running the below example, but adding a nodeselector to ensure it starts on arm, results in the workflow failing.

```
time="2023-03-31T06:51:10 UTC" level=info msg="capturing logs" argo=true
time="2023-03-31T06:51:10 UTC" level=info msg="Starting Workflow Executor" version=v3.4.5
time="2023-03-31T06:51:10 UTC" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-03-31T06:51:10 UTC" level=info msg="Executor initialized" deadline="2023-03-31 07:51:08 +0000 UTC" includeScriptOutput=false namespace=ci podName=arm-resource-createcrz28-main-19500
35453 template="{\"name\":\"main\",\"inputs\":{},\"outputs\":{},\"nodeSelector\":{\"nodegroup\":\"arm-spot\"},\"metadata\":{},\"resource\":{\"action\":\"create\",\"manifest\":\"apiVersion: arg
oproj.io/v1alpha1\\nkind: Workflow\\nmetadata:\\n  generateName: owned-eg-\\n  ownerReferences:\\n  - apiVersion: argoproj.io/v1alpha1\\n    blockOwnerDeletion: true\\n    controller: true\\n
   kind: Workflow\\n    name: arm-resource-createcrz28\\n    uid: 3e7ec3e5-2f10-446a-939f-5e1a5f3d513a\\nspec:\\n  entrypoint: main\\n  templates:\\n  - container:\\n      image: argoproj/argo
say:v2\\n    name: main\\n\",\"setOwnerReference\":true},\"archiveLocation\":{\"archiveLogs\":true,\"s3\":{\"endpoint\":\"s3.amazonaws.com\",\"bucket\":\"pipekit-argo-workflows\",\"region\":\"
us-east-2\",\"insecure\":false,\"useSDKCreds\":true,\"encryptionOptions\":{},\"key\":\"my-artifacts/2023/03/31/arm-resource-createcrz28/arm-resource-createcrz28-main-1950035453\"}}}" version="
&Version{Version:v3.4.5,BuildDate:2023-02-07T12:36:25Z,GitCommit:1253f443baa8ad1610d2e62ec26ecdc85fe1b837,GitTag:v3.4.5,GitTreeState:clean,GoVersion:go1.18.10,Compiler:gc,Platform:linux/arm64,
}"
time="2023-03-31T06:51:10 UTC" level=info msg="Loading manifest to /tmp/manifest.yaml"
time="2023-03-31T06:51:10 UTC" level=info msg="kubectl create -f /tmp/manifest.yaml -o json"
time="2023-03-31T06:51:10 UTC" level=warning msg="Non-transient error: fork/exec /bin/kubectl: exec format error"
time="2023-03-31T06:51:10 UTC" level=error msg="executor error: no more retries fork/exec /bin/kubectl: exec format error"
time="2023-03-31T06:51:10 UTC" level=fatal msg="no more retries fork/exec /bin/kubectl: exec format error"
time="2023-03-31T06:51:11 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```

I would summise that the kubectl installation within workflows is pinned to AMD64, and should instead be dynamic depending on whether the executor pod is ARM or AMD64 (or probably windows?)

### Version

v3.4.6., latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: k8s-owner-reference-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      This example creates a Kubernetes resource that will be deleted
      when the workflow is deleted via Kubernetes GC.

      A workflow is used for this example, but the same approach would apply
      to other resource types.

      https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
spec:
  entrypoint: main
  templates:
    - name: main
      nodeSelector:
        kubernetes.io/arch: arm64
      resource:
        action: create
        setOwnerReference: true
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: owned-eg-
          spec:
            entrypoint: main
            templates:
              - name: main
                container:
                  image: argoproj/argosay:v2
```

### Logs from the workflow controller

```text
time="2023-03-31T06:57:05.523Z" level=info msg="Processing workflow" namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.523Z" level=info msg="Task-result reconciliation" namespace=ci numObjs=0 workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.523Z" level=info msg="Pod failed: Error (exit code 1): no more retries fork/exec /bin/kubectl: exec format error" displayName="arm-resource-createjbqq4(0)" namespace=ci pod=arm-resource-createjbqq4-main-962656022 templateName=main workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="node changed" namespace=ci new.message="Error (exit code 1): no more retries fork/exec /bin/kubectl: exec format error" new.phase=Failed new.progress=0/1 nodeID=arm-resource-createjbqq4-962656022 old.message= old.phase=Pending old.progress=0/1 workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="Node not set to be retried after status: Failed" namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="node arm-resource-createjbqq4 phase Running -> Failed" namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="node arm-resource-createjbqq4 message: Error (exit code 1): no more retries fork/exec /bin/kubectl: exec format error" namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="node arm-resource-createjbqq4 finished: 2023-03-31 06:57:05.5241626 +0000 UTC" namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="TaskSet Reconciliation" namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg=reconcileAgentPod namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="Updated phase Running -> Failed" namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="Updated message  -> Error (exit code 1): no more retries fork/exec /bin/kubectl: exec format error" namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="Marking workflow completed" namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="Checking daemoned children of " namespace=ci workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.524Z" level=info msg="Workflow to be dehydrated" Workflow Size=2739
time="2023-03-31T06:57:05.530Z" level=info msg="cleaning up pod" action=deletePod key=ci/arm-resource-createjbqq4-1340600742-agent/deletePod
time="2023-03-31T06:57:05.532Z" level=info msg="Create events 201"
time="2023-03-31T06:57:05.535Z" level=info msg="Update workflows 200"
time="2023-03-31T06:57:05.535Z" level=info msg="Workflow update successful" namespace=ci phase=Failed resourceVersion=52084364 workflow=arm-resource-createjbqq4
time="2023-03-31T06:57:05.536Z" level=info msg="Queueing Failed workflow ci/arm-resource-createjbqq4 for delete in 1h0m0s due to TTL"
time="2023-03-31T06:57:05.537Z" level=info msg="Delete pods 404"
time="2023-03-31T06:57:05.540Z" level=info msg="Create events 201"
time="2023-03-31T06:57:05.543Z" level=info msg="DeleteCollection workflowtaskresults 200"
time="2023-03-31T06:57:05.546Z" level=info msg="Create events 201"
time="2023-03-31T06:57:05.551Z" level=info msg="Create events 201"
time="2023-03-31T06:57:06.634Z" level=info msg="Get leases 200"
time="2023-03-31T06:57:06.642Z" level=info msg="Update leases 200"
```

### Logs from in your workflow's wait container

```text
No wait container is created.
```
