### ISSUE TITLE
examples/workflow-of-workflows.yaml doesn't work

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-workflows#10792]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I find this odd, because the examples seem to be tested as part of the CI.

However, certainly on Kubernetes 1.24, 1.25 and 1.26 (the versions I have to hand), [workflow-of-workflows.yaml ](https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/workflow-of-workflows.yaml)fails because the step name is too long for kubernetes.

```
Pod "workflow-of-workflows-lhp2p-triggerWorkflowUsingResourceWithoutArgument-1109926433" is invalid: metadata.name: Invalid value: "workflow-of-workflows-lhp2p-triggerWorkflowUsingResourceWithoutArgument-1109926433": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

So while the fix for this should be reasonably simple (don't put uppercase names in the step), some work is needed to understand why the examples pass CI when they shouldn't.

The CI script is here: https://github.com/argoproj/argo-workflows/blob/master/hack/test-examples.sh

Update:  It seems that not all the examples are tested (not sure on the reasoning behind this). Only workflows with `workflows.argoproj.io/test` are tested, and this isn't one of them.

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# This template demonstrates a workflow of workflows.
# Workflow triggers one or more workflow and manage it.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-of-workflows-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: workflow1
            template: triggerWorkflowUsingResourceWithoutArgument
            arguments:
              parameters:
              - name: workflowtemplate
                value: "workflow-template-submittable"
        - - name: workflow2
            template: triggerWorkflowUsingResourceWithArgument
            arguments:
              parameters:
              - name: workflowtemplate
                value: "workflow-template-submittable"
              - name: message
                value: "Welcome Argo"

    - name: triggerWorkflowUsingResourceWithoutArgument
      inputs:
        parameters:
          - name: workflowtemplate
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: workflow-of-workflows-1-
          spec:
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
    - name: triggerWorkflowUsingResourceWithArgument
      inputs:
        parameters:
          - name: workflowtemplate
          - name: message
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: workflow-of-workflows-2-
          spec:
            arguments:
              parameters:
              - name: message
                value: {{inputs.parameters.message}}
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```
