### ISSUE TITLE
Adding `strategies` field to enable multiple deletion policies to be selected

### ISSUE THREAD

**Issue by zamonia500** [argoproj/argo-workflows#10791]
# Summary

Adding `strategies` field expanding current `strategy` field.

# Use Cases

To select multiple ArtifactGC policy

# Details

Currently, The current workflow supports the [`spec.artifactGC.strategy` field](https://argoproj.github.io/argo-workflows/walk-through/artifacts/#artifact-garbage-collection) to specify the artifact deletion conditions.

<details>
<summary>Workflow example</summary>
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-gc-
spec:
  entrypoint: main
  artifactGC:
    strategy: OnWorkflowDeletion  # default Strategy set here applies to all Artifacts by default
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2
        command:
          - sh
          - -c
        args:
          - |
            echo "can throw this away" > /tmp/temporary-artifact.txt
            echo "keep this" > /tmp/keep-this.txt
      outputs:
        artifacts:
          - name: temporary-artifact
            path: /tmp/temporary-artifact.txt
            s3:
              key: temporary-artifact.txt
          - name: keep-this
            path: /tmp/keep-this.txt
            s3:
              key: keep-this.txt
            artifactGC:
              strategy: Never   # optional override for an Artifact
```
</details>

User can currently choose one of two options, `OnWorkflowCompletion` and `OnWorkflowDeletion`, but in most cases, I prefer deletion to occur.
So my suggestion is just add `strategies` field followed by [this comment](https://github.com/argoproj/argo-workflows/pull/9354#issuecomment-1216939529)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
