### ISSUE TITLE
 CLI: HTTP client ignores proxy

### ISSUE THREAD

**Issue by Adam-D-Lewis** [argoproj/argo-workflows#10794]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md)) - Sorry, I'm not a gopher :(

### What happened/what you expected to happen?

Runnning 
```./argo-linux-amd64 submit -n dev hello-world.yaml --proxy-url http://localhost:8000 --argo-server <my-domain>:443 --argo-http1 --argo-base-href=/argo --token <my-token> --secure=true -v```

outputs the curl command that is run which is 
`
curl -X POST -H 'Authorization: ******' -d '{"namespace":"dev","workflow":{"kind":"Workflow","apiVersion":"argoproj.io/v1alpha1","metadata":{"generateName":"hello-world-","namespace":"dev","creationTimestamp":null,"labels":{"workflows.argoproj.io/archive-strategy":"false"},"annotations":{"workflows.argoproj.io/description":"This is a simple hello world example.\nYou can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world\n"}},"spec":{"templates":[{"name":"whalesay","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"docker/whalesay:latest","command":["cowsay"],"args":["hello world"],"resources":{}}}],"entrypoint":"whalesay","arguments":{}},"status":{"startedAt":null,"finishedAt":null}},"createOptions":{}}' 'https://<my-domain>:443/argo/api/v1/workflows/dev?'
`

As you can see the `--proxy-url` flag is ignored.  I would have expected a `-x http://localhost:8000` to be added to the curl command.

### Version

v3.4.5 (latest binary I could find)

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
