### ISSUE TITLE
Allow users to add/show descriptions of workflow templates

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#10823]
If the annotation `workflows.argoproj.io/description` is available, present it nicely in the UI and allow users to edit it.

**Comment by jmeridth** [comment]
If someone adds the following:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-awesome-workflowtemplate
  annotations:
    workflows.argoproj.io/description: "The most amazing workflowtemplate EVAR"
```

to a workflowtemplate it will be available in the UI via https://argo-workflows-url/workflow-templates underneath the workflowtemplate name.
