### ISSUE TITLE
archiveLogs: true has no effect on HTTP Template

### ISSUE THREAD

**Issue by egze** [argoproj/argo-workflows#10834]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When using container templates, the output of the execution is saves fron stdout as artifact, when `archiveLogs: true` is enabled.

For HTTP Templates the `archiveLogs: true` has no effect. I am looking for ways how to save http response as an artifact, because the response can be quite big, over a megabyte.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-template-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: get-google-homepage
            template: http
            arguments:
              parameters: [{name: url, value: "https://www.google.com"}]
    - name: http
      inputs:
        parameters:
          - name: url
      http:
        url: "{{inputs.parameters.url}}"
```

### Logs from the workflow controller

```text
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:10.787Z" level=info msg="Starting Workflow Executor" version=untagged
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:10.792Z" level=info msg="Starting Agent" requeueTime=10s taskWorkers=16 workflow=http-template-7zgtv
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:10.795Z" level=info msg="Watch workflowtasksets 200"
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:10.797Z" level=info msg="TaskSet Event" event_type=ADDED workflow=http-template-7zgtv
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:10.887Z" level=info msg="Processing task" nodeID=http-template-7zgtv-2137851634
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:11.148Z" level=info msg="Sending result" message= nodeID=http-template-7zgtv-2137851634 phase=Succeeded requeue=0s
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:20.794Z" level=info msg="Processing Patch" workflow=http-template-7zgtv
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:20.805Z" level=info msg="Patch workflowtasksets/status 200"
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:20.886Z" level=info msg="Patched TaskSet"
```

### Logs from in your workflow's wait container

```text
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:10.787Z" level=info msg="Starting Workflow Executor" version=untagged
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:10.792Z" level=info msg="Starting Agent" requeueTime=10s taskWorkers=16 workflow=http-template-7zgtv
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:10.795Z" level=info msg="Watch workflowtasksets 200"
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:10.797Z" level=info msg="TaskSet Event" event_type=ADDED workflow=http-template-7zgtv
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:10.887Z" level=info msg="Processing task" nodeID=http-template-7zgtv-2137851634
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:11.148Z" level=info msg="Sending result" message= nodeID=http-template-7zgtv-2137851634 phase=Succeeded requeue=0s
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:20.794Z" level=info msg="Processing Patch" workflow=http-template-7zgtv
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:20.805Z" level=info msg="Patch workflowtasksets/status 200"
http-template-7zgtv-1340600742-agent: time="2023-04-05T18:47:20.886Z" level=info msg="Patched TaskSet"
```
