### ISSUE TITLE
Variable `workflow.parameters` does not work

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#10883]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Expect to see all the parameters get printed out in the container but got this error instead:

```
 error in entry template execution: invalid character 'n' after object key:value pair
```

Other parameters as well as `workflow.parameters.message` seem to work correctly:

```
'{{`{{workflow.name}}`}}' -- works
'{{workflow.name}}' -- works
'{{workflow.parameters.message}}' -- works

'{{workflow.parameters}}' -- doesn't work
'{{`{{workflow.parameters}}`}}' -- doesn't work
'{{workflow.parameters.json}}' -- doesn't work
```

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-payload
spec:
  serviceAccountName: argo
  arguments:
    parameters:
      - name: message
        value: hello argo
      - name: message2
        value: '{{workflow.parameters}}'
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message2
            value: '{{workflow.parameters.message2}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message2}}'
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by terrytangyuan** [comment]
Seems like `workflow.parameters` is fine when referencing directly in the template. It does not work in `spec.arguments.parameters`. Working examples:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-payload
spec:
  serviceAccountName: argo
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message2
            value: '{{workflow.parameters}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message2}}'
```

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-payload
spec:
  serviceAccountName: argo
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{workflow.parameters}}'

```
