### ISSUE TITLE
Template not found on initial creation

### ISSUE THREAD

**Issue by drew-viles** [argoproj/argo-workflows#10899]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Creating a CronWorkflow fails to find 2nd template in a sequence of steps on initial creation - more details below.

Templates should be detected on first creation and shouldn't need replacing twice.

### Version

I'm using helm chart: 0.24.0 - the latest available which gives me `AppVersion: v3.4.7`

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

I've created a `CronWorkflow` and `WorkflowTemplates` as follows:

```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron
  namespace: argo-workflows
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: test
    templates:
      - name: test
        steps:
          - - name: builder-test
              templateRef:
                name: test1
                template: test
          - - name: scanner-test
              templateRef:
                name: test2
                template: test
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test1
  namespace: argo-workflows
spec:
  entrypoint: test
  templates:
    - name: test
      script:
        image: ubuntu:22.04
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: | 
          echo "test build complete"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test2
  namespace: argo-workflows
spec:
  entrypoint: test
  templates:
    - name: test
      script:
        image: ubuntu:22.04
        imagePullPolicy: IfNotPresent
        command: [bash]
        source: |
          echo "test scan complete"
```

And I get the following error in the log (Below)

If I then change the  `test2` name in `CronWorkflow`:

```
          - - name: scanner-test
              templateRef:
                name: test3
                template: test
```

Apply that and then switch it back to:
```
          - - name: scanner-test
              templateRef:
                name: test2
                template: test
```
and apply it again.

It all works fine from that point onwards... It's a bit strange.

### Logs from the workflow controller
```
time="2023-04-13T11:28:38.031Z" level=error msg="cannot validate Workflow: templates.test.steps[1].scanner-test template reference test2.test not found" conditionType=SpecError namespace=argo-workflows workflow=test-cron
time="2023-04-13T11:28:38.031Z" level=error msg="invalid cron workflow" cronWorkflow=argo-workflows/test-cron error="cannot validate Workflow: templates.test.steps[1].scanner-test template reference test2.test not found"
```

### Logs from in your workflow's wait container
N/A
