### ISSUE TITLE
Terminating or stopping an operation does not completely end workflow's task

### ISSUE THREAD

**Issue by 249805118** [argoproj/argo-workflows#10896]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When I was running workflow, some Pods were in running state and others were in waiting state due to resource problems. At this time, I terminated the operation or stopped the operation, and the running Pods would stop. However, the Pods in waiting would continue to run, and resources would not be released until the rest of the Pods were completed.

In summary, terminating or stopping an operation does not completely end workflow's tasks

### Version

v3.4.6

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gpu-benchmark-
  namespace: default
spec:
  arguments:
    parameters:
    - name: count
      value: "10"
  entrypoint: main
  parallelism: 400
  podGC:
    strategy: OnPodSuccess
  templates:
  - name: main
    dag:
      tasks:
      - name: sequence-count
        template: tf-benchmark
        withSequence:
          count: "{{workflow.parameters.count}}"
      - name: sequence-start-end
        template: tf-benchmark


  - name: tf-benchmark
    container:
      image: nvidia/samples:dcgmproftester-2.0.10-cuda11.0-ubuntu18.04
      command: [/usr/bin/dcgmproftester11]
      args: ["--no-dcgm-validation", "-t", "1004", "-d", "300"]
      resources:
        limits:
          cpu: 2
          memory: 4Gi
          nvidia.com/gpu: 1
        requests:
          cpu: 2
          memory: 4Gi
          nvidia.com/gpu: 1
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by sarabala1979** [comment]
@249805118 Can you provide  wait container/workflow controller logs?

**Comment by andef** [comment]
I have been experiencing the same issue on v3.4.8

Submit a workflow that has a request that only makes some of the pods get scheduled and some pending:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sleep-
  namespace: argo
spec:
  entrypoint: wf
  templates:
  - name: wf
    steps:
    - - name: sleep
        template: sleep
        withParam: '[0, 1, 2, 3]'
  - name: sleep
    container:
      image: busybox:latest
      command: [sleep]
      args: ["300"]
      resources:
        requests:
          cpu: '1'
```
After submit it looks like this:
![started](https://github.com/argoproj/argo-workflows/assets/5502925/9b76cdc8-a316-49be-8e02-823d1033b6d9)

After pressing stop:
![stopped](https://github.com/argoproj/argo-workflows/assets/5502925/385a947f-4576-46f1-b379-053d3568ae08)

The workflow seems to have stopped, but the pending pods are instead scheduled and running:
```bash
$ kubectl -n argo get pod | grep sleep
sleep-5z4nd-sleep-2439398254           2/2     Running   0          60s
sleep-5z4nd-sleep-706581146            0/2     Error     0          60s
sleep-5z4nd-sleep-799906850            2/2     Running   0          60s
sleep-5z4nd-sleep-82800318             0/2     Error     0          60s
```

Controller log:
[controller.log](https://github.com/argoproj/argo-workflows/files/12488841/controller.log)

Wait container log of one of the pending pods:
[wait.log](https://github.com/argoproj/argo-workflows/files/12488876/wait.log)
