### ISSUE TITLE
S3 artifact driver fails to put empty files

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#10902]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When a file is empty (0 byte), S3 artifact driver fails to put a file to the bucket due to the following error:

```
Error (exit code 1): failed to put file: You must provide the Content-Length HTTP header.
```

```
time="2023-04-12T18:27:53.814Z" level=info msg="Save artifact" artifactName=main-logs duration=9.444637ms error="failed to put file: You must provide the Content-Length HTTP header." key=default/<REDACTED>-6ljf9/2023-04-12-182739/<REDACTED>-998323734/main.log
```

We should consider checking the file length before uploading it. However, I don't know if this issue is specific to S3. Other artifact drivers might support uploading empty files.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: noprint-
  namespace: argo-mls
spec:
  entrypoint: noprint
  templates:
  - name: noprint
    script:
      image: python:alpine3.6
      command: [python]
      source: >
              import time
```
```


### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
