### ISSUE TITLE
Downward API Volume

### ISSUE THREAD

**Issue by bakayolo** [argoproj/argo-workflows#1091]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/
Currently not possible to to expose pod information using downward api volume

**Comment by Siebjee** [comment]
It's possible to expose this already, just as the kubernetes docs state. Here is a workflow example

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: podinfo-
  namespace: siebren
  labels:
    foo: bar
spec:
  serviceAccountName: argo-events-sa
  entrypoint: whalesay
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
  templates:
  - name: whalesay
    metadata:
      labels:
        pod/foo: foo
        pod/bar: bar
        pod/baz: baz
    container:
      image: docker/whalesay
      workingDir: /etc/podinfo
      command:
        - /bin/sh
        - -c
      args:
        - cat labels
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
      resources:
        limits:
          memory: 32Mi
          cpu: 100m
```
