### ISSUE TITLE
 Stop and then retry does not work and changes Workflow orignal (pre stop) Node tree 

### ISSUE THREAD

**Issue by sid8489** [argoproj/argo-workflows#10918]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

We stop a running workflow , and  do a retry on the same, then node tree gets altered/corrupted, some  nodes  goes missing or are marked as Skipped.

On stoping a workflow last node and it's boundary nodes should be marked as failed , and post retry the failed node should be restarted and Node tree should remain the same

One can run the provided workflow  and try following below steps to reproduce.

1. Stop When 1st step s1 is in Running state
<img width="1343" alt="Screenshot 2023-04-14 at 10 40 54 PM" src="https://user-images.githubusercontent.com/85802930/232112930-9c629aab-ba3a-435e-abe2-1030f6abb763.png">

<img width="1339" alt="Screenshot 2023-04-14 at 10 41 02 PM" src="https://user-images.githubusercontent.com/85802930/232112995-99f61db7-bafc-4dc1-8271-3e08f59e0664.png">

Then Post Retry

<img width="1216" alt="Screenshot 2023-04-14 at 10 44 26 PM" src="https://user-images.githubusercontent.com/85802930/232112634-540a8ae5-e184-42d8-9102-6f43ce4cd9eb.png">

2.   Stop When 1st step s2 is in Pending state (Note: I have on purpose used a non existent image so that  s2 remains in pending state) . 
<img width="1324" alt="Screenshot 2023-04-14 at 11 00 50 PM" src="https://user-images.githubusercontent.com/85802930/232117222-547bef73-e5ef-47e9-9464-485cf44dad34.png">

<img width="1320" alt="Screenshot 2023-04-14 at 11 01 05 PM" src="https://user-images.githubusercontent.com/85802930/232117111-350db038-cb64-420b-a3d3-35e2b6ce4145.png">
Then Post Retry
<img width="931" alt="Screenshot 2023-04-14 at 11 03 10 PM" src="https://user-images.githubusercontent.com/85802930/232116936-470516d5-d71f-4615-9ad9-5c5fef0b2a00.png">

### Version

v3.3.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  name: stop-and-retry
spec:
  templates:
    - name: xyz
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: s1
            template: argosay
            arguments: {}
        - - name: s2
            template: argosay1
            arguments: {}
    - name: argosay
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - hello
        resources: {}
    - name: argosay1
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: main
        image: 'argoproj/argosayaaaaaa:v2'
        command:
          - /argosay
        args:
          - echo
          - hello
        resources: {}
  entrypoint: xyz
  arguments:
    parameters:
      - name: message
        value: hello argo
  serviceAccountName: argo-workflows
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
