### ISSUE TITLE
`workflowMetadata` set in `workflowDefaults` doesn't work for `WorkflowTemplate`

### ISSUE THREAD

**Issue by pockyhe** [argoproj/argo-workflows#10946]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I set default key-value pair in labels of workflowMetadata in workflowDefaults like the following:
![image](https://user-images.githubusercontent.com/64390829/233297970-976b2f4f-ec0e-46c7-b32d-85b3d8e97d38.png)
Then, I tried to use workflow.labels directly in workflowtemplate and submitted it. It cause error:
```
time="2023-04-20T15:56:10.021Z" level=fatal msg="Failed to submit workflow: rpc error: code = InvalidArgument desc = templates.whalesay-template: failed to resolve {{workflow.labels.arg-name}}
```

It seems that workflow submitted by workflowtemplate cannot get the default workflowMetadata or metadata in workflowDefaults.

How can I make workflow.labels in workflowtemplate get default value?

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  entrypoint: whalesay-template
  templates:
    - name: whalesay-template
      container:
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{workflow.labels.arg-name}}'
```

### Logs from the workflow controller

```text
no
```

### Logs from in your workflow's wait container

```text
no
```
