### ISSUE TITLE
Cannot set both parallelism and namespaceParallelism

### ISSUE THREAD

**Issue by yuzhouliu9** [argoproj/argo-workflows#10985]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

In the `workflow-controller-configmap`, setting:
``` 
  parallelism: "10"
  namespaceParallelism: "5"
```

**Expectation**
The global number of running workflows to be limited at 10, and the running workflows per namespace limited to 5.

**Actual**
However, in testing, argo-workflows limits the global number of workflows to 5.

Having each setting individually works as expected, but not when they are together. This is a cluster installation.

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

Simple workflow that sleeps 5 mins.
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallelism-test-
spec:
  entrypoint: test
  podGC:
    strategy: OnWorkflowCompletion
  ttlStrategy:
    secondsAfterCompletion: 60
  templates:
  - name: test
    steps:
    - - name: test-1
        template: sleep
  - name: sleep
    container:
      image: alpine:latest
      command: [sleep, "300"]
```

Script that submits the above workflow 10 times to a namespace
```sh
#!/bin/bash

for i in {1..10}
do
    argo submit workflow.yaml -n $1 &
done
```

Submit to `default` and `devops` namespace
```
./submit.sh default
./submit.sh devops
```

### Screenshots from UI, notice the number of running workflows for each namespace, and stuck waiting.
![Screenshot 2023-04-26 at 4 28 52 PM](https://user-images.githubusercontent.com/89029096/234696008-4cfe5ae5-9be3-4559-92ac-18cc22bceb65.png)

![Screenshot 2023-04-26 at 4 27 26 PM](https://user-images.githubusercontent.com/89029096/234696051-391a3020-7845-4b57-9c2d-7887eabdd490.png)

### Logs from the workflow controller
[controller_logs.txt](https://github.com/argoproj/argo-workflows/files/11337003/controller_logs.txt)

### Logs from in your workflow's wait container
I don't think this is relevant.
