### ISSUE TITLE
withSequence not work

### ISSUE THREAD

**Issue by TomLi121** [argoproj/argo-workflows#10990]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

**Bad Request: templates.parameter-aggregation.steps failed to resolve {{steps.odd-or-even.outputs.parameters}}**

This works fine if you replace withSequence with withItems . like
withItems: [1, 2, 3, 4]

I think using withSequence should work just fine

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# Example workflow to demonstrate parameter aggregation.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameter-aggregation-
spec:
  entrypoint: parameter-aggregation
  templates:
  - name: parameter-aggregation
    steps:
    # First loop through a list of numbers and determine if the number is odd or even. This is
    # captured in output parameter 'evenness'. (e.g. {"num": "4", "evenness": "even"})
    - - name: odd-or-even
        template: odd-or-even
        arguments:
          parameters:
          - name: num
            value: "{{item}}"
        withSequence:
          count: "3"
    # Next, for each even number, divide it by two (using a script template).
    # Skip odd numbers using a `when` clause.
    - - name: divide-by-2
        template: divide-by-2
        arguments:
          parameters:
          - name: num
            value: "{{item.num}}"
        withParam: "{{steps.odd-or-even.outputs.parameters}}"
        when: "{{item.evenness}} == even"
    # Finally, print all numbers processed in the previous step
    - - name: print
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withParam: "{{steps.divide-by-2.outputs.result}}"

  # odd-or-even accepts a number and returns whether or not that number is odd or even
  - name: odd-or-even
    inputs:
      parameters:
      - name: num
    container:
      image: alpine:latest
      command: [sh, -xc]
      args:
      - |
        sleep 1 &&
        echo {{inputs.parameters.num}} > /tmp/num &&
        if [ $(({{inputs.parameters.num}}%2)) -eq 0 ]; then
          echo "even" > /tmp/even;
        else
          echo "odd" > /tmp/even;
        fi
    outputs:
      parameters:
      - name: num
        valueFrom:
          path: /tmp/num
      - name: evenness
        valueFrom:
          path: /tmp/even

  # divide-by-2 divides a number in half
  - name: divide-by-2
    inputs:
      parameters:
      - name: num
    script:
      image: alpine:latest
      command: [sh, -x]
      source: |
        #!/bin/sh
        echo $(({{inputs.parameters.num}}/2))

  # whalesay prints a number using whalesay
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
