### ISSUE TITLE
ui: getPodName is using v1 by default

### ISSUE THREAD

**Issue by or-shachar** [argoproj/argo-workflows#11015]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I noticed that for some workflows the podName is wrongfully set as the nodeID (which is the v1 format).

This resulted in bad log streaming for running templates. (I thought it was related to https://github.com/argoproj/argo-workflows/issues/10124 but I think it's a pure UI issue).

Looking at the ts code I saw this condition:
https://github.com/argoproj/argo-workflows/blob/0c24ca1ba8a5c38c846d595770e16398f6bd84a5/ui/src/app/shared/pod-name.ts#L14

The `version` here is taken straight from the direct annotation of the workflow: https://github.com/argoproj/argo-workflows/blob/133b4a384364079e5c82580c4969ded636cbadf5/ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx#L56

I think that after https://github.com/argoproj/argo-workflows/commit/cc9d14cf0d60812e177ebb447181df933199b722 we should change the condition so that v2 would be used by default also for UI.

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
{
  "metadata": {
    "name": "fantastic-rhino",
    "namespace": "argo-workflows",
    "labels": {
      "example": "true"
    }
  },
  "spec": {
    "arguments": {
      "parameters": [
        {
          "name": "message",
          "value": "hello argo"
        }
      ]
    },
    "entrypoint": "argosay",
    "templates": [
      {
        "name": "argosay",
        "inputs": {
          "parameters": [
            {
              "name": "message",
              "value": "{{workflow.parameters.message}}"
            }
          ]
        },
        "container": {
          "name": "main",
          "image": "argoproj/argosay:v2",
          "command": [
            "/argosay"
          ],
          "args": [
            "echo",
            "{{inputs.parameters.message}}"
          ]
        }
      }
    ],
    "ttlStrategy": {
      "secondsAfterCompletion": 300
    },
    "podGC": {
      "strategy": "OnPodCompletion"
    }
  }
}
```

### Logs from the workflow controller

```text
Irrelevant
```

### Logs from in your workflow's wait container

```text
Irrelevant
```
