### ISSUE TITLE
WorkflowTemplates referred to by other WTs don't carry forward affinity

### ISSUE THREAD

**Issue by Goorzhel** [argoproj/argo-workflows#11014]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

**Expected:** Pods created from WTs referred to by other WTs have `.spec.affinity` set according to the referred WT (in the case attached, the referred WT is `wftmpl/hello`).

**Actual:** Pods have no affinity.

```
$ argo submit --from=wftmpl/say-hello -p subject=world --generate-name=hello-
Name:                hello-p4x5d
Namespace:           svc
ServiceAccount:      unset
Status:              Pending
Created:             Sat Apr 29 20:05:57 -0700 (now)
Progress:
Parameters:
  subject:           world
$ kg -o json pod hello-p4x5d-greet-2063515318 | jq .spec.affinity
null
```

### Version

2.4.6 (also latest)

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

<details>

<summary>Details tags added for the sake of my scroll wheel finger</summary>

```YAML
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: say-hello
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: subject
      description: Person or thing to greet
  volumes:
  templates:
  - name: main
    inputs:
      parameters:
      - name: subject
        default: "world"
    steps:
    - - name: hello
        templateRef:
          name: hello
          template: hello
        arguments:
          parameters:
          - name: subject
            value: "{{inputs.parameters.subject}}"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello
spec:
  entrypoint: hello
  podMetadata:
    labels:
      workflow.goorzhel.com: "hello"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: workflow.goorzhel.com
            operator: In
            values: [hello]
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: NotIn
            values: ["k3s"]
  arguments:
    parameters:
    - name: subject
      description: Person or thing to greet
  templates:
  - name: hello
    inputs:
      parameters:
      - name: subject
    steps:
    - - name: greet
        template: greet
        arguments:
          parameters:
          - name: subject
            value: "{{inputs.parameters.subject}}"

  - name: greet
    inputs:
      parameters:
      - name: subject
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["Hello, {{inputs.parameters.subject}}!"]
```

</details>

### Logs from the workflow controller

<details>

```text
time="2023-04-30T03:05:57.040Z" level=info msg="Processing workflow" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.061Z" level=info msg="Updated phase  -> Running" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.062Z" level=info msg="Steps node hello-p4x5d initialized Running" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.062Z" level=info msg="StepGroup node hello-p4x5d-3868001127 initialized Running" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.062Z" level=info msg="Steps node hello-p4x5d-548563289 initialized Running" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.062Z" level=info msg="StepGroup node hello-p4x5d-609621357 initialized Running" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.063Z" level=info msg="Pod node hello-p4x5d-2063515318 initialized Pending" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.213Z" level=info msg="Created pod: hello-p4x5d[0].hello[0].greet (hello-p4x5d-greet-2063515318)" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.213Z" level=info msg="Workflow step group node hello-p4x5d-609621357 not yet completed" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.213Z" level=info msg="Workflow step group node hello-p4x5d-3868001127 not yet completed" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.213Z" level=info msg="TaskSet Reconciliation" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.213Z" level=info msg=reconcileAgentPod namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:05:57.235Z" level=info msg="Workflow update successful" namespace=svc phase=Running resourceVersion=6153953 workflow=hello-p4x5d
time="2023-04-30T03:06:07.216Z" level=info msg="Processing workflow" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:07.217Z" level=info msg="Task-result reconciliation" namespace=svc numObjs=0 workflow=hello-p4x5d
time="2023-04-30T03:06:07.217Z" level=info msg="node changed" namespace=svc new.message= new.phase=Running new.progress=0/1 nodeID=hello-p4x5d-2063515318 old.message= old.phase=Pending old.progress=0/1 workflow=hello-p4x5d
time="2023-04-30T03:06:07.218Z" level=info msg="Workflow step group node hello-p4x5d-609621357 not yet completed" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:07.218Z" level=info msg="Workflow step group node hello-p4x5d-3868001127 not yet completed" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:07.218Z" level=info msg="TaskSet Reconciliation" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:07.218Z" level=info msg=reconcileAgentPod namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:07.235Z" level=info msg="Workflow update successful" namespace=svc phase=Running resourceVersion=6154080 workflow=hello-p4x5d
time="2023-04-30T03:06:17.236Z" level=info msg="Processing workflow" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:17.237Z" level=info msg="Task-result reconciliation" namespace=svc numObjs=0 workflow=hello-p4x5d
time="2023-04-30T03:06:17.237Z" level=info msg="node changed" namespace=svc new.message= new.phase=Running new.progress=0/1 nodeID=hello-p4x5d-2063515318 old.message= old.phase=Running old.progress=0/1 workflow=hello-p4x5d
time="2023-04-30T03:06:17.238Z" level=info msg="Workflow step group node hello-p4x5d-609621357 not yet completed" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:17.238Z" level=info msg="Workflow step group node hello-p4x5d-3868001127 not yet completed" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:17.238Z" level=info msg="TaskSet Reconciliation" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:17.238Z" level=info msg=reconcileAgentPod namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:17.243Z" level=info msg="cleaning up pod" action=terminateContainers key=svc/hello-p4x5d-greet-2063515318/terminateContainers
time="2023-04-30T03:06:17.243Z" level=info msg="https://10.43.0.1:443/api/v1/namespaces/svc/pods/hello-p4x5d-greet-2063515318/exec?command=%2Fbin%2Fsh&command=-c&command=kill+-15+1&container=istio-proxy&stderr=true&stdout=true&tty=false"
time="2023-04-30T03:06:17.252Z" level=info msg="Workflow update successful" namespace=svc phase=Running resourceVersion=6154184 workflow=hello-p4x5d
time="2023-04-30T03:06:17.386Z" level=info msg="signaled container" container=istio-proxy error="<nil>" namespace=svc pod=hello-p4x5d-greet-2063515318 stderr= stdout=
time="2023-04-30T03:06:27.254Z" level=info msg="Processing workflow" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.254Z" level=info msg="Task-result reconciliation" namespace=svc numObjs=0 workflow=hello-p4x5d
time="2023-04-30T03:06:27.254Z" level=info msg="node changed" namespace=svc new.message= new.phase=Succeeded new.progress=0/1 nodeID=hello-p4x5d-2063515318 old.message= old.phase=Running old.progress=0/1 workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="Step group node hello-p4x5d-609621357 successful" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="node hello-p4x5d-609621357 phase Running -> Succeeded" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="node hello-p4x5d-609621357 finished: 2023-04-30 03:06:27.25537223 +0000 UTC" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="Outbound nodes of hello-p4x5d-2063515318 is [hello-p4x5d-2063515318]" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="Outbound nodes of hello-p4x5d-548563289 is [hello-p4x5d-2063515318]" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="node hello-p4x5d-548563289 phase Running -> Succeeded" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="node hello-p4x5d-548563289 finished: 2023-04-30 03:06:27.255588088 +0000 UTC" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="Step group node hello-p4x5d-3868001127 successful" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="node hello-p4x5d-3868001127 phase Running -> Succeeded" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="node hello-p4x5d-3868001127 finished: 2023-04-30 03:06:27.2556539 +0000 UTC" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="Outbound nodes of hello-p4x5d-548563289 is [hello-p4x5d-2063515318]" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="Outbound nodes of hello-p4x5d is [hello-p4x5d-2063515318]" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="node hello-p4x5d phase Running -> Succeeded" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="node hello-p4x5d finished: 2023-04-30 03:06:27.255907429 +0000 UTC" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="TaskSet Reconciliation" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg=reconcileAgentPod namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="Updated phase Running -> Succeeded" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.255Z" level=info msg="Marking workflow completed" namespace=svc workflow=hello-p4x5d
time="2023-04-30T03:06:27.261Z" level=info msg="cleaning up pod" action=deletePod key=svc/hello-p4x5d-1340600742-agent/deletePod
time="2023-04-30T03:06:27.276Z" level=info msg="Workflow update successful" namespace=svc phase=Succeeded resourceVersion=6154283 workflow=hello-p4x5d
time="2023-04-30T03:06:27.285Z" level=info msg="cleaning up pod" action=labelPodCompleted key=svc/hello-p4x5d-greet-2063515318/labelPodCompleted
time="2023-04-30T03:06:47.387Z" level=info msg="cleaning up pod" action=killContainers key=svc/hello-p4x5d-greet-2063515318/killContainers
```

</details>

### Logs from in your workflow's wait container

<details>

```text
time="2023-04-30T03:06:02.976Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-04-30T03:06:02.976Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=svc podName=hello-p4x5d-greet-2063515318 template="{\"name\":\"greet\",\"inputs\":{\"parameters\":[{\"name\":\"subject\",\"value\":\"world\"}]},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"docker/whalesay\",\"command\":[\"cowsay\"],\"args\":[\"Hello, world!\"],\"resources\":{}}}" version="&Version{Version:untagged,BuildDate:2023-04-28T01:32:34Z,GitCommit:91f2a4548832d1a669ed2cc32623ead83013fc97,GitTag:untagged,GitTreeState:clean,GoVersion:go1.19.8,Compiler:gc,Platform:linux/amd64,}"
time="2023-04-30T03:06:02.976Z" level=info msg="Starting deadline monitor"
time="2023-04-30T03:06:06.979Z" level=info msg="Main container completed" error="<nil>"
time="2023-04-30T03:06:06.979Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-04-30T03:06:06.979Z" level=info msg="No output parameters"
time="2023-04-30T03:06:06.979Z" level=info msg="No output artifacts"
time="2023-04-30T03:06:06.979Z" level=info msg="Alloc=10101 TotalAlloc=15864 Sys=28781 NumGC=4 Goroutines=7"
time="2023-04-30T03:06:06.979Z" level=info msg="Deadline monitor stopped"
time="2023-04-30T03:06:06.979Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
```

</details>
