### ISSUE TITLE
Entrypoint ignored when WT references another WT

### ISSUE THREAD

**Issue by Gab-Menezes** [argoproj/argo-workflows#11039]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

If you have a WT `A` that have a `main` entrypoint (obviously `A` has a template called `main`) and reference this template in another WT `B` with: `.spec.workflowTemplateRef` the entrypoint will not be carried. Now if you use this template `B` in conventional workflow `W` with: `.spec.workflowTemplateRef` you get an error message saying that the entrypoint is missing.

**Expected:** The `.spec.entrypoint` would be carried in a WT that references another WT

**Actual:** If I apply the first two files (`wt.yaml` and `wt-wt.yaml`) (check below section) and lint the workflow I get:
![image](https://user-images.githubusercontent.com/29588635/236420626-52d86c1d-4739-4744-b874-cc98928baab1.png)
If add the entrypoint to the workflow or delete the `wt-wt` template and add to it I get:
![image](https://user-images.githubusercontent.com/29588635/236420825-4e280a81-dacb-464c-95ec-3d69d8914e6f.png)

### Version

3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
#wt.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wt
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["Hello, {{workflow.parameters.name}}!"]
---
#wt-wt.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wt-wt
spec:
  synchronization:
    mutex:
      name: my-mutex-{{workflow.parameters.mutex-name}}
  arguments:
    parameters:
      - name: name
        value: argo
  workflowTemplateRef:
    name: wt
---
#wf.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-
spec:
  arguments:
    parameters:
      - name: mutex-name
        value: my-mutex
  workflowTemplateRef:
    name: wt-wt
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by JPZ13** [comment]
Hey @Gab-Menezes - are you able to work around the issue by referencing the template itself within the workflow template ref? For example:
```
workflowTemplateRef:
  name: wf
  template: main
```

**Comment by Gab-Menezes** [comment]
@JPZ13 the field `template` doesn't exist in `workflowTemplateRef`. Tried adding to `wf.yaml` and `wt-wt.yaml`
![image](https://github.com/argoproj/argo-workflows/assets/29588635/dde23f55-7843-4046-9d1a-6dc5cd6b2d8f)
If you try to use this yaml instead the first `wt-wt.yaml` you will get the same error.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wt-wt
spec:
  synchronization:
    mutex:
      name: my-mutex-{{workflow.parameters.mutex-name}}
  arguments:
    parameters:
      - name: name
        value: argo
  workflowTemplateRef:
    name: wt
    template: main
```
