### ISSUE TITLE
Liveness probe fails with 500 and "workflow never reconciled" (under-resourced k8s apiserver)

### ISSUE THREAD

**Issue by PidgeyBE** [argoproj/argo-workflows#11051]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

This issue explains exactly what happens https://github.com/argoproj/argo-workflows/issues/6351
As it was closed, I'm opening a regression report.

Similar to the parent issue, we are deploying multiple workflows on our kubernetes cluster.
We haven't enabled Workflow GC/TTL so workflows keep stacking up in the kubernetes etcd.
After a while (when ~100 Workflow CRs are present), we notice Workflows are not being executed anymore. As in the parent issue, we see that `status.phase` is not being set any more on the Workflow CR.
When checking the `/healthz` endpoint, we see:
```
500 workflow never reconciled: workflow-0a9cf5a8-73e4-4d4e-924b-0be6f9c26d51
```

Because we were using the bitnami helm charts for argo workflows, the Argo Workflows Controller is not restarted because the bitnami helm charts have a bad liveness probe.

Loggingwize, I enabled `--debug` logging on the workflow controller, but nothing extraordinary is logged. What we do see is that the `Watch workflows` log line stops printing when the issue occurs:
![image](https://user-images.githubusercontent.com/19860056/236789876-2d2722c5-62ae-4051-8fdb-f48f5b5b7c6a.png)

We think the issue is triggered by the amount of Workflows that are putting stress on K8s etcd + the fact that our kubernetes API server was underdimensioned:
![image](https://user-images.githubusercontent.com/19860056/236790230-1cd34ff8-e399-4819-9b44-4b5d98bbc3a1.png)

The size of a single workflow manifest is ~100kB.

We are mitigating the issue now by:
* Using the correct liveness probe for the Workflow Controller so it gets automatically restarted when failing.
* Enabling Workflow GC TTL to minimize the load on kubernetes etcd
* Granting more resources to our kubernetes master node.

However, we think the Argo Workflows Controller should be more resilient to a sloppy kubernetes API.

CC @alexec as you were involved in the parent issue. 

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Issue is not related to a specific kind of workflow. But by the amount of Workflows present in the kubernetes cluster + the fitness of the Kubernetes API.
```

### Logs from the workflow controller
See main description about what stood out for me in the logs (i.e. the stopping of `Watch workflows`)
Full logs: 
[argo_controller.log](https://github.com/argoproj/argo-workflows/files/11432075/argo_controller.log)

### Logs from in your workflow's wait container

```text
$ kubectl logs -n bonzai -c wait -l workflow.argoproj.io/phase!=Succeeded 
No resources found in bonzai namespace.
```
```

**Comment by tooptoop4** [comment]
@PidgeyBE what is the correct liveness probe?

**Comment by PidgeyBE** [comment]
> @PidgeyBE what is the correct liveness probe?

@tooptoop4 The argo helm charts have the correct liveness probe: https://github.com/argoproj/argo-helm/blob/2197c8e0402ab1074761af8d5f45825f0d59d4e1/charts/argo-workflows/values.yaml#L252
But we are (currently) using the Bitnami charts which only check if port 6060 has a TCP socket open: https://github.com/bitnami/charts/blob/dfa8cd40702d00d38fc313ff68408ceecba68dd3/bitnami/argo-workflows/templates/controller/deployment.yaml#L150 , which can be overwritten by:
```
    customLivenessProbe:
      httpGet:
        port: 6060
        path: /healthz
```

**Comment by terrytangyuan** [comment]
Closing as it's related to Bitnami charts

**Comment by PidgeyBE** [comment]
Hi @terrytangyuan 
I probably didnt make myself clear.
The bug/regression I'm raising is _not_ related to Bitnami charts. The only relation to Bitnami charts is that the Bitnami charts have a bad liveness probe, which makes the regression more apparent.

The issue that was allegedly solved in https://github.com/argoproj/argo-workflows/issues/6351 is not actually solved, so I don't see a reason to close this issue.

**Comment by terrytangyuan** [comment]
It would be helpful to see YAML of your problematic workflow and relevant controller logs.

**Comment by PidgeyBE** [comment]
Hi @terrytangyuan 
Thank you fro reopening the issue.
I've added workflow controller logs to the initial post.

And an example workflow here: [workflow_yaml.txt](https://github.com/argoproj/argo-workflows/files/11432205/workflow_yaml.txt)
Note: This workflow succeeded after restarting the workflow controller.
However: I don't think a "problematic workflow" is the issue. The issue is the workflow controller stops picking/processing up _any_ workflow. Even a simple dummy workflow. 

The best way to reproduce the issue (in my experience) is:
1. Reducing the resources of the kubernetes master node as much as possible (e.g. only allocate 1 vcpu for the kubernetes master node)
2. Creating a lot of Workflow CRs so `kubectl get workflows --all-namespaces | wc -l` yields a few hundreds.
3. Deploy a new workflow
4. Like in https://github.com/argoproj/argo-workflows/issues/6351 and https://github.com/argoproj/argo-workflows/issues/7845 the `status.phase` remains empty.

According to https://github.com/argoproj/argo-workflows/issues/7845#issuecomment-1038941164 the issue is mitigated by deleting old workflows, which is what we see as well. But according to me, that's not a real solution. I think the Argo workflows Controller should be resilient enough to overcome a slow kubernetes API. Or at least log a clear error message about it.

Of course, if you disagree, you can close the issue again :)

**Comment by Eva-Music** [comment]
I have the same bug! And it happened suddenly after I added s3 artifact repository.

**Comment by PidgeyBE** [comment]
Although it sounds weird that it would be related to the s3 artifact repository, we use this feature as well.

**Comment by Izvunzemen** [comment]
We hit the same issue, is there any solution to this?

**Comment by terrytangyuan** [comment]
Please share the YAML of any problematic workflows that have never been reconciled

**Comment by jkldrr** [comment]
We are currently encountering the same issue with a much simpler single step workflow, but we run a lot of them. The health endpoint reports: workflow never reconciled ...
argo-workflows version: 3.4.10
K8s-version: 1.27.3

**Comment by GuerreiroLeonardo** [comment]
I have the same error: here is my yaml:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-latampay-compensation
spec:
  serviceAccountName: {{ include "application.serviceAccountName" . }}
  archiveLogs: true
  activeDeadlineSeconds: 28800
  ttlStrategy:
    secondsAfterCompletion: 1296000
  podGC:
    strategy: OnWorkflowSuccess
  entrypoint: conciliation
  {{- if eq .Values.env "prd" }}
  hooks:
    running:
      expression: workflow.status == "Failed" || workflow.status == "Error"
      template: error-handler
  {{- end }}
  arguments:
    parameters:
    - name: date
      value: {{`"{{=sprig.dateInZone('2006-01-02', sprig.toDate('2006-01-02T15:04:05Z07:00', workflow.creationTimestamp.RFC3339), 'UTC')}}"`}} 
  templates:
    - name: conciliation
      metadata:
        labels:
          azure.workload.identity/use: {{ default false .Values.serviceAccount.useWorkloadIdentity | quote }}
      container:
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["npm", "run", "release",  "--"]
        args: 
         - "--task=paymentcompensation"
         - {{`"--date={{workflow.parameters.date}}"`}}
        env:
          - name: ENVIRONMENT
            value: {{ .Values.env }}
          - name: AZURE_KEYVAULT_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.keyvaultName }}
                key: AzureKeyVault_Endpoint
                optional: false
          - name: AZURE_KEYVAULT_ENABLED
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.keyvaultName }}
                key: AzureKeyVault_Enabled
                optional: false
          - name: AZURE_KEYVAULT_TENANTID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.keyvaultName }}
                key: AzureKeyVault_TenantId
                optional: false
          - name: AZURE_KEYVAULT_CLIENTID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.keyvaultName }}
                key: AzureKeyVault_ClientId
                optional: false
          - name: AZURE_KEYVAULT_CLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.keyvaultName }}
                key: AzureKeyVault_ClientSecret
                optional: false
    {{- if eq .Values.env "prd" }}
    - name: error-handler
      container:
        image: curlimages/curl
        command: [ curl ]
        args:
          - '--location'
          - 'https://di.webhook.office.com/webhookb2/c771f713-36fa-47f5-b68964@335f05ae-c8b2-44cf-be82-1c05dcd8e51c/IncomingWebhook/561f9425ac44801/c33aca60-f77c-45e6-88a3-74312d886016'
          - '--header'
          - 'Content-Type: application/json'
          - '--data-raw'
          - '{"@type": "MessageCard","themeColor": "0076D7","summary": "Workflow execution finished!","sections": [{"activityTitle": "Workflow execution finished!","activitySubtitle": "Veja o status abaixoU0001F447U0001F3FB","activityImage": "https://argoproj.github.io/argo-workflows/assets/logo.png","facts": [{"name": "Workflow","value": "{{ "{{" }}workflow.name{{ "}}" }}"},{"name": "Status","value": "{{ "{{" }}workflow.status{{ "}}" }}"}, {"name": "Environment","value": {{ .Values.env | quote }} }],"markdown": true}]}'
    {{- end }}
```
