### ISSUE TITLE
UI shows "null is not an object" if retry a failed container set workflow

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-workflows#11061]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

If i retry a failed container set workflow from the UI (retry button upper left hand side in workflow view) the UI shows following error:
```
null is not an object (evaluating 'r.type')

Stack Trace
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:341:68304
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:341:67160
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:341:64859
Pa@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:397:69883
uc@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:397:96720
sc@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:397:96645
$s@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:397:93675
$s@[native code]
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:397:45316
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:405:3845
Xo@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:397:45262
Uo@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:397:45197
Ks@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:397:90460
ba@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:397:62277
ba@[native code]
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:432:1138209
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:341:212417
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:18:29137
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:18:28290
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:18:27358
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:18:27030
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:23:28558
@https://argo-workflows.radiosphere.com/main.4552298cb2e9cc74bb4b.js:18:27030

Component Stack

    in t
    in t
    in div
    in div
    in div
    in div
    in div
    in Unknown
    in Unknown
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in div
    in Unknown
    in t
    in t
    in Unknown
    in t
```

Page needs to be reloaded to show Workflow list again.

<img width="693" alt="Screenshot 2023-05-10 at 10 04 40" src="https://github.com/argoproj/argo-workflows/assets/50194881/37bccf64-d40c-4a44-90a5-d3eb3626afe3">

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: container-set-test
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: app
      value: app
  serviceAccountName: workflow
  templates:
  - name: main
    inputs:
      parameters:
      - name: app
    containerSet:
      containers:

      - name: run
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -eux
          exit 0
        
      - name: fail
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -eux
          exit 1
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
