### ISSUE TITLE
ui: Common filters buttons

### ISSUE THREAD

**Issue by or-shachar** [argoproj/argo-workflows#11112]
# Summary

I think we should add onfigurable quick-filter buttons at the top of the workflow history view.
Something like:
|MOCK|
|---|
|![Picture1](https://github.com/argoproj/argo-workflows/assets/2962963/f5eb3b7d-21cb-4901-95c0-96018345f27e)|

# Use Cases

## Problem
- Sometimes our server runs many workflows of different kinds (I'm talking about hundreds of runs per day).
- To navigate to different history views of different contexts, user needs to either:
       - Re-type the filter every time. Sometimes the drop-down even misses some of the possible values (I guess due to [this](https://github.com/argoproj/argo-workflows/issues/4546))
       - Use browser bookmarks (local to machine / user account).

## Suggested solution:
- As a user, I want to quickly jump to different views with different label filtering
- As an admin, I want all users to enjoy common filters.
- Seems like we have unused real estate on the top of the page that can accommodate more custom buttons. 

Maybe as part of the configmap I can provide something like this:
```yaml
navColor: lightslategray # maybe this should be moved to `web` as well
web:
   navColor: lightslategray
   common_filters:
        - name: "TEST BACKNED"
          filter: "label=deploy/type=backend&label=deploy/env=test"
        - name: "TEST INFRA"
          filter: "label=deploy/type=infra&label=deploy/env=stage"
        - name: "STAGE BACKEND"
          filter: "label=deploy/type=backend&label=deploy/env=stage"
        - name: "STAGE INFRA"
          filter: "label=deploy/type=infra&label=deploy/env=stage"
```
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
This should be achievable via https://github.com/argoproj/argo-workflows/pull/10808.

**Comment by or-shachar** [comment]
@terrytangyuan - Awesome!

@rbreeze  - looks amazing!

Excuse my tsx ignorance, but will this make the link open up in a new tab / reload the page?
```tsx
          ...this.state.links.map(link => ({
              title: link.name,
              iconClassName: 'fa fa-external-link',
              action: () => (window.location.href = link.url)
```

If so - maybe we should add another type of link that simply changes the filter on the current view without reloading the page?

WDYT?

**Comment by terrytangyuan** [comment]
I think it opens up a new tab. cc @rbreeze @jiachengxu who contributed this for feedback.

**Comment by moonyoungCHAE** [comment]
If a way of filtering without reloading the page is added by config map, it will be convenient because the filters set by the user on the UI will be maintained. However, I think it could cause confusion if the filtering button is located at the same level as the existing reload button. So it would be better to use the existed way to redirect url.

**Comment by agilgur5** [comment]
> If so - maybe we should add another type of link that simply changes the filter on the current view without reloading the page?

that could be done as a field on the `links` spec. e.g. `newTab: true` or something

**Comment by Joibel** [comment]
This has been implemented. Since v3.5 you can configure buttons at the top of the Workflow List view via the `links` section of the workflow-controller ConfigMap using `scope: workflow-list`, e.g.:

```yaml
links: |
  - name: Test Backend
    scope: workflow-list
    url: /workflows/my-ns?label=deploy/type=backend&label=deploy/env=test
```

See https://argo-workflows.readthedocs.io/en/latest/links/ and the example in `docs/workflow-controller-configmap.yaml`.

The follow-up question in this thread about new-tab vs same-tab was addressed by the `target` field on links (https://github.com/argoproj/argo-workflows/pull/14314, released in v3.7) — set `target: _self` to navigate in the current tab.

Closing as implemented; please open a new issue if you specifically want these links to change the filters client-side without a page navigation.
