### ISSUE TITLE
argo deletes persistant volume claims prematurely when parallelism is set lower than the number of items in loop

### ISSUE THREAD

**Issue by abrabah** [argoproj/argo-workflows#11119]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Submitting a workflow looping over items in parallel using persistent volume claims causes the whole workflow to hang if workflow.spec.parallelism is set too low. Logs indicate that the workflow gets cancelled due to "max parallelism reached", which again causes the pvc's to get garbage collected.  I expected argo workflow to honor the parallelism field and not launch more sub tasks than allowed by throttling execution.

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: loop-fail-3
spec:
  entrypoint: constrained-loops-with-volumes
  parallelism: 1
  volumeClaimTemplates:
  - metadata:
      name: one
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: two
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  
  
  templates:
  - name: constrained-loops-with-volumes
    steps:
    - - name: write-and-read-msg-from-pvc
        template: write-and-read-msg-from-pvc
        arguments:
          parameters:
          - name: pvc
            value: '{{item}}'
        withItems: 
          - one
          - two
  - name: write-and-read-msg-from-pvc
    inputs:
      parameters:
      - name: pvc
    steps:
    - - name: write-msg
        template: write-msg
        arguments:
          parameters:
          - name: pvc
            value: '{{inputs.parameters.pvc}}'        
    - - name: read-msg
        template: read-msg
        arguments:
          parameters:
          - name: pvc
            value: '{{inputs.parameters.pvc}}'
  - name: write-msg
    inputs:
      parameters:
      - name: pvc
    script:
      image: busybox:stable
      command: ["sh"]
      source: | 
        echo "Hello! i'm writing to pvc; '{{inputs.parameters.pvc}}'" >> /pvc/msg
      volumeMounts:
      - name: '{{inputs.parameters.pvc}}'
        mountPath: /pvc
  - name: read-msg
    inputs:
      parameters:
      - name: pvc
    script:
      image: busybox:stable
      command: ["sh"]
      source: | 
        echo "Found the following message;"
        cat /pvc/msg
      volumeMounts:
      - name: '{{inputs.parameters.pvc}}'
        mountPath: /pvc
```

### Logs from the workflow controller

```text
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.621Z" level=info msg="Processing workflow" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.627Z" level=info msg="Updated phase  -> Running" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.627Z" level=info msg="Creating pvc loop-fail-3-one" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.640Z" level=info msg="Creating pvc loop-fail-3-two" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.646Z" level=info msg="Steps node loop-fail-3 initialized Running" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.646Z" level=info msg="StepGroup node loop-fail-3-3565738732 initialized Running" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.647Z" level=info msg="Steps node loop-fail-3-1631888154 initialized Running" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.647Z" level=info msg="StepGroup node loop-fail-3-4073678796 initialized Running" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.651Z" level=info msg="Pod node loop-fail-3-37876413 initialized Pending" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.665Z" level=info msg="Created pod: loop-fail-3[0].write-and-read-msg-from-pvc(0:one)[0].write-msg (loop-fail-3-write-msg-37876413)" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.665Z" level=info msg="Workflow step group node loop-fail-3-4073678796 not yet completed" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.666Z" level=info msg="workflow active pod spec parallelism reached 1/1" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.666Z" level=info msg="Workflow step group node loop-fail-3-3565738732 not yet completed" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.666Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.666Z" level=info msg=reconcileAgentPod namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:07.740Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=2544 workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.667Z" level=info msg="Processing workflow" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.667Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.667Z" level=info msg="node changed" namespace=default new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=loop-fail-3-37876413 old.message= old.phase=Pending old.progress=0/1 workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.669Z" level=info msg="workflow active pod spec parallelism reached 1/1" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.669Z" level=error msg="error in entry template execution" error="Max parallelism reached" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.669Z" level=info msg="Deleting PVC loop-fail-3-one" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.675Z" level=info msg="Deleting PVC loop-fail-3-two" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.682Z" level=info msg="Removing PVC \"kubernetes.io/pvc-protection\" finalizer" claimName=loop-fail-3-one namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.695Z" level=info msg="Removing PVC \"kubernetes.io/pvc-protection\" finalizer" claimName=loop-fail-3-two namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.709Z" level=info msg="Deleted 2/2 PVCs" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:17.726Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=2586 workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.726Z" level=info msg="Processing workflow" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.727Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.727Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=loop-fail-3-37876413 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.727Z" level=info msg="Creating pvc loop-fail-3-one" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.734Z" level=info msg="Creating pvc loop-fail-3-two" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.747Z" level=info msg="Step group node loop-fail-3-4073678796 successful" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.747Z" level=info msg="node loop-fail-3-4073678796 phase Running -> Succeeded" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.747Z" level=info msg="node loop-fail-3-4073678796 finished: 2023-05-23 09:43:27.747649033 +0000 UTC" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.747Z" level=info msg="StepGroup node loop-fail-3-4140642177 initialized Running" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.747Z" level=info msg="SG Outbound nodes of loop-fail-3-37876413 are [loop-fail-3-37876413]" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.748Z" level=info msg="Pod node loop-fail-3-3172455969 initialized Pending" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.767Z" level=info msg="Created pod: loop-fail-3[0].write-and-read-msg-from-pvc(0:one)[1].read-msg (loop-fail-3-read-msg-3172455969)" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.767Z" level=info msg="Workflow step group node loop-fail-3-4140642177 not yet completed" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.767Z" level=info msg="workflow active pod spec parallelism reached 1/1" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.767Z" level=info msg="Workflow step group node loop-fail-3-3565738732 not yet completed" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.767Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.767Z" level=info msg=reconcileAgentPod namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.831Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=2623 workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:27.838Z" level=info msg="cleaning up pod" action=labelPodCompleted key=default/loop-fail-3-write-msg-37876413/labelPodCompleted
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.754Z" level=info msg="Processing workflow" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.754Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.755Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=loop-fail-3-3172455969 old.message= old.phase=Pending old.progress=0/1 workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.756Z" level=info msg="SG Outbound nodes of loop-fail-3-37876413 are [loop-fail-3-37876413]" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.756Z" level=info msg="Step group node loop-fail-3-4140642177 successful" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.756Z" level=info msg="node loop-fail-3-4140642177 phase Running -> Succeeded" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.756Z" level=info msg="node loop-fail-3-4140642177 finished: 2023-05-23 09:43:37.756936656 +0000 UTC" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.756Z" level=info msg="Outbound nodes of loop-fail-3-3172455969 is [loop-fail-3-3172455969]" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.757Z" level=info msg="Outbound nodes of loop-fail-3-1631888154 is [loop-fail-3-3172455969]" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.757Z" level=info msg="node loop-fail-3-1631888154 phase Running -> Succeeded" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.757Z" level=info msg="node loop-fail-3-1631888154 finished: 2023-05-23 09:43:37.757031699 +0000 UTC" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.757Z" level=info msg="Checking daemoned children of loop-fail-3-1631888154" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.757Z" level=info msg="Steps node loop-fail-3-1336303057 initialized Running" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.757Z" level=info msg="StepGroup node loop-fail-3-1269459701 initialized Running" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.757Z" level=info msg="Pod node loop-fail-3-2820639080 initialized Pending" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.774Z" level=info msg="Created pod: loop-fail-3[0].write-and-read-msg-from-pvc(1:two)[0].write-msg (loop-fail-3-write-msg-2820639080)" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.774Z" level=info msg="Workflow step group node loop-fail-3-1269459701 not yet completed" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.774Z" level=info msg="Workflow step group node loop-fail-3-3565738732 not yet completed" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.774Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=loop-fail-3
workflow-controller-575d78d78f-kb4b5 workflow-controller time="2023-05-23T09:43:37.774Z" level=info msg=reconcileAgentPod namespace=default workflow=loop-fail-3
```

### Logs from in your workflow's wait container

```text
N/A
```
