### ISSUE TITLE
Self Reporting Progress not updating

### ISSUE THREAD

**Issue by McPonolith** [argoproj/argo-workflows#11125]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Attempting to utilise the Self Reporting Progress feature however the UI always reports 0%, until completed and then jumps to 100%.

Tried the following setups from fresh (Also used the killercoda deployement, same issue)
- https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml
- https://github.com/argoproj/argo-workflows/releases/download/v3.3.0/install.yaml
- https://github.com/argoproj/argo-workflows/releases/download/v3.4.7/install.yaml

They all exhibit the same issue.

Tried example workflow from https://github.com/argoproj/argo-workflows/blob/master/docs/progress.md#self-reporting-progress

Also modified it to:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: progress-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: progress
            template: progress
    - name: progress
      metadata:
        annotations:
          workflows.argoproj.io/progress: 0/100
      container:
        image: alpine:3.14
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            env
            echo "The progress file:$ARGO_PROGRESS_FILE"
            for i in `seq 1 10`; do sleep 10; echo "$(($i*10))"'/100' > $ARGO_PROGRESS_FILE; cat $ARGO_PROGRESS_FILE; done
            echo "Finished"
            cat $ARGO_PROGRESS_FILE
            echo "End"

```

The progress is correctly being outputted to the logs, but it is not updating in the sidebar/ui.

Verified that the following settings where set correctly (via `env`)
```
ARGO_PROGRESS_FILE_TICK_DURATION=3s
ARGO_PROGRESS_FILE=/var/run/argo/progress
```

And that the file was writeable by `cat` in the script.

Not sure what else to do, appears to be a bug, but a bug thats existed from the start of the feature (i.e. 3.3.0). If its not a bug the documentation is misleading as the example does not work.

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: progress-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: progress
            template: progress
    - name: progress
      metadata:
        annotations:
          workflows.argoproj.io/progress: 0/100
      container:
        image: alpine:3.14
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            for i in `seq 1 10`; do sleep 10; echo "$(($i*10))"'/100' > $ARGO_PROGRESS_FILE; done
```

### Logs from the workflow controller

```text
time="2023-05-24T15:47:35.269Z" level=info msg="Processing workflow" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:35.295Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:35.300Z" level=info msg="DAG node progress-zqgws initialized Running" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:35.309Z" level=info msg="All of node progress-zqgws.progress dependencies [] completed" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:35.312Z" level=info msg="Pod node progress-zqgws-251981532 initialized Pending" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:35.344Z" level=info msg="Created pod: progress-zqgws.progress (progress-zqgws-progress-251981532)" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:35.345Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:35.345Z" level=info msg=reconcileAgentPod namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:35.382Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=841 workflow=progress-zqgws
time="2023-05-24T15:47:45.253Z" level=info msg="Processing workflow" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:45.264Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=progress-zqgws
time="2023-05-24T15:47:45.270Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:45.271Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/100 nodeID=progress-zqgws-251981532 old.message= old.phase=Pending old.progress=0/1 workflow=progress-zqgws
time="2023-05-24T15:47:45.280Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:45.280Z" level=info msg=reconcileAgentPod namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:45.346Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=864 workflow=progress-zqgws
time="2023-05-24T15:47:55.322Z" level=info msg="Processing workflow" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:55.324Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=progress-zqgws
time="2023-05-24T15:47:55.324Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:55.324Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/100 nodeID=progress-zqgws-251981532 old.message=PodInitializing old.phase=Pending old.progress=0/100 workflow=progress-zqgws
time="2023-05-24T15:47:55.326Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:55.326Z" level=info msg=reconcileAgentPod namespace=argo workflow=progress-zqgws
time="2023-05-24T15:47:55.343Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=888 workflow=progress-zqgws
time="2023-05-24T15:48:58.208Z" level=info msg="Processing workflow" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:48:58.209Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=progress-zqgws
time="2023-05-24T15:48:58.210Z" level=info msg="task-result changed" namespace=argo nodeID=progress-zqgws-251981532 workflow=progress-zqgws
time="2023-05-24T15:48:58.211Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:48:58.212Z" level=info msg="node changed" namespace=argo new.message= new.phase=Running new.progress=0/100 nodeID=progress-zqgws-251981532 old.message= old.phase=Running old.progress=50/100 workflow=progress-zqgws
time="2023-05-24T15:48:58.215Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:48:58.215Z" level=info msg=reconcileAgentPod namespace=argo workflow=progress-zqgws
time="2023-05-24T15:48:58.234Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=888 workflow=progress-zqgws
time="2023-05-24T15:49:40.125Z" level=info msg="Processing workflow" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:49:40.126Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=progress-zqgws
time="2023-05-24T15:49:40.126Z" level=info msg="task-result changed" namespace=argo nodeID=progress-zqgws-251981532 workflow=progress-zqgws
time="2023-05-24T15:49:40.126Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:49:40.128Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/100 nodeID=progress-zqgws-251981532 old.message= old.phase=Running old.progress=50/100 workflow=progress-zqgws
time="2023-05-24T15:49:40.129Z" level=info msg="Outbound nodes of progress-zqgws set to [progress-zqgws-251981532]" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:49:40.129Z" level=info msg="node progress-zqgws phase Running -> Succeeded" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:49:40.129Z" level=info msg="node progress-zqgws finished: 2023-05-24 15:49:40.1298657 +0000 UTC" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:49:40.130Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:49:40.130Z" level=info msg=reconcileAgentPod namespace=argo workflow=progress-zqgws
time="2023-05-24T15:49:40.130Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:49:40.130Z" level=info msg="Marking workflow completed" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:49:40.130Z" level=info msg="Marking workflow as pending archiving" namespace=argo workflow=progress-zqgws
time="2023-05-24T15:49:40.136Z" level=info msg="cleaning up pod" action=deletePod key=argo/progress-zqgws-1340600742-agent/deletePod
time="2023-05-24T15:49:40.148Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=1044 workflow=progress-zqgws
time="2023-05-24T15:49:40.171Z" level=info msg="archiving workflow" namespace=argo uid=78521755-c678-4861-a4c5-bf8771d238c1 workflow=progress-zqgws
time="2023-05-24T15:49:40.178Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/progress-zqgws-progress-251981532/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
time="2023-05-24T15:49:30.477Z" level=info msg="No output artifacts"
time="2023-05-24T15:49:30.478Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: progress-zqgws/progress-zqgws-progress-251981532/main.log"
time="2023-05-24T15:49:30.478Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2023-05-24T15:49:30.478Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=progress-zqgws/progress-zqgws-progress-251981532/main.log path=/tmp/argo/outputs/logs/main.log
time="2023-05-24T15:49:30.535Z" level=info msg="Save artifact" artifactName=main-logs duration=56.876154ms error="<nil>" key=progress-zqgws/progress-zqgws-progress-251981532/main.log
time="2023-05-24T15:49:30.535Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2023-05-24T15:49:30.535Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2023-05-24T15:49:30.559Z" level=info msg="Alloc=9814 TotalAlloc=16631 Sys=28029 NumGC=5 Goroutines=10"
time="2023-05-24T15:49:30.560Z" level=info msg="Deadline monitor stopped"
time="2023-05-24T15:49:30.560Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
```

**Comment by McPonolith** [comment]
It appears this issue was caused by a slower than expected updated time (60s instead of 3s) and the annotation in the sample workflow.

For example run the following workflow
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: progress-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: progress
            template: progress
    - name: progress
      metadata:
          annotations:
            workflows.argoproj.io/progress: 0/100 # Remove this on second run
      container:
        image: alpine:3.14
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            for i in `seq 1 66`; do sleep 10; echo "$i"'/66' > $ARGO_PROGRESS_FILE; done
```

It seems when the workflow-manager goes to update the progress it updates the value of the annotation every-time instead of just at the start. This results in the progress always showing as 0/100.

Now remove the annotation. it should work fine (if you wait long enough)

If you inspect the wait container logs you will see the progress updating, but it wont update in the UI. It seems to take around a minute to update, not the expected 3s https://argoproj.github.io/argo-workflows/progress/#self-reporting-progress

However this may just be a mis-communication in that the executor updates the pod information every 3s, it may take longer for the controller to update the UI.

There is still however the issue of the annotation overriding the self-reported value everytime. This is very easily reproducible. If you need any further assistance, please let me know. Im also new to Argo Workflows and Kubernetes so my terminology might be slightly off.

Cheers,
Emmet

**Comment by StoyanTc** [comment]
Are there any chances to see this bug fixed in the near future?
We have long running workflows in our company and since the ARGO provides just a very limited real-time metrics this is the only way to follow the progress of our pipelines.

**Comment by ClemDoum** [comment]
Hi there. Same for me I run both short and long-lived tasks. Having the ability to self-report progress during long task is critical. 
Is there any update ?

**Comment by ClemDoum** [comment]
OK my mistake, I noticed the progress at the end of my self reporting workflow was correct. 
In my case the issue was that I needed enable self reporting with the `ARGO_PROGRESS_PATCH_TICK_DURATION` env variable:
```yml
- name: ARGO_PROGRESS_FILE_TICK_DURATION
  value: 1s
- name: ARGO_PROGRESS_PATCH_TICK_DURATION
  value: 1s
```
