### ISSUE TITLE
workflow.parameters.json does not escape double quotes

### ISSUE THREAD

**Issue by captaincoordinates** [argoproj/argo-workflows#11131]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

The JSON provided by `workflow.parameters.json`, as described [here](https://argoproj.github.io/argo-workflows/variables/#global), does not escape quotes in parameter values and can produce invalid JSON.

I expected double quotes in workflow input parameters to be escaped so that `workflow.parameters.json` always provides a valid JSON string.

The provided workflow reproduces this error. If the `"` is removed from `argument-1`'s value the error goes away.

### Version

3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
kind: Workflow
metadata:
  generateName: json-test-
spec:
  entrypoint: params-dumper
  arguments:
    parameters:
      - name: argument-1
        value: with " quote
  templates:
    - name: params-dumper
      container:
        image: python
        command:
          - python
          - -c
        args:
          - |
            from json import loads
            from json.decoder import JSONDecodeError
            try:
              loads("""{{workflow.parameters.json}}""")
            except JSONDecodeError as e:
              print(f"not ok: {e}")
              raise e
            else:
              print("ok")
```

### Logs from the workflow controller

```text
time="2023-05-25T19:00:05.217Z" level=info msg="Processing workflow" namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:05.221Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:05.221Z" level=info msg="Pod node json-test-v265d initialized Pending" namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:05.227Z" level=info msg="Created pod: json-test-v265d (json-test-v265d)" namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:05.227Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:05.227Z" level=info msg=reconcileAgentPod namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:05.231Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1819 workflow=json-test-v265d
time="2023-05-25T19:00:15.228Z" level=info msg="Processing workflow" namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:15.228Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=json-test-v265d
time="2023-05-25T19:00:15.228Z" level=info msg="Pod failed: Error (exit code 1)" displayName=json-test-v265d namespace=argo pod=json-test-v265d templateName=params-dumper workflow=json-test-v265d
time="2023-05-25T19:00:15.229Z" level=info msg="node changed" namespace=argo new.message="Error (exit code 1)" new.phase=Failed new.progress=0/1 nodeID=json-test-v265d old.message= old.phase=Pending old.progress=0/1 workflow=json-test-v265d
time="2023-05-25T19:00:15.229Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:15.229Z" level=info msg=reconcileAgentPod namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:15.229Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:15.229Z" level=info msg="Updated message  -> Error (exit code 1)" namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:15.229Z" level=info msg="Marking workflow completed" namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:15.229Z" level=info msg="Checking daemoned children of " namespace=argo workflow=json-test-v265d
time="2023-05-25T19:00:15.234Z" level=info msg="cleaning up pod" action=deletePod key=argo/json-test-v265d-1340600742-agent/deletePod
time="2023-05-25T19:00:15.235Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=1848 workflow=json-test-v265d
time="2023-05-25T19:00:15.244Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/json-test-v265d/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
time="2023-05-25T19:00:06.916Z" level=info msg="Starting Workflow Executor" version=v3.4.7
time="2023-05-25T19:00:06.918Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-05-25T19:00:06.918Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo podName=json-test-v265d template="{\"name\":\"params-dumper\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"python\",\"command\":[\"python\",\"-c\"],\"args\":[\"from json import loads\\nfrom json.decoder import JSONDecodeError\\ntry:\\n  loads(\\\"\\\"\\\"[{\\\"name\\\":\\\"argument-1\\\",\\\"value\\\":\\\"with \\\\\\\" quote\\\"}]\\\"\\\"\\\")\\nexcept JSONDecodeError as e:\\n  print(f\\\"not ok: {e}\\\")\\n  raise e\\nelse:\\n  print(\\\"ok\\\")\\n\"],\"resources\":{}}}" version="&Version{Version:v3.4.7,BuildDate:2023-04-11T16:19:29Z,GitCommit:f2292647c5a6be2f888447a1fef71445cc05b8fd,GitTag:v3.4.7,GitTreeState:clean,GoVersion:go1.19.8,Compiler:gc,Platform:linux/amd64,}"
time="2023-05-25T19:00:06.919Z" level=info msg="Starting deadline monitor"
time="2023-05-25T19:00:09.920Z" level=info msg="Main container completed" error="<nil>"
time="2023-05-25T19:00:09.920Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-05-25T19:00:09.920Z" level=info msg="No output parameters"
time="2023-05-25T19:00:09.920Z" level=info msg="No output artifacts"
time="2023-05-25T19:00:09.920Z" level=info msg="Alloc=9943 TotalAlloc=14857 Sys=29549 NumGC=4 Goroutines=7"
time="2023-05-25T19:00:09.920Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
```

**Comment by vancanhuit** [comment]
Hello, I want to make a first contribution to Argo Workflows. Can I work on this issue?

**Comment by Transmitt0r** [comment]
I took a look at the code 

The Parameter definition is here https://github.com/argoproj/argo-workflows/blob/f3c948a047e01d99a150e82b267b000db850bcbf/pkg/apis/workflow/v1alpha1/workflow_types.go#L853-L876

And the Arguments definition here https://github.com/argoproj/argo-workflows/blob/f3c948a047e01d99a150e82b267b000db850bcbf/pkg/apis/workflow/v1alpha1/workflow_types.go#L1689C1-L1699

And the parameters are marshaled here https://github.com/argoproj/argo-workflows/blob/f3c948a047e01d99a150e82b267b000db850bcbf/workflow/controller/operator.go#L605

I suspect that we will need to implement the Marshaler interface for Parameters or Arguments to make sure that the quotes are correctly escaped

**Comment by Cool-fire** [comment]
But Doesn't `json.Marshal` already escape the quotes while marshaling, I just tested it out on sample code and looks like it does omit quotes 

https://go.dev/play/p/NhGQvzdWXYy

**Comment by Transmitt0r** [comment]
@Cool-fire just checked the docs and you're right it should escape quotes

**Comment by Transmitt0r** [comment]
I tried to simplify the setup a bit and used the following workflow:
```yaml
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  generateName: json-test-
spec:
  entrypoint: params-dumper
  arguments:
    parameters:
      - name: argument-1
        value: with " quote
  templates:
    - name: params-dumper
      container:
        image: alpine
        command:
          - echo
        args:
          - "{{ workflow.parameters.json }}"
```
And the output seems correct:
 log from main container:
 ```log
[{"name":"argument-1","value":"with \" quote"}]
time="2023-06-05T10:26:41 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
```

wait also looks super similar to yours (if you take a closer look at line 4 with the six backslashes before the quote):
```log
time="2023-06-05T10:26:18 UTC" level=info msg="Starting Workflow Executor" version=v3.4.8
time="2023-06-05T10:26:18 UTC" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-06-05T10:26:18 UTC" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo podName=json-test-frzdr templa
te="{\"name\":\"params-dumper\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine\",\"command\":[\"echo\"],\"args\":[\"[{\\\"name\\\":\\\"
argument-1\\\",\\\"value\\\":\\\"with \\\\\\\" quote\\\"}]\"],\"resources\":{}}}" version="&Version{Version:v3.4.8,BuildDate:2023-05-25T22:19:57Z,GitCommit:9e27baee4b3be78bb662ffa5e
3a06f8a6c28fb53,GitTag:v3.4.8,GitTreeState:clean,GoVersion:go1.20.4,Compiler:gc,Platform:linux/amd64,}"
time="2023-06-05T10:26:18 UTC" level=info msg="Starting deadline monitor"
time="2023-06-05T10:26:42 UTC" level=info msg="Main container completed" error="<nil>"
time="2023-06-05T10:26:42 UTC" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-06-05T10:26:42 UTC" level=info msg="No output parameters"
time="2023-06-05T10:26:42 UTC" level=info msg="No output artifacts"
time="2023-06-05T10:26:42 UTC" level=info msg="Alloc=8934 TotalAlloc=15913 Sys=28541 NumGC=5 Goroutines=7"
time="2023-06-05T10:26:42 UTC" level=info msg="Deadline monitor stopped"
```
What's going on here seems to be some weird interaction when placing `{{ workflow.parameters.json }}` in `args` when using `echo` either as `cmd` or also inside the `args`. When you run the following example, when running `echo` from cmd and putting the json in the args, the string is displayed and escaped correctly, but when you run `sh -c`in cmd and have an arg that then calls echo, all the quotes are gone except the escaped one.
```yaml
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  generateName: json-test-
spec:
  entrypoint: params-dumper-working
  arguments:
    parameters:
      - name: argument-1
        value: with " quote
  templates:
    - name: params-dumper-not-working
      container:
        image: python:alpine
        command: ["sh", "-c"]
        args:
          - |
            echo "{{ workflow.parameters.json }}"
    - name: params-dumper-working
      container:
        image: python:alpine
        command: ["echo"]
        args:
          - "{{ workflow.parameters.json }}"
    - name: params-dumper-also-working
      container:
        image: python:alpine
        command: ["echo"]
        args:
          - |
            "{{ workflow.parameters.json }}"
```

I figure out one way to circumvent this:
```yaml
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  generateName: json-test-
spec:
  entrypoint: params-dumper-python
  arguments:
    parameters:
      - name: argument-1
        value: with " quote
  templates:
    - name: params-dumper-python
      container:
        image: python:alpine
        command: ["python", "/config/load_workflow.py"]
        args:
          - "{{ workflow.parameters.json }}"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: python-script
          items:
          - key: "load_workflow.py"
            path: "load_workflow.py"

---
#ConfigMap to hold python script
kind: ConfigMap
apiVersion: v1
metadata:
  name: python-script
data:
  load_workflow.py: |
    import json
    import sys
    s = sys.argv[1]
    print(s)
    d = json.loads(s)
    print(d)
```

**Comment by agilgur5** [comment]
I don't remember the exact semantics of the quoting, but I used `sprig.trim` in an expression in the past to get JSON to parse properly. Had to trial-and-error a lot till it worked

**Comment by spencercjh** [comment]
The problem of the person who raised the issue is still not fixed. It can still be easily reproduced.

![image](https://github.com/argoproj/argo-workflows/assets/29922079/095795ac-a908-492c-9d2c-9d86f4ba22bb)

```yaml
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  generateName: json-test-
spec:
  entrypoint: params-dumper
  arguments:
    parameters:
      - name: argument-1
        value: with " quote
  templates:
    - name: params-dumper
      container:
        image: python
        command:
          - python
          - -c
        args:
          - |
            from json import loads
            from json.decoder import JSONDecodeError
            s = {{workflow.parameters.json}}
            print("""json: {{workflow.parameters.json}}""")
            try:
              loads("""{{workflow.parameters.json}}""")
            except JSONDecodeError as e:
              print(f"not ok: {e}")
              raise e
            else:
              print("ok")
```


You can see the main log:

`json: [{"name":"argument-1","value":"with " quote"}]`

The `value` in `workflow.parameters.json` is illegal without escaping double quotes.

**Comment by spencercjh** [comment]
> The problem of the person who raised the issue is still not fixed. It can still be easily reproduced.
> 
> ![image](https://user-images.githubusercontent.com/29922079/260625754-095795ac-a908-492c-9d2c-9d86f4ba22bb.png)
> 
> ```yaml
> kind: Workflow
> apiVersion: argoproj.io/v1alpha1
> metadata:
>   generateName: json-test-
> spec:
>   entrypoint: params-dumper
>   arguments:
>     parameters:
>       - name: argument-1
>         value: with " quote
>   templates:
>     - name: params-dumper
>       container:
>         image: python
>         command:
>           - python
>           - -c
>         args:
>           - |
>             from json import loads
>             from json.decoder import JSONDecodeError
>             s = {{workflow.parameters.json}}
>             print("""json: {{workflow.parameters.json}}""")
>             try:
>               loads("""{{workflow.parameters.json}}""")
>             except JSONDecodeError as e:
>               print(f"not ok: {e}")
>               raise e
>             else:
>               print("ok")
> ```
> 
> You can see the main log:
> 
> `json: [{"name":"argument-1","value":"with " quote"}]`
> 
> The `value` in `workflow.parameters.json` is illegal without escaping double quotes.
> 
> I will try to fix it. 🚀

Sorry I didn't read @Transmitt0r's reply carefully, he/she has clearly explained why the problem arises and how to avoid it.

I check the main container args of failed workflow, it has been well-escaped. So I don't think it's a problem with Argo Workflows, it's a problem with technique when writing python steps.

![image](https://github.com/argoproj/argo-workflows/assets/29922079/de5e0db5-ce38-4368-a46e-4ce3be8b23ff)


I wrote [a couple of examples](https://github.com/spencercjh/argo-workflows/commit/128e3e90d81dc43bf8348c815a3fb3a63eb8b491) to illustrate the situation.

I am not extremely family with Python and shell. I hope someone to give a conclusion for the issue.

**Comment by caelan-io** [comment]
Thank you @Transmitt0r and @spencercjh for providing very detailed assessments of this issue and its root cause! 🌟🌟 

For future users who find this issue, please refer to their comments that explain in detail how to resolve this:
- [comment 1](https://github.com/argoproj/argo-workflows/issues/11131#issuecomment-1576613243) by @Transmitt0r 
- [comment 2](https://github.com/argoproj/argo-workflows/issues/11131#issuecomment-1678847767) by @spencercjh 

I am closing as resolved.

**Comment by captaincoordinates** [comment]
Sorry but I believe something is still broken here. The following Workflow has no Python and yet still fails due to improper JSON encoding when `workflow.parameters.json` is included in `args`, similar to the issue @Transmitt0r described [here](https://github.com/argoproj/argo-workflows/issues/11131#issuecomment-1576613243) but not quite the same, as `echo` is not present.

> What's going on here seems to be some weird interaction when placing {{ workflow.parameters.json }} in args when using echo either as cmd or also inside the args

@Transmitt0r's workaround does work, even when the argument has an escaped quote as shown below, but it's not ideal as it leaves a persistent ConfigMap in k8s after the Workflow and its other resources have been destroyed. That means I need to maintain a uniquely-named ConfigMap for each template that needs access to `workflow.parameters.json` in each Workflow, and given my use-case that could quickly grow to thousands of ConfigMaps.

Can we please re-open this issue to determine why the behaviour of `{{workflow.parameters.json}}` changes depending on where it is referenced?

```YAML
kind: Workflow
metadata:
  generateName: json-test-
spec:
  entrypoint: params-dumper
  arguments:
    parameters:
      - name: argument-1
        value: with escaped \" quote
  templates:
    - name: params-dumper
      outputs:
        artifacts:
          - name: dumped-json
            path: /tmp/params.json
            archive:
              none:
      container:
        image: stedolan/jq
        command:
          - bash
          - -c
        args:
          - |
            set -x
            cat << EOF > /tmp/params.json
            {{workflow.parameters.json}}
            EOF
            jq . /tmp/params.json
```

**Comment by captaincoordinates** [comment]
Sorry, again, I may have to retract my latest comment - further testing suggests that `workflow.parameters.json` is being passed as `with escaped \\\" quote`, which _is_ what I would expect in this scenario. I believe one of those `\` characters is being swallowed by the bash interpreter. If I ever get out of escape-character-hell I'll see if something similar could explain how that referenced is handled in my earlier Workflow.

**Comment by captaincoordinates** [comment]
For future reference this is how I've worked around the various escape character issues without using the `ConfigMap` approach. This approach assumes that the text "EOF" does not occur anywhere in the workflow parameter JSON or in the Python script, so in my actual use-case I'll be replacing "EOF" with something extremely unlikely to occur in either of those places such as a UUID.

```YAML
kind: Workflow
metadata:
  generateName: json-test-
spec:
  entrypoint: params-dumper
  arguments:
    parameters:
      - name: argument-1
        value: with \" quote
  templates:
    - name: params-dumper
      container:
        image: python
        command:
          - bash
          - -c
        args:
          - |
            cat << EOF > /tmp/params.json.b64
            {{=sprig.b64enc(workflow.parameters.json)}}
            EOF
            cat << EOF > /tmp/script.py
            from base64 import b64decode
            from json import loads
            from json.decoder import JSONDecodeError
            with open("/tmp/params.json.b64", "rb") as f:
              parameters_json = b64decode(f.read()).decode()
            try:
              parameters = loads(parameters_json)
            except JSONDecodeError as e:
              print(f"JSON not ok: {e}")
              raise e
            except Exception as e:
              print(f"Something not ok: {e}")
              raise e
            else:
              print(parameters)
            EOF
            python /tmp/script.py
```
