### ISSUE TITLE
securityContext default override not as expected

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#11130]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

https://github.com/argoproj/argo-workflows/discussions/11127

I have the below controller configmap on v3.4.7.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce
  mainContainer: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 8737
      runAsGroup: 8737
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  executor: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 8737
      runAsGroup: 8737
      privileged: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  workflowDefaults: |
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 8737
        runAsGroup: 8737
```

I am trying to remove `securityContext.capabilities.drop` from the `main` container in a containerset.

I've tried setting `capabilities` to `null` or `{}` on my `main` container.

I've tried setting `drop` to `null` or `[]` on my `main` container.

e.g.

```yaml
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              capabilities: null
```

```yaml
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              capabilities: {}
```

But when I check the yaml of my pod, the container's securityContext capabilities is still drop all.

Referencing @alexec's blog post

* https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce

And helm's deleting a default key

* https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key

@terrytangyuan 

> Seems like a bug. The logic here needs to be revisited: https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/workflowpod.go#L607-L629

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by rwong2888** [comment]
I also tried @crenshaw-dev 's suggestion of `podSpecPatch` which did not work

```
containerSet:
        podSpecPatch: '{"containers":[{"name":"main", "securityContext":{"capabilities":{}}}]}'
        containers:
```

```
      containerSet:
        podSpecPatch: '{"containers":[{"name":"main", "securityContext":{"capabilities":null}}]}'
        containers:
```

Referencing

* https://github.com/argoproj/argo-workflows/blob/master/examples/pod-spec-patch.yaml#L13

**Comment by sarabala1979** [comment]
@rohankmr414  it looks like a JSON merge issue.  Please take a look at operator.go and workflowPod.go. These two places Json will merge to construct the securitycontext.

**Comment by mslapek** [comment]
The merge logic is in `createWorkflowPod` from `workflowpod.go`:

https://github.com/argoproj/argo-workflows/blob/0f1b4365ec1644942abd7c7cb87f427d7f6e30a9/workflow/controller/workflowpod.go#L111-L129

However, I'm afraid we cannot have the expected result with `mainCtrs []apiv1.Container` as an input – because we cannot differ between two kinds of `null`:

1. Set by user explicitly in JSON – so we want to **delete** the key.
2. Omitted by user in JSON – so we want to **use** a default value.

To solve the issue, we would need to take untyped JSON as an input `mainCtrs []map[string]any` - so `json.Unmarshal` would decode the intent properly.

**Question** Should we make big-change of `mainCtrs` to this new type? (looks like a big churn ☹️)

**Comment by rwong2888** [comment]
not stale

**Comment by terrytangyuan** [comment]
@jswxstw Are you interested in working on this?

**Comment by jswxstw** [comment]
> @jswxstw Are you interested in working on this?

I have an idea, why not use strategic merge patch instead.

**Comment by jswxstw** [comment]
> The merge logic is in `createWorkflowPod` from `workflowpod.go`:
> 
> https://github.com/argoproj/argo-workflows/blob/0f1b4365ec1644942abd7c7cb87f427d7f6e30a9/workflow/controller/workflowpod.go#L111-L129
> 
> However, I'm afraid we cannot have the expected result with `mainCtrs []apiv1.Container` as an input – because we cannot differ between two kinds of `null`:
> 
> 1. Set by user explicitly in JSON – so we want to **delete** the key.
> 2. Omitted by user in JSON – so we want to **use** a default value.
> 
> To solve the issue, we would need to take untyped JSON as an input `mainCtrs []map[string]any` - so `json.Unmarshal` would decode the intent properly.
> 
> **Question** Should we make big-change of `mainCtrs` to this new type? (looks like a big churn ☹️)

@terrytangyuan I‘m thinking about add a `containerSpecPatch` into Template like `podSpecPatch`, so that there is no need to make changes to mainCtrs. Is this acceptable?

**Comment by terrytangyuan** [comment]
That sounds confusing though. Let's try reusing the current fields if possible

**Comment by terrytangyuan** [comment]
@jswxstw Please do not delete comments unless necessary since others will lose the context.

**Comment by jswxstw** [comment]
> That sounds confusing though. Let's try reusing the current fields if possible

ok, `podSpecPatch` seems like it can be used to solve this problem, I will try to check out why it did not work.

**Comment by jswxstw** [comment]
> '{"containers":[{"name":"main", "securityContext":{"capabilities":{}}}]}'

The correct usage of `podSpecPatch`: 
```yaml
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    podSpecPatch: '{"containers":[{"name":"main", "securityContext":{"capabilities":null}}]}'
    containerSet:
```
However, there is still a bug here: @terrytangyuan 
https://github.com/argoproj/argo-workflows/blob/29cf90eda5c2e8902708ca2cc1cc48417bc45b55/workflow/controller/workflowpod.go#L350-L372

before PodSpecPatchMerge: `'{"containers":[{"name":"main", "securityContext":{"capabilities":null}}]}'`
after PodSpecPatchMerge: `'{"containers":[{"name":"main", "securityContext":{"capabilities":{}}}]}'`
