### ISSUE TITLE
Label workflows with updator

### ISSUE THREAD

**Issue by toyamagu-2021** [argoproj/argo-workflows#11148]
# Summary

- I'd like to see an updator label we can see who updated a workflow.
  - Ref(creator): https://github.com/argoproj/argo-workflows/pull/3440
- the label will be like this: `workflow.WorkflowFullName + "/updator.resumed": "admin"`

# Use Cases

- To audit who suspended/stopped/resumed/etc a workflow
- Pseudo-approval process for [Intermediate Parameter](https://argoproj.github.io/argo-workflows/intermediate-inputs/), with condition `creator` != `updator`.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tooptoop4** [comment]
@toyamagu-2021 is this done?

**Comment by toyamagu-2021** [comment]
Not done. #11763 implements insert some information in Node, but not label.

**Comment by Joibel** [comment]
This has been implemented as the "actor" labels rather than "updator". Since v3.7.0 (#14104, which closed the near-identical #14102) the server applies:

```yaml
workflows.argoproj.io/actor: admin
workflows.argoproj.io/actor-email: admin.at.your.org
workflows.argoproj.io/actor-preferred-username: admin-preferred-username
workflows.argoproj.io/action: Resume
```

on suspend, resume, stop, terminate and retry of a Workflow, and on update of WorkflowTemplate, ClusterWorkflowTemplate and CronWorkflow. See `workflow/creator/creator.go` (`LabelActor`) and `workflow/common/common.go` on main.

This covers both use cases here: auditing who acted on a workflow, and gating on `creator` != acting user. The one difference from the original proposal is that a single actor/action pair is stored (latest wins) rather than a label per action such as `updator.resumed`.

Closing as implemented. Note the actor labels are still undocumented - docs/workflow-creator.md only covers the creator labels - so a docs PR would be a welcome follow-up.
