### ISSUE TITLE
Artifacts cannot be stored in object-lock enabled S3 buckets

### ISSUE THREAD

**Issue by akloss-cibo** [argoproj/argo-workflows#11182]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Artifacts cannot be stored into AWS S3 buckets with Object Lock enabled.

~I believe this may be fixed by https://github.com/minio/minio/pull/15433~

### Version

3.4.7 and latest (and probably others)

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    iam.amazonaws.com/role: AWSIAMROLENAME
    workflows.argoproj.io/pod-name-format: v1
  name: wf-artifact-test
spec:
  entrypoint: wf-artifact-test
  templates:
  - name: wf-artifact-test
    metadata:
      annotations:
        iam.amazonaws.com/role: '{{workflow.annotations.iam.amazonaws.com/role}}'
    podSpecPatch: |
      containers:
      - name: wait
        image: argoproj/argoexec:latest
    container:
      name: wf-artifact-test
      image: busybox
      command:
      - /bin/sh
      - -c
      - |
        echo '{}' > /out/test.json
        sleep 1
        cat /out/test.json
      resources:
        requests:
          cpu: 100m
          memory: &memory 300Mi
        limits:
          memory: *memory
      volumeMounts:
      - name: out
        mountPath: /out
    volumes:
    - name: out
      emptyDir: {}
    outputs:
      artifacts:
      - archive:
          none: {}
        name: test-artifact
        path: /out/test.json
        s3:
          bucket: object-lock-enabled-bucket
          endpoint: s3.amazonaws.com
          key: test/test-artifact.json
```

### Logs from the workflow controller

```text
(none)
```

### Logs from in your workflow's wait container

```text
time="2023-06-05T20:02:44.014Z" level=warning msg="Non-transient error: Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters"
time="2023-06-05T20:02:44.014Z" level=error msg="executor error: failed to put file: Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters"
time="2023-06-05T20:02:44.114Z" level=fatal msg="failed to put file: Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters"
```
```
