### ISSUE TITLE
Aggregated outputs of failed parallel tasks

### ISSUE THREAD

**Issue by vancanhuit** [argoproj/argo-workflows#11221]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I have a use case where I need to collect all output parameters (or artifacts) of all parallel tasks but it seems that we can't collect outputs of failed tasks:

https://github.com/argoproj/argo-workflows/blob/6e97c7d6babd9115f9872b06cdfa02bc5950fb74/workflow/controller/operator.go#LL2924C8-L2924C8

So why don't we include the output parameters of failed nodes in aggregated outputs?

![Screenshot from 2023-06-15 23-04-34](https://github.com/argoproj/argo-workflows/assets/18382438/1971b22b-00ec-4b85-b7f2-02b0d7374d55)

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
spec:
  entrypoint: main

  templates:
    - name: main
      dag:
        tasks:
          - name: build
            template: build
            arguments:
              parameters:
                - name: num
                  value: "{{item}}"
            withItems:
              - 1
              - 2
          - name: collect
            template: collect
            depends: "build.AnySucceeded || build.AllFailed"
            arguments:
              parameters:
                - name: aggregated-outputs
                  value: "{{tasks.build.outputs.parameters.pod-name}}"
    - name: build
      inputs:
        parameters:
          - name: num
      outputs:
        parameters:
          - name: pod-name
            value: "{{pod.name}}"
      container:
        image: debian:11.7
        command:
          - sh
          - -c
        args:
          - |
            n={{inputs.parameters.num}}
            exit $(($n % 2))

    - name: collect
      inputs:
        parameters:
          - name: aggregated-outputs
      container:
        image: debian:11.7
        command:
          - sh
          - -c
        args:
          - |
            echo "{{inputs.parameters.aggregated-outputs}}"
```

### Logs from the workflow controller

```text
time="2023-06-15T15:57:30.735Z" level=info msg="Processing workflow" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.738Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.738Z" level=info msg="DAG node test-nwgqv initialized Running" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.738Z" level=info msg="TaskGroup node test-nwgqv-3361402689 initialized Running (message: )" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.738Z" level=info msg="All of node test-nwgqv.build(0:1) dependencies [] completed" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.738Z" level=info msg="Pod node test-nwgqv-1803670843 initialized Pending" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.747Z" level=info msg="Created pod: test-nwgqv.build(0:1) (test-nwgqv-build-1803670843)" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.747Z" level=info msg="All of node test-nwgqv.build(1:2) dependencies [] completed" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.747Z" level=info msg="Pod node test-nwgqv-1286867769 initialized Pending" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.756Z" level=info msg="Created pod: test-nwgqv.build(1:2) (test-nwgqv-build-1286867769)" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.756Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.756Z" level=info msg=reconcileAgentPod namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:30.762Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=6898 workflow=test-nwgqv
time="2023-06-15T15:57:40.737Z" level=info msg="Processing workflow" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:40.737Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=2 workflow=test-nwgqv
time="2023-06-15T15:57:40.737Z" level=info msg="task-result changed" namespace=argo nodeID=test-nwgqv-1286867769 workflow=test-nwgqv
time="2023-06-15T15:57:40.737Z" level=info msg="task-result changed" namespace=argo nodeID=test-nwgqv-1803670843 workflow=test-nwgqv
time="2023-06-15T15:57:40.737Z" level=info msg="Pod failed: Error (exit code 1)" displayName="build(0:1)" namespace=argo pod=test-nwgqv-build-1803670843 templateName=build workflow=test-nwgqv
time="2023-06-15T15:57:40.738Z" level=info msg="node changed" namespace=argo new.message="Error (exit code 1)" new.phase=Failed new.progress=0/1 nodeID=test-nwgqv-1803670843 old.message= old.phase=Pending old.progress=0/1 workflow=test-nwgqv
time="2023-06-15T15:57:40.738Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=test-nwgqv-1286867769 old.message= old.phase=Pending old.progress=0/1 workflow=test-nwgqv
time="2023-06-15T15:57:40.740Z" level=info msg="node test-nwgqv-3361402689 phase Running -> Failed" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:40.740Z" level=info msg="node test-nwgqv-3361402689 finished: 2023-06-15 15:57:40.740299031 +0000 UTC" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:40.740Z" level=info msg="All of node test-nwgqv.collect dependencies [build] completed" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:40.741Z" level=info msg="Pod node test-nwgqv-3553655367 initialized Pending" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:40.763Z" level=info msg="Created pod: test-nwgqv.collect (test-nwgqv-collect-3553655367)" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:40.763Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:40.763Z" level=info msg=reconcileAgentPod namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:40.773Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=6955 workflow=test-nwgqv
time="2023-06-15T15:57:40.779Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/test-nwgqv-build-1803670843/labelPodCompleted
time="2023-06-15T15:57:40.779Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/test-nwgqv-build-1286867769/labelPodCompleted
time="2023-06-15T15:57:50.766Z" level=info msg="Processing workflow" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.767Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=3 workflow=test-nwgqv
time="2023-06-15T15:57:50.767Z" level=info msg="task-result changed" namespace=argo nodeID=test-nwgqv-3553655367 workflow=test-nwgqv
time="2023-06-15T15:57:50.767Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=test-nwgqv-3553655367 old.message= old.phase=Pending old.progress=0/1 workflow=test-nwgqv
time="2023-06-15T15:57:50.769Z" level=info msg="Outbound nodes of test-nwgqv set to [test-nwgqv-3553655367]" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.770Z" level=info msg="node test-nwgqv phase Running -> Succeeded" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.770Z" level=info msg="node test-nwgqv finished: 2023-06-15 15:57:50.770067911 +0000 UTC" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.770Z" level=info msg="Checking daemoned children of test-nwgqv" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.770Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.770Z" level=info msg=reconcileAgentPod namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.770Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.770Z" level=info msg="Marking workflow completed" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.771Z" level=info msg="Marking workflow as pending archiving" namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.771Z" level=info msg="Checking daemoned children of " namespace=argo workflow=test-nwgqv
time="2023-06-15T15:57:50.779Z" level=info msg="cleaning up pod" action=deletePod key=argo/test-nwgqv-1340600742-agent/deletePod
time="2023-06-15T15:57:50.806Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=6997 workflow=test-nwgqv
time="2023-06-15T15:57:50.838Z" level=info msg="archiving workflow" namespace=argo uid=62a16f23-d2d6-469d-b6c5-f9ee2b1d7fb1 workflow=test-nwgqv
time="2023-06-15T15:57:50.842Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/test-nwgqv-collect-3553655367/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
time="2023-06-15T15:57:35.422Z" level=info msg="Saving path output parameter: pod-name"
time="2023-06-15T15:57:35.422Z" level=info msg="No output artifacts"
time="2023-06-15T15:57:35.423Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: test-nwgqv/test-nwgqv-build-1286867769/main.log"
time="2023-06-15T15:57:35.423Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2023-06-15T15:57:35.423Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=test-nwgqv/test-nwgqv-build-1286867769/main.log path=/tmp/argo/outputs/logs/main.log
time="2023-06-15T15:57:35.444Z" level=info msg="Save artifact" artifactName=main-logs duration=21.388172ms error="<nil>" key=test-nwgqv/test-nwgqv-build-1286867769/main.log
time="2023-06-15T15:57:35.445Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2023-06-15T15:57:35.445Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2023-06-15T15:57:35.484Z" level=info msg="Create workflowtaskresults 201"
time="2023-06-15T15:57:35.485Z" level=info msg="Alloc=8377 TotalAlloc=16620 Sys=28285 NumGC=5 Goroutines=10"
time="2023-06-15T15:57:35.426Z" level=info msg="Saving path output parameter: pod-name"
time="2023-06-15T15:57:35.426Z" level=info msg="No output artifacts"
time="2023-06-15T15:57:35.427Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: test-nwgqv/test-nwgqv-build-1803670843/main.log"
time="2023-06-15T15:57:35.427Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2023-06-15T15:57:35.427Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=test-nwgqv/test-nwgqv-build-1803670843/main.log path=/tmp/argo/outputs/logs/main.log
time="2023-06-15T15:57:35.445Z" level=info msg="Save artifact" artifactName=main-logs duration=17.493222ms error="<nil>" key=test-nwgqv/test-nwgqv-build-1803670843/main.log
time="2023-06-15T15:57:35.445Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2023-06-15T15:57:35.445Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2023-06-15T15:57:35.486Z" level=info msg="Create workflowtaskresults 201"
time="2023-06-15T15:57:35.487Z" level=info msg="Alloc=8723 TotalAlloc=16655 Sys=28797 NumGC=5 Goroutines=10"
time="2023-06-15T15:57:44.570Z" level=info msg="No output parameters"
time="2023-06-15T15:57:44.570Z" level=info msg="No output artifacts"
time="2023-06-15T15:57:44.571Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: test-nwgqv/test-nwgqv-collect-3553655367/main.log"
time="2023-06-15T15:57:44.571Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2023-06-15T15:57:44.571Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=test-nwgqv/test-nwgqv-collect-3553655367/main.log path=/tmp/argo/outputs/logs/main.log
time="2023-06-15T15:57:44.584Z" level=info msg="Save artifact" artifactName=main-logs duration=12.868292ms error="<nil>" key=test-nwgqv/test-nwgqv-collect-3553655367/main.log
time="2023-06-15T15:57:44.584Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2023-06-15T15:57:44.584Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2023-06-15T15:57:44.607Z" level=info msg="Create workflowtaskresults 201"
time="2023-06-15T15:57:44.610Z" level=info msg="Alloc=9197 TotalAlloc=16603 Sys=28285 NumGC=5 Goroutines=10"
```
