### ISSUE TITLE
`argo get` displays incorrect PODNAME when Node has a templateRef

### ISSUE THREAD

**Issue by SlaterByte** [argoproj/argo-workflows#11250]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

## Configuration

- argo-workflows ==v3.4.8 (including argo cli tooling)
- POD_NAMES=v2
- Workflow `example-wf` references a separate WorkflowTemplate `example-wft` in a Step.
- Actual Kubernetes Pod `.metadata.name` == `example-wf-wft-main-3406344706`

## Current behavior

Output from `argo get example-wf`. Note that the PODNAME `example-wf-example-wft/wft-main-3406344706` is incorrect and does not match the actual Pod name of `example-wf-wft-main-3406344706`. Instead, it includes formatted text intended
for use in the TEMPLATE column.

```shell
$ argo get example-wf -n workflows
Name:                example-wf
Namespace:           workflows
ServiceAccount:      executor
Status:              Succeeded
Conditions:          
 PodRunning          False
 Completed           True
Created:             Wed Jun 21 09:22:42 -0500 (22 seconds ago)
Started:             Wed Jun 21 09:22:42 -0500 (22 seconds ago)
Finished:            Wed Jun 21 09:22:52 -0500 (12 seconds ago)
Duration:            10 seconds
Progress:            1/1
ResourcesDuration:   6s*(100Mi memory),9s*(1 cpu)

STEP           TEMPLATE              PODNAME                                     DURATION  MESSAGE
 ✔ example-wf  wf-main                                                                       
 └───✔ step1   example-wft/wft-main  example-wf-example-wft/wft-main-3406344706  9s          
```

## Expected behavior

PODNAME for the Node matches the actual Pod's `.metadata.name` value.

```shell
$ argo get example-wf -n workflows
Name:                example-wf
Namespace:           workflows
ServiceAccount:      executor
Status:              Succeeded
Conditions:          
 PodRunning          False
 Completed           True
Created:             Wed Jun 21 09:22:42 -0500 (22 seconds ago)
Started:             Wed Jun 21 09:22:42 -0500 (22 seconds ago)
Finished:            Wed Jun 21 09:22:52 -0500 (12 seconds ago)
Duration:            10 seconds
Progress:            1/1
ResourcesDuration:   6s*(100Mi memory),9s*(1 cpu)

STEP           TEMPLATE              PODNAME                         DURATION  MESSAGE
 ✔ example-wf  wf-main                                                           
 └───✔ step1   example-wft/wft-main  example-wf-wft-main-3406344706  9s          
```

## Related issues:

- [PODNAMES as shown from argocli does not match with actual generated pod names #7646](https://github.com/argoproj/argo-workflows/issues/7646)
- [Wrong Pod name in argo get command result from CLI #9906](https://github.com/argoproj/argo-workflows/issues/9906)
- [Invalid node IDs in workflow.status #10107](https://github.com/argoproj/argo-workflows/issues/10107)
- [Wrong podName in workflow.status #10124](https://github.com/argoproj/argo-workflows/issues/10124)

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: example-wf
spec:
  entrypoint: wf-main
  templates:
    - name: wf-main
      steps:
        - - name: step1
            templateRef:
              name: example-wft
              template: wft-main

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: example-wft
spec:
  entrypoint: wft-main
  templates:
    - name: wft-main
      container:
        image: docker.io/docker/whalesay:latest
        command:
          - cowsay
          - Hello
          - Argo
```

### Logs from the workflow controller

```text
Not relevant
```

### Logs from in your workflow's wait container

```text
Not relevant
```
