### ISSUE TITLE
SSO Login in argo-workflow failing with HTTP 400 Error with authentication through Microsoft AD (OIDC)

### ISSUE THREAD

**Issue by praveenjindal62** [argoproj/argo-workflows#11268]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

SSO Login in argo-workflow failing with HTTP 400 Error with authentication through Microsoft AD (OIDC)

### Summary

We have configured SSO authentication mode with Microsoft AD as OIDC provider. Authentication through Microsoft AD is happening successfully, but while handling a callback we can see error page with HTTP 400 error. 

On further investigation into code, issue found to be in below code 

https://github.com/argoproj/argo-workflows/blob/aa2b66a5b7d8c3ab2af900a5fbda948b13d14085/server/auth/sso/sso.go#L230C2-L235C3

Here code is looking for a cookie with value of variable `state` and then setting a Cookie Header with value of `state`. Post that it is return HTTP 400 Error because cookie named with value of var `state` wasn't available. That doesn't make sense. If Cookie not found, then while error handling it should set the cookie with name `state`

### Configuration
```
sso:
      issuer: <issuer-url>
      clientId:
        name: argo-workflow-oidc-secret
        key: client-id
      clientSecret:
        name: argo-workflow-oidc-secret
        key: client-secret
      redirectUrl: http://arog-workflows.my.org.com/oauth2/callback
      rbac:
        enabled: true
      scopes: 
        - groups
        - emails
```

I already fixed and tested the fix, and would like to contribute the fix as a PR along with another enhancement that I raised with issue #11252 

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not Applicable
```

### Logs from the workflow controller

```text
Not Applicable
```

### Logs from in your workflow's wait container

```text
Not Applicable
```
