### ISSUE TITLE
Success hooks do not fire on top level nodes in a nested dag template

### ISSUE THREAD

**Issue by mnarozny** [argoproj/argo-workflows#11292]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When using hooks on nested dag templates, the success hook on the top level node does not fire immediately, takes about 10 seconds which sometimes causes the workflow to finish without sending a success hook at all.

In the example workflow, it will only work if the two dag tasks are lucky enough to align properly
job-1 hook will be fine because job-2 is still running, however, the job-2 success will only fire if job-1 is currently in progress or still running it's success hook (seems to give enough time for job-2 to be able to 'realise' the status is success and fire it's hook). This issue could be potentially related to this one: https://github.com/argoproj/argo-workflows/issues/10961 

I tried adding sleep jobs to this as well and it kind of works - as long as the subsequent dag node is in progress for at least 10 seconds, the previous task has still a chance to run the success hook. But if that subsequent node is too quick (like cashed for example) and the workflow goes further like 2 levels down, the old success node is forgotten.

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-dag-outer-hooks-inner-dag
spec:
  entrypoint: main

  templates:
    - name: main
      dag:
        tasks:
          - name: job-1
            template: dag-job
            arguments:
              parameters:
                - name: sleep_duration
                  value: 1
            hooks:
              running:
                expression: tasks['job-1'].status == "Running"
                template: hook
                arguments:
                  parameters:
                    - name: sleep_duration
                      value: 1
                    - name: context
                      value: "job-1"
              success:
                expression: tasks['job-1'].status == "Succeeded"
                template: hook
                arguments:
                  parameters:
                    - name: sleep_duration
                      value: 1
                    - name: context
                      value: "job-1"
          - name: job-2
            template: dag-job
            arguments:
              parameters:
                - name: sleep_duration
                  value: 50
            hooks:
              running:
                expression: tasks['job-2'].status == "Running"
                template: hook
                arguments:
                  parameters:
                    - name: sleep_duration
                      value: 1
                    - name: context
                      value: "job-2"
              success:
                expression: tasks['job-2'].status == "Succeeded"
                template: hook
                arguments:
                  parameters:
                    - name: sleep_duration
                      value: 1
                    - name: context
                      value: "job-2"

    - name: dag-job
      inputs:
        parameters:
          - name: sleep_duration
      dag:
        tasks:
          - name: dag-job-1
            template: sleep
            arguments:
              parameters:
                - name: sleep_duration
                  value: "{{ inputs.parameters.sleep_duration }}"
          - name: dag-job-2
            dependencies: [dag-job-1]
            template: sleep
            arguments:
              parameters:
                - name: sleep_duration
                  value: "{{ inputs.parameters.sleep_duration }}"

    - name: hook
      synchronization:
        mutex:
          name: "{{ inputs.parameters.context }}"
      inputs:
        parameters:
          - name: sleep_duration
          - name: context
      script:
        image: alpine
        command: [/bin/sh]
        source: |
          echo "Fake API call - sleeping for {{ inputs.parameters.sleep_duration }}, context is {{ inputs.parameters.context }}"
          sleep {{ inputs.parameters.sleep_duration }}
    
    - name: sleep
      inputs:
        parameters:
          - name: sleep_duration
      script:
        image: alpine:latest
        command: [/bin/sh]
        source: |
          echo "Sleeping for {{ inputs.parameters.sleep_duration }}"
          sleep {{ inputs.parameters.sleep_duration }}
```

### Logs from the workflow controller

```text
{"level":"info","msg":"Processing workflow","namespace":"ci-workflows","time":"2023-07-04T11:26:10.350Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Task-result reconciliation","namespace":"ci-workflows","numObjs":6,"time":"2023-07-04T11:26:10.351Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"task-result changed","namespace":"ci-workflows","nodeID":"example-dag-outer-hooks-inner-dagpxf2t-290109003","time":"2023-07-04T11:26:10.351Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"node changed","namespace":"ci-workflows","new.message":"","new.phase":"Succeeded","new.progress":"0/1","nodeID":"example-dag-outer-hooks-inner-dagpxf2t-290109003","old.message":"","old.phase":"Running","old.progress":"0/1","time":"2023-07-04T11:26:10.351Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.running","time":"2023-07-04T11:26:10.351Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"success","level":"info","lifeCycleHook":"success","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.success","time":"2023-07-04T11:26:10.351Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.running","time":"2023-07-04T11:26:10.352Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"success","level":"info","lifeCycleHook":"success","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.success","time":"2023-07-04T11:26:10.352Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-2.hooks.running","time":"2023-07-04T11:26:10.352Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"All of node example-dag-outer-hooks-inner-dagpxf2t.job-2.dag-job-2 dependencies [dag-job-1] completed","namespace":"ci-workflows","time":"2023-07-04T11:26:10.352Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Pod node example-dag-outer-hooks-inner-dagpxf2t-306886622 initialized Pending","namespace":"ci-workflows","time":"2023-07-04T11:26:10.353Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Created pod: example-dag-outer-hooks-inner-dagpxf2t.job-2.dag-job-2 (example-dag-outer-hooks-inner-dagpxf2t-sleep-306886622)","namespace":"ci-workflows","time":"2023-07-04T11:26:10.368Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-2.hooks.running","time":"2023-07-04T11:26:10.368Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"ci-workflows","time":"2023-07-04T11:26:10.368Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"reconcileAgentPod","namespace":"ci-workflows","time":"2023-07-04T11:26:10.368Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Workflow update successful","namespace":"ci-workflows","phase":"Running","resourceVersion":"504134345","time":"2023-07-04T11:26:10.380Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"action":"labelPodCompleted","key":"ci-workflows/example-dag-outer-hooks-inner-dagpxf2t-sleep-290109003/labelPodCompleted","level":"info","msg":"cleaning up pod","time":"2023-07-04T11:26:10.387Z"}
{"level":"info","msg":"Processing workflow","namespace":"ci-workflows","time":"2023-07-04T11:26:20.370Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Task-result reconciliation","namespace":"ci-workflows","numObjs":6,"time":"2023-07-04T11:26:20.371Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"node changed","namespace":"ci-workflows","new.message":"","new.phase":"Running","new.progress":"0/1","nodeID":"example-dag-outer-hooks-inner-dagpxf2t-306886622","old.message":"","old.phase":"Pending","old.progress":"0/1","time":"2023-07-04T11:26:20.371Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.running","time":"2023-07-04T11:26:20.371Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"success","level":"info","lifeCycleHook":"success","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.success","time":"2023-07-04T11:26:20.372Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.running","time":"2023-07-04T11:26:20.372Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"success","level":"info","lifeCycleHook":"success","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.success","time":"2023-07-04T11:26:20.372Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-2.hooks.running","time":"2023-07-04T11:26:20.372Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-2.hooks.running","time":"2023-07-04T11:26:20.373Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"ci-workflows","time":"2023-07-04T11:26:20.373Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"reconcileAgentPod","namespace":"ci-workflows","time":"2023-07-04T11:26:20.373Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Workflow update successful","namespace":"ci-workflows","phase":"Running","resourceVersion":"504135480","time":"2023-07-04T11:26:20.385Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Processing workflow","namespace":"ci-workflows","time":"2023-07-04T11:26:30.386Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Task-result reconciliation","namespace":"ci-workflows","numObjs":6,"time":"2023-07-04T11:26:30.387Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"node unchanged","namespace":"ci-workflows","nodeID":"example-dag-outer-hooks-inner-dagpxf2t-306886622","time":"2023-07-04T11:26:30.387Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.running","time":"2023-07-04T11:26:30.388Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"success","level":"info","lifeCycleHook":"success","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.success","time":"2023-07-04T11:26:30.388Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.running","time":"2023-07-04T11:26:30.388Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"success","level":"info","lifeCycleHook":"success","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.success","time":"2023-07-04T11:26:30.388Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-2.hooks.running","time":"2023-07-04T11:26:30.388Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-2.hooks.running","time":"2023-07-04T11:26:30.389Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"ci-workflows","time":"2023-07-04T11:26:30.389Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"reconcileAgentPod","namespace":"ci-workflows","time":"2023-07-04T11:26:30.389Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Processing workflow","namespace":"ci-workflows","time":"2023-07-04T11:27:13.143Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Task-result reconciliation","namespace":"ci-workflows","numObjs":7,"time":"2023-07-04T11:27:13.143Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"task-result changed","namespace":"ci-workflows","nodeID":"example-dag-outer-hooks-inner-dagpxf2t-306886622","time":"2023-07-04T11:27:13.144Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"node changed","namespace":"ci-workflows","new.message":"","new.phase":"Succeeded","new.progress":"0/1","nodeID":"example-dag-outer-hooks-inner-dagpxf2t-306886622","old.message":"","old.phase":"Running","old.progress":"0/1","time":"2023-07-04T11:27:13.144Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"success","level":"info","lifeCycleHook":"success","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.success","time":"2023-07-04T11:27:13.144Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.running","time":"2023-07-04T11:27:13.144Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.running","time":"2023-07-04T11:27:13.145Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"success","level":"info","lifeCycleHook":"success","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-1.hooks.success","time":"2023-07-04T11:27:13.145Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-2.hooks.running","time":"2023-07-04T11:27:13.145Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Outbound nodes of example-dag-outer-hooks-inner-dagpxf2t-2920921857 set to [example-dag-outer-hooks-inner-dagpxf2t-306886622]","namespace":"ci-workflows","time":"2023-07-04T11:27:13.145Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"node example-dag-outer-hooks-inner-dagpxf2t-2920921857 phase Running -\u003e Succeeded","namespace":"ci-workflows","time":"2023-07-04T11:27:13.145Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"node example-dag-outer-hooks-inner-dagpxf2t-2920921857 finished: 2023-07-04 11:27:13.14600152 +0000 UTC","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Checking daemoned children of example-dag-outer-hooks-inner-dagpxf2t-2920921857","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"hookName":"running","level":"info","lifeCycleHook":"running","msg":"Running hooks","namespace":"ci-workflows","node":"example-dag-outer-hooks-inner-dagpxf2t.job-2.hooks.running","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Outbound nodes of example-dag-outer-hooks-inner-dagpxf2t set to [example-dag-outer-hooks-inner-dagpxf2t-740035475 example-dag-outer-hooks-inner-dagpxf2t-306886622]","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"node example-dag-outer-hooks-inner-dagpxf2t phase Running -\u003e Succeeded","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"node example-dag-outer-hooks-inner-dagpxf2t finished: 2023-07-04 11:27:13.146354115 +0000 UTC","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Checking daemoned children of example-dag-outer-hooks-inner-dagpxf2t","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"TaskSet Reconciliation","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"reconcileAgentPod","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Updated phase Running -\u003e Succeeded","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Marking workflow completed","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Marking workflow as pending archiving","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"Checking daemoned children of ","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"key":"example-dag-outer-hooks-inner-dagpxf2t","level":"info","msg":"Released all acquired locks","namespace":"ci-workflows","time":"2023-07-04T11:27:13.146Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"action":"deletePod","key":"ci-workflows/example-dag-outer-hooks-inner-dagpxf2t-1340600742-agent/deletePod","level":"info","msg":"cleaning up pod","time":"2023-07-04T11:27:13.151Z"}
{"level":"info","msg":"Workflow update successful","namespace":"ci-workflows","phase":"Succeeded","resourceVersion":"504145322","time":"2023-07-04T11:27:13.158Z","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"level":"info","msg":"archiving workflow","namespace":"ci-workflows","time":"2023-07-04T11:27:13.548Z","uid":"ebf680c3-bef8-4a4d-b144-7b595f152496","workflow":"example-dag-outer-hooks-inner-dagpxf2t"}
{"action":"labelPodCompleted","key":"ci-workflows/example-dag-outer-hooks-inner-dagpxf2t-sleep-306886622/labelPodCompleted","level":"info","msg":"cleaning up pod","time":"2023-07-04T11:27:13.552Z"}
{"level":"info","msg":"Queueing Succeeded workflow ci-workflows/example-dag-outer-hooks-inner-dagpxf2t for delete in 1h0m0s due to TTL","time":"2023-07-04T11:27:13.603Z"}
```

### Logs from in your workflow's wait container

```text
example-dag-outer-hooks-inner-dag5f7fk-hook-2820830060: {"level":"info","msg":"Create workflowtaskresults 201","time":"2023-07-04T10:21:32.878Z"}
example-dag-outer-hooks-inner-dag5f7fk-hook-2820830060: {"level":"info","msg":"Alloc=11568 TotalAlloc=20546 Sys=43389 NumGC=5 Goroutines=10","time":"2023-07-04T10:21:32.878Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"Starting Workflow Executor","time":"2023-07-04T10:21:42.197Z","version":"untagged"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"Duration":1000000000,"Factor":1.6,"Jitter":0.5,"Steps":5,"level":"info","msg":"Using executor retry strategy","time":"2023-07-04T10:2
1:42.199Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"deadline":"2023-07-04T11:20:36Z","includeScriptOutput":false,"level":"info","msg":"Executor initialized","namespace":"ci-workflows","
podName":"example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037","template":"{\"name\":\"sleep\",\"inputs\":{\"parameters\":[{\"name\":\"sleep_duration\",\"value\":\"50\"}]},\"outputs\":{},\
"metadata\":{},\"script\":{\"name\":\"\",\"image\":\"alpine:latest\",\"command\":[\"/bin/sh\"],\"resources\":{},\"source\":\"echo \\\"Sleeping for 50\\\"\\nsleep 50\\n\"},\"archiv
eLocation\":{\"archiveLogs\":true,\"s3\":{\"endpoint\":\"s3.amazonaws.com\",\"bucket\":\"argo-workflows-artifacts-infrastructure-production\",\"region\":\"us-east-1\",\"insecure\"
:false,\"useSDKCreds\":true,\"key\":\"example-dag-outer-hooks-inner-dag5f7fk/example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037\"}},\"activeDeadlineSeconds\":1800,\"timeout\":\"45m\"}","time":"2023-07
-04T10:21:42.199Z","version":"\u0026Version{Version:untagged,BuildDate:2023-06-13T00:26:22Z,GitCommit:bc457cae6a431461f858e2a2f953fbb16af43a8f,GitTag:untagged,GitTreeState:clean,G
oVersion:go1.20.4,Compiler:gc,Platform:linux/amd64,}"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"Starting deadline monitor","time":"2023-07-04T10:21:42.199Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"error":null,"level":"info","msg":"Main container completed","time":"2023-07-04T10:22:33.208Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"No Script output reference in workflow. Capturing script output ignored","time":"2023-07-04T10:22:33.208Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"No output parameters","time":"2023-07-04T10:22:33.208Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"No output artifacts","time":"2023-07-04T10:22:33.208Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"S3 Save path: /tmp/argo/outputs/logs/main.log, key: example-dag-outer-hooks-inner-dag5f7fk/example-dag-outer-hooks-inner-dag5f7fk-sleep-24
14904037/main.log","time":"2023-07-04T10:22:33.208Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"Creating minio client using AWS SDK credentials","time":"2023-07-04T10:22:33.208Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"bucket":"argo-workflows-artifacts-infrastructure-production","endpoint":"s3.amazonaws.com","key":"example-dag-outer-hooks-inner-dag5f7fk/example-d
ag-whatever5f7fk-sleep-2414904037/main.log","level":"info","msg":"Saving file to s3","path":"/tmp/argo/outputs/logs/main.log","time":"2023-07-04T10:22:33.218Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"artifactName":"main-logs","duration":70963106,"error":null,"key":"example-dag-outer-hooks-inner-dag5f7fk/example-dag-outer-hooks-inner-dag5f7fk-sleep-241490403
7/main.log","level":"info","msg":"Save artifact","time":"2023-07-04T10:22:33.279Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","localArtPath":"/tmp/argo/outputs/logs/main.log","msg":"not deleting local artifact","time":"2023-07-04T10:22:33.279Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"Successfully saved file: /tmp/argo/outputs/logs/main.log","time":"2023-07-04T10:22:33.279Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"Create workflowtaskresults 201","time":"2023-07-04T10:22:33.297Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"Alloc=11547 TotalAlloc=20540 Sys=34429 NumGC=5 Goroutines=10","time":"2023-07-04T10:22:33.298Z"}
example-dag-outer-hooks-inner-dag5f7fk-sleep-2414904037: {"level":"info","msg":"Deadline monitor stopped","time":"2023-07-04T10:22:33.298Z"}
```
