### ISSUE TITLE
`result` output parameter of script templates occasionally become empty

### ISSUE THREAD

**Issue by boiledfroginthewell** [argoproj/argo-workflows#11330]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

The attached workflow runs successfully most of the time but it randomly fails once in 40 to 100 runs. When it failed, the value of `{{steps.echo.outputs.result}}` was empty even if the `echo` step successufully finished.

The outputs and archived logs in the UI are also empty.

![image](https://github.com/argoproj/argo-workflows/assets/19183832/77e23a68-f617-4b08-9328-101fc198a225)
![image](https://github.com/argoproj/argo-workflows/assets/19183832/ef8bdb06-bd86-4ed6-b383-fa1688bff361)
![image](https://github.com/argoproj/argo-workflows/assets/19183832/b18b6b53-ad60-4f86-aeb2-168b792309bf)

But kubernetes logs show that the script correctly displayed messages.

```
$ kubectl logs test-output-4q6zg-echo-336682105
time="2023-07-10T12:09:37.409Z" level=info msg="capturing logs" argo=true
hello
time="2023-07-10T12:09:37.412Z" level=info msg="sub-process exited" argo=true error="<nil>"
```

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-output-
spec:
  podGC:
    strategy: OnWorkflowSuccess
  ttlStrategy:
    secondsAfterCompletion: 1
    secondsAfterSuccess: 1
    secondsAfterFailure: 3600

  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: echo
            template: echo
        - - name: verify
            template: verify
            arguments:
              parameters:
                - name: message
                  value: "{{steps.echo.outputs.result}}"

    - name: echo
      script:
        image: busybox:1.35
        command: [sh]
        source: |
          echo hello
        # env:
        #   - name: ARGO_DEBUG_PAUSE_AFTER
        #     value: "true"
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"

    - name: verify
      inputs:
        parameters:
          - name: message
      script:
        image: busybox:1.35
        command: [sh]
        source: |
          if [ "{{inputs.parameters.message}}" != "hello" ]; then
            echo "steps.echo.outputs.result is empty: {{inputs.parameters.message}}" >&2
            exit 1
          fi
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
time="2023-07-10T12:10:15.735Z" level=info msg="No output parameters"
time="2023-07-10T12:10:15.735Z" level=info msg="No output artifacts"
time="2023-07-10T12:10:15.736Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: test-output-4q6zg/test-output-4q6zg-verify-664085946/main.log"
time="2023-07-10T12:10:15.736Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2023-07-10T12:10:15.736Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=test-output-4q6zg/test-output-4q6zg-verify-664085946/main.log path=/tmp/argo/outputs/logs/main.log
time="2023-07-10T12:10:16.169Z" level=info msg="Save artifact" artifactName=main-logs duration=433.751568ms error="<nil>" key=test-output-4q6zg/test-output-4q6zg-verify-664085946/main.log
time="2023-07-10T12:10:16.169Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2023-07-10T12:10:16.169Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2023-07-10T12:10:16.183Z" level=info msg="Alloc=8474 TotalAlloc=16633 Sys=27773 NumGC=5 Goroutines=10"
time="2023-07-10T12:10:16.183Z" level=info msg="Deadline monitor stopped"
time="2023-07-10T12:09:37.829Z" level=info msg="Capturing script output"
time="2023-07-10T12:09:37.829Z" level=info msg="No output parameters"
time="2023-07-10T12:09:37.829Z" level=info msg="No output artifacts"
time="2023-07-10T12:09:37.830Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: test-output-4q6zg/test-output-4q6zg-echo-336682105/main.log"
time="2023-07-10T12:09:37.830Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2023-07-10T12:09:37.830Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=test-output-4q6zg/test-output-4q6zg-echo-336682105/main.log path=/tmp/argo/outputs/logs/main.log
time="2023-07-10T12:09:37.997Z" level=info msg="Save artifact" artifactName=main-logs duration=167.537273ms error="<nil>" key=test-output-4q6zg/test-output-4q6zg-echo-336682105/main.log
time="2023-07-10T12:09:37.997Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2023-07-10T12:09:37.997Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2023-07-10T12:09:38.049Z" level=info msg="Alloc=8546 TotalAlloc=16632 Sys=23677 NumGC=5 Goroutines=10"
```
