### ISSUE TITLE
Allow skipping download of input artifacts based on condition

### ISSUE THREAD

**Issue by MrOnlineCoder** [argoproj/argo-workflows#11333]
# Summary

Allow skipping download of input artifacts based on condition for a step template by adding a `when` property, similiar to step definition:

```yml
inputs:
      artifacts:
        - name: large-dataset
          when: '{{workflow.parameters.cacheNeeded}} == true'
          path: '/opt/app/dataset'
          s3:
            bucket: 'my-bucket'
            key: 'large-5-gigabyte-data-that-can-be-skipped-sometimes.zip'
            accessKeySecret:
              name: '...'
              key: '...'
            secretKeySecret:
              name: '...'
              key: '...'
```

# Use Cases

I have a workflow with a container step that downloads pretty large artifacts. There are cases where I do not need this operation and I want to control it via workflow parameters for example. Currently, I have not found a way to do that.

The `fromExpression` field has examples only related to output artifacts, and it still expects to emit a valid artifact, while I need to completely skip one of the artifacts.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
