### ISSUE TITLE
UI: Show description for intermediate parameters

### ISSUE THREAD

**Issue by katylava** [argoproj/argo-workflows#11353]
# Summary

UI: Show description for intermediate parameters

# Use Cases

We have users of our Argo workflows that will only interact with it through the UI. They won't be writing workflows and won't be familiar with the yaml source of these workflows. They'll only be submitting new workflows from workflow templates in the UI.

I have created a workflow template with a suspend template and intermediate parameters, like so:

```yaml
    - name: wait-for-approval
      inputs:
        parameters:
          - name: approve
            default: 'NO'
            enum:
              - 'YES'
              - 'NO'
            description: >-
              Choose YES to continue workflow and activate on the
              production network
      outputs:
        parameters:
          - name: approve
            valueFrom:
              supplied: {}
      metadata: {}
      suspend:
        duration: 12h
```

I was hoping the description would show up in the dialog box to resume the workflow, but it does not. It would be useful if the UI displayed the description in a tooltip like it does for the parameters you see when you submit a new workflow from a workflow template.

<img width="996" alt="intermediate parameters screenshot" src="https://github.com/argoproj/argo-workflows/assets/10575/a884caf9-3441-4d17-b6b1-61dcd08b3c43">

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
