### ISSUE TITLE
azure artifact is unable to download directories from azure blob storage

### ISSUE THREAD

**Issue by viploveb** [argoproj/argo-workflows#11385]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

**Observed behaviour -** 

Azure artifact is not able to download nested directories, while S3 artifact does.
In the sample workflow provided below, if the blob path contains further directories (i.e blob path - /artifact/default , and under default there multiple other directories) then it fails to download the artifact. But if the blob path contains only files then it downloads it successfully.
I tested this behaviour with S3 artifacts, didn't observe any issues it downloads both directories and files successfully. 

Init container logs where azure artifact is configured - 

```
time="2023-07-18T15:47:32 UTC" level=info msg="Starting Workflow Executor" version=untagged
time="2023-07-18T15:47:32 UTC" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-07-18T15:47:32 UTC" level=info msg="Executor initialized" deadline="2023-07-19 15:47:31 +0000 UTC" includeScriptOutput=false namespace=default podName=s3-azure-artifact-l2h42-consume-1069730489 template="{\"name\":\"consume\",\"inputs\"
:{\"artifacts\":[{\"name\":\"file\",\"path\":\"/tmp\",\"azure\":{\"endpoint\":\"https://<storage_account_name>.blob.core.windows.net\",\"container\":\"argo\",\"useSDKCreds\":true,\"blob\":\"argo-artifacts/default/databricks/1689675741/raw-metadata/atlan-da
tabricks-1689675741-dcg55/\"},\"archive\":{\"none\":{}},\"optional\":true}]},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"argoproj/argosay:v2\",\"command\":[\"bash\",\"-c\"],\"args\":[\"ls /tmp\"],\"resources\":{}},\"arc
hiveLocation\":{\"archiveLogs\":true,\"azure\":{\"endpoint\":\"https://<storage_account_name>.blob.core.windows.net/argo\\",\\"container\\":\\"\\",\\"useSDKCreds\\":true,\\"blob\\":\\"argo-artifacts/default/s3-azure-artifact-l2h42/s3-azure-artifact-l2h42-consume-106
9730489\"}}}" version="&Version{Version:untagged,BuildDate:2023-07-17T23:53:44Z,GitCommit:307f78703068efb0645ba5c814fa98c86f9684ad,GitTag:untagged,GitTreeState:clean,GoVersion:go1.20.4,Compiler:gc,Platform:linux/amd64,}"
time="2023-07-18T15:47:33 UTC" level=info msg="Start loading input artifacts..."
time="2023-07-18T15:47:33 UTC" level=info msg="Downloading artifact: file"
time="2023-07-18T15:47:33 UTC" level=info msg="Downloading from Azure Blob Storage" blob=argo-artifacts/default/databricks/1689675741/raw-metadata/atlan-databricks-1689675741-dcg55/ container=argo endpoint="https://<storage_account_name>.blob.core.windows.
net"
time="2023-07-18T15:47:35 UTC" level=info msg="Downloading directory from Azure Blob Storage" blob=argo-artifacts/default/databricks/1689675741/raw-metadata/atlan-databricks-1689675741-dcg55/ container=argo endpoint="https://<storage_account_name>.blob.core.windows.net"
time="2023-07-18T15:47:35 UTC" level=info msg="Listing blobs in Azure Blob Storage" blob=argo-artifacts/default/databricks/1689675741/raw-metadata/atlan-databricks-1689675741-dcg55/ container=argo endpoint="https://<storage_account_name>.blob.core.windows.
net"
time="2023-07-18T15:47:35 UTC" level=info msg="Load artifact" artifactName=file duration=2.709414395s error="unable to download directory argo-artifacts/default/databricks/1689675741/raw-metadata/atlan-databricks-1689675741-dcg55/: unable to downl
oad file /argo/inputs/artifacts/file.tmp/catalogs/failure/result-count.txt: unable to create file /argo/inputs/artifacts/file.tmp/catalogs/failure/result-count.txt: open /argo/inputs/artifacts/file.tmp/catalogs/failure/result-count.txt: no such fi
le or directory" key=argo-artifacts/default/databricks/1689675741/raw-metadata/atlan-databricks-1689675741-dcg55/
time="2023-07-18T15:47:35 UTC" level=error msg="executor error: artifact file failed to load: unable to download directory argo-artifacts/default/databricks/1689675741/raw-metadata/atlan-databricks-1689675741-dcg55/: unable to download file /argo/
inputs/artifacts/file.tmp/catalogs/failure/result-count.txt: unable to create file /argo/inputs/artifacts/file.tmp/catalogs/failure/result-count.txt: open /argo/inputs/artifacts/file.tmp/catalogs/failure/result-count.txt: no such file or directory
"
time="2023-07-18T15:47:35 UTC" level=info msg="Alloc=8763 TotalAlloc=19889 Sys=28797 NumGC=6 Goroutines=8"
time="2023-07-18T15:47:35 UTC" level=fatal msg="artifact file failed to load: unable to download directory argo-artifacts/default/databricks/1689675741/raw-metadata/atlan-databricks-1689675741-dcg55/: unable to download file /argo/inputs/artifacts
/file.tmp/catalogs/failure/result-count.txt: unable to create file /argo/inputs/artifacts/file.tmp/catalogs/failure
```

Init container logs for S3 artifact - 
```
time="2023-07-18T15:44:57.068Z" level=info msg="Start loading input artifacts..."
time="2023-07-18T15:44:57.068Z" level=info msg="Downloading artifact: file"
time="2023-07-18T15:44:57.068Z" level=info msg="S3 Load path: /argo/inputs/artifacts/file.tmp, key: argo-artifacts/default/databricks/1689620707/raw-metadata/atlan-databricks-1689620707-r94j4"
time="2023-07-18T15:44:57.068Z" level=info msg="Creating minio client using AWS SDK credentials"
time="2023-07-18T15:45:00.206Z" level=info msg="Getting file from s3" bucket=<bucket_name> endpoint=s3.ap-south-1.amazonaws.com key=argo-artifacts/default/databricks/1689620707/raw-metadata/atlan-databricks-1689620707-r94j
4 path=/argo/inputs/artifacts/file.tmp
time="2023-07-18T15:45:00.333Z" level=info msg="Getting directory from s3" bucket=<bucket_name> endpoint=s3.ap-south-1.amazonaws.com key=argo-artifacts/default/databricks/1689620707/raw-metadata/atlan-databricks-1689620707
-r94j4 path=/argo/inputs/artifacts/file.tmp
time="2023-07-18T15:45:00.333Z" level=info msg="Listing directory from s3" bucket=<bucket_name> endpoint=s3.ap-south-1.amazonaws.com key=argo-artifacts/default/databricks/1689620707/raw-metadata/atlan-databricks-1689620707
-r94j4
time="2023-07-18T15:45:01.477Z" level=info msg="Successfully download file: /argo/inputs/artifacts/file"
time="2023-07-18T15:45:01.477Z" level=info msg="Alloc=8467 TotalAlloc=16969 Sys=22994 NumGC=5 Goroutines=4"
```

**Expected behaviour -** 

Just like S3 artifact, Azure artifact should be able to download directories and files

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: s3-azure-artifact
spec:
  templates:
    - name: main
      dag:
        tasks:
          - name: consume
            template: consume
    - name: consume
      inputs:
        artifacts:
          - name: file
            path: /tmp
            azure:
              endpoint: <azure_blob_endpoint>
              container: <container_name>
              useSDKCreds: true
              blob: >-
                <blob_path> (example - artifacts/default/test-wf)
            archive:
              none: {}
            optional: true
      container:
        name: ''
        image: argoproj/argosay:v2
        command:
          - bash
          - '-c'
        args:
          - ls /tmp
  entrypoint: main
```

### Logs from the workflow controller

```text
.
```

### Logs from in your workflow's wait container

```text
.
```
