### ISSUE TITLE
Incorrect creator labels on a resubmitted Workflow

### ISSUE THREAD

**Issue by umi0410** [argoproj/argo-workflows#11414]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Let's consider an original Workflow submitted by a user named foo. The Workflow should have creator labels as follows:

- `workflows.argoproj.io/creator: 0af436c4-faee-418a-8f0d-860ba852c87b`
- `workflows.argoproj.io/creator-email: foo.at.example.com`
- `workflows.argoproj.io/creator-preferred-username: foo`

**After the user `bar` resubmits the original Workflow, we would expect the new Workflow has creators labels about the user `bar`.**

However, when another user, bar, resubmits the original Workflow, we expect the new Workflow to have creator labels associated with the user bar.

Unfortunately, the new Workflow has incorrect labels related to the previous user, foo, as shown below:

- `workflows.argoproj.io/creator-email: foo.at.example.com`
- `workflows.argoproj.io/creator-preferred-username: foo`

Furthermore, it lacks the `workflows.argoproj.io/creator` label.

Upon investigating the code[^1] responsible for Workflow resubmission, I identified an issue with determining the appropriate creator labels for the new Workflow that is created by resubmission.

[^1]: [workflow/util/util.go#L646-L653](https://github.com/argoproj/argo-workflows/blob/master/workflow/util/util.go#L646-L653)

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
A mere simple whalesay Workflow is enough.

apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
    - name: whalesay              # name of the template
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "hello world" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
```

### Logs from the workflow controller

```text
Doesn't seem related to the workflow controller.
```

### Logs from in your workflow's wait container

```text
Doesn't seem related to a wait container.
```
