### ISSUE TITLE
lifecycle hooks executed when conditions are not met(DAG)

### ISSUE THREAD

**Issue by GeunSam2** [argoproj/argo-workflows#11422]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

A life cycle hook that should not be executed is executed.
When before task is fail in dag workflows, next step task's `running lifecycle hook` trigger without met any condition.

![image](https://github.com/argoproj/argo-workflows/assets/41275199/8d62c555-fd2a-4d9e-a63f-5d38e5b2e990)
`B.hooks.running` should not have been executed.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
        - name: A
          hooks:
            running: 
              expression: tasks.A.status == "Running"
              template: http
            success:
              expression: tasks.A.status == "Succeeded"
              template: http
          template: failtask
        - name: B
          dependencies: [A]
          hooks:
            running: 
              expression: tasks.B.status == "Running"
              template: http
            success:
              expression: tasks.B.status == "Succeeded"
              template: http
          template: echo

    - name: echo
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo sample"]

    - name: failtask
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["exit 1"]

    - name: http
      http:
        url: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"
```
```


### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
