### ISSUE TITLE
I want to contribute to issue 11219, I need help from a mentor.

### ISSUE THREAD

**Issue by shmruin** [argoproj/argo-workflows#11433]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous experience in Java, Kotlin with Spring Boot, and some Go experience**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #11219**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: (async). (Timezone - KST)

----

I already fix the issue but not sure if this change will affect to other codes.
I am lack of knowledge about testing changes.
So I left some mentoring request. Thanks.

**Comment by shmruin** [comment]
Thanks, @caelan-io . I am trying to test the #11219 with go test, but it seems quite weird.
As the original case is using sleep, as below. It seems I have to wait until all workflow is finished.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-steps-simple
  namespace: default
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: job-1
            template: sleep
            arguments:
              parameters:
                - name: sleep_duration
                  value: 5
          - name: job-2
            template: sleep
            arguments:
              parameters:
                - name: sleep_duration
                  value: 3

    - name: sleep
      synchronization:
        mutex:
          name: mutex-example-steps-simple
      inputs:
        parameters:
          - name: sleep_duration
      script:
        image: alpine:latest
        command: [/bin/sh]
        source: |
          echo "Sleeping for {{ inputs.parameters.sleep_duration }}"
          sleep {{ inputs.parameters.sleep_duration }}
      memoize:
        key: "memo-key-1"
        cache:
          configMap:
            name: cache-example-steps-simple
```
```go
         // ...
         cancel, controller := newController(wf)
	defer cancel()

	ctx := context.Background()

	woc := newWorkflowOperationCtx(wf, controller)
	woc.operate(ctx)

	assert.Equal(t, wfv1.WorkflowRunning, woc.wf.Status.Phase)
	job1CacheHit, job2CacheHit := false, false
	for _, node := range woc.wf.Status.Nodes {
		switch node.DisplayName {
		case "job-1":
			fmt.Println(node)
			job1CacheHit = node.MemoizationStatus.Hit
		case "job-2":
			fmt.Println(node)
			job2CacheHit = node.MemoizationStatus.Hit
		default:
			fmt.Println(node.TemplateName)
		}
	}
	assert.False(t, job1CacheHit)
	assert.True(t, job2CacheHit)
```
