### ISSUE TITLE
UI: Intermediate parameters window is not scrollable

### ISSUE THREAD

**Issue by elliotgunton** [argoproj/argo-workflows#11448]
# Summary

For intermediate parameter suspending nodes with many parameters, the window for inputting values does not scroll. The only way to see the input box is to zoom out in your browser, otherwise the input fields are accessible by tabbing through, but not visible. The "ok"/"cancel" buttons are also inaccessible without zooming out.

e.g. for a node with 15 inputs, I can only see 10 here:

![image](https://github.com/argoproj/argo-workflows/assets/17798778/d69a3489-0b1d-4fd1-9e03-5f0dd4eea9f1)

# Use Cases

Any intermediate parameters with 10+ inputs would be easier to use

<details><summary>Example yaml to test</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: intermediate-params-test-
spec:
  entrypoint: suspender
  templates:
  - name: suspender
    suspend: {}
    inputs:
      parameters:
      - default: ''
        name: param-1
      - default: ''
        name: param-2
      - default: ''
        name: param-3
      - default: ''
        name: param-4
      - default: ''
        name: param-5
      - default: ''
        name: param-6
      - default: ''
        name: param-7
      - default: ''
        name: param-8
      - default: ''
        name: param-9
      - default: ''
        name: param-10
      - default: ''
        name: param-11
      - default: ''
        name: param-12
      - default: ''
        name: param-13
      - default: ''
        name: param-14
      - default: ''
        name: param-15
    outputs:
      parameters:
      - name: param-1
        valueFrom:
          supplied: {}
      - name: param-2
        valueFrom:
          supplied: {}
      - name: param-3
        valueFrom:
          supplied: {}
      - name: param-4
        valueFrom:
          supplied: {}
      - name: param-5
        valueFrom:
          supplied: {}
      - name: param-6
        valueFrom:
          supplied: {}
      - name: param-7
        valueFrom:
          supplied: {}
      - name: param-8
        valueFrom:
          supplied: {}
      - name: param-9
        valueFrom:
          supplied: {}
      - name: param-10
        valueFrom:
          supplied: {}
      - name: param-11
        valueFrom:
          supplied: {}
      - name: param-12
        valueFrom:
          supplied: {}
      - name: param-13
        valueFrom:
          supplied: {}
      - name: param-14
        valueFrom:
          supplied: {}
      - name: param-15
        valueFrom:
          supplied: {}
```

</details>

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
