### ISSUE TITLE
Failed workflows can never be diagnosed as failed sometimes, meaning it is impossble to stop

### ISSUE THREAD

**Issue by isubasinghe** [argoproj/argo-workflows#11452]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Expected: 
When the user issues a stop/terminate request, the workflow should be marked as Failed. 

Happens:
When the user issues a stop/terminate (depending the progress to the targetTasks) ,the workflow will be never marked as Failed. 

Conditional make this easy to replicate, but I think this is a general issue. 

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-coinflip-
  annotations:
    workflows.argoproj.io/description: |
      This is an example of coin flip defined as a DAG.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#dag
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    retryStrategy:
      limit: "10"
    dag:
      tasks:
      - name: A
        template: coinflip
      - name: B
        depends: "A"
        template: main
      - name: C
        depends: "A"
        template: main
      - name: D
        depends: "B && C"
        template: coinflip

  - name: coinflip
    retryStrategy:
      limit: "10"
    steps:
    - - name: flip-coin
        template: flip-coin
    - - name: heads
        template: heads
        when: "{{steps.flip-coin.outputs.result}} == heads"
      - name: tails
        template: coinflip
        when: "{{steps.flip-coin.outputs.result}} == tails"

  - name: flip-coin
    retryStrategy:
      limit: "10"
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)

  - name: heads
    retryStrategy:
      limit: "10"
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\""]

  - name: main
    retryStrategy:
      limit: "10"
    containerSet:
      containers:
        - name: a
          image: ubuntu:20.04
          command:
            - "sleep"
            - "20"
        - name: b
          image: ubuntu:20.04
          command:
            - "sleep"
            - "20"
          dependencies: ["a"]
        - name: c
          image: ubuntu:20.04
          command:
            - "sleep"
            - "20"
          dependencies: ["a"]
        - name: d
          image: ubuntu:20.04
          command:
            - "sleep"
            - "20"
          dependencies: ["b", "c"]
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
