### ISSUE TITLE
`failed to resolve {{workflow.annotations.xxx}}` when annotations are defined in `workflowDefaults`

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#11465]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

## The issue
- you define an annotation in the workflow-controller-configmap section `workflowDefaults`
- you make a reference to this annotation in the workflow at any place with `{{workflow.annotations.xxx}}` where xxx is the name annotation
- when trying to submit the workflowTemplate argo refuses it with the error:
`ERROR - Workflow <workflow.yaml>: templates.exit.steps failed to resolve {{workflow.annotations.xxx}}`

This is really annoying because I wanted to use annotations to get some behavior in the exit-handler.
I will use something else, but I think it should be supported.

## Expected behavior
labels and annotations can be dynamic by definition, this should raise a warning but not an error.

### Version

v3.4.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
---
# In the workflow-controller-configmap
  workflowDefaults: |
    metadata:
      annotations:
        xxx: hello test
---
# The workflow
metadata:
  name: delightful-tiger
  labels:
    example: 'true'
spec:
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.annotations.xxx}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
```

### Logs from the UI or argo-server

```text
Bad Request: templates.argosay: failed to resolve {{workflow.annotations.xxx}}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by juliev0** [comment]
If you want to explore this on your own in the code, `{{workflow.annotations}}` are supposed to be getting set [here](https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/operator.go#L537). You can see if the `woc.execWf.Spec.WorkflowMetadata` that it's using [here](https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/operator.go#L537) is set as you expect. 

To confirm, your ConfigMap looks something like this? (copied from [here](https://argoproj.github.io/argo-workflows/default-workflow-specs/)):
```
# This file describes the config settings available in the workflow controller configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # Default values that will apply to all Workflows from this controller, unless overridden on the Workflow-level
  workflowDefaults: |
    metadata:
      annotations:
        xxxx: yyy
```

**Comment by sylock** [comment]
Yes, my configmap is like you say.
The thing is: the workflowDefaults are set at the runtime, when the pod is executed. But I get the error while pushing the workflow template through the API (from my CI/CD). At that moment, the workflow template does not have these values set. So the linter refuses it.

**Comment by caelan-io** [comment]
I'm sorry to hear you ran into this bug. Do you know if this was an issue on v3.3?

Also, would this workaround be viable for you? 

Create a workflow level exit handler and use kustomize/similar tool to apply the exit-handler to all WorkflowTemplates labeled with  `appType: apply-logic`:

````yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-exit-handler
spec:
  onExit: exit-handler
  templates:
    - name: exit-handler
      container:
        image: alpine:latest
        command: [ sh, -c ]
        # TODO implement actual handling
        args: [ "echo workflow exited with error!" ]
````
Apply this patch based on a label: 
kustomization.yaml
````yaml
patches:
  - path: exit-handler.yaml
    target:
      kind: WorkflowTemplate
      labelSelector: appType=apply-logic
````

Then label each app I want this applied to:
````yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: etp-logic-app
  labels:
    appType: apply-logic
````
