### ISSUE TITLE
Argo CLI: Lint: Enums can't have default in WorkflowTemplate

### ISSUE THREAD

**Issue by frmrm** [argoproj/argo-workflows#11471]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

This appears to be a variation of #6044.

When creating a WorkflowTemplate I would expect that I can define an `enum` parameter that also provides a `default` matching one of the enum values if no value was provided when the `WorkflowTemplate` becomes an actual `Workflow`. This does not appear to be the case. When I attempt to `argo lint` this I get the following error:

```
in "value-bug-example" (WorkflowTemplate): rpc error: code = InvalidArgument desc = spec.arguments.test-parameter.value is required
```

### Version

v3.4.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: value-bug-example

spec:
  arguments:
    parameters:
      - name: test-parameter
        enum: ['hello', 'goodbye']
        default: 'hello'

  templates:
    - name: test
      script:
        image: ubuntu
        source: echo {{workflow.parameters.test-parameter}}
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
