### ISSUE TITLE
Indirect infinite recursion doesn't get prevented

### ISSUE THREAD

**Issue by Joibel** [argoproj/argo-workflows#11499]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

With a workflow which recurses the controller will attempt to recurse forever. Take the recursion example from [the documentaton](../blob/master/docs/walk-through/recursion.md) and make it always coinflip for an example.
It feels like this should be prevented by having a configurable maximum recursion depth.

### Version

Current master

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: recursive2-
spec:
  entrypoint: coinflip
  templates:
  - name: coinflip
    steps:
    # flip a coin
    - - name: flip-coin
        template: flip-coin
    # evaluate the result in parallel
    - - name: heads
        template: coinflip              # call heads template if "heads"
        when: "{{steps.flip-coin.outputs.result}} == heads"
      - name: tails                     # keep flipping coins if "tails"
        template: coinflip
        when: "{{steps.flip-coin.outputs.result}} == tails"

  - name: coinflip
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)

  - name: heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\""]
```

### Logs from the workflow controller

```text
Not interesting
```

### Logs from in your workflow's wait container

```text
Not relevant
```
