### ISSUE TITLE
ContainerSet Retry strategy does nothing?

### ISSUE THREAD

**Issue by nicolas-vivot** [argoproj/argo-workflows#11502]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hi,

According to [this closed issue](https://github.com/argoproj/argo-workflows/issues/7290) we are supposed to be able to configure a retry strategy that applies to containers in a `ContainerSet`, not to the whole `Pod`.

After reading the documentation, i tried the following two configuration:

1. specifying a `retryStategy` with a `limit` of `2` at the template level (same level as `volumes`, `containerset`, `metadata`, etc.)
2. specifying a`retryStategy` with a `retries` of `2` at the containerset level (as specified in the above mentioned issue)

In case 1, the retry strategy applies to the entire `Pod`, meaning that the pod is restarted as any other container templates. The consequence is that all containers within this containerset are restarted, not just the container that failed.
![image](https://github.com/argoproj/argo-workflows/assets/79290619/f91d82d6-1a8e-4804-8f59-eeac59803038)

In case 2, no retry strategy is happening.
![image](https://github.com/argoproj/argo-workflows/assets/79290619/279ee4f9-a6c7-4cf1-8f2d-29f7df484b6e)

So, while the case 1 seems to work as expected (retrying all containers), the case 2 seems to retry nothing.
Checking logs, a single error log is logged, which probably validate the fact that no retry is happening.

Questions:

- do you really support restarting / retry strategy on a per container basis for `containerset` ?
- If yes, could you please indicate some clear documentation or workflow example that illustrate it ?

### Version

3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bug
  annotations:
    workflows.argoproj.io/description: |
      This workflow template is used to reproduce a bug.
spec:
  entrypoint: test
  templates:

    - name: test
      containerSet:
        retryStrategy:
          retries: "2"
        containers:
          - name: c1
            image: python:alpine3.6
            command:
              - python
              - -c
            args:
              - |
                print("hi")
          - name: c2
            image: python:alpine3.6
            command:
              - invalid
              - command
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
