### ISSUE TITLE
Mount `input-artifacts` into `initContainers`

### ISSUE THREAD

**Issue by djmcgreal-cc** [argoproj/argo-workflows#11519]
# Summary

Currently `initContainers` can't access `input: artifacts`.

Workaround: 
```
    podSpecPatch: | #can't specify it directly because then it fails validation
      initContainers:
        - name: summation
          volumeMounts:
            - mountPath: /data
              name: input-artifacts #have to manually add the data directory to initContainers, unfortunately - hope Argo don't change their internals on this
              subPath: data
```

Given the structure of the Workflow yaml, I'd naturally assumed that the `input-artifacts` would be mounted into `initContainers` also.

# Use Cases

Due to a lack of a `when` clause on output artifacts I have a `initContainer` doing the real work which needs the artifacts and a `container` whose code conditionally copies them to a different file path and then making the artifacts optional.

I also commonly use an initContainer pattern as storage is difficult in EKS where we can't assume Workflow Pods will be scheduled in the same availability zone to use EBS backed PVCs.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
