### ISSUE TITLE
inconsistent hasLocation between S3 and Azure artifacts

### ISSUE THREAD

**Issue by roelarents** [argoproj/argo-workflows#11512]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

In the context of [key-only artifacts](https://argoproj.github.io/argo-workflows/key-only-artifacts/) and [artifact repository ref](https://argoproj.github.io/argo-workflows/artifact-repository-ref/). I found an inconsistency between [Azure's](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L2628) and [S3's](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L2495) `hasLocation`. The S3 driver incorporates the endpoint, while Azure doesn't. `hasLocation` [is used](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L1245) a.o. for determining whether to "fill in the blanks" for key-only artifacts.

I found this while trying to make key-only artifacts work for azure. I expected/hoped that I could provide an artifact with not only the key (blob) but also the bucket (container). Unfortunately that was not true (see #11514). But
* in case of specifying the bucket (container) with Azure, the error was "accountKey secret is required ..." (because the defaults from the artifactRepository were not copied/relocated), while
* in case of specifying the bucket with S3, the error was that the artifact could not be found (because the default bucket was used which is different from what I filled in).

It's not really a high prio issue, I think, but also not very big, so something to look at. Looking at other `hasLocation` implementations, like git which also includes the repo (uri) or OSS which includes the endpoint, I think the endpoint should be incorporated for Azure too.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: key-only-artifacts-test
spec:
  entrypoint: main
#  artifactRepositoryRef:
#    key: test-azure or test-s3
  templates:
    - name: main
      inputs:
        artifacts:
          - name: foo
            path: /foo.txt
#            s3:
#              bucket: my-bucket
#              key: foo.txt
            azure:
#              container: my-container
              blob: foo.txt
      script:
        name: noop
        image: busybox
        source:
          echo /foo.txt
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: artifact-repositories
  annotations:
    workflows.argoproj.io/default-artifact-repository: test-azure
data:
  test-azure |
    azure:
      endpoint: http://127.0.0.1/devstoreaccount1
      container: public
      accountKeySecret:
        name: azurite
        key: key
  test-s3: |
    s3:
      bucket: public
      endpoint: 127.0.0.1:9000
      insecure: true
      accessKeySecret:
        name: minio
        key: access-key
      secretKeySecret:
        name: minio
        key: secret-key
---
kind: Secret
apiVersion: v1
metadata:
  name: minio
type: Opaque
data:
  access-key: bWluaW9zdG9yYWdl # miniostorage
  secret-key: bWluaW9zdG9yYWdl
---
kind: Secret
apiVersion: v1
metadata:
  name: azurite
type: Opaque
data:
  key: RWJ5OHZkTTAyeE5PY3FGbHFVd0pQTGxtRXRsQ0RYSjFPVXpGVDUwdVNSWjZJRnN1RnEyVVZFckN6NEk2dHEvSzFTWkZQVE90ci9LQkhCZWtzb0dNR3c9PQo= # azurite default key, not secret
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```
