### ISSUE TITLE
Argo workflow controller use more memory usage in the latest v3.4.9 release

### ISSUE THREAD

**Issue by zhangtbj** [argoproj/argo-workflows#11547]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

It works fine when we use the previous `v3.4.8` release, the argo workflow controller memory usage is around 1.6Gi:
<img width="682" alt="Screenshot 2023-08-09 at 15 41 28" src="https://github.com/argoproj/argo-workflows/assets/18108042/a2d112f4-ba3f-47e4-81e7-4f5898ae9c3f">

We have almost 1000+ complex workflow CRs in our namespace:
<img width="560" alt="Screenshot 2023-08-09 at 15 43 21" src="https://github.com/argoproj/argo-workflows/assets/18108042/917b5710-5c16-4b74-a204-c36f5cb6a15a">

But after we upgrade to the latest `v3.4.9` release, the memory usage of the controller increases faster, and finally reports OOMKilled or the pod was evicted:
<img width="730" alt="Screenshot 2023-08-09 at 16 05 21" src="https://github.com/argoproj/argo-workflows/assets/18108042/1b2f4b53-74e0-4a82-9072-454399c7355f">

### Version

v3.4.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
It is not related to the workflow content, you can leverage a large workflow CR and create it 1000+ times, then compare the memory usage of `v3.4.8` and `3.4.9`, then I think you can see the problem directly.
```

### Logs from the workflow controller

Finally the controller pod will be killed or evicted, so the log will be stopped at here:
```text
...
time="2023-08-09T07:55:30.303Z" level=info msg="SG Outbound nodes of neste-nd080722032606-azure-vm-linux-1742835238 are [neste-nd080722032606-azure-vm-linux-1668514597]" namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
time="2023-08-09T07:55:30.303Z" level=info msg="SG Outbound nodes of neste-nd080722032606-azure-vm-linux-2999330105 are [neste-nd080722032606-azure-vm-linux-2394216160]" namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
time="2023-08-09T07:55:30.303Z" level=info msg="SG Outbound nodes of neste-nd080722032606-azure-vm-linux-229198371 are [neste-nd080722032606-azure-vm-linux-3628204516]" namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
time="2023-08-09T07:55:30.303Z" level=info msg="SG Outbound nodes of neste-nd080722032606-azure-vm-linux-475868555 are [neste-nd080722032606-azure-vm-linux-3532128505]" namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
time="2023-08-09T07:55:30.303Z" level=info msg="SG Outbound nodes of neste-nd080722032606-azure-vm-linux-2088444962 are [neste-nd080722032606-azure-vm-linux-1472970905]" namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
time="2023-08-09T07:55:30.304Z" level=info msg="SG Outbound nodes of neste-nd080722032606-azure-vm-linux-2511078093 are [neste-nd080722032606-azure-vm-linux-632432796]" namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
time="2023-08-09T07:55:30.305Z" level=info msg="Workflow step group node neste-nd080722032606-azure-vm-linux-2978116099 not yet completed" namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
time="2023-08-09T07:55:30.305Z" level=info msg="Workflow step group node neste-nd080722032606-azure-vm-linux-3963016816 not yet completed" namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
time="2023-08-09T07:55:30.305Z" level=info msg="Workflow step group node neste-nd080722032606-azure-vm-linux-1515623741 not yet completed" namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
time="2023-08-09T07:55:30.305Z" level=info msg="TaskSet Reconciliation" namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
time="2023-08-09T07:55:30.305Z" level=info msg=reconcileAgentPod namespace=action-dev workflow=neste-nd080722032606-azure-vm-linux
```

### Logs from in your workflow's wait container

```text
We have 11 nodes, and each node has 7Gi memory. so the environment setting is good.
```

**Comment by Joibel** [comment]
We do not have the same issue here since upgrading from 3.4.8 to 3.4.9 our memory usage is stable.

![image](https://github.com/argoproj/argo-workflows/assets/1827156/20badccf-e2d8-4b0a-a6a1-408e85f52b86)

@zhangtbj I suspect we'll need more investigation on how you're using workflows unless someone else can replicate your issue.

**Comment by zhangtbj** [comment]
Hi @Joibel ,

Thanks for the reply. Do you also create lots of large workflow CR in your test/monitoring?

Is there any way I can check my settings or this is my workflow helm release settings, others are default:
```
argo-workflows:
  singleNamespace: true
  createAggregateRoles: false
  crds:
    install: false
  images:
    # imagePullPolicy to apply to all containers
    pullPolicy: IfNotPresent
  controller:
    containerRuntimeExecutor: pns
    clusterWorkflowTemplates:
      enabled: false
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 3Gi
        cpu: 1000m
  server:
    clusterWorkflowTemplates:
      enabled: false
    podAnnotations:
      # `emptyDir` mounted to this Pod may prevent the k8s autoscaler to scale down the cluster
      # Read more here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    extraArgs:
      # https://argoproj.github.io/argo-workflows/argo-server-auth-mode/
      # when server is exposed we don't need to provide token
      - --auth-mode=server

  useDefaultArtifactRepo: true
  artifactRepository:
    s3:
      bucket: argo-artifacts
      insecure: true
      endpoint: argo-minio.capact-system-dev.svc.cluster.local:9000
      accessKeySecret:
        name: argo-minio
        key: root-user
      secretKeySecret:
        name: argo-minio
        key: root-password

minio:
  podSecurityContext:
    enabled: false
  service:
    port: 9000
  defaultBuckets: "argo-artifacts,terraform:download"
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 400m

  volumePermissions:
    image:
      pullPolicy: IfNotPresent
    enabled: true

  deployment:
    updateStrategy:
      type: RollingUpdate

  pdb:
    create: true
    maxUnavailable: 1

oauth2-proxy:
  config:
    clientID: "<your client id>"
    clientSecret: "<your client secret>"
  extraArgs:
    provider: keycloak-oidc
    oidc-issuer-url: https://keycloak.capact.local/realms/supermaestro
    code-challenge-method: S256
    allowed-role: superAdmin
    upstream: http://argo-argo-workflows-server.capact-system-dev.svc.cluster.local:2746
  ingress:
    enabled: true
    className: nginx
    path: /
    pathType: Prefix
    annotations:
      acmechallengetype: http01
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/tls-acme: "true"
    hosts:
      - workflow.capact.dev
    tls:
      - secretName: argoworkflows-tls
        hosts:
          - workflow.capact.dev
```
