### ISSUE TITLE
Overriding parameter to retry workflow does not work when using WorkflowTempalate

### ISSUE THREAD

**Issue by toyamagu-2021** [argoproj/argo-workflows#11631]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

## Description

- Changes in workflow parameters on retrying are not reflected when submitted from WorkflowTemplate.
  - ![image](https://github.com/argoproj/argo-workflows/assets/83329336/318eb3fd-f178-4a50-855c-9807cc39fa2d)
- `spec.arguments.parameters` is changed as expected but not for `status.storedWorkflowTemplateSpec`
- If we change `status.storedWorkflowTemplateSpec` manually, it works fine.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
spec:
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: code
            value: '{{workflow.parameters.code}}'
      outputs: {}
      metadata: {}
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - sh
          - '-c'
        args:
          - exit '{{inputs.parameters.code}}'
        resources: {}
  entrypoint: argosay
  arguments:
    parameters:
      - name: code
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
