### ISSUE TITLE
Deleting a workflow on the workflow details page doesn't do anything

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-workflows#11661]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

If you go to the workflows details page and hit delete (and then confirm the delete), you are taken back to the workflows list page... where your workflow is still sat there staring at you :)

We do not have workflows archiving enabled.

### Version

v3.5.0-rc1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
any workflow
```

### Logs from the workflow controller

```text
I couldn't find anything useful. I'll update if I find anything.
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by terrytangyuan** [comment]
cc @toyamagu-2021 This might be related to your fix

**Comment by terrytangyuan** [comment]
If you refresh, would it be gone?

**Comment by toyamagu-2021** [comment]
I cannot reproduce this both on master branch and on 3.5.0-rc1 on k3d cluster... 🤔 

<img width="1034" alt="image" src="https://github.com/argoproj/argo-workflows/assets/83329336/e3ff491f-9946-414e-a90f-e180fdf5d077">
<img width="612" alt="image" src="https://github.com/argoproj/argo-workflows/assets/83329336/c44da420-a6f2-4608-bccc-788060d52bf7">

**Comment by toyamagu-2021** [comment]
Could you give me your workflow metadata.labels?
Might be following line returns false.

https://github.com/argoproj/argo-workflows/blob/7cb22a2aa33b7f5c92d5d87bfa69faed35b3d06a/ui/src/app/workflows/components/workflow-details/workflow-details.tsx#L194-L195

Or please give me your workflow (might be meaningless...).

**Comment by tico24** [comment]
Happens with a basic hello world though:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  namespace: ci
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
spec:
  serviceAccountName: ci
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```
