### ISSUE TITLE
Not able to Resubmit/Retry workflow with volumeClaimTemplates

### ISSUE THREAD

**Issue by om3171991** [argoproj/argo-workflows#11672]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hi Team,
We are using **volumeClaimTemplates** to create a Persistent Volume Claim (PVC) at the beginning of the workflow, making it accessible to various tasks or steps within the workflow. However, when attempting to resubmit the workflow, it continues to reference the outdated PVC, which was deleted due to the volumeClaimGC process triggered upon workflow completion. Please suggest how can we resubmit workflow. 

![image](https://github.com/argoproj/argo-workflows/assets/86664910/1fbd9c9d-7c53-43d5-b25c-2c9fda7d75c8)

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-issue-
spec:
  volumeClaimGC:
    strategy: OnWorkflowCompletion
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 1Gi
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: "{{workflow.name}}-workspace" ## PVC gets created with {{workflowname}}-{{volumeClaimTemplates.name}}
  templates:
    - name: main
      script:
        image: python:3.9
        command: [ bash ]
        source: |
          ls -lrt /workspace
          exit 1
        workingDir: /workspace
        volumeMounts:
          - name: workspace
            mountPath: /workspace
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
