### ISSUE TITLE
Default hooks for every step in a Template (stepDefaults)

### ISSUE THREAD

**Issue by leoleonsio** [argoproj/argo-workflows#11718]
# Summary

It would be nice to have the possibility of defining default `hooks` for each step that appears in a given Template.
In the current set up there is no way of defining a single set of hooks for all the `steps` which are a part of a Template.
Instead, the `hooks` section has to be repeated in each step, even if it follows the same pattern.

# Use Cases
Example use case includes a workflow that reports the progress of every step.
Our current solution is to add `hooks` under each step.
A custom `status-notifier` template has to be mentioned explicitly in the `hooks` section of every step.

Example below (`templates` section from a `Workflow`):

```yaml
  templates:
    - name: main # entrypoint template
      steps:
        - - name: step1
            template: step-template
            arguments:
              parameters:
                - name: sleep_time
                  value: "15"
            hooks:
              running:
                expression: steps.step1.status == "Running"
                template: status-notifier
                arguments:
                  parameters:
                    - name: status
                      value: "Running step1"
              success:
                expression: steps.step1.status == "Succeeded"
                template: status-notifier
                arguments:
                  parameters:
                    - name: status
                      value: "Finished step1"
        - - name: step2
            template: step-template
            arguments:
              parameters:
                - name: sleep_time
                  value: "15"
            hooks:
              running:
                expression: steps.step2.status == "Running"
                template: status-notifier
                arguments:
                  parameters:
                    - name: status
                      value: "Running step2"
              success:
                expression: steps.step2.status == "Succeeded"
                template: status-notifier
                arguments:
                  parameters:
                    - name: status
                      value: "Finished step2"
```

Instead, I would like to be able to specify something of this sort:
```yaml
  templates:
    - name: main # entrypoint template
      
      # proposed stepDefaults section
      stepDefaults:
        hooks:
          running:
            expression: steps.current_step.status == "Running"
            template: status-notifier
            arguments:
              parameters:
                - name: status
                  value: "Running {{ steps.current_step.name }}"
          success:
            expression: steps.current_step.status == "Succeeded"
            template: status-notifier
            arguments:
              parameters:
                - name: status
                  value: "Finished {{ steps.current_step.name }}"
      steps:
        - - name: step1
            template: step-template
            arguments:
              parameters:
                - name: sleep_time
                  value: "15"
        - - name: step2
            template: step-template
            arguments:
              parameters:
                - name: sleep_time
                  value: "15"
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
