### ISSUE TITLE
valueFrom for inputs.parameters.default

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-workflows#11724]
# Summary

The workflows are already super handy with the default values for inputs parameters. The next step would be to support `valueFrom` in the `default` field for input parameters of workflows.

# Use Cases

We're having plenty of workflows where the git-user and git-email and or ssh-key names etc. are gives as parameter. They only change in a minimal set of workflows. Still as there are so many workflows using them, I don't like the idea of setting the default value in every workflow. It would be nice to define them once in a configMap (or secret) and use the value in the default field.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by nice-pink** [comment]
I just realised that what I was trying is already possible. But I think there is no documentation on this feature or at least I didn't find it so far.

So for anyone finding this issue somehow:

`inputs.parameters` support `valueFrom.configMapKeyRef` which can be overridden with an `argument.parameter`.

Here is an example:
```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: value-from-overwrite
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: print
        template: print-param
        arguments:
          parameters:
          # this value will override the valueFrom of the input parameter
          - name: param
            value: peng

  - name: print-param
    inputs:
      parameters:
      - name: param
        valueFrom:
          # value from config map will be used, if param is not passed as argument
          configMapKeyRef:
            name: cm-param
            key: param
          # default value will be used, if param is not passed as argument and config map value can't be retrieved
          default: piff
    container:
      image: cgr.dev/chainguard/bash:latest
      command:
      - /bin/bash
      - -c
      - |
        set -eu
        echo "{{inputs.parameters.param}}"
```
