### ISSUE TITLE
Make pod name more clear in case of reusing templates 

### ISSUE THREAD

**Issue by StepanKuksenko** [argoproj/argo-workflows#11725]
# Summary. 

It is not clear which pod is related to this or that workflow task in case of reusing templates.   
Seems like a pod name is generated by the name of the reusable template but not a main template that reuses it. Which makes it difficult to find a proper pod in Kubernetes.  

# Use Cases. 
1. Create a workflow with dag tasks that reuse the same template. 
2. Try to find the proper pod in Kubernetes which is related to a specific dag task.  
    
**Workflow example:**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: check-pod-names
  namespace: nlp-metis-trainer
spec:
  serviceAccountName: argo-workflows-workflow
  workflowMetadata:
    labels:
      app.kubernetes.io/name: "check-pod-names"
  entrypoint: dag-tasks
  templates:
    - name: dag-tasks

      dag:
        tasks:
          - name: dag-task-first
            template: reusable-template

          - name: dag-task-second
            template: reusable-template

          - name: dag-task-third
            template: reusable-template

    - name: reusable-template
      container:
        image: alpine:latest
        command: [ sh, -c ]
        args: [ "sleep 1000" ]
```
  
**Dag tasks and pod names corelation in Argo Workflow UI**. 
<img width="1465" alt="Screenshot 2023-09-01 at 10 04 12 AM" src="https://github.com/argoproj/argo-workflows/assets/39428259/ff5a7d3b-7be4-4d9a-9c28-2973f9c8557e">
  
**Related pod names in Kubernetes**   
```bash
kubectl get po -l workflows.argoproj.io/workflow=check-pod-names
NAME                                           READY   STATUS    RESTARTS   AGE
check-pod-names-reusable-template-1240941911   2/2     Running   0          119s
check-pod-names-reusable-template-1280178539   2/2     Running   0          119s
check-pod-names-reusable-template-1609878920   2/2     Running   0          119s
```

  
It would be easier to find a proper pod related to a specific task if it would us the template name which calls a reusable template instead of using the name of a template that was called.   
  
**Prefered behaviour**  
```bash
kubectl get po -l workflows.argoproj.io/workflow=check-pod-names
NAME                                           READY   STATUS    RESTARTS   AGE
check-pod-names-dag-task-first-1240941911   2/2     Running   0          119s
check-pod-names-dag-task-second-1280178539   2/2     Running   0          119s
check-pod-names-dag-task-third-1609878920   2/2     Running   0          119s
```
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
