### ISSUE TITLE
Invalid prometheus labels on realtime gauge breaks metrics server 

### ISSUE THREAD

**Issue by alec-rabold** [argoproj/argo-workflows#11826]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Labels currently aren't validated when constructing a realtime gauge metric. Because of this, an invalid label will bring down the metrics server:
```
$ curl http://localhost:9090/metrics

An error has occurred while serving metrics:

"invalid-label" is not a valid label name for metric "argo_workflows_my_metric"
```

Removing `realtime` has the desired behavior, where the error is reported in the workflow's `Conditions`:
```
MetricsError: could not construct metric 'my_metric': metric label 'invalid-label' is invalid: keys may only contain alphanumeric characters, '_', or ':'
```

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: echo
spec:
  entrypoint: echo
  templates:
    - name: echo
      container:
        image: alpine:3.7
        command: [echo, "test"]
  metrics:
    prometheus:
      - name: my_metric
        help: "Help"
        labels:
          - key: invalid-label
            value: '{{workflow.uid}}'
        gauge:
          value: "{{ workflow.duration }}"
          realtime: true
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
