### ISSUE TITLE
Update default chart values. `sso: enabled` is missing, leading to: `error: empty issuer` when using sso configuration (v0.29.0 and higher)

### ISSUE THREAD

**Issue by xmsanchez** [argoproj/argo-workflows#11838]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Deploying helm chart 0.29.0 or higher declaring SSO configuration while omitting "enabled: true" leads to: "error: empty issuer" in the server logs, making it crash.

This key is not documented in the default values.yaml file.

It happens due to a change introduced in [0.29.0](https://github.com/argoproj/argo-helm/commit/5fb6688bcbeef2b7b1e1ed8a96d4eb7d172e5c1d#diff-cec457098d9d42755fa547ad6016ce4901bc41f31553e4a1caf9526dbc577961).

The default values file should reflect this (defaulting to false).

UPDATE: Given the following conditional, I'm not sure why it crashes. It really shouldn't since the sso block should not be evaluated.

```yaml
    {{- with .Values.server.sso }}
    {{- if .Values.server.sso.enabled }}
    sso:
       ...
```

### Version

Chart version: 0.29.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

Deploy the helm chart with these values:

```YAML

server:
  extraArgs:
  - --auth-mode=client
  - --auth-mode=sso
  sso:
    enabled: true
    clientId:
      name: dex-shared-secret
      key: client-id
    clientSecret:
      name: dex-shared-secret
      key: client-secret
    issuer: https://dex.example.com
    redirectUrl: https://argowf.example.com/oauth2/callback
    sessionExpiry: 8h
    scopes:
      - groups
      - email
      - profile
    rbac:
      enabled: true
```

### Logs from the workflow controller

```text
Logs from argo-workflows-server:


time="2023-09-18T10:28:03.883Z" level=info msg="not enabling pprof debug endpoints"
time="2023-09-18T10:28:03.884Z" level=info authModes="[client sso]" baseHRef=/ managedNamespace= namespace=argo-workflows secure=true ssoNamespace=argo-workflows
time="2023-09-18T10:28:03.884Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode"
Error: issuer empty
Usage:
  argo server [flags]

Examples:

See https://argoproj.github.io/argo-workflows/argo-server/

issuer empty
Flags::
      --access-control-allow-origin string 
      ...
```
