### ISSUE TITLE
Reopening and Resubmitting PR #9287

### ISSUE THREAD

**Issue by polyedre** [argoproj/argo-workflows#11848]
# Summary

Hi everyone,

I hope this message finds you well. I recently tested the changes in PR #9287 (https://github.com/argoproj/argo-workflows/pull/9287) and found that the fix effectively enables the deployment of Argo Workflows behind an Nginx Ingress Controller. Although the PR has been abandoned, I believe these modifications are valuable and would greatly benefit the community.

I'm interested in re-implementing and resubmitting the changes for consideration. Would the maintainers be open to this contribution? Your feedback would be greatly appreciated.

Looking forward to hearing your thoughts.

Best regards,

## Use Cases

Instances of argo-workflows behind the Nginx Ingress Controller could benefit from this.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
If you can add a test as asked for in [the original code review](https://github.com/argoproj/argo-workflows/pull/9287#discussion_r947234627), it's an overall small change that I think could be accepted.

> and found that the fix effectively enables the deployment of Argo Workflows behind an Nginx Ingress Controller

I have Argo SSE working fine behind an NGINX IGC, so I'm not sure what issue you're experiencing exactly

**Comment by agilgur5** [comment]
Found the original issue: #9286. Though that one reports it on Kong, not NGINX.

There's also an [annotation workaround](https://github.com/argoproj/argo-workflows/issues/9286#issuecomment-1468318354) listed there -- are you able to use a similar annotation in your NGINX Ingress to get around this?

**Comment by polyedre** [comment]
Kong is a wrapper on top of Nginx, so the Header is valid with both ingresses.

As we use the Nginx Ingress Controller, we tried to disable `[proxy-buffering](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-buffering)` or use other annotations:

```yaml
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "21600"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Connection '';
        chunked_transfer_encoding off;
        proxy_cache off;
```

We were only able to access the details of a workflows on the UI with the Header.
