### ISSUE TITLE
mutex ignored if using semaphore at same top level

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#11859]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

logs show nothing about mutex and i verified 2 workflows were able to run at same time

logs show semaphore is working.

then i tried removing semaphore and mutex worked. so seems they don't work together?

https://github.com/argoproj/argo-workflows/blob/master/workflow/sync/sync_manager.go#L280-L283 seems like it doesn't loop through both types of synchronization cc @sarabala1979 

### Version

3.4.11

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: redact-
spec:
  serviceAccountName: argo-workflows-server
  onExit: exit-handler
  entrypoint: flow
  synchronization:
    semaphore:
      configMapKeyRef:
        name: argowf-semaphores
        key: redact
    mutex:
      name: "{{= sprig.coalesce('something','catch') }}"
...can't share the rest
```
```


### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
Is there a reason you'd want to use both? Could you give a concrete use-case?

More specifically, you should be able to do everything you can with a mutex with a semaphore.

But yea it should probably error out if that's not allowed, instead of silently ignoring it

**Comment by tooptoop4** [comment]
so i use parallelism to not scale up too many workers
i use a lower semaphore on my sensor so that cronworkflows can have some slots to run (ie cronworkflows will be able to fill parallelism-semaphore)
then i want mutex at a per table level lock

**Comment by agilgur5** [comment]
Oh right, you basically have to do this since you can't have multiple semaphores right now, correct?

I remember your [Slack thread](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1693477592194889?thread_ts=1693477592.194889&cid=C01QW9QSSSK) and #9382.

If multiple semaphores were supported, that would suffice for your use-case too, right?

**Comment by tooptoop4** [comment]
multi semaphores would be even better

**Comment by agilgur5** [comment]
oh right, good point! that is a very good use-case.

hopefully it's not too difficult to allow both a mutex and a semaphore on a single Workflow. I don't _think_ the structs and CR fields overlap, but would have to do a deeper dive to make sure.

**Comment by agilgur5** [comment]
Hmm there is one problem with supporting multiple synchronization variables on a Workflows -- it can lead to a deadlock. I suppose that could be left to the user to properly use and resolve though?

**Comment by tooptoop4** [comment]
why deadlock? it should only consume the mutex if there is room to fit under the semaphore limit too

**Comment by agilgur5** [comment]
Oh good point! I think then the main thing is that grabbing multiple locks has to be atomic in the Controller code to prevent a race that could cause a deadlock

**Comment by agilgur5** [comment]
Ok dove into the code a bit and the good thing is that it is already [atomic](https://github.com/argoproj/argo-workflows/blob/26481a2146107ad0937ef7698c27f3686f93c81e/workflow/sync/sync_manager.go#L118).

The problematic code isn't on the lines you linked but actually in the `TryAcquire` function. Specifically it assumes there is only one lock to acquire and [`Synchronization.GetType()`](https://github.com/argoproj/argo-workflows/blob/26481a2146107ad0937ef7698c27f3686f93c81e/workflow/sync/sync_manager.go#L133) returns _either_ Semaphore or Mutex, and so code using it does not quite handle the situation of both. [Semaphore](https://github.com/argoproj/argo-workflows/blob/26481a2146107ad0937ef7698c27f3686f93c81e/pkg/apis/workflow/v1alpha1/workflow_types.go#L1651) happens to be the one it checks for first, hence mutex being ignored.

Fixing this will also handle much of the code needed for multiple semaphores, outside of the spec changes necessary (which do affect a number of places too).

**Comment by agilgur5** [comment]
Ok supporting both is actually a bit confusing in the current code due to the assumption that it must be one or the other in the structs. It needs to be rewritten with a wrapper that can have multiple.

At that point, it would actually be easier (and probably less breaking) to just make them mutually exclusive and then implement multi-semaphore (which would also be mutually exclusive with single semaphore and single mutex).

So I might just do that. #10191 may be quite relevant here and potentially blocking with respect to holder keys

**Comment by jakkubu** [comment]
Hi @agilgur5 what is the status of this? I have the similar use-case: mutex is used for guarding a resource, (namespace)-parallelism is affecting other teams, so we wanted to use semaphore for limiting number of workflows.

**Comment by sarabala1979** [comment]
@jakkubu @tooptoop4 Here is the workaround for having multiple locks 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: redact-
spec:
  serviceAccountName: argo-workflows-server
  onExit: exit-handler
  entrypoint: start
  synchronization:
    semaphore:
      configMapKeyRef:
        name: argowf-semaphores
        key: redact
  templates:
    - name: start
      synchronization:
        mutex:
          name: "{{= sprig.coalesce('something','catch') }}"
      steps:
        - name: flow
          template: flow
```
