### ISSUE TITLE
Artifacts not set in Status.Nodes | ArtifactGC prevents Workflow deletion

### ISSUE THREAD

**Issue by Garett-MacGowan** [argoproj/argo-workflows#11879]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

This issue stems from #10840. I expect to be able to delete a workflow and have the garbage collection remove the artifact from the repository.

In this specific case, the workflow finalizer isn't removed from the workflow due to a failure [here](https://github.com/argoproj/argo-workflows/blob/d0588ea092012c36ce06f44b008dc057bdf72154/workflow/controller/artifact_gc.go#L135), implying that the artifacts aren't being written to Status.Nodes. Upon inspecting the workflow manifest's `Status.Nodes`, I can confirm that no output artifacts are listed. Artifacts are successfully being written to GCS upon triggering "stop" for the workflow.

**Steps to Reproduce**
1) Have a workflow with a long-running process
2) Stop the workflow mid-execution
3) Artifacts are written to GCS
4) Attempt to delete the workflow
5) Notice that the workflow cannot be deleted since the finalizer can't be removed & the artifacts are not deleted.

**Partial Remedy**
While preparing this ticket, I notice that by adding at least one successful workflow and artifact to my DAG (in parallel), the workflow's finalizer is successfully deleted & the successful DAG step's artifacts are also successfully cleaned up, **however**, the failed (stopped) DAG step's artifacts are not cleaned up. This can lead to dangling resources in GCS.

**Suggested Fix**
Ensure that stopped/failed workflow step's output artifacts are written to `Status.Nodes`

### Version

3.5.0-rc1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# https://argoproj.github.io/argo-workflows/cron-workflows/
# https://argoproj.github.io/argo-workflows/fields/
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: TEMP
spec:
  # Start up 5 minutes to 6 AM to ensure system is online.
  schedule: "55 5 * * *"
  timezone: America/New_York
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  # Run the workflow for 16 hours, 10 minutes (between 5:55 AM and 10:05 PM)
  activeDeadlineSeconds: 58200
  workflowSpec:
    entrypoint: test-dag
    templates:
      - name: test-dag
        dag:
          tasks:
            - name: test
              template: test
              continueOn:
                failed: true
    # Clean up artifacts https://argoproj.github.io/argo-workflows/walk-through/artifacts/#artifact-garbage-collection
    artifactGC:
      strategy: OnWorkflowDeletion
      serviceAccountName: argo-workflows-sa
      forceFinalizerRemoval: true
    # How long to keep workflows around after they have completed https://argoproj.github.io/argo-workflows/fields/#ttlstrategy
    ttlStrategy:
      # 5 minutes
      secondsAfterCompletion: 300
      secondsAfterSuccess: 300
      secondsAfterFailure: 300
    # a temporary volume, named workdir, will be used as a working directory for this workflow. This volume is passed
    # around from step to step.
    volumeClaimTemplates:
      - metadata:
          name: logs
        spec:
          accessModes: [ "ReadWriteMany" ]
          resources:
            requests:
              storage: 2.5G
    serviceAccountName: argo-workflows-sa
    templates:
      - name: test
        volumes:
          - name: logs
            emptyDir: { }
        container:
          name: test
          image: alpine:latest
          command:
            - sh
            - '-c'
          args:
            - |
              echo 'testing' > /tmp/test.txt
              while true
              do
                # loop indefinitely
                sleep 1
              done
        outputs:
          artifacts:
            - name: 'test'
              path: /tmp/test.txt
              archive:
                none: { }
              gcs:
                # https://argoproj.github.io/argo-workflows/variables/
                key: "{{workflow.name}}-{{workflow.creationTimestamp.Y}}-{{workflow.creationTimestamp.m}}-{{workflow.creationTimestamp.d}}_{{workflow.creationTimestamp.H}}-{{workflow.creationTimestamp.M}}-{{workflow.creationTimestamp.S}}/test.txt"
```

### Logs from the workflow controller

```text
time="2023-09-24T06:32:14.100Z" level=debug msg="processing Artifact GC Strategy OnWorkflowDeletion" namespace=pipeline-dev workflow=pipeline-cron-workflow-dev-9thnn
time="2023-09-24T06:32:14.100Z" level=debug msg="processing Artifact GC Strategy OnWorkflowDeletion" namespace=pipeline-dev workflow=pipeline-cron-workflow-dev-9thnn
time="2023-09-24T06:32:14.100Z" level=debug msg="No Artifact Search Results returned from strategy OnWorkflowDeletion" namespace=pipeline-dev workflow=pipeline-cron-workflow-dev-9thnn
time="2023-09-24T06:32:14.101Z" level=debug msg="Log changes patch: {\"status\":{\"artifactGCStatus\":{\"strategiesProcessed\":{\"OnWorkflowDeletion\":true}}}}"
time="2023-09-24T06:32:14.101Z" level=info msg="Workflow to be dehydrated" Workflow Size=4845
time="2023-09-24T06:32:14.113Z" level=debug msg="Update workflows 200"
time="2023-09-24T06:32:14.114Z" level=info msg="Workflow update successful" namespace=pipeline-dev phase=Failed resourceVersion=121464951 workflow=pipeline-cron-workflow-dev-9thnn
```

### Logs from in your workflow's wait container

```text
time="2023-09-24T06:29:25.935Z" level=info msg="Starting Workflow Executor" version=v3.5.0-rc1
time="2023-09-24T06:29:25.941Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-09-24T06:29:25.941Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=pipeline-dev podName=pipeline-cron-workflow-dev-9thnn-test-2481151211 template="{\"name\":\"test\",\"inputs\":{},\"outputs\":{\"artifacts\":[{\"name\":\"test\",\"path\":\"/tmp/test.txt\",\"gcs\":{\"key\":\"pipeline-cron-workflow-dev-9thnn-2023-09-24_06-28-19/test.txt\"},\"archive\":{\"none\":{}}}]},\"metadata\":{},\"container\":{\"name\":\"test\",\"image\":\"alpine:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo 'testing' \\u003e /tmp/test.txt\\nwhile true\\ndo\\n  # loop indefinitely\\n  sleep 1\\ndone\\n\"],\"resources\":{}},\"volumes\":[{\"name\":\"logs\",\"emptyDir\":{}}],\"archiveLocation\":{\"archiveLogs\":false,\"gcs\":{\"bucket\":\"project-workflow-artifacts\",\"key\":\"pipeline-cron-workflow-dev-9thnn/pipeline-cron-workflow-dev-9thnn-test-2481151211\"}}}" version="&Version{Version:v3.5.0-rc1,BuildDate:2023-08-15T18:44:17Z,GitCommit:6cd3e810e9c953e0a78070f41ab8f7d799fe51d3,GitTag:v3.5.0-rc1,GitTreeState:clean,GoVersion:go1.20.7,Compiler:gc,Platform:linux/amd64,}"
time="2023-09-24T06:29:25.942Z" level=info msg="Starting deadline monitor"
time="2023-09-24T06:31:19.023Z" level=info msg="Main container completed" error="<nil>"
time="2023-09-24T06:31:19.040Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-09-24T06:31:19.040Z" level=info msg="No output parameters"
time="2023-09-24T06:31:19.040Z" level=info msg="Saving output artifacts"
time="2023-09-24T06:31:19.045Z" level=info msg="Deadline monitor stopped"
time="2023-09-24T06:31:19.050Z" level=info msg="Staging artifact: test"
time="2023-09-24T06:31:19.052Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2023-09-24T06:31:19.058Z" level=info msg="Copying /tmp/test.txt from container base image layer to /tmp/argo/outputs/artifacts/test.tgz"
time="2023-09-24T06:31:19.065Z" level=info msg="/var/run/argo/outputs/artifacts/tmp/test.txt.tgz -> /tmp/argo/outputs/artifacts/test.tgz"
time="2023-09-24T06:31:19.080Z" level=info msg="Untaring /tmp/argo/outputs/artifacts/test.tgz archive before upload"
time="2023-09-24T06:31:19.105Z" level=info msg="GCS Save path: /tmp/argo/outputs/artifacts/test.txt, key: pipeline-cron-workflow-dev-9thnn-2023-09-24_06-28-19/test.txt"
time="2023-09-24T06:31:19.773Z" level=info msg="Save artifact" artifactName=test duration=668.368403ms error="<nil>" key=pipeline-cron-workflow-dev-9thnn-2023-09-24_06-28-19/test.txt
time="2023-09-24T06:31:19.773Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/artifacts/test.txt
time="2023-09-24T06:31:19.773Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/test.txt"
time="2023-09-24T06:31:19.795Z" level=debug msg="Create workflowtaskresults 201"
time="2023-09-24T06:31:19.798Z" level=info msg="Alloc=26019 TotalAlloc=37269 Sys=47741 NumGC=5 Goroutines=10"
```

**Comment by Garett-MacGowan** [comment]
As promised, here's the new ticket dedicated to my issue @juliev0 @

**Comment by juliev0** [comment]
Okay, ultimately the root cause is outside of the ArtifactGC logic itself, but nonetheless I can try to look at this when I get time.

**Comment by Garett-MacGowan** [comment]
@juliev0 much appreciated.

**Comment by Garett-MacGowan** [comment]
@juliev0 I took a peek at the source code. I have a hypothesis that I'm hoping you can shine some light on. Perhaps it can expedite your investigation when you get around to it.

My best guess is that the code execution never gets to this line [here](https://github.com/argoproj/argo-workflows/blob/b5f69a8826609eabc6e11fb477eea3472ba4f91f/workflow/controller/dag.go#L353) in `workflow/controller/dag.go`. I think this segment is responsible for setting the artifacts in `status.nodes`.

I think the execution never reaches the above due, perhaps, to this line [here](https://github.com/argoproj/argo-workflows/blob/b5f69a8826609eabc6e11fb477eea3472ba4f91f/workflow/controller/dag.go#L307) in `workflow/controller/dag.go`, which returns early because of `case wfv1.NodeError, wfv1.NodeFailed:`. After inspecting the workflow's status.nodes.node.phase, it seems that `wfv1.NodeFailed` is set when the workflow is stopped.

The solution may be to set outputs in `status.nodes` irrespective of `case wfv1.NodeError, wfv1.NodeFailed:`. Is there any reason why this shouldn't be done?

The same issue seems to exist in `workflow/controller/steps.go` [here](https://github.com/argoproj/argo-workflows/blob/b5f69a8826609eabc6e11fb477eea3472ba4f91f/workflow/controller/steps.go#L117C6-L117C12).

Thanks for the help!

**Comment by juliev0** [comment]
> here

That's good investigation. I don't see any reason why Outputs shouldn't be set in that case. @agilgur5 do you see any reason?

@Garett-MacGowan would you be able to try seeing if you can fix this? I don't have much bandwidth and really haven't worked myself with this particular part of the code.

**Comment by Garett-MacGowan** [comment]
I can give it a go. Will have to set up the dev environment. Any guidance would be helpful @agilgur5.

**Comment by juliev0** [comment]
Great, thank you. Have you seen this page?: https://argoproj.github.io/argo-workflows/running-locally/

if you have questions let us know.

**Comment by agilgur5** [comment]
> Okay, ultimately the root cause is outside of the ArtifactGC logic itself

Ah well I'm not too familiar with ArtifactGC but if this is actually in steps or DAG, that would be a part of the codebase that I'm familiar. Guess we're switching off ironically 😅

I can take a look tomorrow-ish. From a quick glance, @Garett-MacGowan's logic makes sense to me. It is an edge case if a step completes after stop, so it might've been missed. IIRC there were some recent changes to make sure artifacts are uploaded if a step completes after stop, so maybe outputs were missed in that change

> Will have to set up the dev environment.
> Have you seen this page?: https://argoproj.github.io/argo-workflows/running-locally/

Devcontainer works pretty well for a fast set-up nowadays. I use it myself as do some other contributors

**Comment by Garett-MacGowan** [comment]
@juliev0 I've seen that page, thanks. I will work through dev setup tomorrow.

@agilgur5 Thanks! Let me know if your look around results in anything I should know.

If you see no problems with it, I'll implement a change so that `steps` and `DAG` update the workflow's `status.nodes` outputs irrespective of `wfv1.NodeError, wfv1.NodeFailed`.

**Comment by Garett-MacGowan** [comment]
@juliev0 & @agilgur5

## WIP update

### Findings

As I work through this, I'm noticing the issue seems to be related only to stopping the workflow (a failure alone doesn't do the trick). I've got a test case that reproduces the error, so now I'm implementing the fix. Since there's no test cases for a step failure with GC, I'll implement one for that too, to be sure.

### My contribution experience + blocks

**Jetbrains Dev Container**

A note in the setup docs to avoid using `Dev Container` with Jetbrains IDEs might be nice since the Jetbrains DevContainer plugin doesn't support `features` in the `devcontainer.json` yet. This is used to install Go, Node, docker-in-docker, and python in the container. See [this ticket](https://youtrack.jetbrains.com/issue/IDEA-323789/Support-features-option-of-devcontainer.json) for tracking of that issue. I wasted a bunch of time trying to figure this out since I initially didn't read the plugin notes fully.

**Dev Container argoexec-image failure loop**

Once I finally got the Dev Container working on VS Code, I still ran into an issue where the container would boot up but require a restart of VS Code to enter the environment. It would otherwise enter a loop where one step would continually fail.
```
executor: ERROR: failed to solve: process "/bin/sh -c make dist/argoexec GIT_COM
MIT=${GIT_COMMIT} GIT_TAG=${GIT_TAG} GIT_TREE_STATE=${GIT_TREE_STATE}" did not c
omplete successfully: exit code: 2
executor: make: *** [Makefile:244: argoexec-image] Error 1
```
Once I restart VS Code, it seems to work fine, but I'm not certain that this error has no consequences...

**Multiple terminals to segregate UI and Controller**

I don't think using [one terminal for the controller + server and another for the UI works...](https://argoproj.github.io/argo-workflows/running-locally/#using-multiple-terminals). I'm not seeing any reference to CTRL in the `make` file. When I try to run the command for starting the UI alone (`make start CTRL=false`) fails since it tries to boot up the controller again (it is already running).

**No debug logs for workflow controller**

It seems that there is no loglevel=debug for the workflow controller as my Dev Container debug logs (enabled by 4+enter) don't show the workflow debug logs.

When I add 
```
args:
    - --loglevel=debug
```
to `test/e2e/manifests/mixins/workflow-controller-deployment.yaml`, debug logs still don't show.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: workflow-controller
          imagePullPolicy: Never
          args:
            - --loglevel=debug
```
