### ISSUE TITLE
semaphore with dynamic key+number

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#11890]
# Summary

Currently mutex allows a dynamic key (example incoming tablename from an argo event). But only allows max 1 wf to consume it.
Currently semaphore requires a static key name (pre-defined in configmap) but allows n number of wfs to consume it.

This new proposal is about having the flexibility from both worlds. ie a semaphore that allows dynamic key (not pre-defined in configmap) and ability to specify n wfs to consume it.

I imagine on a sensor it could look like:
```yaml
  synchronization:
    semaphore:
      name: "{{=...parse_tbl from sensor message}}"
      maxInParallel: 3
```

also allow semaphore to be applied conditionally based on an expression? ie if somearg='x' then semaphore of 'y' applied else don't apply any semaphore.
alternatively can it fallback to a mutex if there is no semaphore with that name defined in the wfcontroller/configmap ?

## Use Cases

To dynamically rate limit the platform, avoid new tables being resource hogs
