### ISSUE TITLE
Combination valueFrom and withParam does not work for dag templates

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-workflows#11900]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

```
arguments:
  parameters:
  - name: param
    valueFrom:
      configMapKeyRef:
        name: cm-{{item.configMap}}
        key: param
withParam: "{{inputs.parameters.cm-list}}"      # parameter specifies the list to iterate over
```

throws the error in the sensor deployment:
```
time="2023-09-29T08:45:39.915Z" level=fatal msg="Failed to submit workflow: templates.main.tasks.print missing value for parameter 'param'"{"level":"error","ts":1695977139.9195628,"logger":"argo-events.sensor","caller":"sensors/listener.go:345","msg":"Failed to execute a trigger","sensorName":"test-resource","error":"failed to execute trigger, failed after retries: failed to execute submit command for workflow , exit status 1","triggerName":"workflow-trigger","triggeredBy":["webhook"],"triggeredByEvents":["62303161646637302d393732362d343865322d383730632d636636383962313466626533"],"stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:345"}
```

when using a `dag` template but works with `steps` template.

Below are the entire sensors and workflows.

### Version

v3.4.11

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Throws an error:

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test-resource
  namespace: argo
spec:
  dependencies:
    - name: webhook
      eventSourceName: webhook
      eventName: test
  revisionHistoryLimit: 1
  template:
    serviceAccountName: argo-events-sa
  triggers:
  - template:
      name: workflow-trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: test-resource-
              namespace: argo
            spec:
              entrypoint: main
              serviceAccountName: workflow
              arguments:
                parameters:
                - name: cm-list                                     # a list of items
                  value: |
                    [
                      { "configMap": "param-test-ping" },
                      { "configMap": "param-test-pong" }
                    ]

              templates:
              - name: main
                inputs:
                  parameters:
                  - name: cm-list
                dag:
                  tasks:
                  - name: print
                    templateRef:
                      name: print-params
                      template: main
                    arguments:
                      parameters:
                      - name: param
                        valueFrom:
                          configMapKeyRef:
                            name: cm-{{item.configMap}}
                            key: param
                    withParam: "{{inputs.parameters.cm-list}}"      # parameter specifies the list to iterate over
```

Works as expected:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test-resource
  namespace: argo
spec:
  dependencies:
    - name: webhook
      eventSourceName: webhook
      eventName: test
  revisionHistoryLimit: 1
  template:
    serviceAccountName: argo-events-sa
  triggers:
  - template:
      name: workflow-trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: test-resource-
              namespace: argo
            spec:
              entrypoint: main
              serviceAccountName: workflow
              arguments:
                parameters:
                - name: cm-list                                     # a list of items
                  value: |
                    [
                      { "configMap": "param-test-ping" },
                      { "configMap": "param-test-pong" }
                    ]

              templates:
              - name: main
                inputs:
                  parameters:
                  - name: cm-list
                steps:
                - - name: print
                    templateRef:
                      name: print-params
                      template: main
                    arguments:
                      parameters:
                      - name: param
                        valueFrom:
                          configMapKeyRef:
                            name: cm-{{item.configMap}}
                            key: param
                    withParam: "{{inputs.parameters.cm-list}}"      # parameter specifies the list to iterate over
```

Workflow template:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: print-params
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: param
    container:
      image: cgr.dev/chainguard/bash:latest
      command:
      - /bin/bash
      - -c
      - |
        set -eu
        echo "{{inputs.parameters.param}}"
```
```


### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
