### ISSUE TITLE
resubmit failing

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#11904]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Dev tried resubmitting a workflow and got this error. I as an admin can do it fine.

```
{"code":7,"message":"workflows.argoproj.io is forbidden: User \"system:serviceaccount:backend:backend\" cannot create resource \"workflows\" in API group \"argoproj.io\" in the namespace \"backend\""}: workflows.argoproj.io is forbidden: User "system:serviceaccount:backend:backend" cannot create resource "workflows" in API group "argoproj.io" in the namespace "backend"
```

role

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-read-role
  namespace: {{ .Values.team }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
# pod get/watch is used to identify the container IDs of the current pod
# pod patch is used to annotate the step's outputs back to controller (e.g. artifact location)
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
- apiGroups:
  - argoproj.io
  verbs:
  - "*"
  resources:
  - clusterworkflowtemplates
  - cronworkflows
  - workflows
  - workflowtaskresults
  - workflowtasksets
  - workflowtasksets/status
  - workflowtemplates
# logs get/watch are used to get the pods logs for script outputs, and for log archival
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
```

cluster-role

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.team }}-cluster-role
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - clusterworkflowtemplates
    verbs:
      - create
      - get
      - list
      - watch
```

### Version

v3.5.0-rc2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

N/A
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

N/A
```
