### ISSUE TITLE
Avoid doing Cluster wide requests when argo workflow is run in namespaced mode

### ISSUE THREAD

**Issue by visheyra** [argoproj/argo-workflows#11938]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I have an argo workflow instance running in namespaced mode with a few namespaces to manage that are given as command line argument with the --managed-namespace flag. Argo workflow is installed via helm and values are rightly set. However, when I first log into argo workflow, I noticed that whenever I'm on one of the workflow pages (clusterworkflowtemplate, workflows, workflowtemplates), when I don't specify a namespace in the searchbox, argo workflow is executing a cluster wide requests to the kube api server. I have a custom rbac that do not allows one to make requests at cluster level but do allows to requests resources at namespace level, all namespaces configured are listed in the managed_namespaces.

It seems weird that argo workflows is perfoming this cluster wide requests while having be explicitely configured to manage resources at namespace level and with the managed namespaces passed as an argument.

relevant part of the helm values:
```
singleNamespace: false
server:
  image:
    tag: v3.4.11
  extraEnv:
    - name: SSO_DELEGATE_RBAC_TO_NAMESPACE
      value: "true"
  secure: true
  extraArgs:
    - --auth-mode
  extraEnv:
    - name: SSO_DELEGATE_RBAC_TO_NAMESPACE
      value: "true"
```

full server command line:
```
          - server
          - --configmap=argo-workflows-workflow-controller-configmap
          - --auth-mode
          - sso
          - "--secure=true"
          - "--loglevel"
          - "info"
          - "--gloglevel"
          - "0"
          - "--log-format"
          - "text"
          - "--namespaced"
```

Error message that indicates the assumed wrong call is made:

![Screenshot 2023-10-04 at 09 13 56](https://github.com/argoproj/argo-workflows/assets/5854290/72e3d4ac-5000-4da6-948a-795dd82e1d9d)

### Version

v3.4.11

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not relevant
```

### Logs from the workflow controller

```text
not relevant
```

### Logs from in your workflow's wait container

```text
not relevant
```
