### ISSUE TITLE
UI: multi-select for input parameters

### ISSUE THREAD

**Issue by maxisam** [argoproj/argo-workflows#12017]
# Summary

Multi-select in the UI for input parameters

## Use Cases

Trigger workflow manually with multi-select input.

This is a reference to the old popular closed issue https://github.com/argoproj/argo-workflows/issues/6824

Thanks for considering this feature. Great OSS project!

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by doncorsean** [comment]
+1 for multiselects

**Comment by agilgur5** [comment]
> This is a reference to the old popular closed issue #6824

To clarify, that issue asked for dropdowns and checkboxes in general, which already existed, but weren't well documented. 

It did _also_ ask for multi-selects (a type of dropdown), which seem to not currently be supported and so actually need a new feature in the UI.
I count at least 7 upvotes for multi-selects specifically in [later comments](https://github.com/argoproj/argo-workflows/issues/6824#issuecomment-1147244935), though some of the original upvotes may have also been for multi-selects.

**Comment by shaharb-hs** [comment]
+1 for multiselect

**Comment by narenmurali** [comment]
+1

**Comment by maayan-cohen-hs** [comment]
+1

**Comment by sakib** [comment]
+1

**Comment by marcelin** [comment]
Can you try this: 

```
name: "Multi-select"
run-name: 🎯${{ github.workflow}} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      dev:
        description: 'Deploy to dev'
        default: false
        type: boolean
      staging:
        description: 'Deploy to staging'
        default: false
        type: boolean
      qat:
        description: 'Deploy to qat'
        default: false
        type: boolean
      prod:
        description: 'Deploy to prod'
        default: false
        type: boolean

jobs:
  get-selected:
    name: Get environment
    runs-on: ubuntu-latest
    outputs: 
      selectedJson: ${{ steps.get-selected-step.outputs.selected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Selected
        id: get-selected-step
        uses: joao-zanutto/get-selected@v1.1.1
        with:
          format: json

  plan-env:
    needs: get-selected
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJSON(needs.get-selected.outputs.selectedJson) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
```
