### ISSUE TITLE
Multiple Plugins Only One works

### ISSUE THREAD

**Issue by whybeyoung** [argoproj/argo-workflows#12013]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

i have wrote two  plugins ,  a and b,  and i configure two plugin.yaml and generate two configs to apply . 

the log in controller seems ok , both plugin were added.

when i want to use
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-test-yd
spec:
  entrypoint: main
  templates:
    - name: main
       plugin:
         b:
          job:
            apiVersion: batch/v1
            kind: Job
            metadata:
              name: test-argo
              namespace: atp
            spec:
              template:
                spec:
                  containers:
                  - name: pi
                    image: perl:5.34.0
                    command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
                  restartPolicy: Never
              backoffLimit: 4

```
to submit workflow . 

according to the The agent executor's log , only  'a' plugin 's controller recevie the job.. however, i thinks it should be schedule to 'b' controller....

maybe a bug, i dont't find that any doc  about it ， how to choose a plugin to run  ？ it's the question....

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Above.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
