### ISSUE TITLE
Some parallell execute Steps may be stucked on running phase when retry workflow manually

### ISSUE THREAD

**Issue by jswxstw** [argoproj/argo-workflows#12010]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

<img width="380" alt="image" src="https://github.com/argoproj/argo-workflows/assets/18543532/f4d7e89a-4e9e-4f67-8458-e30aa2dd24fb">

As the picture shows, workflow has three parallell execute nodes: step-case(Failed), retry-step-case(Failed), retry-step-group-case(Succeeded).
If I retry this workflow manually, retry-step-group-case(0) will stucked on running phase even if workflow is completed.
<img width="368" alt="image" src="https://github.com/argoproj/argo-workflows/assets/18543532/922aea28-e4e3-4620-8c46-37f7126ad5ae">

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-fail-with-argument-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: code
        value: 1
  templates:
  - name: main
    steps:
    - - name: retry-step-group-case
        template: fail-step-group
      - name: retry-step-case
        template: fail-with-argument-with-retry
        arguments:
          parameters:
            - name: code
              value: '{{workflow.parameters.code}}'
      - name: step-case
        template: fail-with-argument
        arguments:
          parameters:
            - name: code
              value: '{{workflow.parameters.code}}'
  - name: fail-with-argument-with-retry
    inputs:
      parameters:
        - name: code
    container:
      image: python:alpine3.6
      command: [python, -c]
      args: ["import sys; sys.exit({{inputs.parameters.code}})"]
    retryStrategy:
      limit: "5"
      backoff:
        duration: "5"
        factor: "2"
        maxDuration: "1m"
  - name: fail-with-argument
    inputs:
      parameters:
        - name: code
    container:
      image: python:alpine3.6
      command: [python, -c]
      args: ["import sys; sys.exit({{inputs.parameters.code}})"]
  - name: fail-with-rate
    container:
      image: python:alpine3.6
      command: ["python", -c]
      args: ["import random; import sys; exit_code = random.choice([0, 0, 1]); sys.exit(exit_code); print(exit_code)"]
  - name: fail-step-group
    steps:
    - - name: step1
        template: fail-with-rate
    - - name: step2
        template: fail-with-rate
    - - name: step3
        template: fail-with-rate
    retryStrategy:
      limit: "5"
      backoff:
        duration: "5"
        factor: "2"
        maxDuration: "1m"
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
