### ISSUE TITLE
Accessing step `.main-logs` in WorkflowTemplate no longer works after upgrade v3.4.11 to v3.4.12

### ISSUE THREAD

**Issue by ndejong** [argoproj/argo-workflows#12065]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

We have workflow templates that reference as argument artifact inputs the `.main-logs` output artifact from the a previous step.  This arrangement has been working well until a recent upgrade from v3.4.11 to v3.4.12 (same also occurs when upgrading to v3.5.x)

The HTTP400 error response content looks like this
```json
{
  "code":3,
  "message":"templates.entrypoint-handler.steps failed to resolve {{ steps.foobar.outputs.artifacts.main-logs }}"
}
```

The supplied sample workflow will work fine in v3.4.11 and prior but fail in v3.4.12 (and v3.5.x)

### Version

v3.4.12

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: bugreport-20231023a

spec:
  workflowMetadata: {}
  entrypoint: entrypoint-handler

  templates:
    - name: entrypoint-handler
      steps:

        - - name: foobar
            template: foobar
            arguments:
              parameters:
                - { name: target, value: "hello world" }

        - - name: workflow-processor
            templateRef:
              name: bugreport-20231023a-templates
              template: workflow-processor
            arguments:
              artifacts:
                - { name: artifact_engine_log, from: "{{ steps.foobar.outputs.artifacts.main-logs }}" }

    # foobar
    # =========================================================================
    - name: foobar
      inputs:
        parameters:
          - { name: target }
      container:
        image: docker/whalesay
        command: [ "cowsay" ]
        args: [ "{{ inputs.parameters.target }}" ]


---


apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: bugreport-20231023a-templates

spec:

  templates:
    - name: workflow-processor

      inputs:
        artifacts:
          - { name: artifact_engine_log, path: "/data/artifact_engine_log", optional: true }

      container:
        image: alpine:latest
        command: ["cat"]
        args: [ "/data/artifact_engine_log" ]
```

### Logs from the workflow controller

```text
NA
```

### Logs from in your workflow's wait container

```text
NA
```

**Comment by tooptoop4** [comment]
maybe caused by https://github.com/argoproj/argo-workflows/pull/11781 ?

**Comment by terrytangyuan** [comment]
cc @shmruin Would you like to take a look?

**Comment by agilgur5** [comment]
Possible workaround may be to use an `expr` expression, i.e. `{{=steps.foobar.outputs.artifacts['main-logs']}}`

**Comment by shmruin** [comment]
Yes, this is because of #11781. It seems start checking [resolveAllVariables](https://github.com/argoproj/argo-workflows/blob/9955958a8c7d835b04de9a602118a7b91c802341/workflow/validate/validate.go#L652) makes problem.

The original code doesn't check this because when [checkValidWorkflowVariablePrefix](https://github.com/argoproj/argo-workflows/blob/9955958a8c7d835b04de9a602118a7b91c802341/workflow/validate/validate.go#L658C7-L658C39), the untrimmed ` steps.` is not match to `steps.` so resolveAllVariables just returns nil without error. (which is checking [global variable prefix](https://github.com/argoproj/argo-workflows/blob/9955958a8c7d835b04de9a602118a7b91c802341/workflow/validate/validate.go#L692))

But with the change of trimming, as #11871 does, it starts checking the tag and `steps.foobar.outputs.artifacts.main-logs` does not pass this. I check this by some small print as below.

```
Bad Request: templates.entrypoint-handler.steps failed to resolve {{ steps.foobar.outputs.artifacts.main-logs }}, scope is map[steps.foobar.exitCode:true steps.foobar.finishedAt:true steps.foobar.hostNodeName:true steps.foobar.id:true steps.foobar.outputs.result:true steps.foobar.startedAt:true steps.foobar.status:true steps.workflow-processor.status:true workflow.annotations:placeholder-5 workflow.annotations.json:placeholder-6 workflow.labels:placeholder-7 workflow.labels.json:placeholder-8 workflow.mainEntrypoint:placeholder-2 workflow.name:placeholder-0 workflow.namespace:placeholder-1 workflow.serviceAccountName:placeholder-3 workflow.status:placeholder-9 workflow.uid:placeholder-4], globalParam is map[workflow.annotations:placeholder-5 workflow.annotations.json:placeholder-6 workflow.labels:placeholder-7 workflow.labels.json:placeholder-8 workflow.mainEntrypoint:placeholder-2 workflow.name:placeholder-0 workflow.namespace:placeholder-1 workflow.serviceAccountName:placeholder-3 workflow.status:placeholder-9 workflow.uid:placeholder-4], tag is ' steps.foobar.outputs.artifacts.main-logs ', trimmedTag is 'steps.foobar.outputs.artifacts.main-logs'
```

It looks like `...artifacts` not exist. (but `workflow.outputs.artifacts.` is [exist](https://github.com/argoproj/argo-workflows/blob/9955958a8c7d835b04de9a602118a7b91c802341/workflow/validate/validate.go#L669C38-L669C65))

`steps.foobar.outputs.artifacts.main-logs` is neither [scope or globalParams](https://github.com/argoproj/argo-workflows/blob/9955958a8c7d835b04de9a602118a7b91c802341/workflow/validate/validate.go#L661) so it should pass [some if-else cases](https://github.com/argoproj/argo-workflows/blob/9955958a8c7d835b04de9a602118a7b91c802341/workflow/validate/validate.go#L664) but nothing match so makes error.

Does it mean that the case checks of `resolveAllVariables` should be updated? I want to know proper validation check case that something like `steps.foobar.outputs.artifacts.main-logs` should be placed.

**Comment by agilgur5** [comment]
Thanks for the in-depth investigation @shmruin!

> Does it mean that the case checks of `resolveAllVariables` should be updated? I want to know proper validation check case that something like `steps.foobar.outputs.artifacts.main-logs` should be placed.

It seems like the actual execution has been allowing this for some time, so it indeed sounds like `resolveAllVariables` needs updating. Basically the validation did not match the actual execution.
There might be some other cases like this one that were missed due to the lack of trimming 😕 Basically one bug was hiding a few more validation bugs underneath.

**Comment by shmruin** [comment]
Are there any way I can check all those kinds of special(implicit) parameters? 
I think I can make 'artifact' keyword pass the validation, like 'workflows.output', but it would be better if I can prevent the other special cases.

**Comment by shmruin** [comment]
It looks like 'artifacts' keyword of output is quite special. By watching the log again, it is not in 'scope' but should works as a keyword. Maybe I can just generalize 'workflows.output.artifacts.' prefix case to something like '*.outputs.artifacts'.

**Comment by shmruin** [comment]
It looks like 'artifacts' keyword of output is quite special. By watching the log again, it is not in 'scope' but should works as a keyword. Maybe I can just generalize 'workflows.output.artifacts.' prefix case to something like '*.outputs.artifacts'.

**Comment by shmruin** [comment]
@agilgur5 , is `main-log` be dealt with some artifact without explicitly using output? 
I check that this error happens because `foobar` step has no ouput artifacts keyword.
If it is like below, then that template will works.

```yaml
    - name: foobar
      inputs:
        parameters:
          - { name: target }
      container:
        image: docker/whalesay
        command: [ "cowsay" ]
        args: [ "{{ inputs.parameters.target }}" ]
      output:
        artifacts:
          - name: main-log
            path: SOME_MAIN_LOG_PATH
```
See [addOutputsToScope](https://github.com/argoproj/argo-workflows/blob/2abc16f6c08432d19fce8988a4f41a728fb2333d/workflow/validate/validate.go#L1048).

If it is the only case, then I think we can make `main-log` to pass the validation even when not using output keyword.

**Comment by agilgur5** [comment]
> @agilgur5 , is `main-log` be dealt with some artifact without explicitly using output?

oh I actually missed that, good catch!

If so, this isn't documented anywhere I could find. That may be how [archive logs](https://argoproj.github.io/argo-workflows/configure-archive-logs/) function? @ndejong are you using archive logs to store your logs as artifacts?

**Comment by ndejong** [comment]
Thanks for the time and attention on this -

@shmruin - unless I'm mis understanding something here, I don't see how this works

> ```yaml
>       output:
>         artifacts:
>           - name: main-log
>             path: SOME_MAIN_LOG_PATH
> ```

By using the `.main-logs` approach as per our use case we are accessing the terminal output of the Argo Workflow itself, not some artifact that is written within the container as this seems to suggest.

@agilgur5 - yes we are picking up other artifacts from both steps in our workflows, our ability to access the `.main-logs` in the later step(s) allows us to make decisions based on the terminal output(s) from the earlier step.

Is there some other way to access the Argo Workflow terminal-output (ie `.main-log`) of a step in a later-step that we are not understanding here?

**Comment by agilgur5** [comment]
> @agilgur5 - yes we are picking up other artifacts from both steps in our workflows, our ability to access the `.main-logs` in the later step(s) allows us to make decisions based on the terminal output(s) from the earlier step.

Is this specifically via the [archive logs](https://argoproj.github.io/argo-workflows/configure-archive-logs/) feature?
If so, this isn't mentioned in your issue or explicitly used in the Workflows you provided -- could you also provide your [`workflow-controller-configmap`](https://argoproj.github.io/argo-workflows/workflow-controller-configmap/) and/or your [`artifact-repositories` ConfigMap](https://argoproj.github.io/argo-workflows/configure-artifact-repository/)?
I imagine that you have an archive logs configuration there


> Is there some other way to access the Argo Workflow terminal-output (ie `.main-log`) of a step in a later-step that we are not understanding here?

The documented way of doing this is accessing through [`outputs.result`](https://argoproj.github.io/argo-workflows/walk-through/output-parameters/#result-output-parameter).

As far as I can currently tell, `main-log` seems to be undocumented behavior of the archive logs feature that you're making use of. There is no explicit reference to that in the [entire codebase](https://github.com/search?q=repo%3Aargoproj%2Fargo-workflows%20%22main-log%22&type=code) -- I believe that just happens to be what your archive logs artifact is called rather than a specific keyword that Argo uses

**Comment by ndejong** [comment]
> Is this specifically via the [archive logs](https://argoproj.github.io/argo-workflows/configure-archive-logs/) feature? If so, this isn't mentioned in your issue or explicitly used in the Workflows you provided -- could you also provide your [`workflow-controller-configmap`](https://argoproj.github.io/argo-workflows/workflow-controller-configmap/) and/or your [`artifact-repositories` ConfigMap](https://argoproj.github.io/argo-workflows/configure-artifact-repository/)? I imagine that you have an archive logs configuration there

Yes I see, had not occurred this was a possibility here; yes we use a local minio instance to provide temporary artifact storage in-between steps; indeed the defaults section of our `workflow-controller-configmap` contains a `archiveLogs: true`

Our `workflow-controller-configmap` trimmed down
```yaml
workflowDefaults:
  spec:
    activeDeadlineSeconds: 900
    archiveLogs: true
    securityContext:
      runAsGroup: 2888
      runAsNonRoot: true
      runAsUser: 2888
    serviceAccountName: argo-workflow-sa
    ttlStrategy:
      secondsAfterCompletion: 10800
```

... and our `artifact-repositories` 
```yaml
s3:
  bucket: artifacts
  endpoint: minio.argo.svc.cluster.local:9000
  accessKeySecret:
    name: minio-credentials
    key: accesskey
  secretKeySecret:
    name: minio-credentials
    key: secretkey
```

There are some things that don't quite align though -
* We do not set the `main-logs` name anywhere in our codebase either
* It's curious that the name [`.main-logs`](https://github.com/search?q=repo%3Aargoproj%2Fargo-workflows+%22main-logs%22&type=code) does appear in Argo Workflow codebase for various **_tests** though (NB: the "s" in log"s")
* It feels like the name `.main-logs` is somehow a default (from where?) that gets applied when we set `archiveLogs: true` without supplying a name in `workflow-controller-configmap` as is the case with our setup.

I should also describe then:-
* Our Argo Workflows gets deployed from a [Helm chart](https://artifacthub.io/packages/helm/argo/argo-workflows)
* The string [`main-logs`](https://github.com/search?q=repo%3Aargoproj%2Fargo-helm%20%22main-logs%22&type=code) does not seem to appear in the argo-helm repo either.

We discovered this technique of accessing `main-logs` after noticing it was referenced in the INPUTS/OUTPUTS tab of the related step in the Argo Workflows user interface, and followed that through until we discovered it was available as an artifact - was not aware this is undocumented, it just made sense at the time.
![image](https://github.com/argoproj/argo-workflows/assets/210474/e32a7365-cb2d-49c6-a94d-ab0cc1f5e9d4)

The reason we use this `main-logs` artifact approach is that the parameter based [`outputs.result`](https://argoproj.github.io/argo-workflows/walk-through/output-parameters/#result-output-parameter) approach fails when terminal outputs contain anything binary.

See the updated example below (on v3.4.11) that fails if you uncomment the 2x parameters items below - it seems that the `outputs.result` parameter passing approach will fail with a MESSAGE `cannot finish template replacement because the result was invalid JSON`

```yaml

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: bugreport-20231023a

spec:
  entrypoint: entrypoint-handler

  templates:
    - name: entrypoint-handler
      steps:

        - - name: step1
            template: step1-template

        - - name: step2
            template: step2-template
            arguments:
              artifacts: [ { name: artifact_from_step1, from: "{{ steps.step1.outputs.artifacts.main-logs }}" } ]
              # parameters: [ { name: parameter_from_step1, value: "{{ steps.step1.outputs.result }}" } ]

    - name: step1-template
      container:
        image: debian:stable-slim
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Binary output to STDOUT"
            head -c256 /dev/urandom
            
            echo "Binary output to STDERR"
            >&2 head -c256 /dev/urandom

    - name: step2-template
      inputs:
        artifacts: [ { name: artifact_from_step1, path: "/tmp/artifact_from_step1" } ]
        # parameters: [ { name: parameter_from_step1 } ]
      container:
        image: debian:stable-slim
        command: ["/bin/bash", "-c"]
        args:
          - |
            cat "/tmp/artifact_from_step1"
```

To boil all that down into summary:-
* we stumbled into our `main-logs` artifacts approach because we discovered that we could not safely pass logs from one step to another using the parameter based `outputs.result` approach
* We were concerned that specially crafted log output from step1 passed through to step2 as an input parameter might be able to inject unexpected values in step2, thus the idea of passing the log-file as an artifact reduced that risk and was therefore preferable.
