### ISSUE TITLE
Sub-template memoized workflow doesn't complete

### ISSUE THREAD

**Issue by Joibel** [argoproj/argo-workflows#12118]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

If you memoize a template it can work - see #11612 which is now fixed.
However, if one of your sub-templates memoizes it memoizes correctly but doesn't complete, and the UI is missing parts 

![image](https://github.com/argoproj/argo-workflows/assets/1827156/b7ee7644-cb3e-42ba-99b7-9248be9b935b)

The `theend` pod does run.

The workflow status looks like:
```
status:                                                                                                                                                                                                                                                                          
  artifactGCStatus:                                                                                                                                                                                                                                                              
    notSpecified: true                                                                                                                                                                                                                                                           
  artifactRepositoryRef:                                                                                                                                                                                                                                                         
    artifactRepository: {}                                                                                                                                                                                                                                                       
    default: true                                                                                                                                                                                                                                                                
  conditions:                                                                                                                                                                                                                                                                    
  - status: "False"                                                                                                                                                                                                                                                              
    type: PodRunning                                                                                                                                                                                                                                                             
  finishedAt: null                                                                                                                                                                                                                                                               
  nodes:                                                                                                                                                                                                                                                                         
    memoized-2-5j7xf:                                                                                                                                                                                                                                                            
      children:                                                                                                                                                                                                                                                                  
      - memoized-2-5j7xf-1044738759                                                                                                                                                                                                                                              
      displayName: memoized-2-5j7xf                                                                                                                                                                                                                                              
      finishedAt: null                                                                                                                                                                                                                                                           
      id: memoized-2-5j7xf                                                                                                                                                                                                                                                       
      name: memoized-2-5j7xf                                                                                                                                                                                                                                                     
      phase: Running                                                                                                                                                                                                                                                             
      progress: 1/1                                                                                                                                                                                                                                                              
      startedAt: "2023-11-01T09:02:15Z"                                                                                                                                                                                                                                          
      templateName: start                                                                                                                                                                                                                                                        
      templateScope: local/memoized-2-5j7xf                                                                                                                                                                                                                                      
      type: DAG                                                                                                                                                                                                                                                                  
    memoized-2-5j7xf-1044738759:                                                                                                                                                                                                                                                 
      boundaryID: memoized-2-5j7xf                                                                                                                                                                                                                                               
      children:                                                                                                                                                                                                                                                                  
      - memoized-2-5j7xf-3953594218                                                                                                                                                                                                                                              
      displayName: foo                                                                                                                                                                                                                                                           
      finishedAt: "2023-11-01T09:02:21Z"                                                                                                                                                                                                                                         
      hostNodeName: k3d-k3s-default-server-0                                                                                                                                                                                                                                     
      id: memoized-2-5j7xf-1044738759                                                                                                                                                                                                                                            
      name: memoized-2-5j7xf.foo                                                                                                                                                                                                                                                 
      outputs:                                                                                                                                                                                                                                                                   
        exitCode: "0"                                                                                                                                                                                                                                                            
      phase: Succeeded                                                                                                                                                                                                                                                           
      progress: 1/1                                                                                                                                                                                                                                                              
      resourcesDuration:                                                                                                                                                                                                                                                         
        cpu: 7                                                                                                                                                                                                                                                                   
        memory: 7                                                                                                                                                                                                                                                                
      startedAt: "2023-11-01T09:02:15Z"                                                                                                                                                                                                                                          
      templateName: dothing                                                                                                                                                                                                                                                      
      templateScope: local/memoized-2-5j7xf                                                                                                                                                                                                                                      
      type: Pod                                                                                                                                                                                                                                                                  
    memoized-2-5j7xf-3953594218:                                                                                                                                                                                                                                                 
      boundaryID: memoized-2-5j7xf                                                                                                                                                                                                                                               
      displayName: bar                                                                                                                                                                                                                                                           
      finishedAt: "2023-11-01T09:02:25Z"                                                                                                                                                                                                                                         
      id: memoized-2-5j7xf-3953594218                                                                                                                                                                                                                                            
      inputs:                                                                                                                                                                                                                                                                    
        parameters:                                                                                                                                                                                                                                                              
        - name: message                                                                                                                                                                                                                                                          
          value: alan                                                                                                                                                                                                                                                            
      memoizationStatus:                                                                                                                                                                                                                                                         
        cacheName: diamond-cache                                                                                                                                                                                                                                                 
        hit: true                                                                                                                                                                                                                                                                
        key: alan-hi                                                                                                                                                                                                                                                             
      name: memoized-2-5j7xf.bar                                                                                                                                                                                                                                                 
      outputs:                                                                                                                                                                                                                                                                   
        parameters:                                                                                                                                                                                                                                                              
        - name: url                                                                                                                                                                                                                                                              
          value: https://argo-workflows.company.com/workflows/namepace/memoized-2-66cj8?tab=workflow                                                                                                                                                                             
      phase: Succeeded                                                                                                                                                                                                                                                           
      startedAt: "2023-11-01T09:02:25Z"                                                                                                                                                                                                                                          
      templateName: diamond                                                                                                                                                                                                                                                      
      templateScope: local/memoized-2-5j7xf                                                                                                                                                                                                                                      
      type: DAG                                                                                                                                                                                                                                                                  
    memoized-2-5j7xf-4284107361:                                                                                                                                                                                                                                                 
      boundaryID: memoized-2-5j7xf                                                                                                                                                                                                                                               
      displayName: theend                                                                                                                                                                                                                                                        
      finishedAt: "2023-11-01T09:02:31Z"                                                                                                                                                                                                                                         
      hostNodeName: k3d-k3s-default-server-0                                                                                                                                                                                                                                     
      id: memoized-2-5j7xf-4284107361                                                                                                                                                                                                                                            
      name: memoized-2-5j7xf.theend                                                                                                                                                                                                                                              
      outputs:                                                                                                                                                                                                                                                                   
        exitCode: "0"                                                                                                                                                                                                                                                            
      phase: Succeeded                                                                                                                                                                                                                                                           
      progress: 1/1                                                                                                                                                                                                                                                              
      resourcesDuration:                                                                                                                                                                                                                                                         
        cpu: 7                                                                                                                                                                                                                                                                   
        memory: 7                                                                                                                                                                                                                                                                
      startedAt: "2023-11-01T09:02:25Z"                                                                                                                                                                                                                                          
      templateName: dothing                                                                                                                                                                                                                                                      
      templateScope: local/memoized-2-5j7xf                                                                                                                                                                                                                                      
      type: Pod              
```

### Version

v3.5.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
The same workflow as #12117.

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: memoized-2-
spec:
  entrypoint: start
  arguments:
    parameters:
    - name: message
      value: alan
  templates:
  - name: start
    dag:
      tasks:
        - name: foo
          template: dothing
        - name: bar
          template: diamond
          depends: "foo"
          arguments:
            parameters:
              - name: message
                value: "{{ workflow.parameters.message }}"
        - name: theend
          template: dothing
          depends: "bar"
  - name: diamond
    inputs:
      parameters:
      - name: message
    memoize:
      key: "{{inputs.parameters.message}}"
      maxAge: "600s"
      cache:
        configMap:
          name: diamond-cache
    dag:
      tasks:
        - name: A
          template: dothing
        - name: B
          template: dothing
          depends: "A"
        - name: C
          template: dothing
          depends: "A"
        - name: D
          template: whalesay
          depends: "B && C"
          arguments:
            parameters:
              - name: message
                value: "{{ inputs.parameters.message }}"
    outputs:
        parameters:
          - name: url
            valueFrom:
              expression: |
                'https://argo-workflows.company.com/workflows/namepace/' + '{{workflow.name}}' + '?tab=workflow'
  - name: dothing
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ['sleep 3; echo "Doing a thing"']
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ['sleep 3; echo "Hi {{inputs.parameters.message}}" > /tmp/hello.txt']
    outputs:
      parameters:
      - name: hello
        valueFrom:
          path: /tmp/hello.txt
```
```


### Logs from the workflow controller on second run

```text
time="2023-11-01T09:02:15.582Z" level=info msg="Processing workflow" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.586Z" level=info msg="Updated phase  -> Running" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.586Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.586Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.586Z" level=info msg="DAG node memoized-2-5j7xf initialized Running" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.586Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-4284107361, taskName theend"
time="2023-11-01T09:02:15.586Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-3953594218, taskName bar"
time="2023-11-01T09:02:15.586Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-1044738759, taskName foo"
time="2023-11-01T09:02:15.586Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-1044738759, taskName foo"
time="2023-11-01T09:02:15.586Z" level=info msg="All of node memoized-2-5j7xf.foo dependencies [] completed" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.586Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.587Z" level=info msg="Pod node memoized-2-5j7xf-1044738759 initialized Pending" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.599Z" level=info msg="Created pod: memoized-2-5j7xf.foo (memoized-2-5j7xf-dothing-1044738759)" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.599Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-3953594218, taskName bar"
time="2023-11-01T09:02:15.599Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-4284107361, taskName theend"
time="2023-11-01T09:02:15.599Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-3953594218, taskName bar"
time="2023-11-01T09:02:15.599Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-4284107361, taskName theend"
time="2023-11-01T09:02:15.599Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.599Z" level=info msg=reconcileAgentPod namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:15.606Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=30449 workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.601Z" level=info msg="Processing workflow" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.601Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.601Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=memoized-2-5j7xf-1044738759 old.message= old.phase=Pending old.progress=0/1 workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.601Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-4284107361, taskName theend"
time="2023-11-01T09:02:25.601Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-3953594218, taskName bar"
time="2023-11-01T09:02:25.601Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-3953594218, taskName bar"
time="2023-11-01T09:02:25.602Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-3953594218, taskName bar"
time="2023-11-01T09:02:25.602Z" level=info msg="All of node memoized-2-5j7xf.bar dependencies [foo] completed" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.602Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.609Z" level=info msg="DAG node memoized-2-5j7xf-3953594218 initialized Pending" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.609Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-4284107361, taskName theend"
time="2023-11-01T09:02:25.609Z" level=warning msg="was unable to obtain the node for memoized-2-5j7xf-4284107361, taskName theend"
time="2023-11-01T09:02:25.609Z" level=info msg="All of node memoized-2-5j7xf.theend dependencies [bar] completed" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.609Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.609Z" level=info msg="Pod node memoized-2-5j7xf-4284107361 initialized Pending" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.613Z" level=info msg="Created pod: memoized-2-5j7xf.theend (memoized-2-5j7xf-dothing-4284107361)" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.613Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.613Z" level=info msg=reconcileAgentPod namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.622Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=30479 workflow=memoized-2-5j7xf
time="2023-11-01T09:02:25.628Z" level=info msg="cleaning up pod" action=labelPodCompleted key=default/memoized-2-5j7xf-dothing-1044738759/labelPodCompleted
time="2023-11-01T09:02:35.616Z" level=info msg="Processing workflow" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:35.616Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=memoized-2-5j7xf
time="2023-11-01T09:02:35.616Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=memoized-2-5j7xf-4284107361 old.message= old.phase=Pending old.progress=0/1 workflow=memoized-2-5j7xf
time="2023-11-01T09:02:35.617Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:35.617Z" level=info msg=reconcileAgentPod namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:35.627Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=30509 workflow=memoized-2-5j7xf
time="2023-11-01T09:02:35.632Z" level=info msg="cleaning up pod" action=labelPodCompleted key=default/memoized-2-5j7xf-dothing-4284107361/labelPodCompleted
time="2023-11-01T09:02:45.651Z" level=info msg="Processing workflow" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:45.651Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=memoized-2-5j7xf
time="2023-11-01T09:02:45.651Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=memoized-2-5j7xf
time="2023-11-01T09:02:45.651Z" level=info msg=reconcileAgentPod namespace=default workflow=memoized-2-5j7xf
```
```


### Logs from in your workflow's wait container

```text
Not relevant
```
