### ISSUE TITLE
Workflow status metric is not being set/emitted properly on manual retry/resubmit from UI

### ISSUE THREAD

**Issue by jordantshaw** [argoproj/argo-workflows#12123]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When retrying or resubmitting a workflow with a Failed status manually from the UI the workflows status is not being set correctly and/or emitted correctly in the metrics.

For example, if the workflow fails the status metric is properly emitted reflecting the failed state.  However, when the workflow is retried from the UI and succeeds, the status does not change from a "Failed" state.  

Prometheus metrics as read from the workflow-controller upon workflow failure:
```
> curl -s http://localhost:9090/metrics | grep metrics-test
argo_workflows_status_gauge{name="metrics-test",priority="P3"} 1
```

Prometheus metrics as read from the workflow-controller after UI retry successful run:
```
> curl -s http://localhost:9090/metrics | grep metrics-test
argo_workflows_status_gauge{name="metrics-test",priority="P3"} 1
```

The expected results would be for argo_workflows_status_gauge metric to go back down to 0 after a successful run.  Like this: 
```
> curl -s http://localhost:9090/metrics | grep metrics-test
argo_workflows_status_gauge{name="metrics-test",priority="P3"} 0
```

### Version

v3.5.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: metrics-test-
spec:
  entrypoint: main
  metrics:
    prometheus:        
        - name: status_gauge
          labels:
            - key: name
              value: "metrics-test"
            - key: priority
              value: "P3"
          help: "Gauge of workflow status"
          when: "{{status}} != Succeeded"
          gauge:
            realtime: false
            value: "1"
        - name: status_gauge
          labels:
            - key: name
              value: "metrics-test"
            - key: priority
              value: "P3"
          help: "Gauge of workflow status"
          when: "{{status}} == Succeeded"
          gauge:
            realtime: false
            value: "0"
  arguments:
    parameters:
      - name: exit-code
        value: "1"
  templates:
    - name: main
      inputs:
        parameters:
          - name: exit-code
            value: '{{workflow.parameters.exit-code}}'
      container:
        image: python:alpine3.6
        command: ["python", -c]
        env:
          - name: EXIT_CODE
            value: '{{inputs.parameters.exit-code}}'
        args: ["import os; import sys; exit_code = int(os.environ.get('EXIT_CODE')); sys.exit(exit_code)"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/argo-workflows-workflow-controller | grep metrics-test-tf6gw
time="2023-11-01T19:36:30.998Z" level=info msg="Processing workflow" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:31.002Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:31.002Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:31.002Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:31.002Z" level=info msg="Pod node metrics-test-tf6gw initialized Pending" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:31.002Z" level=error msg="was unable to obtain node for " namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:31.013Z" level=info msg="Created pod: metrics-test-tf6gw (metrics-test-tf6gw)" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:31.013Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:31.013Z" level=info msg=reconcileAgentPod namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:31.024Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=4535668 workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.017Z" level=info msg="Processing workflow" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.019Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.019Z" level=info msg="Pod failed: Error (exit code 1)" displayName=metrics-test-tf6gw namespace=argo pod=metrics-test-tf6gw templateName=main workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.019Z" level=info msg="node changed" namespace=argo new.message="Error (exit code 1)" new.phase=Failed new.progress=0/1 nodeID=metrics-test-tf6gw old.message= old.phase=Pending old.progress=0/1 workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.019Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.019Z" level=info msg=reconcileAgentPod namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.019Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.019Z" level=info msg="Updated message  -> Error (exit code 1)" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.019Z" level=info msg="Marking workflow completed" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.025Z" level=info msg="cleaning up pod" action=deletePod key=argo/metrics-test-tf6gw-1340600742-agent/deletePod
time="2023-11-01T19:36:41.033Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=4535703 workflow=metrics-test-tf6gw
time="2023-11-01T19:36:41.035Z" level=info msg="Queueing Failed workflow argo/metrics-test-tf6gw for delete in 72h0m0s due to TTL"
time="2023-11-01T19:36:46.037Z" level=info msg="cleaning up pod" action=deletePod key=argo/metrics-test-tf6gw/deletePod
time="2023-11-01T19:43:55.107Z" level=info msg="Queueing Failed workflow argo/metrics-test-tf6gw for delete in 71h52m46s due to TTL"
time="2023-11-01T19:44:25.309Z" level=info msg="Processing workflow" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:25.310Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=metrics-test-tf6gw
time="2023-11-01T19:44:25.310Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:25.310Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:25.311Z" level=info msg="Pod node metrics-test-tf6gw initialized Pending" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:25.311Z" level=error msg="was unable to obtain node for " namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:25.323Z" level=info msg="Created pod: metrics-test-tf6gw (metrics-test-tf6gw)" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:25.324Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:25.324Z" level=info msg=reconcileAgentPod namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:25.330Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=4536422 workflow=metrics-test-tf6gw
time="2023-11-01T19:44:35.322Z" level=info msg="Processing workflow" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:35.323Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=metrics-test-tf6gw
time="2023-11-01T19:44:35.323Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=metrics-test-tf6gw old.message= old.phase=Pending old.progress=0/1 workflow=metrics-test-tf6gw
time="2023-11-01T19:44:35.323Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:35.323Z" level=info msg=reconcileAgentPod namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:35.323Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:35.323Z" level=info msg="Marking workflow completed" namespace=argo workflow=metrics-test-tf6gw
time="2023-11-01T19:44:35.328Z" level=info msg="cleaning up pod" action=deletePod key=argo/metrics-test-tf6gw-1340600742-agent/deletePod
time="2023-11-01T19:44:35.332Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=4536456 workflow=metrics-test-tf6gw
time="2023-11-01T19:44:35.332Z" level=info msg="Queueing Succeeded workflow argo/metrics-test-tf6gw for delete in 72h0m0s due to TTL"
time="2023-11-01T19:44:40.336Z" level=info msg="cleaning up pod" action=deletePod key=argo/metrics-test-tf6gw/deletePod
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=metrics-test-tf6gw,workflow.argoproj.io/phase!=Succeeded
No resources found in argo namespace.
```
