### ISSUE TITLE
add Cron Schedule for workflow template

### ISSUE THREAD

**Issue by sabreensalama** [argoproj/argo-workflows#12175]
# Summary
```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: wft-pg-extract-ref-data
spec:
  schedule: {{ .Values.postgres.dataImporter.cronTime | quote }}
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    workflowTemplateRef:
      name: wft-pg-extract-ref-data
-------------------------------------------
example of template
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wft-pg-extract-props-goals
spec:

  entrypoint: pg-extract-props-goals
  serviceAccountName: argo-workflows-pg
  podDisruptionBudget:
    minAvailable: 1

  templates:
  - name: pg-extract-props-goals
    metadata:
      annotations:
        karpenter.sh/do-not-evict: "true"
    nodeSelector:
      node.vodafone.com/lifecycle: "on-demand"
    tolerations:
      - key: "node.vodafone.com/on-demand"
        operator: "Exists"
        effect: "NoSchedule"
    script:
      image: "{{ .Values.postgres.dataExporter.image.registry }}/{{ .Values.postgres.dataExporter.image.repository }}:{{ .Values.postgres.dataExporter.image.tag }}"
      command: [ "/bin/bash" ]
      env:
        - name: PG_CONNECT_ENDPOINT
          value: {{ .Values.postgres.common.pgRdsCluster.connect.endpoint }}
        - name: CONNECT_USER
          valueFrom:
            secretKeyRef:
              name: test
              key: username
      volumeMounts:
        - mountPath: test
          name: temp-pvc

      source: |
        bash main.sh EXTRACT_WRAPPER NBA_EDWH
    outputs:
        artifacts:
          - name: out-art
            path: test
            s3:
              region: "{{ .Values.workflows.common.s3Export.region }}"
              endpoint: "{{ .Values.workflows.common.s3Export.endpoint }}"
              bucket: "{{ .Values.workflows.common.s3Export.bucket }}"
              key: "{{ .Values.workflows.common.s3Export.key }}/campaigngoals/"
            archive:
              none: {}

```

What change needs making?
need to add a schedule attribute to the workflow template  spec the below line
 # schedule: {{ .Values.postgres.dataImporter.cronTime | quote }}

## Use Cases

When would you use this?
I have around 10 tasks with 10 workflow template files and I need to run each one  with a cronjob , currently I should use the cron workflow and for this  I should have another 10 files too , this will make a huge files also I will use more tasks so more files too
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
