### ISSUE TITLE
Overrride for the already set arguments, e.g. inputs inheiritance 

### ISSUE THREAD

**Issue by dkalashnik** [argoproj/argo-workflows#12187]
# Summary

I found the only way to define the template that can be used with default parameters or with some args set in the workflow.
This behavior is needed to create a library with some default args and with multiple layers. Example:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cowsay
spec:
  serviceAccountName: workflow
  templates:
  - name: cowsay
    inputs:
      parameters:
      - name: baseTemplateWithValue
        value: set-in-root-template
      - name: baseTemplateWithoutValue
    container:
      image: docker/whalesay
      command: [cowsay]
      args:
        - "baseTemplateValue: "
        - "{{inputs.parameters.baseTemplateWithValue}}"
        - "baseTemplateWithoutValue: "
        - "{{inputs.parameters.baseTemplateWithoutValue}}"
        - "workflowParametersValue"
        - "{{workflow.parameters.workflowParametersValue}}"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cowsay-specific
spec:
  serviceAccountName: workflow
  templates:
  - name: no-override
    steps:
    - - name: redefine-args
    inputs:
      parameters:
      - name: baseTemplateWithValue
        value: set-in-child-template
      - name: baseTemplateWithoutValue
    steps:
    - - name: redefine-args-step
        templateRef:
          name: cowsay
          template: cowsay
        arguments:
          parameters:
            - name: baseTemplateWithValue
              value: "{{inputs.parameters.baseTemplateWithValue}}"
            - name: baseTemplateWithoutValue
              value: "{{inputs.parameters.baseTemplateWithoutValue}}"
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pass-parameters-through-layers-
spec:
  entrypoint: T
  arguments:
    parameters:
    - name: workflowParametersValue
      value: set-in-workflow
  templates:
  - name: T
    steps:
    - - name: S4-override-layers
        templateRef:
          name: cowsay-specific
          template: redefine-args
        arguments:
          parameters:
            - name: baseTemplateWithValue
              value: set-in-workflow
            - name: baseTemplateWithoutValue
              value: set-in-workflow

      - name: S5-override-single-arg
        templateRef:
          name: cowsay-specific
          template: redefine-args
        arguments:
          parameters:
            - name: baseTemplateWithoutValue
              value: set-in-workflow

      - name: S6-default-values
        templateRef:
          name: cowsay-specific
          template: redefine-args
```

## Use Cases

Merging of the defined args will allow to have this multilayer inheritance without this extra inputs/passing inputs default values syntactic anti-sugar. It is still working, but a little bit messy.
Example that is not working now, but seems logical, main step is `S3`:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cowsay-specific
spec:
  serviceAccountName: workflow
  templates:
  - name: no-override
    steps:
    - - name: no-override-step
        templateRef:
          name: cowsay
          template: cowsay
        arguments:
          parameters:
            - name: baseTemplateWithoutValue
              value: set-in-child-template

  - name: set-args
    steps:
    - - name: set-args-step
        templateRef:
          name: cowsay
          template: cowsay
        arguments:
          parameters:
            - name: baseTemplateWithValue
              value: set-in-child-template
            - name: baseTemplateWithoutValue
              value: set-in-child-template
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cowsay
spec:
  serviceAccountName: workflow
  templates:
  - name: cowsay
    inputs:
      parameters:
      - name: baseTemplateWithValue
        value: set-in-root-template
      - name: baseTemplateWithoutValue
    container:
      image: docker/whalesay
      command: [cowsay]
      args:
        - "baseTemplateValue: "
        - "{{inputs.parameters.baseTemplateWithValue}}"
        - "baseTemplateWithoutValue: "
        - "{{inputs.parameters.baseTemplateWithoutValue}}"

        - "workflowParametersValue"
        - "{{workflow.parameters.workflowParametersValue}}"
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pass-parameters-through-layers-
spec:
  entrypoint: T
  arguments:
    parameters:
    - name: workflowParametersValue
      value: set-in-workflow
  templates:
  - name: T
    steps:
    - - name: S1-no-override
        templateRef:
          name: cowsay-specific
          template: no-override

      - name: S2-override-template
        templateRef:
          name: cowsay-specific
          template: set-args

      - name: S3-override-workflow
        templateRef:
          name: cowsay-specific
          template: set-args
        arguments:
          parameters:
            - name: baseTemplateWithValue
              value: set-in-workflow
            - name: baseTemplateWithoutValue
              value: set-in-workflow

```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
