### ISSUE TITLE
choices from an enum of a workflow parameter disappear in a resubmit run

### ISSUE THREAD

**Issue by shiraOvadia** [argoproj/argo-workflows#12195]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

What happens:
When I resubmit a certain workflow and choose to override the parameters, a parameter which is configured with a list of possible choices using "enum", becomes a free regular parameter in the resubmit run.

What I expect to happen:
when I resubmit a workflow, a parameter defined with an enum set of values preserves its enum list in the resubmit process, and no other values are allowed.

### Version

3.5.0, 3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-with-enum-values-
spec:
  entrypoint: argosay
  arguments:
    parameters:
      - name: message
        value: yes
        enum:
          - yes
          - no
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        image: docker/whalesay:latest
        command: [ cowsay ]
        args: [ "{{inputs.parameters.message}}" ]
```

### Logs from the workflow controller

```text
Irrelevant
```

### Logs from in your workflow's wait container

```text
Irrelevant
```
