### ISSUE TITLE
`mode: 0755` with "kubectl apply" -> `mode: 493` with the UI

### ISSUE THREAD

**Issue by dahnyou** [argoproj/argo-workflows#12205]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

From this example: 
https://github.com/argoproj/argo-workflows/blob/master/examples/arguments-artifacts.yaml

If you create a "WorkflowTemplate" in the UI, the `mode: 0755` is interpreted as a decimal -> `755` and the chmod is incorrect.
If you create a "WorkflowTemplate" and do a `kubectl apply`, the octal 0755 will be displayed as `493` as a decimal in the UI. 

Conclusion: modifying the `mode` in the UI will result to incorrect permissions. The mapping is incorrect.

![image](https://github.com/argoproj/argo-workflows/assets/132251349/32480be6-519a-4339-9e72-1def79b036c0)

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  generateName: arguments-artifacts-
spec:
  entrypoint: kubectl-input-artifact
  arguments:
    artifacts:
    - name: kubectl
      http:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl

  templates:
  - name: kubectl-input-artifact
    inputs:
      artifacts:
      - name: kubectl
        path: /usr/local/bin/kubectl
        mode: 0755
    container:
      image: debian:9.4
      command: [sh, -c]
      args: ["kubectl version"]
```

### Logs from the workflow controller

```text
not needed
```

### Logs from in your workflow's wait container

```text
not needed
```
