### ISSUE TITLE
Unable to modify parameters when resuming a DAG

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#12207]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Expect that we could modify parameters when resuming a DAG. However, we get the following error:

```
{"code":13,"message":"cannot set output parameters because node is not expecting any raw parameters"}: cannot set output parameters because node is not expecting any raw parameters
```

It appears that this problem is specific to a dag since suspend works fine with steps template.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  generateName: suspend-template-
  namespace: example-workflow-namespace
  labels:
    example: 'true'
spec:
  entrypoint: suspend
  templates:
  - name: suspend
    dag:
      tasks:
      - name: test-suspend-workflow
        template: test-suspend-workflow-for-duration
        arguments:
          parameters: [{name: duration, value: "10m"}]
      - name: release
        template: whalesay
        dependencies: [test-suspend-workflow]

  - inputs:
      parameters:
      - name: duration
    name: test-suspend-workflow-for-duration
    suspend:
      duration: '{{ inputs.parameters.duration }}'

  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
```
```


### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
