### ISSUE TITLE
v3.5.1 only works in / endpoint BASE_HREF

### ISSUE THREAD

**Issue by gabrielfsousa** [argoproj/argo-workflows#12217]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

blank page when using different BASE_HREF

### Version

v3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
...
    targetMemoryUtilizationPercentage: 50
  baseHref: /argowf/
  clusterWorkflowTemplates:
...

error in chrome console:
Uncaught SyntaxError: Unexpected token
```

### Logs from the workflow controller

```text
no errors in logs
```

### Logs from in your workflow's wait container

```text
no errors in logs
```
