### ISSUE TITLE
Resubmit: Templates in metrics are pre-expanded

### ISSUE THREAD

**Issue by Joibel** [argoproj/argo-workflows#12242]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Resubmitting a workflow with top level metric templates submits them pre-expanded.

Note the difference between the workflow name and the `key: name` in the yaml here on the retry.
![image](https://github.com/argoproj/argo-workflows/assets/1827156/25641060-9132-4ca3-ae4a-68805fbaa815)

Fundamentally I think these are templated permanently in the original workflow run, so the fact they were a templated value isn't present in the workflow object which is then retried. 

I am happy for someone else to supply a fix here.

### Version

3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: metrics-example-
spec:
  metrics:
    prometheus:
      - name: result_counter
        help: "Count of workflow execution by result status"
        labels:
          - key: status
            value: "{{status}}"
          - key: name
            value: "{{workflow.name}}"
          - key: job_name
            value: "foo"
        counter:
          value: "1"
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: a
            template: whalesay
    - name: whalesay
      container:
        image: alpine
        command:
          - sh
          - -c
          - |
            echo "I'm just here to look pretty"
```

### Logs from the workflow controller

```text
Nothing to see here
```

### Logs from in your workflow's wait container

```text
Irrelevant
```
