### ISSUE TITLE
'fair/roundrobin' scheduler based on occurrences of a parameter

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#12253]
workflows can have input parameters ie a key from a json such as
```yaml
spec:
  # invoke the wf template with argument from argo-events json sqs event source
  # to the tablename parameter
  entrypoint: whalesay
  arguments:
    parameters:
    - name: tablename
      value: {{...some_value_from_sqs...}}
```

current issue i see is that argoworkflows scheduler is quite static and based on time wf received and a priority tag in the yaml that the submitter of the wf sets only (along with mutex/semaphore, which i've raised about in other issues, especially being blocked by parallelism setting leading to much less than expected number of wfs really running). this leads to noisy neighbour issue where if 1000s of wfs are submitted with the parameter of tablename=tableABC just seconds before a wf for tablename=tableXYZ is submitted then the wf for XYZ is essentially blocked (pending for too long).....taking the example further the number of tables are random, with potentially never before seen table names. What would really help is an option to make the argowf scheduler choose to set wfs to 'running' based on the least common wfs already running, ie if there is already 2 ABC running don't start a 3rd ABC or a 4th ABC from the pending queue just because they were submitted earlier but instead look through the queue to consider any other table (ie for a DEF or GHI table or any non-ABC) and set them to 'running' first before choosing to set the 3rd/4th ABCs to running
