### ISSUE TITLE
Better support for webHDFS artifacts (e.g. up/downloading unarchived directories)

### ISSUE THREAD

**Issue by alexdittmann** [argoproj/argo-workflows#12252]
# Summary

Argo workflows currently only has partial webHDFS support via HTTP artifacts. It would be nice to have a better/full support, e.g. also allow up/downloading of unarchived directories.

## Use Cases

In argo workflows, webHDFS support is currently realized via HTTP artifacts. See [here](https://github.com/argoproj/argo-workflows/blob/master/examples/webhdfs-input-output-artifacts.yaml) for an example workflow.
However, the current implementation does not offer all the functionality that webHDFS provides.
For example, it does not support workflows with unarchived directories being uploaded as output artifacts, i.e. when using the `archive: none: {}` option. In that case, the workflow will fail with an error like `Put \"http://httpbin:9100/put\": read /tmp/argo/outputs/artifacts/my-art: is a directory`, because internally the HTTP artifact driver will just try to upload it as a single file.
<details>
<summary>See an example of such a failing workflow</summary>

```yaml
# can be run as an e2e test similar to the other http artifact e2e tests
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-artifact-http-
spec:
  entrypoint: main
  templates:
  - name: main
    outputs:
      artifacts:
      - name: my-art
        path: /my-artifact
        http:
          url: http://httpbin:9100/put
        archive:  # <------------ this leads to failure
          none: {}
    container:
      image: argoproj/argosay:v2
      command: [sh, -c]
      args: ["mkdir /my-artifact && echo testdata > /my-artifact/my-file"]
```
</details>

However, from a webHDFS perspective this could be easily supported by uploading the files in that directory individually. 
The downloading of an (unarchived) folder from a remote webHDFS URL does not work either right now. For this, the artifact driver would need to know if the remote URL points to a single file or a directory, and in the latter case download the whole directory.  Again, from a webHDFS perspective this would be possible with the [webHDFS LISTSTATUS operation](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/WebHDFS.html#List_a_Directory).
Since webHDFS provides the functionality for up/downloading of unarchived directories as artifacts, it would be nice to have this supported in argo as well.

From an implementation point of view, we see two possibilities of achieving this: either extend the current HTTP artifact logic to allow special handling for certain APIs like webHDFS, or introduce a new webHDFS artifact type for that purpose. 
In a [slack message](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1700463409099429?thread_ts=1700235520.113979&cid=C01QW9QSSSK) I also got to know that argo generally wants to limit additions of new features and go more towards a plugin approach.

My team would like to do such a contribution, but we would also like to know whether such a contribution would be accepted or not before.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
