### ISSUE TITLE
child steps template with outputs breaks execution of the parent steps template

### ISSUE THREAD

**Issue by ivancili** [argoproj/argo-workflows#12286]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Okay, so this is a weird one.

If you run the workflow I provided below, you'll see that `step1`, which is supposed to trigger template `t2`, never shows up in the UI. The workflow gets marked as successful, and after inspecting the workflow status manually using kubectl, I can see that `step1` did get executed, but it is not visible in the UI. This might not be a bug in the UI since the controller could be doing something wrong, and the UI follows along. I don't have enough knowledge about internals to know right away.

This only happens when `step0` calls another StepsTemplate that has outputs declared (in this case it is `t1`). When I remove outputs from `t1` it works, the `step1` does show up in the UI. If `step0` calls `t2` it works as well.

<details>
<summary>Workflow that does not work - step1 never shows up in the UI</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
  labels:
    test: test
spec:
  entrypoint: t0
  templates:
    - name: t0
      steps:
        - - name: step0
            template: t1
        - - name: step1
            template: t2
    - name: t1
      outputs:
        parameters:
          - name: dummy
            valueFrom:
              expression: "1"
      steps:
        - - name: step2
            template: t2
    - name: t2
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo this is t2"]
```
</details>

<details>
<summary>How the UI looks like</summary>
<img width="132" alt="case1_doesnt_work" src="https://github.com/argoproj/argo-workflows/assets/16418251/a8063513-5ca2-41a4-a256-dd7ce947fa73">
</details>

<details>
<summary>Workflow that does work - step1 shows up in the UI (outputs from t1 are removed)</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
  labels:
    test: test
spec:
  entrypoint: t0
  templates:
    - name: t0
      steps:
        - - name: step0
            template: t1
        - - name: step1
            template: t2
    - name: t1
      # outputs:
      #   parameters:
      #     - name: dummy
      #       valueFrom:
      #         expression: "1"
      steps:
        - - name: step2
            template: t2
    - name: t2
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo this is t2"]
```
</details>

<details>
<summary>How the UI looks like</summary>
<img width="138" alt="case2_works" src="https://github.com/argoproj/argo-workflows/assets/16418251/ecfbb3d9-2fcc-47c6-b0b4-c417dcc16e36">
</details>

I was getting around this issue https://github.com/argoproj/argo-workflows/issues/12283 by declaring dummy outputs, but then I noticed the bug I described above.

### Version

v3.5.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
  labels:
    test: test
spec:
  entrypoint: t0
  templates:
    - name: t0
      steps:
        - - name: step0
            template: t1
        - - name: step1
            template: t2
    - name: t1
      outputs:
        parameters:
          - name: dummy
            valueFrom:
              expression: "1"
      steps:
        - - name: step2
            template: t2
    - name: t2
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo this is t2"]
```

### Logs from the workflow controller

```text
-
```

### Logs from in your workflow's wait container

```text
-
```
