### ISSUE TITLE
template level exit handler has no access to step status when referencing template with no outputs

### ISSUE THREAD

**Issue by ivancili** [argoproj/argo-workflows#12283]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Hi, I ran into issues due to [this line](https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/exit_handler.go#L36) when setting up an exit handler for a step in my workflow. When the referenced template has no outputs, this line will evaluate to false, and the exit handler won't have access to any parameters from the `scopeMap`. I need access to `{{steps.<step-name>.status}}`, which is technically available in the `scopeMap`, but because my template has no outputs it won't be resolved. See examples below.

The fix is to move the `outputs != nil` check to `resolveExitTmplArgument` function and adjust the behavior there. I can create a PR, but it will be next week at the earliest.

<details>
<summary>Workflow that does not work (check exit handler logs):</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
  labels:
    test: test
spec:
  entrypoint: t0
  templates:
    - name: t0
      steps:
        - - name: step0
            template: t1
            hooks:
              exit:
                template: t3
                arguments:
                  parameters:
                    - name: status
                      value: "{{steps.step0.status}}"
    - name: t1
      steps:
        - - name: step1
            template: t2
    - name: t2
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo this is t2"]
    - name: t3
      inputs:
        parameters:
          - name: status
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo hook status {{inputs.parameters.status}}"]
```
</details>

<details>
<summary>Workflow that does work after adding a dummy output (check exit handler logs):</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
  labels:
    test: test
spec:
  entrypoint: t0
  templates:
    - name: t0
      steps:
        - - name: step0
            template: t1
            hooks:
              exit:
                template: t3
                arguments:
                  parameters:
                    - name: status
                      value: "{{steps.step0.status}}"
    - name: t1
      outputs:
        parameters:
          - name: dummy
            valueFrom:
              expression: "1"
      steps:
        - - name: step1
            template: t2
    - name: t2
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo this is t2"]
    - name: t3
      inputs:
        parameters:
          - name: status
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo hook status {{inputs.parameters.status}}"]
```
</details>

### Version

3.5.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
  labels:
    test: test
spec:
  entrypoint: t0
  templates:
    - name: t0
      steps:
        - - name: step0
            template: t1
            hooks:
              exit:
                template: t3
                arguments:
                  parameters:
                    - name: status
                      value: "{{steps.step0.status}}"
    - name: t1
      steps:
        - - name: step1
            template: t2
    - name: t2
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo this is t2"]
    - name: t3
      inputs:
        parameters:
          - name: status
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo hook status {{inputs.parameters.status}}"]
```

### Logs from the workflow controller

```text
-
```

### Logs from in your workflow's wait container

```text
-
```
