### ISSUE TITLE
Inconsistencies execution to apply resources

### ISSUE THREAD

**Issue by aarnaud** [argoproj/argo-workflows#12319]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Random success or failure to apply resources with Argo Workflow.  It's seem the service account isn't always mounted.

Error rate is near 1/5 on my cluster. 

```
time="2023-12-05T02:50:09 UTC" level=info msg="Loading manifest to /tmp/manifest.yaml"
time="2023-12-05T02:50:09 UTC" level=info msg="kubectl apply -f /tmp/manifest.yaml -o json"
error: You must be logged in to the server (the server has asked for the client to provide credentials)
time="2023-12-05T02:50:10 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```

### Version

v3.5.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-with-pvc-
spec:
  serviceAccountName: default
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    steps:
    - - name: create-volume
        template: create-volume
        arguments:
          parameters:
          - name: targetName
            value: "test"

  - name: create-volume
    inputs:
      parameters:
        - name: targetName
    resource:
      action: apply
      setOwnerReference: false
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: {{inputs.parameters.targetName}}
        spec:
          accessModes: ['ReadWriteOnce']
          resources:
            requests:
              storage: '100Gi'
    outputs:
      parameters:
        - name: pvc-name
          valueFrom:
            jsonPath: '{.metadata.name}'
```

### Logs from the workflow controller

```text
ime="2023-12-05T02:49:18.689Z" level=info msg="Processing workflow" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.691Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.691Z" level=info msg="Updated phase  -> Running" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.691Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.691Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.691Z" level=info msg="Steps node build-with-pvc-mlr4g initialized Running" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.691Z" level=info msg="StepGroup node build-with-pvc-mlr4g-2611829741 initialized Running" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.691Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.691Z" level=info msg="Pod node build-with-pvc-mlr4g-576609390 initialized Pending" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.789Z" level=info msg="Created pod: build-with-pvc-mlr4g[0].create-volume (build-with-pvc-mlr4g-create-volume-576609390)" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.789Z" level=info msg="Workflow step group node build-with-pvc-mlr4g-2611829741 not yet completed" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.789Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.789Z" level=info msg=reconcileAgentPod namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:18.850Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=15856588 workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="Processing workflow" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="Pod failed: Error (exit code 1)" displayName=create-volume namespace=default pod=build-with-pvc-mlr4g-create-volume-576609390 templateName=create-volume workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="node changed" namespace=default new.message="Error (exit code 1)" new.phase=Failed new.progress=0/1 nodeID=build-with-pvc-mlr4g-576609390 old.message= old.phase=Pending old.progress=0/1 workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="Step group node build-with-pvc-mlr4g-2611829741 deemed failed: child 'build-with-pvc-mlr4g-576609390' failed" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="node build-with-pvc-mlr4g-2611829741 phase Running -> Failed" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="node build-with-pvc-mlr4g-2611829741 message: child 'build-with-pvc-mlr4g-576609390' failed" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="node build-with-pvc-mlr4g-2611829741 finished: 2023-12-05 02:49:28.790695164 +0000 UTC" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="step group build-with-pvc-mlr4g-2611829741 was unsuccessful: child 'build-with-pvc-mlr4g-576609390' failed" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="Outbound nodes of build-with-pvc-mlr4g-576609390 is [build-with-pvc-mlr4g-576609390]" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="Outbound nodes of build-with-pvc-mlr4g is [build-with-pvc-mlr4g-576609390]" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="node build-with-pvc-mlr4g phase Running -> Failed" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="node build-with-pvc-mlr4g message: child 'build-with-pvc-mlr4g-576609390' failed" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="node build-with-pvc-mlr4g finished: 2023-12-05 02:49:28.790734149 +0000 UTC" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg=reconcileAgentPod namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="Updated phase Running -> Failed" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="Updated message  -> child 'build-with-pvc-mlr4g-576609390' failed" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.790Z" level=info msg="Marking workflow completed" namespace=default workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.796Z" level=info msg="cleaning up pod" action=deletePod key=default/build-with-pvc-mlr4g-1340600742-agent/deletePod
time="2023-12-05T02:49:28.838Z" level=info msg="Workflow update successful" namespace=default phase=Failed resourceVersion=15856706 workflow=build-with-pvc-mlr4g
time="2023-12-05T02:49:28.843Z" level=info msg="cleaning up pod" action=labelPodCompleted key=default/build-with-pvc-mlr4g-create-volume-576609390/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
time="2023-12-05T02:50:09.588Z" level=info msg="Starting Workflow Executor" version=v3.5.2
time="2023-12-05T02:50:09.591Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-12-05T02:50:09.591Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=default podName=build-with-pvc-mlr4g-create-volume-576609390 template="{\"name\":\"create-volume\",\"inputs\":{\"parameters\":[{\"name\":\"targetName\",\"value\":\"test\"}]},\"outputs\":{\"parameters\":[{\"name\":\"pvc-name\",\"valueFrom\":{\"jsonPath\":\"{.metadata.name}\"}}]},\"metadata\":{},\"resource\":{\"action\":\"apply\",\"manifest\":\"apiVersion: v1\\nkind: PersistentVolumeClaim\\nmetadata:\\n  name: test\\nspec:\\n  accessModes: ['ReadWriteOnce']\\n  resources:\\n    requests:\\n      storage: '100Gi'\\n\"}}" version="&Version{Version:v3.5.2,BuildDate:2023-11-27T18:24:31Z,GitCommit:5b6ad2be163ecd3f0251a931ab84dba3c6085ad2,GitTag:v3.5.2,GitTreeState:clean,GoVersion:go1.21.4,Compiler:gc,Platform:linux/amd64,}"
time="2023-12-05T02:50:09.591Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
time="2023-12-05T02:50:09.591Z" level=info msg="kubectl apply -f /tmp/manifest.yaml -o json"
error: You must be logged in to the server (the server has asked for the client to provide credentials)
time="2023-12-05T02:50:10.561Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```

**Comment by terrytangyuan** [comment]
Can you check the pod to see if it's indeed because of the missing SA?

**Comment by aarnaud** [comment]
I compared a successful pod vs failure pod both have the service account present in the ‘describe pod‘ and both have the SA mount point too in the descriptions.

**Comment by aarnaud** [comment]
I can also reproduce with :
```
  - name: create-volume
    inputs:
      parameters:
        - name: targetName
    container:
      image: bitnami/kubectl:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
            cat <<EOF | kubectl apply -f -
            apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: test
            spec:
              accessModes: [ 'ReadWriteOnce' ]
              resources:
                requests:
                  storage: '100Gi'
            EOF
```

but adding `sleep 5;` seem to solve the issue so it seem to be a timing issue
