### ISSUE TITLE
Workflow-list links unable to render namespace

### ISSUE THREAD

**Issue by dmarquez-splunk** [argoproj/argo-workflows#12322]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Unsure if this is a bug or by design or whether to label this as an enhancement or bug but since archived workflow menu item was removed, I'd like to add a workflow-list link that shows only archived workflows for the current selected namespace. I am unable to achieve this because namespace is not rendered by argo when using `{metadata.namespace}` at the workflow-list scope. It would be nice to enhance workflow-list rendering to include the current selected namespace. When I use `${metadata.namespace}` it does not get rendered and shows as `{metadata.namespace}` in the UI.

The link I have configured for this:
```yaml
 name: Archived Workflows
 scope: workflow-list
 url: https://<argo-host>/workflows/${metadata.namespace}?&label=workflows.argoproj.io%2Fworkflow-archiving-status%3DArchived
```

What I see in the UI:
![Screenshot 2023-12-05 at 11 45 22 AM](https://github.com/argoproj/argo-workflows/assets/105759482/16362f42-6bf3-481a-a49a-b62968799c57)

What I expect to see is the currently selected namespace used when clicking on the "Archived Workflows" link

### Version

v3.5.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
