### ISSUE TITLE
Large workflow support

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo-workflows#1233]
FEATURE REQUEST:

What would be the best way to run an Argo workflow that would involve a million containers? 

It seems that there would not be enough space in the Argo status spec to hold the information about all the PODs. 

What would be the best way to accomplish this?  

I am thinking that we could have a top level Argo workflow that launches multiple Argo workflows that run independently of the first one. What do you think?

**Comment by dtaniwaki** [comment]
I think having Template CRD and including it in Workflow is good. We can also bind variables like many template engines can do. Also it’s possible to nest templates.

e.g. in Workflow
```
templates:
- name: foo
  include: template_name_1
  vars:
    x: 1
- name: bar
  include: template_name_2
```

**Comment by xianlubird** [comment]
@dtaniwaki So all of theses workflow will use the same Workflow CRD?   Will they be split into multi small workflow?

Maybe this a great feature to hold very large workflow.

**Comment by Ark-kun** [comment]
```
  - name: foobar
    steps:
    - - include tmpl2.foo
    - - include tmpl2.bar
```

Maybe it's better to have template references (referencing external files) like this:

```
  - name: foobar
    steps:
    - - templateRef:
          url: https://.../bar.template.yaml
    - - templateRef:
          file: ./bar.template.yaml
```
