### ISSUE TITLE
Failed to resolve `{{workflow.failures}}` in exit handler

### ISSUE THREAD

**Issue by galoniz** [argoproj/argo-workflows#12330]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

according to the documentation here: https://argoproj.github.io/argo-workflows/variables/#exit-handler

workflow.failures supposed to be available to use, but it isnt. i tried to submit a workflow template and got the following: `templates.send-slack: failed to resolve {{ workflow.failures.message }}`

### Version

v3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# An exit handler is a template reference that executes at the end of the workflow
# irrespective of the success, failure, or error of the primary workflow. To specify
# an exit handler, reference the name of a template in 'spec.onExit'.
# Some common use cases of exit handlers are:
# - sending notifications of workflow status (e.g. e-mail/slack)
# - posting the pass/fail status to a webhook result (e.g. github build result)
# - cleaning up workflow artifacts
# - resubmitting or submitting another workflow
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: exit-handlers-
spec:
  entrypoint: intentional-fail
  onExit: exit-handler
  templates:
  # primary workflow template
  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]

  # exit handler related templates
  # After the completion of the entrypoint template, the status of the
  # workflow is made available in the global variable {{workflow.status}}.
  # {{workflow.status}} will be one of: Succeeded, Failed, Error
  - name: exit-handler
    steps:
    - - name: notify
        template: send-email
      - name: celebrate
        template: celebrate
        when: "{{workflow.status}} == Succeeded"
      - name: cry
        template: cry
        when: "{{workflow.status}} != Succeeded"
  - name: send-email
    container:
      image: alpine:latest
      command: [sh, -c]
      # Tip: {{workflow.failures}} is a JSON list. If you're using bash to read it, we recommend using jq to manipulate
      # it. For example:
      #
      # echo "{{workflow.failures}}" | jq -r '.[] | "Failed Step: \(.displayName)\tMessage: \(.message)"'
      #
      # Will print a list of all the failed steps and their messages. For more info look up the jq docs.
      # Note: jq is not installed by default on the "alpine:latest" image, however it can be installed with "apk add jq"
      args: ["echo send e-mail: {{workflow.name}} {{workflow.status}} {{workflow.duration}}. Failed steps {{workflow.failures}}"]
  - name: celebrate
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo hooray!"]
  - name: cry
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo boohoo!"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by galoniz** [comment]
the actual workflow template that fails (i changed the image because its irrelevant to the issue and its private:
`apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: send-slack
spec:
  arguments:
    parameters:
      - name: env
        value: "production"
      - name: region
        value: "us-east-1"
  templates:
  - name: send-slack
    volumes:
      - name: slack-send-configmap-payload
        configMap:
          name: slack-send-configmap-payload
    inputs:
      parameters:
      - name: env
      - name: region
    container:
      image: private-repo/send-slack:test
      imagePullPolicy: Always
      volumeMounts:
        - name: slack-send-configmap-payload
          mountPath: /config
      env:
      - name: SLACK_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: viktor-slack-token
            key: token
      - name: WORKFLOW_NAME
        value: "{{workflow.name}}"
      - name: SUCCESS
        value: "{{workflow.status}}"
      - name: DURATION
        value: "{{workflow.duration}}"
      - name: NAMESPACE
        value: "{{workflow.namespace}}"
      - name: ENV
        value: "{{inputs.parameters.env}}"
      - name: REGION
        value: "{{inputs.parameters.region}}"
      - name: FAILURES
        value: "{{workflow.namespace}}"`

**Comment by Joibel** [comment]
Neither your workflow nor template have `{{ workflow.failures.message }}` in them as you've pasted them in here.

To be clear `{{ workflow.failures.message }}` should not work either, workflows doesn't work as jq, you're expected to slice up your json inside a container, not expect workflows to do it for you.

**Comment by galoniz** [comment]
thanks for the reply @Joibel . {{ workflow.failures.message }} doesn't work for me either. 
can you share an example how should it be used? because it doesn't work in my case

**Comment by lionelnicolas** [comment]
I have the same `Failed to resolve {{workflow.failures}}` issue after upgrading to v3.5.2. Using v3.4.11 works fine.

```
Failed: invalid spec: templates.notify-ended templates.notify-ended: failed to resolve {{ workflow.failures }}
```


```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-debug
spec:
  entrypoint: entrypoint-debug

  hooks:
    exit:
      template: notify-ended

(...)

  templates:
    - name: notify-ended
      container:
        image: "{{ workflow.parameters.docker_registry }}/{{ workflow.parameters.docker_repository }}:{{ workflow.parameters.docker_tag }}"
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Prepare notification payload
            echo '{{ workflow.parameters.json_body }}' >/tmp/notification.body.json
            echo '{{ workflow.failures }}' >/tmp/notification.failures.quoted
            cat /tmp/notification.failures.quoted
(...)
```

**Comment by lionelnicolas** [comment]
Just tried v3.5.4 and the issue still occurs.

**Comment by lionelnicolas** [comment]
If that's helpful, the first failing release for me is `v3.4.12`. So, `v3.4.11` works and `v3.4.12` shows the `failed to resolve {{ workflow.failures }}` issue.

https://github.com/argoproj/argo-workflows/compare/v3.4.11...v3.4.12

**Comment by eduardodbr** [comment]
@galoniz I tested the example that you provided and it works fine, please describe the issue that you are facing.

@lionelnicolas @Anton-Sagurov  I was able to reproduce your error. The issue is caused by `workflow.failures` being set only when using `onExit` but not when using `hooks: exit:`. 

I couldn't find which PR created this regression but I think I can create a simple fix.

**Comment by agilgur5** [comment]
> If that's helpful, the first failing release for me is `v3.4.12`. So, `v3.4.11` works and `v3.4.12` shows the `failed to resolve {{ workflow.failures }}` issue.
> 
> [v3.4.11...v3.4.12](https://github.com/argoproj/argo-workflows/compare/v3.4.11...v3.4.12)

> I couldn't find which PR created this regression but I think I can create a simple fix.

This sounds like it was due to #11781, which fixed a validation miss on templates with whitespace in them, which then revealed some other bugs hiding behind that. Notably the problematic Workflows given above all use `{{ workflow.failures }}` with whitespace as opposed to `{{workflow.failures}}`, so they would have bypassed validation prior to 3.4.12

**Comment by eduardodbr** [comment]
> > If that's helpful, the first failing release for me is `v3.4.12`. So, `v3.4.11` works and `v3.4.12` shows the `failed to resolve {{ workflow.failures }}` issue.
> > [v3.4.11...v3.4.12](https://github.com/argoproj/argo-workflows/compare/v3.4.11...v3.4.12)
> 
> > I couldn't find which PR created this regression but I think I can create a simple fix.
> 
> This sounds like it is due to #11781, which fixed a validation miss on templates with whitespace in them, which then revealed some other bugs hiding behind that. Notably the problematic Workflows given above all use `{{ workflow.failures }}` with whitespace as opposed to `{{workflow.failures}}`, so they would have bypassed validation prior to 3.4.12

nice catch!  
I opened a PR to fix the issue,  `{{workflow.failures}}` should be available on `onExit` and on exit hooks.
However, PR https://github.com/argoproj/argo-workflows/pull/8066 made `workflow.status` available in all templates, maybe we could do it for `workflow.failures` as well, since both are only mentioned in exit handler documentation.

**Comment by mark-huynh** [comment]
still an issue in v3.6.0

**Comment by mark-huynh** [comment]
more specifically this seems to happen when specifying onExit within a template 
```
...
  templates:

    - name: test-exithook-failure-message
      dag:
        tasks:
          - name: intentional-fail
            inline:
              container:
                image: alpine:latest
                command: [sh, -c]
                args: ["echo intentional failure; exit 1"]
            onExit: exit-handler

    - name: exit-handler
      steps:
      - - name: notify
          template: send-email

    - name: send-email
      container:
        image: alpine:latest
        command: [sh, -c]
        # Tip: {{workflow.failures}} is a JSON list. If you're using bash to read it, we recommend using jq to manipulate
        # it. For example:
        #
        # echo "{{workflow.failures}}" | jq -r '.[] | "Failed Step: \(.displayName)\tMessage: \(.message)"'
        #
        # Will print a list of all the failed steps and their messages. For more info look up the jq docs.
        # Note: jq is not installed by default on the "alpine:latest" image, however it can be installed with "apk add jq"
        args: ["echo send e-mail: {{workflow.name}} {{workflow.status}} {{workflow.duration}}. Failed steps {{workflow.failures}}"]
```

will cause a `(WorkflowTemplate): rpc error: code = InvalidArgument desc = templates.exit-handler templates.exit-handler.steps[0].notify templates.send-email: failed to resolve {{workflow.failures}}`

but when specifying 

```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: xxx
spec:
  onExit: exit-handler
...
  templates:
    - name: test-exithook-failure-message
    ...
```

error is not there
