### ISSUE TITLE
Cannot use reference to `outputs.parameters` outside of `withItems`/`withParams`

### ISSUE THREAD

**Issue by elliotgunton** [argoproj/argo-workflows#12357]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Running a Dag/Steps with a template ref, I want to get all the parameters using this syntax:
```
'{{tasks.a.outputs.parameters}}'
```
referenced [here](https://argoproj.github.io/argo-workflows/variables/#steps-templates) in the docs.

However, upon submission, I get the error:
```
$ argo submit use-params-wt.yaml -n argo --watch
FATA[2023-12-13T15:04:29.535Z] Failed to submit workflow: rpc error: code = InvalidArgument desc = templates.dag.tasks.b failed to resolve {{tasks.a.outputs.parameters}} 

$ argo version
argo: v3.5.2
  BuildDate: 2023-11-27T19:06:22Z
  GitCommit: 5b6ad2be163ecd3f0251a931ab84dba3c6085ad2
  GitTreeState: clean
  GitTag: v3.5.2
  GoVersion: go1.21.4
  Compiler: gc
  Platform: linux/amd64
```

Compared to accessing parameters in the templateref args directly (e.g. `'{{tasks.a.outputs.parameters.param-1}}'`), which works fine. See repro example below

### Version

v3.4.4 and latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

WorkflowTemplate to use:
```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: generate-params
  namespace: argo
spec:
  entrypoint: output-params
  templates:
    - container:
        command:
          - cowsay
        image: docker/whalesay
      name: output-params
      outputs:
        parameters:
          - name: param-1
            value: '42'
          - name: param-2
            value: test param
```

Workflow referencing the workflow template:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-ref-param-passing-
spec:
  entrypoint: dag
  templates:
  - container:
      args:
      - '{{inputs.parameters.all-params}}'
      command:
      - cowsay
      image: docker/whalesay
    inputs:
      parameters:
      - name: all-params
    name: in
  - dag:
      tasks:
      - name: a
        templateRef:
          name: generate-params
          template: output-params
          clusterScope: false
      - arguments:
          parameters:
          - name: all-params
            value: '{{tasks.a.outputs.parameters.param-1}}'
        depends: a
        name: b
        template: in
    name: dag
```

### Logs from the workflow controller

```text
N/A - cannot submit
```

### Logs from in your workflow's wait container

```text
N/A - cannot submit
```

**Comment by Joibel** [comment]
`tasks.<TASKNAME>.outputs.parameters` is documented as: When the previous task uses withItems or withParams, this contains a JSON array of the output parameter maps of each invocation

So what you're trying here is not intended to work as is, because you're not attempting a `withItems` or `withParams`.
I don't think it's an unreasonable enhancement to make it work though.

**Comment by elliotgunton** [comment]
Thanks for the comment @Joibel, I didn't actually see that in the docs! I originally thought this worked for templates within the workflow i.e. not a `templateRef`, but upon double checking, it seems that also fails to validate/submit, e.g.:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-ref-param-passing-
spec:
  entrypoint: dag
  templates:
  - container:
      command:
        - cowsay
      image: docker/whalesay
    name: output-params
    outputs:
      parameters:
        - name: param-1
          value: '42'
        - name: param-2
          value: test param
  - container:
      args:
      - '{{inputs.parameters.all-params}}'
      command:
      - cowsay
      image: docker/whalesay
    inputs:
      parameters:
      - name: all-params
    name: in
  - dag:
      tasks:
      - name: a
        template: output-params
      - arguments:
          parameters:
          - name: all-params
            value: '{{tasks.a.outputs.parameters}}'
        depends: a
        name: b
        template: in
    name: dag
```

in the UI gets `Internal Server Error: templates.dag.tasks.b failed to resolve {{tasks.a.outputs.parameters}}`

Will update the issue name
