### ISSUE TITLE
Failed to parse workflow: jsonL: cannot unmarshal array into GO struct field DAGTask.spec.templates.dag.tasks.arguments of type v1alpha1.Arguments

### ISSUE THREAD

**Issue by kungkook** [argoproj/argo-workflows#12355]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Failed to parse workflow: jsonL: cannot unmarshal array into GO struct field DAGTask.spec.templates.dag.tasks.arguments of type v1alpha1.Arguments

### Version

argo:v3.0.0-rc6

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-dag3  # workflow的名字
  #namespace: 10006--67275600
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
spec:
  entrypoint: main  # 定义main为主要templates
  arguments:
    parameters:
    - name: recevie_task # 定义recevie_task
      value: task_msg
  templates:
    - name: main
      dag:
        tasks:
          - name: yewuxuqiuzonghefenxi  #业务需求综合分析
            template: yewuxuqiuzonghefenxi 
            arguments:
              parameters:
              - name: param
                value: "{{workflow.parameters.recevie_task}}"
          - name: mubiaoquyufenxi  #目标区域分析(依赖业务需求综合分析)
            depends: yewuxuqiuzonghefenxi 
            template: echo
            arguments:
              parameters:
              - name: param
                value: "{{tasks.yewuxuqiuzonghefenxi.outputs.parameters.result}}"
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
