### ISSUE TITLE
How to set  host header in the http template?

### ISSUE THREAD

**Issue by Bryce-huang** [argoproj/argo-workflows#12385]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

```yaml
     http:
        method: GET
        url: http://172.21.0.102?name={{ inputs.parameters.name }}
        headers:
          - name: Host
            value: fc.forbar.com
```

The host header shuold pass to server.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
http:
        method: GET
        url: http://172.21.0.102?name={{ inputs.parameters.name }}
        headers:
          - name: Host
            value: fc.forbar.com
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
