### ISSUE TITLE
examples/default-pdb-support.yaml is invalid

### ISSUE THREAD

**Issue by komapa** [argoproj/argo-workflows#12396]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

The example here is wrong: https://github.com/argoproj/argo-workflows/blob/main/examples/default-pdb-support.yaml#L10

It needs to be either:

```
  podDisruptionBudget:
    maxUnavailable: "0"
```

or

```
  podDisruptionBudget:
    minAvailable: "100%"
```

`minAvailable: 9999` does not pass CRD validation.

### Version

main

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: default-pdb-support-

spec:
  entrypoint: pdbcreate
  serviceAccountName: default
  podDisruptionBudget:
    minAvailable: 9999   # Provide arbitrary big number if you don't know how many pods workflow creates
  templates:
  - name: pdbcreate
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["sleep 10"]
```
```


### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
