### ISSUE TITLE
ArtifactGC: Inherit / Allow Specification of Scheduling Constraints

### ISSUE THREAD

**Issue by Garett-MacGowan** [argoproj/argo-workflows#12393]
# Summary

Currently, the ArtifactGC pod has no scheduling constraints inherited or specified in the artifactGC config. I would like to add scheduling constraints to the ArtifactGC pod.

I am willing to implement this myself but I would like approval of the idea before hand. TLDR proposal: inherit scheduling constraints from the workflow pod and/or allow the specification of entirely different constraints.

This could be broken up into two tickets, one for inheriting constraints, and another for explicitly defining affinity and tolerations.

## Problem

A lack of scheduling constraints is a problem for setups where all node pools in a cluster have taints that must be tolerated, making the ArtifactGC pod unschedulable.

## Use Cases

Aside from the aforementioned problem, having fine-grained control over ArtifactGC pod placement could be used for cost optimization. E.g. garbage collecting on a very cheap node pool.

## Proposed Solution

1) Default to no constraints (same as existing behavior)
```
workflowSpec:
  # Clean up artifacts https://argoproj.github.io/argo-workflows/walk-through/artifacts/#artifact-garbage-collection
  artifactGC:
    strategy: OnWorkflowDeletion
    serviceAccountName: argo-workflows-sa
```

2) Inherit constraints flag
```
workflowSpec:
  # Clean up artifacts https://argoproj.github.io/argo-workflows/walk-through/artifacts/#artifact-garbage-collection
  artifactGC:
    strategy: OnWorkflowDeletion
    serviceAccountName: argo-workflows-sa
    inheritWorkflowSchedulingConstraints: true
```

3) Allow definition of affinity & tolerations
```
workflowSpec:
  # Clean up artifacts https://argoproj.github.io/argo-workflows/walk-through/artifacts/#artifact-garbage-collection
  artifactGC:
    strategy: OnWorkflowDeletion
    serviceAccountName: argo-workflows-sa
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node_pool
                  operator: In
                  values:
                    - my-cheap-node-pool
    tolerations:
      - key: node_pool
        value: my-cheap-node-pool
        effect: NoSchedule
        operator: Equal
```

@juliev0 tagging you here since I know you deal with / have dealt with ArtifactGC.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
<!--
