### ISSUE TITLE
Incorrect message on UI when podGC is enabled with `deleteDelayDuration`

### ISSUE THREAD

**Issue by bkanuka** [argoproj/argo-workflows#12395]
# Summary

I have my `workflowDefaults` set with:
```yaml
      podGC:
        strategy: OnWorkflowCompletion
        deleteDelayDuration: 168h  # Delete pods 7 days after completion
```

However, the UI states:  "Your pod GC settings will delete pods and their logs immediately on completion. ".  This isn't quite true because my pods will be deleted 7 days after completion.

I would propose that this message is _not_ shown when the `podGC` is set to anything other than the default, or greater than the default.

## Use Cases

I use `OnWorkflowCompletion` and a long `deleteDelayDuration` so that my Kubernetes cluster isn't forever holding on to a growing list of completed pods.  Keeping only the last week of pods is sufficient and keeps the list of pods in k8s at a reasonable level.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
