### ISSUE TITLE
Stopped archived workflow missing artifacts in UI

### ISSUE THREAD

**Issue by Garett-MacGowan** [argoproj/argo-workflows#12401]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When a workflow is stopped and archived, artifacts are missing.

I expect artifacts to be present for stopped & archived workflows.

I already implemented a fix, this issue is here only to reference in the commit and PR.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-stopped-
spec:
  workflowMetadata:
    labels:
      workflows.argoproj.io/test: "true"
      workflows.argoproj.io/workflow: "wf-stopped"
  entrypoint: wf-stopped-main
  serviceAccountName: argo
  executor:
    serviceAccountName: default
  volumeClaimTemplates:
    - metadata:
        name: artifacts
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  templates:
    - name: wf-stopped-main
      dag:
        tasks:
          - name: create-artifact
            template: artifact-creator
          - name: delay-stop-workflow
            template: delay-stop
          - name: stop-workflow
            template: workflow-stopper
            dependencies: [delay-stop-workflow]
    - name: delay-stop
      container:
        image: alpine:latest
        volumeMounts:
          - name: artifacts
            mountPath: /mnt/vol
        command: [sh, -c]
        args:
          - |
            echo "Delaying workflow stop"
            ls /mnt
            x=0
            while [ $x -le 60 ]
            do
              sleep 1
              if [ -f "/mnt/vol/test.txt" ]; then
                echo "Artifact found in shared volume"
                break
              fi
              x=$(( $x + 1 ))
            done
    - name: workflow-stopper
      container:
        image: argoproj/argocli:latest
        args: 
          - stop
          - -l
          - workflows.argoproj.io/workflow=wf-stopped
          - --namespace=argo
          - --loglevel=debug
    - name: artifact-creator
      metadata:
        labels:
          template: "artifact-creator"
      container:
        image: alpine:latest
        volumeMounts:
          - name: artifacts
            mountPath: /mnt/vol
        command: [sh, -c]
        args:
          - |
            echo 'testing' > /mnt/vol/test.txt
            echo "Artifact saved to /mnt/vol/test.txt"
            echo "Pretending to continue to do work."
            ls /mnt
            while :
            do
              sleep 1
            done
      outputs:
        artifacts:
          - name: artifact-creator
            path: /mnt/vol/test.txt
            s3:
              key: artifact-creator
              bucket: my-bucket-3
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
            archive:
              none: {}
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
