### ISSUE TITLE
Output does not capture the details from Base image layer

### ISSUE THREAD

**Issue by manju-rn** [argoproj/argo-workflows#12418]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I have written small workflow which creates a containers and gathers the output from the file within the container.  However, the Output param gives error even though the file exists in the container

I am using the Home Assistant image and wish to capture the details of /config/configuration.yaml when the container is created.
I can see that in `wait` container, it tries to copy (to wait container?), but then it fails and hence the Output params are empty.  Detailed logs are provided
```
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=info msg="Copying /config/configuration.yaml from base image layer"
```
```
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=error msg="executor error: open /var/run/argo/outputs/parameters/config/configuration.yaml: no such file or directory"
```

### Version

3.4.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-steps-template
  namespace: argo-events
spec:
  entrypoint: build-steps
  templates:
  - name: build-steps
    steps:
    - - name: step1        
        templateRef:
          name: ha-container-template
          template: ha-container
```

WorkFlow Template file
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ha-container-template
  namespace: argo-events
spec:
  templates:
  - name: ha-container
    container:
      image: homeassistant/home-assistant:latest
    outputs:
      parameters:
      - name: message
        valueFrom:
          path: /config/configuration.yaml
```
```


### Logs from the workflow controller

```text
Out of Init Container
----
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:35:11 UTC" level=info msg="Start loading input artifacts..."
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:35:11 UTC" level=info msg="Alloc=7345 TotalAlloc=12981 Sys=26213 NumGC=4 Goroutines=4"
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:35:12 UTC" level=info msg="Starting deadline monitor"
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=info msg="Main container completed" error="<nil>"
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=info msg="No Script output reference in workflow. Capturing script output ignored"
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=info msg="Saving output parameters"
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=info msg="Saving path output parameter: message"
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=info msg="Copying /config/configuration.yaml from base image layer"
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=error msg="executor error: open /var/run/argo/outputs/parameters/config/configuration.yaml: no such file or directory"
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=info msg="No output artifacts"
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=info msg="Alloc=7366 TotalAlloc=13541 Sys=25701 NumGC=5 Goroutines=8"
kaniko-workflow-2ncdc-ha-container-3139883534: time="2023-12-27T05:38:37 UTC" level=fatal msg="open /var/run/argo/outputs/parameters/config/configuration.yaml: no such file or directory"
```

**Comment by agilgur5** [comment]
Your problem is that the `homeassistant/home-assistant` image does not have a file `/config/configuration.yaml`:

```sh
❯ docker run -it homeassistant/home-assistant -- bash
2513a9edf9c2:/config# cat /config/configuration.yaml
cat: can't open '/config/configuration.yaml': No such file or directory
2513a9edf9c2:/config# ls
2513a9edf9c2:/config#
```

I don't know much about Home Assistant, but [its docs](https://www.home-assistant.io/installation/linux/#platform-installation) do clearly state that you're supposed to mount your own `configuration.yaml` in that location. It does not come with one.

**Comment by manju-rn** [comment]
@agilgur5 Not exactly. the configuration.yaml with the defaults gets created when the container starts.
The point now is when i give the below, argo workflow does not run the container?
```
spec:
  templates:
  - name: ha-container
    container:
      image: homeassistant/home-assistant:latest
```

**Comment by agilgur5** [comment]
> The point now is when i give the below, argo workflow does not run the container?

It'll run whatever the `entrypoint` of the container is if you don't specify a command to run.

> Not exactly. the configuration.yaml with the defaults gets created when the container starts.

Ok. I wouldn't know, although the docs do say to mount your own there. We could check the source code.
Also if it creates a file, it could delete the file at the end as well, idk

**Comment by manju-rn** [comment]
> It'll run whatever the `entrypoint` of the container is if you don't specify a command to run.
which is what is intriguing, since if i just run as a docker image separately and exec into container you could see that configuration.yaml has been generated (& multiple files in the same /config) location.

**Comment by manju-rn** [comment]
>Also if it creates a file, it could delete the file at the end as well, idk

This got me thinking, the file is not deleted, but argo waits for the container to complete?  since home assistant continues to run once started. Obviously the file will be deleted if the container does.  So I could map /config/configuration.yaml to a volume and check then

**Comment by agilgur5** [comment]
Hmm... I see it does create it at run-time (which is a bit of an anti-pattern for containers):

```sh
❯ docker run -it homeassistant/home-assistant        
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-assistant (no readiness notification)
s6-rc: info: service legacy-services successfully started
Unable to find configuration. Creating default one in /config
^C^C^C^C^C^C^C^C^C^Cs6-rc: info: service legacy-services: stopping
[05:11:24] INFO: Home Assistant Core finish process exit code 0
[05:11:24] INFO: Home Assistant Core service shutdown
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

> but argo waits for the container to complete? since home assistant continues to run once started

Yea it just runs it to completion. I noticed when I ran the entrypoint too that it just runs indefinitely (I had to manually kill the container in Docker).

> Is there a way to check the logs of the container being run?

Yes the `main` container's logs should contain your container's logs. As in:

```sh
kubectl logs -n argo -c main <your pod>
```

**Comment by manju-rn** [comment]
> How are you stopping it in Argo? It's possible a non-graceful termination could cause an issue too with the filesystem

actually am not stopping it at all. Why is why I think non-graceful termination would result in deletion of file. However, if I provide a volume, it should still persist it. I have tried to do this, but the results are same
```
  - name: ha-container
    container:
      image: homeassistant/home-assistant:latest
      # args: ["cat home-assistant.log > /tmp/hello_world.txt"]
      volumeMounts:
      - name: ha-config-path
        mountPath: /config      
    outputs:
      parameters:
      - name: message
        valueFrom:
          path: /config/configuration.yaml
```
