### ISSUE TITLE
ENV Merge Bug 

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argo-workflows#12424]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I want the workflow work well.

but when I submit and get it:
![image](https://github.com/argoproj/argo-workflows/assets/72060326/c9ca594f-1d3f-4ad9-8cb6-132959735dbf)

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
workflow-controller-configmap:  

data:
    mainContainer: |
      env:
      - name: ENV1
        value: "env1"
      - name: ENV2
        value: "env2"
---
apiVersion: v1
stringData:
  sec: testenv
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scripts-python-
spec:
  entrypoint: python-script-example
  templates:
  - name: python-script-example
    steps:
    - - name: generate
        template: gen-random-int
    - - name: print
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate.outputs.result}}"

  - name: gen-random-int
    script:
      image: python:alpine3.6
      command: [python]
      name: ""
      env:
      - name: MY_ENV
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: sec
      source: |
        import random
        i = random.randint(1, 100)
        print(i)

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo result was: {{inputs.parameters.message}}"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

time="2023-12-29T09:36:39.686Z" level=warning msg="Non-transient error: Pod \"scripts-python-szr4c-gen-random-int-1950539070\" is invalid: spec.containers[1].env[0].valueFrom: Invalid value: \"\": may not be specified when `value` is not empty"
time="2023-12-29T09:36:39.686Z" level=info msg="Failed to create pod scripts-python-szr4c(0)[0].generate(0) (scripts-python-szr4c-gen-random-int-1950539070): Pod \"scripts-python-szr4c-gen-random-int-1950539070\" is invalid: spec.containers[1].env[0].valueFrom: Invalid value: \"\": may not be specified when `value` is not empty" namespace=default workflow=scripts-python-szr4c
time="2023-12-29T09:36:39.686Z" level=warning msg="Non-transient error: Pod \"scripts-python-szr4c-gen-random-int-1950539070\" is invalid: spec.containers[1].env[0].valueFrom: Invalid value: \"\": may not be specified when `value` is not empty"
time="2023-12-29T09:36:39.686Z" level=error msg="Mark error node" error="Pod \"scripts-python-szr4c-gen-random-int-1950539070\" is invalid: spec.containers[1].env[0].valueFrom: Invalid value: \"\": may not be specified when `value` is not empty" namespace=default nodeName="scripts-python-szr4c(0)[0].generate(0)" workflow=scripts-python-szr4c
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
