### ISSUE TITLE
Simplify Workflow of Workflows calls to existing workflow templates

### ISSUE THREAD

**Issue by imclvr** [argoproj/argo-workflows#12425]
_(my apologies if another enhancement proposal like this already exists, but I was unable to find it. Feel free to close and link otherwise)._
 
# Summary

Currently, when making an implementation of [Workflow of Workflows](https://argoproj.github.io/argo-workflows/workflow-templates/) pattern, a resource with a workflow needs to be created for calling another existing workflow template, like

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-of-workflows-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: workflow1
            template: resource-1
            arguments:
              parameters:
              - name: workflowtemplate
                value: "workflow-template-submittable"
        - - name: workflow2
            template: resource-2
            arguments:
              parameters:
              - name: workflowtemplate
                value: "workflow-template-submittable"
              - name: message
                value: "Welcome Argo"

    - name: resource-1
      inputs:
        parameters:
          - name: workflowtemplate
      resource:
        action: create
        manifest: |
           # --- COMPLEX, EMBEDDED WORKFLOW HERE TO CALL A WORKFLOW TEMPLATE ---
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
    - name: resource-2
      # ....
```

Instead, it would be great that calling existing workflows would be simpler, probably inside steps like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-of-workflows-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: workflow1
            template: resource-1
            arguments:
              parameters:
              - name: workflowtemplate
                value: "workflow-template-submittable"
            workflowTemplateRef:
              name: workflow-template-already-defined-that-does-stuff-i-want-with-passed-parameters.
```

## Use Cases

- Workflows that chain existing templates either with steps, DAG, etc.
- Better separation of concerns by fostering isolation thanks to simpler YAML syntax.
- Less redundancy on YAML which implies less chance of errors.
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by manju-rn** [comment]
> Instead, it would be great that calling existing workflows would be simpler, probably inside steps like:

This is already possible, see this https://github.com/argoproj/argo-workflows/blob/main/examples/cluster-workflow-template/workflow-template-ref-with-entrypoint-arg-passing.yaml

Is there something else you meant?

**Comment by imclvr** [comment]
Hi,

Thanks for your reply.

Not sure if such example suits this case, as the wf template reference is
outside a `dag` or `steps` section where a `template` is required. And
unfortunately templates require to define embedded workflows just with the
same format of the example you referenced, IIRC.

**Comment by manju-rn** [comment]
> Not sure if such example suits this case, as the wf template reference is outside a `dag` or `steps` section where a `template` is required

WF and WF templates should have no relation to the DAG or the plain steps.  A WF can reference a WFTemplate, a WF Teamplate can reference a WFTemplate, if that's what you are trying to do.  For example, i have the below - My Webhook calls template as per WFTemplate.yaml which in turn calls another template as WFTeamplate_Kaniko.yaml.  Hence the Kaniko container is like re-usable and can be plugged in any template or directly in workflow. This way I create bunch of reusable WFtemplate to utilize in my various workflows

WFTemplate.yaml - Called by webhook
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-steps-template
  namespace: argo-events
spec:
  entrypoint: build-steps
  volumes:
    - name: kaniko-host-path
      hostPath:
        path: /home/manju/kaniko/src/build
        type: Directory
  templates:
  - name: build-steps
    steps:
    - - name: step1        
        templateRef: # Reference to other WorkflowTemplate (it is different from template, which is a task) defined in the same namespace
          name: kaniko-container-template # Name of the WFtemplate
          template: kaniko-container   # Name of the task of the WF Template
```

WFTeamplate_Kaniko.yaml - This template can be called in anywwhere

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kaniko-container-template
  namespace: argo-events
spec:
  templates:
  - name: kaniko-container
    container:
      image: gcr.io/kaniko-project/executor:latest
      command: [executor, --no-push, "--tar-path=/images/myimage.tar"]
      volumeMounts:
      - name: kaniko-host-path
        mountPath: /workspace
    outputs:
      artifacts:
      - name: tarfile
        path: /images/myimage.tar
```
