### ISSUE TITLE
Custom columns do not read from annotations like documentation states

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argo-workflows#12422]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Add an annotation to my workflow that I have listed on my `workflow-controller-configmap.yaml` under `columns` with `key: annotation`.

Example in `workflow-controller-configmap.yaml`

```yaml
  columns: |
    - name: Custom Column
      type: annotation
      key: workflows.argoproj.io/custcom-column
```

[Example kustomize overlay](https://github.com/argoproj/argo-workflows/blob/954884d64c7b2d24a2e5fa0641a66692d182fefd/manifests/quick-start/base/overlays/workflow-controller-configmap.yaml#L46) to edit for local testing

### Actual (Current)

`unknown` always shows in custom column

![Screenshot 2023-12-28 at 9 47 33 PM](https://github.com/argoproj/argo-workflows/assets/35014/34988bfc-d440-4c0d-b450-387eda72a25e)

### Expected

value from workflow annotation

### Version

v3.5.2 and latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: custom-column-
  namespace: argo
  labels:
    example: 'true'
  annotations:
    argo-events.argoproj.io/customcolumn: custom-column
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
nothing relevant since this is a UI issue
```

### Logs from in your workflow's wait container

```text
Nothing relevant since this is a UI issue
```
