### ISSUE TITLE
Resource duration is overestimated for cpu

### ISSUE THREAD

**Issue by AloysAqemia** [argoproj/argo-workflows#12468]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

The resourcesDuration field in a completely workflow currently greatly overestimates the cpu consumption of the workflows. The example workflow below, for instance, ends with ~125s of consumed CPU, while we would expect it to be closer to 60s.

The issue comes from this line: https://github.com/argoproj/argo-workflows/blob/main/util/resource/summary.go#L33

When the `q.Value()` function is called, small decimal quantities are rounded up. As a result, the `wait` container that requests `10m` cores, is counted as if it requested a full core.

See the snippet below for a sample that shows the issue with the `Value()` function:
```go
import (
	"fmt"

	"k8s.io/apimachinery/pkg/api/resource"
)

func main() {
	a := resource.MustParse("10m")
	fmt.Println(a.Value())      // 1
	fmt.Println(a.MilliValue()) // 10
	fmt.Println(a.AsDec())      // 0.010

	a = resource.MustParse("1000m")
	fmt.Println(a.Value())      // 1
	fmt.Println(a.MilliValue()) // 1000
	fmt.Println(a.AsDec())      // 1
}
```
Because of this, small CPU requests are rounded up to one core, and the cpu resources consumed by workflows are greatly overestimated.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: resources-test-
  namespace: workflows
spec:
  serviceAccountName: server
  entrypoint: sleep
  templates:
    - name: sleep
      container:
        image: ubuntu:22.04
        command: [ sleep ]
        args: [ "60" ]
        resources:
          requests:
            memory: 128Mi
            cpu: 1
```

### Logs from the workflow controller

```text
Nothing relevant
```

### Logs from in your workflow's wait container

```text
Nothing relevant
```
