### ISSUE TITLE
Memoized didn't created when there is retryStrategy

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argo-workflows#12490]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I want a configmap named cache-config but not found.

I think the root cause is when the workflow have retrystrategy, memoizationStatus will only in ParentNode instead of children node.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: memoized-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    memoize:
      key: "cache-key"
      cache:
        configMap:
          name: cache-config
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay world > /tmp/hello_world.txt"]
    outputs:
      parameters:
      - name: hello
        valueFrom:
          path: /tmp/hello_world.txt
---
workflowDefaults: |
    spec:
      # must complete in 8h (28,800 seconds)
      activeDeadlineSeconds: 28800
      # keep workflows for 1d (86,400 seconds)
      ttlStrategy:
        secondsAfterCompletion: 86400
        secondsAfterFailure: 86400
        secondsAfterSuccess: 86400
      retryStrategy:
        limit: 4
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
