### ISSUE TITLE
Parameter usage vulnerable to workflow injection

### ISSUE THREAD

**Issue by phoebelilius** [argoproj/argo-workflows#12534]
### Pre-requisites

- [X] I have double-checked my configuration
- [ ] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Not sure if this is a bug or user error, please advise.

When using input parameters in bash script (within `script` `source`), the parameter is used unescaped.
For example: 
```
      script:
        image: debian:9.4
        command:
          - bash
        source: |
          echo '{{inputs.parameters.message}}'
```
This results in code vulnerable to any input containing `'` quote mark. 
For example, we could inject a command by passing in `hello argo'; ls -la /; echo 'finished injection` (tested this, and indeed the `ls -la` executes).

Same thing happens if `echo "{{inputs.parameters.message}}"` is used and a double quote `"` is passed.

This does _not_ happen if using `container` and `args`:
```
      container:
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
```

For example, if using env variables, this would not be the case:
```
# MYVAR='foo"bar'
# echo "$MYVAR"  
foo"bar
```

Am I using bash wrong in the context of argo workflows?

### Version

v3.5.2 (sorry I'm not able to test with `:latest`)

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-escaping
spec:
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      outputs: {}
      metadata: {}
      script:
        name: ''
        image: debian:9.4
        command:
          - bash
        resources: {}
        source: |
          echo '{{inputs.parameters.message}}'
  entrypoint: argosay
  arguments:
    parameters:
      - name: message
        value: hello argo
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
