### ISSUE TITLE
ArgoWorkflows in Cluster Scope - RBACs not working properly in UI

### ISSUE THREAD

**Issue by bilyboy785** [argoproj/argo-workflows#12558]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

We use Argo Workflows in Cluster Scope with an external Dex for SSO. We have different teams, needs to work on WorkflowTemplates & Workflows in their namespaces. We need to allow them to see WorkflowTemplates in others Namespace too.

When I log in with my user1, I see in the UI that I'm using the SA readonly, instead of being attached to the serviceAccount team1 in the namespace team1.

However, the user seems to have the right permissions (those of serviceAccount team1). But why do we see the serviceAccount readonly?

![](https://camo.githubusercontent.com/4eaaaf3cc6348a3ff95b289aeb9e5b10e545f4ea7de9854dd4e8b2d5fb1110e4/68747470733a2f2f6d656469612e636c65616e73686f742e636c6f75642f6d656469612f31353931372f553649794c38794b636c573934677a66716a34337742434d6b6c43507969514d53657645633479512e6a7065673f457870697265733d31373035363139353532265369676e61747572653d6c713236555631394142756f5a67633758473377376a724952687669345933374e726f734d49776a44474d4b6550533452496559617770447331476f536b7a474c4b723552467344706f426569306c67734362326a445941313246315a79424c634c466f6c736b507962345652536b336b726347415473747742714d5a2d6752783267727e6a65667a536677497e666a4a53676c6f507449346b5a542d774737704b3269474b2d444b4234464e596b34424f46744f4461365a5776787e646a716b46476154635a52326739314c65696c2d434a7a5a446533306a6f573332646e516c5042714c514f44673250456c56584f397456756c7747536b6f6b47563645386b6d696d553053714968686e567154575a6f7759773252335174792d63345a486962537151326c4d3353453747384c62324f626264495465556e4e457a44514d4c506366756752424e5a4377702d4c534538674e775f5f264b65792d506169722d49643d4b3236394a4d4154395a4634475a)

we expect differents cases :

- User1 from team1 loggin : he should be linked to serviceAccount team1 in namespace team1 with all permissions in team1 namespace
- User2 from team2 loggin : he should be linked to serviceAccount team2 in namespace team2 with all permissions in team2 namespace
- [...]
- UserX from teamX loggin : no rule match, he should be map to the default argo-workflow-server serviceAccount, with minimal permissions (readonly).

### Version

v3.5.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
So we configure RBACs to allow UserA working in NamespaceA and Get WorkflowTemplates in NamespaceB, NamespaceC :


- apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: argoworkflows-role-team1
      namespace: fifty
    rules:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs:
          - '*'
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: argoworkflows-role-binding-team1
      namespace: team1
    subjects:
      - kind: ServiceAccount
        name: team1
    roleRef:
      kind: Role
      name: argoworkflows-role-team1
      apiGroup: rbac.authorization.k8s.io
  - apiVersion: v1
    kind: Secret
    type: kubernetes.io/service-account-token
    metadata:
      namespace: team1
      name: team1.service-account-token
      annotations:
        kubernetes.io/service-account.name: team1
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: team1
      namespace: team1
      annotations:
        workflows.argoproj.io/rbac-rule: "'team1' in groups"
        workflows.argoproj.io/rbac-rule-precedence: '2'
```

We set rbac-rule: true to a new readonly serviceAccount :

```
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: readonly
      namespace: argo-workflows
      annotations:
        workflows.argoproj.io/rbac-rule: 'true'
        workflows.argoproj.io/rbac-rule-precedence: '0'
  - apiVersion: v1
    kind: Secret
    type: kubernetes.io/service-account-token
    metadata:
      namespace: argo-workflows
      name: readonly.service-account-token
      annotations:
        kubernetes.io/service-account.name: readonly
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: argoworkflows-cluster-role-readonly
    rules:
      - apiGroups:
          - argoproj.io
        resources:
          - workflowstemplates
          - clusterworkflowtemplates
        verbs:
          - get
          - list
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: argoworkflows-cluster-role-binding-readonly
    subjects:
      - kind: ServiceAccount
        name: readonly
        namespace: argo-workflows
    roleRef:
      kind: ClusterRole
      name: argoworkflows-cluster-role-readonly
      apiGroup: rbac.authorization.k8s.io
```

### Logs from the workflow controller

```text
(not a problem with a Workflow)
```

### Logs from in your workflow's wait container

```text
(not a problem with a Workflow)
```
