### ISSUE TITLE
Set main container resources (cpu,memory) for "resource" template (fix argoexec OOM)

### ISSUE THREAD

**Issue by ebuildy** [argoproj/argo-workflows#12586]
# Summary

I want to fix argoexec container OOM:

Running this template:

```yaml
    - name: copy-pvc
      resource:
          action: create
          manifest: |
            apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
                name: {{workflow.name}}-source
              .......
```

Make argoexec container crash because OOM. I would like to configure memory limit for this template.

## Use Cases

All template types such `script` , and `resource` , `http`  that use argoexec container should be easily configurable (`script` is already OK)

What about allowing this:

```yaml
    - name: copy-pvc
      container:
          resources:
              limits:
                 memory: 128Mi
      resource:
          action: create
          manifest: |
            ....
```

With actual version, this gives error:

```
templates.backup-take.steps[0].read-pvc templates.read-pvc multiple template types specified. choose one of: container, containerSet, steps, script, resource, dag, suspend, template, template ref
```

Another use-case:

"I am on AKS cluster, I want to clone a PVC attached to a pod in availability zone 1"

--> The argoexec container pod must run in the same zone
