### ISSUE TITLE
Enhancement: Artifact should support `includes` option to avoid downloading unnecessary files.

### ISSUE THREAD

**Issue by link89** [argoproj/argo-workflows#12588]
# Summary

 Support a new option named `includes` in Artifact and implement code to filter data download according to the glob pattern in `includes` field.

## Use Cases

In Argo Workflow, a step can be configured to download artifacts from previous steps. However, it downloads all files in the artifact directory. But it is not always necessary to download all files. It is a common case that previous step uploads all generated files (for audit purpose), but the downstream step only needs a few of them. In this case, downloading all files is a waste of time and bandwidth.

My suggestion is to add `includes` option to the artifact to allow users to specify which files to download. This is different to the existed `subPath` option, which append a subpath to the `from` path.  `includes` doesn't change the `from` path, but only limit the system to download files that match the pattern. For example:

```yaml
  - name: step2
    ...
    artifacts:
      - name: generated-files
        from: {{steps.step1.outputs.artifacts}}
        includes: ["*.txt", "*.csv"]
```

Besides, includes should also support reference to previous step's outputs. For example, the previous step return a list of data_files in its output, then the downstream step can make use of it to filter file

```yaml
  - name: step2
    ...
    artifacts:
      - name: generated-files
        from: {{steps.step1.outputs.artifacts}}
        includes: {{steps.step1.outputs.parameters.data_files}}
```

[Optional] An extra `excludes` option can also be added to exclude files from the artifact. For example:

```yaml
  - name: step2
    ...
    artifacts:
      - name: generated-files
        from: {{steps.step1.outputs.artifacts}}
        excludes: {{steps.step1.outputs.parameters.audit_files}}
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.
