### ISSUE TITLE
`Artifact Server returned internal error` `Access Denied` when downloading artifact from UI using a SSO admin

### ISSUE THREAD

**Issue by bumper-jorge-pino** [argoproj/argo-workflows#12629]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

What happened? I get an internal error when trying to download an artifact from the UI when logged as a SSO admin user.
What did you expect? Being able to download the artifact.

### Version

v3.5.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
                - name: cypress-e2e
                  inputs:
                    parameters:
                      - name: aws-role-id
                      - name: branch_base
                  nodeSelector:
                    eks.amazonaws.com/capacityType: ON_DEMAND
                    node.kubernetes.io/instance-type: m5.xlarge
                  metadata:
                    annotations:
                      iam.amazonaws.com/role: "{{inputs.parameters.aws-role-id}}"
                  tolerations:
                  - key: "dedicated"
                    operator: "Equal"
                    value: "tests"
                    effect: "NoSchedule"
                  container:
                    resources:
                      limits:
                        cpu: 4
                        memory: 8Gi
                      requests:
                        cpu: 2
                        memory: 1Gi
                    volumeMounts:
                      - mountPath: /home/bumper
                        name: workdir
                    image: cypress/included:13.6.1
                    env:
                      - name: TERM
                        value: xterm
                    workingDir: /home/bumper/core-bumper
                    command: [sh, -c]
                    args:
                      - (yarn start:cypress)&
                        yarn wait-on http://localhost:3000 &&
                        yarn cypress install --force &&
                        yarn cypress run --env tags="@working" &&
                        yarn create:coverage-report
                    envFrom:
                    - secretRef:
                        name: argo-workflows-cicd-configs
                    - secretRef:
                        name: argo-workflows-cicd-secrets
                  outputs:
                    artifacts:
                    - name: e2e-coverage-report
                      path: cypress/report/coverage
                      s3:
                        endpoint: s3.amazonaws.com
                        bucket: bumper-argo-workflows-artifacts
                        region: eu-west-1
                        key: e2e-coverage-report/{{inputs.parameters.branch_base}}-coverage-report.tgz
```

### Logs from the workflow ~controller~ Server

```text
time="2024-02-05T16:03:05.660Z" level=info msg="selected SSO RBAC service account for user" email= loginServiceAccount=admin-user serviceAccount=admin-user ssoDelegated=false ssoDelegationAllowed=false subject=CgkxMDM1NjQxOTASBmdpdGh1Yg
time="2024-02-05T16:03:05.661Z" level=info msg="Get artifact file" artifactName=e2e-coverage-report namespace=cicd nodeId=frontend-pr-release-fe-pz52t-995080838 workflowName=frontend-pr-release-fe-pz52t
time="2024-02-05T16:03:05.675Z" level=info msg="Creating minio client using IAM role"
time="2024-02-05T16:03:05.731Z" level=info msg="Check if directory" artifactName=e2e-coverage-report duration=62.162266ms error="Access Denied" key=e2e-coverage-report/release-fe-coverage-report.tgz
time="2024-02-05T16:03:05.731Z" level=error msg="Artifact Server returned internal error" error="Access Denied"
time="2024-02-05T16:03:05.731Z" level=info duration=72.569413ms method=GET path=/artifact-files/cicd/workflows/frontend-pr-release-fe-pz52t/frontend-pr-release-fe-pz52t-995080838/outputs/e2e-coverage-report size=22 status=500
time="2024-02-05T16:03:07.803Z" level=info duration="91.18µs" method=GET path=index.html size=487 status=0
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
