### ISSUE TITLE
Workflow of workflows fails when input parameters are specified on inner workflow

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj/argo-workflows#12634]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

**Context**
My organization has a use case for workflows of workflows. However, when we create inner workflows via the resource specification the Argo Server fails to resolve `{{input.parameters.whatever}}`. The outer workflow template does not have any inputs specified while the inner workflows (specified as resources) have inputs + arguments specified (via steps).

**Expected**
I expected the workflow to be submitted successfully since inner workflows submitted as resources should be independent of the outer workflow.

**What actually happened**
I fail to submit the workflow with an error like
```
`templates.main.steps[0].w1r templates.w1r: failed to resolve {{inputs.parameters.msg}}`
```

**Extra context**
The workflow YAML file is created via [Hera](https://github.com/argoproj-labs/hera). I went through Hera's code and could not find anything that generates anything unnecessarily. In addition, I verified the YAML, looked through Argo docs + examples. Since I cannot even submit this workflow I cannot get `kubectl` logs. 

Hera discussion on the topic: https://github.com/argoproj-labs/hera/discussions/803

**Hera specification**

```python
from hera.workflows import Workflow, Steps, script, Resource

@script(image="python:3.7")
def foo(msg):
    print(msg)


with Workflow(name="foo1", entrypoint="main") as w1:
    with Steps(name="main"):
        foo(name="foo1", arguments={"msg": "Hello, World!"})

with Workflow(name="foo2", entrypoint="main") as w2:
    with Steps(name="main"):
        foo(name="foo1", arguments={"msg": "Hello, World!"})

with Workflow(name="main", entrypoint="main") as w:
    w1r = Resource(name="w1r", manifest=w1, action="create")
    w2r = Resource(name="w2r", manifest=w2, action="create")

    with Steps(name="main"):
        w1r()
        w2r()

w.create()
```

### Version

v3.3.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: main
  namespace: default
spec:
  entrypoint: main
  templates:
  - name: w1r
    resource:
      action: create
      manifest: "apiVersion: argoproj.io/v1alpha1\nkind: Workflow\nmetadata:\n  name:\
        \ foo1\n  namespace: default\nspec:\n  entrypoint: main\n  templates:\n  -\
        \ name: main\n    steps:\n    - - arguments:\n          parameters:\n    \
        \      - name: msg\n            value: Hello, World!\n        name: foo1\n\
        \        template: foo\n  - inputs:\n      parameters:\n      - name: msg\n\
        \    name: foo\n    script:\n      command:\n      - python\n      image:\
        \ python:3.7\n      source: 'import os\n\n        import sys\n\n        sys.path.append(os.getcwd())\n\
        \n        import json\n\n        try: msg = json.loads(r'''''{{inputs.parameters.msg}}''''')\n\
        \n        except: msg = r'''''{{inputs.parameters.msg}}'''''\n\n\n       \
        \ print(msg)'\n"
  - name: w2r
    resource:
      action: create
      manifest: "apiVersion: argoproj.io/v1alpha1\nkind: Workflow\nmetadata:\n  name:\
        \ foo2\n  namespace: default\nspec:\n  entrypoint: main\n  templates:\n  -\
        \ name: main\n    steps:\n    - - arguments:\n          parameters:\n    \
        \      - name: msg\n            value: Hello, World!\n        name: foo1\n\
        \        template: foo\n  - inputs:\n      parameters:\n      - name: msg\n\
        \    name: foo\n    script:\n      command:\n      - python\n      image:\
        \ python:3.7\n      source: 'import os\n\n        import sys\n\n        sys.path.append(os.getcwd())\n\
        \n        import json\n\n        try: msg = json.loads(r'''''{{inputs.parameters.msg}}''''')\n\
        \n        except: msg = r'''''{{inputs.parameters.msg}}'''''\n\n\n       \
        \ print(msg)'\n"
  - name: main
    steps:
    - - name: w1r
        template: w1r
    - - name: w2r
        template: w2r
```

### Logs from the workflow controller

```text
NOT APPLICABLE / cannot submit workflow
```

### Logs from in your workflow's wait container

```text
NOT APPLICABLE / cannot submit workflow
```
