### ISSUE TITLE
`deleteDelayDuration` JSON schema and validation mismatch

### ISSUE THREAD

**Issue by hobti01** [argoproj/argo-workflows#12631]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I'm really not understanding the syntax for `deleteDelayDuration` implemented in 3.5 https://github.com/argoproj/argo-workflows/pull/11325.
The examples use
```yaml
deleteDelayDuration: 1h
```
But the schema (https://github.com/argoproj/argo-workflows/blob/v3.5.4/api/openapi-spec/swagger.json#L14403) says it should be
```yaml
deleteDelayDuration:
  duration: 1h
```
The schema-correct option fails with a validation error in the UI.

Is the schema wrong, the docs wrong or the code wrong?  I cannot determine what is correct, although only the schema-incorrect version is submittable.

### Version

3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-gc-strategy-
spec:
  entrypoint: main
  podGC:
    strategy: OnPodCompletion
    deleteDelayDuration:
      duration: 30s
  templates:
  - name: main
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["exit 0"]
```

### Logs from the workflow ~controller~ server

No logs from the controller, the workflow cannot be submitted from the UI as a 400 error is returned from the Server.

```
time="2024-02-06T13:37:24.226Z" level=info duration="145.147µs" method=POST path=/api/v1/workflows/argo size=134 status=400
```

### Logs from in your workflow's wait container

No logs, no workflow is created.
