### ISSUE TITLE
Step has Parent WorkflowTemplate's service account instead of its own

### ISSUE THREAD

**Issue by epDHowwD** [argoproj/argo-workflows#12642]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Parent WorkflowTemplate:
```yaml
metadata:
  name: parent-workflow
spec:
  templates:
    - steps:
        - templateRef:
            name: child-workflow
            template: child-workflow
  serviceAccountName: parentSA
```

Child WorkflowTemplate:
```yaml
metadata:
  name: child-workflow
spec:
  # ...
  serviceAccountName: childSA
```

When the parent workflow is executed and creates the workflow pods for the child-workflow, the generated pods use the service account of the parent workflow instead of the child workflow:

```yaml
metadata:
  name: parent-workflow-xxx-child-workflow-xxxxxxx
spec:
  serviceAccount: parentSA
  serviceAccountName: parentSA
```

Is this maybe wanted? It is not so clear from the documentation. We prepared the 'child' workflowTemplate to provide certain functionality that requires RBAC permissions bound to a certain service account. When using another account which indeed has the permission to trigger any workflow to refer to this as a workflow step in a larger workflow, then it cannot successfully execute this child workflow as it lacks this extra permissions.

The idea is that the child workflow with the child workflow's service account is the only account that get's this permissions and provides only the feature to execute the logic provided in this workflow but not in any other interface.

See this in the context of strict workflow referencing.

### Version

v3.4.10

**Comment by agilgur5** [comment]
It looks like your child `WorkflowTemplate` doesn't have a template-level SA? Just a Workflow-level SA?

I believe it is correct behavior for the parent to override the child in this case because their SAs are on the same level, at Workflow-level. The parent's SA is an explicit override.

You're also using a `templateRef` for a specific template of the child, and not the whole Workflow (i.e. with `workflowTemplateRef`), though I believe the results would be the same in that case due to your construction.

If you want your child template to always retain it's SA, you can specify the SA at the template-level

**Comment by epDHowwD** [comment]
Thanks @agilgur5. We got it running adding the SA on template level. The suggestion using `workflowTemplateRef` on caller side is not working out because of #6698. Seems this is not generally supported for use in a dag.

**Comment by rahulgcm** [comment]
@epDHowwD 
Can you pls share the example workflow using which are able to solved this issue

**Comment by epDHowwD** [comment]
The solution was to move the `serviceAccountName` from `spec` level to template level (all templates of the workflow):

``` yaml
metadata:
  name: child-workflow
spec:
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    serviceAccountName: childSA
    ...
```
