### ISSUE TITLE
Add WorkflowTemplate name as label when using `workflowTemplateRef`

### ISSUE THREAD

**Issue by eduardodbr** [argoproj/argo-workflows#12670]
# Summary

What change needs making?

When a `Workflow` or a `CronWorkflow` is submitted from a WorkflowTemplate,( i.e. using the `workflowTemplateRef`) it would be nice to have the `WorkflowTemplate` name as a label for easier filtering using the UI.

## Use Cases

When would you use this?

A workflow like:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-template-hello-world
spec:
  workflowTemplateRef:
    name: workflow-template-submittable
```

Or workflows that are children of a CronWorkflow like: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-from-template
spec:
  schedule: "* * * * *"
  workflowSpec:
    workflowTemplateRef:
      name: workflow-template-submittable
```

would have labels:

```yaml
labels:
    workflows.argoproj.io/workflow-template: workflow-template-submittable
```

I am available to contribute to this new feature if accepted. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by agilgur5** [comment]
> or a `CronWorkflow`

Implementation-wise, I don't think this part matters, since a `CronWorkflow` creates `Workflows`, so it would be functionally equivalent to a `Workflow` with a `workflowTemplateRef`

Also I simplified the title a good bit for simplicity and readability

**Comment by sarabala1979** [comment]
@eduardodbr  I would like to understand the usecase for this. Because `workflowTemplateRef` is a static value it is known during spec creation. `Label` can be added to the workflow spec itself.


Let me know if I am missing anything


```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
     workflows.argoproj.io/workflow-template: workflow-template-submittable    
  name: workflow-template-hello-world
spec:
  workflowTemplateRef:
    name: workflow-template-submittable
```

```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-from-template
spec:
  schedule: "* * * * *"
  workflowMetadata:
     labels:
        workflows.argoproj.io/workflow-template: workflow-template-submittable    
  workflowSpec:
    workflowTemplateRef:
      name: workflow-template-submittable
```
