### ISSUE TITLE
Expression should also work in `arguments.parameters`, not just `outputs.parameters`

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-workflows#12685]
# Summary

This request is related to issue #6207, which basically requests the same for artifacts. I think it can be split into two tickets though, for less complexity. 

## Use Cases

We have got several large workflows where workflow templates are shared. In some a "translation" from one variable to another is needed, e.g. is-dev (bool) -> dev (string). So the condition is not based on a step output, but on an input variable. Instead of adding an additional step doing this conversion and outputting a string, we can easily archive this by adding valueFrom.Expression for arguments.

## Example workflow

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-arg-param-
spec:
  entrypoint: conditional-arg-param
  templates:
  - name: conditional-arg-param
    input:
      parameters:
      - name: is-dev
        default: "true"
    steps:
    - - name: print
        template: print-message
        arguments:
          parameters:
          - name: message
            valueFrom:
              expression: "inputs.parameters['is-dev'] == true ? dev : prod"

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by agilgur5** [comment]
are you able to directly template this now without an explicit `expression` field? like the below:

```yaml
        arguments:
          parameters:
          - name: message
            value: "{{=inputs.parameters['is-dev'] == true ? dev : prod}}"
```

**Comment by nice-pink** [comment]
Thanks for the quick reply. No, it does not work. It passes the string as is:

```
Parameters
msg       {{=inputs.parameters['is-heads'] == true ? heads : tails}}
```

**Comment by agilgur5** [comment]
Is that output from the CLI? Expressions are evaluated at run-time, so the clients will list the parameters raw

I'm fairly sure in-line expressions work inside `arguments.parameters`. Here's a few recent examples [from](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1708307196702399?thread_ts=1708292213.140899&cid=C01QW9QSSSK) [Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1708425382369109) that use them.

**Comment by jswxstw** [comment]
### Example workflow
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-arg-param-
spec:
  entrypoint: conditional-arg-param
  templates:
  - name: conditional-arg-param
    inputs:
      parameters:
      - name: is-dev
        default: "true"
    steps:
    - - name: print
        template: print-message
        arguments:
          parameters:
          - name: message
            value: # see examples below
  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```
Example 1: `"{{=inputs.parameters.is-dev == true ? dev : prod}}"`
output: 
```
_______________________________________ 
/ {{=inputs.parameters.is-dev == true ? \
\ dev : prod}}                          /
 --------------------------------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
```

Example 2: `"{{inputs.parameters.is-dev}} == true ? dev : prod"`
output:
```
 ___________________________ 
< true == true ? dev : prod >
 --------------------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/
```
However, @nice-pink may expect the output be like: 
```
 _____ 
< dev >
 ----- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/ 
```
