### ISSUE TITLE
SSO not working with github, gcp Oauth2 with dex (argocd)

### ISSUE THREAD

**Issue by dangdong163** [argoproj/argo-workflows#12706]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I am configuring sso with dex (installed on argocd) using oidc github or gcp. But it all failed. I got error `Invalid client_id`. even i config right client_id. 
<img width="744" alt="image" src="https://github.com/argoproj/argo-workflows/assets/139737826/90a86cce-46ad-4ba5-82b9-26d321a4fd26">
<img width="581" alt="image" src="https://github.com/argoproj/argo-workflows/assets/139737826/309ec2e6-5a9c-4c4c-9b58-127763134203">
<img width="378" alt="image" src="https://github.com/argoproj/argo-workflows/assets/139737826/ea7d7e3d-c1bc-4f00-a414-12078509c214">

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
level=error msg="Failed to parse authorization request: Invalid client_id (\"ce4723e72cd31dc5be06\")."
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
time="2024-02-28T06:29:38.781Z" level=info msg="Alloc=11716 TotalAlloc=31194 Sys=27493 NumGC=12 Goroutines=103"
time="2024-02-28T06:29:56.978Z" level=info duration="149.296µs" method=GET path=index.html size=487 status=0
time="2024-02-28T06:30:16.978Z" level=info duration="131.668µs" method=GET path=index.html size=487 status=0
time="2024-02-28T06:30:36.978Z" level=info duration="97.479µs" method=GET path=index.html size=487 status=0
time="2024-02-28T06:30:56.979Z" level=info duration="147.805µs" method=GET path=index.html size=487 status=0
time="2024-02-28T06:31:16.978Z" level=info duration="122.578µs" method=GET path=index.html size=487 status=0
time="2024-02-28T06:31:36.978Z" level=info duration="117.885µs" method=GET path=index.html size=487 status=0
time="2024-02-28T06:31:56.978Z" level=info duration="116.596µs" method=GET path=index.html size=487 status=0
time="2024-02-28T06:32:16.979Z" level=info duration="150.483µs" method=GET path=index.html size=487 status=0
time="2024-02-28T06:32:36.978Z" level=info duration="114.268µs" method=GET path=index.html size=487 status=0
time="2024-02-28T06:32:56.978Z" level=info duration="112.111µs" method=GET path=index.html size=487 status=0
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
When showing configuration, please use text instead of images, text is [much more accessible](https://meta.stackoverflow.com/a/285557/3431180) than images.
Also your secret is visible in the images, you may want to rotate that if it's not already a test secret.

I have a very similar configuration working (different auth provider though) and so do other users (here's an old one with Okta a [few months ago](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1701252663218859)), so this sounds like something is misconfigured rather than there being a bug.


> I got error `Invalid client_id`. even i config right client_id.

Are you trying to use the same `client_id` for GitHub and Argo Workflows? These are two separate clients.
Dex is a client of GitHub and Argo Workflows is a (static) client of Dex.

In the first section of the [SSO with Argo CD Dex doc](https://argo-workflows.readthedocs.io/en/latest/argo-server-sso-argocd/), it shows creating a `Secret` that both Dex and Argo Workflows can access.

**Comment by papillon88** [comment]
@agilgur5 Im facing a "similar" issue here - except in my case - the readiness probe for argo-server pods fails (says connection refused) and the pods dont get to ready state.  
Argo-server Pod events below -
<img width="1450" alt="image" src="https://github.com/argoproj/argo-workflows/assets/11804111/f7e2baf2-3647-47a7-8944-1beb4e2ddb91">

Argo-server Pod logs below -
```
time="2024-05-30T14:26:55.979Z" level=debug msg="CLI version" version="{v3.5.5 2024-02-29T21:01:29Z c80b2e91ebd7e7f604e88442f45ec630380effa0 v3.5.5 clean go1.21.7 gc linux/amd64}"
time="2024-05-30T14:26:55.979Z" level=info msg="not enabling pprof debug endpoints"
time="2024-05-30T14:26:55.980Z" level=info authModes="[sso sso]" baseHRef=/workflows/ managedNamespace= namespace=argo secure=false ssoNamespace=argo
time="2024-05-30T14:26:55.980Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argo-workflows.readthedocs.io/en/release-3.5/tls/"
```

That being said, the Argo-controller pods are up and running. Dont see any errors in event logs and pod logs. 

//argocd config
```
dex:
  env:
    - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: argo-workflows-sso
          key: client-secret
server:
  ingress:
    path: /cd

configs:
  params:
    server.basehref: /cd
    server.rootpath: /cd
  cm:
    url: https://argo.int.cloud.net/cd
    dex.config: |
      staticClients:
        - id: argo-workflows-sso
          name: Argo Workflow
          redirectURIs:
            - https://argo.int.cloud.net/workflows/oauth2/callback
          secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23ctUrIKwIKw6UcXpb
            clientSecret: 9db2c01e29ac8f06c3703c7f5f005ff2ac2578d2
            orgs:
            - name: deb-org-1
```

//argoworkflows config
```
server:
  baseHref: /workflows/

  authModes:
    - sso

  ingress:
    paths:
      - /workflows(/|$)(.*)

    sso:
    enabled: true
    issuer: https://argo.int.cloud.net/cd/api/dex
    clientId:
      name: argo-workflows-sso
      key: client-id
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    redirectUrl: https://argo.int.cloud.net/workflows/oauth2/callback
```

**Please note that both argocd and argoworkflows are under /cd and /workflows respectively -
https://argo.int.cloud.net/cd
https://argo.int.cloud.net/workflows**

However, If I disable sso in argo-workflows, the argo-server pods are able to get to ready state and running - no issues there - readiness probe works fine. 

Any ideas as to why the Readiness fails for the argo-servers when sso is enabled ? Any help is greatly appreciated !
