### ISSUE TITLE
Combining parameters and expr-lang logic doesn't seem to work

### ISSUE THREAD

**Issue by winterrobert** [argoproj/argo-workflows#12709]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Trying to use [expressions](https://argo-workflows.readthedocs.io/en/latest/variables/#expression) for comparing numbers from input parameters, this logic seems to work for expressions like `==` but not for `>` for example.

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: testwf
spec:
  entrypoint: calculate-memory-limit
  arguments:
    parameters:
    - name: number_of_transactions
      value: 50000

  templates:
  - name: calculate-memory-limit
    inputs:
      parameters:
        - name: number_of_transactions
        - name: doesntwork
          value: "{{= asInt(inputs.parameters.number_of_transactions) > 40000 ? '2222Mi' : '2233Mi' }}"
        - name: works1
          value: "{{= asInt(inputs.parameters.number_of_transactions) == 40000 ? '2222Mi' : '2233Mi' }}"
        - name: works2
          value: "{{= 50000 > 40000 ? '2222Mi' : '2233Mi' }}"
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        print('doesntwork: {{inputs.parameters.doesntwork}}')
        print('works1: {{inputs.parameters.works1}}')
        print('works2: {{inputs.parameters.works1}}')
```

### Logs from the workflow controller

```text
time="2024-02-28T14:37:17.046Z" level=info msg="Processing workflow" namespace=local workflow=testwf
time="2024-02-28T14:37:17.048Z" level=info msg="Updated phase  -> Running" namespace=local workflow=testwf
time="2024-02-28T14:37:17.049Z" level=info msg="Pod node testwf initialized Pending" namespace=local workflow=testwf
time="2024-02-28T14:37:17.049Z" level=error msg="Mark error node" error="cannot finish template replacement because the result was invalid JSON" namespace=local nodeName=testwf workflow=testwf
time="2024-02-28T14:37:17.049Z" level=info msg="node testwf phase Pending -> Error" namespace=local workflow=testwf
time="2024-02-28T14:37:17.049Z" level=info msg="node testwf message: cannot finish template replacement because the result was invalid JSON" namespace=local workflow=testwf
time="2024-02-28T14:37:17.049Z" level=info msg="node testwf finished: 2024-02-28 14:37:17.049987775 +0000 UTC" namespace=local workflow=testwf
time="2024-02-28T14:37:17.049Z" level=error msg="error in entry template execution" error="cannot finish template replacement because the result was invalid JSON" namespace=local workflow=testwf
time="2024-02-28T14:37:17.050Z" level=info msg="Updated phase Running -> Error" namespace=local workflow=testwf
time="2024-02-28T14:37:17.050Z" level=info msg="Updated message  -> error in entry template execution: cannot finish template replacement because the result was invalid JSON" namespace=local workflow=testwf
time="2024-02-28T14:37:17.050Z" level=info msg="Marking workflow completed" namespace=local workflow=testwf
time="2024-02-28T14:37:17.050Z" level=info msg="Checking daemoned children of " namespace=local workflow=testwf
time="2024-02-28T14:37:17.054Z" level=info msg="Workflow update successful" namespace=local phase=Error resourceVersion=26908 workflow=testwf
time="2024-02-28T14:37:17.055Z" level=info msg="cleaning up pod" action=deletePod key=local/testwf-1340600742-agent/deletePod
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by agilgur5** [comment]
> * [x] I can confirm the issue exists when I tested with `:latest`

> v3.4.8

You marked `:latest` as checked, but v3.4.8 is not latest, nor the latest of the 3.4.x patch series. I don't think that would fix the error, but it is worth checking, and the issue template should be filled out correctly

**Comment by winterrobert** [comment]
Thanks @agilgur5 - I tried with the latest helm chart (v3.5.4) but got the same result; I updated the issue to reflect it.

**Comment by jswxstw** [comment]
There is an error in the usage of parameters in the example workflow: 
`inputs.parameters.number_of_transactions` -> `workflow.parameters.number_of_transactions`
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: testwf
spec:
  entrypoint: calculate-memory-limit
  arguments:
    parameters:
    - name: number_of_transactions
      value: 50000

  templates:
  - name: calculate-memory-limit
    inputs:
      parameters:
        - name: number_of_transactions
        - name: doesntwork
          value: "{{= asInt(workflow.parameters.number_of_transactions) > 40000 ? '2222Mi' : '2233Mi' }}"
        - name: works1
          value: "{{= asInt(workflow.parameters.number_of_transactions) == 40000 ? '2222Mi' : '2233Mi' }}"
        - name: works2
          value: "{{= 50000 > 40000 ? '2222Mi' : '2233Mi' }}"
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        print('doesntwork: {{inputs.parameters.doesntwork}}')
        print('works1: {{inputs.parameters.works1}}')
        print('works2: {{inputs.parameters.works2}}')
```
