### ISSUE TITLE
Obtain nonexistent node with agent pod generating many error logs

### ISSUE THREAD

**Issue by jswxstw** [argoproj/argo-workflows#12726]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

https://github.com/argoproj/argo-workflows/blob/a927379f761fbffe733857e7a23d69511fba90de/workflow/controller/exec_control.go#L27

HTTP/Plugin nodes are running in the agent pod and it is shared within the same workflow. Therefore, `woc.nodeID(agentPod)` will generate a nodeID that never exists.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-
spec:
  entrypoint: main
  templates:
    - name: main
      plugin:
        hello: { }
```

### Logs from the workflow controller

```text
time="2023-12-08T10:34:07.212Z" level=error msg="was unable to obtain node for hello-7wwcp-2166136261" namespace=argo workflow=hello-7wwcp
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
