### ISSUE TITLE
header key "x-geoip-city" contains value with non-printable ASCII characters

### ISSUE THREAD

**Issue by lucasfcnunes** [argoproj/argo-workflows#12721]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

# Description

I'm a developer from Brazil and I'm facing a problem with Argo Workflows API. Some of the cities in my country have special characters in their names, such as São Paulo, Belém, or Florianópolis. These characters are part of the diacritical marks that are used to indicate the pronunciation of some letters. However, when I send requests to the Argo Workflows API from these cities, I get an HTTP 500 error. This means that the server encountered an unexpected condition that prevented it from fulfilling the request. I suspect that this is because the API does not handle non-ASCII characters well. This could also affect other languages that use different alphabets, such as Chinese, Japanese, or Hindi. I would like to know how to fix this issue or if there is a workaround for it.

PSs:
- I don't know which exact character is causing the issue (I know that é, ó, ã, ... are all ASCII actually). I could try getting it.
- I'm using [ingress-nginx](https://github.com/kubernetes/ingress-nginx) + [geoip2](https://www.maxmind.com/en/geoip-databases) data add `x-geoip-city` and more to the headers

# Error Message

```json
{"code":13,"message":"header key \"x-geoip-city\" contains value with non-printable ASCII characters"}
```

![image](https://github.com/argoproj/argo-workflows/assets/29926675/87530f99-97d0-4abc-9520-3bf8a7a96f7b)

### Version

v3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
NA (web)
```

### Logs from the workflow controller

```text
NA (web)
```

### Logs from in your workflow's wait container

```text
NA (web)
```

**Comment by agilgur5** [comment]
> * I'm using [ingress-nginx](https://github.com/kubernetes/ingress-nginx) + [geoip2](https://www.maxmind.com/en/geoip-databases) data add `x-geoip-city` and more to the headers

Workaround would be to exclude Argo when adding this header. Normally this would only be selectively added to upstreams that use it, rather than unconditionally added.

> Error Message

Are there any other relevant logs from the Server?

> I suspect that this is because the API does not handle non-ASCII characters well.

I'd check if it handles them inside of Workflows or inside of user info or something... although I'm not sure these are valid characters in all contexts

**Comment by lucasfcnunes** [comment]
A workaround (on ingress-nginx) is adding the annotation `nginx.ingress.kubernetes.io/configuration-snippet` to the ingress with the `more_clear_headers` and `more_clear_input_headers` directives to remove the `x-geoip-city` header from the traffic as follows:

```yaml
# values.yaml.gotmpl (helmfile/helm)
(...)
server:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      external-dns.alpha.kubernetes.io/hostname: &fqdn '{{ .Values.argo_workflows_host }}'
      # TODO: re-add "x-geoip-city" after solving https://github.com/argoproj/argo-workflows/issues/12721
      nginx.ingress.kubernetes.io/configuration-snippet: |-
        more_clear_headers 'x-geoip-city';
        more_clear_input_headers 'x-geoip-city';
(...)
```

# References
- https://github.com/openresty/headers-more-nginx-module
- https://stackoverflow.com/questions/71522076/clearing-all-response-headers-in-nginx
