### ISSUE TITLE
Expr does not work as expected after upgrading to 3.5.5

### ISSUE THREAD

**Issue by vermaxik** [argoproj/argo-workflows#12739]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

We use JSON a lot in our project, and in some cases an object returns `null`. We have conditions or relations between tasks and would like to return `null` if there no nested object instead of non-parsed go template.

For this cases here is [optional chaining](https://github.com/expr-lang/expr/blob/master/docs/language-definition.md#optional-chaining) in expr-lang.

We were waiting for this in 3.5, but  after upgrading from 3.5.4 to 3.5.5 it does not work as expected. But in [playground](https://expr-lang.org/playground) it works as before.

### Version

3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Here is simple workflow:

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: optinal-field
spec:
  arguments:
    parameters:
      - name: config
        value: '{"a": {"nested_a": 1}}'
      - name: config_null
        value: '{"a": null}'
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: a
            value: "{{= fromJSON(workflow.parameters.config).a?.nested_a }}"
          - name: a_null
            value: "{{= toJSON(fromJSON(workflow.parameters.config_null).a?.nested_a ?? null) }}"
      script:
        image: debian:9.4
        command: [bash]
        source: |
          echo "{{= inputs.parameters.a }}"
          echo "{{= inputs.parameters.a_null }}"
```

3.5.4 (empty object returns null)
<img width="552" alt="Screenshot 2024-03-05 at 11 08 37" src="https://github.com/argoproj/argo-workflows/assets/2705386/1f799588-f016-4aee-ae83-6ca417f36659">

3.5.5 
<img width="578" alt="Screenshot 2024-03-05 at 11 00 32" src="https://github.com/argoproj/argo-workflows/assets/2705386/46142a91-9eae-478a-a855-e73de9603ecb">
```


### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by jswxstw** [comment]
expr-lang: `null` should be `nil`, try the workflow as below: 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: optinal-field
spec:
  arguments:
    parameters:
      - name: config
        value: '{"a": {"nested_a": 1}}'
      - name: config_null
        value: '{"a": null}'
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: a
            value: "{{= fromJSON(workflow.parameters.config).a?.nested_a }}"
          - name: a_null
            value: "{{= toJSON(fromJSON(workflow.parameters.config_null).a?.nested_a ?? nil) }}"
      script:
        image: debian:9.4
        command: [bash]
        source: |
          echo "{{= inputs.parameters.a }}"
          echo "{{= inputs.parameters.a_null }}"
```
