### ISSUE TITLE
cannot retry large archived workflow that needs offloading

### ISSUE THREAD

**Issue by heidongxianhua** [argoproj/argo-workflows#12740]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

when I retry a large archived workflow (which is failed), it can not retry because of the server error.
![image](https://github.com/argoproj/argo-workflows/assets/22924371/e2b65621-2ffe-4296-a943-a1251a4cc0b9)
And I have set offloadNodeStatus=true in configmap, due to the related code, the `offloadNodeStatus` is only valid for the workflow which are not archived. As for archived workflow, it is invalid, the workflow will get all infos from nodeOffloadRepo if need and save it to argo_archived_workflows table, then when retry this workflow, it create a new workflow with 
complete information not using nodeOffloadRepo, so it will be failed.

### Version

V3.5.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:
    - - name: run-pod1
        template: run-pod
      - name: run-pod2
        template: run-pod
      - name: run-pod3
        template: run-pod
    - - name: run-pod4
        template: run-pod
      - name: run-pod5
        template: run-pod
      - name: run-pod6
        template: run-pod
    - - name: run-pod7
        template: run-pod
      - name: run-pod8
        template: run-pod
      - name: run-pod9
        template: run-pod
    - - name: run-pod10
        template: run-pod
      - name: run-pod11
        template: run-pod
      - name: run-pod12
        template: run-pod
    - - name: run-pod2-sleep
        template: run-pod-sleep

  - name: run-pod
    steps:
    - - name: run-pod1
        template: run-pod-1
      - name: run-pod2
        template: run-pod-1
      - name: run-pod3
        template: run-pod-1
    - - name: run-pod4
        template: run-pod-1
      - name: run-pod5
        template: run-pod-1
      - name: run-pod6
        template: run-pod-1
  - name: run-pod-1
    steps:
    - - name: run-pod1
        template: run-pod-2
      - name: run-pod2
        template: run-pod-2
      - name: run-pod3
        template: run-pod-2
    - - name: run-pod4
        template: run-pod-2
      - name: run-pod5
        template: run-pod-2
      - name: run-pod6
        template: run-pod-2
  - name: run-pod-2
    steps:
    - - name: run-pod1
        template: run-pod-3
      - name: run-pod2
        template: run-pod-3
      - name: run-pod3
        template: run-pod-3
    - - name: run-pod4
        template: run-pod-3
      - name: run-pod5
        template: run-pod-3
      - name: run-pod6
        template: run-pod-3
  - name: run-pod-3
    steps:
    - - name: run-pod1
        template: run-pod-4
      - name: run-pod2
        template: run-pod-4
      - name: run-pod3
        template: run-pod-4
    - - name: run-pod4
        template: run-pod-4
      - name: run-pod5
        template: run-pod-4
      - name: run-pod6
        template: run-pod-4
  - name: run-pod-4
    steps:
    - - name: run-pod1
        template: run-pod-5
      - name: run-pod2
        template: run-pod-5
      - name: run-pod3
        template: run-pod-5
    - - name: run-pod4
        template: run-pod-5
      - name: run-pod5
        template: run-pod-5
      - name: run-pod6
        template: run-pod-5
  - name: run-pod-5
    container:
      image: docker/whalesay:latest
      command: [python3, -c]
      args: ["print('gfn')"]
  - name: run-pod-sleep ## where running here, we need to stop wf
    container:
      image: docker/whalesay:latest
      command: [python3, -c]
      args: ["print('gfn')\nimport time\ntime.sleep(100)"]
  ttlStrategy:
    secondsAfterCompletion: 3
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```
argo server:
```
level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = etcdserver: request is too large" grpc.code=Internal grpc.method=RetryArchivedWorkflow grpc.service=workflowarchive.ArchivedWorkflowService grpc.start_time="2024-03-04T11:54:36Z" grpc.time_ms=282.849 span.kind=server system=grpc
``` 

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
