### ISSUE TITLE
Validation fails when using expressions in GCS Artifact bucket/key (only when in subordinate step/task)

### ISSUE THREAD

**Issue by ezk84** [argoproj/argo-workflows#12742]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

The following workflow fails validation with the following error:

> Failed to submit workflow: rpc error: code = InvalidArgument desc = templates.steps-with-steps.steps[0].step templates.steps-with-artifact.steps[0].call-template-with-artifact.arguments.input.from, artifact location, or key is required

This only happens when the steps template that instantiates the input artifact is being called in another template. If one submits the workflow with the entrypoint `steps-with-artifact`, then validation passes and the workflow runs as expected.

Another way to bypass the validation error is to move the calculation of the expressions for bucket/key one level up, by creating input parameters as shown here:

```yaml
    - name: steps-with-artifact
      inputs:
        parameters:
          - name: gcs-uri
          - name: bucket
             value: "{{= ( inputs.parameters['gcs-uri'] | split('/') )[2] }}"
          - name: key
             value: "{{= ( inputs.parameters['gcs-uri'] | split('/') )[3:] | join('/') }}"
      steps:
        - - name: call-template-with-artifact
            template: template-with-artifact
            arguments:
              artifacts:
                - name: input
                  gcs:          
                    bucket: "{{ inputs.parameters.bucket }}"
                    key: "{{ inputs.parameters.key }}"
```

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-artifact-expr-
  namespace: argo
spec:
  entrypoint: steps-with-steps
  podGC:
    strategy: "" # prevents logs from disappearing immediately
  ttlStrategy:
    secondsAfterCompletion: 600 # 5 minutes and then it'll be deleted
  arguments:
    parameters:
      - name: gcs-uri
        value: gs://geo-data-engineering/requirements.txt
  templates:
    - name: steps-with-steps
      inputs:
        parameters:
          - name: gcs-uri
      steps:
        - - name: step
            template: steps-with-artifact
            arguments:
              parameters:
                - name: gcs-uri
                  value: "{{inputs.parameters.gcs-uri}}"

    - name: steps-with-artifact
      inputs:
        parameters:
          - name: gcs-uri
      steps:
        - - name: call-template-with-artifact
            template: template-with-artifact
            arguments:
              artifacts:
                - name: input
                  gcs:
                    bucket: "{{= ( inputs.parameters['gcs-uri'] | split('/') )[2] }}"
                    key: "{{= ( inputs.parameters['gcs-uri'] | split('/') )[3:] | join('/') }}"

    - name: template-with-artifact
      inputs:
        artifacts:
          - name: input
            path: /tmp/input
      script:
        image: alpine:3.7
        command: [sh]
        source: |
          cat /tmp/input
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
