### ISSUE TITLE
Retry on PutFile failure in s3

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#12779]
# Summary

This is the case when s3 is used for artifact repository.
Temporary errors may occur when saving logs, and logs may not be saved.
```console
Error (exit code 1): failed to put file: Rate exceeded
```
You can work around this error by retrying with an exponential backoff, but it may not be desirable to rerun the step itself.
Therefore, we propose to implement our own retry with exponential backoff when saving to S3.

https://github.com/argoproj/argo-workflows/blob/ebce8ef7a083c392881aa87e9a330c7ecb0bcd92/workflow/artifacts/s3/s3.go#L221

## Use Cases

This is the case when s3 is used for artifact repository.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by jswxstw** [comment]
`Rate exceeded` is not in `s3TransientErrorCodes` now. I'm not sure if it shoud be added into it.

https://github.com/argoproj/argo-workflows/blob/0270a0faad550363fe3c5f1a9ae565694eeb0829/workflow/artifacts/s3/errors.go#L10-L22

**Comment by panicboat** [comment]
Thanks for the answer.
I tried adding it to workflow-controller-configmap but wasn't sure if it was retrying.
I tried changing the aws credentials to the wrong one and specifying the error in the TRANSIENT_ERROR_PATTERN as a way to reproduce it.

```
Error (exit code 1): timed out waiting for the condition: failed to put file: The AWS Access Key Id you provided does not exist in our records.
```

```yaml
  executor: |
    env:
      - na
me: TRANSIENT_ERROR_PATTERN
        value: "(The AWS Access Key Id you provided does not exist in our records)"
```

[workflow-controller-5b6b9db7bb-xqrnl.log](https://github.com/argoproj/argo-workflows/files/14581253/workflow-controller-5b6b9db7bb-xqrnl.log)

```yaml
metadata:
  name: sparkly-tiger
  namespace: default
  labels:
    example: 'true'
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```
[sparkly-tiger.yaml](https://github.com/argoproj/argo-workflows/files/14581278/sparkly-tiger.yaml.txt)
![image](https://github.com/argoproj/argo-workflows/assets/4182311/81fe332c-9724-4e6b-9be9-65452fc427eb)
