### ISSUE TITLE
Cronworkflow with concurrencyPolicy: Replace/Forbid should not queue up pending workflows

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#12778]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When argo-workflow-controller hits parallelism limit,
the new scheduled cronworkflow will all be in pending regardless of the `concurrencyPolicy`

[Concurrent policy](https://argo-workflows.readthedocs.io/en/latest/cron-workflows/#cronworkflow-options)
Policy that determines what to do if multiple Workflows are scheduled at the same time. Available options: Allow: allow all, Replace: remove all old before scheduling a new, Forbid: do not allow any new while there are old

![image](https://github.com/argoproj/argo-workflows/assets/20961507/2bc1acd2-ab46-475d-a037-6aed5e49e75f)

Although when the parallelism slot is available, the controller will clear up the pending cronworkflow according to `concurrencyPolicy`
There still exists a problem if we have alerts that depend on the number of pending workflows, we could end up with hundreds of pending workflow that triggers the alert.
I think in an ideal scenario, when a cronworkflow is scheduled, It should check existing scheduled pending workflow as well and operate accordingly.

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  name: omniscient-rhino
  namespace: argo
spec:
  schedule: '* * * * *'
  concurrencyPolicy: "Replace"
  workflowSpec:
    entrypoint: argosay
    templates:
        container:
          name: main
          image: argoproj/argosay:v2
          command:
            - /argosay
          args:
            - echo
            - hello
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
