### ISSUE TITLE
proposal: using multiple parameters more efficiently

### ISSUE THREAD

**Issue by dkrynick** [argoproj/argo-workflows#12794]
# Current state

Users can use a configmap to define parameters. This means ~30 parameters create ~100 lines of code in YAML.

This is because Argo requires users to assign every ConfigMap field to a parameter individually which results in a lot of lines of repetitive code in the workflow.

## User story

As an Argo user maintaining the ConfigMap, >100 lines of code for managing parameters becomes very heavy to maintain. 

For example, users often use parameters for 3rd-party tool configs, like Spark job configs that have names & paths of storage buckets, config for the Spark application e.g. cpu and memory resources, job specific arguments etc.

```
 inputs:
        parameters:
          - name: name
            valueFrom:
              configMapKeyRef:
                name: cm-apps
                key: nameTpsipMalicious
          - name: imagePullSecrets
            valueFrom:
              configMapKeyRef:
                name: cm-images
                key: imagePullSecrets
          - name: nodeSelectorKey
            valueFrom:
              configMapKeyRef:
                name: cm-cluster
                key: nodeSelectorKey
          - name: nodeSelectorValue
            valueFrom:
              configMapKeyRef:
                name: cm-cluster
                key: nodeSelectorValue
          - name: objectStorageSecret
            valueFrom:
              configMapKeyRef:
                name: cm-cluster
                key: objectStorageSecret
          - name: objectStorageAccessKeyRef
            valueFrom:
              configMapKeyRef:
                name: cm-cluster
                key: objectStorageAccessKeyRef
          - name: objectStorageSecretKeyRef
            valueFrom:
              configMapKeyRef:
                name: cm-cluster
                key: objectStorageSecretKeyRef
          - name: serviceAccount
            valueFrom:
              configMapKeyRef:
                name: cm-cluster
                key: serviceAccount
          - name: sparkImage
            valueFrom:
              configMapKeyRef:
                name: cm-images
                key: sparkImage
          . . . .
```

# Proposed future state

Introducing `valuesFrom`. Note the plural in the name. This is for use on inputs where you can currently use `valueFrom`.
This can be used in two forms:

ConfigMap
```
inputs:
  parameters:
    - name: cm-cluster
      valuesFrom:
         configMap:
      	     name: cm-cluster
      	     keys:
        	- nodeSelectorKey
        	- nodeSelectorValue
        	- objectStorageSecret
        	- objectStorageAccessKeyRef
        	- objectStorageSecretKeyRef
        	- serviceAccount  
```
Which could then be accessed as `{{ inputs.parameters.cm-cluster.serviceAccount }}`

Outputs
```
inputs:
  parameters:
    - name: other-task
      valuesFrom:
    	 outputs:
      	   source: steps.other
      	   keys:
            - output1
            - output2
inputs:
  parameters:
    - name: other-task
      valuesFrom:
    	 outputs:
      	   source: steps.other
      	   allKeys: true
```
Which could be accessed via `{{ inputs.parameters.other-task.output1 }}`

If you had one massive template you could reduce lines by in a single step importing all of the ConfigMap values and just outputting them as output parameters because then they can be referenced by other steps in the same template as just `{{ tasks.<configmapcopy>.outputs.parameters.name }}`

#### From a Python developer perspective:
It would be helpful to have 1 module with global args in a class, so it’s just one line to hold all the params and that’s imported into the workflow. This is similar to the Airflow devex.

Users might have a config-params.py or config-params.yaml with some dictionary having global variables:

```
RESOURCES = {
  " executorInstances": {
    "stats": {
       "ip1d": 9,
        "domain1d": 9,
       },
    "nomrank": {
        "daily": 4,
        "periodic": 8,
      },
  },
 ...,
}
```
so then I could simply do:
`from config import RESOURCES`

and reference params directly when needed:

```
RESOURCES.stats.ip1d.executorInstances
RESOURCES.stats.domain1d.executorInstances
```
