### ISSUE TITLE
Workflow Details page makes unnecessary Archived request

### ISSUE THREAD

**Issue by ryancurrah** [argoproj/argo-workflows#12814]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Users of Argo Workflows version ~3.5.5~ 3.5 experience an issue where the Workflow Details page attempts to fetch workflows as if they were archived, even when the archived workflows feature is not utilized. This behavior results in an unnecessary API call, leading to the error message `getting archived workflows not supported` and potentially degrading the UI experience.

The issue manifests before the workflow details page loads, with the UI erroneously trying to retrieve an archived version of the workflow based on its UID.

~Initial troubleshooting suggested setting the `ARGO_ARTIFACT_SERVER` environment variable to `false` as a potential fix. However, the error persisted on the workflow details page, and archived logs ceased to function after applying this workaround.~ _edited by agilgur5: this is actually unrelated, see [below comment](https://github.com/argoproj/argo-workflows/issues/12814#issuecomment-2002524593)_.

Discussion on [Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1710510295856659) highlighted a section of the frontend code responsible for this behavior, indicating that the UI checks for an archived workflow status unnecessarily. This check occurs even when archived workflows are not enabled, which should indicate that the workflow is not considered archived.

The conversation concluded with the suggestion to file a GitHub issue to track this problem, aiming for a more concise and efficient handling of workflow status checks in the UI to prevent unnecessary API calls and improve the user experience.

### Potential Solutions:

1. Adjust the frontend code to ensure that archived workflow checks are only performed when necessary, based on the presence of appropriate configuration settings.

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  name: delightful-bear
  namespace: default
  labels:
    example: 'true'
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

Ensure workflow archives are disabled.

View the workflow details page. Look for the error message before the page loads.

![2024-03-15 09 43 39](https://github.com/argoproj/argo-workflows/assets/6209771/d2987e59-ff7e-43c2-a702-a075d98a2e97)
