### ISSUE TITLE
 UI can't get stream logs until main container finished

### ISSUE THREAD

**Issue by ntqp97** [argoproj/argo-workflows#12811]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Argo workflow UI can receive logs from running pods. No need to wait until the pod is completed to get it from the artifact

### Version

v3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Just run a workflow. And see the logs when the task running and logs when the task finished on Argo workflow UI
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by shuangkun** [comment]
Can you paste a workflow to reproduce it?
I run a workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
    - name: whalesay              # name of the template
      container:
        image: centos:latest
        command: ["bin/sh"]
        args:
        - -c
        - |
          for ((i=0; i<=10000;i++)); do echo $i; sleep 10; done
```
And I can get logs in real time
```
time="2024-03-19T02:56:09 UTC" level=info msg="capturing logs" argo=true
0
1
2
time="2024-03-19T02:56:37 UTC" level=debug msg="ignore signal urgent I/O condition" argo=true
3

```
