### ISSUE TITLE
Support exitCode on aggregated output

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#12853]
# Summary

Currently argo only supports using aggregated outputs (e.g. `tasks.execute-parallel-steps.outputs.result`) in parameter 
https://argo-workflows.readthedocs.io/en/stable/walk-through/loops/#accessing-the-aggregate-results-of-a-loop

but not aggregated exitCode `tasks.execute-parallel-steps.outputs.exitCode` or `tasks.execute-parallel-steps.exitCode`,
this could be useful when we want to determine which direction the workflow should proceed after the the `withParam`/`withSequence`/`withItems` step.

We would like to use the following workflow construct
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loop-test-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: execute-parallel-steps
          template: print-json-entry
          arguments:
            parameters:
            - name: index
              value: '{{item}}'
          withParam: '[0, 1]'
        - name: call-access-aggregate-output
          depends: "execute-parallel-steps.Failed"
          template: access-aggregate-output
          arguments:
            parameters:
            - name: aggregate-results
              value: '{{tasks.execute-parallel-steps.exitCode}}'  # 👈
  - name: print-json-entry
    inputs:
      parameters:
      - name: index
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit {{inputs.parameters.index}}"]
  - name: access-aggregate-output
    inputs:
      parameters:
      - name: aggregate-results
        value: 'no-value'
    script:
      image: alpine:latest
      command: [sh]
      source: |
        echo 'inputs.parameters.aggregate-results: "{{inputs.parameters.aggregate-results}}"'
```

 `tasks.execute-parallel-steps.exitCode` passes template validation but won't evaluate
![image](https://github.com/argoproj/argo-workflows/assets/20961507/530a2e10-8a55-43fd-83a7-6d33f6732ed0)

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.
