### ISSUE TITLE
OSS client  PutObject not support file larger than 5Gi

### ISSUE THREAD

**Issue by AlbeeSo** [argoproj/argo-workflows#12877]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When I tried to put a huge output file larger than 5Gi to aliyun OSS, I received such error messages in wait container:
```
time="2024-04-03T10:10:37.725Z" level=info msg="OSS Save path: /tmp/argo/outputs/artifacts/out.tgz, key: argo-workflows/test/big"
time="2024-04-03T10:10:37.804Z" level=warning msg="failed to put file: oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage=\"Post body size must be less than 5G.\", RequestId=660D2B1DAFD89A3732CCE935, Ec=0017-00000102"
time="2024-04-03T10:10:37.804Z" level=warning msg="Non-transient error: oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage=\"Post body size must be less than 5G.\", RequestId=660D2B1DAFD89A3732CCE935, Ec=0017-00000102"
time="2024-04-03T10:10:37.804Z" level=info msg="Save artifact" artifactName=out duration=79.453168ms error="oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage=\"Post body size must be less than 5G.\", RequestId=660D2B1DAFD89A3732CCE935, Ec=0017-00000102" key=argo-workflows/test/big
time="2024-04-03T10:10:37.804Z" level=error msg="executor error: oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage=\"Post body size must be less than 5G.\", RequestId=660D2B1DAFD89A3732CCE935, Ec=0017-00000102"
```

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: alpine:latest
        command:
          - sh
          - -c
        args:
          - |
            mkdir -p /out
            dd if=/dev/random of=/out/testfile.txt bs=20M count=1024
            echo "created files!"
      outputs:
        artifacts:
          - name: out
            path: /out/testfile.txt
            oss:
              endpoint: http://oss-cn-zhangjiakou-internal.aliyuncs.com
              bucket: bucket
              key: argo-workflows/test/bigfile
              accessKeySecret:
                name: my-argo-workflow-credentials
                key: accessKey
              secretKeySecret:
                name: my-argo-workflow-credentials
                key: secretKey
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
