### ISSUE TITLE
Suspend enum input ignores default value

### ISSUE THREAD

**Issue by artem-zherdiev-ingio** [argoproj/argo-workflows#12896]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Enum ignores default input values with suspend, users have to manually choose value everytime and it's not possible to see which value was as default. Outputs are also empty if not select value by hand.
![image](https://github.com/argoproj/argo-workflows/assets/114490731/ba37d54a-4cf6-47c4-ae93-9e67fdd6faf6)
![image](https://github.com/argoproj/argo-workflows/assets/114490731/199a9d7e-2c1f-4cbe-b071-389ac8fcec3e)

Expectation: if suspend inputs have a default value, the enum has it prepopulated as well as regular input.

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: broken-enum
  namespace: workflows
spec:
  serviceAccountName: workflows-executor

  entrypoint: pipeline
  templates:
    - name: wait
      suspend:
        duration: '15m'
      inputs:
        parameters:
          - name: input
          - name: select
            enum:
              - default
              - option1
              - option2
              - option3
      outputs:
        parameters:
          - name: input
            valueFrom:
              supplied: {}
          - name: select
            valueFrom:
              supplied: {}

    - name: pipeline
      dag:
        tasks:
          - name: wait
            template: wait
            arguments:
              parameters:
                - name: input
                  value: default
                - name: select
                  value: default
```

### Logs from the workflow controller

```text
time="2024-04-05T12:35:24.738Z" level=info msg="Processing workflow" Phase= ResourceVersion=285746611 namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=info msg="Task-result reconciliation" namespace=workflows numObjs=0 workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=info msg="Updated phase  -> Running" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=info msg="DAG node broken-enum-w94q2 initialized Running" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=warning msg="was unable to obtain the node for broken-enum-w94q2-2533498415, taskName wait"
time="2024-04-05T12:35:24.768Z" level=warning msg="was unable to obtain the node for broken-enum-w94q2-2533498415, taskName wait"
time="2024-04-05T12:35:24.768Z" level=info msg="All of node broken-enum-w94q2.wait dependencies [] completed" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=info msg="Suspend node broken-enum-w94q2-2533498415 initialized Pending" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=info msg="node broken-enum-w94q2.wait suspended" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=info msg="node broken-enum-w94q2-2533498415 phase Pending -> Running" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=info msg="TaskSet Reconciliation" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.768Z" level=info msg=reconcileAgentPod namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:24.780Z" level=info msg="Workflow update successful" namespace=workflows phase=Running resourceVersion=285746612 workflow=broken-enum-w94q2
time="2024-04-05T12:35:34.781Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=285746612 namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:34.782Z" level=info msg="Task-result reconciliation" namespace=workflows numObjs=0 workflow=broken-enum-w94q2
time="2024-04-05T12:35:34.782Z" level=info msg="node broken-enum-w94q2.wait suspended" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:34.782Z" level=info msg="TaskSet Reconciliation" namespace=workflows workflow=broken-enum-w94q2
time="2024-04-05T12:35:34.782Z" level=info msg=reconcileAgentPod namespace=workflows workflow=broken-enum-w94q2
```

### Logs from in your workflow's wait container

```text
-
```
