### ISSUE TITLE
" no artifact logs are available " when workflow is achived.

### ISSUE THREAD

**Issue by liudongqing** [argoproj/argo-workflows#12948]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

We just upgrade the argo workflow from 3.4.4 to 3.5.5. We enabled archive 
```
persistence:
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
    # save the entire workflow into etcd and DB
    nodeStatusOffLoad: true
    # enable archiving of old workflows
    archive: true
    postgresql:
```
but didn't enable archive logs.
```
artifactRepository:
  # -- Archive the main container logs as an artifact
  archiveLogs: false

```
Before upgrade, we can see logs of the finished workflow (either success or fail) from UI(the server gets the log from pod I guess), but after upgrade, the UI will complain " no artifact logs are available "  and no logs returned.

Is it an expected result ? or is any configuration item controlling this behavior ?

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
any workflows
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
> Is it correct for a finished workflow became archived immediately?

A Workflow is labeled for archiving when [it completes](https://github.com/argoproj/argo-workflows/blob/88304568af5b8222344cde8e5b96d1a8484a50f8/workflow/controller/operator.go#L2362) and when that label [is detected](https://github.com/argoproj/argo-workflows/blob/88304568af5b8222344cde8e5b96d1a8484a50f8/workflow/controller/controller.go#L1070-L1084), archiving is kicked off

That is generally independent of deletion, however, which is based on your TTL or `retentionPolicy`.
It sounds like you have a longer TTL potentially, and so you have Workflows that are simultaneously in the archive and still in the cluster? In that case, the pod logs should still be retrievable.

I think I see the issue here, it's probably not falling back to Pod logs properly in 3.5.

3.5 unified the Archived + Live UI into one page (#11121) so there is no distinction now in the UI. In particular, [this line](https://github.com/argoproj/argo-workflows/blob/910a9aabce5de6568b54350c181a431f8263605a/ui/src/app/shared/services/workflows-service.ts#L208) would previously only be triggered if you were navigating archived workflows specifically, but now it can be triggered on a live workflow that is also archived. The comment above that line is not quite correct in your case

**Comment by y-elip** [comment]
@agilgur5 Hello, any idea when this degradation will be fixed?
It is preventing us to update to newer version of Argo-Workflows, because having access to completed or failed workflows logs is important part of our daily routine

**Comment by agilgur5** [comment]
> Hello, any idea when this degradation will be fixed?

No, [any updates](https://justinmayer.com/posts/any-updates/) [would be in the thread](https://sindresorhus.com/blog/issue-bumping). PRs welcome.

> having access to completed or failed workflows logs is important part of our daily routine

To be clear this only affects users of Archived Workflows with long Workflow or podGC TTLs. If you're not using Archived Workflows or have short TTLs, this doesn't affect you.

**Comment by miltalex** [comment]
I will have a look to see if I can prepare an PR with a fix

**Comment by miltalex** [comment]
Could I ask for some example configuration or a way to reproduce the issue consistently? I tried using archived workflows with different TTL values and strategies without much success and I feel some of my settings might be different from the ones that produce the above bug.

**Comment by y-elip** [comment]
> Could I ask for some example configuration or a way to reproduce the issue consistently? I tried using archived workflows with different TTL values and strategies without much success and I feel some of my settings might be different from the ones that produce the above bug.

Sure. We are using helm chart 0.41.11 for argo-wf ver 3.5.8

```
persistence:
  archive: true
  postgresql:
    <postgresql related block>
controller:
    workflowDefaults:
      spec:
        ttlStrategy:
          secondsAfterSuccess: 432000
          secondsAfterFailure: 864000
          secondsAfterCompletion: 432000
```
