### ISSUE TITLE
Output artifacts by glob/pattern matching

### ISSUE THREAD

**Issue by SkinyMonkey** [argoproj/argo-workflows#1296]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What happened**:

My step generates 10 files, and the number can change.
I want to pass those files to another step.

**What you expected to happen**:

I thought there would be a way to apply pattern matching or globbing.
In the output of a step, in `outputs.artifacts.path` for example:
```yaml
 - name: whalesay
    container:
      image: repo/generate_files
    outputs:
      artifacts:
      - name: json
        path: /tmp/*.json
```

**Comment by Ark-kun** [comment]
AFAIK, Argo archives the whole path be it a single file or directory.

Just remove the pattern and Argo will pass all the files:

```
 - name: whalesay
    container:
      image: repo/generate_files
    outputs:
      artifacts:
      - name: json
        path: /tmp
```

**Comment by SkinyMonkey** [comment]
My example wasn't a good one.
I got a step that generates some json and some pdf plots.
(the step executes an open source program we didn't write)

If I want to pass only the json files to another step?

```
- name: whalesay
    container:
      image: repo/generate_files
    outputs:
      artifacts:
      - name: json
        path: /tmp/*.json
      - name: pdf
        path: /tmp/*.pdf
```

I know i can code an intermediate step to do the work, like move them to a folder or something ...
But that would be very redundant work.
We could try to factor it into something that generate an intermediate step but that would mean code something external that could be added to argo itself.
