### ISSUE TITLE
Incorrect Pod Name in Workflow Failures JSON When Using `templateRef`

### ISSUE THREAD

**Issue by ryancurrah** [argoproj/argo-workflows#12967]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### Slack thread

Issue was originally reported on Slack: https://cloud-native.slack.com/archives/C01QW9QSSSK/p1710875939718929

### What happened/what did you expect to happen?

There appears to be a bug in the `workflow.failures` JSON, specifically in the naming convention used for the pod name. The expected pod name format should include the task name between two hyphens (--) as observed in the UI and via Kubectl commands. However, the JSON output does not reflect this format, leading to potential issues when programmatically using this pod name to perform an action that requires it, like generating a link to the failed task logs.

In our Workflow here is the failure message with the incorrect `podName`.

```json
[
  {
    "displayName": "pr-go-test-cdx-ryaniscool-1179-rck45",
    "message": "",
    "templateName": "main",
    "phase": "Failed",
    "podName": "pr-go-test-cdx-ryaniscool-1179-rck45",
    "finishedAt": "2024-03-19T19:10:00Z"
  },
  {
    "displayName": "setup",
    "message": "Error (exit code 1)",
    "templateName": "",
    "phase": "Failed",
    "podName": "pr-go-test-cdx-ryaniscool-1179-rck45--1909009551",
    "finishedAt": "2024-03-19T19:09:54Z"
  }
]
```

**Details:**
- **Workflow Name:** pr-go-test-cdx-ryaniscool-1179-rck45
- **Expected Pod Name:** pr-go-test-cdx-ryaniscool-1179-rck45-setup-1909009551
- **Actual Pod Name in JSON:** pr-go-test-cdx-ryaniscool-1179-rck45--1909009551

This discrepancy was identified while attempting to provide developers with direct links to the failed workflow step in the UI. The incorrect pod name format prevents these links from functioning correctly.

**Relevant Code:**
The issue seems to originate from the pod name generation logic in the operator.go file:
```go
PodName: wfutil.GeneratePodName(woc.wf.Name, node.Name, node.TemplateName, node.ID, wfutil.GetPodNameVersion()),
```
[View the code here](https://github.com/argoproj/argo-workflows/blob/17087ec7dfbc3968fd5e63d5a7cc8b4f0919d9c0/workflow/controller/operator.go#L410)

**Reproduction:**
The issue can be reproduced using this [Go Playground link](https://go.dev/play/p/KJf2PtliKEh).

**Possible Cause:**
It appears that the `templateName` is empty in the JSON output, which results in the malformed `podName`. This might be due to the use of `templateRef` instead of `template` in the workflow definition, which does not properly set the `templateName`.

**Proposed Solution:**
A potential fix could involve ensuring that the `templateName` is correctly derived from `templateRef` when `templateName` is absent. This could be implemented by checking both `TemplateName` and `TemplateRef.Template` for a valid template name.

**Suggested Enhancement:**
Using the existing exported function  `GetTemplateFromNode` might ensure consistent use of the template name. Find where template name is being read in the codebase and ensure everything uses this exported function instead (if applicable).

https://github.com/argoproj/argo-workflows/blob/b1c37686c35b78fc93a025f37469591ef5de0c1b/workflow/util/util.go#L1059

**Next Steps:**
I propose to create a pull request to address this issue, including appropriate tests to ensure the fix is effective. Additionally, I will investigate how the `displayName` field is set, as it seems to correctly use the template name.

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: error-prone-template
spec:
  templates:
    - name: fail-template
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo 'Simulating a failure'; exit 1"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: error-workflow-
spec:
  entrypoint: main
  onExit: capture-failures  # This is the finalizer step that will run after the main workflow
  templates:
    - name: main
      steps:
        - - name: trigger-error
            templateRef:
              name: error-prone-template
              template: fail-template  # Assuming 'fail-template' is a template in 'error-prone-template' that fails

    - name: capture-failures
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo 'Workflow failures: {{workflow.failures}}'"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
