### ISSUE TITLE
`argo lint` is not case sensitive

### ISSUE THREAD

**Issue by martin-redmaple** [argoproj/argo-workflows#13006]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When attempting to lint a `CronWorkflow` definition file, `argo lint` does not detect keys with incorrect capitalisation. If these are applied using `kubectl`, then the cron workflow does not work as expected. Using `argo cron create` works, as this tool appears to correct the capitalisation.

See example below, with upper case `U` in `schedUle`. I would expect `argo lint` to produce an error. Instead it produces the following:

```
➜  argo lint cronWorkflow.yaml
✔ no linting errors found!
```

### Version

v3.5.6

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cronworkflow
  namespace: argo
spec:
  schedUle: "30 13 * * *"
  timezone: "Europe/London"
  workflowspec:
    entrypoint: main
    templates:
      - name: main
        steps:
          - - name: 1-test-echo
              template: test-echo
      - name: test-echo
        container:
          image: alpine:3.7
          command: [echo, "Hello world"]
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
