### ISSUE TITLE
add volumes support to ExecutorPlugin

### ISSUE THREAD

**Issue by dgolja** [argoproj/argo-workflows#13026]
# Summary

I was looking at the [executor plugins](https://argo-workflows.readthedocs.io/en/stable/executor_plugins/) spec definition, which is basically subset of the [containers definition](https://github.com/argoproj/argo-workflows/blob/main/pkg/plugins/spec/plugin_types.go#L30). I was wondering if we should also extend the spec with the [Volumes](https://pkg.go.dev/k8s.io/api/core/v1#Volume) definition or is there an security issue with that? I am mostly after a way how I could mount secrets/config maps volumes inside the plugin(s).

## Use Cases

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ExecutorPlugin
metadata:
  name: hello
spec:
  sidecar:
    volumes:
      - name: secret-volume
        secret:
          secretName: dotfile-secret
    container:
      # ...
      volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/etc/secret-volume"
      # ...
```
I believe there is value in having access to secret volumes, which can be managed through ESO for specific use cases where you want to dynamically manage secrets for plugins.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.
