### ISSUE TITLE
UI: Containerset nodes receive the wrong podname

### ISSUE THREAD

**Issue by instauro** [argoproj/argo-workflows#13038]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When trying to get the logs for a (any) containerset container in the UI, the user is faced with a blank page. 
![image](https://github.com/argoproj/argo-workflows/assets/123898174/4a2c01ad-aa1e-41e1-9ed2-f340f5c0d4a4)
This is due to the podname being incorrectly calculated for these nodes, which makes the request to the backend return an empty response.

Expected behavior would be to be able to view the logs in similar fashion as for pod nodes.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: graph-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      This workflow demonstrates running a graph of tasks within containers in a single pod.
    workflows.argoproj.io/version: ">= 3.1.0"
spec:
  entrypoint: main
  templates:
    - name: main
      containerSet:
        containers:
          - name: a
            image: argoproj/argosay:v2
          - name: b
            image: argoproj/argosay:v2
            dependencies: ["a"]
          - name: c
            image: argoproj/argosay:v2
            dependencies: ["a"]
          - name: d
            image: argoproj/argosay:v2
            dependencies: ["b", "c"]
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
