### ISSUE TITLE
Can't schedule CronWorkflows using CRON syntax for first day of month

### ISSUE THREAD

**Issue by JPZ13** [argoproj/argo-workflows#13063]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When using the CRON workaround for scheduling a workflow on the first Monday of the month, the workflow-controller and the UI display differently for when the Workflow will run next.

For a CronWorkflow with the following schedule:
```
spec:
  workflowSpec:
    arguments:
      parameters:
        - name: cluster
          value: -------
        - name: max_version
          value: '1.28'
        - name: region
          value: us-east-1
    workflowTemplateRef:
      name: cluster-update
  schedule: 0 4 */100,1-7 * TUE
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  timezone: America/Detroit
```

We would expect the next scheduled time to be in however many days to the first Tuesday of the month, but we're seeing that it shows as being scheduled the Tuesday of this week:
![image (3)](https://github.com/argoproj/argo-workflows/assets/6625432/ed6724f7-afd4-4eb9-a84c-cdfb2a7d3719)

This issue stems from this discussion on Slack: https://cloud-native.slack.com/archives/C01QW9QSSSK/p1715619295295039

Note: I did check that the controller cron package we use is unmaintained with no new commits landing to the default branch or releases in the last four years: https://isitmaintained.com/project/robfig/cron. Maybe upgrading to a new package would solve

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
See above snippet
```

### Logs from the workflow controller

```text
Not needed
```

### Logs from in your workflow's wait container

```text
Not needed
```
