### ISSUE TITLE
Workflow with GPUs on GKE Autopilot fail but run fine as regular jobs

### ISSUE THREAD

**Issue by oliverdain** [argoproj/argo-workflows#13073]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I'm trying to run a workflow on [GKE Autopilot](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview) that uses a GPU. However, it fails to schedule with errors like:

```
task 'gait-train-7hdrn.train' errored: admission webhook "warden-validating.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints. Violations details: {"[denied by autogke-pod-limit-constraints]":["Max cpu requested by init containers for workload 'gait-train-7hdrn-train-3042955063' is higher than the Autopilot maximum of '11'.","Total cpu requested by containers for workload 'gait-train-7hdrn-train-3042955063' is higher than the Autopilot maximum of '11'.","Max memory requested by init containers for workload 'gait-train-7hdrn-train-3042955063' is higher than the Autopilot maximum of '74Gi'.","Total memory requested by containers for workload 'gait-train-7hdrn-train-3042955063' is higher than the Autopilot maximum of '74Gi'."]} Requested by user: 'system:serviceaccount:argo:argo', groups: 'system:serviceaccounts,system:serviceaccounts:argo,system:authenticated'.
```

Note that I see this failure even though I've requested only 5 CPU and 25Gi of RAM. If I run with the same resource requests and node selectors as a K8's Job it schedules and runs just fine.

I'm using node selectors to get an A100 GPU as described [in the autopilot docs](https://cloud.google.com/kubernetes-engine/docs/how-to/autopilot-gpus).

### Version

v3.5.6

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
This workflow fails:


apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gait-train-
  namespace: training
spec:
  entrypoint: run
  podGC:
    deleteDelayDuration: 10m
    strategy: OnWorkflowCompletion
  serviceAccountName: argo-workload
  templates:
  - container:
      args: []
      command:
      - /bin/bash
      - -c
      - nvidia-smi
      env: []
      image: debian:bookworm
      name: train
      resources:
        limits:
          cpu: '5'
          memory: 25Gi
          nvidia.com/gpu: 1
        requests:
          cpu: '5'
          memory: 25Gi
          nvidia.com/gpu: 1
      volumeMounts: []
    daemon: false
    inputs: null
    name: train
    nodeSelector:
      cloud.google.com/compute-class: Accelerator
      cloud.google.com/gke-accelerator: nvidia-tesla-a100
      cloud.google.com/gke-accelerator-count: '1'
  - dag:
      tasks:
      - arguments: null
        dependencies: []
        name: train
        template: train
        withSequence: null
    inputs: null
    name: run
  ttlStrategy:
    secondsAfterCompletion: 432000
```

while this k8's job succeeds (note the image is private so it contains `nvida-smi` but you can substitue `debian:bookworm` and the job will schedule and then fail with a command-not-found error).

```
apiVersion: batch/v1
kind: Job
metadata:
  name: testing
  namespace: training
spec:
  template:
    spec:
      containers:
      - args: []
        command:
        - /bin/bash
        - -c
        - nvidia-smi
        env: []
        image: us-west1-docker.pkg.dev/infra-88/main/cuda:v1.0.0
        name: train
        resources:
          limits:
            cpu: '5'
            memory: 25Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '5'
            memory: 25Gi
            nvidia.com/gpu: '1'
        volumeMounts: []
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      restartPolicy: Never
      terminationGracePeriodSeconds: 60
  ttlSecondsAfterFinished: 600
```
```


### Logs from the workflow controller

```text
time="2024-05-21T17:55:33.551Z" level=info msg="Processing workflow" Phase= ResourceVersion=28791416 namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.562Z" level=info msg="Task-result reconciliation" namespace=training numObjs=0 workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.562Z" level=info msg="Updated phase  -> Running" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.562Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.562Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.562Z" level=info msg="DAG node gait-train-wvpj5 initialized Running" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.562Z" level=warning msg="was unable to obtain the node for gait-train-wvpj5-3685538568, taskName train"
time="2024-05-21T17:55:33.563Z" level=warning msg="was unable to obtain the node for gait-train-wvpj5-3685538568, taskName train"
time="2024-05-21T17:55:33.563Z" level=info msg="All of node gait-train-wvpj5.train dependencies [] completed" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.563Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.563Z" level=info msg="Pod node gait-train-wvpj5-3685538568 initialized Pending" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.667Z" level=warning msg="Non-transient error: admission webhook \"warden-validating.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-pod-limit-constraints]\":[\"Max cpu requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Total cpu requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Max memory requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\",\"Total memory requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\"]}\nRequested by user: 'system:serviceaccount:argo:argo', groups: 'system:serviceaccounts,system:serviceaccounts:argo,system:authenticated'."
time="2024-05-21T17:55:33.667Z" level=info msg="Failed to create pod gait-train-wvpj5.train (gait-train-wvpj5-train-3685538568): admission webhook \"warden-validating.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-pod-limit-constraints]\":[\"Max cpu requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Total cpu requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Max memory requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\",\"Total memory requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\"]}\nRequested by user: 'system:serviceaccount:argo:argo', groups: 'system:serviceaccounts,system:serviceaccounts:argo,system:authenticated'." namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.667Z" level=warning msg="Non-transient error: admission webhook \"warden-validating.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-pod-limit-constraints]\":[\"Max cpu requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Total cpu requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Max memory requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\",\"Total memory requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\"]}\nRequested by user: 'system:serviceaccount:argo:argo', groups: 'system:serviceaccounts,system:serviceaccounts:argo,system:authenticated'."
time="2024-05-21T17:55:33.667Z" level=error msg="Mark error node" error="admission webhook \"warden-validating.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-pod-limit-constraints]\":[\"Max cpu requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Total cpu requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Max memory requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\",\"Total memory requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\"]}\nRequested by user: 'system:serviceaccount:argo:argo', groups: 'system:serviceaccounts,system:serviceaccounts:argo,system:authenticated'." namespace=training nodeName=gait-train-wvpj5.train workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.667Z" level=info msg="node gait-train-wvpj5-3685538568 phase Pending -> Error" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.667Z" level=info msg="node gait-train-wvpj5-3685538568 message: admission webhook \"warden-validating.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-pod-limit-constraints]\":[\"Max cpu requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Total cpu requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Max memory requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\",\"Total memory requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\"]}\nRequested by user: 'system:serviceaccount:argo:argo', groups: 'system:serviceaccounts,system:serviceaccounts:argo,system:authenticated'." namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.667Z" level=info msg="node gait-train-wvpj5-3685538568 finished: 2024-05-21 17:55:33.667802218 +0000 UTC" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.667Z" level=error msg="Mark error node" error="task 'gait-train-wvpj5.train' errored: admission webhook \"warden-validating.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-pod-limit-constraints]\":[\"Max cpu requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Total cpu requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Max memory requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\",\"Total memory requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\"]}\nRequested by user: 'system:serviceaccount:argo:argo', groups: 'system:serviceaccounts,system:serviceaccounts:argo,system:authenticated'." namespace=training nodeName=gait-train-wvpj5.train workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.668Z" level=info msg="node gait-train-wvpj5-3685538568 message: task 'gait-train-wvpj5.train' errored: admission webhook \"warden-validating.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-pod-limit-constraints]\":[\"Max cpu requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Total cpu requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '11'.\",\"Max memory requested by init containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\",\"Total memory requested by containers for workload 'gait-train-wvpj5-train-3685538568' is higher than the Autopilot maximum of '74Gi'.\"]}\nRequested by user: 'system:serviceaccount:argo:argo', groups: 'system:serviceaccounts,system:serviceaccounts:argo,system:authenticated'." namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.668Z" level=info msg="Outbound nodes of gait-train-wvpj5 set to [gait-train-wvpj5-3685538568]" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.668Z" level=info msg="node gait-train-wvpj5 phase Running -> Error" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.668Z" level=info msg="node gait-train-wvpj5 finished: 2024-05-21 17:55:33.668304282 +0000 UTC" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.668Z" level=info msg="TaskSet Reconciliation" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.668Z" level=info msg=reconcileAgentPod namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.668Z" level=info msg="Updated phase Running -> Error" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.668Z" level=info msg="Marking workflow completed" namespace=training workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.674Z" level=info msg="cleaning up pod" action=deletePod key=training/gait-train-wvpj5-1340600742-agent/deletePod
time="2024-05-21T17:55:33.683Z" level=info msg="Workflow update successful" namespace=training phase=Error resourceVersion=28791419 workflow=gait-train-wvpj5
time="2024-05-21T17:55:33.684Z" level=info msg="Queueing Error workflow training/gait-train-wvpj5 for delete in 120h0m0s due to TTL"
```

### Logs from in your workflow's wait container

```text
$ kubectl logs -n argo -c wait -l "workflows.argoproj.io/workflow=gait-train-wvpj5,workflow.argoproj.io/phase!=Succeeded"
No resources found in argo namespace.
$ kubectl logs -n training -c wait -l "workflows.argoproj.io/workflow=gait-train-wvpj5,workflow.argoproj.io/phase!=Succeeded"
No resources found in training namespace.
```
```
