### ISSUE TITLE
Archived workflows deletion with GC stopped working after move to namespace install

### ISSUE THREAD

**Issue by utkarsh079** [argoproj/argo-workflows#13108]
### Pre-requisites

- [X] I have double-checked my configuration
- [ ] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

We have lately noticed that in all the clusters where we moved to namespace install for workflow controllers, deletion of archived workflow has stopped.

### Version

v3.0.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

ConfigMap:
```YAML
#containerRuntimeExecutor: emissary
podGCGracePeriodSeconds: 60
executor:
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
  env:
    - name: GCE_METADATA_TIMEOUT
      value: 10s
persistence:
  archive: true
  archiveTTL: 10d
  nodeStatusOffLoad: true
  postgresql:
    port:<>
    host: <>
    database: argoworkflows
    tableName: argo_workflows
    userNameSecret:
      name: <>
      key: username
    passwordSecret:
      name: <>
      key: password
workflowDefaults:
  spec:
    ttlStrategy:
      secondsAfterCompletion: 10
      secondsAfterFailure: 20
      secondsAfterSuccess: 10
sso:
  clientId:
    key: client-id
    name: <>
  clientSecret:
    key: client-secret
    name: <>
  issuer: <>
  rbac:
    enabled: true
  scopes:
  - groups
  - email
  sessionExpiry: 168h
```

Controller deployment:
```yaml
containers:
    - name: controller
      image: <>/workflow-controller:latest
      command:
        - workflow-controller
      args:
        - '--configmap'
        - workflow-controller-configmap
        - '--loglevel'
        - warn
        - '--gloglevel'
        - '3'
        - '--namespaced'
        - '--workflow-workers'
        - '128'
        - '--workflow-ttl-workers'
        - '32'
        - '--pod-cleanup-workers'
        - '32'
        - '--qps'
        - '60'
        - '--burst'
        - '90'
```

### Logs from the workflow controller

```text
No errors or warning related to GC in logs
```

### Logs from in your workflow's wait container

```text
No errors or warning related to GC in logs
```
