### ISSUE TITLE
Argo Workflow MetricsError: Custom Metrics Unable to Resolve Output variables

### ISSUE THREAD

**Issue by yang-wang11** [argoproj/argo-workflows#13118]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I am encountering an issue with my Argo Workflow template related to the metrics configuration. The error message indicates that it is unable to substitute parameters for the metric count and fails to resolve {{steps.generate.outputs.result}}.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: custom-metrics-
spec:
  entrypoint: output-parameter
  metrics:
    prometheus:
      - name: count
        labels:
          - key: app
            value: argo
        help: "Count of the generated number"
        gauge:
          value: "{{steps.generate.outputs.result}}"
  templates:
  - name: output-parameter
    steps:
    - - name: generate
        template: generator
    - - name: print
        template: printer
        arguments:
          parameters:
          - name: count
            value: "{{steps.generate.outputs.result}}"

  - name: generator
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 10 | tee /tmp/count"]  
    outputs:
      parameters:
      - name: count 
        valueFrom:
          path: /tmp/count 

  - name: printer
    inputs:
      parameters:
      - name: count
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.count}}"]
```

### Logs from the workflow controller

```text
# argo get custom-metrics-65qbp
Name:                custom-metrics-65qbp
Status:              Succeeded
Conditions:          
 PodRunning          False
 Completed           True
✖ MetricsError unable to substitute parameters for metric 'count': failed to resolve {{steps.generate.outputs.result}}

# kubectl logs -n argo deploy/workflow-controller | grep custom-metrics-65qbp
{"level":"info","msg":"TaskSet Reconciliation","namespace":"maintenance","time":"2024-05-30T09:57:21.741Z","workflow":"custom-metrics-65qbp"}
{"level":"info","msg":"reconcileAgentPod","namespace":"maintenance","time":"2024-05-30T09:57:21.741Z","workflow":"custom-metrics-65qbp"}
{"level":"info","msg":"Updated phase Running -\u003e Succeeded","namespace":"maintenance","time":"2024-05-30T09:57:21.741Z","workflow":"custom-metrics-65qbp"}
{"level":"info","msg":"Marking workflow completed","namespace":"maintenance","time":"2024-05-30T09:57:21.741Z","workflow":"custom-metrics-65qbp"}
{"level":"error","msg":"unable to substitute parameters for metric 'count': failed to resolve {{steps.generate.outputs.result}}","namespace":"maintenance","time":"2024-05-30T09:57:21.742Z","workflow":"custom-metrics-65qbp"}
{"action":"deletePod","key":"maintenance/custom-metrics-65qbp-1340600742-agent/deletePod","level":"info","msg":"cleaning up pod","time":"2024-05-30T09:57:21.747Z"}
{"action":"deletePod","error":"pods \"custom-metrics-65qbp-1340600742-agent\" not found","key":"maintenance/custom-metrics-65qbp-1340600742-agent/deletePod","level":"warning","msg":"failed to clean-up pod","time":"2024-05-30T09:57:21.773Z"}
{"level":"warning","msg":"Non-transient error: pods \"custom-metrics-65qbp-1340600742-agent\" not found","time":"2024-05-30T09:57:21.773Z"}
{"level":"info","msg":"Workflow update successful","namespace":"maintenance","phase":"Succeeded","resourceVersion":"448906","time":"2024-05-30T09:57:21.774Z","workflow":"custom-metrics-65qbp"}
```

### Logs from in your workflow's wait container

```text
# kubectl logs -c wait -l workflows.argoproj.io/workflow=custom-metrics-65qbp,workflow.argoproj.io/phase!=Succeeded                                                                                                            
{"deadline":"0001-01-01T00:00:00Z","includeScriptOutput":true,"level":"info","msg":"Executor initialized","namespace":"maintenance","podName":"custom-metrics-65qbp-generator-967939906","templateName":"generator","time":"2024-05-30T09:57:03.961Z","version":"\u0026Version{Version:untagged,BuildDate:2024-05-29T20:02:01Z,GitCommit:fce51dfd0d49c521102a2c1a8d661fab742578a5,GitTag:untagged,GitTreeState:clean,GoVersion:go1.21.10,Compiler:gc,Platform:linux/amd64,}"}
{"level":"info","msg":"Starting deadline monitor","time":"2024-05-30T09:57:04.067Z"}
{"error":null,"level":"info","msg":"Main container completed","time":"2024-05-30T09:57:05.067Z"}
{"level":"info","msg":"Capturing script output","time":"2024-05-30T09:57:05.067Z"}
{"level":"info","msg":"Saving output parameters","time":"2024-05-30T09:57:05.067Z"}
{"level":"info","msg":"Saving path output parameter: count","time":"2024-05-30T09:57:05.067Z"}
{"level":"info","msg":"Copying /tmp/count from base image layer","time":"2024-05-30T09:57:05.067Z"}
{"level":"info","msg":"Successfully saved output parameter: count","time":"2024-05-30T09:57:05.067Z"}
{"level":"info","msg":"No output artifacts","time":"2024-05-30T09:57:05.067Z"}
{"level":"info","msg":"Alloc=6542 TotalAlloc=12745 Sys=24165 NumGC=5 Goroutines=8","time":"2024-05-30T09:57:05.126Z"}
{"level":"info","msg":"Starting Workflow Executor","time":"2024-05-30T09:57:14.037Z","version":"untagged"}
{"Duration":1000000000,"Factor":1.6,"Jitter":0.5,"Steps":5,"level":"info","msg":"Using executor retry strategy","time":"2024-05-30T09:57:14.040Z"}
{"deadline":"0001-01-01T00:00:00Z","includeScriptOutput":false,"level":"info","msg":"Executor initialized","namespace":"maintenance","podName":"custom-metrics-65qbp-printer-671601449","templateName":"printer","time":"2024-05-30T09:57:14.040Z","version":"\u0026Version{Version:untagged,BuildDate:2024-05-29T20:02:01Z,GitCommit:fce51dfd0d49c521102a2c1a8d661fab742578a5,GitTag:untagged,GitTreeState:clean,GoVersion:go1.21.10,Compiler:gc,Platform:linux/amd64,}"}
{"level":"info","msg":"Starting deadline monitor","time":"2024-05-30T09:57:14.124Z"}
{"error":null,"level":"info","msg":"Main container completed","time":"2024-05-30T09:57:16.125Z"}
{"level":"info","msg":"No Script output reference in workflow. Capturing script output ignored","time":"2024-05-30T09:57:16.125Z"}
{"level":"info","msg":"No output parameters","time":"2024-05-30T09:57:16.125Z"}
{"level":"info","msg":"No output artifacts","time":"2024-05-30T09:57:16.125Z"}
{"level":"info","msg":"Alloc=7203 TotalAlloc=12720 Sys=20069 NumGC=4 Goroutines=8","time":"2024-05-30T09:57:16.179Z"}
{"level":"info","msg":"Deadline monitor stopped","time":"2024-05-30T09:57:16.205Z"}
```
