### ISSUE TITLE
support a combination of retryPolicy

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#13119]
# Summary

What change needs making?

We want to use both `OnError` and `OnTransientError`
https://argo-workflows.readthedocs.io/en/stable/retries/#retry-policies
But only one type is supported at the moment.

We have workarounds

**workaround 1 `OnError` + expression**
```
  retryStrategy:
    retryPolicy: OnError
    expression: >-
      lastRetry.message contains 'Pod was terminated in response to imminent node shutdown' 
```
but we are facing issue https://github.com/argoproj/argo-workflows/issues/13058

**workaround 2 `OnTransientError` + patterns from `OnError`**
```
  retryStrategy:
    retryPolicy: OnTransientError
...
    env:
      - name: TRANSIENT_ERROR_PATTERN
        value: "(pod_deleted|post workflowtaskresults)"
```
issue: takes time to identify all argo internal error, and every error is a step back in SLA

## Use Cases

When would you use this?
To retry on both argo internal error `OnError` and transient error `OnTransientError`

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.
