### ISSUE TITLE
Metrics Error: failure metric for workflow status not reporting correctly if in WorkflowTemplate

### ISSUE THREAD

**Issue by dpadhiar** [argoproj/argo-workflows#13162]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Included failure metric with condition `when: {{status}} == Failed` in WorkflowTemplate. Expected metric to appear when workflow referencing this template failed however this is not the case. Works when metric is for success. Failure metric works if it is on workflow level instead of template.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dag-task-test
spec:
  entrypoint: dag-task
  templates:
  - name: dag-task
    metrics:
        prometheus:
        - counter:
            value: "1"
          # help: DAG Task Workflow succeeded
          # name: dagtask_workflow_success
          # when: '{{status}} == Succeeded'
          help: DAG Task Workflow failed
          name: dagtask_workflow_failure
          when: '{{status}} == Failed'
    dag:
      tasks:
      - name: TEST-ONE
        template: echo
        arguments:
          parameters: 
            - name: message
              value: "console output-->TEST-{{item.command}}"
            - name: tag
              value: "{{item.tag}}"
        withItems:
          - { tag: TEST-ONE-A, command: ONE-A }
          - { tag: TEST-ONE-B, command: ONE-B }

      - name: TEST-TWO
        template: echo
        arguments:
          parameters: 
            - name: message
              value: "console output-->TEST-{{item.command}}"
            - name: tag
              value: "{{item.tag}}"
        withItems:
          - { tag: TEST-TWO-A, command: TWO-A }
          - { tag: TEST-TWO-B, command: TWO-B }

  - name: echo
    inputs:
      parameters:
      - name: message
      - name: tag
    container:
      image: alpine:3.7
      # command: [echo, "{{inputs.parameters.message}}"]
      # to fail it
      command: ["{{inputs.parameters.message}}"]
----
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-task
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: dag-task-test
              template: dag-task
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
