### ISSUE TITLE
Suspended CronWorkflow still generates Workflows that remain in running state

### ISSUE THREAD

**Issue by Bryce-huang** [argoproj/argo-workflows#13178]
### Pre-requisites

- [X] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Description:
When suspending a CronWorkflow, new workflows are still being generated. However, these workflows remain perpetually in the running state and never complete. This behavior is unexpected, as suspending the CronWorkflow should prevent any new workflows from being created.

Expected Behavior:
When a CronWorkflow is suspended, no new workflows should be generated.

Current Behavior:
Despite the CronWorkflow being suspended, new workflows are still being generated. These generated workflows stay in the running state indefinitely.

Steps to Reproduce:

Create a CronWorkflow with a specified schedule.
Suspend the CronWorkflow using the command:

```
argo cron suspend <cron-workflow-name>
```

Observe that new workflows are still being generated and they remain in the running state.

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  annotations:
    cronworkflows.argoproj.io/last-used-schedule: CRON_TZ=Asia/Shanghai */5 * * *
      *
  creationTimestamp: "2024-06-13T08:49:14Z"
  generation: 38
  labels:
    wfaas-cron-workflow: tetsauto-five
    wfaas-workflow: tetsauto-five
  name: tetsauto-five
  namespace: 1669-1sa
  resourceVersion: "1264987374"
  uid: 1a96eb30-978c-4ac1-8240-3f8ae33926ce
spec:
  failedJobsHistoryLimit: 10
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 5
  suspend: false
  timezone: Asia/Shanghai
  workflowSpec:
    archiveLogs: false
    arguments:
      parameters:
      - name: test
        value: "1234"
      - name: auto
        value: "5678"
    entrypoint: main
    parallelism: 10
    podGC:
      strategy: OnWorkflowCompletion
    podMetadata:
      labels:
        wfaas-cron-workflow: tetsauto-five
        wfaas-workflow: tetsauto-five
    suspend: true
    ttlStrategy:
      secondsAfterCompletion: 864000
    workflowMetadata:
      labels:
        wfaas-cron-workflow: tetsauto-five
        wfaas-workflow: tetsauto-five
    workflowTemplateRef:
      name: gtest
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

normal logs
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
nope
tetsauto-five-1718269200     Running     108m    
tetsauto-five-1718269500     Running     103m    
tetsauto-five-1718269800     Running     98m     
tetsauto-five-1718270400     Running     88m     
tetsauto-five-1718270700     Running     83m     
tetsauto-five-1718271000     Running     78m     
tetsauto-five-1718271300     Succeeded   73m     
tetsauto-five-1718271600     Succeeded   68m     
tetsauto-five-1718271900     Succeeded   63m     
tetsauto-five-1718272200     Succeeded   58m     
tetsauto-five-1718272500     Succeeded   53m     
tetsauto-five-1718272800     Running     48m     
tetsauto-five-1718273100     Running     43m     
tetsauto-five-1718273400     Running     38m     
tetsauto-five-1718273700     Running     33m     
tetsauto-five-1718274000     Running     28m     
tetsauto-five-1718274300     Running     23m     
tetsauto-five-1718274600     Running     18m     
tetsauto-five-1718274900     Running     13m     
tetsauto-five-1718275200     Running     8m30s   
tetsauto-five-1718275500     Running     3m30s   
```

**Comment by Bryce-huang** [comment]
Nobody has the same problem?

**Comment by alfredjingle** [comment]
For anyone else who comes across this: the issue is caused by suspending the workflow that the cron triggers, rather than suspending the cron workflow itself. You can see this in the cron workflow spec shared by @Bryce-huang:

```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
# ...metadata labels, etc
spec:
  failedJobsHistoryLimit: 10
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 5
  suspend: false # THIS SHOULD BE SET TO TRUE TO PREVENT THE CRON WORKFLOW FROM RUNNING
  timezone: Asia/Shanghai
  workflowSpec:
    # ... workflow spec
    suspend: true # This will not stop the cron workflow from running. It just suspends the workflow triggered by the cron job
    ttlStrategy:
      secondsAfterCompletion: 864000
    workflowMetadata:
      labels:
        wfaas-cron-workflow: tetsauto-five
        wfaas-workflow: tetsauto-five
    workflowTemplateRef:
      name: gtest
```
