### ISSUE TITLE
When a workflow is retried, the OnExit node does not retry, and its parent node does not retry in some scenarios

### ISSUE THREAD

**Issue by JasonChen86899** [argoproj/argo-workflows#13184]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

1. OnExit node can retry when a workflow is retried
2. If a parent node has only a succeed child and this child is only onExit node, this parent root can also retry

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: retry-workflow-with-continueon
spec:
  entrypoint: dag
  templates:
    - name: dag
      retryStrategy:
        limit: 2
        retryPolicy: OnError
      dag:
        failFast: false
        tasks:
          - name: success
            template: node-to-exit
            arguments:
              parameters:
                - name: exitCode
                  value: 0
          - name: failure
            template: node-to-exit
            dependencies: [success]
            onExit: on-exit
            arguments:
              parameters:
                - name: exitCode
                  value: 1
          - name: task-after-failure
            template: node-to-exit
            dependencies: [failure]
            arguments:
              parameters:
                - name: exitCode
                  value: 0
          - name: continue
            template: node-to-exit
            continueOn:
              failed: true
            dependencies: [success]
            arguments:
              parameters:
                - name: exitCode
                  value: 2
          - name: task-after-continue
            template: node-to-exit
            dependencies: [continue]
            arguments:
              parameters:
                - name: exitCode
                  value: 0

    - name: node-to-exit
      inputs:
        parameters:
          - name: exitCode
      container:
        image: alpine:3.7
        command: [ sh, "-c", "exit {{inputs.parameters.exitCode}}" ]

    - name: on-exit
      container:
        image: alpine:3.7
        command: [ sh, "-c", "exit 0" ]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
