### ISSUE TITLE
Argo workflow includes synchronization on both mutex and semaphore, only the semaphore is functioning as expected

### ISSUE THREAD

**Issue by uday-mandava** [argoproj/argo-workflows#13182]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

In Argo workflow, we have used both mutex and semaphore synchronization mechanisms to ensure mutual exclusion and limiting the parallelism across workflows. However, upon testing the workflow, we have found that while the semaphore is correctly working, the mutex is not being honored as expected. 

### Version

3.4.16

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
"synchronization": {
      "mutex": {
        "name": "xyz-mutex"
      },
      "semaphore": {
        "configMapKeyRef": {
          "key": "wf-sem-abc",
          "name": "rl-cm-qwerty",
          "optional": null
        }
      }
    }
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

v
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
v
```
