### ISSUE TITLE
Single-node workflow with failed exit handler cannot be retried correctly 

### ISSUE THREAD

**Issue by jswxstw** [argoproj/argo-workflows#13196]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

The demo workflow failed because of exit handler failure.
<img width="134" alt="image" src="https://github.com/argoproj/argo-workflows/assets/18543532/c3db7759-18b1-4653-a043-0ac231b9b1bf">
The succeeded node `workflow-exit-handler-fail` turn to `Error` phase with message: "pod deleted" after manual retry.
<img width="1270" alt="image" src="https://github.com/argoproj/argo-workflows/assets/18543532/cda0653c-2503-4a30-bb86-930764e53cd0">
https://github.com/argoproj/argo-workflows/blob/8f3860d7683068ab4f93bc725eb24dbbaee78e11/workflow/util/util.go#L993-L998
The root node is reset to `Running`, I think this is the root cause.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-exit-handler-fail
spec:
  entrypoint: echo
  onExit: exit-handler
  templates:
  - name: echo
    container:
      image: alpine:3.18
      command: [sh, -c]
      args: ["echo hello-world"]
  - name: fail
    container:
      image: alpine:3.18
      command: [sh, -c]
      args: ["exit 1"]
  - name: exit-handler
    steps:
      - - name: exit-handler-task
          template: fail
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
