### ISSUE TITLE
retry stopped workflow not correct due to skipped pending node

### ISSUE THREAD

**Issue by heidongxianhua** [argoproj/argo-workflows#13210]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

when I stop a DAG workflow and a step is in pending status, then the step will be set to skipped. Then I retry the workflow, the workflow succeed but do nothing.

stop the workflow 
![image](https://github.com/argoproj/argo-workflows/assets/22924371/dfc4d83a-4304-4ddf-a983-da08e359094d)

and then retry it:

![image](https://github.com/argoproj/argo-workflows/assets/22924371/b64fa909-a5e6-4a2b-b67f-e5c966f70092)

### Version

lastest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  generateName: dag-test-
  namespace: argo
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: step1
          template: run-pod-2
        - name: step2
          template: run-pod-2
        - name: step3
          depends: step1.Succeeded && step2.Succeeded #&& (step2 || step2.Failed)
          template: run-pod-1
        - name: step4
          depends: (step3.Succeeded || step3.Failed)
          template: run-pod-2
  - name: run-pod-1
    container:
      image: docker/whalesay:latest
      command: [python3, -c]
      args: ["print('gfn')\nimport time\ntime.sleep(15)"]
  - name: run-pod-2
    container:
      image: docker/whalesay:latest
      command: [python3, -c]
      args: ["print('gfn')"] 
  ttlStrategy:
    secondsAfterCompletion: 3600
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
nothing
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
nothing
```
