### ISSUE TITLE
Download large file from S3 cause memory rise in the init container

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-workflows#1322]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
demo argo yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
spec:
  entrypoint: start

  templates:
    - name: start
      dag:
        tasks:
          - name: demo
            template: demo

    - name: demo
      inputs:
        artifacts:
        # models is 48G
        - name: models
          path: /s3/models
          s3:
            endpoint: ***
            bucket: ***
            key: ##
      container:
        image: demo:beta
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "15"
            memory: "60G"
          limits:
            cpu: "15"
            memory: "65G"
```
we download a big directory(/s3/models) of 48G from s3, we find that the memory of init container is increate to 50G!
![991554972841_ pic_hd](https://user-images.githubusercontent.com/49295268/56010166-2e0fe200-5d15-11e9-9f87-9c9af491430a.jpg)

**What you expected to happen**:
the memory of init container is not very high.

**Anything else we need to know?**:
No

**Environment**:
- Argo version: v2.2.0
- Kubernetes version : Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
