### ISSUE TITLE
UI: Description/tool-tip disappears when you enter a value for one input when submitting a Workflow

### ISSUE THREAD

**Issue by williamle92** [argoproj/argo-workflows#13242]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Hello,

In the workflows UI, when I add a value as one of the inputs, the description/tool-tip disappears for all other fields.

I expect the description/tool-tip to be available when I am adding inputs to a workflow template. 

With a value added as an input:
![image](https://github.com/argoproj/argo-workflows/assets/81194035/d740d04c-64ee-4f7f-85ed-884a6b3e1af8)
With a value set for one of the fields:
![image](https://github.com/argoproj/argo-workflows/assets/81194035/23669417-dddf-4e4e-8f34-0659c21a3ec8)

Thank you for your time!

### Version

v3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
spec:
  templates:
    - name: description
      inputs:
        parameters:
          # required values
          - name: campaign_id
            description: The id of the campaign.
          - name: integration
            enum:
              - users
              - contact_actions
              - responses
            description: The type of integration you want to run.
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
