### ISSUE TITLE
workflow deadline is not ignored for exit handler

### ISSUE THREAD

**Issue by jswxstw** [argoproj/argo-workflows#13252]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

The exit handler exited with code 143.
```shell
Name:                exit-test-pbtxh
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Failed
Message:             child 'exit-test-pbtxh-3591793683' failed
Conditions:
 PodRunning          False
 Completed           True
Created:             Thu Jun 27 10:58:43 +0800 (37 seconds ago)
Started:             Thu Jun 27 10:58:43 +0800 (37 seconds ago)
Finished:            Thu Jun 27 10:58:58 +0800 (22 seconds ago)
Duration:            15 seconds
Progress:            0/2
ResourcesDuration:   0s*(1 cpu),9s*(100Mi memory)

STEP                       TEMPLATE      PODNAME                           DURATION  MESSAGE
 ✖ exit-test-pbtxh         main                                                      child 'exit-test-pbtxh-3591793683' failed
 └───✖ fail                fail          exit-test-pbtxh-fail-3591793683   3s        Error (exit code 1)

 ✖ exit-test-pbtxh.onExit  exit-handler                                              child 'exit-test-pbtxh-4222353037' failed
 └───✖ sleep               sleep         exit-test-pbtxh-sleep-4222353037  6s        Error (exit code 143)
```

wait container logs shows that `time="2024-06-27T02:58:53.000Z" level=info msg="Step exceeded its deadline"`

`ARGO_DEADLINE` is set, which is the root cause.
```yaml
    - name: ARGO_DEADLINE
      value: "2024-06-27T02:58:53Z"
```

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: exit-test-
spec:
  entrypoint: main
  activeDeadlineSeconds: 10
  hooks:
    exit:
      template: exit-handler
  templates:
    - name: main
      steps:
      - - name: fail
          template: fail
    - name: fail
      container:
        image: alpine:3.18
        command: [sh, -c]
        args: ["exit 1"]
    - name: exit-handler
      steps:
      - - name: sleep
          template: sleep
    - name: sleep
      container:
        image: alpine:3.18
        command: [sh, -c]
        args: ["sleep 15"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
time="2024-06-27T02:58:50.269Z" level=info msg="Starting Workflow Executor" version=untagged
time="2024-06-27T02:58:50.273Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2024-06-27T02:58:50.273Z" level=info msg="Executor initialized" deadline="2024-06-27 02:58:53 +0000 UTC" includeScriptOutput=false namespace=argo podName=exit-test-pbtxh-sleep-4222353037 templateName=sleep version="&Version{Version:untagged,BuildDate:2024-06-27T02:30:46Z,GitCommit:ac9cb3ae93bb441bb7ce09b74e99789adf599eae,GitTag:untagged,GitTreeState:clean,GoVersion:go1.21.10,Compiler:gc,Platform:linux/amd64,}"
time="2024-06-27T02:58:50.280Z" level=debug msg="Create workflowtaskresults 201"
time="2024-06-27T02:58:50.281Z" level=info msg="Starting deadline monitor"
time="2024-06-27T02:58:53.000Z" level=info msg="Step exceeded its deadline"
time="2024-06-27T02:58:53.000Z" level=info msg="Killing containers"
time="2024-06-27T02:58:55.283Z" level=info msg="Main container completed" error="<nil>"
time="2024-06-27T02:58:55.283Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2024-06-27T02:58:55.283Z" level=info msg="No output parameters"
time="2024-06-27T02:58:55.283Z" level=info msg="No output artifacts"
time="2024-06-27T02:58:55.283Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: exit-test-pbtxh/exit-test-pbtxh-sleep-4222353037/main.log"
time="2024-06-27T02:58:55.283Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2024-06-27T02:58:55.283Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=exit-test-pbtxh/exit-test-pbtxh-sleep-4222353037/main.log path=/tmp/argo/outputs/logs/main.log
time="2024-06-27T02:58:55.292Z" level=info msg="Save artifact" artifactName=main-logs duration=8.809122ms error="<nil>" key=exit-test-pbtxh/exit-test-pbtxh-sleep-4222353037/main.log
time="2024-06-27T02:58:55.292Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2024-06-27T02:58:55.292Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2024-06-27T02:58:55.296Z" level=debug msg="Create workflowtaskresults 409"
time="2024-06-27T02:58:55.300Z" level=debug msg="Patch workflowtaskresults 200"
time="2024-06-27T02:58:55.300Z" level=info msg="Alloc=7820 TotalAlloc=12727 Sys=19813 NumGC=4 Goroutines=9"
time="2024-06-27T02:58:55.304Z" level=debug msg="Patch workflowtaskresults 200"
time="2024-06-27T02:58:55.304Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
```
