### ISSUE TITLE
Pod validation error when `retries` is used and pod evicted during workflow node pending

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#13259]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Workflow Errored with template validation error when
- a pod is evicted (e.g. due to node eviction)
- during wf node pending phase.

Note: if there's no pod eviction, the template will pass validation and progress successfully

Expect:
pod created and started without error,

### Version

v3.5.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# e.g.
# a workflow with the following podspecpatch

apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  podSpecPatch: |
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            preference:
              matchExpressions:
                - key: eks.amazonaws.com/capacityType
                  operator: "{{=sprig.ternary('NotIn', 'In', sprig.int(retries) > 0)}}"
                  values:
                    - "SPOT"
  retryStrategy:
    affinity:
      nodeAntiAffinity: {}
    backoff:
      duration: 1s
      factor: 2
    limit: 2
    retryPolicy: Always
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "hello world" ]
```

### Logs from the workflow controller

```text
time="2024-06-19T10:21:26.299Z" level=info msg=reconcileAgentPod namespace=default workflow=atlan-databricks-1718777334-b4v7k
time="2024-06-19T10:21:26.300Z" level=info msg="Workflow to be dehydrated" Workflow Size=60917
time="2024-06-19T10:21:26.424Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=76829852 workflow=atlan-databricks-1718777334-b4v7k
time="2024-06-19T10:21:35.618Z" level=info msg="Processing workflow" namespace=default workflow=retry-od-test-srn7q
time="2024-06-19T10:21:35.623Z" level=info msg="Task-result reconciliation" namespace=default numObjs=1 workflow=retry-od-test-srn7q
time="2024-06-19T10:21:35.623Z" level=info msg="task-result changed" namespace=default nodeID=retry-od-test-srn7q-686389397 workflow=retry-od-test-srn7q
time="2024-06-19T10:21:35.623Z" level=info msg="Workflow pod is missing" namespace=default nodeName="retry-od-test-srn7q(0)" nodePhase=Pending recentlyStarted=false workflow=retry-od-test-srn7q
time="2024-06-19T10:21:35.666Z" level=warning msg="Non-transient error: Pod \"retry-od-test-srn7q-argosay-686389397\" is invalid: spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].operator: Invalid value: \"{{=sprig.ternary('NotIn', 'In', sprig.int(retries) > 0)}}\": not a valid selector operator"
time="2024-06-19T10:21:35.667Z" level=info msg="Failed to create pod retry-od-test-srn7q(0) (retry-od-test-srn7q-argosay-686389397): Pod \"retry-od-test-srn7q-argosay-686389397\" is invalid: spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].operator: Invalid value: \"{{=sprig.ternary('NotIn', 'In', sprig.int(retries) > 0)}}\": not a valid selector operator" namespace=default workflow=retry-od-test-srn7q
time="2024-06-19T10:21:35.669Z" level=warning msg="Non-transient error: Pod \"retry-od-test-srn7q-argosay-686389397\" is invalid: spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].operator: Invalid value: \"{{=sprig.ternary('NotIn', 'In', sprig.int(retries) > 0)}}\": not a valid selector operator"
time="2024-06-19T10:21:35.670Z" level=error msg="Mark error node" error="Pod \"retry-od-test-srn7q-argosay-686389397\" is invalid: spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].operator: Invalid value: \"{{=sprig.ternary('NotIn', 'In', sprig.int(retries) > 0)}}\": not a valid selector operator" namespace=default nodeName="retry-od-test-srn7q(0)" workflow=retry-od-test-srn7q
time="2024-06-19T10:21:35.671Z" level=info msg="node retry-od-test-srn7q-686389397 phase Pending -> Error" namespace=default workflow=retry-od-test-srn7q
time="2024-06-19T10:21:35.671Z" level=info msg="node retry-od-test-srn7q-686389397 message: Pod \"retry-od-test-srn7q-argosay-686389397\" is invalid: spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].operator: Invalid value: \"{{=sprig.ternary('NotIn', 'In', sprig.int(retries) > 0)}}\": not a valid selector operator" namespace=default workflow=retry-od-test-srn7q
time="2024-06-19T10:21:35.671Z" level=info msg="node retry-od-test-srn7q-686389397 finished: 2024-06-19 10:21:35.6719243 +0000 UTC" namespace=default workflow=retry-od-test-srn7q
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
