### ISSUE TITLE
Expose workflow start and finish time

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-workflows#1326]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request

**What happened**:
we want to log duration for success workflow

**What you expected to happen**:
should expose both `finishedAt` & `startedAt` value as global variables.
```
status:
  finishedAt: 2019-04-17T18:37:21Z
  ....
  startedAt: 2019-04-17T18:37:11Z
```
We currently have `workflow.status` for `exit-handler` to provide some information for user, but we want to further provide `duration` and `startTime` for user debug/logging purpose.

**Environment**:
- Argo version:
v2.3.0-rc1

- Kubernetes version :
v1.11.8
