### ISSUE TITLE
Submit Workflow UI: parameter description tooltips disappear after changing any parameter values

### ISSUE THREAD

**Issue by XiangningLi** [argoproj/argo-workflows#13278]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When firstly open the `Submit Workflow` panel, each parameter has its description shown with a question-circle tooltip. Once made changes on any parameter value, all description tooltips disappeared and can not bring back, unless reopen the `Submit Workflow` panel.

Initial states:
<img width="300" alt="Screenshot 2024-06-28 at 14 33 18" src="https://github.com/argoproj/argo-workflows/assets/48453354/15254778-db79-4f52-8ee4-14b3664d68ec">

After changing a value:
<img width="300" alt="Screenshot 2024-06-28 at 14 33 27" src="https://github.com/argoproj/argo-workflows/assets/48453354/1e79066b-ed56-4a0b-8ef1-483383f34de5">

### Version

latest (v3.5.8)

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-workflow
spec:
  entrypoint: entrypoint
  arguments:
    parameters:
      - name: parameter-1
        description: 'parameter 1'
      - name: parameter-2
        description: 'parameter 2'
      - name: parameter-3
        description: 'parameter 3'
  templates:
    - name: entrypoint
      inputs:
        parameters:
          - name: parameter-1
          - name: parameter-2
          - name: parameter-3
      steps:
        - - name: hello
            template: hello
            arguments:
              parameters:
                - name: parameter-1
                  value: '{{inputs.parameters.parameter-1}}'
                - name: parameter-2
                  value: '{{inputs.parameters.parameter-2}}'
                - name: parameter-3
                  value: '{{inputs.parameters.parameter-3}}'

    - name: hello
      inputs:
        parameters:
          - name: parameter-1
          - name: parameter-2
          - name: parameter-3
      script:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.parameter-1}}, {{inputs.parameters.parameter-2}}, {{inputs.parameters.parameter-3}}"]
```
