### ISSUE TITLE
exit code is always -1 instead of actual exit code with steps that reference a template defined in the same yaml

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#13297]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

with the below workflow and retrystrategy you would expect it not to retry since exit code 2 is not in the retryStrategy but it will in fact retry because lastRetry.exitCode is always going to -1

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    steps:
    - - name: whalesay1
        template: whalesay1
  - name: whalesay1
    container:
      image: ubuntu:latest
      command: ["/bin/bash", "-c"]
      args: ["exit 2"]
```

```
templateDefaults:
  retryStrategy:
    limit: 1
    retryPolicy: "Always"
    expression: 'lastRetry.status == "Error" or (lastRetry.status == "Failed" and (asInt(lastRetry.exitCode) in [255,137,143] or (asInt(lastRetry.exitCode) in [-1])))'
    backoff:
      duration: "75"
      factor: 1
      maxDuration: "300"
```

### Version

3.4.11

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    steps:
    - - name: whalesay1
        template: whalesay1
  - name: whalesay1
    container:
      image: ubuntu:latest
      command: ["/bin/bash", "-c"]
      args: ["exit 2"]
```
```


### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

see https://github.com/argoproj/argo-workflows/issues/12572#issuecomment-2162093707
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

n/a
```

**Comment by jswxstw** [comment]
I strongly recommend not including `retryStrategy` to `templateDefaults` now, because it will be applied to both template `hello-hello-hello` and `whalesay1`, which causes a lot of meaningless retries.

**Comment by tooptoop4** [comment]
wow @jswxstw yours is even worse, 4 pods run, for me even 2 pods run is bad instead of 1! this is P1 issue right?

**Comment by jswxstw** [comment]
> wow @jswxstw yours is even worse, 4 pods run, for me even 2 pods run is bad instead of 1! this is P1 issue right?

Not really, the workflow I showed is equivalent to the following workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello    
  templates:
  - name: hello-hello-hello
    retryStrategy:
      limit: 1
    steps:
    - - name: whalesay1
        template: whalesay1
  - name: whalesay1
    retryStrategy:
      limit: 1
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["exit 2"]
```
Template `whalesay1` and `hello-hello-hello` both retried two times according to the retryStrategy which is also as expected.
