### ISSUE TITLE
SSO error: `token not valid` after keycloak database restore

### ISSUE THREAD

**Issue by zillani** [argoproj/argo-workflows#13322]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

- argo-workflows configured with keycloak based SSO was working as expected, we performed database restore as part of disaster-recovery process. After the restore, we are not able to login into workflows. observing 401 from the UI
- then I re-created the client secret, (also persisted in keycloak database), but that did not help

I expect login to be successful, instead, I receive "token invalid"

### workflow server logs

The following is the log from workflow-server,
`Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid. see https://argo-workflows.readthedocs.io/en/release-3.5/faq/" grpc.code=Unauthenticated grpc.method=GetUserInfo grpc.service=info.InfoService grpc.start_time="2024-07-04T19:36:31Z" grpc.time_ms=0.099 span.kind=server system=grpc`

as the error here indicates that the token is not valid, I recreated the tokens which is used by the service account, check this,

```yaml
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    workflows.argoproj.io/rbac-rule: '''mwpadmin'' in groups'
    workflows.argoproj.io/rbac-rule-precedence: "1"
  labels:
    argocd.argoproj.io/instance: mav-core
  name: mwp
  namespace: mav-platform
secrets:
- name: mwp-workflow-token
- name: mwp-token-4xk8d
```

### workflow configuration

Below is my workflow configmap's sso configuration,
```yaml
    sso:
      issuer: https://keycloak.foo.local/realms/master
      clientId:
        name: argo-server-sso
        key: client-id
      clientSecret:
        name: argo-server-sso
        key: client-secret
      redirectUrl: https://workflows.foo.local/oauth2/callback
      rbac:
        enabled: true
      scopes:
        - groups
        - email
        - profile
      sessionExpiry: 4h
      insecureSkipVerify: true
```
Below, are my workflow-server arguments, (`--auth-mode=sso`)
```yaml
      - args:
        - server
        - --configmap=argo-workflows-workflow-controller-configmap
        - --auth-mode=sso
        - --secure=false
        - --loglevel
        - info
        - --gloglevel
        - "0"
        - --log-format
        - text
```

### Version
kubernetes: v1.20.15
workflows:  v3.5.4 & latest (tested both)

### Client secret check
I have also verified whether the client-id and secret match that from keycloak (UI & database) or not. & there are no error logs from the keycloak (session created)

```yaml
apiVersion: v1
data:
  client-id: d29ya2Zsb3dz
  client-secret: aGFoWnNRYWY1TVREDACTED1OUJPWWlLb2EwcHhNZ0VwRWo=
````

### Logs from the workflow controller

```text
time="2024-07-08T02:21:34.710Z" level=info msg="Alloc=4612 TotalAlloc=774150 Sys=20837 NumGC=1738 Goroutines=18"
time="2024-07-08T02:22:23.171Z" level=info msg="healthz: current pod is not the leader"
time="2024-07-08T02:23:23.170Z" level=info msg="healthz: current pod is not the leader"
```
