### ISSUE TITLE
No pod logs when upgrading from v3.3 to v3.5

### ISSUE THREAD

**Issue by Andrei-sys** [argoproj/argo-workflows#13330]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

After I did an upgrade from v3.3 to v3.5, there are no pod logs anymore in the ArgoWF UI. Checked the controller SA, Role/RoleBinding, and it should work as it did before.

### Version(s)

v3.5.0

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
        requests:
          memory: 128Mi
          cpu: 100m
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by Joibel** [comment]
v3.5.0 isn't recommended. Can you retest with v3.5.8.

Pod logs are collected from the argo-server, not the controller.

Do you have [log archiving](https://argo-workflows.readthedocs.io/en/latest/configure-archive-logs/) enabled?

You've given very little information here, and log viewing is working for most people in 3.5 which has been out for a while. Please give more information on how you've installed this and what you have changed from the installation manifests.

**Comment by Andrei-sys** [comment]
Hi, indeed the catch was that pod logs are collected from argo-server. I was focusing on the controller part. Thank you, I have added this resource in my Role and now it is working. However, will try to change from v3.5.0.

**Comment by Andrei-sys** [comment]
Hi, although logs reappeared in the Argoworkflows UI, they dissapear after couple of minutes and in version v3.3, the previous one I was using, there was no such behaviour. Do you have any idea how can I made logs persist more. My ttl and GC settings are the following:
```
ttlStrategy:
  secondsAfterCompletion: 3600
volumeClaimGC:
  strategy: OnWorkflowCompletion
podGC:
  strategy: OnWorkflowSuccess
```
