### ISSUE TITLE
name (or sql) filter for archive ttl

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#13336]
currently archive ttl docs show this, would be great if u could filter wfs by some name to not be deleted (or alternatively delete only those name prefixes specified).

## Archive TTL

You can configure the time period to keep archived workflows before they will be deleted by the archived workflow garbage collection function.
The default is forever.

Example:

    persistence: 
      archiveTTL: 10d

**Comment by qingfeng777** [comment]
How about this? Under the `persistence` configuration, add a field named `keepPrefixes`. All matched workflows will not be deleted.
```
    persistence: 
      archiveTTL: 10d
      keepPrefixes:
        - xxxx
        - xxxx
```

**Comment by Joibel** [comment]
> How about this? Under the `persistence` configuration, add a field named `keepPrefixes`. All matched workflows will not be deleted.
> 
> ```yaml
>     persistence: 
>       archiveTTL: 10d
>       keepPrefixes:
>         - xxxx
>         - xxxx
> ```

I'm not sure I like this design.

Prefixes implies that you're naming your workflows in a common, but not otherwise required manner.
Changing the list of preserved archived workflows is done centrally, and for big organizations would require coordination between the teams with the workflows and those with control over the controller.

If we are to stick to something like this I'd probably ask for something more complex such as using label matching for grouping workflows, along with namespace selection. Harder to implement as it needs more columns in the database

```yaml
persistence: 
  archiveTTL: 10d
  ttlOverride: # I dislike this name, naming things is hard
    - labels:
        labelname: value1
        otherlabel: value2
      namespaces:
        - production
      ttl: 20d
```

I was wondering about a new field on the workflow itself, which could specify the archiveTTL for this workflow. This would override the central archiveTTL. It'd still want a new column, but is much simpler in other respects. I prefer this.
