### ISSUE TITLE
`kubectl get wf` is retuning some workflows that are not returned in the workflows or archived workflows API

### ISSUE THREAD

**Issue by madhur-lyric** [argoproj/argo-workflows#13346]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

`kubectl get wf -n {namespace}` returns some workflows not found in the workflows or archived workflows API (fetched without any parameters), but they are returned when fetched or deleted individually using the API: `api/v1/workflows/{namespace}/{workflow-name}`.

### Version(s)

v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N.A.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by Joibel** [comment]
Can you show how we could reproduce this issue?

**Comment by tooptoop4** [comment]
yo @madhur-lyric u got no logs, no examples, nuffin

**Comment by xsolinsx** [comment]
I'm experiencing this
logs seem to be unhelpful (see below)

![image](https://github.com/user-attachments/assets/da59a976-a772-4031-9851-be582d9cffbb)

if I refresh the page the archived one disappears (also I don't understand why only one of them gets archived)

![image](https://github.com/user-attachments/assets/4e762a7b-0667-4f66-b1fb-368463b0cf64)

this is the workflow
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: etls-test
spec:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  serviceAccountName: argo-workflow
  entrypoint: dag
  templates:
    - name: test
      container:
        image: alpine:3
        command:
          - echo
          - "test"
    - name: dag
      dag:
        tasks:
          - name: test
            template: test

```

below some things that the administrator of our cluster was able to retrieve (sorry if they are not related to the flow above, but I had him investigate this on another flow I was testing), I hope it will be helpful

![image](https://github.com/user-attachments/assets/534a576d-2130-40d3-b69e-bdfca31e44d3)
here the -22lcb is archived and we are not able to retrieve it as shown in the following images
![image](https://github.com/user-attachments/assets/6996215f-542f-46e2-ad64-557d4b701014)
![image](https://github.com/user-attachments/assets/d7a92240-bbba-4b06-9b6c-981ef187e4f0)
while if we query it specifically we are able to find it
![image](https://github.com/user-attachments/assets/8d94226a-148c-422b-a804-02bed673a279)
![image](https://github.com/user-attachments/assets/b5c702ce-e6c5-4791-ab7a-468e6d1d858b)

this is a log related to another flow that was archived and is not visible anymore through the GUI
![image](https://github.com/user-attachments/assets/f8713e1c-2844-45f5-9aaf-00ea41e1d93f)

for us this is happening ONLY for archived workflows, but we don't understand why only a few of them get archived while others don't, even if they are all started with the same parameters, etc.
