### ISSUE TITLE
Arifact GC not executing when a workflow has tasks with inline templates

### ISSUE THREAD

**Issue by Kha-Lik** [argoproj/argo-workflows#13354]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I have not checked the latest version of Argo because I don't have control over our environment

**Happened**:
The artifactGC task was not created and the artifacts remained in a GCS bucket

**Expected**: 
The artifactGC task was created for a workflow with inline templates, artifacts were deleted from a GCS bucket

### Version(s)

v3.5.4

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  serviceAccountName: argo-workflow
  entrypoint: artifact-example
  ttlStrategy:
    secondsAfterCompletion: 180
  artifactGC:
    strategy: OnWorkflowCompletion 
    serviceAccountName: argo-workflow
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        inline:
          container:
            image: docker/whalesay:latest
            command: [sh, -c]
            args: ["cowsay hello world | tee /tmp/hello_world.txt"]
          outputs:
            artifacts:
            - name: hello-art
              path: /tmp/hello_world.txt
    - - name: consume-artifact
        inline:
          inputs:
            artifacts:
            - name: message
              path: /tmp/message
          container:
            image: alpine:latest
            command: [sh, -c]
            args: ["cat /tmp/message"]
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"
```

### Logs from the workflow controller

```text
kubectl logs -n argo deployment.apps/argo-workflows-workflow-controller | grep artifact-passing-p2qgn


time="2024-07-16T21:12:49.260Z" level=info msg="Processing workflow" Phase= ResourceVersion=648699592 namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.267Z" level=info msg="Task-result reconciliation" namespace=kddadev6-capture-workflows numObjs=0 workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.267Z" level=info msg="Updated phase  -> Running" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.267Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.268Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.268Z" level=info msg="Steps node artifact-passing-p2qgn initialized Running" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.268Z" level=info msg="StepGroup node artifact-passing-p2qgn-1879951682 initialized Running" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.268Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.269Z" level=info msg="Pod node artifact-passing-p2qgn-1402143536 initialized Pending" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.316Z" level=info msg="Created pod: artifact-passing-p2qgn[0].generate-artifact (artifact-passing-p2qgn--1402143536)" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.316Z" level=info msg="Workflow step group node artifact-passing-p2qgn-1879951682 not yet completed" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.316Z" level=info msg="TaskSet Reconciliation" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.316Z" level=info msg=reconcileAgentPod namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:49.327Z" level=info msg="Workflow update successful" namespace=kddadev6-capture-workflows phase=Running resourceVersion=648699596 workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.317Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=648699596 namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.318Z" level=info msg="Task-result reconciliation" namespace=kddadev6-capture-workflows numObjs=0 workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.319Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.319Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.319Z" level=info msg="node changed" namespace=kddadev6-capture-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=artifact-passing-p2qgn-1402143536 old.message= old.phase=Pending old.progress=0/1 workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.320Z" level=info msg="Step group node artifact-passing-p2qgn-1879951682 successful" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.320Z" level=info msg="node artifact-passing-p2qgn-1879951682 phase Running -> Succeeded" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.320Z" level=info msg="node artifact-passing-p2qgn-1879951682 finished: 2024-07-16 21:12:59.320623319 +0000 UTC" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.320Z" level=info msg="StepGroup node artifact-passing-p2qgn-738926495 initialized Running" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.320Z" level=info msg="SG Outbound nodes of artifact-passing-p2qgn-1402143536 are [artifact-passing-p2qgn-1402143536]" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.320Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.321Z" level=info msg="Pod node artifact-passing-p2qgn-3674481728 initialized Pending" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.343Z" level=info msg="Created pod: artifact-passing-p2qgn[1].consume-artifact (artifact-passing-p2qgn--3674481728)" namespace=kddadev6-capture-workflows workflowartifact-passing-p2qgn
time="2024-07-16T21:12:59.343Z" level=info msg="Workflow step group node artifact-passing-p2qgn-738926495 not yet completed" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.344Z" level=info msg="TaskSet Reconciliation" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.344Z" level=info msg=reconcileAgentPod namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.355Z" level=info msg="Workflow update successful" namespace=kddadev6-capture-workflows phase=Running resourceVersion=648699727 workflow=artifact-passing-p2qgn
time="2024-07-16T21:12:59.362Z" level=info msg="cleaning up pod" action=labelPodCompleted key=kddadev6-capture-workflows/artifact-passing-p2qgn--1402143536/labelPodCompleted
time="2024-07-16T21:13:09.345Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=648699727 namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.347Z" level=info msg="Task-result reconciliation" namespace=kddadev6-capture-workflows numObjs=0 workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.347Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.347Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.347Z" level=info msg="node changed" namespace=kddadev6-capture-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=artifact-passing-p2qgn-3674481728 old.message= old.phase=Pending old.progress=0/1 workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="SG Outbound nodes of artifact-passing-p2qgn-1402143536 are [artifact-passing-p2qgn-1402143536]" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="Step group node artifact-passing-p2qgn-738926495 successful" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="node artifact-passing-p2qgn-738926495 phase Running -> Succeeded" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="node artifact-passing-p2qgn-738926495 finished: 2024-07-16 21:13:09.348391234 +0000 UTC" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="Outbound nodes of artifact-passing-p2qgn-3674481728 is [artifact-passing-p2qgn-3674481728]" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="Outbound nodes of artifact-passing-p2qgn is [artifact-passing-p2qgn-3674481728]" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="node artifact-passing-p2qgn phase Running -> Succeeded" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="node artifact-passing-p2qgn finished: 2024-07-16 21:13:09.348486263 +0000 UTC" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="TaskSet Reconciliation" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg=reconcileAgentPod namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="Updated phase Running -> Succeeded" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.348Z" level=info msg="Marking workflow completed" namespace=kddadev6-capture-workflows workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.353Z" level=info msg="cleaning up pod" action=deletePod key=kddadev6-capture-workflows/artifact-passing-p2qgn-1340600742-agent/deletePod
time="2024-07-16T21:13:09.358Z" level=info msg="Workflow update successful" namespace=kddadev6-capture-workflows phase=Succeeded resourceVersion=648699854 workflow=artifact-passing-p2qgn
time="2024-07-16T21:13:09.360Z" level=info msg="Queueing Succeeded workflow kddadev6-capture-workflows/artifact-passing-p2qgn for delete in 3m0s due to TTL"
time="2024-07-16T21:13:09.439Z" level=info msg="cleaning up pod" action=labelPodCompleted key=kddadev6-capture-workflows/artifact-passing-p2qgn--3674481728/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=artifact-passing-p2qgn,workflow.argoproj.io/phase!=Succeeded


No resources found in argo namespace.
```

**Comment by shuangkun** [comment]
I have reproduced the problem and will see how to solve it.

**Comment by shuangkun** [comment]
After reconfirming, I found that this problem does not exist in the latest version.

**Comment by NeelArle** [comment]
Hi all, I am facing the same problem with version 3.6.10. The argo workflow run is as follows (I tried even without setting service accounts):

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  serviceAccountName: argo-workflow
  entrypoint: artifact-example
  artifactGC:
    strategy: OnWorkflowCompletion 
    serviceAccountName: argo-workflow
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        inline:
          container:
            image: argoproj/argosay:v2
            command: [sh, -c]
            args:
              - |
                echo "hello world" > /tmp/hello_world.txt
          outputs:
            artifacts:
            - name: hello-art
              path: /tmp/hello_world.txt
              artifactGC:
                strategy: OnWorkflowCompletion 
    - - name: consume-artifact
        inline:
          inputs:
            artifacts:
            - name: message
              path: /tmp/message
          container:
            image: alpine:latest
            command: [sh, -c]
            args: ["cat /tmp/message"]
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"
```

Argo workflow controller and server side I detect no errors. The artifactGC strategy also appears to be set up but no Workflow Artifact GC Task is triggered when the workflow is completed

The workflow examples proposed by you, for example the following https://github.com/argoproj/argo-workflows/blob/main/examples/artifact-gc-workflow.yaml works well as expected.

Could you please consider this and re-open the issue?
