### ISSUE TITLE
 argoproj/argo-events#1927: event flow diagram not showing Bitbucket eventsource icon

### ISSUE THREAD

**Issue by shyoon-devops** [argoproj/argo-workflows#13386]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### References
References argoproj/argo-events#1927

### Describe the bug
The workflows are being triggered ok but the event source icon is just missing from the 'event flow' diagram

### Version(s)
v3.5.8

### EventSource & Sensor

```YAML
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: bitbucket
  namespace: argo
spec:
  template:
    serviceAccountName: operate-workflow-sa
  service:
    ports:
      - port: 12000
        targetPort: 12000
  bitbucketserver:
    abc-xxx:
      repositories:
        - projectKey: 'xxx'
          repositorySlug: 'abc-xxx'
      webhook:
        endpoint: /webhook/abc/abc-xxx
        port: '12000'
        method: POST
        url: https://qa-abc.xxx.net
    events:
      - repo:refs_changed
    accessToken:
      name: bitbucketserver-access
      key: token
    webhookSecret:
      name: bitbucketserver-access
      key: secret
    deleteHookOnFinish: true
    bitbucketserverBaseURL: https://bitbucket.xxx.com/rest


apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: xxx-xxx-bitbucket
  namespace: argo
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
  - name: bitbucket-dependency
    eventSourceName: bitbucket
    eventName: abc-xxx
    transform:
      jq: ".body"
    filters:
      dataLogicalOperator: "and"
      data:
      - path: "changes.0.ref.type"
        type: "string"
        value:
        - "TAG"
      - path: "changes.0.type"
        type: "string"
        value:
        - "ADD"
  triggers:
  - template:
      name: xxx-xxx-workflow-trigger
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: xxx-xxx-
              namespace: argo
            spec:
              workflowTemplateRef:
                name: xxx-xxx-new-template
                clusterScope: true
              arguments:
                parameters:
                - name: git-change-ref-id
                  value: ""
                - name: git-change-display-id
                  value: ""
                - name: git-change-type
                  value: ""
                - name: git-change-user
                  value: ""
        parameters:
        - src:
            dependencyName: bitbucket-dependency
            dataKey: changes.0.ref.id
          dest: spec.arguments.parameters.0.value
        - src:
            dependencyName: bitbucket-dependency
            dataKey: changes.0.ref.displayId
          dest: spec.arguments.parameters.1.value
        - src:
            dependencyName: bitbucket-dependency
            dataKey: changes.0.ref.type
          dest: spec.arguments.parameters.2.value
        - src:
            dependencyName: bitbucket-dependency
            dataKey: actor.name
          dest: spec.arguments.parameters.3.value
```

### Screenshot

![image](https://github.com/user-attachments/assets/5df805cc-5ac7-4647-a237-22dc9b813b1a)
