### ISSUE TITLE
UI: Some labels cannot be obtained in `Links`.

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#13390]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

[In the markdown title & description issue](https://github.com/argoproj/argo-workflows/pull/10553) `workflows.argoproj.io/name` and others are enabled, but setting `${metadata.labels.workflows.argoproj.io/name}` will set them to null.

For example, add the following settings.
```yaml
- name: Datadog
  scope: workflow
  url: https://app.datadoghq.com/dashboard/q5s-6jz-xyr?tpl_var_environment[0]=production&tpl_var_workflow_name[0]=${metadata.labels.workflows.argoproj.io/name}
```

https://app.datadoghq.com/dashboard/q5s-6jz-xyr?fromUser=false&refresh_mode=sliding&tpl_var_environment%5B0%5D=production&tpl_var_workflow_name%5B0%5D=null&view=spans&from_ts=1721613850051&to_ts=1721786650051&live=true
![image](https://github.com/user-attachments/assets/c946a3d7-607d-455a-864c-4ebd31e0b483)

This datadog dashboard is only visible to us, but you can see that the retrieval is failing.

### Version(s)

v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# 
metadata:
  name: fantastic-tiger
  namespace: default
  labels:
    example: 'true'
    workflows.argoproj.io/name: fantastic-tiger
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
