### ISSUE TITLE
3.5.9 UI error: `getTemplateNameFromNode is not defined`

### ISSUE THREAD

**Issue by MartinLoeper** [argoproj/argo-workflows#13422]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I clicked the Logs button on my workflow node which is a pod and got the following:

![Screenshot from 2024-08-01 01-15-39](https://github.com/user-attachments/assets/acdb7761-356a-4271-998f-fcf3706c3b83)

The button on the top left works well, but selecting a node and clicking the logs button in the bottom right triggers the exception:
![Screenshot from 2024-08-01 01-26-23](https://github.com/user-attachments/assets/e461c2ef-6495-40a7-8b79-ff24c846f2dd)

### Version(s)

v3.5.9

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
This issue happens no matter which workflow I use, e.g. the example workflow:

metadata:
  name: wonderful-tiger
  namespace: argo
  labels:
    example: 'true'
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
time="2024-07-31T23:11:51.172Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=24285543 workflow=amrest-live-9w47l
time="2024-07-31T23:12:01.174Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=24285543 namespace=argo workflow=amrest-live-9w47l
time="2024-07-31T23:12:01.174Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=amrest-live-9w47l
time="2024-07-31T23:12:01.174Z" level=info msg="task-result changed" namespace=argo nodeID=amrest-live-9w47l-3049899756 workflow=amrest-live-9w47l
time="2024-07-31T23:12:01.174Z" level=info msg="Pod failed: Error (exit code 1)" displayName=live namespace=argo pod=amrest-live-9w47l-run-task-3049899756 templateName=run-task workflow=amrest-live-9w47l
time="2024-07-31T23:12:01.174Z" level=info msg="node changed" namespace=argo new.message="Error (exit code 1)" new.phase=Failed new.progress=0/1 nodeID=amrest-live-9w47l-3049899756 old.message= old.phase=Running old.progress=0/1 workflow=amrest-live-9w47l
time="2024-07-31T23:12:01.175Z" level=info msg="Outbound nodes of amrest-live-9w47l set to [amrest-live-9w47l-3049899756]" namespace=argo workflow=amrest-live-9w47l
time="2024-07-31T23:12:01.175Z" level=info msg="node amrest-live-9w47l phase Running -> Failed" namespace=argo workflow=amrest-live-9w47l
time="2024-07-31T23:12:01.175Z" level=info msg="node amrest-live-9w47l finished: 2024-07-31 23:12:01.175486992 +0000 UTC" namespace=argo workflow=amrest-live-9w47l
```

### Logs from in your workflow's wait container

```text
time="2024-07-31T23:11:42.878Z" level=info msg="Starting Workflow Executor" version=v3.5.9
time="2024-07-31T23:11:42.889Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2024-07-31T23:11:42.889Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo podName=amrest-live-9w47l-run-task-3049899756 templateName=run-task version="&Version{Version:v3.5.9,BuildDate:2024-07-30T06:02:51Z,GitCommit:45b59a6ccf208149321403f6c822a483e4891f79,GitTag:v3.5.9,GitTreeState:clean,GoVersion:go1.21.12,Compiler:gc,Platform:linux/amd64,}"
time="2024-07-31T23:11:42.931Z" level=info msg="Starting deadline monitor"
time="2024-07-31T23:11:53.935Z" level=info msg="Main container completed" error="<nil>"
time="2024-07-31T23:11:53.935Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2024-07-31T23:11:53.935Z" level=info msg="No output parameters"
time="2024-07-31T23:11:53.935Z" level=info msg="No output artifacts"
time="2024-07-31T23:11:53.936Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: amrest-live-9w47l/amrest-live-9w47l-run-task-3049899756/main.log"
time="2024-07-31T23:11:53.936Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2024-07-31T23:11:53.936Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=amrest-live-9w47l/amrest-live-9w47l-run-task-3049899756/main.log path=/tmp/argo/outputs/logs/main.log
time="2024-07-31T23:11:53.944Z" level=info msg="Save artifact" artifactName=main-logs duration=8.360963ms error="<nil>" key=amrest-live-9w47l/amrest-live-9w47l-run-task-3049899756/main.log
time="2024-07-31T23:11:53.944Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2024-07-31T23:11:53.944Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2024-07-31T23:11:53.965Z" level=info msg="Alloc=7936 TotalAlloc=13947 Sys=23397 NumGC=4 Goroutines=10"
```
