### ISSUE TITLE
3.5.10 cli regression on submitting workflow with workflowtemplateref

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#13436]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Submitted a workflow with a `spec.WorkflowTemplateRef` fails on cli version `v3.5.10` with server version `v3.5.8`

```
FATA[2024-08-05T15:16:56.949Z] Failed to parse workflow: strict decoding error: unknown field "spec.WorkflowTemplateRef"
```

Reverted cli to `v3.5.8` and submit works.

```
❯ TAG="v0.0.5"
APP=$(basename $PWD)
CI="../../Operations-argo-workflow-resources/workflows/ci.yaml"
argo -n argo submit ${CI} --watch \
    -p repo=https://github.com/xxx/argo-containers.git \
    -p application-name=${APP} \
    -p image-tag=${TAG} \
    -p dockerfile=${APP}/Dockerfile \
    -p salt-and-hash-image-tag=false \
    -p generate-artifactory-credentials=true \
    -p slack-channels="devopsslacktest techops-alerts-development" \
    -p enable-snyk="false" -v
DEBU[2024-08-05T15:21:24.943Z] CLI version                                   version="{v3.5.10+2582992.dirty 2024-08-01T12:06:39Z 25829927431d9a0f46d17b72ae74aedb8d700884 v3.5.10 dirty go1.22.5 gc darwin/arm64}"
DEBU[2024-08-05T15:21:24.943Z] Client options                                opts="(argoServerOpts=(url=,path=,secure=true,insecureSkipVerify=false,http=false),instanceID=)"
I0805 15:21:24.947533   21079 loader.go:372] Config loaded from file:  /Users/rwong/.kube/.switch_tmp/config.2556292904.tmp
FATA[2024-08-05T15:21:24.953Z] Failed to parse workflow: strict decoding error: unknown field "spec.WorkflowTemplateRef"
```

### Version(s)

v3.5.10,v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-
spec:
  arguments:
    parameters:
      - name: application-name
        value: test
      - name: comment-on-pr
        value: "false"
      - name: container-repo
        value: "us-east4-docker.pkg.dev/xxx/containers"
      - name: dockerfile
        value: ./Dockerfile
      - name: environment-target
        value: STAGING
      - name: environment-type
        value: stage
      - name: generate-artifactory-credentials
        value: false
      - name: golang-build-deps
        value: "false"
      - name: image-tag
        value: latest
      - name: buildkit-extra-args
        value: ""
      - name: repo
        value: https://github.com/xxx/test.git
      - name: revision
        value: main
      - name: salt-and-hash-image-tag
        value: true
      - name: slack-channels
        value: "xxx"
      - name: snyk-tag
        value: ""
      - name: snyk-threshold
        value: ""
      - name: snyk-source-dir
        value: /app
      - name: snyk-bucket
        value: snyk-reports
      - name: enable-snyk
        value: "true"
      - name: enable-snyk-code-scan
        value: "true"
      - name: enable-snyk-dependency-scan
        value: "true"
      - name: enable-snyk-container-scan
        value: "true"
      - name: enable-snyk-notification
        value: "true"
      - name: gate-snyk-code-scan
        value: "false"
      - name: gate-snyk-dependency-scan
        value: "false"
      - name: gate-snyk-container-scan
        value: "false"
      - name: pr-url
        value: ""
  WorkflowTemplateRef:
    name: ci
    clusterScope: true
```
```


### Logs from the workflow controller

```text
N/A. No workflow is created.
```

### Logs from in your workflow's wait container

```text
N/A. No workflow is created.
```
