### ISSUE TITLE
`outputs.result` is not visible unless a later step references it

### ISSUE THREAD

**Issue by wmcnamee-coreweave** [argoproj/argo-workflows#13464]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I expected to be able to see the `results` output from a `script` template in the UI (even if I didn't use it in a later step). However, in all cases, unless a subsequent step references `{{steps.X.outputs.result}}` it is not visible in the UI. 

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/b920b826-f7a5-4bca-ade5-c3bb93ad92d2">

### Version(s)

v3.5.10

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-bug
  namespace: argo-workflows
spec:
  entrypoint: print-message
  templates:
  - name: print-message
    script:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'done'"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
