### ISSUE TITLE
Volume-based artifact passing system

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo-workflows#1349]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

I'd like to implement a feature that automatically mounts a single volume to the workflow pods to passively orchestrate the data passing.

I'm working on implementing this feature and will submit PR once it's ready.

It's possible to implement now on top of Argo, but it might be nice to have it built-in.
I've previously illustrated the proposal in https://github.com/argoproj/argo/pull/1227#issuecomment-472106438

The main idea is to substitute the Argo's "active" way of passing artifacts (copying, packing, uploading/downloading/unpacking) with a passive system that has many advantages:
* Much faster artifact storage I/O. No packing/unpacking. No copying files.
* Artifact size is not limited by main/wait container disk sizes.

Syntax (unresolved):
```yaml
# New syntax
artifactStorage: 
  volume: # Will automatically mount this volume to all Pods in a particular way
    persistentVolumeClaim:
      claimName: vol01

#The rest of the code is the usual artifact-passing syntax
templates:
  - name: producer
    outputs:
      artifacts:
      - name: out-art1
        path: /argo/outputs/out-art1/data
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world > /argo/outputs/out-art1/data"]

  - name: consumer
    inputs:
      artifacts:
      - name: in-art1
        path: /argo/inputs/in-art1/data
    container:
      image: docker/whalesay:latest
      command: [cat, '/argo/inputs/in-art1/data']

  - name: main
    dag:
      tasks:
      - name: producer-task
        template: producer
      - name: consumer-task
        template: consumer
        arguments:
          artifacts:
          - name: in-art1
            from: "{{tasks.producer-task.outputs.artifacts.out-art1}}"
```

Transformed spec:
```yaml
volumes:
  - name: argo-storage
    persistentVolumeClaim:
      claimName: vol01
templates:
  - name: producer
    outputs:
      parameters:
      - name: out-art1-subpath
        value: "{{workflow.uid}}/{{pod.name}}/out-art1/"
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world > /argo/outputs/out-art1/data"]
      volumeMounts:
        - name: argo-storage
          mountPath: /argo/outputs/out-art1/
          subPath: "{{workflow.uid}}/{{pod.name}}/out-art1/"

  - name: consumer
    inputs:
      parameters:
      - name: in-art1-subpath
    container:
      image: docker/whalesay:latest
      command: [cat, '/argo/inputs/in-art1/data']
      volumeMounts:
        - name: argo-storage
          mountPath: /argo/inputs/in-art1/
          subPath: "{{input.parameters.in-art1-subpath}}"
          readOnly: true

  - name: main
    dag:
      tasks:
      - name: producer-task
        template: producer
      - name: consumer-task
        template: consumer
        arguments:
          artifacts:
          - name: in-art1-subpath
            from: "{{tasks.producer-task.outputs.parameters.out-art1-subpath}}"
```

This system becomes becomes better with the https://github.com/argoproj/argo/issues/1329,  https://github.com/argoproj/argo/issues/1348 and https://github.com/argoproj/argo/pull/1300 features.

* https://github.com/argoproj/argo/pull/1300 adds the ability to reference the artifact paths which is required for using generated paths
* https://github.com/argoproj/argo/issues/1348 adds the ability to generate artifact paths. This ensures that the paths are compatible with volume mounts.
* https://github.com/argoproj/argo/issues/1329 allows passing the resolved paths to the downstream tasks without having to hack the command-line.
