### ISSUE TITLE
Workflow failed when using `optional` `subpath` in `withParam`

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argo-workflows#13564]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

```
tianshuangkun@U-4YKHFNR6-2229 local % argo get artifact-passing-subpath-hkrmb
Name:                artifact-passing-subpath-hkrmb
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Failed
Message:             failed to resolve {{steps.hello-world-to-file.outputs.artifacts.foo}}
Conditions:
 PodRunning          False
 Completed           True
Created:             Fri Sep 06 10:55:01 +0800 (17 minutes ago)
Started:             Fri Sep 06 10:55:01 +0800 (17 minutes ago)
Finished:            Fri Sep 06 10:55:09 +0800 (16 minutes ago)
Duration:            8 seconds
Progress:            1/1
ResourcesDuration:   0s*(1 cpu),3s*(100Mi memory)

STEP                               TEMPLATE             PODNAME                                                        DURATION  MESSAGE
 ✖ artifact-passing-subpath-hkrmb  artifact-example                                                                              failed to resolve {{steps.hello-world-to-file.outputs.artifacts.foo}}
 ├───✔ hello-world-to-file         hello-world-to-file  artifact-passing-subpath-hkrmb-hello-world-to-file-1338204656  5s
```

### Version(s)

latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-subpath-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: hello-world-to-file
        template: hello-world-to-file
    - - name: hello-world-to-file2
        template: hello-world-to-file2
        arguments:
          artifacts:
          - name: bar
            from: "{{steps.hello-world-to-file.outputs.artifacts.foo}}"
            optional: true
            subpath: bar.txt
        withParam: "[0, 1]"

  - name: hello-world-to-file
    container:
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: [sh, -c]
      args: ["sleep 1; echo hello world"]
    outputs:
      artifacts:
      - name: foo
        path: /tmp/foo
        optional: true
        archive:
          none: {}

  - name: hello-world-to-file2
    inputs:
      artifacts:
      - name: bar
        path: /tmp/bar.txt
        optional: true
        archive:
          none: {}
    container:
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: [sh, -c]
      args: ["sleep 1; echo hello world"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
