### ISSUE TITLE
ArtifactGC Pod remains in Running state with sidecars of istio service-mesh

### ISSUE THREAD

**Issue by Ankitsachdeva** [argoproj/argo-workflows#13576]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

# Summary

The main container terminated with doing the garbage collection as expected and istio sidecar proxy keeps and running.

Bug:

I have added a pod annotation to kill the istio-proxy container - `workflows.argoproj.io/kill-cmd-istio-proxy: '["pilot-agent", "request", "POST", "quitquitquit"]'`

The istio-proxy sidecar keeps on running and it never gets completed.

Ideal Solution:

The command to kill the istio-proxy container, should be executed once the main container is finished in `ArtifactGCTask`.

ArtifactGC spec in workflow:

```yaml
...
spec:
  entrypoint: main
  serviceAccountName: key-only-sa
  artifactGC:
    strategy: OnWorkflowDeletion
    serviceAccountName: key-only-sa
    podMetadata:
      annotations:
        workflows.argoproj.io/kill-cmd-istio-proxy: '["pilot-agent", "request", "POST", "quitquitquit"]'
```

<details><summary>WorkflowArtifactGCTask</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowArtifactGCTask
metadata:
  creationTimestamp: "2024-09-09T09:53:51Z"
  generation: 1
  labels:
    workflows.argoproj.io/artifact-gc-pod: "3658387271"
  name: key-only-artifacts-b7zfx-artgc-wfdel-4119998894-0
  namespace: argo
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: key-only-artifacts-b7zfx
spec:
  artifactsByNode:
    key-only-artifacts-b7zfx-3900716432:
      archiveLocation:
        s3:
          bucket: my-bucket
          endpoint: s3.amazonaws.com
          key: argo-artifacts/{{pod.name}}
          useSDKCreds: true
      artifacts:
        file:
          archive:
            none: {}
          name: file
          path: /tmp/file/output.txt
          s3:
            key: argo-artifacts/key-only-artifacts-b7zfx-generate-3900716432/output.txt
status:
  artifactResultsByNode:
    key-only-artifacts-b7zfx-3900716432:
      artifactResults:
        file:
          name: file
          success: true
```
</details>

Argo Version:

workflow-controller:3.5.10

### Version(s)

3.5.10

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: key-only-artifacts-
spec:
  entrypoint: main
  serviceAccountName: key-only-sa
  artifactGC:
    strategy: OnWorkflowDeletion
    serviceAccountName: key-only-sa
    podMetadata:
      annotations:
        workflows.argoproj.io/kill-cmd-istio-proxy: '["pilot-agent", "request", "POST", "quitquitquit"]'
  templates:
    - name: main
      dag:
        tasks:
          - name: generate
            template: generate
            retryStrategy:
               limit: "2"
               retryPolicy: "OnError"
          - name: consume
            template: consume
            dependencies:
              - generate
            arguments: 
              artifacts:
              - name: file
                from: "{{tasks.generate.outputs.artifacts.file}}"
    - name: generate
      container:
        image: argoproj/argosay:v2
        args: [ echo, hello world!, /tmp/file/output.txt ]
      outputs:
        artifacts:
          - name: file
            path: /tmp/file/output.txt
            archive:
              none: {}
    - name: consume
      container:
        image: argoproj/argosay:v2
        args: [cat, /tmp/file/output.txt]
      inputs:
        artifacts:
          - name: file
            path: /tmp/file/output.txt
            # s3:
              # key: my-file
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

time="2024-09-09T09:59:11.843Z" level=info msg="Processing workflow" namespace=argo workflow=key-only-artifacts-b7zfx
time="2024-09-09T09:59:11.844Z" level=info msg="Checking daemoned children of " namespace=argo workflow=key-only-artifacts-b7zfx
time="2024-09-09T09:59:21.715Z" level=info msg="Processing workflow" namespace=argo workflow=key-only-artifacts-b7zfx
time="2024-09-09T09:59:21.715Z" level=info msg="Checking daemoned children of " namespace=argo workflow=key-only-artifacts-b7zfx
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l 

time="2024-09-09T09:53:53.701Z" level=info msg="S3 Delete artifact: key: argo-artifacts/key-only-artifacts-b7zfx-generate-3900716432/output.txt"
time="2024-09-09T09:53:53.795Z" level=info msg="Creating minio client using AWS SDK credentials"
time="2024-09-09T09:53:53.944Z" level=info msg="Deleting object from s3" bucket=my-bucket endpoint=s3.amazonaws.com key="argo-artifacts/key-only-artifacts-b7zfx-generate-3900716432/output.txt"
```
