### ISSUE TITLE
ArtifactGC fails if output artifact with non-existent file is configured with `optional: true`

### ISSUE THREAD

**Issue by encigem** [argoproj/argo-workflows#13583]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

What happened?:
   - When configuring Artifact Garbage Collection in a workflow, if the workflow reaches it's deadline before it manages to create a file which is to be used as an output artifact and that artifact is configured with `optional: true` parameter, then the ArtGC pod which runs after the steps are terminated fails with the message: `Error: You need to configure artifact storage. More information on how to do this can be found in the docs: https://argoproj.github.io/argo-workflows/configure-artifact-repository/`
   -  If you remove the `optional: true` config from the offending artifact and re-run, then no artifact GC pod is created when the workflow terminates from deadline exceeded.
   - If you remove the offending artifact item entirely and re-run, no such `Error: You need to configure artifact storage` messages appear and the other artifacts are cleaned as expected when timeout occurs.

What did I expect to happen:
  - I expected the existing artifacts to be cleaned up and the non-existent artifact to be ignored in the ArtGC pod. The ArtGC pod should finish with a success

### Version(s)

v3.4.10, v3.5.10, latest(sha256:4f03ff7ecaef4061dddd2c08f80de4d766b253aa3a57a87e69dd3a797bb42b1e)

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-artgc-
  namespace: argo
spec:
  entrypoint: main
  activeDeadlineSeconds: 20

  volumes:
    - name: emptydir
      emptyDir: {}

  templates:
    - name: main
      dag:
        tasks:
          - name: prepare-data
            template: prepare-data
            arguments:
              parameters: 
              - name: index
                value: "{{item}}"
            withParam: '[1, 2, 3]'
          
    - name: prepare-data
      inputs:
        parameters:
          - name: index
          - name: image
            value: "alpine:latest"
      outputs:
        artifacts:
          # Comment out the 'late-artifact' item and re-run to get a
          # successful artifact garbage collection pod execution
          - name: late-artifact-{{inputs.parameters.index}}
            path: "/empty-dir/late-artifact.txt"
            artifactGC:
              strategy: OnWorkflowCompletion
            optional: true  # removing this will result in no ArtGC pod being run
          - name: abcartifact-{{inputs.parameters.index}}
            path: "/empty-dir/abcartifact.txt"
            artifactGC:
              strategy: OnWorkflowCompletion
            optional: true
          - name: 123artifact-{{inputs.parameters.index}}
            path: "/empty-dir/123artifact.txt"
            artifactGC:
              strategy: OnWorkflowCompletion
            optional: true
      container:
        image: "{{inputs.parameters.image}}"
        volumeMounts:
          - name: emptydir
            mountPath: /empty-dir
        workingDir: /empty-dir
        command: ["sh", "-c"]
        args:
          - |

            set -x
            
            echo Hi > abcartifact.txt
            echo Hi > 123artifact.txt

            # cause timeout
            sleep 20

            echo Hi > late-artifact.txt
```

### Logs from the workflow controller

```text
$  kubectl logs -n argo deploy/workflow-controller | grep test-artgc-pv7h2

time="2024-09-09T15:50:26.593Z" level=info msg="Processing workflow" Phase=Failed ResourceVersion=209475215 namespace=argo workflow=test-artgc-pv7h2
time="2024-09-09T15:50:26.594Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=test-artgc-pv7h2
time="2024-09-09T15:50:36.472Z" level=info msg="Processing workflow" Phase=Failed ResourceVersion=209475215 namespace=argo workflow=test-artgc-pv7h2
time="2024-09-09T15:50:36.472Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=test-artgc-pv7h2
```

### Logs from in your workflow's wait container

```text
$  kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=test-artgc-pv7h2,workflow.argoproj.io/phase!=Succeeded

error: container wait is not valid for pod test-artgc-pv7h2-artgc-wfcomp-2166136261
```
