### ISSUE TITLE
Using the artifacts function of argo to upload application logs to minio, it prompts "no such file or directory"

### ISSUE THREAD

**Issue by zhangconan** [argoproj/argo-workflows#13622]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Using the artifacts function of argo to upload application logs to minio, it prompts "no such file or directory"。 I hope to upload logs to minio normally

### Version(s)

V3.4.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
- name: main
  inputs: {}
  outputs: {}
  metadata: {}
  daemon: true
  steps:
    - - name: '1811663817060106241'
        template: '1811663817060106241'
        arguments: {}
- name: '1811663817060106241'
  inputs: {}
  outputs:
    artifacts:
      - name: service-log
        path: /tmp/service.log
        s3:
          key: /stream-job/mq/logs/1836605842368106496.log
        archive:
          none: {}
  metadata: {}
  container:
    name: ''
    image: >-
      registry.cn-zhangjiakou.aliyuncs.com/images
    command:
      - /bin/sh
      - '-c'
      - java org.springframework.boot.loader.JarLauncher
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    imagePullPolicy: IfNotPresent
- name: exit
  inputs: {}
  outputs: {}
  metadata: {}
  steps:
    - - name: exit-fail
        template: exit-fail
        arguments: {}
- name: exit-fail
  inputs: {}
  outputs: {}
  metadata: {}
  container:
    name: ''
    image: >-
      registry.cn-zhangjiakou.aliyuncs.com/images-failture
    command:
      - /bin/sh
      - '-c'
      - java org.springframework.boot.loader.JarLauncher
    resources: {}
    imagePullPolicy: IfNotPresent
```

### Logs from the workflow controller

```text
time="2024-09-19T11:11:28.094Z" level=info msg="Starting Workflow Executor" version=v3.4.8 
time="2024-09-19T11:11:28.098Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5 
time="2024-09-19T11:11:28.098Z" level=info msg="Starting deadline monitor" 
time="2024-09-19T11:13:10.630Z" level=info msg="Deadline monitor stopped" 
time="2024-09-19T11:13:10.630Z" level=info msg="stopping progress monitor (context done)" error="context canceled" 
time="2024-09-19T11:13:11.146Z" level=warning msg="Non-transient error: context canceled" 
time="2024-09-19T11:13:11.146Z" level=info msg="Main container completed" error="context canceled" 
time="2024-09-19T11:13:11.146Z" level=info msg="No Script output reference in workflow. Capturing script output ignored" 
time="2024-09-19T11:13:11.146Z" level=info msg="No output parameters" 
time="2024-09-19T11:13:11.146Z" level=info msg="Saving output artifacts" 
time="2024-09-19T11:13:11.146Z" level=info msg="Staging artifact: service-log" 
time="2024-09-19T11:13:11.146Z" level=info msg="Copying /tmp/service.log from container base image layer to /tmp/argo/outputs/artifacts/service-log.tgz" 
time="2024-09-19T11:13:11.146Z" level=info msg="/var/run/argo/outputs/artifacts/tmp/service.log.tgz -> /tmp/argo/outputs/artifacts/service-log.tgz" 
time="2024-09-19T11:13:11.146Z" level=error msg="executor error: open /var/run/argo/outputs/artifacts/tmp/service.log.tgz: no such file or directory" 
time="2024-09-19T11:13:11.147Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: argo/2024/09/kafka-consume-1836603978960474112/kafka-consume-1836603978960474112-1811663817060106241-647481992/main.log" 
time="2024-09-19T11:13:11.147Z" level=info msg="Creating minio client using static credentials" endpoint="minio-headless:9000" 
time="2024-09-19T11:13:11.147Z" level=info msg="Saving file to s3" bucket=kernel endpoint="minio-headless:9000" key=argo/2024/09/kafka-consume-1836603978960474112/kafka-consume-1836603978960474112-1811663817060106241-647481992/main.log path=/tmp/argo/outputs/logs/main.log 
time="2024-09-19T11:13:11.151Z" level=info msg="Save artifact" artifactName=main-logs duration=4.93656ms error="<nil>" key=argo/2024/09/kafka-consume-1836603978960474112/kafka-consume-1836603978960474112-1811663817060106241-647481992/main.log 
time="2024-09-19T11:13:11.152Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log 
time="2024-09-19T11:13:11.152Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log" 
time="2024-09-19T11:13:11.201Z" level=info msg="Create workflowtaskresults 201" 
time="2024-09-19T11:13:11.202Z" level=info msg="Alloc=8249 TotalAlloc=16822 Sys=28541 NumGC=5 Goroutines=7" 
time="2024-09-19T11:13:11.202Z" level=fatal msg="open /var/run/argo/outputs/artifacts/tmp/service.log.tgz: no such file or directory"
```

### Logs from in your workflow's wait container

```text
time="2024-09-19T11:11:28.094Z" level=info msg="Starting Workflow Executor" version=v3.4.8 
time="2024-09-19T11:11:28.098Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5 
time="2024-09-19T11:11:28.098Z" level=info msg="Starting deadline monitor" 
time="2024-09-19T11:13:10.630Z" level=info msg="Deadline monitor stopped" 
time="2024-09-19T11:13:10.630Z" level=info msg="stopping progress monitor (context done)" error="context canceled" 
time="2024-09-19T11:13:11.146Z" level=warning msg="Non-transient error: context canceled" 
time="2024-09-19T11:13:11.146Z" level=info msg="Main container completed" error="context canceled" 
time="2024-09-19T11:13:11.146Z" level=info msg="No Script output reference in workflow. Capturing script output ignored" 
time="2024-09-19T11:13:11.146Z" level=info msg="No output parameters" 
time="2024-09-19T11:13:11.146Z" level=info msg="Saving output artifacts" 
time="2024-09-19T11:13:11.146Z" level=info msg="Staging artifact: service-log" 
time="2024-09-19T11:13:11.146Z" level=info msg="Copying /tmp/service.log from container base image layer to /tmp/argo/outputs/artifacts/service-log.tgz" 
time="2024-09-19T11:13:11.146Z" level=info msg="/var/run/argo/outputs/artifacts/tmp/service.log.tgz -> /tmp/argo/outputs/artifacts/service-log.tgz" 
time="2024-09-19T11:13:11.146Z" level=error msg="executor error: open /var/run/argo/outputs/artifacts/tmp/service.log.tgz: no such file or directory" 
time="2024-09-19T11:13:11.147Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: argo/2024/09/kafka-consume-1836603978960474112/kafka-consume-1836603978960474112-1811663817060106241-647481992/main.log" 
time="2024-09-19T11:13:11.147Z" level=info msg="Creating minio client using static credentials" endpoint="minio-headless:9000" 
time="2024-09-19T11:13:11.147Z" level=info msg="Saving file to s3" bucket=kernel endpoint="minio-headless:9000" key=argo/2024/09/kafka-consume-1836603978960474112/kafka-consume-1836603978960474112-1811663817060106241-647481992/main.log path=/tmp/argo/outputs/logs/main.log 
time="2024-09-19T11:13:11.151Z" level=info msg="Save artifact" artifactName=main-logs duration=4.93656ms error="<nil>" key=argo/2024/09/kafka-consume-1836603978960474112/kafka-consume-1836603978960474112-1811663817060106241-647481992/main.log 
time="2024-09-19T11:13:11.152Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log 
time="2024-09-19T11:13:11.152Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log" 
time="2024-09-19T11:13:11.201Z" level=info msg="Create workflowtaskresults 201" 
time="2024-09-19T11:13:11.202Z" level=info msg="Alloc=8249 TotalAlloc=16822 Sys=28541 NumGC=5 Goroutines=7" 
time="2024-09-19T11:13:11.202Z" level=fatal msg="open /var/run/argo/outputs/artifacts/tmp/service.log.tgz: no such file or directory"
```
