### ISSUE TITLE
Templated mutex name not resolved

### ISSUE THREAD

**Issue by nicolasbillamboz-flowbird** [argoproj/argo-workflows#13629]
### Pre-requisites

- [X] I have double-checked my configuration
- [ ] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

The mutex name is not resolved correctly when it is based on a workflow parameter, which is also based on another workflow parameter.

See the workflow below.
1. mutex name is defined as `{{ workflow.parameters.derived-mutex-name }}`
2. `derived-mutex-name` is defined as `"{{ workflow.parameters.base-mutex-name }}"`
3. `base-mutex-name` is defined as a parameter of the argo submit command line, let's say `mycustommutex`

In this workflow dag is used (and might be the reason of the defect).

With this workflow, if I run the following command:
```
argo submit my-workflow.yml --parameter base-mutex-name=mycustommutex
```
 I get the following message indicating the name of the mutex at runtime:
```
Waiting for argo-wf/Mutex{{ workflow.parameters.base-mutex-name }} lock. Lock status: 0/1
```
However the command `echo {{ workflow.parameters.derived-mutex-name }}` outputs correctly the resolved name:
```
mycustommutex
```

I have not tested this scenario with the latest version, because I'm not responsible of the deployment of argo in my company.

### Version(s)

v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mutex-name-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: base-mutex-name
    - name: derived-mutex-name
      value: "{{ workflow.parameters.base-mutex-name }}"
  templates:
  - name: main
    dag:
      tasks:
      - name: first
        template: print-mutex-name
      - name: second
        template: print-mutex-name
  - name: print-mutex-name
    synchronization:
      mutex:
        name: "{{ workflow.parameters.derived-mutex-name }}"
    container:
      image: alpine
      command: [ "/bin/sh", "-c" ]
      args:
      - |
        #!/bin/bash
        echo {{ workflow.parameters.derived-mutex-name }}
        sleep 30
```

### Logs from the workflow controller

```text
I'm not granted the permission to get these logs
```

### Logs from in your workflow's wait container

```text
I'm not granted the permission to get these logs
```
