### ISSUE TITLE
If a running workflow is deleted, workflow archive is not created

### ISSUE THREAD

**Issue by frauniki** [argoproj/argo-workflows#13658]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

We manage workflow resources directly in GitOps.
In an environment where ArchiveWorkflow is enabled, if there is a workflow in the running state and the workflow is deleted by GitOps, the archive is not created even though ArchiveWorkflow is enabled.

This is due to the workflow archive mechanism in Argo Workflows.
Workflow controller triggers the workflow archive when the workflow phase is marked as `Succeeded` or `Failed` or `Failed`.
https://github.com/argoproj/argo-workflows/blob/main/workflow/controller/operator.go#L2411

However, if a running workflow is deleted, the workflow archive is not created because the workflow phase is deleted without being marked as any phase.
Thus, the target workflow will be forever untraceable.
This problem could potentially occur in non-GitOps environments as well.

I think the workflow phase should be marked as one of the end phases before deleting the workflow. (i.e. the workflow archive is created).
However, I could not think of a good way to block workflow deletion until the workflow phase is changed.

### Version(s)

v3.5.11

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# Delete workflow during running status
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: hello-world
  templates:
  - name: hello-world
    container:
      image: busybox
      command: [sleep]
      args: ["10000"]
```

### Logs from the workflow controller

```text
None
```

### Logs from in your workflow's wait container

```text
None
```
