### ISSUE TITLE
Support retryStrategy on resource templates

### ISSUE THREAD

**Issue by epa095** [argoproj/argo-workflows#1370]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Both

**What happened**:
I set
```yaml
retryStrategy:
   limit: 5
```
on a resource template. The template running timeouts (which happens sometimes when there is large workflows) with the message
```
Error from server (Timeout): error when creating "/tmp/manifest.yaml": the server was unable to return a response in the time allotted, but may still be processing the request (post horizontalpodautoscalers.autoscaling)
```
but **the step is not retried** even though it has a retryStrategy of 5.

**What you expected to happen**:
The step to try again up to 5 times.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-11-26T12:57:14Z
  compiler: gc
  gitCommit: 435f92c719f279a3a67808c80521ea17d5715c66
  gitTreeState: clean
  gitVersion: v1.12.3
  goVersion: go1.10.4
  major: "1"
  minor: "12"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-11-26T14:31:35Z
  compiler: gc
  gitCommit: 753b2dbc622f5cc417845f0ff8a77f539a4213ea
  gitTreeState: clean
  gitVersion: v1.11.5
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64

```
