### ISSUE TITLE
Cron: don't create minutely workflow on spec error

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#13701]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

if we push new cron workflow with some errors, argo could replace it with default one dummy workflow which will run every minute

https://github.com/argoproj/argo-workflows/blob/ba75efb228fa3fbab91e2b1c7689f6db3f3c3b62/ui/src/app/shared/examples.ts#L79-L87

We need option to change this default workflow to some invalid one, to prevent unnecessary dummy jobs run.

this is noted in [a comment of](https://medium.com/@yauheni.pashkelevich/guys-we-found-that-its-not-possible-to-change-default-template-for-cron-job-ad9bce4af52f?source=responses-----aa037cd782be----0----------------------------) the [3.6 blog post](https://blog.argoproj.io/argo-workflows-3-6-aa037cd782be) but i have also noticed this

### Version(s)

3.5.11

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by Joibel** [comment]
Could you provide further information on the exact steps to reproduce this?
I tried:
* Create a bad CronWorkflow using `kubectl` it does not replace it with the one you linked.
* Create a bad CronWorkflow using `argo` cli it just reports it as bad, does not submit it and does not replace it
* Create a bad CronWorkflow using the web userinterface it reports it as bad in the user interface and does not submit it and does not replace it

**Comment by tooptoop4** [comment]
🦀

**Comment by agilgur5** [comment]
> run every minute

This is also intentional for an example, so that you can easily see it execute

**Comment by tooptoop4** [comment]
```
metadata:
  name: d-bear3
  namespace: argo
  labels:
    example: "true"
spec:
  workflowMetadata:
    labels:
      example: "true"
  schedule: "2 2 * * *"
  workflowSpec:
    entrypoint: argosay
    arguments:
      parameters:
        - name: message
          value: hello argo
    templates:
      - name: argosay
        inputs:
          parameters:
            - name: message
              value: {{`{{workflow.parameters.message}}`}}
        container:
          name: main
          image: argoproj/argosay:v2
          command:
            - /argosay
          args:
            - echo
            - {{`{{workflow.parameters.message}}`}}
    ttlStrategy:
      secondsAfterCompletion: 300
    podGC:
      strategy: OnPodCompletion
```
