### ISSUE TITLE
Support GitHub app authentication with artifacts

### ISSUE THREAD

**Issue by aburan28** [argoproj/argo-workflows#13825]
# Summary

What change needs making?
Add support to use a GitHub app private key to authenticate to GitHub. 

## Use Cases

When would you use this?
In Workflows where git repos are cloned.
---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by MasonM** [comment]
This should already be possible using [external secrets operator](https://external-secrets.io/latest/api/generator/), though I haven't tried it, e.g.
```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appID: "0000000" # (1)
  installID: "00000000" # (5)
  url: "" # (Default https://api.github.com.)
  repositories: # Optional
    - "Hello-World"
  permissions: # Optional
    contents: read
  auth:
    privateKey:
      secretRef:
        name: github-app-pem # (2)
        key: key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-auth-template
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: GithubAccessToken
        name: github-auth-token
  refreshInterval: "15m"
  target:
    name: github-creds
    template:
      engineVersion: v2
      data:
        username: "x-access-token"
        password: "{{ .token }}"
``` 

Then configure the workflow to access the generated secret via `usernameSecret`/`passwordSecret`, e.g.
```yaml
        git:
          repo: https://github.com/argoproj/argo-workflows.git
          revision: "v2.1.1"
           usernameSecret:
             name: github-creds
             key: username
           passwordSecret:
             name: github-creds
             key: password
```
