### ISSUE TITLE
Show envFrom in UI container information, matching env behavior

### ISSUE THREAD

**Issue by inigohidalgo** [argoproj/argo-workflows#13901]
# Summary

Currently, if an environment variable is specified using

```yaml
env:
  - name: VAR_NAME
    value: dev
```

it is shown in the web UI like so
![image](https://github.com/user-attachments/assets/a5d1eff1-b433-47f2-9809-3179e4ffaadd)

On the other hand, when populating environment variables using 

```yaml
envFrom:
          - configMapRef:
              name: {{ include "components.usecase_configmap" . }}

          - secretRef:
              name: {{ include "components.usecase_secrets" . }}
```

This is not reflected in the UI anywhere that I can see.

## Use Cases

When would you use this?

It is helpful to have this visibility on which configMaps or secretRefs are being inserted into a container's environment, it would have saved me some unnecessary debugging last week https://github.com/argoproj/argo-workflows/issues/3310#issuecomment-2454945741

The asymmetry in ENV being shown but not showing anything for envFrom is what led me to this confusion. If neither had been shown in the UI I would've found the issue faster.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.
