### ISSUE TITLE
possibility to add filters to variables

### ISSUE THREAD

**Issue by dberardo-com** [argoproj/argo-workflows#13952]
is it possible to add jinja-filter like operations to interpolated variables such as?:
```

   - -name: memoized-task
            template: memoized-task
            arguments:
              parameters:
                - name: memoize-key
                  value: "{{replace .my-input \"[!@#$%^&*()]\" \"_\" | replace \" \" \"_\"}}"


```
