### ISSUE TITLE
HTTP templates:  the outputs always get overridden with result

### ISSUE THREAD

**Issue by anvmga** [argoproj/argo-workflows#13955]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

In Http templates, the output always gets overridden with result. 

Below workflow only prints result only and not any other values passed. More details mentioned here https://github.com/argoproj/argo-workflows/discussions/13950#discussioncomment-11404302)

Expected Output:
Received message: 103.158.255.79
URL: https://httpbin.org/get

Received Output:
Received message: {{steps.get.outputs.parameters.result}}
URL: {{steps.get.outputs.parameters.url}}

### Version(s)

v3.6.0

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-output-parameters-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: get
        template: http-get

    - - name: print
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{steps.get.outputs.parameters.result}}"
          - name: url
            value: "{{steps.get.outputs.parameters.url}}"

  - name: http-get
    http:
      url: https://httpbin.org/get
    outputs:
      parameters:
      - name: result
        valueFrom:
          jsonPath: '{.origin}'
      - name: url
        value: "https://httpbin.org/get"

  - name: print-message
    inputs:
      parameters:
      - name: message
      - name: url
    script:
      image: alpine:3.7
      command: [sh, -c]
      source: |
        echo "Received message: {{inputs.parameters.message}}"
        echo "URL: {{inputs.parameters.url}}"
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
