### ISSUE TITLE
Workflow final status

### ISSUE THREAD

**Issue by jiahe0510** [argoproj/argo-workflows#13967]
# Summary

The current workflow using DAG template will set the skipped task as parent status. Hence if the parent task of the leaf is failed, then the leaf task will be considered as failed. Therefore, the whole workflow will be set as Failed. Handle scenario that set skipped task as succeeded.

## Use Cases

Consider we have a DAG that have 3 tasks. 
1 ----- 2
|
-------3

The logic is if 1 failed then run 3, if 1 succeeded run 2. Any of 2 or 3 is succeeded, we want the whole workflow as succeeded.
 

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Joibel** [comment]
I'm not sure I follow your request well enough. Can you write a workflow we can talk about using [enhanced depends](https://argo-workflows.readthedocs.io/en/release-3.4/enhanced-depends-logic/) and tell us where this doesn't work for you.

**Comment by jiahe0510** [comment]
> I'm not sure I follow your request well enough. Can you write a workflow we can talk about using [enhanced depends](https://argo-workflows.readthedocs.io/en/release-3.4/enhanced-depends-logic/) and tell us where this doesn't work for you.

Thanks for your reply. Here is the workflow I was talking about.

```yaml
name: test
outputs: {}
metadata: {}
dag:
  tasks:
  - name: task1
    arguments:
      parameters: []
    templateRef:
      name: root
      template: v1
      clusterScope: true
  - name: task2
    arguments:
      parameters: []
    templateRef:
      name: success
      template: v1
      clusterScope: true
    dependencies:
    - task1
    when: "({{tasks.task1.status}}==Failed)"
  - name: task3
    arguments:
      parameters: []
    templateRef:
      name: fail
      template: v1
      clusterScope: true
    dependencies:
    - task1
    when: "({{tasks.task1.status}}==Succeeded)"
  failFast: false
```

If the root task(task1) is failed, then it will go to the leaf task(task2), and it will success. The workflow now is completed. When calculating the whole workflow status, the task3(skipped task) will be assigned to its parent status, which is failed. Hence, the whole workflow will be assigned to Failed. Is there anyway to count such scenario as succeeded?

**Comment by jiahe0510** [comment]
> you could add a task 4 (simple echo) that depends on 2 or 3 succeeded, so that task 4 will always execute if 2 or 3 is good, this will make the workflow marked successful
> 
> you could try use [depends ](https://argo-workflows.readthedocs.io/en/latest/enhanced-depends-logic/)to make the yaml slightly cleaner

Thanks for the suggestion. It seems that it could solve the issue. Though, it make the whole workflow weird. lol

**Comment by bygui86** [comment]
I think anyway that an optional condition to define "when" a workflow can be considered "successful" would be a really nice feature :)

Let's suppose I have a dag like this

   A
  /   \
 /     \
B     C

```
name: test
outputs: {}
metadata: {}
dag:
  tasks:
  - name: taskA
    arguments:
      parameters: []
    templateRef:
      name: A
      template: v1
      clusterScope: true
  - name: taskB
    arguments:
      parameters: []
    templateRef:
      name: B
      template: v1
      clusterScope: true
    depends: taskA
  - name: taskC
    arguments:
      parameters: []
    templateRef:
      name: C
      template: v1
      clusterScope: true
    depends: taskA
```

Task A, then task B and C depending on task A to be successful.
If either B or C fails, then the whole workflow is marked as failed.
There are cases in which the workflow status could depend on task C OR task B:
- if either B or C is successful, the workflow final status is successful
- if both B and C fail, the workflow final status is fail

Something simple like (supporting simple boolean logical operators like &&, || )

```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: test
spec:
  entrypoint: main
  onExit: exit
  arguments:
    parameters: [...]
  templates:
    - name: main
      finalStatusDepends: "taskB || taskC"
      inputs:
        parameters: [...]
      dag: [...]
    - name: exit
      inputs:
        parameters: [...]
      dag: [...]
```
