### ISSUE TITLE
Lint fails on global output parameter in wft

### ISSUE THREAD

**Issue by Gilwyad** [argoproj/argo-workflows#13997]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

argo lint fails on a workflow template that I am able to kubectl apply and is working in a workflow! 

More details in the discussion #13870

### Version(s)

v3.5.10

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-with-global-output-parameter-lint-fails
spec:
  templates:
    - name: test-one
      steps:
        - - name: hello-test-1
            template: hello1
          - name: hello-test-2
            template: hello2
            when: '{{workflow.outputs.parameters.variable}} == true'

    - name: hello1
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo hello test 1"]

    - name: hello2
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo hello test 2"]
```

### Logs from the workflow controller

```text
The bug is not in the workflow execution, but in `argo lint`.
```

### Logs from in your workflow's wait container

```text
The bug is not in the workflow execution, but in `argo lint`.
```

**Comment by shuangkun** [comment]
Could you add a real global outputs parameter?
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-with-global-output-parameter-lint-fails
spec:
  templates:
    - name: test-one
      steps:
        - - name: hello-test-1
            template: hello1
          - name: hello-test-2
            template: hello2
            when: '{{workflow.outputs.parameters.variable}} == true'

    - name: hello1
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo hello test 1"]
      outputs:
        parameters:
        - name: variable
          value: "test"
          globalName: variable

    - name: hello2
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo hello test 2"]
13997 % argo template lint global-output.yaml
✔ no linting errors found!
```
