### ISSUE TITLE
Global customer-defined initContainer configuration

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argo-workflows#14018]
# Summary

Global customer-defined initContainer configuration.

## Use Cases

In large-scale simulation scenarios, we need to use initContainer to prepare data in each step, but we don’t want to configure it in each pod, so we hope to have a global configuration similar to mainContainer to configure initContainer.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by shuangkun** [comment]
We tried to use this method in workflowDefaults for global configuration, but mirrorVolumeMounts did not take effect. I also found the reason, because when creating a pod, the addInitContainers operation is earlier than applyPodPatch.
```  
  podSpecPatch: |
      initContainers:
        - name: my-init-contaienr
          image：init-image:latest
          mirrorVolumeMounts: true
          resources:
            requests:
              memory: 2Gi
              cpu: 300m
```
