### ISSUE TITLE
sso rbac doesnt work

### ISSUE THREAD

**Issue by bvbvr** [argoproj/argo-workflows#14033]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Install argo workflow from quick installation and settings sso\rbac from 
https://argo-workflows.readthedocs.io/en/latest/argo-server-sso/#to-start-argo-server-with-sso
In deployment:
```
      - args:
        - server
        - --auth-mode=sso
        - --configmap=argo-cm
        env:
        - name: ARGO_SERVER_CONFIGMAP_NAME
          value: argo-rbac-cm
        image: quay.io/argoproj/argocli:v3.6.2
```
In cm argo-cm
```
    sso:
      issuer: https://isso.example.com/auth/realms/gg
      sessionExpiry: 240h
      clientId:
        name: client-id-secret
        key: client-id-key
      clientSecret:
        name: client-secret-secret
        key: client-secret-key
      redirectUrl: https://workflow.example.com/oauth2/callback
      scopes:
       - email
       - roles
       - openid
       - profile
       - username
      rbac:
        enabled: true
```
in  argo-rbac-cm
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rbac-cm
  namespace: argo
data:
  policy.csv: |
    p, role:admin, *, *, allow
  
    g, user:elonmusk, role:admin
    g, user:adam, role:readonly
```

and in logs argo-server have got error:
time="2024-12-26T13:21:25.658Z" level=error msg="failed to perform RBAC authorization" error="no service account rule matches"
time="2024-12-26T13:21:25.658Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = not allowed" grpc.code=PermissionDenied grpc.method=GetUserInfo grpc.service=info.InfoService grpc.start_time="2024-12-26T13:21:25Z" grpc.time_ms=1.622 span.kind=server system=grpc

### Version(s)

v3.6.2 

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
v3.6.2
```

### Logs from the workflow controller

```text
-
```

### Logs from in your workflow's wait container

```text
-
```
