### ISSUE TITLE
Can't use ShutdownStrategy when using DAG and outputs.

### ISSUE THREAD

**Issue by sfrique** [argoproj/argo-workflows#14036]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I am trying to use DAG and `ShutdownStrategy` , my use case is CI.
I have a checkout step that generates outputs/artifacts and want to use this outputs in to decide if we should start next steps or skip it. I also need some outputs for steps to work as expected.

The setup i want is to be able that if any step fails, i want to terminate/stop all running tasks.

I basically could not convert my workflow to DAG to do this, i can do it without the `ShutdownStrategy`.

When setting `ShutdownStrategy` the checkout steps just fails.

obs: I may have miss understood this, please correct me if i ma wrong.

this workflow works: https://raw.githubusercontent.com/argoproj/argo-workflows/refs/heads/main/test/e2e/functional/global-outputs-dag.yaml
when i add `shutdown: Terminate` it just fails, if i add `Stop` it says it can't resolve
`Unable to resolve: "workflow.outputs.artifacts.my-global-art"`

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-outputs-dag-
spec:
  entrypoint: generate-globals
  onExit: consume-globals
  shutdown: Stop

  templates:
    - name: generate-globals
      dag:
        tasks:
          - name: generate
            template: global-output
          - name: consume-globals
            dependencies: [generate]
            template: consume-globals

    # Template which produces a global parameter and artifact
    - name: global-output
      container:
        image: alpine:3.7
        command: [sh, -c]
        args: ["sleep 1; echo -n hello world > /tmp/hello_world.txt"]
      outputs:
        parameters:
          # export a global parameter. The parameter will be programatically available in the completed
          # workflow object under: workflow.status.outputs.parameters
          - name: hello-param
            valueFrom:
              path: /tmp/hello_world.txt
            globalName: my-global-param
        # export a global artifact. The artifact will be programatically available in the completed
        # workflow object under: workflow.status.outputs.artifacts
        artifacts:
          - name: hello-art
            path: /tmp/hello_world.txt
            globalName: my-global-art

    # Once exported, global outputs are referenceable in later parts of the workflow.
    # In this example, the consume-globals template is invoked after the generate-globals step, as
    # well as in the onExit handler. and can reference the globals, my-global-param and my-global-art.
    - name: consume-globals
      dag:
        tasks:
          - name: consume-global-param
            template: consume-global-param
          - name: consume-global-art
            template: consume-global-art
            arguments:
              artifacts:
                - name: art
                  from: "{{workflow.outputs.artifacts.my-global-art}}"

    - name: consume-global-param
      container:
        image: alpine:3.7
        command: [sh, -c]
        args: ["echo {{workflow.outputs.parameters.my-global-param}}"]

    - name: consume-global-art
      inputs:
        artifacts:
          - name: art
            path: /art
      container:
        image: alpine:3.7
        command: [sh, -c]
        args: ["cat /art"]
```

### Logs from the workflow controller

```text
➜ kubectl logs -n argo deploy/workflow-controller | grep global-outputs-dag-m24fx
time="2024-12-28T06:40:01.726Z" level=info msg="Processing workflow" Phase= ResourceVersion=1227 namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.730Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.730Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.730Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.730Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.731Z" level=info msg="DAG node global-outputs-dag-m24fx initialized Running" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.731Z" level=warning msg="was unable to obtain the node for global-outputs-dag-m24fx-2363500871, taskName consume-globals"
time="2024-12-28T06:40:01.731Z" level=warning msg="was unable to obtain the node for global-outputs-dag-m24fx-4011138787, taskName generate"
time="2024-12-28T06:40:01.731Z" level=warning msg="was unable to obtain the node for global-outputs-dag-m24fx-4011138787, taskName generate"
time="2024-12-28T06:40:01.731Z" level=info msg="All of node global-outputs-dag-m24fx.generate dependencies [] completed" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.731Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.731Z" level=info msg="Pod node global-outputs-dag-m24fx-4011138787 initialized Pending" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.731Z" level=info msg="node global-outputs-dag-m24fx-4011138787 phase Pending -> Failed" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.731Z" level=info msg="node global-outputs-dag-m24fx-4011138787 message: workflow shutdown with strategy: Terminate" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.731Z" level=info msg="node global-outputs-dag-m24fx-4011138787 finished: 2024-12-28 06:40:01.731801421 +0000 UTC" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.731Z" level=warning msg="was unable to obtain the node for global-outputs-dag-m24fx-2363500871, taskName consume-globals"
time="2024-12-28T06:40:01.732Z" level=info msg="Skipped node global-outputs-dag-m24fx-2363500871 initialized Omitted (message: omitted: depends condition not met)" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.732Z" level=info msg="Outbound nodes of global-outputs-dag-m24fx set to [global-outputs-dag-m24fx-2363500871]" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.732Z" level=info msg="node global-outputs-dag-m24fx phase Running -> Failed" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.732Z" level=info msg="node global-outputs-dag-m24fx finished: 2024-12-28 06:40:01.732121913 +0000 UTC" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.732Z" level=info msg="Running OnExit handler: consume-globals" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.732Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.732Z" level=info msg="Updated message  -> Stopped with strategy 'Terminate'" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.732Z" level=info msg="Marking workflow completed" namespace=argo workflow=global-outputs-dag-m24fx
time="2024-12-28T06:40:01.736Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=1229 workflow=global-outputs-dag-m24fx
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=global-outputs-dag-m24fx,workflow.argoproj.io/phase!=Succeed
ed
No resources found in argo namespace.
```
