### ISSUE TITLE
Whether you can provide a read-only option for a graphical interface

### ISSUE THREAD

**Issue by zhaomingcheng01** [argoproj/argo-workflows#14040]
Whether you can provide a read-only option for a graphical interface

**Comment by tooptoop4** [comment]
u can, look at RBAC docs

**Comment by shuangkun** [comment]
You can bind read-only permissions to logged-in users.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: argo-aggregate-to-view
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workfloweventbindings
  - workfloweventbindings/finalizers
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  - clusterworkflowtemplates
  - clusterworkflowtemplates/finalizers
  - workflowtaskresults
  - workflowtaskresults/finalizers
  verbs:
  - get
  - list
  - watch
```
