### ISSUE TITLE
dynamic template naming on workflowTemplates fails unexpectedly

### ISSUE THREAD

**Issue by MenD32** [argoproj/argo-workflows#14042]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

templating a template name fails when using a workflowTemplate's input, this bug can be mitigated by using an intermediate template to output the input of the workflowTemplate 

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: example-workflow-template-a
spec:
  templates:
  - name: whalesay-template
    inputs:
      parameters:
        - name: message
    steps:
      - - name: whalesay
          templateRef:
            name: example-workflow-template-b
            template: "{{ inputs.parameters.message }}"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: example-workflow-template-b
spec:
  templates:
  - name: whalesay-template
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello from template"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-workflow-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:
      - - name: whalesay
          templateRef:
            name: example-workflow-template-a
            template: whalesay-template
          arguments:
            parameters:
              - name: message
                value: "whalesay-template"
```

### Logs from the workflow controller

```text
not relevant
```

### Logs from in your workflow's wait container

```text
not relevant
```
