### ISSUE TITLE
`argo lint` prints YAML to JSON conversion error twice when it's used with `--offline` option

### ISSUE THREAD

**Issue by pakio** [argoproj/argo-workflows#14050]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

`argo lint` prints YAML to JSON conversion error twice when it's used with `--offline` option.

### Version(s)

741ab0ef7b6432925e49882cb4294adccf5912ec

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
Here's the command to reproduce the error


❯ argo lint hello-world-invalid.yaml
ERRO[2025-01-04T17:11:01.928Z] yaml file at index 0 is not valid: error converting YAML to JSON: yaml: line 16: found a tab character that violates indentation
✖ found nothing to lint in the specified paths, failing...
❯ argo lint --offline hello-world-invalid.yaml
ERRO[2025-01-04T17:11:17.510Z] yaml file at index 0 is not valid: error converting YAML to JSON: yaml: line 16: found a tab character that violates indentation
ERRO[2025-01-04T17:11:17.510Z] yaml file at index 0 is not valid: error converting YAML to JSON: yaml: line 16: found a tab character that violates indentation
✖ found nothing to lint in the specified paths, failing...


yaml file used to verify the result
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
spec:
  entrypoint: hello-world
  templates:
  - name: hello-world
    container:
      image: busybox
        command: [echo]     # invalid indent
        args: ["hello world"] # invalid indent
```
```


### Logs from the workflow controller

```text
N/A (it only happens when argo lint is called with offline mode)
```

### Logs from in your workflow's wait container

```text
N/A
```
