### ISSUE TITLE
UI can't get stream logs until main container finished

### ISSUE THREAD

**Issue by galoniz** [argoproj/argo-workflows#14063]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

similar to issue [12811](https://github.com/argoproj/argo-workflows/issues/12811) that was closed, 
Argo workflow UI can receive logs from running pods. 
Once the jobs are finished, the logs are outputed to the UI

I expect logs to be streamed while the job runs.

regarding RBAC: I validate and it has watch logs permission for my user: `apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: argo-workflows
    meta.helm.sh/release-namespace: argo-workflows
  creationTimestamp: "2023-11-29T08:15:39Z"
  labels:
    app: server
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/part-of: argo-workflows
    app.kubernetes.io/pd-service-name: eks-infra
    helm.sh/chart: argo-workflows-0.45.3
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: argo-workflows-admin
  resourceVersion: "850694153"
  uid: 9bcb6df2-e770-4656-b787-36c65b4baed6
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workfloweventbindings
  - workfloweventbindings/finalizers
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  - clusterworkflowtemplates
  - clusterworkflowtemplates/finalizers
  - workflowtasksets
  - workflowtasksets/finalizers
  - workflowtaskresults
  - workflowtaskresults/finalizers
  - workflowartifactgctasks
  - workflowartifactgctasks/finalizers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
`

<img width="676" alt="Screenshot 2025-01-09 at 10 03 42" src="https://github.com/user-attachments/assets/700b2d9d-9a89-4934-8096-c96e724143b3" />
<img width="1076" alt="Screenshot 2025-01-09 at 10 02 48" src="https://github.com/user-attachments/assets/862f4890-e7aa-4bd3-9520-6faeec83d77a" />

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: log-streaming-template
spec:
  templates:
  - name: stream-logs
    script:
      image: busybox
      command: [sh]
      source: |
        echo "Starting log stream..."
        for i in $(seq 1 30); do
          echo "Log line $i: $(date)"
          sleep 2
        done
        echo "Log stream finished."
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: log-streaming-workflow
spec:
  entrypoint: run-log-streaming
  templates:
  - name: run-log-streaming
    steps:
    - - name: stream-logs-step
        templateRef:
          name: log-streaming-template
          template: stream-logs
```

### Logs from the workflow controller

```text
No logs related in controller
```

### Logs from in your workflow's wait container

```text
No logs for wait
```

**Comment by shuangkun** [comment]
It looks like we have encountered this before. Have you tested it with the latest version?

**Comment by galoniz** [comment]
> It looks like we have encountered this before. Have you tested it with the latest version?
@shuangkun yes, 3.6.2 is now the latest

**Comment by galoniz** [comment]
any update on this?

**Comment by mohsin-786** [comment]
Even on 3.6.5 the same issue persists.

**Comment by tczhao** [comment]
I tried running 3.6.5 locally but couldn't reproduce the issue.
How do you install the 3.6.5
does argo server cluster roles have the following permission
```
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - get
  - list
  - watch
  - delete
```
