### ISSUE TITLE
argo service account has no permission to create configmap

### ISSUE THREAD

**Issue by jingkkkkai** [argoproj/argo-workflows#14073]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

in our case, we encountered error when creating a workflow contains a large size of raw data input artifacts
the error message is shown as following:
```
configmaps is forbidden: User "system:serviceaccount:canal-flow:argo" cannot create resource "configmaps" in API group "" in the namespace "canal-flow"
```

based on the argo codebase, 
when creating a pod, the workflow-controller checks the length of each template’s environment variables. 
Ref: [workflowpod.go#L424](https://github.com/argoproj/argo-workflows/blob/a7a72e7ca3c2bbf127b65fdcf1b5b85fbd2aad19/workflow/controller/workflowpod.go#L424)

If it exceeds the maxEnvVarLen (131072), the environment variables are passed to the pod via a ConfigMap instead.
Ref: [workflowpod.go#L431](https://github.com/argoproj/argo-workflows/blob/a7a72e7ca3c2bbf127b65fdcf1b5b85fbd2aad19/workflow/controller/workflowpod.go#L431)

However, it seems that the service account used by the workflow-controller, ‘argo,’ doesn’t have permission to create ConfigMaps.
Ref: [workflow-controller-rbac/workflow-controller-role.yaml#L30](https://github.com/argoproj/argo-workflows/blob/a7a72e7ca3c2bbf127b65fdcf1b5b85fbd2aad19/manifests/namespace-install/workflow-controller-rbac/workflow-controller-role.yaml#L30)

Can anyone help with this issue?

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: large-input-artifact-
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      artifacts:
      - name: large-input
        path: /tmp/input-data.txt
        raw:
          data: |
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            <<Repeat until more than 131072 characters>>
            
    container:
      image: alpine:3.16
      command: [sh, -c]
      args:
        - |
          echo "Processing large input artifact...";
          cat /tmp/input-data.txt | wc -c;
          echo "Data successfully processed.";
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
