### ISSUE TITLE
Memory (RAM) increases exponentially on submitting large number of workflows and it s not cleared even after the workflow run

### ISSUE THREAD

**Issue by JishinJames** [argoproj/argo-workflows#14084]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### Description:
Memory (RAM) increases exponentially on submitting large number of workflows and it s not cleared even after the workflow run

### Environment:
Argo Workflows version: 3.5.12
Parallel workflows: 6000+

### What happened:
The Argo Workflows Controller's memory consumption increases exponentially. Despite this excessive memory usage, the controller crashes frequently. It does not log any specific error messages prior to these crashes, making it challenging to pinpoint the cause or underlying issue.
Hence we did a memory profiling of argo controller pod and some experiments were tried out to check whether it can be mitigated.

How to reproduce it (as minimally and precisely as possible):
Set up an environment with 300+ nodes.
Launch 5000+ workflows in parallel.
Monitor the RAM usage of the Argo Workflows Controller and note any unexpected crashes.

![Image](https://github.com/user-attachments/assets/77b6cd2a-ace8-446a-a8d7-ffc109b9f1b2)

### Version(s)

v3.5.8, v3.5.10, v3.5.12

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
metadata:
  name: test-workflow
spec:
  templates:
    - name: execution
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: generate-file-test
            template: generate-file
            arguments: {}
        - - name: read-file-test
            template: read-file
            arguments:
              artifacts:
                - name: generated-file
                  from: >-
                    {{steps.generate-file-test.outputs.artifacts.generated-file}}
        - - name: remove-file-test
            template: generate-and-remove-file
            arguments: {}
    - name: generate-file
      inputs: {}
      outputs:
        artifacts:
          - name: generated-file
            path: /data/test-file.txt
      metadata: {}
      container:
        name: ''
        image: alpine:3.7
        command:
          - sh
          - '-c'
        args:
          - >
            mkdir -p /data;

            echo "This is a test file created by Argo Workflow" >
            /data/test-file.txt;

            cat /data/test-file.txt
        resources: {}
        volumeMounts:
          - name: temp-storage
            mountPath: /data
    - name: read-file
      inputs:
        artifacts:
          - name: generated-file
            path: /data/test-file.txt
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: alpine:3.7
        command:
          - sh
          - '-c'
        args:
          - |
            echo "Getting file from Volume"
            ls -al /data
            cat /data/test-file.txt
        resources: {}
        volumeMounts:
          - name: temp-storage
            mountPath: /data
    - name: generate-and-remove-file
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: alpine:3.7
        command:
          - sh
          - '-c'
        args:
          - |
            mkdir -p /data;
            export FILE_PATH='/data/test-file.txt'
            echo "This is a test file created by Argo Workflow" > $FILE_PATH;
            cat $FILE_PATH

            if [ ! -f $FILE_PATH ]; then
              echo "File $FILE_PATH does not exist"
              exit 1
            else
              rm -f $FILE_PATH
              echo "File has been removed."
              ls -al /data
            fi
        resources: {}
        volumeMounts:
          - name: temp-storage
            mountPath: /data
  entrypoint: execution
  arguments:
    parameters:
      - name: wf-message
        value: This is a testing workflow on CPU node!
  volumes:
    - name: temp-storage
      emptyDir: {}
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
time="2025-01-15T11:10:57Z" level=info msg="index config" indexWorkflowSemaphoreKeys=true
time="2025-01-15T11:10:57Z" level=info msg="cron config" cronSyncPeriod=10s
time="2025-01-15T11:10:57Z" level=info msg="Memoization caches will be garbage-collected if they have not been hit after" gcAfterNotHitDuration=30s
time="2025-01-15T11:10:57.406Z" level=warning msg="Non-transient error: <nil>"
time="2025-01-15T11:10:57.414Z" level=warning msg="Non-transient error: <nil>"
W0115 11:10:58.545737       1 shared_informer.go:401] The sharedIndexInformer has started, run more than once is not allowed
time="2025-01-15T11:10:59.186Z" level=error msg="cannot validate Workflow: WorkflowTemplate Informer cannot find WorkflowTemplate of name \"delete-wrong-ids\" in namespace \"argo-image-search\"" conditionType=SpecError namespace=argo-image-search workflow=delete-wrong-ids-dev
time="2025-01-15T11:10:59.186Z" level=error msg="invalid cron workflow" cronWorkflow=argo-image-search/delete-wrong-ids-dev error="cannot validate Workflow: WorkflowTemplate Informer cannot find WorkflowTemplate of name \"delete-wrong-ids\" in namespace \"argo-image-search\""
time="2025-01-15T11:10:59.389Z" level=error msg="cannot validate Workflow: WorkflowTemplate Informer cannot find WorkflowTemplate of name \"test-lucene-filter-workflow\" in namespace \"argo-image-search\"" conditionType=SpecError namespace=argo-image-search workflow=test-lucene-filter-workflow
time="2025-01-15T11:10:59.389Z" level=error msg="invalid cron workflow" cronWorkflow=argo-image-search/test-lucene-filter-workflow error="cannot validate Workflow: WorkflowTemplate Informer cannot find WorkflowTemplate of name \"test-lucene-filter-workflow\" in namespace \"argo-image-search\""
time="2025-01-15T11:14:24.354Z" level=error msg="unable to substitute parameters for metric 'after_executed': failed to resolve {{workflow.failures}}" namespace=argo-dev workflow=stress-testing-86d2t
time="2025-01-15T11:14:24.361Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-dev workflow=stress-testing-86d2t
time="2025-01-15T11:14:24.362Z" level=error msg="was unable to obtain node for stress-testing-2ngbw"
time="2025-01-15T11:14:24.362Z" level=error msg="was unable to obtain node for stress-testing-2ngbw-1482424255"
time="2025-01-15T11:14:24.395Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-dev workflow=stress-testing-86d2t
time="2025-01-15T11:14:24.396Z" level=error msg="was unable to obtain node for stress-testing-2ngbw-3197284649"
time="2025-01-15T11:14:24.581Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-dev workflow=stress-testing-86d2t
time="2025-01-15T11:14:24.581Z" level=error msg="was unable to obtain node for stress-testing-2ngbw-273366853"
time="2025-01-15T11:14:24.641Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-dev workflow=stress-testing-86d2t
time="2025-01-15T11:14:24.641Z" level=error msg="was unable to obtain node for stress-testing-2ngbw-3098736065"
time="2025-01-15T11:14:24.707Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-dev workflow=stress-testing-86d2t
time="2025-01-15T11:14:24.708Z" level=error msg="was unable to obtain node for stress-testing-2ngbw-3285503829"
time="2025-01-15T11:14:24.778Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-dev workflow=stress-testing-86d2t
time="2025-01-15T11:14:24.778Z" level=error msg="was unable to obtain node for stress-testing-2ngbw-3101850513"
time="2025-01-15T11:14:24.864Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-dev workflow=stress-testing-86d2t
time="2025-01-15T11:14:24.864Z" level=error msg="was unable to obtain node for stress-testing-2ngbw-3403075349"
time="2025-01-15T11:14:24.927Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-dev workflow=stress-testing-86d2t
time="2025-01-15T11:14:24.927Z" level=error msg="was unable to obtain node for stress-testing-2ngbw-3835149785"
time="2025-01-15T11:14:24.991Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo-dev workflow=stress-testing-86d2t

time="2025-01-15T11:14:34.437Z" level=error msg="was unable to obtain node for stress-testing-2ngbw-1842043933"
```

### Logs from in your workflow's wait container

```text
no logs in wait container
```
