### ISSUE TITLE
The pod exists in the cluster but log show "no artifact logs are available"

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argo-workflows#14083]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

The pod still exists in the cluster
```
upgrade % kubectl get pod -n argo | grep wf
hello-world-wfpfz               0/2     Completed   0          18h
```
but log shows "no artifact logs are available"
![Image](https://github.com/user-attachments/assets/f28a1fd4-a2b4-4017-8923-8f810551591a)

### Version(s)

latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

set persistence archive to true
```YAML
  persistence: |
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
      connMaxLifetime: 0s # 0 means connections don't have a max lifetime
    archiveTTL: 30d
    archive: true
```

submit workflow
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec.
metadata:
  generateName: hello-world-    # name of the workflow spec.
spec:
  entrypoint: main          # invoke the main template.
  templates:
    - name: main              # name of the template.
      container:
        image: busybox:latest
        command: [ echo ]
        args: [ "hello world" ]
      initContainers:
      - name: hello
        image: busybox:latest
        command: ["echo", "hello"]
        mirrorVolumeMounts: true
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
