### ISSUE TITLE
`HTTP` and `Plugin` nodes cannot be manually retried

### ISSUE THREAD

**Issue by jswxstw** [argoproj/argo-workflows#14124]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

#13734 refactored the retry logic, but `HTTP` and `Plugin` nodes cannot be manually retried after this change.

```shell
# ./dist/argo get http-template-98l24
Name:                http-template-98l24
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Failed
Message:             child 'http-template-98l24-3189028985' failed
Conditions:          
 PodRunning          False
 Completed           True
Created:             Sun Jan 26 15:02:00 +0800 (2 minutes ago)
Started:             Sun Jan 26 15:02:00 +0800 (2 minutes ago)
Finished:            Sun Jan 26 15:02:04 +0800 (2 minutes ago)
Duration:            4 seconds
Progress:            0/2
Parameters:          
  url:               https://raw.githubusercontent.com/argoproj/argo-workflows/thisisnotahash/pkg/apis/workflow/v1alpha1/generated.swagger.json

STEP                    TEMPLATE  PODNAME  DURATION  MESSAGE
 ✖ http-template-98l24  main                         child 'http-template-98l24-3189028985' failed  
 └─┬─✖ fail1            http                         received non-2xx response code: 404            
   └─✖ fail2            http                         received non-2xx response code: 404 
```

```shell
# ./dist/argo retry http-template-98l24 -p url="https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"
INFO[2025-01-26T15:04:33.446Z] Workflow to be dehydrated                     Workflow Size=4107
Name:                http-template-98l24
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Running
Conditions:          
 PodRunning          False
 Completed           False
Created:             Sun Jan 26 15:02:00 +0800 (2 minutes ago)
Started:             Sun Jan 26 15:04:33 +0800 (now)
Duration:            0 seconds
Progress:            0/2
Parameters:          
  url:               https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json

STEP                    TEMPLATE  PODNAME  DURATION  MESSAGE
 ● http-template-98l24  main                                                              
 └─┬─✖ fail1            http                         received non-2xx response code: 404  
   └─✖ fail2            http                         received non-2xx response code: 404
```

https://github.com/argoproj/argo-workflows/blob/c92ac3630b07bb83b94d7d690fb694c9067bc4a8/workflow/util/util.go#L1173-L1178

It seems that here missed `HTTP` and `Plugin` types.

### Version(s)

c92ac3630b07bb83b94d7d690fb694c9067bc4a8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-template-
spec:
  entrypoint: main
  arguments:
    parameters:
      # good: https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json
      # bad: https://raw.githubusercontent.com/argoproj/argo-workflows/thisisnotahash/pkg/apis/workflow/v1alpha1/generated.swagger.json
      - name: url
        value: "https://raw.githubusercontent.com/argoproj/argo-workflows/thisisnotahash/pkg/apis/workflow/v1alpha1/generated.swagger.json"
  templates:
    - name: main
      steps:
        - - name: fail1
            template: http
          - name: fail2
            template: http

    - name: http
      http:
        url: "{{workflow.parameters.url}}"
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
