### ISSUE TITLE
CronWorkflow that uses templateRef cannot submit.

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#14195]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

It seems that CronWorkflow submissions that use templateRef & pass parameters are no longer possible.
These workflows are not executed even if they are scheduled and are not logged in the workflow-controller log, making them difficult to detect.
![Image](https://github.com/user-attachments/assets/cbf08824-6993-48ff-908b-7953b0eb0f82)
```console
{"code":3,"message":"templates.main.steps[1].gc-unmarked templates.main: failed to resolve {{workflow.parameters.days_safety_margin}}"}: templates.main.steps[1].gc-unmarked templates.main: failed to resolve {{workflow.parameters.days_safety_margin}}
```

### Version(s)

v3.6.4

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: "cron-workflow"
spec:
  schedule: "* * * * *"
  workflowSpec:
    entrypoint: argosay
    templates:
      - name: argosay
        steps:
          - - name: main
              templateRef:
                name: workflow-template
                template: argosay
              arguments:
                parameters:
                  - name: message
                    value: "hello world"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template
spec:
  entrypoint: argosay
  arguments:
    parameters:
      - name: message
        value: hello argo
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: "{{workflow.parameters.message}}"
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - "{{inputs.parameters.message}}"
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
