### ISSUE TITLE
UI: Retry Node side panel is not scrollable for overriding parameters

### ISSUE THREAD

**Issue by williamburgson** [argoproj/argo-workflows#14208]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

The Retry Node side panel does not scroll for overriding parameters. The only way to see the input box is to zoom out in the browser, the other buttons are also inaccessible without zooming out.

<img width="749" alt="Image" src="https://github.com/user-attachments/assets/931b42b3-2f40-4d72-b7c9-20b370449686" />

### Version(s)

v3.6.4, sha56:25248ac38be63a23d3643922a788470504e5fd98d686380d41a04923963b14ae

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: omniscient-poochenheimer-
spec:
  templates:
    - name: argosay
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - "{{workflow.parameters.msg1}}"
  entrypoint: argosay
  arguments:
    parameters:
      - name: msg1
        value: hello world
      - name: msg2
        value: "1"
      - name: msg3
        value: "1"
      - name: msg4
        value: "1"
      - name: msg5
        value: "1"
      - name: msg6
        value: "1"
      - name: msg7
        value: "1"
      - name: msg8
        value: "1"
      - name: msg9
        value: "1"
      - name: msg10
        value: "1"
      - name: msg11
        value: "1"
      - name: msg12
        value: "1"
      - name: msg13
        value: "1"
      - name: msg14
        value: "1"
      - name: msg15
        value: "1"
      - name: msg16
        value: "1"
      - name: msg17
        value: "1"
      - name: msg18
        value: "1"
```

### Logs from the workflow controller

```text
irrelevant, this is a argo ui issue
```

### Logs from in your workflow's wait container

```text
irrelevant, this is a argo ui issue
```
