### ISSUE TITLE
Workflow is Error but taskset node is not Error when Agent pod failed

### ISSUE THREAD

**Issue by Tuilot** [argoproj/argo-workflows#14200]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

When I submit the workflow to argo namepsace , the agent pod failed
Then, the workflow turns to Error state, but the taskset node is still Pending.

agent pod:
`# kubectl -n argo get po hello-plugin-1340600742-agent -owide
NAME                            READY   STATUS    RESTARTS   AGE     IP               NODE                NOMINATED NODE   READINESS GATES
hello-plugin-1340600742-agent   4/4     Evicted   0          3m19s   192.168.28.240   train070.hogpu.cc   <none>           <none>`

taskset: 
`#  kubectl -n argo get workflowtaskset hello-plugin -oyaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTaskSet
metadata:
  creationTimestamp: "2025-02-17T09:50:11Z"
  generation: 1
  labels:
    workflows.argoproj.io/completed: "true"
  name: hello-plugin
  namespace: argo
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    name: hello-plugin
    uid: 0709dfa5-3603-487d-ba45-40e1f19ccc87
  resourceVersion: "5377104186"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflowtasksets/hello-plugin
  uid: 43313c93-90f3-41cc-8467-0d1c845c9a60
spec:
  tasks:
    hello-plugin-2816962999:
      inputs: {}
      metadata: {}
      name: hello-plugin
      outputs: {}
      plugin:
        hello: {}
status:
  nodes:
    hello-plugin-2816962999:
      message: Queuing
      phase: Pending`

workflow:
`# kubectl -n argo get wf hello-plugin -oyaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    workflows.argoproj.io/pod-name-format: v1
  creationTimestamp: "2025-02-17T09:50:11Z"
  generation: 4
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Error
    workflows.argoproj.io/workflow-archiving-status: Archived
  name: hello-plugin
  namespace: argo
  resourceVersion: "5377104189"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/hello-plugin
  uid: 0709dfa5-3603-487d-ba45-40e1f19ccc87
spec:
  arguments: {}
  entrypoint: main
  templates:
  - dag:
      tasks:
      - arguments: {}
        name: hello
        template: hello-plugin
    inputs: {}
    metadata: {}
    name: main
    outputs: {}
  - inputs: {}
    metadata: {}
    name: hello-plugin
    outputs: {}
    plugin:
      hello: {}
status:
  artifactRepositoryRef:
    artifactRepository: {}
    default: true
  conditions:
  - status: "False"
    type: PodRunning
  - status: "True"
    type: Completed
  finishedAt: "2025-02-17T09:53:43Z"
  nodes:
    hello-plugin:
      children:
      - hello-plugin-2816962999
      displayName: hello-plugin
      finishedAt: "2025-02-17T09:53:43Z"
      id: hello-plugin
      name: hello-plugin
      outboundNodes:
      - hello-plugin-2816962999
      phase: Error
      progress: 0/1
      startedAt: "2025-02-17T09:50:11Z"
      templateName: main
      templateScope: local/hello-plugin
      type: DAG
    hello-plugin-2816962999:
      boundaryID: hello-plugin
      displayName: hello
      finishedAt: "2025-02-17T09:53:43Z"
      id: hello-plugin-2816962999
      message: Queuing
      name: hello-plugin.hello
      phase: Pending
      progress: 0/1
      startedAt: "2025-02-17T09:50:11Z"
      templateName: hello-plugin
      templateScope: local/hello-plugin
      type: Plugin
  phase: Error
  progress: 0/1
  startedAt: "2025-02-17T09:50:11Z"`

### Version(s)

latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  name: hello-plugin
spec:
  entrypoint: main
  templates:
  - dag:
      tasks:
      - arguments: {}
        name: hello
        template: hello-plugin
    name: main
  - name: hello-plugin
    plugin:
      hello: {}
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
time="2025-02-17T17:53:43.164Z" level=info msg="Processing workflow" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg=updateAgentPodStatus namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=error msg="Mark error node" error="agent pod failed with reason:\"The node was low on resource: ephemeral-storage.\"" namespace=argo nodeName=hello-plugin.hello workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="node hello-plugin-2816962999 phase Pending -> Error" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="node hello-plugin-2816962999 message: agent pod failed with reason:\"The node was low on resource: ephemeral-storage.\"" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="Outbound nodes of hello-plugin set to [hello-plugin-2816962999]" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="node hello-plugin phase Running -> Error" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="node hello-plugin finished: 2025-02-17 09:53:43.165321874 +0000 UTC" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="Checking daemoned children of hello-plugin" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg=reconcileAgentPod namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="Marking workflow as pending archiving" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.170Z" level=info msg="Workflow update successful" namespace=argo phase=Error resourceVersion=5377104182 workflow=hello-plugin
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by jswxstw** [comment]
So weird, this issue should have been fixed by #12723.

Logs as below show that node `hello-plugin-2816962999` has been marked as `Error`.
```
time="2025-02-17T17:53:43.165Z" level=error msg="Mark error node" error="agent pod failed with reason:\"The node was low on resource: ephemeral-storage.\"" namespace=argo nodeName=hello-plugin.hello workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="node hello-plugin-2816962999 phase Pending -> Error" namespace=argo workflow=hello-plugin
time="2025-02-17T17:53:43.165Z" level=info msg="node hello-plugin-2816962999 message: agent pod failed with reason:\"The node was low on resource: ephemeral-storage.\"" namespace=argo workflow=hello-plugin
```

In addition, completed taskset nodes in `WorkflowTaskSet` should also be removed.
https://github.com/argoproj/argo-workflows/blob/f5d59e9a69460196545652f89b351ee60107db0e/workflow/controller/taskset.go#L70

```YAML
hello-plugin-2816962999:
      boundaryID: hello-plugin
      displayName: hello
      finishedAt: "2025-02-17T09:53:43Z" # finishedAt is not nil, so it has already been marked as completed.
      id: hello-plugin-2816962999
      message: Queuing # I have never seen such an error message before, and here should be 'agent pod failed with reason...'
      name: hello-plugin.hello
      phase: Pending
      progress: 0/1
      startedAt: "2025-02-17T09:50:11Z"
      templateName: hello-plugin
      templateScope: local/hello-plugin
      type: Plugin
```
