### ISSUE TITLE
Failed to load version/info Error: {"code":16,"message":"token not valid} error while opening argo workflow UI

### ISSUE THREAD

**Issue by pravinjec** [argoproj/argo-workflows#14219]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Hi Team,

I am deploying argo workflow to eks cluster through its helm chart and sso enabled  and currently server and controller pods are running.
But when opening through UI login page opened but below right corner getting Failed to load version/info Error: {"code":16,"message":"token not valid error.

Also checked server logs and found below error. Not sure for which code it is mentioning not valid.

time="2025-02-24T10:02:19.375Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid. see https://argo-workflows.readthedocs.io/en/latest/faq/" grpc.code=Unauthenticated grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2025-02-24T10:02:19Z" grpc.time_ms=0.042 span.kind=server system=grpc

Also earlier i have added authmode as sso but after going through some of the issues added client as well and created token as per this doc https://argo-workflows.readthedocs.io/en/latest/access-token/#token-creation.

Then through client able to loging but getting this error if i open anything on workflow UI.

lowed to list workflows in namespace \"\". Maybe you want to specify a namespace with query parameter `.namespace=`?" grpc.code=PermissionDenied grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2025-02-24T10:03:59Z" grpc.time_ms=3.889 span.kind=server system=grpc
time="2025-02-24T10:03:59.868Z" level=info duration=4.471281ms method=GET path=/api/v1/workflows/ size=172 status=403.

My requirement is it should work through sso login and for which token it is saying not valid.
Please help me to fix the issue.

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
spec:
      containers:
      - args:
        - server
        - --configmap=argo-workflows-workflow-controller-configmap
        - --auth-mode=sso
        - --auth-mode=client
        - --secure=true
        - --loglevel
        - info
        - --gloglevel
        - "0"
        - --log-format
        - text
        env:
        - name: IN_CLUSTER
          value: "true"
        - name: ARGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ARGO_BASE_HREF
          value: /
        image: quay.io/argoproj/argocli:v3.6.2
        imagePullPolicy: Always
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

n  sessionExpiry: 0s\ntelemetryConfig: {}\nworkflowEvents:\n  enabled: true\n"
time="2025-02-24T09:50:06.695Z" level=info msg="Persistence configuration enabled"
time="2025-02-24T09:50:06.695Z" level=info msg="Node status offloading is disabled"
time="2025-02-24T09:50:06.695Z" level=info msg="Workflow archiving is enabled"
time="2025-02-24T09:50:06.695Z" level=info executorImage="quay.io/argoproj/argoexec:v3.6.2" executorImagePullPolicy= managedNamespace=
time="2025-02-24T09:50:06.795Z" level=info msg="Performing periodic GC" periodicity=5m0s
time="2025-02-24T09:50:06.795Z" level=info msg="Archived workflows TTL zero - so archived workflow GC disabled - you must restart the controller if you enable this"
time="2025-02-24T09:50:06.796Z" level=info msg="Starting CronWorkflow controller"
time="2025-02-24T09:50:06.796Z" level=info msg="Starting workflow garbage collector controller (retentionWorkers 4)"
time="2025-02-24T09:50:06.796Z" level=info msg="Started workflow garbage collection"
W0224 09:50:06.796220       1 shared_informer.go:463] The sharedIndexInformer has started, run more than once is not allowed
time="2025-02-24T09:55:06.528Z" level=info msg="Alloc=6057 TotalAlloc=15712 Sys=28501 NumGC=8 Goroutines=177"
time="2025-02-24T10:00:06.528Z" level=info msg="Alloc=6395 TotalAlloc=16822 Sys=28501 NumGC=10 Goroutines=177"
time="2025-02-24T10:05:06.528Z" level=info msg="Alloc=6221 TotalAlloc=17790 Sys=28501 NumGC=13 Goroutines=177"
Pravinku1M-BNG1:devops-k8s-deployment pravin.kumar$
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
