### ISSUE TITLE
Long arguments cause init-container to fail

### ISSUE THREAD

**Issue by MenD32** [argoproj/argo-workflows#14250]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Entering large arguments as inputs to a template causes `argument list too long` error inside the `main` container.

The usual fix would be using artifacts instead of parameters, but the problem with artifacts is that they cannot be processed dynamically using expressions.

I'm not sure what the best solution is, I think that a simple solution would be to allow passing parameters as files, using the init-container, or something similar. 

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-example-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: message
      value: '{{= repeat("A", 500000) }}'

  templates:
  - name: main
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["echo {{inputs.parameters.message}}"]
```

### Logs from the workflow controller

```text
Irrelevant
```

### Logs from in your workflow's wait container

```text
Irrelevant
```

**Comment by MenD32** [comment]
This is only an issue because of the way argo treats long parameters though. If you could mount parameters as a file it wouldn't be an issue

**Comment by jswxstw** [comment]
Not really, it fails when executing `echo AAAA...`, which is because the parameter length exceeds the `ARG_MAX` limit.

It works well if you do not use `echo`.
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-example-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: message
      value: '{{= repeat("A", 500000) }}'

  templates:
  - name: main
    inputs:
      parameters:
      - name: message
    script:
      command:
      - python
      image: python:alpine3.6
      source: |
        print("{{inputs.parameters.message}}")
```
