### ISSUE TITLE
Optional artifact yielding failed to resolve when not passed alongside withParams or withItems

### ISSUE THREAD

**Issue by macieksalwowski** [argoproj/argo-workflows#14267]
### Pre-requisites

- [x] I have double-checked my configuration
- [ ] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [ ] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

After upgrading argo from 3.5.11 to 3.5.13 we started to observe _failed to resolve_ errors in the workflows when artifact marked as _optional_ is not passed. Now, in 3.5.14, the problem still exists. 

The issue only arises when dag or task includes withItems or withParams parameter (similarly to [this issue](https://github.com/argoproj/argo-workflows/issues/6805)). To highlight, in 3.5.11 version such problem does not occur.

An example of failing workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: fail-optional-artifact-with-items
spec:
  serviceAccountName: argo
  entrypoint: artifact-example
  templates:
    - name: artifact-example
      steps:
        - - name: generate-artifact
            template: whalesay
        - - name: consume-artifact
            template: print-message
            arguments:
              artifacts:
                - name: message
                  optional: true
                  from: "{{steps.generate-artifact.outputs.artifacts.message}}"
            withItems:
              - hello world

    - name: whalesay
      container:
        image: argoproj/argosay:v1
        command: [sh, -c]
        args: ["sleep 1;"]
      outputs:
        artifacts:
          - name: message
            optional: true
            path: /tmp/hello_world
          

    - name: print-message
      inputs:
        artifacts:
          - name: message
            optional: true
            path: /tmp/message
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["test -e /tmp/message && ls /tmp/message || echo 0"]
```

And similar workflow, without withItems in task (removed lines 20, 21), that succeeds:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: success-optional-artifact-no-with-items
spec:
  serviceAccountName: argo
  entrypoint: artifact-example
  templates:
    - name: artifact-example
      steps:
        - - name: generate-artifact
            template: whalesay
        - - name: consume-artifact
            template: print-message
            arguments:
              artifacts:
                - name: message
                  optional: true
                  from: "{{steps.generate-artifact.outputs.artifacts.message}}"

    - name: whalesay
      container:
        image: argoproj/argosay:v1
        command: [sh, -c]
        args: ["sleep 1;"]
      outputs:
        artifacts:
          - name: message
            optional: true
            path: /tmp/hello_world
          

    - name: print-message
      inputs:
        artifacts:
          - name: message
            optional: true
            path: /tmp/message
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["test -e /tmp/message && ls /tmp/message || echo 0"]
```

Find also the error message from when those workflows were run on argo 3.5.14.

![Image](https://github.com/user-attachments/assets/1e1a8d58-be80-4076-a9a1-73da7afe0230)

### Version(s)

v3.5.11, v3.5.13, v3.5.14
