### ISSUE TITLE
Cannot access nested fields in items in loops

### ISSUE THREAD

**Issue by yorickdevries** [argoproj/argo-workflows#14265]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Within loops you can access items via `{{item.key}}`, however, if you have nested items, you cannot access these fields anymore.

See also: https://argo-workflows.readthedocs.io/en/latest/walk-through/loops/
If I adapt the example slightly so all items have an item with key `obj`. I get the following error:
![Image](https://github.com/user-attachments/assets/cd68524c-2242-4de0-9d79-c79032fb740c)

See the used workflow here:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-maps-
spec:
  entrypoint: loop-map-example
  templates:
  - name: loop-map-example # parameter specifies the list to iterate over
    steps:
    - - name: test-linux
        template: cat-os-release
        arguments:
          parameters:
          - name: image
            value: "{{item.obj.image}}"
          - name: tag
            value: "{{item.obj.tag}}"
        withItems:
        - { obj: { image: 'debian', tag: '9.1' }}       #item set 1
        - { obj: { image: 'debian', tag: '8.9' }}       #item set 2
        - { obj: { image: 'alpine', tag: '3.6' }}       #item set 3
        - { obj: { image: 'ubuntu', tag: '17.10' }}     #item set 4

  - name: cat-os-release
    inputs:
      parameters:
      - name: image
      - name: tag
    container:
      image: "{{inputs.parameters.image}}:{{inputs.parameters.tag}}"
      command: [cat]
      args: [/etc/os-release]
```

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-maps-
spec:
  entrypoint: loop-map-example
  templates:
  - name: loop-map-example # parameter specifies the list to iterate over
    steps:
    - - name: test-linux
        template: cat-os-release
        arguments:
          parameters:
          - name: image
            value: "{{item.obj.image}}"
          - name: tag
            value: "{{item.obj.tag}}"
        withItems:
        - { obj: { image: 'debian', tag: '9.1' }}       #item set 1
        - { obj: { image: 'debian', tag: '8.9' }}       #item set 2
        - { obj: { image: 'alpine', tag: '3.6' }}       #item set 3
        - { obj: { image: 'ubuntu', tag: '17.10' }}     #item set 4

  - name: cat-os-release
    inputs:
      parameters:
      - name: image
      - name: tag
    container:
      image: "{{inputs.parameters.image}}:{{inputs.parameters.tag}}"
      command: [cat]
      args: [/etc/os-release]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
