### ISSUE TITLE
When ArchiveStrategy is set to None (not tar/zip) empty folders are skipped

### ISSUE THREAD

**Issue by yorickdevries** [argoproj/argo-workflows#14276]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

When ArchiveStrategy is set to None (not tar/zip) empty folders are skipped.
If I have output defined as follows:
```
    outputs:
      artifacts:
      - name: output
        path: /tmp/
```

I get my folders/files properly:

![Image](https://github.com/user-attachments/assets/3c343a89-d49a-47d7-a977-5f899ef5c283)

When I apply `{archive: none: {}}` when I don't want to have my files zipped, the folder b is not written at all.

![Image](https://github.com/user-attachments/assets/4736bf86-d83a-4305-b82f-2239ebe012f2)

The workflow below demonstrates this issue

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-write-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: hello-world-to-file
    - - name: consume-artifact
        template: print-input
        arguments:
          artifacts:
          - name: input
            from: "{{steps.generate-artifact.outputs.artifacts.output}}"
 
  - name: hello-world-to-file
    script:
      command:
      - python
      image: python:3.10
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
     
        os.mkdir("/tmp/a")
        os.mkdir("/tmp/b")
       
        f = open("/tmp/a/hello.txt", "w")
        f.write("Hello world")
        f.close()
    outputs:
      artifacts:
      - name: output
        path: /tmp/
# uncommenting the following lines introduces the issue
#        archive:
#          none: {}
 
  - name: print-input
    inputs:
      artifacts:
      - name: input
        path: /tmp/
    script:
      command:
      - python
      image: python:3.10
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
     
        print(os.listdir("/tmp/"))
       
        f = open("/tmp/a/hello.txt", "r")
        print(f.read())
        f.close()
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
