### ISSUE TITLE
Retrying a timeout suspended node with different user input doesn't spin up the subsequent nodes

### ISSUE THREAD

**Issue by kush-work** [argoproj/argo-workflows#14282]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

When the workflow's suspend node times out due to no user input received; we skip the subsequent workflows. But if we retry the suspend node and give another input; the further nodes do not spin up if the input is changed.

Before retrying the timed out node
<img width="131" alt="Image" src="https://github.com/user-attachments/assets/6aafaa33-c7c4-4780-8295-cec4f8589e62" />

After retrying and supplying different input

<img width="121" alt="Image" src="https://github.com/user-attachments/assets/ea2d5482-10a6-4fb3-9ebb-644b29c1f454" />
Nothing spin up post that and there are no useful logs in either controller or containers

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: minimal-suspend-timeout-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
      - - name: wait
          template: wait
      - - name: after
          template: after

  # Suspends for 5 seconds, then times out and fails.
  - name: wait
    suspend:
      duration: "5s"

  - name: after
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["Hello, I'm after the suspend!"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

There are no logs emmitted for this event in workflow
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
