### ISSUE TITLE
Add Source field to InitContainers

### ISSUE THREAD

**Issue by jrussell9000** [argoproj/argo-workflows#14288]
# Summary

My workflows often involve passing parameters to a Python script run in advance of a containerized application. Currently, I do this using steps. It would be great to be able to do it via initContainers, but the 'Source' field isn't (currently) supported.  

## Use Cases

Any time I need to run an initial script that incorporates passed parameters.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by jrussell9000** [comment]
Getting back to this...finally.... Here's what I'd like to be able to do:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: init-container-
spec:
  entrypoint: init-container-example
  templates:
  - name: init-container-example
    container:
      image: alpine:latest
      command: ["echo", "randomint"]
      volumeMounts:
      - name: foo
        mountPath: /foo
    initContainers:
    - name: python-init
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        randomint = random.randint(1, 100)
        print(randomint)
      mirrorVolumeMounts: true
  volumes:
    - name: foo
      emptyDir: {}
``` 

Currently, "source" isn't allowed within initContainers - also I'm not certain how to go about passing the output of an initContainer script to the main container.
