### ISSUE TITLE
UI issue: Dropdown disappears when shrinking the viewport

### ISSUE THREAD

**Issue by garireo2549** [argoproj/argo-workflows#14290]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

When the UI is resized, argo-dropdown moves out of the screen.

<img width="531" alt="Image" src="https://github.com/user-attachments/assets/e09f4848-87a7-4848-bb35-96ec8dc8f984" />

### Version(s)

:latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: hello-world       # invoke the hello-world template
  templates:
    - name: hello-world         # name of the template
      container:
        image: busybox
        command: [ echo ]
        args: [ "hello world" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
```

### Logs from the workflow controller

```text
none
```

### Logs from in your workflow's wait container

```text
none
```
