### ISSUE TITLE
Not reflect input parameter values and output `placeholder-XXX` when workflow refers to WorkflowTemplate using inline templates

### ISSUE THREAD

**Issue by okzw999** [argoproj/argo-workflows#14329]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

When below all conditions are met, each input parameter value is not reflected in container process, and alternatively `placeholder-XXX` is assigned.
- Refer to WorkflowTemplate which uses inline templates for step
- In `inline`, inputs.parameters are defined and referred in container process

I confirmed not only with server environment based on MySQL, but also with local environment(MacOS) based on [quick-start-minimal](https://github.com/argoproj/argo-workflows/blob/main/manifests/quick-start-minimal.yaml).

After update to v3.6.4, submit result is below(This workflow is simply echo each parameter value.).
```
% argo submit --serviceaccount=argo -n argo test-inline-wf.yaml --log --wait    
Name:                test-inline-cmccz
Namespace:           argo
ServiceAccount:      argo
Status:              Pending
Created:             Thu Mar 13 17:43:58 +0900 (now)
Progress:            
Parameters:          
  params1:           foo1
  params2:           bar1
test-inline-cmccz-2738253414: time="2025-03-13T17:44:02.574Z" level=info msg="capturing logs" argo=true
test-inline-cmccz-2738253414: placeholder-12
test-inline-cmccz-2738253414: placeholder-13
test-inline-cmccz-2738253414: time="2025-03-13T17:44:03.576Z" level=info msg="sub-process exited" argo=true error="<nil>"
test-inline-cmccz Succeeded at 2025-03-13 17:44:08 +0900 JST
```

![Image](https://github.com/user-attachments/assets/c9b51917-2174-42f8-a377-7a91d0a7d473)

`placeholder-XXX` is already assigned at submission, confirming by `--dry-run`.
```
% argo submit --serviceaccount=argo -n argo test-inline-wf.yaml --dry-run -oyaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  generateName: test-inline-
  namespace: argo
spec:
  arguments:
    parameters:
    - name: params1
      value: foo1
    - name: params2
      value: bar1
  entrypoint: main
  serviceAccountName: argo
  templates:
  - inputs: {}
    metadata: {}
    name: main
    outputs: {}
    steps:
    - - arguments:
          parameters:
          - name: params1
            value: '{{workflow.parameters.params1}}'
          - name: params2
            value: '{{workflow.parameters.params2}}'
        name: inline
        templateRef:
          name: test-inline-template
          template: main
status:
  finishedAt: null
  startedAt: null
  storedTemplates:
    namespaced/test-inline-template/inline/inline-main:
      inputs:
        parameters:
        - name: params1
        - name: params2
      metadata: {}
      outputs: {}
      script:
        command:
        - bash
        image: XXXXX # in-house image based on rocky linux 9.
        name: ""
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 256Mi
        source: |-
          echo placeholder-12
          echo placeholder-13
    namespaced/test-inline-template/main:
      inputs:
        parameters:
        - name: params1
          value: foo
        - name: params2
          value: bar
      metadata: {}
      name: main
      outputs: {}
      steps:
      - - arguments:
            parameters:
            - name: params1
              value: '{{inputs.parameters.params1}}'
            - name: params2
              value: '{{inputs.parameters.params2}}'
          inline:
            inputs:
              parameters:
              - name: params1
              - name: params2
            metadata: {}
            outputs: {}
            script:
              command:
              - bash
              image: XXXXX # in-house image based on rocky linux 9.
              name: ""
              resources:
                limits:
                  cpu: "1"
                  memory: 512Mi
                requests:
                  cpu: "1"
                  memory: 256Mi
              source: |-
                echo {{inputs.parameters.params1}}
                echo {{inputs.parameters.params2}}
          name: inline-main
```

Before update(v3.6.3 and older), each input parameter value `foo1` and `bar1` is correctly reflected.
```
% argo submit --serviceaccount=argo -n argo test-inline-wf.yaml --log --wait    
Name:                test-inline-nh9dc
Namespace:           argo
ServiceAccount:      argo
Status:              Pending
Created:             Thu Mar 13 16:57:37 +0900 (now)
Progress:            
Parameters:          
  params1:           foo1
  params2:           bar1
test-inline-nh9dc-1515243566: time="2025-03-13T16:57:41.683Z" level=info msg="capturing logs" argo=true
test-inline-nh9dc-1515243566: foo1
test-inline-nh9dc-1515243566: bar1
test-inline-nh9dc-1515243566: time="2025-03-13T16:57:42.684Z" level=info msg="sub-process exited" argo=true error="<nil>"
test-inline-nh9dc Succeeded at 2025-03-13 16:57:47 +0900 JST
```

![Image](https://github.com/user-attachments/assets/4b292146-66e9-4a56-86cf-64f94eb5d6a8)

`--dry-run` result is also correct.
```
% argo submit --serviceaccount=argo -n argo ArgoWorkflow/test-inline-wf.yaml --dry-run -oyaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  generateName: test-inline-
  namespace: argo
spec:
  arguments:
    parameters:
    - name: params1
      value: foo1
    - name: params2
      value: bar1
  entrypoint: main
  serviceAccountName: argo
  templates:
  - inputs: {}
    metadata: {}
    name: main
    outputs: {}
    steps:
    - - arguments:
          parameters:
          - name: params1
            value: '{{workflow.parameters.params1}}'
          - name: params2
            value: '{{workflow.parameters.params2}}'
        name: inline
        templateRef:
          name: test-inline-template
          template: main
status:
  finishedAt: null
  startedAt: null
  storedTemplates:
    namespaced/test-inline-template/inline/inline-main:
      inputs:
        parameters:
        - name: params1
        - name: params2
      metadata: {}
      outputs: {}
      script:
        command:
        - bash
        image: XXXXX # in-house image based on rocky linux 9.
        name: ""
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 256Mi
        source: |-
          echo foo1
          echo bar1
    namespaced/test-inline-template/main:
      inputs:
        parameters:
        - name: params1
          value: foo
        - name: params2
          value: bar
      metadata: {}
      name: main
      outputs: {}
      steps:
      - - arguments:
            parameters:
            - name: params1
              value: '{{inputs.parameters.params1}}'
            - name: params2
              value: '{{inputs.parameters.params2}}'
          inline:
            inputs:
              parameters:
              - name: params1
              - name: params2
            metadata: {}
            outputs: {}
            script:
              command:
              - bash
              image: XXXXX # in-house image based on rocky linux 9.
              name: ""
              resources:
                limits:
                  cpu: "1"
                  memory: 512Mi
                requests:
                  cpu: "1"
                  memory: 256Mi
              source: |-
                echo {{inputs.parameters.params1}}
                echo {{inputs.parameters.params2}}
          name: inline-main
```

Additionally, this issue is NOT occurred when workflow doesn't refer to WorkflowTemplate and directly defines inline templates for step, regardless of any version.
Below is directly defined workflow submission result by v3.6.4.
```
% argo submit --serviceaccount=argo -n argo test-inline-wf-raw.yaml --log --wait
Name:                test-inline-pn7bx
Namespace:           argo
ServiceAccount:      argo
Status:              Pending
Created:             Thu Mar 13 13:28:58 +0900 (now)
Progress:            
Parameters:          
  params1:           foo1
  params2:           bar1
test-inline-pn7bx-4095344764: foo1
test-inline-pn7bx-4095344764: bar1
test-inline-pn7bx-4095344764: time="2025-03-13T13:29:03.901Z" level=info msg="sub-process exited" argo=true error="<nil>"
test-inline-pn7bx Succeeded at 2025-03-13 13:29:08 +0900 JST
```
  

I investigated this issue-occurrence pattern by changing Server/CLI version, and summarized below.

( ◯: occurred)
| Resource submitted from  | How to submit | Server | CLI | Result |
| --- | --- |  :---: |  :---: | :---: |
| Workflow  | `argo submit` | v3.5.13  | v3.5.13  | |
| Workflow  | `argo submit` | v3.5.13  | v3.6.4  | ◯ |
| Workflow  | `argo submit` | v3.6.0  | v3.6.0 | |
| Workflow  | `argo submit` | v3.6.0  | v3.6.4 | ◯ |
| Workflow  | `argo submit` | v3.6.1  | v3.6.1 | |
| Workflow  | `argo submit` | v3.6.1  | v3.6.4 | ◯ |
| Workflow  | `argo submit` | v3.6.2  | v3.6.2 | |
| Workflow  | `argo submit` | v3.6.2  | v3.6.4 | ◯ |
| Workflow  | `argo submit` | v3.6.3  | v3.6.3 | |
| Workflow  | `argo submit` | v3.6.3  | v3.6.4 | ◯ |
| Workflow  | `argo submit` | v3.6.4  | v3.5.13  | ◯ |
| Workflow  | `argo submit` | v3.6.4  | v3.6.4  | ◯ |
| Workflow  | `argo submit` | v3.6.5  | v3.6.5  | ◯ |
| Workflow  | `kubectl apply` | v3.5.13  | -  | |
| Workflow  | `kubectl apply` | v3.6.0  | -  | |
| Workflow  | `kubectl apply` | v3.6.1  | -  | |
| Workflow  | `kubectl apply` | v3.6.2  | -  | |
| Workflow  | `kubectl apply` | v3.6.3  | -  | |
| Workflow  | `kubectl apply` | v3.6.4  | -  | ◯ |
| Workflow  | `kubectl apply` | v3.6.5  | - | ◯ |
| CronWorkflow  | cronSchedule or submit button in UI  | v3.5.13  | - | - |
| CronWorkflow  | cronSchedule or submit button in UI  | v3.6.4  | - | ◯ |

As shown by above table, this issue is not occurred until Server and CLI version is v3.6.3, and is occurred from v3.6.4.
However, difference between v3.6.3 and v3.6.4 is only revert.
https://github.com/argoproj/argo-workflows/compare/v3.6.3...v3.6.4
I don't understand why the difference results in this issue.

### Version(s)

v3.6.4, v3.6.5

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
---
#### WorkflowTemplate
# test-inline-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-inline-template
spec:
  templates:
  - inputs:
      parameters:
      - name: params1
      - name: params2
    name: main
    steps:
    - - name: inline-main
        arguments:
          parameters:
          - name: params1
            value: '{{inputs.parameters.params1}}'
          - name: params2
            value: '{{inputs.parameters.params2}}'
        inline:
          inputs:
            parameters:
            - name: params1
            - name: params2
          script:
            command:
            - bash
            image: rockylinux:9 # replaced with in-house image based on rocky linux 9.
            name: ""
            resources:
              limits:
                cpu: "1"
                memory: 512Mi
              requests:
                cpu: "1"
                memory: 256Mi
            source: |-
              echo {{inputs.parameters.params1}}
              echo {{inputs.parameters.params2}}

# I confirmed it's the same result even if input parameter value in `inline` is defined as below.
#         .....
#         inline:
#           inputs:
#             parameters:
#             - name: params1
#                value: foo
#             - name: params2
#               value: bar
#           script:
#             .....

---
#### Workflow using WorkflowTemplate
# test-inline-wf.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-inline-
spec:
  arguments:
    parameters:
    - name: params1
      value: foo1
    - name: params2
      value: bar1
  entrypoint: main
  serviceAccountName: argo
  templates:
  - name: main
    steps:
    - - arguments:
          parameters:
          - name: params1
            value: '{{workflow.parameters.params1}}'
          - name: params2
            value: '{{workflow.parameters.params2}}'
        name: inline
        templateRef:
          name: test-inline-template
          template: main

---
#### Workflow NOT using WorkflowTemplate
# Below is directly defined inline process, which correctly reflect input parameters.
# test-inline-wf-raw.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-inline-
spec:
  arguments:
    parameters:
    - name: params1
      value: foo1
    - name: params2
      value: bar1
  entrypoint: main
  serviceAccountName: argo
  templates:
  - name: main
    steps:
    - - name: inline
        arguments:
          parameters:
          - name: params1
            value: '{{workflow.parameters.params1}}'
          - name: params2
            value: '{{workflow.parameters.params2}}'
        inline:
          inputs:
            parameters:
            - name: params1
            - name: params2
          script:
            command:
            - bash
            image: rockylinux:9 # replaced with in-house image based on rocky linux 9.
            name: main
            resources:
              limits:
                cpu: "1"
                memory: 512Mi
              requests:
                cpu: "1"
                memory: 256Mi
            source: |-
              echo {{inputs.parameters.params1}}
              echo {{inputs.parameters.params2}}
```

### Logs from the workflow controller

```text
time="2025-03-13T08:43:58.696Z" level=info msg="Processing workflow" Phase= ResourceVersion=1390277820 namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.706Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=test-inline-cmccz
time="2025-03-13T08:43:58.706Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.706Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.706Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.706Z" level=info msg="Steps node test-inline-cmccz initialized Running" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.706Z" level=info msg="StepGroup node test-inline-cmccz-876788866 initialized Running" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.706Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.706Z" level=info msg="Steps node test-inline-cmccz-1134888305 initialized Running" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.706Z" level=info msg="StepGroup node test-inline-cmccz-819476373 initialized Running" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.706Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.707Z" level=info msg="Pod node test-inline-cmccz-2738253414 initialized Pending" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.724Z" level=info msg="Created pod: test-inline-cmccz[0].inline[0].inline-main (test-inline-cmccz-2738253414)" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.724Z" level=info msg="Workflow step group node test-inline-cmccz-819476373 not yet completed" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.724Z" level=info msg="Workflow step group node test-inline-cmccz-876788866 not yet completed" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.724Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.724Z" level=info msg=reconcileAgentPod namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.731Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1390277824 workflow=test-inline-cmccz
time="2025-03-13T08:43:58.732Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=1390277824 namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.733Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=test-inline-cmccz
time="2025-03-13T08:43:58.733Z" level=info msg="node changed" namespace=argo new.message= new.phase=Pending new.progress=0/1 nodeID=test-inline-cmccz-2738253414 old.message= old.phase=Pending old.progress=0/1 workflow=test-inline-cmccz
time="2025-03-13T08:43:58.734Z" level=info msg="Workflow step group node test-inline-cmccz-819476373 not yet completed" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.734Z" level=info msg="Workflow step group node test-inline-cmccz-876788866 not yet completed" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.734Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.734Z" level=info msg=reconcileAgentPod namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.740Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1390277828 workflow=test-inline-cmccz
time="2025-03-13T08:43:58.742Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=1390277828 namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.742Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=test-inline-cmccz
time="2025-03-13T08:43:58.742Z" level=info msg="node unchanged" namespace=argo nodeID=test-inline-cmccz-2738253414 workflow=test-inline-cmccz
time="2025-03-13T08:43:58.743Z" level=info msg="Workflow step group node test-inline-cmccz-819476373 not yet completed" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.743Z" level=info msg="Workflow step group node test-inline-cmccz-876788866 not yet completed" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.743Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:43:58.743Z" level=info msg=reconcileAgentPod namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.723Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=1390277828 namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.724Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=test-inline-cmccz
time="2025-03-13T08:44:08.724Z" level=info msg="task-result changed" namespace=argo nodeID=test-inline-cmccz-2738253414 workflow=test-inline-cmccz
time="2025-03-13T08:44:08.724Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=test-inline-cmccz-2738253414 old.message= old.phase=Pending old.progress=0/1 workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="Step group node test-inline-cmccz-819476373 successful" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="node test-inline-cmccz-819476373 phase Running -> Succeeded" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="node test-inline-cmccz-819476373 finished: 2025-03-13 08:44:08.725489315 +0000 UTC" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="Outbound nodes of test-inline-cmccz-2738253414 is [test-inline-cmccz-2738253414]" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="Outbound nodes of test-inline-cmccz-1134888305 is [test-inline-cmccz-2738253414]" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="node test-inline-cmccz-1134888305 phase Running -> Succeeded" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="node test-inline-cmccz-1134888305 finished: 2025-03-13 08:44:08.725631812 +0000 UTC" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="Step group node test-inline-cmccz-876788866 successful" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="node test-inline-cmccz-876788866 phase Running -> Succeeded" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="node test-inline-cmccz-876788866 finished: 2025-03-13 08:44:08.725667249 +0000 UTC" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="Outbound nodes of test-inline-cmccz-1134888305 is [test-inline-cmccz-2738253414]" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="Outbound nodes of test-inline-cmccz is [test-inline-cmccz-2738253414]" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="node test-inline-cmccz phase Running -> Succeeded" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="node test-inline-cmccz finished: 2025-03-13 08:44:08.725793365 +0000 UTC" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg=reconcileAgentPod namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="Marking workflow completed" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.725Z" level=info msg="Marking workflow as pending archiving" namespace=argo workflow=test-inline-cmccz
time="2025-03-13T08:44:08.732Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=1390277969 workflow=test-inline-cmccz
time="2025-03-13T08:44:08.738Z" level=info msg="archiving workflow" namespace=argo uid=1b77c804-be87-4159-acc7-f3309ced7d89 workflow=test-inline-cmccz
time="2025-03-13T08:44:08.754Z" level=info msg="Queueing Succeeded workflow argo/test-inline-cmccz for delete in 3m0s due to TTL"
time="2025-03-13T08:44:13.738Z" level=info msg="cleaning up pod" action=deletePod key=argo/test-inline-cmccz-2738253414/deletePod
time="2025-03-13T08:47:09.001Z" level=info msg="Deleting garbage collected workflow 'argo/test-inline-cmccz'"
time="2025-03-13T08:47:09.007Z" level=info msg="Successfully request 'argo/test-inline-cmccz' to be deleted"
```

### Logs from in your workflow's wait container

```text
n/a
```
