### ISSUE TITLE
Docs reference a UI service that does not exist

### ISSUE THREAD

**Issue by mbrancato** [argoproj/argo-workflows#14327]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

These docs reference accessing the `argo-server` service after installing via Helm.

https://github.com/argoproj/argo-workflows/blob/347c2d173e6abfce0faae58f7e6913bd78d25c3b/docs/quick-start.md?plain=1#L77-L83

Additionally, when I try to access that port on the `argo-workflows-server`, it seems to be gRPC only and not HTTP. I think this is referring to a UI in a different Argo project.

I installed using helm like this:
```
helm install argo-workflows argo/argo-workflows --namespace argo --create-namespace
```

### Version(s)

v3.6.5

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
helm repo add argo https://argoproj.github.io/argo-helm
helm install argo-workflows argo/argo-workflows --namespace argo --create-namespace

kubectl -n argo port-forward service/argo-server 2746:2746
curl -v localhost:2746
```

### Logs from the workflow controller

```text
n/a

kubectl port-forward just exits, I see no logs on the server.
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by afzal442** [comment]
> it seems to be gRPC only and not HTTP. I think this is referring to a UI in a different Argo project.

Sorry! what do you mean `a UI in a different Argo project`?

**Comment by ashwatprakash-tz** [comment]
@mbrancato Can you please elaborate as to what do you mean by gRPC and not http?

**Comment by mbrancato** [comment]
> @mbrancato Can you please elaborate as to what do you mean by gRPC and not http?

@BlackStarTLM it was a protobuf response.

**Comment by mbrancato** [comment]
> > it seems to be gRPC only and not HTTP. I think this is referring to a UI in a different Argo project.
> 
> Sorry! what do you mean `a UI in a different Argo project`?

@afzal442 IIRC it was exactly as I stated, the `argo/argo-workflows` helm chart does not deploy any service resource named `argo-server`. This may be some holdover since the Argo Workflows chart used to be called `argo/argo` and maybe an older version deployed that service name.

```
% kubectl -n argo port-forward service/argo-server 2746:2746 
Error from server (NotFound): services "argo-server" not found
```

**Comment by manzil-infinity180** [comment]
@mbrancato 
This needs to be (check from `kubectl get all -n argo`)

```
kubectl -n argo port-forward services/argo-workflows-server 2746:2746 
Forwarding from 127.0.0.1:2746 -> 2746
Forwarding from [::1]:2746 -> 2746
```

**Comment by manzil-infinity180** [comment]
when you do 
```
helm install argo-workflows argo/argo-workflows --namespace argo --create-namespace --dry-run
```
and search for the service, you will find this 

```
apiVersion: v1
kind: Service
metadata:
  name: argo-workflows-server
  namespace: "argo"
  labels:
    helm.sh/chart: argo-workflows-0.45.22
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/component: server
    app: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-workflows
    app.kubernetes.io/version: "v3.7.1"
spec:

```

the docs is correct, the reason is when you do "kubectl apply -f https://github.com/argoproj/argo-workflows/releases/download/v3.7.1/quick-start-minimal.yaml", this installs the service with the service name  `argo-server`, which is what you are trying to access 

This docs is about 

https://github.com/argoproj/argo-workflows/blob/347c2d173e6abfce0faae58f7e6913bd78d25c3b/docs/quick-start.md?plain=1#L21-L35
