### ISSUE TITLE
Artifacts: HTML artifact with CSS 401 Unauthorized

### ISSUE THREAD

**Issue by Prims47** [argoproj/argo-workflows#14333]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Hello,

Context: I have created a WorkflowTemplate in which I generate a Cucumber report. I put this report in an s3 bucket and I want to preview it. I want to make sure that my WorkflowTemplate has all the rights via a serviceAccount.

The HTML page is retrieved but the CSS files return a 401.

I have an SSO authentication system on Argo Workflow.

Debug: When I look at the network I see that the HTML page in the request header has a cookie with a token, but the css calls do not.

### Version(s)

v3.4.7

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: templates-reporting-cucumber
spec:
  templates:
  - name: report
    inputs:
      artifacts:
      - name: reports
        path: /reports
        s3:
          key: '{{workflow.creationTimestamp}}-{{workflow.name}}/cucumber'
      parameters:
      - name: project
      - name: branch
      - name: browser
        value: ''
      - name: device
        value: ''
      - name: environment
        value: ''
      - name: platform
        value: ''
    container:
      image: ecr.XXX/cucumber-reporter:1.0.1-beta.1
      env:
      - name: CUCUMBER_REPORTS_PROJECT
        value: "{{inputs.parameters.project}}"
      - name: CUCUMBER_REPORTS_BUILD
        value: "{{workflow.name}}"
      - name: CUCUMBER_REPORTS_DIRECTORY
        value: /reports
      - name: CUCUMBER_REPORTS_BRANCH
        value: "{{inputs.parameters.branch}}"
      - name: CUCUMBER_REPORTS_BROWSER
        value: "{{inputs.parameters.browser}}"
      - name: CUCUMBER_REPORTS_DEVICE
        value: "{{inputs.parameters.device}}"
      - name: CUCUMBER_REPORTS_ENVIRONMENT
        value: "{{inputs.parameters.environment}}"
      - name: CUCUMBER_REPORTS_PLATFORM
        value: "{{inputs.parameters.platform}}"
    outputs:
      artifacts:
      - name: html-reports
        path: /reports/cucumber-html-reports
        s3:
          key: '{{workflow.creationTimestamp}}-{{workflow.name}}/'
        archive:
          none: { }
    serviceAccountName: argo-workflow-sa
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
