### ISSUE TITLE
Argo Sever: workflow missed workflows.argoproj.io/creator label when submitted by resubmit button in Argo UI workflows page or archived workflows page

### ISSUE THREAD

**Issue by ChenRussell** [argoproj/argo-workflows#14348]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

workflow missed `workflows.argoproj.io/creator` label when submitted by resubmit button in Argo UI workflows page or archived workflows page

### Version(s)

v3.4.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: alpine
        command: ["echo"]
        args: ["Hello, Argo!"]
```

### Logs from the workflow controller

```text
no logs
```

### Logs from in your workflow's wait container

```text
no logs
```
