### ISSUE TITLE
template annotation not available in schema, recognized by controller

### ISSUE THREAD

**Issue by sstaley-hioscar** [argoproj/argo-workflows#14377]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Unable to add annotations to template as described here:
https://argo-workflows.readthedocs.io/en/latest/walk-through/annotations/#adding-annotations-to-a-template

When adding a workflow with the annotation in that place using the editor in the GUI, the annotation is not saved, and upon refresh is not found in the template. 

Additionally, I do not see it defined in the 3.6.5 json schema:
https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.5/api/jsonschema/schema.json 
although it is defined here:
https://github.com/argoproj/argo-workflows/blob/8793d8893b68ca81800ff9c3512780636ed733cd/api/jsonschema/schema.json#L7030

### Version(s)

v.3.5.8,v3.6.5

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
spec:
  templates:
    - name: main
      annotations:
        workflows.argoproj.io/display-name: "my-custom-display-name"
      container:
        name: ""
        image: alpine:3.7
        args:
          - echo
          - $Name
        env:
          - name: USER
            value: workflow_examples
          - name: Cluster
            value: eks-oscar-1
          - name: Environment
            value: dev
          - name: Namespace
            value: workflow-examples
          - name: Role
            value: workflow_examples
          - name: Name
            value: "{{workflow.labels.app}}"
          - name: ExternalDNS
            value: "{{workflow.labels.app}}.workflow-examples.dev.hioscar.com"
          - name: InternalDNS
            value: "{{workflow.labels.app}}.workflow-examples.svc.cluster.local"
          - name: OscarCommonName
            value: "{{workflow.labels.app}}.workflow-examples.dev.oscar"
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 512Mi
            memory: 512Mi
          requests:
            cpu: 500m
            ephemeral-storage: 512Mi
            memory: 512Mi
        imagePullPolicy: IfNotPresent
      retryStrategy:
        limit: 1
        retryPolicy: OnTransientError
  entrypoint: main
  arguments: {}
  ttlStrategy:
    secondsAfterCompletion: 604800
  podDisruptionBudget:
    minAvailable: 100
  workflowMetadata:
    labels:
      app: container-dev
      app.kubernetes.io/instance: container-dev
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: container-dev
      meta.helm.sh/release-namespace: workflow-examples
      release: prometheus
      workflow_template: container-dev
```

### Logs from the workflow controller

```text
nothing of note
```

### Logs from in your workflow's wait container

```text
N/A
```
