### ISSUE TITLE
GitHub webhook authentication fails for `workflow_run` event type but works for release event type

### ISSUE THREAD

**Issue by mapou-dr** [argoproj/argo-workflows#14388]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

When sending GitHub webhook events to Argo Workflows, I've discovered that some event types are properly authenticated while others are rejected with a 401 error. Specifically:

- GitHub `release` events with action `published` are properly processed
- GitHub `workflow_run` events with action `completed` are rejected with error: `{"code":16,"message":"token not valid. see https://argo-workflows.readthedocs.io/en/release-3.5/faq/"}`

The issue appears to be that the GitHub webhook handler in Argo Workflows doesn't recognize or properly authenticate newer GitHub event types like `workflow_run`, `workflow_dispatch`, and `workflow_job`. These events are documented in GitHub's webhook documentation but aren't included in Argo's event handling code.

**Expected behavior:** All valid GitHub webhook events should be authenticated and processed similarly, regardless of event type.

### Version(s)

v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
The issue can be reproduced with this WorkflowEventBinding:
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: workflow-run-completed-binding
  namespace: github-webhook-processor
spec:
  event:
    selector: payload.action == "completed" && metadata["x-github-event"] == ["workflow_run"]
  submit:
    workflowTemplateRef:
      name: workflow-run-completed
    arguments:
      parameters:
        - name: payload
          valueFrom:
            event: payload
        - name: github-event
          valueFrom:
            event: metadata["x-github-event"][0]
        - name: github-hook-id
          valueFrom:
            event: metadata["x-github-hook-id"][0]
        - name: github-delivery
          valueFrom:
            event: metadata["x-github-delivery"][0]

And webhook clients secret:
kind: Secret
apiVersion: v1
metadata:
  name: argo-workflows-webhook-clients
  namespace: github-webhook-processor
stringData:
  github.com: |
    type: github
    secret: "your-webhook-secret"
```

### Logs from the workflow controller

```text
argo-workflows-server-d8675cc7c-hw6gs time="2025-04-15T12:54:41.542Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid. see https://argo-workflows.readthedocs.io/en/release-3.5/faq/" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2025-04-15T12:54:41Z" grpc.time_ms=0.04 span.kind=server system=grpc
```

### Logs from in your workflow's wait container

```text
nothing here
```
