### ISSUE TITLE
ArtifactGC with `archive: none` fails silently when artifact key does not end with a slash (`/`)

### ISSUE THREAD

**Issue by alexdittmann** [argoproj/argo-workflows#14387]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I was testing out artifactGC for (s3) output artifacts with the `archive: none: {}` option set and it was not working as expected. I then found this issue: https://github.com/argoproj/argo-workflows/issues/12857 which should have already resolved this. I realized that the behavior is due to the way i defined the output artifact key. 
In my example workflow, i dont end the s3 key with a slash (`/`). This causes the artifact to not be correctly identified as a directory anymore, which i think is because of these changes: https://github.com/argoproj/argo-workflows/pull/13091/files. It only checks, if the artifact key ends with a slash instead of doing a "real" check for directory. As a result, the artifacts are not deleted. No error about this is thrown either and it seems that artifactGC succeeded. See also this status output:
```yaml
status:
  artifactGCStatus:
    podsRecouped:
      artficat-gc-archive-none-artgc-wfcomp-2166136261: true
    strategiesProcessed:
      OnWorkflowCompletion: true
  conditions:
  - status: "False"
    type: PodRunning
  - status: "True"
    type: Completed
  finishedAt: "2025-04-15T11:17:18Z"
  nodes:
    artficat-gc-archive-none:
      displayName: artficat-gc-archive-none
      finishedAt: "2025-04-15T11:17:15Z"
      hostNodeName: k3d-k3s-default-server-0
      id: artficat-gc-archive-none
      name: artficat-gc-archive-none
      outputs:
        artifacts:
        - archive:
            none: {}
          deleted: true  # shows deleted, but is not
          name: dontKeepDir
          path: /tmp/dontKeepDir
          s3:
            key: aaaaaaaaaa/dontKeepDir # no trailing slash
            ...
        - deleted: true
          name: main-logs
          s3:
            key: artficat-gc-archive-none/artficat-gc-archive-none/main.log
        exitCode: "0"
      phase: Succeeded
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      startedAt: "2025-04-15T11:17:10Z"
      templateName: output-artifact-gc
      templateScope: local/artficat-gc-archive-none
      type: Pod
  phase: Succeeded
  progress: 1/1
  resourcesDuration:
    cpu: 0
    memory: 2
  startedAt: "2025-04-15T11:17:10Z"
  taskResultsCompletionStatus:
    artficat-gc-archive-none: true
```

Im not sure if this counts as bug or wrong usage, but defining directory-style output artifacts like that without a trailing slash generally works fine in workflows. So I would assume this also applies to artifactGC.

### Version(s)

latest (9b7c0c4c4ce1ecb8e1d27df95d14ccef09cffe0f)

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: artficat-gc-archive-none
  namespace: argo
spec:
  artifactGC:
    strategy: OnWorkflowCompletion
    forceFinalizerRemoval: true
  entrypoint: output-artifact-gc
  templates:
    - container:
        args:
          - mkdir /tmp/dontKeepDir && echo "hello" > /tmp/dontKeepDir/hello1.txt && echo "hello" > /tmp/dontKeepDir/hello2.tx
        command:
          - sh
          - '-c'
        image: >-
          nginx
      name: output-artifact-gc
      outputs:
        artifacts:
          - name: dontKeepDir
            path: /tmp/dontKeepDir
            archive:
              none: {}
            s3:
              key: aaaaaaaaaa/dontKeepDir  # no trailing slash
              ...
```

### Logs from the workflow controller

```text
-
```

### Logs from in your workflow's wait container

```text
time="2025-04-15T11:16:25.001Z" level=info msg="S3 Delete artifact: key: aaaaaaaaaa/dontKeepDir"
time="2025-04-15T11:16:25.100Z" level=info msg="Creating minio client using static credentials" endpoint=***
time="2025-04-15T11:16:25.100Z" level=info msg="Deleting object from s3" bucket=*** endpoint=*** key=aaaaaaaaaa/dontKeepDir
time="2025-04-15T11:16:25.248Z" level=info msg="S3 Delete artifact: key: artficat-gc-archive-none/artficat-gc-archive-none/main.log"
time="2025-04-15T11:16:25.250Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2025-04-15T11:16:25.250Z" level=info msg="Deleting object from s3" bucket=my-bucket endpoint="minio:9000" key=artficat-gc-archive-none/artficat-gc-archive-none/main.log
```
