### ISSUE TITLE
Workflow status is `successful` even though a task failed

### ISSUE THREAD

**Issue by hanneskaeufler** [argoproj/argo-workflows#14399]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

We have some workflows which had an error in a task, causing them to receive an invalid podspecpatch.
```
task '52186919-4b86-4a39-8282-f0bca485f210' errored: Error applying PodSpecPatch
```

This should cause the workflow to fail.
However, the logs of the task which receives the `{{workflow.status}}` as an input argument show us that `{{workflow.status}}` evaluated to `successful`.

```
  [...]
  "job_id": "52186919-4b86-4a39-8282-f0bca485f210",
  "state": "SUCCESSFUL", # we .UPPER the status in python
```

![Image](https://github.com/user-attachments/assets/1e49d7de-5235-4aea-aaa6-06b2873619a4)

![Image](https://github.com/user-attachments/assets/5aeaab52-2fe0-46f0-9da6-faf29df9fb27)

I have not yet been able to repro this with a minimal example, but this is essentially the structure:

### Version(s)

v3.6.4

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
spec:
  templates:
    - name: raas
      inputs: {}
      outputs: {}
      metadata: {}
      dag:
        tasks:
          - name: a
            template: start
            arguments: {}
          - name: b
            template: start
            arguments: {}
            depends: a
          - name: c
            template: start
            arguments: {}
            when: "false"
            depends: b
    - name: start
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: python:latest
        command:
          - python3
        resources: {}
        imagePullPolicy: Always
      podSpecPatch: "{{=sprig.something}}"
    - name: workflow-cleanup
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: python:latest
        command:
          - python3
        args:
          - -c
          - print('{{workflow.status}}')
        resources: {}
        imagePullPolicy: Always
  entrypoint: my-entrypoint
  arguments: {}
  ttlStrategy:
    secondsAfterCompletion: 300
    secondsAfterSuccess: 300
    secondsAfterFailure: 300
  hooks:
    exit:
      template: workflow-cleanup
      arguments: {}
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```
