### ISSUE TITLE
bump github.com/argoproj/argo-events from 1.9.1 to 1.9.6

### ISSUE THREAD

**Issue by vkamlesh** [argoproj/argo-workflows#14394]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Argo-event version bumps to v1.9.6 to fix https://github.com/advisories/GHSA-hmp7-x699-cvhq

### Version(s)

e99702e9c423246050346a2ef590d48410998877

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: artficat-gc-archive-none
  namespace: argo
spec:
  artifactGC:
    strategy: OnWorkflowCompletion
    forceFinalizerRemoval: true
  entrypoint: output-artifact-gc
  templates:
    - container:
        args:
          - mkdir /tmp/dontKeepDir && echo "hello" > /tmp/dontKeepDir/hello1.txt && echo "hello" > /tmp/dontKeepDir/hello2.tx
        command:
          - sh
          - '-c'
        image: >-
          nginx
      name: output-artifact-gc
      outputs:
        artifacts:
          - name: dontKeepDir
            path: /tmp/dontKeepDir
            archive:
              none: {}
            s3:
              key: aaaaaaaaaa/dontKeepDir  # no trailing slash
              ...
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
