### ISSUE TITLE
when expression fails under high parallel workflow load Summary

### ISSUE THREAD

**Issue by ferhirata** [argoproj/argo-workflows#14408]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

🐛 Bug Report: when expression fails under high parallel workflow load
Summary
We're encountering a recurring issue where when expressions fail to evaluate correctly under high parallel workflow execution. This problem only happens when many workflows are triggered concurrently. The same workflow executes correctly when run individually.

We are running Argo Workflows version 3.6.4 on Google Kubernetes Engine (GKE) in Google Cloud Platform (GCP).

📋 Version
Argo Workflows: v3.6.4

Kubernetes: 1.31.6-gke.1020000 (GKE)

Platform: GCP (Google Kubernetes Engine)

🔁 Steps to Reproduce
Submit a workflow that includes a script step writing output to a file and exposing it via outputs.parameters.

Use the output in a when: condition or in withParam.

Trigger multiple instances of the workflow (e.g., 200–300) concurrently.

Observe that many workflows fail with expression-related errors.

🧪 Example Error
Invalid 'when' expression '{{tasks.model-counter.outputs.parameters.result}} > 2': Invalid token: '{{' (hint: try wrapping the affected expression in quotes ("))

🔍 Observations
The model-counter-template step writes an integer to a file and outputs it as a parameter using valueFrom.path.

In high-concurrency scenarios, the value is either not written in time or not recognized by the controller.

The issue is not present when workflows are executed sequentially.

This behavior did not occur in Argo Workflows v3.2.2 with the same workflow YAML.

### Version(s)

v3.6.4

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
- name: model-counter-template 
    retryStrategy:
      limit: "3"
      retryPolicy: "Always"
    inputs:
      artifacts:
        - name: model-counter
          path: /tmp/model-counter
          mode: 0777
          gcs:
            bucket: 'INTERMEDIATE_BUCKET_NAME'
            key: "FILE_NAME/model-counter/"
    script:
      image: python:3.9-slim
      command: [ python ]
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        runAsGroup: 1000
      source: |
        import os
        import time

        def countmodels(path):
            count = 0
            if os.path.exists(path):
                for file in os.listdir(path):
                    full_path = os.path.join(path, file)
                    if os.path.isfile(full_path):
                        try:
                            with open(full_path) as f:
                                tmp = f.readlines()
                                count += int(*tmp)
                        except:
                            continue
            return count

        result_path = "/tmp/model-counter-result.txt"

        # Tenta escrever com segurança
        try:
            with open(result_path, "w") as f:
                f.write(str(countmodels('/tmp/model-counter')))
                f.flush()
                os.fsync(f.fileno())
        except Exception as e:
            print("Erro ao salvar resultado:", e)
            with open(result_path, "w") as f:
                f.write("0")

        # Aguarda até que o arquivo esteja de fato visível no sistema
        for _ in range(5):  # tenta por até ~5 segundos
            if os.path.exists(result_path):
                break
            print(f"Aguardando {result_path} aparecer...")
            time.sleep(1)
    outputs:
      parameters:
        - name: result
          valueFrom:
            path: /tmp/model-counter-result.txt


      - name: exit-zero-models
        depends: "model-counter.Succeeded"
        template: exit-dag
        when: "{{tasks.model-counter.outputs.parameters.result}} == 0"
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
