### ISSUE TITLE
YAML of output parameters

### ISSUE THREAD

**Issue by doteric** [argoproj/argo-workflows#14406]
# Summary

A great addition would be to allow specifying a yaml to grab the output parameters from and use them as desired.

## Use Cases

A chunky yaml file of multiple different outputs generated and extracting all those values to separated file and defining each on separately makes the workflow yaml quite "heavy".

Example:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-example-wf-template
  namespace: argo-workflows
spec:
  templates:
    - name: my-example-job-template
      script:
        image: some_image
        command: [sh]
        source: |
          # Some script that will generate a YAML full of different parameters (example yaml below)
      outputs:
        parameters:
          - fromYaml:
              path: /tmp/example.yml
```

Example YAML:
```
param1:
  inner1:  "hello_world"
param2: "world2"
example: "example"
```

Example usage of output:
```
- name: second-job
   depends: 'my-example-job'
   template: second-job-template
   when: '{{tasks.my-example-job.outputs.parameters.param1.inner1}} == "hello_world"'
```

Potentially arrays  could also be supported, but not crucial.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.
