### ISSUE TITLE
There doesn't seem to be a way to leverage argo workflows to generate argocd applications

### ISSUE THREAD

**Issue by nunoo** [argoproj/argo-workflows#14413]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I'm trying to leverage argo workflows to generate argocd applications. I'm using the Resource template type, with the following conditions:

	Resource: &wfv1.ResourceTemplate{
		Action: "apply",
		Manifest:         argoCDAppStr,
		SuccessCondition: "status.sync.status == Synced,status.health.status == Healthy",
		FailureCondition: "status.health.status notin (Healthy,Progressing,)",
	},
However this can fail if the app was in a prior bad state, as it doesn't reset the condition. Is there a recommended way to check if argocd is healthy, or should I use a custom container to set this up?

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
Resource: &wfv1.ResourceTemplate{
		Action: "apply",
		Manifest:         argoCDAppStr,
		SuccessCondition: "status.sync.status == Synced,status.health.status == Healthy",
		FailureCondition: "status.health.status notin (Healthy,Progressing,)",
	},
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by caelan-io** [comment]
It looks like you'll need to use a custom script container for now to achieve this.

One approach to solve this is to use an inline script to execute kubectl commands on resources. Below is an example of a `wait --for=` command:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: k8s-jobs-
  namespace: argo-workflows
spec:
  entrypoint: wait
  templates:
    - name: wait
      steps:
        - - name: wait
            inline:
              script:
                name: wait
                image: alpine/kubectl:latest
                command:
                  - sh
                  - -c
                source: |
                  kubectl config set-cluster kubernetes --server=https://${KUBERNETES_SERVICE_HOST} --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                  kubectl config set-credentials sa-user --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)                  
                  kubectl config set-context kubernetes --cluster=kubernetes --user=sa-user
                  kubectl wait --for=jsonpath='{.metadata.annotations.workflows\.argoproj\.io/version}'="v1.0"  workflowtemplate/my-pipeline -n argo-workflows
```

Argo Workflows could add wait as a supported action, or even others. Adding wait would make it more intuitive/ native in Argo WF versus having to write an inline script like the above.
- The trouble with adding wait as an action is we also need to add a param for “what we want to wait for”, i.e. waitFor field.
- This would be a medium to large feature and would touch quite a bit of code
