### ISSUE TITLE
ArgoWF 3.6.5 outputs custom metrics type incorrectly in prometheus endpoint

### ISSUE THREAD

**Issue by anderskotsalaineneqt** [argoproj/argo-workflows#14425]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Hi,
To start this bug has been discussed here in the Cloud-native-computing slack [thread](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1744123416283909) and been confirmed as a bug by @Joibel 

The basic issue is that if one is outputting a custom metric of type "Counter" in one's workflow as shown in the example below the type of the metric is set as "Gauge" in the metric type shown in the promethues endpoint "/metric"

**Example workflow with custom metric**
```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: download-clamav-daily
spec:
  podGC:
    strategy: OnWorkflowCompletion
  volumeClaimGC:
    strategy: OnWorkflowCompletion
  schedule: "0 8 * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    arguments:
      parameters:
        - name: bucket-name
          value: "lp-unpackman-stage"
    serviceAccountName: conveyor-events
    entrypoint: downloader
    templates:
      - name: downloader
        volumes:
        container:
          image: image-name-clamav-server
          command: [sh]
          args:
            - "-ce"
            - |
              unzip -o /tmp/clamav-db-in.zip -d /var/lib/clamav/
              ls -la /var/lib/clamav
              freshclam
              zip /tmp/clamav-db-out.zip /var/lib/clamav/*
        inputs:
          artifacts:
            - name: daily-db-input
              path: "/tmp/clamav-db-in.zip"
              gcs:
                bucket: "{{workflow.parameters.bucket-name}}"
                key: "clamav/clamav-db.zip"
        outputs:
          artifacts:
            - name: daily-db-output
              path: "/tmp/clamav-db-out.zip"
              gcs:
                bucket: "{{workflow.parameters.bucket-name}}"
                key: "clamav/clamav-db.zip"
              archive:
                none: {}
    podMetadata:
      labels:
        team: lp-portal
        tags.datadoghq.com/env: stage
        tags.datadoghq.com/service: lp-conveyor.download-clamav-daily
        tags.datadoghq.com/version: "627cad995d12e8c72b74a7e84027b9463925229f"
    metrics:
      prometheus:
        - name: result_counter
          help: "Count of workflow execution by result status"
          labels:
            - key: workflow_name
              value: download-clamav-daily
            - key: status
              value: "{{status}}"
            - key: team
              value: lp-portal
            - key: service
              value: lp-conveyor.download-clamav-daily
            - key: env
              value: stage
          counter:
            value: "1"
```

In Argo WF 3.5.4 this metric is output like this at /metrics
```
# HELP argo_workflows_result_counter Count of workflow execution by result status
# TYPE argo_workflows_error_count counter
argo_workflows_error_count{cause="CronWorkflowSpecError"} 0
argo_workflows_error_count{cause="CronWorkflowSubmissionError"} 0
```

In Argo WF 3.6.5 this metric is output like this at /metrics
```
# HELP argo_workflows_result_counter Count of workflow execution by result status
# TYPE argo_workflows_result_counter gauge
argo_workflows_result_counter{env="area2",service="lp-portal-commander.export-schema",status="Failed",team="lp-portal",workflow_name="export-schema"} 1

This change in metric type changes how Datadog ingests the metric/displays the metric and how Datadog monitors looking for successful runs of workflows can be set up.
```

### Version(s)

v.3.6.5

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: brett-flakey-test
  namespace: hello-i-am
spec:
  schedule: "*/25 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: flakey
    metrics:
      prometheus:
      - name: cron_count_failed
        help: Count of workflows with Failed status
        labels:
        - key: pod_name
          value: brett-flakey-test
        - key: namespace
          value: hello-i-am
        when: "{{workflow.status}} == 'Failed'"
        counter:
          value: '1'
      - name: cron_count_error
        help: Count of workflows with Error status
        labels:
        - key: pod_name
          value: brett-flakey-test
        - key: namespace
          value: hello-i-am
        when: "{{workflow.status}} == 'Error'"
        counter:
          value: '1'
      - name: cron_count_succeeded
        help: Count of workflows with Succeeded status
        labels:
        - key: pod_name
          value: brett-flakey-test
        - key: namespace
          value: hello-i-am
        when: "{{workflow.status}} == 'Succeeded'"
        counter:
          value: '1'
      - name: cron_runtime_duration
        help: How long is the workflow running
        labels:
        - key: pod_name
          value: brett-flakey-test
        - key: namespace
          value: hello-i-am
        gauge:
          realtime: true
          value: '{{duration}}'
    templates:
    - name: flakey
      metrics:
      container:
        image: python:alpine3.6
        command: ["python", -c]
        # fail with a 66% probability
        args: ["import random; import sys; exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)"]
```

### Logs from the workflow controller

```text
not relevant
```

### Logs from in your workflow's wait container

```text
not relevant
```

**Comment by nicdard** [comment]
I would like to work on this :)

**Comment by Joibel** [comment]
> I would like to try taking a look at this :)

Please do, I've assigned it to you for now.

**Comment by nicdard** [comment]
Hey @Joibel sorry for the late reply I was sick
I will start to have a better look at this in the weekend, I might contact you in the next days

**Comment by C0deWave** [comment]
Hi, I’m also experiencing the same issue on Argo Workflows v3.6.10.
It seems that this problem still exists in this version as well.

**Comment by benoit-parmentier-2** [comment]
## Argo Template

I just tested it with the configuration below.

```yaml
      - name: workflow_status_count
        help: "Workflow status"
        counter:
          value: "1"
        labels:
          - key: argo_workflow_basename
            value: "{{workflow.parameters.workflow_basename}}"
          - key: status
            value: "{{workflow.status}}"
```

## Behaviour 

CHART VERSION : `0.42.7` and APP VERSION: `v3.5.12`
The `argo_workflows_workflow_status_count` metric is correctly returned as Counter 🟢 

```yaml
# HELP argo_workflows_step_status_count Step Status
# TYPE argo_workflows_step_status_count Counter
argo_workflows_workflow_status_count{argo_workflow_basename="workflow-example",status="Failed"} 1
```

CHART VERSION : `0.43.0` and APP VERSION: `v3.6.0`
The `argo_workflows_workflow_status_count` metric is returned as Gauge 🔴  

```yaml
# HELP argo_workflows_workflow_status_count Workflow Status
# TYPE argo_workflows_workflow_status_count Gauge
argo_workflows_workflow_status_count{argo_workflow_basename="workflow-example",status="Failed"} 1
```

## Conclusion

The regression was introduced in version `v3.6.0`.

This bug prevents my monitoring from working properly. ☹️

🌻  @nicdard Do you know where this bug comes from ? 🙏
