### ISSUE TITLE
"Allowing referencing template-input-parameters or workflow-parameters in outputs.parameters.valueFrom.parameter"

### ISSUE THREAD

**Issue by itai1357** [argoproj/argo-workflows#14423]
# Summary
When defining a WorkflowTemplate, I attempted to expose a template's input parameter as an output parameter using outputs.parameters.valueFrom.parameter. This is useful for passing parameters through a step or exposing them at the workflow level for reuse or inspection.

However, referencing inputs.parameters.X / workflow.parameters.X in the valueFrom.parameter field causes the workflow to fail at runtime. This limitation makes it difficult to pass through parameters without explicitly echoing them to a file and reading them back.

Expected behavior:
It should be possible to write something like:
```
outputs:
  parameters:
    - name: original-input
      valueFrom:
        parameter: '{{inputs.parameters.some-input}}'
```

Actual behavior:
This results in a runtime error, even though the value exists at execution time.

Would love to hear if this behavior is by design or if support for this could be added.
What change needs making?

## Use Cases

Supporting this would allow cleaner workflows, avoiding unnecessary script templates just to forward parameter values.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by itai1357** [comment]
I just solve it. I thought I tried it before but apperently I missed it

this one is working (without '{{' and '}}')

```
outputs:
  parameters:
    - name: original-input
      valueFrom:
        parameter: '{{inputs.parameters.some-input}}'
```
