### ISSUE TITLE
`withParam` incompatible with `CronWorkflow`

### ISSUE THREAD

**Issue by cmdoret** [argoproj/argo-workflows#14436]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Using `withParam` to enable dynamic fan-out works as expected in a regular `Workflow`, but it crashes in a `CronWorkflow` (even when using a `WorkflowTemplate`).

**Expected:** withParam dynamically creates tasks based on a json list.
**Observed:** The workflow crashes with:
```
withParam value could not be parsed as a JSON list: {{tasks.find-new-files.outputs.result}}: invalid character '{' looking for beginning of object key string
```
> Note: it works as expected if the json list contains a single element.

### Version(s)

v3.6.7

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

Does not work:
```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: demo-scheduler
spec:
  schedule: "*/5 * * * *"
  timezone: "UTC"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 300
  workflowSpec:
    workflowTemplateRef:
      name: demo-parser
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: demo-parser
spec:
  entrypoint: process-new-files
  templates:
  - name: process-new-files
    dag:
      tasks:
      - name: find-new-files
        template: find-new-files

      - name: process-dir
        dependencies: [find-new-files]
        template: process-dir
        arguments:
          parameters:
          - name: catplus_dir
            value: "{{item}}"
        withParam: "{{tasks.find-new-files.outputs.result}}" # <<<< FAILS HERE

  - name: find-new-files
    script:
      image: alpine:latest
      command: [sh]
      source: |
        #!/bin/sh
        # pretend to do work
        echo -n "[\"1.txt\",\"2.txt\"]"

  - name: process-dir
    inputs:
      parameters:
      - name: catplus_dir
    container:
      image: alpine:latest
      command: ["echo", "{{inputs.parameters.catplus_dir}}"] 
```

This works:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demo-scheduler
spec:
  entrypoint: process-new-files
  templates:
  - name: process-new-files
    dag:
      tasks:
      - name: find-new-files
        template: find-new-files

      - name: process-dir
        dependencies: [find-new-files]
        template: process-dir
        arguments:
          parameters:
          - name: catplus_dir
            value: "{{item}}"
        withParam: "{{tasks.find-new-files.outputs.result}}"

  - name: find-new-files
    script:
      image: alpine:latest
      command: [sh]
      source: |
        #!/bin/sh
        # pretend to do work
        echo -n "[\"1.txt\",\"2.txt\"]"

  - name: process-dir
    inputs:
      parameters:
      - name: catplus_dir
    container:
      image: alpine:latest
      command: ["echo", "{{inputs.parameters.catplus_dir}}"]
```

### Logs from the workflow controller

```text
time="2025-04-30T11:05:00.000Z" level=info msg="Running demo-scheduler" namespace=argo workflow=demo-scheduler
time="2025-04-30T11:05:00.073Z" level=info msg="Processing workflow" Phase= ResourceVersion=21152082 namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.084Z" level=info msg="Processing argo/demo-scheduler" cronWorkflow=argo/demo-scheduler
time="2025-04-30T11:05:00.086Z" level=info msg="CronWorkflow argo/demo-scheduler added" cronWorkflow=argo/demo-scheduler
time="2025-04-30T11:05:00.165Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.165Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.165Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.165Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.165Z" level=info msg="DAG node demo-scheduler-1746011100 initialized Running" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.165Z" level=warning msg="was unable to obtain the node for demo-scheduler-1746011100-228480475, taskName process-dir"
time="2025-04-30T11:05:00.165Z" level=warning msg="was unable to obtain the node for demo-scheduler-1746011100-1869838126, taskName find-new-files"
time="2025-04-30T11:05:00.165Z" level=warning msg="was unable to obtain the node for demo-scheduler-1746011100-1869838126, taskName find-new-files"
time="2025-04-30T11:05:00.165Z" level=info msg="All of node demo-scheduler-1746011100.find-new-files dependencies [] completed" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.165Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.165Z" level=info msg="Pod node demo-scheduler-1746011100-1869838126 initialized Pending" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.177Z" level=info msg="Created pod: demo-scheduler-1746011100.find-new-files (demo-scheduler-1746011100-find-new-files-1869838126)" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.177Z" level=warning msg="was unable to obtain the node for demo-scheduler-1746011100-228480475, taskName process-dir"
time="2025-04-30T11:05:00.177Z" level=warning msg="was unable to obtain the node for demo-scheduler-1746011100-228480475, taskName process-dir"
time="2025-04-30T11:05:00.177Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.177Z" level=info msg=reconcileAgentPod namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00Z" level=info msg="add pod event" pod=demo-scheduler-1746011100-find-new-files-1869838126
time="2025-04-30T11:05:00Z" level=info msg="update pod event" pod=demo-scheduler-1746011100-find-new-files-1869838126
time="2025-04-30T11:05:00Z" level=info msg="update pod event" pod=demo-scheduler-1746011100-find-new-files-1869838126
time="2025-04-30T11:05:00.268Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=21152105 workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.270Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=21152105 namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.270Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.270Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=demo-scheduler-1746011100-1869838126 old.message= old.phase=Pending old.progre
ss=0/1 workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.270Z" level=warning msg="was unable to obtain the node for demo-scheduler-1746011100-228480475, taskName process-dir"
time="2025-04-30T11:05:00.270Z" level=warning msg="was unable to obtain the node for demo-scheduler-1746011100-228480475, taskName process-dir"
time="2025-04-30T11:05:00.270Z" level=warning msg="was unable to obtain the node for demo-scheduler-1746011100-228480475, taskName process-dir"
time="2025-04-30T11:05:00.270Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.270Z" level=info msg=reconcileAgentPod namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:00.368Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=21152107 workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:01Z" level=info msg="update pod event" pod=demo-scheduler-1746011100-find-new-files-1869838126
time="2025-04-30T11:05:03Z" level=info msg="update pod event" pod=demo-scheduler-1746011100-find-new-files-1869838126
time="2025-04-30T11:05:04Z" level=info msg="update pod event" pod=demo-scheduler-1746011100-find-new-files-1869838126
time="2025-04-30T11:05:05Z" level=info msg="update pod event" pod=demo-scheduler-1746011100-find-new-files-1869838126
time="2025-04-30T11:05:10.178Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=21152107 namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.178Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.179Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=demo-scheduler-1746011100-1869838126 old.message=PodInitializing old.phase=Pending old.prog
ress=0/1 workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.179Z" level=warning msg="was unable to obtain the node for demo-scheduler-1746011100-228480475, taskName process-dir"
time="2025-04-30T11:05:10.179Z" level=warning msg="was unable to obtain the node for demo-scheduler-1746011100-228480475, taskName process-dir"
time="2025-04-30T11:05:10.180Z" level=info msg="Skipped node demo-scheduler-1746011100-228480475 initialized Error (message: withParam value could not be parsed as a JSON list: {{tasks.find-new-files.outputs.result}}: invalid
 character '{' looking for beginning of object key string)" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.180Z" level=info msg="Outbound nodes of demo-scheduler-1746011100 set to [demo-scheduler-1746011100-228480475]" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.180Z" level=info msg="node demo-scheduler-1746011100 phase Running -> Error" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.180Z" level=info msg="node demo-scheduler-1746011100 finished: 2025-04-30 11:05:10.18016382 +0000 UTC" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.180Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.180Z" level=info msg=reconcileAgentPod namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.180Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.180Z" level=info msg="Marking workflow completed" namespace=argo workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10.199Z" level=info msg="Workflow update successful" namespace=argo phase=Error resourceVersion=21152194 workflow=demo-scheduler-1746011100
time="2025-04-30T11:05:10Z" level=info msg="queueing pod for cleanup" action=labelPodCompleted namespace=argo podName=demo-scheduler-1746011100-find-new-files-1869838126
time="2025-04-30T11:05:10Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/demo-scheduler-1746011100-find-new-files-1869838126/labelPodCompleted namespace=argo podName=demo-scheduler-1746011100-find-new-fi
les-1869838126
time="2025-04-30T11:05:10Z" level=info msg="delete pod event" pod=demo-scheduler-1746011100-find-new-files-1869838126
time="2025-04-30T11:05:13.565Z" level=info msg="Deleted Workflow 'demo-scheduler-xq9zc' due to CronWorkflow 'demo-scheduler' history limit" namespace=argo workflow=demo-scheduler
time="2025-04-30T11:05:13.578Z" level=info msg="Processing argo/demo-scheduler" cronWorkflow=argo/demo-scheduler
time="2025-04-30T11:05:13.579Z" level=info msg="CronWorkflow argo/demo-scheduler added" cronWorkflow=argo/demo-scheduler
```

### Logs from in your workflow's wait container

```text
time="2025-04-30T11:02:47.292Z" level=info msg="Starting Workflow Executor" version=v3.6.7
time="2025-04-30T11:02:47.298Z" level=info msg="Using executor retry strategy" Duration=1s Fact
or=1.6 Jitter=0.5 Steps=5
time="2025-04-30T11:02:47.298Z" level=info msg="Executor initialized" deadline="0001-01-01 00:0
0:00 +0000 UTC" includeScriptOutput=false namespace=argo podName=demo-scheduler-process-dir-121
5897085 templateName=process-dir version="&Version{Version:v3.6.7,BuildDate:2025-04-29T16:21:04
Z,GitCommit:8d7dae690e152d19fb40f7affbb68fb783b32172,GitTag:v3.6.7,GitTreeState:clean,GoVersion
:go1.24.2,Compiler:gc,Platform:linux/amd64,}"
time="2025-04-30T11:02:47.316Z" level=info msg="Starting deadline monitor"
time="2025-04-30T11:02:49.317Z" level=info msg="Main container completed" error="<nil>"
time="2025-04-30T11:02:49.317Z" level=info msg="No Script output reference in workflow. Capturi
ng script output ignored"
time="2025-04-30T11:02:49.317Z" level=info msg="No output parameters"
time="2025-04-30T11:02:49.317Z" level=info msg="No output artifacts"
time="2025-04-30T11:02:49.342Z" level=info msg="Alloc=11792 TotalAlloc=16349 Sys=23893 NumGC=4 
Goroutines=7"
time="2025-04-30T11:02:49.349Z" level=info msg="Deadline monitor stopped"
time="2025-04-30T11:02:47.287Z" level=info msg="Starting Workflow Executor" version=v3.6.7
time="2025-04-30T11:02:47.293Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2025-04-30T11:02:47.293Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo podName=demo-scheduler-process-dir-888425247 templateName=process-dir ver
sion="&Version{Version:v3.6.7,BuildDate:2025-04-29T16:21:04Z,GitCommit:8d7dae690e152d19fb40f7affbb68fb783b32172,GitTag:v3.6.7,GitTreeState:clean,GoVersion:go1.24.2,Compiler:gc,Platform:linux/amd64,}"
time="2025-04-30T11:02:47.316Z" level=info msg="Starting deadline monitor"
time="2025-04-30T11:02:49.317Z" level=info msg="Main container completed" error="<nil>"
time="2025-04-30T11:02:49.317Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2025-04-30T11:02:49.317Z" level=info msg="No output parameters"
time="2025-04-30T11:02:49.317Z" level=info msg="No output artifacts"
time="2025-04-30T11:02:49.341Z" level=info msg="Alloc=7102 TotalAlloc=16267 Sys=28245 NumGC=5 Goroutines=7"
time="2025-04-30T11:02:49.348Z" level=info msg="Deadline monitor stopped"
time="2025-04-30T11:02:36.239Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2025-04-30T11:02:36.239Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=true namespace=argo podName=demo-scheduler-find-new-files-2520434530 templateName=find-new-fil
es version="&Version{Version:v3.6.7,BuildDate:2025-04-29T16:21:04Z,GitCommit:8d7dae690e152d19fb40f7affbb68fb783b32172,GitTag:v3.6.7,GitTreeState:clean,GoVersion:go1.24.2,Compiler:gc,Platform:linux/amd64,}"
time="2025-04-30T11:02:36.260Z" level=info msg="Starting deadline monitor"
time="2025-04-30T11:02:38.261Z" level=info msg="Main container completed" error="<nil>"
time="2025-04-30T11:02:38.261Z" level=info msg="Capturing script output"
time="2025-04-30T11:02:38.261Z" level=info msg="No output parameters"
time="2025-04-30T11:02:38.261Z" level=info msg="No output artifacts"
time="2025-04-30T11:02:38.284Z" level=info msg="Alloc=11988 TotalAlloc=16374 Sys=24405 NumGC=4 Goroutines=7"
time="2025-04-30T11:02:38.295Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2025-04-30T11:02:38.295Z" level=info msg="Deadline monitor stopped"
```

**Comment by cmdoret** [comment]
Just checked, it's failing too with `Workflow` + `workflowTemplateRef`.
I also get `withParam value could not be parsed as a JSON list: {{tasks.find-new-files.outputs.result}}: invalid character '{' looking for beginning of object key string`

<details>
<summary>manifest</summary

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demo-scheduler
spec:
  arguments:
  workflowTemplateRef:
    name: demo-parser
    clusterScoped: false
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: demo-parser
spec:
  entrypoint: process-new-files
  templates:
  - name: process-new-files
    dag:
      tasks:
      - name: find-new-files
        template: find-new-files

      - name: process-dir
        dependencies: [find-new-files]
        template: process-dir
        arguments:
          parameters:
          - name: catplus_dir
            value: "{{item}}"
        withParam: "{{tasks.find-new-files.outputs.result}}"

  - name: find-new-files
    script:
      image: alpine:latest
      command: [sh]
      source: |
        #!/bin/sh

        ROOT="/data/batch"

        # pretend to do work
        echo -n "[\"1.txt\",\"2.txt\"]"

  - name: process-dir
    inputs:
      parameters:
      - name: catplus_dir
    container:
      image: alpine:latest
      command: ["echo", "{{inputs.parameters.catplus_dir}}"] 

```

</details>
