### ISSUE TITLE
Workflows with steps involving empty withParam qualifiers don't seem to work properly

### ISSUE THREAD

**Issue by ozankabak** [argoproj/argo-workflows#1447]
**Is this a BUG REPORT or FEATURE REQUEST?**:
A bug report.

**What happened**:
Workflows with steps involving the `withParam` qualifier does not seem to generate outputs correctly when the `withParam` list is empty. The template denoting the output variable of the affected step (e.g. `{{steps.affected-step.outputs.parameters}}`) does not go through substitution and stays as is.

**What you expected to happen**:
The template denoting the output variable of the affected step should go through substitution and render to an empty list.

**How to reproduce it (as minimally and precisely as possible)**:
Create a two-step workflow where:
- The first step involves a `withParam` qualifier whose value is a workflow variable.
- The first step generates an output variable.
- The second step uses the first step's output variable.

Pass an empty iterable when instantiating the workflow. The second step will not get an empty list, but will get a raw (i.e. un-rendered) template.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:09Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-06-06T01:44:30Z"
  compiler: gc
  gitCommit: 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
  gitTreeState: clean
  gitVersion: v1.14.3
  goVersion: go1.12.5
  major: "1"
  minor: "14"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-06-06T01:36:19Z"
  compiler: gc
  gitCommit: 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
  gitTreeState: clean
  gitVersion: v1.14.3
  goVersion: go1.12.5
  major: "1"
  minor: "14"
  platform: linux/amd64
```
