### ISSUE TITLE
workflowMetadata doesn't work with markdown

### ISSUE THREAD

**Issue by ledniy** [argoproj/argo-workflows#14470]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

workflowMetadata doens't work with markdown, it just renders it as is
<img width="284" alt="Image" src="https://github.com/user-attachments/assets/13eb2a81-69b8-4be1-8876-a94156aee316" />

### Version(s)

v3.6.7

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
spec:
  entrypoint: main
  workflowMetadata:
    generateName: test-
    annotations:
      workflows.argoproj.io/description: |
        Test
        `tag`
  templates:
  - name: main
    container:
      image: alpine:latest
      command: [sh, -c]
      args:
        - |
          echo "Hello, world!"
```

### Logs from the workflow controller

```text
-
```

### Logs from in your workflow's wait container

```text
-
```
