### ISSUE TITLE
Template expression not resolved when source task is skipped

### ISSUE THREAD

**Issue by bmjhversteeg** [argoproj/argo-workflows#14498]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

When a task B references output (params or result) from a task A that was Skipped, the template expression (e.g. `{{ tasks.A.outputs.result }}`) is not resolved.

The problem seems to originate in [util/template/simple_template.go#L30-L35](https://github.com/argoproj/argo-workflows/blob/cb39b3ec953e6473ccd6257a94853a578a6208a6/util/template/simple_template.go#L30-L35) and [util/template/expression_template.go#L78-L82](https://github.com/argoproj/argo-workflows/blob/cb39b3ec953e6473ccd6257a94853a578a6208a6/util/template/expression_template.go#L78-L82) where we return the literal string when an error is encountered, which is the case because the task output we are looking does not exist.

When referencing output from a Skipped task, I'd expect the value to be either empty or null, but not the literal template string. 

### Output from reproducible workflow (see below)

<img width="515" alt="Image" src="https://github.com/user-attachments/assets/b2ff08f6-1aef-4a36-b80b-55132cec74f8" />

### Version(s)

v3.6.7

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: skipped-task-output-
spec:
  entrypoint: two-step
  templates:
    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.7
        command:
          - echo
          - "{{inputs.parameters.message}}"
    - name: two-step
      dag:
        tasks:
          - name: task-1
            template: echo
            arguments:
              parameters:
                - name: message
                  value: foo
            when: 'false'
          - name: task-2
            dependencies:
              - task-1
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "{{tasks.task-1.outputs.result}}"
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by bmjhversteeg** [comment]
> This should be a feature rather than a bug because if a replacement value cannot be found and `allowUnresolved` is true, the template string will be used, which is as expected.

While I agree that is not a bug in the true sense, because the behaviour is as described by the code, I do think this is usability problem, because in my opinion returning the exact template string is not very useful.

Maybe to give some more context why this is an issue for us (and I suspect also for others):
- Imagine task A and B both returning a value
- Task B runs conditionally 
- Task C merges the outputs of A and B into an array
- When task A and B are both run, there is no problem and the output of task C will be: `["A","B"]`.
- When task B is skipped, the output of task C will be `["A","{{tasks.task-B.outputs.result}}"]`, which would require downstream tasks to deal with filtering out template strings.


A simplified example of the above:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: skipped-task-output-
spec:
  entrypoint: merge
  templates:
    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.7
        command:
          - echo
          - "{{inputs.parameters.message}}"
    - name: merge-inputs
      inputs:
        parameters:
          - name: inputA
          - name: inputB
      container:
        image: alpine:3.7
        command:
          - echo
          - "{{=sprig.list(inputs.parameters.inputA,inputs.parameters.inputB)}}"
    - name: merge
      dag:
        tasks:
          - name: task-A
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "A"
          - name: task-B
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "B"
            when: 'false'
          - name: task-merge
            dependencies:
              - task-A
              - task-B
            template: merge-inputs
            arguments:
              parameters:
                - name: inputA
                  value: "{{tasks.task-A.outputs.result}}"
                - name: inputB
                  value: "{{tasks.task-B.outputs.result}}"
```

**Comment by ezk84** [comment]
I have another use case where addressing this would make things saner from a usability standpoint.

Imagine I have a global output parameter called `error`, which gets set if some steps fail, and then in a failure hook I want to do:

```yaml
template: slack-message
arguments:
  parameters:
    - name: message
      value: >-
        An error occurred: {{= workflow.outputs.parameters.error ?? 'Unknown error' }}
```

Currently, if the step that sets the global `error` parameter hasn't run before an error occurs, this message gets rendered as 
`An error occurred: {{= workflow.outputs.parameters.error ?? 'Unknown error' }}`. This I intuit is because `workflow.outputs.parameters.error` isn't resolvable when the hook runs, even though I am attempting to handle its non-existence in the expression itself. 

I've tried to handle this using Expr's `get` (also nested multiple times) to no avail. 

EDIT: I've tried again using Expr's Optional chaining `?.` operator and then it works: 

`{{= workflow?.outputs?.parameters?.error ?? 'Unknown error' }}` renders as `Unknown error`. 

@bmjhversteeg maybe try optional chaining and then `filter` for nil values in the array?

**Comment by bmjhversteeg** [comment]
> [@bmjhversteeg](https://github.com/bmjhversteeg) maybe try optional chaining and then `filter` for nil values in the array?

Good suggestion, I didn't even think about optional chaining! I almost thought this solved it, but for some reason it seems that if you use optional chaining, you never get a value out of the expression. Let's take my example above and apply optional chaining to both Task-A and Task-B.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: skipped-task-output-
spec:
  entrypoint: merge
  templates:
    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.7
        command:
          - echo
          - "{{inputs.parameters.message}}"
    - name: merge-inputs
      inputs:
        parameters:
          - name: inputA
          - name: inputB
      container:
        image: alpine:3.7
        command:
          - echo
          - "{{=sprig.list(inputs.parameters.inputA,inputs.parameters.inputB)}}"
    - name: merge
      dag:
        tasks:
          - name: task-A
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "A"
          - name: task-B
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "B"
            when: 'false'
          - name: task-merge
            dependencies:
              - task-A
              - task-B
            template: merge-inputs
            arguments:
              parameters:
                - name: inputA
                  value: "{{= tasks['task-A']?.outputs?.result ?? 'empty' }}"
                - name: inputB
                  value: "{{= tasks['task-B']?.outputs?.result ?? 'empty' }}"
```

![Image](https://github.com/user-attachments/assets/8892e6bc-4cae-41b2-b84f-eb719d4a22be)

It would appear the optional chaining is not respected at all. For Task-B we expect the word `empty` because it is skipped, but for Task-A we expect the input `A`, but it also reports `empty`.

@ezk84  In your example, did it ever work when `workflow.outputs.parameters.error` had a value? Or did it also *appear*  to work but in fact you would always get the coalesced value?

**Comment by ezk84** [comment]
Hmmm, I just tried it and indeed it doesn't work 😢. 

Regardless of whether `workflow.outputs.parameters.error` has a value `workflow?.outputs?.parameters?.error` is always nil. 

This seems to be the deeper issue at work here. It is arguably fair enough that the expression `{{ tasks.A.outputs.result }}` is not resolvable when task A didn't run (as per @chengjoey's comment) and its value gets set to the plain expression input value. The answer then would be to use optional chaining for an expression we know might not resolve.

But then it definitely is a bug for `{{= tasks?.A?.outputs?.result }}` to always be nil.

**Comment by bmjhversteeg** [comment]
> But then it definitely is a bug for `{{= tasks?.A?.outputs?.result }}` to always be nil.

Found a related issue from 2 years ago: https://github.com/argoproj/argo-workflows/issues/11549

**Comment by ezk84** [comment]
Here is a minimal workflow to illustrate this (running this on 3.6.7, which has Expr v1.17.0 AFAIK).

I would expect the output `message` variable to have the same value for the first two lines

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-workflow-errors-
spec:
  entrypoint: main
  hooks:
    failure:
      expression: workflow.status == "Failed" || workflow.status == "Error"
      template: globalise-message
      arguments:
        parameters:
          - name: message
            value: |
              Standard chaining: "{{= workflow.outputs.parameters.error ?? 'default' }}"
              Optional chaining: "{{= workflow?.outputs?.parameters?.error ?? 'default' }}"
              Does optional chaining even work?: "{{= 'A value' ?? 'default' }}"

  templates:
    - name: main
      steps:
        - - name: stepA
            template: just-error
            arguments:
              parameters:
                - name: id
                  value: "stepA"
    - name: just-error
      inputs:
        parameters:
          - name: id
      outputs:
        parameters:
          - name: error
            globalName: error
            valueFrom:
              path: /tmp/error
      script:
        image: busybox
        command: [sh]
        source: |
          echo "An error happened in {{ inputs.parameters.id }}" > /tmp/error
          exit 1
    - name: globalise-message
      inputs:
        parameters:
          - name: message
      outputs:
        parameters:
          - name: message
            globalName: message
            value: "{{ inputs.parameters.message }}"
      container:
        image: busybox
        command: [sh, -c, exit 0]
```

**Comment by bmjhversteeg** [comment]
Maybe it helps anybody who is still trying to deal with the issue above: instead of trying to use optional chaining, it does work to check 'outputs' presence in the tasks object. Doesn't look nice, but this works:


```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: skipped-task-output-
spec:
  entrypoint: merge
  templates:
    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.7
        command:
          - echo
          - "{{inputs.parameters.message}}"
    - name: merge-inputs
      inputs:
        parameters:
          - name: inputA
          - name: inputB
      container:
        image: alpine:3.7
        command:
          - echo
          - "{{=sprig.list(inputs.parameters.inputA,inputs.parameters.inputB)}}"
    - name: merge
      dag:
        tasks:
          - name: task-A
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "A"
          - name: task-B
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "B"
            when: 'false'
          - name: task-merge
            dependencies:
              - task-A
              - task-B
            template: merge-inputs
            arguments:
              parameters:
                - name: inputA
                  value: "{{= 'outputs' in tasks['task-A'] ? tasks['task-A'].outputs.result : 'empty' }}"
                - name: inputB
                  value: "{{= 'outputs' in tasks['task-B'] ? tasks['task-B'].outputs.result : 'empty' }}"
```

<img width="1307" height="432" alt="Image" src="https://github.com/user-attachments/assets/06e73bab-dd7d-4d4f-8eb8-a54fbcc521d5" />
