### ISSUE TITLE
Zombie daemon container pods after workflow finished execution

### ISSUE THREAD

**Issue by MenD32** [argoproj/argo-workflows#14544]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Workflows with daemon containers that have processes that catch SIGTERM signals will not be terminated by the argo workflows controller when the workflow finishes execution.

it appears that the controller tries to send a SIGTERM signal to the process, without checking that it actually was stopped (assuming that if a 0 error code is returned, the process died). this behavior will cause zombie pods to keep running on the Kubernetes cluster and this will raise any kind of error. so users will not know that argo workflows fails to clean up.

### Version(s)

v3.6.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
# llm-d-inference-sim is an example for a container that catches SIGTERM signals, as an example 

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: minimal-daemon-
spec:
  serviceAccountName: operate-workflow-sa
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: model-daemon
            template: model-daemon
        - - name: wait-10s
            template: wait-10s
    - name: model-daemon
      daemon: true
      container:
        image: ghcr.io/llm-d/llm-d-inference-sim:v0.1.0
        command: ["/bin/bash", "-c"]
        args:
          - |
            /app/llm-d-inference-sim --model Qwen/Qwen2.5-0.5B-Instruct
    - name: wait-10s
      container:
        image: ubuntu:22.04
        command: ["sh", "-c"]
        args: ["sleep 10"]
```

### Logs from the workflow controller

```text
unnecessary
```

### Logs from in your workflow's wait container

```text
unnecessary
```
