### ISSUE TITLE
CronWorkflow Title and Description markdown annotations are not working

### ISSUE THREAD

**Issue by iAlexMlops** [argoproj/argo-workflows#14553]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I found issue https://github.com/argoproj/argo-workflows/pull/12674 which was closed but I try to check description in v3.6.6-v3.6.10 version and I can't to get some visual effects in UI for CronWorkflow. But it works for simple Workflow

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/d92afd2f-06af-4996-8346-059fbe31d72d" />

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/08eeb576-cd2a-4c2a-a0db-69a6c0ec6131" />

### Version(s)

v3.6.6,v3.6.7,v3.6.8,v3.6.10,:latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
metadata:
  name: lovely-dragon
  namespace: argo
  labels:
    example: "true"
  annotations:
    workflows.argoproj.io/title: '**Test Title**'
    workflows.argoproj.io/description: |
      `Test`
spec:
  workflowMetadata:
    labels:
      example: "true"
  schedules:
    - "* * * * *"
  workflowSpec:
    entrypoint: argosay
    arguments:
      parameters:
        - name: message
          value: hello argo
    templates:
      - name: argosay
        inputs:
          parameters:
            - name: message
              value: "{{workflow.parameters.message}}"
        container:
          name: main
          image: argoproj/argosay:v2
          command:
            - /argosay
          args:
            - echo
            - "{{inputs.parameters.message}}"
    ttlStrategy:
      secondsAfterCompletion: 300
    podGC:
      strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
time="2025-06-06T13:42:10.079Z" level=info msg="Alloc=7109 TotalAlloc=34088 Sys=29269 NumGC=11 Goroutines=180"
time="2025-06-06T13:43:00.000Z" level=info msg="Running lovely-dragon" namespace=argo workflow=lovely-dragon
time="2025-06-06T13:43:00.001Z" level=info msg="lovely-dragon is suspended, skipping execution" namespace=argo workflow=lovely-dragon
time="2025-06-06T13:43:07.588Z" level=info msg="Processing argo/lovely-dragon" cronWorkflow=argo/lovely-dragon
time="2025-06-06T13:43:07.588Z" level=info msg="Deleting 'argo/lovely-dragon'" cronWorkflow=argo/lovely-dragon
time="2025-06-06T13:43:33.535Z" level=info msg="Processing argo/lovely-dragon" cronWorkflow=argo/lovely-dragon
time="2025-06-06T13:43:33.535Z" level=info msg="CronWorkflow argo/lovely-dragon added" cronWorkflow=argo/lovely-dragon
time="2025-06-06T13:43:35.423Z" level=info msg="Processing argo/lovely-dragon" cronWorkflow=argo/lovely-dragon
time="2025-06-06T13:43:35.424Z" level=info msg="CronWorkflow argo/lovely-dragon added" cronWorkflow=argo/lovely-dragon
time="2025-06-06T13:44:00.000Z" level=info msg="Running lovely-dragon" namespace=argo workflow=lovely-dragon
time="2025-06-06T13:44:00.000Z" level=info msg="lovely-dragon is suspended, skipping execution" namespace=argo workflow=lovely-dragon
time="2025-06-06T13:44:00.006Z" level=info msg="Processing argo/lovely-dragon" cronWorkflow=argo/lovely-dragon
time="2025-06-06T13:44:00.006Z" level=info msg="CronWorkflow argo/lovely-dragon added" cronWorkflow=argo/lovely-dragon
```

### Logs from in your workflow's wait container

```text
-
```
