### ISSUE TITLE
Create semaphore key if it doesn't exist in Configmap

### ISSUE THREAD

**Issue by aaronmell** [argoproj/argo-workflows#14570]
# Summary

It would be nice to have functionality that would allow for a semaphore to automatically generate its key if it does not exist in the configmap.

I could see adding a optional property such as createIfMissing that would create the key automatically. Additionally maybe an annotation on the CM could be used to set the default max number of parallel executions.

```
synchronization:
    semaphore:
      configMapKeyRef:
        name: environments
        key: "{{workflow.parameters.environment_name}}"
        createIfMissing: true
```

## Use Cases

When your business scales horizontally instead of vertically you manage many different cookie-cutter envrionments with ArgoWF. However, its painful to automate updating the configmap with a new key every time a new environment is added.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Joibel** [comment]
I don't think we should do this.

A full Create, Delete and Update as an API would be useful, but this only allows Create. Without Update or Delete capabilities it's likely to proliferate a bunch of unused ConfigMaps to your cluster.

I'd suggest some templates and using ArgoCD to manage this, or some other self-serve mechanism in the mean time.

**Comment by aaronmell** [comment]
@Joibel I'm not asking for it to create a new Configmap. Just add a key automatically to the configmap if the key doesn't already exist (Maybe thats what your referring to with the comment about missing CRUD functionality).

I'm not sure of any solution I could use to manage this short of writing my own automation to add a key every time we add a new environment.

**Comment by tczhao** [comment]
How about using resource template as part of the step/dag, this is much more flexible
https://argo-workflows.readthedocs.io/en/stable/walk-through/kubernetes-resources/

**Comment by aaronmell** [comment]
> How about using resource template as part of the step/dag, this is much more flexible https://argo-workflows.readthedocs.io/en/stable/walk-through/kubernetes-resources/

So doing a merge operation like this could work I think
```
  templates:
  - name: update-semaphore
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: v1
        kind: ConfigMap
        spec:
          data: 
            {{input.parameters.key}}: "1"
```
The only downside to this solution is that you would have to have a separate workflow that managed the configmap if the semaphore was at the workflow level. 

That might be an acceptable tradeoff though.
