### ISSUE TITLE
WorkflowTemplate generateName not used

### ISSUE THREAD

**Issue by antoinetran** [argoproj/argo-workflows#14590]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

When submitting a workflow thanks to a workflowtemplate in Argo GUI, the name of the workflow does not rely on `generateName`. See example below.
Expected result: the workflow name should match the prefix set by `generateName`.

### Version(s)

v3.6.7

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate                  # new type of k8s spec
metadata:
  name: hello-world-template
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: hello-world       # invoke the hello-world template
  templates:
    - name: hello-world         # name of the template
      container:
        image: busybox
        command: [ echo ]
        args: [ "hello world" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
```

### Logs from the workflow controller

```text
not relevant
```

### Logs from in your workflow's wait container

```text
not relevant
```

**Comment by antoinetran** [comment]
The `generateName` is only used with Workflow kind, eg:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: hello-world       # invoke the hello-world template
  templates:
    - name: hello-world         # name of the template
      container:
        image: busybox
        command: [ echo ]
        args: [ "hello world" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
```

**Comment by jmabuin** [comment]
Hi @antoinetran 

Is maybe the problem **name** and **generateName** are being used at the same time?

According to the docs here: https://github.com/argoproj/argo-workflows/blob/main/api/jsonschema/schema.json#L11519

`GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided`

**Comment by antoinetran** [comment]
> Hi [@antoinetran](https://github.com/antoinetran)
> 
> Is maybe the problem **name** and **generateName** are being used at the same time?
> 
> According to the docs here: https://github.com/argoproj/argo-workflows/blob/main/api/jsonschema/schema.json#L11519
> 
> `GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided`

It seems this is the rule!

But we cannot put a WorkflowTemplate without setting its name. So the generateName field is a valid field of WorkflowTemplate, but it is then never used. Instead, it is only used in Workflow, because we can submit it without name field.

On the other hand, the name field of WorkflowTemplate is not used as a name in Workflow. Instead, Argo uses it as a generateName.
E.g.:
```
kind: Workflow
metadata:
  name: hello-world
```
=> creates a workflow with "hello-world".

```
kind: WorkflowTemplate
metadata:
  name: hello-world
```
=> creates a workflow with "hello-world-XXXXX", as if it was in fact
```
kind: WorkflowTemplate
metadata:
  generateName: hello-world-
```

So because the name in WorkflowTemplate has already a special treatment (it is not reused exactly as a Workflow's name), maybe we can make this rule: a WorkflowTemplate that has a generateName will honor this generateName instead of Argo doing its own generateName?

But anyway, this is not really important. We named our WorkflowTemplate with suffix like "hello-world-template" and expect the Workflow to be named without "-template". Maybe we can just remove the "-template" in our WorkflowTemplate.

**Comment by rockc2020** [comment]
I'm also looking forward to this feature, since we are running workflows against many clusters with a single workflowtemplate. From the list of workflows in the argo workflows UI, it's hard to distinguish among those workflows. (workflow name is `<workflow-template-name>-<hash>`.)
It'd much easier for us if the cluster name, as a parameter of the workflow, can be part of the workflow's name, like this:
```yaml
metadata:
  name: cluster-upgrade
  generateName: cluster-upgrade-{{workflow.parameters.cluster-name}}-
```
