### ISSUE TITLE
`templateRef` parameter validation not working

### ISSUE THREAD

**Issue by jaseemabid** [argoproj/argo-workflows#14603]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

**Expected Behaviour:**

`argo lint` should fail when a WorkflowTemplate calls another template via `templateRef` with incorrect parameter names that don't match the referenced template's expected parameters.

**Actual Behaviour:**

`argo lint --offline` passes validation even when wrong parameter names are provided to `templateRef`.

**Steps to Reproduce:**
 
1. Run 👇🏼 template as `argo lint --offline template.yaml`
3. Observe that it reports "✔ no linting errors found!"

**Expected Result:**

Should fail with parameter validation error since `wrong-param-name` doesn't match the expected `message` parameter.

**Environment:**

- Argo Workflows version: All of them.

### Version(s)

v3.6.10, 459c19db6e9dd86dd757c21644404cb784863fae

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template
spec:
  templates:
  - name: hello-world
    inputs:
      parameters:
      - name: message
        value: "Hello World"
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.message}}"]

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: caller-template
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: call-hello
        templateRef:
          name: hello-world-template
          template: hello-world
        arguments:
          parameters:
          - name: wrong-param-name  # This should cause validation to fail
            value: "This parameter doesn't exist in the referenced template"
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```
