### ISSUE TITLE
argo submit --from workflowtemplate used outdated template spec after template was deleted and recreated

### ISSUE THREAD

**Issue by kevinlacaille** [argoproj/argo-workflows#14607]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I had a `WorkflowTemplate` named `create-point-cloud-stac` in a namespace with large resource requests (`cpu: "8"`, `memory: "16Gi"`). I deleted the template using `kubectl delete workflowtemplate create-point-cloud-stac -n <namespace>`, then re-applied it locally with reduced resource values (`cpu: "2000m"`, `memory: "8Gi"`).

However, when I submitted a new workflow using:

```bash
argo submit --from workflowtemplate/create-point-cloud-stac -n <namespace>
```

the resulting pod still used the *old* values (`cpu: 8`, `memory: 16Gi`), making it unschedulable.

I expected that since the template was deleted and re-applied, the new submission would use the updated resource values. It appears that Argo was using a cached or stale version of the deleted template even though the newly applied template had different values.

The correct version of the pod spec only appeared after I force-deleted the previously submitted (but stuck) workflow and re-submitted again.

### Version(s)

argo cli v3.5.10, argo controller quay.io/argoproj/workflow-controller:v3.5.10, kubernetes v1.29.13-eks-5d632ec

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-point-cloud-stac
  namespace: <namespace>
spec:
  entrypoint: create-point-cloud-stac
  templates:
    - name: create-point-cloud-stac
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo Hello from Argo"]
        resources:
          requests:
            cpu: "2000m"
            memory: "8Gi"
          limits:
            cpu: "4000m"
            memory: "16Gi"


Steps to reproduce:

1. Create a `WorkflowTemplate` with large resource requests (e.g., `cpu: 8`, `memory: 16Gi`)
2. Delete it: `kubectl delete workflowtemplate create-point-cloud-stac -n <namespace>`
3. Recreate it with reduced requests (as above)
4. Submit: `argo submit --from workflowtemplate/create-point-cloud-stac -n <namespace>`
5. Observe that the pod still uses the original resource requests
```

### Logs from the workflow controller

```text
No relevant logs were found in the workflow controller for workflow `create-point-cloud-stac-grq7w`.

Command used:
kubectl logs -n <controller-namespace> deploy/<workflow-controller-name> | grep create-point-cloud-stac-grq7w

Tested in multiple namespaces where the workflow controller is deployed, but the controller produced no output for this workflow.
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

No logs available. The workflow pod was never scheduled due to an unsatisfiable nodeSelector and resource requests. As a result, no wait container was started and no pod was created.
```
