### ISSUE TITLE
Even with continueOn for error continuation, there’s an issue where ⁠outputs.parameters cannot be correctly retrieved.

### ISSUE THREAD

**Issue by garireo2549** [argoproj/argo-workflows#14602]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I'm experiencing an issue with Workflow where I cannot retrieve the output parameter value from a step that has the continueOn directive set to continue despite failures.

- output
  - `{{steps.output-step.outputs.parameters.out}}`

<img width="1910" alt="Image" src="https://github.com/user-attachments/assets/bf033ba5-e94e-4ac6-b438-df45618acba2" />

If the workflow ends normally, you will get the output correctly.
Change `command: ["sh", "-c", "exit 1"]` to `command: ["sh", "-c", "echo result"].

<img width="1910" alt="Image" src="https://github.com/user-attachments/assets/9e20589d-0fc7-47c5-90f5-010e1fd62dbf" />

If the `template` that caused the error is not a step, you can get the `output` correctly.

<img width="1910" alt="Image" src="https://github.com/user-attachments/assets/35271eb7-6f03-4519-a7d7-0bd7c2e6d432" />

### Version(s)

:latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-pod-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
      - - name: output-step
          template: output-step
          continueOn:
            failed: true
            error: true

      - - name: use-output
          template: use-output
          arguments:
            parameters:
              - name: result
                value: "{{steps.output-step.outputs.parameters.out}}"

  - name: output-step
    outputs:
      parameters:
        - name: out
          valueFrom:
            parameter: "{{steps.output.outputs.parameters.result}}"
    steps:
      - - name: output
          template: output

  - name: output
    outputs:
      parameters:
        - name: result
          valueFrom:
            path: result
            default: result
    container:
      image: alpine
      command: ["sh", "-c", "exit 1"]

  - name: use-output
    inputs:
      parameters:
        - name: result
    container:
      image: alpine
      command: ["sh", "-c", "echo {{inputs.parameters.result}}"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep test-pod-nwhks

no logs.
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=test-pod-nwhks,workflow.argoproj.io/phase!=Succeeded

time="2025-06-25T04:56:21.933Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: test-pod-nwhks/test-pod-nwhks-output-2390463508/main.log"
time="2025-06-25T04:56:21.933Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2025-06-25T04:56:21.933Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=test-pod-nwhks/test-pod-nwhks-output-2390463508/main.log path=/tmp/argo/outputs/logs/main.log
time="2025-06-25T04:56:21.945Z" level=info msg="Save artifact" artifactName=main-logs duration=11.402417ms error="<nil>" key=test-pod-nwhks/test-pod-nwhks-output-2390463508/main.log
time="2025-06-25T04:56:21.945Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2025-06-25T04:56:21.945Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2025-06-25T04:56:21.952Z" level=debug msg="Create workflowtaskresults 409"
time="2025-06-25T04:56:21.960Z" level=debug msg="Patch workflowtaskresults 200"
time="2025-06-25T04:56:21.960Z" level=info msg="Alloc=7310 TotalAlloc=17153 Sys=23637 NumGC=5 Goroutines=10"
time="2025-06-25T04:56:21.968Z" level=debug msg="Patch workflowtaskresults 200"
time="2025-06-25T04:56:28.958Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2025-06-25T04:56:28.958Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=test-pod-nwhks/test-pod-nwhks-use-output-2568274325/main.log path=/tmp/argo/outputs/logs/main.log
time="2025-06-25T04:56:28.968Z" level=info msg="Save artifact" artifactName=main-logs duration=10.039625ms error="<nil>" key=test-pod-nwhks/test-pod-nwhks-use-output-2568274325/main.log
time="2025-06-25T04:56:28.968Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2025-06-25T04:56:28.968Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2025-06-25T04:56:28.973Z" level=debug msg="Create workflowtaskresults 409"
time="2025-06-25T04:56:28.976Z" level=debug msg="Patch workflowtaskresults 200"
time="2025-06-25T04:56:28.977Z" level=info msg="Alloc=11913 TotalAlloc=17120 Sys=23125 NumGC=4 Goroutines=10"
time="2025-06-25T04:56:28.986Z" level=debug msg="Patch workflowtaskresults 200"
time="2025-06-25T04:56:28.986Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
```

**Comment by jswxstw** [comment]
I think this is by design, `output` step fails so its outputs will not be resolved in `output-step`.
Therefore, you should set `continueOn` to `output` step.
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-pod-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
      - - name: output-step
          template: output-step

      - - name: use-output
          template: use-output
          arguments:
            parameters:
              - name: result
                value: "{{steps.output-step.outputs.parameters.out}}"

  - name: output-step
    outputs:
      parameters:
        - name: out
          valueFrom:
            parameter: "{{steps.output.outputs.parameters.result}}"
    steps:
      - - name: output
          template: output
          continueOn:
            failed: true
            error: true

  - name: output
    outputs:
      parameters:
        - name: result
          valueFrom:
            path: result
            default: result
    container:
      image: alpine
      command: ["sh", "-c", "exit 1"]

  - name: use-output
    inputs:
      parameters:
        - name: result
    container:
      image: alpine
      command: ["sh", "-c", "echo {{inputs.parameters.result}}"]
```
