### ISSUE TITLE
argoworkflow+dex+gitlab  SSO RBAC Namespace Delegation not taking effect

### ISSUE THREAD

**Issue by yunwei201331** [argoproj/argo-workflows#14610]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

argoworkflow+dex+gitlab  SSO RBAC Namespace Delegation not taking effect 
 

### Version(s)

latest

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
The configurations for ServiceAccount (SA) and RoleBinding are as follows
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ali
  namespace: ali
  annotations:
    workflows.argoproj.io/rbac-rule: "'ali' in groups"        
    workflows.argoproj.io/rbac-rule-precedence: "10" 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ali-secrets-full-access
  namespace: ali
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ali-secrets-full-access-binding
  namespace: ali
subjects:
- kind: ServiceAccount
  name: ali
  namespace: ali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ali-secrets-full-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ali-namespace-full-access
  namespace: ali
rules:
- apiGroups: ["", "apps", "batch", "argoproj.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ali-namespace-full-access-binding
  namespace: ali
subjects:
- kind: ServiceAccount
  name: ali
  namespace: ali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ali-namespace-full-access

kubectl create secret generic ali.service-account-token --from-literal=token=$(kubectl create token ali -n ali --duration=2400h) -n ali


I have already added environment variables SSO_DELEGATE_RBAC_TO_NAMESPACE to the argo-workflows-server Deployment
    env:
    - name: SSO_DELEGATE_RBAC_TO_NAMESPACE
      value: "true" 

The errors are as follows.
level=debug msg="handing oauth2 callback Bearer v2:eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIiwiemlwIjoiREVGIn0.B3hX-p7QWrwxEUOpjabINr9MmT6uaSEnKQ9ffpChwoXrOt7USdCQny3wZOPPmxJlztsM_LQjp4mcWK0gDqwIkUnVJoCfquY2HWKpVcAzqIvUdKyQ2n0oB6yt39Fuhvc_LYxq0qKlUapuGpSZzY84VeHt1dslKi2yS0i-AcBB6AjprqS4LAxyJ1_qFc3KZ7tFGuHkk6NfCRgKxSfJx55TGkGXWCg-B5WVqGBBdQDf0arUFWgEVJvo7drrANgR39pOXJVwyKwdSYvP7ocVETw_3-zuppuAhc1kdipQvibbQYfCHwYymgsCoV9upUWZNfl1EdY3F0OEB-BEBUiMrhsVFw.6ikFw7ukGwUOiza1.5Roz-ThYzP-RCngOyN9PrGl0_RIVyJUtdFhD0qh60N3LujdXcAD1prz5ejfElICug7DjuHRitBMB8wsf05Qt1cFmtWeobHRs79exgMHMx7ABnXTEFhQ9Z8H1gBi_7LaXtmqkB_X6vmQBs01iO1tL33Wl6Oufr_HYMU8b8bfJzg.5OHok0-J3-rTG0XlvyhDWQ"
level=info duration=19.472151ms method=GET path=/oauth2/callback size=50 status=302
level=info duration="58.369µs" method=GET path=index.html size=487 status=0
level=error msg="failed to perform RBAC authorization" error="no service account rule matches"
level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = not allowed" grpc.code=PermissionDenied grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2025-06-27T08:28:53Z" grpc.time_ms=2.016 span.kind=server system=grpc
level=info duration=2.573698ms method=GET path=/api/v1/info size=34 status=403
level=error msg="failed to perform RBAC authorization" error="no service account rule matches"
level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = not allowed" grpc.code=PermissionDenied grpc.method=GetUserInfo grpc.service=info.InfoService grpc.start_time="2025-06-27T08:28:53Z" grpc.time_ms=1.342 span.kind=server system=grpc
```

### Logs from the workflow controller

```text
time="2025-06-27T16:18:22.178Z" level=info msg="DB migration is disabled"
time="2025-06-27T16:18:22.178Z" level=info msg="Generating Self Signed TLS Certificates for Telemetry Servers"
time="2025-06-27T16:18:22.178Z" level=info msg="Starting Workflow Controller" defaultRequeueTime=10s version=v3.6.10
time="2025-06-27T16:18:22.178Z" level=info msg="Current Worker Numbers" cronWorkflowWorkers=8 podCleanup=4 workflowArchive=8 workflowTtlWorkers=4 workflowWorkers=32
time="2025-06-27T16:18:22.179Z" level=info msg="Watching task results" labelSelector="!workflows.argoproj.io/controller-instanceid,workflows.argoproj.io/workflow"
time="2025-06-27T16:18:22.179Z" level=info msg=Plugins executorPlugins=false
time="2025-06-27T16:18:22.179Z" level=info msg="Starting prometheus metrics server at localhost:9090/metrics"
time="2025-06-27T16:18:22.188Z" level=info msg="Manager initialized successfully"
time="2025-06-27T16:18:22.221Z" level=info msg="Received Workflow Controller config map argo/argo-workflows-workflow-controller-configmap update"
time="2025-06-27T16:18:22.227Z" level=info msg="Configuration:\nartifactRepository: {}\ninitialDelay: 0s\nmetricsConfig: {}\nnodeEvents: {}\npodSpecLogStrategy: {}\nsso:\n  clientId:\n    key: client-id\n    name: argo-workflows-sso\n  clientSecret:\n    key: client-secret\n    name: argo-workflows-sso\n  insecureSkipVerify: true\n  issuer: http://192.168.72.10:30400\n  rbac:\n    enabled: true\n  redirectUrl: http://192.168.72.10:30651/oauth2/callback\n  scopes:\n  - openid\n  - profile\n  - email\n  - groups\n  sessionExpiry: 0s\n  userInfoPath: /userinfo\ntelemetryConfig: {}\nworkflowEvents: {}\n"
time="2025-06-27T16:18:22.227Z" level=info msg="Persistence configuration disabled"
time="2025-06-27T16:18:22.227Z" level=info executorImage="quay.io/argoproj/argoexec:v3.6.10" executorImagePullPolicy= managedNamespace=
time="2025-06-27T16:18:22.401Z" level=info msg="Performing periodic GC" periodicity=5m0s
time="2025-06-27T16:18:22.401Z" level=info msg="Persistence disabled - so archived workflow GC disabled - you must restart the controller if you enable this"
time="2025-06-27T16:18:22.401Z" level=info msg="Starting workflow garbage collector controller (retentionWorkers 4)"
time="2025-06-27T16:18:22.401Z" level=info msg="Started workflow garbage collection"
time="2025-06-27T16:18:22.401Z" level=info msg="Starting CronWorkflow controller"
W0627 16:18:22.401991       1 shared_informer.go:463] The sharedIndexInformer has started, run more than once is not allowed
time="2025-06-27T16:23:22.161Z" level=info msg="Alloc=5615 TotalAlloc=10772 Sys=18261 NumGC=6 Goroutines=177"
time="2025-06-27T16:28:22.160Z" level=info msg="Alloc=6379 TotalAlloc=11761 Sys=18261 NumGC=8 Goroutines=177"
time="2025-06-27T16:33:22.161Z" level=info msg="Alloc=6268 TotalAlloc=12664 Sys=18261 NumGC=11 Goroutines=177"
time="2025-06-27T16:38:22.161Z" level=info msg="Alloc=5693 TotalAlloc=12960 Sys=18261 NumGC=13 Goroutines=177"
time="2025-06-27T16:43:22.161Z" level=info msg="Alloc=5637 TotalAlloc=13900 Sys=18261 NumGC=16 Goroutines=177"
time="2025-06-27T16:48:22.161Z" level=info msg="Alloc=5696 TotalAlloc=14823 Sys=18261 NumGC=18 Goroutines=177"
time="2025-06-27T16:53:22.161Z" level=info msg="Alloc=6378 TotalAlloc=15770 Sys=18261 NumGC=21 Goroutines=177"
time="2025-06-27T16:58:22.160Z" level=info msg="Alloc=5700 TotalAlloc=15984 Sys=18261 NumGC=23 Goroutines=177"
time="2025-06-27T17:03:22.161Z" level=info msg="Alloc=5721 TotalAlloc=16960 Sys=18261 NumGC=26 Goroutines=177"
dex is working,as follows
[root@master ~]# kubectl logs -f dex-5f8646c986-rpvgx -ndex
time="2025-06-27T16:18:00Z" level=info msg="Dex Version: v2.35.3-dirty, Go Version: go1.19.2, Go OS/ARCH: linux amd64"
time="2025-06-27T16:18:00Z" level=info msg="config using log level: debug"
time="2025-06-27T16:18:00Z" level=info msg="config issuer: http://192.168.72.10:30400"
time="2025-06-27T16:18:00Z" level=info msg="kubernetes client apiVersion = dex.coreos.com/v1"
time="2025-06-27T16:18:00Z" level=info msg="creating custom Kubernetes resources"
time="2025-06-27T16:18:00Z" level=info msg="checking if custom resource authcodes.dex.coreos.com has already been created..."
time="2025-06-27T16:18:00Z" level=info msg="The custom resource authcodes.dex.coreos.com already available, skipping create"
time="2025-06-27T16:18:00Z" level=info msg="checking if custom resource authrequests.dex.coreos.com has already been created..."
time="2025-06-27T16:18:00Z" level=info msg="The custom resource authrequests.dex.coreos.com already available, skipping create"
time="2025-06-27T16:18:00Z" level=info msg="checking if custom resource oauth2clients.dex.coreos.com has already been created..."
time="2025-06-27T16:18:00Z" level=info msg="The custom resource oauth2clients.dex.coreos.com already available, skipping create"
time="2025-06-27T16:18:00Z" level=info msg="checking if custom resource signingkeies.dex.coreos.com has already been created..."
time="2025-06-27T16:18:00Z" level=info msg="The custom resource signingkeies.dex.coreos.com already available, skipping create"
time="2025-06-27T16:18:00Z" level=info msg="checking if custom resource refreshtokens.dex.coreos.com has already been created..."
time="2025-06-27T16:18:00Z" level=info msg="The custom resource refreshtokens.dex.coreos.com already available, skipping create"
time="2025-06-27T16:18:00Z" level=info msg="checking if custom resource passwords.dex.coreos.com has already been created..."
time="2025-06-27T16:18:00Z" level=info msg="The custom resource passwords.dex.coreos.com already available, skipping create"
time="2025-06-27T16:18:00Z" level=info msg="checking if custom resource offlinesessionses.dex.coreos.com has already been created..."
time="2025-06-27T16:18:00Z" level=info msg="The custom resource offlinesessionses.dex.coreos.com already available, skipping create"
time="2025-06-27T16:18:00Z" level=info msg="checking if custom resource connectors.dex.coreos.com has already been created..."
time="2025-06-27T16:18:00Z" level=info msg="The custom resource connectors.dex.coreos.com already available, skipping create"
time="2025-06-27T16:18:00Z" level=info msg="checking if custom resource devicerequests.dex.coreos.com has already been created..."
time="2025-06-27T16:18:00Z" level=info msg="The custom resource devicerequests.dex.coreos.com already available, skipping create"
time="2025-06-27T16:18:00Z" level=info msg="checking if custom resource devicetokens.dex.coreos.com has already been created..."
time="2025-06-27T16:18:00Z" level=info msg="The custom resource devicetokens.dex.coreos.com already available, skipping create"
time="2025-06-27T16:18:00Z" level=info msg="config storage: kubernetes"
time="2025-06-27T16:18:00Z" level=info msg="config static client: argo-workflows"
time="2025-06-27T16:18:00Z" level=info msg="config connector: gitlab"
time="2025-06-27T16:18:00Z" level=info msg="config skipping approval screen"
time="2025-06-27T16:18:00Z" level=info msg="config refresh tokens rotation enabled: true"
time="2025-06-27T16:18:00Z" level=info msg="keys expired, rotating"
time="2025-06-27T16:18:00Z" level=info msg="keys rotated, next rotation: 2025-06-27 22:18:00.724826255 +0000 UTC"
time="2025-06-27T16:18:00Z" level=info msg="listening (http) on 0.0.0.0:5556"
time="2025-06-27T16:28:53Z" level=info msg="login successful: connector \"gitlab\", username=\"aliuser\", preferred_username=\"aliuser\", email=\"ali@qq.com\", groups=[\"ali\"]"
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
