### ISSUE TITLE
argoexec does not resolve script outputs from other tasks / steps

### ISSUE THREAD

**Issue by ptemmer** [argoproj/argo-workflows#1628]
**BUG REPORT**:

**What happened**:
```yaml
  templates:
  - name: sensorAction
    dag:
      tasks:
      - name: sanitize-branch-name
        template: sanitize
        arguments:
          parameters:
          - name: branch
            value: "{{workflow.parameters.branch}}"
      - name: open
        dependencies: [sanitize-branch-name]
        arguments:
          parameters:
          - name: branch
            value: "{{tasks.sanitize-branch-name.outputs.result}}"
        template: open
  - name: sanitize
    inputs:
      parameters:
      - name: branch
    script:
      image: debian
      command: [bash]
      source: |
        echo "{{inputs.parameters.branch}}" | sed -r 's,/,-,g'
  - name: open
    inputs:
      parameters:
      - name: branch
    script:
      image: debian
      command: [bash]
      source: |
        echo {{inputs.parameters.branch}}
```
Instead of inserting the value of `{{tasks.sanitize-branch-name.outputs.result}}`, it is passed literally as "{{tasks.sanitize-branch-name.outputs.result}}" to the open template.
In the sanitize-branch-name step, the argoexec wait container shows:
```
level=info msg="No Script output reference in workflow. Capturing script output ignored"
```
When explicitly using `argoproj/argoexec:v.2.3.0` it works as expected.

**What you expected to happen**:
`{{tasks.sanitize-branch-name.outputs.result}}` to be substituted by the sanitize-branch-name output

**How to reproduce it (as minimally and precisely as possible)**:
Use `argoproj/argoexec:latest`

**Comment by simster7** [comment]
@ptemmer I have not been able to reproduce this issue. Here is my attempt:

```
$ ./dist/argo submit - <<EOF
> apiVersion: argoproj.io/v1alpha1
> kind: Workflow
> metadata:
>   name: a-workflow-test
> spec:
>   entrypoint: sensorAction
>   templates:
>   - name: sensorAction
>     dag:
>       tasks:
>       - name: sanitize-branch-name
>         template: sanitize
>         arguments:
>           parameters:
>           - name: branch
>             value: "branch/name"
>       - name: open
>         dependencies: [sanitize-branch-name]
>         arguments:
>           parameters:
>           - name: branch
>             value: "{{tasks.sanitize-branch-name.outputs.result}}"
>         template: open
>   - name: sanitize
>     inputs:
>       parameters:
>       - name: branch
>     script:
>       image: debian
>       command: [bash]
>       source: |
>         echo "{{inputs.parameters.branch}}" | sed -r 's,/,-,g'
>   - name: open
>     inputs:
>       parameters:
>       - name: branch
>     script:
>       image: debian
>       command: [bash]
>       source: |
>         echo {{inputs.parameters.branch}}
> EOF
Name:                a-workflow-test
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Thu Oct 17 09:54:54 -0700 (now)
```
Taking a look at the results it looks like it worked as expected:
```
$ ./dist/argo watch a-workflow-test
Name:                a-workflow-test
Namespace:           argo
ServiceAccount:      default
Status:              Succeeded
Created:             Thu Oct 17 09:54:54 -0700 (35 seconds ago)
Started:             Thu Oct 17 09:54:54 -0700 (35 seconds ago)
Finished:            Thu Oct 17 09:55:11 -0700 (18 seconds ago)
Duration:            17 seconds

STEP                                  PODNAME                     DURATION  MESSAGE
 ✔ a-workflow-test (sensorAction)
 ├-✔ sanitize-branch-name (sanitize)  a-workflow-test-3499661895  7s
 └-✔ open (open)                      a-workflow-test-1658852141  8s
$ kubectl logs a-workflow-test-1658852141 -c main
branch-name
```

And I'm using the latest `argoexec` and `workflow-controller`:
```
Containers:
  workflow-controller:
    Container ID:  docker://697f7232021bf5ede2a6248a8852248721627155825b12dab7d0c46095da64be
    Image:         argoproj/workflow-controller:latest
    Image ID:      docker-pullable://argoproj/workflow-controller@sha256:ba0b0d0a0204a69f04086964594ad43ebf53e7e224f20f06f1a2032068c2aea8
    Port:          <none>
    Host Port:     <none>
    Command:
      workflow-controller
    Args:
      --configmap
      workflow-controller-configmap
      --executor-image
      argoproj/argoexec:latest
```
Are you still having this issue? If so, could you provide more advice on how to reproduce?

**Comment by ptemmer** [comment]
I just realized I did not mention I was having this issue with 2.4.0rc. I'll try with the final 2.4 release and confirm.

**Comment by simster7** [comment]
Fee free to repoen if the issue comes up again

**Comment by LinuxSuRen** [comment]
Got the same issue on v3.4.11

**Comment by rossigee** [comment]
I can reproduce with this with latest version (v3.5.10)...

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: expression-destructure-json-complex-outputs-result-
spec:
  serviceAccountName: argo-workflow
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: fake-generated-json
            template: fake-json

          - name: extract-parameter-from-last-step 
            template: extract-value
            inputs:
              parameters:
                - name: result
                  value: "{{steps.fake-generated-json.outputs.result}}"
                - name: a
                  value: "{{=jsonpath(steps.fake-generated-json.outputs.result, '$.a')}}"
                - name: b
                  value: "{{=jsonpath(steps.fake-generated-json.outputs.result, '$.b')}}"
                - name: c
                  value: "{{=jsonpath(steps.fake-generated-json.outputs.result, '$.c')}}"
            dependencies:
              - fake-generated-json

    - name: fake-json
      container:
        image: alpine:latest
        command:
          - sh
          - -c
        args:
          - |
            echo "{ \"a\": 10, \"b\": \"alpha\", \"c\": true}"

    - name: extract-value
      inputs:
        parameters:
          - name: "result"
            value: ""
          - name: "a"
            value: ""
          - name: "b"
            value: ""
          - name: "c"
            value: ""
      container:
        image: alpine:latest
        command:
          - sh
          - -c
        args:
          - |
            echo "Result: {{ inputs.parameters.result }}"
            echo "Value 'a': {{ inputs.parameters.a }}"
            echo "Value 'b': {{ inputs.parameters.b }}"
            echo "Value 'c': {{ inputs.parameters.c }}"

```
