### ISSUE TITLE
Enable to schedule Argo CD deployments using workflows

### ISSUE THREAD

**Issue by kivio** [argoproj/argo-workflows#1665]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:
As user of Argo as whole ecosystem I want to easy schedule Deployment using Workflows that all Argo components can use it.
**What you expected to happen**:
In this moment I need to use Argo CD API to do that using curl container
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Idea:
I want simple workflow construction that will schedule deployments.
```yaml
name: schedule-app-deploy
deployment: # it will utilize special container under the hood
  namespace: app-resources
  project: new-frontend
  app: guest-book
```
