### ISSUE TITLE
Parameter aggregation doesn't work when aggregating file-based output parameters created in a 'script' template

### ISSUE THREAD

**Issue by ryan-maus** [argoproj/argo-workflows#1685]
BUG REPORT

**What happened**:
When an output parameter is created from a file in a ```script``` template, that parameter cannot be used in parameter aggregation.

**What you expected to happen**:
I would expect it to be aggregated similarly to output parameters generated from other types of templates.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aggregation-bug-minimal-repro-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: test-array
      value: |
        ["a", "b", "c"]

  templates:
  - name: main
    inputs:
      parameters: [{ name: test-array }]
    dag:
      tasks:
        # this is just a simple task to show that echo-py works like echo
      - name: show-echo-py-works
        template: echo-py
        arguments:
          parameters: [{ name: message, value: hello world }]

        # also a simple task to show that the parameter output of echo-py works as expected in other scenarios
      - name: show-echo-py-output-param-works
        dependencies: [show-echo-py-works]
        template: echo
        arguments:
          parameters: [{ name: message, value: "{{tasks.show-echo-py-works.outputs.parameters.output-param}}" }]

      - name: parallel-echo
        template: echo # POSSIBLE BUG HERE: switching this to echo-py results in this error on 'argo submit'
                       # Failed to submit workflow: templates.main.tasks.aggregate-messages failed to resolve {{tasks.parallel-echo.outputs.parameters}}
        arguments:
          parameters: [{ name: message, value: "{{item}}" }]
        withParam: "{{inputs.parameters.test-array}}"

      - name: aggregate-messages
        dependencies: [parallel-echo]
        template: echo
        arguments:
          parameters:
          - { name: message, value: "{{tasks.parallel-echo.outputs.parameters}}" } # parameter aggregation here

  - name: echo
    inputs:
      parameters: [{ name: message }]
    outputs:
      parameters: [{ name: output-param, valueFrom: { path: /tmp/output.txt }}]
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo SHELL:{{inputs.parameters.message}} | tee /tmp/output.txt "]

  - name: echo-py
    inputs:
      parameters: [{ name: message }]
    outputs:
      parameters: [{ name: output-param, valueFrom: { path: /tmp/output.txt }}]
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        with open('/tmp/output.txt', 'w') as file:
          print('PYTHON {{inputs.parameters.message}}')
          file.write('PYTHON {{inputs.parameters.message}}')
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-19T11:13:49Z"
  compiler: gc
  gitCommit: 96fac5cd13a5dc064f7d9f4f23030a6aeface6cc
  gitTreeState: clean
  gitVersion: v1.14.6
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-09-06T18:30:33Z"
  compiler: gc
  gitCommit: c9de33b5439df6e206d7ba646787c6ace92d737b
  gitTreeState: clean
  gitVersion: v1.14.6-gke.2
  goVersion: go1.12.9b4
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                aggregation-bug-minimal-repro-7knhm
Namespace:           default
ServiceAccount:      default
Status:              Succeeded
Created:             Wed Oct 16 20:22:39 -0500 (11 seconds ago)
Started:             Wed Oct 16 20:22:39 -0500 (11 seconds ago)
Finished:            Wed Oct 16 20:22:50 -0500 (now)
Duration:            11 seconds
Parameters:          
  test-array:        ["a", "b", "c"]


STEP                                    PODNAME                                         DURATION  MESSAGE
 ✔ aggregation-bug-minimal-repro-7knhm                                                            
 ├-✔ parallel-echo(0:a)                 aggregation-bug-minimal-repro-7knhm-1202659154  2s        
 ├-✔ parallel-echo(1:b)                 aggregation-bug-minimal-repro-7knhm-1074957080  2s        
 ├-✔ parallel-echo(2:c)                 aggregation-bug-minimal-repro-7knhm-1853657018  2s        
 ├-✔ show-echo-py-works                 aggregation-bug-minimal-repro-7knhm-267766859   4s        
 ├-✔ aggregate-messages                 aggregation-bug-minimal-repro-7knhm-2458033281  2s        
 └-✔ show-echo-py-output-param-works    aggregation-bug-minimal-repro-7knhm-4018091049  2s
```
When using ```echo-py``` in the parallel step:
```
2019/10/16 20:23:59 Failed to submit workflow: templates.main.tasks.aggregate-messages failed to resolve {{tasks.parallel-echo.outputs.parameters}}
```
