### ISSUE TITLE
Randomly Collision in pod names when Big workflow submitted  

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#1714]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
**What happened**:
Recently observed Workflow controller is crashing with panic whenever POD name collision happens.

**What you expected to happen**:
Pod names should be a unique per workflow and workflow should continually run.

**How to reproduce it (as minimally and precisely as possible)**:
The bug is observed inconsistently when big workflow (300+ steps ) is submitted.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
``` v2.4.2
- Kubernetes version :
```v1.14
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
time="2019-10-24T18:04:44Z" level=error msg="Recovered from panic: node cff-sybill-xr4j9[3].parallelize-task[0].select-partitioned-files-and-run-batch(27:s3://idl-cdoml-uw2-processing-cdoml-prd/cff-models/cff-sybill/develop/data/input/training_100p/part-00027-74b11656-3841-48c5-9bf9-e43ee4cd78c5-c000.snappy.parquet).model-execution(2) already initialized\ngoroutine 169 [running]:\nruntime/debug.Stack(0xc00015f560, 0x16e1c97, 0x5)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate.func2(0xc00015f560)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:149 +0xb6\n
panic(0x1473a00, 0xc0007b2af0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9
\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).initializeNode(0xc00015f560, 0xc001ae1e60, 0x108, 0x16e0737, 0x3, 0x18b3e40, 0xc0012975c0, 0xc000f5df80, 0x1b, 0x16e4677, ...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1360 
+0xdab\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).initializeExecutableNode(0xc00015f560, 0xc001ae1e60, 0x108, 0x16e0737, 0x3, 0xc000868560, 0xc001a7a000, 0x18b3e40, 0xc0012975c0, 0xc000f5df80, ...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1304 
+0xd6\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00015f560, 0xc001ae1e60, 0x108, 0x18b3e40, 0xc0012975c0, 0xc000a07ee0, 0xc0019b7420, 0x2, 0x4, 0x0, ...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1203 
+0x1174\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc00015f560, 0xc00066d800, 0xc003647f40, 0xf)\n\t/go/src/github.com/argoproj/argo/workflow/controller/dag.go:406 
+0x754\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeDAG(0xc00015f560, 0xc000ddc200, 0xf5, 0xc000a07ee0, 0xc000ead200, 0xc00187f740, 0x1a, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/dag.go:231 
+0x287\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00015f560, 0xc00168dd00, 0xf5, 0x18b3ec0, 0xc0003d7e00, 0xc002b7fb40, 0xc0033bbdc0, 0x2, 0x4, 0x0, ...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1216 
+0xdd3\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc00015f560, 0xc002d3e000, 0x64, 0x4, 0xc0019b2930, 0x27, 0xc00177d220, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:211 
+0xd7a\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc00015f560, 0xc00075bb90, 0x24, 0xc002b7fb40, 0xc00220a480, 0xc000806020, 0x10, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:77 
+0x448\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00015f560, 0xc0019b27b0, 0x24, 0x18b3ec0, 0xc002b8e460, 0xc002b7f200, 0xc0033bab60, 0x2, 0x4, 0x0, ...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1210 
+0xd63\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc00015f560, 0xc002b8e3c0, 0x1, 0x4, 0xc002232ec0, 0x13, 0xc00177f988, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:211 +0xd7a\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc00015f560, 0xc000806030, 0x10, 0xc002b7f200, 0xc00160d8c0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:77 +0x448\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00015f560, 0xc001e65690, 0x10, 0x18b3e80, 0xc00160cd80, 0xc000870f40, 0xc0000f42c0, 0xc, 0xc, 0x0, ...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1210 +0xd63\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate(0xc00015f560)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:212 +0x51c\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc000340400, 0xc000744300)\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:304 +0x53f\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc000340400)\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:230 +0x2b\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker-fm()\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:171 +0x2a\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0006da0c0)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006da0c0, 0x3b9aca00, 0x0, 0xc0000a6001, 0xc0003d2000)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbe\nk8s.io/apimachinery/pkg/util/wait.Until(0xc0006da0c0, 0x3b9aca00, 0xc0003d2000)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d\ncreated by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:171 +0x75f\n" namespace=data-mlplatform-ml-batch-svc-usw2-prd-stg workflow=cff-sybill-xr4j9


$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by jessesuen** [comment]
I think this new logic is causing the problem. @dtaniwaki can you check

```golang
		// This is the case the child node has been done,
		//  but the retry node state is still running.
		//  Create another child node.
		nodeName = fmt.Sprintf("%s(%d)", retryNodeName, len(retryParentNode.Children))
		node = nil
	}
```

**Comment by thundergolfer** [comment]
> The bug is observed inconsistently when big workflow (300+ steps ) is submitted.

Just curious, is this a real workflow, or an abnormally large workflow created specifically to surface the bug? 

If it's real, how is this workflow being defined? It seems having a single YAML for the workflow would be painfully large and unwieldy?

**Comment by sarabala1979** [comment]
It is a real workflow. We are using Argo workflow for  ML training and modeling.  No of steps will be dynamically increased based on no of input files that are using `withItems` argument options. Each step is a DAG of three tasks.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: large-ml-workflow-
spec:
  entrypoint: hello-hello-hello

  templates:
    - name: hello-hello-hello
      steps:
        - - name: generate
            template: gen-number-list
        - - name: hello1
            template: diamond
            arguments:
              parameters:
                - name: seconds
                  value: "{{item}}"
            withParam: "{{steps.generate.outputs.result}}"
    - name: gen-number-list
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import json
          import sys
          json.dump([i for i in range(1, 100)], sys.stdout)

    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]

    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.7
        command: [echo, "{{inputs.parameters.message}}"]

    - name: diamond
      dag:
        tasks:
          - name: A
            template: nested-diamond
            arguments:
              parameters: [{name: message, value: A}]
          - name: B
            dependencies: [A]
            template: nested-diamond
            arguments:
              parameters: [{name: message, value: B}]
          - name: C
            dependencies: [A]
            template: nested-diamond
            arguments:
              parameters: [{name: message, value: C}]
          - name: D
            dependencies: [B, C]
            template: nested-diamond
            arguments:
              parameters: [{name: message, value: D}]
    - name: nested-diamond
      inputs:
        parameters:
          - name: message
      dag:
        tasks:
          - name: A
            template: echo
            arguments:
              parameters: [{name: message, value: "{{inputs.parameters.message}}A"}]
          - name: B
            dependencies: [A]
            template: echo
            arguments:
              parameters: [{name: message, value: "{{inputs.parameters.message}}B"}]
          - name: C
            dependencies: [A]
            template: echo
            arguments:
              parameters: [{name: message, value: "{{inputs.parameters.message}}C"}]
          - name: D
            dependencies: [B, C]
            template: echo
            arguments:
              parameters: [{name: message, value: "{{inputs.parameters.message}}D"}]
```

**Comment by thundergolfer** [comment]
@sarabala1979 thanks for info. Makes total sense that it involves dynamic step generation.

**Comment by dtaniwaki** [comment]
I think this code is related.
https://github.com/argoproj/argo/blob/12b983f4c00bda3f9bedd14a316b0beade6158ed/workflow/controller/operator.go#L1237-L1241

If something happens during the actual node processing, the node is not registered as a child and the children's number is not increased, therefore, new nodes with an existing name are generated.

Here's the minimum manifest to reproduce this issue.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-container-
spec:
  entrypoint: retry-container
  templates:
  - name: retry-container
    retryStrategy:
      limit: 5
    container:
      image:
```

However, the manifest example described in the issue description doesn't have `retryStrategy`. I think we should make sure if the panic appeared in the log is actually caused by this manifest.
