### ISSUE TITLE
When using script template input artifact is not able to save in volume mount

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo-workflows#1722]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

**What happened**:
When using script template input artifact is not able to save in volume mount

**How to reproduce it (as minimally and precisely as possible)**:

```
- name: execute
    inputs:
      artifacts:
      - name: config
        path: /mnt/vol/.aws/config
        mode: 0777
        raw:
          data: |
            [profile default]
            role_arn = arn:abc
            credential_source = Ec2InstanceMetadata
    script:
      volumeMounts:
      - mountPath: /mnt/vol/.aws
        name: aws
      image: my-image
      env:
      - name: AWS_DEFAULT_REGION
        value: us-west-2
      - name: AWS_CONFIG_FILE
        value: /mnt/vol/.aws/config
      command: [sh]
      source: |
        echo "Hello World"
```

**Anything else we need to know?**:

```
time="2019-10-31T23:50:37Z" level=info msg="Start loading input artifacts..."
time="2019-10-31T23:50:37Z" level=info msg="Downloading artifact: config"
time="2019-10-31T23:50:37Z" level=info msg="Specified artifact path /mnt/volume/.aws/config overlaps with volume mount at /mnt/volume/.aws. Extracting to volume mount"
time="2019-10-31T23:50:37Z" level=error msg="executor error: open /mainctrfs/mnt/volume/.aws/config.tmp: no such file or directory"
time="2019-10-31T23:50:37Z" level=info msg="Alloc=4745 TotalAlloc=9854 Sys=70334 NumGC=3 Goroutines=4"
time="2019-10-31T23:50:37Z" level=fatal msg="open /mainctrfs/mnt/volume/.aws/config.tmp: no such file or directory"
```

**Environment**:
- Argo version:
```
$ argo version

argo: v2.4.2
  BuildDate: 2019-10-21T18:39:52Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
