### ISSUE TITLE
[Bug] Global Output params not getting set if step fails

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo-workflows#1759]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

**What happened**:
Global Output params not getting set if step fails

**What you expected to happen**:
Global Output params should get set irrespective of step failing

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-outputs-
spec:
  serviceAccountName: jenkins
  entrypoint: generate-globals
  onExit: consume-globals

  templates:
  - name: generate-globals
    steps:
    - - name: generate
        template: global-output
        arguments:
          parameters:
          - name: msg
            value: hello-world
    - - name: generate-2
        template: global-output
        arguments:
          parameters:
          - name: msg
            value: hi-deepak
    - - name: generate-another
        template: global-output
        arguments:
          parameters:
          - name: msg
            value: goodbye-world

  # Template which produces a global parameter and artifact
  - name: global-output
    inputs:
      parameters:
      - name: msg
    script:
      image: alpine:3.7
      command: [sh]
      source: |
        echo -n {{inputs.parameters.msg}} > /tmp/hello_world.txt &&
        status=$(cat /tmp/hello_world.txt) &&
        echo -n ${status}
        if [ ${status} == 'goodbye-world' ]; then
          exit 1;
        fi
    outputs:
      parameters:
      # export a global parameter. The parameter will be programatically available in the completed
      # workflow object under: workflow.status.outputs.parameters
      - name: hello-param
        valueFrom:
          path: /tmp/hello_world.txt
        globalName: my-global-param

  # Once exported, global outputs are referenceable in later parts of the workflow.
  # In this example, the consume-globals template is invoked after the generate-globals step, as
  # well as in the onExit handler. and can reference the globals, my-global-param and my-global-art.
  - name: consume-globals
    steps:
    - - name: consume-global-param
        template: consume-global-param

  - name: consume-global-param
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["echo {{workflow.outputs.parameters.my-global-param}}"]
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
Name:                e2e-tests-credit-card-model-xkjq4
Namespace:           data-mlplatform-training-pltfrm-usw2-ppd-qal
ServiceAccount:      jenkins
Status:              Failed
Message:             child 'e2e-tests-credit-card-model-xkjq4-234577952' failed
Created:             Tue Nov 12 10:53:22 -0800 (2 hours ago)
Started:             Tue Nov 12 10:53:22 -0800 (2 hours ago)
Finished:            Tue Nov 12 10:53:40 -0800 (2 hours ago)
Duration:            18 seconds
Parameters:          
  env:               QAL
  k8s-iam-role-annotation: k8s-data-mlplatform-training-pltfrm-usw2-ppd-qal
  ml-platform-role:  arn:aws:iam::952298799207:role/sagemaker_training_role
  giturl:            https://github.intuit.com/dkumar11/e2e-tests-credit-card-model.git
  gitbranch:         sagemaker_training_job_fail_2
  gitcommit:         ed884542c72497c7d61eba11793b4a344e5a3a1a-20191108192402
  model-artifact:    docker.artifactory.a.intuit.com/data/mlplatform/training-pltfrm/service/e2e-tests-credit-card-model:ed884542c72497c7d61eba11793b4a344e5a3a1a-20191108192144
Output Parameters:   
  my-global-param:   hi-deepak

STEP                                                           PODNAME                                       DURATION  MESSAGE
 ✖ e2e-tests-credit-card-model-xkjq4 (generate-globals)                                                                child 'e2e-tests-credit-card-model-xkjq4-234577952' failed
 ├---✔ generate (global-output)                                e2e-tests-credit-card-model-xkjq4-1170030584  4s        
 ├---✔ generate-2 (global-output)                              e2e-tests-credit-card-model-xkjq4-490201916   4s        
 └---✖ generate-another (global-output)                        e2e-tests-credit-card-model-xkjq4-234577952   4s        failed with exit code 1
                                                                                                                                    
 ✔ e2e-tests-credit-card-model-xkjq4.onExit (consume-globals)                                                          
 └---✔ consume-global-param (consume-global-param)             e2e-tests-credit-card-model-xkjq4-353356540   2s

```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
time="2019-11-12T18:53:33Z" level=info msg="Creating PNS executor (namespace: data-mlplatform-training-pltfrm-usw2-ppd-qal, pod: e2e-tests-credit-card-model-xkjq4-234577952, pid: 8, hasOutputs: true)"
time="2019-11-12T18:53:33Z" level=info msg="Executor (version: v2.4.2, build_date: 2019-10-21T18:39:09Z) initialized (pod: data-mlplatform-training-pltfrm-usw2-ppd-qal/e2e-tests-credit-card-model-xkjq4-234577952) with template:\n{\"name\":\"global-output\",\"arguments\":{},\"inputs\":{\"parameters\":[{\"name\":\"msg\",\"value\":\"goodbye-world\"}]},\"outputs\":{\"parameters\":[{\"name\":\"hello-param\",\"valueFrom\":{\"path\":\"/tmp/hello_world.txt\"},\"globalName\":\"my-global-param\"}]},\"metadata\":{},\"script\":{\"name\":\"\",\"image\":\"alpine:3.7\",\"command\":[\"sh\"],\"resources\":{},\"source\":\"echo -n goodbye-world \\u003e /tmp/hello_world.txt \\u0026\\u0026\\nstatus=$(cat /tmp/hello_world.txt) \\u0026\\u0026\\necho -n ${status}\\nif [ ${status} == 'goodbye-world' ]; then\\n  exit 1;\\nfi\\n\"}}"
time="2019-11-12T18:53:33Z" level=info msg="Loading script source to /argo/staging/script"
time="2019-11-12T18:53:33Z" level=info msg="Start loading input artifacts..."
time="2019-11-12T18:53:33Z" level=info msg="Alloc=4646 TotalAlloc=9766 Sys=70334 NumGC=3 Goroutines=4"

$ kubectl logs <failedpodname> -c wait
time="2019-11-12T18:53:34Z" level=info msg="Creating PNS executor (namespace: data-mlplatform-training-pltfrm-usw2-ppd-qal, pod: e2e-tests-credit-card-model-xkjq4-234577952, pid: 24, hasOutputs: true)"
time="2019-11-12T18:53:34Z" level=info msg="Executor (version: v2.4.2, build_date: 2019-10-21T18:39:09Z) initialized (pod: data-mlplatform-training-pltfrm-usw2-ppd-qal/e2e-tests-credit-card-model-xkjq4-234577952) with template:\n{\"name\":\"global-output\",\"arguments\":{},\"inputs\":{\"parameters\":[{\"name\":\"msg\",\"value\":\"goodbye-world\"}]},\"outputs\":{\"parameters\":[{\"name\":\"hello-param\",\"valueFrom\":{\"path\":\"/tmp/hello_world.txt\"},\"globalName\":\"my-global-param\"}]},\"metadata\":{},\"script\":{\"name\":\"\",\"image\":\"alpine:3.7\",\"command\":[\"sh\"],\"resources\":{},\"source\":\"echo -n goodbye-world \\u003e /tmp/hello_world.txt \\u0026\\u0026\\nstatus=$(cat /tmp/hello_world.txt) \\u0026\\u0026\\necho -n ${status}\\nif [ ${status} == 'goodbye-world' ]; then\\n  exit 1;\\nfi\\n\"}}"
time="2019-11-12T18:53:34Z" level=info msg="Waiting on main container"
time="2019-11-12T18:53:34Z" level=warning msg="Polling root processes (1m0s)"
time="2019-11-12T18:53:34Z" level=info msg="pid 42: &{root 29 2147484141 {681410830 63709181614 0x29179c0} {171 16884646 1 16877 0 0 0 0 29 4096 0 {1573584814 613410326} {1573584814 681410830} {1573584814 681410830} [0 0 0]}}"
time="2019-11-12T18:53:34Z" level=info msg="Secured filehandle on /proc/42/root"
time="2019-11-12T18:53:34Z" level=info msg="containerID 577b579cfbdc20381e21ee36ba20de2cc5181282f53db3f61e36c5ef1cba0039 mapped to pid 42"
time="2019-11-12T18:53:34Z" level=info msg="pid 42: &{root 29 2147484141 {681410830 63709181614 0x29179c0} {171 16884646 1 16877 0 0 0 0 29 4096 0 {1573584814 613410326} {1573584814 681410830} {1573584814 681410830} [0 0 0]}}"
time="2019-11-12T18:53:35Z" level=info msg="main container started with container ID: 577b579cfbdc20381e21ee36ba20de2cc5181282f53db3f61e36c5ef1cba0039"
time="2019-11-12T18:53:35Z" level=info msg="Starting annotations monitor"
time="2019-11-12T18:53:35Z" level=info msg="Main pid identified as 42"
time="2019-11-12T18:53:35Z" level=info msg="Successfully secured file handle on main container root filesystem"
time="2019-11-12T18:53:35Z" level=info msg="Waiting for main pid 42 to complete"
time="2019-11-12T18:53:35Z" level=info msg="Starting deadline monitor"
time="2019-11-12T18:53:35Z" level=info msg="Stopped root processes polling due to successful securing of main root fs"
time="2019-11-12T18:53:36Z" level=info msg="Main pid 42 completed"
time="2019-11-12T18:53:36Z" level=info msg="Main container completed"
time="2019-11-12T18:53:36Z" level=info msg="Saving output parameters"
time="2019-11-12T18:53:36Z" level=info msg="Saving path output parameter: hello-param"
time="2019-11-12T18:53:36Z" level=info msg="Copying /tmp/hello_world.txt from base image layer"
time="2019-11-12T18:53:36Z" level=info msg="Annotations monitor stopped"
time="2019-11-12T18:53:36Z" level=info msg="Successfully saved output parameter: hello-param"
time="2019-11-12T18:53:36Z" level=info msg="No output artifacts"
time="2019-11-12T18:53:36Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2019-11-12T18:53:36Z" level=info msg="Annotating pod with output"
time="2019-11-12T18:53:36Z" level=info msg="Killing sidecars"
time="2019-11-12T18:53:36Z" level=info msg="Alloc=5715 TotalAlloc=12443 Sys=70334 NumGC=4 Goroutines=9"
```

**Comment by Ark-kun** [comment]
> Global Output params should get set irrespective of step failing

I'm not sure this behavior should be expected.
I'd be negatively surprised if failed steps resulted in changes.

**Comment by xianlubird** [comment]
same to @Ark-kun

**Comment by alexec** [comment]
@simster7 can you link to the fix you mentioned today?

**Comment by wreed4** [comment]
I have a use-case for this.

I need to share a value from a step in my main template to my exit handler.  I feel like this must be a common pattern but I can't find any good way to do it.  so I've solved it with one level of indirection:
```yaml
  entrypoint: main
  onExit: exit

  #####################
  ## Top-level flow ##
  #####################
  templates:
  # This level of indirection is needed to pass the parameter of one step here
  # into the exit handler.  We tried many MANY ways of doing this and this is
  # by far the cleanest.
  - name: main
    steps:
    - - name: impl
        template: impl

  - name: impl
    outputs:
      parameters:
      - name: out
        valueFrom:
          parameter: "{{steps.get-desired-value.outputs.parameters.out}}"
        globalName: out
    steps:
      # step that SUCCEEDS. does NOT generate a global param
    - - name: get-desired-value
        template: get-value
      # step that FAILS
    - - name: iterate-over-value
        template: other-template
        arguments:
          parameters:
          - name: name
            value: "{{item.name}}"
          - name: namespace
            value: "{{item.namespace}}"
        withParam: "{{steps.get-desired-value.outputs.parameters.out}}"

  ##################
  #  Exit Handler  #
  ##################
  - name: exit
    dag:
      tasks:
      # try to use desired value from above
      - name: clean-up-values
        template: third-template
        arguments:
          parameters:
          - name: name
            value: "{{item.name}}"
          - name: namespace
            value: "{{item.namespace}}"
          - name: suspend
            value: "{{item.suspend}}"
        withParam: "{{workflow.outputs.parameters.out}}"
```
The reason I cannot have the subtemplate put a global variable is because actually that subtemplate is called twice and I only want one of the calls values.  I tried to do this at first by setting the global output on the subtemplate with a parameterized, predictable name, but when linting the workflow, I cannot refer to the name I know it will be.  i.e.:
```yaml
....
withParam: "{{workflow.outputs.parameters.out-known-value}}"
....
globalName: "out-{{intputs.parameters.name}}"
```

This is a bit of a large issue for us as I cannot figure out a decent way to get a value into the exit handler and I can't find any examples that do this which is a little shocking as I have to imagine it's a major use-case of an exit handler. 

I actually only need this value in an exit handler _specifically in the case that a step in the main function fails_! :laughing:

Is there anything I'm missing?
