### ISSUE TITLE
Go templating substitution is enforcing on second pass

### ISSUE THREAD

**Issue by ptemmer** [argoproj/argo-workflows#1765]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
The following use case is currently not possible with Workflows:

Have a workflow that creates an Argo Sensor, which has a nested Argo Workflow as triggered resource containing go templating. The nested go templates should not be substituted. As a nasty workaround was possible in previous versions of Argo Workflow:

`{{workflow.parameters.left_brace}}{{workflow.parameters.left_brace}}inputs.parameters.someParam{{workflow.parameters.right_brace}}{{workflow.parameters.right_brace}}`

Version 2.4.1 however is doing a second enforcing pass, resulting in an error stating `failed to submit workflow: failed to resolve {{inputs.parameters.someParam}}`

**What you expected to happen**:
The workflow to be created, containing {{inputs.parameters.someParam}} "as is" in the Sensor's triggered resource.

**How to reproduce it (as minimally and precisely as possible)**:
``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-wf
spec:
  entrypoint: A
  arguments:
    parameters:
    - name: left_brace
      value: '{'
    - name: right_brace
      value: '}'
  serviceAccountName: argo

  templates:
  - name: A
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Sensor
        metadata:
          labels:
            sensors.argoproj.io/sensor-controller-instanceid: argo-events
            argo-events-sensor-version: v0.10
          name: test-sensor
          namespace: argo
        spec:
          dependencies:
          - name: webhook-gateway:webhook
          eventProtocol:
            http:
              port: "9300"
            type: HTTP    
          template:
            spec:
              containers:
              - image: argoproj/sensor:v0.10
                imagePullPolicy: Always
                name: sensor
          triggers:
          - template:
              version: argoproj.io/v1alpha1
              kind: Workflow
              group: argoproj
              name: test
              source:
                resource: 
                  apiVersion: argoproj.io/v1alpha1
                  kind: Workflow
                  metadata:
                    generateName: nested-test-wf
                  spec:
                    arguments:
                      parameters:
                      - name: someParam
                        value: "value for someParam"
                    entrypoint: A
                    serviceAccountName: argo
                    templates:
                    - name: A
                      inputs:
                        parameters:
                        - name: someParam
                      container:
                        image: busybox
                        command: [sh]
                        args:
                        - -c
                        - echo {{workflow.parameters.left_brace}}{{workflow.parameters.left_brace}}inputs.parameters.someParam{{workflow.parameters.right_brace}}{{workflow.parameters.right_brace}}
```
**Anything else we need to know?**:

**Environment**:
- Argo version: 2.4.1
- Kubernetes version : 1.14.8
