### ISSUE TITLE
Pass `parallelism` via CLI? Error on string vs int

### ISSUE THREAD

**Issue by sebinsua** [argoproj/argo-workflows#1780]
Is it possible to pass in parallelism via the command line?

I tried to setup a parameter to do this, but got an error about the value not being a number.

```
Failed to parse workflow:
error unmarshaling JSON: while decoding JSON: json:
cannot unmarshal string into Go struct field WorkflowSpec.parallelism of type int64
```

If it's not possible by default to set this for the workflow from the command line, is there a way of coercing a string containing a number into a number?

**Edit**: Do you have [anything like an `int` filter](https://stackoverflow.com/a/28234670)? I heard you were using Jinja but I can't find it within the codebase.

**Comment by simster7** [comment]
> Is it possible to pass in parallelism via the command line?

Currently not possible.

> Do you have anything like an int filter? I heard you were using Jinja but I can't find it within the codebase.

Not as far as I know.

> If it's not possible by default to set this for the workflow from the command line, is there a way of coercing a string containing a number into a number?

Could you elaborate a bit on this? Are you trying to run dynamically generated Workflows?

**Comment by sebinsua** [comment]
> > If it's not possible by default to set this for the workflow from the command line, is there a way of coercing a string containing a number into a number?
> 
> Could you elaborate a bit on this? Are you trying to run dynamically generated Workflows?

I tried this at one point, but it doesn't work:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-parallelism-parameter-
spec:
  entrypoint: entrypoint-name
  arguments:
    parameters:
    - name: parallelism
      value: 10
  parallelism: "{{workflow.parameters.parallelism}}"
```

I'm not trying to run dynamicly generated workflows. I just wanted to be able to configure the level of parallelism a workflow should be run by at the point of submission.
