### ISSUE TITLE
Proposal: A better way to specify optional dependencies

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo-workflows#1781]
Currently in Argo every task has `depends` attribute that lists the tasks that needs to succeed first.
Argo also supports the `continueOn: Failure` attribute that makes the downstream tasks run even when the current task fails.

I think these two options are still not enough to express some common user scenarios.
I also think that the `continueOn` is a bit problematic since it changes the orchestration of other downstream tasks, while I think that it's better for tasks to change their *own* behavior (e.g. to enable running when the upstream fails).

Common scenarios:

1. Only start task when all dependent tasks succeed (supported by default)
2. Start task when one of two dependencies succeeded.
3. Start task when some optional dependency has run and failed.
4. Start task even when some optional dependency was skipped (e.g. due to conditional execution).

Different task states:
* succeeded
* failed
* skipped
* completed = succeeded or failed
* any = skipped or completed (does not include running tasks!)

Logical operators:
* and
* or
* not

Some example tasks:
```yaml
name: chose-initial-or-better-model
depends:
  and:
  - completed: get-initial-model
  - any: find-better-model
```

```yaml
depends:
  or:
  - completed: A
  - completed: B
```

```yaml
name: exit-cleanup
depends:
  and:
  - any: A
  - any: B
  - any: C
```

Some real-world scenarios:
* Aggregate after [conditional] branching
* * Depending on a flag, train the model using TrainerA or TrainerB. Then pass on the model that was trained.
* * If model is good or we've exhausted the retraining limit and then output the model. Otherwise, train the model a bit more on top of the current model.
* Reacting to failures:
* * Send e-mail on failure of particular task
* Reacting to completion
* * Stop some cluster when all tasks that use it complete (succeed or fail)
* Skipping optional task if it fails
* * Try to train a new model, but use the old model if the training failed for any reason
