### ISSUE TITLE
Python SDK for Argo

### ISSUE THREAD

**Issue by zhujiangyou** [argoproj/argo-workflows#1786]
hi,Where can I find a python SDK to replace Argo's various command-line interfaces？

**Comment by simster7** [comment]
We are working on an REST/gRPC API server that will provide the same functionality as the CLI.

**Comment by CermakM** [comment]
Hello @zhujiangyou ... check out https://github.com/CermakM/argo-client-python

**Comment by alexec** [comment]
What kind of functions would an SDK need to be minimally useful?

**Comment by CermakM** [comment]
@alexec @simster7 We've recently started working on [Argo Python SDK](https://github.com/CermakM/argo-python-sdk) ... it's under development, but starting to be quite useful already.

It builds upon the [models]( https://github.com/CermakM/argo-client-python) that I mentioned above.

Here is a hello-world example of the SDK usage:

<table>
<tr><th>Argo YAML</th><th>Argo Python</th></tr>
<tr>
<td valign="top"><p>

```yaml
# @file: hello-world.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      name: whalesay
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

</p></td>
<td valign="top"><p>

```python
from argo.workflows.sdk import Workflow
from argo.workflows.sdk import template

from argo.workflows.sdk.templates import V1Container


class HelloWorld(Workflow):

    entrypoint = "whalesay"

    @template
    def whalesay(self) -> V1Container:
        container = V1Container(
            image="docker/whalesay:latest",
            name="whalesay",
            command=["cowsay"],
            args=["hello world"]
        )

        return container
```

</p></td>
</tr>
</table>
