### ISSUE TITLE
Second step cannot get correct input value from loop item

### ISSUE THREAD

**Issue by TrevorNodeJS** [argoproj/argo-workflows#1793]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG 
**What happened**:
call  docker/whalesay:latest cowsay two times in every loop.
second call cannot print out correct message. Print our the item[0]'s content: hello world abc001sap.comabc001.

Because input parameters are item[0].

**What you expected to happen**:
Second step should print out correct message. 

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-two-steps-
spec:
  entrypoint: loop-example-main
  arguments:
    parameters:
      - name: tenants
        value: |
          [
            { "tenant-id": "abc001", "subdomain": "sap.com" , "message": "hello world abc001"},
            { "tenant-id": "ibm001", "subdomain": "ibm" , "message": "hello world ibm"},
            { "tenant-id": "apple001", "subdomain": "apple" , "message": "hello world apple"}
          ]

  templates:
  - name: loop-example-main
    parallelism: 1
    inputs:
      parameters:
        - name: tenants
    steps:
    - - name: loop-two-steps
        template: loop-two-steps
        arguments:
          parameters:
            - name: message
              value: "{{item.message}}"
            - name: tenant-id
              value: "{{item.tenant-id}}"
            - name: subdomain
              value: "{{item.subdomain}}"
        withParam: "{{inputs.parameters.tenants}}" 


  - name: loop-two-steps
    inputs:
      parameters:
      - name: message
      - name: tenant-id
      - name: subdomain

    steps:
    - - name: print-message-1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}" 
          - name: tenant-id
            value: "{{inputs.parameters.tenant-id}}" 
          - name: subdomain
            value: "{{inputs.parameters.subdomain}}"

    - - name: print-message-2
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}" 
          - name: tenant-id
            value: "{{inputs.parameters.tenant-id}}"
          - name: subdomain
            value: "{{inputs.parameters.subdomain}}"

  - name: whalesay
    inputs:
      parameters:
      - name: message
      - name: tenant-id
      - name: subdomain
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}{{inputs.parameters.subdomain}}{{inputs.parameters.tenant-id}}"]

```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```bash
$ argo version
argo: v2.4.2
  BuildDate: 2019-10-21T18:40:37Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: windows/amd64
```
- Kubernetes version :
```bash
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-10-15T12:11:03Z"
  compiler: gc
  gitCommit: 211047e9a1922595eaa3a1127ed365e9299a6c23
  gitTreeState: clean
  gitVersion: v1.14.8
  goVersion: go1.12.10
  major: "1"
  minor: "14"
  platform: windows/amd64
serverVersion:
  buildDate: "2019-10-15T12:02:12Z"
  compiler: gc
  gitCommit: 211047e9a1922595eaa3a1127ed365e9299a6c23
  gitTreeState: clean
  gitVersion: v1.14.8
  goVersion: go1.12.10
  major: "1"
  minor: "14"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>

- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```
