### ISSUE TITLE
Setting Global Output value of failed task sometimes works (indeterminate)

### ISSUE THREAD

**Issue by ebelisle** [argoproj/argo-workflows#1840]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Sometimes the output value of a failed task is set.

**What you expected to happen**:
The output value of a failed task is always set.  (or never set, if you want to match the behavior of a failed step)

**How to reproduce it (as minimally and precisely as possible)**:
Run attatched script.  (May take 2-3 runs).  Global outputs "until-dag-b*" will end with different values, some final, some initial. (Results are also shown in logs from result step)

**Anything else we need to know?**:
* Script attached below.  Specify `--serviceaccount` if needed.  Run with 
`argo submit  --watch argo-test.yaml`
* script also includes behavior of failed step setting global output.

**Environment**:
- Argo version:
```
argo: v2.4.3
  BuildDate: 2019-12-06T03:36:38Z
  GitCommit: cfe5f377bc3552fba90afe6db7a76edd92c753cd
  GitTreeState: clean
  GitTag: v2.4.3
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-19T11:13:54Z"
  compiler: gc
  gitCommit: 2d3c76f9091b6bec110a5e63777c332469e0cba2
  gitTreeState: clean
  gitVersion: v1.15.3
  goVersion: go1.12.9
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-10-18T17:56:01Z"
  compiler: gc
  gitCommit: b7174db5ee0e30c94a0b9899c20ac980c0850fc8
  gitTreeState: clean
  gitVersion: v1.14.8-eks-b7174d
  goVersion: go1.12.10
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                argo-test-x7cct
Namespace:           default
ServiceAccount:      developer
Status:              Failed
Created:             Thu Dec 12 13:46:07 -0700 (1 minute ago)
Started:             Thu Dec 12 13:46:07 -0700 (1 minute ago)
Finished:            Thu Dec 12 13:46:26 -0700 (1 minute ago)
Duration:            19 seconds
Output Parameters:
  global-result:     sample B
  until-b:
  until-c:           reset by c
  until-dag-b1:      initial-b1
  until-dag-b2:      initial-b2
  until-dag-b3:      initial-b3
  until-dag-b4:      final-b4
  until-dag-b5:      initial-b5
  until-dag-b6:      initial-b6
  until-dag-b7:      initial-b7
  until-dag-b8:      final-b8
  until-dag-b9:      initial-b9
  until-dag-b0:      initial-b0

STEP                                     PODNAME                     DURATION  MESSAGE
 ✖ argo-test-x7cct (root-flow)
 ├-✔ dag-a (dag-a)                       argo-test-x7cct-3911329071  2s
 ├-✖ sample-flow (sample-flow)                                                 child 'argo-test-x7cct-4191935787' failed
 | ├---✔ a (a)                           argo-test-x7cct-3573759395  2s
 | ├---✔ b (b)                           argo-test-x7cct-2347762391  2s
 | └---✖ c (c)                           argo-test-x7cct-4191935787  1s        failed with exit code 1
 ├-✖ dag-b0 (dag-b0)                     argo-test-x7cct-2244169462  3s        failed with exit code 1
 ├-✖ dag-b1 (dag-b1)                     argo-test-x7cct-2260947081  3s        failed with exit code 1
 ├-✖ dag-b2 (dag-b2)                     argo-test-x7cct-2210614224  3s        failed with exit code 1
 ├-✖ dag-b3 (dag-b3)                     argo-test-x7cct-2227391843  3s        failed with exit code 1
 ├-✖ dag-b4 (dag-b4)                     argo-test-x7cct-2311279938  3s        failed with exit code 1
 ├-✖ dag-b5 (dag-b5)                     argo-test-x7cct-2328057557  3s        failed with exit code 1
 ├-✖ dag-b6 (dag-b6)                     argo-test-x7cct-2277724700  3s        failed with exit code 1
 ├-✖ dag-b7 (dag-b7)                     argo-test-x7cct-2294502319  3s        failed with exit code 1
 ├-✖ dag-b8 (dag-b8)                     argo-test-x7cct-2378390414  3s        failed with exit code 1
 └-✖ dag-b9 (dag-b9)                     argo-test-x7cct-2395168033  3s        failed with exit code 1

 ✔ argo-test-x7cct.onExit (sample-exit)
 ├---○ success (show-global-result)                                            when 'Failed == Succeeded' evaluated false
 ├---✔ failure (show-global-result)      argo-test-x7cct-1109601981  3s
 └---✔ results (results)                 argo-test-x7cct-2655340870  3s
```
- executor logs:
```
# logs for b3 and b4, which had different global output results:

% argo logs argo-test-x7cct-2227391843 -c wait                                                                                                                                                  DI-7803/canary
time="2019-12-12T20:46:12Z" level=info msg="Creating a docker executor"
time="2019-12-12T20:46:12Z" level=info msg="Executor (version: v2.4.3, build_date: 2019-12-06T03:35:39Z) initialized (pod: default/argo-test-x7cct-2227391843) with template:\n{\"name\":\"dag-b3\",\"arguments\":{},\"inputs\":{},\"outputs\":{\"parameters\":[{\"name\":\"until-dag-b\",\"value\":\"final-b3\",\"globalName\":\"until-dag-b3\"}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo 'sample dag-B'; exit 1\"],\"resources\":{}}}"
time="2019-12-12T20:46:12Z" level=info msg="Waiting on main container"
time="2019-12-12T20:46:13Z" level=info msg="main container started with container ID: f834d03302ee730f4caa73546c8c9793a0af473eec048d9c85286756fe659f1c"
time="2019-12-12T20:46:13Z" level=info msg="Starting annotations monitor"
time="2019-12-12T20:46:13Z" level=info msg="docker wait f834d03302ee730f4caa73546c8c9793a0af473eec048d9c85286756fe659f1c"
time="2019-12-12T20:46:13Z" level=info msg="Starting deadline monitor"
time="2019-12-12T20:46:13Z" level=info msg="Main container completed"
time="2019-12-12T20:46:13Z" level=info msg="Saving output parameters"
time="2019-12-12T20:46:13Z" level=info msg="Saving path output parameter: until-dag-b"
time="2019-12-12T20:46:13Z" level=info msg="No output artifacts"
time="2019-12-12T20:46:13Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2019-12-12T20:46:13Z" level=info msg="Annotating pod with output"
time="2019-12-12T20:46:13Z" level=info msg="Annotations monitor stopped"
time="2019-12-12T20:46:13Z" level=info msg="Killing sidecars"
time="2019-12-12T20:46:13Z" level=info msg="Alloc=5653 TotalAlloc=12004 Sys=70590 NumGC=4 Goroutines=9"

% argo logs argo-test-x7cct-2311279938 -c wait                                                                                                                                                  DI-7803/canary
time="2019-12-12T20:46:13Z" level=info msg="Creating a docker executor"
time="2019-12-12T20:46:13Z" level=info msg="Executor (version: v2.4.3, build_date: 2019-12-06T03:35:39Z) initialized (pod: default/argo-test-x7cct-2311279938) with template:\n{\"name\":\"dag-b4\",\"arguments\":{},\"inputs\":{},\"outputs\":{\"parameters\":[{\"name\":\"until-dag-b\",\"value\":\"final-b4\",\"globalName\":\"until-dag-b4\"}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo 'sample dag-B'; exit 1\"],\"resources\":{}}}"
time="2019-12-12T20:46:13Z" level=info msg="Waiting on main container"
time="2019-12-12T20:46:14Z" level=info msg="main container started with container ID: 61640ef0dd820be0c40c13cf64187196c82d4fd148ec5935f513c2169e7e53c7"
time="2019-12-12T20:46:14Z" level=info msg="Starting annotations monitor"
time="2019-12-12T20:46:14Z" level=info msg="Starting deadline monitor"
time="2019-12-12T20:46:14Z" level=info msg="docker wait 61640ef0dd820be0c40c13cf64187196c82d4fd148ec5935f513c2169e7e53c7"
time="2019-12-12T20:46:14Z" level=info msg="Main container completed"
time="2019-12-12T20:46:14Z" level=info msg="Saving output parameters"
time="2019-12-12T20:46:14Z" level=info msg="Saving path output parameter: until-dag-b"
time="2019-12-12T20:46:14Z" level=info msg="No output artifacts"
time="2019-12-12T20:46:14Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2019-12-12T20:46:14Z" level=info msg="Annotating pod with output"
time="2019-12-12T20:46:14Z" level=info msg="Annotations monitor stopped"
time="2019-12-12T20:46:14Z" level=info msg="Killing sidecars"
time="2019-12-12T20:46:14Z" level=info msg="Alloc=5149 TotalAlloc=12011 Sys=70334 NumGC=4 Goroutines=9"

# both init executor logs were emtpy
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

- test-workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-test-
spec:
  entrypoint: root-flow
  onExit: sample-exit
  templates:

  - name: root-flow
    dag:
      tasks:
      - name: sample-flow
        template: sample-flow
      - name: dag-a
        template: dag-a
      - name: dag-b1
        dependencies: [dag-a]
        template: dag-b1
      - name: dag-b2
        dependencies: [dag-a]
        template: dag-b2
      - name: dag-b3
        dependencies: [dag-a]
        template: dag-b3
      - name: dag-b4
        dependencies: [dag-a]
        template: dag-b4
      - name: dag-b5
        dependencies: [dag-a]
        template: dag-b5
      - name: dag-b6
        dependencies: [dag-a]
        template: dag-b6
      - name: dag-b7
        dependencies: [dag-a]
        template: dag-b7
      - name: dag-b8
        dependencies: [dag-a]
        template: dag-b8
      - name: dag-b9
        dependencies: [dag-a]
        template: dag-b9
      - name: dag-b0
        dependencies: [dag-a]
        template: dag-b0

  - name: sample-flow
    steps:
      - - name: a
          template: a
      - - name: b
          template: b
      - - name: c
          template: c

  - name: sample-exit
    steps:
      - - name: success
          template: show-global-result
          when: "{{workflow.status}} == Succeeded"
      - - name: failure
          template: show-global-result
          when: "{{workflow.status}} != Succeeded"
      - - name: results
          template: results

  - name: a
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample A' > /tmp/result; exit 0"]
    outputs:
      parameters:
        - name: result
          valueFrom:
            path: /tmp/result
          globalName: global-result
        - name: until-b
          value: "reset by b"
          globalName: until-b
        - name: until-c
          value: "reset by c"
          globalName: until-c

  - name: b
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample B' > /tmp/result; exit 0"]
    outputs:
      parameters:
        - name: result
          valueFrom:
            path: /tmp/result
          globalName: global-result
        - name: until-b
          value: ""
          globalName: until-b

  - name: c
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample C' > /tmp/result; exit 1"]
    outputs:
      parameters:
        - name: until-c
          value: ""
          globalName: until-c

  - name: dag-a
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-A'; exit 0"]
    outputs:
      parameters:
        - {name: until-dag-b1, value: "initial-b1", globalName: until-dag-b1}
        - {name: until-dag-b2, value: "initial-b2", globalName: until-dag-b2}
        - {name: until-dag-b3, value: "initial-b3", globalName: until-dag-b3}
        - {name: until-dag-b4, value: "initial-b4", globalName: until-dag-b4}
        - {name: until-dag-b5, value: "initial-b5", globalName: until-dag-b5}
        - {name: until-dag-b6, value: "initial-b6", globalName: until-dag-b6}
        - {name: until-dag-b7, value: "initial-b7", globalName: until-dag-b7}
        - {name: until-dag-b8, value: "initial-b8", globalName: until-dag-b8}
        - {name: until-dag-b9, value: "initial-b9", globalName: until-dag-b9}
        - {name: until-dag-b0, value: "initial-b0", globalName: until-dag-b0}

  - name: dag-b1
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-B'; exit 1"]
    outputs:
      parameters: [{name: until-dag-b, value: "final-b1", globalName: until-dag-b1}]

  - name: dag-b2
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-B'; exit 1"]
    outputs:
      parameters: [{name: until-dag-b, value: "final-b2", globalName: until-dag-b2}]
  - name: dag-b3
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-B'; exit 1"]
    outputs:
      parameters: [{name: until-dag-b, value: "final-b3", globalName: until-dag-b3}]
  - name: dag-b4
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-B'; exit 1"]
    outputs:
      parameters: [{name: until-dag-b, value: "final-b4", globalName: until-dag-b4}]
  - name: dag-b5
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-B'; exit 1"]
    outputs:
      parameters: [{name: until-dag-b, value: "final-b5", globalName: until-dag-b5}]
  - name: dag-b6
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-B'; exit 1"]
    outputs:
      parameters: [{name: until-dag-b, value: "final-b6", globalName: until-dag-b6}]
  - name: dag-b7
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-B'; exit 1"]
    outputs:
      parameters: [{name: until-dag-b, value: "final-b7", globalName: until-dag-b7}]
  - name: dag-b8
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-B'; exit 1"]
    outputs:
      parameters: [{name: until-dag-b, value: "final-b8", globalName: until-dag-b8}]
  - name: dag-b9
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-B'; exit 1"]
    outputs:
      parameters: [{name: until-dag-b, value: "final-b9", globalName: until-dag-b9}]
  - name: dag-b0
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample dag-B'; exit 1"]
    outputs:
      parameters: [{name: until-dag-b, value: "final-b0", globalName: until-dag-b0}]
  - name: show-global-result
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'sample D: {{workflow.outputs.parameters.global-result}}'; exit 0"]

  - name: results
    script:
      image: alpine:latest
      command: [sh]
      source: |
        echo 'successful step can reset global value: expected: "" actual: "{{workflow.outputs.parameters.until-b}}"'
        echo 'failing step does not reset global value: expected: "reset by c" actual: "{{workflow.outputs.parameters.until-c}}"'
        echo 'failing task sometimes does not update global value: expected: "final-b1" actual: "{{workflow.outputs.parameters.until-dag-b1}}"'
        echo 'failing task sometimes does not update global value: expected: "final-b2" actual: "{{workflow.outputs.parameters.until-dag-b2}}"'
        echo 'failing task sometimes does not update global value: expected: "final-b3" actual: "{{workflow.outputs.parameters.until-dag-b3}}"'
        echo 'failing task sometimes does not update global value: expected: "final-b4" actual: "{{workflow.outputs.parameters.until-dag-b4}}"'
        echo 'failing task sometimes does not update global value: expected: "final-b5" actual: "{{workflow.outputs.parameters.until-dag-b5}}"'
        echo 'failing task sometimes does not update global value: expected: "final-b6" actual: "{{workflow.outputs.parameters.until-dag-b6}}"'
        echo 'failing task sometimes does not update global value: expected: "final-b7" actual: "{{workflow.outputs.parameters.until-dag-b7}}"'
        echo 'failing task sometimes does not update global value: expected: "final-b8" actual: "{{workflow.outputs.parameters.until-dag-b8}}"'
        echo 'failing task sometimes does not update global value: expected: "final-b9" actual: "{{workflow.outputs.parameters.until-dag-b9}}"'
        echo 'failing task sometimes does not update global value: expected: "final-b0" actual: "{{workflow.outputs.parameters.until-dag-b0}}"'
```
