### ISSUE TITLE
Suspend duration units not supported?

### ISSUE THREAD

**Issue by dougtoppin** [argoproj/argo-workflows#1875]
Checklist:

 * [x ] I've included the version.
 * [x ] I've included reproduction steps.
 * [x ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Following example suspend at https://raw.githubusercontent.com/argoproj/argo/master/examples/suspend-template.yaml

Suspend duration units not supported, example indicates that units included with duration should work

**What you expected to happen**:

Pass argo lint and successfully delay for 1 minute

**How to reproduce it (as minimally and precisely as possible)**:

submit a workflow with the following

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: suspend-template-
spec:
  entrypoint: suspend
  templates:
  - name: suspend
    steps:
    - - name: build
        template: whalesay
    - - name: delay
        template: delay
    - - name: release
        template: whalesay

  - name: delay
    suspend:
      duration: 2m    # Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"

  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
```

argo lint fails with

```
# argo lint wf.yaml
FATA[0000] wf.yaml failed to parse: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field SuspendTemplate.duration of type int32
```

argo submit fails with

```
argo submit --watch wf.yaml
2019/12/18 19:13:30 Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field SuspendTemplate.duration of type int32
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.4.3
  BuildDate: 2019-12-06T03:36:01Z
  GitCommit: cfe5f377bc3552fba90afe6db7a76edd92c753cd
  GitTreeState: clean
  GitTag: v2.4.3
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-09-18T14:36:53Z"
  compiler: gc
  gitCommit: 2bd9643cee5b3b3a5ecbd3af49d09018f0773c77
  gitTreeState: clean
  gitVersion: v1.16.0
  goVersion: go1.12.9
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-12-07T21:12:17Z"
  compiler: gc
  gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
  gitTreeState: clean
  gitVersion: v1.17.0
  goVersion: go1.13.4
  major: "1"
  minor: "17"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```
