### ISSUE TITLE
Can't set size of volumeClaimTemplate using a workflow variable

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo-workflows#1932]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

Running Argo 2.4.2, trying to use a workflow parameter to set the size of a `volumeClaimTemplate` fails with:
```
error unmarshaling JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```
The workflow is never submitted.

**What you expected to happen**:

I expect the workflow to validate successfully and be submitted.

**How to reproduce it (as minimally and precisely as possible)**:

Try to submit this workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: templated-volume-size-
spec:
  entrypoint: whalesay-volume
  arguments:
    parameters:
    - name: volume-size
      value: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "{{workflow.parameters.volume-size}}" 
  templates:
  - name: whalesay-volume 
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["echo generating message in volume; cowsay hello world | tee /mnt/vol/hello_world.txt"]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol

```

**Environment**:
- Argo version:
```
$ argo version
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:52Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-09-18T14:51:13Z"
  compiler: gc
  gitCommit: 67d2fcf276fcd9cf743ad4be9a9ef5828adc082f
  gitTreeState: clean
  gitVersion: v1.15.4
  goVersion: go1.12.9
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-11-26T00:40:25Z"
  compiler: gc
  gitCommit: a6ba43f5a24ac29e631bb627c9b2a719c4e93638
  gitTreeState: clean
  gitVersion: v1.15.4-gke.22
  goVersion: go1.12.11b4
  major: "1"
  minor: 15+
  platform: linux/amd64
```
