### ISSUE TITLE
Input artifacts should allow for defaults

### ISSUE THREAD

**Issue by samath117** [argoproj/argo-workflows#2026]
# Summary

Just like how input parameters allow for default values, input artifacts should allow for defaults which can be overridden by the instantiation.

# Motivation

The same as default input parameters. In my use case, I want to provide a default configuration file in the template but allow it to be overridden if necessary.

# Proposal

The notation should be the same as default input parameters. Here is an example of how those work:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: default-input-parameter-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:
    - - name: print-parameter
        template: parameter-printing
        arguments:
          parameters:
          - name: parameter
            value: replacement

  - name: parameter-printing
    inputs:
      parameters:
      - name: parameter
        value: default
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["echo {{inputs.parameters.parameter}}"]
```
This simply prints `replacement`. If the `arguments.parameters` field is removed, it prints `default`.

(Note: This usage is not well-documented. I think I actually discovered it by hoping it would work this way and being pleasantly surprised. I now use this all the time, so I would recommend adding this workflow or something similar as an example.)

My proposal is that the artifact behavior should behave the same. For instance, here would be the analogous workflow with a default input artifact:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: default-input-artifact-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:
    - - name: print-artifact
        template: artifact-printing
        arguments:
          artifacts:
          - name: artifact
            raw:
              data: |
                replacement contents

  - name: artifact-printing
    inputs:
      artifacts:
      - name: artifact
        path: /tmp/file
        raw:
          data: |
            default contents
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["cat /tmp/file"]
```

This template should just print `replacement contents`. However, it currently prints `default contents`, showing that the artifacts with contents specified in the template cannot be overridden in the same way that parameters can.

If the `inputs.artifacts.raw` field is removed, then it successfully prints `replacement contents`. It seems that the underlying logic just needs to be changed to first check if the artifact has been provided by the instantiation and use that definition if it has.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
