### ISSUE TITLE
Argo linter doesn't recognize global output parameters specified indirectly

### ISSUE THREAD

**Issue by samath117** [argoproj/argo-workflows#2057]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**Summary**:
When I set a global output parameter in a complicated way (that's "too smart" for Argo validation), then the linter complains when I use it (and I therefore can't run the workflow). The same problem also arises if I want to use a global output parameter within a WorkflowTemplate. However, if I hack it by passing the information through a default input parameter, I'm able to avoid the linter's detection and everything works as intended. I would like the option to avoid the linter's detection without this hack.

**Details**:

Consider the following workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-parameter-passing-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:
    - - name: pass-parameter
        template: global-parameter-passing
        arguments:
          parameters:
          - name: global-parameter-name
            value: key
          - name: global-parameter-value
            value: value
    - - name: print-parameter
        template: parameter-printing
        arguments:
          parameters:
          - name: parameter
            value: "{{workflow.outputs.parameters.key}}"

  - name: global-parameter-passing
    inputs:
      parameters:
      - name: global-parameter-name
      - name: global-parameter-value
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["exit 0"]
    outputs:
      parameters:
      - name: global-parameter
        value: "{{inputs.parameters.global-parameter-value}}"
        globalName: "{{inputs.parameters.global-parameter-name}}"

  - name: parameter-printing
    inputs:
      parameters:
      - name: parameter
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["echo {{inputs.parameters.parameter}}"]
```

This workflow should first create a global output parameter with name `key` and value `value`. Then it should just print `value`. However, Argo's linter is not able to figure this out:
```
FATA[0000] global-parameter-passing.yaml: templates.plan.steps[1].print-parameter failed to resolve {{workflow.outputs.parameters.key}}
```

It seems clear what's happening: "globalName: key" isn't directly in the workflow, so it gets concerned. However, there is also fix that really shouldn't work but does:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-parameter-passing-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:
    - - name: pass-parameter
        template: global-parameter-passing
        arguments:
          parameters:
          - name: global-parameter-name
            value: key
          - name: global-parameter-value
            value: value
    - - name: print-parameter
        template: parameter-printing

  - name: global-parameter-passing
    inputs:
      parameters:
      - name: global-parameter-name
      - name: global-parameter-value
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["exit 0"]
    outputs:
      parameters:
      - name: global-parameter
        value: "{{inputs.parameters.global-parameter-value}}"
        globalName: "{{inputs.parameters.global-parameter-name}}"

  - name: parameter-printing
    inputs:
      parameters:
      - name: parameter
        value: "{{workflow.outputs.parameters.key}}"
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["echo {{inputs.parameters.parameter}}"]
```
All I've changed is to move the problematic `{{workflow.outputs.parameters.key}}` into the printing template as a default input parameter, and then just not passed a replacement in the `print-parameter` instantiation. Something about this setup simply evades the linter, and it runs as expected:
```
print-parameter:        value
```

Of course, I wouldn't do this to a general template that I'd like to reuse. Instead, if I want to use `global-parameter-passing` to set a global output parameter, I have to add redundant single-step template "wrappers" simply in order to pass those parameters into an existing template and avoid getting caught on the linter. Moreover, I have to do this for every possible template that might want to use these global output parameters, increasing my template bloat considerably.

Templates like `global-parameter-passing` aren't the only situation where this arises. Any time I want to define a template in a WorkflowTemplate file but have it reference global output parameters, I have to apply the same default input parameter trick, because since they aren't part of a workflow, they aren't aware of previous steps that came before. This happens frequently because I use global output parameters to get information from steps that might not run.

How would I want this fixed? While the linter could be smarter, it's already quite slow as it is. I'd prefer if I could tell the linter to simply overlook global output parameter checking. I looked into the `--strict` flag in `argo submit`, but I can't find a way to turn it off (it's default on and isn't passed with a boolean...), if that would even solve the problem.

I'm using Argo v2.4.1.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
