### ISSUE TITLE
CLI watch and wait is not exiting if resource got deleted in resource template

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#2108]
Similar issue #2078 
Argo Cli `watch or wait` keeps hanging if  resource got deleted in the resource template 

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: pod-resource-wf
spec:
  entrypoint: pi-tmpl
  templates:
  - name: pi-tmpl
    resource:
      action: create
      setOwnerReference: true
      successCondition: status.succeeded > 0
      failureCondition: status.failed > 3
      manifest: |
        apiVersion: v1
        kind: Pod
        metadata:
          generateName: pi-pod-
        spec:
          containers:
          - name: pi
            image: "perl"
            command: ["sh", "-c", "sleep 10000"]
```
