### ISSUE TITLE
Read-only RBAC has the UI showing workflow as deleted when it is not

### ISSUE THREAD

**Issue by ddseapy** [argoproj/argo-workflows#2145]
Checklist:

 * [X ] I've included the version.
 * [X ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
**EDIT - This looks to be JUST a UI issue, and not a security concern**

When setting the RBAC for the server pod to the following, I am able to delete workflows from the archive, but not from the cluster.
```yaml
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflowtemplates
  - cronworkflows
  verbs:
  - get
  - list
  - watch
```
**What you expected to happen**:

I should get permission denied trying to delete the workflow from postgres

**How to reproduce it (as minimally and precisely as possible)**:

Set the rbac to what is listed above for the server.  Run a workflow.  Try to delete the workflow from the archive in the UI.  It will succeed even though it should fail.

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.5.0-rc7
- Kubernetes version : 1.16.4

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
