### ISSUE TITLE
Pods do not get deleted on success/failure

### ISSUE THREAD

**Issue by nirav24** [argoproj/argo-workflows#2173]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
I am trying to implement GC strategy to delete pods automatically after workflow is done. However, podsdon't get deleted. I've tried with all strategy options ([see](https://github.com/Duske/argo/blob/bd4750fbb9413eea8ced0ca642664f54fb5b3c47/examples/pod-gc-strategy.yaml#L15)), but result is the same.

**What you expected to happen**:

Workflows should be deleted after Success or failure.

**How to reproduce it (as minimally and precisely as possible)**:
Submit following workflow with argo CLI.

**Anything else we need to know?**:

`Workflow.yaml`

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: nirav-test-    # name of the workflow spec
spec:
  podGC:
    strategy: OnPodCompletion
  entrypoint: pod-gc-strategy          # invoke the whalesay template
  templates:
  - name: pod-gc-strategy
    steps:
    - - name: fail
        template: fail
      - name: succeed
        template: succeed

  - name: fail
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["exit 1"]

  - name: succeed
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["exit 0"]
```

**Environment**:
- Argo version:
```
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:52Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-10-15T12:11:03Z"
  compiler: gc
  gitCommit: 211047e9a1922595eaa3a1127ed365e9299a6c23
  gitTreeState: clean
  gitVersion: v1.14.8
  goVersion: go1.12.10
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-11-07T19:12:22Z"
  compiler: gc
  gitCommit: 56d89863d1033f9668ddd6e1c1aea81cd846ef88
  gitTreeState: clean
  gitVersion: v1.13.11-gke.14
  goVersion: go1.12.11b4
  major: "1"
  minor: 13+
  platform: linux/amd64
```
