### ISSUE TITLE
RetryStrategy not applying correctly

### ISSUE THREAD

**Issue by cscetbon** [argoproj/argo-workflows#2260]
**What happened**:

The following RetryStrategy does not work as expected 
```
retryStrategy:
  limit: 5
  retryOn: Always
  backoff:
    duration: 5m
    factor: 2
    maxDuration: 30m
```

I have a template called for a list of items :
```
...
    onExit: exit-handler
    parallelism: 2
...
    templates:
      - - name: generate-report
          templateRef:
            name: wt-generate-report
            template: generate-report
          arguments:
            parameters:
            - name: query
              value: "{{item}}"
          withItems:
          - q1
          - ...
          - q10
```
with **wt-generate-report** being
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wt-generate-report
spec:
  templates:
  - name: generate-report
    retryStrategy:
      limit: 5
      retryOn: Always
      backoff:
        duration: 5m
        factor: 2
        maxDuration: 30m
    inputs:
      parameters:
      - name: query
    container:
      ...
      args:
        - ...
        - --query-name
        - "{{inputs.parameters.query}}"
```
q8 fails after 2 min only but instead of restarting it, Argo calls the exit handler after q10 is done. It seems maxDuration applies to the whole workflow instead of the current container. There is not much information about that in the documentation and I think at least we should have the ability to limit the duration of the whole workflow but also the duration of each item. 

```
crawl-then-generate-report-rsc8r-167879159
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 15 Feb 2020 00:10:17 -0500
      Finished:     Sat, 15 Feb 2020 00:10:37 -0500
crawl-then-generate-report-rsc8r-2031518775
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 15 Feb 2020 00:10:17 -0500
      Finished:     Sat, 15 Feb 2020 00:10:37 -0500
crawl-then-generate-report-rsc8r-2179883348
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 15 Feb 2020 00:11:21 -0500
      Finished:     Sat, 15 Feb 2020 01:22:42 -0500
crawl-then-generate-report-rsc8r-2616921566
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 15 Feb 2020 00:10:40 -0500
      Finished:     Sat, 15 Feb 2020 00:10:59 -0500
crawl-then-generate-report-rsc8r-2659547343
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 15 Feb 2020 00:11:00 -0500
      Finished:     Sat, 15 Feb 2020 00:11:19 -0500
crawl-then-generate-report-rsc8r-2881338586
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 15 Feb 2020 00:11:02 -0500
      Finished:     Sat, 15 Feb 2020 00:11:28 -0500
crawl-then-generate-report-rsc8r-339585767
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 14 Feb 2020 23:30:09 -0500
      Finished:     Fri, 14 Feb 2020 23:30:24 -0500
crawl-then-generate-report-rsc8r-3636458821
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 15 Feb 2020 00:13:53 -0500
      Finished:     Sat, 15 Feb 2020 01:52:49 -0500
crawl-then-generate-report-rsc8r-3913657823
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 14 Feb 2020 23:30:32 -0500
      Finished:     Sat, 15 Feb 2020 00:00:11 -0500
crawl-then-generate-report-rsc8r-3915905737
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 15 Feb 2020 00:11:30 -0500
      Finished:     Sat, 15 Feb 2020 00:13:51 -0500
crawl-then-generate-report-rsc8r-3923119477
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 14 Feb 2020 23:30:09 -0500
      Finished:     Fri, 14 Feb 2020 23:59:21 -0500
crawl-then-generate-report-rsc8r-4017970170
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 14 Feb 2020 23:59:23 -0500
      Finished:     Sat, 15 Feb 2020 00:00:15 -0500
crawl-then-generate-report-rsc8r-4250406424
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 15 Feb 2020 00:10:39 -0500
      Finished:     Sat, 15 Feb 2020 00:10:58 -0500
crawl-then-generate-report-rsc8r-905616778
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 15 Feb 2020 02:02:51 -0500
      Finished:     Sat, 15 Feb 2020 02:03:02 -0500
```

**What you expected to happen**:
I would expect each container to be retried using the RetryStrategy but not the whole workflow.

**Anything else we need to know?**:
I think the documentation should be improved toi give more information about it. When it's applied, the scope it's applied to etc...

**Environment**:
- Argo version:
```
argo: vapiserverimpl+90a7931.dirty
  BuildDate: 2020-01-11T01:41:40Z
  GitCommit: 90a793136a0938ffe78e2b9ab84b5cd790dcd080
  GitTreeState: dirty
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-01-23T14:21:54Z"
  compiler: gc
  gitCommit: 59603c6e503c87169aea6106f57b9f242f64df89
  gitTreeState: clean
  gitVersion: v1.17.2
  goVersion: go1.13.6
  major: "1"
  minor: "17"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-11-13T11:11:50Z"
  compiler: gc
  gitCommit: 7015f71e75f670eb9e7ebd4b5749639d42e20079
  gitTreeState: clean
  gitVersion: v1.15.6
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: linux/amd64
```
