### ISSUE TITLE
Template metadata is not propagated when using templateRef

### ISSUE THREAD

**Issue by pclalv** [argoproj/argo-workflows#2265]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

A template's `metadata` does not get added to the metadata defined in its `templateRef` template.

**What you expected to happen**:

A template's `metadata` gets added to the metadata defined in its `templateRef` template.

**How to reproduce it (as minimally and precisely as possible)**:

1. `kubectl apply` the following resources:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: paul-example
  generateName: step-
  labels:
    consumer: paul
spec:
  templates:
    - name: main
      metadata:
        labels:
          consumer: paul
      parameters:
        - name: cpu
          value: "100m"
        - name: memory
          value: "128Mi"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["test"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: paul-example-pass-metadata
  labels:
    consumer: paul
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: run
        metadata:
          labels:
            another-label: foo
            consumer: paul
        templateRef:
          name: paul-example
          template: main
```
2. Observe that the pod doesn't end up with the label `another-label`:
```sh-session
$ kg workflow,workflowtemplate,pod -lconsumer=paul
NAME                                              AGE
workflow.argoproj.io/paul-example-pass-metadata   9s

NAME                                        AGE
workflowtemplate.argoproj.io/paul-example   9s

NAME                                        READY   STATUS      RESTARTS   AGE
pod/paul-example-pass-metadata-4161934669   0/2     Completed   0          10s

$ kg workflow,workflowtemplate,pod -lanother-label
No resources found in argo namespace.
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```yaml
# argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:23Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```yaml
# kubectl version -o yaml
clientVersion:
  buildDate: "2019-11-14T04:24:34Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.13
  major: "1"
  minor: "16"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-10-15T12:04:30Z"
  compiler: gc
  gitCommit: a8b52209ee172232b6db7a6e0ce2adc77458829f
  gitTreeState: clean
  gitVersion: v1.13.12
  goVersion: go1.11.13
  major: "1"
  minor: "13"
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
