### ISSUE TITLE
Argo server should start without configmap

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#2285]
**What happened**:
If the workflow-controller is running in a cluster scope, the user can submit the workflow from their namespace. The user wants to run the argo server in hosted/local mode for their namespace. They don't enable persistence and they don't have permission for Argo namespace. Argo server is throwing below error.
```
error: “FATA[0000] configmaps “workflow-controller-configmap” not found”
```

**What you expected to happen**:
Argo server can start without `workflow-controller-configmap`
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by heavytail** [comment]
Saw this bug again in 2.7.0
```
level=fatal msg="configmaps \"workflow-controller-configmap\" not found"
```
```
argo version
argo: v2.7.0
  BuildDate: 2020-03-31T23:35:53Z
  GitCommit: 4d1175eb68f6578ed5d599f877be9b4855d33ce9
  GitTreeState: clean
  GitTag: v2.7.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: windows/amd64
```
```
kubectl version -o yaml
clientVersion:
  buildDate: "2019-12-07T21:20:10Z"
  compiler: gc
  gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
  gitTreeState: clean
  gitVersion: v1.17.0
  goVersion: go1.13.4
  major: "1"
  minor: "17"
  platform: windows/amd64
serverVersion:
  buildDate: "2020-02-21T10:47:45Z"
  compiler: gc
  gitCommit: 20c697423de11d4d5d08c6832a513217ca11a6aa
  gitTreeState: clean
  gitVersion: v1.16.7
  goVersion: go1.13.6
  major: "1"
  minor: "16"
  platform: linux/amd64
```
