### ISSUE TITLE
CronWorkflow: workflow metadata

### ISSUE THREAD

**Issue by vh** [argoproj/argo-workflows#2395]
# Summary

Add the ability to specify workflow metadata (labels, annotations). 

# Motivation

I want to filter workflows by label.

```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "* * * * *"
  timezone: "America/Los_Angeles"
  # There is no way to specify workflow metadata (or I haven't found it)
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: docker/whalesay:latest
          command: [cowsay]
          args: ["🕓 hello world"]
```

# Proposal

```
workflowMetadata:
  labels:
    hello: world
workflowSpec:
  ...
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
