### ISSUE TITLE
Add support for alternate variable-reference syntax

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo-workflows#2430]
# Summary

(This would be a significant change, so I understand if it's not really feasible)

Argo currently supports syntax like this for referencing variables:
```
{{some.variable.reference}}
```

It would be a significant UX improvement for my team if we could use something other than `{{ }}` as the syntax.

# Motivation

I have two main motivations for asking.

First, my team uses Helm to publish & share utility `WorkflowTemplate` definitions, as well as to inject top-level inputs into `CronWorkflow` specs on deployment. Helm uses the same syntax for its own variable substitution, so you have to jump through some hoops to "hide" the Argo variables from the rendering engine. There are a few ways to get around it, but we've landed on:
```
{{ "{{some.variable.reference}}" }}
```
It's not the worst thing ever, but it's definitely not ideal. It's really easy to forget the double-bracketing, or misplace a bracket, or quote in the wrong place, etc. It also adds another layer of cognitive load to reading templates (is this a Helm variable, or an Argo variable?).

Second, whenever the YAML parser in `kubectl` / `helm` (and potentially `argo`, I can't remember) sees a leading `{` in a value, it assumes that the value is an object specified using JSON syntax. When the second character is another `{`, it fails parsing. This means that any stand-alone Argo variable reference has to be quoted, but references embedded in the middle of some other string don't need to be. This adds to all the other inconsistencies that come with writing YAML, as you end up with statements like:
```yaml
arguments:
  parameters:
    - name: input-one
      value: '{{some.bare.variable}}' # Very tempting to remove these quotes
    - name: input-two
      value: gs://{{some.prefixed.variable}}/
```
It gets even more "fun" when you mix it with our Helm hack:
```yaml
arguments:
  parameters:
    - name: input-one
      value: '{{ "{{some.bare.variable}}" }}' # Or {{ "{{some.bare.variable}}" | quote }}
    - name: input-two
      value: gs://{{ "{{some.prefixed.variable}}" }}/ # Or {{ "gs://{{some.prefixed.variable}}/" }}
```

None of these are show-stopping problems, but they do introduce a lot of small code-style decisions that bog us down / confuse newcomers to the code.

# Proposal

I'm not familiar enough with the codebase to have a deep proposal (but I'd be willing to dig in and implement this if there's interest!). I do see some high-level design questions that would need to be addressed first:
* Should the controller hard-code a second option for variable references? Or should the choice be exposed as config, so users can do whatever they want?
* If hard-coding a 2nd choice, what should it be?
   * `[[ ]]` would make Helm happy, but it'd have similar issues with the YAML parser.
   * `<< >>` and `(( ))` feel "safe", but I haven't thought about it too deeply.
* If exposing the choice as config, where should that config go?
   * Exposing it in the controller's config map feels least complex, but it could make reusing templates from different sources trickier (sorry I can't use your template, it uses `(())` but I'm running with `<<>>`)
   * Exposing it as an annotation on workflows / templates / cron workflows would help with the reusability, but it feels like that'd be a lot more complicated for the controller / server to deal with.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by danxmoran** [comment]
(Just thinking out loud): Instead of an annotation, could this be implemented using new `spec` fields? With default values of "{{" and "}}"

**Comment by smitthakkar96** [comment]
I would like to work on this if the maintainers agree to make this change. It looks really ugly when used with helm

**Comment by simster7** [comment]
I've given some thought to this and see some blockers before introducing this in the controller:

1. It seems like an abstraction violation for us to implement a solution in the controller for a problem which is really external to it (collisions with Helm).

1. I can foresee some issues with `WorkflowTemplates`. We agree that it's not a good idea to define the syntax on the controller-level, as it would be impossible to run Workflows with different syntaxes.

    However, I also see an issue in defining this in either a Workflow annotation or the Workflow Spec: if a Workflow references a single template withing an external `WorkflowTemplate` with a different syntax, how should it be resolved? We would have to consider the syntax preferences of the `WorkflowTemplate` and the `Workflow`.

    This seems _doable_, but in my opinion it would be more of a maintenance burden than it would be useful.

1. Most importantly perhaps is a reason pointed out by @jessesuen. We rely on the `{{...}}` syntax for a technical reason as well: since it is impossible to have a valid JSON with the `{{` token, we can exploit this to replace Argo variables by converting Argo objects to JSON, doing the replace, and converting back. This might not hold true for other tokens, such as `[[`.

From here I can see at least two paths forward:

1. Implement this as a convenience feature in a step outside of the controller, either as a utility arguments to `argo submit` (something like `argo submit --var-open="<<" --var-close=">>"`). However, this would only be useful when using `argo submit`.

2. Take an official position that we do not want to support this behavior and would leave it to our users to script around it. A user in Slack (@brabster) posted a promising workaround:

> I think I've found a neat solution specifically for the Helm usecase. Change the `{{` and `}}` to whatever values you want that don't conflict with anything and use a post-processor to sed them back
>
> eg. template
> ```
> inputs:
>   parameters:
>     - name: fetch-url
>     - name: local-dump-path
>       value: {{ .Values.foo }}
>  outputs:
>    parameters:
>      - name: local-dump-path
>        value: "{-inputs.parameters.local-dump-path-}"
>```
>
> then `helm install foobar helm-chart --post-renderer ./helm-chart/post-render-argo.sh`
>
> where `post-render-argo.sh` is
> ```
> #!/bin/bash
> set -e
> sed 's/{-/{{/g' | sed 's/-}/}}/g' <&0
> ```

**Comment by brabster** [comment]
I'm pretty happy with my workaround, not seen any issues so far. I have a more detailed walkthough up at https://tempered.works/posts/2020-05-23-helm-charts-for-argo-workflows with a linked Github example repo if helpful.

If you do decide to implement, on point (3) I think it would be reasonable to require new delimiters to not be valid JSON syntax and to expect users to ensure that is so.

**Comment by mac9416** [comment]
We've found that the initial reaction to ``{{`{{}}`}}`` is confusion. But after that, it's okay.

If we did find we needed it, I think the workaround would be sufficient.

**Comment by simster7** [comment]
Thanks guys, closing this issue.

**Comment by ryedin** [comment]
i know this is closed, however, there is a case that is not being covered (unless I've missed something in the docs somewhere that explains how to do this): the workflow of worklows pattern, where the inner workflow resource wants to define parameters that it manages. So Argo itself needs a way to escape double curly braces (like Helm supports via `{{ "{{" }}`. The Helm level problem is well understood and various degrees of ugly, but workable. 

Consider the following Argo workflow that spawns a child workflow that itself wants to manage parameters. In this example there is also the `taskName` parameter managed from the outer level to illustrate the difference:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-outer
spec:
  entrypoint: run
      
  templates:
  - name: run
    steps:
    - - name: spawn-a-workflow
         template: spawn-a-workflow
         arguments:
            parameters:
            - name: taskName
               value: "foo"

  - name: spawn-a-workflow
    inputs:
      parameters:
      - name: taskName
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          name: this-was-spawned
        spec:
          entrypoint: run

          templates:
          - name: run
            dag:
              tasks:
              - name: configure
                templateRef:
                  name: configuration-template
                  template: configure
              - name: update-build-id
                templateRef:
                  name: update-build-id
                  template: update-build-id
                dependencies: ['configure']
              - name: "{{inputs.parameters.taskName}}" # these are resolved from the outer level as "foo" just fine
                templateRef:
                  name: "{{inputs.parameters.taskName}}"
                  template: run
                arguments:
                  parameters:
                  - name: buildId
                    value: "{{tasks.update-build-id.outputs.parameters.buildId}}" # this level, however, we want this inner flow to be able to manage this parameter... but how???
                dependencies:
                - update-build-id

      successCondition: status.phase == Succeeded
      failureCondition: status.phase in (Failed, Error)
```

So our issue is that there is no known way that we can figure out to get argo to escape the curly braces in that buildId parameter such that they remain intact for the new `Workflow` resource that is being created to let it manage it.

On the entire Internet(tm), I've only found one person ask about how to do this in argo, here: https://stackoverflow.com/questions/56341558/how-to-escape-and-in-argo-workflow - and the only answer is clearly wrong (argo is not jinja)

Is there any way this is currently possible? There are some pretty gnarly dynamic code generation based things we're trying to do that this would make drastically easier if we had a path to escape these delimiters

**Comment by mac9416** [comment]
I don't think the StackOverflow post is _100%_ incorrect. I believe Jinja is used for some of the templating logic.

The only workaround that I can think of is _super_ hacky, but I think it'd work: store the template string you need as a parameter and then interpolate that as needed in the manifest.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-outer
spec:
  entrypoint: run
      
  templates:
  - name: run
    steps:
    - - name: spawn-a-workflow
        template: spawn-a-workflow
        arguments:
          parameters:
          - name: taskName
            value: "foo"
  - name: spawn-a-workflow
    inputs:
      parameters:
      - name: taskName
      - name: template
        value: "\"{{tasks.update-build-id.outputs.parameters.buildId}}\""
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          name: this-was-spawned
        spec:
          entrypoint: run

          templates:
          - name: run
            dag:
              tasks:
              - name: configure
                templateRef:
                  name: configuration-template
                  template: configure
              - name: update-build-id
                templateRef:
                  name: update-build-id
                  template: update-build-id
                dependencies: ['configure']
              - name: "{{inputs.parameters.taskName}}" # these are resolved from the outer level as "foo" just fine
                templateRef:
                  name: "{{inputs.parameters.taskName}}"
                  template: run
                arguments:
                  parameters:
                  - name: buildId
                    value: 
                dependencies:
                - update-build-id
      successCondition: status.phase == Succeeded
      failureCondition: status.phase in (Failed, Error)
```

I haven't tested it yet. But if I recall correctly, `inputs.paramters[].value` isn't processed for variable interpolation, so I think the template should be stored as a string literal.

**Comment by BhaRgav-MoRadiya** [comment]
> I haven't tested it yet. But if I recall correctly, `workflow.parameters[].value` isn't processed for variable interpolation, so I think the template should be stored as a string literal.

This does not seem to work.its replacing the variable and then tries to interpolate.so same issue.

**Comment by RoryDoherty** [comment]
@ryedin Did you ever figure out a way to escape Argo Workflow variables to pass them as literal strings?

**Comment by nicolas-vivot** [comment]
So many workaround depending on the different use cases that lead to either making managed resources dirty or increasing the complexity / configuration of external tools in the CI/CD tool chain.

I understand it might not be an easy change, but it's definitely a legit request. As an Argo user, i would expect to have the ability to fix it at the source instead of everywhere else in my system.

There is absolutely no way to avoid to have this delimiter hard-coded and instead have the ability to configure it during the installation, or on a configuration map?

**Comment by moriarity-da** [comment]
For those not wanting to use the sed post-renderer workaround posted above, you can add the argo wf variable reference as a value in your values.yaml file like below:

wf yaml:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: reconcile-approvals
  namespace: argo
spec:
  template:
    serviceAccountName: {{ .Values.argo.serviceAccount }}
  dependencies:
    - name: http-post-trigger
      eventSourceName: webhook
      eventName: reconcile-approvals
  triggers:
  - template:
      name: reconcile-approvals
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: reconcile-approvals-
              namespace: argo
            spec:
                entrypoint: main
                arguments:
                  parameters:
                  - name: message
                    value: reconciling approvals
                templates:
                  - name: main
                    inputs:
                      parameters:
                      - name: message
                    container:
                      image: "{{ .Values.containerRegistry }}/{{ .Values.argo.reconcileApprovals.image }}"
                      command: ["python", "main.py"]
                      args:
                      - --message
                      - '{{ .Values.argo.messageArgs }}'
                      ...
```

helm values.yaml:
```yaml
...
argo:
  messageArgs: '{{inputs.parameters.message}}'
...
```
