### ISSUE TITLE
Custom db schema for persistence tables

### ISSUE THREAD

**Issue by paguos** [argoproj/argo-workflows#2452]
# Summary

In the latest release of argo (v2.6.2 at the time of writting) it is not possible to define a schema when enabling persistence. I would like to have persistence stored in a schema different that `public`. 

# Motivation

Many applications or organizations use a database for multiple purposes. Having the ability to choose the schema where to store the information about argo would be useful. 

# Proposal

An extra parameter in the **workflow-controller-configmap** when persistence is enabled: 
```yaml
postgresql:
        host: localhost
        port: 5432
        database: postgres
        tableName: argo_workflows
        schema: argo # new attribute
        userNameSecret:
          name: argo-postgres-config
          key: username
        passwordSecret:
          name: argo-postgres-config
          key: password
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
