### ISSUE TITLE
Can't watch correctly a workflow submitted using --from cronwf/xxx

### ISSUE THREAD

**Issue by cscetbon** [argoproj/argo-workflows#2469]
**What happened**:
Can't submit and watch a cronworkflow as opposed to a regular workflow. I can submit then watch it but not both at once like a regular workflow.

**What you expected to happen**:
I would expect to be able to watch the workflow created from a cronworkflow the same way I can with a regular workflow.
So I would expect something like

```
$ argo submit -w --from cronwf/test-watch
...
STEP                                   PODNAME                       DURATION  MESSAGE
 ● cyril-tests-rfkx4 (cyril-template)
 └---● my-template (my-template)       cyril-tests-rfkx4-3188693807  3s
Name:                cyril-tests-rfkx4
Namespace:           reporting
ServiceAccount:      default
Status:              Succeeded
Created:             Tue Mar 17 23:05:48 -0400 (4 seconds ago)
Started:             Tue Mar 17 23:05:48 -0400 (4 seconds ago)
Finished:            Tue Mar 17 23:05:51 -0400 (1 second ago)
Duration:            3 seconds
```

**How to reproduce it (as minimally and precisely as possible)**:

```
$ k apply -f cronwf-test-watch.yaml
$ argo submit -w --from cronwf/test-watch
Name:                test-watch-hvq79
Namespace:           reporting
ServiceAccount:      default
Status:              Pending
Created:             Tue Mar 17 23:08:48 -0400 (now) <== stuck here until it succeeds.
test-watch-hvq79 Succeeded at 2020-03-17 23:08:51 -0400 EDT
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.6.3
  BuildDate: 2020-03-16T17:56:00Z
  GitCommit: 2e8ac609cba1ad3d69c765dea19bc58ea4b8a8c3
  GitTreeState: clean
  GitTag: v2.6.3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-02-13T18:08:14Z"
  compiler: gc
  gitCommit: 06ad960bfd03b39c8310aaf92d1e7c12ce618213
  gitTreeState: clean
  gitVersion: v1.17.3
  goVersion: go1.13.8
  major: "1"
  minor: "17"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-11-13T11:11:50Z"
  compiler: gc
  gitCommit: 7015f71e75f670eb9e7ebd4b5749639d42e20079
  gitTreeState: clean
  gitVersion: v1.15.6
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: linux/amd64
```

See [Archive 2.zip](https://github.com/argoproj/argo/files/4346763/Archive.2.zip) for the workflow and cronworkflow to use to test the issue

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@simster7 I'm pretty sure you won't see the updates to the _workflow_ by watching the _cron workflow_?

**Comment by simster7** [comment]
Will take a look

**Comment by simster7** [comment]
I'm unable to reproduce https://cl.ly/ecdae86ea6ad

Could you share your logs?

**Comment by cscetbon** [comment]
Which logs ?

**Comment by cscetbon** [comment]
@simster7 You can see the logs I sent to @sarabala1979 https://argoproj.slack.com/files/UGGQJKB6C/FV7T6GGHY/argo-wf-controlle.log. That was with another example but maybe you can see something there.

**Comment by cscetbon** [comment]
@simster7 I get `The media could not be loaded, either because the server or network failed or because the format is not supported.` when trying to see your picture/video. so you can submit and watch at the same time a workflow created from a cronwf ?

**Comment by simster7** [comment]
>  when trying to see your picture/video. so you can submit and watch at the same time a workflow created from a cronwf ?

Yes I'm able to submit and watch successfully.

I found this line in your logs:
```
time="2020-03-17T18:24:22Z" level=error msg="vendors-report-n4965 error in entry template execution: Max parallelism reached\ngithub.com/argoproj/argo/errors.New\n\t/go/src/github.com/argoproj/argo/errors/errors.go:49\ngithub.com/argoproj/argo/workflow/controller.init\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:91\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5222\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5217\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:190\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357" namespace=reporting workflow=vendors-report-n4965
```

Perhaps when you're submitting and watching, there is a max parallelism limit preventing the immediate execution of your workflow, which is causing this issue?

**Comment by cscetbon** [comment]
Perhaps but parallelism should impact the worklow not watching it

**Comment by cscetbon** [comment]
I'm also wondering how parallelism can be a problem as soon as the workflow starts ? There should be some steps running to reach that parallelism number.

**Comment by cscetbon** [comment]
@simster7, is that bug fixed in the last release ?

**Comment by cscetbon** [comment]
Still the same issue on 2.8

**Comment by sarabala1979** [comment]
@cscetbon I am not able to reproduce it.  can you provide your example which will reproduce this issue?
Here my example.
```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "* * * * *"
  timezone: "America/Los_Angeles"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    arguments:
      parameters:
        - name: seq-list
          value: |
            ["a","b","c","d"]
        - name: parallel-list
          value: |
            [1,2,3,4]

    entrypoint: parallel-worker
    templates:
      - name: parallel-worker
        inputs:
          parameters:
            - name: seq-list
            - name: parallel-list
        steps:
          - - name: parallel-worker
              template: seq-worker
              arguments:
                parameters:
                  - name: seq-list
                    value: "{{inputs.parameters.seq-list}}"
                  - name: parallel-id
                    value: "{{item}}"
              withParam: "{{inputs.parameters.parallel-list}}"

      - name: seq-worker
        parallelism: 1
        inputs:
          parameters:
            - name: seq-list
            - name: parallel-id
        steps:
          - - name: seq-step
              template: one-job
              arguments:
                parameters:
                  - name: parallel-id
                    value: "{{inputs.parameters.parallel-id}}"
                  - name: seq-id
                    value: "{{item}}"
              withParam: "{{inputs.parameters.seq-list}}"

      - name: one-job
        inputs:
          parameters:
            - name: seq-id
            - name: parallel-id
        container:
          image: alpine
          command: ['/bin/sh', '-c']
          args: ["echo {{inputs.parameters.parallel-id}} {{inputs.parameters.seq-id}}; sleep 10"]
```
