### ISSUE TITLE
Conditional artifact/parameter logic

### ISSUE THREAD

**Issue by samath117** [argoproj/argo-workflows#2496]
# Summary

In some steps/dag templates, there is a `when` conditional specifying which of two (or more) steps should run. In this situation, though, there is currently no way to export an artifact or parameter from "the step that ran" in that set, or any other condition.

# Motivation

Suppose you want to handle recursion using an Argo workflow with an output artifact. Here's an example of exactly this logic, slightly modified from the [recursive coinflip](https://github.com/argoproj/argo/blob/master/examples/coinflip-recursive.yaml):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: coinflip-recursive-
spec:
  entrypoint: coinflip
  templates:
  - name: coinflip
    steps:
    - - name: flip-coin
        template: flip-coin
    - - name: heads
        template: heads
        when: "{{steps.flip-coin.outputs.result}} == heads"
      - name: tails
        template: coinflip
        when: "{{steps.flip-coin.outputs.result}} == tails"
    outputs:
      artifacts:
      - name: heads-result
        from: ????

  - name: flip-coin
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)
  - name: heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\" > /result.txt"]
    outputs:
      artifacts:
      - name: heads-result
        path: /result.txt
```

In this example, the `heads` template has an output artifact that we would like to pass to the parent, `coinflip`. However, we can't use the rigid way that parents can inherit artifacts from their children, since they don't know which one of their children will be sending the appropriate artifact. If `heads` doesn't run, then it should recursively look for the artifact in `tails`, which will then apply the same logic. However, Argo does not currently offer any way to specify such logic.

One "hack" that works in this situation is to use global artifacts. Just export `heads-result` as a global artifact and have `coinflip` export that global artifact. However, this solution has issues:
1. If multiple `coinflip` instances are running simultaneously, they could end up conflicting and passing the wrong information.
2. It doesn't work at all for WorkflowTemplates, because they [don't admit](https://github.com/argoproj/argo/issues/2057) references like `"{{workflow.outputs.artifacts.heads-result}}"`
3. There is still [an outstanding bug](https://github.com/argoproj/argo/issues/1902) about overwriting parameters from nested templates.

# Proposal

This is the part I'm least sure about. Ideally, the conditional logic would be as general as possible. A couple of options:

1) Create another field like `parentName` similar to `globalName` to automatically export (overwriting if necessary) artifacts/parameters one level higher, but not to the entire workflow. That way, you would just need to add `parentName: heads-result` to the `heads` template. This would be cleanest in this circumstance and others, but also obscures where the output artifacts came from a bit. Maybe you would still have to set up a receiver like `- name: heads-result`...

2) Add govaluate-type logic within `from` fields for artifacts and `valueFrom.parameter` fields for parameters. In the above, this could look like:
```yaml
    outputs:
      artifacts:
      - name: heads-result
        from: "{{steps.heads.outputs.artifacts.heads-result}} if {{steps.flip-coin.outputs.result}} == heads else {{steps.tails.outputs.artifacts.heads-result}}"
```

3) A more structured/formalized version of (2).

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
