### ISSUE TITLE
Container sequences

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#2551]
# Summary

It should be possible to run multiple steps within the same pod ~using ephemeral containers~.

# Motivation

* Avoids the need to pass artifacts around.

# Proposal

TODO

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by tvalasek** [comment]
Would that work for: Avoids the need to pass output parameters around?

**Comment by simster7** [comment]
Yes! That's the main advantage

**Comment by simster7** [comment]
The main advantage of this feature would be to avoid passing artifacts using an external provider between different tasks in a Workflow, when the intermediary artifacts can be discarded after use. 

To achieve this, we would make use of [ephemeral containers in K8s](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/). The idea is that the controller would create and remove ephemeral containers in a single pod, allowing them to all use the same filesystem

I envision something like a steps template:

```yaml
- name: sequence
  sequence:
    - - name: create-artifact
        template: gen-data
    - - name: consume-artifact
        template: process-data

- name: gen-data
  container:
    ...
  outputs:
    artifacts:
      file: ...

- name: process-data
  inputs:
    artifacts:
      file: ...
  container:
    ...
```

Ideally, users would simply be able to rename `steps` to `sequence` in order to leverage this feature. The controller would only need the existing `inputs`/`outputs` already found in templates to achieve this.

**NOTE:** This feature is still only an idea: we're about to start creating a PoC to see just how viable it is. Nothing is set in stone (not even the name `sequence`) and I expect this to change as we learn more about the limitations/features of this. All feedback is welcome at this time!
