### ISSUE TITLE
Environment variables doesn't display when exec into the pod

### ISSUE THREAD

**Issue by ptran32** [argoproj/argo-workflows#2588]
Checklist:

 * [X] I've included the version.
 * [X] I've included reproduction steps.
 * [X] I've included the workflow YAML.
 * [X] I've included the logs.
 
**What happened**:

Environment variables defined in the yaml file doesn't display when I exec into a pod.
`kubectl exec -it test-jwtqs bash`
`env`

The output doesn't show the 2 variables defined below:
- FOO
- BAR

The pod has been deployed with the following command and the content below:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
spec:
  entrypoint: test
  templates:
  - name: test
    container:
      image: alpine
      command: [sleep]
      args: ["300"]

      env:
      - name: FOO
        value: "Hello"
      - name: BAR
        value: "Goodbye"
```

Command used to deploy: 
`argo submit templates/file.yaml`

**What you expected to happen**:

I expect to see my variables FOO and BAR using "env" command

**How to reproduce it (as minimally and precisely as possible)**:
Create a yaml file with this content below:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
spec:
  entrypoint: test
  templates:
  - name: test
    container:
      image: alpine
      command: [sleep]
      args: ["300"]

      env:
      - name: FOO
        value: "Hello"
      - name: BAR
        value: "Goodbye"
```

`argo submit <FILENAME>.yaml`

**Anything else we need to know?**:
When I change the yaml file, remove the line args and replace the command argument like below:
`command: [env]` , now I can see the 2 variables in the output.

I also noticed that apparently all environment variables from pod to pods are replicated everywhere. 
After deleting the three Argo CRD, I could start a new pod without these replicated env variables:
- cronworkflows.argoproj.io      
- workflows.argoproj.io           
- workflowtemplates.argoproj.io

**Environment**:
- Argo version:
```
argo: v2.6.3
  BuildDate: 2020-03-16T17:56:00Z
  GitCommit: 2e8ac609cba1ad3d69c765dea19bc58ea4b8a8c3
  GitTreeState: clean
  GitTag: v2.6.3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-10-15T19:16:51Z"
  compiler: gc
  gitCommit: 20c265fef0741dd71a66480e35bd69f18351daea
  gitTreeState: clean
  gitVersion: v1.15.5
  goVersion: go1.12.10
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-25T14:50:46Z"
  compiler: gc
  gitCommit: 9e991415386e4cf155a24b1da15becaa390438d8
  gitTreeState: clean
  gitVersion: v1.18.0
  goVersion: go1.13.8
  major: "1"
  minor: "18"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get test-jwtqs
Name:                test-jwtqs
Namespace:           toto
ServiceAccount:      default
Status:              Succeeded
Created:             Sat Apr 04 01:18:55 -0400 (9 minutes ago)
Started:             Sat Apr 04 01:18:55 -0400 (9 minutes ago)
Finished:            Sat Apr 04 01:23:58 -0400 (4 minutes ago)
Duration:            5 minutes 3 seconds

STEP                  PODNAME     DURATION  MESSAGE
 ✔ test-jwtqs (test)  test-jwtqs  5m
```
- executor logs:
```
Don't have any logs here, because pods start successfully
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)

time="2020-04-04T05:18:59Z" level=info msg="Processing workflow" namespace=toto workflow=test-jwtqs
time="2020-04-04T05:20:15Z" level=info msg="Alloc=4644 TotalAlloc=240181 Sys=70080 NumGC=330 Goroutines=101"
time="2020-04-04T05:20:52Z" level=info msg="Processing workflow" namespace=toto workflow=hello-world-vhg8z
time="2020-04-04T05:20:52Z" level=info msg="Updating node &NodeStatus{ID:hello-world-vhg8z,Name:hello-world-vhg8z,DisplayName:hello-world-vhg8z,Type:Pod,TemplateName:whalesay,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2020-04-04 05:15:50 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} status Running -> Succeeded"
time="2020-04-04T05:20:52Z" level=info msg="Updated phase Running -> Succeeded" namespace=toto workflow=hello-world-vhg8z
time="2020-04-04T05:20:52Z" level=info msg="Marking workflow completed" namespace=toto workflow=hello-world-vhg8z
time="2020-04-04T05:20:52Z" level=info msg="Checking daemoned children of " namespace=toto workflow=hello-world-vhg8z
time="2020-04-04T05:20:52Z" level=info msg="Workflow update successful" namespace=toto phase=Succeeded resourceVersion=93312 workflow=hello-world-vhg8z
time="2020-04-04T05:20:52Z" level=info msg="Processing workflow" namespace=toto workflow=test-jwtqs
time="2020-04-04T05:20:53Z" level=info msg="Labeled pod toto/hello-world-vhg8z completed"
time="2020-04-04T05:22:45Z" level=info msg="Processing workflow" namespace=toto workflow=test-gkqn2
time="2020-04-04T05:22:45Z" level=info msg="Updating node &NodeStatus{ID:test-gkqn2,Name:test-gkqn2,DisplayName:test-gkqn2,Type:Pod,TemplateName:test,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2020-04-04 05:17:41 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} status Running -> Succeeded"
time="2020-04-04T05:22:45Z" level=info msg="Updated phase Running -> Succeeded" namespace=toto workflow=test-gkqn2
time="2020-04-04T05:22:45Z" level=info msg="Marking workflow completed" namespace=toto workflow=test-gkqn2
time="2020-04-04T05:22:45Z" level=info msg="Checking daemoned children of " namespace=toto workflow=test-gkqn2
time="2020-04-04T05:22:45Z" level=info msg="Workflow update successful" namespace=toto phase=Succeeded resourceVersion=93558 workflow=test-gkqn2
time="2020-04-04T05:22:46Z" level=info msg="Labeled pod toto/test-gkqn2 completed"
time="2020-04-04T05:23:58Z" level=info msg="Processing workflow" namespace=toto workflow=test-jwtqs
time="2020-04-04T05:23:58Z" level=info msg="Updating node &NodeStatus{ID:test-jwtqs,Name:test-jwtqs,DisplayName:test-jwtqs,Type:Pod,TemplateName:test,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2020-04-04 05:18:55 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} status Running -> Succeeded"
time="2020-04-04T05:23:58Z" level=info msg="Updated phase Running -> Succeeded" namespace=toto workflow=test-jwtqs
time="2020-04-04T05:23:58Z" level=info msg="Marking workflow completed" namespace=toto workflow=test-jwtqs
time="2020-04-04T05:23:58Z" level=info msg="Checking daemoned children of " namespace=toto workflow=test-jwtqs
time="2020-04-04T05:23:58Z" level=info msg="Workflow update successful" namespace=toto phase=Succeeded resourceVersion=93734 workflow=test-jwtqs
time="2020-04-04T05:23:59Z" level=info msg="Labeled pod toto/test-jwtqs completed"
```

**Logs**

```
argo get test-jwtqs
argo get test-jwtqs                                             (⎈ minikube:toto) 2.8.0
Name:                test-jwtqs
Namespace:           toto
ServiceAccount:      default
Status:              Succeeded
Created:             Sat Apr 04 01:18:55 -0400 (11 minutes ago)
Started:             Sat Apr 04 01:18:55 -0400 (11 minutes ago)
Finished:            Sat Apr 04 01:23:58 -0400 (6 minutes ago)
Duration:            5 minutes 3 seconds

STEP                  PODNAME     DURATION  MESSAGE
 ✔ test-jwtqs (test)  test-jwtqs  5m

```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
