### ISSUE TITLE
onExit step gets stuck if the workflow exceeds activeDeadlineSeconds

### ISSUE THREAD

**Issue by markterm** [argoproj/argo-workflows#2603]
Checklist:

 * [X] I've included the version.
 * [X] I've included reproduction steps.
 * [X] I've included the workflow YAML.
 * [] I've included the logs.
 
**What happened**:

onExit step gets stuck if the workflow exceed the deadline, and workflow stays in 'Running' state'

**What you expected to happen**:

either onExit step executes or it doesn't.

**How to reproduce it (as minimally and precisely as possible)**:

Submit this workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: exit-handlers
spec:
  entrypoint: intentional-fail
  activeDeadlineSeconds: 1
  onExit: exit-handler
  templates:
  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]
  - name: exit-handler
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo send e-mail: {{workflow.name}} {{workflow.status}}."]
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-05T16:54:35Z"
  compiler: gc
  gitCommit: f6278300bebbb750328ac16ee6dd3aa7d3549568
  gitTreeState: clean
  gitVersion: v1.15.2
  goVersion: go1.12.7
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-09-18T14:39:02Z"
  compiler: gc
  gitCommit: 8fca2ec50a6133511b771a11559e24191b1aa2b4
  gitTreeState: clean
  gitVersion: v1.14.7
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:

```
Name:                exit-handlers
Namespace:           staging
ServiceAccount:      default
Status:              Running
Created:             Mon Apr 06 15:11:12 +0100 (1 hour ago)
Started:             Mon Apr 06 15:11:12 +0100 (1 hour ago)
Duration:            1 hour 21 minutes

STEP                                    PODNAME                   DURATION  MESSAGE
 ⚠ exit-handlers (intentional-fail)     exit-handlers             0s        Pod "exit-handlers" is invalid: spec.activeDeadlineSeconds: Invalid value: 0: must be between 1 and 2147483647, inclusive

 ◷ exit-handlers.onExit (exit-handler)  exit-handlers-1117225324  1h
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
