### ISSUE TITLE
Workflows referencing workflow parameters cannot be used as WorkflowTemplates

### ISSUE THREAD

**Issue by salanki** [argoproj/argo-workflows#2634]
Checklist:

 * [X] I've included the version.
 * [X] I've included reproduction steps.
 * [X] I've included the workflow YAML.
 * [X] I've included the logs.
 
**What happened**:
Submitting a Workflow as a WorkflowTemplate that references workflow parameters fail.

**What you expected to happen**:
Per https://github.com/argoproj/argo/blob/master/docs/workflow-templates.md#workflowtemplate-spec, any `Workflow` should be able to be used as a `WorkflowTemplate`. 

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ argo template create workflow-template.yaml
2020/04/07 21:47:52 Failed to create workflow template: templates.whalesay templates.whalesay: failed to resolve {{workflow.parameters.message}}
```
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-template
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: hello world
    - name: name
      value: Peter

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
      - name: name
    container:
      name: main
      image: 'docker/whalesay:latest'
      command:
      - cowsay
      args:
      - "{{workflow.parameters.message}} from {{workflow.parameters.name}}"

```

What also surprises me is that submitting this WorkflowTemplate works as expected:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-template
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: hello world
    - name: name
      value: Peter

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
      - name: name
    container:
      name: main
      image: 'docker/whalesay:latest'
      command:
      - cowsay
      args:
      - "{{inputs.parameters.message}} from {{inputs.parameters.name}}"
```
```bashs
$ argo submit --from=workflowtemplate/test-template
$ argo logs test-template-w2wdv
test-template-w2wdv:  ________________________
test-template-w2wdv: < hello world from Peter >
test-template-w2wdv:  ------------------------
```

Is it always intended that the WorkflowTemplate level parameters are automatically supplied as input parameters to the entrypoint?

**Environment**:
- Argo version:
```
argo: v2.7.1
  BuildDate: 2020-04-07T16:40:24Z
  GitCommit: 2a3f59c10ae260a460b6ad97a0cadd8667d4b488
  GitTreeState: clean
  GitTag: v2.7.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
