### ISSUE TITLE
WorkflowTemplate reports invalid spec:  template '' undefined

### ISSUE THREAD

**Issue by ericmeadows** [argoproj/argo-workflows#2727]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
Attempted to simplify single-file Workflow by using WorkflowTemplates, and although the tasks completes successfully, it reports as failed every time, with the following value occupying `Message`:
```
invalid spec: templates.testing-relative-calls.steps[0].git-initial-status.template '' undefined
```

**What you expected to happen**:
The separated workflow just works.

**How to reproduce it (as minimally and precisely as possible)**:
Run `argo submit <filename>` on the yaml, and watch it hang.

**Anything else we need to know?**:
- **testing-relative-calls.yaml**
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: testing-relative-calls
  namespace: argo-events
spec:
  entrypoint: github-pending
  onExit: exit-handler
  arguments: []
    # <<REMOVED FOR SANITY>>
  volumes: []
  templates:
  - name: github-pending
    steps:
    - - name: git-initial-status
        templateRef:
          name: github
          template: report-github-status
        arguments:
          parameters:
          - name: state
            value: "pending"
  - name: exit-handler
    steps:
    - - name: successful
        templateRef:
          name: github
          template: report-github-status
        arguments:
          parameters:
          - name: state
            value: "success"
        when: "{{workflow.status}} == Succeeded"
      - name: failure
        templateRef:
          name: github
          template: report-github-status
        arguments:
          parameters:
          - name: state
            value: "failure"
        when: "{{workflow.status}} != Succeeded"
```
- **report-github-status.yaml**
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: github
  namespace: argo-events
spec:
  templates:
  - name: report-github-status
    inputs:
      parameters:
      - name: state
      - name: build-base-uri
        value: "{{workflow.parameters.build-base-uri}}"
      - name: git-commit-sha
        value: "{{workflow.parameters.git-commit-sha}}"
      - name: workflow-name
        value: "{{workflow.name}}"
      - name: github-repo-statuses-base-uri
        value: "{{workflow.parameters.github-repo-statuses-base-uri}}"
      - name: github-token-secret-name
        value: "{{workflow.parameters.github-token-secret-name}}"
      - name: github-token-secret-key
        value: "{{workflow.parameters.github-token-secret-key}}"
    script:
      image: ellerbrock/alpine-bash-curl-ssl:latest
      command: [bash]
      env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: "{{inputs.parameters.github-token-secret-name}}"
            key: "{{inputs.parameters.github-token-secret-key}}"
      source: |
        case {{inputs.parameters.state}} in
          success)
            description="The build was successful!"
            ;;
          failed)
            description="The build failed"
            ;;
          *)
            description="The build is running"
            ;;
        esac
        read -r -d '' curl_data << EOM
        {
            "state": "{{inputs.parameters.state}}",
            "target_url": "{{inputs.parameters.build-base-uri}}/{{inputs.parameters.workflow-name}}",
            "description": "$description",
            "context": "ci-cd/argo-workflows"
        }
        EOM
        set -x
        curl \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          {{inputs.parameters.github-repo-statuses-base-uri}}/{{inputs.parameters.git-commit-sha}} \
          -d "$curl_data"
```

**Environment**:
- Argo version:
```
argo: vv2.7.4+50b209c.dirty
  BuildDate: 2020-04-16T16:28:14Z
  GitCommit: 50b209ca14c056fb470ebb8329e255304dd5be90
  GitTreeState: dirty
  GitTag: v2.7.4
  GoVersion: go1.13
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-12-11T12:42:56Z"
  compiler: gc
  gitCommit: 6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4
  gitTreeState: clean
  gitVersion: v1.15.7
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-18T22:49:35Z"
  compiler: gc
  gitCommit: aa93664bafe74f3c051e021b27a64e28ac34ab40
  gitTreeState: clean
  gitVersion: v1.15.11-gke.1
  goVersion: go1.12.17b4
  major: "1"
  minor: 15+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                testing-relative-calls
Namespace:           argo-events
ServiceAccount:      SANITIZED
Status:              Running
Message:             invalid spec: templates.testing-relative-calls.steps[0].git-initial-status.template '' undefined
Created:             Thu Apr 16 16:31:23 -0400 (13 minutes ago)
Started:             Thu Apr 16 16:31:23 -0400 (13 minutes ago)
Finished:            Thu Apr 16 16:31:23 -0400 (13 minutes ago)
Duration:            0 seconds
Parameters:       [] # SANITIZED

STEP                                                      TEMPLATE                             PODNAME                                                           DURATION  MESSAGE
 ● testing-relative-calls                                 git-initial-status                                                                              
 └---◷ git-initial-status                                 github/report-github-status          testing-relative-calls-3382379192  13m    
```
- executor logs:
```
Completed pods, not failed!
```
- workflow-controller logs:
```
W0416 20:51:57.549050       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20191225075139-73fd2ddc9180/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 16172178 (16175377)
time="2020-04-16T20:52:09Z" level=info msg="Alloc=6574 TotalAlloc=111353 Sys=71360 NumGC=85 Goroutines=101"
time="2020-04-16T20:53:17Z" level=info msg="Processing workflow" namespace=argo-events workflow=testing-relative-calls
time="2020-04-16T20:53:17Z" level=info msg="Updated phase  -> Running" namespace=argo-events workflow=testing-relative-calls
time="2020-04-16T20:53:17Z" level=info msg="Steps node {testing-relative-calls testing-relative-calls testing-relative-calls Steps github-pending nil    Running   2020-04-16 20:53:17.28125219 +0000 UTC 0001-01-01 00:00:00 +0000 UTC   <nil> nil nil [] []} initialized Running" namespace=argo-events workflow=testing-relative-calls
time="2020-04-16T20:53:17Z" level=info msg="StepGroup node {testing-relative-calls-4000565252 testing-relative-calls[0] [0] StepGroup github-pending nil    Running testing-relative-calls  2020-04-16 20:53:17.281321122 +0000 UTC 0001-01-01 00:00:00 +0000 UTC   <nil> nil nil [] []} initialized Running" namespace=argo-events workflow=testing-relative-calls
time="2020-04-16T20:53:17Z" level=info msg="Pod node {testing-relative-calls-3382379192 testing-relative-calls[0].git-initial-status git-initial-status Pod  &TemplateRef{Name:github,Template:report-github-status,RuntimeResolution:false,}    Pending testing-relative-calls  2020-04-16 20:53:17.281776102 +0000 UTC 0001-01-01 00:00:00 +0000 UTC   <nil> nil nil [] []} initialized Pending" namespace=argo-events workflow=testing-relative-calls
time="2020-04-16T20:53:17Z" level=info msg="Created pod: testing-relative-calls[0].git-initial-status (testing-relative-calls-3382379192)" namespace=argo-events workflow=testing-relative-calls
time="2020-04-16T20:53:17Z" level=info msg="Workflow step group node &NodeStatus{ID:testing-relative-calls-4000565252,Name:testing-relative-calls[0],DisplayName:[0],Type:StepGroup,TemplateName:github-pending,TemplateRef:nil,Phase:Running,BoundaryID:testing-relative-calls,Message:,StartedAt:2020-04-16 20:53:17.281321122 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[testing-relative-calls-3382379192],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} not yet completed" namespace=argo-events workflow=testing-relative-calls
time="2020-04-16T20:53:17Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"testing-relative-calls\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=argo-events workflow=testing-relative-calls
time="2020-04-16T20:53:17Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=argo-events workflow=testing-relative-calls
time="2020-04-16T20:53:17Z" level=info msg="Update retry attempt 1 successful" namespace=argo-events workflow=testing-relative-calls
time="2020-04-16T20:53:17Z" level=info msg="Workflow update successful" namespace=argo-events phase=Running resourceVersion=16176791 workflow=testing-relative-calls
```

**Logs**

argo get <workflowname>
```
Name:                testing-relative-calls
Namespace:           argo-events
ServiceAccount:      SANITIZED
Status:              Running
Message:             invalid spec: templates.github-pending.steps[0].git-initial-status.template '' undefined
Created:             Thu Apr 16 16:53:17 -0400 (3 minutes ago)
Started:             Thu Apr 16 16:53:17 -0400 (3 minutes ago)
Finished:            Thu Apr 16 16:53:17 -0400 (3 minutes ago)
Duration:            0 seconds
Parameters:          SANITIZED

STEP                                                      TEMPLATE                             PODNAME                            DURATION  MESSAGE
 ● testing-relative-calls                                 github-pending                                                                              
 └---◷ github-pending                                     github/report-github-status          testing-relative-calls-3382379192  3m
```
NO FAILED PODS

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
