### ISSUE TITLE
Swagger giving wrong Kubernetes definitions.

### ISSUE THREAD

**Issue by cburbridge** [argoproj/argo-workflows#2888]
**What happened**:

The swagger definition for the Argo API includes Kubernetes  definitions such  as `io.k8s.api.core.v1.Volume` and ``io.k8s.api.core.v1.Container`. Some definitions don't match those from Kubernetes, e.g:

Argo defines:

```
    "io.k8s.api.core.v1.SecretKeySelector": {
      "description": "SecretKeySelector selects a key of a Secret.",
      "type": "object",
      "properties": {
        "key": {
          "description": "The key of the secret to select from.  Must be a valid secret key.",
          "type": "string"
        },
        "localObjectReference": {
          "description": "The name of the secret in the pod's namespace to select from.",
          "$ref": "#/definitions/io.k8s.api.core.v1.LocalObjectReference"
        },
        "optional": {
          "type": "boolean",
          "format": "boolean",
          "title": "Specify whether the Secret or its key must be defined\n+optional"
        }
      }
    },
```

whereas Kubernetes (1.14.9) defines:

```
  "io.k8s.api.core.v1.SecretKeySelector": {
      "description": "SecretKeySelector selects a key of a Secret.",
      "properties": {
        "key": {
          "description": "The key of the secret to select from.  Must be a valid secret key.",
          "type": "string"
        },
        "name": {
          "description": "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
          "type": "string"
        },
        "optional": {
          "description": "Specify whether the Secret or its key must be defined",
          "type": "boolean"
        }
      },
      "required": [
        "key"
      ],
      "type": "object"
    },
```

This means that following the Argo supplied definition with the "localObjectReference" field causes workflows submitted via the Argo REST API to fail. Following the Kubernetes 1.14.9 supplied API sepc works fine.

The same for `io.k8s.api.core.v1.Volume`, where a `volumeSource` attribute features in the Argo definition but not Kubernetes.

**What you expected to happen:**

The Kubernetes definitions to be supplied by Kubernetes, not via the Argo spec. This was the case in Argo release 2.3.

**Environment:**

Argo version:
```
argo: v2.7.5
  BuildDate: 2020-04-21T00:55:01Z
  GitCommit: ede163e1af83cfce29b519038be8127664421329
  GitTreeState: clean
  GitTag: v2.7.5
  GoVersion: go1.13
  Compiler: gc
  Platform: linux/amd64

```
Kubernetes version :
```
clientVersion:
  buildDate: "2020-02-11T18:14:22Z"
  compiler: gc
  gitCommit: 06ad960bfd03b39c8310aaf92d1e7c12ce618213
  gitTreeState: clean
  gitVersion: v1.17.3
  goVersion: go1.13.6
  major: "1"
  minor: "17"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-02-07T01:31:02Z"
  compiler: gc
  gitCommit: 502bfb383169b124d87848f89e17a04b9fc1f6f0
  gitTreeState: clean
  gitVersion: v1.14.9-eks-502bfb
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```
---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
