### ISSUE TITLE
Support Json list on WithSequence 

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#3046]
# Summary
`WithParam` will take JSON array and generate parallel steps for execution.  `WithSequence` should support the same.
There is a workaround to achieve the sequence execution using `parallelism`

```yaml
  - name: loop-param-result-example
    parallelism: 1
    steps:
    - - name: generate
        template: gen-number-list
    - - name: sleep
        template: sleep-n-sec
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"

```

What change you think needs making.

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
