### ISSUE TITLE
Support onRetry handler

### ISSUE THREAD

**Issue by tmshn** [argoproj/argo-workflows#3067]
# Summary

Introducing handler mechanism which is called after a node exits but before sleep for next retry.

# Motivation

`onExit` callback handler for DAGTask is quite useful, but it lacks an ability to do stuffs between each retry attempts.

`onRetry` handler can be used for say

- Notification to Slack (especially for long running jobs)
- Reporting status to external system
- Logging (especially when application crashes without being able to handle exception)

# Proposal

`retryStrategy` is the field for `template`, so adding new field `onRetry` to them seems good option.
As additional suggestion, `onExit` handler can be added to `template` to align UX (if there's no `RetryStrategy`, it will be connected directry to each physical node, and if there's `RetryStrategy`, connected to `Retry` node)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
How about something like this mimic this behavior? Note: I drafted this without testing, might need some modifications to work.

```yaml

template: on-retry-steps
retryStrategy:
  limit: 5
steps:
  - - name: flakey
      template: flakey
  - - name: send-slack
      when: "{{steps.flakey.status}} == Failed"
      template: send-slack
```

**Comment by tmshn** [comment]
Thank you for your suggestion @simster7 !

Actually our workaround is something quite similar to yours:

```yaml
retryStrategy:
  limit: 5
steps:
  - - name: flakey
      template: flakey
      # ↓ Need to proceed to the 'send-slack' step
      continueOn:
        failed: true
  - - name: send-slack
      template: send-slack
      when: "{{steps.flakey.status}} != Succeeded"
  # ↓ Final status of this step should be of 'flasky' step, rather than of 'send-slack'.
  - - name: signal-fail
      template: signal-fail
      when: "{{steps.flakey.status}} != Succeeded"
```

But obviously this kind of workaround increases the complexity of the dag, resulting harder to understand the execution graph.
