### ISSUE TITLE
Prometheus metrics port not taken into account

### ISSUE THREAD

**Issue by ptemmer** [argoproj/argo-workflows#3093]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
No matter the port number configured for the prometheus metrics server in the workflow configmap, the workflow-controller-metrics targetPort is always set to 9090.

**What you expected to happen**:
workflow-controller-metrics service should reflect the configured metrics port, as defined in the workflow controller's configmap.

**How to reproduce it (as minimally and precisely as possible)**:
```
    # metricsConfig controls the path and port for prometheus metrics
    metricsConfig:
      enabled: true
      path: /metrics
      port: 8080
      metricsTTL: "10m"
      disableLegacy: true
```

Apply configmap, and restart the workflow-controller.
Verify that the workflow-controller-metrics service does not reflect the port defined in the configmap.

**Anything else we need to know?**:

**Environment**:

- Argo version:
```
$ argo version
argo: v2.8.0
  BuildDate: 2020-05-11T22:55:43Z
  GitCommit: 8f696174746ed01b9bf1941ad03da62d312df641
  GitTreeState: clean
  GitTag: v2.8.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-04-10T21:53:58Z"
  compiler: gc
  gitCommit: 7879fc12a63337efff607952a323df90cdc7a335
  gitTreeState: clean
  gitVersion: v1.18.1
  goVersion: go1.14.2
  major: "1"
  minor: "18"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-04-03T17:45:13Z"
  compiler: gc
  gitCommit: 126eb499523e5fffc0138e8e2e031787e5ab1943
  gitTreeState: clean
  gitVersion: v1.14.8
  goVersion: go1.12.10
  major: "1"
  minor: "14"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- workflow-controller-metrics service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: workflow-controller-metrics
  namespace: argo
spec:
  clusterIP: 10.0.47.226
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: workflow-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
