### ISSUE TITLE
Artifact Garbage Collection

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo-workflows#3102]
# Summary

When a Workflow is deleted, we should consider garbage collecting artifacts from those workflows where possible.  This should likely be configurable.

# Motivation

Right now, manual intervention is needed in order to clean up artifacts that were created as part of Workflows if desired.  For high frequency workflows with high amounts of artifacts (think a CI system), cleaning up these artifacts can be pretty important for cost savings.

# Proposal

Each type of artifact storage will need to support a `deleteArtifact` function.  When a Workflow is deleted (not simply Archived, but actually deleted), all artifacts associated with that workflow would be cleaned up automatically.

We could make this configurable with something like

```yaml
  # The rest of the output config was omitted
  outputs:
    artifacts:
    - name: my-output-artifact
      artifactGC:
        strategy: Never | OnWorkflowDeletion | OnWorkflowArchival
```

Initially, I'd suggest that the default be `Never` to match existing behavior unless you're OK with making a breaking change.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
