### ISSUE TITLE
serviceAccountName is not propagated from the kubectl binary properly for WorkflowSpec

### ISSUE THREAD

**Issue by toninis** [argoproj/argo-workflows#3113]
Checklist:

 * [X] I've included the version.
 * [X] I've included reproduction steps.
 * [X] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
The **CronWorkflow** behaves differently if you submit it from `kubectl` vs `argo-cli` and it ignores the serviceAccountName configuration under the **WorkflowSpec**

**What you expected to happen**:
The same behaviour

**How to reproduce it (as minimally and precisely as possible)**:
If you submit this YAML you get two different configurations on Argo.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-aws-iam-default
  namespace: <namespace>
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 20
  workflowSpec:
    entrypoint: aws
    ServiceAccountName: workflow-default
    templates:
      - name: aws
        metadata:
          annotations:
            iam.amazonaws.com/role: <a super role>
        container:
          image: amazon/aws-cli
          command:
            - aws
          args:
            - s3
            - ls
            - <a_super_bucket>
```
From kubectl:
```bash
kubectl apply -f test.yml
```
```yaml
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"CronWorkflow","metadata":{"annotations":{},"name":"test-aws-iam","namespace":"<namespace>"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":20,"schedule":"*/2 * * * *","startingDeadlineSeconds":0,"successfulJobsHistoryLimit":10,"workflowSpec":{"ServiceAccountName":"workflow-default","entrypoint":"aws","templates":[{"container":{"args":["s3","ls","<bucket>"],"command":["aws"],"image":"amazon/aws-cli"},"metadata":{"annotations":{"iam.amazonaws.com/role":"<role>"}},"name":"aws"}]}}}
  generation: 1
  name: test-aws-iam
  namespace: <namespace>
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 20
  schedule: '*/2 * * * *'
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 10
  workflowSpec:
    arguments: {}
    entrypoint: aws
    templates:
    - arguments: {}
      container:
        args:
        - s3
        - ls
        - <bucket>
        command:
        - aws
        image: amazon/aws-cli
        name: ""
        resources: {}
      inputs: {}
      metadata:
        annotations:
          iam.amazonaws.com/role: <role>
      name: aws
      outputs: {}
status: {}
```
from argo cli :
```bash
argo cron create test.yml
```
```yaml
metadata:
  generation: 1
  name: test-aws-iam
  namespace: <namespace>
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 20
  schedule: '*/2 * * * *'
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 10
  workflowSpec:
    arguments: {}
    entrypoint: aws
    serviceAccountName: workflow-default
    templates:
    - arguments: {}
      container:
        args:
        - s3
        - ls
        - <bucket>
        command:
        - aws
        image: amazon/aws-cli
        name: ""
        resources: {}
      inputs: {}
      metadata:
        annotations:
          iam.amazonaws.com/role: <role>
      name: aws
      outputs: {}
status: {}
```

**Environment**:

- Argo version:
```
argo: v2.8.0
  BuildDate: 2020-05-11T22:55:43Z
  GitCommit: 8f696174746ed01b9bf1941ad03da62d312df641
  GitTreeState: clean
  GitTag: v2.8.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-03-12T21:08:59Z"
  compiler: gc
  gitCommit: d94a81c724ea8e1ccc9002d89b7fe81d58f89ede
  gitTreeState: clean
  gitVersion: v1.15.11
  goVersion: go1.12.17
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-12T21:00:06Z"
  compiler: gc
  gitCommit: d94a81c724ea8e1ccc9002d89b7fe81d58f89ede
  gitTreeState: clean
  gitVersion: v1.15.11
  goVersion: go1.12.17
  major: "1"
  minor: "15"
  platform: linux/amd64
```

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
