### ISSUE TITLE
steps.XX.outputs.parameters.YY is invalid when XX is expanded

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#3182]
**What happened**:

A user tried to do something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: entry
  templates:
  - name: entry
    steps:
    - - name: one
        template: whalesay
        withSequence:
          count: "1"
    - - name: two
        template: whalesay
        withParam: "{{steps.one.outputs.parameters.aaa}}"

  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello"]
    outputs:
      parameters:
      - name: aaa
        value: "asdf"

```

We currently allow the referencing of `{{steps.one.outputs.parameters.aaa}}`. However, when that step is expanded with items, then `{{steps.one.outputs.parameters.aaa}}` is ambiguous and does not represent a single value. 

The above workflow fails with error: `withParam value could not be parsed as a JSON list: {{steps.one.outputs.parameters.aaa}}`

```
Name:                steps-66hj2
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             withParam value could not be parsed as a JSON list: {{steps.one.outputs.parameters.aaa}}
Conditions:
 Completed           True
Created:             Fri Jun 05 12:45:37 -0700 (5 seconds ago)
Started:             Fri Jun 05 12:45:37 -0700 (5 seconds ago)
Finished:            Fri Jun 05 12:45:43 -0700 (now)
Duration:            6 seconds

STEP             TEMPLATE  PODNAME                DURATION  MESSAGE
 ✖ steps-66hj2   entry                                      withParam value could not be parsed as a JSON list: {{steps.one.outputs.parameters.aaa}}
 ├---✔ one(0:0)  whalesay  steps-66hj2-411194440  4s
```

We should do one of two things:
1. prevent this through validation
2. Make `{{steps.one.outputs.parameters.aaa}}` reference a virtual json list of the all items of the referenced variable.
