### ISSUE TITLE
Allow `onExit` to use `workflowTemplateRef`

### ISSUE THREAD

**Issue by ajitspendse** [argoproj/argo-workflows#3188]
# Summary

`onExit` handler allows specifying a template defined within the same workflow/workflow template. It would be great if `workflowTemplateRef` functionality can be extended to `onExit` handler as well.

# Motivation
In a Kubernetes deployment, we define a centrally configured `workflowDefaults` and also deploy some re-usable workflow templates. Using these facilities, it is also possible to define a common exit handler. However, current implementation makes it mandatory to have the exit handler template defined in same workflow. If this feature is available, a common exit handler can be defined at cluster level and used across all workflow definitions. Overrides can still be available at individual workflow or step level.

# Proposal

`onExit` used in central `workflowDefaults` should be able to reference to a template within another workflow template. Same can also be used in a workflow and step level `onExit`.

If a workflow specific onExit is defined, it can be used as a preferred exit handler over the centrally managed handler (this might be already happening). Step level `onExit` can also follow similar strategy.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
you can have `OnExit` on Entrypoint template in `WorkflowTemplate`.

**Comment by ajitspendse** [comment]
Can you please point me to the documentation for the same? I dug around, but could not find corresponding documentation or an example using this.

Also, having a generic functionality like `workflowTemplateRef` for onExit will not make it mandatory for users to use pre-defined WorkflowTemplate and would allow to use a single configuration - as part of `workflowDefaults` -  where a common exit handler can be defined, applicable across all workflows executed.

Happy to be corrected, if I am missing something.

**Comment by sarabala1979** [comment]
I found bug in the Workflowtemplate Exithandler. I fixed it #3259. It is available in master.

**Comment by ajitspendse** [comment]
This change still needs the workflow to mention following -

```
workflowTemplateRef:
    name: workflow-template-whalesay-template
```

The change proposed is to get rid of this requirement and allow a single global exit handler to be configured and executed for all workflows that get executed - irrespective of the templates they use.

This will allow the administrators to centrally control the exit handler and take appropriate actions/setup alerting mechanisms, in case workflow execution was unsuccessful/failed.

**Comment by sarabala1979** [comment]
`workflowTemplateRef` main purpose is move all the logic/code to `workflowtemplate` and workflow should simply refer it.  I understand your requirement. you can achieve the above usecase using `templateref`.
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay
  onExit: exit-handler
  templates:
  - name: whalesay
    steps:
      - - name: call-whalesay-template
          templateRef:
            name: workflow-template-whalesay-template
            template: whalesay-template
          arguments:
            parameters:
            - name: message
              value: "hello world"
  - name: exit-handler
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```
