### ISSUE TITLE
Allow setting defaults for `template` in workflows

### ISSUE THREAD

**Issue by max-sixty** [argoproj/argo-workflows#3201]
[Edit — renamed to "Allow setting defaults for 'template' in workflows", and https://github.com/argoproj/argo-workflows/issues/6419 opened for `container`]

# Summary

Allow setting defaults for the `container` field in workflows

# Motivation

ref [Slack discussion](https://argoproj.slack.com/archives/C8J6SGN12/p1591723434019300)

Currently if we want to set a default image pull policy for containers, we need an additional layer of config, like kustomize, or to add it to every workflow manually.

# Proposal

I'm not sure; potentially allow this to flow through `workflowDefaults` like:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    workflowDefaults:
      metadata:
        annotations:
          argo: workflows
      spec:
        templates:
          container:
            imagePullPolicy: Always  # <- here
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by foobarbecue** [comment]
This is a specific example of a more general problem -- the YAML way of doing things leads to lots of repetition. It would be nice to have a generic system for setting defaults, or extending templates. Currently I'm using yaml anchors and aliases as a workaround.

**Comment by max-sixty** [comment]
Yes, kustomize should be good at that. I've used it elsewhere successfully, I may give that a try for argo.

**Comment by alexec** [comment]
@sarabala1979 this might be one to work on next.

**Comment by max-sixty** [comment]
Hi @sarabala1979 — thanks for doing #5410. Can I ask whether it closes this issue though? Is there a way of setting *container* defaults?

I tried with:

```yaml
    templateDefaults:
      container:
        image: "{{workflow.parameters.image}}"
```

But this doesn't seem to work. It would need to merge the `container` entries in here with those from the template.

**Comment by sarabala1979** [comment]
This will support  but only thing `container` will add to all `template`  if this container is for all template then this will work

**Comment by max-sixty** [comment]
Possibly I'm making a mistake and actually this does work — could I check I'm doing it right?

This fails with `   ✖ in "hello-world-" (Workflow): templates.whalesay.container.image may not be empty`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templateDefaults:
    container:
      image: docker/whalesay:earliest
  templates:
    - name: whalesay
      container:
        # image: docker/whalesay:latest
        command: [cowsay]
        args: ["hello world"]
```

And commenting out `container`, or all the fields of `container` fails with `   ✖ in "hello-world-" (Workflow): template 'whalesay' type is unknown`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templateDefaults:
    container:
      image: docker/whalesay:earliest
  templates:
    - name: whalesay
      container:
        # image: docker/whalesay:latest
        # command: [cowsay]
        # args: ["hello world"]
```

---

The feature request was to be able to set defaults for the `image` field of all `container` tasks, so this would work:

```yaml

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templateDefaults:
    container:
      image: docker/whalesay:earliest
  templates:
    - name: whalesay
      container:
        # image: docker/whalesay:latest <- would be ":earliest" unless uncommented
        command: [cowsay]
        args: ["hello world"]

    # This wouldn't be affected by the default, because it doesn't have a `container` field
    - name: whalesee
      script:
        image: docker/whalesay:latest
        command: [python]
        source: "import datetime"
```
