### ISSUE TITLE
Allow setting workflow parameter values using ConfigMap

### ISSUE THREAD

**Issue by erhhung** [argoproj/argo-workflows#3212]
# Summary

There is currently no way to set a workflow parameter value (for both global `spec.arguments.parameters` and `steps[].arguments.parameters`) using the `valueFrom.configMapKeyRef` construct in the same way `env` variables can be defined.

It would be nice to be able to use a value from a ConfigMap as the default and still allow it to be overridden using the CLI `-p` option.

# Motivation

I want to define a custom Docker registry endpoint in a ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: worker
data:
  docker.registry: '123456789012.dkr.ecr.us-west-1.amazonaws.com'
```

And be able to use it in a workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: myworkflow-
spec:
  entrypoint: step1
  arguments:
    parameters:
    - name: registry
      valueFrom:
        configMapKeyRef:
          name: environment-config
          key: docker.registry
  templates:
  - name: step1
    container:
      image: '{{workflow.parameters.registry}}/step1:latest'
      command: [./start.sh]
```

# Proposal

Same behavior as `valueFrom.configMapKeyRef` for environment variables.

In this specific example of customizing the Docker registry endpoint, if there's another better way without duplicating the actual value in multiple places, that would also be appreciated.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Great suggestion. I'll look into this

**Comment by simster7** [comment]
Looked into this. Problem with the suggestion is that `valueFrom` is used only to retrieve values for _output_ parameters. Arguments may only use `parameters.value` to specify the value.

Good news is that you can use a `resource` template to get the value from your `ConfigMap` today:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: get-cm-value-
spec:
  entrypoint: entry

  templates:
    - name: entry
      steps:
        - - name: get-cm-value
            template: get-cm-value
        - - name: use-cm-value
            template: use-cm-value
            arguments:
              parameters:
                - name: docker-val
                  value: "{{steps.get-cm-value.outputs.parameters.docker-val}}"

    - name: get-cm-value
      resource:
        action: get
        # This specifies which ConfigMap to look at
        manifest: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: environment-config
      outputs:
        parameters:
          - name: docker-val
            valueFrom:
              jsonPath: '{.data.docker-registry}'    # Pick which value you want here


    - name: use-cm-value
      inputs:
        parameters:
          - name: docker-val
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo {{inputs.parameters.docker-val}}"]
```

**Comment by simster7** [comment]
Closing as solved? Feel free to comment if not

**Comment by erhhung** [comment]
Sorry I wasn't monitoring the responses closely.

@simster7, I don't quite understand your explanation about `valueFrom` being only used to retrieve _output_ parameters, as if that's logically the only way it's supposed to work.

If I can inject _input_ environment variables (`container.env`) using `valueFrom.configMapKeyRef` or `valueFrom.secretKeyRef` (see [secrets.yaml](../blob/master/examples/secrets.yaml)), or even simpler `envFrom.configMapRef`, then I don't see why logically I can't also fetch ConfigMap values for `inputs.parameters` or `workflow.parameters`.

Your example using a `resource` template is **at best a workaround** because it's extremely verbose (see all the places `docker-val` is used). It requires an **extra boilerplate template step** on every workflow (because I'd need the registry URL in every workflow) that will also appear in the dashboard graph. Sure, it's a low-level, generic approach to perform any action on any K8s resource, but then why there exists a convenience "function" for injecting environment variables? It's this imbalance of expectations that I see as the main problem.

**Comment by andizzle** [comment]
Bump. Can we re-open this as a feature request?

**Comment by alexec** [comment]
@andizzle re-opened. Would you like to submit a PR?

**Comment by firecast** [comment]
@alexec I've create a PR for this issue as it is something that my company also wanted

**Comment by Guillermogsjc** [comment]
Hi @alexec @firecast,  is this feature already deployed on any version?

It would be very nice it it mimic the behaviour of `env` and `envFrom` in a similar manne, and to allow both `configMapRef` and `secretRef` would be beast:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fav-dag-with-arguments-from-configmap
  namespace: argo
spec:  
  arguments:
   paramsFrom:
     - configMapRef:
         name: configmap-with-workflow-parameters
   parameters:
     - name: ANOTHER_PARAM
       value: another_param_value
```

**Comment by alexec** [comment]
This feature was never merged. Hopefully some one from the community will take it on.

**Comment by softwarebloat** [comment]
Hi!
I have the same need. I saw the PR but i'm pretty new to the project and never coded in Go. anyone from the community wants to continue the work on that PR together? :smiley:

**Comment by alexec** [comment]
#4427 go abandoned. Another users needs to pick this piece of work up.

**Comment by terrytangyuan** [comment]
Please try out these two new examples and let me know if you encounter any issues!
1. https://github.com/argoproj/argo-workflows/blob/master/examples/global-parameters-from-configmap.yaml
1. https://github.com/argoproj/argo-workflows/blob/master/examples/arguments-parameters-from-configmap.yaml

Note that the ConfigMap used in these examples is defined [here](https://github.com/argoproj/argo-workflows/blob/master/examples/configmaps/simple-parameters-configmap.yaml).

**Comment by apiwoni** [comment]
@erhhung @terrytangyuan This issue has been resolved for `spec.templates[].inputs.parameters` but `spec.arguments.parameters` does not work with `valueFrom.configMapKeyRef`.  The links above show examples. for `spec.templates[].inputs.parameters` which work. 

This is not working:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-from-configmap-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
#      value: "this is working but not valueFrom.configMapKeyRef"
      valueFrom:
        configMapKeyRef:
          name: simple-parameters
          key: msg
  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

```
argo submit arguments-parameters-from-configmap.yaml
FATA[2021-10-05T15:44:29.416Z] Failed to submit workflow: templates.whalesay inputs.parameters.message was not supplied
```

**Comment by terrytangyuan** [comment]
@apiwoni Could you submit a separate bug report with reproducible example and other necessary information like controller logs?

**Comment by apiwoni** [comment]
> @apiwoni Could you submit a separate bug report with reproducible example and other necessary information like controller logs?

@terrytangyuan I think this may not be an issue because it works when I declare `args: ["{{workflow.parameters.message}}"]` and remove `spec.templates[].inputs.parameters` as in this example with variable in global scope:
https://github.com/argoproj/argo-workflows/blob/v3.2.0-rc5/examples/global-parameters-from-configmap.yaml

Let me verify that `valueFrom` works in `arguments.paramaters` in https://github.com/argoproj/argo-workflows/blob/v3.2.0-rc5/examples/dag-custom-metrics.yaml before I submit bug report where it is referenced as local variable.

Thank you

**Comment by Guillermogsjc** [comment]
Hi , do you think it would be possible to amplify the feature to allow `paramsFrom` performing mimic on `env` and `envFrom` ?

```yaml
arguments:
   paramsFrom:
     - configMapRef:
         name: configmap-with-workflow-parameters
```
