### ISSUE TITLE
WorkflowTemplates not respecting ttlStrategy

### ISSUE THREAD

**Issue by zachaller** [argoproj/argo-workflows#3227]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
Create a workflow template with a ttlStrategy and call the workflow using workflowTemplateRef the workflow did not get cleaned up when it ttl'ed
**What you expected to happen**:
I wanted the workflow to get cleaned up according to the ttl time
**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable-2.9
  namespace: argo-events
  labels:
    workflows.argoproj.io/controller-instanceid: argo-v2.9
spec:
  ttlStrategy:
    secondsAfterCompletion: 60
  serviceAccountName: argo-events-sa
  entrypoint: start
  arguments:
    parameters:
      - name: message
        value: "hello world"
  templates:
    - name: start
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [echo]
        args: ["{{inputs.parameters.message}}"] 
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo-events
  generateName: workflow-template-hello-world-
  labels:
    workflows.argoproj.io/controller-instanceid: argo-v2.9
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: message
        value: "hello world"
  workflowTemplateRef:
    name: workflow-template-submittable-2.9
```

**Anything else we need to know?**:
Logs had no valuable information

**Environment**:

- Argo version:
```
2.9-rc1
```
- Kubernetes version :
```
1.17.5
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
