### ISSUE TITLE
withParam value could not be parsed as a JSON list with nested list parameters

### ISSUE THREAD

**Issue by TTRh** [argoproj/argo-workflows#3288]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

Working with a parameter that contains a nested list, argo fail with json parsing error even json payload is correct.

**What you expected to happen**:

We should be able to use json input parameters with nested lists. 

**Related PRs**

* https://github.com/argoproj/argo/issues/1389

**How to reproduce it (as minimally and precisely as possible)**:

You can see we have as input a json list.
Removing the `data[].dict_param.bug` key it passes, but if you keep it it fails.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bug-nested-list-param-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: data
        value: |
          [
            {
              "scalar_param": "bar",
              "dict_param": {"foo": "bar", "bug": [1, 2]},
              "list_param": [{"foo": "bar"}]
            }
          ]

  templates:

    - name: main
      inputs:
        parameters:
          - name: data
            value: "{{workflow.parameters.data}}"
      steps:
        - - name: multiple-workflow
            template: one-workflow
            arguments:
              parameters:
                - name: scalar_param
                  value: "{{item.scalar_param}}"
                - name: dict_param
                  value: "{{item.dict_param}}"
                - name: list_param
                  value: "{{item.list_param}}"
            withParam: "{{inputs.parameters.data}}"

    - name: one-workflow
      inputs:
        parameters:
          - name: scalar_param
          - name: dict_param
          - name: list_param
      steps:
        - - name: read-scalar
            template: echo-param
            arguments:
              parameters:
                - name: data
                  value: "{{inputs.parameters.scalar_param}}"
          - name: read-dict
            template: echo-param
            arguments:
              parameters:
                - name: data
                  value: "{{inputs.parameters.dict_param}}"
          - name: read-list
            template: echo-param
            arguments:
              parameters:
                - name: data
                  value: "{{inputs.parameters.list_param}}"

    - name: echo-param
      inputs:
        parameters:
          - name: data
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo 'Input parameter: <{{inputs.parameters.data}}>'"]
```

**Anything else we need to know?**:

**Environment**:

- Argo version:
```
▶ argo version
argo: v2.8.1
  BuildDate: 2020-05-28T23:39:46Z
  GitCommit: 0fff4b21c21c5ff5adbb5ff62c68e67edd95d6b8
  GitTreeState: clean
  GitTag: v2.8.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
▶  kubectl version -o yaml
clientVersion:
  buildDate: "2019-12-11T12:41:00Z"
  compiler: gc
  gitCommit: 575467a0eaf3ca1f20eb86215b3bde40a5ae617a
  gitTreeState: clean
  gitVersion: v1.14.10
  goVersion: go1.12.12
  major: "1"
  minor: "14"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-03-18T04:24:17Z"
  compiler: gc
  gitCommit: f459c0672169dd35e77af56c24556530a05e9ab1
  gitTreeState: clean
  gitVersion: v1.14.9-eks-f459c0
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- workflow result:

```
▶ argo --loglevel DEBUG get bug-nested-list-param-6shm8
DEBU[0000] CLI version                                   version="{v2.8.1 2020-05-28T23:39:46Z 0fff4b21c21c5ff5adbb5ff62c68e67edd95d6b8 v2.8.1 clean go1.13.4 gc linux/amd64}"
DEBU[0000] Client options                                opts="{{ false false} 0x1574ab0 0xc0006db090}"
Name:                bug-nested-list-param-6shm8
Namespace:           unicron-serenity-dev
ServiceAccount:      default
Status:              Failed
Message:             withParam value could not be parsed as a JSON list: [
  {
    "scalar_param": "bar",
    "dict_param": {"foo": "bar", "bug": ["1", "2"]},
    "list_param": [{"foo": "bar"}]
  }
]
Conditions:          
 Completed           True
Created:             Wed Jun 24 08:59:22 +0200 (32 seconds ago)
Started:             Wed Jun 24 08:59:22 +0200 (32 seconds ago)
Finished:            Wed Jun 24 08:59:22 +0200 (32 seconds ago)
Duration:            0 seconds
Parameters:          
  data:              [
  {
    "scalar_param": "bar",
    "dict_param": {"foo": "bar", "bug": ["1", "2"]},
    "list_param": [{"foo": "bar"}]
  }
]


STEP                            TEMPLATE  PODNAME  DURATION  MESSAGE
 ✖ bug-nested-list-param-6shm8  main                         withParam value could not be parsed as a JSON list: [
  {
    "scalar_param": "bar",
    "dict_param": {"foo": "bar", "bug": ["1", "2"]},
    "list_param": [{"foo": "bar"}]
  }
]  
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
