### ISSUE TITLE
Workflow fails when using PVC

### ISSUE THREAD

**Issue by hadim** [argoproj/argo-workflows#3305]
I observed a bug that makes a workflow to instantaneously fail upon starting when it uses a PVC. The logs on the associated pod show no error and the output of the node(s) show what they are supposed to show. So in short the workflow works but Argo reports an error.

Here is the failing workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: volumes-pvc-
spec:
  entrypoint: generate-message
  serviceAccountName: workflow

  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi

  templates:
    - name: generate-message
      script:
        image: docker/whalesay:latest
        command: [sh]
        source: |
          echo generating message in volume
          mkdir -p /mnt/vol
          cowsay hello world | tee /mnt/vol/hello_world.txt
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
```

Here is a similar one that works:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: volumes-pvc-
spec:
  entrypoint: generate-message
  serviceAccountName: workflow

  # volumeClaimTemplates:
  #   - metadata:
  #       name: workdir
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 100Mi

  templates:
    - name: generate-message
      script:
        image: docker/whalesay:latest
        command: [sh]
        source: |
          echo generating message in volume
          mkdir -p /mnt/vol
          cowsay hello world | tee /mnt/vol/hello_world.txt
        # volumeMounts:
        #   - name: workdir
        #     mountPath: /mnt/vol

```

I am on GKE and use the following storage class provisioner: `pd.csi.storage.gke.io`.

This has been tested on 2.8.1, 2.8.2, 2.9.0-rc2 and 2.9.0-rc3.
