### ISSUE TITLE
Remote ingress access broken on 2.9.0

### ISSUE THREAD

**Issue by hadim** [argoproj/argo-workflows#3379]
I tried 2.9.0 and when trying to access the UI from outside the cluster (using an ingress on GKE), I got a 404 error (the server does not respond to the request).

Everything works fine with 2.9.0-rc4. I don't know whether it's a configuration change or a bug. I looked at the changelog and can't see anything obvious.

Here is the manifest I use:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server-remote
spec:
  selector:
    matchLabels:
      app: argo-server-remote
  template:
    metadata:
      labels:
        app: argo-server-remote
    spec:
      containers:
        - args: [server, --auth-mode, client, --namespaced]
          image: argoproj/argocli:v2.9.0
          name: argo-server-remote
          ports:
            - containerPort: 2746
              name: web
          readinessProbe:
            httpGet:
              path: /
              port: 2746
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 20
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: argo
---
apiVersion: v1
kind: Service
metadata:
  name: argo-server-remote
spec:
  type: NodePort
  ports:
    - name: web
      port: 2746
      targetPort: 2746
  selector:
    app: argo-server-remote
```

The only thing I have changed between my tests is `image: argoproj/argocli:v2.9.0` to `image: argoproj/argocli:v2.9.0-rc4`.

When accessing the UI locally (using `kubectl proxy`), it works perfectly.
