### ISSUE TITLE
Script steps fail with exceededQuota

### ISSUE THREAD

**Issue by jamesgunnfiveai** [argoproj/argo-workflows#3396]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
Parallel steps that would take the workflow over the cluster CPU limit (set at 64) fail to schedule and error the workflow when defined using `script`:
Error is
`pods "quota-test-698219065" is forbidden: exceeded quota: compute, requested: requests.cpu=10100m, used: requests.cpu=60700m, limited: requests.cpu=64`

**What you expected to happen**:
Steps should remain pending until resource is freed, as happens when steps are defined using `container` syntax.

**How to reproduce it (as minimally and precisely as possible)**:

With the below worflow, the following command behaves as expected:
`argo submit workflow.yaml --entrypoint multicontainer --watch`
The following command fails as reported:
`argo submit workflow.yaml --entrypoint multiscript --watch`

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: quota-test
spec:
  entrypoint: multiscript
  templates:
  - name: script
    resubmitPendingPods: true
    script:
      image: busybox
      resources:
        limits:
          cpu: 10
      command: [bash]
      source: |
          sleep 5
  - name: container
    resubmitPendingPods: true
    container:
      image: busybox
      resources:
        limits:
          cpu: 10
      command: [sh, -c]
      args: ["sleep 5"]

  - name: multiscript
    dag:
      tasks:
      - name: script
        template: script
        withItems:
          - a
          - b
          - c
          - d
          - e
          - f
          - g
          - h
          - i
          - j

  - name: multicontainer
    dag:
      tasks:
      - name: container
        template: container
        withItems:
          - a
          - b
          - c
          - d
          - e
          - f
          - g
          - h
          - i
          - j
```

**Anything else we need to know?**:

**Environment**:

- Argo version

Client
```
argo: v2.9.1
  BuildDate: 2020-07-03T15:06:40Z
  GitCommit: 6b967d08c0a142aaa278538f2407c28de467262e
  GitTreeState: clean
  GitTag: v2.9.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
Server is at 2.7.3

- Kubernetes version :
v1.18.4 (client)
v1.14.9-eks-f459c (server)

Additional logs can be provided if required.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
