### ISSUE TITLE
Cannot use `workflow.parameters` to set Workflow metadata?

### ISSUE THREAD

**Issue by mecampbellsoup** [argoproj/argo-workflows#3434]
## To reproduce

1. Write a Workflow template that attempts to set `metadata.labels` with some key/value pair, where the value is set from Workflow parameters (`job_id` being the workflow param in this example):

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: render-
  labels:
    jobId: "{{workflow.parameters.job_id}}"
```

2. Submit the workflow, passing in `job_id` as a workflow parameter.

3. Observe that the workflow fails to submit to Argo.

```
Kubeclient::HttpError (Workflow.argoproj.io "render-w85k4" is invalid: metadata.labels: Invalid value: "{{workflow.parameters.job_id}}": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')):

app/lib/argo/argo.rb:47:in `workflow_submit'
```

**Comment by sarabala1979** [comment]
Instead of using the  `-p` workflow parameter for workflow metadata, you can use -l option to add or update the label directly

**Comment by elocke** [comment]
+1 I can't trust my users to add the label themselves. This would be nice to set via other inputs

**Comment by alexec** [comment]
I'm not clear on the need for labels. Do you need to search the templates?

**Comment by elocke** [comment]
@alexec I have a template defined for a process that takes a parameter. I want to set a label on that workflow automatically so I can group by the label to see the workflow history for a certain input parameter.

**Comment by alexec** [comment]
Seems like a valid request. I wonder if we could create a Javascript only solution that would be cheap.

**Comment by alexec** [comment]
I'm reviewing this popular issue. I'm assuming the use case is querying workflows by parameter?

**Comment by alexec** [comment]
```yaml
spec:
  workflowMetadata:
    labels: {}
    annotations: {}
    labelsFrom: {}
    annotationsFrom: {}
```
```

**Comment by Guillermogsjc** [comment]
Hi @alexec, being able to put workflow.parameters or attributes as labels would be nice to be able to do:

```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: asd
  namespace: argo

spec:
  schedule: 0 7 * * 1-5
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 0
  workflowSpec:    
    workflowTemplateRef:
      name: workflow-template-submittable
    arguments:
      parameters:
      - name: message
        value: hello
  workflowMetadata:
    labels:
      example-parameter-from-label: {{workflow.parameters.my-param-label}}
      from-argo-uid: {{workflow.uid}}
```
