### ISSUE TITLE
Workflow Template Catalog

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#3438]
With the introduction of workflow templates,  we could not create a sharable library of templates that people could download and install.

E.g.

```
$ argo hub search ci
NAME         URL
ci-example https://argoproj.github.io/argo/templates/ci.yaml

$ argo template create -f https://argoproj.github.io/argo/templates/ci.yaml
```

**Comment by ericandrewmeadows** [comment]
My thought behind this was to enable Airflow-like behavior with Hooks and Operators.  We have a lot of code that we could share template-wise for CI/CD, but I would imagine that you could create templates as well for model training and saving, in order to standardize some data I/O interfaces to steps.

Other places where this could be useful:  Slack notifications, email notifications, etc. as templates.

**Comment by dcherman** [comment]
Absolutely!  Similar to the `catalog` that Tekton has, I think it would be great to have a set of WorkflowTemplates/ClusterWorkflowTemplates for common tasks, that way everyone isn't re-inventing the wheel.

**Comment by alexec** [comment]
https://github.com/tektoncd/catalog

**Comment by alexec** [comment]
Some additional thoughts on this:

The TektonCD catalog appears to have about 50 items in it. I'd imagine we'd want to start with at least 20 ourselves. Our catalog will succeed or fail based on content.

Helm already provides a way to package manifests. 

Rather than storing templates, we could store packages of resources, e.g. if the workflow depends on other Kuberenetes resources.

Let us call these `template packages`.

We'll want to GitOps them, so they need to work with `kubctl apply -f`.  I.e. each 

```
kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/master/task/argocd-task-sync-and-wait/0.1/argocd-task-sync-and-wait.yaml
```

Each package is going to be similar to a Helm chart.

We need to store metadata - in fact very similar metadata to the TektonCD catalog.

```
annotaions:
  # a semantic version range to indicate with versions of Argo Workflow the template is compatible with
  workflows.argoproj.io/version: v2.9.2
  # a description of the template
  workflows.argoproj.io/description: ...
  # comma-separated tags to enable searching and categorization
  workflows.argoproj.io/tags: ...
```

We do not need versions of each template package, that is just a Git tag.
