### ISSUE TITLE
Event based Resume the suspended Workflow (EventTemplate)

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#3443]
# Summary
The workflow needs to be suspended and wait for the event to resume it.  This is very similar to `suspendtemplate` which is currently suspending workflow, so it can be resumed based on the manual intervention or duration.

Please give examples of your use case, e.g. when would you use this.

# Proposal
The event template needs to support multiple event sources.
1. Kafka
2. Kubernetes Event
3. SQS
4. SNS

Sample template format

```yaml
- name: eventTmpl
    event:
      source:
        kafka:
          url: kafka.argo-events:9092
          topic: topic-2
          partition: "1"
      condition:
         jsonExpression: ".event.source.type == resume"
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
Sample Workflow

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: event-template-
spec:
  entrypoint: event
  templates:
  - name: event
    steps:
    - - name: build
        template: whalesay
    - - name: event
        template: eventTmpl
    - - name: release
        template: whalesay

  - name: eventTmpl
      event:
        source:
          kafka:
            url: kafka.argo-events:9092
            topic: topic-2
            partition: "1"
        condition:
          jsonExpression: ".event.source.type == resume"
          
  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
```
