### ISSUE TITLE
Failed to resolve `{{workflow.failures}}` in exit handler

### ISSUE THREAD

**Issue by zachaller** [argoproj/argo-workflows#3448]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**: When submitting a workflow that used to work with argo workflows cli 2.8 now fails on argocli 2.9
with ```invalid spec: templates.exit-handler.steps[1].workflow-failed-notification templates.workflow-failed-notification: failed to resolve {{workflow.failures}}```

**What you expected to happen**: The workflow gets submitted

**How to reproduce it (as minimally and precisely as possible)**: The failure happens on an exit handler that looks something like this:
```
 name: exit-handler
      steps:
        - - name: workflow-succeeded-notification
            template: workflow-succeeded-notification
            when: "{{workflow.status}} == Succeeded"
        - - name: workflow-failed-notification
            template: workflow-failed-notification
            when: "{{workflow.status}} != Succeeded"
    - name: workflow-succeeded-notification
      script:
        image: <imageurl>
        command: [bash]
        source: |
          curl -X POST -H 'Content-type: application/json'\
                       -d '{
                        "blocks": [
                            {"type": "section",
                            "text": {"text": "- *workflow:* _'{{workflow.name}}'_\n- *namespace:* _'{{workflow.namespace}}'_\n- *status:* _'{{workflow.status}}'_\n",
                                     "type": "mrkdwn"}}
                        ]
                      }' <slackurl>
    - name: workflow-failed-notification
      script:
        image: <imageurl>
        command: [bash]
        source: |
          TEMP=$(echo "{{workflow.failures}}" | jq -r '.[] | {"type": "section","text": {"type": "mrkdwn","text": "- *name:* _ \(.displayName)_\n- *template:* _\(.templateName)_\n- *message:* _\(.message)_\n- *phase:* _\(.phase)_\n- *podName:* _\(.podName)_\n- *finishedAt:* _\(.finishedAt)_\n"}},{"type": "divider"}' | jq -s .)
          echo "{\"blocks\": $TEMP}" > failures.json
          cat failures.json
          curl -X POST -H "Content-Type: application/json" --data-binary @failures.json <slackURL>
```

**Anything else we need to know?**:

**Environment**:

- Argo version:
```
2.9.2
```
- Kubernetes version :
```
1.17.8
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@simster7 a regression related to exit handler. Do you want to own?

**Comment by simster7** [comment]
I'd be happy to own

**Comment by simster7** [comment]
Hmm, @zachaller I was able to submit this Workflow without a problem on latest:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: false
spec:
  entrypoint: whalesay
  onExit: exit-handler
  templates:
    - name: whalesay
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo hello"]

    - name: exit-handler
      steps:
        - - name: workflow-succeeded-notification
            template: workflow-succeeded-notification
            when: "{{workflow.status}} == Succeeded"
        - - name: workflow-failed-notification
            template: workflow-failed-notification
            when: "{{workflow.status}} != Succeeded"

    - name: workflow-succeeded-notification
      script:
        image: alpine
        command: [bash]
        source: |
          curl -X POST -H 'Content-type: application/json'\
                       -d '{
                        "blocks": [
                            {"type": "section",
                            "text": {"text": "- *workflow:* _'{{workflow.name}}'_\n- *namespace:* _'{{workflow.namespace}}'_\n- *status:* _'{{workflow.status}}'_\n",
                                     "type": "mrkdwn"}}
                        ]
                      }' <slackurl>

    - name: workflow-failed-notification
      script:
        image: alpine
        command: [bash]
        source: |
          TEMP=$(echo "{{workflow.failures}}" | jq -r '.[] | {"type": "section","text": {"type": "mrkdwn","text": "- *name:* _ \(.displayName)_\n- *template:* _\(.templateName)_\n- *message:* _\(.message)_\n- *phase:* _\(.phase)_\n- *podName:* _\(.podName)_\n- *finishedAt:* _\(.finishedAt)_\n"}},{"type": "divider"}' | jq -s .)
          echo "{\"blocks\": $TEMP}" > failures.json
          cat failures.json
          curl -X POST -H "Content-Type: application/json" --data-binary @failures.json <slackURL>
```

Do you see anything missing that could help me reproduce?

**Comment by zachaller** [comment]
So this is an example that is a bit closer to what we are doing but I had to remove a bunch of stuff, this one dose however behave slightly different than what I was seeing with our full versison of the workflow this one submits but then if I look at kubectl get events I see this 

```
3s          Normal    WorkflowRunning                                                                                workflow/build-api-xph7f              Workflow Running
3s          Warning   WorkflowFailed                                                                                 workflow/build-api-xph7f              invalid spec: templates.exit-handler.steps[1].workflow-failed-notification templates.workflow-failed-notification: failed to resolve {{workflow.failures}}
```

vs before it was throwing it right on the output of the cli, not sure if it matters but to clarify if we use argo CLI 2.8 and submit to a 2.9 or any version controller it was working however when we use the 2.9 cli it fails.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    workflows.argoproj.io/controller-instanceid: argo-v2.9
  generateName: build-api-
spec:
  entrypoint: ci-build-api
  onExit: exit-handler
  arguments:
    parameters:
      - name: revision
        value: "master"
      - name: namespace
        value: "namespace"
      - name: cluster
        value: "cluster"
  templates:
    - name: ci-build-api
      inputs:
        parameters:
          - name: revision
          - name: cluster
          - name: namespace
      steps:
        - - name: build
            template: build-api
            arguments:
              parameters:
                - name: revision
                  value: "{{inputs.parameters.revision}}"
        - - name: update-kustomization
            template: update-kustomize
            arguments:
              parameters:
                - name: cluster
                  value: "{{inputs.parameters.cluster}}"
                - name: namespace
                  value: "{{inputs.parameters.namespace}}"
                - name: gitHash
                  value: "{{steps.build.outputs.parameters.gitHash}}"

    - name: build-api
      inputs:
        parameters:
          - name: revision
      script:
        image: ubuntu
        command: [bash]
        source: |
          echo 4326ds > /tmp/gitHash.txt
        env:
          - name: DOCKER_HOST
            value: 127.0.0.1
      sidecars:
        - name: dind
          image: docker:18-dind
          securityContext:
            privileged: true
          mirrorVolumeMounts: true
      outputs:
        parameters:
          - name: gitHash
            valueFrom:
              path: /tmp/gitHash.txt

    - name: update-kustomize
      inputs:
        parameters:
          - name: namespace
          - name: cluster
          - name: gitHash
      script:
        image: ubuntu
        command: [bash]
        source: |
          echo test

    - name: exit-handler
      steps:
        - - name: workflow-succeeded-notification
            template: workflow-succeeded-notification
            when: "{{workflow.status}} == Succeeded"
        - - name: workflow-failed-notification
            template: workflow-failed-notification
            when: "{{workflow.status}} != Succeeded"
    - name: workflow-succeeded-notification
      script:
        image: ubuntu
        command: [bash]
        source: |
          curl -X POST -H 'Content-type: application/json'\
                       -d '{
                        "blocks": [
                            {"type": "section",
                            "text": {"text": "- *workflow:* _'{{workflow.name}}'_\n- *namespace:* _'{{workflow.namespace}}'_\n- *status:* _'{{workflow.status}}'_\n",
                                     "type": "mrkdwn"}}
                        ]
                      }' <slackurl>
    - name: workflow-failed-notification
      script:
        image: ubuntu
        command: [bash]
        source: |
          TEMP=$(echo "{{workflow.failures}}" | jq -r '.[] | {"type": "section","text": {"type": "mrkdwn","text": "- *name:* _ \(.displayName)_\n- *template:* _\(.templateName)_\n- *message:* _\(.message)_\n- *phase:* _\(.phase)_\n- *podName:* _\(.podName)_\n- *finishedAt:* _\(.finishedAt)_\n"}},{"type": "divider"}' | jq -s .)
          echo "{\"blocks\": $TEMP}" > failures.json
          cat failures.json
          curl -X POST -H "Content-Type: application/json" --data-binary @failures.json <slackurl>
```
