### ISSUE TITLE
Parameters with values that contain quotes are not valid yaml when used in a resource manifest

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#3449]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

A parameter with quotes when passed to a k8s `resource` manifest does not work

```
argo submit test.yaml -p command='echo "foo"'
2020/07/10 08:21:43 Failed to submit workflow: templates.pi-tmpl.resource.manifest must be a valid yaml
```

Not using quotes works
```
argo submit test.yaml -p command='echo foo'
Name:                k8s-jobs-d6nfg
Namespace:           default
ServiceAccount:      default
Status:              Pending
Created:             Fri Jul 10 08:21:37 -0700 (now)
Parameters:
  command:           echo foo
```

**What you expected to happen**:

I expect to be able to pass quotes in parameter values.

**How to reproduce it (as minimally and precisely as possible)**:

I modified the https://github.com/argoproj/argo/tree/master/examples#kubernetes-resources example to have a parameter.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: k8s-jobs-
spec:
  entrypoint: pi-tmpl
  arguments:
      parameters:
      - name: command
  templates:
  - name: pi-tmpl
    resource:                   # indicates that this is a resource template
      action: create            # can be any kubectl action (e.g. create, delete, apply, patch)
      successCondition: status.succeeded > 0
      failureCondition: status.failed > 3
      manifest: |               #put your kubernetes spec here
        apiVersion: batch/v1
        kind: Job
        metadata:
          generateName: pi-job-
        spec:
          template:
            metadata:
              name: pi
            spec:
              containers:
              - name: pi
                image: perl
                command:
                  - "/bin/sh"
                  - "-c"
                  - "{{workflow.parameters.command}}"
              restartPolicy: Never
          backoffLimit: 4
```

Then run

```
argo submit test.yaml -p command='echo "foo"'
```

**Anything else we need to know?**:

Nope

**Environment**:

- Argo version:
```
argo version
argo: v2.8.1
  BuildDate: 2020-05-28T23:40:32Z
  GitCommit: 0fff4b21c21c5ff5adbb5ff62c68e67edd95d6b8
  GitTreeState: clean
  GitTag: v2.8.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$  kubectl version -o yaml
clientVersion:
  buildDate: "2020-01-15T08:26:26Z"
  compiler: gc
  gitCommit: e7f962ba86f4ce7033828210ca3556393c377bcc
  gitTreeState: clean
  gitVersion: v1.16.6-beta.0
  goVersion: go1.13.5
  major: "1"
  minor: 16+
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-12T21:00:06Z"
  compiler: gc
  gitCommit: d94a81c724ea8e1ccc9002d89b7fe81d58f89ede
  gitTreeState: clean
  gitVersion: v1.15.11
  goVersion: go1.12.17
  major: "1"
  minor: "15"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

n/a

**Logs**

n/a

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
