### ISSUE TITLE
Error: `exec: "/argo/staging/script": permission denied`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#3496]
# Summary

I want to stop this error:

```
failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/argo/staging/script\": permission denied": unknown
```

# Motivation

It is annoying to need to specify `command: [sh]` for scripts, when it could just be Unix executable.

```yaml
      script:
        image: 'docker/whalesay:latest'
        command: [sh]
        source: |
          true
```

```yaml
      script:
        image: 'docker/whalesay:latest'
        source: |
          #!/bin/sh
          true
```

# Proposal

Using chmod.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
https://chmodcommand.com/chmod-744/

**Comment by alexec** [comment]
```
      script:
        name: main
        image: 'docker/whalesay:latest'
        resources: {}
        source: |
          #!/bin/sh
          true
```

**Comment by alexec** [comment]
Interplay with entrypoint?

**Comment by guoweis-outreach** [comment]
I tried this but still receives the same error
source: |
        #!/bin/sh
        az storage entity query -t mytable --filter "PartitionKey eq 'mytest'"

```
OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/argo/staging/script\": permission denied": unknown
```

**Comment by guoweis-outreach** [comment]
oh, but adding this with that does.
       command: [sh]

**Comment by alexec** [comment]
Solution for this is to use `command`:

```yaml
  script:
        image: 'docker/whalesay:latest'
        command: [sh]
        source: |
          true
```
