### ISSUE TITLE
Make it possible to parametrize `retryStretegy.limit`

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo-workflows#3646]
# Summary

If retry count can be parametrize using workflow parameter it would really help us. 

# Motivation

We have standard workflow templates which are being used for multiple use cases. We need to set retry count for different usecase depending on user input

Example:
```
# This example demonstrates the use of retry back offs
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-backoff-
spec:
  arguments:
     parameters:
     - name: retry-count
  entrypoint: retry-backoff
  templates:
  - name: retry-backoff
    retryStrategy:
      limit: {{workflow.parameters.retry-count}}
      backoff:
        duration: "1"       # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
        factor: 2
        maxDuration: "1m" # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
    container:
      image: python:alpine3.6
      command: ["python", -c]
      # fail with a 66% probability
      args: ["import random; import sys; exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)"]
```

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by mehtadeepen** [comment]
@alexec @sarabala1979 If this is already possible, please let me know.

**Comment by sarabala1979** [comment]
Not possible now. The limit is `int` type and will not accept string

**Comment by simster7** [comment]
I am working on a PoC to see if allowing behavior like this is possible. See https://github.com/argoproj/argo/pull/3610

**Comment by alexec** [comment]
```golang
// RetryStrategy provides controls on how to retry a workflow step
type RetryStrategy struct {
	// Limit is the maximum number of attempts when retrying a container
	Limit *int32 `json:"limit,omitempty" protobuf:"varint,1,opt,name=limit"`

	// RetryPolicy is a policy of NodePhase statuses that will be retried
	RetryPolicy RetryPolicy `json:"retryPolicy,omitempty" protobuf:"bytes,2,opt,name=retryPolicy,casttype=RetryPolicy"`

	// Backoff is a backoff strategy
	Backoff *Backoff `json:"backoff,omitempty" protobuf:"bytes,3,opt,name=backoff,casttype=Backoff"`
}
```

Change limit to `intorstr.IntOrStr`.

**Comment by alexec** [comment]
@simster7 to add work-around.

**Comment by simster7** [comment]
Ugly, but functional, workaround:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  arguments:
    parameters:
      - name: retries
        value: 2
  templates:

  - name: hello-hello-hello
    inputs:
      parameters:
        - name: retries
    steps:
    - - name: try1
        template: whalesay
        continueOn:
          failed: true
    - - name: try2
        template: whalesay
        when: "1 <= {{inputs.parameters.retries}} && {{steps.try1.status}} == Failed"
        continueOn:
          failed: true
    - - name: try3
        template: whalesay
        when: "2 <= {{inputs.parameters.retries}} && {{steps.try2.status}} == Failed"
        continueOn:
          failed: true
    - - name: try4
        template: whalesay
        when: "3 <= {{inputs.parameters.retries}} && {{steps.try3.status}} == Failed"
        continueOn:
          failed: true
    - - name: try5
        template: whalesay
        when: "4 <= {{inputs.parameters.retries}} && {{steps.try4.status}} == Failed"
        continueOn:
          failed: true
    - - name: try6
        template: whalesay
        when: "5 <= {{inputs.parameters.retries}} && {{steps.try5.status}} == Failed"
        continueOn:
          failed: true

  - name: whalesay
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["exit 1"]
```
