### ISSUE TITLE
Cron workflow time parameters

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#3649]
# Summary

It could be useful to have a parameter that is passed to workflows created from a cron that states the time of the cron schedule.

# Motivation

This could be potentially useful in backfill scenarios.

# Proposal

How do you think this should be implemented?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@sarabala1979 are you doing thisplease?

**Comment by kangtiann** [comment]
we need this too !!!!
Is someone working for this ?

we can achieve this feature if need.

**Comment by sarabala1979** [comment]
I will work on this. this has 9 thumbs. There is a workaround you can use `workflow.creationTimestamp`

**Comment by simster7** [comment]
Annoying workaround, but the large number at the end of the workflow name that is started by a cron workflow is the UNIX timestamp of its schedule time. So by using `{{pod.name}}` you can extract its scheduled time

**Comment by alexec** [comment]
I think we can do this with an annotation? (I don't think a label would be correct).

then can we do something like `{{workflow.annotations.cronScheduleTime}}`?

**Comment by sarabala1979** [comment]
@simster7 @alexec  I think we can pass as a workflow parameter `{{workflow.parameters.schedule_time}}`, so it can be use as a resolvable variable across the workflows. I am working on change. I will demo today or tomorrow.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "* * * * *"
  timezone: "America/Los_Angeles"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: docker/whalesay:latest
          command: [cowsay]
          args: ["🕓 hello world {{workflow.parameters.schedule_time}}"]
```
