### ISSUE TITLE
WorkflowTemplate with required parameters

### ISSUE THREAD

**Issue by laymain** [argoproj/argo-workflows#3743]
# Summary

It would be nice to allow WorkflowTemplate to have required parameters that **must** be provided on submission.

# Use Cases

I'm using a fully parameterized WorflowTemplate and I would like to be able to declare required parameters  
without default value and to fail if these required parameters are not provided on `submit`.

Let's say that we have a WorkflowTemplate to delete some data on a period:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
spec:
  entrypoint: data-deletion
  arguments:
    parameters:
      - name: inclusive-start-date
      - name: exclusive-end-date
      - name: dry-run
        value: false
...
```

Defining the period (`inclusive-start-date` and `exclusive-end-date`) is required and default value makes no sense here.

Besides, defaut values are risky, if we submit a Workflow and forget to provide a parameter  
or even make a typo in a parameter name, it will **silently** use its default value.
In such a case, I'd rather like to receive an error on submission.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
