### ISSUE TITLE
Cron Backfill example doesn't work

### ISSUE THREAD

**Issue by d-e-solutions** [argoproj/argo-workflows#3807]
## Summary

I was trying a functionality that is required for our use case: cron backfill. I took the examples from this page : https://argoproj.github.io/argo/cron-backfill/, but unfortunately it doesn't work. 

Here is the complete file
```
# This is an example of back-filling day for a daily cron workflow.
# See ../docs/cron-backfill.md
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: job
spec:
  arguments:
    parameters:
      - name: date
  templates:
    - name: main
      inputs:
        parameters:
          - name: date
            value: "{{inputs.parameters.date}}"
            # use "yesterday" is a magic value to tell the script it needs to determine the day to run
            default: yesterday
      script:
        image: docker/whalesay:latest
        command:
          - sh
        source: |
          date="{{inputs.parameters.date}}"
          if [ $date = yesterday ]; then
            date=$(date -d yesterday +%Y-%m-%d)
          fi
          echo "run for $date"
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: daily-job
spec:
  # run daily at 2am
  schedule: "0 2 * * *"
  workflowSpec:
    workflowTemplateRef:
      name: job
---
# This version will create jobs as fast as it can - not waiting for
# each to complete. Use this when you really need each workflow separate.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: backfill-v1
spec:
  entrypoint: main
  # the backfill must use a service account which can create workflows
  # you should not - despite this example - use "argo-server"
  serviceAccountName: argo-server
  templates:
    - name: main
      steps:
        - - name: day
            template: create-job
            arguments:
              parameters:
                - name: date
                  value: "{{item}}"
            withSequence:
              # run for the 19th to the 21st
              start: "19"
              end: "21"
              format: "2020-05-%02X"
    - # this template creates each workflow
      name: create-job
      inputs:
        parameters:
          - name: date
      resource:
        action: apply
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            # using a name based on the date prevents re-creating resources,
            # making this more robust
            name: job-{{inputs.parameters.date}}
          spec:
            entrypoint: main
            templates:
              - name: main
                steps:
                  - - name: start-job
                      arguments:
                        parameters:
                          - name: date
                            value: "{{inputs.parameters.date}}"
                      templateRef:
                        name: job
                        template: main
---
# This version creates each job as part of the workflow, and limits concurrent jobs using
# `spec.parallelism`
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: backfill-v2
spec:
  entrypoint: main
  # limit to one job at a time
  parallelism: 1
  templates:
    - name: main
      steps:
        - - name: create-job
            templateRef:
              name: job
              template: main
            arguments:
              parameters:
                - name: date
                  value: "{{item}}"
            withSequence:
              # run for the 19th to the 21st
              start: "19"
              end: "21"
              format: "2020-05-%02X"
```

When I try to submit the WorkflowTemplate, I get this error :
```spec.arguments.date.value is required```

When I try to submit the cron workflow, it throws the following error:
```Invalid CronWorkflow: metadata.namespace cannot be blank```
I then add a namespace to it, but I get the following error :
```cannot validate Workflow: spec.entrypoint is required```

I am a complete beginner, so I did not dive into the details but I think you should know examples in your doc doesn't work.

## Diagnostics

What version of Argo Workflows are you running?
```
argo: v2.10.0-rc7+267da53.dirty
  BuildDate: 2020-08-14T00:41:49Z
  GitCommit: 267da535b66ed1dab8bcc90410260b7cf4b80e2c
  GitTreeState: dirty
  GitTag: v2.10.0-rc7
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
The patch fixes the issue on master:

```
diff --git a/examples/cron-backfill.yaml b/examples/cron-backfill.yaml
index 5f35e211..15982981 100644
--- a/examples/cron-backfill.yaml
+++ b/examples/cron-backfill.yaml
@@ -8,6 +8,7 @@ spec:
   arguments:
     parameters:
       - name: date
+        value: yesterday
   templates:
     - name: main
       inputs:
@@ -35,6 +36,7 @@ spec:
   # run daily at 2am
   schedule: "0 2 * * *"
   workflowSpec:
+    entrypoint: main
     workflowTemplateRef:
       name: job
 ---
```

But this used to work - so what changed?

@bnoeson can you tell me which version of Argo Workflows you are using?

**Comment by alexec** [comment]
@sarabala1979 I think this behaviour has changed and you have been working in this area. To get this working I had to add `entrypoint`:

```
  workflowSpec:
    entrypoint: main
    workflowTemplateRef:
      name: job
```
