### ISSUE TITLE
Getting the parent status about Dag or Step

### ISSUE THREAD

**Issue by sh-tatsuno** [argoproj/argo-workflows#3829]
# Summary

I want to get the parent's status in onExit function except Job Level Callback.

# Use Cases

I want to use onExit function for using callback function based on the final task status.

for example:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-primay-branch-
spec:
  entrypoint: status
  templates:
  - name: a
    container:
      image:  docker/whalesay:latest
      command: ["sh", "-c"]
      args: ["sleep 1 && echo good morning"]
  - name: exit
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["exit!"]
  - name: steps-exit
    steps:
      - - name: step-exit
          template: exit
      - - name: step-exit-b
          when: '{{parent.A.status}} in (Failure, Error)' // <- do not work
          template: exit
  - name: steps
    steps:
      - - name: step-a
          template: a
  - name: status
    dag:
      tasks:
      - name: A
        onExit: steps-exit
        template: steps
```
