### ISSUE TITLE
Refer to parameters of parents nodes from onExit nodes in Dag or Steps

### ISSUE THREAD

**Issue by sh-tatsuno** [argoproj/argo-workflows#3840]
# Summary

Parameters & status can be used in onExit nodes in Dag or Steps like workflow level onExit.

# Use Cases

Use when run callback functions run based on the status of it's parent's node

Like below

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-primay-branch-
spec:
  entrypoint: status
  templates:
  - name: a
    container:
      image:  docker/whalesay:latest
      command: ["sh", "-c"]
      args: ["echo good morning"]
  - name: b
    container:
      image:  docker/whalesay:latest
      command: [cowsay]
      args: ["the task finished successfully"]
  - name: c
    container:
      image:  docker/whalesay:latest
      command: [cowsay]
      args: ["the task failed"]
  - name: exit-steps
    steps:
      - - name: success-callback
          template: b
          when: '{{tasks.A.status}} == Succeeded' // <- like this, but it has a problem if the name is duplicated
        - name: failure-callback
          template: c
          when: '{{tasks.A.status}} != Succeeded' // <- like this
  - name: status
    dag:
      tasks:
      - name: A
        template: a 
        onExit: exit-steps // want to get the params of A such as name, status
```

This is my implementation example (not completed)

https://github.com/sh-tatsuno/argo/commit/5dade0af8b4e56e5c8dbf7b5f8896ebd0fb17e37

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
