### ISSUE TITLE
WorkflowTemplate cannot work together with DAG?

### ISSUE THREAD

**Issue by ozooxo** [argoproj/argo-workflows#3843]
# Summary

From doc https://argoproj.github.io/argo/examples/#dag using DAG I need `templates:` with some traditional template and a DAG template which refers to the previous templates. From doc https://argoproj.github.io/argo/workflow-templates/ we `workflowTemplateRef` and do not still have `templates:`. There seems no way for me to setup a DAG which refers to a workflow template?

I tried some

```
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  workflowTemplateRef:
    name: workflow-template-submittable
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: workflow-template-submittable
        arguments:
          parameters: [{name: foo, value: "bar"}]
```

and it replies `Templates is invalid field in spec if workflow referred WorkflowTemplate reference`.

# Use Cases

I'd like a DAG which each step refers to a workflow template.
