### ISSUE TITLE
RetryStrategy Not working in the template which has withParams attribute : gives no output to next step

### ISSUE THREAD

**Issue by PranjaliSoni** [argoproj/argo-workflows#3981]
## Summary 
**Retry Doesn't work with WithParams
Empty Output to Next Step**

Tried a workflow with simply dividing by 2 step and printing in next step. The step which has loop(i.e. withParams breaks with retry and gives empty output to the next step) . Works fine without retryStrategy
## Diagnostics

2.10.0

```
# Example workflow to demonstrate parameter aggregation.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameter-aggregation-
spec:
  entrypoint: parameter-aggregation
  templates:
  - name: parameter-aggregation
    steps:
    - - name: divide-by-2
        template: divide-by-2
        arguments:
          parameters:
          - name: num
            value: "{{item}}"
        withItems: [1, 2, 3, 4]
    # Finally, print all numbers processed in the previous step
    - - name: print
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withParam: "{{steps.divide-by-2.outputs.result}}"

  # divide-by-2 divides a number in half
  - name: divide-by-2
    retryStrategy: 
        limit: 2
        backoff: 
            duration: "1"
            factor: 2
    inputs:
      parameters:
      - name: num
    script:
      image: alpine:latest
      command: [sh, -x]
      source: |
        #!/bin/sh
        echo $(({{inputs.parameters.num}}/2))
  # whalesay prints a number using whalesay
  - name: whalesay
    retryStrategy: 
        limit: 2
        backoff: 
            duration: "1"
            factor: 2
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

State with Retry of print Step
```
PHASE
 Skipped
MESSAGE
Skipped, empty params
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
