### ISSUE TITLE
Prevent retries to execute on the same Kubernetes nodes

### ISSUE THREAD

**Issue by salanki** [argoproj/argo-workflows#4085]
# Summary

In large, primarily on-prem Kubernetes clusters it is possible that a Kubernetes node has a hardware / software issue contributing to the failure of a Workflow step. When using retries, it is possible (and in some setups likely) that the Pod created for the retry will be scheduled on the same Kubernetes node, leading to the retry failing as well where it would not had the Pod been scheduled on a different node.

# Use Cases

This feature is applicable to primarily large clusters where physical nodes can go unhealthy without being properly detected by the Kubernetes control-plane.

# Implementation

https://github.com/argoproj/argo/pull/2732 brought in `hostNodeName` on the steps (execution steps in Argo are called Nodes, causing some confusion when discussing physical Kubernetes nodes in the same context). When the feature is enabled, we could keep a list of `hostNodeName`s on the Retry node. Then, when a retry is needed and the new Pod is scheduled the list of previous `hostNodeName`s is added on the new Pod spec as an anti affinity.

Resulting affinity:
```yaml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - previousHostNodeA
                - previousHostNodeB
```

These need to be merged with existing affinities that might come from the Workflow.

This feature should be disabled by default, as small clusters might need retries to execute on the same host. I suggest it be enabled via a flag on `retryStrategy` in the Workflow spec, ie:

```yaml
      retryStrategy:
        limit: 1
        sceduleOnDifferentHostNodes: true
```

(open to better suggestion of flag name)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by salanki** [comment]
Interesting, I don't really see how that will work but I am very interested in hearing it!

**Comment by jessesuen** [comment]
The way this may be possible is by:

1. Add a label to the container. e.g.:

```yaml
labels:
  dont-schedule-here: foo
```

2. Also add a podSpecPatch which has anti-affinity against the label defined above:

```yaml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dont-schedule-here
                operator: NotIn
                values:
                - foo
```

The label could be dynamic using workflow variables.

Note, I haven't tried the above, but thats how I think it might work today.
