### ISSUE TITLE
Workflows are not getting deleted after TTL seconds

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#4106]
## Summary 
The Workflows are not getting deleted even after TTL configured seconds on EKS clusters. Argo Cli delete is also not working.

What happened/what you expected to happen?

## Diagnostics
I can see the metadata has finalizers
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-09-22T05:30:59Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2020-09-22T05:32:06Z"
  finalizers:
  - foregroundDeletion
```

What version of Argo Workflows are you running?

```yaml
Paste the workflow here, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
