### ISSUE TITLE
support customization of labels and annotations in workload pod spec

### ISSUE THREAD

**Issue by MartinForReal** [argoproj/argo-workflows#4135]
# Summary

customize pod annotation and labels. 

# Use Cases

When would you use this?

disable istio pod auto injection
---
Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Here the example 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    metadata:
      labels:
        "test": "test"
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```
