### ISSUE TITLE
Workflow Controller Dies When Running several thousand pods

### ISSUE THREAD

**Issue by punjabdhaputar** [argoproj/argo-workflows#4140]
## Summary 

When running four concurrent workflows each with 1000 pods, the workflow controller died with no clear indication as to why it died

## Diagnostics

What version of Argo Workflows are you running?
v2.10.0

kubectl becomes unreachable as well with an I/O timeout error as well:
```
Unable to connect to the server: dial tcp 54.212.43.18:443: i/o timeout
```

Tail of logs from workflow controller
```
time="2020-09-27T06:27:56Z" level=warning msg="Deadline exceeded" namespace=argo-fresh2 workflow=1000genomes-workflow-wj4bd
time="2020-09-27T06:27:56Z" level=warning msg="Deadline exceeded" namespace=argo-fresh2 workflow=1000genomes-workflow-wj4bd
time="2020-09-27T06:27:56Z" level=warning msg="Deadline exceeded" namespace=argo-fresh2 workflow=1000genomes-workflow-wj4bd
time="2020-09-27T06:27:57Z" level=info msg="insignificant pod change" key=argo-fresh2/1000genomes-workflow-bph6p-3233233161
time="2020-09-27T06:27:58Z" level=info msg="Workflow update successful" namespace=argo-fresh2 phase=Running resourceVersion=12671221 workflow=1000genomes-workflow-wj4bd
time="2020-09-27T06:27:59Z" level=info msg="Processing workflow" namespace=argo-fresh2 workflow=1000genomes-workflow-wj4bd
time="2020-09-27T06:27:59Z" level=info msg="insignificant pod change" key=argo-fresh2/1000genomes-workflow-j6j2p-2746699568
time="2020-09-27T06:27:59Z" level=info msg="insignificant pod change" key=argo-fresh2/1000genomes-workflow-snqf8-1579490378
time="2020-09-27T06:27:59Z" level=info msg="insignificant pod change" key=argo-fresh2/1000genomes-workflow-j6j2p-3262559692
time="2020-09-27T06:28:00Z" level=info msg="insignificant pod change" key=argo-fresh2/1000genomes-workflow-snqf8-99511793
time="2020-09-27T06:28:01Z" level=info msg="insignificant pod change" key=argo-fresh2/1000genomes-workflow-wj4bd-1043985656
time="2020-09-27T06:28:02Z" level=info msg="insignificant pod change" key=argo-fresh2/1000genomes-workflow-wj4bd-2984316738
time="2020-09-27T06:28:02Z" level=info msg="insignificant pod change" key=argo-fresh2/1000genomes-workflow-j6j2p-3730332034
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Is it failing with OOM? can you provide the failed POD spec?

**Comment by alexec** [comment]
+1 to @sarabala1979. The pod's manifest will show why the pod was terminated and I bet it is OOM too.

**Comment by punjabdhaputar** [comment]
> +1 to @sarabala1979. The pod's manifest will show why the pod was terminated and I bet it is OOM too.

For the Pod's manifest, do you mean the manifest of the workflow-controller? If so, I have copied the manifest of the workflow-controller below:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --pod-workers
        - "64"
        - --workflow-workers
        - "64"
        - --qps
        - "40"
        - --burst
        - "60"
        - --executor-image
        - argoproj/argoexec:v2.10.0
        - --namespaced
        command:
        - workflow-controller
        image: argoproj/workflow-controller:v2.10.0
        resources:
          limits:
            cpu: "3"
            memory: 6000Mi
          requests:
            cpu: "3"
            memory: 6000Mi
        name: workflow-controller
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: argo
```
