### ISSUE TITLE
Send Workflow/Step/DAG status notification to external system via http (Slack/PagerDuty/API)

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#4152]
# Summary
Argo should send the status of  Workflow/Step/Dag  to an external system like slack/messaging system/pagerduty/API endpoint.

# Use Cases
User can configure their notification system to receive the status of workflow/step/DAG. User can configure more than one endpoint to send the status.

```yaml
notification:
   - name: slack
      endpoint: http://localhost:8080/api/wokflow/status
      workflowStatus:
           Failed: true
           Success: true
      stepStatus:
           Failed: true
           Success: true
      dagStatus:
           Failed: true
           Success: true
   - name: workflowSlack
      endpoint: http://localhost:8080/api/wokflow/status
      workflowStatus:
           Failed: true
           Success: true
```
Sample Workflow: 

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: whalesay
  notification:
   - name: slack
      endpoint: http://localhost:8080/api/wokflow/status
      workflowStatus:
           Failed: true
           Success: true
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

Nofitication Payload :
WorkflowStatus:
```JSON
{ "workflowName": "test", 
    "status": "Failed",
    "message": "step1 failed"
}
```
StepStatus:
```JSON
{ "workflowName": "test", 
    "stepName": "step",
    "status": "Failed",
    "message": "exit code 1"
}
```
DAGStatus:
```JSON
{ "workflowName": "test", 
    "dagName" : "task-1",
    "status": "Failed",
    "message": "exit code 1"
}
```
    
Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
