### ISSUE TITLE
Add successConditionDuration option for k8s resources

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#4177]
# Summary

When using successConditions for k8s resources during update operations the resource can already be in the correct state which causes the step to succeed. This is problematic when operators have delays in reconciling after an update action.

https://github.com/argoproj/argo/tree/master/examples#kubernetes-resources

# Use Cases

Our use case is a custom operator that has occasional delays at reconciling when it is busy.

One possibility is introducing a successConditionDurationSeconds that would wait for the state to be in the desired state for the specified duration. 
```
  templates:
  - name: pi-tmpl
    resource:                   
      action: apply
      [...]      
      successCondition: status.status == Synced
      successConditionDurationSeconds: 30
      [....]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by sarabala1979** [comment]
you can use `activeDeadlineSecond`to  fail the step if the successCondition is not meet within a given duration

```
templates:
  - name: pi-tmpl
     activeDeadlineSeconds: 30
    resource:                   
      action: apply
      [...]      
      successCondition: status.status == Synced
```

**Comment by blkperl** [comment]
@sarabala1979 We already use activeDeadlineSecond to fail the step in that case.  The issue we are seeing is something like the following:

```
status = Synced 
k8s update
status = Synced          # custom operator has not reconciled yet
argo step completes
status = Syncing        # custom operator has reconciled
status = Synced         # custom operator has finished it's update to dependent resources and reconciled
```

We need successCondition to be true for a duration let's say 30 seconds otherwise there is a chance that the resource can be in the correct state because the operator hasn't reconciled before the argo step checks the successCondition. 

```
status = Synced 
k8s update
status = Synced          # custom operator has not reconciled yet
argo step waits for status to be Synced for 30 seconds
status = Syncing        # custom operator has reconciled
status = Synced         # custom operator has finished it's update to dependent resources and reconciled
argo step completes once 30 seconds have elapsed
```

**Comment by sarabala1979** [comment]
you can use `suspendtemplate` for waiting duration. 

```YAML
templates:
  - name: main
     steps: 
      - - name: pi-tmpl
           template: pi-tmpl
      - - name: wait
           template: wait-tmpl

  - name: pi-tmpl
    resource:                   
      action: apply
      [...]      
      successCondition: status.status == Synced
 - name: wait-tmpl
    suspend:
        duration: "20"
```
