### ISSUE TITLE
Allow overriding image / tag from command line

### ISSUE THREAD

**Issue by max-sixty** [argoproj/argo-workflows#4187]
# Summary

Currently I think it's possible to override a few attributes from the command line — parameters, entrypoint, service account, and name. 

Would it be worthwhile to allow overriding image or the image tag too?

# Use Cases

I often find myself wanting to override the image or tag; because I've recently pushed a new version of an image. and want to test it. To the extent that's a common request, would there be support for being able to override that from the command line. I recognize that each task can have its own image, and so is a bit more complicated.

Of course if there's a better approach I'd appreciate the direction. Thanks as ever.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by max-sixty** [comment]
One approach that can work here is using the image as a workflow parameter:

```
  workflowSpec:
    entrypoint: foo
    arguments:
      parameters:
        - name: image
          value: gcr.io/foo/bar
...
    templates:
      - name: copy-from-vendor
        container:
          image: "{{workflow.parameters.image}}"
```

...and then the image can be passed from the command line like any other parameter.

Unfortunately I think this approach means that the image then can't be updated with kustomize, using [this approach](https://argoproj.slack.com/archives/C8J6SGN12/p1594143752125200?thread_ts=1594134743.122500&cid=C8J6SGN12) from Evan.

**Comment by max-sixty** [comment]
This is tangential to this issue, but in case others hit the same challenge I did, here's a way to get this approach working with kustomize:

`config.yaml`:
```yaml
images:
- path: spec/workflowSpec/templates/script/image
  kind: CronWorkflow
- path: spec/templates/script/image
  kind: WorkflowTemplate
- path: spec/workflowSpec/templates/container/image
  kind: CronWorkflow
- path: spec/templates/container/image
  kind: WorkflowTemplate
- path: spec/workflowSpec/templates/sidecars/image
  kind: CronWorkflow
- path: spec/templates/sidecars/image
  kind: WorkflowTemplate
```

`kustomization.yaml`:
```yaml
images:
  - name:  gcr.io/foo/bar
    newTag: 0.1.0
  - name: "{{workflow.parameters.image}}"
    newName: gcr.io/foo/bar
    newTag: 0.1.0

configurations:
- config.yaml
```
