### ISSUE TITLE
v2.11: workflow-controller-configmap serviceAccountName not being honored

### ISSUE THREAD

**Issue by ki-ichino** [argoproj/argo-workflows#4208]
## Summary 

`serviceAccountName` in `workflowDefaults` takes no effect.

## Diagnostics

> What version of Argo Workflows are you running?

v2.11.1

I created the following `workflow-controller-configmap` with a default `serviceAccountName`.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    workflowDefaults:
      spec:
        serviceAccountName: argo-workflow
```

I submitted a workflow omitting `serviceAccountName`.
So, I expected for Argo to use `argo-workflow` ServiceAccount specified in `workflowDefaults.spec`.
However, Argo used `default` ServiceAccount.

```
$ argo submit --log tutorial-01.yml
Name:                tutorial-01-xsn58
Namespace:           argo-tutorial
ServiceAccount:      default
Status:              Pending
Created:             Sun Oct 04 16:02:47 +0900 (now)
```

Actually, the pod ran as `default`.

```
$ kubectl get pod tutorial-01-xsn58-1084908792 -o yaml
apiVersion: v1
kind: Pod
spec:
  serviceAccount: default
  serviceAccountName: default
```

It's noted that the workflow resource has the expected `ServiceAccountName`.

```
$ kubectl get wf tutorial-01-xsn58 -o yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  serviceAccountName: argo-workflow
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
