### ISSUE TITLE
Allow setting workflow *input* parameters in UI

### ISSUE THREAD

**Issue by meurig** [argoproj/argo-workflows#4234]
# Summary

The user should be given the chance to set input parameters in the UI when submitting a workflow from a template.

The work done in https://github.com/argoproj/argo/issues/3498 is great, but it only works when (default?) values for the parameters have been set in arguments.parameters.

Instead I suggest both the list of inputs.parameters and arguments.parameters should be considered when presenting a list of parameters to the user.

# Use Cases

I have several workflow templates configured that take required parameters. I frequently submit these via the UI.

In version 2.10.0 I was able to paste in some arguments.parameters with values in the yaml and submit the workflow.

In version 2.9.0 I could do the same, but without values and specify the values in the UI.

As if 2.11.0 I'm unable to submit these workflow via the UI without adding arguments.parameters with default values to the workflowtemplate.spec:

![image](https://user-images.githubusercontent.com/507747/95382437-8e1f1e80-08e1-11eb-8d04-0ed020b50a7c.png)

Shows as no parameters:

![image](https://user-images.githubusercontent.com/507747/95382534-b149ce00-08e1-11eb-9117-3b2123966e99.png)

This appears to be the line in question:
https://github.com/alexec/argo/blob/d26ede0b6d132d5f8ddb40f6eabd97d53a182a74/ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx#L91

Instead of referencing this.state.template.spec.arguments.parameters I think it should get the inputs.parameters from whichever template/entrypoint is selected in the dropdown, possibly referencing arguments.parameters (of the same template/entrypoint?) to fill in some default values if they're specified.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Sounds good. Would you like to submit a PR?

**Comment by meurig** [comment]
Sadly I have other commitments (and no argo dev environment set up), so I can't at the moment - sorry!

**Comment by kennytrytek** [comment]
I'd be willing to take a stab at this one. Looks like https://github.com/argoproj/argo/blob/master/docs/running-locally.md has steps for local setup for iterating on the UI, so I should be good there.

**Comment by simster7** [comment]
This should already be on the newly merged UI. Please check before starting work

**Comment by kennytrytek** [comment]
Got the UI set up locally and confirmed this issue is still present in the latest commit in this repo.
<details><summary>Using this workflow template</summary>
<p>

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: whalesay
spec:
  entrypoint: whalesay-template
  arguments:
    parameters:
      - name: message
        value: hello
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: argoproj/argosay:v2
        args: ["echo", "{{inputs.parameters.message}}"]
        imagePullPolicy: IfNotPresent
    - name: whalesay-template-two
      inputs:
        parameters:
          - name: message-two
      container:
        image: argoproj/argosay:v2
        args: ["echo", "{{inputs.parameters.message-two}}"]
        imagePullPolicy: IfNotPresent

```

</p>
</details>

![submit-whalesay](https://user-images.githubusercontent.com/6892590/106842071-e89a7280-6668-11eb-889e-3279fe1863a0.gif)

It is expected that when I select the "whalesay-template-two" template in the dropdown, the parameters should update. They do not; the parameters from the first template are still shown.

I'll start looking at what code needs to change and open a PR when I can.
