### ISSUE TITLE
`workflowDefaults` in `workflow-controller-configmap` doesn't work?

### ISSUE THREAD

**Issue by ozooxo** [argoproj/argo-workflows#4246]
## Summary 

I added a customized `label` (as suggested by [this example](https://argoproj.github.io/argo/default-workflow-specs/)) and a `serviceAccountName` into the `workflowDefaults` section in `workflow-controller-configmap`. Both doesn't work.

## Diagnostics

What Kubernetes provider are you using? 

EKS.

What version of Argo Workflows are you running? 

```
kubectl exec -it argo-server-**** -- argo version
argo: v2.10.0
  BuildDate: 2020-08-18T23:15:20Z
  GitCommit: 195c6d8310a70b07043b9df5c988d5a62dafe00d
  GitTreeState: clean
  GitTag: v2.10.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```

Paste a workflow that reproduces the bug, including status:

I have my `workflow-controller-configmap` as seen below.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  workflowDefaults: |
    metadata:
      labels:
        foo: bar
    spec:
      serviceAccountName: argo
```

Created a trivial WorkflowTemplate

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cynthia-say
spec:
  entrypoint: cynthia-say
  templates:
  - name: cynthia-say
    container:
      image: busybox:1.32.0
      command: ["echo"]
      args: ["hello", "cynthia"]
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"
```

and they I can see (1) the label is not applied, and (2) the service account mounted is not the one I specified:

```
$ kubectl describe pod cynthia-say-xxxxx

...
Labels:             workflows.argoproj.io/completed=true
                    workflows.argoproj.io/workflow=cynthia-say-29nnv
Annotations:        kubernetes.io/psp: eks.privileged
                    workflows.argoproj.io/node-name: cynthia-say-29nnv
                    workflows.argoproj.io/template:
                      {"name":"cynthia-say","arguments":{},"inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"busybox:1.32.0","command":["ec...
...
Containers:
  wait:
  ...
    Mounts:
      ...
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qghdc (ro)
  main:
    ...
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qghdc (ro)
```

I should be getting the token from the right service account `/var/run/secrets/kubernetes.io/serviceaccount from argo-token-sm88z (ro)`.

**Comment by ediezh** [comment]
This is affecting me too. At first I noticed the default ttlStrategy is not working, but then on further investigation that all the workflow defaults are not applied. I have the below workflowDefaults configured.
```
workflowDefaults:
  metadata:
    annotations:
      argo: workflows
  spec:
    activeDeadlineSeconds: 86400
    ttlStrategy:
      secondsAfterCompletion: 7200
      secondsAfterSuccess: 7200
```

I'm running v2.11.2
