### ISSUE TITLE
Using Kustomize only works on argo namespace

### ISSUE THREAD

**Issue by max-sixty** [argoproj/argo-workflows#4247]
## Summary 

I'm not sure whether this is a problem with my approach, kustomize, or argo. I suspect the first, but posting here at least in case it's helpful for others — it took me a while to figure out what the problem was.

## Diagnostics

Run this with kustomize, noting the resources are namespaced to `argo-2`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-2
# namespace: argo
resources:
- https://github.com/argoproj/argo/manifests/cluster-install?ref=v2.11.3
```

But this still produces some resources that are namespaced to `argo`, noting the last line:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cluster-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo  # <- here
```

Argo server then wouldn't start.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
