### ISSUE TITLE
[UI]  Unknown error. Open your browser error console for more information.

### ISSUE THREAD

**Issue by hadim** [argoproj/argo-workflows#4297]
I tried argo 2.11.3 and 2.11.4. I don't remember seeing this issue using 2.10.*.

Sometimes on the main page after switching tab for a while I get the following message:

![Screenshot from 2020-10-15 18-43-40](https://user-images.githubusercontent.com/528003/96193725-d4463480-0f16-11eb-8a9e-9f2e8c8dd455.png)

Refreshing the page removes the error message and I can see the list of workflow again as normal.

---

Then when visualizing a workflow and clicking on the bell icon I have the same error:

![Screenshot from 2020-10-15 18-44-24](https://user-images.githubusercontent.com/528003/96193801-00fa4c00-0f17-11eb-9128-72f1d8475d26.png)

The JS error message is not always the same:

```
/api/v1/workflow-events/argo?listOptions.resourceVersion=55737240&fields=result.object.metadata.name,result.object.metadata.namespace,result.object.metadata.resourceVersion,result.object.metadata.uid,result.object.status.finishedAt,result.object.status.phase,result.object.status.startedAt,result.type,result.object.metadata.labels,result.object.spec.suspend:1 Failed to load resource: the server responded with a status of 502 ()
/api/v1/stream/events/argo?listOptions.fieldSelector=involvedObject.kind=Workflow,involvedObject.name=fantastic-poochenheimer:1 Failed to load resource: the server responded with a status of 403 ()
DevTools failed to load SourceMap: Could not parse content for https://xxxxxxxxxx.com/workflows/argo/swagger-ui.css.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://xxxxxxxxxx.com/workflows/argo/ReactToastify.css.map: Unexpected token < in JSON at position 0
/api/v1/workflow-events/argo?listOptions.fieldSelector=metadata.name=fantastic-poochenheimer:1 Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR
```

Here is another similar one:

```
/api/v1/workflow-events/argo?listOptions.resourceVersion=55737240&fields=result.object.metadata.name,result.object.metadata.namespace,result.object.metadata.resourceVersion,result.object.metadata.uid,result.object.status.finishedAt,result.object.status.phase,result.object.status.startedAt,result.type,result.object.metadata.labels,result.object.spec.suspend:1 Failed to load resource: the server responded with a status of 502 ()
/api/v1/stream/events/argo?listOptions.fieldSelector=involvedObject.kind=Workflow,involvedObject.name=fantastic-poochenheimer:1 Failed to load resource: the server responded with a status of 403 ()
/api/v1/workflow-events/argo?listOptions.fieldSelector=metadata.name=fantastic-poochenheimer:1 Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR
translate.js:1109 Uncaught (in promise) Error: getTranslators: detection is already running
    at Zotero.Translate.Web.<anonymous> (translate.js:1109)
    at Zotero.Translate.Web.getTranslators (promise.js:34)
    at Object.init (inject.js:104)
    at Object.historyChanged (inject.js:662)
    at messageListener (messaging_inject.js:122)
    at messaging_inject.js:132
/api/v1/workflow-events/argo?listOptions.resourceVersion=55768730&fields=result.object.metadata.name,result.object.metadata.namespace,result.object.metadata.resourceVersion,result.object.metadata.uid,result.object.status.finishedAt,result.object.status.phase,result.object.status.startedAt,result.type,result.object.metadata.labels,result.object.spec.suspend:1 Failed to load resource: the server responded with a status of 502 ()
DevTools failed to load SourceMap: Could not parse content for https://xxxxxxx/workflows/swagger-ui.css.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://xxxxxxx/workflows/ReactToastify.css.map: Unexpected token < in JSON at position 0
```

---

Besides those errors everything looks fine: the workflows run correctly we can see the logs as well as the DAG on the UI.

`argo-server` is deployed on GKE behind an ingress using HTTPS (I also tried HTTP and have the same error).

Also, I don't see anything wrong in the logs of `argo-server` (running on 3 replicates) as well as the controller.

Let me know if you need more informations.

**Comment by alexec** [comment]
You appear to be opening the new events tab and you are getting a 403 error. This is because the user does not have permission to watch events. Please look at this example to fix:

https://github.com/argoproj/argo/blob/master/manifests/namespace-install/argo-server-rbac/argo-server-role.yaml#L31

**Comment by hadim** [comment]
I was still using a custom argo-role unmodified since the bump in version. Thank you @alexec , the new role fixed it.

**Comment by hadim** [comment]
Now the role is fixed, I can see the events for every workflow (very nice feature by the way).

That being said I still see this " Unknown error. Open your browser error console for more information." message on the UI (see above screenshot).

```
/api/v1/workflow-events/argo?listOptions.resourceVersion=56265595&fields=result.object.metadata.name,result.object.metadata.namespace,result.object.metadata.resourceVersion,result.object.metadata.uid,result.object.status.finishedAt,result.object.status.phase,result.object.status.startedAt,result.type,result.object.metadata.labels,result.object.spec.suspend:1 Failed to load resource: the server responded with a status of 502 ()
```

The way I can reproduce it is:

- go to the main workflow page: `/workflows/argo` (Fargo namespace): here I can see the list of running and completed workflows.
- switch tab and do something else for a few minutes.
- go back to the main workflow tab and "sometimes" (often) the message appears. II feel like it depends how long I wait, usually, the error shows up after a couple of minutes.

I also this error when doing the same steps but on the event page of a workflow: `/workflows/argo/workflow-test-rtk2m?tab=events&nodeId=null` for example.

In both cases, refreshing the page works and everything go back to normal.

**Comment by alexec** [comment]
502 is a proxy error. What proxy are you using? They often need extra config to work with HTTP2.

**Comment by hadim** [comment]
I am using GKE with the GKE built-in ingress. I enabled HTTP2 following the doc from https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-http2. The configuration works seeing:

```bash
$ gcloud compute backend-services list
NAME                            BACKENDS                                               PROTOCOL
k8s-be-32337--xxxxxxx  us-central1-c/instanceGroups/k8s-ig--xxxxxxx  HTTP2
```

as specified in the doc but I still see the error.

It might be a tricky configuration thing I am missing. Feel free to close if you don't think this is related to argo.

Thanks again for the help.

**Comment by alexec** [comment]
I would recommend checking out other argo issues that mention ingresses.

**Comment by hadim** [comment]
For the record, the example from the GKE documentation works but I have an `UNKNOWN STATE` error on the GKE ingress backend service when trying to use HTTP/2.

Here is the spec I am using:

```yaml
# The below spec is an attempt to make argo works over HTTP/2 over the GKE ingress.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-h2
spec:
  selector:
    matchLabels:
      app: argo-h2
  template:
    metadata:
      labels:
        app: argo-h2
    spec:
      containers:
        - args: [server, --auth-mode, client, --namespaced]
          image: argoproj/argocli:v2.11.5
          name: argo-h2
          ports:
            - containerPort: 2746
              name: h2-port
          readinessProbe:
            httpGet:
              path: /
              port: 2746
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 20
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: argo-remote
---
apiVersion: v1
kind: Service
metadata:
  name: argo-service-h2
  annotations:
    cloud.google.com/app-protocols: '{"h2-port":"HTTP2"}'
  labels:
    app: argo-h2
spec:
  type: NodePort
  ports:
    - name: h2-port
      port: 2746
      targetPort: 2746
  selector:
    app: argo-h2
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo-ingress-h2
spec:
  backend:
    serviceName: argo-service-h2
    servicePort: 2746
```

The `gcloud compute backend-services list` command correctly shows that HTTP2 is used.

After the ingress has been created (check on the GKE dashboard), the ingress shows the following error: ` Some backend services are in UNKNOWN state` and access to the endpoint IP returns a 502 error.

I can't find more error messages looking at the backend service related to the ingress.

---

If someone has the same issue on GKE and found a solution, please let us know here.

**Comment by hadim** [comment]
Continuing my investigations.

If I keep all the other components the same (`Service` and `Ingress`) and only replace the `argo-server` in `Deployment` by:

```yaml
      containers:
        - name: argo-h2
          image: k8s.gcr.io/echoserver:1.10
          ports:
            - containerPort: 8443
```

Then I can access to the ingress endpoint and obtain the following:

```bash

Hostname: argo-h2-58c99fd9cd-ksz28

Pod Information:
	-no pod information available-

Server values:
	server_version=nginx: 1.13.3 - lua: 10008

Request Information:
	client_address=xxxxxx
	method=GET
	real path=/
	query=
	request_version=2
	request_scheme=https
	request_uri=https://xxxxxx:8443/

Request Headers:
	accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
	accept-encoding=gzip, deflate, br
	accept-language=fr-FR,fr;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6
	cache-control=max-age=0
	dnt=1
	host=34.120.230.216
	sec-fetch-dest=document
	sec-fetch-mode=navigate
	sec-fetch-site=cross-site
	sec-fetch-user=?1
	upgrade-insecure-requests=1
	user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
	via=1.1 google
	x-client-data=CgTGzpsV
	x-cloud-trace-context=1f3af07f62df2c4a6f942414050c8ea7/12229719372054769173
	x-forwarded-for=xxxxxxx
	x-forwarded-proto=https

Request Body:
	-no body in request-

```

meaning that indeed HTTP2 works between the LB and the pod.

I tried using `argoproj/argocli:v2.11.5` with and without ` --secure, --insecure-skip-verify,` but got a 502 errors in both cases. Pod's logs show nothing.
