### ISSUE TITLE
Configure artifacts using URIs, e.g `s3://my-bucket/my-key`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4349]
# Summary

It might be convenient and more compact to represent artifacts by URIs. A bit like [go getter](https://github.com/hashicorp/go-getter), but with the option to put as well as get.

# Use Cases

Add more repositories. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Local files
Git
Mercurial
HTTP
Amazon S3
Google GCP

We'd also need:

* Raw
* Artifactory (maybe just use HTTP)
* OSS

How do you do secrets?

**Comment by Ark-kun** [comment]
>go getter,

Does go-getter support canonical storage URIs? E.g. gs:// s3:// http:// etc.

> How do you do **secrets?**

Maybe we can have a configmap that can specify authentication for **all** URI schemes.
The confimap can be per-cluster or specified per-workflow (like `ArtifactRepositoryRef`)

In the future we could also make it possible to specify auth/secrets per-bucket.


P.S. I do not have a big stake in this.
The scenarios that could be useful to me is:
* Upstream produces a URI (e.g. "gs://my-bucket/file.txt") via an Argo parameter, then downstream consumes it as a file (Argo artifact).
* Upstream produces an artifact, downstream wants to receive a URI for that artifact as an input parameter.
There are workarounds for these scenarios now, but they're pretty cumbersome or even impossible. For example, given a URI, some intermediate template could split it into scheme, bucket an key and output those as separate parameters that can be plugged into the downstream's `s3` structure.
It would be easier if we could do:

```
name: downstream
inputs:
  parameters:
  - name: input1-uri
  artifacts:
  - name: input1
    path: ...
    uri: {{inputs.parameters.input1-uri}}
```

```
name: dag-task-1
template: downstream
arguments:
  parameters:
  - name: input1-uri
     valueFrom: {{tasks.upstream.outputs.parameters.some-uri}}
```
