### ISSUE TITLE
Workflow parameters aren't visible in the UI

### ISSUE THREAD

**Issue by d-e-solutions** [argoproj/argo-workflows#4418]
# Summary

As a user of the Argo UI interface, I would like to be able to see the argument parameters used to trigger a Workflow.

# Use Cases

I create my workflows based on a WorkflowTemplate. This WorkflowTemplate has some arguments, as a date for example.

```
spec:
...
  arguments:
    parameters:
      - name: DATE
        value: {{workflow.creationTimestamp.Y}}-{{workflow.creationTimestamp.m}}-{{workflow.creationTimestamp.d}}
```

Workflows are created :
- On a timely basis by CronWorkflow
- Manually through the UI by clicking the submit button on the WorkflowTemplate page, and providing the arguments.

When using those 2 ways, I don't see on any place in the UI the arguments that were used to trigger the workflow. For now I have to check the logs, which is not convenient at all.

I would like to have the possibility to see the value of the DATE argument here, as : DATE=2020-10-29, so I know for which date the workflow was run.

I am using version v2.11.6.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
