### ISSUE TITLE
tasks.TASK_NAME.status failed to resolve

### ISSUE THREAD

**Issue by Sharathmk99** [argoproj/argo-workflows#4430]
## Summary 

What happened/what you expected to happen?

> Passing in variables tasks.TASK_NAME.status causes a failed to resolve error.
> `Internal Server Error: templates.main.tasks.task2 templates.task2-template: failed to resolve {{tasks.task1.status}}`

## Diagnostics

What Kubernetes provider are you using? 
`AKS`
What version of Argo Workflows are you running? 
`v2.11.3`

Workflow Sample:
```yaml
metadata:
  name: xyz-
  generateName: xyz-
  namespace: ml-workflow
spec:
  templates:
    - name: main
      dag:
        tasks:
          - name: task1
            template: task1-template
          - name: task2
            template: task2-template
    - name: task1-template
      container:
        name: task1
        image: alpine:latest
    - name: task2-template
      container:
        name: task2
        image: alpine:latest
        env:
          - name: INPUT_PATH
            value: "{{tasks.task1.status}}"
  entrypoint: main
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
are you getting this error in CLI or server log?

**Comment by Sharathmk99** [comment]
I tried submitting via UI and also via python. I didn't try using cli

**Comment by sarabala1979** [comment]
the template name is missing in variable `"{{main.tasks.task1.status}}"`
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: xyz
  generateName: xyz-
  namespace: argo
spec:
  templates:
    - name: main
      dag:
        tasks:
          - name: task1
            template: task1-template
          - name: task2
            template: task2-template
    - name: task1-template
      container:
        name: task1
        image: alpine:latest
    - name: task2-template
      container:
        name: task2
        image: alpine:latest
        env:
          - name: INPUT_PATH
            value: "{{main.tasks.task1.status}}"
  entrypoint: main
```

**Comment by Sharathmk99** [comment]
HI @sarabala1979 ,

Thank you for quick response. I tried with template name, now i don't get any error but status value is not replaced. Please find below sample workflow,

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: xyz
  generateName: xyz-
  namespace: argo
spec:
  templates:
    - name: main
      dag:
        tasks:
          - name: task1
            template: task1-template
          - name: task2
            template: task2-template
            dependencies: ["task1"]
    - name: task1-template
      container:
        name: task1
        image: alpine:latest
    - name: task2-template
      container:
        name: task2
        image: alpine:latest
        command: ["printenv"]
        env:
          - name: INPUT_PATH
            value: "{{main.tasks.task1.status}}"
  entrypoint: main
```

Task2 Logs(First 3 lines),

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=xyz-563385519
INPUT_PATH={{main.tasks.task1.status}}
```

Please suggest how to make sure status is replaced.

Thanks.
