### ISSUE TITLE
read some symbol encoded when read parameter by loop

### ISSUE THREAD

**Issue by na-bot-o** [argoproj/argo-workflows#4431]
## Summary 

What happened/what you expected to happen?

Some symbol is read as encoding when loop workflow by parameter list

## Diagnostics

What Kubernetes provider are you using? 
`GKE` and `minikube` 
What version of Argo Workflows are you running? 
`v2.11.4`

### Workflow Sample:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: read-parameter
spec:
  entrypoint: read-parameter
  templates:
  - name: read-parameter
    steps:
    - - name: read-parameter
        template: read-parameter-by-items
        arguments:
          parameters:
          - name: value
            value: “{{item.value}}"
        withItems:
        - { value: hoge > fuga}
        - { value: 'hoge > fuga'} 
        - { value: hoge < fuga'} 
        - { value: hoge & fuga} 
  - name: read-parameter-by-items
    inputs:
      parameters:
      - name: value
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.value}}"]
```

### results(workflow name by list):
```
read-parameterv2d4q[0].read-parameter(0:value:hoge \u003e fuga)
read-parameterv2d4q[0].read-parameter(1:value:hoge \u003e fuga)
read-parameterv2d4q[0].read-parameter(2:value:hoge \u003c fuga')
read-parameterv2d4q[0].read-parameter(3:value:hoge \u0026 fuga)
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
