### ISSUE TITLE
Sub-Templates that can be merged with templates during creation

### ISSUE THREAD

**Issue by snowzach** [argoproj/argo-workflows#4480]
# Summary

It would be awesome to have a sub-template configuration that could be included/merged with an existing templates. (Kinda like Kubernetes PodPresets)

# Use Cases

Examples: 
* Node Selector / Toleration configuration to get a workflow step to run on specific nodes 
* Sidecar configuration to include an SQL proxy sidecar

I was thinking about this from the standpoint of creating a mutating admission controller webhook but couldn't find a decent one that did what I wanted. It would be ideal if this could just be a resource where you could reference a partial template that gets merged. 

The tolerations/node selector config could schedule for lots of different node types and with a simple annotation you could send a workflow to a specific node. (In my case, I want to keep the nodes shutdown unless I'm running the workflow)

Also, I would like to be able to easily inject proxy sidecars into workflows without having to specify the full configuration. 

Another option would just be a way to include parametrically include yaml when writing templates. 

If there's a way to do this already, I haven't found it yet.

---

**Message from the maintainers**:
Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
How would you envisage configuring this behaviour?

**Comment by snowzach** [comment]
I think honestly the schema could be that of a normal template and then some option that "merges" the two templates together. Anything with the same `name` could either combine or replace if that's easier... Probably a lot easier to implement if it replaces things with duplicate names. 

So a template example I would find useful is for a Google SQL Proxy Sidecar

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: argo
  name: sidecars
spec:
  templates:
    - name: cloudsql-proxy-sidecar
      sidecars:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          imagePullPolicy: IfNotPresent
          command: ["/cloud_sql_proxy",
                    "-instances={{{inputs.parameters.project}}:{{inputs.parameters.region}}:{{inputs.parameters.instance}}=tcp:0.0.0.0:{{inputs.parameters.listen_port}}",
                    "-credential_file=/credentials/service_account.json"]
          volumeMounts:
            - name: credentials
              mountPath: /credentials
              readOnly: true
          resources:
            limits:
              cpu: 150m
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: credentials
          secret:
            secretName: cloud-sql-secrets
      inputs:
        parameters:
          - name: listen_port
            value: "5432"
          - name: project
          - name: region
          - name: instance
```

And then in my main template I could import it as a "template preset" (much like the somewhat unsupported Kubernetes PodPreset):
```

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
spec:
  entrypoint: main-workflow
  arguments:
    parameters:
      - name: project
        value: "someproject"
      - name: region
        value: "us-east1"
      - name: instance
        value: "db1"
  templates:
  - name: main-workflow
    inputs:
      parameters:
        - name: nextcloud_base_dir
        - name: query
        - name: force
    steps:
      - - name: some-workflow-that-uses-sql-proxy
          templatePreset:
            - name: sidecars
              template: cloudsql-proxy-sidecar
              strategy: replace / merge <- Honestly replace would be fine/enough for me
          container:
            image: registry/mysqlcontainer:latest
            resources:
              requests:
                memory: 64Mi
                cpu: 100m
            command: [whatever]
            env:
            - name: DATABASE_HOST
              value: "localhost:5432"
          inputs:
            parameters:
            - name: project
              value: "{{workflow.parameters.project}}"
            - name: region
              value: "{{workflow.parameters.region}}"
            - name: instance
              value: "{{workflow.parameters.instance}}"
```
