### ISSUE TITLE
Weird argument arrangement when using script template

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-workflows#4481]
# Summary

I wanted to add a template that is activated on a workflow exit (the `onExit` field) with a purpose of notifying the user about the workflow status. I decided to use a template of type `script`, like this:

```YAML
name: "workflow-status-test"
script: 
 image: "python:3.6-alpine"
 command:
  - python3
 args:
  - "{{workflow.status}}"
 source: "import sys; import my_notify_func; my_notify_func(sys.argv[1])"
```

This failed. After inspecting the pod, I saw that Argo passed the arguments to the python container in the following way `Succeeded /argo/staging/script`, I would expect it to do it like this `/argo/staging/script Succeeded`.

Later I noticed in one of your examples in git repo that I could embed a template directly in the `source` field. But this wasn't documented anywhere (at least I didnt see it). So, this solves my issue:

```YAML
name: "workflow-status-test"
script: 
 image: "python:3.6-alpine"
 command:
  - python3
 source: "import my_notify_func; my_notify_func('{{workflow.status}}')"
```

The order in which the arguments are passed is unintuitive and I don't see a case where this particular order would be useful. My suggestion is to change the order (so first goes the script path, and then the user args) or put a notice/disclaimer in the docs. Also, you could provide an example for using templates [here](https://argoproj.github.io/argo/examples/), or document it.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Why not do this:

```yaml
name: "workflow-status-test"
script: 
 image: "python:3.6-alpine"
 command:
  - python3
 source: |
   import sys; import my_notify_func; my_notify_func("{{workflow.status}}")
```
