### ISSUE TITLE
BASE_HREF=/argo/ does not result in <base href=/argo/> tag.

### ISSUE THREAD

**Issue by jfreuter-finnet** [argoproj/argo-workflows#4485]
## Summary 

I am trying to set up Argo Workflows behind a Kong Ingress Controller.  When I access argo through the ingress, I get the main html page, but not any linked resources. This results in a blank page.

I have configured the base BASE_HREF environment variable to "/argo/" and I can see in the argo server logs that baseHRef is set to "/argo/". Howevery, the html contains `<base href="/" >` instead of the expected `<base href="/argo/">`

## Diagnostics

What Kubernetes provider are you using?  Azure / AKS

What version of Argo Workflows are you running? 2.11.7

Deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: argoworkflows
  name: argo-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
        - args:
            - server
            - '--namespaced'
            - '--auth-mode'
            - server
            - '--auth-mode'
            - client
          env:
            - name: BASE_HREF
              value: /argo/
          image: 'argoproj/argocli:v2.11.7'
          name: argo-server
          ports:
            - containerPort: 2746
              name: web
          readinessProbe:
            httpGet:
              path: /
              port: 2746
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: argo-server
      volumes:
        - emptyDir: {}
          name: tmp
```
argo-server logs:

```
time="2020-11-06T15:53:03Z" level=info authModes="[server client]" baseHRef=/argo/ managedNamespace=default namespace=default secure=false
time="2020-11-06T15:53:03Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/a
rgo/tls/"
time="2020-11-06T15:53:03Z" level=info msg="config map" name=workflow-controller-configmap
time="2020-11-06T15:53:03Z" level=info msg="SSO disabled"
time="2020-11-06T15:53:03Z" level=info msg="Starting Argo Server" instanceID= version=v2.11.7
time="2020-11-06T15:53:03Z" level=info msg="Creating DB session"
time="2020-11-06T15:53:03Z" level=info msg="Node status offloading config" ttl=5m0s
time="2020-11-06T15:53:03Z" level=info msg="Creating event controller" operationQueueSize=16 workerCount=4
time="2020-11-06T15:53:03Z" level=info msg="Argo Server started successfully on http://localhost:2746"
time="2020-11-06T15:58:03Z" level=info msg="Alloc=7220 TotalAlloc=18022 Sys=70080 NumGC=7 Goroutines=78"
```

HTML:
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Argo</title>
    <base href="/">
    <link href="assets/styles/heebo.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">
    <link rel="icon" type="image/png" href="assets/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="assets/favicon/favicon-16x16.png" sizes="16x16">
</head>

<body>
    <div id="app"></div>
<script type="text/javascript" src="main.44d1c937d2b2bb2c533b.js"></script></body>

</html>

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
