### ISSUE TITLE
Semaphore support in workflowTemplates and/or API

### ISSUE THREAD

**Issue by fwfichtner** [argoproj/argo-workflows#4500]
# Summary

Using v2.12.0-rc1 the semaphore locks work if we submit workflows via CLI or UI, but they are ignored when we are submitting via API (they are not part of `io.argoproj.workflow.v1alpha1.WorkflowSubmitRequest`) or when the semaphore locks only exist in the workflowTemplate (instead of the submitting workflow).

# Use Cases

It would be good to have at least one of the options for automated processing.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Can you provide sample workflow and workflowtemplate?

**Comment by fwfichtner** [comment]
Here's a workflowTemplate and a workflow (putting the semaphore into the workflow works):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: synchronization-wf-level
spec:
  entrypoint: whalesay
  synchronization:
    semaphore:
      configMapKeyRef:
        name: my-config
        key: workflow
  templates:
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["hello world"]
        imagePullPolicy: "IfNotPresent"
  
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: synchronization-wf-level-
spec:
  entrypoint: whalesay
  workflowTemplateRef:
    name: synchronization-wf-leveljs9nb
```

As an alternative the object is also missing in the REST submit.
