### ISSUE TITLE
Output artifact duplicated in a fan-in topology with the use of retryStrategy

### ISSUE THREAD

**Issue by saitoy1** [argoproj/argo-workflows#4508]
## Summary 

An output artifact is duplicated in a fan-in topology when a pre-fan-in step producing the artifact specifies `retryStrategy`; the duplication occurs regardless of whether there is an actual retry or not. I can work around this duplication behavior by deduping the result on my end. That said, if this is a bug, it'd be great if it could be addressed on the Argo side.

## Diagnostics

What Kubernetes provider are you using?
v1.18

What version of Argo Workflows are you running? 
v2.11.7

Reproduction steps are borrowed from [StackOverflow](https://stackoverflow.com/questions/60569353/dynamic-fan-in-in-argo-workflows) (and [this](https://github.com/argoproj/argo/issues/2393) enhancement request) with a minor addition that `retryStrategy` is added in the `write` step (the retry limit `3` does not matter for reproducibility and can be arbitrary).
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-result-
spec:
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    steps:
    - - name: generate
        template: gen-number-list
    - - name: write
        template: output-number
        arguments:
          parameters:
          - name: number
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"
    - - name: fan-in
        template: fan-in
        arguments:
          parameters:
          - name: numbers
            value: "{{steps.write.outputs.parameters}}"

  - name: gen-number-list
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        json.dump([i for i in range(20, 31)], sys.stdout)

  - name: output-number
    inputs:
      parameters:
      - name: number
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.number}} > /tmp/number.txt"]
    outputs:
      parameters:
        - name: number
          valueFrom:
            path: /tmp/number.txt
    retryStrategy:
      limit: 3

  - name: fan-in
    inputs:
      parameters:
        - name: numbers
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo received {{inputs.parameters.numbers}}"]
```
The above `fan-in` step produces an output that looks like
```
[{"number":"20"},{"number":"20"},{"number":"21"},{"number":"21"},{"number":"22"},{"number":"22"},{"number":"23"},{"number":"23"},{"number":"24"},{"number":"24"},{"number":"25"},{"number":"25"},{"number":"26"},{"number":"26"},{"number":"27"},{"number":"27"},{"number":"28"},{"number":"28"},{"number":"29"},{"number":"29"},{"number":"30"},{"number":"30"}]
```
when we should expect each number to appear only once.

Also, the same issue can be reproducible with a DAG instead of steps:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-result-
spec:
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    dag:
      tasks:
      - name: generate
        template: gen-number-list
      - name: write
        depends: "generate.Succeeded"
        template: output-number
        arguments:
          parameters:
          - name: number
            value: "{{item}}"
        withParam: "{{tasks.generate.outputs.result}}"
      - name: fan-in
        depends: "write.Succeeded"
        template: fan-in
        arguments:
          parameters:
          - name: numbers
            value: "{{tasks.write.outputs.parameters}}"

  - name: gen-number-list
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        json.dump([i for i in range(20, 31)], sys.stdout)

  - name: output-number
    inputs:
      parameters:
      - name: number
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.number}} > /tmp/number.txt"]
    outputs:
      parameters:
        - name: number
          valueFrom:
            path: /tmp/number.txt
    retryStrategy:
      limit: 3

  - name: fan-in
    inputs:
      parameters:
        - name: numbers
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo received {{inputs.parameters.numbers}}"]
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by saitoy1** [comment]
Adding this comment to keep this issue alive. I can work around it but fixing it would be nicer.

**Comment by ebr** [comment]
@saitoy1 did you find a viable workaround?

**Comment by saitoy1** [comment]
Hi @ebr,
Yes, at the least this workaround has been working on my end, which roughly looks like the following:
```
  - name: report-artifacts
    script:
      image: ...
      command: [python]
      source: |
          import hashlib

          artifacts_containing_duplicate = {{workflow.outputs.parameters.some-previous-step}}
          # hash on ID of each artifact to perform deduplication.
          test_failures = {hashlib.md5().hexdigest(artifact.id): artifact for artifact in artifacts_containing_duplicate}.values()
          ...
```
The step of reporting final artifacts is a script step written in Python. I just use Python's `dict` to eliminate duplicates before the final report. Should this issue get fixed, I will remove this band-aid. Hope that answers your question?

**Comment by saitoy1** [comment]
Hi @ebr,
Yes, at the least this workaround has been working on my end, which roughly looks like the following:
```
  - name: report-artifacts
    script:
      image: ...
      command: [python]
      source: |
          artifacts_containing_duplicate = {{workflow.outputs.parameters.some-previous-step}}
          # hash on ID of each artifact to perform deduplication.
          deduped_artifacts = {artifact.id: artifact for artifact in artifacts_containing_duplicate}.values()
          ...
```
The step of reporting final artifacts is a script step written in Python. I just use Python's `dict` to eliminate duplicates before the final report. Should this issue get fixed, I will remove this band-aid. Hope that answers your question?

**Comment by saitoy1** [comment]
Hi @ebr,

Yes, at the least this workaround has been working on my end, and here is what looks like, reusing my workflow `loop-param-result-example` from above.
```
  - name: fan-in
    inputs:
      parameters:
        - name: numbers
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json

        numbers = {{inputs.parameters.numbers}}

        # For instance, n looks like {"number": "20"} and we hash on the value part, e.g. "20" in this case.
        numbers_deduped = {n['number']: n for n in numbers}.values()

        print(json.dumps(list(numbers_deduped)))
```
Basically, I filter duplicates in the last step `fan-in`, using a Python's dict. The `print` function then yields:
```
[{"number": "20"}, {"number": "21"}, {"number": "22"}, {"number": "23"}, {"number": "24"}, {"number": "25"}, {"number": "26"}, {"number": "2
7"}, {"number": "28"}, {"number": "29"}, {"number": "30"}]
```
Should this issue get fixed, I will remove this band-aid fix. Hope this answers your question?

**Comment by altonchuzhan** [comment]
I have exactly the same issue.

**Comment by smile-luobin** [comment]
fixed it: 
in file: workflow/controller/operator.go;
modify function processAggregateNodeOutputs;
     for _, node := range childNodes { => for _, node := range childNodes[1:] {
as the first item is the parentNode of these childNodes.

**Comment by smile-luobin** [comment]
i am trying to fix this bug. but i cann't push my codes successfully. is there any contributor guides?

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md

**Comment by ebr** [comment]
This is still and issue us in 3.0.7. We've resorted to fixing it in Python, thanks to @saitoy1

**Comment by smile-luobin** [comment]
There is a bug in processAggregateNodeOutputs for dag or steps in workflow-controller.

The bug source code is: 

- https://github.com/argoproj/argo-workflows/blob/510b4a816dbb2d33f37510db1fd92b841c4d14d3/workflow/controller/dag.go#L507

- https://github.com/argoproj/argo-workflows/blob/510b4a816dbb2d33f37510db1fd92b841c4d14d3/workflow/controller/steps.go#L116

For fanout task/step, argo will generate a nodeName based these output items with prefix "(":

- https://github.com/argoproj/argo-workflows/blob/510b4a816dbb2d33f37510db1fd92b841c4d14d3/workflow/controller/operator.go#L2863

For retryStrategy, argo will generate a childNode for node with "(childIndex)":
- https://github.com/argoproj/argo-workflows/blob/510b4a816dbb2d33f37510db1fd92b841c4d14d3/workflow/controller/operator.go#L1702

So, both the parentNodeName and childNodeName are contains nodeName and prefix "(", but in bug source code only "strings.HasPrefix(node.Name, ancestorNode.Name+"(")" is not enough. And the result will contains both parentNode and childNodes.

**Comment by saitoy1** [comment]
Just adding a comment to prevent this from being closed. Looks like the fix is underway though. Thanks for the help!

**Comment by brews** [comment]
I think another potential workaround with https://github.com/argoproj/argo-workflows/issues/4508#issue-740137802 as an example, is to change from 

```yaml
      - name: fan-in
        depends: "write.Succeeded"
        template: fan-in
        arguments:
          parameters:
          - name: numbers
            value: "{{tasks.write.outputs.parameters}}"
```

to

```yaml
      - name: fan-in
        depends: "write.Succeeded"
        template: fan-in
        arguments:
          parameters:
          - name: numbers
            value: "{{= sprig.uniq(tasks.write.outputs.parameters) }}"
```

if you know that elements in `tasks.write.outputs.parameters` _should_ be unique.
