### ISSUE TITLE
2.11.7 Argo UI - graph edge rendering is wonky

### ISSUE THREAD

**Issue by ryedin** [argoproj/argo-workflows#4509]
## Summary 

Take a look at the attached picture. No other way to describe it. The edges render sanely in the previous version we tried (2.10.1), but get very screwy in the latest.

render screenshot:
![Screen Shot 2020-11-10 at 4 15 42 PM](https://user-images.githubusercontent.com/151376/98741026-90a5e580-2371-11eb-934c-368a9006abdc.png)

workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: run-r-script
spec:
  entrypoint: run

  templates:
    - name: run
      parallelism: 2
      dag:
        tasks:
          - name: cdc-tasks
            templateRef:
              name: etl-task-template
              template: summary-task
            arguments:
              parameters:
                - name: name
                  value: cdc-tasks

            dependencies: ['cdc-prediction-inputs', 'cdc-nsc-outcomes', 'cdc-student-demographics']

          - name: cdc-prediction-inputs
            templateRef:
              name: etl-task-template
              template: etl-task-with-summary
            arguments:
              parameters:
                - name: taskName
                  value: cdc-prediction-inputs
                - name: moduleSchema
                  value: k12intel_staging_etl
                - name: moduleTable
                  value: stageLakeRecords
                - name: dataSchema
                  value: ''
                - name: dataTable
                  value: ''
                - name: recordType
                  value: Prediction_Inputs
                - name: recordGroup
                  value: ''

            dependencies: ['stage-prediction-inputs', 'cdc-student-demographics']

          - name: cdc-nsc-outcomes
            templateRef:
              name: etl-task-template
              template: etl-task-with-summary
            arguments:
              parameters:
                - name: taskName
                  value: cdc-nsc-outcomes
                - name: moduleSchema
                  value: k12intel_staging_etl
                - name: moduleTable
                  value: stageLakeRecords
                - name: dataSchema
                  value: ''
                - name: dataTable
                  value: ''
                - name: recordType
                  value: Student_CCR_Factors
                - name: recordGroup
                  value: ''


            dependencies: ['cdc-prediction-inputs', 'stage-nsc-outcomes']

          - name: cdc-student-demographics
            templateRef:
              name: etl-task-template
              template: etl-task-with-summary
            arguments:
              parameters:
                - name: taskName
                  value: cdc-student-demographics
                - name: moduleSchema
                  value: k12intel_staging_etl
                - name: moduleTable
                  value: stageLakeRecords
                - name: dataSchema
                  value: ''
                - name: dataTable
                  value: ''
                - name: recordType
                  value: Student_Demographics
                - name: recordGroup
                  value: ''


            dependencies: ['stage-student-demographics', 'stage-nsc-outcomes']

          - name: stage-prediction-inputs
            templateRef:
              name: etl-task-template
              template: etl-task-with-summary
            arguments:
              parameters:
                - name: taskName
                  value: stage-prediction-inputs
                - name: moduleSchema
                  value: k12intel_staging_etl
                - name: moduleTable
                  value: loadLakeRecords
                - name: dataSchema
                  value: ''
                - name: dataTable
                  value: ''
                - name: recordType
                  value: Prediction_Inputs
                - name: recordGroup
                  value: ''

            dependencies: ['stage-student-demographics']

          - name: stage-student-demographics
            templateRef:
              name: etl-task-template
              template: etl-task-with-summary
            arguments:
              parameters:
                - name: taskName
                  value: stage-student-demographics
                - name: moduleSchema
                  value: k12intel_staging_etl
                - name: moduleTable
                  value: loadLakeRecords
                - name: dataSchema
                  value: ''
                - name: dataTable
                  value: ''
                - name: recordType
                  value: Student_Demographics
                - name: recordGroup
                  value: ''

            dependencies: ['download-prediction-inputs']

          - name: download-prediction-inputs
            templateRef:
              name: etl-task-template
              template: etl-task-with-summary
            arguments:
              parameters:
                - name: taskName
                  value: download-prediction-inputs
                - name: moduleSchema
                  value: k12intel_staging_etl
                - name: moduleTable
                  value: downloadFTPFiles
                - name: dataSchema
                  value: ''
                - name: dataTable
                  value: ''
                - name: recordType
                  value: Prediction_Inputs
                - name: recordGroup
                  value: Predictions

            dependencies: []

          - name: stage-nsc-outcomes
            templateRef:
              name: etl-task-template
              template: etl-task-with-summary
            arguments:
              parameters:
                - name: taskName
                  value: stage-nsc-outcomes
                - name: moduleSchema
                  value: k12intel_staging_etl
                - name: moduleTable
                  value: loadLakeRecords
                - name: dataSchema
                  value: ''
                - name: dataTable
                  value: ''
                - name: recordType
                  value: Student_CCR_Factors
                - name: recordGroup
                  value: ''

            dependencies: ['stage-prediction-inputs']

          - name: run-r-script
            templateRef:
              name: etl-task-template
              template: r-task
            arguments:
              parameters:
                - name: taskName
                  value: run-r-script
            dependencies: ['cdc-tasks']

```

referenced templates (paraphrased... not complete because don't think that's relevant to the UI issue):
```
  templates:
  - name: etl-task-with-summary
    inputs:
      parameters:
      - name: taskName
      - name: moduleSchema
      - name: moduleTable
      - name: dataSchema
      - name: dataTable
      - name: recordType
      - name: recordGroup
      - name: summary
        default: "none"
    dag:
      tasks:
      - name: execute
        template: etl-task
        arguments:
          parameters:
          - name: taskName
            value: "{{inputs.parameters.taskName}}"
          - name: moduleSchema
            value: "{{inputs.parameters.moduleSchema}}"
          - name: moduleTable
            value: "{{inputs.parameters.moduleTable}}"
          - name: dataSchema
            value: "{{inputs.parameters.dataSchema}}"
          - name: dataTable
            value: "{{inputs.parameters.dataTable}}"
          - name: recordType
            value: "{{inputs.parameters.recordType}}"
          - name: recordGroup
            value: "{{inputs.parameters.recordGroup}}"
      - name: summary
        template: summary-task
        arguments:
          parameters:
          - name: name
            value: "{{inputs.parameters.taskName}}"
          - name: summary
            value: |
                    {{inputs.parameters.taskName}}: {{tasks.execute.outputs.parameters.exitCode}}
                    --- dependencies ---
                    {{inputs.parameters.summary}}
        depends: execute.Succeeded
      - name: failure
        template: failure-task
        arguments:
          parameters:
          - name: name
            value: "{{inputs.parameters.taskName}}"
        depends: execute.Failed

  - name: etl-task
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    retryStrategy:
      limit: 2
      retryPolicy: "Always"
    inputs:
      parameters:
      - name: taskName
      - name: moduleSchema
      - name: moduleTable
      - name: dataSchema
      - name: dataTable
      - name: recordType
      - name: recordGroup
    container:
      image: some_image
      command:
      - bash
      - -c
      - some_command
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
