### ISSUE TITLE
pick persistence password from mounted property file

### ISSUE THREAD

**Issue by mailtoraja18** [argoproj/argo-workflows#4550]
# Summary
My persistence passwords are stored/rotated in AWS Secrets manager. I can fetch it using a init container to a property file written to a designated location like /tmp/secrets  . I cannot work with a config map. Do I have any options ?

**Comment by sarabala1979** [comment]
@mailtoraja18  https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
```
