### ISSUE TITLE
Cannot get the result outputs when we have many parents

### ISSUE THREAD

**Issue by chermed** [argoproj/argo-workflows#4584]
Bug report

## Summary 

I have a dag :
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: analyze-things-
spec:
  entrypoint: texte
  templates:
    - name: curl
      inputs:
        parameters:
          - name: endpoint
          - name: msg
      container:
        image: byrnedo/alpine-curl
        command:
          - curl
          - -skSL
          - --fail
          - "http://{{inputs.parameters.endpoint}}:8080/"
          - --data
          - "{{inputs.parameters.msg}}"
    - name: debug
      inputs:
        parameters:
          - name: endpoint
          - name: msg
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import json
          import sys
          print('ENDPOINT :')
          endpoint="""{{inputs.parameters.endpoint}}"""
          msg="""{{inputs.parameters.msg}}"""
          print(type(endpoint))
          print(endpoint)
          print('MSG :')
          print(type(msg))
          print(msg)
          json.dump(json.dumps("OK"), sys.stdout)
    - name: get-values
      inputs:
        parameters:
          - name: endpoint
          - name: msg
      script:
        image: python:alpine3.7
        command: [python]
        source: |
          import json
          import sys
          msg="""{{inputs.parameters.msg}}"""
          msg = json.loads(msg).get('values')
          print(json.dumps(msg, indent=2, ensure_ascii=False))

    - name: texte
      dag:
        tasks:
          - name: FA
            template: curl
            arguments:
              parameters:
                [
                  { name: endpoint, value: "func-a.default" },
                  { name: msg, value: "{{workflow.parameters.msg}}" },
                ]
          - name: FB
            dependencies: [FA]
            template: curl
            arguments:
              parameters:
                [
                  { name: endpoint, value: "func-b.default" },
                  { name: msg, value: "{{tasks.FA.outputs.result}}" },
                ]
          - name: FB-SPLIT
            dependencies: [FB]
            template: get-values
            arguments:
              parameters:
                [
                  { name: endpoint, value: "dummy" },
                  { name: msg, value: "{{tasks.FB.outputs.result}}" },
                ]
          - name: FD
            dependencies: [FB-SPLIT]
            template: curl
            arguments:
              parameters:
                [
                  { name: endpoint, value: "func-external.default" },
                  { name: msg, value: '{"value": {{item}} }' },
                ]
            withParam: "{{tasks.FB-SPLIT.outputs.result}}"
          - name: FF
            dependencies: [FD]
            template: debug
            arguments:
              parameters:
                [
                  { name: endpoint, value: "func-f.default" },
                  { name: msg, value: "{{tasks.FD.outputs.result}}" },
                ]

```
## Diagnostics

What Kubernetes provider are you using? 
` K8s Rev: v1.17.12+k3s1`

What version of Argo Workflows are you running? 
```
╰─$ argo version              
argo: v2.11.7
  BuildDate: 2020-11-02T21:00:02Z
  GitCommit: bf3fec176cf6bdf3e23b2cb73ec7d4e3d051ca40
  GitTreeState: clean
  GitTag: v2.11.7
  GoVersion: go1.13.15
  Compiler: gc
  Platform: darwin/amd64
```

```yaml
Output of the workflow, including status:

Name:                analyze-things-pfdrb
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Sun Nov 22 17:00:39 +0100 (24 minutes ago)
Parameters:          
  msg:               {"txt":"egypt 3259  tunesie 5636"}
analyze-things-pfdrb-2264706263: {
analyze-things-pfdrb-2264706263:   "task_id": "3654e5d8-5f33-41c2-9731-836a7658de9e",
analyze-things-pfdrb-2264706263:   "values": [
analyze-things-pfdrb-2264706263:     [
analyze-things-pfdrb-2264706263:       "egypt",
analyze-things-pfdrb-2264706263:       3259
analyze-things-pfdrb-2264706263:     ],
analyze-things-pfdrb-2264706263:     [
analyze-things-pfdrb-2264706263:       "tunesie",
analyze-things-pfdrb-2264706263:       5636
analyze-things-pfdrb-2264706263:     ]
analyze-things-pfdrb-2264706263:   ]
analyze-things-pfdrb-2264706263: }
analyze-things-pfdrb-2281483882: {
analyze-things-pfdrb-2281483882:   "task_id": "3654e5d8-5f33-41c2-9731-836a7658de9e",
analyze-things-pfdrb-2281483882:   "values": [
analyze-things-pfdrb-2281483882:     [
analyze-things-pfdrb-2281483882:       "EGYPT",
analyze-things-pfdrb-2281483882:       3259
analyze-things-pfdrb-2281483882:     ],
analyze-things-pfdrb-2281483882:     [
analyze-things-pfdrb-2281483882:       "TUNESIE",
analyze-things-pfdrb-2281483882:       5636
analyze-things-pfdrb-2281483882:     ]
analyze-things-pfdrb-2281483882:   ]
analyze-things-pfdrb-2281483882: }
analyze-things-pfdrb-3940223875: [
analyze-things-pfdrb-3940223875:   [
analyze-things-pfdrb-3940223875:     "EGYPT",
analyze-things-pfdrb-3940223875:     3259
analyze-things-pfdrb-3940223875:   ],
analyze-things-pfdrb-3940223875:   [
analyze-things-pfdrb-3940223875:     "TUNESIE",
analyze-things-pfdrb-3940223875:     5636
analyze-things-pfdrb-3940223875:   ]
analyze-things-pfdrb-3940223875: ]
analyze-things-pfdrb-2942105771: {
analyze-things-pfdrb-2942105771:   "task_id": "3c848e4d-cf4b-4e84-a0a5-71a1f2f00655",
analyze-things-pfdrb-2942105771:   "value": [
analyze-things-pfdrb-2942105771:     "TUNESIE",
analyze-things-pfdrb-2942105771:     5600
analyze-things-pfdrb-2942105771:   ]
analyze-things-pfdrb-2942105771: }
Name:                analyze-things-pfdrb
Namespace:           argo
ServiceAccount:      default
Status:              Succeeded
Conditions:          
 Completed           True
Created:             Sun Nov 22 17:00:39 +0100 (25 minutes ago)
Started:             Sun Nov 22 17:00:39 +0100 (25 minutes ago)
Finished:            Sun Nov 22 17:01:11 +0100 (24 minutes ago)
Duration:            32 seconds
ResourcesDuration:   14s*(1 cpu),14s*(100Mi memory)
Parameters:          
  msg:               {"txt":"egypt 3259  tunesie 5636"}

STEP                       TEMPLATE    PODNAME                          DURATION  MESSAGE
 ✔ analyze-things-pfdrb    texte                                                    
 ├-✔ FA                    curl        analyze-things-pfdrb-2264706263  5s          
 ├-✔ FB                    curl        analyze-things-pfdrb-2281483882  5s          
 ├-✔ FB-SPLIT              get-values  analyze-things-pfdrb-3940223875  4s          
 ├-✔ FD(0:[EGYPT 3259])    curl        analyze-things-pfdrb-2157517803  5s          
 ├-✔ FD(1:[TUNESIE 5636])  curl        analyze-things-pfdrb-2942105771  4s          
 └-✔ FF                    debug       analyze-things-pfdrb-2214373406  3s 

```

![dag](https://i.ibb.co/0QPTb7j/Capture-d-e-cran-2020-11-22-a-17-31-25.png "DAG")

**The problem:**

The expression `{{tasks.FD.outputs.result}}` from the task `FD` is not rendered, it gives as value `{{tasks.FD.outputs.result}}` and the reason maybe that the task `FD` has `withParam` 

**The expected value is :**
`{{tasks.FD.outputs.result}}` from the task `FD` should return list of lists

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chermed** [comment]
### Another example :
```
# Example workflow to demonstrate parameter aggregation in a DAG.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simple-
spec:
  entrypoint: parameter-aggregation
  templates:
    - name: parameter-aggregation
      dag:
        tasks:
          - name: tt
            template: generator
          - name: fois10
            dependencies: [tt]
            template: fois10
            arguments:
              parameters:
                - name: num
                  value: "{{item}}"
            withParam: "{{tasks.tt.outputs.parameters.numbers}}"
          - name: show
            dependencies: [fois10]
            template: print
            arguments:
              parameters:
                - name: message
                  value: "{{tasks.fois10.outputs.result}}"
    - name: generator
      container:
        image: alpine:latest
        command: [sh, -xc]
        args:
          - |
            echo "[3, 4]" > /tmp/numbers;
      outputs:
        parameters:
          - name: numbers
            valueFrom:
              path: /tmp/numbers
    - name: fois10
      inputs:
        parameters:
          - name: num
      container:
        image: alpine:latest
        command: [sh, -xc]
        args:
          - |
            echo {{inputs.parameters.num}}
    - name: print
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

### Console output :

```
Name:                simple-ndcxt
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Mon Nov 23 00:59:41 +0100 (now)
simple-ndcxt-1214427733: + echo '[3, 4]'
simple-ndcxt-1213184311: + echo 30
simple-ndcxt-1213184311: 30
simple-ndcxt-1536447921: + echo 40
simple-ndcxt-1536447921: 40
simple-ndcxt-1884801564:  _________________________________ 
simple-ndcxt-1884801564: < {{tasks.fois10.outputs.result}} >
simple-ndcxt-1884801564:  --------------------------------- 
simple-ndcxt-1884801564:     \
Name:                simple-ndcxt
Namespace:           argo
ServiceAccount:      default
Status:              Succeeded
Conditions:          
 Completed           True
Created:             Mon Nov 23 00:59:41 +0100 (25 seconds ago)
Started:             Mon Nov 23 00:59:42 +0100 (24 seconds ago)
Finished:            Mon Nov 23 01:00:07 +0100 (now)
Duration:            25 seconds
ResourcesDuration:   16s*(1 cpu),16s*(100Mi memory)

STEP              TEMPLATE               PODNAME                  DURATION  MESSAGE
 ✔ simple-ndcxt   parameter-aggregation                                       
 ├-✔ tt           generator              simple-ndcxt-1214427733  5s          
 ├-✔ fois10(0:3)  fois10                 simple-ndcxt-1213184311  6s          
 ├-✔ fois10(1:4)  fois10                 simple-ndcxt-1536447921  8s          
 └-✔ show         print                  simple-ndcxt-1884801564  7s
```

### Logs (results not rendered)
```
W
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
 _________________________________
< {{tasks.fois10.outputs.result}} >
 ---------------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/


```
