### ISSUE TITLE
Support of Sprig (filter for variables)

### ISSUE THREAD

**Issue by chermed** [argoproj/argo-workflows#4585]
# Summary

why not integrate a library like sprig (http://masterminds.github.io/sprig/) to be able to transform data without adding extra tasks, example:
```
          - name: FD
            dependencies: [FB-SPLIT]
            template: curl
            arguments:
              parameters:
                [
                  { name: endpoint, value: "func-external.default" },
                  { name: msg, value: '{"value": {{item}} }' },
                ]
            withParam: "{{tasks.FB-SPLIT.outputs.result | toObject | field .results | toList}}"
```

What change needs making?

# Use Cases

When would you use this?
Let's assume that  I have many functions (top of serverless framework) that accepts JSON  as input and outputs
The syntax of the input json is `{"value": {"itemX","valueY}}`
The syntax of the output json is `{"results": [{"item0","value0"}, ..., {"itemN","valueN}]}`

When building the dag, we need to loop on results and then construct the new JSON. the problem is that we need to extra tasks to make transformation.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This is an interesting idea. Would you like to submit a PR? @simster7 might be willing to give pointers.

**Comment by alexec** [comment]
@jessesuen this go a lot of thumbs-up very quickly - I think it supports your arguments for better in-template data processing features

**Comment by alexec** [comment]
Our main evaluation library is https://github.com/antonmedv/expr

**Comment by alexec** [comment]
We use fasttemplate for templates, it is fast, but basic and Sprig does not support it. We would need to introduce a new syntax.

**Comment by alexec** [comment]
This could be solved by plugins obviously. #5025

**Comment by max-sixty** [comment]
Ref https://github.com/argoproj/argo-workflows/issues/1293

**Comment by max-sixty** [comment]
@simster7 tell me if this is chirping from the peanut gallery — but will this approach involve writing & maintaining code within Argo for each transformation? Is there an approach for inheriting functionality immediately from a library like gomplate or sprig, even if it involves another pass on top of `fasttemplate`?

**Comment by alexec** [comment]
Question for @chermed @max-sixty, the example in the is `withParam`. I initially thought you needed more powerful templates everywhere, but is this almost completely a problem for `withParam`?

**Comment by max-sixty** [comment]
My original use case was date manipulation, not in `withParam`, but obv don't overfit on me...

**Comment by alexec** [comment]
@max-sixty could you provide other examples? `withParam` is a good example of where using filter and map operations would be powerful, however I'd love to see more use cases to we can more fully understand this.

**Comment by max-sixty** [comment]
The case we had was having a legible date format for workflow creation time, which ends up being verbose and inflexile:

```yaml
        - name: run_date
          value: "{{workflow.creationTimestamp.Y}}{{workflow.creationTimestamp.m}}{{workflow.creationTimestamp.d}}"
```

This would be much easier with sprig / gomplate / etc:

```yaml
"{{workflow.creationTimestamp | date "2006-01-02"}}"
```

**Comment by alexec** [comment]
```
yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: expression-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: task-0
            template: pod-0
            arguments:
              parameters:
                - name: foo
                  value: "{{=int(item) + 1}}"
            # stringify: withParam must be a JSON list encoded as a string
            withParam: "{{=stringify(filter([1, 3, 7], {# > 1}))}}"
    - name: pod-0
      inputs:
        parameters:
          - name: foo
      container:
        image: argoproj/argosay:v2
        args: [ echo, "hello {{=int(inputs.parameters.foo) * 10}}" ]
```

**Comment by simster7** [comment]
I think a good distinction between #5115 and #4958 is the scope of the data. Enhanced templating targets quick, in-line, modifications to parameters while the `data:` template deals with sourcing and transforming a large amount of data.

I like to think of the `data:` template as bash pipes: trying to replicate an experience such as `cat file.txt | sed ... | grep ... | sort | uniq | xargs ...`

Enhanced templating would be like doing in-place calls `echo $(( $var + 1))` or `cat $(pwd)/file.go`

**Comment by alexec** [comment]
I think the scope of this has to be limited. What I can't currently fathom is, expr is missing group and reduce operators. I'm asking them to add them (because adding them myself would require some solid 1st-year CompSci compiler writing skills I seem to no longer possess). I'd like to allow changing the templating library.

**Comment by simster7** [comment]
> What I can't currently fathom is, expr is missing group and reduce operators.

Agreed. This is why I think expr is very limited for this use case

**Comment by alexec** [comment]
It's more powerful than `text/template`, but I think we might want something more powerful still. Maybe a mini-scripting language.

**Comment by alexec** [comment]
See #1293

**Comment by alexec** [comment]
Example of the proposed solution - PLEASE COMMENT!

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: expression-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: task-0
            template: pod-0
            arguments:
              parameters:
                - name: foo
                  value: "{{=int(item) + 1}}"
            # stringify: withParam must be a JSON list encoded as a string
            withParam: "{{=toJson(filter([1, 3, 7], {# > 1}))}}"
    - name: pod-0
      inputs:
        parameters:
          - name: foo
      container:
        image: argoproj/argosay:v2
        args: [ echo, "hello {{=int(inputs.parameters.foo) * 10}}" ]
```
