### ISSUE TITLE
Incorrect statement about assuming the workflow-controller is running in UTC timezone

### ISSUE THREAD

**Issue by artheus** [argoproj/argo-workflows#4614]
The statement about argo assuming that the workflow-controller is running in UTC is incorrect, as it actually expects the workflow-controller to be running in the same timezone as argo.

I've been testing this for my work, and by simply setting the `TZ` environment variable to a IANA standard timezone (in my case `CET`) for both the argo pod and the workflow-controller pod, UTC is completely out of the picture, and all logs and cron workflows are working correctly.

https://github.com/argoproj/argo/blob/7f2ff80f130b3cd5834b4c49ab6c1692dd93a76c/ui/src/app/cron-workflows/components/cron-workflow-summary-panel.tsx#L40

**How did I deploy?**
At work we are using a helm chart based on your documentation on deployment, and the argo-helm project.
But it all comes down to these two deployments:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  replicas: 2
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      serviceAccountName: argo-server
      containers:
      - args:
        - server
        - --auth-mode
        - client
        env:
        - name: TZ
          value: CET
        image: argoproj/argocli:{{.Values.argoVersion}}
        name: argo-server
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      serviceAccountName: argo
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - argoproj/argoexec:{{ .Values.argoVersion }}
        env:
        - name: TZ
          value: CET
        command:
        - workflow-controller
        image: argoproj/workflow-controller:{{ .Values.argoVersion }}
        name: workflow-controller
```

As you can see, I set `TZ=CET` env variable for both the argo and the workflow-controller, which makes it work perfectly for our environment. But in our case the note "(assumes workflow-controller is in UTC)" becomes very confusing for the users.

**What should be changed?**
As I see it, there are some alternatives:

* The note in the UI (and other places if exists) should be changed depending on the configured timezone. as such:
  ```go
  tz, _ := time.Now().Zone()
  fmt.Sprintf("(assumes workflow-controller is in %s)", tz)
  ```
* Read time information such as timezone from the workflow-controller, and warn in the WebUI if the pods are not configured equally. This would somehow be the preferable solution, as it would let the WebGUI be cleaner without confusing notes, as long as everything is installed correctly.
