### ISSUE TITLE
Support podSpecPatch for patching volumeMounts

### ISSUE THREAD

**Issue by zen-xu** [argoproj/argo-workflows#4623]
# Use Cases

When would you use this?

I create a cluster workflow template, one parameter is `volume-mounts`. With this parameter I can choose already created pvcs to mount on the pod instead all of them.

But current `argo` seems not support for patching `volumeMounts` yet. Because  I will get spec.containers[1].volumeMounts[0].name: Not found: `${volume-name}`, which has already defined in workflow template volumes

Here is simple demo just use emptyDir
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demo
spec:
  entrypoint: main
  templates:
    - name: main
      podSpecPatch: |
        containers:
        - name: main
          volumeMounts:
          - name: home
            mountPath: /home/me
      volumes:
      - name: home
        emptyDir: {}
      script:
        image: alpine:latest
        command: [sh]
        source: echo hello
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Pod creation code is checking `volumemounts`  to attach the `volume` on pod spec. Here it is dynamically adding into pod Spec, so volume is not attaching to pod spec.

**Comment by mac9416** [comment]
@sarabala1979 can you point us to the place in code where this happens? I could try to hunt it down, but I get lost quickly. :-)

@zen-xu I'm curious, what's your use case? In the StackOverflow post, you were passing in volume mounts via a param. That worries me a little bit, because it opens a risk of YAML injection. Maybe there's a cleaner approach in general?

Given the current constraints, it seems as if the pod spec would have to include mounts for all volumes and then be overwritten by the patch to include only the desired mounts and the desired mount paths.

**Comment by sarabala1979** [comment]
@zen-xu @mac9416  Just discussed with @jessesuen. I enhance the code to support this usecase

**Comment by mac9416** [comment]
@sarabala1979 sweet! I think at some point docs will need to be sprinkled with "don't just parameterize all the things, it's a security nightmare." But for the moment I guess more features is always good. :-)

**Comment by sarabala1979** [comment]
>@sarabala1979 can you point us to the place in code where this happens? I could try to hunt it down, but I get lost quickly. :-)

https://github.com/argoproj/argo/blob/e1919c86b3ecbd1760a404de6d8637ac0ae6ce0b/workflow/controller/workflowpod.go#L726

**Comment by zen-xu** [comment]
> @sarabala1979 can you point us to the place in code where this happens? I could try to hunt it down, but I get lost quickly. :-)
> 
> @zen-xu I'm curious, what's your use case? In the StackOverflow post, you were passing in volume mounts via a param. That worries me a little bit, because it opens a risk of YAML injection. Maybe there's a cleaner approach in general?
> 
> Given the current constraints, it seems as if the pod spec would have to include mounts for all volumes and then be overwritten by the patch to include only the desired mounts and the desired mount paths.

The issue demo is used to verify patching volumeMounts will failed.

My case is I'll create a clusterWorkflowTemplate, and it has many already created volumes pvc (maybe `a`, `b`, `c`), 
But users only have some of these pvcs, for example user A has pvc `a` and `b`, user B has pvc `a` and `c` . 
So I need patch volumeMounts  instead mount all of them

**Comment by zen-xu** [comment]
May be can argo support optional mount a volume?
 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demo
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
        - name: user
      volumes:
      - name: volumeA
        persistentVolumeClaim:
          claimName: user-A-datas
      - name: volumeB
        persistentVolumeClaim:
          claimName: user-B-datas
      script:
        image: alpine:latest
        command: [sh]
        source: echo hello
        volumeMounts:
        - mountPath: /home/A/datas
          name: user-A-datas
          when: "{{inputs.parameters.user}} == A"
        - mountPath: /home/B/datas
          name: user-B-datas
          when: "{{inputs.parameters.user}} == B"
```

**Comment by alexec** [comment]
I've spoken to @sarabala1979 today.

* `podSpecPatch` is intended for parameterizing fields that are not a parameterizable string (e.g int, resource quantity). It is not intended for conditionally adding volumes.
* This is not a popular issue.
* For this complex use-case -  you can create your workflows programmatically (e.g. using the Python SDK) to have whatever volumes you want.

I've asked @sarabala1979 to pause his work pending further discussion.

**Comment by zen-xu** [comment]
@alexec
But in my case I shoud optional mount volumes in  **Cluster Workflow Template**,  which like a function receive parameters
 and encapsulate the logic rather than let users to implement the workflows logic

**Comment by wreed4** [comment]
Just found this issue, I'm trying to do something similar, but I'm trying to parameterize the "readOnly" field on a volumeMount.  Not conditionally add a volume, but conditionally mount it as read-only.  these kinds of things crop up a lot when trying to write library templates.  Is there a way to do this?  I'm getting a message saying it failed during the merge, but seemingly no actual error from the merge, so I can't see what I'm doing wrong.

**Comment by wreed4** [comment]
Never mind!! I think I solved it.  
```yaml
  - name: ephemeral-volume
    inputs:
      parameters:
      - name: readOnly
        value: "false"
    volumes:
    - name: image
      csi:
        driver: csi-image.warm-metal.tech
        volumeAttributes:
          image: "hello-world"
    podSpecPatch: |-
      containers:
      - name: main
        volumeMounts:
        - name: image
          mountPath: /mountedImage
          readOnly: {{inputs.parameters.readOnly}}
    container:
      image: busybox:glibc
      volumeMounts:
      - name: image
        mountPath: /mountedImage
      command: [sh, -c]
      args: &script
      - |
        set -e
        set -x
        [ -f /mountedImage/hello ] && echo "hello exists!" || exit 1
        [ -f /mountedImage/hello2 ] && exit 1 || echo "hello2 does not exists!"

        touch "/mountedImage/{{pod.name}}" || true
        if {{inputs.parameters.readOnly}}; then
          [ -f /mountedImage/{{pod.name}} ] && exit 1 || echo "{{pod.name}} does not exists!"
        else
          [ -f /mountedImage/{{pod.name}} ] && echo "{{pod.name}} exists!" || exit 1
        fi

        ls /mountedImage
```
