### ISSUE TITLE
Support get json parameter field value

### ISSUE THREAD

**Issue by zen-xu** [argoproj/argo-workflows#4624]
# Use Cases

When would you use this?

So can argo provide `withJson`, so I can use "{{item.field}}" like `withParam`, which must be **json array** in `Loop`.

Demo
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demo
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
        - name: json-params
      steps:
      - - name: main
           template: task
           arguments:
             parameters:
             - name: param1
               value: "{{item.param1}}"
             - name: param2
               value: "{{item.param2}}"
           withJson: "{{inputs.parameters.json-params}}"
    - name: task
      inputs:
        parameters:
        - name: param1
        - name: param2
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo {{inputs.parameters.param1}}
          echo {{inputs.parameters.param2}}
```

Or more humanized, just get json field value from template variable
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demo
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
        - name: json-params
      steps:
      - - name: main
           template: task
           arguments:
             parameters:
             - name: param1
               value: "{{inputs.parameters.json-params.param1}}"
             - name: param2
               value: "{{inputs.parameters.json-params.param2}}"
    - name: task
      inputs:
        parameters:
        - name: param1
        - name: param2
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo {{inputs.parameters.param1}}
          echo {{inputs.parameters.param2}}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by whynowy** [comment]
`withParam` also can take a json array and iterate the items, check the example: https://github.com/argoproj/argo/blob/master/examples/loops-param-argument.yaml

**Comment by Seanny123** [comment]
I think what @whynowy is referring to is using a previous step's JSON output parameter as input to `withParams`.

For example, something like:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  arguments:
    parameters:
      - name: s3-bucket
      - name: input-csv
      - name: output-path

  volumes:
    - name: workdir
      emptyDir: {}

  entrypoint: main

  templates:
    - name: main
      steps:
        - - name: get-inputs
            # Produces the complete set of work units from the initial input
            template: split-csv
            arguments:
              artifacts:
                - name: csv-file
                  s3:
                    endpoint: s3.amazonaws.com
                    bucket: "{{workflow.parameters.s3-bucket}}"
                    key: "{{workflow.parameters.input-csv}}"

        - - name: process-each
            # Iterates over the a set of work units produced by the previous step
            template: big-compute
            arguments:
              parameters:
                - name: param0
                  value: "{{item.param0}}"
                - name: param1
                  value: "{{item.param1}}"
                - name: param2
                  value: "{{item.param2}}"
            withParam: "{{steps.get-inputs.outputs.parameters.json-data}}"
    
    - name: split-csv
      # Given a CSV file, convert each row into a JSON-formatted object,
      # and output the list all resulting objects as an artifact,
      # and the length of this list as a parameter
      inputs:
        artifacts:
          - name: csv-file
            path: /workdir/input.csv
      outputs:
        parameters:
          - name: json-data
            valueFrom:
              path: /workdir/data.json
      script:
        image: python:alpine
        command: [python]
        source: |
          from csv import reader
          import json
          from pathlib import Path
          import os

          with open("{{inputs.artifacts.csv-file.path}}", "r") as fi:
            rows = reader(fi)
            next(rows)
            data = [{"param0": r[0], "param1": r[1], "param2": r[2]} for r in list(rows)]

          with open("{{outputs.parameters.json-data.path}}", "w") as fi:
            json.dump(data, fi)
      
        volumeMounts:
          - name: workdir
            mountPath: /workdir

    - name: big-compute
      inputs:
        parameters:
          - name: param0
          - name: param1
          - name: param2
      outputs:
        artifacts:
          - name: collected-outputs
            path: /workdir/out
            archive:
              none: {}
            s3:
              endpoint: s3.amazonaws.com
              bucket: "{{workflow.parameters.s3-bucket}}"
              key: "{{workflow.parameters.output-path}}"
      script:
        image: fedora:33
        command: [bash]
        source: |
          set -xe

          mkdir /workdir/out && cd /workdir/out
          echo "{{inputs.parameters.param0}},{{inputs.parameters.param1}},{{inputs.parameters.param2}}" \
                > {{inputs.parameters.param0}}_{{inputs.parameters.param1}}_{{inputs.parameters.param2}}

        resources:
          requests:
            memory: 30Mi
            cpu: 20m
          limits:
            memory: 30Mi
            cpu: 20m
        volumeMounts:
          - name: workdir
            mountPath: /workdir
```

This isn't exactly what the OP is asking for, but it is close enough it was worth posting my solution.

**Comment by Seanny123** [comment]
I think what @whynowy is implying is that you can currently accomplish this with an awkward intermediary pod to convert a artifact to a parameter:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  arguments:
    parameters:
      - name: s3-bucket
      - name: input-json
      - name: output-path

  volumes:
    - name: workdir
      emptyDir: {}

  entrypoint: main

  templates:
    - name: main
      steps:
        - - name: get-inputs
            template: get-json
            arguments:
              artifacts:
                - name: json-file
                  s3:
                    endpoint: s3.amazonaws.com
                    bucket: "{{workflow.parameters.s3-bucket}}"
                    key: "{{workflow.parameters.input-json}}"

        - - name: iter-json
            # Iterates over the a set of work units produced by the previous step
            template: big-compute
            arguments:
              parameters:
                - name: param0
                  value: "{{item.param0}}"
                - name: param1
                  value: "{{item.param1}}"
                - name: param2
                  value: "{{item.param2}}"
            withParam: "{{steps.get-inputs.outputs.parameters.json-data}}"

    - name: get-json
      inputs:
        artifacts:
          - name: json-file
            path: /tmp/input.json
      outputs:
        parameters:
          - name: json-data
            valueFrom:
              path: /tmp/data.json
      script:
        image: alpine:latest
        command: [sh]
        source: |
          cp {{inputs.artifacts.json-file.path}} {{outputs.parameters.json-data.path}}
  
    - name: big-compute
      inputs:
        parameters:
          - name: param0
          - name: param1
          - name: param2
      outputs:
        artifacts:
          - name: collected-outputs
            path: /workdir/out
            archive:
              none: {}
            s3:
              endpoint: s3.amazonaws.com
              bucket: "{{workflow.parameters.s3-bucket}}"
              key: "{{workflow.parameters.output-path}}"
      script:
        image: fedora:33
        command: [bash]
        source: |
          set -xe

          mkdir /workdir/out && cd /workdir/out
          echo "{{inputs.parameters.param0}},{{inputs.parameters.param1}},{{inputs.parameters.param2}}" \
                > {{inputs.parameters.param0}}_{{inputs.parameters.param1}}_{{inputs.parameters.param2}}.txt

        resources:
          requests:
            memory: 30Mi
            cpu: 20m
          limits:
            memory: 30Mi
            cpu: 20m
        volumeMounts:
          - name: workdir
            mountPath: /workdir
```
