### ISSUE TITLE
Allow optional input artifacts to fail to resolve without erroring

### ISSUE THREAD

**Issue by samath117** [argoproj/argo-workflows#4647]
# Summary

If an input artifact is optional and its reference fails upon execution, most commonly because the `from` field references another step that was skipped, the workflow should continue with the optional input artifact omitted.

# Use Cases

First requested by sahil sawhney in Slack: "I am trying to skip a step lets say `StepA` using `when` in my workflow and this step produces an artifact which is used by further step lets say `StepB`. Now when `StepA` executes, everything is fine, but when `StepA` is skipped, the workflow fails as `StepB` could not access artifacts that were supposed to be generated by `StepB`"

In general, some data processing pipelines will have optional components that produce artifacts to be brought into the general pipeline, but only if they run. There does not seem to be a built-in way to achieve this type of optionality, i.e. to route this decision-making through the `when` conditional.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This should actually be the case. If an artifact is optional, it should not error. This maybe a bug.

Can you please attach a reproducible workflow YAML manifest and tell me what version you are running?

**Comment by samath117** [comment]
Here's my test example. I'm running Argo v2.11.8

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: optional-input-artifact-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:
    - - name: create-artifact
        template: artifact-creation
        when: "false"
    - - name: print-artifact
        template: artifact-printing
        arguments:
          artifacts:
          - name: artifact
            from: "{{steps.create-artifact.outputs.artifacts.hello}}"

  - name: artifact-creation
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["echo 'hello' > /tmp/hello.txt"]
    outputs:
      artifacts:
      - name: hello
        path: /tmp/hello.txt

  - name: artifact-printing
    inputs:
      artifacts:
      - name: artifact
        path: /tmp/file
        optional: true
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["echo 'goodbye'"]
```

Logs:
```
Name:                optional-input-artifact-b9tn7
Namespace:           sam
ServiceAccount:      default
Status:              Failed
Message:             unable to resolve references: Unable to resolve: {{steps.create-artifact.outputs.artifacts.hello}}
Conditions:
 Completed           True
Created:             Fri Dec 04 14:41:32 -0500 (now)
Started:             Fri Dec 04 14:41:32 -0500 (now)
Finished:            Fri Dec 04 14:41:32 -0500 (now)
Duration:            0 seconds

STEP                              TEMPLATE           PODNAME  DURATION  MESSAGE
 ✖ optional-input-artifact-b9tn7  plan                                  unable to resolve references: Unable to resolve: {{steps.create-artifact.outputs.artifacts.hello}}
 ├---○ create-artifact            artifact-creation                     when 'false' evaluated false
```

**Comment by alexec** [comment]
`unable to resolve references: Unable to resolve: {{steps.create-artifact.outputs.artifacts.hello}}` 

? error is not related to optional?

**Comment by samath117** [comment]
The input artifact `artifact` in `artifact-printing` is optional, and `{{steps.create-artifact.outputs.artifacts.hello}}` is the reference being passed for it in the `print-artifact` invocation. The reference fails, but the artifact is optional so the step should proceed without it.

**Comment by simster7** [comment]
Fix for this is done. Please note that the `optional` flag is required on the parameter as well as the argument:

```yaml
    - - arguments:
          artifacts:
          - from: '{{steps.create-artifact.outputs.artifacts.hello}}'
            name: artifact
            optional: true
        name: print-artifact
        template: artifact-printing
```
