### ISSUE TITLE
Question: How to recover data of postgresql with statefulset.

### ISSUE THREAD

**Issue by mykidong** [argoproj/argo-workflows#4689]
Hi, 

I have installed argo workflow with modifying the manifest of quick-start-postgres https://github.com/argoproj/argo/blob/master/manifests/quick-start-postgres.yaml .
I have changed Deployment of postgres to Statefulset like this:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        component: argo-workflow
      name: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: password
          image: postgres:12-alpine
          name: main
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - psql
                - -U
                - postgres
                - -c
                - SELECT 1
            initialDelaySeconds: 15
            timeoutSeconds: 2
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      nodeSelector:
        kubernetes.io/os: linux
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: direct.csi.min.io
```
I have added a PVC for which I have used minio direct csi to persist postgresql data.
I have tested my spark jobs running with argo workflow. All the jobs work fine. 

Now, I want to see that the postgresql pod of statefulset will get the same pvc without data loss after killing postgresql pod.
I have tried rolling out statefulset of postgresql with adding some annotation to metadata with kubectl edit like this:
```
kubectl edit statefulsets.apps postgres -n ai-developer;
...
...
spec:
...
  template:
    metadata:
      annotations:
        configHash: hash-3
      ...
```
With postgresql statefulset edit, rollout has been done, but it seems that there is no data in postgresql database with reporting error message in argo workflow ui.

As long as I know, a pod in statefulset will be restarted with getting the same pvc without data loss after killing that pod. 
My question is, there is a way to recover data of postgresql using statefulset after rolling out postgresql statefulset?

-- Kidong.
