### ISSUE TITLE
Template reference fails for template with multiple steps

### ISSUE THREAD

**Issue by vivekthangathurai** [argoproj/argo-workflows#4696]
## Summary 

What happened/what you expected to happen?

I am trying to use the workflowTemplate in one of the workflow but an error is thrown saying "template not found"

```
- - name: build-test-push
    templateRef:
         name: ci-pipeline-golang-build-test-docker-push-input-template
         template: ci-pipeline
```
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: workflow-test
  name: ci-pipeline-golang-build-test-docker-push-input-template
spec:
  templates:
    - name: ci-pipline
      inputs:
        artifacts:
          - name: source
        parameters:
          - name: version
          - name: branch
      steps:                 
        - - name: docker-push-development
            template: docker-push-development
            arguments:
              artifacts:
                - name: source
                  from: "{{inputs.artifacts.source}}"
              parameters:
                - name: version
                  value: "{{inputs.parameters.version}}"
        - - name: unit-test
            template: unit-test
            arguments:
              parameters:
                - name: version
                  value: "{{inputs.parameters.version}}"
        - - name: sonar-scanner
            template: sonar-scanner
            arguments:
              artifacts:
                - name: source
                  from: "{{inputs.artifacts.source}}"
        - - name: static-analysis
            template: static-analysis
            arguments:
              artifacts:
                - name: source
                  from: "{{inputs.artifacts.source}}"
                - name: coverage_txt
                  from: "{{steps.unit-test.outputs.artifacts.coverage_txt}}"  
                - name: dependency-check-report
                  from: "{{steps.sonar-scanner.outputs.artifacts.dependency-check-report}}"    
              parameters:
                - name: version
                  value: "{{inputs.parameters.version}}"     
        - - name: docker-push-production
            template: docker-push-production
            arguments:
              artifacts:
                - name: source
                  from: "{{inputs.artifacts.source}}"
              parameters:
                - name: version
                  value: "{{inputs.parameters.version}}"
          - name: docker-push-smoke-test
            template: docker-push-smoke-test
            arguments:
              artifacts:
                - name: source
                  from: "{{inputs.artifacts.source}}"
              parameters:
                - name: version
                  value: "{{inputs.parameters.version}}"
        - - name: git-tag
            template: git-tag
            when: '"{{inputs.parameters.branch}}" == "master"'
            arguments:
              artifacts:
                - name: source
                  from: "{{inputs.artifacts.source}}"
              parameters:
                - name: version
                  value: "{{inputs.parameters.version}}"
............
............ continued
```

## Diagnostics

What Kubernetes provider are you using? 
AWS
What version of Argo Workflows are you running? 
2.10.1

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

kubectl --context=tools.infra.use1  logs -n workflow-test $(kubectl --context=tools.infra.use1  get pods -l app=workflow-controller -n workflow-test  -o name) | grep appconfigrxzpgq
time="2020-12-10T16:42:04Z" level=info msg="Processing workflow" namespace=workflow-test workflow=appconfigrxzpgq
time="2020-12-10T16:42:04Z" level=info msg="Updated phase  -> Running" namespace=workflow-test workflow=appconfigrxzpgq
time="2020-12-10T16:42:04Z" level=info msg="Updated phase Running -> Failed" namespace=workflow-test workflow=appconfigrxzpgq
time="2020-12-10T16:42:04Z" level=info msg="Updated message  -> invalid spec: templates.ci-pipline.steps[4].build-full template reference ci-pipeline-golang-build-test-docker-push-input-template.ci-pipeline not found" namespace=workflow-test workflow=appconfigrxzpgq
time="2020-12-10T16:42:04Z" level=info msg="Marking workflow completed" namespace=workflow-test workflow=appconfigrxzpgq
time="2020-12-10T16:42:04Z" level=info msg="Checking daemoned children of " namespace=workflow-test workflow=appconfigrxzpgq
time="2020-12-10T16:42:04Z" level=info msg="Workflow update successful" namespace=workflow-test phase=Failed resourceVersion=292179954 workflow=appconfigrxzpgq
time="2020-12-10T16:42:04Z" level=info msg="Found Workflow workflow-test/appconfigrxzpgq set expire at 2020-12-10 16:58:44 +0000 UTC (16m39.009883746s from now)"
time="2020-12-10T16:42:04Z" level=info msg="Queueing workflow workflow-test/appconfigrxzpgq for delete in 16m39.009883746s"
time="2020-12-10T16:42:04Z" level=info msg="Found Workflow workflow-test/appconfigrxzpgq set expire at 2020-12-10 16:58:44 +0000 UTC (16m39.009689831s from now)"
time="2020-12-10T16:42:04Z" level=info msg="Queueing workflow workflow-test/appconfigrxzpgq for delete in 16m39.009689831s"
time="2020-12-10T16:42:05Z" level=info msg="appconfigrxzpgq released all acquired locks"
time="2020-12-10T16:42:06Z" level=info msg="Workflow update successful" namespace=workflow-test phase=Failed resourceVersion=292179954 workflow=appconfigrxzpgq
time="2020-12-10T16:44:55Z" level=info msg="Found Workflow workflow-test/appconfigrxzpgq set expire at 2020-12-10 16:58:44 +0000 UTC (13m48.593645407s from now)"
time="2020-12-10T16:44:55Z" level=info msg="Queueing workflow workflow-test/appconfigrxzpgq for delete in 13m48.593645407s"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
