### ISSUE TITLE
failed to save outputs: Timeout: request did not complete within requested timeout 34s

### ISSUE THREAD

**Issue by idsvandermolen** [argoproj/argo-workflows#4754]
## Summary 

We have a cluster-wide Argo install. When deploying a simple workflow with `argo submit --watch ./wf.yaml`, the container finishes but about 30s later we get this error:
```
failed to save outputs: Timeout: request did not complete within requested timeout 34s
```
It is always returning the error with `34s`, even if we change the `sleep` value in the workflow.

## Diagnostics

What Kubernetes provider are you using? 
We are using GKE `v1.17.13-gke.2001`

What version of Argo Workflows are you running? 
Tested with `v2.11.3` and `v2.11.8`

Argo client version `argo version`:
```
argo: latest+310e099.dirty
  BuildDate: 2020-11-21T04:39:19Z
  GitCommit: 310e099f82520030246a7c9d66f3efaadac9ade2
  GitTreeState: dirty
  GitTag: v2.11.8
  GoVersion: go1.15.5
  Compiler: gc
  Platform: darwin/amd64
```

Service Account:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
```

Role (from https://argoproj.github.io/argo/workflow-rbac/):
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
rules:
# pod get/watch is used to identify the container IDs of the current pod
# pod patch is used to annotate the step's outputs back to controller (e.g. artifact location)
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
# logs get/watch are used to get the pods logs for script outputs, and for log archival
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
```

Role-binding:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-role
subjects:
- kind: ServiceAccount
  name: test
```

Original Workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
spec:
  serviceAccountName: test
  entrypoint: main
  templates:
    - name: test
      container:
        image: busybox:1.32.0
        command:
          - /bin/sh
          - -c
          - sleep 1

    - name: main
      dag:
        tasks:
          - name: test
            template: test
```

Output from `kubectl get wf test -o yaml`:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-12-16T14:01:40Z"
  generation: 5
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Error
  name: test
  namespace: cw-app-development-i-van-der-molen
  resourceVersion: "289478561"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/cw-app-development-i-van-der-molen/workflows/test
  uid: 8eac1ba0-13ba-4e01-83d0-6705754bbfbb
spec:
  arguments: {}
  entrypoint: main
  serviceAccountName: test
  templates:
  - arguments: {}
    container:
      command:
      - /bin/sh
      - -c
      - sleep 1
      image: busybox:1.32.0
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: test
    outputs: {}
  - arguments: {}
    dag:
      tasks:
      - arguments: {}
        name: test
        template: test
    inputs: {}
    metadata: {}
    name: main
    outputs: {}
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-12-16T14:03:18Z"
  nodes:
    test:
      children:
      - test-461011369
      displayName: test
      finishedAt: "2020-12-16T14:03:18Z"
      id: test
      name: test
      outboundNodes:
      - test-461011369
      phase: Error
      startedAt: "2020-12-16T14:01:40Z"
      templateName: main
      templateScope: local/test
      type: DAG
    test-461011369:
      boundaryID: test
      displayName: test
      finishedAt: "2020-12-16T14:03:17Z"
      hostNodeName: gke-gc-dev-kube0-default-green-95a55670-3rrl
      id: test-461011369
      message: 'failed to save outputs: Timeout: request did not complete within requested
        timeout 34s'
      name: test.test
      phase: Error
      resourcesDuration:
        cpu: 67
        memory: 67
      startedAt: "2020-12-16T14:01:40Z"
      templateName: test
      templateScope: local/test
      type: Pod
  phase: Error
  resourcesDuration:
    cpu: 67
    memory: 67
  startedAt: "2020-12-16T14:01:40Z"
```

```
time="2020-12-16T14:01:40Z" level=info msg="Processing workflow" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:01:40Z" level=info msg="Updated phase  -> Running" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:01:40Z" level=info msg="DAG node test initialized Running" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:01:40Z" level=info msg="All of node test.test dependencies [] completed" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:01:40Z" level=info msg="Pod node test-461011369 initialized Pending" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:02:10Z" level=info msg="Created pod: test.test (test-461011369)" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:02:10Z" level=info msg="Workflow update successful" namespace=cw-app-development-i-van-der-molen phase=Running resourceVersion=289478025 workflow=test
time="2020-12-16T14:02:11Z" level=info msg="Processing workflow" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:02:11Z" level=info msg="Updating node test-461011369 message: ContainerCreating"
time="2020-12-16T14:02:11Z" level=info msg="Skipped pod test.test (test-461011369) creation: already exists" namespace=cw-app-development-i-van-der-molen podPhase=Pending workflow=test
time="2020-12-16T14:02:11Z" level=info msg="Workflow update successful" namespace=cw-app-development-i-van-der-molen phase=Running resourceVersion=289478038 workflow=test
time="2020-12-16T14:02:12Z" level=info msg="Processing workflow" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:02:12Z" level=info msg="Updating node test-461011369 status Pending -> Running"
time="2020-12-16T14:02:12Z" level=info msg="Workflow update successful" namespace=cw-app-development-i-van-der-molen phase=Running resourceVersion=289478044 workflow=test
time="2020-12-16T14:02:13Z" level=info msg="Processing workflow" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:02:15Z" level=info msg="Processing workflow" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:03:18Z" level=info msg="Processing workflow" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:03:18Z" level=info msg="Pod failed" displayName=test namespace=cw-app-development-i-van-der-molen pod=test-461011369 templateName=test workflow=test
time="2020-12-16T14:03:18Z" level=info msg="Updating node test-461011369 status Running -> Error"
time="2020-12-16T14:03:18Z" level=info msg="Updating node test-461011369 message: failed to save outputs: Timeout: request did not complete within requested timeout 34s"
time="2020-12-16T14:03:18Z" level=info msg="Outbound nodes of test set to [test-461011369]" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:03:18Z" level=info msg="node test phase Running -> Error" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:03:18Z" level=info msg="node test finished: 2020-12-16 14:03:18.125664513 +0000 UTC" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:03:18Z" level=info msg="Checking daemoned children of test" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:03:18Z" level=info msg="Updated phase Running -> Error" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:03:18Z" level=info msg="Marking workflow completed" namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:03:18Z" level=info msg="Checking daemoned children of " namespace=cw-app-development-i-van-der-molen workflow=test
time="2020-12-16T14:03:18Z" level=info msg="Workflow update successful" namespace=cw-app-development-i-van-der-molen phase=Error resourceVersion=289478561 workflow=test
time="2020-12-16T14:03:49Z" level=info msg="Labeled pod completed" namespace=cw-app-development-i-van-der-molen pod=test-461011369
```
```argo get test
Name:                test
Namespace:           cw-app-development-i-van-der-molen
ServiceAccount:      test
Status:              Error
Conditions:          
 Completed           True
Created:             Wed Dec 16 15:01:40 +0100 (15 minutes ago)
Started:             Wed Dec 16 15:01:40 +0100 (15 minutes ago)
Finished:            Wed Dec 16 15:03:18 +0100 (14 minutes ago)
Duration:            1 minute 38 seconds
ResourcesDuration:   1m7s*(1 cpu),1m7s*(100Mi memory)

STEP       TEMPLATE  PODNAME         DURATION  MESSAGE
 ⚠ test    main                                                                                                                        
 └-⚠ test  test      test-461011369  1m        failed to save outputs: Timeout: request did not complete within requested timeout 34s  
```
Logs from wait container `kubectl logs test-461011369 wait`:
```
time="2020-12-16T14:02:11.855Z" level=info msg="Starting Workflow Executor" version=v2.11.8
time="2020-12-16T14:02:11.858Z" level=info msg="Creating a docker executor"
time="2020-12-16T14:02:11.858Z" level=info msg="Executor (version: v2.11.8, build_date: 2020-11-21T03:26:01Z) initialized (pod: cw-app-development-i-van-der-molen/test-461011369) with template:\n{\"name\":\"test\",\"arguments\":{},\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"busybox:1.32.0\",\"command\":[\"/bin/sh\",\"-c\",\"sleep 1\"],\"resources\":{}}}"
time="2020-12-16T14:02:11.858Z" level=info msg="Waiting on main container"
time="2020-12-16T14:02:12.075Z" level=info msg="main container started with container ID: 445696f0be5ddecca8ef9be3ff94ffab366b9f073f9935f022495ab0e688e530"
time="2020-12-16T14:02:12.075Z" level=info msg="Starting annotations monitor"
time="2020-12-16T14:02:12.080Z" level=info msg="Starting deadline monitor"
time="2020-12-16T14:02:12.080Z" level=info msg="docker wait 445696f0be5ddecca8ef9be3ff94ffab366b9f073f9935f022495ab0e688e530"
time="2020-12-16T14:02:13.070Z" level=info msg="Main container completed"
time="2020-12-16T14:02:13.070Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2020-12-16T14:02:13.070Z" level=info msg="Capturing script exit code"
time="2020-12-16T14:02:13.070Z" level=info msg="Annotations monitor stopped"
time="2020-12-16T14:02:13.080Z" level=info msg="Deadline monitor stopped"
time="2020-12-16T14:02:13.096Z" level=info msg="No output parameters"
time="2020-12-16T14:02:13.096Z" level=info msg="No output artifacts"
time="2020-12-16T14:02:13.096Z" level=info msg="Annotating pod with output"
time="2020-12-16T14:02:47.101Z" level=error msg="executor error: Timeout: request did not complete within requested timeout 34s"
time="2020-12-16T14:02:47.101Z" level=info msg="Killing sidecars"
time="2020-12-16T14:02:47.106Z" level=info msg="Alloc=6771 TotalAlloc=14712 Sys=70336 NumGC=4 Goroutines=7"
time="2020-12-16T14:03:17.121Z" level=fatal msg="Timeout: request did not complete within requested timeout 34s"
```

Perhaps it's a somehow related to https://github.com/argoproj/argo/issues/4692 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
