### ISSUE TITLE
Unable to resolve global artifacts created in nested workflows

### ISSUE THREAD

**Issue by Trojan295** [argoproj/argo-workflows#4772]
## Summary 

I try to create a workflow with nested workflows, which export global artifacts in some steps. These global artifacts are then used as `arguments` in steps in the entrypoint workflow.

In case the global artifacts are created in a nested workflow at depth 2 or more, then Argo fails the workflow validation and does not start the workflow:
```
Failed: invalid spec: templates.global-output.steps failed to resolve {{workflow.outputs.artifacts.global-art}}
```

I believe it's a bug, as global artifacts created at the nested depth 1 can be used. I also tried to build Argo without the validation (by commenting out https://github.com/argoproj/argo/blob/master/workflow/controller/operator.go#L262) and my workflow passed successfully.

## Diagnostics

**What Kubernetes provider are you using?** 
I'm using `kind` 1.19.1
```
$ kubectl version                                                            
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Argo Workflows are you running?** 
I'm using Argo v2.11.7

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: global-output
spec:
  entrypoint: global-output

  templates:
  - name: global-output
    steps:
    - - name: nested
        template: nested-level1
    - - name: consume-global
        template: consume-global
        arguments:
          artifacts:
          - name: art
            from: "{{workflow.outputs.artifacts.global-art}}"

  - name: nested-level1
    steps:
      - - name: nested
          template: output-global

  - name: output-global
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["sleep 1; echo -n art > /tmp/art.txt; echo -n param > /tmp/param.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/art.txt
        globalName: global-art

  - name: consume-global
    inputs:
      artifacts:
      - name: art
        path: /art
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["cat /art"]
```
Status from `kubectl get wf -o yaml ${workflow} `
```
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-12-18T09:42:26Z"
  message: 'invalid spec: templates.global-output.steps failed to resolve {{workflow.outputs.artifacts.global-art}}'
  phase: Failed
  startedAt: "2020-12-18T09:42:26Z"
```

Logs from the `workflow-controller`:
```
time="2020-12-18T09:39:45Z" level=info msg="config map" name=argo-workflow-controller-configmap
time="2020-12-18T09:39:45Z" level=info msg="Configuration:\nartifactRepository:\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: argo-minio\n    bucket: argo-artifacts\n    endpoint: argo-minio.argo.svc.cluster.local:9000\n    insecure: true\n    secretKeySecret:\n      key: secretkey\n      name: argo-minio\ncontainerRuntimeExecutor: pns\nexecutor:\n  name: \"\"\n  resources:\n    limits:\n      cpu: 500m\n      memory: 512Mi\n    requests:\n      cpu: 100m\n      memory: 64Mi\nmetricsConfig: {}\nnodeEvents: {}\npodSpecLogStrategy: {}\nsso:\n  clientId:\n    key: \"\"\n  clientSecret:\n    key: \"\"\n  issuer: \"\"\n  redirectUrl: \"\"\ntelemetryConfig: {}\n"
time="2020-12-18T09:39:45Z" level=info msg="Persistence configuration disabled"
time="2020-12-18T09:39:45Z" level=info msg="Starting Workflow Controller" version=v2.11.7
time="2020-12-18T09:39:45Z" level=info msg="Workers: workflow: 32, pod: 32"
time="2020-12-18T09:39:45Z" level=info msg="Persistence disabled - so archived workflow GC disabled - you must restart the controller if you enable this"
time="2020-12-18T09:39:45Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2020-12-18T09:39:45Z" level=info msg="Performing periodic GC every 5m0s"
time="2020-12-18T09:39:45Z" level=info msg="Starting prometheus metrics server at localhost:9090/metrics"
time="2020-12-18T09:39:45Z" level=info msg="Starting CronWorkflow controller"
time="2020-12-18T09:39:45Z" level=info msg="Started workflow TTL worker"
time="2020-12-18T09:39:45Z" level=info msg="Manager initialized successfully"
time="2020-12-18T09:42:26Z" level=info msg="Processing workflow" namespace=default workflow=global-output
time="2020-12-18T09:42:26Z" level=info msg="Updated phase  -> Running" namespace=default workflow=global-output
time="2020-12-18T09:42:26Z" level=info msg="Updated phase Running -> Failed" namespace=default workflow=global-output
time="2020-12-18T09:42:26Z" level=info msg="Updated message  -> invalid spec: templates.global-output.steps failed to resolve {{workflow.outputs.artifacts.global-art}}" namespace=default workflow=global-output
time="2020-12-18T09:42:26Z" level=info msg="Marking workflow completed" namespace=default workflow=global-output
time="2020-12-18T09:42:26Z" level=info msg="Checking daemoned children of " namespace=default workflow=global-output
time="2020-12-18T09:42:26Z" level=info msg="Workflow update successful" namespace=default phase=Failed resourceVersion=2178 workflow=global-output
time="2020-12-18T09:44:45Z" level=info msg="Alloc=5486 TotalAlloc=22105 Sys=72128 NumGC=10 Goroutines=174"
time="2020-12-18T09:49:45Z" level=info msg="Alloc=5551 TotalAlloc=22409 Sys=72128 NumGC=12 Goroutines=174"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
