### ISSUE TITLE
wf step should skip instead of parsing `withParam` when `when` evaluated False

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#4784]
## Summary 

What happened/what you expected to happen?

When `when` condition is evaluated False, wf step should skip instead of parsing `withParam `values (dag is doing it this way)

Maybe controller/steps.go should check shouldExecute(step.When) before expandStep in expandStepGroup

## Diagnostics

What Kubernetes provider are you using? 

k3d

What version of Argo Workflows are you running? 

master af03a74

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-result-
spec:
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    steps:
    - - name: generate
        template: gen-number-list
      # Iterate over the list of numbers generated by the generate step above
    - - name: sleep
        template: sleep-n-sec
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"
        when: "{{steps.generate.outputs.result}} == 2"
  # Generate a list of numbers in JSON format
  - name: gen-number-list
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        print(1)

  - name: sleep-n-sec
    inputs:
      parameters:
      - name: seconds
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo sleeping for {{inputs.parameters.seconds}} seconds; sleep {{inputs.parameters.seconds}}; echo done"]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
