### ISSUE TITLE
does it support nested steps definition?

### ISSUE THREAD

**Issue by arraytodd** [argoproj/argo-workflows#4792]
# Summary

I want to define steps keywork in steps context, such as
 steps:
 
    - - name: test1
        template: run-hello
      - name: test2
        template: run-hello
        -- name: test2-01
            template: run-hello
        -- name: test2-02
            template: run-hello

    - - name: exit
        template: run-exit
    - - name: cleanup
        template: cleanup
# Use Cases
but got a error:
 error converting YAML to JSON: yaml: line 52: mapping values are not allowed in this context
When would you use this?
![flow](https://user-images.githubusercontent.com/12149026/102857489-79bfdc00-4463-11eb-9078-6d755f32bed0.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by arraytodd** [comment]
please ignore the type, the correct version as below:

- - name: test1
    template: run-hello
  - name: test2
    template: run-hello
    - - name: test2-01
        template: run-hello
    - - name: test2-02
        template: run-hello

- - name: exit
    template: run-exit
- - name: cleanup
    template: cleanup

I add two steps under the step named test2, but not works

**Comment by dinever** [comment]
Hi @arraytodd I think DAG should be the way to go here: https://argoproj.github.io/argo-workflows/examples/#dag

Just make sure you set the `dependencies` correctly.

If you really want to stick with `steps`. You can define the sub-steps inside another template. For example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
​
  # This spec contains two templates: hello-hello-hello and whalesay
  templates:
  - name: hello-hello-hello
    # Instead of just running a container
    # This template has a sequence of steps
    steps:
    - - name: hello1            # hello1 is run before the following steps
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: hello2a           # double dash => run after previous step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2a"
      - name: more-steps           # single dash => run in parallel with previous step
        template: more-steps
​
  # This is the same template as from the previous example
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
​
  - name: more-steps
    steps:
    - - name: hello2b
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2b"
    - - name: hello3b
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello3b"
```

This gives:

![Screen Shot 2021-02-23 at 1 26 40 AM](https://user-images.githubusercontent.com/1311594/108872935-b2497680-75c8-11eb-8d69-9c8ca2bb934c.png)
