### ISSUE TITLE
Can't pass artifacts into a subworkflow create from a workflow template

### ISSUE THREAD

**Issue by simonfrey** [argoproj/argo-workflows#4796]
I try to get my workflows more DRY and for this I need to create a sub workflow and pass arguments to it. 

I tried to follow https://github.com/argoproj/argo/blob/master/examples/nested-workflow.yaml & https://argoproj.github.io/argo/workflow-of-workflows/ but either I get the structure wrong or argo has a problem with artifact passing to sub workflows

## Expected behavior

Argo passes artifacts into sub workflow and executes without errors

## Actual behavior

Argo fails with a weird message regarding secrets:

```
failed to load artifacts: open /argo/secret/artifacts-sa/service-account: no such file or directory
```

### Main
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: main
  namespace: argo
spec:
  entrypoint: wf
  serviceAccountName: deploy-image-wf
  templates:
    - name: wf
      dag:
        tasks:
          - name: create-artifacts
            template: create-artifacts
          - name: consume-artifacts
            template: consume-artifacts
            dependencies: [create-artifacts]
            arguments:
              artifacts:
                - name: files
                  from: "{{tasks.create-artifacts.outputs.artifacts.files}}"
    - name: create-artifacts
      outputs:
        artifacts:
          - name: files
            path: /tmp/artifacts_out
      container:
        image: docker/whalesay:latest
        command: [sh, -c]
        args: ["
          cowsay hello world | tee /tmp/artifacts_out
        "]
    - name: consume-artifacts
      inputs:
        artifacts:
          - name: files
            path: /tmp/artifacts_out
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: deploy-image-subworkflow-
          spec:
            arguments:
              artifacts: 
                - name: files
                  from: "{{inputs.artifacts.files}}"
            workflowTemplateRef:
              name: consume-artifacts
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
```
### consume-artifacts
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: consume-artifacts
  namespace: argo
spec:
  entrypoint: wf
  serviceAccountName: deploy-image-wf
  arguments:
    artifacts:
      - name: files
        path: /tmp/files
        from: " "
  templates:
    - name: wf
      dag:
        tasks:
          - name: consume
            template: consume
    - name: consume
      container:
        image: alpine:3.7
        command: [sh, -c]
        args: ["
          cat /tmp/files
        "]
```
