### ISSUE TITLE
Stream processing using pre-spun up services

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4865]
# Summary

Rather than using a pod to process each items in `withItems` it might be neat to submit the work to a service, one which could be spun up at the start of a workflows:

```yaml
spec:
  services:
    - name: my-processor
      template:
        spec: # .pod spec
  templates:
    - name: data
       service:
         name: my-processor
      withItems: [1, 2]
```

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
