### ISSUE TITLE
`workflow.parameters` cannot be referenced in `synchronization` field

### ISSUE THREAD

**Issue by hisener** [argoproj/argo-workflows#4894]
## Summary 

`workflow.parameters` cannot be used in `synchronization` (both mutex and semaphore) after upgrading from v2.11.7 to v2.12.4. I am using it in `WorkflowTemplate` if that matters.

## Diagnostics

What Kubernetes provider are you using? 

EKS v1.15.12-eks-31566f

What version of Argo Workflows are you running? 

v2.12.4

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: semaphore-ref
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: semaphoreConfigMapKeyRef
        value: ""
  synchronization:
    semaphore:
      configMapKeyRef:
        name: my-config
        key: "{{workflow.parameters.semaphoreConfigMapKeyRef}}"
  templates:
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["hello world"]
```

```
$ kubectl logs
Failed to acquire the synchronization lock. configmaps "{{workflow.parameters.semaphoreConfigMapKeyRef}}" not found
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mutex
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: repository
        value: ""
  synchronization:
    mutex:
      name: "{{workflow.parameters.repository}}"
  templates:
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["hello world"]
```

```
Paste the logs from the workflow controller:
$ kubectl logs
time="2021-01-17T11:10:04.994Z" level=info msg="argo/Mutex/{{workflow.parameters.repository}} acquired by argo/picnic-argo-gh-m2ppc " mutex="argo/Mutex/{{workflow.parameters.repository}}"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@sarabala1979 ?

**Comment by sarabala1979** [comment]
I will take a look

**Comment by sarabala1979** [comment]
Current design `spec` level `synchronization` doesn't support the parameter substitution.  But Template level `synchronization` will support the parameter substitution.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mutex
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: repository
        value: ""
  templates:
    - name: whalesay
       synchronization:
          mutex:
             name: "{{workflow.parameters.repository}}"
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["hello world"]
```
