### ISSUE TITLE
Unable to resume workflow for a particular node when multiple nodes are suspended 

### ISSUE THREAD

**Issue by Deepa050** [argoproj/argo-workflows#4910]
## Summary 

I have two nodes suspended and I am trying to resume one of them using API  and nodefieldselector as display name 

## Diagnostics

argo version 

argo: v2.12.3
  BuildDate: 2021-01-05T00:49:48Z
  GitCommit: 93ee530126cc1fc154ada84d5656ca82d491dc7f
  GitTreeState: clean
  GitTag: v2.12.3
  GoVersion: go1.13
  Compiler: gc
  Platform: darwin/amd64

I have 3 workflow templates created. 

1st template
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sample-template
spec:
  templates:
  - name: email
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: approval
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: promote
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: waiting-for-approval
    suspend: {}
```

2nd template 
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wftempl1
spec:
  templates:
  - name: approval-and-promotion
    dag:
      tasks:
      - name: notification-email
        templateRef:
          name: sample-template
          template: email
        arguments:
          parameters:
          - name: message
            value: email-value
      - name: wait-approval
        dependencies: [notification-email]
        templateRef:
          name: sample-template
          template: waiting-for-approval
      - name: register-approval-to-tool
        dependencies: [wait-approval]
        templateRef:
          name: sample-template
          template: approval
        arguments:
          parameters:
          - name: message
            value: approved
      - name: deployment
        dependencies: [register-approval-to-tool]
        templateRef:
          name: sample-template
          template: promote
        arguments:
          parameters:
          - name: message
            value: promoted
```

3rd template 
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wftempl2
spec:
  templates:
  - name: promotion
    dag:
      tasks:
      - name: notification-email
        templateRef:
          name: sample-template
          template: email
        arguments:
          parameters:
          - name: message
            value: email-value
      - name: pr-approval
        dependencies: [notification-email]
        templateRef:
          name: sample-template
          template: approval
        arguments:
          parameters:
          - name: message
            value: approved
      - name: deployment
        dependencies: [pr-approval]
        templateRef:
          name: sample-template
          template: promote
        arguments:
          parameters:
          - name: message
            value: promoted
```

Workflow submitted is refering the above templates 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: appr-promotion-
spec:
  entrypoint: code-release
  templates:
  - name: code-release
    dag:
      tasks:
      - name: start
        templateRef:
          name: sample-template
          template: email
        arguments:
          parameters:
          - name: message
            value: start
      - name: app1
        dependencies: [start]
        templateRef:
          name: wftempl1
          template: approval-and-promotion
      - name: app2
        dependencies: [start]
        templateRef:
          name: wftempl2
          template: promotion
      - name: app3
        dependencies: [start]
        templateRef:
          name: wftempl1
          template: approval-and-promotion
      - name: deployment-complete
        dependencies: [app1,app2,app3]
        templateRef:
          name: sample-template
          template: email
        arguments:
          parameters: [{name: message, value: deployment request complete}]
```

I am trying to resume task app3 using below api and payload but its not working.
http://localhost:2746/api/v1/workflows/argo/appr-promotion-zh6bj/resume
```
{
    "namespace": "argo",
    "name": "appr-promotion-zh6bj",
    "nodeFieldSelector": "displayName=appr-promotion-zh6bj.app3.wait-approval"
}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
