### ISSUE TITLE
Identify A Workflow Archive Process From Argo Events

### ISSUE THREAD

**Issue by kennytrytek-wf** [argoproj/argo-workflows#4917]
# Summary

If I use Argo Events to emit events on `workflow` resources, I receive an event indicating that a workflow is deleted when the archive process runs. However, deleting a workflow does not guarantee it was archived; it may have only been deleted.

I would like some kind of information to exist on the event that indicates the workflow has been archived.

<details><summary>Here is an example EventSource configured to watch workflows:</summary>
<p>

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: workflows
spec:
  resource:
    workflow-change:
      namespace: argo
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      eventTypes:
        - ADD
        - UPDATE
        - DELETE
      filter:
        afterStart: true
```

</p>
</details>

<details><summary>After executing the Hello World example, here is the final event received from a Sensor sending HTTP requests to a local server:</summary>
<p>

```
{
  "body": {
    "apiVersion": "argoproj.io/v1alpha1",
    "kind": "Workflow",
    "metadata": {
      "creationTimestamp": "2021-01-20T19:55:28Z",
      "generateName": "hello-world-",
      "generation": 6,
      "labels": {
        "workflows.argoproj.io/archive-strategy": "false",
        "workflows.argoproj.io/completed": "true",
        "workflows.argoproj.io/phase": "Succeeded"
      },
      "name": "hello-world-2lhkj",
      "namespace": "argo",
      "resourceVersion": "41184396",
      "selfLink": "/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/hello-world-2lhkj",
      "uid": "2af9c0df-bcc7-43b0-987d-8f412f0a110d"
    },
    "spec": {
      "arguments": {},
      "entrypoint": "whalesay",
      "serviceAccountName": "<redacted>",
      "templates": [
        {
          "arguments": {},
          "container": {
            "args": [
              "hello world"
            ],
            "command": [
              "cowsay"
            ],
            "image": "docker/whalesay:latest",
            "name": "",
            "resources": {}
          },
          "inputs": {},
          "metadata": {},
          "name": "whalesay",
          "outputs": {}
        }
      ],
      "ttlStrategy": {
        "secondsAfterFailure": 604800,
        "secondsAfterSuccess": 1
      }
    },
    "status": {
      "conditions": [
        {
          "status": "True",
          "type": "Completed"
        }
      ],
      "finishedAt": "2021-01-20T19:55:35Z",
      "nodes": {
        "hello-world-2lhkj": {
          "displayName": "hello-world-2lhkj",
          "finishedAt": "2021-01-20T19:55:33Z",
          "hostNodeName": "<redacted>",
          "id": "hello-world-2lhkj",
          "name": "hello-world-2lhkj",
          "outputs": {
            "artifacts": [
              {
                "archiveLogs": true,
                "name": "main-logs",
                "s3": {
                  "accessKeySecret": {
                    "key": "<redacted>",
                    "name": "<redacted>"
                  },
                  "bucket": "<redacted>",
                  "endpoint": "s3.amazonaws.com",
                  "key": "hello-world-2lhkj/hello-world-2lhkj/main.log",
                  "secretKeySecret": {
                    "key": "<redacted>",
                    "name": "<redacted>"
                  }
                }
              }
            ],
            "exitCode": "0"
          },
          "phase": "Succeeded",
          "resourcesDuration": {
            "cpu": 3,
            "memory": 3
          },
          "startedAt": "2021-01-20T19:55:28Z",
          "templateName": "whalesay",
          "templateScope": "local/hello-world-2lhkj",
          "type": "Pod"
        }
      },
      "phase": "Succeeded",
      "resourcesDuration": {
        "cpu": 3,
        "memory": 3
      },
      "startedAt": "2021-01-20T19:55:28Z"
    }
  },
  "id": "36616632636231622d303364622d343238312d623532382d613530353264613934623164",
  "type": "DELETE"
}
```

</p>
</details>

# Use Cases

In this case, Argo Events are being used to update information in an in-house CI/CD database.

# Expected Behavior

Looking at the following parts of the Argo code base leads me to believe that a label should be applied to the Workflow ending in "/workflow-archiving-status", and I would expect to see that label in the DELETE event shown above. So maybe this is closer to a bug than enhancement, but I may not be understanding the system correctly.
[Archive status label](https://github.com/argoproj/argo/blob/v2.12.5/workflow/common/common.go#L63-L68)
[Add pending archive status label during workflow phase update (if archiving is enabled)](https://github.com/argoproj/argo/blob/6e961ec928ee35e3ae022826f020c9722ad614d6/workflow/controller/operator.go#L1919-L1926)
[Configure workflow controller to watch for and act on workflows that have pending archive label](https://github.com/argoproj/argo/blob/f872366f3b40fc346266e3ae328bdc25eb2082ec/workflow/controller/controller.go#L766-L780)
[Update archive status label after archive is complete](https://github.com/argoproj/argo/blob/f872366f3b40fc346266e3ae328bdc25eb2082ec/workflow/controller/controller.go#L820-L850)
[Actual DB archive operation (only tangentially related, not important here)](https://github.com/argoproj/argo/blob/f872366f3b40fc346266e3ae328bdc25eb2082ec/persist/sqldb/workflow_archive.go#L76)

I know we have archiving configured correctly because workflows get archived automatically. However, neither of [these INFO log messages](https://github.com/argoproj/argo/blob/6e961ec928ee35e3ae022826f020c9722ad614d6/workflow/controller/operator.go#L1919-L1926) get shown in the workflow controller output. This seems to support the idea that the archive-status label should never be applied, but then my question becomes: How are any workflows archived? I thought the archive-status label was central to how Argo keeps track of workflow archive status? I see that in those lines I just linked the controller is operating on the `wf` object instead of `orig`, so maybe it's not expected that those labels are persisted?

Here is a subset of our configuration:
```
controller:
  persistence:
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
    nodeStatusOffLoad: false
    archive: true
    postgresql:
      ssl: true
      sslMode: require
      host: '' # populated at deploy time
      port: '' # populated at deploy time
      database: postgres
      tableName: argo_workflows
  workflowDefaults:
    spec:
      serviceAccountName: argo-workflow
      ttlStrategy:
        secondsAfterSuccess: 1
        secondsAfterFailure: 604800
```

---

**Message from the maintainers**:

Want this feature? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
what version are you running? >v2.12ish?

**Comment by kennytrytek** [comment]
Looks like v2.11.7 right now.

**Comment by alexec** [comment]
To determine that a workflow has been archived you may look for `workflows.argoproj.io/workflow-archiving-status: Archived`. Only completed workflows are archived, it is possible to delete workflows before they can be completed and therefore before they are archived.

**Comment by kennytrytek-wf** [comment]
I assume `workflows.argoproj.io/workflow-archiving-status` will be a label on the Workflow object? If so, why doesn't that label appear in the event included in the description?
```
      "labels": {
        "workflows.argoproj.io/archive-strategy": "false",
        "workflows.argoproj.io/completed": "true",
        "workflows.argoproj.io/phase": "Succeeded"
      },
```
Is there any way to receive that information through the Event stream?

**Comment by alexec** [comment]
Could it be due to this label?

workflows.argoproj.io/archive-strategy": "false"

Presumably you’ve added this to prevent archiving?

**Comment by kennytrytek-wf** [comment]
It is possible that label is related, though that is not something I have set and the archive process still happens automatically as configured in the controller:
```
controller:
  persistence:
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
    nodeStatusOffLoad: false
    archive: true
  workflowDefaults:
    spec:
      serviceAccountName: argo-workflow
      ttlStrategy:
        secondsAfterSuccess: 1
        secondsAfterFailure: 604800
```

Is there some other setting I need to change that would cause different labels to be used or produce different events?
