### ISSUE TITLE
Workflow hangs and odd linkage errors when using retryStrategy in workflowDefaults and withParam

### ISSUE THREAD

**Issue by snowzach** [argoproj/argo-workflows#4950]
## Summary 
I am running a simple workflow. I was having issues with workflows randomly failing. I added retryStrategy to the defaultWorkflow options to have it basically auto-retry anything that failed. It seems like it's causing random hangs in my workflows during the onExit stage. I am starting to wonder  if it's also related to the withParam section of my workflow as without that I had a much harder time reproducing it.

## Diagnostics
What Kubernetes provider are you using? GKE
What version of Argo Workflows are you running?  2.12.6

Argo Configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  containerRuntimeExecutor: pns # Needed to work with containerd
  workflowDefaults: |
    spec:
      activeDeadlineSeconds: 28800
      podGC:
        strategy: OnWorkflowSuccess
      ttlStrategy:
        secondsAfterCompletion: 28800
      retryStrategy:
        retryPolicy: OnError
        limit: 3
```

Simple Workflow - Will work the first time... run it a few more times concurrently and it should hang.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: error-example-
spec:
  onExit: exiter
  entrypoint: main-workflow
  templates:
  - name: main-workflow
    steps:
    # Get a timestamp to use for the report
    - - name: whalesay
        template: whalesay
        arguments:
          parameters:
            - name: item
              value: "{{item}}"
        withItems:
        - A
        - B
        - C
  
  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["ITEM: {{inputs.parameters.item}}"]
      resources:
        limits:
          memory: 32Mi
          cpu: 100m
    inputs:
      parameters:
      - name: item

  - name: exiter
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["I'm done"]
      resources:
        limits:
          memory: 32Mi
          cpu: 100m
```

This is what the UI looks like when I run that workflow: 

![image](https://user-images.githubusercontent.com/7305473/105871935-d153e900-5fc7-11eb-9c11-7aebbd45eb09.png)

When I have the retryStrategy in the defaultWorkflow it's like there's no parent node.

It works the first time I run it... It processes both and the `onExit` works as expected. It seems like if you continue to run the same workflow it will hang at the onExit stage.
