### ISSUE TITLE
Workflow cannot  be deleted by TTL when templates have a daemon node

### ISSUE THREAD

**Issue by njlkj** [argoproj/argo-workflows#4956]
## Summary 

What happened/what you expected to happen?

Workflow  should be auto deleted by ttl controller, but because of `daemon ` node,workflow  cannot be set completed.I think  `!woc.hasDaemonNodes()` can't be used as a judgment condition. 
 
```golang
       # workflow/controller/operator.go:1900
	switch phase {
	case wfv1.WorkflowSucceeded, wfv1.WorkflowFailed, wfv1.WorkflowError:
		// wait for all daemon nodes to get terminated before marking workflow completed
		if markCompleted && !woc.hasDaemonNodes() {
			woc.log.Infof("Marking workflow completed")
			woc.wf.Status.FinishedAt = metav1.Time{Time: time.Now().UTC()}
			woc.globalParams[common.GlobalVarWorkflowDuration] = fmt.Sprintf("%f", woc.wf.Status.FinishedAt.Sub(woc.wf.Status.StartedAt.Time).Seconds())
			if woc.wf.ObjectMeta.Labels == nil {
				woc.wf.ObjectMeta.Labels = make(map[string]string)
			}
			woc.wf.ObjectMeta.Labels[common.LabelKeyCompleted] = "true"
			woc.wf.Status.Conditions.UpsertCondition(wfv1.Condition{Status: metav1.ConditionTrue, Type: wfv1.ConditionTypeCompleted})
			err := woc.deletePDBResource(ctx)
			if err != nil {
				woc.wf.Status.Phase = wfv1.WorkflowError
				woc.wf.ObjectMeta.Labels[common.LabelKeyPhase] = string(wfv1.NodeError)
				woc.updated = true
				woc.wf.Status.Message = err.Error()
			}
			if woc.controller.wfArchive.IsEnabled() {
				if woc.controller.isArchivable(woc.wf) {
					woc.log.Infof("Marking workflow as pending archiving")
					woc.wf.Labels[common.LabelKeyWorkflowArchivingStatus] = "Pending"
				} else {
					woc.log.Infof("Doesn't match with archive label selector. Skipping Archive")
				}
			}
			woc.updated = true
		}
	}

```

## Diagnostics

What Kubernetes provider are you using? 
v1.18.3
What version of Argo Workflows are you running? 
latest
```yaml
# kubectl -nargo get wf daemon-nginx-ch8bv  
daemon-nginx-ch8bv                 Succeeded   19m
#  kubectl -nargo describe wf  daemon-nginx-ch8bv             
Name:         daemon-nginx-ch8bv
Namespace:    argo
Labels:       createby=lkj
              workflows.argoproj.io/phase=Succeeded
Annotations:  <none>
API Version:  argoproj.io/v1alpha1
Kind:         Workflow
Metadata:
  Creation Timestamp:  2021-01-27T08:09:27Z
  Generate Name:       daemon-nginx-
  Generation:          5
  Managed Fields:
    API Version:  argoproj.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName:
      f:spec:
        .:
        f:entrypoint:
        f:serviceAccountName:
    Manager:      kubectl
    Operation:    Update
    Time:         2021-01-27T08:09:27Z
    API Version:  argoproj.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:createby:
          f:workflows.argoproj.io/phase:
      f:spec:
        f:arguments:
        f:templates:
        f:ttlStrategy:
          .:
          f:secondsAfterSuccess:
      f:status:
        .:
        f:artifactRepositoryRef:
          .:
          f:default:
        f:conditions:
        f:finishedAt:
        f:nodes:
          .:
          f:daemon-nginx-ch8bv:
            .:
            f:children:
            f:displayName:
            f:finishedAt:
            f:id:
            f:name:
            f:outboundNodes:
            f:phase:
            f:progress:
            f:resourcesDuration:
              .:
              f:cpu:
              f:memory:
            f:startedAt:
            f:templateName:
            f:templateScope:
            f:type:
          f:daemon-nginx-ch8bv-2446417455:
            .:
            f:boundaryID:
            f:children:
            f:displayName:
            f:finishedAt:
            f:id:
            f:name:
            f:phase:
            f:progress:
            f:resourcesDuration:
              .:
              f:cpu:
              f:memory:
            f:startedAt:
            f:templateName:
            f:templateScope:
            f:type:
          f:daemon-nginx-ch8bv-2513675026:
            .:
            f:boundaryID:
            f:children:
            f:displayName:
            f:finishedAt:
            f:id:
            f:name:
            f:phase:
            f:progress:
            f:resourcesDuration:
              .:
              f:cpu:
              f:memory:
            f:startedAt:
            f:templateName:
            f:templateScope:
            f:type:
          f:daemon-nginx-ch8bv-2782442775:
            .:
            f:boundaryID:
            f:displayName:
            f:finishedAt:
            f:id:
            f:inputs:
              .:
              f:parameters:
            f:name:
            f:outputs:
              .:
              f:artifacts:
              f:exitCode:
            f:phase:
            f:progress:
            f:resourcesDuration:
              .:
              f:cpu:
              f:memory:
            f:startedAt:
            f:templateName:
            f:templateScope:
            f:type:
          f:daemon-nginx-ch8bv-3699291052:
            .:
            f:boundaryID:
            f:children:
            f:displayName:
            f:finishedAt:
            f:hostNodeName:
            f:id:
            f:name:
            f:outputs:
              .:
              f:artifacts:
              f:exitCode:
            f:phase:
            f:podIP:
            f:progress:
            f:resourcesDuration:
              .:
              f:cpu:
              f:memory:
            f:startedAt:
            f:templateName:
            f:templateScope:
            f:type:
        f:phase:
        f:progress:
        f:resourcesDuration:
          .:
          f:cpu:
          f:memory:
        f:startedAt:
    Manager:         workflow-controller
    Operation:       Update
    Time:            2021-01-27T08:09:57Z
  Resource Version:  22664529
  Self Link:         /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/daemon-nginx-ch8bv
  UID:               b3f88e3e-e8c0-4349-bc32-6d13aac4be4b
Spec:
  Arguments:
  Entrypoint:            daemon-nginx-example
  Service Account Name:  argo
  Templates:
    Arguments:
    Inputs:
    Metadata:
    Name:  daemon-nginx-example
    Outputs:
    Steps:
      [map[arguments:map[] name:nginx-server template:nginx-server]]
      [map[arguments:map[parameters:[map[name:server-ip value:{{steps.nginx-server.ip}}]]] name:nginx-client template:nginx-client]]
    Arguments:
    Container:
      Image:  nginx:v1
      Name:   
      Readiness Probe:
        Http Get:
          Path:                 /
          Port:                 80
        Initial Delay Seconds:  2
        Timeout Seconds:        1
      Resources:
    Daemon:  true
    Inputs:
    Metadata:
    Name:  nginx-server
    Outputs:
    Arguments:
    Container:
      Args:
        echo curl --silent -G http://{{inputs.parameters.server-ip}}:80/ && curl --silent -G http://{{inputs.parameters.server-ip}}:80/
      Command:
        /bin/sh
        -c
      Image:  curl:v1
      Name:   
      Resources:
    Inputs:
      Parameters:
        Name:  server-ip
    Metadata:
    Name:  nginx-client
    Outputs:
  Ttl Strategy:
    Seconds After Success:  300
Status:
  Artifact Repository Ref:
    Default:  true
  Conditions:
    Status:     False
    Type:       PodRunning
  Finished At:  <nil>
  Nodes:
    daemon-nginx-ch8bv:
      Children:
        daemon-nginx-ch8bv-2513675026
      Display Name:  daemon-nginx-ch8bv
      Finished At:   2021-01-27T08:09:47Z
      Id:            daemon-nginx-ch8bv
      Name:          daemon-nginx-ch8bv
      Outbound Nodes:
        daemon-nginx-ch8bv-2782442775
      Phase:     Succeeded
      Progress:  2/2
      Resources Duration:
        Cpu:           1
        Memory:        0
      Started At:      2021-01-27T08:09:27Z
      Template Name:   daemon-nginx-example
      Template Scope:  local/daemon-nginx-ch8bv
      Type:            Steps
    daemon-nginx-ch8bv-2446417455:
      Boundary ID:  daemon-nginx-ch8bv
      Children:
        daemon-nginx-ch8bv-2782442775
      Display Name:  [1]
      Finished At:   2021-01-27T08:09:47Z
      Id:            daemon-nginx-ch8bv-2446417455
      Name:          daemon-nginx-ch8bv[1]
      Phase:         Succeeded
      Progress:      1/1
      Resources Duration:
        Cpu:           1
        Memory:        0
      Started At:      2021-01-27T08:09:37Z
      Template Name:   daemon-nginx-example
      Template Scope:  local/daemon-nginx-ch8bv
      Type:            StepGroup
    daemon-nginx-ch8bv-2513675026:
      Boundary ID:  daemon-nginx-ch8bv
      Children:
        daemon-nginx-ch8bv-3699291052
      Display Name:  [0]
      Finished At:   2021-01-27T08:09:37Z
      Id:            daemon-nginx-ch8bv-2513675026
      Name:          daemon-nginx-ch8bv[0]
      Phase:         Succeeded
      Progress:      2/2
      Resources Duration:
        Cpu:           1
        Memory:        0
      Started At:      2021-01-27T08:09:27Z
      Template Name:   daemon-nginx-example
      Template Scope:  local/daemon-nginx-ch8bv
      Type:            StepGroup
    daemon-nginx-ch8bv-2782442775:
      Boundary ID:   daemon-nginx-ch8bv
      Display Name:  nginx-client
      Finished At:   2021-01-27T08:09:39Z
      Id:            daemon-nginx-ch8bv-2782442775
      Inputs:
        Parameters:
          Name:   server-ip
          Value:  10.244.1.3
      Name:       daemon-nginx-ch8bv[1].nginx-client
      Outputs:
        Artifacts:
          Name:  main-logs
          s3:
            Key:    daemon-nginx-ch8bv/daemon-nginx-ch8bv-2782442775/main.log
        Exit Code:  0
      Phase:        Succeeded
      Progress:     1/1
      Resources Duration:
        Cpu:           1
        Memory:        0
      Started At:      2021-01-27T08:09:37Z
      Template Name:   nginx-client
      Template Scope:  local/daemon-nginx-ch8bv
      Type:            Pod
    daemon-nginx-ch8bv-3699291052:
      Boundary ID:  daemon-nginx-ch8bv
      Children:
        daemon-nginx-ch8bv-2446417455
      Display Name:    nginx-server
      Finished At:     2021-01-27T08:09:37Z
      Host Node Name:  10.177.255.20
      Id:              daemon-nginx-ch8bv-3699291052
      Name:            daemon-nginx-ch8bv[0].nginx-server
      Outputs:
        Artifacts:
          Name:  main-logs
          s3:
            Key:    daemon-nginx-ch8bv/daemon-nginx-ch8bv-3699291052/main.log
        Exit Code:  0
      Phase:        Succeeded
      Pod IP:       10.244.1.3
      Progress:     1/1
      Resources Duration:
        Cpu:           0
        Memory:        0
      Started At:      2021-01-27T08:09:27Z
      Template Name:   nginx-server
      Template Scope:  local/daemon-nginx-ch8bv
      Type:            Pod
  Phase:               Succeeded
  Progress:            2/2
  Resources Duration:
    Cpu:       1
    Memory:    0
  Started At:  2021-01-27T08:09:27Z
Events:
  Type    Reason                 Age   From                 Message
  ----    ------                 ----  ----                 -------
  Normal  WorkflowRunning        21m   workflow-controller  Workflow Running
  Normal  WorkflowNodeSucceeded  21m   workflow-controller  Succeeded node daemon-nginx-ch8bv[0]
  Normal  WorkflowNodeSucceeded  20m   workflow-controller  Succeeded node daemon-nginx-ch8bv[1].nginx-client
  Normal  WorkflowNodeSucceeded  20m   workflow-controller  Succeeded node daemon-nginx-ch8bv[1]
  Normal  WorkflowNodeSucceeded  20m   workflow-controller  Succeeded node daemon-nginx-ch8bv
  Normal  WorkflowSucceeded      20m   workflow-controller  Workflow completed
```

```
# Paste the logs from the workflow controller:
time="2021-01-27T08:09:47.784Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.785Z" level=info msg="Setting node daemon-nginx-ch8bv-2782442775 outputs" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.785Z" level=info msg="Updating node daemon-nginx-ch8bv-2782442775 status Pending -> Succeeded" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.785Z" level=info msg="Processing ready daemon pod: /api/v1/namespaces/argo/pods/daemon-nginx-ch8bv-3699291052" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.785Z" level=info msg="SG Outbound nodes of daemon-nginx-ch8bv-3699291052 are [daemon-nginx-ch8bv-3699291052]" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.786Z" level=info msg="Step group node daemon-nginx-ch8bv-2446417455 successful" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.786Z" level=info msg="node daemon-nginx-ch8bv-2446417455 phase Running -> Succeeded" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.786Z" level=info msg="node daemon-nginx-ch8bv-2446417455 finished: 2021-01-27 08:09:47.786235081 +0000 UTC" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.786Z" level=info msg="Outbound nodes of daemon-nginx-ch8bv-2782442775 is [daemon-nginx-ch8bv-2782442775]" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.786Z" level=info msg="Outbound nodes of daemon-nginx-ch8bv is [daemon-nginx-ch8bv-2782442775]" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.786Z" level=info msg="node daemon-nginx-ch8bv phase Running -> Succeeded" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.786Z" level=info msg="node daemon-nginx-ch8bv finished: 2021-01-27 08:09:47.786301 +0000 UTC" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.786Z" level=info msg="Checking daemoned children of daemon-nginx-ch8bv" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.786Z" level=info msg="Updating execution control of daemon-nginx-ch8bv-3699291052: {\"deadline\":\"0001-01-01T00:00:00Z\"}" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.792Z" level=info msg="Signalling daemon-nginx-ch8bv-3699291052 of updates" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.794Z" level=info msg="https://10.96.0.1:443/api/v1/namespaces/argo/pods/daemon-nginx-ch8bv-3699291052/exec?command=sh&command=-c&command=kill+-s+USR2+%24%28pidof+argoexec%29&container=wait&stderr=true&stdout=true&tty=false"
time="2021-01-27T08:09:47.800Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.800Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.808Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=22664455 workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:47.814Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/daemon-nginx-ch8bv-2782442775/labelPodCompleted
time="2021-01-27T08:09:47.912Z" level=info msg="Signal of daemon-nginx-ch8bv-3699291052 (wait) successfully issued" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:57.801Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:57.802Z" level=info msg="Setting node daemon-nginx-ch8bv-3699291052 daemoned: 0xc000a4d1df -> <nil>" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:57.802Z" level=info msg="Setting node daemon-nginx-ch8bv-3699291052 outputs" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:57.802Z" level=info msg="Updating node daemon-nginx-ch8bv-3699291052 status Running -> Succeeded" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:57.803Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:57.813Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=22664529 workflow=daemon-nginx-ch8bv
time="2021-01-27T08:09:57.819Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/daemon-nginx-ch8bv-3699291052/labelPodCompleted
time="2021-01-27T08:10:07.825Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:10:07.827Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:11:31.671Z" level=info msg="Alloc=15726 TotalAlloc=252842 Sys=72384 NumGC=46 Goroutines=186"
time="2021-01-27T08:16:31.671Z" level=info msg="Alloc=9817 TotalAlloc=263600 Sys=72384 NumGC=49 Goroutines=186"
time="2021-01-27T08:21:31.671Z" level=info msg="Alloc=12957 TotalAlloc=274397 Sys=72384 NumGC=51 Goroutines=186"
time="2021-01-27T08:26:31.670Z" level=info msg="Alloc=10570 TotalAlloc=285056 Sys=72384 NumGC=54 Goroutines=186"
time="2021-01-27T08:26:49.106Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-nginx-fjw2w
time="2021-01-27T08:26:49.106Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-nginx-8hxzd
time="2021-01-27T08:26:49.110Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-nginx-fjw2w
time="2021-01-27T08:26:49.110Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-nginx-8hxzd
time="2021-01-27T08:30:07.827Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-nginx-ch8bv
time="2021-01-27T08:30:07.829Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-nginx-ch8bv
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you please attach the YAML for your workflow? It should use public images so we can run it.

**Comment by njlkj** [comment]
> Can you please attach the YAML for your workflow? It should use public images so we can run it.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: daemon-nginx-
spec:
  entrypoint: daemon-nginx-example

  templates:
  - name: daemon-nginx-example
    steps:
    - - name: nginx-server
        template: nginx-server
    - - name: nginx-client
        template: nginx-client
        arguments:
          parameters:
          - name: server-ip
            value: "{{steps.nginx-server.ip}}"

  - name: nginx-server
    daemon: true
    container:
      image: nginx:1.13
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 2
        timeoutSeconds: 1

  - name: nginx-client
    inputs:
      parameters:
      - name: server-ip
    container:
      image: appropriate/curl:latest
      command: ["/bin/sh", "-c"]
      args: ["echo curl --silent -G http://{{inputs.parameters.server-ip}}:80/ && curl --silent -G http://{{inputs.parameters.server-ip}}:80/"]
```
