### ISSUE TITLE
Stream processing using `mkfifo`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4988]
Can we mount an empty dir on the wait container and the main container, and then have the wait container read from a Kafka topic and write the data to the FIFO as a JSON stream?

https://en.wikipedia.org/wiki/JSON_streaming

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: fifo
spec:
  volumes:
    - name: workspace
      emptyDir: { }
  restartPolicy: Never
  containers:
    - name: source
      image: alpine:latest
      volumeMounts:
        - mountPath: /workspace
          name: workspace
      command:
        - sh
        - -c
        - |
          mkfifo /workspace/pipe
          cat /dev/random > /workspace/pipe
    - name: sink
      image: alpine:latest
      volumeMounts:
        - mountPath: /workspace
          name: workspace
      command:
        - sh
        - -c
        - |
          sleep 2
          cat /workspace/pipe
```

https://github.com/argoproj/argo/issues/2729

**Comment by alexec** [comment]
This is just a sidecar!

**Comment by alexec** [comment]
```yaml
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  generateName: fifo-
spec:
  entrypoint: main
  templates:
    - name: main
      volumes:
        - name: workspace
          emptyDir: { }
      initContainers:
        - name: mkfifo
          image: alpine:latest
          volumeMounts:
            - mountPath: /workspace
              name: workspace
          command:
            - sh
          args:
            - -c
            - mkfifo /workspace/fifo
      sidecars:
        - name: source
          image: alpine:latest
          volumeMounts:
            - mountPath: /workspace
              name: workspace
          command:
            - sh
          args:
            - -c
            - |
              for x in $(seq 1 1000); do
                echo $x > /workspace/fifo
                sleep 1
              done
      container:
        image: alpine:latest
        volumeMounts:
          - mountPath: /workspace
            name: workspace
        command:
          - sh
        args:
          - -c
          - |
            while read l </workspace/fifo; do
              echo $l
            done
```
