### ISSUE TITLE
"token not valid for running mode" after SSO authentication

### ISSUE THREAD

**Issue by Deepa050** [argoproj/argo-workflows#4991]
## Summary 

Argo UI comes back to login page with error `{"code":16,"message":"token not valid for running mode”}` after completing SSO user authentication.

## Diagnostics

argo version:
argo: v2.12.3
  BuildDate: 2021-01-05T00:49:48Z
  GitCommit: 93ee530126cc1fc154ada84d5656ca82d491dc7f
  GitTreeState: clean
  GitTag: v2.12.3
  GoVersion: go1.13
  Compiler: gc
  Platform: darwin/amd64

I have added sso configuration in  the config map "workflow-controller-configmap"
```yaml
sso: |
      issuer: https://cloudsso-test.xxx.com
      clientId:
        name: argo-server-sso
        key: clientID
      clientSecret:
        name: argo-server-sso
        key: clientSecret
      redirectUrl: http://argo-code.xxx.com/workflows/argo
      scopes:
       - groups
       - email
      rbac:
        enabled: false
```
I have added the required secrets for SSO and also starting argo-server  in "--auth-mode sso"

argo-server logs :
```
time="2021-02-02T07:34:01.198Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=GetVersion grpc.service=info.InfoService grpc.start_time="2021-02-02T07:34:01Z" grpc.time_ms=0.34 span.kind=server system=grpc
time="2021-02-02T07:34:01.218Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2021-02-02T07:34:01Z" grpc.time_ms=0.065 span.kind=server system=grpc
```

**Please note we use JWT token for SSO and not JWE.** 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Did you also add —autho-mode=sso?

**Comment by Deepa050** [comment]
Yes I did. Below is the yaml for argo-server.  Application goes through the entire SSO authentication successfully but fails to run after that. Can you also confirm if using JWT token doesnt impact in anyway since argo document says it uses JWE. 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - args:
        - server
        - --namespaced
        - --auth-mode
        - sso
        image: argoproj/argocli:v2.12.3
        name: argo-server
        ports:
        - containerPort: 2746
          name: web
        readinessProbe:
          httpGet:
            path: /
            port: 2746
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: argo-server
```

**Comment by alexec** [comment]
It does not make sense to have groups without RBAC enabled. Groups are only used for RBAC.

```yaml
     scopes:
       - groups
       - email
      rbac:
        enabled: true
```

**Comment by Deepa050** [comment]
I tried this but same issue.

**Comment by simster7** [comment]
Possibly fixed by: https://github.com/argoproj/argo/pull/4735

Please try upgrading

**Comment by Deepa050** [comment]
Upgrded to 2.12.8 but that didnt work 
```
argo: v2.12.8
  BuildDate: 2021-02-08T23:25:36Z
  GitCommit: d19d4eeed3224ea7e854c658d3544663e86cd509
  GitTreeState: clean
  GitTag: v2.12.8
  GoVersion: go1.13
  Compiler: gc
  Platform: darwin/amd64
```

I tried `--auth-mode sso --auth-mode server ` and that's when the SSO login went through. May be because of the bearer token in server mode. But how to make it work solely on `--auth-mode sso`

**Comment by alexec** [comment]
Have you tried private browsing mode yet?

**Comment by Deepa050** [comment]
Yes I have. same issue.

**Comment by arnoldrw** [comment]
Any chance you are using istio with argo? I saw this same behavior when running argo with istio. The fix was to add an annotation for the argo server deployment to exclude the kubernetes api IP range from being handled by istio. EG
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
  annotations:
    traffic.sidecar.istio.io/excludeOutboundIPRanges: yourk8iprange/16
```

The idea for this came from experience with other istio race condition issues outlined in [1282](https://github.com/argoproj/argo-workflows/issues/1282).

If you are using ssl termination this will get you to a separate, consistent error where on a user's first login they will receive an error stating:
```
http: named cookie not present
```

If they refresh, it will go away. 


I believe this is due to how the state cookie is initiated in HandleRedirect [here](https://github.com/argoproj/argo-workflows/blob/893e9c9fe1bfc6cb2b3a97debb531614b2b2432a/server/auth/sso/sso.go#L193). The secure property is based on the original server standup and whether TLS configuration is passed through [here](https://github.com/argoproj/argo-workflows/blob/master/server/apiserver/argoserver.go#L107). If you are running with TLS termination there is a very good chance that you are not running with the --secure flag, and thus you have no TLS configuration. This causes HandleRedirect to specify the cookie as httponly, then when you authenticate in over https that cookie is lost as it was set to httponly. [This line](https://github.com/argoproj/argo-workflows/blob/893e9c9fe1bfc6cb2b3a97debb531614b2b2432a/server/auth/sso/sso.go#L211) then sets the cookie and does so without the secure enforcement like in HandleRedirect, so if the user refreshes the https version of the cookie now exists, allowing them in. 

I believe this latter scenario could be patched by changing HandleRedirect and rather than setting Secure to s.secure, do a check of the redirectURL scheme and set it appropriately eg:
```
func (s *sso) HandleRedirect(w http.ResponseWriter, r *http.Request) {
	redirectUrl := r.URL.Query().Get("redirect")
	state := pkgrand.RandString(10)
         secureScheme := r.URL.Scheme == "https"
	http.SetCookie(w, &http.Cookie{
		Name:     state,
		Value:    redirectUrl,
		Expires:  time.Now().Add(3 * time.Minute),
		HttpOnly: true,
		SameSite: http.SameSiteLaxMode,
		Secure:   secureScheme,
	})
	http.Redirect(w, r, s.config.AuthCodeURL(state), http.StatusFound)
}
```
