### ISSUE TITLE
Artifact repository agnostic key-only artifacts

### ISSUE THREAD

**Issue by Bobgy** [argoproj/argo-workflows#5001]
# Summary

I was looking at the new key-only artifact support: https://github.com/argoproj/argo/pull/4618.
It looks awesome and very useful.

However, it seems to me that there's a missing piece. A workflow may use key-only artifacts like the example:
https://github.com/argoproj/argo/blob/master/examples/key-only-artifact.yaml
```
...
          artifacts:
          - name: file
            path: /mnt/file
            s3:
              key: my-file
...
```

However, the definition is still tied to s3. I think it helps if the definition can be artifact repository agnostic, for example
```
          artifacts:
          - name: file
            path: /mnt/file
            genericKey: my-file
```

# Use Cases

The same workflow definition would be agnostic to choice of artifact repository store, it can be s3, gcs, oss, and maybe hdfs (if path is mapped to key).

Note, I do not have plans to use this feature yet, but it may making key-only artifacts more useful that I can consider in the future.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
