### ISSUE TITLE
exitCode not working with continueOn

### ISSUE THREAD

**Issue by clementlecorre** [argoproj/argo-workflows#5003]
## Summary 

What happened/what you expected to happen?

I see a bug when I use the `continueOn` function and the `exitCode` variable. It stays in the form `{{tasks.task1.exitCode}}` it is never replaced.

## Diagnostics

What Kubernetes provider are you using? 

AWS/EKS: v1.17.12-eks-7684af

What version of Argo Workflows are you running? 

argo-server: v2.12.6

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-demo-
spec:
  entrypoint: workflow-demo
  arguments:
    parameters:
    - name: jobs_list
      value: '[{"id":"1"}]'

  templates:
  - name: workflow-demo
    dag:
      tasks:
      - name: processing
        template: processing
        arguments:
          parameters:
            - name: p1
              value: "{{workflow.parameters.jobs_list}}"

  - name: processing
    inputs:
      parameters:
      - name: p1
    dag:
      tasks:
      - name: processings
        template: dag-1
        arguments:
          parameters:
            - name: id
              value: "{{item.id}}"
        withParam: "{{inputs.parameters.p1}}"

  - name: dag-1
    inputs:
      parameters:
      - name: id
    dag:
      tasks:
      - name: task1
        template: fail
        continueOn:
          failed: true

      - name: failed-task1
        template: echo-exitCode-exit1
        arguments:
          parameters:
            - name: exitCode
              value: "{{tasks.task1.exitCode}}"
        dependencies: [task1]
        when: "{{tasks.task1.status}} == Failed"

      - name: succeeded-task1
        template: echo-exitCode
        arguments:
          parameters:
            - name: exitCode
              value: "{{tasks.task1.exitCode}}"
        dependencies: [task1]
        when: "{{tasks.task1.status}} == Succeeded"

      - name: end
        dependencies: [succeeded-task1,failed-task1]
        template: ok-bis
        continueOn:
          failed: true
        arguments:
          artifacts:
          - name: a1
            from: "{{tasks.task1.outputs.artifacts.a1}}"

  - name: ok-bis
    container:
      image: alpine:3.7
      command:
        - sh
        - -c
        - exit 0
    inputs:
      artifacts:
      - name: a1
        path: /etc/hostname

  - name: fail
    retryStrategy:
      limit: 1
      retryPolicy: "Always"
    container:
      image: alpine:3.7
      command:
        - sh
        - -c
        - exit 1
    outputs:
      artifacts:
      - name: a1
        path: /etc/hostname_____

  - name: echo-exitCode
    inputs:
      parameters:
      - name: exitCode
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"Exit code was: {{inputs.parameters.exitCode}}\""]

  - name: echo-exitCode-exit1
    inputs:
      parameters:
      - name: exitCode
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"Exit code was: {{inputs.parameters.exitCode}}\"; exit 1"]
```

I see in my job failed-task1:

`Exit code was: {{tasks.task1.exitCode}}`

the value is never replaced....

💡 I did two tests, when an artifact exists and when it does not. I think that when it doesn't exist the exit code is not updated?

Thanks,

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
