### ISSUE TITLE
argo server --kubeconfig not work when behind nginx reverse proxy

### ISSUE THREAD

**Issue by lixiv** [argoproj/argo-workflows#5016]
## Summary 

run argo server use kubeconfig:
```yaml
spec:
  containers:
  - args:
    - server
    - --namespaced
    - --kubeconfig
    - /root/.kube/argo-server.kubeconfig
    image: argoproj/argocli:v2.12.5
```

I can access argo ui directly by http://xxx:2476, everything is normal.  
But when I put argo server behind a nginx reverse proxy and access from nginx, argo server try access apiserver using the serviceaccount instead of the specified kubeconfig, errors occured.
After I add authentication header in nginx conf,  access problems solved.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
