### ISSUE TITLE
Cronworkflows create workflows in "Pending" state

### ISSUE THREAD

**Issue by jelther** [argoproj/argo-workflows#5050]
This is a very hard scenario to reproduce:

I have several Cronworkflows with `concurrencyPolicy` as `Forbid` and now and then I see that my workflows are stuck in a `Pending`  state without any log from `workflow-controller`.

The problem solves itself when I restart the workflow-controller but since they are critical, this is not a solution.

All CronWorkflow configurations are similar to this:
```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: myworkflow
  namespace : mynamespace
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  workflowSpec:
    entrypoint: run-extraction
    templates:
      - name: run-extraction
        retryStrategy:
          limit: 50
          retryPolicy: "Always"
        activeDeadlineSeconds: 1800
        container:
          name: 'myworkflow'
          image: 'myimage'
          args:
            - '--myparameter=xxxx'
          env:
            - name: my_variable
              valueFrom:
                secretKeyRef:
                  name: var1
                  key: var2
          imagePullPolicy: IfNotPresent
```

What I expect is a resilient recover when the `workflow-controller` is not able to schedule any Workflow.

The argo version is `argoproj/workflow-controller:v2.12.6`.

Has anyone had this kind of issue ?

Thanks!
