### ISSUE TITLE
v3.0.0-rc1: ui does not display fail hosts

### ISSUE THREAD

**Issue by goock** [argoproj/argo-workflows#5054]
## Summary 

The retry node stopped displaying `FAIL HOSTS` in UI.

![image](https://user-images.githubusercontent.com/10375055/107385667-63451100-6af3-11eb-9846-7e1694029aec.png)

I'm the author of the PR that introduces the change `feat(controller): Add retry on different host` https://github.com/argoproj/argo/pull/4679
I will submit PR to fix this.

## Diagnostics

What Kubernetes provider are you using? 
We use our own infrastructure.

What version of Argo Workflows are you running? 
`v3.0.0-rc1`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: random-fail-
spec:
  entrypoint: random
  templates:
  - name: random
    retryStrategy:
      limit: 10
      retryPolicy: "Always"  
      affinity:
        nodeAntiAffinity: {}
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        import time
        random.seed(time.time())        
        i = random.randint(0, 6)
        print(i)
        exit(i)
```

The controller's log does not show anything related.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
> I will submit PR to fix this.

Thank you, assigned

**Comment by goock** [comment]
We use a special yaml manifest, separate definitions for cluster and for namespaces.
I debugged and tracked down that we had an invalid configmap definition and cache was not created properly.
The configmap must be exactly what we have in 3.0.0.
We can close this issue.

**Comment by goock** [comment]
**Update**

The following workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: random-fail-
spec:
  entrypoint: random
  templates:
  - name: random
    retryStrategy:
      limit: 10
      retryPolicy: "Always"
      affinity:
        nodeAntiAffinity: {}
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        import time
        random.seed(time.time())
        i = random.randint(0, 10)
        print(i)
        exit(i)
```
could run too briefly to be notified from a `SharedInformer` about changes in cache/store as a result `HOST NODE NAME` is missing sometimes. This happens especially in good infrastructures but it never happens in my local development env.
When hostname is missing `objs` becomes `nil` here
https://github.com/argoproj/argo-workflows/blob/8a8759f38c5773cebecf3dd5fca1ec3b5095ef27/workflow/controller/operator.go#L1084

To solve the issue pod needs to run a little bit longer, adding something simple like `time.sleep(10)` solves the issue.

@simster7 Is there anything we can do about in Argo workflow or this is rather a go client's feature that does not guarantee to deliver all events.
