### ISSUE TITLE
Support regex validation of input parameters

### ISSUE THREAD

**Issue by mac9416** [argoproj/argo-workflows#5061]
# Summary

(I feel like I've mentioned this in another issue, but I can't find it.)

Argo should accept a `pattern` attribute for parameters to perform regex validation. If the parameter value doesn't match the regex, the workflow should fail.

Example syntax:

```yaml
spec:
  entrypoint: print-message
  arguments:
    parameters:
      - name: message
        pattern: "^[a-zA-Z0-9]+$"
```

# Use Cases

When an input parameter gets used in a script, regex validation would be helpful to avoid code injection.

Take this WorkflowTemplate for example: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: scripts-bash-
spec:
  entrypoint: print-message
  arguments:
    parameters:
      - name: message
  templates:
    - name: print-message
      inputs:
        parameters:
          - name: message
      script:
        image: debian:9.4
        command: [bash]
        source: |
          echo {{inputs.parameters.message}}
```

If I allow some not-completely-trusted actor to submit workflows (say, someone else in my _thriving_ new message-printing startup), they could craft an input parameter to do something nefarious:

```yaml
argo submit input_validation.yaml -p message="1; cat /etc/hosts" --watch
```

Of course there are countless other ways an input parameter could be used for an injection attack. Adding regex pattern checking would provide a simple front-line defense.

(I'm aware there are work-arounds. I could carefully craft the script to avoid injections breaking out of some code construct; I could add a preliminary step to validate the inputs as environment variables. But none of the work-around would make it as simple/easy as a built-in validation pattern feature.)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
