### ISSUE TITLE
In-memory input/output parameter transformation

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5069]
Users want to transform data without the expensive overhead of starting pods. Today, they might use Python to perform some basic mapping and filtering. They've requested support for Sprig #4585 (which cannot work because the code uses of `fasttemplate` rather than `text/template`).

There's been a suggestion of a new data template, and obviously, a plugin template #5025 could achieve this.

I think we could actually achieve this 1st-class for all template type as part of inputs and outputs:

```yaml
- name: main
   inputs:
     parameters:
       - name: foo
         value: "1"
         transformation: 
           expression: value + "bar
```

I think this is simpler, more flexible, and more powerful.

This cannot work for artifacts, as the controller cannot read artifacts.

**Comment by simster7** [comment]
The main advantage of this proposal is that the transformation code will not require a pod. However, for very large outputs it will lock the operator, which it's not something I'm sure we'd want. Because of this restriction and others -- for example, we wouldn't allow any network calls from the operator -- this implementation could be limited from the start.

Also, from a design perspective, I'm not sure it makes sense to put this in an input parameter. It's like trying to run code in a function signature, e.g.:

```go
func main(foo = strings.Replace(foo, "a", "b") string) {
  fmt.Println(foo)
}
```

I am definitely open to making transformation occur outside of a `data` template, but not sure this is the way. I'd be happy to discuss this more in stand up, though.

**Comment by alexec** [comment]
The limitation is intentional. This could not and should not support anything making a network I would define as complex and which would warrant its own template type and 1st-class support. Did you read #4585?

**Comment by simster7** [comment]
This is going to be done in the `data:` template as discussed. Close?

**Comment by alexec** [comment]
I've created a PoC which might show my thinking better. 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: transformation-
  labels:
    argo-e2e: true
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: foo
            value: "1"
            transformation:
              expression: int(value) + 2
      container:
        image: argoproj/argosay:v2
        args: [echo, "{{inputs.parameters.foo}}", foo]
      outputs:
        parameters:
          - name: foo
            valueFrom:
              path: foo
            transformation:
              expression: int(value) + 3
```

**Comment by alexec** [comment]
![image](https://user-images.githubusercontent.com/1142830/107717317-36763280-6c88-11eb-9ae2-7bd5e913d13b.png)

**Comment by alexec** [comment]
I *think* data template may be able to do this too, I'd like to see an example.

**Comment by simster7** [comment]
Was supposed to demo today, it definitely does do this.

**Comment by simster7** [comment]
I have strong objections to this being done on the `inputs` level as I mentioned above. My "automagical" approach with the `data:` template still does this fully in-memory while providing a safe way to do this from a DSL design perspective.

**Comment by alexec** [comment]
Objections noted. Can you please attach an example of doing this using a data template?

**Comment by simster7** [comment]
Simple, all done in-memory:

```
  - name: collect-artifacts
    inputs:
      parameters:
        - name: processed
    data:
      transformation:
        - map:
            expression: "{{item}} + 1"
```

**Comment by simster7** [comment]
A live example to illustrate. Note first step taking 0 seconds, indicating it was done in-memory

```
$  cat examples/with-artifacts.yaml
# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: process-var
        template: process-var
    - - name: print-artifact
        template: print-message
        arguments:
          parameters:
          - name: file
            value: "{{steps.process-var.outputs.result}}"

  - name: process-var
    inputs:
      parameters:
        - name: test
          value: "[\"foo\"]"
    data:
      transformation:
        - map:
            expression: "{{item}} + \"-bar\""

  - name: print-message
    inputs:
      parameters:
      - name: file
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.file}}"]
$  ./dist/argo submit  examples/with-artifacts.yaml
Name:                artifact-passing-g94b4
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Fri Feb 12 08:37:20 -0800 (now)
Progress:
$  ./dist/argo get @latest
Name:                artifact-passing-g94b4
Namespace:           argo
ServiceAccount:      default
Status:              Succeeded
Conditions:
 PodRunning          False
 Completed           True
Created:             Fri Feb 12 08:37:20 -0800 (15 seconds ago)
Started:             Fri Feb 12 08:37:20 -0800 (15 seconds ago)
Finished:            Fri Feb 12 08:37:24 -0800 (11 seconds ago)
Duration:            4 seconds
Progress:            2/2
ResourcesDuration:   2s*(1 cpu),1s*(100Mi memory)

STEP                       TEMPLATE          PODNAME                            DURATION  MESSAGE
 ✔ artifact-passing-g94b4  artifact-example
 ├───✔ process-var         process-var       artifact-passing-g94b4-545014019   0s
 └───✔ print-artifact      print-message     artifact-passing-g94b4-3307859365  2s
$  kubectl logs artifact-passing-g94b4-3307859365 -c main
[foo-bar]
```

**Comment by alexec** [comment]
Nice. It’s a bit longer, but it is not hard and certainly better than what we currently have. I don’t think it is enough to mean this issue is not something we should do, just makes it less needed.

**Comment by alexec** [comment]
The expression syntax you’re using mixes fast template and expr. How can we avoid that?

**Comment by simster7** [comment]
> The expression syntax you’re using mixes fast template and expr. How can we avoid that?

This was done on purpose. `{{item}}` is more Argo-y and I have added it as a convenience. No `fasttemplate` is used in this at all.

This has the same result:
```
    data:
      transformation:
        - map:
            expression: "# + \"-bar\""
```

**Comment by alexec** [comment]
Can we use something less fastemplate and more plain expr? I can see that it make a small set of expressions impossible.

**Comment by simster7** [comment]
> Can we use something less fastemplate and more plain expr? I can see that it make a small set of expressions impossible.

Plain `expr` is fully supported. `{{item}}` is just syntax sugar.

**Comment by alexec** [comment]
I'd remove the syntax sugar then. I don't think it is needed. I'd like us to move away from the `{{` syntax due to various problems it creates (e.g. incompatible with Helm, functionally limited, conflicting.

**Comment by alexec** [comment]
This is really a workaround and can be solved much better by directly addressing our templating language.

**Comment by jomach** [comment]
> A live example to illustrate. Note first step taking 0 seconds, indicating it was done in-memory
> 
> ```
> $  cat examples/with-artifacts.yaml
> # This example demonstrates the ability to pass artifacts
> # from one step to the next.
> apiVersion: argoproj.io/v1alpha1
> kind: Workflow
> metadata:
>   generateName: artifact-passing-
> spec:
>   entrypoint: artifact-example
>   templates:
>   - name: artifact-example
>     steps:
>     - - name: process-var
>         template: process-var
>     - - name: print-artifact
>         template: print-message
>         arguments:
>           parameters:
>           - name: file
>             value: "{{steps.process-var.outputs.result}}"
> 
>   - name: process-var
>     inputs:
>       parameters:
>         - name: test
>           value: "[\"foo\"]"
>     data:
>       transformation:
>         - map:
>             expression: "{{item}} + \"-bar\""
> 
>   - name: print-message
>     inputs:
>       parameters:
>       - name: file
>     container:
>       image: alpine:latest
>       command: [sh, -c]
>       args: ["echo {{inputs.parameters.file}}"]
> 
> 
> $  ./dist/argo submit  examples/with-artifacts.yaml
> Name:                artifact-passing-g94b4
> Namespace:           argo
> ServiceAccount:      default
> Status:              Pending
> Created:             Fri Feb 12 08:37:20 -0800 (now)
> Progress:
> 
> 
> $  ./dist/argo get @latest
> Name:                artifact-passing-g94b4
> Namespace:           argo
> ServiceAccount:      default
> Status:              Succeeded
> Conditions:
>  PodRunning          False
>  Completed           True
> Created:             Fri Feb 12 08:37:20 -0800 (15 seconds ago)
> Started:             Fri Feb 12 08:37:20 -0800 (15 seconds ago)
> Finished:            Fri Feb 12 08:37:24 -0800 (11 seconds ago)
> Duration:            4 seconds
> Progress:            2/2
> ResourcesDuration:   2s*(1 cpu),1s*(100Mi memory)
> 
> STEP                       TEMPLATE          PODNAME                            DURATION  MESSAGE
>  ✔ artifact-passing-g94b4  artifact-example
>  ├───✔ process-var         process-var       artifact-passing-g94b4-545014019   0s
>  └───✔ print-artifact      print-message     artifact-passing-g94b4-3307859365  2s
> 
> 
> $  kubectl logs artifact-passing-g94b4-3307859365 -c main
> [foo-bar]
> ```

Are you sure this works ? I tried it on my cluster with emissary and I get: 

Error (exit code 64): unable to process data template: unable to process data source: no valid source is used for data template
Argo version 3.2.9

**Comment by matanlb** [comment]
Yeah seems like `source.artifactPaths` is required.
What is the new way to do simple input transformations?

**Comment by matanlb** [comment]
I was able to do what I needed with the `=` prefix syntax.
My need was to check a string was a give value so my usage of the input was 
`args: [{{= inputs.parameters.state == "Unknown" }}`]

But I would to apply it to the example discussed in this thread it would like something like this:

```
# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - name: print-artifact
       template: print-message
       arguments:
          parameters:
          - name: file
            value: "[\"foo\"]"

  - name: print-message
    inputs:
      parameters:
      - name: file
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{= inputs.parameters.file + '"-bar"'}}"] # this is the important bit
```
