### ISSUE TITLE
Metrics evaluated before the step is over.

### ISSUE THREAD

**Issue by therealnb** [argoproj/argo-workflows#5134]
## Summary 

What happened/what you expected to happen?

When I have this
```
      metrics:
        prometheus:
          - name: backup_db_table
            help: "Backing up a db table"
            when: "{{status}} == Running"
            labels:
              - key: table
                value: "{{inputs.parameters.table}}"
              - key: status
                value: "{{status}}"
            counter:
              value: "1"
```
I never get any metrics emitted. If I change it to
```
      metrics:
        prometheus:
          - name: backup_db_table
            help: "Backing up a db table"
            # when: "{{status}} == Running"
            labels:
              - key: table
                value: "{{inputs.parameters.table}}"
              - key: status
                value: "{{status}}"
            counter:
              value: "1"
```
The status is always "Running". 

I want to emit metrics with a label = failed or success. This is what the docs seem to say.

I thought the status was meant to be evaluated when the step completes. This looks more like it is running in realtime.

## Diagnostics

What Kubernetes provider are you using? 

minikube version: v1.15.1
commit: 23f40a012abb52eff365ff99a709501a61ac5876

What version of Argo Workflows are you running? 

argo: v2.12.0-rc3
  BuildDate: 2020-11-23T12:28:02Z
  GitCommit: 85cafe6e882f9a49e402c29d14e04ded348b07b2
  GitTreeState: clean
  GitTag: v2.12.0-rc3
  GoVersion: go1.13
  Compiler: gc
  Platform: darwin/amd64

image: argoproj/workflow-controller:v2.12.0-rc2

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 

    namespaced/clickhouse-backup-template/backup-db-table:
      arguments: {}
      container:
        args:
        - -v
        - -f
        - -XPOST
        - http://{{inputs.parameters.ch_server}}:{{inputs.parameters.port}}/backup/create?table={{workflow.parameters.db_name}}.{{inputs.parameters.table}}&name={{inputs.parameters.bkname}}
        image: nigelbrown/chops:1
        name: ""
        resources: {}
      inputs:
        parameters:
        - name: ch_server
        - name: port
        - name: table
        - name: bkname
      metadata: {}
      metrics:
        prometheus:
        - counter:
            value: "1"
          help: Backing up a db table
          labels:
          - key: table
            value: '{{inputs.parameters.table}}'
          - key: status
            value: '{{status}}'
          name: backup_db_table
      name: backup-db-table
      outputs: {}
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

This was way too long. It did not seem to contain any metric info. The rest of the workflow worked well. 

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
