### ISSUE TITLE
Missing support for input git artifacts from on-prem gitlab with SSH auth with user is not named `git`

### ISSUE THREAD

**Issue by chtcvl** [argoproj/argo-workflows#5147]
## Summary 

Using SSH repo url in input artifact git driver - expecting git SSH user to be parsed from git repo url. Instead hardcoded `git` user is passed: [workflow/artifacts/git/git.go#L44](https://github.com/argoproj/argo-workflows/blob/65fb530e291e1586fdcd12ca7dc4245ef3dfa551/workflow/artifacts/git/git.go#L44)

## Diagnostics

What Kubernetes provider are you using? 
k8sapi

What version of Argo Workflows are you running? 
3.0.0-rc2

```yaml
    - name: workload
      inputs:
        artifacts:
        - name: workload-script
          path: /src
          git:
            repo: gitolite@gitlab.example.com:projects/workflows.git
            revision: "tasks/workflow"
            sshPrivateKeySecret:
              name: gitlab-ro-ssh
              key: gitlab-ro-ssh
            insecureIgnoreHostKey: true
```

Workflow status message:
```
exit code 1: Error; ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain; ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

On gitlab host:
```
Feb 19 16:30:10 gitlab.example.com sshd[115757]: Invalid user git from 10.24.0.246 port 51618
Feb 19 16:30:10 gitlab.example.com sshd[115757]: input_userauth_request: invalid user git [preauth]
Feb 19 16:30:10 gitlab.example.com sshd[115761]: Invalid user git from 10.24.0.247 port 52534
Feb 19 16:30:10 gitlab.example.com sshd[115761]: input_userauth_request: invalid user git [preauth]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
