### ISSUE TITLE
Template defaults

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5148]
# Summary

Users sometimes want to set default values for templates. We do this piecemeal today, e.g. by adding a new field under `spec`, but we could do this in a general way, e.g.

```yaml
spec:
  templateDefaults:
    memoization:
      cache: "cache-name-v1"
```

Note that template defaults should be parameterization (e.g. using `fasttemplate`).

# Use Cases

To reduce duplication.

See #5113
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
