### ISSUE TITLE
Historical Backfill: Enhance withSequence(or any other equivalent) to accept Date loop format

### ISSUE THREAD

**Issue by saranyaeu2987** [argoproj/argo-workflows#5164]
# Summary

Enhance `withSequence` (other any other equivalent) to accept Date format

# Use Cases
backfills are usually historical dates. Right now, withSequence only support number loop. 

Example:
```
 withSequence:
       start: "2020-01-01"
       end:  "2021-01-01"
       format: "date loop format"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
