### ISSUE TITLE
Can't use expressions involving {{retries}} in podSpecPatch

### ISSUE THREAD

**Issue by therc** [argoproj/argo-workflows#5219]
## Summary 

I get errors when I try to use `{{retries}}` in podSpecPatch, with and without quotes.
This seems to be a variant of https://github.com/argoproj/argo-workflows/issues/4767
I think I'm supposed to quote `{{entries}}`, but that gives me `Error in Unmarshalling after merge the patch`.
Below is the simplest podSpecPatch I could think of. I was really trying something like `"memory": (2 ** {{retries}})+"GB"`. I'm sure there will be other surprises with expressions, but right now I can't figure how to use a plain variable.

Looking at the source, it looks like `retries` is a string. I'm not sure if that's the problem, given that a string is fine the basic case of using the existing variable as is. Maybe it would all magically work if if were an integer, both the variable reference and the arithmetic expression?

## Diagnostics

What Kubernetes provider are you using? 
EKS 1.18

What version of Argo Workflows are you running? 
2.10.2

I made slight tweaks to one of the examples:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-with-steps-
  generation: 3
  labels:
    user: foo
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Failed
    manager: workflow-controller
    operation: Update
    time: "2021-02-25T22:22:28Z"
  name: retry-with-steps-cdvvg
  namespace: argo
spec:
  arguments: {}
  entrypoint: retry-with-steps
  # serviceAccountName: argo
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: retry-with-steps
    outputs: {}
    steps:
    - - arguments: {}
        name: hello1
        template: random-fail
    - - arguments: {}
        name: hello2a
        template: random-fail
      - arguments: {}
        name: hello2b
        template: random-fail
  - arguments: {}
    container:
      args:
      - 'import random; import sys; print(''retries: {{retries}}''); exit_code = random.choice([0,
        0, 1, 1, 1]); sys.exit(exit_code)'
      command:
      - python
      - -c
      image: python:alpine3.6
      name: ""
      resources: {}
    inputs:
      parameters:
      - name: ret
        value: '{{retries}}'
    metadata:
      labels:
        user: foo
    name: random-fail
    outputs: {}
    podSpecPatch: '{"containers":[{"name":"main", "resources":{"requests":{"cpu":
      {{retries}} }}}]}'
    retryStrategy:
      limit: 10
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2021-02-25T22:22:28Z"
  message: child 'retry-with-steps-cdvvg[0].hello1' errored
  nodes:
    retry-with-steps-cdvvg:
      children:
      - retry-with-steps-cdvvg-3565907139
      displayName: retry-with-steps-cdvvg
      finishedAt: "2021-02-25T22:22:28Z"
      id: retry-with-steps-cdvvg
      message: child 'retry-with-steps-cdvvg[0].hello1' errored
      name: retry-with-steps-cdvvg
      outboundNodes:
      - retry-with-steps-cdvvg-872421055
      phase: Failed
      startedAt: "2021-02-25T22:22:27Z"
      templateName: retry-with-steps
      templateScope: local/retry-with-steps-cdvvg
      type: Steps
    retry-with-steps-cdvvg-872421055:
      boundaryID: retry-with-steps-cdvvg
      displayName: hello1(0)
      finishedAt: "2021-02-25T22:22:28Z"
      hostNodeName: ip-10-1-145-61.ec2.internal
      id: retry-with-steps-cdvvg-872421055
      inputs:
        parameters:
        - name: ret
          value: "0"
      message: Invalid PodSpecPatch String
      name: retry-with-steps-cdvvg[0].hello1(0)
      phase: Error
      startedAt: "2021-02-25T22:22:27Z"
      templateName: random-fail
      templateScope: local/retry-with-steps-cdvvg
      type: Pod
    retry-with-steps-cdvvg-1306962068:
      boundaryID: retry-with-steps-cdvvg
      children:
      - retry-with-steps-cdvvg-872421055
      displayName: hello1
      finishedAt: null
      id: retry-with-steps-cdvvg-1306962068
      inputs:
        parameters:
        - name: ret
          value: '{{retries}}'
      name: retry-with-steps-cdvvg[0].hello1
      phase: Running
      startedAt: "2021-02-25T22:22:27Z"
      templateName: random-fail
      templateScope: local/retry-with-steps-cdvvg
      type: Retry
    retry-with-steps-cdvvg-3565907139:
      boundaryID: retry-with-steps-cdvvg
      children:
      - retry-with-steps-cdvvg-1306962068
      displayName: '[0]'
      finishedAt: "2021-02-25T22:22:28Z"
      id: retry-with-steps-cdvvg-3565907139
      message: child 'retry-with-steps-cdvvg[0].hello1' errored
      name: retry-with-steps-cdvvg[0]
      phase: Error
      startedAt: "2021-02-25T22:22:27Z"
      templateName: retry-with-steps
      templateScope: local/retry-with-steps-cdvvg
      type: StepGroup
  phase: Failed
  startedAt: "2021-02-25T22:22:27Z"
```

The logs from the controller are what you'd expect them to look like.

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
