### ISSUE TITLE
Azure DevOps git fetch fails due to go-git issue

### ISSUE THREAD

**Issue by mmckane** [argoproj/argo-workflows#5235]
## Summary 

Trying to use Azure DevOps artifact clone for git over SSH and it fails.

example git input artifact block:
```
      artifacts:
      - name: k8s-mgmt
        path: /src
        git:
          repo: git@ssh.dev.azure.com:v3/REDACTED/k8s-applications
          revision: "master"
          sshPrivateKeySecret:
            name: ado-ssh
            key: id_rsa
          depth: 3
```

This appears to be related to argoproj/argo-cd#1067 and  go-git/go-git#64

Can something like argoproj/argo-cd#1071 be implemented for argo workflows.

What version of Argo Workflows are you running? 
2.9.1

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-cookiecutter
  namespace: argo
spec:
  templates:
  - name: deploy-application
    inputs:
      parameters:
      - name: repo_url
      - name: repo_path
      - name: app_env
      - name: cluster_env
      - name: revision
      - name: branch
      - name: helm
      artifacts:
      - name: k8s-mgmt
        path: /src
        git:
          repo: git@ssh.dev.azure.com:v3/REDACTED/k8s-applications
          revision: "master"
          sshPrivateKeySecret:
            name: ado-ssh
            key: id_rsa
          depth: 3
    script:
      command: ["python3"]
      image: REDACTED
      source: REDACTED
      volumeMounts:
      - mountPath: /src
        name: workdir
    outputs:
      parameters:
      - name: argocd_endpoints
        valueFrom:
          path: /src/ARGOCD_ENDPOINTS
      - name: argocd_app_name
        valueFrom:
          path: /src/ARGOCD_APP_NAME
      - name: argocd_app_init_name
        valueFrom:
          path: /src/ARGOCD_APP_INIT_NAME
      - name: argocd_team_name
        valueFrom:
          path: /src/ARGOCD_TEAM_NAME

```

Error from Init pod workflow doesn't even seem to start:
```
empty git-upload-pack given
github.com/argoproj/argo/errors.Wrap
	/go/src/github.com/argoproj/argo/errors/errors.go:88
github.com/argoproj/argo/errors.InternalWrapError
	/go/src/github.com/argoproj/argo/errors/errors.go:71
github.com/argoproj/argo/workflow/artifacts/git.gitClone
	/go/src/github.com/argoproj/argo/workflow/artifacts/git/git.go:96
github.com/argoproj/argo/workflow/artifacts/git.(*GitArtifactDriver).Load
	/go/src/github.com/argoproj/argo/workflow/artifacts/git/git.go:42
github.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).LoadArtifacts
	/go/src/github.com/argoproj/argo/workflow/executor/executor.go:165
github.com/argoproj/argo/cmd/argoexec/commands.loadArtifacts
	/go/src/github.com/argoproj/argo/cmd/argoexec/commands/init.go:34
github.com/argoproj/argo/cmd/argoexec/commands.NewInitCommand.func1
	/go/src/github.com/argoproj/argo/cmd/argoexec/commands/init.go:14
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:766
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:852
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:800
main.main
	/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
