### ISSUE TITLE
Workflow Logs format annotation

### ISSUE THREAD

**Issue by krrrr38** [argoproj/argo-workflows#5238]
# Summary

When adding `workflows.argoproj.io/logs-format` annotation, server returns formatted workflow logs.

# Use Cases

We sometimes output json logs from pods, because it is useful for fluentd, datadog logs and so on.
But when using json logs, it is difficult to read on the argo-workflows ui. So format log using annotation metadata.

# Proposal

Propose `workflows.argoproj.io/logs-format` annotation which contains logs format metadata.

- `format string`: log format which contains field parameter
- `extractor.type string`: log extraction type, currently support only `jsonpath`
- `extractor.fields map[string]struct{path string, required bool}`: log field extractor to fillin format parameters
- `ignoreExtractError bool`: Sometimes pod output not-json logs which we don't expect, at that time we don't need warn/error logs. So add `ignoreExtractError bool` which change `log.warn` or `log.debug` when parameter extraction error raised.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    workflows.argoproj.io/logs-format: |
      {
        "format": "[{{level}}] {{message}} {{stacktrace}}",
        "extractor": {
          "type": "jsonpath",
          "fields": {
            "level": { "path": "$.level", "required": true },
            "message":  { "path": "$.message", "required": true },
            "stacktrace":  { "path": "$.stacktrace", "required": false },
          }
        },
        "ignoreExtractError": true
      }
```

If exist above annotation, raw logs convert from

```jsonl
{"level": "INFO", "message": "blah1", "unknown": "field"}
{"level": "INFO", "message": "blah2", "stacktrace": "stacktracestacktrace"}
{"message": "no required level field", "raw": "json"}
not json line
```

to

```
[INFO] blah1
[INFO] blah2 stacktracestacktrace
{"message": "no required level field", "raw": "json"}
not json line
```

We might change the following log `content` using annotation.

https://github.com/argoproj/argo-workflows/blob/af5abc8e1b93d041e1d89d796a7912e99704e5fa/util/logs/workflow-logger.go#L118

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
