### ISSUE TITLE
templates.whalesay.steps[0].call-whalesay-template template reference

### ISSUE THREAD

**Issue by anankun** [argoproj/argo-workflows#5244]
## Summary 
I got a `template not found` error

What happened/what you expected to happen?
1、I created a WorkflowTemplate named 'workflow-template-submittable';
2、Then  I create Workflow ref template;
3、But I got en error such as 
      Internal Server Error: templates.whalesay.steps[0].call-whalesay-template template reference workflow-template-submittable.whalesay-template not found:

## Diagnostics

What Kubernetes provider are you using? 
k8s：v1.18.5

What version of Argo Workflows are you running? 
v2.12.3

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:                              # You should only reference external "templates" in a "steps" or "dag" "template".
      - - name: call-whalesay-template
          templateRef:                  # You can reference a "template" from another "WorkflowTemplate" using this field
            name: workflow-template-submittable   # This is the name of the "WorkflowTemplate" CRD that contains the "template" you want
            template: whalesay-template # This is the name of the "template" you want to reference
          arguments:                    # You can pass in arguments as normal
            parameters:
            - name: message
              value: "hello world hhh"
```

![图片](https://user-images.githubusercontent.com/13867253/109480792-f18b3200-7ab6-11eb-9377-c4e6b7870b68.png)
