### ISSUE TITLE
container set next steps: container replicas

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5282]
Currently, you must specify the exact container names. What if you could have replicas of the same process? Would that be useful?

```yaml
containers:
- name: main
  replicas: 2
```

This creates containers named `main-0` and `main-1`.

See #2551
