### ISSUE TITLE
Is there a way to get the PVC  name created by Workflow like "{{inputs.parameters.xxxx}} ”

### ISSUE THREAD

**Issue by codeflitting** [argoproj/argo-workflows#5290]
# Summary

I using  ResourceTemplate in the Template to create my custom job, and want to mount the pvc created by workflow volumeClaimTemplates

Is there any way to configure my ResourceTemplate like "{{inputs.parameters.xxxx”}} ?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
You want access to the PVCs name in your template? Do you know this already.

**Comment by codeflitting** [comment]
```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: tfjob-ps-worker

spec:
  templates:
    - name: tfjob-ps-worker
      inputs:
        parameters:
          - name: volumeClaimName
          - name: psNumber
          - name: workerNumber

      resource:
        action: create
        successCondition: statuus
        failureCondition:
        manifest: |
          apiVersion: "kubeflow.org/v1"
          kind: "TFJob"
          metadata:
            generateName: tfjob-
          spec:
            tfReplicaSpecs:
              PS:
                replicas: "{{inputs.parameters.psNumber}}"
                restartPolicy: Never
                template:
                  spec:
                    containers:
                      - name: tensorflow
                        image: kubeflow/tf-dist-mnist-test:1.0
                        volumeMounts:
                          - name: "{{inputs.parameters.volumeClaimName}}"
                            mountPath: "/input/"
                            subPath: "input/"
                          - name: "{{inputs.parameters.volumeClaimName}}"
                            mountPath: "/output/"
                            subPath: "output/"
                          - name: "{{inputs.parameters.volumeClaimName}}"
                            mountPath: "/code/"
                            subPath: "code/"
              Worker:
                replicas: "{{inputs.parameters.workerNumber}}"
                restartPolicy: Never
                template:
                  spec:
                    containers:
                      - name: tensorflow
                        image: kubeflow/tf-dist-mnist-test:1.0
                        volumeMounts:
                          - name: "{{inputs.parameters.volumeClaimName}}"
                            mountPath: "/input/"
                            subPath: "input/"
                          - name: "{{inputs.parameters.volumeClaimName}}"
                            mountPath: "/output/"
                            subPath: "output/"
                          - name: "{{inputs.parameters.volumeClaimName}}"
                            mountPath: "/code/"
                            subPath: "code/"
```

How can i pass volumeClaimName created by workflow's volumeClaimTemplates  to this template?
