### ISSUE TITLE
retryStrategy limit execute more than specified

### ISSUE THREAD

**Issue by everton-nasc** [argoproj/argo-workflows#5341]
## Summary 

Setting the `retry policy limit` integer, the algorithm is being identifying the limit integer as an array instead a plane integer.

## Diagnostics
**Scenario 1**
Retry policy limit = 2
Retry on = `Always`
**Expected**: Flankey test has executed 2 times
**Measured**: Flankey test has executed 3 times
<img width="1264" alt="Screen Shot 2021-03-09 at 9 15 28 AM" src="https://user-images.githubusercontent.com/58737540/110495265-f86b0380-80b9-11eb-99b2-8eb4ba3f2961.png">

**Scenario 2**
Retry policy limit = 1
Retry on = `Always`
**Expected**: Flankey test has executed 1 times
**Measured**: Flankey test has executed 2 times
<img width="1344" alt="Screen Shot 2021-03-09 at 9 15 12 AM" src="https://user-images.githubusercontent.com/58737540/110495289-fdc84e00-80b9-11eb-9291-cf0f4315bee0.png">

What Kubernetes provider are you using? 
* minikube version: v1.17.1
* Kubernetes v1.20.2 
* Docker 20.10.2

What version of Argo Workflows are you running? 
2.12.9
3.0.0-rc1/rc2/rc3/rc4

```yaml
# For complete documentation please see:
#
#   docs/metrics.md
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: steps
  metrics:
    prometheus:
      - name: duration_gauge
        labels:
          - key: name
            value: workflow
        help: "Duration gauge by name"
        gauge:
          realtime: true                  # This metric will be emitted in real time. For more info see: docs/metrics.md
          value: "{{workflow.duration}}"  # Use {{workflow.duration}} in workflow-level and {{duration}} in template-level

  templates:
    - name: steps
      metrics:
        prometheus:
          - name: duration_gauge
            labels:
              - key: name
                value: steps
            help: "Duration gauge by name"
            gauge:
              realtime: true
              value: "{{duration}}"       # Use {{duration}} in template-level and {{workflow.duration}} in workflow-level
      steps:
        - - name: random-int
            template: random-int
        - - name: flakey
            template: flakey

    - name: random-int
      metrics:
        prometheus:
          - name: random_int_step_histogram
            help: "Value of the int emitted by random-int at step level"
            when: "{{status}} == Succeeded"    # Only emit metric when step succeeds
            histogram:
              buckets:
                - 2.01
                - 4.01
                - 6.01
                - 8.01
                - 10.01
              value: "{{outputs.parameters.rand-int-value}}"
          - name: duration_gauge
            labels:
              - key: name
                value: random-int
            help: "Duration gauge by name"
            gauge:
              realtime: true
              value: "{{duration}}"
      outputs:
        parameters:
          - name: rand-int-value
            globalName: rand-int-value
            valueFrom:
              path: /tmp/rand_int.txt
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["RAND_INT=$((1 + RANDOM % 10)); echo $RAND_INT; echo $RAND_INT > /tmp/rand_int.txt"]

    - name: flakey
      retryStrategy:
        limit: "2"
        retryPolicy: "Always"
      metrics:
        prometheus:
          - name: result_counter
            help: "Count of step execution by result status"
            labels:
              - key: name
                value: flakey
              - key: status
                value: "{{status}}"
            counter:
              value: "1"
      container:
        image: python:alpine3.6
        command: ["python", -c]
        # fail with a 66% probability
        args: ["import random; import sys; exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)"]
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
