### ISSUE TITLE
UI [v3.0.0-rc*]: infinite logs loading after pod is garbage collected

### ISSUE THREAD

**Issue by jacek-jablonski** [argoproj/argo-workflows#5362]
## Summary 

This occurs after workflow is completed (successfully or not) and is still present on `Workflows` list. I go to completed workflow details and click `MAIN LOGS`. Spinner `Waiting for data...` shows and logs are never loaded.

However when Workflow land in `Archived Workflows` I can click `MAIN LOGS` and are visible instantly.

## Diagnostics

What Kubernetes provider are you using?
GKE

What version of Argo Workflows are you running? 
v3.0.0-rc6

Workflow:
```
metadata:
  name: fantastic-rhino
  namespace: default
  labels:
    example: 'true'
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```
time="2021-03-11T10:03:43.232Z" level=info msg="Processing workflow" namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:43.239Z" level=info msg="Updated phase  -> Running" namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:43.239Z" level=info msg="Pod node fantastic-rhino initialized Pending" namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:43.279Z" level=info msg="Created pod: fantastic-rhino (fantastic-rhino)" namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:43.321Z" level=info msg="Workflow update successful" namespace=stat-jobs phase=Running resourceVersion=361311484 workflow=fantastic-rhino
time="2021-03-11T10:03:53.279Z" level=info msg="Processing workflow" namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:53.279Z" level=info msg="Setting node fantastic-rhino outputs" namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:53.279Z" level=info msg="Updating node fantastic-rhino status Pending -> Succeeded" namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:53.279Z" level=info msg="Updated phase Running -> Succeeded" namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:53.279Z" level=info msg="Marking workflow completed" namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:53.279Z" level=info msg="Marking workflow as pending archiving" namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:53.279Z" level=info msg="Checking daemoned children of " namespace=stat-jobs workflow=fantastic-rhino
time="2021-03-11T10:03:53.288Z" level=info msg="Workflow update successful" namespace=stat-jobs phase=Succeeded resourceVersion=361311870 workflow=fantastic-rhino
time="2021-03-11T10:03:53.290Z" level=info msg="archiving workflow" namespace=stat-jobs uid=85376e81-d141-4f77-b7a3-f6ad89cce06f workflow=fantastic-rhino
time="2021-03-11T10:03:53.293Z" level=info msg="cleaning up pod" action=deletePod key=stat-jobs/fantastic-rhino/deletePod
time="2021-03-11T10:03:53.319Z" level=info msg="archiving workflow" namespace=stat-jobs uid=85376e81-d141-4f77-b7a3-f6ad89cce06f workflow=fantastic-rhino
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by philippeboyd** [comment]
I'm having the same issue but not when setting `pdGC`. Linked to #5002 , I get this behaviour on the Daemon pod. When using the yaml provided in #5002 's description, the Daemon pod is still (visually) running but is completed in K8S. The issue of the infinite logs loading happens on that Daemon pod but not the other one.

**Comment by simster7** [comment]
@jacek-jablonski @philippeboyd Sorry for the delay, can you guys confirm if this is a regression? Is this problem present on `v2.12.*`? If not, is it present on all the `v3.0.0-rc*` releases `<6`?

**Comment by philippeboyd** [comment]
@simster7 can confirm the infinite log bug is also present in v2.12.10

Daemon pods are also "visually" running; Pod is completed (`whalesay-w8fws-456624308              0/2     Completed`)

![image](https://user-images.githubusercontent.com/3239656/111197892-60778900-8595-11eb-8b9e-b4207618db12.png)

**Comment by simster7** [comment]
@philippeboyd Thanks! Can you attach that simple workflow you used to reproduce the error? That would help me tremendously

**Comment by philippeboyd** [comment]
@simster7 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: whalesay-
spec:
  entrypoint: whalesay
  podGC:
    strategy: OnPodCompletion
  templates:
  - name: whalesay
    dag:
      tasks:
        - name: redis
          template: redis-tmpl
        - name: whale
          dependencies: [redis]
          template: whale-tmpl
  - name: redis-tmpl
    daemon: true
    container:
      image: redis:alpine
  - name: whale-tmpl
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
```
