### ISSUE TITLE
Allow expresions in metrics value

### ISSUE THREAD

**Issue by Matzz** [argoproj/argo-workflows#5368]
# Summary
I'm using Argo v2.11.7. I think it would be very useful to allow expressions in metrics values:
```
  workflowSpec:
    arguments: {}
    entrypoint: main
    metrics:
      prometheus:
      - gauge:
          value: '{{1+2}}'
        help: Test metric
        name: test_metric1
```
Right now I'm getting:
`✖ MetricsError unable to substitute parameters for metric 'test_metric1': failed to resolve {{1+2}}`
I also tried `value: '{={1+2}}'` but with the same result

# Use Cases
Calculate more sophisticated metrics. For example I wanted to report the current status of last run of cron workflow:
`value: '{{workflow.status == Failed ? 1 : 0}}'` (`when:` is not suitable here because there is no `else` option)
 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
