### ISSUE TITLE
{{retries}} variable in PodSpecPatch not correctly updated

### ISSUE THREAD

**Issue by dinever** [argoproj/argo-workflows#5388]
## Summary 

When using `{{retries}}` inside a PodSpecPatch:

```yaml
podSpecPatch: |
  containers:
    - name: main
      resources:
        limits:
          memory: "{{=(sprig.int(retries) + 1) * 64}}Mi"
```

The variable is not being updated at each retry.

## Diagnostics

What Kubernetes provider are you using? 

Running on local k3d

What version of Argo Workflows are you running? 

Latest master (982e5e9df483e0ce9aa43080683fabadf54e83f2)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-add-memory-
spec:
  entrypoint: retry-add-memory
  templates:
  - name: retry-add-memory
    retryStrategy:
      limit: "5"
      retryPolicy: "Always"
    podSpecPatch: |
      containers:
        - name: main
          resources:
            limits:
              memory: "{{=(sprig.int(retries) + 1) * 64}}Mi"
    container:
      image: python
      command: ["python", "-c"]
      args: ["[i for i in range(10 ** 7)]"]
      resources:
        limits:
          memory: 64Mi
```

In this example, the memory limit will always be 64MB not matter how many times we retry.

The reason is that before executing the template, we replaced the variables at this step:

https://github.com/argoproj/argo-workflows/blob/982e5e9df483e0ce9aa43080683fabadf54e83f2/workflow/controller/operator.go#L1502-L1506

After this point, `{{retries}}` in pod spec patch is replaced by the actual value (0). Later before we retry, `SubstituteParams` won't work for pod spec patch anymore.

https://github.com/argoproj/argo-workflows/blob/982e5e9df483e0ce9aa43080683fabadf54e83f2/workflow/controller/operator.go#L1685-L1688

I'll open a PR soon for my proposed fix for this issue. Thanks!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
