### ISSUE TITLE
Proposal: failureStrategy for DAGs and expandable tempaltes

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5398]
# Summary

Support more advanced strategies for when failing from a DAG or Steps template.

# Use Cases

Currently a DAG has `failFast`, and [recently](https://github.com/argoproj/argo-workflows/issues/3644#issuecomment-799033153) templates also support `failFast` in conjunction with `parallelism` and `with{Items,Prams}`, etc. However, this could be extended further.

Something like:
```yaml
failureStrategy:
  when: "{{numberFailed}} > 2 || {{numberSkipped}} > 0"
  terminateRunningPods: true     # or `false` to allow them to complete
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
