### ISSUE TITLE
Sprig can return default values and no error if no evaluation is possible

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5399]
Not sure if there's anything we can or we should do. This is Sprig's [explicit behavior](https://github.com/Masterminds/sprig/tree/3ac42c7bc5e4be6aa534e036fb19dde4a996da2e#principles-driving-our-function-selection):

```
Template functions should not return errors unless there is no way to print a sensible value. For example, converting a string to an integer should not produce an error if conversion fails. Instead, it should display a default value.
```

So, the user is responsible for knowing this?

Example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello {{=(sprig.int(gdfasdfsadfasdf))}}"]
```

Result:
```
 _________
< hello 0 >
 ---------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

**Comment by alexec** [comment]
This is why I did not include Spig functions at top-level (i.e. `sprig.toInt` rather than `toInt`), so we can provide our own safe versions (pending user 👍 )

**Comment by dinever** [comment]
Looks like `sprig` uses [cast.ToInt](https://github.com/spf13/cast/blob/8d17101741c81653ee960aa20f9febb31f1218aa/cast.go#L65-L69) for type conversion, `err` is omitted.

If we really want to raise the error, we can implement our own type conversion functions by using `cast.ToIntE`. e.g.:

```diff
diff --git a/util/expr/env/env.go b/util/expr/env/env.go
index 99527274..ffa611f8 100644
--- a/util/expr/env/env.go
+++ b/util/expr/env/env.go
@@ -2,8 +2,10 @@ package env

 import (
        "encoding/json"
-
+       "fmt"
        "github.com/Masterminds/sprig"
+       "github.com/spf13/cast"
+
        exprpkg "github.com/argoproj/pkg/expr"
        "github.com/doublerebel/bellows"
 )
@@ -15,9 +17,22 @@ func GetFuncMap(m map[string]interface{}) map[string]interface{} {
        }
        env["toJson"] = toJson
        env["sprig"] = sprig.GenericFuncMap()
+       env["toIntE"] = ToIntE
        return env
 }

+func ToIntE(v interface{}) int {
+       if v == nil {
+               // add an extra check here since cast.ToIntE doesn't return error on nil
+               panic(fmt.Errorf("unable to cast nil to int"))
+       }
+       i, err := cast.ToIntE(v)
+       if err != nil {
+               panic(err)
+       }
+       return i
+}
+
 func toJson(v interface{}) string {
        output, err := json.Marshal(v)
        if err != nil {
```

Workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello {{=(toIntE(gdfasdfsadfasdf))}}"]
```

Output:

```
hello-world-4flcq:  ______________________________________
hello-world-4flcq: < hello {{=(toIntE(gdfasdfsadfasdf))}} >
hello-world-4flcq:  --------------------------------------
hello-world-4flcq:     \
hello-world-4flcq:      \
hello-world-4flcq:       \
hello-world-4flcq:                     ##        .
hello-world-4flcq:               ## ## ##       ==
hello-world-4flcq:            ## ## ## ##      ===
hello-world-4flcq:        /""""""""""""""""___/ ===
hello-world-4flcq:   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
hello-world-4flcq:        \______ o          __/
hello-world-4flcq:         \    \        __/
hello-world-4flcq:           \____\______/
```
