### ISSUE TITLE
Combined output of STDOUT and STDERR in non-Docker executors breaks existing functionality

### ISSUE THREAD

**Issue by raftAtGit** [argoproj/argo-workflows#5408]
# Summary

Kubernetes deprecated Docker, so we need non-Docker executors to run Argo workflows. 

However this breaks existing workflows which depend on conditions based on output of previous steps. 
(i.e. they write `true` or `false` to `stdout`, all the other logs go to `stderr`. This works fine with `Docker` executor but broken with `k8sapi` and `pns` executors)

The suggested workaround mentioned in the [issue 3289](https://github.com/argoproj/argo-workflows/issues/3289), piping `stderr` to `/dev/null` is not an option, since it will make debugging the workflows almost impossible.

I believe you need to preserve same functionality in non-Docker executors. Otherwise, if not technically possible, provide another means of output to be evaluated in conditions.

# Use Cases

All the existing workflows which depend on `stdout` output and assumes `stderr` is ignored.
In our case, an example is [PIVT/peer-org-flow](https://github.com/hyfen-nl/PIVT/tree/master/fabric-kube/peer-org-flow)

# Edit

See the [below comment](https://github.com/argoproj/argo-workflows/issues/5408#issuecomment-816720914) for an effective workaround.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by alexec** [comment]
Can you try with the `emissary` executor? You'll need to run `:latest`. I'm not clear what behaviour it uses. 

@terrytangyuan thoughts on this?

**Comment by terrytangyuan** [comment]
There isn't a way to support non-combined output currently yet as the `GetLogs()` we are using from k8s go client does not expose that as an option (correct me if I am wrong). 

In the meantime, I'd suggest:
1. Trying out `emissary` executor that Alex mentioned above. 
2. `/dev/null` should be the easiest way to get around for now. For debugging purposes you should probably redirect your error logs to a place that can be persisted or ingested via a separate sidecar or logging service.
3. You can also redirect your logs as an artifact and then build your conditional logic based on the content of the artifact.

**Comment by raftAtGit** [comment]
I couldnt make `emissary` executor work. 

For `v3.0.0-rc6`, it executes the step but then fails with below error. Weird it's looking for docker.
```
Error (exit code 1): failed to wait for main container to complete: timed out waiting for the condition: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

For `latest`, installed from below link, workflow controller crashes with below error:
https://raw.githubusercontent.com/argoproj/argo/latest/manifests/install.yaml

```
LEADER_ELECTION_IDENTITY must be set so that the workflow controllers can elect a leader
```
I tried to put an entry `LEADER_ELECTION_IDENTITY` into controller ConfigMap but didnt help.

> You can also redirect your logs as an artifact and then build your conditional logic based on the content of the artifact.

Is there an example using contents of the artifact as condition?

**Comment by terrytangyuan** [comment]
> Is there an example using contents of the artifact as condition?

The relevant doc on artifacts is here: https://github.com/argoproj/argo-workflows/tree/master/examples#artifacts. You should be able to use `{{xxx.xxx}}` expression to obtain the value of the artifact and then use it in your `when` condition.

**Comment by raftAtGit** [comment]
thanks, is there a special syntax for that? below is the slightly modified version of `coinflip` example, but fails when evaluating `when` condition with below error:
```
Invalid 'when' expression '{{steps.flip-coin.outputs.artifacts.result}} == heads': Invalid token: '{{' (hint: try wrapping the affected expression in quotes ("))
```

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: coinflip-
spec:
  entrypoint: coinflip
  volumes:
  - name: work
    emptyDir: {}
  templates:
  - name: coinflip
    steps:
    - - name: flip-coin
        template: flip-coin
    - - name: heads
        template: heads
        when: "{{steps.flip-coin.outputs.artifacts.result}} == heads"
      - name: tails
        template: tails
        when: "{{steps.flip-coin.outputs.artifacts.result}} == tails"

  - name: flip-coin
    outputs:
      artifacts:
      - name: result
        path: /work/result
    script:
      image: alpine:3.6
      command: [sh]
      source: |
        echo "tails" > /work/result
      volumeMounts:
        - name: work
          mountPath: /work

  - name: heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\""]

  - name: tails
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was tails\""]
```

**Comment by terrytangyuan** [comment]
Have you tried what's hinted in the error message? This should work `when: '"{{steps.flip-coin.outputs.artifacts.result}}" == heads'`.

**Comment by raftAtGit** [comment]
yes, I tried. then it interprets `"{{steps.flip-coin.outputs.artifacts.result}}"` as a string literal and both conditions evaluate to false

**Comment by terrytangyuan** [comment]
> yes, I tried. then it interprets `"{{steps.flip-coin.outputs.artifacts.result}}"` as a string literal and both conditions evaluate to false

Perhaps this is worth a separate bug report that can be investigated later. 

Regarding the error `LEADER_ELECTION_IDENTITY must be set so that the workflow controllers can elect a leader`, it looks like https://raw.githubusercontent.com/argoproj/argo/latest/manifests/install.yaml is missing `LEADER_ELECTION_IDENTITY`. You can set it in your controller's env var like this:
```
        command:
        - workflow-controller
        env:
        - name: LEADER_ELECTION_IDENTITY
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
```

**Comment by raftAtGit** [comment]
>> yes, I tried. then it interprets "{{steps.flip-coin.outputs.artifacts.result}}" as a string literal and both conditions evaluate to false

>Perhaps this is worth a separate bug report that can be investigated later.

sure, I can create a separate bug report. 

but are we sure contents of artifacts can be used in conditions? I didn't notice that in the documents yet. and passing artifacts over to other steps and evaluating them is quite different things. to my imagination, the later requires downloading the artifact to the controller (which can be huge) and consuming its contents.

**Comment by raftAtGit** [comment]
One workaround for this issue is, storing the output in an `artifact`, then in an intermediate step printing the contents of the artifact and using output of intermediate step in `when` condition.

Working example:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: coinflip-
spec:
  entrypoint: coinflip
  volumes:
  - name: work
    emptyDir: {}
  templates:
  - name: coinflip
    steps:
    - - name: flip-coin
        template: flip-coin
    - - name: flip-coin-output
        template: print-output
        arguments:
          artifacts:
          - name: result
            from: "{{steps.flip-coin.outputs.artifacts.result}}"
    - - name: heads
        template: heads
        when: "{{steps.flip-coin-output.outputs.result}} == heads"
      - name: tails
        template: tails
        when: "{{steps.flip-coin-output.outputs.result}} == tails"

  - name: flip-coin
    outputs:
      artifacts:
      - name: result
        path: /work/result
    script:
      image: alpine:3.6
      command: [sh]
      source: |
        echo "some logging goes here.."
        echo "tails" > /work/result
      volumeMounts:
        - name: work
          mountPath: /work
  - name: print-output
    inputs:
      artifacts:
      - name: result
        path: /work/result
    script:
      image: alpine:3.6
      command: [sh]
      source: |
        cat /work/result

  - name: heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\""]

  - name: tails
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was tails\""]
```
