### ISSUE TITLE
Output of template artifact persisted via calling WorflowStep

### ISSUE THREAD

**Issue by adamvonpaternos** [argoproj/argo-workflows#5417]
# Summary

Ability to persist WorkflowStep's an artifact output from a step of a template (which has no defined persistence) to an artifact repository.
 
# Use Cases

Consider a template within a WorkflowTemplate of given tool which generates a file but does not persist IO to an artifact store aide from the deployed minio associated with intermediate artifact passing.
Now, consider  a template within a WorkflowTemplate which then calls the aforementioned template as a step with the intention of persisting IO to some specified artifact store. This may be viewed as a logical step of a pipeline where output may be meaningful, but not necessarily the final output of a pipeline.

This currently does not seem possible based on my experience. Is this potentially a feature or intended behavior? This ideally would be nice for abstracting IO from tools/components utilized in pipelines where artifact store would be determined at submission time.
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tool
spec:
  templates:
  - name: command
    container:
      image: someimage
      args:
        - "entrypoint args which generate file to {{outputs.artifacts.file.path}}"
    inputs:
      parameters:
        - name: base_filename
      artifacts:
        - name: input_file
          path: "/mnt/inputs/{{inputs.parameters.base_filename}}.in"
          mode: 0755
    outputs:
      parameters:
      - name: file_one
        value: "{{inputs.parameters.base_filename}}.out"
      artifacts:
      - name: file_one
        path: "/tmp/{{inputs.parameters.base_filename}}.out"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: orchestrator
spec:
  templates:
  - name: call-and-handle
    inputs:
      parameters:
        - name: base_filename
        - name: s3_endpoint
        - name: s3_k8s_secret
        - name: in_s3_bucket
        - name: file_key
        - name: out_s3_bucket
        - name: out_s3_prefix
    steps:
    - - name: call-tool
        templateRef:
          name: tool
          template: command
        arguments:
          parameters:
          - name: base_filename
            value: "{{inputs.parameters.base_filename}}"
          artifacts:
          - name: input_file
            s3:
              endpoint: "{{inputs.parameters.s3_endpoint}}"
              bucket: "{{inputs.parameters.in_s3_bucket}}"
              key: "{{inputs.parameters.file_key}}"
              accessKeySecret:
                name: "{{inputs.parameters.s3_k8s_secret}}"
                key: accessKey
              secretKeySecret:
                name: "{{inputs.parameters.s3_k8s_secret}}"
                key: secretKey
          - name: file_one # ideally this would then upload the output artifact from the called template
            s3:
              endpoint: "{{inputs.parameters.s3_endpoint}}"
              bucket: "{{inputs.parameters.out_s3_bucket}}"
              key: "{{inputs.parameters.out_s3_prefix}}/STEP/file.tool.out"
              accessKeySecret:
                name: "{{inputs.parameters.s3_k8s_secret}}"
                key: accessKey
              secretKeySecret:
                name: "{{inputs.parameters.s3_k8s_secret}}"
                key: secretKey 
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
