### ISSUE TITLE
Passing Arguments (artifacts and Parameters) to Exithandler

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#5452]
# Summary
The current `onExit` template can access only global variables and workflow status.  The current workaround it declare the template level `parameter` to global.
![image](https://user-images.githubusercontent.com/33908564/111665568-19290c80-87d0-11eb-912e-1ebb82232dc9.png)

What change needs making?

# Use Cases
Passing the `step` and `DAG` level parameters and artifact to `Exithandler

```yaml
  onExitTemplate:
    template: whalesay
    arguments:
      parameters:
      - name: message
        valueFrom:
          parameter: "{{steps.step1.outputs.results}}"
```
```yaml
  onExitTemplate:
    template: whalesay
    arguments:
      artifacts:
      - name: message
        valueFrom:
          parameter: "{{steps.heads.outputs.artifacts.result}}"
```

Support:
#4138
#3348

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
