### ISSUE TITLE
Global variable workflow.duration cannot be resolved in exit handler during validation

### ISSUE THREAD

**Issue by mikeczech** [argoproj/argo-workflows#5484]
## Summary 

What happened/what you expected to happen?

We are trying to use the global variable **workflow.duration** from a template that is part of an exit handler, but we are seeing a validation error when creating the workflow template.  If we skip the validation via kubectl, it apparently works.   

I've also created a PR with a potential fix for this issue: https://github.com/argoproj/argo-workflows/pull/5483

## Diagnostics

What version of Argo Workflows are you running? 
v2.12.4

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: exit-handlers-234
spec:
  entrypoint: intentional-fail
  onExit: exit-handler
  templates:
  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]

  - name: exit-handler
    steps:
    - - name: notify
        arguments:
          parameters:
            - name: wfDuration
              value: "{{workflow.duration}}"
        template: send-email
        when: "{{workflow.status}} == Succeeded"

  - name: send-email
    inputs:
      parameters:
        - name: wfDuration
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo send e-mail: {{workflow.name}} {{inputs.parameters.wfDuration}}"]

```

If we attempt to create a workflow template from this YAML file, we get the following error message.
```
argo template create wf.yaml -n argo
ERRO[2021-03-22T18:10:38.424Z] Error in file wf.yaml: templates.exit-handler.steps failed to resolve {{workflow.duration}}
FATA[2021-03-22T18:10:38.424Z] Errors encountered in validation
```

If we skip the validation, it apparently works as expected:
```
kubectl apply -f wf.yaml -n argo
argo submit --from workflowtemplate/exit-handlers-234 -n argo

Name:                exit-handlers-234-mzmwf
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Mon Mar 22 18:18:39 +0100 (now)
Progress:
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
