### ISSUE TITLE
Passing k8s secret to a workflow as input

### ISSUE THREAD

**Issue by RoiSightfull** [argoproj/argo-workflows#5506]
# Summary

I know it is possible to pass a secret to a container via ENV or FILE. but it is not possible to pass it as an argument of a workflow.

# Use Cases

I have a few tools which accept values as command line args. These args are values which I'm not convenient in putting in YAMLs as plaintext and would like to store as k8s secrets.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by alexec** [comment]
Could you propose the syntax? Where would the secrets be? In the user namespace? The controller would need RBAC access. Might not pass security audit for some users.

**Comment by RoiSightfull** [comment]
Thanks for the quick comment!

## Syntax
Regarding the syntax I though something along the lines:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      valueFrom:
         secretKeyRef:
           name: my-secret
           key: mypassword


  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]

```

The valueFrom idea is taken from here: https://argoproj.github.io/argo-workflows/examples/#secrets

## Secrets location
regarding the location of the secrets, I think placing the secret in the user namespace and giving permissions to the controller to this specific secret only will pass most security audits.

using the `resourceNames` https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources

**Comment by alexec** [comment]
That looks good. Would you like to submit a PR?

**Comment by shuheiktgw** [comment]
Hi, may I work on this issue if no one does right now?

**Comment by shadiramadan** [comment]
So for functionality is this basically a clone of #6982 @alexec @terrytangyuan ?

Should we also sanitize the display of such parameters as 'secret' ?

Should you be able to mark a parameter as secret at all?
```
- name: my-pass
  value: {{some-output-val}}
  secret: "true"
```
Which could subsequently not display the raw anywhere?
Same with outputs I guess... or is this overkill?

ArgoCD displays secrets like this:
![image](https://user-images.githubusercontent.com/875944/152257307-c34c2b70-d400-40f0-8ab7-c6618bf53bd8.png)

I'm having an issue right now where I'm using the http template and I have an API key.
Right now it is passed in as a param but it renders in the UI.  The alternative is to make a container running curl and pass it as an env value.... but I felt that was overkill.

**Comment by alexec** [comment]
I think you mean it is a clone of #6662. I think it might be more difficult. I think we store parameters in the workflows status. But, we should not do this with secrets. I might be wrong. Could you investigate?

**Comment by sarabala1979** [comment]
@roitalpaz you can mount the secret on pods. this is a more secure way to access the secret in container

**Comment by panakour** [comment]
any update on this?

**Comment by jamesgoodhouse** [comment]
I'm unsure the reason Argo can't load secrets like this, but I suspect it was an intentional decision to limit Argo from accessing secrets directly. I just load the secret name into my workflows and pass it down to the container that needs it, and have it be "responsible" for getting the value from the secret.

**Comment by jamesgoodhouse** [comment]
why not just pass the secret name in and have the container load the secret? there's no need for argo to load the secret, nor do i think it should.

**Comment by beejiujitsu** [comment]
> why not just pass the secret name in and have the container load the secret? there's no need for argo to load the secret, nor do i think it should.

The HTTP Template is a built-in template that doesn't offer container parameters, so what you're suggesting isn't possible.

https://argoproj.github.io/argo-workflows/http-template/

**Comment by kevinpauli** [comment]
I too am attempting to use http template, and would like to set the authorization header using a value from a secret.

**Comment by beejiujitsu** [comment]
> I too am attempting to use http template, and would like to set the authorization header using a value from a secret.

I wrote this workflow to work-around the httpTemplate secrets limitation.

You're welcome to modify this `WorkFlowTemplate` to suit your needs.

```
---
 apiVersion: argoproj.io/v1alpha1
 kind: WorkflowTemplate
 metadata:
   annotations:
     workflows.argoproj.io/description: 'Forked subgraph: notify Discord'
     workflows.argoproj.io/maintainer: '@beejiujitsu'
     workflows.argoproj.io/version: '>= v3.3.6'
   name: forked-subgraph-notify-discord
 spec:
   activeDeadlineSeconds: 172800
   arguments:
     parameters:
       - name: content_prefix
       - name: forked_subgraph_name
       - name: forked_subgraph_url
   entrypoint: main
   podGC:
     strategy: OnWorkflowSuccess
   podMetadata:
     labels:
       app: forked-subgraph
   templates:
     - container:
         args:
           - $(WEBHOOK_URL)
           - '--include'
           - '--json'
           - '{"content": "{{inputs.parameters.content_prefix}} {{inputs.parameters.forked_subgraph_name}}: {{inputs.parameters.forked_subgraph_url}}"}'
         command:
           - curl
         env:
           - name: WEBHOOK_URL
             valueFrom:
               secretKeyRef:
                 key: forked-subgraph
                 name: discord-webhooks
         image: curlimages/curl:7.84.0
         name: curl
         resources:
           limits:
             memory: 100Mi
           requests:
             memory: 50Mi
         securityContext:
           allowPrivilegeEscalation: false
           runAsGroup: 1000
           runAsUser: 1000
       inputs:
         parameters:
           - name: content_prefix
           - name: forked_subgraph_name
           - name: forked_subgraph_url
       name: main 
```

**Comment by johnlinp** [comment]
Hi, I created a workaround for the secret parameter: a template that extracts secret as a output parameter.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: secret-extractor
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: secretName
          - name: secretKey
      outputs:
        parameters:
          - name: secretValue
            valueFrom:
              path: /tmp/secret-value
      container:
        image: docker-registry.netbase.com/alpine:latest
        command:
          - sh
          - '-c'
        args:
          - echo -n "$SECRET_VALUE" > /tmp/secret-value
        env:
          - name: SECRET_VALUE
            valueFrom:
              secretKeyRef:
                name: "{{inputs.parameters.secretName}}"
                key: "{{inputs.parameters.secretKey}}"
  entrypoint: main
```

One can use it in steps, for example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: demo
spec:
  templates:
    - name: main
      steps:
        - - name: extract-secret
            templateRef:
              name: secret-extractor
              template: main
            arguments:
              parameters:
                - name: secretName
                  value: demo-secret
                - name: secretKey
                  value: password
        - - name: print-msg
            template: msg-printer
            arguments:
              parameters:
                - name: msg
                  value: "{{steps.extract-secret.outputs.parameters.secretValue}}"
    - name: msg-printer
      inputs:
        parameters:
          - name: msg
      container:
        image: docker-registry.netbase.com/alpine:latest
        command:
          - echo
          - "{{inputs.parameters.msg}}"
  entrypoint: main
```

**Comment by Igor992** [comment]
@johnlinp Thanks for this, works perfectly! 👍🏼

**Comment by Sajiyah-Salat** [comment]
is this issue still persists.

**Comment by tooptoop4** [comment]
i have similar issue with resources.requests....getting ```"Failed to parse workflow template: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"``` with:
```
        resources:
          requests:
            memory: "{{inputs.parameters.ram}}Gi"
            cpu: "{{inputs.parameters.cpu}}"
```

**Comment by xmsanchez** [comment]
@beejiujitsu solution works perfectly and is the most efficient and secure suggested solution in this thread IMO.

```
         command:
           - curl
         args:
           - $(WEBHOOK_URL)
           - '--include'
           - '--json'
           - '{"content": "{{inputs.parameters.content_prefix}} {{inputs.parameters.forked_subgraph_name}}: {{inputs.parameters.forked_subgraph_url}}"}'
         env:
           - name: WEBHOOK_URL
             valueFrom:
               secretKeyRef:
                 key: forked-subgraph
                 name: discord-webhooks
```

**Comment by joebowbeer** [comment]
With support for resource `action: get` another workaround is:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: secret-extractor
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: secretNamespace
        value: default
      - name: secretName
      - name: secretKey
    outputs:
      parameters:
      - name: secretValue
        valueFrom:
          jsonPath: '{.data.{{inputs.parameters.secretKey}}}'
    resource:
      action: get
      manifest: |
        apiVersion: v1
        kind: Secret
        metadata:
          name: {{inputs.parameters.secretName}}
          namespace: {{inputs.parameters.secretNamespace}}
```

**Comment by umi0410** [comment]
@terrytangyuan I'm interested in this issue. Could I work on this?

**Comment by terrytangyuan** [comment]
@umi0410 Sure go ahead

**Comment by umi0410** [comment]
@terrytangyuan I wrote a PR for the initial implementation. Could you take a look at it?

**Comment by artemklevtsov** [comment]
> > I too am attempting to use http template, and would like to set the authorization header using a value from a secret.
> 
> I wrote this workflow to work-around the httpTemplate secrets limitation.
> 
> You're welcome to modify this `WorkFlowTemplate` to suit your needs.
> 
> ```
> ---
>  apiVersion: argoproj.io/v1alpha1
>  kind: WorkflowTemplate
>  metadata:
>    annotations:
>      workflows.argoproj.io/description: 'Forked subgraph: notify Discord'
>      workflows.argoproj.io/maintainer: '@beejiujitsu'
>      workflows.argoproj.io/version: '>= v3.3.6'
>    name: forked-subgraph-notify-discord
>  spec:
>    activeDeadlineSeconds: 172800
>    arguments:
>      parameters:
>        - name: content_prefix
>        - name: forked_subgraph_name
>        - name: forked_subgraph_url
>    entrypoint: main
>    podGC:
>      strategy: OnWorkflowSuccess
>    podMetadata:
>      labels:
>        app: forked-subgraph
>    templates:
>      - container:
>          args:
>            - $(WEBHOOK_URL)
>            - '--include'
>            - '--json'
>            - '{"content": "{{inputs.parameters.content_prefix}} {{inputs.parameters.forked_subgraph_name}}: {{inputs.parameters.forked_subgraph_url}}"}'
>          command:
>            - curl
>          env:
>            - name: WEBHOOK_URL
>              valueFrom:
>                secretKeyRef:
>                  key: forked-subgraph
>                  name: discord-webhooks
>          image: curlimages/curl:7.84.0
>          name: curl
>          resources:
>            limits:
>              memory: 100Mi
>            requests:
>              memory: 50Mi
>          securityContext:
>            allowPrivilegeEscalation: false
>            runAsGroup: 1000
>            runAsUser: 1000
>        inputs:
>          parameters:
>            - name: content_prefix
>            - name: forked_subgraph_name
>            - name: forked_subgraph_url
>        name: main 
> ```

But pass env to the args not works for me:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: curl-test-
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: quay.io/curl/curl:latest
        env:
          - name: URL
            value: https://ifconfig.co
        command:
          - curl
        args:
          - ${URL}
```

What am I doing wrong?

**Comment by beejiujitsu** [comment]
> > > I too am attempting to use http template, and would like to set the authorization header using a value from a secret.
> > 
> > 
> > I wrote this workflow to work-around the httpTemplate secrets limitation.
> > You're welcome to modify this `WorkFlowTemplate` to suit your needs.
> > ```
> > ---
> >  apiVersion: argoproj.io/v1alpha1
> >  kind: WorkflowTemplate
> >  metadata:
> >    annotations:
> >      workflows.argoproj.io/description: 'Forked subgraph: notify Discord'
> >      workflows.argoproj.io/maintainer: '@beejiujitsu'
> >      workflows.argoproj.io/version: '>= v3.3.6'
> >    name: forked-subgraph-notify-discord
> >  spec:
> >    activeDeadlineSeconds: 172800
> >    arguments:
> >      parameters:
> >        - name: content_prefix
> >        - name: forked_subgraph_name
> >        - name: forked_subgraph_url
> >    entrypoint: main
> >    podGC:
> >      strategy: OnWorkflowSuccess
> >    podMetadata:
> >      labels:
> >        app: forked-subgraph
> >    templates:
> >      - container:
> >          args:
> >            - $(WEBHOOK_URL)
> >            - '--include'
> >            - '--json'
> >            - '{"content": "{{inputs.parameters.content_prefix}} {{inputs.parameters.forked_subgraph_name}}: {{inputs.parameters.forked_subgraph_url}}"}'
> >          command:
> >            - curl
> >          env:
> >            - name: WEBHOOK_URL
> >              valueFrom:
> >                secretKeyRef:
> >                  key: forked-subgraph
> >                  name: discord-webhooks
> >          image: curlimages/curl:7.84.0
> >          name: curl
> >          resources:
> >            limits:
> >              memory: 100Mi
> >            requests:
> >              memory: 50Mi
> >          securityContext:
> >            allowPrivilegeEscalation: false
> >            runAsGroup: 1000
> >            runAsUser: 1000
> >        inputs:
> >          parameters:
> >            - name: content_prefix
> >            - name: forked_subgraph_name
> >            - name: forked_subgraph_url
> >        name: main 
> > ```
> 
> But pass env to the args not works for me:
> 
> ```yaml
> # yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json
> apiVersion: argoproj.io/v1alpha1
> kind: Workflow
> metadata:
>   generateName: curl-test-
> spec:
>   entrypoint: main
>   templates:
>     - name: main
>       container:
>         image: quay.io/curl/curl:latest
>         env:
>           - name: URL
>             value: https://ifconfig.co
>         command:
>           - curl
>         args:
>           - ${URL}
> ```
> 
> What am I doing wrong?
> 
> Work only with shell:
> 
> ```yaml
>         command:
>           - sh
>         args:
>           - -c
>           - curl -s ${URL}
> ```

You're using curly braces for the arg env var; use parentheses.  See my example again.

**Comment by rossigee** [comment]
Security issues aside, the workarounds so far all depend on containers and shell substitution, so aren't very efficient.

It would be great to be able to pull a secret into an HTTP template without needing an intermediate container step. For example, pull a variable 'discord_url' in and use it as the 'url' for a POST request.

**Comment by jamietanna** [comment]
Looking at https://github.com/argoproj/argo-workflows/issues/5506#issuecomment-1266430170 above, this can leak the secrets into the result of i.e. `kubectl get workflow -n ... demo-mfhxg -o yaml`.

For instance, the following (redacted) output shows that the `hunter2` secret is shown in cleartext:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  ...
spec:
  arguments: {}
  workflowTemplateRef:
    name: demo
status:
  ...
  nodes:
    demo-mfhxg:
      ...
    demo-mfhxg-1656709087:
      ...
      inputs:
        parameters:
        - name: msg
          value: hunter2                                        # <<<<<<<<<<<<
      name: demo-mfhxg[1].print-msg
      ...
    demo-mfhxg-2338360831:
      ...
      name: demo-mfhxg[0].extract-secret
      outputs:
        exitCode: "0"
        parameters:
        - name: secretValue
          value: hunter2                                        # <<<<<<<<<<<<
          valueFrom:
            path: /tmp/secret-value
      ...
    demo-mfhxg-4081967695:
      ...
    demo-mfhxg-4149225266:
      ...
  phase: Succeeded
  progress: 2/2
  resourcesDuration:
    cpu: 8
    memory: 8
  startedAt: "2025-07-17T09:27:03Z"
  storedTemplates:
    namespaced/demo/main:
      ...
      steps:
      - - arguments:
            parameters:
            - name: secretName
              value: ...
            - name: secretKey
              value: ...
          name: extract-secret
          templateRef:
            name: secret-extractor
            template: main
      - - arguments:
            parameters:
            - name: msg
              value: '{{steps.extract-secret.outputs.parameters.secretValue}}'
          name: print-msg
          template: msg-printer
    namespaced/demo/msg-printer:
      container:
        command:
        - echo
        - '{{inputs.parameters.msg}}'
        image: alpine:latest
        name: ""
        resources: {}
      inputs:
        parameters:
        - name: msg
      metadata: {}
      name: msg-printer
      outputs: {}
    namespaced/secret-extractor/main:
      container:
        args:
        - |
          # echo "{{inputs.parameters.secretName}}"
          # echo "{{inputs.parameters.secretKey}}"
          # echo "$SECRET_VALUE"
          echo -n "$SECRET_VALUE" > /tmp/secret-value
          # cat /tmp/secret-value
        command:
        - sh
        - -c
        env:
        - name: SECRET_VALUE
          valueFrom:
            secretKeyRef:
              key: '{{inputs.parameters.secretKey}}'
              name: '{{inputs.parameters.secretName}}'
        image: alpine:latest
        name: ""
        resources: {}
      inputs:
        parameters:
        - name: secretName
        - name: secretKey
      metadata: {}
      name: main
      outputs:
        parameters:
        - name: secretValue
          valueFrom:
            path: /tmp/secret-value
  storedWorkflowTemplateSpec:
    ...
```

Is there a straightforward way to avoid this?
