### ISSUE TITLE
Extend Pod GC to keep them alive during Workflow Lifespan

### ISSUE THREAD

**Issue by manupm87** [argoproj/argo-workflows#5515]
# Summary

Currently pods are automatically garbage collected which translates on logs being lost -unless an artifact repository is configured, and even then logs are difficult to consult-.

It would be good to have an option in `spec.podGC.strategy` like `OnWorkflowDeletion` that would allow the pods to live until then.

# Use Cases
Whenever a workflow needs to be debugged, but the workflow has completed and pods have been garbage collected, so we can avoid setting up an artifact repository.

Artifact repository is not enough since, AFAIK, it's impossible to retrieve logs from Argo CLI after pods have been GC.

It is true that you can check logs stored in the Artifact repo through the Argo Server UI, but there could be cases where developers don't have access to the Argo Server.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Isn’t this the same as not specifying pod GC and not deleting the workflow? Once you are done with debugging you can manually delete the workflow, which will also delete the pods associated with it via owner references.

**Comment by manupm87** [comment]
> Isn’t this the same as not specifying pod GC and not deleting the workflow? Once you are done with debugging you can manually delete the workflow, which will also delete the pods associated with it via owner references.

We currently don't have any pod GC and pods are being deleted automatically (sth like 10 minutes after completion) even though the workflows are kept via `ttlStrategy`

**Comment by terrytangyuan** [comment]
Sounds like an issue with `ttlStrategy` instead. Are you sure you don't have other GC mechanism on workflows in your cluster? Could you share a minimal reproducible example?

**Comment by manupm87** [comment]
I've just spawned a workflow from this template, and after 20 minutes the pod was destroyed.

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-vol
spec:
  serviceAccountName: argo-workflow-runner-dev
  ttlStrategy:
    secondsAfterSuccess: 14400    # Time to live after workflow is successful (4hours)
    secondsAfterFailure: 86400    # Time to live after workflow fails (24 hours)
  entrypoint: hello-world
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  
  templates:
  - name: hello-world
    container:
      image: google/cloud-sdk:latest
      command: 
        - /bin/sh
        - -c 
        - |
          echo "Hello World"
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
      volumeMounts:    
        - name: workdir
          mountPath: /mnt/vol
    
    tolerations:
    - key: "argo-data-plane"
      operator: "Exists"
      effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: argo-data-plane
              operator: In
              values:
              - "true"
```

For reference, this is the content of the Workflow Controller Configmap:

```
apiVersion: v1
data:
  config: |
    containerRuntimeExecutor: k8sapi
    artifactRepository:
      archiveLogs: true
      gcs:
        bucket: argo-workflows-logs
    workflowRestrictions:
      templateReferencing: Secure
kind: ConfigMap
```

I'm starting to think that it has something to do with the Persistent Volume Claim being Terminated. As I've tried exactly same workflow with no PVC and it's still alive.
