### ISSUE TITLE
Executor trying to copy from base image when using trailing slash in `volumeMounts[*].volumePath`

### ISSUE THREAD

**Issue by rccrdpccl** [argoproj/argo-workflows#5520]
## Summary 

Having declared a template with:

```
volumeMounts:
- name: out
  mountPath: /tmp/out/
```

When running it, just before completion we'd run into the error (`executor error: CopyFile() is not implemented in the k8sapi executor.`)

After a bit of digging into the code, I have tried with
```
volumeMounts:
- name: out
  mountPath: /tmp/out
```

And it worked. It turns out that when checking if the artifact is from the base image or a mount dir, eventually this method is called:

https://github.com/argoproj/argo-workflows/blob/d717865716ea399284c6193ceff9970e66bc5f45/workflow/common/util.go#L40

The above linked line adds a trailing slash to the path, therefore ending up with 2 when there is already present.

## Diagnostics

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 
2.12.3

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: output-artifact-bug
spec:
  entrypoint: mytemplate
  serviceAccount: <redacted>
  templates:
  - name: mytemplate
    outputs:
      artifacts:
      - name: test-out-artifact
        path: "/tmp/out/myartifact.tar"
        gcs:
          bucket: <redacted>
          key: "mykey.tar"
          serviceAccountKeySecret:
            name: <redacted>
            key: <redacted>
    volumes:
    - name: out
      emptyDir: {}
    script:
      image: bash:5.1
      command: [bash]
      source: |
        touch /tmp/out/myartifact.tar
      volumeMounts:
      - name: out
        mountPath: /tmp/out/
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

time="2021-03-26T15:08:59.072Z" level=info msg="Processing workflow" namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.073Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.083Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.083Z" level=info msg="Updated message  -> invalid spec: templates.mytemplate.outputs.artifacts.test-out-artifact: k8sapi executor does not support outputs from base image layer.  Use an emptyDir: https://argoproj.github.io/argo/empty-dir/" namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.083Z" level=info msg="Marking workflow completed" namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.083Z" level=info msg="Checking daemoned children of " namespace=argo workflow=output-artifact-bug-dtmcw
time="2021-03-26T15:08:59.092Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=1436328119 workflow=output-artifact-bug-dtmcw

```

Changing the workload to the following (removing trailing slash in the `volumeMounts.mountPath`), will work.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: output-artifact-bug
spec:
  entrypoint: mytemplate
  serviceAccount: <redacted>
  templates:
  - name: mytemplate
    outputs:
      artifacts:
      - name: test-out-artifact
        path: "/tmp/out/myartifact.tar"
        gcs:
          bucket: <redacted>
          key: "mykey.tar"
          serviceAccountKeySecret:
            name: <redacted>
            key: <redacted>
    volumes:
    - name: out
      emptyDir: {}
    script:
      image: bash:5.1
      command: [bash]
      source: |
        touch /tmp/out/myartifact.tar
      volumeMounts:
      - name: out
        mountPath: /tmp/out
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
