### ISSUE TITLE
can't get it to work with AWS ALB

### ISSUE THREAD

**Issue by bgdnlp** [argoproj/argo-workflows#5523]
## Summary 

Trying to set up version 3.0-rc9 on an EKS cluster with ALB Ingress. We can't get it to work no matter what combination of protocols and arguments we tried.

## Diagnostics

What Kubernetes provider are you using? 
AWS EKS

What version of Argo Workflows are you running? 
v3.0.0-rc9

```yaml
 # Connecting to Kubernetes node directly. This is always HTTPS and HTTP1
 » curl -Ik https://172.XX.XX.XXX:30XXX
HTTP/1.1 200 OK

 # Connecting to ALB
 » curl -Ik https://my-argowf.domain/
HTTP/1.1 502 Bad Gateway
Server: awselb/2.0
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
time="2021-03-26T13:56:28.250Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-03-26T13:56:28.261Z" level=info msg="Get configmaps 200"
time="2021-03-26T13:56:28.265Z" level=info msg="Configuration:\nartifactRepository:\n  archiveLogs: true\n  s3:\n    bucket: MY-S3-BUCKET\n    endpoint: s3.amazonaws.com\n    region: eu-west-1\ncontainerRuntimeExecutor: pns\ninitialDelay: 0s\nmetricsConfig: {}\nnodeEvents: {}\npodSpecLogStrategy: {}\ntelemetryConfig: {}\n"
time="2021-03-26T13:56:28.265Z" level=info msg="Persistence configuration disabled"
time="2021-03-26T13:56:28.265Z" level=info msg="Starting Workflow Controller" version=v3.0.0-rc9
time="2021-03-26T13:56:28.265Z" level=info msg="Workers: workflow: 32, pod: 32, pod cleanup: 4"
time="2021-03-26T13:56:28.267Z" level=info msg="Watch configmaps 200"
time="2021-03-26T13:56:28.268Z" level=info msg="List pods 200"
time="2021-03-26T13:56:28.269Z" level=info msg="List workflowtemplates 200"
time="2021-03-26T13:56:28.272Z" level=info msg="List configmaps 200"
time="2021-03-26T13:56:28.284Z" level=info msg="List workflows 200"
time="2021-03-26T13:56:28.311Z" level=info msg="Watch pods 200"
time="2021-03-26T13:56:28.311Z" level=info msg="Watch configmaps 200"
time="2021-03-26T13:56:28.311Z" level=info msg="Watch workflows 200"
time="2021-03-26T13:56:28.311Z" level=info msg="Watch workflowtemplates 200"
time="2021-03-26T13:56:28.374Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2021-03-26T13:56:28.381Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2021-03-26T13:56:28.395Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2021-03-26T13:56:28.397Z" level=info msg="List clusterworkflowtemplates 200"
time="2021-03-26T13:56:28.398Z" level=info msg="Watch clusterworkflowtemplates 200"
time="2021-03-26T13:56:28.400Z" level=info msg="List workflows 200"
time="2021-03-26T13:56:28.411Z" level=info msg="Manager initialized successfully"
I0326 13:56:28.411771       1 leaderelection.go:243] attempting to acquire leader lease  argowf/workflow-controller...
time="2021-03-26T13:56:28.416Z" level=info msg="Get leases 404"
time="2021-03-26T13:56:28.437Z" level=info msg="Create leases 201"
I0326 13:56:28.439602       1 leaderelection.go:253] successfully acquired lease argowf/workflow-controller
time="2021-03-26T13:56:28.441Z" level=info msg="new leader" id=workflow-controller-67689c45cb-tdhcg leader=workflow-controller-67689c45cb-tdhcg
time="2021-03-26T13:56:28.442Z" level=info msg="started leading" id=workflow-controller-67689c45cb-tdhcg
time="2021-03-26T13:56:28.442Z" level=info msg="Performing periodic GC every 5m0s"
time="2021-03-26T13:56:28.443Z" level=info msg="Persistence disabled - so archived workflow GC disabled - you must restart the controller if you enable this"
time="2021-03-26T13:56:28.443Z" level=info msg="Starting workflow TTL controller (workflowTTLWorkers 4)"
time="2021-03-26T13:56:28.443Z" level=info msg="Started workflow TTL worker"
time="2021-03-26T13:56:28.444Z" level=info msg="Starting CronWorkflow controller"
time="2021-03-26T13:56:28.449Z" level=info msg="Starting prometheus metrics server at localhost:9090/metrics"
time="2021-03-26T13:56:28.451Z" level=info msg="List cronworkflows 200"
time="2021-03-26T13:56:28.452Z" level=info msg="Get leases 200"
time="2021-03-26T13:56:28.452Z" level=info msg="Create events 201"
time="2021-03-26T13:56:28.453Z" level=info msg="List workflows 200"
```
---
Here's the relevant K8s manifests, these get applied with kustomize over the official manifest.

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  template:
    spec:
      containers:
        - name: argo-server
          args:
            - server
            - --auth-mode=sso
            # - --argo-http1=true
            # - --namespace=argowf
            # - --secure=false
            # - --verbose
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: root-ca-dev
      volumes:
        - name: root-ca-dev
          secret:
            secretName: trusted-tls-certificate-authorities
            items:
              - key: root-ca-dev
                path: root-ca-dev.crt
                mode: 0644
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argowf-server
  namespace: argowf
  labels:
    app: argowf-server
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8, 172.30.0.0/16
    alb.ingress.kubernetes.io/group.name: ops-apps
    alb.ingress.kubernetes.io/load-balancer-attributes: |
      access_logs.s3.enabled=true,
      access_logs.s3.bucket=MY-LOG-BUCKET,
      access_logs.s3.prefix=elasticloadbalancing
    alb.ingress.kubernetes.io/listen-ports: |
      [
        {"HTTP": 80},
        {"HTTPS":443}
      ]
    alb.ingress.kubernetes.io/actions.tls-redirect: |
      {
        "Type": "redirect",
        "RedirectConfig": {
          "Protocol": "HTTPS",
          "Port": "443",
          "StatusCode": "HTTP_301"
        }
      }
    alb.ingress.kubernetes.io/certificate-arn: 	arn:aws:acm:eu-west-1:123456789012:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
spec:
  rules:
    - host: my-argowf.domain
      http:
        paths:
          - path: /*
            backend:
              serviceName: tls-redirect
              servicePort: use-annotation
          - backend:
              serviceName: argo-server
              servicePort: web      # 2467
```

We can't figure out what we're doing wrong. There's more configuration than needed in the snippets above, but maybe it helps.

We tried telling the ALB to use HTTP2 when talking to the cluster, that obviously didn't work since the cluster answers to HTTP1. Not sure if that's right. Tried gRPC got HTTP code 464 from ALB, no idea what that means.

Tried turning HTTPS off with `--secure=false`, that doesn't seem to work, it's still HTTPS. Tried `--argo-http1`, but it's already HTTP1 either way.

It feels like we're doing something stupid, apologies if this ticket is out of place, but after two days of reading and trying everything we could think of I'm not sure what else to do.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-alb-ingress
  namespace: argo
  annotations:
    kubernetes.io/ingress.class: aws-alb
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=false
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/subnets: XXXX
    alb.ingress.kubernetes.io/security-groups: iXXX
    alb.ingress.kubernetes.io/certificate-arn: XXX
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-XXX
    external-dns.alpha.kubernetes.io/hostname: XXX
  labels:
    app: nginx-service
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: argo-server
              servicePort: 2746
```

This works for us.
