### ISSUE TITLE
Timeout for resource template

### ISSUE THREAD

**Issue by deepk2u** [argoproj/argo-workflows#5549]
# Summary

need a way to be able to timeout the resource operation if it's taking too much time

# Use Cases

We have some custom resources which take a lot of time for many reasons and workflow gets stuck on that step and we want to be able to timeout the step

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by terrytangyuan** [comment]
A solution to this could be setting `ActiveDeadlineSeconds` for the pod/main container in `workflowSpec.PodSpecPatch` and then setting your resource's owner reference to that particular step so that the CR would not continue running forever.

**Comment by Joibel** [comment]
This is supported today - a resource template runs in an ordinary workflow pod, so both timeout fields apply to it.

`activeDeadlineSeconds` kills the pod once it has been running too long:

```yaml
- name: create-cr
  activeDeadlineSeconds: 300
  resource:
    action: create
    successCondition: status.phase == Ready
    manifest: |
      ...
```

`timeout` is enforced by the controller and also counts time the node spends Pending:

```yaml
- name: create-cr
  timeout: 5m
  resource:
    action: create
    successCondition: status.phase == Ready
    manifest: |
      ...
```

`timeout` has been valid on resource templates since v2.12.0 (#3686); the `podSpecPatch` workaround suggested above is no longer needed.

Note that timing out only fails the step and removes the pod - it does not remove the custom resource that was already created. If you want the CR cleaned up too, set `setOwnerReference: true` on the resource template (or delete it from an exit handler), which is the other half of the original suggestion.

Closing as already implemented. Please comment if `timeout` does not behave as described on a supported version and we will reopen.
