### ISSUE TITLE
Passing a string array as an input parameter of a template

### ISSUE THREAD

**Issue by laymain** [argoproj/argo-workflows#5570]
# Summary

It would be nice to be able to define dynamic template parameters using string arrays.

As a workaround I can define multiple templates pointing to the same image, but it would drastically reduce the workflow complexity since all the pod configuration (annotations, labels, nodeSelector, tolerations...) has to be duplicated.

_Feature has already been requested here: https://github.com/argoproj/argo-workflows/issues/3887_

# Use Cases

I have a single container with multiple commands, it would be nice to be able to reuse the same template multiple times with a different amount of parameters, something that could look like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-params-
spec:
  entrypoint: test
  templates:
  - name: test
    steps:
    - - name: first-step
        template: echo-args
        arguments:
          parameters:
          - name: args
            value: ["1", "2", "3"]
    - - name: second-step
        template: echo-args
        arguments:
          parameters:
          - name: args
            value: ["a", "b", "c", "d"]
​  - name: echo-args
    inputs:
      parameters:
      - name: args
    container:
      image: alpine
      command: [echo]
      args: {{inputs.parameters.args}}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by laymain** [comment]
Here is another workaround based on this comment: https://github.com/argoproj/argo-workflows/issues/3191#issuecomment-641630979

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-params-
spec:
  entrypoint: test
  templates:
  - name: test
    steps:
    - - name: first-step
        template: echo-args
        arguments:
          parameters:
          - name: args
            value: '["1", "2", "3"]'
    - - name: second-step
        template: echo-args
        arguments:
          parameters:
          - name: args
            value: '["a", "b", "c", "d"]'
  - name: echo-args
    inputs:
      parameters:
      - name: args
    podSpecPatch: '{"containers":[{"name":"main", "args":{{inputs.parameters.args}}}]}'
    container:
      image: alpine
      command: [echo]
```

Pretty ugly workaround but it does work until we have a more elegant solution ;)

**Comment by simster7** [comment]
I was about to bring that workaround up :)

I agree that a first-class solution would improve UX here. I'll look into it :)

**Comment by pisymbol** [comment]
The echo solution is just gross.

**Comment by laymain** [comment]
By the "echo solution" you mean the podSpecPatch workaround?

**Comment by pisymbol** [comment]
Both. This is one of the most basic things you can do - run a command with command line arguments. Is this really that hard? Also, how would you do this in a WorkflowTemplate instead. That is my use case - I want to define a template to run various commands and allow the workflow to specify the options depending on flow. This seems like a really simply, generic, everyday usecase.

**Comment by laymain** [comment]
The use of `echo` here is just an example.  
I'm successfully using the podSpecPatch workaround just as described in the example in a WorkflowTemplate

**Comment by pisymbol** [comment]
Can you give an example?

**Comment by laymain** [comment]
The example given earlier works fine with a WorkflowTemplate
https://github.com/argoproj/argo-workflows/issues/5570#issuecomment-811908575

**Comment by pisymbol** [comment]
It doesn't for me:

```
 1 apiVersion: argoproj.io/v1alpha1
  2 kind: WorkflowTemplate
  3 metadata:
  4   name: my-cmd-template
  5 spec:
  6   arguments:
  7     parameters:
  8     - name: options
  9       value: []
 10   templates:
 11   - name: my-cmd
 12     inputs:
 13       parameters:
 14       - name: options
 15     container:
 16       image: docker/my-cmd:latest
 17       command: ["my-cmd"]
 18       env:
 19       - name: foo
 20         value: bar
...
 26   podSpecPatch: |
 27     containers:
 28     - name: my-cmd
 29       args: {{inputs.parameters.options}}
```

```
...
  8 spec:
  9   serviceAccountName: argo
 10   entrypoint: main
 11   templates:
 12   - name: main
 13     steps:
 14       - - name: call-my-cmd-template
 15           templateRef:
 16             name: my-cmd-template
 17             template: my-cmd
 18           arguments:
 19             parameters:
 20             - name: options
 21               value: ["a", "b", "c"]
```

**Comment by pisymbol** [comment]
I assume the ```podSpecPatch``` should be in the WirkflowTemplate not in the Workflow?

**Comment by laymain** [comment]
`podSpecPatch` should be a string containing json not yaml, have a look at the example.

Something like this in your case:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-cmd-template
spec:
  templates:
  - name: my-cmd
    inputs:
      parameters:
      - name: options
    container:
      image: docker/my-cmd:latest
      command: ["my-cmd"]
      env:
      - name: foo
        value: bar
    podSpecPatch: '{"containers":[{"name":"main", "args":{{inputs.parameters.options}}}]}'
```

```yaml
...
spec:
  serviceAccountName: argo
  entrypoint: main
  templates:
  - name: main
    steps:
      - - name: call-my-cmd-template
          templateRef:
            name: my-cmd-template
            template: my-cmd
          arguments:
            parameters:
            - name: options
              value: '["a", "b", "c"]'
```
