### ISSUE TITLE
TLS configuration and/or docs enhancement

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-workflows#5582]
# Summary

It looks like after 3.0 release argo server listens on https port with self-signed certificate (#5581 )
I think it would be great to have a dedicated ConfigMap with tls.cert and tls.key parameters which would be mounted inside pod (Like it is implemented in ArgoCD) so it would be very easy to generate a valid certificate with cert-manager or ue any pre-isued one.
At least it would be great to have a parameter or doc which would tell where the cert is read from. It looks like it is harcoded now and it's impossible to mount CM inside pod without even knowing where the self-signed cert is located...

# Use Cases

When deploying a new instance with Ingress it would be great to use ACME from cert-manager

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This sounds like a great idea. Would you like to submit a PR? We could ship it with crt/key in a config map too.

**Comment by max-sixty** [comment]
I _think_ this means that a Google IAP setup no longer works with existing settings. Does anyone have a similar setup and has it working?

(as ever, not meant as a complaint — thank you for the incredible pace of improvements to argo!)

**Comment by hadim** [comment]
Is that possible to disable HTTPS for HTTP? I am currently using 2.10.2 with Google IAP and it works fine but would like to switch to 3.0.1 (currently blocked by https://github.com/argoproj/argo-workflows/issues/5554).

**Comment by hadim** [comment]
The key for me to make 3.0.1 work with Google IAP was to disable the now default secure mode with `--secure=false` (TLS termination is done at the level of the load balancer).

**Comment by Unb9rn** [comment]
I think we need some docs at least. I've tried issuing a cert with cert-manager, mounting it inside pod but still nothing:
Changes I've tried:
```
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /home/argo/argo-server.crt
          name: tls
          readOnly: true
          subPath: argo-server.crt
        - mountPath: /home/argo/argo-server.key
          name: tls
          readOnly: true
          subPath: argo-server.key
      securityContext:
        fsGroup: 8737
        runAsNonRoot: true
      volumes:
      - emptyDir: {}
        name: tmp
      - name: tls
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: argo-server.crt
          - key: tls.key
            path: argo-server.key
          secretName: argo-secret
```
Apiserver still uses the default cert...

**Comment by Unb9rn** [comment]
After running through sources, I've figured out where it tries to load key from.
After creating an ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-server-ingress
  namespace: argo
  labels:
    "use-http01-solver": "true"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: argo.somedomain.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: argo-server
            port:
              name: web
  tls:
  - hosts:
    - argo.somedomain.com
    secretName: argo-secret
```
I was able to mount it inside the pod and run it with ssl passthrough,
after adding something like:
```
        volumeMounts:
        - mountPath: /argo-server.crt
          name: tls
          readOnly: true
          subPath: argo-server.crt
        - mountPath: /argo-server.key
          name: tls
          readOnly: true
          subPath: argo-server.key
      securityContext:
        fsGroup: 8737
      volumes:
      - name: tls
        secret:
          items:
          - key: tls.crt
            path: argo-server.crt
          - key: tls.key
            path: argo-server.key
          secretName: argo-secret
```
I'm not sure wheteher fsgroup is required but I saw it in dockerfile, so why not?

**Comment by alexec** [comment]
@Unb9rn I think your "work-around" is actually the correct solution. Would you like to document it for other users to benefit from?

**Comment by Unb9rn** [comment]
@alexec Yeah, why not, will do =) 
Anyway, I think ArgoCD's soultion looks more "k8s-native" to me, without necessity to edit deployments and manually inject some secrets...

**Comment by alexec** [comment]
I think your workaround is a fine solution. Those are the correct paths for the crt and key. Mounting a secret containing the values will always work. If anyone were to ask me how to do this, I would say do what @Unb9rn did.

**Comment by kmorkans** [comment]
That solution seems at most like a workaround.
I would agree with @Unb9rn that the correct way would be to do it in a standard way by reading a certificate secret by a certain name. That then can be provided by cert-manager or other ways.

**Comment by alexec** [comment]
would anyone would like to submit a PR to add something a bit more to their taste?

**Comment by cyberbliss** [comment]
Additional note for those wanting to use nginx-ingress with the ssl passthrough solution above - you need to explicitly tell nginx to enable ssl passthrough as it is disabled by default (https://kubernetes.github.io/ingress-nginx/user-guide/tls/#ssl-passthrough)

**Comment by opyh** [comment]
@ghost Could you edit your comment so your solution uses `/home/argo/argo-server.key` as mount path, not `/argo-server.key`? This might help others to save some time :)

**Comment by Lunchee85** [comment]
I have tried doing as the now deleted user suggested and specified the .crt and .key in a secret which I then mounted on the pod via a Deployment (I tried both on ```/home/argo/argo-server.key``` and just ```/argo-server.key```), but while using the UI I still get the "Not secure" warning on my browser and see that the used certificate is not mine. 
Argo's version is 3.2.4.

Also, I'm using Openshift 4.7 and my route looks something like this:
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argo-server
spec:
  host:{my-argo-workflows-instance}.com
  port:
    targetPort: web
  tls:
    termination: passthrough
  to:
    kind: Service
    name: argo-server
    weight: 100
  wildcardPolicy: None
```
Does anybody have any idea if this behavior is normal?
