### ISSUE TITLE
Cannot seem to set SSO Expiry

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5598]
## Summary 

I believe I should be able to set an expiry value in my sso config to trigger user logouts after a given time period. However, If I set the `expiry` to `1h`, nothing happens after 1 hour.

```
  sso: |
    issuer: https://example.biz/api/dex
    expiry: 1h
...
```

I also tried `expiry: 1` and `sessionExpiry: 1h` just in case I was reading the code wrong, but in each instance, I do not get logged out after 1 hour.

Each time I set the value I manually killed the server pods so that they re-create themselves with the new config.

## Diagnostics

What Kubernetes provider are you using? EKS 1.19

What version of Argo Workflows are you running? v3.0.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Works for me. I set the expiry time to 10s:

```
       name: argo-server-sso
       key: clientSecret
     redirectUrl: http://localhost:2746/oauth2/callback
+    sessionExpiry: 10s
     scopes:
     - groups
     - email
```

Can you please attach your complete config YAML?
