### ISSUE TITLE
govaluate types mismatch

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-workflows#5644]
## Summary 
I am trying to run a workflow with some conditional steps(I am trying to figure out if a new branch in GitLab was created):
`when: "{{inputs.parameters.sha-before}} != 0000000000000000000000000000000000000000 && {{inputs.parameters.sha-after}} == 0000000000000000000000000000000000000000"`

But this comparison would fail with an error:
`Error node gitlab-workflow-render-gb79x[0]: Invalid 'when' expression '5d1ca167fd6272d60bbf69f49f0a0ca502765081 == '0000000000000000000000000000000000000000' && 5d1ca167fd6272d60bbf69f49f0a0ca502765081 != '0000000000000000000000000000000000000000'': Cannot transition token types from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]`

It looks like govaluate thinks that commit hash is of some numeric type...

## Diagnostics

What Kubernetes provider are you using? 
Yandex Cloud

What version of Argo Workflows are you running? 
3.0.1

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    argo: workflows
  labels:
    env: devdynamic
    events.argoproj.io/action-timestamp: "1617984446200"
    events.argoproj.io/sensor: gitlab-project-render
    events.argoproj.io/trigger: gitlab-workflow-render-trigger
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/controller-instanceid: system-controller
    workflows.argoproj.io/phase: Failed
  name: gitlab-workflow-render-fw6mg
  namespace: argo-events
spec:
  arguments:
    parameters:
    - name: ref
      value: master
    - name: sha-before
      value: 5d1ca167fd6272d60bbf69f49f0a0ca502765081
    - name: sha-after
      value: 5d1ca167fd6272d60bbf69f49f0a0ca502765081
  entrypoint: infra-handler
  templates:
  - inputs:
      parameters:
      - name: sha-before
      - name: sha-after
    metadata: {}
    name: infra-handler
    outputs: {}
    serviceAccountName: argo-events-sa
    steps:
    - - arguments:
          parameters:
          - name: ref
            value: '{{workflow.parameters.ref}}'
        name: create-on-branch-commence
        template: infra-generator
        when: '{{inputs.parameters.sha-before}} == 0000000000000000000000000000000000000000
          && {{inputs.parameters.sha-after}} != 0000000000000000000000000000000000000000'
      - arguments:
          parameters:
          - name: ref
            value: '{{workflow.parameters.ref}}'
        name: destroy-on-branch-abstand
        template: infra-destroyer
        when: '{{inputs.parameters.sha-before}} != 0000000000000000000000000000000000000000
          && {{inputs.parameters.sha-after}} == 0000000000000000000000000000000000000000'
  - container:
      args:
      - echo
      - branch created= {{inputs.parameters.ref}}
      image: argoproj/argosay:v2
      name: ""
      resources: {}
    inputs:
      parameters:
      - name: ref
    metadata: {}
    name: infra-generator
    outputs: {}
    serviceAccountName: argo-events-sa
  - container:
      args:
      - echo
      - branch deleted= {{inputs.parameters.ref}}
      image: argoproj/argosay:v2
      name: ""
      resources: {}
    inputs:
      parameters:
      - name: ref
    metadata: {}
    name: infra-destroyer
    outputs: {}
    serviceAccountName: argo-events-sa
  ttlStrategy:
    secondsAfterSuccess: 5
status:
  artifactRepositoryRef:
    default: true
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2021-04-09T16:11:08Z"
  message: 'Invalid ''when'' expression ''5d1ca167fd6272d60bbf69f49f0a0ca502765081
    == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081
    != 0000000000000000000000000000000000000000'': Cannot transition token types from
    NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]'
  nodes:
    gitlab-workflow-render-ffq9c:
      children:
      - gitlab-workflow-render-ffq9c-4264465097
      displayName: gitlab-workflow-render-ffq9c
      finishedAt: "2021-04-09T16:11:08Z"
      id: gitlab-workflow-render-ffq9c
      inputs:
        parameters:
        - name: sha-before
          value: 5d1ca167fd6272d60bbf69f49f0a0ca502765081
        - name: sha-after
          value: 5d1ca167fd6272d60bbf69f49f0a0ca502765081
      message: 'Invalid ''when'' expression ''5d1ca167fd6272d60bbf69f49f0a0ca502765081
        == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081
        != 0000000000000000000000000000000000000000'': Cannot transition token types
        from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]'
      name: gitlab-workflow-render-ffq9c
      phase: Failed
      startedAt: "2021-04-09T16:11:08Z"
      templateName: infra-handler
      templateScope: local/gitlab-workflow-render-ffq9c
      type: Steps
    gitlab-workflow-render-ffq9c-4264465097:
      boundaryID: gitlab-workflow-render-ffq9c
      displayName: '[0]'
      finishedAt: "2021-04-09T16:11:08Z"
      id: gitlab-workflow-render-ffq9c-4264465097
      message: 'Invalid ''when'' expression ''5d1ca167fd6272d60bbf69f49f0a0ca502765081
        == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081
        != 0000000000000000000000000000000000000000'': Cannot transition token types
        from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]'
      name: gitlab-workflow-render-ffq9c[0]
      phase: Error
      startedAt: "2021-04-09T16:11:08Z"
      templateScope: local/gitlab-workflow-render-ffq9c
      type: StepGroup
  phase: Failed
  progress: 0/0
  startedAt: "2021-04-09T16:11:08Z"

```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

time="2021-04-09T16:11:08.683Z" level=info msg="Processing workflow" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.689Z" level=info msg="Updated phase  -> Running" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="Steps node gitlab-workflow-render-ffq9c initialized Running" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="StepGroup node gitlab-workflow-render-ffq9c-4264465097 initialized Running" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=error msg="Mark error node" error="Invalid 'when' expression '5d1ca167fd6272d60bbf69f49f0a0ca502765081 == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081 != 0000000000000000000000000000000000000000': Cannot transition token types from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]" namespace=argo-events nodeName="gitlab-workflow-render-ffq9c[0]" workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="node gitlab-workflow-render-ffq9c-4264465097 phase Running -> Error" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="node gitlab-workflow-render-ffq9c-4264465097 message: Invalid 'when' expression '5d1ca167fd6272d60bbf69f49f0a0ca502765081 == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081 != 0000000000000000000000000000000000000000': Cannot transition token types from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="node gitlab-workflow-render-ffq9c-4264465097 finished: 2021-04-09 16:11:08.690595529 +0000 UTC" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="step group gitlab-workflow-render-ffq9c-4264465097 was unsuccessful: Invalid 'when' expression '5d1ca167fd6272d60bbf69f49f0a0ca502765081 == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081 != 0000000000000000000000000000000000000000': Cannot transition token types from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="Outbound nodes of gitlab-workflow-render-ffq9c is []" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="node gitlab-workflow-render-ffq9c phase Running -> Failed" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="node gitlab-workflow-render-ffq9c message: Invalid 'when' expression '5d1ca167fd6272d60bbf69f49f0a0ca502765081 == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081 != 0000000000000000000000000000000000000000': Cannot transition token types from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="node gitlab-workflow-render-ffq9c finished: 2021-04-09 16:11:08.690708242 +0000 UTC" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="Checking daemoned children of gitlab-workflow-render-ffq9c" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="Updated phase Running -> Failed" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="Updated message  -> Invalid 'when' expression '5d1ca167fd6272d60bbf69f49f0a0ca502765081 == 0000000000000000000000000000000000000000 && 5d1ca167fd6272d60bbf69f49f0a0ca502765081 != 0000000000000000000000000000000000000000': Cannot transition token types from NUMERIC [5] to VARIABLE [d1ca167fd6272d60bbf69f49f0a0ca502765081]" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="Marking workflow completed" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="Doesn't match with archive label selector. Skipping Archive" namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.690Z" level=info msg="Checking daemoned children of " namespace=argo-events workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:08.715Z" level=info msg="Workflow update successful" namespace=argo-events phase=Failed resourceVersion=16881938 workflow=gitlab-workflow-render-ffq9c
time="2021-04-09T16:11:18.683Z" level=info msg="Workflow processing has been postponed due to max parallelism limit" key=argo-events/gitlab-workflow-render-ffq9c

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
