### ISSUE TITLE
workflowTemplateRef gives missing entrypoint error when used within a WorkflowTemplate 

### ISSUE THREAD

**Issue by jherman3** [argoproj/argo-workflows#5665]
## Summary 

I am trying to reference a WorkflowTemplate from another WorkflowTemplate for the purpose of submitting workflows from the UI while allowing a few different sets of default parameters to be chosen. We have a base workflow and several child workflows which are simply different sets of parameters to the base workflow. Using workflowTemplateRef creates a valid template but submitting the template from the UI or CLI gives `Internal Server Error: template reference <entrypoint name> not found`
I've included what I'm trying to accomplish (`child-template-broken`) as well as two work-arounds, one that's quite verbose and one that uses the deprecated template ref behavior, since this is much easier to explain with code. 

## Diagnostics

What Kubernetes provider are you using? 
Can reproduce on minikube

What version of Argo Workflows are you running? 
2.11.8

## Workflow Templates

```yaml
# Base workflow referenced by other workflow templates
# The goal is to create several different templates that can be used to conveniently instantiate
# this workflow with different default values.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: base-template
  namespace: argo
spec:
  entrypoint: base-main
  arguments:
    parameters:
    - name: base1
      value: NO_DEFAULT # needed to make this show up in the UI, is there a better way?
    - name: base2
      value: NO_DEFAULT
    - name: base3
      value: NO_DEFAULT
  templates:
  - name: base-main
    inputs:
      parameters:
      - name: base1
      - name: base2
      - name: base3
    container:
      image: "docker/whalesay"
      command: [cowsay]
      args:
      - "{{inputs.parameters.base1}}"
      - "{{inputs.parameters.base2}}"
      - "{{inputs.parameters.base3}}"

---
# The field reference suggests that WorkflowTemplateSpec has a workflowTemplateRef field on it, and this workflow template is
# able to be created, but when you submit via the UI or CLI it fails to find the entrypoint.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: child-template-broken
  namespace: argo
spec:
  entrypoint: base-main
  arguments:
    parameters:
    # From UI or CLI, user can just set base3, and can override others if they wish
    - name: base1
      value: default_value_1
    - name: base2
      value: default_value_2
    - name: base3
      value: NO_DEFAULT
  workflowTemplateRef:
    # Internal Server Error: template reference child-template.base-main not found
    name: base-template

---
# Works, but verbose. Requires declaring each arg 3 times and manually forwarding to base workflowtemplate,
# which gets long when you have many parameters.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: child-template-verbose
  namespace: argo
spec:
  arguments:
    parameters:
    - name: base1
      value: default_value_1
    - name: base2
      value: default_value_1
    - name: base3
      value: NO_DEFAULT
  templates:
  - name: child
    inputs:
      parameters:
      - name: base1
      - name: base2
      - name: base3
    steps:
    - - name: invoke-base
        templateRef:
          name: base-template
          template: base-main
        arguments:
          parameters:
          - name: base1
            value: "{{inputs.parameters.base1}}"
          - name: base2
            value: "{{inputs.parameters.base2}}"
          - name: base3
            value: "{{inputs.parameters.base3}}"

---
# Works, but relies on deprecated behavior
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: child-template-hack
  namespace: argo
spec:
  entrypoint: invoke-base
  arguments:
    parameters:
    - name: base1
      value: default_value_1
    - name: base2
      value: default_value_2
    - name: base3
      value: NO_DEFAULT
  templates:
  # Deprecated use of template override
  - name: invoke-base
    templateRef:
      name: base-template
      template: base-main
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
At first glace - I don't think this can be a bug - we'd've seen many reports.

**Comment by jherman3** [comment]
Thanks for looking. Is this type of use not supported? The documentation for [WorkflowSpec](https://argoproj.github.io/argo-workflows/fields/#workflowspec) and [WorkflowTemplateSpec](https://argoproj.github.io/argo-workflows/fields/#workflowtemplatespec) have identical descriptions for `workflowTemplateRef`, which is why I thought they would behave the same way, but it works for Workflow and gives the above error in WorkflowTemplate. 
Is the intended use of this ref in WorkflowTemplate different than in Workflow?

**Comment by alexec** [comment]
@sarabala1979 ?

**Comment by sarabala1979** [comment]
@jherman3 
```yaml
# Base workflow referenced by other workflow templates
# The goal is to create several different templates that can be used to conveniently instantiate
# this workflow with different default values.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: base-template
  namespace: argo
spec:
  entrypoint: base-main
  arguments:
    parameters:
    - name: base1
      value: NO_DEFAULT # needed to make this show up in the UI, is there a better way?
    - name: base2
      value: NO_DEFAULT
    - name: base3
      value: NO_DEFAULT
  templates:
  - name: base-main
    inputs:
      parameters:
      - name: base1
      - name: base2
      - name: base3
    container:
      image: "docker/whalesay"
      command: [cowsay]
      args:
      - "{{inputs.parameters.base1}}"
      - "{{inputs.parameters.base2}}"
      - "{{inputs.parameters.base3}}"

---
# The field reference suggests that WorkflowTemplateSpec has a workflowTemplateRef field on it, and this workflow template is
# able to be created, but when you submit via the UI or CLI it fails to find the entrypoint.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: child-template-broken
  namespace: argo
spec:
  entrypoint: base-main
  arguments:
    parameters:
    # From UI or CLI, user can just set base3, and can override others if they wish
    - name: base1
      value: default_value_1
    - name: base2
      value: default_value_2
    - name: base3
      value: NO_DEFAULT
  workflowTemplateRef:
    # Internal Server Error: template reference child-template.base-main not found
    name: base-template
```
The above example is nested `workflowtemplateRef` which doesn't support.  When CLI or UI submit workflowTemplate, it will create a workflow with `workflowtemplateRef`. In your case that workflowTemplate has one more workflowtemplateRef.
Currently controller doesn;t support the nested `workflowTemplateRef`
