### ISSUE TITLE
Node lost outputs  if waitContainer failed before AnnotateOutputs execute

### ISSUE THREAD

**Issue by uucloud** [argoproj/argo-workflows#5669]
## Summary 
Sometimes I can't get the archive log of failed nodes, the interface `/artifacts-by-uid/{uid}/{name}/main-file` returned `artifact not found`  but `main.log` could find in s3. This is because node outputs path not exist which cause waitContainer return before outputs annotation patched to pod, and then `podReconciliation` can't save node output.

This bug still exists in the latest version.

## Diagnostics

What Kubernetes provider are you using? 
v1.13.7

What version of Argo Workflows are you running? 
v2.12.10

This can be easily repeated：

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-verify
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["if false; then echo 'Im ok' && echo 'successful results' > /tmp/test.txt ;else echo 'Im not ok' && return 1;fi"]
    outputs:
      parameters:
      - name: test
        valueFrom:
          path: /tmp/test.txt
```

```
Paste the logs from the workflow controller:
![image](https://user-images.githubusercontent.com/13742734/114568909-20481b00-9ca7-11eb-9769-19755bb32caa.png)

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
