### ISSUE TITLE
Argo CLI lint command incorrectly flags spec.entrypoint as missing field

### ISSUE THREAD

**Issue by boonware** [argoproj/argo-workflows#5710]
## Summary 

Argo CLI lint is incorrectly complaining that field `spec.entrypoint` is missing from a workflow definition.

## Diagnostics

Argo CLI version `2.12.11` (latest)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-workflow-
spec:
  entrypoint: my-entrypoint
  templates:
    - name: my-template
      steps:
        - - name: my-step
            templateRef:
              name: my-template-name
              template: my-template-workflow
```

Running `argo lint workflow/` where `workflow/` is a directory containing the workflow produces the following console output:
```

\ERRO[2021-04-19T13:08:58.517Z] Error in file workflow/my-workflow.yaml: spec.entrypoint is required
FATA[2021-04-19T13:08:58.517Z] Errors encountered in validation  
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
