### ISSUE TITLE
Kubernetes resource creation template fails for resources like ConfigMap, Secrets, Pods etc

### ISSUE THREAD

**Issue by mojojoji** [argoproj/argo-workflows#5722]
Creation of resources like ConfigMap, Secret fails when a kubernetes resource type template is used. This is happening because there is a check for empty resourceGroup. But resourceGroup will be empty for certain resources like ConfigMap, Secrets, Pods etc.

https://github.com/argoproj/argo-workflows/blob/dba2c044e6d471f65dec868ff2453b90c088bd3e/workflow/executor/resource.go#L59-L61

The resource is created but because of the above check, the workflow fails with error 
```Group, kind, and name are all required but at least one of them is missing from the manifest```

How can argo workflows be used to create ConfigMaps and Secrets in one of the steps?

The workflow that gave this error is
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-workflow
spec:
  entrypoint: hello-config-gen
  templates:
    - name: hello-config-gen
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: hello-config
          data:
            username: test
```
