### ISSUE TITLE
Passing artifacts as manifest to resource template

### ISSUE THREAD

**Issue by deepk2u** [argoproj/argo-workflows#5735]
# Summary

What change needs making?

I need to pass input artifacts as manifest to resource template

# Use Cases
I have a huge k8s manifest that is coming as an artifact from another step and because of size limitations, we can not take that manifest as a parameter, so artifact is an alternative.

When would you use this?

```
- name: spark-application
    inputs:
      parameters:
      - name: phase
      artifacts:
      - name: spark-manifest-yaml
        path: /tmp/spark-manifest.yaml
    resource:
      action: create
      manifest: "{{inputs.artifacts.spark-manifest-yaml}}"
```

currently, it throws error: ` templates.spark-application.resource.manifest must be a valid yaml`

Alternative: Instead of using a resource template, we can use a script template and do a kubectl create, but we don't get other benefits of resource template like successConditions or FailureCondifitos, etc.
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
