### ISSUE TITLE
The env variable can't be used in another env variable.

### ISSUE THREAD

**Issue by madhuresh04** [argoproj/argo-workflows#5766]
## Summary 

I was expecting that when i declare an env variable , the same can be referenced i another env variable too (in the same container). But it was not happening. 
I gave tries with  $, ${} , {$} , {{$}}

## Diagnostics

What version of Argo Workflows are you running? 
v2.12
kubectl get workflow -oyaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: docker-host-1
  namespace: flow-argo-stage
spec:
  entrypoint: A
  serviceAccountName: flow-account
  templates:
  - name: A
    container:
      image: container-registry.alm.fkcloud.in/build-infra_tm-flow/step-templates/docker:v1
      env:
      - name: DOCKER_HOST_IP
        valueFrom: 
          fieldRef: 
            fieldPath: "status.podIP"
      - name: DOCKER_HOST
        value: "{{$DOCKER_HOST_IP}}"
      command: ["/bin/sh", "-c"]
      args: [ docker ps ;echo $DOCKER_HOST_IP; echo "IP" ; echo $DOCKER_HOST ; sleep 200 ;]
```

kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```
unable to resolve docker endpoint: parse tcp://{{$DOCKER_HOST_IP}}: invalid character "{" in host name
10.51.242.89
IP
{{$DOCKER_HOST_IP}}
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by madhuresh04** [comment]
We want to run docker commands from the script and want DOCKER_HOST variable to be set as tcp://${DOCKER_HOST_IP}:2375 
Were this DOCKER_HOST_IP is coming from the the env variable 
```
 - name: DOCKER_HOST_IP
        valueFrom: 
          fieldRef: 
            fieldPath: "status.podIP"
```
