### ISSUE TITLE
Reading outputs from an input directory fails in k8sapi

### ISSUE THREAD

**Issue by dhenneke** [argoproj/argo-workflows#5770]
## Summary 

I want to run a workflow that gets a working directory as an input, runs a container to modify the files, and publishes the modified working directory as an output. This should work with the `k8sapi` executer since the input folder is already part of an `emptyDir` volume.

Given this example workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-raw-
spec:
  entrypoint: raw-contents
  templates:
  - name: raw-contents
    inputs:
      artifacts:
      - name: myfile
        path: /input
        s3:
          key: input.tar.gz
    container:
      image: ubuntu:latest
      command: [sh, -c]
      args: ["echo 'some change' >> /input/file"]
    outputs:
      artifacts:
      - name: my-output
        path: /input
        s3:
          key: output.tar.gz
```

When I submit it, I get the following output:

```sh
# ./argo-darwin-amd64 submit --watch my-workflow.yaml

Name:                input-artifact-raw-dsg8v
Namespace:           argo
ServiceAccount:      default
Status:              Failed
Message:             invalid spec: templates.raw-contents.outputs.artifacts.my-output: k8sapi executor does not support outputs from base image layer.  Use an emptyDir: https://argoproj.github.io/argo-workflows/empty-dir/
Conditions:          
 Completed           True
Created:             Wed Apr 28 18:14:59 +0200 (now)
Started:             Wed Apr 28 18:14:59 +0200 (now)
Finished:            Wed Apr 28 18:14:59 +0200 (now)
Duration:            0 seconds
Progress:            0/0
```

## Diagnostics

Interestingly, the `WorkflowExecutor#isBaseImagePath(...)` function has explicit code to handle this case: https://github.com/argoproj/argo-workflows/blob/60a64c8254d406ff85e8f936d6c76da8d7a028e8/workflow/executor/executor.go#L445-L452

But the validator function `templateValidationCtx#validateBaseImageOutputs(...)` doesn't allow this use-case:
https://github.com/argoproj/argo-workflows/blob/60a64c8254d406ff85e8f936d6c76da8d7a028e8/workflow/validate/validate.go#L968-L975

Is this an supported scenario?

---

What Kubernetes provider are you using?  -> `k3d`
```sh
# brew install k3d
# k3d cluster create
```

What version of Argo Workflows are you running? -> `3.0.2`
```sh
# kubectl create ns argo
# kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/quick-start-minimal.yaml
```

I edited the `workflow-controller-configmap` configmap to use the k8sapi by default:
```diff
  apiVersion: v1
  data:
    artifactRepository: |
      archiveLogs: true
      s3:
        ...
+   containerRuntimeExecutor: k8sapi
-   containerRuntimeExecutor: docker
    containerRuntimeExecutors: |
      - name: k8sapi
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
