### ISSUE TITLE
SSO RBAC not working with most claims

### ISSUE THREAD

**Issue by victorkirov** [argoproj/argo-workflows#5786]
## Summary 

We're running Argo Workflows with SSO and RBAC enabled. We're using Google as the OIDC provider. The email scope is being requested as was confirmed in the URL when signing in on Google.

With RBAC disabled, anyone is able to login to the server successfully.

With RBAC enabled, we have annotated the server workflow account with the precedence and rule.

When we try to set a rule for the email `email endsWith '@ourdomain.com'`, we get this log: `level=error msg="failed to perform RBAC authorization" error="no service account rule matches"`

If I set the rule to `iss == '<my_iss_id>'` or `iss endsWith '<my_iss_id>'`, then I can successfully log in (but my colleagues cannot).

Setting to `true` also works but completely opens up the server to anyone with a Google account.

We also tried `hd == 'ourdomain.com'` and that also failed.

Expected behaviour is for the `email` rules to work, and, preferably, the `hd` rules as well.

## Diagnostics

We are using GKE and Argo Workflows v2.12.5

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Your rule looks correct to me. Can you confirm that if you open the user info page, the. Your email is shown? You need to configure the server is request the email scope.

**Comment by victorkirov** [comment]
No, it doesn't look like it's there:
![image](https://user-images.githubusercontent.com/3322667/116774440-ddcf5e00-aa5c-11eb-9c35-816144ae4e34.png)

This is the google login link we use:
```
https://accounts.google.com/o/oauth2/v2/auth/identifier?client_id=<our_client_id>&redirect_uri=<argo_url>%2Foauth2%2Fcallback&response_type=code&scope=email%20openid&state=<state>&flowName=GeneralOAuthFlow
```

The email scope is definitely there and going through the flow manually does get me a JWT with the email claim.

**Comment by AshwiniSwain** [comment]
@victorkirov Can you please share your rbac.yaml file. I have tried the rule `email endsWith '@ourdomain.com'`, and it works for me

**Comment by alexec** [comment]
The user interface will show your email address. This makes me wonder if you’re using an older version which does not support it. Can you please try with 2.12.11?

**Comment by victorkirov** [comment]
I just tried v2.12.11, but no luck :/

This is probably relevant, we are using the Helm charts to deploy Argo Workflows. The SSO section is configured as below:

```
    sso:
      issuer: https://accounts.google.com
      clientId:
        name: argo-server-sso
        key: client-id
      clientSecret:
        name: argo-server-sso
        key: client-secret
      redirectUrl: https://argo-dev.<our_url>.com/oauth2/callback
      rbac:
        enabled: true
        secretWhitelist: []
      scopes:
      - email
```
