### ISSUE TITLE
Resource Template Patch Fails Due to Insufficient Permissions

### ISSUE THREAD

**Issue by orrymr** [argoproj/argo-workflows#5789]
## Summary 

What happened/what you expected to happen?
I expect to be able to create a workflow with a resource template which is able to patch an existing deployment in my cluster.
The deployment is in the "dev" namespace. Argo Workflows is installed in argo-workflows.
I am getting a permission error: default serviceaccount (which workflows is using) doesn't have "get" permissions for deployments in the argo-workflows namespace. Why should it need "get" permissions for deployments in argo-workflows namespace when the deployment is in the dev namespace?

## Diagnostics

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 

V3.0.2

First, create the following deployment by `kubectl apply -f deployment-patch.yaml` , where deployment-patch.yaml is the following:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patch-demo
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: patch-demo-ctr
        image: nginx
      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: test-team
```

Next, patch the above deployment `argo submit patch-wf.yaml`, where patch-wf.yaml is the following:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: patch-wf-
spec:
  entrypoint: patch-template
  templates:
    - name: patch-template
      resource:
        action: patch
        flags:
        - deployment
        - "patch-demo"
        manifest: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: patch-demo
            namespace: dev
          spec:
            template:
              spec:
                containers:
                - name: patch-demo-ctr-2
                  image: redis
```

This results in the following error:

```
Error (exit code 1): Error from server (Forbidden): deployments.apps "patch-demo" is forbidden: User "system:serviceaccount:argo-workflows:default" cannot get resource "deployments" in API group "apps" in the namespace "argo-workflows" 
```

argo-workflows is the namespace where my workflow controller is installed. It's a namespace installation (as i only want it to pick up workflows created in the argo-workflows namespace).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by wanghong230** [comment]
It is just an RBAC issue. By default, we just ask for the bare minimum permission.

In your case, the default service account in the argo-workflows namespace is being used for your workflow which doesn't have the permission to touch the deployment object. You need to create additional role and role binding to enhance the default service account permission to allow that.

**Comment by orrymr** [comment]
@wanghong230  The deployment object I wish to patch is in the "dev" namespace, though. 
So why is it complaining that the default serviceaccount cannot touch deployment resources in the "argo-workflows" namespace? 

Regardless, I modified the RBAC rules as suggested:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-get-deployment
  namespace: argo-workflows
rules:
- apiGroups:
  - "app"
  resources:
  - deployments
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-get-deployment-from-argo-workflows-ns 
  namespace: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-get-deployment
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-workflows
```

and the problem persists.

I though that possibly I would need to allow access to the deployments resource, within the dev namespace, so I tried the following as well:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-get-deployment
  namespace: dev
rules:
- apiGroups:
  - "app"
  resources:
  - deployments
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-get-deployment-from-argo-workflows-ns 
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-get-deployment
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-workflows
```

(note the namespace changes in the above: in the Role and RoleBinding's .metadata.namespace .
