### ISSUE TITLE
Documentation request: Expression templates don't work for variable names with hyphens in them

### ISSUE THREAD

**Issue by Radolumbo** [argoproj/argo-workflows#5804]
## Summary 

I would anticipate that expression templates would work any place that simple templates work. It seems like they are only working in specific places within a YAML. They work, for example, when part of the args for a container. However, they don't work in volumes or annotations (or probably many other places), even though simple templates do.

## Diagnostics

As an example, this works:
```
volumes:
- name secret-vol
  secret:
    secretName: "{{inputs.parameters.kube-secret-name}}"
```

This does not work:
```
volumes:
- name secret-vol
  secret:
    secretName: "{{=inputs.parameters.kube-secret-name}}"
```

Is this behavior intended? And if so, can I convince you otherwise? :) 

Being able to dynamically choose some of these fields based on inputs would be SO immensely useful.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
