### ISSUE TITLE
`WorkflowEventBinding` supports only a subset of documented arguments

### ISSUE THREAD

**Issue by avifried1** [argoproj/argo-workflows#5806]
## Summary 

There is no way of creating a WorkflowEventBinding configuration with constants as arguments.
Using `expression` as per the [documentation](https://argoproj.github.io/argo-workflows/fields/#valuefrom):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: some-eventbinding
  labels:
    job-name: transunion-data-integration
spec:
  event:
    selector: discriminator == "some_disc"
  submit:
    workflowTemplateRef:
      name: some-template
    arguments:
      parameters:
        - name: some_param
          valueFrom:
            expression: "some_param"
```

The parameter is parsed as empty:

```yaml
    arguments:
      parameters:
        - name: some_param
           valueFrom: {}
```

Same thing happens with the `default` option. Only option that seems to work is `event`, so there's no way of supplying a WorkflowEventBinding with given values.
  
## Diagnostics

Argo workflows v`3.0.2`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
An expression can be a constant string value. Eg. ‘“Const”’

**Comment by avifried1** [comment]
in the example I gave for reproduction the expression is a const, but it's not even getting parsed

**Comment by alexec** [comment]
Can you please attach a complete example that does not work? I would expect to see more users with this problem.

**Comment by stefankraus-wf** [comment]
Whoops, looks like I am trying to use a >=3.1 feature in 3.0.2. My mistake, I apologize for commandeering the issue.

**Comment by mspdt22** [comment]
I am encountering this issue. Sample spec:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: on-pr-merge
spec:
  event:
    selector: [redacted]
  submit:
    workflowTemplateRef:
      name: my-workflow-template
    arguments:
      parameters:
        - name: which-bucket
          valueFrom:
            expression: foo
```

When I `kubectl describe` the workflow event binding, I see under events:

```
Warning  WorkflowEventBindingError  15m   workflow-controller  failed to dispatch event: failed to evaluate workflow template parameter "which-bucket" expression: unexpected token EOF (1:1)
```
