### ISSUE TITLE
Example not working for emptyDir

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#5825]
## Summary 

Example in the docs should work

## Diagnostics

What Kubernetes provider are you using? AKS with containerd

What version of Argo Workflows are you running? irrelevant

yaml is currently at https://argoproj.github.io/argo-workflows/empty-dir/

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: empty-dir-
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      volumes:
        - name: out
          emptyDir: { }
      outputs:
        artifacts:
          - name: message
            path: /mnt/out/message
```

Error:

Error (exit code 1): stat /mainctrfs/mnt/out/message: no such file or directory

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
