### ISSUE TITLE
Workflows with error in onExit handler never finish

### ISSUE THREAD

**Issue by vladlosev** [argoproj/argo-workflows#5835]
## Summary 

What happened/what you expected to happen?

When Argo fails to run an `onExit` handler in a workflow, it never marks the workflow as finished, even if all the nodes in it are fulfilled.
Expected: the workflow is marked as errored.

## Diagnostics

What Kubernetes provider are you using?
EKS 1.19, kind v0.10.0

What version of Argo Workflows are you running? 
3.0.2

Paste a workflow that reproduces the bug, including status:
```yaml
# kubectl get wftmpl -o yaml test-exit-handler
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-exit-handler
  namespace: test
spec:
  entrypoint: argosay
  onExit: exit-handler
  templates:
    - name: argosay
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - hello argo
    - name: exit-handler
      templateRef:
        name: nonexistent
        template: exit-handler

# The bug only manifests when the workflow is created via workflowTemplateRef.
# kubectl get wf -o yaml test-exit-handler
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-exit-handler-
  namespace: test
spec:
  workflowTemplateRef:
    name: test-exit-handler
```

Paste the logs from the workflow controller:

These entries show up in the logs every 30 minutes after the workflow is created:
```yaml
# kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
time="2021-05-05T19:30:40.534Z" level=debug msg="Syncing all CronWorkflows"
time="2021-05-05T19:30:44.497Z" level=info msg="Get leases 200"
time="2021-05-05T19:30:44.521Z" level=info msg="Update leases 200"
time="2021-05-05T19:30:49.497Z" level=info msg="Get leases 200"
time="2021-05-05T19:30:49.512Z" level=info msg="Update leases 200"
time="2021-05-05T19:30:49.677Z" level=info msg="Processing workflow" namespace=test workflow=test-exit-handler-s77sx
time="2021-05-05T19:30:49.683Z" level=debug msg="Evaluating node test-exit-handler-s77sx: template: *v1alpha1.WorkflowStep (argosay), boundaryID: " namespace=test workflow=test-exit-handler-s77sx
time="2021-05-05T19:30:49.683Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=,name=)" depth=0 tmpl="*v1alpha1.WorkflowStep (argosay)"
time="2021-05-05T19:30:49.683Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=,name=)" depth=0 tmpl="*v1alpha1.WorkflowStep (argosay)"
time="2021-05-05T19:30:49.683Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=,name=)" depth=0 tmpl="*v1alpha1.WorkflowStep (argosay)"
time="2021-05-05T19:30:49.683Z" level=debug msg="Node test-exit-handler-s77sx already completed" namespace=test workflow=test-exit-handler-s77sx
time="2021-05-05T19:30:49.683Z" level=info msg="Running OnExit handler: exit-handler" namespace=test workflow=test-exit-handler-s77sx
time="2021-05-05T19:30:49.684Z" level=debug msg="Evaluating node test-exit-handler-s77sx.onExit: template: *v1alpha1.WorkflowStep (exit-handler), boundaryID: " namespace=test workflow=test-exit-handler-s77sx
time="2021-05-05T19:30:49.684Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=,name=)" depth=0 tmpl="*v1alpha1.WorkflowStep (exit-handler)"
time="2021-05-05T19:30:49.684Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=,name=)" depth=0 tmpl="*v1alpha1.WorkflowStep (exit-handler)"
time="2021-05-05T19:30:49.684Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=,name=)" depth=0 tmpl="*v1alpha1.WorkflowStep (exit-handler)"
time="2021-05-05T19:30:49.684Z" level=error msg="Mark error node" error="template 'exit-handler' type is unknown" namespace=test nodeName=test-exit-handler-s77sx.onExit workflow=test-exit-handler-s77sx
time="2021-05-05T19:30:49.684Z" level=error msg="error in exit template execution" error="template 'exit-handler' type is unknown" namespace=test workflow=test-exit-handler-s77sx
time="2021-05-05T19:30:49.726Z" level=debug msg="Check the workflow existence"
time="2021-05-05T19:30:50.504Z" level=debug msg="Syncing all CronWorkflows"
time="2021-05-05T19:30:54.541Z" level=info msg="Get leases 200"
time="2021-05-05T19:30:54.599Z" level=info msg="Update leases 200"
time="2021-05-05T19:30:59.619Z" level=info msg="Get leases 200"
time="2021-05-05T19:30:59.661Z" level=info msg="Update leases 200"
```

It appears that upon encountering an error during the execution of the `onExit` template, the `operator()` function simply [exits](https://github.com/argoproj/argo-workflows/blob/3f808661ce1e44a28602715cccfad096332b9d03/workflow/controller/operator.go#L386) and never actually marks the workflow as an error.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
