### ISSUE TITLE
templateDefaults not supported when called from another template

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#5842]
## Summary 

What happened/what you expected to happen?

I have 2 templates, let's call them wf1 and wf2

wf2 calls wf1 with a templateRef

when wf1 is executed in this context, some step in wf1 complains about a missing volume

in wf1, the volume is declared in a templateDefaults

Here are the relevant parts

## Diagnostics

What Kubernetes provider are you using? AKS

What version of Argo Workflows are you running? latest

I suppose the templateDefaults of a workflowtemplate are not applied when the template is called from another template

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by christopheblin** [comment]
wf2.yml (I have edited it manually to prevent leaking some sensitive data, it may contain some errors)

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dataset-coverage
spec:   
  entrypoint: main
  arguments:
    parameters:
    - name: coverage
      value: "fr-xxx"

  templateDefaults:
    metadata:
      labels:
        coverage: "{{workflow.parameters.coverage}}"
    volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-share  

  templates:
  - name: main
    steps:
    - - name: generate
        template: generate
    - - name: execute
        templateRef:                  
          name: wf1 
          template: main
        arguments:
          parameters:
          - name: coverage
            value: "{{workflow.parameters.coverage}}"
          - name: dataset
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"

  - name: generate
    script:
      image: python:alpine3.6
      command: 
        - "/bin/sh"
      args:
        - "-c"
        - >
          find /data/config/$COVERAGE -maxdepth 1 -type d ! -name $COVERAGE 
          | xargs -n 1 basename 
          | python3 -c "import sys,json; print(json.dumps([row for row in sys.stdin.read().splitlines()]))"
      volumeMounts:
        - mountPath: /data
          name: my-volume
      env:
        - name: COVERAGE
          value: "{{workflow.parameters.coverage}}"
```

wf1.yml (I truncated to a single step, this workflow is working if launched standalone)

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dataset
spec:
  serviceAccountName: argo  
  entrypoint: main
  arguments:
    parameters:
    - name: coverage
      value: "fr-xxx"
    - name: dataset
      value: "city"
  
  templateDefaults:
    metadata:
      labels:
        coverage: "{{workflow.parameters.coverage}}"
        dataset: "{{workflow.parameters.dataset}}"
    volumes:
      - name: out
        emptyDir: { }
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-share  

  templates:
  - name: main
    steps:
    - - name: config
        template: dataset-config  
  
  - name: dataset-config
    container:
      image: alpine:latest
      workingDir: /dataset
      command: 
        - "/bin/sh"
      args:
        - "-c"
        - "-x"
        - >
          cat config/$COVERAGE/$DATASET/config.env 
          | sed  -E 's/([^=]*)=(.*)/ echo \2 > \/out\/\1.txt/' 
          | xargs -I{} sh -c '{}' 
          && ls /out 
      volumeMounts:
        - mountPath: /out
          name: out
        - mountPath: /dataset
          name: my-volume
      env:
        - name: COVERAGE
          value: "{{workflow.parameters.coverage}}"
        - name: DATASET
          value: "{{workflow.parameters.dataset}}" 
    outputs:
      parameters:
      - name: url      
        valueFrom:
          path: /out/URL.txt
          default: ""

```

MESSAGE
step group deemed errored due to child dataset-coverage-2v277[1].execute(1:xxxxxxx)[0].config error: volume 'out' not found in workflow spec

However, wf1.yml > templateDefaults DOES contain the 'out' volume (as well as labels)

![Capture d’écran 2021-05-06 à 10 44 40](https://user-images.githubusercontent.com/11044877/117268979-266d8980-ae58-11eb-8acb-09ee7ead7e94.png)

Note that I cannot see if labels worked because the pod does not exist (the name is taken from GUI POD NAME)

```
k describe pod dataset-coverage-2v277-2326547145
Error from server (NotFound): pods "dataset-coverage-2v277-2326547145" not found

```
