### ISSUE TITLE
Logs not archived in s3 bucket.

### ISSUE THREAD

**Issue by akshaybhatt14495** [argoproj/argo-workflows#5868]
## Summary 

What happened
Let say archive logs flag is true, (Logs will be pushed to s3 bucket). So in case of step failure/success logs used to save in s3 bucket. 
But In case of step failure due to timeout, Logs not getting saved in s3 bucket

what you expected to happen?
In any status of step. Logs should be saved to s3 bucket.

## Diagnostics

What Kubernetes provider are you using? 
clientVersion:
  buildDate: "2020-02-13T18:06:54Z"
  compiler: gc
  gitCommit: 06ad960bfd03b39c8310aaf92d1e7c12ce618213
  gitTreeState: clean
  gitVersion: v1.17.3
  goVersion: go1.13.8
  major: "1"
  minor: "17"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-06-17T11:33:59Z"
  compiler: gc
  gitCommit: c96aede7b5205121079932896c4ad89bb93260af
  gitTreeState: clean
  gitVersion: v1.18.4
  goVersion: go1.13.9
  major: "1"
  minor: "18"
  platform: linux/amd64

What version of Argo Workflows are you running? 
argo: v2.12.7
  BuildDate: 2021-02-01T22:11:06Z
  GitCommit: 5f5150730c644865a5867bf017100732f55811dd
  GitTreeState: clean
  GitTag: v2.12.7
  GoVersion: go1.13
  Compiler: gc
  Platform: darwin/amd64
```yaml

Paste a workflow that reproduces the bug, including status:

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: retry-workflow
spec:
  activeDeadlineSeconds: 600
  entrypoint: retryExample
  serviceAccountName: flow-account
  templates:
  - name: retryExample
    activeDeadlineSeconds: 10
    container:
      resources:
        limits:
          cpu: "1"
          memory: "2e9"
        requests:
          cpu: "1"
          memory: "2e9"
      image: apline
      imagePullPolicy: Always
      name: ""
      args:
      - |-
        echo sleeping for 60 sec;
        sleep 60;
        echo sleep complete;
      command:
      - /bin/sh
      - -c
```

```
Paste the logs from the workflow controller:
https://gist.github.com/akshaybhatt14495/172d299420b3cdb7773753506eee500b

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
