### ISSUE TITLE
Linting fails to recognize global output parameters created within layered templates

### ISSUE THREAD

**Issue by samath117** [argoproj/argo-workflows#5873]
## Summary 

Global output parameters are getting incorrectly flagged by the linter when they are invoked through a series of templates. First consider a series of layered templates like this:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: layer1-templates
spec:
  templates:
  - name: global-parameter-setting
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["echo 'hello world' > /parameter.txt"]
    outputs:
      parameters:
      - name: parameter
        valueFrom:
          path: /parameter.txt
        globalName: parameter
```

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: layer2-templates
spec:
  templates:
  - name: global-parameter-setting
    steps:
    - - name: set-parameter
        templateRef:
          name: layer1-templates
          template: global-parameter-setting
```

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: layer3-templates
spec:
  templates:
  - name: global-parameter-setting
    steps:
    - - name: set-parameter
        templateRef:
          name: layer2-templates
          template: global-parameter-setting
```

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: base-templates
spec:
  templates:
  - name: parameter-passing
    inputs:
      parameters:
      - name: parameter
      artifacts:
      - name: parameter
        path: /parameter.txt
        raw:
          data: |
            {{inputs.parameters.parameter}}
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["exit 0"]
    outputs:
      parameters:
      - name: parameter
        valueFrom:
          path: /parameter.txt
```

Now consider a simple workflow that uses this global parameter:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: layered-workflow-
spec:
  entrypoint: plan
  onExit: exit-handler
  templates:
  - name: plan
    steps:
    - - name: generate-parameter
        templateRef:
          name: layer2-templates
          template: global-parameter-setting
    - - name: process-parameter
        templateRef:
          name: base-templates
          template: parameter-passing
        arguments:
          parameters:
          - name: parameter
            value: "{{workflow.outputs.parameters.parameter}}"
```

This fails the linter with the following error:
```
templates.plan.steps failed to resolve {{workflow.outputs.parameters.parameter}}
```
However, if we change the `templateRef.name` of `generate-parameter` from `layer2-templates` to `layer1-templates`, then it passes the linter and works correctly. This shouldn't happen, because the layering doesn't change what actually runs, including the global parameter it produces.

Finally consider the following workflow, where the receiving end is put into an exit handler instead:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: layered-workflow-
spec:
  entrypoint: plan
  onExit: exit-handler
  templates:
  - name: plan
    steps:
    - - name: generate-parameter
        templateRef:
          name: layer3-templates
          template: global-parameter-setting

  - name: exit-handler
    steps:
    - - name: process-parameter
        templateRef:
          name: base-templates
          template: parameter-passing
        arguments:
          parameters:
          - name: parameter
            value: "{{workflow.outputs.parameters.parameter}}"
```

Unlike the previous example, this one actually works with `layer2-templates` as well as `layer1-templates` but fails with `layer3-templates`. Again, this doesn't make any sense, and I'm actually surprised that the behavior is different for the exit handler.

## Diagnostics

I was able to reproduce this error in both v3.0.2 and v2.12.11. (The only change is the display of the linting failure.)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
