### ISSUE TITLE
Extend withParam field to support an inputs.artifacts.ARR values

### ISSUE THREAD

**Issue by amitm02** [argoproj/argo-workflows#5877]
# Summary

Currently withParam only accepts a (json array)` inputs.parameters.ARR` as a value. e.g:

```
 - - name: test-linux
        template: cat-os-release
        arguments:
          parameters:
          - name: image
            value: "{{item.image}}"
          - name: tag
            value: "{{item.tag}}"
        withParam: "{{inputs.parameters.os-list}}"
```

Allowing it to accept ` inputs.artifat.ARR` as its value will allow Argo to loop over very large arrays.

What change needs making?

copying here from slack thread:

> Hong Wang: Cool, we are on the same page. Technically, it is not as simple as it looks like. WithParam is actually done in the controller side which is running in argo namespaces, the controller can do it because the annotation is part of the pod spec, with the help of wait container, controller can access that info and expand withParam. The artifact is a different story, the main controller normally don't have the access to the secrets in other namespaces, so it won't be able to load the artifact file, and look into the JSON to expand it. Please do create an issue to track this. We are adding a feature called Argo-Agent might be able to solving this by running an additional agent pod inside user namespace to full-fill some controller responsibility. So, it could be promising to implement it in the end.

# Use Cases

When would you use this?

Currently, the only way to loop over a large array is via withSequence. it is cumbersome and hard to read and develop.
[link](https://github.com/argoproj/argo-workflows/blob/master/examples/handle-large-output-results.yaml)

This enhancement will allow the to store the big array (>256kb) in an Artifact and still be able to loop over it in the regular way.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by amitm02** [comment]
@alexec, a few questions.
1. for the docs, I see that the data template store the results in `outputs.result`, can `outputs.result` store >256kb data?
2. Can the data template work with the configured key-only artifact?
3. Can the data template loop over a specific folder in the artifact? else it means that it will have to loop over ALL the artifacts or all workflows which can be a heavy task.
4. would you mind putting here a simple example of how to use the data template to loop over huge arrays? that would be awesome!

**Comment by alexec** [comment]
> @alexec, a few questions.
> 
> 1. from the docs, I see that the data template store the results in `outputs.result`, can `outputs.result` store >256kb data?

Short answer - no. Use artifacts.

> 2. Can the data template work with the configured key-only artifact?

Yes.

> 3. Can the data template loop over a specific folder in the artifact? else it means that it will have to loop over ALL the artifacts for all workflows which can be a heavy task.

Yes.

> 4. would you mind putting here a simple example of how to use the data template to loop over huge arrays? that would be awesome!

There is an example in the `examples` folder.

**Comment by amitm02** [comment]
It is very likely I'm missing something.  but looking into _data template_ I couldn't find how it improves the situation.
Assuming I'm having the simple template `echo`.
It is trivial and clear how to  loop over an array stored in a parameter using `withParam`, and run the echo template per item.
If that array is large (>256kb) and stored in an atrifact, I can no longer use the _echo_ template below.
Both the `withSequence`  and the `data template` workarounds forces me to make "hacky" changes to the echo template and add middle steps.

```
- name: echo
      inputs:
        parameters:
        - name: message
      container:
        image: alpine:3.7
        command: [echo, "{{inputs.parameters.message}}"]
```
