### ISSUE TITLE
Creating A Resource Using Git Artifact

### ISSUE THREAD

**Issue by orrymr** [argoproj/argo-workflows#5878]
## Summary 

I have a workflow with 2 steps. The first is simply doing a git clone in order to create a git artifact. The repository I clone has a workflow yaml in it. I then want to use the workflow yaml in the next step, where I have a resource template. That is, the resource template should create the workflow which was in the git repo cloned in step 1! 

## Diagnostics

What Kubernetes provider are you using? GKE

What version of Argo Workflows are you running? 3.0.1

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: possible-bug-
spec:
  entrypoint: all-steps
  templates:
  - name: all-steps
    steps:
    - - name: step-1-create-git-artifact
        template: git-clone 
    - - name: step-2-create-workflow
        template: create-resource
        arguments:
          parameters:
          - name: resource-manifest
            value: "steps.step-1-create-git-artifact.outputs.parameters.manifest"
  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: /src
        git:
          repo: https://github.com/argoproj/argo-workflows.git
          revision: master
    container:
      image: golang:1.10
      workingDir: /src
      command: [sh, -c]
      args: ["sleep 1;
              cat examples/hello-world.yaml > /tmp/hello-world.yaml"]
    outputs:
      parameters:
        - name: manifest
          valueFrom:
            default: "hello-world.yaml didnt work"
            path: "/tmp/hello-world.yaml"
  - name: create-resource
    inputs:
      parameters:
      - name: resource-manifest
    resource:
      action: create
      manifest: "{{inputs.parameters.resource-manifest}}"
```

```
Paste the logs from the workflow controller:
 Error (exit code 1): error: error validating "/tmp/manifest.yaml": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false  
```

I have also seen this error when changing the yamls:

```
create-resource master-resource-creator-lhvgb-729962375  2s    Error (exit code 1): error: error parsing /tmp/manifest.yaml: error converting YAML to JSON: yaml: mapping values are not allowed in this context
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
