### ISSUE TITLE
Custom metrics - DAG/TASK not being emitted properly

### ISSUE THREAD

**Issue by everton-nasc** [argoproj/argo-workflows#5881]
## Summary 

Seems the custom metrics for DAG/TASK are not being emitted properly.

## Diagnostics

What Kubernetes provider are you using? 
```
GKE
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```
What version of Argo Workflows are you running? 
**v3.0.2**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-task-
spec:
  entrypoint: dag-task
  serviceAccountName: argo-server
  metrics:
    prometheus:
      - name: playground_workflow_duration
        help: "Duration gauge by name - workflow level"
        labels:
          - key: "playground_id_workflow"
            value: "test"
          - key: status
            value: "{{workflow.status}}"
        gauge:
          realtime: false
          value: "{{workflow.duration}}"
      - name: playground_workflow_result_counter
        help: "Count of workflow execution by result status  - workflow level"
        labels:
          - key: "playground_id_workflow_counter"
            value: "test"
          - key: status
            value: "{{workflow.status}}"
        counter:
          value: "1"
  templates:
  - name: dag-task
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
        metrics:
          prometheus:
            - name: playground_workflow_duration
              help: "Duration gauge by name - task level"
              labels:
                - key: "playground_id_workflow"
                  value: "{{task.name}}"
                - key: status
                  value: "{{status}}"
              gauge:
                realtime: false
                value: "{{duration}}"
            - name: playground_workflow_result_counter
              help: "Count of workflow execution by result status  - task level"
              labels:
                - key: "playground_id_workflow_counter"
                  value: "{{task.name}}"
                - key: status
                  value: "{{status}}"
              counter:
                value: "1"

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
```

```
time="2021-05-11T17:44:36.810Z" level=info msg="Processing workflow" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:36.813Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:36.813Z" level=info msg="DAG node dag-task-bfqsm initialized Running" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:36.814Z" level=info msg="All of node dag-task-bfqsm.A dependencies [] completed" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:36.814Z" level=info msg="Pod node dag-task-bfqsm-660967064 initialized Pending" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:36.831Z" level=info msg="Created pod: dag-task-bfqsm.A (dag-task-bfqsm-660967064)" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:36.843Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=65071248 workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.810Z" level=info msg="Processing workflow" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.811Z" level=info msg="Setting node dag-task-bfqsm-660967064 outputs" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.811Z" level=info msg="Updating node dag-task-bfqsm-660967064 status Pending -> Succeeded" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.811Z" level=info msg="Outbound nodes of dag-task-bfqsm set to [dag-task-bfqsm-660967064]" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.811Z" level=info msg="node dag-task-bfqsm phase Running -> Succeeded" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.811Z" level=info msg="node dag-task-bfqsm finished: 2021-05-11 17:44:46.811510709 +0000 UTC" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.811Z" level=info msg="Checking daemoned children of dag-task-bfqsm" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.811Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.811Z" level=info msg="Marking workflow completed" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.811Z" level=info msg="Doesn't match with archive label selector. Skipping Archive" namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.811Z" level=info msg="Checking daemoned children of " namespace=argo workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.824Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=65071397 workflow=dag-task-bfqsm
time="2021-05-11T17:44:46.831Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/dag-task-bfqsm-660967064/labelPodCompleted
time="2021-05-11T17:44:56.842Z" level=info msg="Workflow processing has been postponed due to max parallelism limit" key=argo/dag-task-bfqsm

```

## Custom metric

Custom metric emitted - workflow-level
```
# HELP argo_workflows_playground_workflow_duration Duration gauge by name - workflow level
# TYPE argo_workflows_playground_workflow_duration gauge
argo_workflows_playground_workflow_duration{playground_id_workflow="test",status="Succeeded"} 10.811587
# HELP argo_workflows_playground_workflow_result_counter Count of workflow execution by result status  - workflow level
# TYPE argo_workflows_playground_workflow_result_counter counter
argo_workflows_playground_workflow_result_counter{playground_id_workflow_counter="test",status="Succeeded"} 2
```

Custom metric emitted - dag-task-level
```
Not emitted
```

Note: Seems there are more related issues regarding custom metrics for DAG/TASK:
* https://github.com/argoproj/argo-workflows/issues/3872
* https://github.com/argoproj/argo-workflows/issues/5536

Not sure, but looks like I'm struggling where should I place the metrics - it is not clear though. Any help will be very appreciated. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
