### ISSUE TITLE
Ability to submit a workflow template but also skipping sections

### ISSUE THREAD

**Issue by gsdevme** [argoproj/argo-workflows#5889]
# Summary

Add the ability to submit a workflow template but skip some tasks

What change needs making?

I think it might be straight forward to mutate the template here https://github.com/argoproj/argo-workflows/blob/master/cmd/argo/commands/submit.go#L222-L227 before its submitted to exclude some steps 

# Use Cases

During development or sometimes during failure its handy to have the ability to start a workflow from a specific section *but* sometimes the dependency means you might need to execute Step 1, Step 5, Step 6 ... but you don't wish to execute Step 2,3,4 (for example).

By allowing submit to skip sections of the template you can craft a submit that allows the dependency to be resolved without needlessly running other sections of the workflow

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

---

If this general idea is acceptable Id be happy to attempt the changes.

**Comment by sarabala1979** [comment]
@gsdevme  you can achieve using workflow parameter and `when` on steps/tasks.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  arguments:
     parameters:
     - name: env
       value: prod
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello1"}]
    - - name: hello2a
        template: whalesay
        when: {{workflow.paramenters.env}} == prod #This step will execute based on parameter value.  
        arguments:
          parameters: [{name: message, value: "hello2a"}]
      - name: hello2b
        template: whalesay
        when: {{workflow.paramenters.env}} == dev
        arguments:
          parameters: [{name: message, value: "hello2b"}]

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```
