### ISSUE TITLE
Support workflow parameters as values for "artifactRepositoryRef.key"

### ISSUE THREAD

**Issue by kulinskyvs** [argoproj/argo-workflows#5891]
# Summary

Add support of workflow parameters as values of "[artifactRepositoryRef.key](https://argoproj.github.io/argo-workflows/artifact-repository-ref/)" for workflows/workflowTemplates?

# Use Cases

I have a ConfigMap with several supported Artifact Repositories.

```yaml
apiVersion: v1
kind: ConfigMap
name: artifact-repositories
data:
  aws-s3: |
    s3:
      bucket: bucketname
      accessKeySecret:
        name: s3-secret
        key: accesskey
      secretKeySecret:
        name: s3-secret
        key: secretkey
  minio: |
    s3:
      bucket: bucketname
      insecure: true
      accessKeySecret:
        name: minio-secret
        key: accesskey
      secretKeySecret:
        name: minio-secret
        key: secretkey
      endpoint: minio:9000
```

Would be great to have the ability to set the artifact repository to be used by a workflow through the workflow input parameters.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow-template
spec:
  arguments:
    parameters:
      - name: artifactRepository
        value: "aws-s3"
  artifactRepositoryRef:
    key: "{{workflow.parameters.artifactRepository}}"
  templates:
  .........
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Joibel** [comment]
This already works, and has done for a long time — `spec.artifactRepositoryRef.key` goes through global-parameter substitution before the repository is resolved, so your example should work as written:

```yaml
spec:
  arguments:
    parameters:
      - name: artifactRepository
        value: aws-s3
  artifactRepositoryRef:
    key: "{{workflow.parameters.artifactRepository}}"
```

The controller substitutes `{{workflow.*}}` over the whole workflow spec (see `substituteGlobalVariables` in `workflow/controller/operator.go`) inside `setExecWorkflow`, which runs before `artifactRepositories.Resolve`. I verified both a plain Workflow and a WorkflowTemplate + `workflowTemplateRef` (with the Workflow overriding the parameter) resolve to the expected config map key on current main.

One caveat: only workflow-level parameters work. The repository ref is resolved once at the start of the workflow and cached in `status.artifactRepositoryRef`, so a value that only becomes known mid-run (e.g. a step's output parameter) cannot be used.

Closing as already supported. This isn't documented, so a small PR adding a note to `docs/artifact-repository-ref.md` would be very welcome.
