### ISSUE TITLE
Add support of using workflow parameters in workflow metadata

### ISSUE THREAD

**Issue by kulinskyvs** [argoproj/argo-workflows#5892]
# Summary

Add support of using workflow parameters for `workflowMetadata` section on the workflow template level? 

# Use Cases

I have a reusable workflow template with some `workflowMetadata` defined - I would like to refer to workflow input parameters from `workflowMetadata` section (use these values when building the labels for example).

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow-template
spec:
  arguments:
    parameters:
      - name: env
        value: "prod"
      - name: platform
        value: my-platform
  workflowMetadata:
    labels:
      environment: "{{ workflow.parameters.env }}"
      platform: "{{ workflow.parameters.platform }}"
  templates:
  .........
```

Supporting workflow parameters inside the `workflowMetadata` section (labels, for example) can increase its reusability and makes the workflows submitted from this template more consistent and discoverable (labeling is done regardless of the labels provided during workflow submission through UI or argocli).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
