### ISSUE TITLE
Optional s3 input artifact appears as empty directory

### ISSUE THREAD

**Issue by shrgabor** [argoproj/argo-workflows#5934]
## Summary 

**What happened:** When an optional input artifact is not supplied, an empty directory is still placed at the given path. This causes unexpected errors if that optional artifact is usually a file.

**What you expected to happen:** The empty directory should simply not be created if the input artifact is not supplied.

This issue is very similar to: #1503 
**But it requires an S3 input artifact.**

## Diagnostics

What version of Argo Workflows are you running? 
Reproduced on: 3.0.2 and 3.0.4

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: minimal-optional-directory-appears-example-
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Error
  name: qwe
  namespace: sohi-wl-d4114
spec:
  entrypoint: plan
  templates:
  - container:
      args:
      - ls -la
      command:
      - sh
      - -c
      image: alpine:latest
      name: ""
    inputs:
      artifacts:
      - name: opt
        optional: true
        path: /file.yaml
        s3:
          accessKeySecret:
            key: access-key
            name: minio
          bucket: hosting
          endpoint: minio:9000
          insecure: true
          key: file.yml
          secretKeySecret:
            key: secret-key
            name: minio
    name: plan
status:
  artifactRepositoryRef:
    default: true
  conditions:
  - status: "False"
    type: PodRunning
  - status: "True"
    type: Completed
  finishedAt: "2021-05-18T06:32:41Z"
  message: 'Error (exit code 1): pods "qwe" is forbidden: User "system:serviceaccount:sohi-wl-d4114:default"
    cannot patch resource "pods" in API group "" in the namespace "sohi-wl-d4114"'
  nodes:
    qwe:
      displayName: qwe
      finishedAt: "2021-05-18T06:32:38Z"
      id: qwe
      inputs:
        artifacts:
        - name: opt
          optional: true
          path: /file.yaml
          s3:
            accessKeySecret:
              key: access-key
              name: minio
            bucket: hosting
            endpoint: minio:9000
            insecure: true
            key: file.yml
            secretKeySecret:
              key: secret-key
              name: minio
      message: 'Error (exit code 1): pods "qwe" is forbidden: User "system:serviceaccount:sohi-wl-d4114:default"
        cannot patch resource "pods" in API group "" in the namespace "sohi-wl-d4114"'
      name: qwe
      phase: Error
      progress: 1/1
      resourcesDuration:
        cpu: 4
        memory: 4
      startedAt: "2021-05-18T06:32:31Z"
      templateName: plan
      templateScope: local/qwe
      type: Pod
  phase: Error
  progress: 1/1
  resourcesDuration:
    cpu: 4
    memory: 4
  startedAt: "2021-05-18T06:32:31Z"
```

```
time="2021-05-18T06:25:29.794Z" level=info msg="Processing workflow" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:29.798Z" level=info msg="Updated phase  -> Running" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:29.798Z" level=info msg="Pod node qwe initialized Pending" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:29.799Z" level=info msg="skip volume mount of opt (/file.yaml): optional artifact was not provided" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:29.815Z" level=info msg="Created pod: qwe (qwe)" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:29.847Z" level=info msg="Workflow update successful" namespace=sohi-wl-d4114 phase=Running resourceVersion=42058 workflow=qwe
time="2021-05-18T06:25:39.817Z" level=info msg="Processing workflow" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:39.817Z" level=info msg="Pod failed: Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" displayName=qwe namespace=sohi-wl-d4114 pod=qwe templateName=plan workflow=qwe
time="2021-05-18T06:25:39.818Z" level=info msg="Updating node qwe status Pending -> Error" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:39.818Z" level=info msg="Updating node qwe message: Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:39.818Z" level=info msg="Updated phase Running -> Error" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:39.818Z" level=info msg="Updated message  -> Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:39.818Z" level=info msg="Marking workflow completed" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:39.818Z" level=info msg="Checking daemoned children of " namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:25:39.842Z" level=info msg="Workflow update successful" namespace=sohi-wl-d4114 phase=Error resourceVersion=42105 workflow=qwe
time="2021-05-18T06:25:39.847Z" level=info msg="cleaning up pod" action=labelPodCompleted key=sohi-wl-d4114/qwe/labelPodCompleted
time="2021-05-18T06:28:18.159Z" level=info msg="Processing workflow" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:18.173Z" level=info msg="Updated phase  -> Running" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:18.174Z" level=info msg="Pod node qwe initialized Pending" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:18.187Z" level=info msg="Created pod: qwe (qwe)" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:18.201Z" level=info msg="Workflow update successful" namespace=sohi-wl-d4114 phase=Running resourceVersion=42422 workflow=qwe
time="2021-05-18T06:28:28.187Z" level=info msg="Processing workflow" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:28.187Z" level=info msg="Pod failed: Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" displayName=qwe namespace=sohi-wl-d4114 pod=qwe templateName=plan workflow=qwe
time="2021-05-18T06:28:28.187Z" level=info msg="Updating node qwe status Pending -> Error" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:28.187Z" level=info msg="Updating node qwe message: Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:28.188Z" level=info msg="Updated phase Running -> Error" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:28.188Z" level=info msg="Updated message  -> Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:28.188Z" level=info msg="Marking workflow completed" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:28.188Z" level=info msg="Checking daemoned children of " namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:28:28.205Z" level=info msg="Workflow update successful" namespace=sohi-wl-d4114 phase=Error resourceVersion=42473 workflow=qwe
time="2021-05-18T06:28:28.219Z" level=info msg="cleaning up pod" action=labelPodCompleted key=sohi-wl-d4114/qwe/labelPodCompleted
time="2021-05-18T06:30:40.896Z" level=info msg="Processing workflow" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:40.899Z" level=info msg="Updated phase  -> Running" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:40.900Z" level=info msg="Pod node qwe initialized Pending" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:40.907Z" level=info msg="Created pod: qwe (qwe)" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:40.926Z" level=info msg="Workflow update successful" namespace=sohi-wl-d4114 phase=Running resourceVersion=42735 workflow=qwe
time="2021-05-18T06:30:50.910Z" level=info msg="Processing workflow" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:50.910Z" level=info msg="Pod failed: Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" displayName=qwe namespace=sohi-wl-d4114 pod=qwe templateName=plan workflow=qwe
time="2021-05-18T06:30:50.910Z" level=info msg="Updating node qwe status Pending -> Error" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:50.910Z" level=info msg="Updating node qwe message: Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:50.911Z" level=info msg="Updated phase Running -> Error" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:50.911Z" level=info msg="Updated message  -> Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:50.911Z" level=info msg="Marking workflow completed" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:50.911Z" level=info msg="Checking daemoned children of " namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:30:50.928Z" level=info msg="Workflow update successful" namespace=sohi-wl-d4114 phase=Error resourceVersion=42784 workflow=qwe
time="2021-05-18T06:30:50.951Z" level=info msg="cleaning up pod" action=labelPodCompleted key=sohi-wl-d4114/qwe/labelPodCompleted
time="2021-05-18T06:31:53.785Z" level=info msg="Processing workflow" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:31:53.787Z" level=info msg="Updated phase  -> Running" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:31:53.787Z" level=info msg="Pod node qwe initialized Pending" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:31:53.787Z" level=info msg="skip volume mount of opt (/file.yaml): optional artifact was not provided" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:31:53.794Z" level=info msg="Created pod: qwe (qwe)" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:31:53.803Z" level=info msg="Workflow update successful" namespace=sohi-wl-d4114 phase=Running resourceVersion=42914 workflow=qwe
time="2021-05-18T06:32:03.795Z" level=info msg="Processing workflow" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:03.795Z" level=info msg="Pod failed: Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" displayName=qwe namespace=sohi-wl-d4114 pod=qwe templateName=plan workflow=qwe
time="2021-05-18T06:32:03.796Z" level=info msg="Updating node qwe status Pending -> Error" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:03.796Z" level=info msg="Updating node qwe message: Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:03.796Z" level=info msg="Updated phase Running -> Error" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:03.796Z" level=info msg="Updated message  -> Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:03.796Z" level=info msg="Marking workflow completed" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:03.796Z" level=info msg="Checking daemoned children of " namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:03.809Z" level=info msg="Workflow update successful" namespace=sohi-wl-d4114 phase=Error resourceVersion=42963 workflow=qwe
time="2021-05-18T06:32:03.850Z" level=info msg="cleaning up pod" action=labelPodCompleted key=sohi-wl-d4114/qwe/labelPodCompleted
time="2021-05-18T06:32:31.979Z" level=info msg="Processing workflow" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:31.981Z" level=info msg="Updated phase  -> Running" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:31.982Z" level=info msg="Pod node qwe initialized Pending" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:31.994Z" level=info msg="Created pod: qwe (qwe)" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:32.009Z" level=info msg="Workflow update successful" namespace=sohi-wl-d4114 phase=Running resourceVersion=43177 workflow=qwe
time="2021-05-18T06:32:41.994Z" level=info msg="Processing workflow" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:41.994Z" level=info msg="Pod failed: Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" displayName=qwe namespace=sohi-wl-d4114 pod=qwe templateName=plan workflow=qwe
time="2021-05-18T06:32:41.995Z" level=info msg="Updating node qwe status Pending -> Error" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:41.995Z" level=info msg="Updating node qwe message: Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:41.995Z" level=info msg="Updated phase Running -> Error" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:41.995Z" level=info msg="Updated message  -> Error (exit code 1): pods \"qwe\" is forbidden: User \"system:serviceaccount:sohi-wl-d4114:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"sohi-wl-d4114\"" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:41.995Z" level=info msg="Marking workflow completed" namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:41.995Z" level=info msg="Checking daemoned children of " namespace=sohi-wl-d4114 workflow=qwe
time="2021-05-18T06:32:42.019Z" level=info msg="Workflow update successful" namespace=sohi-wl-d4114 phase=Error resourceVersion=43226 workflow=qwe
time="2021-05-18T06:32:42.101Z" level=info msg="cleaning up pod" action=labelPodCompleted key=sohi-wl-d4114/qwe/labelPodCompleted
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
