### ISSUE TITLE
valueFrom expression not working

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#5944]
I'm trying to do a conditional parameter and running into some errors. Can anyone advise?

```
FATA[2021-05-18T16:52:23.217Z] Failed to submit workflow: templates.pipeline.steps[1].build-image templates.build-image.steps[0].generate-image-tag valueFrom type unspecified. choose one of: path, jqFilter, jsonPath, parameter, raw
```

I tried on v3.0.4 and v3.0.5

Using https://argoproj.github.io/argo-workflows/examples/conditional-parameters.yaml as reference.

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-image
spec:
  entrypoint: build-image
  arguments:
    parameters:
      - name: image-tag
        value: latest
      - name: salt-and-hash-image-tag
        value: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737
    privileged: false
  templates:
    - name: build-image
      steps:
        - - name: generate-image-tag
            templateRef:
              name: generate-image-tag
              template: generate-image-tag
            arguments:
              parameters:
                - name: image-tag
                  value: "{{workflow.parameters.image-tag}}"
                - name: salt-and-hash-image-tag
                  value: "{{workflow.parameters.salt-and-hash-image-tag}}"
```

```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: generate-image-tag
spec:
  entrypoint: generate-image-tag
  arguments:
    parameters:
      - name: image-tag
        value: latest
      - name: salt-and-hash-image-tag
        value: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737
    privileged: false
  templates:
    - name: generate-image-tag
      inputs:
        parameters:
          - name: image-tag
          - name: salt-and-hash-image-tag
      steps:
        - - name: echo-salt-and-hash-image-tag
            templateRef:
              name: echo
              template: echo
            arguments:
              parameters:
                - name: echo-input
                  value: "{{inputs.parameters.salt-and-hash-image-tag}}"
        - - name: salt-and-hash-image-tag
            when: "'{{inputs.parameters.salt-and-hash-image-tag}}' == 'true'"
            templateRef:
              name: salt-and-hash
              template: salt-and-hash
            arguments:
              parameters:
                - name: salt-and-hash-input
                  value: "{{inputs.parameters.image-tag}}"
          - name: echo-image-tag
            when: "'{{inputs.parameters.salt-and-hash-image-tag}}' != 'true'"
            templateRef:
              name: echo
              template: echo
            arguments:
              parameters:
                - name: echo-input
                  value: "{{inputs.parameters.image-tag}}"
      outputs:
        parameters:
          - name: generated-image-tag
            valueFrom:
              expression: "steps['echo-salt-and-hash-image-tag'].outputs.result == 'true' ? {{steps.salt-and-hash-image-tag.outputs.result}} : {{steps.echo-image-tag.outputs.result}}"
```

```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: salt-and-hash
spec:
  entrypoint: salt-and-hash
  arguments:
    parameters:
      - name: salt-and-hash-input
        value: ""
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737
    privileged: false
  templates:
    - name: salt-and-hash
      inputs:
        parameters:
          - name: salt-and-hash-input
      script:
        image: alpine:latest
        command:
          - sh
        source: >-
          echo -n "{{inputs.parameters.salt-and-hash-input}}$(tr -dc A-Za-z0-9 </dev/urandom | head -c 64)" |
          sha256sum |
          awk '{print $1}'
```

```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: echo
spec:
  entrypoint: echo
  arguments:
    parameters:
      - name: echo-input
        value: ""
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737
    privileged: false
  templates:
    - name: echo
      inputs:
        parameters:
          - name: echo-input
      script:
        image: alpine:latest
        command:
          - sh
        source: |-
          echo "{{inputs.parameters.echo-input}}"
```
