### ISSUE TITLE
privileged not recognized

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#5948]
I am following the guide in https://argoproj.github.io/argo-workflows/workflow-pod-security-context/

I am getting linting errors. Also, I do not see privileged applied to the pod.

I am using argo v3.1.0-rc5, but the same behaviour occurred with v3.0.3 and v3.0.4

```
 ❯ argo lint echo.yaml
echo.yaml:
   ✖ in "echo" (WorkflowTemplate): json: unknown field "privileged"

✖ 1 linting errors found!
```

```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: echo
spec:
  entrypoint: echo
  arguments:
    parameters:
      - name: echo-input
        value: ""
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737
    privileged: false
  templates:
    - name: echo
      inputs:
        parameters:
          - name: echo-input
      script:
        image: alpine:latest
        command:
          - sh
        source: |-
          echo "{{inputs.parameters.echo-input}}
```
