### ISSUE TITLE
Expression of format asInt(inputs.parameters["my-int-param"]) do not work

### ISSUE THREAD

**Issue by amitm02** [argoproj/argo-workflows#5957]
Variable expression of format `asInt(inputs.parameters["my-int-param"])`, as appears in the docs do not work.
Formats of format `asInt(inputs.parameters['count-count'])` do work.

Argo V3.1-rc5

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-sequence-
spec:
  entrypoint: loops-sequence
  arguments:
    parameters:
    - name: count-count
      value: "3"
  templates:
  - name: loops-sequence
    inputs:
      parameters:
        - name: count-count
    steps:
    # Example with a count
    - - name: sequence-count
        template: echo
        arguments:
          parameters:
          - name: msg
            value: "{{item}}"
        withSequence:
          # count: "{{=asInt(inputs.parameters['count-count'])}}" #this works
          count: '{{=asInt(inputs.parameters["count-count"])}}' #invalid syntax
   
  - name: echo
    inputs:
      parameters:
      - name: msg
    container:
      image: alpine:latest
      command: [echo, "{{inputs.parameters.msg}}"]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
