### ISSUE TITLE
Support spaces in success/failure Condition

### ISSUE THREAD

**Issue by wreed4** [argoproj/argo-workflows#5958]
# Summary

success or failure condition should be able to express something like 
```
successCondition: status.message = "My message here"
```

# Use Cases

I'm trying to use `resource` templates to test the status of `ExternalSecrets` https://github.com/external-secrets/kubernetes-external-secrets.  I want to validate that certain secrets fail to be provisioned.  The error they display in that case is `ERROR, Secrets Manager can't find the specified secret.`.  I'm trying to do something like 
```yaml
    resource:
      action: create
      setOwnerReference: true
      successCondition: "status.status == 'ERROR, Secrets Manager can't find the specified secret.'"
      manifest: |
        apiVersion: kubernetes-client.io/v1
        kind: ExternalSecret
        metadata:
          name: {{inputs.parameters.name}}
        spec:
          backendType: secretsManager
          roleArn: "{{inputs.parameters.roleArn}}"
          dataFrom:
          - {{inputs.parameters.dataFrom}}
```
Unsurprisingly I'm getting the following error: 
```
success condition 'status.status == 'ERROR, Missing credentials in config'' failed to parse: unable to parse requirement: invalid label value: "'ERROR": at key: "status.status": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

To get around this I need to return the status and write a whole separate template to validate that string.  Ideally I would be able to use the success/failureconditions instead. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
