### ISSUE TITLE
Step occasionally fails when render parameters in another parameter

### ISSUE THREAD

**Issue by andizzle** [argoproj/argo-workflows#5960]
## Summary 

What happened/what you expected to happen?
We have a special workflow that does the following steps:
1. extract a k8s manifest from configMap, the manifest has Argo parameters embedded. 
2. Submit the manifest to k8s

Here's a snippet of the manifest stored in k8s:
```yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: {{pod.name}}
  labels:
    app: ad-metrics-raw-to-bq-hourly
spec:
  type: Scala
  mode: cluster
  image: ad-events-to-bq:v1.1.0
  imagePullPolicy: Always
  sparkVersion: "2.4.5"
  timeToLiveSeconds: 10800
  arguments:
    - "{{inputs.parameters.startAt}}"
  restartPolicy:
    type: Never
```

This configMap is retrieved by a step like this and passed to the next step to be submitted to k8s:
```yaml
    - - name: load-ad-metrics-raw-to-bq-manifest
          template: load-configmap
          arguments:
              parameters:
                  - name: configMapName
                      value: ad-metrics-raw-to-bq-hourly-workflow
    - - name: ad-metrics-raw-to-bq
          template: execute
          arguments:
              parameters:
                  - name: manifest
                      value: >-
                          {{steps.load-ad-metrics-raw-to-bq-manifest.outputs.parameters.manifest}}
                  - name: startAt
                      value: '{{inputs.parameters.startAt}}'
                  - name: retryLimit
                      value: '0'
```

Where `load-configmap` is 
```yaml
name: load-configmap
arguments: {}
inputs:
    parameters:
        - name: configMapName
outputs:
    parameters:
        - name: manifest
            valueFrom:
                jsonPath: '{.data.manifest}'
        - name: imageTag
            valueFrom:
                jsonPath: '{.data.imageTag}'
metadata: {}
resource:
    action: get
    manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
            name: {{inputs.parameters.configMapName}}
    flags:
        - '--namespace={{workflow.namespace}}'
```

and `execute` is
```yaml
name: execute
arguments: {}
inputs:
    parameters:
        - name: manifest
        - name: startAt
        - name: retryLimit
            default: '3'
        - name: semaphore
            default: other
outputs: {}
metadata:
    annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
resource:
    action: create
    manifest: |
        {{inputs.parameters.manifest}}
    successCondition: status.applicationState.state = COMPLETED
    failureCondition: 'status.applicationState.state in (FAILED, SUBMISSION_FAILED)'
    flags:
        - '--namespace={{workflow.namespace}}'
retryStrategy:
    limit: '{{inputs.parameters.retryLimit}}'
    retryPolicy: Always
synchronization:
    semaphore:
        configMapKeyRef:
            name: ad-metrics-pipeline-synchronization
            key: '{{inputs.parameters.semaphore}}'
            optional: true
```

While this works most of the time, Argo occasionally throws this error at the `execute` step
```
error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"pod.name":interface {}(nil)}
```

Interestingly the rendered manifests looks correct, the job was able to carry out successfully, but Argo would consider the step failed due this this error in the MESSAGE section.

## Diagnostics

What Kubernetes provider are you using?
In house k8s 1.14

What version of Argo Workflows are you running? 
v2.12.6

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
