### ISSUE TITLE
Support for configmaps in `withItems` and `withParam` of loops

### ISSUE THREAD

**Issue by joyciep** [argoproj/argo-workflows#5978]
# Summary

What change needs making?

Add a way to reference values from configmaps in `withItems` / `withParam` in loops. Something like

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  templates:
  - name: loop-example
    steps:
    - - name: print-message
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems:              # invoke whalesay once for each item in parallel
          configMapKeyRef:
            name: my-config
            key: tables

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

```
apiVersion: v1
kind: ConfigMap
metadata:
 name: my-config
data:
  tables:
  - table1
  - table2
  - table3
```

# Use Cases

When would you use this?

My usecase is to reuse an existing configmap used by other deployments and I can easily change the configuration across my workflows and deployments.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by shuangkun** [comment]
Is it possible to add a field “withItemsRef”

```
        withItemsRef:             
          configMapKeyRef:
            name: my-config
            key: tables
```
