### ISSUE TITLE
Default auth mode is not set to "server"

### ISSUE THREAD

**Issue by yoichiwo7** [argoproj/argo-workflows#5995]
## Summary 

After updating Argo Workflow from v3.0 to v3.1-rc7, we were experiencing `"token not valid for running mode"` error when accessing argo-server's Web UI. This error always redirected us to Login page.

Although the following document indicates the default auth mode is set to `server`, it seems like the default auth mode is set to `client` and this behavior was causing the error. 
https://github.com/argoproj/argo-workflows/blob/v3.1.0-rc8/docs/argo-server-auth-mode.md

After explicitly setting the `--auth-mode` to `server` in the manifest, the auth mode is set to `server` and works without error. (NOTE: we were also setting `--secure=false` option to disable TLS)

```yaml
# Snippet of the argo-server manifest
    spec:
      containers:
      - name: argo-server
        image: docker.io/argoproj/argocli:v3.1.0-rc8
        args:
        - server
        - "--secure=false"
        # Need to add auth-mode setting explicitly.
        - "--auth-mode=server"
```

If the document is correct, default auth mode must be set to `server` when `--auth-mode` option isn't set.

## Diagnostics

What Kubernetes provider are you using? 
-> Kubernetes v1.16

What version of Argo Workflows are you running? 
-> Argo Workflow v3.1.0-rc7, v3.1.0-rc8

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
-> K8sAPI

Did this work in a previous version? I.e. is it a regression?
-> Worked as expected in Argo Workflow v3.0.2. Possible regression.

argo-server's startup log: Without `--auth-mode` option, **authModes is set to ["client"]**.
```
level=info authModes="[client]" baseHRef=/ managedNamespace= namespace=argo secure=false
level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo-workflows/tls/"                                                                   level=info msg="config map" name=workflow-controller-configmap
level=info msg="SSO disabled"
level=info msg="Starting Argo Server" instanceID= version=v3.1.0-rc8
level=info msg="Creating DB session"
level=info msg="Node status offloading config" ttl=5m0s
level=info msg="Creating event controller" operationQueueSize=16 workerCount=4
level=info msg="Argo Server started successfully on http://localhost:2746"
```

argo-server's error log:
```
level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-05-25T06:57:04Z" grpc.time_ms=0.114 span.kind=server system=grp
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
