### ISSUE TITLE
ResourcesDurations do not include daemon steps

### ISSUE THREAD

**Issue by withnale** [argoproj/argo-workflows#5997]
## Summary 

The ResourcesDuration metrics should count the number of cpu and memory units used by a workflow. At present, these
ignore any steps which are marked as `daemon: true`.

## Diagnostics

This occurs on GKE running 1.19.x using argo-workflows v3.0.3

With the workflow included below, if you run the same workflow with the `cpu` parameter set to `low` the same resource metrics are obtained when the parameter is set to `high`. In the first case, the cpu request/limits are set to '1' and in the second they are set to '7'.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: resources-
spec:
  entrypoint: steps
  serviceAccountName: dataload
  arguments:
    parameters:
      - name: cpu
        value: "low"
  templates:
  - name: steps
    steps:
    - - name: daemon-low
        when: "{{workflow.parameters.cpu}} == low"
        template: daemon-low
      - name: daemon-high
        when: "{{workflow.parameters.cpu}} == high"
        template: daemon-high
    - - name: main
        template: main

  - name: daemon-low
    daemon: true
    container:
      resources:
        limits:
          cpu: '1'
        requests:
          cpu: '1'
      image: docker/whalesay
      command: [sh, -c]
      args: ["sleep 6000000"]

  - name: daemon-high
    daemon: true
    container:
      resources:
        limits:
          cpu: '7'
        requests:
          cpu: '7'
      image: docker/whalesay
      command: [sh, -c]
      args: ["sleep 6000000"]


  - name: main
    container:
      image: docker/whalesay
      command: [sh, -c]
      args: ["sleep 240"] 
```

I have not included the full step output (I can if you wish), but the node definition for the daemon step looks like this:

```yaml
    resources-jzhwv-3659598309:
      boundaryID: resources-jzhwv
      children:
      - resources-jzhwv-3314606353
      displayName: daemon-high
      finishedAt: "2021-05-25T10:31:32Z"
      hostNodeName: gke-lynx-main-d205400f-1m2b
      id: resources-jzhwv-3659598309
      name: resources-jzhwv[0].daemon-high
      phase: Succeeded
      podIP: 172.28.141.27
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
      startedAt: "2021-05-25T10:31:22Z"
      templateName: daemon-high
      templateScope: local/resources-jzhwv
      type: Pod
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
