### ISSUE TITLE
failed to resolve {{workflow.parameters}}

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#6036]
Trying to submit the following template

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello
spec:
  templates:
    - name: hello-main
      steps:
        - - name: hello
            template: hello-hello
    - name: hello-hello
      container:
        image: 'alpine:latest'
        command:
          - /bin/sh
        args:
          - '-c'
          - 'echo main step of hello {{workflow.parameters}}'
  entrypoint: hello-main
```
 
Gives the error :

`Unsuccessful HTTP response: templates.hello-main.steps[0].hello templates.hello-hello: failed to resolve {{workflow.parameters}}`

Using latest image of both server and controller

Base don https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md#global, it is supposed to be a global var available everywhere

Anything wrong on my side or bug ?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
