### ISSUE TITLE
"argo template lint" errors on missing arguments

### ISSUE THREAD

**Issue by atombender** [argoproj/argo-workflows#6044]
Here's what happens:

```sh
$ argo template lint ./k8s/environments/staging/wftmpl-webhooks.yaml
./k8s/environments/staging/wftmpl-webhooks.yaml:
   ✖ in "webhooks" (WorkflowTemplate): spec.arguments.commit.value is required
```

My workflow template starts with this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: webhooks
spec:
  arguments:
    parameters:
    - name: commit
```

First of all, there's no flag to pass parameters to the linter to make it pass.

Second of all, how does that error make any sense? The arguments to the template doesn't matter to linting. Those arguments can be anything at runtime, so they cannot possibly be linted.

Is `argo template lint` intended for some other use case than linting workflow templates?

```sh
$ argo version
argo: v3.0.7+e79e7cc.dirty
  BuildDate: 2021-05-26T00:43:44Z
  GitCommit: e79e7ccda747fa4487bf889142c744457c26e9f7
  GitTreeState: dirty
  GitTag: v3.0.7
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
