### ISSUE TITLE
PodGC OnPodCompletion strategy does not work in 3.1-rc10

### ISSUE THREAD

**Issue by amitm02** [argoproj/argo-workflows#6051]
## Summary 

While running the workflow below, the completed pods sequence-kldp5-3397304079 and sequence-kldp5-808541759 are not removed by OnPodCompletion strategy.

Runnign on V3.1-rc10, Emissary, GKE

```
> k get pods
NAME                                   READY   STATUS      RESTARTS   AGE
argo-server-6767f6f858-fmnvp           1/1     Running     3          29h
minio-9464498c9-gtgkt                  1/1     Running     0          7d4h
postgres-bb76cd4b7-5jpkg               1/1     Running     0          3d17h
sequence-kldp5-3397304079              0/2     Completed   0          7m49s
sequence-kldp5-808541759               0/4     Completed   0          7m49s
workflow-controller-6b698f496d-rhxdh   1/1     Running     8          29h
```

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sequence-
  labels:
    workflows.argoproj.io/container-runtime-executor: emissary
spec:
  entrypoint: entry
  podGC:
    strategy: OnPodCompletion
    # strategy: OnPodSuccess
  templates:
    - name: entry
      steps:
        - - name: container-set
            template: container-set
          - name: regular-container
            template: regular-container
        - - name: approve
            template: approve

    - name: container-set
      containerSet:
        containers:
          - name: a
            image: argoproj/argosay:v2
          - name: b
            image: argoproj/argosay:v2
            dependencies:
              - a
          - name: c
            image: argoproj/argosay:v2
            dependencies:
              - b
    
    - name: regular-container
      container:
        image: docker/whalesay
        command: [cowsay]

    - name: approve
      suspend: {}


```
[wf.yaml.txt](https://github.com/argoproj/argo-workflows/files/6570084/wf.yaml.txt)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
