### ISSUE TITLE
schema.json expects retryStrategy.limit to be string only

### ISSUE THREAD

**Issue by yanp** [argoproj/argo-workflows#6060]
## Summary 

What happened/what you expected to happen?

Latest `schema.json` complains that the `retryStrategy.limit` field can only be type string:
![image](https://user-images.githubusercontent.com/5286182/120403167-8856cd00-c2f8-11eb-8f83-d20bb20be38a.png)

I expect it to accept integer.

## Diagnostics

What version of Argo Workflows are you running?

`v3.1.0-rc11`

Did this work in a previous version? I.e. is it a regression?

Yes, it works with `v2.12` versioned schema. It happened since `v3.0`

Workflow spec to reproduce:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      retryStrategy:
        limit: 10

      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["hello world"]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
