### ISSUE TITLE
using a different bucket of an artifact repository in different steps/tasks ?

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#6077]
## Summary 

at the moment, you can crate a ConfigMap named artifact-repositories with multiple repositories

then, inside each workflow, you can specify the repo to use with artifactRepositoryRef

let's assume you need step1 to read from the bucket1 and to write to bucket2

in this case, you need to choose one of the 2 repos as a "default" (and to repeat the repository info into the other one)

It all comes down to the fact that the "bucket" is ignored when you specify artifactRepositoryRef

```
kind: Workflow
metadata:
  generateName: input-artifact-s3-
spec:
  artifactRepositoryRef: repo1
  entrypoint: input-artifact-s3-example
  templates:
  - name: input-artifact-s3-example
    inputs:
      artifacts:
      - name: my-art
        path: /my-artifact
        s3:
          bucket: my-other-bucket #here, this should "override" the bucket configured in repo1
          key: path/in/bucket
    container:
      image: debian:latest
      command: [sh, -c]
      args: ["ls -l /my-artifact"]
```

Of course, in the example, I could use repo2 (which would be configured to my-other-bucket) but the point is to have another template that is using my-bucket.

Of course (and this is what I am doing right now), I can repeat the whole s3 config inline but the point is to have the configuration of repositories stored in configmaps

is this a bug or by design ? 

See #6065 to extend the problem to multiple repositories

do not hesitate to ask me more details

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
