### ISSUE TITLE
cannot get {{workflow.failures}} when many pods fail

### ISSUE THREAD

**Issue by rzsquirrel** [argoproj/argo-workflows#6093]
## Summary 

What happened/what you expected to happen?

We expect {{workflow.failures}} to get us failure info, which is especially useful when we have many failing pods. However, we've noticed that as the number of pods reaches ~800, it's possible that the content from from {{workflow.failures}} is too large, causing the following error.
`Pod "test-many-failures-ctxc2-2007524166" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`
I've seen these errors before, typically for parameters that are too large. This is something we can avoid by using artifacts, but there doesn't seem to be any way to take in {{workflow.failures}} since referencing it in the template alone is enough to cause this error. (See included example.) It'd be nice if we could at least take it as input from an artifact.

## Diagnostics

The following example recreates the error on Argo 3.0.7. It spins up 1000 failing pods and then attempts to reference {{workflow.failures}} in its exit handler.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-many-failures-
  labels:
    workflows.argoproj.io/container-runtime-executor: pns
spec:
  entrypoint: loops-sequence
  onExit: exit-handler
  artifactRepositoryRef:
    configMap: workflow-controller-configmap
    key: artifactRepository
  arguments:
    parameters:
    - name: count
      value: 1000
  
  templates:
  - name: loops-sequence
    serviceAccountName: argo-workflow-watcher
    steps:
    - - name: sequence-with-a-really-long-name-to-replicate-memory-limit-error-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        template: intentional-fail
        withSequence:
          count: "{{workflow.parameters.count}}"

  - name: intentional-fail
    serviceAccountName: argo-workflow-watcher
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]
  
  - name: save-workflow-failures
    serviceAccountName: argo-workflow-watcher
    outputs:
      artifacts:
        - name: workflow-failures
          path: /tmp/workflow-failures.txt
    script:
      image: python:alpine3.8
      command: [python]
      source: |
        import time
        workflow_failures = '''{{workflow.failures}}'''
        with open('/tmp/workflow-failures.txt', 'w') as f:
            # we'd like to save workflow failure info w/ the code below, but the error is reproducible w/o it
            # f.write(workflow_failures)
            f.write('hello')
        time.sleep(5)  # necessary for PNS executor to collect artifact

  - name: exit-handler
    dag:
      tasks:
      - name: save-failures
        template: save-workflow-failures

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
