### ISSUE TITLE
Mutex in DAG caused a panic and prevented the exit-handler from running

### ISSUE THREAD

**Issue by ChaosInTheCRD** [argoproj/argo-workflows#6103]
## Summary 

*Note: I have not managed to reproduce/isolate the issue, but I would like this to be the start of my contribution / involvement with the Argo Workflows community. I have spent the last few days looking at the codebase, and hope that I am getting closer to becoming valuable for contribution. If anyone from the Argo team would like to collaborate with me on this issue (if it is a problem that is recurring), that would be awesome.*

Upon implementing a mutex in a template that was referred to in a DAG step, e.g.
```
- name: update-crd-step
   depends: "run-tests-step.Succeeded"
   template: update-crd
   when: "{{tasks.run-tests-step.outputs.parameters.test-status}} == Passed"
...
- name: update-crd
    synchronization:
      mutex:
         name: crd-updating
    inputs:
      artifacts:
      - name: example-artifact
         path: /etc/example.json
...

```

The workflows (there were multiple that experienced the issue) that kicked off refused to start the `exit-handler` configured in the workflow, upon the moment that the workflow failed (the workflow failing is not related to this bug).
upon inspection of the workflow-controller pod logs, the following stacktrace was found:

```
runtime error: invalid memory address or nil pointer dereference\" 
  stack=\"goroutine 300 [running]:
runtime/debug.Stack(0xc09f9dc242, 0x180bdc0, 0x29f3e30)
	/usr/local/go/src/runtime/debug/stack.go:24 
  +0x9d
github.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).operate.func2(0xc0025cac00)
	/go/src/github.com/argoproj/argo/workflow/controller/operator.go:184 
  +0xbe
panic(0x180bdc0, 0x29f3e30)
	/usr/local/go/src/runtime/panic.go:679 
  +0x1b2
github.com/argoproj/argo/v2/pkg/apis/workflow/v1alpha1.(*SynchronizationStatus).GetStatus(...)
	/go/src/github.com/argoproj/argo/pkg/apis/workflow/v1alpha1/workflow_types.go:2600
github.com/argoproj/argo/v2/workflow/sync.(*Manager).Release(0xc02e2a6680, 0xc00223d800, 0xc031f2ef60, 0x24, 0xc048085000)
	/go/src/github.com/argoproj/argo/workflow/sync/sync_manager.go:161 
  +0x31d
github.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc0025cac00, 0xc03568e460, 0xc052c2a1a0, 0x16)
	/go/src/github.com/argoproj/argo/workflow/controller/dag.go:337 
  +0x1fce
github.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).executeDAG(0xc0025cac00, 0xc032c24540, 0x38, 0xc04dcc35c0, 0xc030ee8480, 0x21, 0xc002748c80, 0x1cbc740, 0xc002725a20, 0xc002826f50, ...)
	/go/src/github.com/argoproj/argo/workflow/controller/dag.go:240 
  +0x2e9
github.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).executeTemplate(0xc0025cac00, 0xc032c24540, 0x38, 0x1cbc740, 0xc002725a20, 0xc066e7ddc0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1733 +0x20e4
github.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc0025cac00, 0xc002725970, 0x1, 0x4, 0xc030ee8240, 0x21, 0xc002828478, 0x0)
	/go/src/github.com/argoproj/argo/workflow/controller/steps.go:240 
  +0x1185
github.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).executeSteps(0xc0025cac00, 0xc057b14580, 0x1e, 0xc066e7ddc0, 0xc030ee8180, 0x21, 0xc002748280, 0x1cbc740, 0xc002724e70, 0xc0025f5660, ...)
	/go/src/github.com/argoproj/argo/workflow/controller/steps.go:94 
  +0x4bc
github.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).executeTemplate(0xc0025cac00, 0xc057b14580, 0x1e, 0x1cbc740, 0xc002724e70, 0xc066e7dd80, 0xc00e51ef00, 0x1, 0x1, 0x0, ...)
	/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1727 
  +0x2050
github.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).operate(0xc0025cac00)
	/go/src/github.com/argoproj/argo/workflow/controller/operator.go:338 
  +0xd3e
github.com/argoproj/argo/v2/workflow/controller.(*WorkflowController).processNextItem(0xc00047f500, 0x0)
	/go/src/github.com/argoproj/argo/workflow/controller/controller.go:574 
  +0x828
github.com/argoproj/argo/v2/workflow/controller.(*WorkflowController).runWorker(0xc00047f500)
	/go/src/github.com/argoproj/argo/workflow/controller/controller.go:496 
  +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc02ea02720)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:152 
  +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc02ea02720, 0x3b9aca00, 0x0, 0x1570401, 0xc0001c28a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:153 
  +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc02ea02720, 0x3b9aca00, 0xc0001c28a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:88 
  +0x4d
created by github.com/argoproj/argo/v2/workflow/controller.(*WorkflowController).Run
	/go/src/github.com/argoproj/argo/workflow/controller/controller.go:215 
  +0xa5d
```

## Diagnostics

What Kubernetes provider are you using? 
Google GKE - `v1.19.9-gke.1400`

What version of Argo Workflows are you running? 
`v2.12.8` - I am aware that at least 1 bug fix for mutexes has been put in place since this version. However, I have not managed to reproduce this issue outside of the environment that is experiencing the issue, and wanted to ensure that this is a problem that the community is aware of.

Furthermore, I am trying to become comfortable with the codebase so I can contribute. For this reason, I would love to be part of the fix if this is still a bug in the latest version, but also fully understand what the problem was if it has been patched.

Did this work in a previous version? I.e. is it a regression?
the bug only arose upon adding this mutex to the particular step in the workflow

Are you pasting thousands of log lines? That's too much information. 
I have tried to narrow in on the logs related to the incident. They are in a gist (below), so that should be good if an engineer wishes to take a closer look.

https://gist.github.com/ChaosInTheCRD/7ab356eba323a47a460167a879c13cb1

I tried to reproduce the bug in an isolated environment (non-production), but was not successful.

---

**Message from the maintainers**:
Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@ChaosInTheCRD Can you provide the reproducible workflow?

**Comment by sarabala1979** [comment]
It looks like `synchronization` in workflow status is nil.  Please provide the live workflow YAML and controller logs. I can guide you to fix this issue.

**Comment by ChaosInTheCRD** [comment]
> @ChaosInTheCRD Can you provide the reproducible workflow?

```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: dumb-test-execution
spec:
  serviceAccountName: argo
  entrypoint: execute-tests
  onExit: exit-cleanup
  templates:
  - name: execute-tests
    dag:
      tasks:
      - name: get-resources-step
        template: get-resources
      - name: download-step
        template: download
      - name: deploy-step
        template: deploy
        # Why deploy/build GKE when the platform failed, or PFT is Locked?
        depends: "download-step && get-resources-step.Succeeded"
      - name: build-yaml-step
        template: build-yaml
        depends: "get-resources-step"
      - name: build-test-step
        template: build-platform-test-yaml
        depends: "get-resources-step"
      - name: build-addons-step
        template: build-addons
        depends: "get-resources-step"
      - name: apply-yaml-step
        template: apply-yaml
        depends: "build-yaml-step && build-addons-step && deploy-step"
      - name: wait-step
        depends: "apply-yaml-step"
        template: wait
      - name: run-tests-step
        depends: "wait-step && build-test-step"
        template: run-tests
      - name: update-crd-step
        depends: "run-tests-step.Succeeded"
        template: update-crd
      - name: notification-step
        depends: "run-tests-step"
        template: notification-failed
      - name: report-error
        template: report-error
        # If we manage to get the lock (get-resources-step) but if any other step fails
        # then we should run this to set the platformtest as Errored.
        depends: "get-resources-step && (deploy-step.Failed || download-step.Failed || run-tests-step.Failed || wait-step.Failed || apply-yaml-step.Failed || build-yaml-step.Failed || build-addons-step.Failed  || build-test-step.Failed)"

  - name: exit-cleanup
    steps:
      - - name: cleanup-services
          template: cleanup-services
          continueOn:
            error: true
            failed: true
        - name: capture-persistent-volumes
          template: capture-persistent-volumes
          continueOn:
            error: true
            failed: true
      - - name: destroy-step
          template: destroy-deploy
      - - name: cleanup-workspace
          template: cleanup-workspace
        - name: cleanup-disks
          template: cleanup-disks

  - name: get-resources
    script:
      image: bitnami/kubectl:1.17.9
      command: [bash]
      source: |
        set -euo pipefail
        echo "fetching resources"
  - name: download
    activeDeadlineSeconds: 300
    retryStrategy:
      limit: 4 # Retry at least twice incase of GH Connectivity issues or terraform module download failure
    script:
      image: bitnami/kubectl:1.17.9
      command: [sh]
      source: |
        echo "downloading"
  - name: deploy
    activeDeadlineSeconds: 5400 # 1.5 Hours or fail. (Credentials are limited to 1 hour - 30 minutes extra for startup/module install etc.)
    script:
      image: bitnami/kubectl:1.17.9
      command: [sh]
      source: |
        echo "deploy..."
  - name: cleanup-workspace
    script:
      image: bitnami/kubectl:1.17.9
      command: [sh]
      source: |
        echo "cleaned up workspace"
  - name: build-yaml
    activeDeadlineSeconds: 600
    retryStrategy:
      limit: 3
    container:
      image: bitnami/kubectl:1.17.9
      command: ["/bin/sh", "-c"]
      args:
      - echo "let's build some yaml"

  - name: build-addons
    retryStrategy:
      limit: 2 # Retry at least twice in case of GH Connectivity issues.
    script:
      image: bitnami/kubectl:1.17.9
      command: [bash]
      source: |
        set -euo pipefail
        echo "another step..."

  - name: build-platform-test-yaml
    activeDeadlineSeconds: 600
    retryStrategy:
      limit: 3
    container:
      image: bitnami/kubectl:1.17.9
      command: ["/bin/sh", "-c"]
      args:
      - echo "hello world"

  - name: apply-yaml
    retryStrategy:
      limit: 5 # Due to some of the CRD's being applied at the same time as objects, kubectl can fail for various timing issues.
    script:
      image: bitnami/kubectl:1.17.9
      command: ["bash"]
      source: |
        set -euo pipefail
        echo "apply yamls..."
        exit 1;
  - name: wait
    activeDeadlineSeconds: 1500 # 25 Minutes or Timeout
    script:
      image: bitnami/kubectl:1.17.9
      command: ["bash"]
      source: |
        set -euo pipefail
        echo "wait until it's running..."
  - name: run-tests
    activeDeadlineSeconds: 18000 # 5 Hours or Timeout
    script:
      image: bitnami/kubectl:1.17.9
      command: [bash]
      source: |
        echo "This is meant to execute some tests..."
  - name: update-crd
    # See mutex here
    synchronization:
      mutex:
        name: platform-stream-crd-update
    script:
      image: bitnami/kubectl:1.17.9
      command: [bash]
      source: |
        set -euo pipefail   
        echo "this is the step with the problem..."
          
  - name: report-error
    script:
      image: bitnami/kubectl:1.17.9
      command: [bash]
      source: |
        # We're not root, so we can't use apt to install things, but we need jq.
        echo "aarggghhhh, we failed!"
  - name: cleanup-services
    script:
      image: bitnami/kubectl:1.17.9
      command: ["bash"]
      source: |
        set -euo pipefail
        echo "cleanup resources"
  - name: capture-persistent-volumes
    script:
      image: bitnami/kubectl:1.17.9
      command: ["bash"]
      source: |
        set -euo pipefail
        echo "delete the volumes"
  - name: destroy-deploy
    script:
      image: bitnami/kubectl:1.17.9
      command: [sh]
      source: |
        echo "destroy clusters"
  - name: cleanup-disks
    script:
      image: bitnami/kubectl:1.17.9
      command: ["bash"]
      source: |
        set -euo pipefail
        echo "Disk Cleanup Complete."
  - name: notification-failed
    script:
      image: bitnami/kubectl:1.17.9
      command: ["bash"]
      source: |-
        echo "No Notification"
```

**Comment by ChaosInTheCRD** [comment]
the funny thing is... it doesn't get close to the point where mutex exists before failing... So I am not sure why it is entering into any of the `synchronization` logic

**Comment by sarabala1979** [comment]
Got the issue. Let me create a reproducible workflow and give it to you for a fix.  Looks like DAG is. updating the status for the unrun task which has mutex. Code is trying to release the mutex for that template.

**Comment by sarabala1979** [comment]
@ChaosInTheCRD I am able to reproduce panic with below workflow. Please try on your environment
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  templates:
    - name: hello-hello-hello
      steps:
        - - name: hello1
            template: diamond
    - name: diamond
      dag:
        tasks:
          - name: A
            template: error
            arguments:
              parameters: [{name: message, value: A}]
          - name: B
            depends: "A.Succeeded"
            template: acquire-lock-1
            arguments:
              parameters: [{name: message, value: B}]
          - name: c
            template: echo
            arguments:
              parameters: [{name: message, value: B}]
          
    - name: error
      retryStrategy:
        limit: 3
      container:
        image: python:alpine3.6
        command: ["python", -c]
        # fail with a 66% probability
        args: ["import random; import sys; exit_code = random.choice([1, 1, 1]); sys.exit(exit_code)"]
        
    - name: acquire-lock-1
      synchronization:
        mutex:
          name: test
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["sleep 50; echo acquired lock"]
    - name: echo
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"it was tails\""]
```
The fix is DAG is checking `node.Fulfilled()` for completion the `node` for releasing the mutex which includes `skipped`. The skipped node didn't acquire the lock so the controller won't populate the `synchronization` in `status`. Here fix in dag.go
https://github.com/argoproj/argo-workflows/blob/1d76c4815704e509d7aedc1a79224fbee65ae8ff/workflow/controller/dag.go#L339
```go
		// Release acquired lock completed task.
		if tmpl != nil && node.Completed() {
			woc.controller.syncManager.Release(woc.wf, node.ID, tmpl.Synchronization)
		}
```
Please go-ahead to fix this issue and include the test.
