### ISSUE TITLE
WorkflowEventBinding breaks the parameter which contains double quotes by json marshal

### ISSUE THREAD

**Issue by ckyoog** [argoproj/argo-workflows#6107]
## Summary 

I believe this issue is a side-effect of #4594 (#4572). A call to json marshal was added by #4594 to encode workflow parameter into a json string. It works well for most situations, but there is an exception -- when the parameter is a simple string and contains double quotes. E.g., given the parameter name is "pname", and a string value 'a"b"c' is going to be passed to it. The reproducing steps are shown below.

## Diagnostics

I am using argo-3.0.7, however, since #4594 was merged before 2.12.0, so I believe every argo version later than 2.12 is impacted by this issue.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflowtemplate-test
spec:
  serviceAccountName: my-sa
  entrypoint: Complete
  activeDeadlineSeconds: 3600
  arguments:
    parameters:
    - name: pname
      value: ""
  templates:
    - name: Complete
      container:
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: [sh, -c]
        args: ["echo '{{workflow.parameters.pname}}' Complete; exit 0"]
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: workfloweventbinding-test
spec:
  event:
    selector: all([payload.pname], {# not in ["", nil]})
  submit:
    workflowTemplateRef:
      name: workflowtemplate-test
    arguments:
      parameters:
      - name: pname
        valueFrom:
          event: payload.pname
```

Let's submit a workflow with `pname` being set to `a"b"c`.

It's no problem if submitting the workflow with argo cli, as follows
```bash
argo -n my-ns submit --from workflowtemplate/workflowtemplate-test -p pname="a\"b\"c"

# the logs of the workflow pod would be
a"b"c Complete
```
But if submitting it with curl (through WorkflowEventBinding), the result is not right.
```bash
curl http://<argo-server>:2746/api/v1/events/my-ns/ -d '{"pname": "a\"b\"c"}'

# the logs would be
a\"b\"c Complete
```
If you check the two workflow with `kubectl get -o yaml`, here is the difference as you can find.
```diff
 spec:
   arguments:
     parameters:
     - name: pname
-      value: a"b"c
+      value: a\"b\"c
```
Although I passed the same value to `pname`, the two resultant workflows have different value for `pname`, and the one whose value is `a\"b\"c` is wrong, and it is created via `curl` method (through WorkflowEventBinding).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
