### ISSUE TITLE
resource is not removed when argo cli delete workflow

### ISSUE THREAD

**Issue by 2qif49lt** [argoproj/argo-workflows#6108]
## Summary 

```
templates:
  - name: main
    dag:
      tasks:
      - name: create-project-env
        template: create-project-env
      - name: pull
        dependencies: [create-project-env]
        template: pull
      - name: import
        dependencies: [pull]
        template: import
       ......
  - name: create-project-env
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: project-env
        data:
          SCHE_PROJ_NAME: {{ workflow.parameters.project }}
          ...
```

i think configmap should be deleted as well.

```
std@master:/data/samba/std/aes-argo$ argo delete aes-g7ddm
Workflow 'aes-g7ddm' deleted
std@master:/data/samba/std/aes-argo$ kubectl get cm -n argo
NAME                            DATA   AGE
artifact-repositories           1      17h
conf                            1      18h
project-env                     4      9m7s
static-env                      8      18h
workflow-controller-configmap   0      17h

```
