### ISSUE TITLE
`Pod was active on the node longer than the specified deadline`: wrong `finishedAt`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6135]
When a workflow fails with `Pod was active on the node longer than the specified deadline`, the `finishedAt` time of the node does not appear to correct.

It should be the the latest finishedAt time of the container status, but it appears that under these circumstances, this is not actually set when the pod failed:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: main
  activeDeadlineSeconds: 5
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2
        args:
          - sleep
          - 10s
...
      hello-world-79hgg:
        displayName: hello-world-79hgg
        finishedAt: "2021-06-11T18:17:12Z"
        hostNodeName: docker-desktop
        id: hello-world-79hgg
        message: Pod was active on the node longer than the specified deadline
        name: hello-world-79hgg
        phase: Failed
        progress: 1/1
        resourcesDuration:
          cpu: 0
          memory: 0
        startedAt: "2021-06-11T18:17:07Z"
```

Pod status:

```yaml
status:
  containerStatuses:
  - containerID: docker://7d9e12d03722ad2667917ae73113151ebab2bea4390199b62ebbe98c71734508
    image: argoproj/argosay:v2
    imageID: docker-pullable://argoproj/argosay@sha256:f0b51e5d3a394af492de5ae50af93f11ba0862480d0eb2cbb48286fe58745303
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: "2021-06-11T18:03:30Z"
  - containerID: docker://39e372213d68da12f555c69f656f4508993e674a253d2df101ffa0845c517ff9
    image: argoproj/argoexec:latest
    imageID: docker://sha256:9d44141038c156bd4f0e6c719d95a25aa7cf11ecb83e52e5deb632a28a15311a
    lastState: {}
    name: wait
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: "2021-06-11T18:03:30Z"
  message: Pod was active on the node longer than the specified deadline
  phase: Failed
  podIP: 10.1.11.176
  podIPs:
  - ip: 10.1.11.176
  qosClass: Burstable
  reason: DeadlineExceeded
  startTime: "2021-06-11T18:03:27Z"
```
