### ISSUE TITLE
archiveLogs is storing empty main.log files

### ISSUE THREAD

**Issue by steve-marmalade** [argoproj/argo-workflows#6145]
## Summary 

The workflow logs that appear on the Argo Server UI are not persisted to the `main.log` that is stored in the artifact repository when `archiveLogs: true`.

## Diagnostics

What Kubernetes provider are you using? 

**GKE on GCP, version `1.20.6-gke.1000`**

What version of Argo Workflows are you running? 

**v3.1.0-rc11**

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

**Emissary**

Did this work in a previous version? I.e. is it a regression?

**I am not sure (I didn't test it)**

Steps to reproduce:

Relevant excerpt of `workflow-controller-configmap`
```
kubectl -n argo get configmap workflow-controller-configmap -o yaml
apiVersion: v1
data:
  artifactRepository: |
    archiveLogs: true
    gcs:
      bucket: my-argo-bucket
      key: logs
  containerRuntimeExecutor: emissary
```

Submit the `hello-world` workflow
```
argo submit -n argo --watch https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/hello-world.yaml
```

Logs show in the Argo Server UI
<img width="1080" alt="Screen Shot 2021-06-14 at 6 19 57 PM" src="https://user-images.githubusercontent.com/85196623/121967815-07a7c000-cd3f-11eb-954f-c8d61220fe84.png">

`main.log` stored in GCS is 0 bytes :(

<img width="986" alt="Screen Shot 2021-06-14 at 6 25 45 PM" src="https://user-images.githubusercontent.com/85196623/121967808-05456600-cd3f-11eb-9f4f-e61e15dbcd0d.png">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
