### ISSUE TITLE
Docker logs command in argo wait container gets stuck when multiple processed are writing to stdout at a rapid rate.

### ISSUE THREAD

**Issue by boarder7395** [argoproj/argo-workflows#6153]
## Summary 

What happened/what you expected to happen?

When running a script with multiple processes that are writing to STDOUT the docker logs command in the argo wait container gets stuck in a bad state and never completes. When I manually kill the docker logs command the container completes successfully.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

AWS EKS

What version of Argo Workflows are you running? 

2.5

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Docker

Did this work in a previous version? I.e. is it a regression?

I have not tested previous versions of argo but my guess is it existed in previous versions as well.

Workflow.yaml

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifactpassing-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.1.1, pipelines.kubeflow.org/pipeline_compilation_time: '2021-05-24T15:08:28.852388',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Pipeline to test speed
      of artifact passing.", "inputs": [{"default": "200000", "name": "logs", "optional":
      true, "type": "String"}], "name": "ArtifactPassing"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.1.1}
spec:
  entrypoint: artifactpassing
  templates:
  - name: artifactpassing
    inputs:
      parameters:
      - {name: logs}
    dag:
      tasks:
      - name: generatelogs
        template: generatelogs
        arguments:
          parameters:
          - {name: logs, value: '{{inputs.parameters.logs}}'}
  - name: generatelogs
    container:
      args: [/opt/generate_excessive_logs.py, --n-logs, '{{inputs.parameters.logs}}']
      command: [python]
      env:
      - {name: WORKFLOWID, value: '{{workflow.uid}}'}
      image: 473391520281.dkr.ecr.us-east-1.amazonaws.com/mltp_playground/master/sample:logs_0.0.9
    inputs:
      parameters:
      - {name: logs}
    nodeSelector: {instanceType: m5.xlarge, tenant: claimalarms, procurement: ondemand}
    tolerations:
    - {effect: NoSchedule, key: tenant, operator: Equal, value: claimalarms}
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": ["/opt/generate_excessive_logs.py", "--n-logs", {"inputValue":
          "logs"}], "command": ["python"], "image": "473391520281.dkr.ecr.us-east-1.amazonaws.com/mltp_playground/master/sample:logs_0.0.9"}},
          "inputs": [{"name": "logs", "type": "String"}], "name": "GenerateLogs"}',
        pipelines.kubeflow.org/component_ref: '{"digest": "79696d4383ddda2e5ec46feb5c5455a160ec3fce8793774d682911d0246abcca",
          "url": "generate.yaml"}', pipelines.kubeflow.org/arguments.parameters: '{"logs":
          "{{inputs.parameters.logs}}"}'}
  arguments:
    parameters:
    - {name: logs, value: '200000'}
  serviceAccountName: pipeline-runner
```

Dockerfile for Image: 473391520281.dkr.ecr.us-east-1.amazonaws.com/mltp_playground/master/sample:logs_0.0.9

```
FROM ubuntu:18.04

COPY generate_excessive_logs.py /opt/generate_excessive_logs.py
```

generate_excessive_logs.py
```python
import argparse

import logging
import logging.handlers
import multiprocessing

from random import choice, random
import time


def listener_configurer():
    root = logging.getLogger()
    h = logging.StreamHandler()
    f = logging.Formatter('%(asctime)s %(processName)-10s %(name)s %(levelname)-8s %(message)s')
    h.setFormatter(f)
    root.addHandler(h)


def handle_command_line():
    parser = argparse.ArgumentParser()
    parser.add_argument('--n-logs', type=int, required=True, help='Number of logs to print.')
    return parser.parse_args()


def listener_process(queue, configurer):
    configurer()
    while True:
        try:
            record = queue.get()
            if record is None:
                break
            logger = logging.getLogger(record.name)
            logger.handle(record)
        except Exception:
            import sys, traceback
            print('Whoops! Problem:', file=sys.stderr)
            traceback.print_exc(file=sys.stderr)


LEVELS = [logging.DEBUG, logging.INFO, logging.WARNING,
          logging.ERROR, logging.CRITICAL]

LOGGERS = ['a.b.c', 'd.e.f', 'd.e.f', 'g.h.i', 'j.k.l']

MESSAGES = [
    'Random message #1',
    'Random message #2',
    'Random message #3',
    'Random message #4',
    'Random message #5',
]


def worker_configurer(queue):
    h = logging.handlers.QueueHandler(queue)
    root = logging.getLogger()
    root.addHandler(h)
    root.setLevel(logging.DEBUG)


def worker_process(queue, configurer):
    configurer(queue)
    name = multiprocessing.current_process().name
    print('Worker started: %s' % name)
    for i in range(100):
        time.sleep(random())
        logger = logging.getLogger(choice(LOGGERS))
        level = choice(LEVELS)
        message = choice(MESSAGES)
        logger.log(level, message)
    print('Worker finished: %s' % name)


def main():
    queue = multiprocessing.Queue(-1)
    listener = multiprocessing.Process(target=listener_process,
                                       args=(queue, listener_configurer))
    listener.start()
    workers = []
    for i in range(96):
        worker = multiprocessing.Process(target=worker_process,
                                         args=(queue, worker_configurer))
        workers.append(worker)
        worker.start()
    for w in workers:
        w.join()
    queue.put_nowait(None)
    listener.join()

if __name__ == '__main__':
    main()
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
