### ISSUE TITLE
Groups are not working with okta sso integration

### ISSUE THREAD

**Issue by nmyalik** [argoproj/argo-workflows#6165]
## Summary 
We're running Argo Workflows with SSO and RBAC enabled. We're using Okta as the OIDC provider.

Our service-account, which pointed to RoleBinding:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-user
  annotations:
    workflows.argoproj.io/rbac-rule: "'admins' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
```
Our config-map: 
```
data:
  config: |
    sso:
      clientID:
        key: clientID
        name: argo-secret
      clientSecret:
        key: clientSecret
        name: argo-secret
      issuer: https://<out_okta_url>
      name: Okta
      rbac:
        enabled: true
      redirectUrl: https://<our_argo_url>/oauth2/callback
      scopes:
      - groups
      - email
```

When we try to set a rule for the email `email endsWith '@ourdomain.com'`, rbac works as expected and with groups in doesn't work.
And we have `okta.groups.read` granted in Okta app. 

Expected behaviour that groups rules to work for okta.

## Diagnostics
We are using EKS.
Argo Workflows v3.0.7.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Do the groups appear correctly in the user info page?

**Comment by nmyalik** [comment]
nope, we have `Groups: -`

**Comment by alexec** [comment]
This means that OKTA is not returning groups to Argo Workflows. Can you speak to them to find out if you need some special configuration?

**Comment by blairham** [comment]
@alexec I can assure you that Okta is returning groups, we have many other OKTA <-> OICD apps including ArgoCD set up the same way which are working. I'm looking to see if there is any data that I can provide to help

**Comment by blairham** [comment]
one difference in configuration between ArgoCD and Argo Workflows we identified was: **requestedIDTokenClaims**
```
requestedScopes: ["openid", "profile", "email", "groups"]
requestedIDTokenClaims: {"groups": {"essential": true}}
```

**Comment by alexec** [comment]
Argo CD puts Dex between it and the SSO provider (e.g. OKTA), and is needed when the OAuth implementation is non-standard, e.g. Github. This may be needed here too.

**Comment by blairham** [comment]
Are you sure? we're using this configuration: https://argoproj.github.io/argo-cd/operator-manual/user-management/okta/#oidc-without-dex

**Comment by alexec** [comment]
Thats' the Argo CD manual and I don't think would apply to Argo Workflows. This is used by our demo environment to connect to Github:

https://github.com/argoproj/argoproj-deployments/tree/master/dex

**Comment by blairham** [comment]
@alexec If I may, I think there might be a wire crossed, replay this. 

> Argo CD puts Dex between it and the SSO provider (e.g. OKTA), and is needed when the OAuth implementation is non-standard, e.g. Github. This may be needed here too.

Are you sure? we're are using this configuration (for ArgoCD as we do no not use dex in our configuration): https://argoproj.github.io/argo-cd/operator-manual/user-management/okta/#oidc-without-dex

Is it your statement that OKTA OIDC is a non-standard OIDC provider? If that is the case, I'm a little confused as to how ArgoCD is able to work with it. We also have several other OIDC integrations with OKTA that do work as well.

Maybe I'm missing something or miss understanding something. Any corrections are welcom

**Comment by blairham** [comment]
And going back to what I mentioned, I think the issues is that Argo is not correctly getting the groupsClaim

**Comment by blairham** [comment]
Because we use [Loft](https://loft.sh) and can also be an [OIDC](https://loft.sh/docs/guides/oidc) provider we have set that up to unblock us from using Argo Workflows. However, we would really like to have it directly connected to OKTA so that we're not reliant on another product for Argo Workflows to work.

**Comment by blairham** [comment]
@alexec, do you think it has anything to do with this?
```
time="2021-06-19T19:40:20.062Z" level=info msg="SSO configuration" clientId="{{okta-sso-secret} client-id <nil>}" issuer="https://<out_okta_url>" redirectUrl="https://<our_argo_url>/oauth2/callback" scopes="[groups email profile opened]"
```
I noticed that the subjectID is some random string and not would I would expect to see, which should, in this case, be the email address.

This is the clientId and clientSecret configuration:
```
clientId:
  key: client-id
  name: okta-sso-secret
clientSecret:
  key: client-secret
  name: okta-sso-secret
  ```

**Comment by alexec** [comment]
That’s what I also thought, but it is wrong. Subject  are typically opaque strings, not email addresses. 

The only scope you need is “groups”. This code is proven with other providers, so my assumption is what is OKTA is doing differently?

**Comment by blairham** [comment]
I was reading through the ArgoCD docs and came across this:
https://argoproj.github.io/argo-cd/operator-manual/user-management/#requesting-additional-id-token-claims

**Comment by blairham** [comment]
you can always create a free okta developer account to work with the code too: https://developer.okta.com/signup/

**Comment by michael132** [comment]
I think this could be related to this?
https://github.com/argoproj/argo-workflows/issues/5953

**Comment by blairham** [comment]
> I think this could be related to this?
> #5953

@michael132 quiet possible. I'm assuming you're using one of those OIDC providers listed?

**Comment by gageorsburn** [comment]
I think the following is why the groups claim is missing:

https://support.okta.com/help/s/article/Okta-Groups-or-Attribute-Missing-from-Id-Token?language=en_US

# Cause
Id token when returned along with access token, is considered Thin Token. Thin id token only carries base claims and some scope dependent claims. Profile attributes (even if profile scope is passed) and groups are skipped (even if groups scope is passed in authorize request). Examples, of when id token and access token are returned together. 

- Implicit flow, where response_type=id_token+token
- Authorization code flow, where openid scope is passed in authorize request
- Resource owner password flow, where openid scope is passed in token request

Note: When id token is returned only (without access token), for example in implicit flow where response_type = id_token, the id token returned is considered Fat Token and should contain all profile attributes if profile scope is passed and groups, if groups scope is passed. 

# Resolution
Since in this case the access token is returned along with id token, the access token can be used to get all user claims (all profile attributes and groups, if profile and groups scopes are passed). 

The Access token can be sent as a bearer token in the authorization header of userinfo request i.e. POST ${baseUrl}/oauth2/v1/userinfo, where base url will be https://{yoursubdomain}.okta.com or https://{yoursubdomain}.okta.com

**Comment by gageorsburn** [comment]
@alexec I could probably give this a go on my free time. Do you have any thoughts around implementation before I start since this change can't affect the existing sso integrations?

**Comment by gageorsburn** [comment]
```
diff --git a/server/auth/sso/sso.go b/server/auth/sso/sso.go
index ef01455f..3140c4dd 100644
--- a/server/auth/sso/sso.go
+++ b/server/auth/sso/sso.go
@@ -54,6 +54,7 @@ type sso struct {
 	rbacConfig      *rbac.Config
 	expiry          time.Duration
 	customClaimName string
+	userInfoPath    string
 }
 
 func (s *sso) IsRBACEnabled() bool {
@@ -71,6 +72,7 @@ type Config struct {
 	SessionExpiry metav1.Duration `json:"sessionExpiry,omitempty"`
 	// customGroupClaimName will override the groups claim name
 	CustomGroupClaimName string `json:"customGroupClaimName,omitempty"`
+	UserInfoPath         string `json:"userInfoPath,omitempty"`
 }
 
 func (c Config) GetSessionExpiry() time.Duration {
@@ -188,6 +190,7 @@ func newSso(
 		rbacConfig:      c.RBAC,
 		expiry:          c.GetSessionExpiry(),
 		customClaimName: c.CustomGroupClaimName,
+		userInfoPath:    c.UserInfoPath,
 	}, nil
 }
 
@@ -260,6 +263,19 @@ func (s *sso) HandleCallback(w http.ResponseWriter, r *http.Request) {
 		}
 	}
 
+	// Some SSO implementations (Okta) require a call to
+	// the OIDC user info path to get attributes like groups
+	if s.userInfoPath != "" {
+		groups, err = c.GetUserInfoGroups(oauth2Token.AccessToken, c.Issuer, s.userInfoPath)
+		if err != nil {
+			w.WriteHeader(401)
+			_, _ = w.Write([]byte(fmt.Sprintf("failed to get groups claim: %v", err)))
+			return
+		}
+	}
+
+	log.Printf("GROUPS: %+v", groups)
+
 	argoClaims := &types.Claims{
 		Claims: jwt.Claims{
 			Issuer:  issuer,
diff --git a/server/auth/types/claims.go b/server/auth/types/claims.go
index 6b6ac568..05149446 100644
--- a/server/auth/types/claims.go
+++ b/server/auth/types/claims.go
@@ -3,6 +3,7 @@ package types
 import (
 	"encoding/json"
 	"fmt"
+	"net/http"
 
 	"gopkg.in/square/go-jose.v2/jwt"
 )
@@ -16,6 +17,10 @@ type Claims struct {
 	RawClaim           map[string]interface{} `json:"-"`
 }
 
+type UserInfo struct {
+	Groups []string `json:"groups"`
+}
+
 // UnmarshalJSON is a custom Unmarshal that overwrites
 // json.Unmarshal to mash every claim into a custom map
 func (c *Claims) UnmarshalJSON(data []byte) error {
@@ -62,3 +67,29 @@ func (c *Claims) GetCustomGroup(customKeyName string) ([]string, error) {
 
 	return newSlice, nil
 }
+
+func (c *Claims) GetUserInfoGroups(accessToken, issuer, userInfoPath string) ([]string, error) {
+	url := fmt.Sprintf("%s%s", issuer, userInfoPath)
+	request, _ := http.NewRequest("GET", url, nil)
+
+	bearer := fmt.Sprintf("Bearer %s", accessToken)
+	request.Header.Set("Authorization", bearer)
+
+	client := &http.Client{}
+	response, err := client.Do(request)
+
+	if err != nil {
+		return nil, err
+	}
+
+	userInfo := UserInfo{}
+
+	defer response.Body.Close()
+	err = json.NewDecoder(response.Body).Decode(&userInfo)
+
+	if err != nil {
+		return nil, err
+	}
+
+	return userInfo.Groups, nil
+}
```

I've verified this patch works with Okta 🥳 ... as long as you all agree with the approach I can submit a formal pull request and write tests.

**Comment by alexec** [comment]
One thought. Isn’t the path to user info in the “well known” endpoint? Other, we’d love to see a PR!

**Comment by gageorsburn** [comment]
@alexec It does, however once again Okta is different....

For example the well known address for google is:
https://accounts.google.com/.well-known/openid-configuration

However the well known address for Okta is:
https://subdomain.okta.com/oauth2/v1/.well-known/openid-configuration

I don't think the endpoint provides the .well-known url does it?

**Comment by alexec** [comment]
I can’t open that second link, but presumably it does not show the user info endpoint. I suggest that if the endpoint cannot be found in the “well known” config, that it defaults to a convention, a convention that happens to work for OKTA.

**Comment by alexec** [comment]
As usual, I’m pushing for the simplest and most frugal solution.

**Comment by blairham** [comment]
Just thought I would post back to this topic since I've been following it as it was opened by one of my team members. This still does not work with Okta as described with Argo Workflows and still only works with ArgoCD. I haven't had the time to dig in myself but this still looks like this has to do with:

`requestedIDTokenClaims: {"groups": {"essential": true}}`

As described here: https://connect2id.com/products/server/docs/guides/requesting-openid-claims#claims-parameter

**Comment by prein** [comment]
Apologies for piggy backing on a closed issue, but I can't get SSO in Argo Workflows to work with Okta. No groups show up in the user info. It always fallbacks to default service account. Can I find a working example for Okta somewhere?

**Comment by newb1e** [comment]
@prein 
I was able to get it working by setting `Groups claim filter` to `.*` in the Okta group settings.
![image](https://user-images.githubusercontent.com/5286697/146935110-b0f4b956-cb1d-49da-aced-2ca58488f16b.png)

**Comment by prein** [comment]
Thanks @newb1e I've updated the claim filter following your (and apparently, this is what official docs recommend too) recommendation. Previously it was left with default value - "None". I wonder what difference it makes. Anyway, still doesn't work for me.

**Comment by pravinjec** [comment]
I am trying to implement rbac on the user through okta groups on argo workflow UI, so created groups on okta side also customgroupclaim is like if any group starts with okta*, also added groups in scopes as below, but after that what all configuration required I am not able to see anywhere like role and rolebinding things to give types of permission to users in the group. Can any one please help

Using argo workflow version v3.6.2

Note: Currently the group that has created on okta side for this app, those user have all the permissions so to restrict them we need this task to be completed.

```
# -- SSO configuration
  sso:
    enabled: true
    issuer: "${sso_issuer}"
    clientId:
      # -- Name of secret to retrieve the app OIDC client ID
      name: ${argo_server_sso_secret_name}
      # -- Key of secret to retrieve the app OIDC client ID
      key: client-id
    clientSecret:
      # -- Name of a secret to retrieve the app OIDC client secret
      name: ${argo_server_sso_secret_name}
      # -- Key of a secret to retrieve the app OIDC client secret
      key: client-secret
    redirectUrl: "${sso_redirect_url}"
    ## If omitted, defaults to 10h.
    sessionExpiry: ""
    insecureSkipVerify: false
    rbac:
      enabled: true
      secretWhitelist: []
    scopes:
      - groups
    sessionExpiry: ""
    issuerAlias: ""
    customGroupClaimName: ""
    userInfoPath: ""
    insecureSkipVerify: false
    filterGroupsRegex: []

```

@newb1e
