### ISSUE TITLE
DAG not properly showing second branch in master

### ISSUE THREAD

**Issue by LarryFinn** [argoproj/argo-workflows#6172]
## Summary 

I noticed a workflow that works fine off a release does not work off master.  The second "mat" branch never shows in the ui and the workflow gets stuck

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using?  minikube

What version of Argo Workflows are you running? master [e7808afd3f99843626aa5ea4a5fb84bcc85737d9]

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary K8SAPI

Did this work in a previous version? I.e. is it a regression? Yes it did worok
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ingest-pipeline-cdw-
spec:
  entrypoint: ingest-task
  arguments:
    parameters:
    - name: job_name
      value: all_the_data
  templates:
    - name: ingest-task
      dag:
        tasks:
        - name: ing
          template: ingest-collections
          dependencies: [sent]
        - name: mat
          template: materializations
          dependencies: [sent]
        - name: sent
          template: sentinel
          arguments:
            parameters:
              - name: job_name
                value: '{{workflow.parameters.job_name}}'
    - name: sentinel
      inputs:
        parameters:
          - name: job_name
      container:
        name: ''
        image: 'alpine:3.13.5'
        command:
          - sh
          - '-c'
        args:
          - 'sleep 30; date; echo got sentinel for {{inputs.parameters.job_name}}'
        resources: {}
   
    - name: ingest-collections
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: get-ingest-collections
            template: get-ingest-collections
        - - name: ingest-collection
            template: ingest-collection
            arguments:
              parameters:
                - name: collection_name
                  value: "{{item.name}}"
            withParam: "{{steps.get-ingest-collections.outputs.result}}"
    - name: get-ingest-collections
      inputs: {}
      outputs: {}
      metadata: {}
      script:
        name: ''
        image: 'python:alpine3.6'
        command:
          - python
        resources: {}
        source: |
          import json
          import sys

          json.dump([{"name":"CollectionMeow"},{"name":"CollectionWoof"}, {"name": "CollectionMoo"}, {"name": "CollectionBleat"}], sys.stdout)
    - name: ingest-collection
      inputs:
        parameters:
          - name: collection_name
      outputs: {}
      metadata: {}
      steps:
        - - name: run-ingest-source
            template: run-ingest-source
            arguments:
              parameters:
                - name: collection_name
                  value: '{{inputs.parameters.collection_name}}'
        - - name: run-ingest-collection
            template: run-ingest-collection
            arguments:
              parameters:
                - name: collection_name
                  value: '{{inputs.parameters.collection_name}}'
    - name: run-ingest-collection
      inputs:
        parameters:
          - name: collection_name
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'alpine:3.13.5'
        command:
          - sh
          - '-c'
        args:
          - 'echo ran collection {{inputs.parameters.collection_name}}'
        resources: {}
    - name: run-ingest-source
      inputs:
        parameters:
          - name: collection_name
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'alpine:3.13.5'
        command:
          - sh
          - '-c'
        args:
          - 'sleep 30; date; echo ran source {{inputs.parameters.collection_name}}'
        resources: {}




    - name: materializations
      steps:
        - - name: get-materializations
            template: get-materializations
        - - name: materialize
            template: materialize
            arguments:
              parameters:
                - name: collection_name
                  value: '{{item.name}}'
            withParam: '{{steps.get-materializations.outputs.result}}'
    - name: get-materializations
      inputs: {}
      outputs: {}
      metadata: {}
      script:
        name: ''
        image: 'python:alpine3.6'
        command:
          - python
        resources: {}
        source: |
          import json
          import sys

          json.dump([{"name":"MaterializePoop"},{"name":"MaterializePee"}], sys.stdout)
    - name: materialize
      inputs:
        parameters:
          - name: collection_name
      steps:
        - - name: ingest-collection
            template: ingest-collection
            arguments:
              parameters:
                - name: collection_name
                  value: '{{inputs.parameters.collection_name}}'
        - - name: run-materialization
            template: run-materialization
            arguments:
              parameters:
                - name: collection_name
                  value: '{{inputs.parameters.collection_name}}'
    - name: run-materialization
      retryStrategy:
        limit: "3"
      inputs:
        parameters:
          - name: collection_name
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'alpine:3.13.5'
        command:
          - sh
          - '-c'
        args:
          - 'echo materialized collection {{inputs.parameters.collection_name}}'
          # - 'echo FAILED materialized collection {{inputs.parameters.collection_name}}; exit 1'
        resources: {}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
