### ISSUE TITLE
Lastest argoexec fail to parse template

### ISSUE THREAD

**Issue by zoftdev** [argoproj/argo-workflows#6194]
## Summary 

use argoproj/argoexec:latest (41c39cfdfaf3) linux/amd64

got error:
```
 k logs -f hlex-test-sqbsr-3511062045 init
time="2021-06-23T03:02:57.835Z" level=info msg="Starting Workflow Executor" executorType=k8sapi version=untagged
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.checkErr(0x2471d40, 0xc00027b480)
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/root.go:139 +0xf4
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.initExecutor(0x415227)
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/root.go:102 +0x5d0
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.loadArtifacts(0x24c56c0, 0xc000054028, 0x0, 0x0)
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/init.go:27 +0x65
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.NewInitCommand.func1(0xc000152b00, 0xc0005c2360, 0x0, 0x2)
```

Not error on  argoexec:v3.0.3-linux-amd64 and argoexec:v3.1.0-linux-amd64
 
## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
1.21

What version of Argo Workflows are you running? 
latest (41c39cfdfaf3) linux/amd64

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
K8SAPI
Did this work in a previous version? I.e. is it a regression?
3.1.0
Are you pasting thousands of log lines? That's too much information. 
no

```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
kubectl get wf -o yaml ${workflow}
`apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2021-06-23T03:05:19Z"
  generateName: hello-world-
  generation: 3
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Error
  name: hello-world-ljpvm
  namespace: provisioning
  resourceVersion: "1375228"
  uid: 5e70113e-9a04-47fb-a501-50c5579d9da1
spec:
  arguments: {}
  entrypoint: hello
  serviceAccountName: workflow-sa
  templates:
  - inputs: {}
    metadata: {}
    name: hello
    outputs: {}
    script:
      command:
      - /bin/bash
      image: registry.gitlab.com/nxcp/tools/cli-devtool:1.1.0
      imagePullPolicy: IfNotPresent
      name: ""
      resources: {}
      source: echo -e "Hello"
status:
  artifactRepositoryRef:
    default: true
  conditions:
  - status: "False"
    type: PodRunning
  - status: "True"
    type: Completed
  finishedAt: "2021-06-23T03:05:29Z"
  message: 'Error (exit code 2): unexpected end of JSON input'
  nodes:
    hello-world-ljpvm:
      displayName: hello-world-ljpvm
      finishedAt: "2021-06-23T03:05:22Z"
      id: hello-world-ljpvm
      message: 'Error (exit code 2): unexpected end of JSON input'
      name: hello-world-ljpvm
      phase: Error
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
      startedAt: "2021-06-23T03:05:19Z"
      templateName: hello
      templateScope: local/hello-world-ljpvm
      type: Pod
  phase: Error
  progress: 1/1
  resourcesDuration:
    cpu: 0
    memory: 0
  startedAt: "2021-06-23T03:05:19Z"`

**Comment by sarabala1979** [comment]
@zoftdev Are you using the `workflowcontroller:latest` also?

**Comment by ognjen-it** [comment]
+1

**Comment by PacoDu** [comment]
I've encountered the same issue, this was due to the workflow controller using the `latest` version of argoexec. Pinning the image with v3.1.1 solved the issue.

The kustomize deployment should not set images to latest for tagged versions.

For reference here is how we fixed the issue:

`patch/workflow-controller-deployment.yaml`
```yaml
- op: replace
  path: /spec/template/spec/containers/0/args/3
  value:
    argoproj/argoexec:v3.1.1
```

`kustomization.yaml`
```yaml
resources:
- git@github.com:argoproj/argo-workflows.git/manifests/cluster-install?ref=v3.1.1

images:
- name: docker.io/argoproj/workflow-controller
  newTag: v3.1.1
- name: docker.io/argoproj/argocli
  newTag: v3.1.1

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: workflow-controller
    path: ./patch/workflow-controller-deployment.yaml
```
