### ISSUE TITLE
UI: Submission of empty parameter for workflow template passes 'undefined'

### ISSUE THREAD

**Issue by jowparks** [argoproj/argo-workflows#6204]
## Summary 

I made a workflow template that has a input param without a default value, the UI accepts the workflow and passes `undefined
:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  arguments:
    parameters:
      - name: message
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

```bash
workflow-template-submittable-nfw6k:  ___________
workflow-template-submittable-nfw6k: < undefined >
workflow-template-submittable-nfw6k:  -----------
workflow-template-submittable-nfw6k:     \
workflow-template-submittable-nfw6k:      \
workflow-template-submittable-nfw6k:       \
workflow-template-submittable-nfw6k:                     ##        .
workflow-template-submittable-nfw6k:               ## ## ##       ==
workflow-template-submittable-nfw6k:            ## ## ## ##      ===
workflow-template-submittable-nfw6k:        /""""""""""""""""___/ ===
workflow-template-submittable-nfw6k:   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
workflow-template-submittable-nfw6k:        \______ o          __/
workflow-template-submittable-nfw6k:         \    \        __/
workflow-template-submittable-nfw6k:           \____\______/

```
And when I submit through the UI I can submit without providing a value, on the backend

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
AWS EKS
What version of Argo Workflows are you running? 
v3.0.2
What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
K8SAPI
Did this work in a previous version? I.e. is it a regression?
N/A
Are you pasting thousands of log lines? That's too much information. 
-

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
