### ISSUE TITLE
Getting a resource object retrieve a string + the object

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#6213]
## Summary 

I have a step that fetch the entire workflow object (to make introspection in a further step).
```yaml
  - name: get-workflow-object
    outputs:
      parameters:
      - name: workflow-object
        valueFrom:
          jsonPath: '{.*}'
    resource:
      action: get
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          name: {{workflow.name}}
          namespace: my-namespace
```

When I check the output while running the workflow, I see:
```
argoproj.io/v1alpha1 Workflow {"creationTimestamp":"2021-06-23T13:06:30Z","generateName":"master-tests-workflow-latest-","generation":7,"labels":{"submit-from-ui":"true","workflows.argoproj.io/creator":"system-serviceaccount-argo-wf-development-argo-server","workflows.argoproj.io/phase":"Running","workflows.argoproj.io/workflow-template":"master-tests-workflow-latest"},"managedFields":[{"apiVersion":"argoproj.io/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":
...
```
The string "argoproj.io/v1alpha1 Workflow" shouldn't be there as it makes things difficult to use the object in a further step.

If my code is wrong or if there is another to achieve this without getting that string before the object, I would be happy to know how.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
Openshift
Client Version: 4.7.2
Server Version: 4.5.5
Kubernetes Version: v1.18.3+08c38ef

What version of Argo Workflows are you running? 
V3.0.1

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
PNS

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
