### ISSUE TITLE
New Workflow submission fails with invalid spec but succeeds to run on Retry

### ISSUE THREAD

**Issue by gnadaban** [argoproj/argo-workflows#6222]
## Summary 

When my Workflow is submitted initially, it fails with a validation error complaining that an input parameter is not specified.
The input parameter in question is an expression, and I have verified it is valid by disabling parts of the workflow and re-running it.

![image](https://user-images.githubusercontent.com/58954625/123359209-e0b96d00-d53a-11eb-8129-3d4a9af49377.png)

After the workflow initial submission fails, if I Retry the workflow it runs, which makes me think it's a validator error:

![image](https://user-images.githubusercontent.com/58954625/123359629-09d9fd80-d53b-11eb-86f3-47d99655dee5.png)

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using?
CAPZ

What version of Argo Workflows are you running?
v3.1.0

What executor are you running? 
K8SAPI

Did this work in a previous version?
No.

Are you pasting thousands of log lines? That's too much information. 

WF status snippet:
```yaml
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2021-06-25T14:10:42Z"
  message: 'invalid spec: templates.bootstrap-cluster.tasks.create-external-dns-identity-manifest
    templates.create-azureidentity-manifest inputs.parameters.namespace was not supplied'
  phase: Failed
  progress: 0/0
```

Workflow snippet showing relevant section
```yaml
      dag:
        tasks:

        # Redacted tasks due to Workflow size

        - arguments:
            parameters:
            - name: namepace
              value: external-dns-{{ tasks.get-sanitized-external-dns-namespace.outputs.parameters.result
                }}
            - name: identity-name
              value: '{{ tasks.create-external-dns-identity.outputs.parameters.identity-name
                }}'
            - name: identity-id
              value: '{{ tasks.create-external-dns-identity.outputs.parameters.identity-id
                }}'
            - name: identity-client-id
              value: '{{ tasks.create-external-dns-identity.outputs.parameters.identity-client-id
                }}'
          dependencies:
          - create-external-dns-identity
          - get-sanitized-external-dns-namespace
          name: create-external-dns-identity-manifest
          template: create-azureidentity-manifest
```

Workflow-Controller log snippet:
```
time="2021-06-25T14:07:41.211Z" level=info msg="node bootstrap-cluster finished: 2021-06-25 14:07:41.211106485 +0000 UTC" namespace=argo workflow=bootstrap-cluster
time="2021-06-25T14:07:41.211Z" level=info msg="Checking daemoned children of bootstrap-cluster" namespace=argo workflow=bootstrap-cluster
time="2021-06-25T14:07:41.211Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=bootstrap-cluster
time="2021-06-25T14:07:41.211Z" level=info msg="Marking workflow completed" namespace=argo workflow=bootstrap-cluster
time="2021-06-25T14:07:41.211Z" level=info msg="Checking daemoned children of " namespace=argo workflow=bootstrap-cluster
time="2021-06-25T14:07:41.293Z" level=info msg="Workflow update successful" namespace=argo phase=Error resourceVersion=202400 workflow=bootstrap-cluster
time="2021-06-25T14:07:41.317Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/bootstrap-cluster-317973652/labelPodCompleted
time="2021-06-25T14:10:35.691Z" level=info msg="Processing workflow" namespace=argo workflow=bootstrap-cluster
time="2021-06-25T14:10:35.766Z" level=info msg="Updated phase  -> Failed" namespace=argo workflow=bootstrap-cluster
time="2021-06-25T14:10:35.766Z" level=info msg="Updated message  -> invalid spec: templates.bootstrap-cluster.tasks.create-external-dns-identity-manifest templates.create-azureidentity-manifest inputs.parameters.namespace was not supplied" namespace=argo workflow=bootstrap-cluster
time="2021-06-25T14:10:35.766Z" level=info msg="Marking workflow completed" namespace=argo workflow=bootstrap-cluster
time="2021-06-25T14:10:35.766Z" level=error msg="Unable to set ExecWorkflow" error="templates.bootstrap-cluster.tasks.create-external-dns-identity-manifest templates.create-azureidentity-manifest inputs.parameters.namespace was not supplied" namespace=argo workflow=bootstrap-cluster
time="2021-06-25T14:10:35.766Z" level=info msg="Checking daemoned children of " namespace=argo workflow=bootstrap-cluster
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gnadaban** [comment]
@alexec : I have just confirms that this is also an issue with `v3.0.3`, even when specifying the namespace **statically**:

Manifest:
```yaml
    - name: create-external-dns-identity-manifest
      template: create-azureidentity-manifest
      arguments:
        parameters:
          - name: namepace
            value: external-dns
          - name: identity-name
            value: >-
              {{
              tasks.create-external-dns-identity.outputs.parameters.identity-name
              }}
          - name: identity-id
            value: >-
              {{
              tasks.create-external-dns-identity.outputs.parameters.identity-id
              }}
          - name: identity-client-id
            value: >-
              {{
              tasks.create-external-dns-identity.outputs.parameters.identity-client-id
              }}
      dependencies:
        - create-external-dns-identity
```

![image](https://user-images.githubusercontent.com/58954625/123554381-ae338e00-d74d-11eb-895e-d204c9d5e1fa.png)
