### ISSUE TITLE
Global output parameters cannot be changed in v3.1.0

### ISSUE THREAD

**Issue by samath117** [argoproj/argo-workflows#6226]
## Summary 

In v3.1.0, if a global output parameter is set by one step and changed by another, later step, the change is reflected in `argo watch` / `argo get` but is not reflected whenever the global output parameter is referenced in the workflow. This bug does not happen in v3.0.8 or earlier versions as far as I've tried.

## Reproduction Steps

Here's an example workflow:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: change-global-parameter-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:
    - - name: create-output-parameter
        template: global-parameter-setting
        arguments:
          parameters:
          - name: value
            value: foo
    - - name: update-output-parameter
        template: global-parameter-setting
        arguments:
          parameters:
          - name: value
            value: bar
    - - name: consume-output-parameter
        template: global-parameter-consumption

  - name: global-parameter-setting
    inputs:
      parameters:
      - name: value
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["exit 0"]
    outputs:
      parameters:
      - name: parameter
        value: "{{inputs.parameters.value}}"
        globalName: parameter

  - name: global-parameter-consumption
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["echo {{workflow.outputs.parameters.parameter}}"]
```

The global parameter named `parameter` is originally set to `foo`, then changed to `bar`, then consumed. So the logs should just say `bar`, but instead, in v3.1.0, here are the logs:
```
change-global-parameter-xcvzx-3848121739: foo
```
In v3.0.8, this all works correctly:
```
change-global-parameter-mrdpf-1364986955: bar
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
