### ISSUE TITLE
Step-level memoization cache key does not support expression template tags

### ISSUE THREAD

**Issue by steve-marmalade** [argoproj/argo-workflows#6227]
## Summary 

I used an expression template tag as the step-level memoization key, and the workflow threw an error.

```yaml
      memoize:
        maxAge: 24h
        key: "{{=sprig.replace(inputs.parameters.database-table, '.', '-')}}"
        cache:
          configMap:
            name: my-workflows
            key: my-step-name
```

Resulted in 

> invalid cache key: {{=sprig.replace(inputs.parameters.database-table, '.', '-')}}

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using?  **GKE**

What version of Argo Workflows are you running? **3.1**

What executor are you running? **Emissary**

Did this work in a previous version? I.e. is it a regression?  **I doubt it**

Are you pasting thousands of log lines? That's too much information. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
