### ISSUE TITLE
Workflows with daemon nodes never get status update

### ISSUE THREAD

**Issue by kobejn-jb** [argoproj/argo-workflows#6237]
## Summary 

If there is a daemon task/step in workflow then controller does not set status.conditions and status.finishedAt. When status.finishedAt is not set correctly TTL can't be applied and wf resource is not being deleted.

## Diagnostics

Kubernetes: EKS 1.18.9
Executor: Docker
Argo: v2.12.2

I believe problem is in condition !woc.hasDaemonNodes(), it suppose to wait until daemons are terminated but in practice it waits forever
```go
        switch phase {
        case wfv1.WorkflowSucceeded, wfv1.WorkflowFailed, wfv1.WorkflowError:
                // wait for all daemon nodes to get terminated before marking workflow completed
                if markCompleted && !woc.hasDaemonNodes() {
                        woc.log.Infof("Marking workflow completed")
                        woc.wf.Status.FinishedAt = metav1.Time{Time: time.Now().UTC()}
                        woc.globalParams[common.GlobalVarWorkflowDuration] = fmt.Sprintf("%f", woc.wf.Status.FinishedAt.Sub(woc.wf.Status.StartedAt.Time).Seconds())
                        if woc.wf.ObjectMeta.Labels == nil {
                                woc.wf.ObjectMeta.Labels = make(map[string]string)
                        }
                        woc.wf.ObjectMeta.Labels[common.LabelKeyCompleted] = "true"
                        woc.wf.Status.Conditions.UpsertCondition(wfv1.Condition{Status: metav1.ConditionTrue, Type: wfv1.ConditionTypeCompleted})
                        err := woc.deletePDBResource(ctx)
                        if err != nil {
                                woc.wf.Status.Phase = wfv1.WorkflowError
                                woc.wf.ObjectMeta.Labels[common.LabelKeyPhase] = string(wfv1.NodeError)
                                woc.updated = true
                                woc.wf.Status.Message = err.Error()
                        }
                        if woc.controller.wfArchive.IsEnabled() {
                                if woc.controller.isArchivable(woc.wf) {
                                        woc.log.Infof("Marking workflow as pending archiving")
                                        woc.wf.Labels[common.LabelKeyWorkflowArchivingStatus] = "Pending"
                                } else {
                                        woc.log.Infof("Doesn't match with archive label selector. Skipping Archive")
                                }
                        }
                        woc.updated = true
                }
        }
```
```yaml
Name:         speed-waste-xf4j9
Namespace:    argo
Labels:   app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=argo-scheduler
              app.kubernetes.io/version=1.16.0
              greensteam.com/workflow=speed-waste
              helm.sh/chart=argo-scheduler-0.1.0
              workflows.argoproj.io/controller-instanceid=argo-controller
              workflows.argoproj.io/phase=Succeeded
...
Status:
  Finished At:  <nil> # This section is not being updated
  Nodes:
    speed-waste-xf4j9:
      Children:
        speed-waste-xf4j9-2865081693
      Display Name:  speed-waste-xf4j9
      Finished At:   2021-06-26T02:55:31Z
      Id:            speed-waste-xf4j9
      Name:          speed-waste-xf4j9
      Outbound Nodes:
        speed-waste-xf4j9-2292792521
      Phase:     Succeeded
      Progress:  2/2
      Resources Duration:
        Cpu:           5401
        Memory:        181640
      Started At:      2021-06-26T02:05:47Z
      Template Name:   run-workflow
      Template Scope:  local/speed-waste-xf4j9
      Type:            Steps
 ...
    speed-waste-xf4j9-4228372220:
      Boundary ID:  speed-waste-xf4j9
      Children:
        speed-waste-xf4j9-1954747447
      Display Name:  prediction-server
      Finished At:   2021-06-26T02:09:27Z
      Id:            speed-waste-xf4j9-4228372220
      Name:          speed-waste-xf4j9[0].prediction-server
      Phase:         Succeeded
      Progress:      2/2
      Resources Duration:
        Cpu:           5401
        Memory:        181640
      Started At:      2021-06-26T02:05:47Z
      Template Name:   prediction-server
      Template Scope:  local/speed-waste-xf4j9
      Type:            Retry
  Phase:               Succeeded
  Progress:            2/2
  Resources Duration:
    Cpu:       5401
    Memory:    181640
  Started At:  2021-06-26T02:05:47Z
Events:        <none>

```
To reproduce you can use WF with daemon from examples:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: daemon-step-
spec:
  entrypoint: daemon-example
  templates:
  - name: daemon-example
    steps:
    - - name: influx
        template: influxdb              # start an influxdb as a daemon (see the influxdb template spec below)

    - - name: init-database             # initialize influxdb
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: curl -XPOST 'http://{{steps.influx.ip}}:8086/query' --data-urlencode "q=CREATE DATABASE mydb"

    - - name: producer-1                # add entries to influxdb
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: for i in $(seq 1 20); do curl -XPOST 'http://{{steps.influx.ip}}:8086/write?db=mydb' -d "cpu,host=server01,region=uswest load=$i" ; sleep .5 ; done
      - name: producer-2                # add entries to influxdb
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: for i in $(seq 1 20); do curl -XPOST 'http://{{steps.influx.ip}}:8086/write?db=mydb' -d "cpu,host=server02,region=uswest load=$((RANDOM % 100))" ; sleep .5 ; done
      - name: producer-3                # add entries to influxdb
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: curl -XPOST 'http://{{steps.influx.ip}}:8086/write?db=mydb' -d 'cpu,host=server03,region=useast load=15.4'

    - - name: consumer                  # consume intries from influxdb
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: curl --silent -G http://{{steps.influx.ip}}:8086/query?pretty=true --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM cpu"

  - name: influxdb
    daemon: true                        # start influxdb as a daemon
    retryStrategy:
      limit: 10                         # retry container if it fails
    container:
      image: influxdb:1.2
      readinessProbe:                   # wait for readinessProbe to succeed
        httpGet:
          path: /ping
          port: 8086

  - name: influxdb-client
    inputs:
      parameters:
      - name: cmd
    container:
      image: appropriate/curl:latest
      command: ["/bin/sh", "-c"]
      args: ["{{inputs.parameters.cmd}}"]
      resources:
        requests:
          memory: 32Mi
          cpu: 100m
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
