### ISSUE TITLE
[emissary] pod hangs running as non-root

### ISSUE THREAD

**Issue by Bobgy** [argoproj/argo-workflows#6238]
## Summary 

What happened/what you expected to happen?

I ran the following workflow with emissary executor:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: hw
  templates:
  - name: hw
    container:
      image: <any-image-that-defaults-to-non-root-user>
      command: [sh, -c, "echo hello"]
```

Result:
The pod hangs forever.
logs for main container: `standard_init_linux.go:211: exec user process caused "permission denied"`
main container errors and completes with this error message.
However, wait container keeps running forever.

Analysis:
because argoexec in /var/run/argo/argoexec is in a volume and not executable from non-root user as expected, somehow wait container cannot know argoexec failed to start because of permission issue.

Expected behavior:
I think the failure is expected, but it'll be drastically better user experience if argo could give a meaningful error message and do not hang forever.

Idea to improve:
let the wait container wait for a heartbeat signal from argoexec, if the signal is not heard for a configured time range (maybe 5min~10min, because we need to wait for pulling the image).
If the signal is not heard, exit early and say sth is wrong with argoexec.

## Context

I'm trying to upgrade KFP to argo v3.1 and switch to emissary executor: https://github.com/kubeflow/pipelines/pull/5922

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 
v3.1.0

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
emissary

Did this work in a previous version? I.e. is it a regression?
No, emissary is new, but it works with Docker executor before.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
