### ISSUE TITLE
mirrorVolumeMounts not working after upgrade to 3.1.0

### ISSUE THREAD

**Issue by stevenbressey** [argoproj/argo-workflows#6246]
## Summary 

After upgrading to v.3.1.0, workflows using the `mirrorVolumeMounts` in `initContainers` or `sidecars` attributes are not working as expected anymore.
I noticed that the pods started by the workflows do not mount the main container's volumes in sidecars or init containers anymore.
I did not see any error or warning in workflow controller logs.

## Diagnostics

What Kubernetes provider are you using? 
GKE 1.19

What version of Argo Workflows are you running? 
v3.1.0

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker

Did this work in a previous version? I.e. is it a regression?
This feature was working correctly in v3.0.1.

Example workflow template:

```yml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: workflow-with-mirror-volumes
spec:
  templates:
  - name: main
    inputs:
      parameters:
        - name: secret_name_ref
    steps:
    - - name: build
        template: build
        arguments:
          parameters:
            - name: secret_name_ref
              value: "{{inputs.parameters.secret_name_ref}}"

  - name: build
    inputs:
      parameters:
        - name: test
    volumes:
      - configMap:
          name: config
        name: config
      - secret:
          secretName: '{{inputs.parameters.secret_name_ref}}'
        name: build-args
      - emptyDir: { }
        name: credentials
      - emptyDir: { }
        name: log
    container:
      volumeMounts:
        - name: workspace
          mountPath: /workspace
        - mountPath: /root/creds/
          name: credentials
        - mountPath: /log
          name: log
        - mountPath: /workspace/build-args
          subPath: build-args
          name: build-args
      name: build
      image: build
      imagePullPolicy: Always
    sidecars:
      - image: fluentd
        name: fluent
        mirrorVolumeMounts: true
        volumeMounts:
          - name: conf
            mountPath: /fluentd/etc/
    initContainers:
      - name: creds
        image: creds
        imagePullPolicy: Always
        mirrorVolumeMounts: true
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you confirm if this works when creating a workflow directly rather than using a template? This will help us understand if the bug is in templates code or elsewhere.

**Comment by stevenbressey** [comment]
Just tried without using a template and it seems to work.
So the issue might be linked to templates indeed.
FYI, I'm also using a `volumeClaimTemplates` in my workflow, which is then supposed to be mounted in main and sidecar containers.

**Comment by stevenbressey** [comment]
@alexec Hi ! 
Just wanted to know if you had any update on this, as we are still stuck with version 3.0.1 for now because of this issue. 
If you need any more information or help investigating the issue, please let me know, I will gladly help.

**Comment by alexec** [comment]
This is with @sarabala1979 to prioritise.

**Comment by sarabala1979** [comment]
@stevenbressey I tried with the latest build. I can see the volumes are mounting on init and sidecar.  can you provide you pod yaml? Can you try with v3.1.2?
Here step I followed
create clusterworkflow template

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: workflow-with-mirror-volumes
spec:
  entrypoint: volumes-emptydir-example
  volumes:
    - name: workdir
      emptyDir: {}
  
  templates:
    - name: volumes-emptydir-example
      container:
        image: debian:latest
        command: ["/bin/bash", "-c"]
        args: ["
        vol_found=`mount | grep /mnt/vol` && \
        if [[ -n $vol_found ]]; then echo \"Volume mounted and found\"; else echo \"Not found\"; fi
      "]
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
      sidecars:
        - image: debian:latest
          name: fluent
          mirrorVolumeMounts: true
      initContainers:
        - name: creds
          image: debian:latest
          imagePullPolicy: Always
          mirrorVolumeMounts: true
```

pod yaml
```yaml
spec:
  containers:
  - command:
    - argoexec
    - wait
    - --loglevel
    - debug
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
      value: pns
    - name: GODEBUG
      value: x509ignoreCN=0
    - name: ARGO_CONTAINER_NAME
      value: wait
    - name: ARGO_TEMPLATE
      value: '{"name":"volumes-emptydir-example","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"debian:latest","command":["/bin/bash","-c"],"args":["
        vol_found=`mount | grep /mnt/vol` \u0026\u0026 if [[ -n $vol_found ]]; then
        echo \"Volume mounted and found\"; else echo \"Not found\"; fi "],"resources":{},"volumeMounts":[{"name":"workdir","mountPath":"/mnt/vol"}]},"initContainers":[{"name":"creds","image":"debian:latest","resources":{},"imagePullPolicy":"Always","mirrorVolumeMounts":true}],"sidecars":[{"name":"fluent","image":"debian:latest","resources":{},"mirrorVolumeMounts":true}]}'
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    image: argoproj/argoexec:agent
    imagePullPolicy: Never
    name: wait
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
        - SYS_CHROOT
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mainctrfs/mnt/vol
      name: workdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-pbw7w
      readOnly: true
  - args:
    - ' vol_found=`mount | grep /mnt/vol` && if [[ -n $vol_found ]]; then echo "Volume
      mounted and found"; else echo "Not found"; fi '
    command:
    - /bin/bash
    - -c
    env:
    - name: ARGO_CONTAINER_NAME
      value: main
    - name: ARGO_TEMPLATE
      value: '{"name":"volumes-emptydir-example","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"debian:latest","command":["/bin/bash","-c"],"args":["
        vol_found=`mount | grep /mnt/vol` \u0026\u0026 if [[ -n $vol_found ]]; then
        echo \"Volume mounted and found\"; else echo \"Not found\"; fi "],"resources":{},"volumeMounts":[{"name":"workdir","mountPath":"/mnt/vol"}]},"initContainers":[{"name":"creds","image":"debian:latest","resources":{},"imagePullPolicy":"Always","mirrorVolumeMounts":true}],"sidecars":[{"name":"fluent","image":"debian:latest","resources":{},"mirrorVolumeMounts":true}]}'
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    image: debian:latest
    imagePullPolicy: Always
    name: main
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/vol
      name: workdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-pbw7w
      readOnly: true
  - env:
    - name: ARGO_CONTAINER_NAME
      value: fluent
    - name: ARGO_TEMPLATE
      value: '{"name":"volumes-emptydir-example","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"debian:latest","command":["/bin/bash","-c"],"args":["
        vol_found=`mount | grep /mnt/vol` \u0026\u0026 if [[ -n $vol_found ]]; then
        echo \"Volume mounted and found\"; else echo \"Not found\"; fi "],"resources":{},"volumeMounts":[{"name":"workdir","mountPath":"/mnt/vol"}]},"initContainers":[{"name":"creds","image":"debian:latest","resources":{},"imagePullPolicy":"Always","mirrorVolumeMounts":true}],"sidecars":[{"name":"fluent","image":"debian:latest","resources":{},"mirrorVolumeMounts":true}]}'
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    image: debian:latest
    imagePullPolicy: Always
    name: fluent
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/vol
      name: workdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-pbw7w
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - env:
    - name: ARGO_CONTAINER_NAME
      value: creds
    - name: ARGO_TEMPLATE
      value: '{"name":"volumes-emptydir-example","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"debian:latest","command":["/bin/bash","-c"],"args":["
        vol_found=`mount | grep /mnt/vol` \u0026\u0026 if [[ -n $vol_found ]]; then
        echo \"Volume mounted and found\"; else echo \"Not found\"; fi "],"resources":{},"volumeMounts":[{"name":"workdir","mountPath":"/mnt/vol"}]},"initContainers":[{"name":"creds","image":"debian:latest","resources":{},"imagePullPolicy":"Always","mirrorVolumeMounts":true}],"sidecars":[{"name":"fluent","image":"debian:latest","resources":{},"mirrorVolumeMounts":true}]}'
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    image: debian:latest
    imagePullPolicy: Always
    name: creds
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/vol
      name: workdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-pbw7w
      readOnly: true
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: workdir
  - name: default-token-pbw7w
    secret:
      defaultMode: 420
      secretName: default-token-pbw7w
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-07-22T05:07:16Z"
    message: '0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/unreachable:
      }, that the pod didn''t tolerate.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```
