### ISSUE TITLE
Retry on different hosts does not work with complex template

### ISSUE THREAD

**Issue by goock** [argoproj/argo-workflows#6248]
## Summary 

I'm the author of the feature from https://github.com/argoproj/argo-workflows/pull/4679

The implementation works perfectly for a very simple workflow like this one:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: random-fail-
spec:
  entrypoint: random
  templates:
  - name: random
    retryStrategy:
      limit: 5
      retryPolicy: "Always"
      affinity:
        nodeAntiAffinity: {}
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        i = random.randint(0, 5)
        print(i)
        exit(i)
```

where `pod` type node is the child of the `retry` node.

However, it does not work for more complex templates like this one:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: random-fail-
spec:
  activeDeadlineSeconds: 36000
  arguments:
    parameters:
      - name: r
        value: "2"
  entrypoint: allrandom
  templates:
  - name: allrandom
    retryStrategy:
      limit: 5
      retryPolicy: "Always"
      affinity:
        nodeAntiAffinity: {}
    steps:
      - - name: random-1
          template: r1
          when: "{{workflow.parameters.r}} == 1"
        - name: random-2
          template: r2
          when: "{{workflow.parameters.r}} == 2"
  - name: r1
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        i = random.randint(0, 10)
        print(i)
        exit(i)
  - name: r2
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        i = random.randint(0, 10)
        print(i)
        exit(i)
```

where `retry` node does not have `pod` type node as a direct child.

I started already working on the fix. 

I replaced https://github.com/argoproj/argo-workflows/blob/43212590d4579c821280fd482b960934139eac2f/workflow/util/retry/retry.go#L10

with a function that finds all children and collects hostnames:

```
func GetFailHosts(nodes wfv1.Nodes, retryNodeName string) []string {
	toVisit := []string{retryNodeName}
	hostNames := []string{}
	for len(toVisit) > 0 {
		n := len(toVisit) - 1
		nodeToVisit := toVisit[n]
		toVisit = toVisit[:n]
		if x, ok := nodes[nodeToVisit]; ok {
			if (x.Phase == wfv1.NodeFailed || x.Phase == wfv1.NodeError) && x.Type == wfv1.NodeTypePod {
				hostNames = append(hostNames, x.HostNodeName)
			}
			for i := 0; i < len(x.Children); i++ {
				childNode := x.Children[i]
				if y, ok := nodes[childNode]; ok {
					toVisit = append(toVisit, y.ID)
				}
			}
		}
	}
	return RemoveDuplicates(hostNames)
}
```

Function https://github.com/argoproj/argo-workflows/blob/6167aaa0c4143021942d74e4906233853a557325/ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx#L25 also needs to be replaced.

I need some advice on how to hook correctly 
https://github.com/argoproj/argo-workflows/blob/6167aaa0c4143021942d74e4906233853a557325/workflow/controller/operator.go#L1697

This function is only called on `retry` node type but `Affinity` must be passed to all `pod` type children. For example, when https://github.com/argoproj/argo-workflows/blob/6167aaa0c4143021942d74e4906233853a557325/workflow/controller/operator.go#L1723 is called the `processedTmpl.Affinity` is always `nil`.

I already tried with a new field in https://github.com/argoproj/argo-workflows/blob/6167aaa0c4143021942d74e4906233853a557325/workflow/controller/controller.go#L66 that maps template names to affinities but maybe there is a simpler and more elegant way to do it.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
