### ISSUE TITLE
Adding Exit handler on step level -- for WorkflowTemplate

### ISSUE THREAD

**Issue by koffemaria2u** [argoproj/argo-workflows#6253]
## Summary 

What happened/what you expected to happen?
- When submitting a workflow/cronwf, `onExit` can be used on the step level when referencing a `container` as shown in this [example](https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/examples/template-on-exit.yaml#L22-L28). However, I have not been able to make it work when the exit handler calls a `WorkflowTemplate` or `ClusterWorkflowTemplate` on the step level.

- I expect this to execute:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: container-on-exit-
spec:
  timezone: UTC
  schedule: 00 11 * * *
  concurrencyPolicy: Forbid
  entrypoint: step-template
  workflowSpec:
    templates:
      - name: step-template
        steps:
        - - name: stepA
             onExit: exitContainer
             template: whalesay
        - - name: stepB
             onExit: exitContainer
             template: whalesay

      - name: whalesay
        container:
          image: docker/whalesay
          command: [cowsay]
          args: ["hello world"]
  
      - name: exitContainer
        steps:
        - - name: wf-goodbye
             templateRef:
                 clusterScope: true
                 name: cwft-goodbye
                 template: goodbye
             arguments:
                 parameters:
                 - name: foo
                   value: bar
            when: "{{workflow.status}} != Succeeded"
           - name: fail-report-slack
            templateRef:
                clusterScope: true
                name: cwft-slack-workflow-failure
                template: slack-workflow-failure
            when: "{{workflow.status}} != Succeeded"
```

- error logs:
```bash
# fail-report-slack error
FATA[2021-06-29T15:56:30.990Z] Failed to submit workflow: templates.exitContainer templates.exitContainer[0].fail-report-slack templates.slack-workflow-failure: failed to resolve {{workflow.failures}}

# wf-goodbye error
FATA[2021-06-29T18:30:28.515Z] Failed to submit workflow: templates.exit-handler templates.exit-handler.steps failed to resolve {{workflow.status}} 

```

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
- v1.21.1

What version of Argo Workflows are you running? 
- v3.0.0

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
- DOCKER

Did this work in a previous version? I.e. is it a regression?
- NO

Are you pasting thousands of log lines? That's too much information. 
- NO
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
