### ISSUE TITLE
malformed Dex configuration found - Workflows & ArgoCD authentication

### ISSUE THREAD

**Issue by jrowinski3d** [argoproj/argo-workflows#6261]
## Summary 

Configuring Argo-Workflows with Argo-CD(Dex) for authentication. Getting `malformed Dex configuration found` 

I expect it to not be malformed as I am following the docs here -> https://argoproj.github.io/argo-workflows/argo-server-sso-argocd/#example-helm-chart-configuration-for-authenticating-against-argocds-dex

## Diagnostics

What Kubernetes provider are you using? 
**Using helm charts to deploy both workflows and cd. Running on GKE v 1.19**

What version of Argo Workflows are you running?
`latest`

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
`Docker` **I believe is the default**

Did this work in a previous version? I.e. is it a regression?
**First time setting it up.**

Logs from dex server:

```bash
kubectl logs -f argo-cd-argocd-dex-server-5cdd486f58-bhjtq 
time="2021-06-30T19:23:21Z" level=info msg="Starting configmap/secret informers"
time="2021-06-30T19:23:21Z" level=info msg="Configmap/secret informer synced"
time="2021-06-30T19:23:21Z" level=info msg="0xc000876360 subscribed to settings updates"
time="2021-06-30T19:23:21Z" level=fatal msg="malformed Dex configuration found" 

```

**helm argo-cd values**

```bash
dex:
  image:
    tag: v2.27.0
  env:
    - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: argo-workflows-sso
          key: client-secret
server:
  config:
    dex.config: |
      staticClients:
      - id: argo-workflows-sso
        name: Argo Workflow
        redirectURIs:
          - https://argo-workflows.domain/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
  image:
    tag: v2.0.4
  ingress:
    enabled: true
    annotations:
      certmanager.k8s.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx-internal
    labels: {}
    ingressClassName: "nginx-internal"
```

**helm argo-workflows values**

```bash
workflow:
  namespace: argo-cd

server:
  extraArgs:
    - --auth-mode=sso
  sso:
    issuer: https://argo-cd.domain/api/dex
    # sessionExpiry defines how long your login is valid for in hours. (optional, default: 10h)
    sessionExpiry: 240h
    clientId:
      name: argo-workflows-sso
      key: client-id
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    redirectUrl: https://argo-workflows.domain/oauth2/callback
```

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@alexec can you comment on this?

**Comment by alexec** [comment]
@gdnlp - you wrote this guide, do have a suggestion?
@jrowinski3d  - if you can avoid Dex, we'd recommend, it adds complexity and failure points, and is often not needed if (like many) your OAuth2/OIDC provider is standard- compliant

**Comment by bgdnlp** [comment]
I wrote the Kustomize part, the helm charts and initial version were written by @hobbsh I believe. I have no idea why Dex would complain. I'd suggest checking the raw version of the config that ends up being loaded by Dex.

**Comment by jrowinski3d** [comment]
> @bgdnlp - you wrote this guide, do have a suggestion?
> @jrowinski3d - if you can avoid Dex, we'd recommend, it adds complexity and failure points, and is often not needed if (like many) your OAuth2/OIDC provider is standard- compliant

We have an instance of Okta internally and would like to use that for our provider. My main goal is to only have `workflows` installed but came across this documentation to get the integration for Okta + Workflows authentication which required `dex`.

I'll have to step back a bit and potentially look at this at a different angle. 

Also just wanted to bring this up as the `helm` section of the docs may not be correct

**Comment by jrowinski3d** [comment]
@bgdnlp I just tested out `kustomize` and got past the issue of **malformed dex config** , but now approaching a 404 not found for the `/api/dex` url.

So something is not correct in the helm setup for some reason.

**Comment by jrowinski3d** [comment]
> I wrote the Kustomize part, the helm charts and initial version were written by @hobbsh I believe. I have no idea why Dex would complain. I'd suggest checking the raw version of the config that ends up being loaded by Dex.

Any chance you could help me on how to check so I can validate the `helm` part of the docs?

**Comment by hobbsh** [comment]
Can you post the raw config that is trying to be loaded as mentioned above? I don't think I changed anything in the helm charts from what I can recall, this was purely documentation around setting this up.

If you're getting a 404, then it's possible you have an issue with your ingress configuration.

**Comment by jrowinski3d** [comment]
> Can you post the raw config that is trying to be loaded as mentioned above? I don't think I changed anything in the helm charts from what I can recall, this was purely documentation around setting this up.
> 
> If you're getting a 404, then it's possible you have an issue with your ingress configuration.

I just came across this issue today: https://github.com/argoproj/argo-cd/issues/3787

I was setting the `url` during the config which turns the "config" to be malformed. Both Helm and Kustomize alike. Apparently not setting it gives the **404** ?

My ingress is as follows and per the docs:

```bash
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # If you encounter a redirect loop or are getting a 307 response code 
    # then you need to force the nginx ingress to connect to the backend using HTTPS/HTTP.
    #
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: argocd.<my.domain>
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: http
  tls:
  - hosts:
    - argocd.<my.domain>
    secretName: argo-cd-secret
```

**Comment by hobbsh** [comment]
Did your Argo stack work before you setup the Dex stuff?

**Comment by jrowinski3d** [comment]
This is a brand new setup.

ArgoCD install -> https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
ArgoWorkflows install -> https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/install.yaml

And then doing the `kustomize` steps or `helm` steps as provided in the docs

**Comment by hobbsh** [comment]
So you're applying the `install.yaml` and then installing with helm on top of that?

**Comment by jrowinski3d** [comment]
Yeah, I tried `helm` at first, and then tried `kustomize` and same results. Just to confirm with you, do you need to have a **connector** setup first to make this work?

I managed to finally get it working, but by setting up an Okta SAML integration with **argo-cd** and then appending the **staticClients** to the `argocd-cm` . Now it looks like my `argo-workflows` is piggy backing on the SAML integration.

**Comment by hobbsh** [comment]
Glad you got it working. I've never tried it without a connector setup so I guess you do. Sorry the documentation is unclear!

**Comment by lacarvalho91** [comment]
I'm trying to do something similar to this, I mistakenly didn't have a connector configured either. Now that I have one configured things are up and running however when Argo Workflows tries to use the Argo CD dex to handle the login I just get an error saying:
```

Not Found

Invalid client_id ("my-client-id").
```

Where `my-client-id` seems correct (it is the value from the Secret documented on https://argoproj.github.io/argo-workflows/argo-server-sso-argocd/#example-helm-chart-configuration-for-authenticating-against-argocds-dex)

One thing I'm wondering is, should the client ID used for the argo workflows static client be the same as the client id used in the connector config? In our case we're using microsoft connector

**Comment by sidh** [comment]
@lacarvalho91 I had the same issue and I think I found solution. `id` in `staticClients` dex config must match whatever client id your workflows is using. You can store it in env just like client-secret (`secretEnv`) and then make dex read it via `idEnv` key instead of `id` (don't forget to put env var name as value).

**Comment by tiwarisanjay** [comment]
@lacarvalho91 @lacarvalho91 @jrowinski3d   It would be great if one of you can have a Youtube video or Github or Medium document for the steps. Like how we can integrate argo workflow using dex and the issues you had. 
I have been having issue as malformed  dex configuration which I am trying to solve but keep getting it.

**Comment by tiwarisanjay** [comment]
@lacarvalho91  Were you able to solve it ? as invalidate client-id ?

**Comment by jrowinski3d** [comment]
Hey @tiwarisanjay , my main problem was I didn't have a `connector` setup in argo-cd dex configMap:

I'm not working on that project anymore but maybe this CM setup will help you out.

Argo cd

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Kustomize sees the value of dex.config as a single string instead of yaml. It will not merge
  # Dex settings, but instead it will replace the entire configuration with the settings below,
  # so add these to the existing config instead of setting them in a separate file
  url: https://argocd.<redacted>
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      id: okta
      name: Okta
      config:
        ssoURL: https://<redacted>/sso/saml 
        # You need `caData` _OR_ `ca`, but not both.
        caData: |
        	<redacted>
        redirectURI: https://argocd.<redacted>/api/dex/callback
        usernameAttr: email
        emailAttr: email
        groupsAttr: group
    staticClients:
    - id: argo-workflows-sso
      name: Argo Workflow
      redirectURIs:
        - https://argo-workflows<redacted>/oauth2/callback
      secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
      
```


Argo-Workflows

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # SSO Configuration for the Argo server.
  # You must also start argo server with `--auth-mode sso`.
  # https://argoproj.github.io/argo-workflows/argo-server-auth-mode/
  sso: |
    # This is the root URL of the OIDC provider (required).
    issuer: https://argocd.<redacted>/api/dex
    # This is name of the secret and the key in it that contain OIDC client
    # ID issued to the application by the provider (required).
    clientId:
      name: argo-workflows-sso
      key: client-id
    # This is name of the secret and the key in it that contain OIDC client
    # secret issued to the application by the provider (required).
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    # This is the redirect URL supplied to the provider (required). It must
    # be in the form <argo-server-root-url>/oauth2/callback. It must be
    # browser-accessible.
    redirectUrl: https://argo-workflows.<redacted>/oauth2/callback
 ````

**Comment by tiwarisanjay** [comment]
@sidh Thank you very much for your input. Finally it worked. 
Just to let everyone else know in descriptive manner. In following code where it says `id: argo-workflows-sso` it should be your actual client-id from OIDC provider. So let me rewrite the documentation part where we have this client id : 
Argo workflow secret : 
```
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
data:
  # client-id is 'my-client-id-1234-1234'
  client-id: YXJnby13b3JrZmxvd3Mtc3Nv
  # client-secret is 'my-client-secret-verysecret'
  client-secret: TVktU0VDUkVULVNUUklORy1DQU4tQkUtVVVJRA==
```
Following code should be 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Kustomize sees the value of dex.config as a single string instead of yaml. It will not merge
  # Dex settings, but instead it will replace the entire configuration with the settings below,
  # so add these to the existing config instead of setting them in a separate file
  dex.config: |
    # Setting staticClients allows ArgoWorkflows to use ArgoCD's Dex installation for authentication
    staticClients:
      - id: my-client-id-1234-1234
        name: Argo Workflow
        redirectURIs:
          - https://argo-workflows.mydomain.com/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```
Thats where documentation sucks as they are using argo-workflows-sso as a client-id too 

@jrowinski3d  Thank you very much for your input. Just figured it out before you posted. But really appreciate your help
