### ISSUE TITLE
Variable DAG targets do not work in WorkflowTemplates

### ISSUE THREAD

**Issue by ebr** [argoproj/argo-workflows#6273]
## Summary 

Given this YAML:

```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate

metadata:
  generateName: dag-target-

spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: target
            value: heads
      dag:
        target: "{{inputs.parameters.target}}"
        tasks:
          - name: heads
            template: heads

    - name: heads
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"it was heads\""]
```

```
$ argo cluster-template create dag-target.yaml
2021/07/02 17:28:30 Failed to create cluster workflow template: ,  templates.main.targets: target 'placeholder-4' is not defined
```

This happens for both CWFT and WFT. However, changing it to a simple `Workflow` and doing `argo submit` seems to work completely fine.

- K8s v1.20
- Argo Workflows v3.0.7; I have not yet been able to test v3.1.x :(
- Docker executor 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
