### ISSUE TITLE
OSS artifact needs to support archive.none

### ISSUE THREAD

**Issue by jibuji** [argoproj/argo-workflows#6293]
# Summary

What change needs making?

according to the doc, artifacts should supports archive.none, but oss artifacts does not fully supported.

# Use Cases

see the following template, when the oss.key is an directory, it will raise "NoSuchKey" error. Again, within ouputs.artifacts, if the oss.key is an directory, it will also raise "NoSuchKey" error.

```yaml
  - name: some-tpl
    inputs:
      artifacts:
      - name: dataset
        path: "/mnt"
        oss:
          key: "some/oss/path"
        archive:
          none: {}
```

When would you use this?

I want to download an OSS directory to an local path using archive.none

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
