### ISSUE TITLE
Step hangs forever w/ retryStrategy added to templates (possibly related to Lifecycle hooks)

### ISSUE THREAD

**Issue by ad22** [argoproj/argo-workflows#6301]
## Summary 

I compose my DAG based on re-usable templates. I'm able to run the workflow successfully without retryStrategy on the templates, but adding the lines 
``` 
        retryStrategy:
          retryPolicy: OnError
          limit: "3"
```
causes the DAG to spin forever. 

See images
**Without retryStrategy**
![image](https://user-images.githubusercontent.com/9344284/124843236-5b748600-df46-11eb-8b20-a22233f1997a.png)

**With retryStrategy**
![image](https://user-images.githubusercontent.com/9344284/124843206-48fa4c80-df46-11eb-99ea-8ba9c7f89e9c.png)

## Diagnostics
Sample WF spec
```    
          name: LinuxJobBase
          container:
            command: ["bash"]
            args:
            - -c
            - >-
                ls
          retryStrategy:
              limit: '3'
              retryPolicy: OnError
  - dag:
     name: DAG
      tasks:
       - name: Python2Compile
         template: LinuxJobBase
      .......
```
Note that there is also an exithandler added to each of the dag steps, via hooks
```
        hooks:
          exit:
            arguments:
              parameters:
              - name: POD_NAME
                value: '{{tasks.Python3UnitTests.outputs.parameters.podname}}'
              - name: NODE_NAME
                value: '{{tasks.Python3UnitTests.outputs.parameters.nodename}}'
              - name: POD_NAMESPACE
                value: '{{tasks.Python3UnitTests.outputs.parameters.podnamespace}}'
              - name: POD_UID
                value: '{{tasks.Python3UnitTests.outputs.parameters.poduid}}'
              - name: IMAGE
                value: '{{tasks.Python3UnitTests.outputs.parameters.image}}'
            template: LinuxExitHandler
```
**What Kubernetes provider are you using?** 
Bare Metal
**What version of Argo Workflows are you running?** 
3.1.0
**What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary**
Emissary

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@ad22 Can you share the controller logs and sample reproducible workflow YAML?

**Comment by ad22** [comment]
@sarabala1979 Here is a complete WF that can reproduce the issue. 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-workflow-without-retry-strategy
spec:
  entrypoint: WORKFLOW
  templates:
  - name: WORKFLOW
    steps:
    - - name: Execute
        template: DAG

  - name: LinuxExitHandler
    container:
      args:
      - -c
      - set -xe && ls -ltr /
      command:
      - sh
      image: alpine:latest
    inputs:
      parameters:
      - name: IMAGE

  - name: LinuxJobBase
    container:
      args:
      - -c
      - set -xe && ls -ltr /
      command:
      - sh
      image: alpine:latest
    retryStrategy:
      limit: '3'
      retryPolicy: OnError
  - name: DAG
    dag:
      tasks:
      - name: Python2Compile
        template: LinuxJobBase
        hooks:
          exit:
            arguments:
              parameters:
              - name: IMAGE
                value: alpine:latest
            template: LinuxExitHandler
      - name: DependencyTesting
        template: LinuxJobBase
        depends: Python2Compile.Succeeded
        hooks:
          exit:
            arguments:
              parameters:
              - name: IMAGE
                value: alpine:latest
            template: LinuxExitHandler
```
Removing the following lines will make it pass
```
    retryStrategy:
      limit: '3'
      retryPolicy: OnError
``` 

**Logs without retryStrategy**
```
time="2021-07-08T16:57:31.982Z" level=info msg="Processing workflow" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:31.982Z" level=info msg="Updating node test-workflow-without-retry-strategybscng-2979735036 exit code 0" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:31.982Z" level=info msg="Updating node test-workflow-without-retry-strategybscng-2979735036 status Pending -> Succeeded" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:31.983Z" level=info msg="Running OnExit handler" lifeCycleHook="&LifecycleHook{Template:LinuxExitHandler,Arguments:Arguments{Parameters:[]Parameter{Parameter{Name:IMAGE,Default:nil,Value:*alpine:latest,ValueFrom:nil,GlobalName:,Enum:[],},},Artifacts:[]Artifact{},},}" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:31.983Z" level=info msg="Pod node test-workflow-without-retry-strategybscng-289371439 initialized Pending" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:31.988Z" level=info msg="Create pods 201"
time="2021-07-08T16:57:31.989Z" level=info msg="Created pod: test-workflow-without-retry-strategybscng[0].Execute.Python2Compile.onExit (test-workflow-without-retry-strategybscng-289371439)" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:31.989Z" level=info msg="Workflow step group node test-workflow-without-retry-strategybscng-3541207464 not yet completed" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:31.995Z" level=info msg="Update workflows 200"
time="2021-07-08T16:57:31.995Z" level=info msg="Workflow update successful" namespace=ci-smoke phase=Running resourceVersion=119877766 workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:31.998Z" level=info msg="Create events 201"
time="2021-07-08T16:57:32.000Z" level=info msg="Create events 201"
time="2021-07-08T16:57:32.001Z" level=info msg="cleaning up pod" action=labelPodCompleted key=ci-smoke/test-workflow-without-retry-strategybscng-2979735036/labelPodCompleted
time="2021-07-08T16:57:32.007Z" level=info msg="Patch pods 200"
time="2021-07-08T16:57:36.106Z" level=info msg="Get leases 200"
time="2021-07-08T16:57:36.109Z" level=info msg="Update leases 200"
time="2021-07-08T16:57:41.111Z" level=info msg="Get leases 200"
time="2021-07-08T16:57:41.113Z" level=info msg="Update leases 200"
time="2021-07-08T16:57:41.990Z" level=info msg="Processing workflow" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:41.990Z" level=info msg="Updating node test-workflow-without-retry-strategybscng-289371439 exit code 0" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:41.990Z" level=info msg="Updating node test-workflow-without-retry-strategybscng-289371439 status Pending -> Succeeded" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:41.991Z" level=info msg="Running OnExit handler" lifeCycleHook="&LifecycleHook{Template:LinuxExitHandler,Arguments:Arguments{Parameters:[]Parameter{Parameter{Name:IMAGE,Default:nil,Value:*alpine:latest,ValueFrom:nil,GlobalName:,Enum:[],},},Artifacts:[]Artifact{},},}" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:41.991Z" level=info msg="All of node test-workflow-without-retry-strategybscng[0].Execute.DependencyTesting dependencies [Python2Compile] completed" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:41.991Z" level=info msg="Pod node test-workflow-without-retry-strategybscng-863198016 initialized Pending" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:41.997Z" level=info msg="Create pods 201"
time="2021-07-08T16:57:41.997Z" level=info msg="Created pod: test-workflow-without-retry-strategybscng[0].Execute.DependencyTesting (test-workflow-without-retry-strategybscng-863198016)" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:41.997Z" level=info msg="Workflow step group node test-workflow-without-retry-strategybscng-3541207464 not yet completed" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:42.002Z" level=info msg="Update workflows 200"
time="2021-07-08T16:57:42.003Z" level=info msg="Workflow update successful" namespace=ci-smoke phase=Running resourceVersion=119878444 workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:42.006Z" level=info msg="Create events 201"
time="2021-07-08T16:57:42.008Z" level=info msg="Create events 201"
time="2021-07-08T16:57:42.010Z" level=info msg="cleaning up pod" action=labelPodCompleted key=ci-smoke/test-workflow-without-retry-strategybscng-289371439/labelPodCompleted
time="2021-07-08T16:57:42.016Z" level=info msg="Patch pods 200"
time="2021-07-08T16:57:46.116Z" level=info msg="Get leases 200"
time="2021-07-08T16:57:46.119Z" level=info msg="Update leases 200"
time="2021-07-08T16:57:51.121Z" level=info msg="Get leases 200"
time="2021-07-08T16:57:51.124Z" level=info msg="Update leases 200"
time="2021-07-08T16:57:51.998Z" level=info msg="Processing workflow" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:51.999Z" level=info msg="Updating node test-workflow-without-retry-strategybscng-863198016 exit code 0" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
time="2021-07-08T16:57:51.999Z" level=info msg="Updating node test-workflow-without-retry-strategybscng-863198016 status Pending -> Succeeded" namespace=ci-smoke workflow=test-workflow-without-retry-strategybscng
```

**Logs with retryStrategy**
```
ime="2021-07-08T17:00:44.891Z" level=info msg="Processing workflow" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:44.891Z" level=info msg="Updating node test-workflow-with-retry-strategy2cw9q-2182140530 exit code 0" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:44.891Z" level=info msg="Updating node test-workflow-with-retry-strategy2cw9q-2182140530 status Pending -> Succeeded" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:44.892Z" level=info msg="Running OnExit handler" lifeCycleHook="&LifecycleHook{Template:LinuxExitHandler,Arguments:Arguments{Parameters:[]Parameter{Parameter{Name:IMAGE,Default:nil,Value:*alpine:latest,ValueFrom:nil,GlobalName:,Enum:[],},},Artifacts:[]Artifact{},},}" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:44.892Z" level=info msg="Pod node test-workflow-with-retry-strategy2cw9q-1858250396 initialized Pending" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:44.961Z" level=info msg="Create pods 201"
time="2021-07-08T17:00:44.961Z" level=info msg="Created pod: test-workflow-with-retry-strategy2cw9q[0].Execute.Python2Compile.onExit (test-workflow-with-retry-strategy2cw9q-1858250396)" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:44.962Z" level=info msg="node test-workflow-with-retry-strategy2cw9q-2954248431 phase Running -> Succeeded" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:44.962Z" level=info msg="node test-workflow-with-retry-strategy2cw9q-2954248431 finished: 2021-07-08 17:00:44.96212654 +0000 UTC" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:44.962Z" level=info msg="Running OnExit handler" lifeCycleHook="&LifecycleHook{Template:LinuxExitHandler,Arguments:Arguments{Parameters:[]Parameter{Parameter{Name:IMAGE,Default:nil,Value:*alpine:latest,ValueFrom:nil,GlobalName:,Enum:[],},},Artifacts:[]Artifact{},},}" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:44.962Z" level=info msg="Pod node test-workflow-with-retry-strategy2cw9q-1437316374 initialized Pending" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:45.039Z" level=info msg="Create pods 201"
time="2021-07-08T17:00:45.039Z" level=info msg="Created pod: test-workflow-with-retry-strategy2cw9q[0].Execute.DependencyTesting.onExit (test-workflow-with-retry-strategy2cw9q-1437316374)" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:45.039Z" level=info msg="Workflow step group node test-workflow-with-retry-strategy2cw9q-3033651663 not yet completed" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:45.046Z" level=info msg="Update workflows 200"
time="2021-07-08T17:00:45.047Z" level=info msg="Workflow update successful" namespace=ci-smoke phase=Running resourceVersion=119890552 workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:45.050Z" level=info msg="Create events 201"
time="2021-07-08T17:00:45.053Z" level=info msg="cleaning up pod" action=labelPodCompleted key=ci-smoke/test-workflow-with-retry-strategy2cw9q-2182140530/labelPodCompleted
time="2021-07-08T17:00:45.055Z" level=info msg="Create events 201"
time="2021-07-08T17:00:45.061Z" level=info msg="Patch pods 200"
time="2021-07-08T17:00:45.077Z" level=info msg="Create events 201"
time="2021-07-08T17:00:46.717Z" level=info msg="Get leases 200"
time="2021-07-08T17:00:46.723Z" level=info msg="Update leases 200"
time="2021-07-08T17:00:51.730Z" level=info msg="Get leases 200"
time="2021-07-08T17:00:51.745Z" level=info msg="Update leases 200"
time="2021-07-08T17:00:55.015Z" level=info msg="Processing workflow" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:55.015Z" level=info msg="Updating node test-workflow-with-retry-strategy2cw9q-1437316374 status Pending -> Running" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:55.015Z" level=info msg="Updating node test-workflow-with-retry-strategy2cw9q-1858250396 exit code 0" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:55.015Z" level=info msg="Updating node test-workflow-with-retry-strategy2cw9q-1858250396 status Pending -> Succeeded" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:55.016Z" level=info msg="Running OnExit handler" lifeCycleHook="&LifecycleHook{Template:LinuxExitHandler,Arguments:Arguments{Parameters:[]Parameter{Parameter{Name:IMAGE,Default:nil,Value:*alpine:latest,ValueFrom:nil,GlobalName:,Enum:[],},},Artifacts:[]Artifact{},},}" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:55.016Z" level=info msg="Running OnExit handler" lifeCycleHook="&LifecycleHook{Template:LinuxExitHandler,Arguments:Arguments{Parameters:[]Parameter{Parameter{Name:IMAGE,Default:nil,Value:*alpine:latest,ValueFrom:nil,GlobalName:,Enum:[],},},Artifacts:[]Artifact{},},}" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
time="2021-07-08T17:00:55.016Z" level=info msg="Workflow step group node test-workflow-with-retry-strategy2cw9q-3033651663 not yet completed" namespace=ci-smoke workflow=test-workflow-with-retry-strategy2cw9q
```

**Comment by sarabala1979** [comment]
@simster7 Can you take a look at this issue?

**Comment by simster7** [comment]
> @simster7 Can you take a look at this issue?

@sarabala1979 I'd be happy to

**Comment by simster7** [comment]
I'm able to reproduce, I'll work on a fix

**Comment by simster7** [comment]
Possibly related: https://github.com/argoproj/argo-workflows/pull/5455/

**Comment by ad22** [comment]
@simster7 I agree - I ran a WF with retryStrategy added to the templates, but removed exit hooks, and it passes successfully.
I'm also able to trigger hangs on larger workflows without retryStrategy added, but while using exit hooks.

I think its a fair conclusion from the above experiments that the behavior is related to the use of exit hooks and not retryStrategy. I'll update the title accordingly.

**Comment by simster7** [comment]
@ad22 Thanks for the info and sorry for the delay... I'll get a chance to look at this soon

**Comment by sarabala1979** [comment]
@simster7 Will you be able to fix it soon? any ETA?

**Comment by simster7** [comment]
> @simster7 Will you be able to fix it soon? any ETA?

Yes, working on it right now

**Comment by simster7** [comment]
PR open: #6451 

@sarabala1979 @ad22

**Comment by ad22** [comment]
Thanks @simster7 
It may be unrelated but I'm able to spawn other "hangs" on the WF. This happens while monitoring the state of the exit handler hook step sequence.  See image
![image](https://user-images.githubusercontent.com/9344284/128068971-8280473b-7cc7-49ae-bf42-64750ecc03bf.png)

**Comment by simster7** [comment]
Can you include a "live" version of the workflow? You can get it from `kubectl get wf <name> -o yaml`. I can the check and see if these are also fixed by my fix

**Comment by ad22** [comment]
Unfortunately the WF has a lot of parts that are not applicable to external environments. Creating a minimally reproducible workflow..

**Comment by ad22** [comment]
@simster7 Here is a WF
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-workflow-with-hang-
spec:
  entrypoint: WORKFLOW
  templates:
  - name: WORKFLOW
    steps:
    - - name: Execute
        template: DAG

  - name: LinuxExitHandler
    inputs:
      parameters:
      - name: IMAGE
    steps:
    - - name: TriageLogger
        template: LinuxTriageLogger
        arguments:
          parameters:
          - name: IMAGE
            value: alpine:latest
    - - name: Cleanup
        template: LinuxWorkspaceCleanup
        arguments:
          parameters:
          - name: IMAGE
            value: alpine:latest

  - name: LinuxTriageLogger
    inputs:
      parameters:
      - name: IMAGE
    container:
      image: alpine:latest
      command: ["sh"]
      args:
      - "-c"
      - >-
        set -xe && ls -ltr /

  - name: LinuxWorkspaceCleanup
    inputs:
      parameters:
      - name: IMAGE
    container:
      image: alpine:latest
      command: ["sh"]
      args:
      - "-c"
      - >-
        set -xe && ls -ltr /

  - name: LinuxJobBase
    container:
      args:
      - -c
      - set -xe && ls -ltr /
      command:
      - sh
      image: alpine:latest
    retryStrategy:
      limit: '3'
      retryPolicy: OnError

  - name: DAG
    dag:
      tasks:
      - name: Python2Compile
        template: LinuxJobBase
        hooks:
          exit:
            arguments:
              parameters:
              - name: IMAGE
                value: alpine:latest
            template: LinuxExitHandler
      - name: DependencyTesting
        template: LinuxJobBase
        depends: Python2Compile.Succeeded
        hooks:
          exit:
            arguments:
              parameters:
              - name: IMAGE
                value: alpine:latest
            template: LinuxExitHandler
```
I'm curious to see if you can reproduce a hang with the above.
I am running an "off the beaten" path multi-namespaced RBAC setup.. but even though I found a few things to fix with 3.1.4 manifests, I can still trigger the hang.
