### ISSUE TITLE
Wrong order of DAG tasks may appear after sortDAGTasks when using Depends instead of Dependencies

### ISSUE THREAD

**Issue by book987** [argoproj/argo-workflows#6306]
## Summary 

What happened/what you expected to happen?

Running workflow belows **may**(about 12% chance to reproduce on my environment) got an error said 'invalid spec: templates.main.tasks.C templates.C-template: failed to resolve {{workflow.outputs.parameters.globalResult}}'

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sort-dag-tasks-test-
  namespace: argo
spec:
  entrypoint: main
  templates:
    - dag:
        tasks:
          - name: A
            template: A-template
          - depends: A
            name: B
            template: B-template
          - depends: B.Succeeded || B.Failed || B.Errored
            name: C
            template: C-template
      name: main
    - name: A-template
      container:
        args:
          - echo "A instance" >/data/result
        command:
          - sh
          - -c
        image: alpine:latest
      outputs:
        parameters:
          - name: result
            globalName: globalResult
            valueFrom:
              default: ""
              path: /data/result
    - name: B-template
      container:
        args:
          - echo "B instance"
        command:
          - sh
          - -c
        image: alpine:latest
    - name: C-template
      container:
        args:
          - echo "{{workflow.outputs.parameters.globalResult}}"
        command:
          - sh
          - -c
        image: alpine:latest
```

## Diagnostics

[sortDAGTasks](https://github.com/argoproj/argo-workflows/blob/v3.1.1/workflow/validate/validate.go#L1347) didn't support topological sorting when using Depends

[TopologicalSorting](https://github.com/argoproj/argo-workflows/blob/v3.1.1/util/sorting/topological_sorting.go#L12) is not stable cause it use map inside, thus this bug cannot reproduce stably

What Kubernetes provider are you using? 
self host, k3d

What version of Argo Workflows are you running? 
v3.1.1

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
docker

Did this work in a previous version? I.e. is it a regression?
tested on v3.0.7, v3.0.8

Are you pasting thousands of log lines? That's too much information. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
