### ISSUE TITLE
WorkflowStep when condition behavior changes after v3.1

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#6314]
## Summary 

What happened/what you expected to happen?

With https://github.com/argoproj/argo-workflows/pull/5115, the when condition is now evaluated as an expr

The below template works prior to v3.1

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-
  namespace: default
spec:
  entrypoint: conditional-example
  arguments:
    parameters:
    - name: should-print
      value: "2021-01-01-test"

  templates:
  - name: conditional-example
    inputs:
      parameters:
      - name: should-print
    steps:
    - - name: print-hello
        template: whalesay
        when: "{{inputs.parameters.should-print}} != 2021-01-01"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello"]
```

However, with the expression update, if a value starts with number, it gets interpreted as numeric token

Currently, I put a  single quote around to make it work.
```
when: "'{{inputs.parameters.should-print}}' != '2021-01-01'"
```

Maybe we need to document this or update the code to make it align with the old behavior?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
