### ISSUE TITLE
Expression templates which produce double quotes throw errors

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-workflows#6325]
## Summary 

[Another issue](https://github.com/argoproj/argo-workflows/issues/6260) shows how it's currently not possible to include double quotes (among a few other characters) in an expression.

This issue shows that any expression which _evaluates to something that contains a double-quote_ will fail.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: generate-string-array-
spec:
  entrypoint: main
  templates:
    - name: main
      script:
        env:
          - name: MESSAGE
            value: "{{=toJson('a')}}"
        image: debian:9.4
        command: [bash]
        source: |
          echo "$MESSAGE"
```

```
$ argo submit test.yaml
FATA[2021-07-12T11:43:34.663Z] Failed to submit workflow: templates.main invalid character 'a' after object key:value pair
```

The CLI throws this error because the expression can be evaluated at submit time. Workflows submitted with a different tool or containing expressions which cannot be evaluated until run-time will throw run-time errors (failing the workflow).

(The underlying error comes from the JSON unmarshaler, which is has encountered JSON something like `"value": ""a""` instead of `"value": "\"a\""`.)

This bug is important because it makes difficult one of the key use cases for this feature: constructing JSON arrays to be used with `withParam`.

[This PR](https://github.com/argoproj/argo-workflows/pull/6285) attempts to resolve both the double-quote-in and the double-quote-out bugs.

## Diagnostics

What Kubernetes provider are you using? 

Minikube

What version of Argo Workflows are you running? 

3.1.1

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Default

Did this work in a previous version? I.e. is it a regression?

No, it's a new feature

Are you pasting thousands of log lines? That's too much information. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
