### ISSUE TITLE
`Parameters` is a Golang map not a slice

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6326]
The iteration order of a Golang map is not deterministic. Often iterating it is in the insertion order, but occasionally (maybe 10%) not. This produced weird bugs.

**Comment by mac9416** [comment]
Example workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: chained-expressions-
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: a
            value: "1"
          - name: b
            value: "{{=asInt(inputs.parameters.a) + 1}}"
          - name: c
            value: "{{=asInt(inputs.parameters.b) + 1}}"
      script:
        env:
          - name: MESSAGE
            value: "{{inputs.parameters.c}}"
        image: debian:9.4
        command: [bash]
        source: |
          echo "$MESSAGE"
```

Adding a few more links to the chain causes it to fail more often.
