### ISSUE TITLE
Creator label override is not working

### ISSUE THREAD

**Issue by apratina** [argoproj/argo-workflows#6357]
## Summary 

I am trying to override `workflows.argoproj.io/creator` label for my workflows.

I configured my sensor that is triggering the workflow and here is an example:

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: my-sensor
  namespace: my-namespace
spec:
  template:
    serviceAccountName: my-serviceaccountname
  dependencies:
    - name: payload
      eventSourceName: my-webhook
      eventName: some-change
  triggers:
    - template:
        name: trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: client-dockerapp-
                labels:
                  appName: dockerapp
                  workflows.argoproj.io/creator: admin
              spec:
                serviceAccountName: my-serviceaccountname
                arguments:
                  parameters:
                    - name: git-repo-url
                      value: ""
                workflowTemplateRef:
                  name: my-cluster-workflow-example
                  clusterScope: true
          parameters:
            - src:
                dependencyName: payload
                dataKey: body.repository.clone_url
              dest: spec.arguments.parameters.0.value
```

When my workflow was submitted, it did not override the label `workflows.argoproj.io/creator` and it uses the default generated label.

Please let me know how can I override the label `workflows.argoproj.io/creator` because in absence of that we are hitting this [condition](https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/workflow/creator/creator.go#L28) and it would truncate the label in such a way that we have label value starting with `-` which is not allowed and fails the workflow from getting submitted.
