### ISSUE TITLE
Problem using PNS executor

### ISSUE THREAD

**Issue by danilorsilva** [argoproj/argo-workflows#6367]
Hello all,

     I have Argo workflow installed on my k8s GKE cluster.

     Argo Workflow version: 3.1.1
     K8s Version: 1.19.9

     I try to execute a workflow and sometimes it works fine and sometimes i have a problem with the message below:

     Error (exit code 1): cannot enter chroot for container named "main": no PID known - maybe short running container

     I saw many people reporting related problems using pns as a executor.

     Is this a problem related to PNS? Anyone had this problem before?

     I did not set a specific image for PNS executor.

Thank you so much for your time!

**Comment by sarabala1979** [comment]
@danilorsilva can you try the 3.1.13 or 3.2.0?

**Comment by PacoDu** [comment]
I have the same issue since we are using PNS executor, we encounter a lots of random  `
Error (exit code 1): cannot enter chroot for container named "main": no PID known - maybe short running container` 

Upgrading to 3.2.3 didn't solved the issue

**Comment by vediatoni** [comment]
Yeah same here, upgrading to 3.2.3 didn't help. It does work sometimes, but most of the time it doesn't. 
This issue should probably get open again.

Here is the workflow I was testing with:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-artifact-s3-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [sh, -c]
        args: ["cowsay hello world | tee /tmp/hello_world.txt"]
      outputs:
        artifacts:
          - name: message
            path: /tmp
            s3:
              endpoint: argo-artifacts:9000
              bucket: argo-bucket
              insecure: true
              key: test/hello_world.txt.tgz
              accessKeySecret:
                name: minio-access
                key: accessKey
              secretKeySecret:
                name: minio-access
                key: secretKey
```
