### ISSUE TITLE
Emissary executor does not handle optional output artifacts

### ISSUE THREAD

**Issue by AntoineDao** [argoproj/argo-workflows#6391]
## Summary 

What happened/what you expected to happen?

We use optional output artifacts in our workflows and have recently switched from `docker` to the `emissary` and noticed that optional output artifacts do not work using the `emissary` executor.

This bug is reproducible by running this workflow using `docker` or `emissary` executors:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          # bind message to the hello-art artifact
          # generated by the generate-artifact step
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      # generate hello-art artifact from /tmp/hello_world.txt
      # artifacts can be directories as well as files
      - name: hello-art
        path: /tmp/hello_world.txt
      - name: optional-art
        path: /tmp/non-existing-path.txt
        optional: true

  - name: print-message
    inputs:
      artifacts:
      # unpack the message input artifact
      # and put it at /tmp/message
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```

I am pretty sure I have found the offending lines of code so will make a PR today with a proposed fix :raised_hands: 

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
 - GKE

What version of Argo Workflows are you running? 
- ~3
 
What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
- Emissary
 
Did this work in a previous version? I.e. is it a regression?
- Don't know

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
