### ISSUE TITLE
Allow setting defaults for `container` in workflows

### ISSUE THREAD

**Issue by max-sixty** [argoproj/argo-workflows#6419]
# Summary

This is a follow-up to https://github.com/argoproj/argo-workflows/issues/3201, which was generously progressed in https://github.com/argoproj/argo-workflows/pull/5410, allowing to set defaults for `template`. This advances that to set defaults for a map _within_ `template` like `container`

# Use Cases

For example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templateDefaults:
    container:
      image: docker/whalesay:earliest             <- setting the default image for containers
  templates:
    - name: whalesay
      container:
        # image: docker/whalesay:latest           <- would be ":earliest" unless uncommented
        command: [cowsay]
        args: ["hello world"]

    # This wouldn't be affected by the default, because it doesn't have a `container` field
    - name: whalesee
      script:
        image: docker/whalesay:latest
        command: [python]
        source: "import datetime"
```

...while there's only one template in that spec, often we have many, all with identical `image` values. That would be simpler and less verbose if setting defaults for `image` were possible.

Thank you for the excellent library!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
