### ISSUE TITLE
Allow shared synchronization across namespaces

### ISSUE THREAD

**Issue by withnale** [argoproj/argo-workflows#6421]
# Summary

It would be good to be able to specify a namespace to the synchronization fields to allow the synchronization limits within the configmap to be shared across namespaces. We'd like to segregate workflows across multiple namespaces but work from the same limits. I'm aware of the global limit on argo-workflow itself but we are also going to have different types of jobs, so whilst that might help initially, we'll still hit that limit.

# Use Cases

So using an sample in the argo-workflow docs, this might be the optional additional `namespace` field:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: synchronization-wf-level-
spec:
  entrypoint: whalesay
  synchronization:
    semaphore:
      configMapKeyRef:
        name: my-config
        namespace: default
        key: workflow
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```
