### ISSUE TITLE
Workflow container limits not applied

### ISSUE THREAD

**Issue by lacarvalho91** [argoproj/argo-workflows#6424]
## Summary 

What happened/what you expected to happen?

Our namespace has a `ResourceQuota` policy configured, meaning all containers must explicitly declare resource requests and limits. However these do not seem to get applied when added to a Workflow. This was working fine on version 2.12.9 and only seems to be an issue when upgrading to 3.x.

When removing the `ResourceQuota` the Workflow ran successfully, so it would appear those container resources are not being applied. 

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using?

GKE

What version of Argo Workflows are you running?

3.0.3, 3.0.8, 3.1.2

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

K8SAPI

Did this work in a previous version? I.e. is it a regression?

This worked in version 2.12.9

Are you pasting thousands of log lines? That's too much information. 

```yml
metadata:
  name: fantastic-whale
  labels:
    example: 'true'
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
        resources:
            limits:
                cpu: '1'
                memory: 512Mi
            requests:
                cpu: '1'
                memory: 128Mi
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

Logs from the workflow controller:

```
time="2021-07-26T10:24:46.563Z" level=info msg="Processing workflow" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.566Z" level=info msg="Get configmaps 404"
time="2021-07-26T10:24:46.567Z" level=warning msg="Non-transient error: configmaps \"artifact-repositories\" not found"
time="2021-07-26T10:24:46.567Z" level=info msg="resolved artifact repository" artifactRepositoryRef=default-artifact-repository
time="2021-07-26T10:24:46.567Z" level=info msg="Updated phase  -> Running" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.567Z" level=info msg="Pod node omniscient-poochenheimer initialized Pending" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.575Z" level=info msg="Create pods 403"
time="2021-07-26T10:24:46.576Z" level=warning msg="Non-transient error: pods \"omniscient-poochenheimer\" is forbidden: [minimum cpu usage per Pod is 500m.  No request is specified, minimum memory usage per Pod is 64Mi.  No request is specified, maximum cpu usage per Pod is 2.  No limit is specified, maximum memory usage per Pod is 2Gi.  No limit is specified]"
time="2021-07-26T10:24:46.576Z" level=info msg="Failed to create pod omniscient-poochenheimer (omniscient-poochenheimer): pods \"omniscient-poochenheimer\" is forbidden: [minimum cpu usage per Pod is 500m.  No request is specified, minimum memory usage per Pod is 64Mi.  No request is specified, maximum cpu usage per Pod is 2.  No limit is specified, maximum memory usage per Pod is 2Gi.  No limit is specified]" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.576Z" level=warning msg="Non-transient error: pods \"omniscient-poochenheimer\" is forbidden: [minimum cpu usage per Pod is 500m.  No request is specified, minimum memory usage per Pod is 64Mi.  No request is specified, maximum cpu usage per Pod is 2.  No limit is specified, maximum memory usage per Pod is 2Gi.  No limit is specified]"
time="2021-07-26T10:24:46.576Z" level=error msg="Mark error node" error="pods \"omniscient-poochenheimer\" is forbidden: [minimum cpu usage per Pod is 500m.  No request is specified, minimum memory usage per Pod is 64Mi.  No request is specified, maximum cpu usage per Pod is 2.  No limit is specified, maximum memory usage per Pod is 2Gi.  No limit is specified]" namespace=bibcd-argo nodeName=omniscient-poochenheimer workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.576Z" level=info msg="node omniscient-poochenheimer phase Pending -> Error" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.576Z" level=info msg="node omniscient-poochenheimer message: pods \"omniscient-poochenheimer\" is forbidden: [minimum cpu usage per Pod is 500m.  No request is specified, minimum memory usage per Pod is 64Mi.  No request is specified, maximum cpu usage per Pod is 2.  No limit is specified, maximum memory usage per Pod is 2Gi.  No limit is specified]" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.576Z" level=info msg="node omniscient-poochenheimer finished: 2021-07-26 10:24:46.576186363 +0000 UTC" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.576Z" level=error msg="error in entry template execution" error="pods \"omniscient-poochenheimer\" is forbidden: [minimum cpu usage per Pod is 500m.  No request is specified, minimum memory usage per Pod is 64Mi.  No request is specified, maximum cpu usage per Pod is 2.  No limit is specified, maximum memory usage per Pod is 2Gi.  No limit is specified]" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.576Z" level=warning msg="Non-transient error: pods \"omniscient-poochenheimer\" is forbidden: [minimum cpu usage per Pod is 500m.  No request is specified, minimum memory usage per Pod is 64Mi.  No request is specified, maximum cpu usage per Pod is 2.  No limit is specified, maximum memory usage per Pod is 2Gi.  No limit is specified]"
time="2021-07-26T10:24:46.576Z" level=info msg="Updated phase Running -> Error" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.576Z" level=info msg="Updated message  -> error in entry template execution: pods \"omniscient-poochenheimer\" is forbidden: [minimum cpu usage per Pod is 500m.  No request is specified, minimum memory usage per Pod is 64Mi.  No request is specified, maximum cpu usage per Pod is 2.  No limit is specified, maximum memory usage per Pod is 2Gi.  No limit is specified]" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.576Z" level=info msg="Marking workflow completed" namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.576Z" level=info msg="Checking daemoned children of " namespace=bibcd-argo workflow=omniscient-poochenheimer
time="2021-07-26T10:24:46.577Z" level=info msg="Create events 201"
time="2021-07-26T10:24:46.582Z" level=info msg="Create events 201"
time="2021-07-26T10:24:46.588Z" level=info msg="Update workflows 200"
time="2021-07-26T10:24:46.588Z" level=info msg="Workflow update successful" namespace=bibcd-argo phase=Error resourceVersion=159991126 workflow=omniscient-poochenheimer
```

The workflow's pods that are problematic:

N/A as pods are not being created.

Logs from in your workflow's wait container, something like:

N/A as pods are not being created.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@lacarvalho91 you have `resourceRequest` in your workflow that is not get applied on pod creation. Am I understanding correctly?
```yaml
        resources:
            limits:
                cpu: '1'
                memory: 512Mi
            requests:
                cpu: '1'
                memory: 128Mi
```
