### ISSUE TITLE
Host path volumes are now needed

### ISSUE THREAD

**Issue by lacarvalho91** [argoproj/argo-workflows#6425]
## Summary 

What happened/what you expected to happen?

Since upgrading from 2.12.9 to 3.x I am unable to submit any workflows. This is because we have pod security policies in place that forbid the use of host path volumes, these policies were in place when using 2.12.9 as well so it would seem in 3.x something has been introduced that requires the use of host path volumes, but I was unable to find anything on https://argoproj.github.io/argo-workflows/upgrading/.

So if this was intentional, why? and which paths in particular? If it wasn't then I guess it is correct to raise this as a bug.

I can confirm that removing the pod security policy stops the error from occurring.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

GKE

What version of Argo Workflows are you running?

I have tried 3.0.3, 3.0.8 and 3.1.2

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

K8SAPI

Did this work in a previous version? I.e. is it a regression?

Yes, this worked fine in 2.12.9

Workflow YAML:

```yaml
metadata:
  name: delightful-python
  labels:
    example: 'true'
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

```bash

# Logs from the workflow controller:

time="2021-07-26T11:48:11.047Z" level=info msg="Processing workflow" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.054Z" level=info msg="Updated phase  -> Running" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.055Z" level=info msg="Pod node delightful-python initialized Pending" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.062Z" level=warning msg="Non-transient error: pods \"delightful-python\" is forbidden: unable to validate against any pod security policy: [spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used]"
time="2021-07-26T11:48:11.062Z" level=info msg="Failed to create pod delightful-python (delightful-python): pods \"delightful-python\" is forbidden: unable to validate against any pod security policy: [spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used]" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.062Z" level=warning msg="Non-transient error: pods \"delightful-python\" is forbidden: unable to validate against any pod security policy: [spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used]"
time="2021-07-26T11:48:11.062Z" level=error msg="Mark error node" error="pods \"delightful-python\" is forbidden: unable to validate against any pod security policy: [spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used]" namespace=bibcd-argo nodeName=delightful-python workflow=delightful-python
time="2021-07-26T11:48:11.062Z" level=info msg="node delightful-python phase Pending -> Error" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.062Z" level=info msg="node delightful-python message: pods \"delightful-python\" is forbidden: unable to validate against any pod security policy: [spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used]" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.062Z" level=info msg="node delightful-python finished: 2021-07-26 11:48:11.062743502 +0000 UTC" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.062Z" level=error msg="error in entry template execution" error="pods \"delightful-python\" is forbidden: unable to validate against any pod security policy: [spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used]" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.062Z" level=warning msg="Non-transient error: pods \"delightful-python\" is forbidden: unable to validate against any pod security policy: [spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used]"
time="2021-07-26T11:48:11.062Z" level=info msg="Updated phase Running -> Error" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.062Z" level=info msg="Updated message  -> error in entry template execution: pods \"delightful-python\" is forbidden: unable to validate against any pod security policy: [spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used]" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.062Z" level=info msg="Marking workflow completed" namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.062Z" level=info msg="Checking daemoned children of " namespace=bibcd-argo workflow=delightful-python
time="2021-07-26T11:48:11.075Z" level=info msg="Workflow update successful" namespace=bibcd-argo phase=Error resourceVersion=160042919 workflow=delightful-python
time="2021-07-26T11:48:11.075Z" level=info msg="Queueing Error workflow bibcd-argo/delightful-python for delete in 5m0s"
time="2021-07-26T11:48:11.075Z" level=info msg="Queueing Error workflow bibcd-argo/delightful-python for delete in 5m0s"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by lacarvalho91** [comment]
I was able to describe a pod from a workflow submitted after removing those policies and I can see this:

```
  docker-sock:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  Socket
```

I'm not using the docker executor though, is this expected?

**Comment by lacarvalho91** [comment]
hmm, `ARGO_CONTAINER_RUNTIME_EXECUTOR:  ` is blank, even though I have it configured to use K8SAPI in the config map. This would make it default to the docker executor I assume?

**Comment by lacarvalho91** [comment]
maybe the config map structure has changed?

**Comment by lacarvalho91** [comment]
The config map I am using:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  containerRuntimeExecutor: k8sapi

  executor: |
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.1
        memory: 64Mi
      limits:
        cpu: 0.5
        memory: 512Mi
```

**Comment by lacarvalho91** [comment]
Looks like the above config map was not being applied by our CD system, I applied it manually and this seems to be resolved now.

However, it does seem like the config map structure has changed. The old one I was using (and was working with 2.12.9) was:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    containerRuntimeExecutor: k8sapi
    executor:
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          cpu: 500m
          memory: 500Mi
```

This structure now appears to have changed to the one in my previous comment.
