### ISSUE TITLE
Provide a timeout setting that can cancel a workflow that is queued but not yet started

### ISSUE THREAD

**Issue by dhenneke** [argoproj/argo-workflows#6426]
# Summary

We want to set a timeout that automatically cancels workflows that have been stuck in a queued state. This can happen when a [synchronization](https://argoproj.github.io/argo-workflows/synchronization/) is configured or the global job limit has been exceeded.

# Use Cases

We use Argo Workflows as a task engine for a user-facing process. We set `activeDeadlineSeconds` to stop jobs that got stuck and take unexpectedly long. But sometimes the workflows are not scheduled due to an exceeded total workflow concurrency limit. In this case, we would like to eagerly cancel the scheduled job after a certain timeout to reduce the load of the system and shorten the overall work queue.

However, we didn't found a setting in the docs or while browsing the code.`activeDeadlineSeconds` limits the time in the `RUNNING` state (i.e. Kubernetes feature), while `timeout` limits the time in `PENDING + RUNNING` state. But not-yet-scheduled workflows have neither a proper state nor a start-time.

Is this already supported, or do you have an idea how this could be implemented? We could implement this kind of watchdog in our application that actively cancel stale workflows via the API, but it would be nicer as a native Argo Workflows feature.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
The current implementation will check the controller level concurrency limit first and check the` activeDeadlineSeconds`. But Once workflow passed concurrency and `activeDeadlineSeconds` is exceeded, the controller will fail the workflow immediately.

**Comment by dhenneke** [comment]
> The current implementation will check the controller level concurrency limit first and check the` activeDeadlineSeconds`. But Once workflow passed concurrency and `activeDeadlineSeconds` is exceeded, the controller will fail the workflow immediately.

@sarabala1979 I'm not sure if my understanding is correct?

Given the following example:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sleep-role
rules:
  # pod get/watch is used to identify the container IDs of the current pod
  # pod patch is used to annotate the step's outputs back to controller (e.g. artifact location)
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
      - list
  # logs get/watch are used to get the pods logs for script outputs, and for log archival
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sleep-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sleep-role
subjects:
  - kind: ServiceAccount
    name: sleep-sa
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: sleep-config
data:
  workflow: "1"


---
# takes 25 seconds to run and locks the semaphore
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: sleep-1
spec:
  serviceAccountName: sleep-sa
  synchronization:
    semaphore:
      configMapKeyRef:
        name: sleep-config
        key: workflow
  entrypoint: sleep
  templates:
  - name: sleep
    container:
      image: alpine:latest
      command: [sh, -c, echo "starting" && sleep 25 && echo "ready"]

---
# should be cancelled because it wasn't executed in time
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: sleep-2
spec:
  serviceAccountName: sleep-sa
  activeDeadlineSeconds: 20
  synchronization:
    semaphore:
      configMapKeyRef:
        name: sleep-config
        key: workflow
  entrypoint: sleep
  templates:
  - name: sleep
    container:
      image: alpine:latest
      command: [sh, -c, echo "starting" && sleep 10 && echo "ready"]
```

The following happens (Argo Workflows v3.0.7):
* `sleep-1` executes for 25 seconds; `sleep-2` is in the `Waiting for */ConfigMap/sleep-config/workflow lock. Lock status 0/1` state
* `sleep-1` finishes and clears the lock; `sleep-2` starts to execute.
* `sleep-2` finishes.

We would like to configure `sleep-2` to be skipped when it's execution deadline of 20 seconds was not met. We neither care for its' execution nor for its' result anymore, so we can safely skip it and avoid unnecessary resource consumption.
