### ISSUE TITLE
Trying to do introspection raise an internal error

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#6431]
## Summary 

For a specific workflow, I would like to retrieve the current workflow object, then parse it with python for triggering some action. Below you can find the most simple and basic workflow to reproduce the issue.

The message from argo-workflow engine is:
```
invalid character 'a' after object key:value pair
```
So it seems that it tries to parse/interpret the value of the variable output and it shouldn't.

## Diagnostics
What Kubernetes provider are you using? 
```
Client Version: 4.7.2
Server Version: 4.5.5
Kubernetes Version: v1.18.3+08c38ef
```
What version of Argo Workflows are you running? 
```
3.1.2
```

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
```
PNS
```

Did this work in a previous version? I.e. is it a regression?
I tried first with 3.0.1 but it was also not working.

Workflow to reproduce
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: serialization-resource-bug
  namespace: YOUR-NAMESPACE
spec:
  entrypoint: main
  serviceAccountName: YOUR-SA
  templates:
  - name: main
    steps:
      - - name: get-workflow-object
          template: get-workflow-object
      - - name: create-artifact
          template: create-artifact
          arguments:
            parameters:
            - name: workflow-object
              value: "{{steps.get-workflow-object.outputs.parameters.workflow-object}}" 
  - name: get-workflow-object
    outputs:
      parameters:
      - name: workflow-object
        valueFrom:
          jsonPath: '{}'
    resource:
      action: get
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          name: {{workflow.name}}
          namespace: YOUR-NAMESPACE
  - name: create-artifact
    inputs:
      parameters:
      - name: workflow-object
    outputs:
      artifacts:
      - name: result
        path: /mnt/out/result
    volumes:
    - name: out
      emptyDir: {}
    script:
      volumeMounts:
      - name: out
        mountPath: /mnt/out
      image: bash
      command: [bash]
      source: |
        echo will do
        cat <<EOF > /mnt/out/result
        {{inputs.parameters.workflow-object}}
        EOF
        echo done
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@sylock Workflow JSON is causing the JSON parsing when it substitutes in the source.  I would recommend storing the workflow JSON as an artifact and pass it across the steps.  code has to handle JSON format in the source. we will investigate and fix it. 

```json
"echo will do\ncat \u003c\u003cEOF \u003e /mnt/out/result\n{\"apiVersion\":\"argoproj.io/v1alpha1\",\"kind\":\"Workflow\",\"metadata\":{\"creationTimestamp\":\"2021-07-27T15:54:08Z\",\"generation\":2,\"labels\":{\"workflows.argoproj.io/phase\":\"Running\"},\"managedFields\":[{\"apiVersion\":\"argoproj.io/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:labels\":{\".\":{},\"f:workflows.argoproj.io/phase\":{}}},\"f:spec\":{\"f:activeDeadlineSeconds\":{},\"f:podSpecPatch\":{},\"f:templates\":{},\"f:ttlStrategy\":{}},\"f:status\":{\"f:artifactRepositoryRef\":{},\"f:nodes\":{},\"f:phase\":{},\"f:progress\":{},\"f:startedAt\":{}}},\"manager\":\"___controller\",\"operation\":\"Update\",\"time\":\"2021-07-27T15:54:08Z\"},{\"apiVersion\":\"argoproj.io/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:spec\":{\".\":{},\"f:arguments\":{},\"f:entrypoint\":{}},\"f:status\":{\".\":{},\"f:finishedAt\":{}}},\"manager\":\"argo\",\"operation\":\"Update\",\"time\":\"2021-07-27T15:54:08Z\"}],\"name\":\"serialization-resource-bug\",\"namespace\":\"argo\",\"resourceVersion\":\"371450\",\"selfLink\":\"/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/serialization-resource-bug\",\"uid\":\"6c5cfd3a-bb62-404b-b640-04367c517b8d\"},\"spec\":{\"activeDeadlineSeconds\":300,\"arguments\":{},\"entrypoint\":\"main\",\"podSpecPatch\":\"terminationGracePeriodSeconds: 3\\n\",\"templates\":[{\"inputs\":{},\"metadata\":{},\"name\":\"main\",\"outputs\":{},\"steps\":[[{\"arguments\":{},\"name\":\"get-workflow-object\",\"template\":\"get-workflow-object\"}],[{\"arguments\":{\"parameters\":[{\"name\":\"workflow-object\",\"value\":\"{{steps.get-workflow-object.outputs.parameters.workflow-object}}\"}]},\"name\":\"create-artifact\",\"template\":\"create-artifact\"}]]},{\"inputs\":{},\"metadata\":{},\"name\":\"get-workflow-object\",\"outputs\":{\"parameters\":[{\"name\":\"workflow-object\",\"valueFrom\":{\"jsonPath\":\"{}\"}}]},\"resource\":{\"action\":\"get\",\"manifest\":\"apiVersion: argoproj.io/v1alpha1\\nkind: Workflow\\nmetadata:\\n  name: serialization-resource-bug\\n  namespace: argo\\n\"}},{\"inputs\":{\"parameters\":[{\"name\":\"workflow-object\"}]},\"metadata\":{},\"name\":\"create-artifact\",\"outputs\":{\"artifacts\":[{\"name\":\"result\",\"path\":\"/mnt/out/result\"}]},\"script\":{\"command\":[\"bash\"],\"image\":\"bash\",\"name\":\"\",\"resources\":{},\"source\":\"echo will do\\ncat \\u003c\\u003cEOF \\u003e /mnt/out/result\\n{"
		apiVersion ":"
		argoproj.io / v1alpha1 ","
		kind ":"
		Workflow ","
```

**Comment by sylock** [comment]
I tried saving the Json as an artifact but I could not do it. I don't think that the "resource" template support artifacts (Did not see it in the documentation and my tries failed).

```
  - name: get-workflow-object
    outputs:
      parameters:
      - name: workflow-object
        valueFrom:
          jsonPath: '{}'
    resource:
      action: get
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          name: {{workflow.name}}
          namespace: YOUR-NAMESPACE
```

**Comment by alexec** [comment]
Please try with v3.1.3

**Comment by sylock** [comment]
Unfortunately I still have the issue with the version 3.1.3:
![image](https://user-images.githubusercontent.com/2362405/127634506-777145e2-89f8-4985-bd99-1d7a3edc69f8.png)

Can you explain me the workaround mentionned by @sarabala1979 with the artifacts? Indeed it would be more elegant and more easy to handle if I could save the JSON object as an artifact than a variable. When I try this it doesn't work since the artifacts output requires a "path" property:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: serialization-resource-bug-3
  namespace: NAMESPACE
spec:
  entrypoint: main
  serviceAccountName: SA
  templates:
  - name: main
    steps:
      - - name: get-workflow-object
          template: get-workflow-object
  - name: get-workflow-object
    outputs:
      artifacts:
      - name: workflow-object
        valueFrom:
          jsonPath: '{}'
    resource:
      action: get
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          name: {{workflow.name}}
          namespace: NAMESPACE
```

**Comment by alexec** [comment]
@sarabala1979 I leave this with you to add to backlog.

**Comment by sylock** [comment]
@sarabala1979 Can I have an update on that issue?

**Comment by alexec** [comment]
@sarabala1979 can you please reply?

**Comment by sarabala1979** [comment]
@sylock I will take a look. I am trying to provide fix or workaround

**Comment by sylock** [comment]
@sarabala1979 @alexec I think that there are 2 different things in this ticket:
## A bug in the serialization
There is probably a bug in the escaping of the data when providing them to a step as an input.

## A feature request - export
For a step of kind "get resource" with a manifest, add the possibility to export the output as an artifact instead of a variable.

I think we should focus on the bug in this ticket, and I can create another one for the feature request. Can you tell me what you think and validate what I can do to make it more clear?

**Comment by sarabala1979** [comment]
@sylock yes. Please create enhancements issues for support artifacts for resource template type.

**Comment by sarabala1979** [comment]
@sylock I spend a whole day fixing the serialize the JSON but I couldn’t get it right. Because template has Json inside json (wf object JSON) which replaced by parameters.  I kind of thinking instead of fix this edge case. I come with workaround. In meantime , we will implement artifact support for `resource` template.

I build custom docker image with `kubectl` sarabala1979/kubectl:latest


```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: serialization-resource-bug
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: get-workflow-object
            template: get-workflow-object
        - - name: create-artifact
            template: create-artifact
            arguments:
              artifacts:
                - name: workflow-object
                  from: "{{steps.get-workflow-object.outputs.artifacts.workflow-object}}"
    - name: get-workflow-object
      outputs:
        artifacts:
          - name: workflow-object
            path: /tmp/wf.yaml
            archive:
              none: {}
      script:
        image: sarabala1979/kubectl:latest
        command: [sh]
        source: |
          kubectl get wf {{workflow.name}} -o yaml > /tmp/wf.yaml
          
    - name: create-artifact
      inputs:
        artifacts:
          - name: workflow-object
            path: /tmp/wf.yaml
      outputs:
        artifacts:
          - name: result
            path: /mnt/out/result
      volumes:
        - name: out
          emptyDir: {}
      script:
        image: bash
        command: [bash]
        source: |
          cat /tmp/wf.yaml
```
