### ISSUE TITLE
Unable to use `step.XXXX.outputs.parameters` with script

### ISSUE THREAD

**Issue by davidcollom** [argoproj/argo-workflows#6439]
## Summary 

In the sample/example code, here: https://github.com/argoproj/argo-workflows/blob/master/examples/parameter-aggregation.yaml

One would assume that this can be done with a `ScriptTemplate` over that of the `UserContainer`.

## Diagnostics

If I use the example provided and run `argo lint` every works/looks fine:
```sh
$ argo lint workflow-template.yaml
workflow-template.yaml is valid
Workflow manifests validated
```

However if I change the template `odd-or-even` to a `ScriptTemplate`:
```yaml
# odd-or-even accepts a number and returns whether or not that number is odd or even
  - name: odd-or-even
    inputs:
      parameters:
      - name: num
    script:
      image: argoproj/argosay:v1
      command: [sh, -xc]
      source: |
        sleep 1
        echo {{inputs.parameters.num}} > /tmp/num
        if [ $(({{inputs.parameters.num}}%2)) -eq 0 ]; then
          echo "even" > /tmp/even
        else
          echo "odd" > /tmp/even
        fi
    outputs:
      parameters:
      - name: num
        valueFrom:
          path: /tmp/num
      - name: evenness
        valueFrom:
          path: /tmp/even
```

Argo lint responds with:

```sh
$ argo lint workflow-template.yaml
ERRO[2021-07-28T09:39:50.254Z] Error in file workflow-template.yaml: templates.parameter-aggregation.steps failed to resolve {{steps.odd-or-even.outputs.parameters}}
FATA[2021-07-28T09:39:50.255Z] Errors encountered in validation
```

What Kubernetes provider are you using? GKE

What version of Argo Workflows are you running? `v3.1.2`

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary `Docker`

Did this work in a previous version? I.e. is it a regression? Also tried on `v2.12.8` and same issue occurs

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Please add full workflow.

**Comment by ziv-codefresh** [comment]
Hey guys, 
I was able to reproduce the issue. 
When i changed the type of the step to script instead of container, the lint phase failed with the following error:

``   ✖ in "parameter-aggregation-" (Workflow): templates.parameter-aggregation.steps failed to resolve {{steps.odd-or-even.outputs.parameters}}
``
Ive started to debug it and i found that it fail on the phase of resolving tag: `steps.odd-or-even.outputs.parameters`
the scope include the following 
![Screen Shot 2021-09-18 at 19 58 14](https://user-images.githubusercontent.com/32479607/133896549-b4537ab1-34fa-4322-83dd-162f5eb580e0.png)
and because  `*.outputs.parameters` is not included so the lint failed with this error.
i dig a bit to find the reason for failure, and i found out that the following part is the origin of the issue. 
```	
if aggregate {
    switch tmpl.GetType() {
    // Not that we don't also include TemplateTypeContainer here, even though it uses `outputs.result` it uses
    // `outputs.parameters` as its aggregator.
    case wfv1.TemplateTypeScript, wfv1.TemplateTypeContainerSet:
	    scope[fmt.Sprintf("%s.outputs.result", prefix)] = true
	    scope[fmt.Sprintf("%s.exitCode", prefix)] = true
    default:
	    scope[fmt.Sprintf("%s.outputs.parameters", prefix)] = true
    }
}
```
so as you can see when we using script template the scope of `outputs.parmaters` in not included. 
i fixed the issue by adding `scope[fmt.Sprintf("%s.outputs.parameters", prefix)] = true` line to the case of   `case wfv1.TemplateTypeScript, wfv1.TemplateTypeContainerSet` as the following:

```	
if aggregate {
    switch tmpl.GetType() {
    // Not that we don't also include TemplateTypeContainer here, even though it uses `outputs.result` it uses
    // `outputs.parameters` as its aggregator.
    case wfv1.TemplateTypeScript, wfv1.TemplateTypeContainerSet:
	    scope[fmt.Sprintf("%s.outputs.result", prefix)] = true
	    scope[fmt.Sprintf("%s.exitCode", prefix)] = true
	    scope[fmt.Sprintf("%s.outputs.parameters", prefix)] = true
    default:
	    scope[fmt.Sprintf("%s.outputs.parameters", prefix)] = true
    }
}
```
and looks like it solve the issue: 

``` ✔ no linting errors found! ```

also i submitted the workflow and looks like the steps are able to use the output params from the script step.

@alexec please let me know if i missing something or its on purpose from the comment in the code i guess there is some motivation for this seperation, i pretty new to this project and i might get it wrong, if its valid solution, i can contribute it off course. let me know please. 

this is the yaml ive reproduce this issue with: 
```
# Example workflow to demonstrate parameter aggregation.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameter-aggregation-
spec:
  entrypoint: parameter-aggregation
  templates:
    - name: parameter-aggregation
      steps:
        # First loop through a list of numbers and determine if the number is odd or even. This is
        # captured in output parameter 'evenness'. (e.g. {"num": "4", "evenness": "even"})
        - - name: odd-or-even
            template: odd-or-even
            arguments:
              parameters:
                - name: num
                  value: "{{item}}"
            withItems: [1, 2, 3, 4]
        - - name: print-nums
            template: whalesay
            arguments:
              parameters:
                - name: message
                  value: "{{steps.odd-or-even.outputs.parameters.num}}"
        - - name: print-evenness
            template: whalesay
            arguments:
              parameters:
                - name: message
                  value: "{{steps.odd-or-even.outputs.parameters.evenness}}"
        # Next, for each even number, divide it by two (using a script template).
        # Skip odd numbers using a `when` clause.
        - - name: divide-by-2
            template: divide-by-2
            arguments:
              parameters:
                - name: num
                  value: "{{item.num}}"
            withParam: "{{steps.odd-or-even.outputs.parameters}}"
            when: "{{item.evenness}} == even"
        # Finally, print all numbers processed in the previous step
        - - name: print
            template: whalesay
            arguments:
              parameters:
                - name: message
                  value: "{{item}}"
            withParam: "{{steps.divide-by-2.outputs.result}}"

    # odd-or-even accepts a number and returns whether or not that number is odd or even
    - name: odd-or-even
      inputs:
        parameters:
          - name: num
      script:
        image: argoproj/argosay:v1
        command: [sh, -x]
        source: |
          sleep 1
          echo {{inputs.parameters.num}} > /tmp/num
          if [ $(({{inputs.parameters.num}}%2)) -eq 0 ]; then
            echo "even" > /tmp/even
          else
            echo "odd" > /tmp/even
          fi
      outputs:
        parameters:
          - name: num
            valueFrom:
              path: /tmp/num
          - name: evenness
            valueFrom:
              path: /tmp/even
    # divide-by-2 divides a number in half
    - name: divide-by-2
      inputs:
        parameters:
          - name: num
      script:
        image: alpine:latest
        command: [sh, -x]
        source: |
          #!/bin/sh
          echo $(({{inputs.parameters.num}}/2))
    # whalesay prints a number using whalesay
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

**Comment by ziv-codefresh** [comment]
Hey guys, 
I was able to reproduce the issue. 
When i changed the type of the step to script instead of container, the lint phase failed with the following error:

``   ✖ in "parameter-aggregation-" (Workflow): templates.parameter-aggregation.steps failed to resolve {{steps.odd-or-even.outputs.parameters}}
``
Ive started to debug it and i found that it fail on the phase of resolving tag: `steps.odd-or-even.outputs.parameters`
the scope include the following 
![Screen Shot 2021-09-18 at 19 58 14](https://user-images.githubusercontent.com/32479607/133896549-b4537ab1-34fa-4322-83dd-162f5eb580e0.png)
and because  `*.outputs.parameters` is not included so the lint failed with this error.
i dig a bit to find the reason for failure, and i found out that the following part is the origin of the issue. 
```	
if aggregate {
    switch tmpl.GetType() {
    // Not that we don't also include TemplateTypeContainer here, even though it uses `outputs.result` it uses
    // `outputs.parameters` as its aggregator.
    case wfv1.TemplateTypeScript, wfv1.TemplateTypeContainerSet:
	    scope[fmt.Sprintf("%s.outputs.result", prefix)] = true
	    scope[fmt.Sprintf("%s.exitCode", prefix)] = true
    default:
	    scope[fmt.Sprintf("%s.outputs.parameters", prefix)] = true
    }
}
```
so as you can see when we using script template the scope of `outputs.parmaters` in not included. 
i fixed the issue by adding `scope[fmt.Sprintf("%s.outputs.parameters", prefix)] = true` line to the case of   `case wfv1.TemplateTypeScript, wfv1.TemplateTypeContainerSet` as the following:

```	
if aggregate {
    switch tmpl.GetType() {
    // Not that we don't also include TemplateTypeContainer here, even though it uses `outputs.result` it uses
    // `outputs.parameters` as its aggregator.
    case wfv1.TemplateTypeScript, wfv1.TemplateTypeContainerSet:
	    scope[fmt.Sprintf("%s.outputs.result", prefix)] = true
	    scope[fmt.Sprintf("%s.exitCode", prefix)] = true
	    scope[fmt.Sprintf("%s.outputs.parameters", prefix)] = true
    default:
	    scope[fmt.Sprintf("%s.outputs.parameters", prefix)] = true
    }
}
```
and looks like it solve the issue: 

``` ✔ no linting errors found! ```

also i submitted the workflow and looks like the steps are able to use the output params from the script step.

@alexec please let me know if i missing something or its on purpose from the comment in the code i guess there is some motivation for this seperation, i pretty new to this project and i might get it wrong, if its valid solution, i can contribute it off course. let me know please. 

this is the yaml ive reproduce this issue with: 
```
# Example workflow to demonstrate parameter aggregation.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameter-aggregation-
spec:
  entrypoint: parameter-aggregation
  templates:
    - name: parameter-aggregation
      steps:
        # First loop through a list of numbers and determine if the number is odd or even. This is
        # captured in output parameter 'evenness'. (e.g. {"num": "4", "evenness": "even"})
        - - name: odd-or-even
            template: odd-or-even
            arguments:
              parameters:
                - name: num
                  value: "{{item}}"
            withItems: [1, 2, 3, 4]
        - - name: print-nums
            template: whalesay
            arguments:
              parameters:
                - name: message
                  value: "{{steps.odd-or-even.outputs.parameters.num}}"
        - - name: print-evenness
            template: whalesay
            arguments:
              parameters:
                - name: message
                  value: "{{steps.odd-or-even.outputs.parameters.evenness}}"
        # Next, for each even number, divide it by two (using a script template).
        # Skip odd numbers using a `when` clause.
        - - name: divide-by-2
            template: divide-by-2
            arguments:
              parameters:
                - name: num
                  value: "{{item.num}}"
            withParam: "{{steps.odd-or-even.outputs.parameters}}"
            when: "{{item.evenness}} == even"
        # Finally, print all numbers processed in the previous step
        - - name: print
            template: whalesay
            arguments:
              parameters:
                - name: message
                  value: "{{item}}"
            withParam: "{{steps.divide-by-2.outputs.result}}"

    # odd-or-even accepts a number and returns whether or not that number is odd or even
    - name: odd-or-even
      inputs:
        parameters:
          - name: num
      script:
        image: argoproj/argosay:v1
        command: [sh, -x]
        source: |
          sleep 1
          echo {{inputs.parameters.num}} > /tmp/num
          if [ $(({{inputs.parameters.num}}%2)) -eq 0 ]; then
            echo "even" > /tmp/even
          else
            echo "odd" > /tmp/even
          fi
      outputs:
        parameters:
          - name: num
            valueFrom:
              path: /tmp/num
          - name: evenness
            valueFrom:
              path: /tmp/even
    # divide-by-2 divides a number in half
    - name: divide-by-2
      inputs:
        parameters:
          - name: num
      script:
        image: alpine:latest
        command: [sh, -x]
        source: |
          #!/bin/sh
          echo $(({{inputs.parameters.num}}/2))
    # whalesay prints a number using whalesay
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```
