### ISSUE TITLE
Script templates don't allocate pod resource requests/limits

### ISSUE THREAD

**Issue by AntoineDao** [argoproj/argo-workflows#6449]
## Summary 

I noticed that pods generated by script templates do not allocate the resource `requests`/`limits`  to the pods they generate.

Here is an example template that doesn't set the expected resource on the resulting pod:

```yaml
metadata:
  name: test-script-resources
spec:
  entrypoint: zip-artifact
  templates:
    - name: zip-artifact
      script:
        image: "python:alpine3.7"
        command:
          - python
        resources:
          limits:
            cpu: "1"
            memory: 10Gi
          requests:
            cpu: "1"
            memory: 3.5Gi
        source: print("woop!")
  podGC:
    strategy: OnPodCompletion

```

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
- GCP

What version of Argo Workflows are you running? 
- 3.0.8

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
- emissary

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
