### ISSUE TITLE
commands.NewResourceCommand should retry when k8s api is unavailable 

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#6467]
## Summary 

Resource executions are not retried for tcp timeouts when the K8s API becomes busy from too many workflows running in parallel. I think we can use retry.OnError from k8s.io/client-go/util/retry to avoid the issue.

```
return retry.OnError(retry.DefaultBackoff, net.IsTimeout, func() (err error) {
   // argo code here
})
```

- https://pkg.go.dev/k8s.io/client-go/util/retry#OnError
- https://pkg.go.dev/k8s.io/apimachinery/pkg/util/net#IsTimeout

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

EKS 1.19

What version of Argo Workflows are you running? 

3.1.2

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

n/a

Did this work in a previous version? I.e. is it a regression?

No

Logs 

```
task-ssh-config-create-update-5lwhb-1844661117: time="2021-08-02T15:28:39.528Z" level=error msg="executor error: Unable to connect to the server: dial tcp 172.20.0.1:443: i/o timeout
github.com/argoproj/argo-workflows/v3/errors.New
/go/src/github.com/argoproj/argo-workflows/errors/errors.go:49
github.com/argoproj/argo-workflows/v3/workflow/executor.(*WorkflowExecutor).ExecResource
/go/src/github.com/argoproj/argo-workflows/workflow/executor/resource.go:44
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.execResource
/go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/resource.go:48
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.NewResourceCommand.func1
/go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/resource.go:25
github.com/spf13/cobra.(*Command).execute
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
github.com/spf13/cobra.(*Command).ExecuteC
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main\n\t/go/src/github.com/argoproj/argo-workflows/cmd/argoexec/main.go:15\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1374"
```

The workflow template that timed out is creating a simple config map that stores ssh keys
```
    resource:
      action: apply
      manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ssh-authorized-keys
          namespace: {{inputs.parameters.envNamespace}}
          labels:
            ssh-user: {{workflow.parameters.sshUserName}}
        data:
          keys: "{{workflow.parameters.sshKeys}}"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
