### ISSUE TITLE
Github App Authentication Support

### ISSUE THREAD

**Issue by marcelobartsch** [argoproj/argo-workflows#6491]
# Summary

for github artifacts would be nice to support github app authentication , as it simple to manage access to repositories than using personal access token.

What change needs making?

Implement github jwt authentication for application in workflow/artifacts/git/git.go , "github.com/bradleyfalzon/ghinstallation" is suppose to provide the helpers to do it simply, also new parameters to the 'git' artifact will be needed as 'Private Pem Key', 'Application Id' and 'Installation Id'

# Use Cases
When manage a huge number of repos from different teams is simpler to use github app to allow access from the workflow or CI/CD platform to the repos than using Personal Access Tokens, this way , is less human interaction needed 

When would you use this?

to checkout code from private github repos
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by marcelobartsch** [comment]
I have created a branch in a fork, it is not well done, but is working 
https://github.com/marcelobartsch/argo-workflows/tree/github-apps

**Comment by marcelobartsch** [comment]
sample workflow
```
# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-checkout-v3
spec:
  serviceAccountName: argo
  arguments:
    parameters:
      - name: project
        value: hermes
      - name: branch
        value: master
  templates:
    - name: git-clone
      inputs:
        parameters:
          - name: project
          - name: branch
        artifacts:
          - name: argo-source
            path: /src
            git:
              repo: "https://github.com/myorganization/{{ inputs.parameters.project }}.git"
              revision: "{{ inputs.parameters.branch }}"
              applicationIdSecret:
                name: github-app-access-token
                key: appId
              installationIdSecret:
                name: github-app-access-token
                key: installId
              applicationKeySecret:
                name: github-app-access-token
                key: key2
      container:
        image: hseeberger/scala-sbt:11.0.12_1.5.5_2.13.6
        command: [sh, -c]
        args: ["sbt build"]
        workingDir: /src
```
