### ISSUE TITLE
Cannot run artifact-passing example in 3.1.5 (3.1.2), got "key unsupported: cannot get key for artifact location, because it is invalid"

### ISSUE THREAD

**Issue by ChanYiLin** [argoproj/argo-workflows#6497]
## Summary 

I installed **argo 3.1.5 (and 3.1.2) on minikube** on my mac and tried to run official [artifact-passing example](https://github.com/argoproj/argo-workflows/blob/master/examples/artifact-passing.yaml). 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt

  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]

```

It failed with following message
```
Name:                artifact-passing-mrfgl
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             child 'artifact-passing-mrfgl-2442905136' failed
Conditions:
 PodRunning          False
 Completed           True
Created:             Fri Aug 06 18:54:16 +0800 (3 minutes ago)
Started:             Fri Aug 06 18:54:16 +0800 (3 minutes ago)
Finished:            Fri Aug 06 18:54:36 +0800 (3 minutes ago)
Duration:            20 seconds
ResourcesDuration:   7s*(1 cpu),7s*(100Mi memory)

STEP                       TEMPLATE          PODNAME                            DURATION  MESSAGE
 ✖ artifact-passing-mrfgl  artifact-example                                               child 'artifact-passing-mrfgl-2442905136' failed
 └---⚠ generate-artifact   whalesay          artifact-passing-mrfgl-2442905136  11s       Error (exit code 1): key unsupported: cannot get key for artifact location, because it is invalid
```

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
**Kubernetes v1.19.0**

What version of Argo Workflows are you running? 
has tested it on **argo v3.1.5 & v3.1.2**

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
**Docker**

Did this work in a previous version? I.e. is it a regression?
It worked in **argo v2.12.2**

## Trace code 
I have traced the code and found the possible root cause

So in argo v3.X, there is `ArtifactLocation` in `Artifact`  [workflow_types.go#L912](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L912)
```
type ArtifactLocation struct {
	// ArchiveLogs indicates if the container logs should be archived
	ArchiveLogs *bool `json:"archiveLogs,omitempty" protobuf:"varint,1,opt,name=archiveLogs"`

	// S3 contains S3 artifact location details
	S3 *S3Artifact `json:"s3,omitempty" protobuf:"bytes,2,opt,name=s3"`

	// Git contains git artifact location details
	Git *GitArtifact `json:"git,omitempty" protobuf:"bytes,3,opt,name=git"`

	// HTTP contains HTTP artifact location details
	HTTP *HTTPArtifact `json:"http,omitempty" protobuf:"bytes,4,opt,name=http"`

	// Artifactory contains artifactory artifact location details
	Artifactory *ArtifactoryArtifact `json:"artifactory,omitempty" protobuf:"bytes,5,opt,name=artifactory"`

	// HDFS contains HDFS artifact location details
	HDFS *HDFSArtifact `json:"hdfs,omitempty" protobuf:"bytes,6,opt,name=hdfs"`

	// Raw contains raw artifact location details
	Raw *RawArtifact `json:"raw,omitempty" protobuf:"bytes,7,opt,name=raw"`

	// OSS contains OSS artifact location details
	OSS *OSSArtifact `json:"oss,omitempty" protobuf:"bytes,8,opt,name=oss"`

	// GCS contains GCS artifact location details
	GCS *GCSArtifact `json:"gcs,omitempty" protobuf:"bytes,9,opt,name=gcs"`
}

func (a *ArtifactLocation) Get() ArtifactLocationType {
	if a == nil {
		return nil
	} else if a.Artifactory != nil {
		return a.Artifactory
	} else if a.Git != nil {
		return a.Git
	} else if a.GCS != nil {
		return a.GCS
	} else if a.HDFS != nil {
		return a.HDFS
	} else if a.HTTP != nil {
		return a.HTTP
	} else if a.OSS != nil {
		return a.OSS
	} else if a.Raw != nil {
		return a.Raw
	} else if a.S3 != nil {
		return a.S3
	}
	return nil
}
```
here, `a.Get()` will be nil, if it doesn't belong to any repository like the **artifact-passing example** above.

so when **executor**  try to load artifacts here in this function  [executor.go#L154](https://github.com/argoproj/argo-workflows/blob/master/workflow/executor/executor.go#L154) 
```
...
		log.Infof("Downloading artifact: %s", art.Name)

		if !art.HasLocationOrKey() {
			if art.Optional {
				log.Warnf("Ignoring optional artifact '%s' which was not supplied", art.Name)
				continue
			} else {
				return errors.Errorf(errors.CodeNotFound, "required artifact '%s' not supplied", art.Name)
			}
		}
		driverArt, err := we.newDriverArt(&art)
		if err != nil {
			return fmt.Errorf("failed to load artifact '%s': %w", art.Name, err)
		}
...
```

```
func (we *WorkflowExecutor) newDriverArt(art *wfv1.Artifact) (*wfv1.Artifact, error) {
	driverArt := art.DeepCopy()
	err := driverArt.Relocate(we.Template.ArchiveLocation)
	return driverArt, err
}
```
it does `err := driverArt.Relocate(we.Template.ArchiveLocation)`

and then the Relocate function at [workflow_types.go#L1024](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L1024) will try to call `a.GetKey()`
```
func (a *ArtifactLocation) Relocate(l *ArtifactLocation) error {
	if a.HasLocation() {
		return nil
	}
	if l == nil {
		return fmt.Errorf("template artifact location not set")
	}
	key, err := a.GetKey()
	if err != nil {
		return err
	}
	*a = *l.DeepCopy()
	return a.SetKey(key)
}
```
it turns out that `a.Get()` return nil and  return **the error** over here [workflow_types.go#L1046](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L1046)
```
func (a *ArtifactLocation) GetKey() (string, error) {
	v := a.Get()
	if v == nil {
		return "", fmt.Errorf("key unsupported: cannot get key for artifact location, because it is invalid")
	}
	return v.GetKey()
}
```

However, in argo v2.12, executor doesn't do **Relocate** 
Also,
GetKey() return "" if it doesn't have repository [workflow_types.go#L932](https://github.com/argoproj/argo-workflows/blob/v2.12.11/pkg/apis/workflow/v1alpha1/workflow_types.go#L932)
```
func (a *ArtifactLocation) GetKey() string {
	if a.S3 != nil {
		return a.S3.Key
	}
	if a.OSS != nil {
		return a.OSS.Key
	}
	if a.GCS != nil {
		return a.GCS.Key
	}
	return ""
}
```
There is no such error `key unsupported: cannot get key for artifact location, because it is invalid` in version 2.X 

BTW, I found the doc
> To run Argo workflows that use artifacts, you must configure and use an artifact repository.

Or does it mean, in 3.X version, argo won't support artifacts without repository anymore and some examples will be deprecated?

Thanks!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
