### ISSUE TITLE
Allow accessing status of the parent step in exit hook (new onExit)

### ISSUE THREAD

**Issue by AndriPL** [argoproj/argo-workflows#6511]
# Summary

Passing status as an argument to a new exit hook is not possible. It seems that during execution of hook, parent step is still running, so its has status is not defined yet. 

However as presented in official example (https://github.com/argoproj/argo-workflows/blob/master/examples/exit-handler-with-param.yaml), we can access outputs of the step, so logically status should also be accessible.

When I execute following workflow, exit hook receives following input:
```yaml
status: {{steps.step-1.status}}
message: hello world
```
So you can see, that we can pass outputs of the parent step, but cannot do the same with status.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: exit-handler-with-param-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      onExitTemplate enables workflow to pass the arguments (parameters/Artifacts) to exit handler template.
    workflows.argoproj.io/version: '>= 3.1.0'
    workflows.argoproj.io/verify.py: |
      assert status["phase"] == "Succeeded"
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: step-1
            template: output
            hooks:
              exit:
                template: exit
                arguments:
                  parameters:
                    - name: status
                      value: "{{steps.step-1.status}}"
                    - name: message
                      value: "{{steps.step-1.outputs.parameters.result}}"

    - name: output
      container:
        image: python:alpine3.6
        command: [sh, -c]
        args: ["echo -n hello world > /tmp/hello_world.txt"]
      outputs:
        parameters:
          - name: result
            valueFrom:
              default: "Foobar"   # Default value to use if retrieving valueFrom fails. If not provided workflow will fail instead
              path: /tmp/hello_world.txt
    
    - name: exit
      inputs:
        parameters:
          - name: status
          - name: message
      script:
        image: python:alpine3.6
        command: [ python ]
        source: |
          print("Status: {{inputs.parameters.status}}")
          print("Message: {{inputs.parameters.message}}")
```

# Use Cases

Status information could be useful for logic implemented in exit hook. For example detecting failed steps and sending a notification.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Accessing parent status on the step-level scope is a little complex.

**Comment by cr4zy-C** [comment]
Hi,
are there any new updates on this issue?
It would be great to be able to distinguish if a step was executed successfully or failed.

**Comment by jherman3** [comment]
In a similar vein, it'd be very helpful if we could use a `when:` clause in the exit hook so we can trigger the exit hook only when the status is not success.

Currently my work-around is to set continueOn failed and use a normal step instead of an exit hook, then have another step which calls `exit 1` conditionally on the first step's status to fail the overall workflow. This feature would make this much cleaner.

**Comment by LingClassmate** [comment]
For help! My workflow configuration is as follows:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: container-on-exit-
spec:
  entrypoint: step-template
  templates:
    - name: step-template
      steps:
        - - name: stepA
            template: echo1
            hooks: 
              exit:
                template: exitContainer
                arguments:
                    parameters:
                      - name: Containerstatus
                        value: "{{steps.stepA.status}}"
        - - name: stepB
            template: echo1
            hooks: 
              exit:
                template: exitContainer
                arguments:
                    parameters:
                      - name: Containerstatus
                        value: "{{steps.stepB.status}}"
            
    - name: echo1
      container:
        image: alpine:3.15
        command: [sh, -c]
        args: ["echo \"it was heads\" ;exit 1"]

    - name: exitContainer
      inputs:
        parameters:
          - name: Containerstatus
      container:
        image: alpine:3.15
        command: [sh, -c]
        args: ["echo  ContainerStatus: {{inputs.parameters.Containerstatus}}"]
```

**Comment by huiwq1990** [comment]
@sarabala1979 hi, I want to use workflow variables in step hooks, like: `steps.<STEPNAME>.id` `steps.<STEPNAME>.ip` `steps.<STEPNAME>.exitCode`. These parent variable will not be changed when the parent pod end, I think we can add them to local scope eralier. 
https://github.com/argoproj/argo-workflows/blob/0e981e44b40186071c6ea77168eedf080c543f07/workflow/controller/operator.go#L1054

**Comment by alexgeorgousis** [comment]
> In a similar vein, it'd be very helpful if we could use a `when:` clause in the exit hook so we can trigger the exit hook only when the status is not success.
> 
> Currently my work-around is to set continueOn failed and use a normal step instead of an exit hook, then have another step which calls `exit 1` conditionally on the first step's status to fail the overall workflow. This feature would make this much cleaner.

By the way, one issue with the `continueOn.failed: true` workaround is that if the workflow is stopped during that step it will become `Succeeded` instead of `Failed (Terminated)` (I've raised #11163 about this).

**Comment by Joibel** [comment]
This works on `main` (and has since v3.6.0), so I'm closing it.

The parent step's phase is pushed into the step/task scope just before the hook is dispatched, so both of these resolve today:

```yaml
steps:
  - - name: step-1
      template: output
      hooks:
        exit:
          template: exit
          # optionally only run the hook on failure
          expression: steps.step-1.status == "Failed"
          arguments:
            parameters:
              - name: status
                value: "{{steps.step-1.status}}"
```

`{{tasks.<name>.status}}` works the same way in a DAG. There are regression tests for both on main (`TestStepsTemplateOnExitStatusArgument`, `TestWorkflowOnExitWorkflowStatus`).

History for anyone hitting this on an older release: #9229 (v3.4.0) made exit-hook arguments resolve from the step/task scope, but resolution was skipped entirely when the step produced no outputs — which is exactly the failure case most people wanted. #13448 removed that restriction in v3.6.0. If you are on v3.4/v3.5 and the parameter comes through as a literal `{{steps.x.status}}`, upgrade.

@jherman3 — your ask for a conditional exit hook is covered by `expression:` on the hook (shown above); no `continueOn: failed` workaround needed.

@huiwq1990 — `steps.<name>.id` / `.ip` / `.exitCode` are still *not* available to a step's own hook (only `.status` and `outputs.parameters` / `outputs.artifacts` are seeded at that point). Please open a separate issue for those so it can be tracked on its own.
