### ISSUE TITLE
Intermittent "invalid cache key" error for step memoization

### ISSUE THREAD

**Issue by steve-marmalade** [argoproj/argo-workflows#6536]
## Summary 

Argo Workflows will intermittently crash with an "invalid cache key" error and then succeed upon retry. 

It appears that in the failure mode, the variable substitution step has not occurred yet, and so Argo is attempting to use the entire expression as the cache key (which contains invalid characters). Maybe there's a race condition somewhere?

## Diagnostics

What Kubernetes provider are you using? GKE

What version of Argo Workflows are you running? 3.1.5

What executor are you running? Emissary

Did this work in a previous version? I.e. is it a regression? No, this was also an issue in 3.1.0

https://user-images.githubusercontent.com/85196623/129223288-ec42b73f-5ccb-42bc-b24d-c682681e865a.mov

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@steve-marmalade Can you provide the reproducible workflow yaml? Can you share the controller log?

**Comment by steve-marmalade** [comment]
@sarabala1979  , here are the workflow controller logs:

```
time="2021-08-12T20:43:27.803Z" level=info msg="Skipped node batch-score-ml-qr4rg-2557347749 initialized Error (message: invalid cache key: txt-to-array-{{=sprig.regexReplaceAll('[_/:]', inputs.parameters['cache-key'], '-')}})" namespace=ml-model workflow=batch-score-ml-qr4rg
time="2021-08-12T20:43:27.803Z" level=error msg="Mark error node" error="step group deemed errored due to child batch-score-ml-qr4rg[2].txt-to-array error: invalid cache key: txt-to-array-{{=sprig.regexReplaceAll('[_/:]', inputs.parameters['cache-key'], '-')}}" namespace=ml-model nodeName="batch-score-ml-qr4rg[2]" workflow=batch-score-ml-qr4rg
time="2021-08-12T20:43:27.803Z" level=info msg="node batch-score-ml-qr4rg-3986073247 phase Running -> Error" namespace=ml-model workflow=batch-score-ml-qr4rg
```

Will get you a reproducible Workflow later today

**Comment by sarabala1979** [comment]
@steve-marmalade  looks like `inputs.parameters['cache-key']` is not in context. Please provide reproducible workflow

**Comment by steve-marmalade** [comment]
@sarabala1979 , here is a reproducible workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cache-key-test-
spec:
  entrypoint: run-all
  templates:
    - name: run-all
      steps:
        - - name: run-first
            template: run-first
        - - name: run-second
            template: run-second
            arguments:
              parameters:
                - name: cache-key
                  value: "{{steps.run-first.outputs.parameters.message}}"
    - name: run-first
      outputs:
        parameters:
          - name: message
            valueFrom:
              path: /tmp/message.txt
      script:
        image: bash
        command: [bash]
        source: |
          echo 'hello_world1' > /tmp/message.txt
    - name: run-second
      inputs:
        parameters:
          - name: cache-key
      memoize:
        key: "run-second-{{=sprig.regexReplaceAll('[_/:]', inputs.parameters['cache-key'], '-')}}"
        cache:
          configMap:
            name: cache-key-test
      script:
        image: bash
        command: [bash]
        source: |
          echo '{{inputs.parameters.cache-key}}'

```

I submitted this around 10 times and it failed with the error on 2 of them. 

In this video you can see that:

- The first time I retried the workflow it immediately failed again with the cache key error
- The second time I retried it ran successfully

https://user-images.githubusercontent.com/85196623/130671933-27c1eebb-6fae-4ab8-b9d2-71b2497e8863.mov
