### ISSUE TITLE
Invalid memory address or nil pointer dereference when using output from a different workflow template with steps

### ISSUE THREAD

**Issue by jbaez** [argoproj/argo-workflows#6550]
## Summary 
 Running a workflows that uses the output from another workflow with steps throws a `invalid memory address or nil pointer dereference`

What happened/what you expected to happen?

- Not sure if this is supposed to be used like this, but I expected to be able to use the resulting artifact from a workflow template (with steps) that sets the output from the last of it's steps.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
- Self hosted

What version of Argo Workflows are you running? 
- v3.1.6

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
- Default (Docker)

Did this work in a previous version? I.e. is it a regression?
- Didn't work on v3.1.2

### Issue can be reproduced with the following Workflow Templates

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-output-artifact
  namespace: argo
spec:
  templates:
  - name: start
    outputs:
      artifacts:
      - name: build_message
        valueFrom: '{{steps.build.outputs.artifacts.build_message}}'
    steps:
    - - name: generate
        template: generate
    - - name: build
        template: build
        arguments:
          parameters:
          - name: message
            value: '{{steps.generate.outputs.parameters.hello_param}}'

  - name: generate
    container:
      image: docker/whalesay:latest
      command:
      - sh
      - -c
      args:
      - echo 'hello' > /tmp/hello.txt
    outputs:
      parameters:
      - name: hello_param
        valueFrom:
          path: /tmp/hello.txt

  - name: build
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      env:
      - name: HELLO_MESSAGE
        value: '{{inputs.parameters.message}}'
      command:
      - sh
      - -c
      args:
      - echo "say ${HELLO_MESSAGE}" > /tmp/hello_message.txt
    outputs:
      artifacts:
      - name: build_message
        path: /tmp/hello_message.txt
```  

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: use-test-output-artifact
  namespace: argo
spec:
  entrypoint: start-test
  templates:
  - name: start-test
    dag:
      tasks:
      - name: get-message
        templateRef:
          name: test-output-artifact
          template: start
      - name: say
        template: say
        arguments:
          artifacts:
          - name: message
            from: '{{tasks.get-message.outputs.artifacts.build_message}}'
        dependencies:
        - get-message

  - name: say
    inputs:
      arguments:
      - name: message
        path: /tmp/message.txt
    container:
      name: main
      image: docker/whalesay:latest
      command:
      - sh
      - -c
      args:
      - cat /tmp/message.txt
```

Submitting `use-test-output-artifact` would throw the error and stay like this:
<img width="150" alt="Screenshot 2021-08-17 at 10 41 08" src="https://user-images.githubusercontent.com/1777543/129697508-c9d28886-72da-4d2a-ad51-90efdb930c88.png">

workflow controller logs
```bash
time="2021-08-17T08:35:22.248Z" level=info msg="Update workflows 200"
time="2021-08-17T08:35:22.249Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=117780442 workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:22.253Z" level=info msg="Create events 201"
time="2021-08-17T08:35:22.256Z" level=info msg="Create events 201"
time="2021-08-17T08:35:22.257Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/use-test-output-artifact-q5l9z-3518499571/labelPodCompleted
time="2021-08-17T08:35:22.259Z" level=info msg="Create events 201"
time="2021-08-17T08:35:22.264Z" level=info msg="Create events 201"
time="2021-08-17T08:35:22.265Z" level=info msg="Patch pods 200"
time="2021-08-17T08:35:26.852Z" level=info msg="Get leases 200"
time="2021-08-17T08:35:26.866Z" level=info msg="Update leases 200"
time="2021-08-17T08:35:31.870Z" level=info msg="Get leases 200"
time="2021-08-17T08:35:31.879Z" level=info msg="Update leases 200"
time="2021-08-17T08:35:32.238Z" level=info msg="Processing workflow" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.238Z" level=info msg="Updating node use-test-output-artifact-q5l9z-576956665 exit code 0" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.238Z" level=info msg="Setting node use-test-output-artifact-q5l9z-576956665 outputs: {\"artifacts\":[{\"name\":\"build_message\",\"path\":\"/tmp/hello_message.txt\",\"s3\":{\"key\":\"use-test-output-artifact-q5l9z/use-test-output-artifact-q5l9z-576956665/build_message.tgz\"}}]}" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.238Z" level=info msg="Updating node use-test-output-artifact-q5l9z-576956665 status Pending -> Succeeded" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.239Z" level=info msg="SG Outbound nodes of use-test-output-artifact-q5l9z-3518499571 are [use-test-output-artifact-q5l9z-3518499571]" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.240Z" level=info msg="Step group node use-test-output-artifact-q5l9z-1147742991 successful" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.240Z" level=info msg="node use-test-output-artifact-q5l9z-1147742991 phase Running -> Succeeded" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.240Z" level=info msg="node use-test-output-artifact-q5l9z-1147742991 finished: 2021-08-17 08:35:32.240086778 +0000 UTC" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.240Z" level=info msg="Outbound nodes of use-test-output-artifact-q5l9z-576956665 is [use-test-output-artifact-q5l9z-576956665]" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.240Z" level=info msg="Outbound nodes of use-test-output-artifact-q5l9z-3379466504 is [use-test-output-artifact-q5l9z-576956665]" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.240Z" level=error msg="Recovered from panic" namespace=argo r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 215 [running]:\nruntime/debug.Stack(0xc032a5c366, 0x1c78160, 0x2e4fd00)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2(0xc000e8fb80, 0x21ad720, 0xc000058020)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:183 +0xd1\npanic(0x1c78160, 0x2e4fd00)\n\t/usr/local/go/src/runtime/panic.go:975 +0x47a\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.getTemplateOutputsFromScope(0xc000fc3b00, 0xc000c1ded0, 0x2a, 0xc000fc3b00, 0xc00102a2c0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2346 +0x1d8\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc000e8fb80, 0x21ad720, 0xc000058020, 0xc00059c2a0, 0x2a, 0xc000812880, 0xc000eb6780, 0x6, 0xc000fc3b00, 0x216d8e0, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:146 +0x5e5\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000e8fb80, 0x21ad720, 0xc000058020, 0xc00059c2a0, 0x2a, 0x216d8e0, 0xc0004aec40, 0xc0009afa40, 0x0, 0x0, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1727 +0x2338\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc000e8fb80, 0x21ad720, 0xc000058020, 0xc0001af6c0, 0xc000d3b901, 0xb)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:460 +0x93d\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc000e8fb80, 0x21ad720, 0xc000058020, 0xc0001af6c0, 0xc000eb66d0, 0x3)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:390 +0x4c5\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc000e8fb80, 0x21ad720, 0xc000058020, 0xc000992900, 0x1e, 0xc0009afa40, 0xc000eb6600, 0x6, 0xc000fc2480, 0x216da60, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:246 +0x334\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000e8fb80, 0x21ad720, 0xc000058020, 0xc000992900, 0x1e, 0x216da60, 0xc000aa2600, 0xc0009afa00, 0x0, 0x0, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1733 +0x14f7\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc000e8fb80, 0x21ad720, 0xc000058020)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:331 +0xf05\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0001ad400, 0x21ad720, 0xc000058020, 0x0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:727 +0x7fb\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0001ad400)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:648 +0x9b\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000ad6130)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:155 +0x5f\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000ad6130, 0x215f120, 0xc0008fc180, 0x1, 0xc000596240)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:156 +0xad\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ad6130, 0x3b9aca00, 0x0, 0x1, 0xc000596240)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:133 +0x98\nk8s.io/apimachinery/pkg/util/wait.Until(0xc000ad6130, 0x3b9aca00, 0xc000596240)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:90 +0x4d\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:298 +0x48a\n" workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.240Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.240Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.240Z" level=info msg="Marking workflow completed" namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.240Z" level=info msg="Checking daemoned children of " namespace=argo workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.247Z" level=info msg="Create events 201"
time="2021-08-17T08:35:32.252Z" level=info msg="Update workflows 200"
time="2021-08-17T08:35:32.253Z" level=info msg="Workflow update successful" namespace=argo phase=Error resourceVersion=117780511 workflow=use-test-output-artifact-q5l9z
time="2021-08-17T08:35:32.259Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/use-test-output-artifact-q5l9z-576956665/labelPodCompleted
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
