### ISSUE TITLE
Regression on Optional GCS Artifact

### ISSUE THREAD

**Issue by AntoineDao** [argoproj/argo-workflows#6576]
## Summary 

What happened/what you expected to happen?

Optional GCS artifacts had been fixed and tested manually in #6393. It seems that some changes in #6302 has caused a regression on this behaviour.

This bug is reproducible by running the following two workflows:

### Failing Workflow
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: gcs-test-
  labels:
    workflows.argoproj.io/container-runtime-executor: emissary
    disposable: 'true'
spec:
  entrypoint: gcs-test
  templates:
    - name: gcs-test
      inputs:
        artifacts:
          - name: my-art
            path: /my-artifact
            optional: true
            gcs:
              bucket: pollination-public
              key: blobs/argo-test/not-exists.txt
              serviceAccountKeySecret:
                name: gcs-creds
                key: serviceAccountKey
      container:
        image: ubuntu:latest
        command: [sh, -c]
        args: ["echo 'no artifact :('"]
```

### Working Workflow
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: gcs-test-
  labels:
    workflows.argoproj.io/container-runtime-executor: emissary
    disposable: 'true'
spec:
  entrypoint: gcs-test
  templates:
    - name: gcs-test
      inputs:
        artifacts:
          - name: my-art
            path: /my-artifact
            optional: true
            http:
              url: ''
      container:
        image: ubuntu:latest
        command: [sh, -c]
        args: ["echo 'no artifact :('"]
```
#### Solution/Cause
I'm pretty sure the issue is caused by a misunderstanding on the `retry` API and the `bool` value to provide to it. The `isTransientGCSErr` function works correctly and the unit tests make sense, however the `Load` and `Save` functions should return `!isTransientGCSErr(err), err` instead of `isTransientGCSErr(err), err`.

https://github.com/argoproj/argo-workflows/blob/2df5f66a33e197389ae906e6f7b8fb271f49c54c/workflow/artifacts/gcs/gcs.go#L100-L119

https://github.com/argoproj/argo-workflows/blob/2df5f66a33e197389ae906e6f7b8fb271f49c54c/workflow/artifacts/gcs/gcs.go#L203-L220

This is because the `Backoff` function wrapping the `Load` and `Save` calls expects the `bool` to indicate whether to retry or not where: `true` = don't retry and `false` = retry.

https://github.com/argoproj/argo-workflows/blob/2df5f66a33e197389ae906e6f7b8fb271f49c54c/util/wait/backoff.go#L9-L26

I'll propose a PR in the next hour or so with some proposed changes.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
- GKE
- 
What version of Argo Workflows are you running? 
- custom fork from argo `master`

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
- Emissary

Did this work in a previous version? I.e. is it a regression?
- Yes this worked when #6393 was merged in

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
