### ISSUE TITLE
Workflow expression not behaving as expected

### ISSUE THREAD

**Issue by chrisk314** [argoproj/argo-workflows#6579]
## Summary 

Hi, I just started using Argo. So far it's working very nicely for my use case so thanks for all the hard work!

I'm struggling on one point though. As far as I can tell from looking at examples what I'm attempting should work. I'm attempting to use an expression to set the value of a parameter for a workflow step. I have a step "job-pre" which runs first. I am then attempting to use the exit status of the template which is executed in this step to set the value of a parameter for a subsequent step "job-post".

The problem is that rather than the template expression being evaluated to set the value of the parameter, instead the parameter is just being set as a string containing the template expression. So the output of the `echo` command in the below example workflow is: 
```
status was: {{=asInt(steps['job-pre'].exitCode) == 0 ? 'succeeded' : 'failed'}}
```
whereas I expect
```
status was: succeeded
```

Here is a minimal example workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-job-
spec:
  entrypoint: job-steps
  templates:
  - name: job-steps
    steps:
    - - name: job-pre
        template: job-pre

    - - name: job-post
        template: job-post
        arguments:
          parameters:
          - name: status
            value: "{{=asInt(steps['job-pre'].exitCode) == 0 ? 'succeeded' : 'failed'}}"

  - name: job-pre
    container:
      image: alpine:latest
      command: ["echo"]
      args: ["hello"]

  - name: job-post
    inputs:
      parameters:
      - name: status
    container:
      image: alpine:latest
      command: ["echo"]
      args: ["status was: {{inputs.parameters.status}}"]
```

In the documentation on worklfow variables [here](https://argoproj.github.io/argo-workflows/variables/) it is stated:
> Some fields in a workflow specification allow for variable references which are automatically substituted by Argo.

So my guess is that `step.arguments.parameters.value` is not one such field. The problem then is one of documentation. To me an Argo template looks similar to a Jinja template. WIth a Jinja template I can use template expressions anywhere. WIthout having explicit guidance about where template expressions can or cannot be used it becomes a matter of trial and error.

Is there a more detailed explanation somewhere? Furthermore, if it's not possible to set a parameter value in this way, then what is the best approach to achieve what I'm trying to do? Of course I can just pass the exit code and then have logic in the `job-post` command which will do the transformation; however, I was hoping it would be possible to pass the value directly using the templating system.

## Diagnostics
Kubernetes version: Microk8s 1.20.9

Argo workflows version: 3.1.6

Executor: PNS

No previous version for reference.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
