### ISSUE TITLE
Can not use named pipe binding as volume in Windows docker container when deployed with Argo

### ISSUE THREAD

**Issue by Tarjei400** [argoproj/argo-workflows#6583]
## Summary 

Can not use named pipe binding for Windows docker container when deployed with Argo
When mounting named pipeline (manifests below) there is an error on mounting with wait container. 
Main container gets docker named pipe correctly and can execute commands properly, however argo executor doesnt seem to be create and hence in Argo UI workflow seems pending forever.

## Diagnostics

I need to run docker client dontainer inside kubermetes in order to be able to build docker images. It is aparently feasable using windows docker image, all that has to be done is to bind named pipeline using a volume. It seems that for some reason, argoexec is binding docker-sock volume using same pipeline, I think the issue i am getting is beacouse volume is already bound and argo tries to resolve path name conflicts (describe in artifacts section)

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
AWS EKS

What version of Argo Workflows are you running? 
v3.0.10

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker

Did this work in a previous version? I.e. is it a regression?
This is first time I am testing this.

Are you pasting thousands of log lines? That's too much information. 

I tested if binding named pipeles works at all and I tested it simply by deploying a pod: 
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app: busybox1
spec:
  containers:
    - image: docker:20.10.8-windowsservercore-1809
      command: ["cmd", "/S", "/C"]
      args: ["ping -t localhost"]
      imagePullPolicy: IfNotPresent
      name: busybox

      volumeMounts:
        - mountPath: \\.\pipe\docker_engine
          name: docker-pipe
  nodeSelector:
    kubernetes.io/os: windows
    kubernetes.io/arch: amd64

  volumes:
    - name: docker-pipe
      hostPath:
        path: \\.\pipe\docker_engine
    - name: docker-sock
      emptyDir: {}
  restartPolicy: Always

```

if you exec into a container and type docker ps, it works a expected.

Workflow yaml which doesnt work

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: docker-named-pipe
spec:
  entrypoint: docker-named-pipe-example

  volumes:
    - name: docker-pipe
      hostPath:
        path: \\.\pipe\docker_engine


  templates:
    - name: docker-named-pipe-example
      container:
        image: docker:20.10.8-windowsservercore-1809
        command: ["cmd", "/S", "/C"]
        args: ["docker ps"]
        volumeMounts:
          - mountPath: \\.\pipe\docker_engine
            name: docker-pipe


      nodeSelector:
        kubernetes.io/os: windows
        kubernetes.io/arch: amd64
```

When submitting a workflow I get following error :
```
 Error: Error response from daemon: invalid volume specification: '\\.\pipe\docker_engine:c:/mainctrfs/\\.\pipe\docker_engine'
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by ad22** [comment]
I do see this behavior on the exit handler on my test, even though the main container completed successfully. See below:
![image](https://user-images.githubusercontent.com/9344284/130694049-95e4e34e-2d35-4c8a-9e73-2733ac5420c2.png)

**Comment by Tarjei400** [comment]
Yes I noticed later that main container exit properly, I printed something I got confused, however it still stays pending in ui. I think it's not desired behaviour right? My best guess is that there is part of code which changes volume path in case there are duplicate mounts in a pod, hence named pipe cannot be mounted 2 times.

**Comment by alexec** [comment]
@argoproj/argo-windows can help maybe?

**Comment by lippertmarkus** [comment]
I think we should just skip named pipes when determining which volume mounts of the main container we add to the wait/init containers. I suggest adding a check like in upstream k8s: https://github.com/ddebroy/kubernetes/blob/5da66fd65fef91ac23cd3951cdf513881a238acd/pkg/volume/util/util.go#L951-L960

and use it here: https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/workflowpod.go#L908 and here: https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/workflowpod.go#L979

to skip volumes which are pipes.

**Comment by ad22** [comment]
Created #6704

**Comment by ad22** [comment]
After running some more experiments - I do not think a patch is required to fix this. 
Please try quoting the pipe in the YAML.

Example:

Use

``` 
 - name: docker-pipe
    hostPath:
      path: "\\\\.\\pipe\\docker-engine"
```

instead of 

```
    - name: docker-pipe
      hostPath:
        path: \\.\pipe\docker_engine
```

**Comment by lippertmarkus** [comment]
That would be even better, thanks for testing!

**Comment by Tarjei400** [comment]
Sorry, I doubt it's working, I tried it before in all combinations (stringified, not stringified) output is always the same
![image](https://user-images.githubusercontent.com/1921727/133050837-663b4d43-09d5-4cd1-9957-6268f26edf00.png)

```
  volumes:
    - name: docker-pipe
      hostPath:
        path: "\\\\.\\pipe\\docker_engine"


  templates:
    - name: dind-windows-sidecar-example
      container:
        image: docker:20.10.8-windowsservercore-1809
        command: ["cmd", "/S", "/C"]
        args: ["docker info"]
        volumeMounts:
          - mountPath: "\\\\.\\pipe\\docker_engine"
            name: docker-pipe

```
