### ISSUE TITLE
Invalid openAPIV3Schema fields on full CRDs

### ISSUE THREAD

**Issue by dan-j** [argoproj/argo-workflows#6588]
## Summary 

What happened/what you expected to happen?

I should be able to apply the CRD manifests in `manifests/base/crds/full`. Instead I get numerous errors that `inline.type` and `items.items` are required.

For `inline`, this is down to it being declared as: `inline: {}` instead of:

```
inline:
  type: object
```

For `items.items`, this is down to `steps` being:

```
steps:
  type: array
  items:
   type: array
```

where it's meant to be:

```
steps:
  type: array
  items:
    type: array
    items:
      type: object
```

## Diagnostics

What Kubernetes provider are you using? **GKE**

What version of Argo Workflows are you running? **v3.2.0-rc1**

What executor are you running? **N/A**

Did this work in a previous version? I.e. is it a regression? **This is the first time I'm trying out Argo, I'm not sure without checking**

Are you pasting thousands of log lines? That's too much information. 

```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
kustomize build manifests/base/crds/full | kubectl create -f-
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
