### ISSUE TITLE
Unable to create service account using manifest (if namespaces are different)

### ISSUE THREAD

**Issue by ameypant13** [argoproj/argo-workflows#6591]
## Summary 
I am trying to create service account using workflow. The workflow runs successfully but the serviceaccount is not created.
Below is my workflow
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scripts-bash-
spec:
  entrypoint: create
  serviceAccountName: kaas-tests
  templates:
  - name: create
    resource:
      action: create
      setOwnerReference: true
      manifest: |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: {{workflow.name}}-sa
          namespace: default
```

 Argo Workflows version:             v3.1.6
Kubernetes version:                     v1.20

```bash
#Logs from the workflow
$ argo logs scripts-bash-wdtzz
scripts-bash-wdtzz: time="2021-08-24T06:55:06.845Z" level=info msg="Starting Workflow Executor" executorType=pns version=v3.1.6
scripts-bash-wdtzz: time="2021-08-24T06:55:06.848Z" level=info msg="Creating PNS executor (namespace: acquia-system, pod: scripts-bash-wdtzz, pid: 6)"
scripts-bash-wdtzz: time="2021-08-24T06:55:06.848Z" level=info msg="Creating a K8sAPI executor"
scripts-bash-wdtzz: time="2021-08-24T06:55:06.848Z" level=info msg="Executor initialized" includeScriptOutput=false namespace=acquia-system podName=scripts-bash-wdtzz template="{\"name\":\"create\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"resource\":{\"action\":\"create\",\"manifest\":\"apiVersion: v1\\nkind: ServiceAccount\\nmetadata:\\n  name: scripts-bash-wdtzz-sa\\n  namespace: default\\n  ownerReferences:\\n  - apiVersion: argoproj.io/v1alpha1\\n    blockOwnerDeletion: true\\n    controller: true\\n    kind: Workflow\\n    name: scripts-bash-wdtzz\\n    uid: c1d85415-d882-4f7b-bcd2-2e643e9d4199\\n\",\"setOwnerReference\":true}}" version="&Version{Version:v3.1.6,BuildDate:2021-08-12T23:41:46Z,GitCommit:14e1278572b28d8b1854858ce7de355ce60199c9,GitTag:v3.1.6,GitTreeState:clean,GoVersion:go1.15.7,Compiler:gc,Platform:linux/amd64,}"
scripts-bash-wdtzz: time="2021-08-24T06:55:06.848Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
scripts-bash-wdtzz: time="2021-08-24T06:55:06.849Z" level=info msg="kubectl create -f /tmp/manifest.yaml -o json"
scripts-bash-wdtzz: time="2021-08-24T06:55:08.577Z" level=info msg="Resource: default/serviceaccount./scripts-bash-wdtzz-sa. SelfLink: api/v1/namespaces/default/serviceaccounts/scripts-bash-wdtzz-sa"
scripts-bash-wdtzz: time="2021-08-24T06:55:08.577Z" level=info msg="Starting SIGUSR2 signal monitor"
scripts-bash-wdtzz: time="2021-08-24T06:55:08.577Z" level=info msg="No output parameters"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
