### ISSUE TITLE
RBAC SSO enabled argo can read secret

### ISSUE THREAD

**Issue by boehb-efs** [argoproj/argo-workflows#6610]
## Summary 

What happened/what you expected to happen?

I have argo installed (3.1.8, via helm) with RBAC SSO enabled. I want to have 2 User-Groups (ServiceAccounts):
sd
* user who can only handle the basics
* admin-user who can also read argo-server-sso-Secret which contains ClientID and ClientSecret for OIDC

Every logged in user should be in group 'user', only those in OIDC-group 'ADMIN' should be in 'admin-user'.

Therefore I configured the following:
```
### User
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
  namespace: argo
  annotations:
    # always true, if user is logged in
    workflows.argoproj.io/rbac-rule: "1 < 2"
    workflows.argoproj.io/rbac-rule-precedence: "0"

### Admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: argo
  annotations:
    # only true, if user is in group 'ADMIN'
    workflows.argoproj.io/rbac-rule: "'/ADMIN' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
```

Once I'm logged in as user (as printed in User Info), I expected the following workflow to fail:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: print-secret
  namespace: argo
spec:
  entrypoint: print-secret
  templates:
    - name: print-secret
      container:
        name: main
        image: 'alpine'
        command:
          - sh
          - '-c'
        args:
          - ' echo $CLIENT_SECRET; '
        env:
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: argo-server-sso
                key: clientSecret
```

However it did print the secret.

## Diagnostics

```
$ kubectl auth can-i --list --as=system:serviceaccount:argo:user -n argo

Resources                                       Non-Resource URLs                     Resource Names   Verbs
*.*                                             []                                    []               [*]
                                                [*]                                   []               [*]
cronworkflows.argoproj.io                       []                                    []               [create get list watch update patch delete]
eventsources.argoproj.io                        []                                    []               [create get list watch update patch delete]
sensors.argoproj.io                             []                                    []               [create get list watch update patch delete]
workfloweventbindings.argoproj.io               []                                    []               [create get list watch update patch delete]
workflows.argoproj.io                           []                                    []               [create get list watch update patch delete]
workflowtemplates.argoproj.io                   []                                    []               [create get list watch update patch delete]
selfsubjectaccessreviews.authorization.k8s.io   []                                    []               [create]
selfsubjectrulesreviews.authorization.k8s.io    []                                    []               [create]
pods/exec                                       []                                    []               [get list watch delete]
pods/log                                        []                                    []               [get list watch delete]
pods                                            []                                    []               [get list watch delete]
serviceaccounts                                 []                                    []               [get list]
secrets                                         []                                    [sso]            [get update create]
events                                          []                                    []               [get watch list create patch]
configmaps                                      []                                    []               [get watch list]
                                                [/.well-known/openid-configuration]   []               [get]
                                                [/api/*]                              []               [get]
                                                [/api]                                []               [get]
                                                [/apis/*]                             []               [get]
                                                [/apis]                               []               [get]
                                                [/healthz]                            []               [get]
                                                [/healthz]                            []               [get]
                                                [/livez]                              []               [get]
                                                [/livez]                              []               [get]
                                                [/openapi/*]                          []               [get]
                                                [/openapi]                            []               [get]
                                                [/openid/v1/jwks]                     []               [get]
                                                [/readyz]                             []               [get]
                                                [/readyz]                             []               [get]
                                                [/version/]                           []               [get]
                                                [/version/]                           []               [get]
                                                [/version]                            []               [get]
                                                [/version]                            []               [get]
```

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

3.1.8

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

k8sapi

Did this work in a previous version? I.e. is it a regression?

installed on clean cluster

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
