### ISSUE TITLE
podMetadata and WorkflowTemplate do not work together 

### ISSUE THREAD

**Issue by mbruner** [argoproj/argo-workflows#6613]
## Summary 

Meta information from `podMetadata` defined in WorkflowTemplate is not applied to pods from workflow.

## Diagnostics

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: simple-wft
spec:
  entrypoint: whalesay
  workflowMetadata:
    labels:
      token: token
  podMetadata:
    labels:
      token: token
  arguments:
    parameters:
      - name: message
        value: hello world
      - name: token
        value: 123
  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

Workflow definition:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-workflow-
spec:
  arguments:
    parameters:
        - name: message
          value: hello world
        - name: token
          value: 123
  workflowTemplateRef:
    name: simple-wft
```
Pod description:
```
❯ kdp example-workflow-fxbqs
Name:         example-workflow-fxbqs
Namespace:    argo
...
Labels:       workflows.argoproj.io/completed=true
              workflows.argoproj.io/workflow=example-workflow-fxbqs
```

What Kubernetes provider are you using? 
EKS
What version of Argo Workflows are you running? 
3.0.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
