### ISSUE TITLE
What it has been rendered on DAG UI seems different from the execution result.

### ISSUE THREAD

**Issue by tkyz** [argoproj/argo-workflows#6625]
## Sumally

Is it supposed to have grp-2 > grp-2-main > grp-2-status on DAG UI as well after grp-1-main-status went successful? 
since it’s an auto job workflow that grp-1 runs followed by grp-2 execution depends on the status.

## Diagnosis

- Argo Workflow Version: v3.1.5

When run the attached yaml (wf-for-issues.yml), 'grp-2' node did not appear in the workflow DAG UI. 
grp-1 has two tasks: success and echo status. 
grp-2 has two tasks: failure and echo status. *grp-2 has dependency with grp-1. 

1. main.grp-1.grp-1-main was processed successfully. 
2. main.grp-1.grp-1-main-status was skipped, as grp-1-main’s status was not Failed or Errored. 
3. main.grp-2 should’ve been run automatically since it has dependency with the status of main.grp-1. 
4.  'grp-2' node did not appear in the workflow DAG UI. (Even though We get the echo "grp-2-main is Failed".)

wf-for-issues.yml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-sample-

spec:

  entrypoint: main

  templates:

    # ----------------------------------------------------------------
    # containers

    # success
    - name: exit0
      container:
        image: alpine:latest
        imagePullPolicy: Always
        command: [sh, -c]
        args: ["echo 0; exit 0"]

    # error
    - name: exit1
      container:
        image: alpine:latest
        imagePullPolicy: Always
        command: [sh, -c]
        args: ["echo 1; exit 1"]

     # echo
    - name: echo
      inputs:
        parameters:
          - name: taskname
          - name: exitstatus
      container:
        image: alpine:latest
        imagePullPolicy: Always
        command: [sh, -c]
        args: ["echo {{inputs.parameters.taskname}} is {{inputs.parameters.exitstatus}}"]

    # ----------------------------------------------------------------
    # dag

    - name: main
      dag:
        tasks:

          - name: grp-1
            template: grp-1

          - name: grp-2
            template: grp-2
            depends: >-
              grp-1

    - name: grp-1
      dag:
        tasks:

          - name: grp-1-main
            template: exit0

          - name: grp-1-main-status
            template: echo
            arguments:
              parameters:
                - name: taskname
                  value: 'grp-1-main'
                - name: exitstatus
                  value: "{{tasks.grp-1-main.status}}"
            depends: >-
              grp-1-main.Failed || grp-1-main.Errored

    - name: grp-2
      dag:
        tasks:

          - name: grp-2-main
            template: exit1

          - name: grp-2-main-status
            template: echo
            arguments:
              parameters:
                - name: taskname
                  value: 'grp-2-main'
                - name: exitstatus
                  value: "{{tasks.grp-2-main.status}}"
            depends: >-
              grp-2-main.Failed || grp-2-main.Errored
```

![dag-ui-screenshot](https://user-images.githubusercontent.com/36824716/131443806-e3666db5-e167-4991-84a7-1f94a9efd8b7.png)
![gcp-log-screenshot](https://user-images.githubusercontent.com/36824716/131443810-7ebb972e-a5d8-44de-9791-41d8411b4fe9.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
