### ISSUE TITLE
token not valid for running mode - SSO 

### ISSUE THREAD

**Issue by gardnerdev** [argoproj/argo-workflows#6634]
## Summary 

This issue is related to [https://github.com/argoproj/argo-workflows/issues/4991](https://github.com/argoproj/argo-workflows/issues/4991) which was closed, I assume by mistake.

Argo UI shows error 

> {"code":16,"message":"token not valid for running mode”} 

after trying  to complete  SSO user authentication.

Kubernetes provider: 
Amazon EKS

Argo workflows version:
3.1.1

Executor:
k8sapi

I have added following configuration: 

```yaml
sso: |
      issuer: https://sso-whatever.com
      clientId:
        name: client-id-secret
        key: client-id-key
      clientSecret:
        name: client-secret-secret
        key: client-secret-key
      redirectUrl: https://my-argo-instance.whatever.com/oauth2/callback/
      scopes:
       - openid
      rbac:
        enabled: true
```

My deployment configuration:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - args:
        - server
        - --auth-mode
        - sso
        image: argoproj/argocli:v3.1.1
        name: argo-server
        ports:
        - containerPort: 2746
          name: web
        readinessProbe:
          httpGet:
            path: /
            port: 2746
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 20
        securityContext:
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: argo-server
      volumes:
      - emptyDir: {}
        name: tmp

```

argo-server logs 
```
time="2021-08-31T14:40:22.222Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-08-31T14:40:22Z" grpc.time_ms=0.044 span.kind=server system=grpc
time="2021-08-31T14:40:25.286Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-08-31T14:40:25Z" grpc.time_ms=0.041 span.kind=server system=grpc

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
