### ISSUE TITLE
startedAt, finishAt, id, ip variables not available in DAG and step templates

### ISSUE THREAD

**Issue by BartoszJaroszkowski** [argoproj/argo-workflows#6641]
## Summary 

I expected to be able to use startedAt, finishAt, id, ip variables within step or DAG templates as stated in documentation [here](https://argoproj.github.io/argo-workflows/variables/#steps-templates) and [here](https://argoproj.github.io/argo-workflows/variables/#dag-templates).  Instead I am unable to submit workflow whenever any of those variables is used. Below I include minimal working example for both cases. Note that both of them work if the aforementioned variables are replaced with status or exitCode.

### Steps
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-timing-
spec:
  entrypoint: steps-timing
  templates:

  - name: steps-timing
    steps:
      - - name: process
          template: wait

      - - name: print-processing-time
          template: printer
          arguments:
            parameters:
            - name: processing-start
              value: "{{steps.process.startedAt}}"

  - name: wait
    container:
      image: alpine:3.7
      command: [sleep, "5"]
  
  - name: printer
    inputs:
      parameters:
        - name: processing-start
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.processing-start}}"]
```

### DAG
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-timing-
spec:
  entrypoint: dag-timing
  templates:

  - name: dag-timing
    dag:
      tasks:
      - name: process
        template: wait

      - name: print-processing-time
        depends: "process"
        template: printer
        arguments:
          parameters:
          - name: processing-start
            value: "{{tasks.process.startedAt}}"

  - name: wait
    container:
      image: alpine:3.7
      command: [sleep, "5"]
  
  - name: printer
    inputs:
      parameters:
        - name: processing-start
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.processing-start}}"]
```

## Diagnostics

Kubernetes:  `v1.21.4` via microk8s

argo: `v3.2.0-rc1`

executor: docker

As far as I can tell from previous bug reports [here](https://github.com/argoproj/argo-workflows/issues/4034) and [here](https://github.com/argoproj/argo-workflows/issues/4270) it has never actually worked.
