### ISSUE TITLE
Output artifacts used in withParam

### ISSUE THREAD

**Issue by zewelor** [argoproj/argo-workflows#6642]
## Summary 

Hi

I want to use step output artifacts, containing json array, to loop over tasks, using withParam. Error I'm receving:

```
withParam value could not be parsed as a JSON list: {{steps.generate-product-ids.outputs.artifacts.product_ids}}: invalid character '{' looking for beginning of object key string
```

Steps I'm using:

```
        steps:
          - - name: generate-product-ids
              template: generate-product-ids
          - - name: per-batch-fetch-and-send
              template: fetch-product-data-and-send
              arguments:
                parameters:
                  - name: src_ids
                    value: '{{item}}'
              withParam: '{{steps.generate-product-ids.outputs.artifacts.product_ids}}'
```

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? Selfhosted 1.19

What version of Argo Workflows are you running? 3.1.8

What executor are you running? Docker

Did this work in a previous version? I.e. is it a regression? Did not check on earlier version

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Error says "withParam" , but YAML says "withItem". Please can you double check YAML?

**Comment by zewelor** [comment]
Fixed yaml, its copied from live argo workflow instance. I did also test withItem, thats why it was left there.

**Comment by alexec** [comment]
Can you please attach the complete workflow.

**Comment by aaronmell** [comment]
Here's a very simple example that fails with
withParam value could not be parsed as a JSON list: {{tasks.create-artifact.outputs.artifacts.output}}: invalid character '{' looking for beginning of object key string

`
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-artifact
spec:
  entrypoint: test-pipeline
  templates:
    - name: create-artifact
      container:
        image: alpine:latest
        command: [sh, -c]
        args:
          - > 
            echo '{"array":[{"foo":"bar"},{"bar":"baz"}]}' | tee /tmp/output.json;
      outputs:
        artifacts:
          - name: output
            path: /tmp/output.json
    - name: do-nothing
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo nothing"]
    - name: test-pipeline
      dag:
        tasks:
          - name: create-artifact
            template: create-artifact
          - name: output
            template: do-nothing
            depends: 'create-artifact'
            withParam: '{{tasks.create-artifact.outputs.artifacts.output}}'
`

**Comment by aaronmell** [comment]
@alexec Can you reopen this? I have provided a test workflow the reproduces the issue.

**Comment by zewelor** [comment]
Bot please take a look at: https://github.com/argoproj/argo-workflows/issues/6642#issuecomment-918375480 :D

**Comment by alexec** [comment]
This works for me:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-artifact-
spec:
  entrypoint: test-pipeline
  templates:
    - name: create-artifact
      container:
        image: alpine:latest
        command: [sh, -c]
        args:
          - >
            echo '[{"foo":"bar"},{"bar":"baz"}]'
    - name: do-nothing
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo nothing"]
    - name: test-pipeline
      dag:
        tasks:
          - name: create-artifact
            template: create-artifact
          - name: output
            template: do-nothing
            depends: 'create-artifact'
            withParam: '{{tasks.create-artifact.outputs.result}}'
```

I'm not sure that `.artifacts.` has been implemented.
