### ISSUE TITLE
argo run failed: Permission denied

### ISSUE THREAD

**Issue by lianxmfor** [argoproj/argo-workflows#6643]
## Summary 

What happened/what you expected to happen?

run argo job failed: `bash: /argo/staging/script: Permission denied`

## Diagnostics

What Kubernetes provider are you using? 

docker desktop for mac.
```shell
(base) ➜  kubectl version 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

What version of Argo Workflows are you running? 

```text
(base) ➜  argo version
argo: v3.1.5
  BuildDate: 2021-08-04T07:03:32Z
  GitCommit: 3dbee0ec368f3ea8c31f49c8b1a4617cc32bcce9
  GitTreeState: clean
  GitTag: v3.1.5
  GoVersion: go1.15.7
  Compiler: gc
  Platform: darwin/amd64
```

Are you pasting thousands of log lines? That's too much information. 

```bash
$ argo -n argo submit workflow.yaml 
$ kubectl -n argo logs seldon-batch-process-2052519094  -c main
bash: /argo/staging/script: Permission denied
```

---

**Message from the maintainers**:

here is my workflow yaml file:

```yaml
# Source: seldon-batch-workflow/templates/workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: seldon-batch-process
  namespace: argo
spec:
  entrypoint: seldon-batch-process
  volumeClaimTemplates:
  - metadata:
      name: "seldon-pvc"
      ownerReferences:
      - apiVersion: argoproj.io/v1alpha1
        blockOwnerDeletion: true
        kind: Workflow
        name: "{{workflow.name}}"
        uid: "{{workflow.uid}}"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "2Mi"
  volumes:
  - name: rclone-config
    secret:
      secretName: "rclone-config-secret"
  templates:
  - name: seldon-batch-process
    steps:
    - - name: create-seldon-resource
        template: create-seldon-resource-template
    - - name: wait-seldon-resource
        template: wait-seldon-resource-template
    - - name: download-object-store
        template: download-object-store-template
    - - name: process-batch-inputs
        template: process-batch-inputs-template
    - - name: upload-object-store
        template: upload-object-store-template
    - - name: delete-seldon-resource
        template: delete-seldon-resource-template

  - name: create-seldon-resource-template
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    resource:
      action: create
      manifest: |
        apiVersion: machinelearning.seldon.io/v1
        kind: SeldonDeployment
        metadata:
          name: "sklearn"
          namespace: argo
          ownerReferences:
          - apiVersion: argoproj.io/v1alpha1
            blockOwnerDeletion: true
            kind: Workflow
            name: "{{workflow.name}}"
            uid: "{{workflow.uid}}"
        spec:
          name: "sklearn"
          predictors:
            - componentSpecs:
              - spec:
                  containers:
                  - name: classifier
                    env:
                    - name: GUNICORN_THREADS
                      value: "10"
                    - name: GUNICORN_WORKERS
                      value: "1"
                    resources:
                      requests:
                        cpu: 5m
                        memory: 10Mi
                      limits:
                        cpu: 50m
                        memory: 100Mi
              graph:
                children: []
                implementation: SKLEARN_SERVER
                modelUri: gs://seldon-models/sklearn/iris
                name: classifier
              name: default
              replicas: 1

  - name: wait-seldon-resource-template
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    script:
      image: bitnami/kubectl:1.17
      command: [bash]
      source: |
        sleep 5
        kubectl rollout status \
            deploy/$(kubectl get deploy -l seldon-deployment-id="sklearn" -o jsonpath='{.items[0].metadata.name}')

  - name: download-object-store-template
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    script:
      image: rclone/rclone:1.53
      volumeMounts:
      - name: "seldon-pvc"
        mountPath: /assets
      - name: rclone-config
        mountPath: /config/rclone
        readOnly: true
      command: [sh]
      source: |
        rclone copyto cluster-minio:data/input-data.txt /assets/input-data.txt

  - name: process-batch-inputs-template
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    script:
      image: seldonio/seldon-core-s2i-python37:1.5.0
      volumeMounts:
      - name: "seldon-pvc"
        mountPath: /assets
      command: [bash]
      source: |
        seldon-batch-processor \
            --deployment-name "sklearn" \
            --benchmark \
            --namespace "argo" \
            --host "istio-ingressgateway.istio-system.svc.cluster.local" \
            --workers "2" \
            --data-type "data" \
            --payload-type "ndarray" \
            --retries "3" \
            --input-data-path "/assets/input-data.txt" \
            --output-data-path "/assets/output-data.txt"

  - name: upload-object-store-template
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    script:
      image: rclone/rclone:1.53
      volumeMounts:
      - name: "seldon-pvc"
        mountPath: /assets
      - name: rclone-config
        mountPath: /config/rclone
        readOnly: true
      command: [sh]
      source: |
        rclone copyto /assets/output-data.txt cluster-minio:data/output-data-{{workflow.uid}}.txt


  - name: delete-seldon-resource-template
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    script:
      image: bitnami/kubectl:1.17
      command: [bash]
      source: |
        sleep 5
        kubectl delete seldondeployments -n argo  sklearn
```

**Comment by alexec** [comment]
Try changing `command: [bash]` to `command: [bash, -c]

**Comment by lianxmfor** [comment]
@alexec Sorry, I just changed all the bash in workflow file to bash -c, but still the same error.

**Comment by lianxmfor** [comment]
The generated pod file contains the following code:

```yaml
  - args:
    - /argo/staging/script
    #- sleep 1000000
    command:
    - bash
    - -c
```

After I changed it to sleep, I ran kubectl exec to get inside the pod:

```shell
$ cd argo
$ ls -l
total 4
drwxrwxrwx 2 root root 4096 Sep  1 15:08 staging
$ cd staging
$ ls -l
total 4
-rw------- 1 root root 140 Sep  1 15:08 script
$ bash script
bash: script: Permission denied
$ cat script
cat: script: Permission denied
```

**Comment by lianxmfor** [comment]
I used the docker command to get into the container as the root user.

```bash
$ docker exec -it -u root 5cb6f2279833  /bin/bash
$ cd /argo/staging/
$ cat script
sleep 5
kubectl rollout status \
    deploy/$(kubectl get deploy -l seldon-deployment-id="sklearn" -o jsonpath='{.items[0].metadata.name}')
$ bash script
```

After running the bash script, I found that the script is executable! This means that the script can be executed by the root account. So I would like to know how can I change the workflow file so that all the files in it are executed under the root account?

The default account number is now 1001:

```shell
oot@seldon-batch-process-2052519094:/argo/staging# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001         1  0.0  0.0   2300   748 ?        Ss   15:08   0:00 sleep 1000000
1001         8  0.0  0.0   2392  1592 pts/0    Ss+  15:09   0:00 sh
root        53  0.0  0.0   3980  3252 pts/1    Ss   15:21   0:00 /bin/bash
root        92  0.0  0.0   7644  2696 pts/1    R+   15:27   0:00 ps aux
````

**Comment by alexec** [comment]
I don' know if `docker run` is relevant. Makes sure every one of your scripts is set-up correctly. You can use pod security policy to pin user ID.

**Comment by wdma** [comment]
More information can be found about my system (yaml etc) can be found here (https://stackoverflow.com/questions/69094527/why-doesnt-this-argo-workflow-run), but in short, I am seeing the same error.  

```
bin/bash: /argo/staging/script: Permission denied
```

I have applied the following permissions to my user (ClusterRole), but in the absence of a comprehensive list of permissions, it is difficult to guess what Argo needs. Can you tell me which permission I need to add here?

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argouser
rules:
  # pod get/watch is used to identify the container IDs of the current pod
  - apiGroups:
      - ""
    resources:
      - pods
      - volumes
      - persistentvolumes
    verbs:
      - get
      - create
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups: ["argoproj.io"] 
    resources:
      - workflows
    verbs:
      - get
      - create
      - list
  - apiGroups: ["workflows.argoproj.io"] 
    resources:
      - workflows
    verbs:
      - get
      - list
      - create
```
