### ISSUE TITLE
SuspendTemplate node starts after skipped node

### ISSUE THREAD

**Issue by keshamin** [argoproj/argo-workflows#6668]
## Summary 

What happened/what you expected to happen?

Here's the DAG:
![image](https://user-images.githubusercontent.com/25623173/131997644-2bced341-05b6-4a73-9530-2f686f2306e6.png)

As you can see "retrain-models" node is skipped by condition using "when" field of a DAG task. 
But node "approve-models-release" of type SuspendTemplate still got created and started despite it depends on skipped parent node.

I expect the child node not to start if its parent is skipped by condition.

## Diagnostics

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 
v3.0.8

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Kubelet

Did this work in a previous version? I.e. is it a regression?
No idea.

<details>
<summary>Show Workflow YAML</summary>

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
spec:
  entrypoint: new-master-pipeline
  templates:
  - name: whalesay
    inputs:
      parameters:
        - name: message
          default: hey
    container:
      image: docker/whalesay
      command: [ cowsay ]
      args: [ "{{inputs.parameters.message}}" ]
  - name: pending-approval
    suspend: { }
  - name: new-master-pipeline
    inputs:
      parameters:
        - default: "false"
          name: retrain
    dag:
      tasks:
      - name: rebuild-image
        template: whalesay

      - depends: rebuild-image
        name: retrain-models
        template: whalesay
        when: '{{inputs.parameters.retrain}} == true'

      - depends: rebuild-image
        name: approve-image-release
        template: pending-approval

      - depends: approve-image-release
        name: release-new-image
        template: whalesay

      - depends: retrain-models
        name: approve-models-release
        template: pending-approval

      - depends: approve-models-release
        name: release-models
        template: whalesay
```
</details>

<details>
<summary>Show contorller logs</summary>

```bash
$ kubectl logs -n argo-workflow deploy/workflow-controller | grep test-nknnq
time="2021-09-03T11:21:46.675Z" level=info msg="Processing workflow" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:46.679Z" level=info msg="Updated phase  -> Running" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:46.681Z" level=info msg="DAG node test-nknnq initialized Running" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:46.681Z" level=info msg="All of node test-nknnq.rebuild-image dependencies [] completed" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:46.681Z" level=info msg="Pod node test-nknnq-1549712555 initialized Pending" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:46.705Z" level=info msg="Created pod: test-nknnq.rebuild-image (test-nknnq-1549712555)" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:46.722Z" level=info msg="Workflow update successful" namespace=argo-workflow phase=Running resourceVersion=315740493 workflow=test-nknnq
time="2021-09-03T11:21:56.706Z" level=info msg="Processing workflow" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.707Z" level=info msg="Setting node test-nknnq-1549712555 outputs" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.707Z" level=info msg="Updating node test-nknnq-1549712555 status Pending -> Succeeded" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.708Z" level=info msg="All of node test-nknnq.retrain-models dependencies [rebuild-image] completed" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.708Z" level=info msg="Skipped node test-nknnq-1104707034 initialized Skipped (message: when 'false == true' evaluated false)" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.708Z" level=info msg="All of node test-nknnq.approve-models-release dependencies [retrain-models] completed" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.708Z" level=info msg="Suspend node test-nknnq-460996650 initialized Pending" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.708Z" level=info msg="node test-nknnq.approve-models-release suspended" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.708Z" level=info msg="node test-nknnq-460996650 phase Pending -> Running" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.708Z" level=info msg="All of node test-nknnq.approve-image-release dependencies [rebuild-image] completed" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.708Z" level=info msg="Suspend node test-nknnq-2478916161 initialized Pending" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.708Z" level=info msg="node test-nknnq.approve-image-release suspended" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.708Z" level=info msg="node test-nknnq-2478916161 phase Pending -> Running" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:21:56.721Z" level=info msg="Workflow update successful" namespace=argo-workflow phase=Running resourceVersion=315740699 workflow=test-nknnq
time="2021-09-03T11:21:56.727Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo-workflow/test-nknnq-1549712555/labelPodCompleted
time="2021-09-03T11:22:06.741Z" level=info msg="Processing workflow" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:22:06.743Z" level=info msg="node test-nknnq.approve-models-release suspended" namespace=argo-workflow workflow=test-nknnq
time="2021-09-03T11:22:06.743Z" level=info msg="node test-nknnq.approve-image-release suspended" namespace=argo-workflow workflow=test-nknnq
```
</details>

<details>
<summary>Logs from in your workflow's wait container</summary>

```bash
$ kubectl logs -c wait -l workflows.argoproj.io/workflow=test-nknnq,workflow.argoproj.io/phase!=Succeeded
time="2021-09-03T11:21:50.018Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2021-09-03T11:21:50.018Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2021-09-03T11:21:50.018Z" level=info msg="No output parameters"
time="2021-09-03T11:21:50.018Z" level=info msg="No output artifacts"
time="2021-09-03T11:21:50.018Z" level=info msg="Annotating pod with output"
time="2021-09-03T11:21:50.036Z" level=info msg="Patch pods 200"
time="2021-09-03T11:21:50.044Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=label=io.kubernetes.pod.namespace=argo-workflow --filter=label=io.kubernetes.pod.name=test-nknnq-1549712555"
time="2021-09-03T11:21:50.071Z" level=info msg="listed containers" containers="map[main:{22d9d50e65de3c7d72c118a678971234d6e6392301da7312827c6b8c37e968dd Exited {0 63766264907 <nil>}} wait:{2f956d6043d12e01d66ba0e2765fccfdaf3d474e1ff8782b6af125b7bb1af8b7 Up {0 63766264907 <nil>}}]"
time="2021-09-03T11:21:50.071Z" level=info msg="Killing sidecars []"
time="2021-09-03T11:21:50.072Z" level=info msg="Alloc=27441 TotalAlloc=32672 Sys=73297 NumGC=5 Goroutines=12"
```
</details>

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
