### ISSUE TITLE
Make HTTP body field accept type string rather than byte

### ISSUE THREAD

**Issue by manterfield** [argoproj/argo-workflows#6674]
# Summary

The new HTTP template `body` field is type `byte`. As far as I can see it's the only field of this type in the Argo field spec. I would expect to be able to pass this field a `string` containing json.

I was unsure whether to post this as a bug or enhancement given how much it limits the usefulness of this feature.

From my experiments the result of it being `byte` is that it can accept hardcoded `base64` and nothing else. I _think_ the problem is that the templating only runs against string fields (half guessing here). However, even if it did accept its value as a templated param, you're left having to convert to `base64` first. That seems like it would be easy enough via an expression, but it's an extra step for (I assume) pretty much all use cases.

# Use Cases

Being able to accept json/json strings in the `body` means we can pass json output from sensors/previous steps directly into the HTTP template. As-is I can't see how I'd do anything other than have a static request payload.

# Reproducible workflow
After speaking with some maintainers on Slack, it seems this isn't the intended behaviour. The below is a minimal workflow to demonstrate what I'm seeing.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-http-input
spec:
  entrypoint: http
  templates:
  - name: http
    http:
      url: http://ww.example.com
      method: POST
      body: "{{inputs.parameters.body}}"
    inputs:
      parameters:
      - name: body
        value: 'Hello world'
```

Running this throws ` Failed: cannot unmarshall spec: error decoding from json: illegal base64 data at input byte 0`
I've tried a number of different configs and the only thing I found that avoided this error was hardcoding a base64 payload into the `body` field directly.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
