### ISSUE TITLE
Setting priority from WorkflowTemplateSpec

### ISSUE THREAD

**Issue by withnale** [argoproj/argo-workflows#6675]
## Summary 

According to the FieldSpec I should be able to set the workflow priority as part of the WorkflowTemplateSpec. 

I can set the priority okay by specifying `.spec.priority` as part of a workflow but if I specify it as `.spec.priority` as part
of a workflowTemplate, where the Workflow and Template is specified as below:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: testworkflow
spec:
  workflowTemplateRef:
    name: testtemplate
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: testtemplate
spec:
  priority: 34
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    steps:
   .... yada yada yada...
```

However, the priority does not seem to get copied across from the template. It is present in the `storedWorkflowTemplateSpec` within the generated workflow, but not in the toplevel spec, where it would actually influence priority.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

v1.20

What version of Argo Workflows are you running? 

v3.1.3

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Kubelet

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
