### ISSUE TITLE
Key unsupported: cannot get key for artifact location, because it is invalid.

### ISSUE THREAD

**Issue by mprzygrodzki** [argoproj/argo-workflows#6676]
## Summary 

Inspired by a template I wanted to create a POC for managing infrastructure by Terraform/Terragrunt. I've based on this one https://raw.githubusercontent.com/argoproj-labs/argo-workflows-catalog/master/templates/terraform-basic/manifests.yaml. Anyway, i've built my custom image which contains all what's needed, main container is executing propery but i'm facing some issues with following errors on wait container  **"key unsupported: cannot get key for artifact location, because it is invalid"** - i'm out of idea what might be wrong, but as far as i read it's related to artifact.

Wait-Container Output:
```
time="2021-09-06T20:16:02.095Z" level=info msg="Starting Workflow Executor" executorType=docker version=v3.1.8
time="2021-09-06T20:16:02.097Z" level=info msg="Creating a docker executor"
time="2021-09-06T20:16:02.097Z" level=info msg="Executor initialized" includeScriptOutput=false namespace=apps podName=terragrunt-vpc-staging-2298416500 template="{\"name\":\"plan\",\"inputs\":{\"artifacts\":[{\"name\":\"terraform\",\"path\":\"/ho
me/terraform\",\"git\":{\"repo\":\"git@bitbucket.org:biotcloud/biot-infra.git\",\"depth\":1,\"sshPrivateKeySecret\":{\"name\":\"github-creds\",\"key\":\"ssh-private-key\"},\"insecureIgnoreHostKey\":true}}]},\"outputs\":{\"artifacts\":[{\"name\":\"
terraform-plan\",\"path\":\"/home/terraform/terraform/staging/vpc/\",\"archive\":{\"none\":{}}}]},\"metadata\":{},\"script\":{\"name\":\"\",\"image\":\"399772605027.dkr.ecr.eu-central-1.amazonaws.com/terraform:1.0.15\",\"command\":[\"sh\",\"-c\",\
"ls -la\\nmkdir -p /home/terraform/\\ncd terraform/staging/vpc\\nterragrunt init -input=false\\nterragrunt plan -parallelism=2 -input=false -no-color -out=tfclientsplan\"],\"resources\":{},\"imagePullPolicy\":\"Always\",\"source\":\"\"},\"archiveL
ocation\":{}}" version="&Version{Version:v3.1.8,BuildDate:2021-08-18T23:21:03Z,GitCommit:0df0f3a98fac4e2aa5bc02213fb0a2ccce9a682a,GitTag:v3.1.8,GitTreeState:clean,GoVersion:go1.15.7,Compiler:gc,Platform:linux/amd64,}"
time="2021-09-06T20:16:02.098Z" level=info msg="Starting annotations monitor"
time="2021-09-06T20:16:02.100Z" level=info msg="Starting deadline monitor"
time="2021-09-06T20:16:02.100Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=label=io.kubernetes.pod.namespace=apps --filter=label=io.kubernetes.pod.nam
e=terragrunt-vpc-staging-2298416500"
time="2021-09-06T20:16:02.129Z" level=info msg="listed containers" containers="map[init:{0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501 Exited {0 63766556096 <nil>}} main:{a51fea160c591558934296591809bb7b36d6afb4494d7d831ff154b34
551c403 Exited {0 63766556101 <nil>}} wait:{b22250ae3ae4b9b2caf44672b984eb21daf7b54857d6128c821ab549b33da962 Exited {0 63766556101 <nil>}}]"
time="2021-09-06T20:16:02.129Z" level=info msg="mapped container name \"wait\" to container ID \"b22250ae3ae4b9b2caf44672b984eb21daf7b54857d6128c821ab549b33da962\" (created at 2021-09-06 20:15:01 +0000 UTC, status Exited)"
time="2021-09-06T20:16:02.129Z" level=info msg="mapped container name \"init\" to container ID \"0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501\" (created at 2021-09-06 20:14:56 +0000 UTC, status Exited)"
time="2021-09-06T20:16:02.129Z" level=info msg="mapped container name \"main\" to container ID \"a51fea160c591558934296591809bb7b36d6afb4494d7d831ff154b34551c403\" (created at 2021-09-06 20:15:01 +0000 UTC, status Exited)"
time="2021-09-06T20:16:03.100Z" level=info msg="docker wait a51fea160c591558934296591809bb7b36d6afb4494d7d831ff154b34551c403"
time="2021-09-06T20:16:03.124Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=label=io.kubernetes.pod.namespace=apps --filter=label=io.kubernetes.pod.nam
e=terragrunt-vpc-staging-2298416500"
time="2021-09-06T20:16:03.129Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=label=io.kubernetes.pod.namespace=apps --filter=label=io.kubernetes.pod.nam
e=terragrunt-vpc-staging-2298416500"
time="2021-09-06T20:16:03.152Z" level=info msg="listed containers" containers="map[init:{0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501 Exited {0 63766556096 <nil>}} main:{a51fea160c591558934296591809bb7b36d6afb4494d7d831ff154b34
551c403 Exited {0 63766556101 <nil>}} wait:{b22250ae3ae4b9b2caf44672b984eb21daf7b54857d6128c821ab549b33da962 Exited {0 63766556101 <nil>}}]"
time="2021-09-06T20:16:03.152Z" level=info msg="Main container completed"
time="2021-09-06T20:16:03.152Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-09-06T20:16:03.152Z" level=info msg="No output parameters"
time="2021-09-06T20:16:03.152Z" level=info msg="Saving output artifacts"
time="2021-09-06T20:16:03.152Z" level=info msg="Staging artifact: terraform-plan"
time="2021-09-06T20:16:03.152Z" level=info msg="Staging /home/terraform/terraform/staging/vpc/ from mirrored volume mount /mainctrfs/home/terraform/terraform/staging/vpc"
time="2021-09-06T20:16:03.152Z" level=info msg="No compression strategy needed. Staging skipped"
time="2021-09-06T20:16:03.153Z" level=error msg="executor error: key unsupported: cannot get key for artifact location, because it is invalid"
time="2021-09-06T20:16:03.153Z" level=info msg="Annotating pod with output"
time="2021-09-06T20:16:03.154Z" level=info msg="listed containers" containers="map[init:{0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501 Exited {0 63766556096 <nil>}} main:{a51fea160c591558934296591809bb7b36d6afb4494d7d831ff154b34
551c403 Exited {0 63766556101 <nil>}} wait:{b22250ae3ae4b9b2caf44672b984eb21daf7b54857d6128c821ab549b33da962 Exited {0 63766556101 <nil>}}]"
time="2021-09-06T20:16:03.179Z" level=info msg="Patch pods 200"
time="2021-09-06T20:16:03.188Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=label=io.kubernetes.pod.namespace=apps --filter=label=io.kubernetes.pod.nam
e=terragrunt-vpc-staging-2298416500"
time="2021-09-06T20:16:03.215Z" level=info msg="listed containers" containers="map[init:{0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501 Exited {0 63766556096 <nil>}} main:{a51fea160c591558934296591809bb7b36d6afb4494d7d831ff154b34
551c403 Exited {0 63766556101 <nil>}} wait:{b22250ae3ae4b9b2caf44672b984eb21daf7b54857d6128c821ab549b33da962 Exited {0 63766556101 <nil>}}]"
time="2021-09-06T20:16:03.215Z" level=info msg="Killing sidecars [\"init\"]"
time="2021-09-06T20:16:03.219Z" level=info msg="Get pods 200"
time="2021-09-06T20:16:03.220Z" level=info msg="docker kill --signal TERM 0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501"
time="2021-09-06T20:16:03.240Z" level=error msg="`docker kill --signal TERM 0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501` failed: Error response from daemon: Cannot kill container: 0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018a
b1f0150a7eb015a501: Container 0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501 is not running\n"
time="2021-09-06T20:16:03.241Z" level=warning msg="Ignored error from 'docker kill --signal TERM': Error response from daemon: Cannot kill container: 0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501: Container 0960ea68aa6bebcee07ed
d7ea7357dd75a93b8a709018ab1f0150a7eb015a501 is not running"
time="2021-09-06T20:16:03.241Z" level=info msg="[docker wait 0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501]"
time="2021-09-06T20:16:03.261Z" level=info msg="Containers [0960ea68aa6bebcee07edd7ea7357dd75a93b8a709018ab1f0150a7eb015a501] killed successfully"
time="2021-09-06T20:16:03.261Z" level=info msg="Alloc=5998 TotalAlloc=11047 Sys=73809 NumGC=4 Goroutines=10"
time="2021-09-06T20:16:03.261Z" level=fatal msg="key unsupported: cannot get key for artifact location, because it is invalid"
```

**Here's my complete workflow template:**

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: apps
  annotations:
    workflows.argoproj.io/description: This workflow run a basic Terraform plan.
    workflows.argoproj.io/maintainer: '@descrepes'
    workflows.argoproj.io/tags: terraform
    workflows.argoproj.io/version: '>= 2.9.0'
  name: terragrunt-vpc-staging
spec:
  entrypoint: update
  arguments:
    parameters:
    - name: terraform-docker-image
      value: "1111111111111111.dkr.ecr.eu-central-1.amazonaws.com/terraform:1.0.15"
    - name: terraform-script-repository
      value: "git@bitbucket.org:mycompany/cloud-infra.git"
  templates:
    - name: plan
      inputs:
        artifacts:
          - name: terraform
            path: /home/terraform
            git:
              repo: "{{workflow.parameters.terraform-script-repository}}"
              sshPrivateKeySecret:
                name: github-creds
                key: ssh-private-key
              insecureIgnoreHostKey: true
              depth: 1
      script:
        imagePullPolicy: "Always"
        image: "{{workflow.parameters.terraform-docker-image}}"
        command:
          - sh
          - -c
          - |-
            mkdir -p /home/terraform/
            cd terraform/staging/vpc
            terragrunt init -input=false
            terragrunt plan -parallelism=2 -input=false -no-color -out=tfclientsplan
      outputs:
        artifacts:
          - name: terraform-plan
            path: /home/terraform/terraform/staging/vpc/
            archive:
              none: {}
          - name: terraform-log
             path: /tmp/terraform-change.log
             archive:
               none: {}

    - name: apply
      inputs:
        artifacts:
        - name: terraform-plan
           path: /home/terraform/terraform/staging/vpc/

      script:
        imagePullPolicy: "Always"
        image: "{{workflow.parameters.terraform-docker-image}}"
        command: ["sh"]
        source: |
          terragrunt apply /home/terraform/output/tfclientsplan -input=false -parallelism=2 -no-color

    - name: approve
      suspend: {}

    - name: update
      dag:
        tasks:
          - name: plan
            template: plan
            outputs:
              artifacts:
                - name: terraform-plan
                  path: /home/terraform/terraform/staging/vpc
          - name: approve
            dependencies: [plan]
            template: approve
          - name: apply
            template: apply
            dependencies: [plan, approve]
            arguments:
              artifacts:
              - name: terraform-plan
                from: "{{tasks.plan.outputs.artifacts.terraform-plan}}"

```

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

**What Kubernetes provider are you using?** 

```EKS 1.20.9```

**What version of Argo Workflows are you running?** 

```v 3.1.8```

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

```K8SAPI```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
There are similar issues raised to this. Maybe Google error mesage?

**Comment by mprzygrodzki** [comment]
@alexec - I believe i've checked all possible solutions which i've found, and none of them worked for me.

**Comment by alexec** [comment]
The error "cannot get key for artifact location, because it is invalid" is caused because there is not configuration for the artifact repository - so the code does not know where to save the data. Looking at the logs, it is the outputs that are missing:

```yaml
      outputs:
        artifacts:
          - name: terraform-plan
            path: /home/terraform/terraform/staging/vpc/
            archive:
              none: {}
          - name: terraform-log
             path: /tmp/terraform-change.log
             archive:
               none: {}
```

I cannot see configuration here, so I need you to check your configuration for your artifact repository. Typically this is an S3 bucket set-up in your `configmaps/workflow-controller-configmap` or `configmaps/artifact-repositories`.
