### ISSUE TITLE
Unable to resolve parameters defined in a WorkflowTemplate

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#6678]
## Summary 

What happened/what you expected to happen?

A workflow should be able to use a workflow template that contains parameters but it failed to resolve the parameters defined in a WorkflowTemplate.

Reproducible YAML:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-args-not-working
spec:
  serviceAccountName: argo
  arguments:
    parameters:
      - name: local-parameter
        value: hello
  templates:
    - name: hello-world
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{workflow.parameters.local-parameter}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-template-args-not-working-
spec:
  serviceAccountName: argo
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template-args-not-working
              template: hello-world

```

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

k3s

What version of Argo Workflows are you running? 

3.2.0-rc1

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

PNS

Did this work in a previous version? I.e. is it a regression?

Haven't checked.

Are you pasting thousands of log lines? That's too much information. 

```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
kubectl get wf -o yaml ${workflow}

Name:         hello-world-template-args-not-working-hngpc
Namespace:    argo
Labels:       workflows.argoproj.io/completed=true
              workflows.argoproj.io/phase=Failed
Annotations:  <none>
API Version:  argoproj.io/v1alpha1
Kind:         Workflow
Metadata:
  Creation Timestamp:  2021-09-07T02:31:23Z
  Generate Name:       hello-world-template-args-not-working-
  Generation:          2
  Managed Fields:
    API Version:  argoproj.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName:
      f:spec:
        .:
        f:entrypoint:
        f:serviceAccountName:
    Manager:      kubectl-create
    Operation:    Update
    Time:         2021-09-07T02:31:23Z
    API Version:  argoproj.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:workflows.argoproj.io/completed:
          f:workflows.argoproj.io/phase:
      f:spec:
        f:arguments:
        f:templates:
      f:status:
        .:
        f:conditions:
        f:finishedAt:
        f:message:
        f:phase:
        f:progress:
        f:startedAt:
        f:storedTemplates:
    Manager:         workflow-controller
    Operation:       Update
    Time:            2021-09-07T02:31:23Z
  Resource Version:  27323
  UID:               ede4eb8e-c43e-4571-a74b-c3c827dff82a
Spec:
  Arguments:
  Entrypoint:            whalesay
  Service Account Name:  argo
  Templates:
    Inputs:
    Metadata:
    Name:  whalesay
    Outputs:
    Steps:
      [map[arguments:map[] name:hello-world templateRef:map[name:hello-world-template-args-not-working template:hello-world]]]
Status:
  Conditions:
    Status:     True
    Type:       Completed
  Finished At:  2021-09-07T02:31:23Z
  Message:      invalid spec: templates.whalesay.steps[0].hello-world templates.hello-world: failed to resolve {{workflow.parameters.local-parameter}}
  Phase:        Failed
  Progress:     0/0
  Started At:   2021-09-07T02:31:23Z
  Stored Templates:
    namespaced/hello-world-template-args-not-working/hello-world:
      Container:
        Args:
          {{workflow.parameters.local-parameter}}
        Command:
          cowsay
        Image:  docker/whalesay
        Name:   
        Resources:
      Inputs:
      Metadata:
      Name:  hello-world
      Outputs:
Events:
  Type     Reason          Age    From                 Message
  ----     ------          ----   ----                 -------
  Warning  WorkflowFailed  3m19s  workflow-controller  invalid spec: templates.whalesay.steps[0].hello-world templates.hello-world: failed to resolve {{workflow.parameters.local-parameter}}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
You can’t refer spec level fields if you are referring ‘ templateRef’. In your scenario, the workflow which referring ‘templateRef’ should have spec level parameter.

**Comment by terrytangyuan** [comment]
Thanks. Just tried and both of the following workflows work. Though it looks like local variable values must be supplied at the template definition inside WorkflowTemplate. Is this the normal behavior? If so, I'll add something to the doc that clarifies this.

Global variable
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-args-not-working-4
spec:
  serviceAccountName: argo
  templates:
    - name: hello-world
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{workflow.parameters.global-parameter}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-template-args-not-working-
spec:
  serviceAccountName: argo
  entrypoint: whalesay
  arguments:
    parameters:
      - name: global
        value: hello
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template-args-not-working-4
              template: hello-world
```

Local variable (value must be supplied at the template definition inside WorkflowTemplate.
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-args-not-working-11
spec:
  serviceAccountName: argo
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hi msg"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-template-args-not-working-
spec:
  serviceAccountName: argo
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template-args-not-working-11
              template: hello-world
```
