### ISSUE TITLE
Expression tag incorrectly treats boolean parameter values as strings

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#6679]
## Summary 

What happened/what you expected to happen?

When the parameter value is `true`, Argo Workflow treats it as string `"true"`, which is incorrect and should be boolean instead.

Reproducible YAML:

This will print "yes":
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-expression-
spec:
  serviceAccountName: argo
  entrypoint: hello-world
  arguments:
    parameters:
    - name: flag
      value: true
  templates:
    - name: hello-world
      container:
        image: docker/whalesay
        args:
          - cowsay
          - "{{=workflow.parameters.flag == 'true'? 'yes' : 'no'}}"
```

And the following workflow (using [ternary operator](https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md#ternary-operators)) would print out the unevaluated expression:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-expression-
spec:
  serviceAccountName: argo
  entrypoint: hello-world
  arguments:
    parameters:
    - name: flag
      value: true
  templates:
    - name: hello-world
      container:
        image: docker/whalesay
        args:
          - cowsay
          - "{{=workflow.parameters.flag ? 'yes' : 'no'}}"

```

```
 ______________________________________ 
/ {{=workflow.parameters.flag? 'yes' : \
\ 'no'}}                               /
 -------------------------------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   

```

Before we start, around 2/3 of issues can be fixed by one of the following:

* Have you double-checked your configuration? Maybe 30% of issues are wrong configuration.
* Have you tested to see if it is fixed in the latest version? Maybe 20% of issues are fixed by this.
* Have you tried using the PNS executer instead of Docker? Maybe 50% of artifact related issues are fixed by this.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

k3d

What version of Argo Workflows are you running? 

v3.2.0-rc1

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

PNS

Did this work in a previous version? I.e. is it a regression?

Haven't checked.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
