### ISSUE TITLE
feat: dynamic referencing for workflows.argoproj.io/creator* labels

### ISSUE THREAD

**Issue by lukasmrtvy** [argoproj/argo-workflows#6681]
# Summary

Would be superb to implement dynamic referencing for `workflows.argoproj.io/creator-email` `workflows.argoproj.io/creator` in workflows triggered by another users ( than creator ) from workflow template.

# Use Cases

We are using SSO and have two groups of users:
- admins -> they are managing workflowtemplates
- users -> they are just triggering workflows from workflowtemplates

Based on this information ( who triggered workflow ) We are mapping users to accounts in Kubernetes. 

Argo Workflows is in this use case selfservice control plane for boostraping environments. 

# Solution
Maybe another set of ( dynamic ) labels like `workflows.argoproj.io/user` `workflows.argoproj.io/user-email` would help to distinguish between creators and users.. 

# Example
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
spec:
  templates:
    - name: test
      container:
        name: test
        image: 'busybox:latest'
        command:
          - /bin/sh
          - '-c'
        args:
          - |
            echo {{workflow.labels.workflows.argoproj.io/creator-email}}
```

Thanks

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
