### ISSUE TITLE
Unable to convert existing Workflow to WorkflowTemplate in v3.0.7

### ISSUE THREAD

**Issue by edhjer** [argoproj/argo-workflows#6694]
## Summary 

What happened/what you expected to happen?

Converted an existing Workflow to a WorkflowTemplate. Referencing the new WorkflowTemplate in another Workflow resulted in `volume $VOLUME_NAME not found in workflow spec` error. Since the original Workflow succeeded, I expected the WorkflowTemplate to succeed as well (based on [this](https://argoproj.github.io/argo-workflows/workflow-templates/#workflowtemplate-spec) section from the docs)

> > v2.7 and after
> 
> In v2.7 and after, all the fields in WorkflowSpec (except for priority that must be configured in a WorkflowSpec itself) are supported for WorkflowTemplates. You can take any existing Workflow you may have and convert it to a WorkflowTemplate by substituting kind: Workflow to kind: WorkflowTemplate.

## Diagnostics

What Kubernetes provider are you using? 
```
Discovered on `EKS` cluster, reproduced with local `kind (kind.x-k8s.io/v1alpha4)` cluster.
```
What version of Argo Workflows are you running? 
```
v.3.0.7 - EKS
v.3.1.0 - kind
```
What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
```
PNS for the kind cluster
```
Did this work in a previous version? I.e. is it a regression?
Not tested with other versions.

```
cat empty-volume-wf.yaml

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: empty-dir-
spec:
  volumes:   <--- NOTE LOCATION
    - name: out
      emptyDir: { }
  entrypoint: main
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2
        command: [sh, -c]
        args: ["cowsay hello world | tee /mnt/out/hello_world.txt"]
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      outputs:
        parameters:
          - name: message
            valueFrom:
              path: /mnt/out/hello_world.txt
---
cat bad-empty-volume-wft.yaml

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bad-empty-dir-wft
spec:
  volumes:
    - name: out
      emptyDir: { }
  entrypoint: main
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2
        command: [sh, -c]
        args: ["cowsay hello world | tee /mnt/out/hello_world.txt"]
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      outputs:
        parameters:
          - name: message
            valueFrom:
              path: /mnt/out/hello_world.txt
---
cat bad-ref-template.yaml

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bad-empty-dir-wft-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: hello-world
            templateRef:
              name: bad-empty-dir-wft
              template: main
---
cat good-empty-volume-wft.yaml

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: good-empty-dir-wft
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2
        command: [sh, -c]
        args: ["cowsay hello world | tee /mnt/out/hello_world.txt"]
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      volumes:  <-- MOVED UNDERNEATH templates
        - name: out
          emptyDir: { }
      outputs:
        parameters:
          - name: message
            valueFrom:
              path: /mnt/out/hello_world.txt
---
cat good-ref-template.yaml

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: good-empty-dir-wft-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: hello-world
            templateRef:
              name: good-empty-dir-wft
              template: main
```

Then run 

```
kubectl create -f empty-volume-wf.yaml (succeeds)

kubectl create -f bad-empty-volume-wft.yaml
kubectl create -f bad-ref-template.yaml (fails)

kubectl create -f good-empty-volume-wft.yaml
kubectl create -f good-ref-template.yaml (succeeds)
```

### Screenshots
<img width="557" alt="Screen Shot 2021-09-08 at 11 55 55 PM" src="https://user-images.githubusercontent.com/17804311/132637723-84748b5c-5908-42a1-b20e-1624f0329892.png">

<img width="562" alt="Screen Shot 2021-09-08 at 11 43 30 PM" src="https://user-images.githubusercontent.com/17804311/132637407-00b93df2-dd01-4b4d-9ce2-e990d8b75faf.png">

<img width="555" alt="Screen Shot 2021-09-08 at 11 43 21 PM" src="https://user-images.githubusercontent.com/17804311/132637380-b0aa8ad7-df3b-45dd-8505-9391bcf2a93f.png">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
