### ISSUE TITLE
feat: Allow pre-processing of event payload variables in WorkflowEventBinding arguments

### ISSUE THREAD

**Issue by aslafy-z** [argoproj/argo-workflows#6695]
# Summary

Allow pre-processing of event payload in WorkflowEventBinding arguments .

# Use Cases

I'd like to pre-process an event payload value into a `WorkflowEventBinding` resource before passing them down as `WorkflowTemplate` variables.
I've found that `submit.arguments.parameters` may contain an expression  key instead of a `valueFrom` reference, but I'm unable to find how to reference a payload variable in it. I'd love to use something like:

```yaml
arguments:
  parameters:
  - name: revision
    expression: "{{=sprig.replace(event.payload['ref'], 'refs/heads/', '')}}"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Try this:

```
arguments:
  parameters:
  - name: revision
    expression: "sprig.replace(event.payload['ref'], 'refs/heads/', '')"
```
