### ISSUE TITLE
Allow the use of workflowTemplateRef in a WorkflowTemplate

### ISSUE THREAD

**Issue by egeland** [argoproj/argo-workflows#6698]
# Summary

A smooth user experience would be to be able to call a `workflowTemplateRef` directly in the steps/dag, with any parameters and `withParam` applying to the target workflowtemplate.

# Use Cases

What I expected to use, and which currently apparently needs other, less obvious, ways to get it to work:
```yaml
...
  templates:
  - name: do-things
    dag:
      tasks:
      - name: find-all
        template: find-all
        arguments:
          parameters:
          - name: repo
            value: "{{ workflow.parameters.repo }}"
      - name: sync-customers
        workflowTemplateRef:
          name: something-to-do-to-many
        depends: find-all
        withParam: "{{ tasks.find-all.outputs.parameters.some-list }}"
        arguments:
          parameters:
          - name: one
            value: "{{ item.one }}"
          - name: two
            value: "{{ item.two }}"
```

This is a nice clean way to fan out to a workflowTemplate, but it currently is not supported(?)
I get `Unsuccessful HTTP response: templates.do-things.tasks.sync-customers failed to get a template`

---

**Message from the maintainers**:

Impacted by this? Give it a 👍. We prioritise the issues with the most 👍.
