### ISSUE TITLE
LogView can't display text of the original container logs in color.

### ISSUE THREAD

**Issue by summylight** [argoproj/argo-workflows#6724]
## Summary 

What happened/what you expected to happen?

After updating the 3.0.x version to 3.1.9 and adding the regular expression filtering function, the argo-server log viewer cannot display the text in color and prints the color code in the original container logs.
But if we input some regexp pattern, log viewer displays color again! 
I guess this is a bug, the regular expression filter function affects the original log display.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
not sure
What version of Argo Workflows are you running? 
3.1.9
What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
K8SAPI
Did this work in a previous version? I.e. is it a regression?
It works well in 3.0.x.
Are you pasting thousands of log lines? That's too much information. 

## Example
Here is my test workflow yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: step-A 
        template: step-template-A

  - name: step-template-A
    script:
      image: alpine
      command: [/bin/sh]
      source: |
          echo -e "\e[1;31m This is red text \e[0m"
          echo -e "\e[1;42m This is red text \e[0m"
          echo -e "Only the expression\u001B[4m hello \u001B[m is underlined."

      
```
The original log:
![Screenshot from 2021-09-14 15-28-26](https://user-images.githubusercontent.com/26787325/133214315-21ff3099-ee07-43fa-a761-6a7726dda6e9.png)
After filter:
![Screenshot from 2021-09-14 15-29-48](https://user-images.githubusercontent.com/26787325/133214457-ab188958-857c-4c47-8752-643af83b0762.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
