### ISSUE TITLE
`concurrencyPolicy: Replace` doesn't work as expected

### ISSUE THREAD

**Issue by ninjaprox** [argoproj/argo-workflows#6735]
## Summary 

What happened/what you expected to happen?

`CronWorkflow` with `concurrencyPolicy: Replace` should replace an existing running workflow with a new one as described in [Concurrency Policy](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy).

It can be reproduced with this `CronWorkflow`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-concurrency-policy
  labels:
    role: test-concurrency-policy
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Replace
  workflowMetadata:
    labels:
      role: test-concurrency-policy
  workflowSpec:
    entrypoint: call
    templates:
    - name: call
      steps:
      - - name: sleep
          template: sleep
    - name: sleep
      container:
        image: alpine
        command:
        - sleep
        args:
        - '300'

```

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using?

- Self-hosted

What version of Argo Workflows are you running?

```
argo: v3.1.3+9337abb.dirty
  BuildDate: 2021-07-28T08:23:53Z
  GitCommit: 9337abb002d3c505ca45c5fd2e25447acd80a108
  GitTreeState: dirty
  GitTag: v3.1.3
  GoVersion: go1.16.6
  Compiler: gc
  Platform: darwin/amd64
```

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

- K8sapi

```bash
argo cron get test-concurrency-policy

Name:                          test-concurrency-policy
Namespace:                     default
Created:                       Wed Sep 15 08:53:22 +0800 (1 hour ago)
Schedule:                      */1 * * * *
Suspended:                     false
ConcurrencyPolicy:             Replace
LastScheduledTime:             Wed Sep 15 10:28:00 +0800 (now)
NextScheduledTime:             Wed Sep 15 10:29:00 +0800 (59 seconds from now) (assumes workflow-controller is in UTC)
Active Workflows:              test-concurrency-policy-1631672820, test-concurrency-policy-1631672880
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
