### ISSUE TITLE
GCS serviceAccountKey invalid character

### ISSUE THREAD

**Issue by AlbertWigmore** [argoproj/argo-workflows#6737]
## Summary 

What happened/what you expected to happen?

When following the instructions for configuring a [GCS artifact repository](https://argoproj.github.io/argo-workflows/configure-artifact-repository/#configuring-gcs-google-cloud-storage) was presented with the error below:

```
Error (exit code 1): GCS client CredentialsFromJSON: invalid character 'e' looking for beginning of value
```

Believe the issue is that the documentation specifies to use a base64 encoded string and the codebase for retrieving the value doesn't perform base64 decoding. The base64 string is sent to the Google Oauth library where it returns the error message as it is expecting a JSON string.

Before we start, around 2/3 of issues can be fixed by one of the following:

* Have you double-checked your configuration? Maybe 30% of issues are wrong configuration. _Checked_
* Have you tested to see if it is fixed in the latest version? Maybe 20% of issues are fixed by this. _Checked_
* Have you tried using the PNS executer instead of Docker? Maybe 50% of artifact related issues are fixed by this. _Not Applicable_

## Diagnostics

What Kubernetes provider are you using? 
- GKE

What version of Argo Workflows are you running? 
- v3.1.1

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
- K8SAPI

Did this work in a previous version? I.e. is it a regression?
- Have not tested this

Configuration is based on the quickstart with postgres example and have included the relevant snippets below.

Secret configuration
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifact-repository-credentials
stringData:
  serviceAccountKey: {base64 encoded string}
type: Opaque
```

Artifact Repository Configuration
```yaml
apiVersion: v1
data:
  default-v1: |
    archiveLogs: true
    gcs:
      bucket: artifacts-argo-workflows
      key: artifact-repository-1/
      serviceAccountKeySecret:
        name: artifact-repository-credentials
        key: serviceAccountKey
  empty: ""
  my-key: |
    archiveLogs: true
    gcs:
      bucket: artifacts-argo-workflows
      key: artifact-repository-2/
      serviceAccountKeySecret:
        name: artifact-repository-credentials
        key: serviceAccountKey
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1
  name: artifact-repositories
---
apiVersion: v1
data:
  artifactRepository: |
    gcs:
      bucket: artifacts-argo-workflows
      key: artifact-repository-3/
      serviceAccountKeySecret:
        name: artifact-repository-credentials
        key: serviceAccountKey
```

It is possible to work around the issue by simply adding the JSON string directly into the kubernetes secret instead. Solution would be to update either the codebase or doc to be in sync.

Happy to submit a PR for the fix if it has been identified correctly in this post.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
