### ISSUE TITLE
WorkflowTemplate volumeClaimTemplates issue

### ISSUE THREAD

**Issue by jp-gouin** [argoproj/argo-workflows#6765]
## Summary 

I tried to define a PVC at WorkflowTemplate level , but when i run the Workflow referencing the template i get the following error : `
volume 'test-workdir' not found in workflow spec`

I assume that a WorkflowTempate is able to define a PVC and shall not rely on PVC claim at the Workflow level

## Diagnostics
Argo Version : 
- Helm : 0.6.0
- v3.1.8
Platform : GKE
Kubernetes Version : v1.20.9-gke.701 
OS : COS with Containerd

## How to reproduce

Use the following WorkflowTemplate

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
  namespace: argo
spec:
  volumeClaimTemplates:
  - metadata:
      name: test-workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    container:
      image: docker/whalesay
      command: [cowsay]
      volumeMounts:
      - name: test-workdir
        mountPath: /mnt/vol
```
And the following Workflow : 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
  namespace: argo
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:
      - - name: call-whalesay-template
          templateRef:
            name: workflow-template-whalesay-template
            template: whalesay-template
          arguments:
            parameters:
            - name: message
              value: "hello world"
```

You should get the following error in the UI : 
```
step group deemed errored due to child workflow-template-hello-world-bjfzf[0].call-whalesay-template error: volume 'test-workdir' not found in workflow spec
```
and 
```
volume 'test-workdir' not found in workflow spec
```

PS : it should be great to be able to define a PVC at step level 😁 , especially when having parallel steps

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
