### ISSUE TITLE
sprig template sometimes fails to render

### ISSUE THREAD

**Issue by samene** [argoproj/argo-workflows#6766]
I have a workflow template like this (truncated, to only include important parts)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: patch-generator-basic
spec:
  arguments:
    parameters:
    - name: patch-name
      value: IN-XXXXX
  templates:
  - name: self-service-ndt
    steps:
    - - name: create-link
        template: create-link
  - name: create-link
    inputs:
      parameters:
      - name: patch-name
        value: "{{=sprig.trim(workflow.parameters['patch-name'])}}"
    container:
      image: bitnami/minio-client:latest
      command: ["/bin/bash", "-c"]
      args: ["/opt/bitnami/scripts/minio-client/entrypoint.sh share download --expire 168h minio/self-service-patch-generator/share/{{inputs.parameters.patch-name}}_{{workflow.creationTimestamp}}.tgz | tee /tmp/share.txt; cat /tmp/share.txt | grep Share  | cut -d' ' -f 2 > /tmp/share-link.txt"]
    outputs:
      parameters:
      - name: mc-stdout
        valueFrom:
          path: /tmp/share-link.txt
```
This works 8 out of 10 times. 2 times (randomly) the sprig template fails to render and I get the string {{=sprig.trim(workflow.parameters['patch-name'])}} in the environment variable.

Argo Workflows 3.1.8

**Comment by terrytangyuan** [comment]
Related https://github.com/argoproj/argo-workflows/issues/6673.

**Comment by alexec** [comment]
Does `patch-name` contain `{` or `}`?

**Comment by alexec** [comment]
Can I ask another question, what happens if you just run with `    value: "{{=workflow.parameters['patch-name']}}"`

**Comment by samene** [comment]
> Can I ask another question, what happens if you just run with ` value: "{{=workflow.parameters['patch-name']}}"`

` value: "{{workflow.parameters['patch-name']}}"` works fine. Havent tried with the {{=

**Comment by alexec** [comment]
@samene if I create an engineer build, could you test an hypothesis for me?

**Comment by samene** [comment]
> @samene if I create an engineer build, could you test an hypothesis for me?

Sure. tell me

**Comment by alexec** [comment]
Before I do that, my hypothesis is that there is some state when using Spring, but I cannot actually see it. Could you check if `{{=workflow.parameters['patch-name']}}` works on not?

**Comment by samene** [comment]
```{{=workflow.parameters['patch-name']}}``` failed too. on the 5th run.

![image](https://user-images.githubusercontent.com/46681492/134043063-a04575cf-b60e-4567-994c-e15da0f96fb1.png)

![image](https://user-images.githubusercontent.com/46681492/134043126-3d88392a-b18d-4faa-b699-00a67e7778cf.png)

**Comment by alexec** [comment]
I've just pushed a change. It will take around 20m to build and publish images to quay.io.

Could you try running your controller with `argopro/workflow-controller:dev-tmpl` in 20m?

**Comment by samene** [comment]
@alexec I tried this image but the workflow fails to start completely. The pod is in pending state. I see this in the controller logs, dont know if it is relevant.
```
E0921 04:02:10.368787       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden: User "system:serviceaccount:argo:argo-argo-workflows-workflow-controller" cannot list resource "workflowtasksets" in API group "argoproj.io" in the namespace "argo"
```
I am on v3.1.8 installed through the helm chart.

**Comment by ThSchrad** [comment]
I have the same problem with another workflow and also tried your image @alexec.
To fix the issue mentioned by @samene I added the required permission to argo-role.
However the pod shows the following error:

`Error (exit code 2): open /argo/podmetadata/annotations: no such file or directory`

I am on v3.1.12.

**Comment by ThSchrad** [comment]
Ah, thank you. Now it works.

With the old image my workflow worked 5 out of 10 times.
The error I get is:
```
/argo/staging/script: line 1: syntax error near unexpected token `('
/argo/staging/script: line 1: `echo '{{=sprig.regexReplaceAll('.*/([^/\.]*).*', workflow.parameters.print, '$1')}}''
```

With the new image the same workflow worked 3 out of 10 times.
The error is the same.

The log of the workflow controller contains no error messages.

This is my workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: sprig
spec:
  arguments:
    parameters:
    - name: print
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: print
        value: "{{=sprig.regexReplaceAll('.*/([^/\\.]*).*', workflow.parameters.print, '$1')}}"
    dag:
      tasks:
      - name: echo
        template: echo
        arguments:
          parameters:
          - name: print
            value: "{{inputs.parameters.print}}"

  - name: echo
    inputs:
      parameters:
      - name: print
    script:
      image: debian:stable-slim
      command: [ bash ]
      source: |
        echo '{{inputs.parameters.print}}'
```
