### ISSUE TITLE
Execute loop in sequentially 

### ISSUE THREAD

**Issue by xi2817-aajgaonkar** [argoproj/argo-workflows#6768]
# Summary

What change needs making?
I am having array and want it to execute it in sequential format.
`withParam` passes the params but executes the loop in parallel

```
  name: create-resources
  inputs:
      parameters:
        - name: resources
   dag:
      tasks:
        - name: resource
          template: resource-operation
          arguments:
            parameters:
             - name: resource
              value: "{{item}}"
            withParam: "{{inputs.parameters.resources}}"        
```           
              
              

# Use Cases

When would you use this?
I want to use this to provision my terraform resources sequentially. I am passing terraform resources in input.
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
