### ISSUE TITLE
Multiple managed-namespace

### ISSUE THREAD

**Issue by guillaumBrisard** [argoproj/argo-workflows#6769]
# Summary

With the [managed-namespace](https://argoproj.github.io/argo-workflows/managed-namespace/) installation, 
would it be possible to manage multiple namespaces ?

# Use Cases

On a single cluster, I have differents teams and each one of them handle multiple products. 
And I would want each team to handle her own argo workflow installation for multiple products.
Because one install by product is to heavy, and with a cluster install there is no enough isolation.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
How about we manage namespaces based on labels?

```
kind: Namespace
metadata:
  name: my-ns
  labels:
    workflows.argoproj.io/managed-namespace: "true"
```
