### ISSUE TITLE
Use template name in custom metric label definition

### ISSUE THREAD

**Issue by mbruner** [argoproj/argo-workflows#6772]
# Summary

We want to collect duration steps for every part of the workflow but for now template name is not available in variables so we can not refer to it while defining labels.

# Use Cases

Collect the same metrics for all steps/tasks in workflow.

```yaml
templateDefaults:
  metrics:
    prometheus:
      - name: result_counter
        help: "Count of step execution by result status"
        labels:
          - key: template_name
            value: "{{templateName}}"
           - key: status
             value: "{{status}}"    # Argo variable in `labels`
        counter:
          value: "1"
```
Also it would be nice to have some common metrics defined on the controller level so later it's possible to reference this definitions in specs. i.e.:
```yaml
  metrics:
    prometheus:
      - name: result_counter
        metricsRef: result_counter
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by diegofd** [comment]
As a workaround while they implemented it you can add a label with the workflow template name by removing the suffix from the `workflow.name`:
```
      metrics:
        prometheus:
          - name: duration_gauge
            labels:
            - key: workflow_template_name
              # Get workflow name without the random suffix
              value: "{{= sprig.join('-', sprig.initial(sprig.splitList('-', workflow.name))) }}"
            help: "Duration gauge by name"
            gauge:
              realtime: true
              value: "{{ workflow.duration }}"
```

Ideally it would be better if `{{ workflow.workflowTemplateRef }}` was available as variable, but it isn't right now.
