### ISSUE TITLE
WorkflowTemplate Submission Widget does not respect Argument Parameter defaults.

### ISSUE THREAD

**Issue by spire-ffoston** [argoproj/argo-workflows#6779]
## Summary 
When attempting to submit a WorkflowTemplate via the web UI, the widget will not populate fields if only the argument parameters `default` field is populated.

i.e.:
```yaml
  arguments:
    parameters:
      - name: model_horizon
        default: 0d
```
Corresponding widget:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/62248514/134200668-333cc8cc-21b6-4cb2-8931-c88c82d23019.png">

Furthermore, if you submit the workflow without populating the fields it will create a workflow with the input parameters set to `undefined` rather than the default value.

However setting a `value` rather than a `default` will result in everything working as expected.

```yaml
  arguments:
    parameters:
      - name: model_horizon
        value: 0d
```

<img width="346" alt="image" src="https://user-images.githubusercontent.com/62248514/134200879-81d7530d-70fc-456b-9205-b284b19fa44b.png">

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? AWS EKS

What version of Argo Workflows are you running? 3.1.8

What executor are you running? PNS

Did this work in a previous version? I.e. is it a regression? Unsure - only ever used 3.1.8

Are you pasting thousands of log lines? That's too much information. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Sorry about the labels. Would you like to submit a PR to fix?

**Comment by kennytrytek-wf** [comment]
Hello, I've taken a closer look at this, and found that the workflow in the issue description is invalid. Arguments cannot have default values. For example, consider this workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arg-defaults
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: say-arg-default
          template: say-message

  - name: say-message
    inputs:
      parameters:
        - name: message
          default: "param default message"
    outputs:
      parameters:
        - name: message
          valueFrom:
            path: /tmp/message
    script:
      image: alpine:3
      command: [/bin/sh]
      source: |
        echo "{{inputs.parameters.message}}" > /tmp/message
```
This workflow cannot be submitted:
```
$ argo submit ./arg-defaults.yaml 
2021/10/04 19:19:31 Failed to submit workflow: templates.main.tasks.say-arg-default.arguments.message.value is required
```

However, this does bring up a good point that the parameter default values are not being used in the UI. If I change the above workflow to be a `WorkflowTemplate`:
```
$ argo template create ./arg-defaults.yaml 
Name:                arg-defaults
Namespace:           argo
Created:             Mon Oct 04 19:28:09 -0500 (now)
```

When I go to submit it in the UI at http://localhost:8080/workflow-templates/argo/arg-defaults, I see this:
![Screen Shot 2021-10-04 at 7 28 46 PM](https://user-images.githubusercontent.com/1466480/135942082-387a569d-d279-4b5b-abda-1606f9331a56.png)

I would expect that message value to be filled with the parameter default, but instead it is empty. This still results in the default value being applied on workflow submission, but makes what is about to happen less visible to the user.

I can see a couple things that could be done here:
1. Make default input parameters appear in the UI.
2. Modify the workflow spec to accept `default` for an `argument` instead of requiring `value` (and make _those_ default values appear in the UI).

@alexec, I'd like to propose a pull request for making input parameters appear in the UI. What are your thoughts about the second item?
