### ISSUE TITLE
Status message is missing from DAG workflow on failure

### ISSUE THREAD

**Issue by emaincourt** [argoproj/argo-workflows#6792]
## Summary

Hi,

I'm quite new to using DAGs with Argo so I might understand it wrong. However, when running a DAG workflow, the error message from the failed task does not get assigned to the workflow status message as it does for classic workflows.

Globally speaking, in case of failure, a DAG workflow does not seem to have a `.Status.Message` field. But the [documentation](https://argoproj.github.io/argo-workflows/fields/#fields_4) does not seem to state anything about that.

In my case I'm using this field to filter out false positives on alerting purpose with argo-events. Having this field set for classic workflows and not for DAGs makes it difficult to create filters, and requires to define multiple event sources as if a field is missing, [argo-events automatically discards the event](https://github.com/argoproj/argo-events/blob/871b1468cf48f255ea4af5f277d94ae19b2909d3/eventsources/sources/resource/start.go#L302), which also makes sense. 

Basically, a filter like the following would make argo-events ignore the event immediately for DAGs:

```yaml
fields:
  - key: status.message
    operation: "!="
    value: "Stopped with strategy 'Terminate'"
```

Is it something that should be expected or would it be possible to have, if not the one from the failed task, a message at all ?

I would obviously be very glad to help implementing this if needed.

Thanks in advance

Argo v3.1.8

## Diagnostics

Run the following workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-error-message-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: fail
            template: echo-status
            arguments:
              parameters:
                - name: status
                  value: "1"

    - name: echo-status
      inputs:
        parameters:
          - name: status
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["exit {{inputs.parameters.status}}"]
```

From both the UI and the workflow manifest, we can tell that task `fail` failed with message `Error (exit code 1)`. However, the workflow itself does not have a `.Status.Message` value.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
