### ISSUE TITLE
Steps after httpTemplate are not visible

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#6794]
![image](https://user-images.githubusercontent.com/61470342/134559088-fda7bce9-4866-4af0-b21d-7fbb08ea9d2b.png)

```
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: get-branch-from-env
spec:
  entrypoint: get-branch-from-env
  arguments:
    parameters:
      - name: url
        value: "https://redacted.com/env/"
  templates:
    - name: get-branch-from-env
      inputs:
        parameters:
          - name: url
      steps:
        - - name: call-env
            template: http
            arguments:
              parameters:
                - name: url
                  value: "{{inputs.parameters.url}}"
        - - name: parse-branch
            template: parse-branch
            arguments:
              parameters:
                - name: env-output
                  value: "{{steps.call-env.outputs.parameters.result}}"
      outputs:
        parameters:
          - name: branch-from-env
            valueFrom:
              parameter: "{{steps.parse-branch.outputs.result}}"

    - name: http
      inputs:
        parameters:
          - name: url
      http:
        url: "{{inputs.parameters.url}}"
        method: GET
      outputs:
        parameters:
          - name: result
            value: default

    - name: parse-branch
      inputs:
        parameters:
          - name: env-output
      script:
        image: forbes-docker.jfrog.io/alpine:latest
        command: [sh]
        source: |-
          echo "{{inputs.parameters.env-output}}" | egrep "^branch: " | sed -E 's/^branch:[[:space:]]+(.*)<br \/>/\1/'
```
