### ISSUE TITLE
Respect order of `envFrom` and `env` in container/script spec to enable k8s dependent variables feature

### ISSUE THREAD

**Issue by vadimgusev-codefresh** [argoproj/argo-workflows#6795]
# Summary

Currently step Pods are created with such spec no matter in which order `env` and `envForm` were defined in:

```yaml
spec:
  containers:
  - name: foo
    env: []
    envFrom: []
```

I would like the order of `env` and `envFrom` to be respected.

# Use Cases

This will enable usage of k8s [dependent variables](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/) feature. This is because definition order of variables matters for this particular feature. Refer to the examples in documentation. I personally account for that in my Helm templates, for example in constructing database connection strings form multiple secret fields.

However in Workflows I have no control over final Pod spec. Example usage of this feature is ENV construction form multiple secret values:

```yaml
script:
  workingDir: '{{ inputs.artifacts.repo.path }}'
  image: alpine/helm:3.5.3
  envFrom:
  - secretRef:
      name: '{{ inputs.parameters.CHARTMUSEUM_SECRET }}'
    prefix: CHARTMUSEUM_
  env:
  - name: CHARTMUSEUM_URL
    # TO MAKE THIS WORK ARGO SHOULD PUT `envFrom` before `env` in pod spec, just like I defined it here
    value: $(CHARTMUSEUM_PROTO)://$(CHARTMUSEUM_USERNAME):$(CHARTMUSEUM_PASSWORD)@$(CHARTMUSEUM_HOST)
```

At this moment (`v.3.2.0-rc4`) Pod spec is rendered in fixed order:

```yaml
env:
- name: CHARTMUSEUM_URL
  value: $(CHARTMUSEUM_PROTO)://$(CHARTMUSEUM_USERNAME):$(CHARTMUSEUM_PASSWORD)@$(CHARTMUSEUM_HOST)
...
envFrom:
- prefix: CHARTMUSEUM_
  secretRef:
    name: chartmuseum-credentials
```
And that leaves `CHARTMUSEUM_URL` as literal `$(CHARTMUSEUM_PROTO)://$(CHARTMUSEUM_USERNAME):$(CHARTMUSEUM_PASSWORD)@$(CHARTMUSEUM_HOST)` in full compliance with k8s feature documentation.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
