### ISSUE TITLE
withParam with AnySucceeded depends logic

### ISSUE THREAD

**Issue by jgibson2** [argoproj/argo-workflows#6799]
# Summary

`task.AnySucceeded` works with a `withItems` loop correctly, but when using it with `withParam` we get an error such as:

```

```

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jgibson2** [comment]
withItems workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: steps-withitems-anysucceeded
spec:
  entrypoint: loops-dag
  podGC:
    strategy: OnWorkflowSuccess
  templates:
  - name: loops-dag
    dag:
      tasks:  
      - name: A
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems: ["a", "b", "c"]
      - name: B
        depends: "A.AnySucceeded"
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "At least one succeeded"
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

withParams workflow (fails):
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: steps-withparam-anysucceeded
spec:
  entrypoint: loops-dag
  podGC:
    strategy: OnWorkflowSuccess
  arguments:
    parameters:
      - name: abcs
        value: ["a", "b", "c"]
  templates:
  - name: loops-dag
    inputs:
      parameters:
        - name: abcs
    dag:
      tasks:  
      - name: A
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withParam: "{{inputs.parameters.abcs}}"
      - name: B
        depends: "A.AnySucceeded"
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "At least one succeeded"
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```
