### ISSUE TITLE
aggregate or separately process the output artifacts of parallel pods

### ISSUE THREAD

**Issue by clumsy456** [argoproj/argo-workflows#6805]
# Summary

If a dag/task includes withItems/withParam parameter, we are not able to resolve its output artifacts, as is shown in #1625. I suggest a syntax to aggregate or separately process the output artifacts of parallel pods.

# Use Cases

There are two situations to use the output artifacts of parallel pods.
## separately process
```
        |---> Pod1_1 ---|---> Pod2_1
begin --|---> Pod1_2 ---|---> Pod2_2
        |---> Pod1_3 ---|---> Pod2_3
```
- Task1 includes withItems/withParam parameters, and 3 pods executed actually.
- Task2 will also create 3 pods, and each pod will process the previous output artifacts of task1 one-on-one.

I suggest task2 should include `withParam` parameter which refers to the output of task1, so the number of pods of task2 will be equal to that of task1.
```yaml
spec:
  entrypoint: dag
  templates:
  - name: dag
    dag:
      tasks:
      # generate output artifacts of parallel pods
      - name: gen
        template: gen-artifact
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems: ["1", "2", "3"]
      # process only one path
      - name: deal-path1
        template: deal-one-path
        arguments:
          artifacts:
          - name: path
            from: "{{item}}"
        withParam: "{{tasks.gen.outputs.artifacts.path1}}"
      # process multi path
      - name: deal-paths
        template: deal-two-path
        arguments:
          artifacts:
          - name: path1
            from: "{{item.path1}}"
          - name: path2
            from: "{{item.path2}}"
        withParam: "{{tasks.gen.outputs.artifacts}}"
      # process param and path
      - name: deal-param-path
        template: deal-param-path
        arguments:
          parameters:
          - name: param
            value: "{{item.parameters.param}}"
          artifacts:
          - name: path
            value: "{{item.artifacts.path1}}"
        withParam: "{{tasks.gen.outputs}}"

  - name: gen-artifact
    inputs:
      parameters:
      - name: message
        ...
    outputs:
      parameters:
      - name: param
        ...
      artifacts:
      - name: path1
        ...
      - name: path2
        ...
  - name: deal-one-path
    inputs:
      artifacts:
      - name: path
        ...
  - name: deal-two-path
    inputs:
      artifacts:
      - name: path1
        ...
      - name: path2
        ...
  - name: deal-param-path
    inputs:
      parameters:
      - name: param
        ...
      artifacts:
      - name: path
        ...
```
- if `withParam` is `{{tasks.A.outputs.artifacts.path}}`, we can use `{{item}}` to refer the output artifact;
- if `withParam` is `{{tasks.A.outputs.artifacts}}`, we can use `{{item.path1}}` and `{{item.path2}}` to refer to multi output artifacts of one pod;
- if `withParam` is `{{tasks.A.outputs}}`, we can use `{{item.parameters.param}}` and `{{item.artifacts.path}}` to refer to output parameter and artifact of one pod.

## aggregate
```
        |---> Pod1_1 ---|
begin --|---> Pod1_2 ---|---> Pod2
        |---> Pod1_3 ---|
```
- Task1 includes withItems/withParam parameters, and 3 pods executed actually.
- Task2 will aggregate all the output artifacts of the 3 pods in one pod.

I suggest add `fromMulti` and `pathMulti` field to tasks.arguments.artifacts and templates.inputs.artifacts seperately.
```yaml
spec:
  entrypoint: dag
  templates:
  - name: dag
    dag:
      tasks:
      # generate output artifacts of parallel pods
      - name: gen
        template: gen-artifact
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems: ["1", "2", "3"]
      # aggregate
      - name: aggregate
        template: aggregate
        arguments:
          artifacts:
          - name: paths
            fromMulti: "{{tasks.gen.outputs.artifacts.path}}"

  - name: gen-artifact
    inputs:
      parameters:
      - name: message
        ...
    outputs:
      artifacts:
      - name: path
        ...
  - name: aggregate
    inputs:
      artifacts:
      - name: paths
        pathMulti: /tmp/path
        ...
```
`pathMulti` is just a template. It will be prefixed with the index. The actual path in the aggregation pod, will be /tmp/0_path, /tmp/1_path and /tmp/2_path.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think this one of the intended uses of key-only artifacts.

Could you achieve this by writing each output to a unique key within bucket storage, and have the aggregating/grouping pod can then just list the key within the bucket to find the needed files:

```yaml
spec:
  entrypoint: dag
  templates:
  - name: dag
    dag:
      tasks:
      # generate output artifacts of parallel pods
      - name: gen
        template: gen-artifact
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems: ["1", "2", "3"]
        outputs:
          artifacts:
           - name: output
              path: /output
              s3:
                key: "{{workflow.name}}/{{item}}"
      # aggregate
      - name: aggregate
        template: aggregate

  - name: gen-artifact
    inputs:
        ...
    outputs:
      artifacts:
      - name: output
         path: /output
        ...
  - name: aggregate
    inputs:
      artifacts:
      - name: input
         path: /inputs
           s3:
              key: "{{workflow.name}}"
```

The use of `key: "{{workflow.name}}/{{item}}" for generation and then ` key: "{{workflow.name}}"` for aggregation is the key.

**Comment by jixinchi** [comment]
> I think this one of the intended uses of key-only artifacts.
> 
> Could you achieve this by writing each output to a unique key within bucket storage, and have the aggregating/grouping pod can then just list the key within the bucket to find the needed files:
> 
> ```yaml
> spec:
>   entrypoint: dag
>   templates:
>   - name: dag
>     dag:
>       tasks:
>       # generate output artifacts of parallel pods
>       - name: gen
>         template: gen-artifact
>         arguments:
>           parameters:
>           - name: message
>             value: "{{item}}"
>         withItems: ["1", "2", "3"]
>         outputs:
>           artifacts:
>            - name: output
>               path: /output
>               s3:
>                 key: "{{workflow.name}}/{{item}}"
>       # aggregate
>       - name: aggregate
>         template: aggregate
> 
>   - name: gen-artifact
>     inputs:
>         ...
>     outputs:
>       artifacts:
>       - name: output
>          path: /output
>         ...
>   - name: aggregate
>     inputs:
>       artifacts:
>       - name: input
>          path: /inputs
>            s3:
>               key: "{{workflow.name}}"
> ```
> 
> The use of `key: "{{workflow.name}}/{{item}}"` for generation and then ` key: "{{workflow.name}}"` for aggregation is the key.

Thanks for your reply!
- As far as I know, there is no `outputs` field in the `task` struct. I'm not sure if you meant to put `s3.key` into `templates[gen-artifact].outputs.artifacts`
- In our usual use, we tend to use `templateRef` in the dag type template, and put the container type template into an individual `WorkflowTemplate`, so that different workflows can use the same container and its inputs and outputs. If we use `s3.key` and `{{workflow.name}}` in an container type template, we cannot achieve the decoupling described above.

**Comment by jixinchi** [comment]
Sorry for replying to you with my company account. "jixinchi" is my company account and "clumsy456" is my personal account. I should have used my company account to raise this issue.

**Comment by alexec** [comment]
You are correct, it is in the template:

```yaml

spec:
  entrypoint: dag
  templates:
  - name: dag
    dag:
      tasks:
      # generate output artifacts of parallel pods
      - name: gen
        template: gen-artifact
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems: ["1", "2", "3"]
      # aggregate
      - name: aggregate
        template: aggregate

  - name: gen-artifact
    inputs:
        ...

    outputs:
          artifacts:
           - name: output
              path: /output
              s3:
                key: "{{workflow.name}}/{{item}}"
        ...
  - name: aggregate
    inputs:
      artifacts:
      - name: input
         path: /inputs
           s3:
              key: "{{workflow.name}}"
```
