### ISSUE TITLE
Executor resource requests not applied to init/wait containers

### ISSUE THREAD

**Issue by zorulo** [argoproj/argo-workflows#6809]
## Summary

**What happened/what you expected to happen?**

We've recently tried upgrading argo from 2.11.x to the latest to take advantage of new features, namely the emissary executor. 

However, now when specifying executor requests for the init/wait containers as described in the [workflow-controller-configmap here](https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-controller-configmap.yaml#L186), the resource requests do not seem to be getting applied like before.

We've tried numerous versions from 2.12.x onwards but none seem to properly apply resource requests as expected.

**What version is it broken in?**

Anything >= 2.12.x

**What version was it working in?**

2.11.x

## Diagnostics

Simple hello world workflow that reproduces this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: hello
  templates:
  - name: hello
    container:
      image: alpine:3.6
      command: [sh, '-c']
      args: ["echo \"Hello world!\""]
```

Running `kubectl describe pod <pod>` on the resulting pod shows that there are no resource requests for the init/wait containers (3.1.12):

```
  wait:
    Container ID:  docker://a2f8d0f4a7e879eec2262d817d526ba4d63c360b47a3cb32b8d3df744b0089b7
    Image:         ...
    Image ID:      ...
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
      --loglevel
      info
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 27 Sep 2021 11:20:09 -0700
      Finished:     Mon, 27 Sep 2021 11:20:10 -0700
    Ready:          False
    Restart Count:  0
    Environment:
      ARGO_POD_NAME:                    hello-world-k22ng (v1:metadata.name)
      ARGO_CONTAINER_RUNTIME_EXECUTOR:  emissary
      GODEBUG:                          x509ignoreCN=0
      ARGO_CONTAINER_NAME:              wait
      ARGO_INCLUDE_SCRIPT_OUTPUT:       false
```

Expected output (2.11.8):

```
  wait:
    Container ID:  docker://d5c3015d2af78b9f537667b490335ba889e3bf31618ff8bc78be52a23b378a22
    Image:         ...
    Image ID:      ...
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 27 Sep 2021 11:22:19 -0700
      Finished:     Mon, 27 Sep 2021 11:22:19 -0700
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     2
      memory:  4Gi
    Environment:
      ARGO_POD_NAME:  hello-world-pvd72 (v1:metadata.name)
```

Our workflow controller configmap specifies as follows:
```
  executor: |
    resources:
      requests:
        cpu: 2
        memory: 4Gi
```

**What Kubernetes provider are you using?**

AWS EKS

**What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary**

Tried docker and emissary

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
