### ISSUE TITLE
Have dropdown-lists and checkboxes for workflow inputs in GUI

### ISSUE THREAD

**Issue by eileensheu** [argoproj/argo-workflows#6824]
# Summary
It would be nice if there are more GUI features for input parameters (i.e. `spec.arguments.parameters`).
For example:
- dropdown-list for single-selection or multi-selection
- checkbox for boolean parameters

Something like (just an idea):
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: workflow-param-1
      type: boolean  # would then be presented as a checkbox in GUI
      value: true
    - name: workflow-param-2
      type: list  # would then be presented as a dropdown-list in GUI
      options: ("option1" "option2" "option3")
      value: ("option1" "option2")
  templates:
  - name: main
    dag:
      tasks:
      - name: step-A 
        template: step-template-A
        arguments:
          parameters:
          - name: template-param-1
            value: "{{workflow.parameters.workflow-param-1}}"
...
```

**Comment by iochagov** [comment]
It would be great to have this feature!

**Comment by asterix201** [comment]
it could be a very useful feature for us

**Comment by tczhao** [comment]
Turned out there's already this functionality, just a bit hard to find

For the boolean case, how about just using a 2 values dropdown, that should achieve the same purpose?

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-with-enum-values
spec:
  entrypoint: argosay
  arguments:
    parameters:
      - name: message
        value: one
        enum:
          -   one
          -   two
          -   three
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
```

**Comment by eileensheu** [comment]
> 
> 
> Turned out there's already this functionality, just a bit hard to find
> 
> For the boolean case, how about just using a 2 values dropdown, that should achieve the same purpose?
> 
> ```
> apiVersion: argoproj.io/v1alpha1
> kind: WorkflowTemplate
> metadata:
>   name: workflow-template-with-enum-values
> spec:
>   entrypoint: argosay
>   arguments:
>     parameters:
>       - name: message
>         value: one
>         enum:
>           -   one
>           -   two
>           -   three
>   templates:
>     - name: argosay
>       inputs:
>         parameters:
>           - name: message
>             value: '{{workflow.parameters.message}}'
>       container:
>         name: main
>         image: 'argoproj/argosay:v2'
>         command:
>           - /argosay
>         args:
>           - echo
>           - '{{inputs.parameters.message}}'
> ```

This works well! Thanks a lot for this information!

I personally would be fine with a two-values-dropdown for the boolean case :)

How about multi-selection in the dropdown? The current dropdown seems to only support single-selection (I've tried holding `ctrl` or `shift` yet still only single option got selected)

**Comment by tczhao** [comment]
with multi-selection,
we probably need an option to specify the separator
and in the future probably min number of selections and max number of selections
```
spec:
  entrypoint: argosay
  arguments:
    parameters:
      - name: message
        value: one
        ui:
            enum:
              -   one
              -   two
              -   three
            separator: ","
```

Hi@alexec
Would it be a good idea to introduce `ui` in parameter, and do a breaking change to move `enum` under `ui`?
Considering these parameter fields are only consumed by the UI and there's potential that more fields will be added.
Doing it this way may provide a clearer separation
