### ISSUE TITLE
Cron Backfill example doesn't work

### ISSUE THREAD

**Issue by duwanqiebi** [argoproj/argo-workflows#6832]
I want to test this example https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/cron-backfill.yaml, , but unfortunately it doesn't work.

When I try to submit the CronWorkflow, I get this error :
`spec.arguments.date.value is required`

Here is the complete file,

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: duwan-test-job
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: date
  templates:
    - name: main
      inputs:
        parameters:
          - name: date
            value: "{{inputs.parameters.date}}"
            # use "yesterday" is a magic value to tell the script it needs to determine the day to run
            default: yesterday
      script:
        image: docker/whalesay:latest
        command:
          - sh
        source: |
          date="{{inputs.parameters.date}}"
          if [ $date = yesterday ]; then
            date=$(date -d yesterday +%Y-%m-%d)
          fi
          echo "run for $date"
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: duwan-test-daily-job
spec:
  schedule: "0/5 * * * *"
  workflowSpec:
    workflowTemplateRef:
      name: duwan-test-job
```

I also read this issue: https://github.com/argoproj/argo-workflows/issues/3807 and add `entrypoint`:

```yaml
workflowSpec:
    entrypoint: main
    workflowTemplateRef:
      name: duwan-test-job
```

But it does not work too.

My argo version:

```bash
➜   argo version
argo: v3.1.10
  BuildDate: 2021-09-10T18:47:08Z
  GitCommit: 2730a51a203d6b587db5fe43a0e3de018a35dbd8
  GitTreeState: clean
  GitTag: v3.1.10
  GoVersion: go1.15.7
  Compiler: gc
  Platform: darwin/amd64
```

**Comment by tczhao** [comment]
Had a look, I think the example isn't exactly correct.
Can you try the following
```
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: date
        # use "yesterday" is a magic value to tell the script it needs to determine the day to run
        value: yesterday
  templates:
    - name: main
      inputs:
        parameters:
          - name: date
            default: "{{inputs.parameters.date}}"
      script:
        image: docker/whalesay:latest
        command:
          - sh
        source: |
          date="{{inputs.parameters.date}}"
          if [ $date = yesterday ]; then
            date=$(date -d yesterday +%Y-%m-%d)
          fi
          echo "run for $date"
```
