### ISSUE TITLE
When using input parameters, output string parameters have extra brackets around them

### ISSUE THREAD

**Issue by andrew-arkhipov** [argoproj/argo-workflows#6844]
## Summary

What happened/what you expected to happen?

Given a task that writes a string to some file and then returns that string as an output parameters, if non-hardcoded input parameters are provided to that task, the output parameter is returned as `"['example output']"` rather than `'example output'`. However, if we hardcode the input parameters (and subsequently delete the `withParam` field), we don't see this error. Try it for yourself by hardcoding the `image` argument for both tasks in the dag.

### What version of Argo Workflows are you running?

v3.1.5

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: <namespace>
  generateName: pipe-test-

spec:
  arguments:
    parameters:
      - name: params
        value: |
          []
  artifactRepositoryRef:
    configMap: workflow-controller-configmap
    key: artifactRepository
  hostNetwork: true
  entrypoint: pipe
  ttlStrategy:
    secondsAfterCompletion: 604800
    secondsAfterSuccess: 604800
    secondsAfterFailure: 604800
  podGC:
    strategy: OnPodSuccess
  templates:
    - name: pipe
      inputs:
        parameters:
          - name: params
            value: |
              []
      outputs: {}
      metadata: {}
      dag:
        tasks:
          - name: build-command
            template: build-command
            arguments:
              parameters:
                - name: image
                  value: '{{item.image}}'
            withParam: '{{inputs.parameters.params}}'
          - name: run-pipeline
            template: run-pipeline
            arguments:
              parameters:
                - name: image
                  value: '{{item.image}}'
                - name: invoke-command
                  value: '{{tasks.build-command.outputs.parameters.command}}'
            withParam: '{{inputs.parameters.params}}'
            dependencies:
              - build-command

    - name: build-command
      serviceAccountName: <serviceAccount>
      inputs:
        parameters:
          - name: image
      outputs:
        parameters:
          - name: command
            valueFrom:
              path: /tmp/command.txt
      script:
        name: ''
        image: '{{inputs.parameters.image}}'
        command:
          - python
        resources: {}
        source: |
          with open('/tmp/command.txt', 'w') as f:
            f.write("echo test")

    - name: run-pipeline
      inputs:
        parameters:
          - name: image
          - name: invoke-command
      container:
        image: '{{inputs.parameters.image}}'
        command: [sh, -c]
        args: ['{{inputs.parameters.invoke-command}}']
        resources: {}
        imagePullPolicy: IfNotPresent
      retryStrategy:
        limit: '4'
        retryPolicy: OnError
        backoff:
          duration: '10'
      serviceAccountName: <serviceAccount>
```

### What Kubernetes provider are you using?

On-prem

### What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

PNS

```bash
Don't have access to all the logs

# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# The workflow's pods that are problematic:
sh: 1: [echo test]: not found

# Logs from in your workflow's wait container, something like:
W
kubernetes.pod.namespace=<REDACTED> --filter=label=io.kubernetes.pod.name=pipe-test-zxvnn-3890438771"
time="2021-10-01T15:57:39.969Z" level=info msg="listed containers" containers="map[main:{dcac09b802acd0cb317a556e66a5f21887dcd362fb493cdf49a57733c5c107c3 Created {0 63768700659 <nil
>}} wait:{7d7f02fa9adaf4b2650227ae903acba3308de9d788ee8c16b583136874b27f37 Up {0 63768700659 <nil>}}]"
time="2021-10-01T15:57:39.969Z" level=info msg="mapped container name \"main\" to container ID \"dcac09b802acd0cb317a556e66a5f21887dcd362fb493cdf49a57733c5c107c3\" (created at 2021-
10-01 15:57:39 +0000 UTC, status Created)"
time="2021-10-01T15:57:39.969Z" level=info msg="mapped container name \"wait\" to container ID \"7d7f02fa9adaf4b2650227ae903acba3308de9d788ee8c16b583136874b27f37\" (created at 2021-
10-01 15:57:39 +0000 UTC, status Up)"
time="2021-10-01T15:57:40.930Z" level=info msg="docker wait dcac09b802acd0cb317a556e66a5f21887dcd362fb493cdf49a57733c5c107c3"
time="2021-10-01T15:57:41.030Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=label=io.
kubernetes.pod.namespace=mld1-workflows-dev --filter=label=io.kubernetes.pod.name=pipe-test-zxvnn-3890438771"
time="2021-10-01T15:57:41.137Z" level=info msg="Main container completed"
time="2021-10-01T15:57:41.137Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-10-01T15:57:41.137Z" level=info msg="Saving logs"
time="2021-10-01T15:57:41.138Z" level=info msg="listed containers" containers="map[main:{dcac09b802acd0cb317a556e66a5f21887dcd362fb493cdf49a57733c5c107c3 Exited {0 63768700659 <nil>
}} wait:{7d7f02fa9adaf4b2650227ae903acba3308de9d788ee8c16b583136874b27f37 Up {0 63768700659 <nil>}}]"
time="2021-10-01T15:57:41.138Z" level=info msg="[docker logs dcac09b802acd0cb317a556e66a5f21887dcd362fb493cdf49a57733c5c107c3]"
time="2021-10-01T15:57:41.240Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: <REDACTED>/pipe-test-zxvnn/pipe-test-zxvnn-3890438771/main.log"
time="2021-10-01T15:57:41.240Z" level=info msg="Creating minio client s3.amazonaws.com using static credentials"
time="2021-10-01T15:57:41.240Z" level=info msg="Saving from /tmp/argo/outputs/logs/main.log to s3 <REDACTED>
time="2021-10-01T15:57:41.396Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2021-10-01T15:57:41.396Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2021-10-01T15:57:41.396Z" level=info msg="No output parameters"
time="2021-10-01T15:57:41.396Z" level=info msg="No output artifacts"
time="2021-10-01T15:57:41.396Z" level=info msg="Annotating pod with output"
time="2021-10-01T15:57:41.409Z" level=info msg="Patch pods 200"
time="2021-10-01T15:57:41.416Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=label=io.
kubernetes.pod.namespace=mld1-workflows-dev --filter=label=io.kubernetes.pod.name=pipe-test-zxvnn-3890438771"
time="2021-10-01T15:57:41.444Z" level=info msg="listed containers" containers="map[main:{dcac09b802acd0cb317a556e66a5f21887dcd362fb493cdf49a57733c5c107c3 Exited {0 63768700659 <nil>
}} wait:{7d7f02fa9adaf4b2650227ae903acba3308de9d788ee8c16b583136874b27f37 Up {0 63768700659 <nil>}}]"
time="2021-10-01T15:57:41.444Z" level=info msg="Killing sidecars []"
time="2021-10-01T15:57:41.444Z" level=info msg="Alloc=9440 TotalAlloc=18045 Sys=74321 NumGC=5 Goroutines=12"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@andrew-arkhipov I tried with the latest version. I am not able to reproduce above issue
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cache-key-test-
spec:
  entrypoint: run-all
  templates:
    - name: run-all
      steps:
        - - name: run-first
            template: run-first
        - - name: run-second
            template: run-second
            arguments:
              parameters:
                - name: message
                  value: "{{steps.run-first.outputs.parameters.message}}"
    - name: run-first
      outputs:
        parameters:
          - name: message
            valueFrom:
              path: /tmp/command.txt
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          with open('/tmp/command.txt', 'w') as f:
            f.write("echo test")
    - name: run-second
      inputs:
        parameters:
          - name: message
      script:
        image: bash
        command: [bash]
        source: |
          echo '{{inputs.parameters.message}}'
```
output:
```txt
k logs cache-key-test-2wvmt-run-second-3400220546 main
echo test
```

**Comment by andrew-arkhipov** [comment]
@sarabala1979 You missed the entire point of the issue. If I do not include input parameters, or I simply hardcode those parameters in to be consumed by the offending template, there is no issue. However, when those parameters are dynamic, or passed in via the `withParam` keyword, that's when I get an error. Your example above (see `run-first`) does not contain any input parameters, so yes, it makes sense that you can't reproduce the issue.

For example, having this as the arguments section to `build-command` in my original workflow will cause the error:
```yaml
arguments:
  parameters:
    - name: image
      value: '{{item.image}}'
withParam: '{{inputs.parameters.params}}'
```
However, having this will throw no issues:
```yaml
arguments:
  parameters:
    - name: image
      value: golang:1.8
```
Why don't you try running my template exactly as is (and updating the values as needed)?

Thanks for your help!
