### ISSUE TITLE
Nodes Not Being Redraw in UI when Workflow Retried After Exceeding activeDeadlineSeconds

### ISSUE THREAD

**Issue by jfb74** [argoproj/argo-workflows#6849]
## Summary

What happened/what you expected to happen?
Might be that someone else submitted an issue on this but I can't seem to find it if so. I have a workflow with various nested steps which loops over using a `withItems` creating the actual execution steps each which have `activeDeadlineSeconds` limit on them. The issue comes from when the `runcollect` step runs the command and the pod runtime exceeds the `activeDeadlineSeconds`. At that point the workflow will fail and I will click retry on the workflow which I would expect to re-start the pods and then show those pods as nodes via the UI. What I find though is that the pods do get kicked off in the backend but on the frontend those nodes are not being redrawn. Once the individual execution step completes and the parent step completes, the workflow continues to further steps in the pipeline (which I have omitted for simplicity from the example yaml below).

What version of Argo Workflows are you running? I have tried this on v2.11.4, v2.12.7, and the latest v3.1.13

## Diagnostics

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: dag-nested-
  namespace: argo
spec:
  serviceAccountName: workflow
  entrypoint: workflowRun
  templates:
    - name: runcollect
      activeDeadlineSeconds: 7200
      retryStrategy:
        limit: 25
        retryPolicy: "Always"
        backoff:
          duration: 2m
          factor: 2
          maxDuration: 30m
      inputs:
        parameters:
          - name: scriptName
      container:
        image: "myImage:latest"
        imagePullPolicy: Always
        command: ["/bin/bash", "--login", "-ic"]
        args:
          - >-
            python runMyScript.py --param {{inputs.parameters.scriptName}}
    - name: runStepOneDetail
      inputs:
        parameters:
          - name: scriptName
      dag:
        tasks:
          - name: runFirstCollect
            template: runcollect
            arguments:
              parameters:
                - name: scriptName
                  value: "{{inputs.parameters.scriptName}}"
    - name: runStepOne
      parallelism: 2
      dag:
        tasks:
          - name: runStepOne
            template: runStepOneDetail
            arguments:
              parameters:
                - name: scriptName
                  value: "{{item.script}}"
            withItems:
              - script: message_details
              - script: messages
              - script: items
              - script: manual_drops
              - script: emails
    - name: workflowRun
      steps:
        - - name: runCollect
            template: runStepOne
```

What Kubernetes provider are you using? EKS

What executor are you running? Docker
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
What happens if you refresh the page?

**Comment by jfb74** [comment]
@alexec The status of the workflow shows as "Failed" and seems to update appropriately once to "running" once I Retry the workflow. Interestingly though, the Message for why it failed says something like `child 'my-workflow-sbf5w-2635620201' failed` in which the "my-workflow-sbf5w" matches the workflow identifier but there is no child I see with the unique identifier of "2635620201". I have to dig a bit more into it because by the time I noticed it our elastic node spun down so the underlying kubernetes pods were pruned.

**Comment by jfb74** [comment]
@sarabala1979 @alexec I was able to generate a complete yaml that replicates the behavior using the python3.9 docker image. What this does is spawn 3 children which are purposefully written to randomly fail. If at least one node fails you can "Retry" the workflow and the children nodes disappear. If all three children nodes succeed, it will move to the next step, but the 3 children nodes are not redrawn in the UI. See that flow of actions below.

Failed:
![image](https://user-images.githubusercontent.com/6969831/149569274-d55ab188-80df-40b5-a25c-333c3822a2d1.png)


After Clicking Retry:
![image](https://user-images.githubusercontent.com/6969831/149569301-bc896d48-2df2-4255-b1da-a27dee7b1172.png)

3 Children Nodes Succeed:
![image](https://user-images.githubusercontent.com/6969831/149569490-bd107b9b-c3ca-4329-973e-4c6550be5149.png)


```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: dag-nested-
  namespace: argo
spec:
  serviceAccountName: workflow
  entrypoint: workflowRun
  templates:
    - name: runcollect
      inputs:
        parameters:
          - name: scriptName
      container:
        image: "python:3.9"
        imagePullPolicy: Always
        command: ["/bin/bash", "--login", "-ic"]
        args:
          - >-
            python -c "import sys; import random; print('failed'); sys.exit(1) if random.random() < 0.5 else print('Hello')"
    - name: runStepOneDetail
      inputs:
        parameters:
          - name: scriptName
      dag:
        tasks:
          - name: runFirstCollect
            template: runcollect
            arguments:
              parameters:
                - name: scriptName
                  value: "{{inputs.parameters.scriptName}}"
    - name: runStepOne
      dag:
        tasks:
          - name: runStepOne
            template: runStepOneDetail
            arguments:
              parameters:
                - name: scriptName
                  value: "{{item.script}}"
            withItems:
              - script: message_details
              - script: messages
              - script: items
    - name: nextStep
      container:
        image: "python:3.9"
        imagePullPolicy: Always
        command: ["/bin/bash", "--login", "-ic"]
        args:
          - >-
            python -c "print('Made it to Next Step')"
    - name: workflowRun
      steps:
        - - name: runCollect
            template: runStepOne
        - - name: NextStep
            template: nextStep
```
