### ISSUE TITLE
Implement get resource manifest output as an artifact

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#6862]
# Summary
Currently when you try to get a manifest, you can only output it as a variable. When you can a complex data structure, it would be more easy to output it as an artifact.

This is what you can do:
```
  - name: get-workflow-object
    outputs:
      parameters:
      - name: workflow-object
        valueFrom:
          jsonPath: '{}'
    resource:
      action: get
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          name: {{workflow.name}}
          namespace: YOUR-NAMESPACE
```

This is what you should be able to do:
```
  - name: get-workflow-object
    outputs:
      artifacts:
      - name: workflow-object
        valueFrom:
          jsonPath: '{}'
    resource:
      action: get
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          name: {{workflow.name}}
          namespace: YOUR-NAMESPACE
```

# Use Cases

See the related use case : https://github.com/argoproj/argo-workflows/issues/6431

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
