### ISSUE TITLE
sprig truncate doesn't work with workflow.name. Negative truncate doesn't work at all.

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#6863]
## Summary

What happened/what you expected to happen?
See the example workflow attached. Issues are:

- Sprig truncate with a negative number doesn't work.

- Sprig truncating workflow.name doesn't work.

What version of Argo Workflows are you running?
3.1.13

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wfnametest
  namespace: ci
  labels:
    workflows.argoproj.io/container-runtime-executor: emissary
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: nameyThing
      value: "{{workflow.name}}"
    - name: otherNameyThing
      value: "hello-world-and-things"
  templates:
  - name: main
    dag:
      tasks:
          # Outputs "test-{{wor"
        - name: print-failed-message
          template: print-message
          arguments:
            parameters:
              - name: MESSAGE
                value: test-{{= sprig.trunc(5, workflow.parameters.nameyThing) }}

          # Outputs "test-{{= sprig.trunc(5, workflow.name) }}"
        - name: print-failed-message2
          template: print-message
          arguments:
            parameters:
              - name: MESSAGE
                value: test-{{= sprig.trunc(5, workflow.name) }}

          # Outputs "test-{{wor"
        - name: print-failed-message3
          template: print-message
          arguments:
            parameters:
              - name: MESSAGE
                value: test-{{= sprig.trunc(5, workflow.parameters.nameyThing) }}

          # Outputs "test-hello"
        - name: print-working-message
          template: print-message
          arguments:
            parameters:
              - name: MESSAGE
                value: test-{{= sprig.trunc(5, workflow.parameters.otherNameyThing) }}

          # Outputs "test-{{= sprig.trunc(-5, workflow.parameters.otherNameyThing) }}"
        - name: negative-truncate-is-broken
          template: print-message
          arguments:
            parameters:
              - name: MESSAGE
                value: test-{{= sprig.trunc(-5, workflow.parameters.otherNameyThing) }}
                
         # Outputs "test-wfnametest-fnb4x"
        - name: print-raw-message
          template: print-message
          arguments:
            parameters:
              - name: MESSAGE
                value: test-{{workflow.parameters.nameyThing}}
         # Outputs "test-wfnametest-fnb4x"
        - name: print-raw-message2
          template: print-message
          arguments:
            parameters:
              - name: MESSAGE
                value: test-{{workflow.name}}

  - name: print-message
    inputs:
      parameters:
      - name: MESSAGE
    script:
      image: docker/whalesay
      command:
        - cowsay
      args: [ '{{ inputs.parameters.MESSAGE }}' ]

```

What Kubernetes provider are you using? EKS 1.21

What executor are you running? Emissary

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Workflow is using sprig v2.22.0 which doesn't support the negative trunc
https://github.com/Masterminds/sprig/blob/e4c0945838d570720d876a6ad9b4568ed32317b4/strings.go#L189-L194

**Comment by sarabala1979** [comment]
@wanghong230 Do you like to submit the PR. for upgrading Sprig latest version?

**Comment by tim-sendible** [comment]
Cheers folks. What about the `{{workflows.name}}` oddness?

**Comment by wanghong230** [comment]
@sarabala1979 Do you recommend https://github.com/Masterminds/sprig/releases/tag/v3.2.0?

**Comment by tim-sendible** [comment]
@wanghong230 3.2.2 contains a security fix FYI.

**Comment by sarabala1979** [comment]
I recommend go with latest release https://github.com/Masterminds/sprig/releases/tag/v3.2.2  this same as 3.2.0 with an upgraded goutil version.

**Comment by wanghong230** [comment]
> Cheers folks. What about the `{{workflows.name}}` oddness?

@sarabala1979 Do you have the answer for this problem?

**Comment by tim-sendible** [comment]
@alexec this isn't closed. Still waiting for information on the main bit, workflow.name

**Comment by wanghong230** [comment]
Here is my current understanding.

workflow.parameters.nameyThing at print-failed-message is got replaced to be {{workflow.name}}.

In the workflow, spec -> arguments -> parameters, the {{workflow.name}} is being treated as simple string, it won't be replaced with the true workflow name.

Next is to check the code to reason about the logic.

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wfnametest
  namespace: ci
  labels:
    workflows.argoproj.io/container-runtime-executor: emissary
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: nameyThing
      value: "{{workflow.name}}"
    - name: otherNameyThing
      value: "hello-world-and-things"
  templates:
  - name: main
    dag:
      tasks:
          # Outputs "test-{{wor"
        - name: print-failed-message
          template: print-message
          arguments:
            parameters:
              - name: MESSAGE
                value: test-{{= sprig.trunc(5, workflow.parameters.nameyThing) }}
```
