### ISSUE TITLE
Disable default workflow archival from within a particular workflow

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#6864]
Similar to https://github.com/argoproj/argo-workflows/issues/6663 I would like to see an option to disable default workflow persistent archival.

**Comment by alexec** [comment]
You mean logs no?

**Comment by rwong2888** [comment]
No @alexec , I mean the archive to the postgresdb. By default it archives every workflow to the db if it is enabled in the configmap. I would like to bypass the default behaviour by adding a field to say a cron workflow to not archive to the db.

**Comment by alexec** [comment]
This feature exists. See docs.

**Comment by rwong2888** [comment]
Hi @alexec 

I am looking in
https://argoproj.github.io/argo-workflows/fields/#workflowspec

I see `archiveLogs` which is only for logs. I do not see anything to exclude workflow from being archived in `persistence.archive`
https://argoproj.github.io/argo-workflows/workflow-controller-configmap.yaml

Am I missing something?

I would like to see a boolean similar to `archiveLogs`, but for `archiveWorkflow` and set it to false to override the default behaviour of archive workflow defined in the configmap `persistence.archive=true`

**Comment by rwong2888** [comment]
I have this cron workflow

```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: clear-non-running-pods
  labels:
    workflows.argoproj.io/archive-strategy: none
spec:
  schedule: "*/10 * * * *"
```

And this configmap

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  persistence: |
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
      connMaxLifetime: 0s
    nodeStatusOffLoad: false
    archive: true
    archiveTTL: 1095d
    clusterName: playground
    postgresql:
      host: x.x.x.x
      port: 5432
      database: postgres
      tableName: argo_workflows
      userNameSecret:
        name: argo-postgres-config
        key: username
      passwordSecret:
        name: argo-postgres-config
        key: password
      ssl: true
      sslMode: require
```

@alexec I am still seeing the workflow get archived every 10 minutes. I also tried moving the label to `spec.metadata.labels`. Am I missing something?

![image](https://user-images.githubusercontent.com/61470342/152859206-2132b308-3616-44ed-85ce-d1a74dd88c8b.png)

**Comment by alexec** [comment]
I don't see the config in your config map? Make sure you restart the controller.

**Comment by rwong2888** [comment]
I think what you are saying is to set `persistence.archive=false` and add a matchlabel for every workflow I want archived.

I want to do the inverse where the default behaviour is to archive every workflow (`persistence.archive=true`) and there is a label/annotation to exclude resources from archival.

Is my understanding correct @alexec ?

**Comment by alexec** [comment]
I think you can do this:

```yaml
selector:
  matchExpressions:
    - {key: workflows.argoproj.io/archive-strategy, operator: NotIn, values: [none]}
```

**Comment by rwong2888** [comment]
@alexec , I updated the configmap and bounced the server and controller, but still seeing both workflows archiving

```
  workflowDefaults: |
    spec:
      ttlStrategy:
        # secondsAfterSuccess: 10800
        secondsAfterSuccess: 300
        secondsAfterFailure: 259200
  persistence: |
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
      connMaxLifetime: 0s
    nodeStatusOffLoad: false
    archive: true
    archiveTTL: 1095d
    clusterName: playground
    postgresql:
      host: x.x.x.x
      port: 5432
      database: postgres
      tableName: argo_workflows
      userNameSecret:
        name: argo-postgres-config
        key: username
      passwordSecret:
        name: argo-postgres-config
        key: password
      ssl: true
      sslMode: require

      archiveLabelSelector:
        matchExpressions:
          - {key: workflows.argoproj.io/archive-strategy, operator: NotIn, values: [none]}
```

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/61470342/153052106-b5bb2c4c-5489-4edf-a402-aa5701b74bd2.png">

**Comment by Nizar-opt** [comment]
@driv This works. Like what is in @rwong2888's ConfigMap. It just had an indentation issue.
```yaml
    archiveLabelSelector:
      matchExpressions:
        - {key: workflows.argoproj.io/archive-strategy, operator: NotIn, values: [none]}
```
