### ISSUE TITLE
arguments.parameters.value can be referenced as local variable but arguments.parameters.valueFrom.configMapKeyRef can be referenced only as global variable

### ISSUE THREAD

**Issue by apiwoni** [argoproj/argo-workflows#6869]
## Summary

`arguments.parameters.value` can be referenced as a local variable using {{input.parameters.param-name}} but `arguments.parameters.valueFrom.configMapKeyRef` can be referenced only as global variable {{workflow.parameters.param-name}}. This is inconsistent behavior!

Issue [#3212](https://github.com/argoproj/argo-workflows/issues/3212) was fixed by allowing `valueFrom.configMapKeyRef`

What happened/what you expected to happen?

I should be able to access variable declared using `arguments.parameters.valueFrom.configMapKeyRef` as {{input.parameters.param-name}} same as for variable declared as `arguments.parameters.value`

What version of Argo Workflows are you running?
argo: v3.2.0-rc5

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-from-configmap-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
#      value: "can be accessed as inputs.parameters.message"
#     Can only be accessed as global variable workflow.parameters.message but not as local variable inputs.parameters.message        
      valueFrom:
        configMapKeyRef:
          name: simple-parameters
          key: msg
  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
#            Workaround to access valueFrom.configMapKeyRef as local variable        
#            value: "{{workflow.parameters.message}}"  
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```
ConfigMap same as https://github.com/argoproj/argo-workflows/blob/v3.2.0-rc5/examples/configmaps/simple-parameters-configmap.yaml

```
argo submit arguments-parameters-from-configmap.yaml
FATA[2021-10-05T17:47:49.367Z] Failed to submit workflow: templates.whalesay inputs.parameters.message was not supplied 
```

When I replace `arguments.parameters.valueFrom` with `arguments.parameters.value` it works

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Thanks, I was able to reproduce. 

It seems like this case is not supported yet: local parameters defined in `spec.arguments.parameters` using `configMapKeyRef` cannot be referenced by `{{inputs.parameters.xxx}}` in templates. 

In other words, the following should work but it doesn't:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-from-configmap-
spec:
  entrypoint: whalesay
  serviceAccountName: argo
  arguments:
    parameters:
    - name: message
      valueFrom:
        configMapKeyRef:
          name: simple-parameters
          key: msg
  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

I can look into this when I get a chance but in the meantime would you or anyone else watching this issue like to submit a PR to fix this?
