### ISSUE TITLE
Workflow executes steps twice with different labels

### ISSUE THREAD

**Issue by alexglatt** [argoproj/argo-workflows#6874]
## Summary

I want to submit an Argo Workflow with multiple steps. Each step needs the same podMetadata label.
However, all the steps defined in the yaml File are executed twice when I choose parallel execution.
Even more confusing is that only the "duplicate" of each step has the defined label.
When I choose sequential execution, only the very first step is executed twice, all following steps are executed only once.
However, in this case, all the following steps that are executed only once don't have the given label.

Argo Version: v3.1.13
Kubectl Version: v1.22.2

## Diagnostics

Bug can be reproduced very easily with the basic Hello World example:
(this example includes parallel execution. For sequential execution it's "- - name: whalesay-spanish")

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  
  podMetadata:
    labels:
      test: label
  
  templates:
  - name: whalesay
    steps:                          
      - - name: whalesay-english
          template: whalesay-english
        - name: whalesay-spanish
          template: whalesay-spanish
          
  - name: whalesay-english 
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
  
  - name: whalesay-spanish
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hola mundo"]
```

With this parallel example, 4 Pods are created (each step twice) where only the duplicates (latter ones) have the label.
Argo Logs:

```bash
hello-world-j5ttz-434513495:  ____________
hello-world-j5ttz-434513495: < hola mundo >
hello-world-j5ttz-434513495:  ------------
hello-world-j5ttz-434513495:     \
hello-world-j5ttz-434513495:      \
hello-world-j5ttz-434513495:       \
hello-world-j5ttz-434513495:                     ##        .
hello-world-j5ttz-434513495:               ## ## ##       ==
hello-world-j5ttz-434513495:            ## ## ## ##      ===
hello-world-j5ttz-434513495:        /""""""""""""""""___/ ===
hello-world-j5ttz-434513495:   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
hello-world-j5ttz-434513495:        \______ o          __/
hello-world-j5ttz-434513495:         \    \        __/
hello-world-j5ttz-434513495:           \____\______/
hello-world-j5ttz-1652768303:  _____________
hello-world-j5ttz-1652768303: < hello world >
hello-world-j5ttz-1652768303:  -------------
hello-world-j5ttz-1652768303:     \
hello-world-j5ttz-1652768303:      \
hello-world-j5ttz-1652768303:       \
hello-world-j5ttz-1652768303:                     ##        .
hello-world-j5ttz-1652768303:               ## ## ##       ==
hello-world-j5ttz-1652768303:            ## ## ## ##      ===
hello-world-j5ttz-1652768303:        /""""""""""""""""___/ ===
hello-world-j5ttz-1652768303:   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
hello-world-j5ttz-1652768303:        \______ o          __/
hello-world-j5ttz-1652768303:         \    \        __/
hello-world-j5ttz-1652768303:           \____\______/
hello-world-j5ttz-whalesay-spanish-434513495:  ____________
hello-world-j5ttz-whalesay-spanish-434513495: < hola mundo >
hello-world-j5ttz-whalesay-spanish-434513495:  ------------
hello-world-j5ttz-whalesay-spanish-434513495:     \
hello-world-j5ttz-whalesay-spanish-434513495:      \
hello-world-j5ttz-whalesay-spanish-434513495:       \
hello-world-j5ttz-whalesay-spanish-434513495:                     ##        .
hello-world-j5ttz-whalesay-spanish-434513495:               ## ## ##       ==
hello-world-j5ttz-whalesay-spanish-434513495:            ## ## ## ##      ===
hello-world-j5ttz-whalesay-spanish-434513495:        /""""""""""""""""___/ ===
hello-world-j5ttz-whalesay-spanish-434513495:   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
hello-world-j5ttz-whalesay-spanish-434513495:        \______ o          __/
hello-world-j5ttz-whalesay-spanish-434513495:         \    \        __/
hello-world-j5ttz-whalesay-spanish-434513495:           \____\______/
hello-world-j5ttz-whalesay-english-1652768303:  _____________
hello-world-j5ttz-whalesay-english-1652768303: < hello world >
hello-world-j5ttz-whalesay-english-1652768303:  -------------
hello-world-j5ttz-whalesay-english-1652768303:     \
hello-world-j5ttz-whalesay-english-1652768303:      \
hello-world-j5ttz-whalesay-english-1652768303:       \
hello-world-j5ttz-whalesay-english-1652768303:                     ##        .
hello-world-j5ttz-whalesay-english-1652768303:               ## ## ##       ==
hello-world-j5ttz-whalesay-english-1652768303:            ## ## ## ##      ===
hello-world-j5ttz-whalesay-english-1652768303:        /""""""""""""""""___/ ===
hello-world-j5ttz-whalesay-english-1652768303:   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
hello-world-j5ttz-whalesay-english-1652768303:        \______ o          __/
hello-world-j5ttz-whalesay-english-1652768303:         \    \        __/
hello-world-j5ttz-whalesay-english-1652768303:           \____\______/
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
