### ISSUE TITLE
templateDefaults has inconsistent behavior and does not allow command line parameter overwrite

### ISSUE THREAD

**Issue by apiwoni** [argoproj/argo-workflows#6880]
## Summary

What happened/what you expected to happen?
I have declared `templateDefaults.inputs.parameters.value|valueFrom.configMapKeyRef` in workflow template referenced by `templates` via workflow steps and the following issues are observed:
- `templates.[name].inputs.parameters.[name]` is not enough and requires `value` or `default` etc. `value` and `default` are not required in other cases
- `templateDefaults.inputs.parameters.value` does not overwrite `templates.[name].inputs.parameters.[name].value|default`
- but `templateDefaults.inputs.parameters.valueFrom.configMapKeyRef`does overwrite `value` or `default`. This is inconsistent
- parameter passed on command line does not overwrite any of `templateDefaults.inputs.parameters.value|valueFrom.configMapKeyRef`

What version of Argo Workflows are you running?
argo: v3.2.0-rc5

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-parameters
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  message_1: "first message from config map"
  message_2: "second message from config map"
  last_message: "last message from config map"
-------------------------------------------------

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wf-template-defaults
spec:
  entrypoint: main
  templateDefaults:
    inputs:
      parameters:
        - name: message1
          valueFrom:
            configMapKeyRef:
              name: message-parameters
              key: message_1
              optional: false
        - name: message2
          # value unlike valueFrom is ignored
          value: "value from templateDefaults"
        - name: lastmessage
          valueFrom:
            configMapKeyRef:
              name: message-parameters
              key: last_message
              optional: true
  templates:
    - name: main
      steps:
        - - name: first-step
            template: first-step
        - - name: second-step
            template: second-step
        - - name: last-step
            template: last-step
    - name: first-step
      inputs:
        parameters:
          - name: message1
            # Why default is required here but not in other cases
            default: ""
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message1}}"]

    - name: second-step
      inputs:
        parameters:
          - name: message2
            default: ""
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message2}}"]

    - name: last-step
      inputs:
        parameters:
          - name: lastmessage
            default: ""
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.lastmessage}}"]
```

```bash
argo submit --from workflowtemplate/wf-template-defaults -p message1=firstMessageFromCommandLine
```
Expected Output:

"firstMessageFromCommandLine"
"value from templateDefaults"
"last message from config map"

Actual Output:

"first message from config map"
""
"last message from config map"

I'm at a loss here. I'm working on translator from Oozie to Argo workflows but I cannot see consistent pattern for paremeters propagation and order of preference!?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
