### ISSUE TITLE
support binary HTTP template bodies

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6888]
Today, v3.2, HTTP template allows you to specify a body as a string. This is useful for `{{..}}` templating, but does not support all potential uses cases. It maybe necessary to support `[]byte` too. This could probably be done like this:

```yaml
bodyFrom:
   bytes: "b2341234==
````

This would allows us to extend this, e.g. to get the body from a config map or secret:

```yaml
bodyFrom:
  configMap:
    name: my-map
    key: my-key
````

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
