### ISSUE TITLE
difference behavior of `{{= workflow.creationTimestamp }}` and `{{ workflow.creationTimestamp }}`

### ISSUE THREAD

**Issue by roy-ht** [argoproj/argo-workflows#6906]
### What happened/what you expected to happen?

`{{= workflow.creationTimesamp }}` should be rfc3339 string, but outputs a map representation like:

```
map[A:Monday B:October H:06 I:06 L:.000 M:11 S:08 Y:2021 Z:UTC a:Mon b:Oct d:11 m:10 p:AM s:1633932668 y:21 z:+0000]
```

#### some investigations

In [Template.Replace](https://github.com/argoproj/argo-workflows/blob/2a2ecc916925642fd8cb1efd026588e6828f82e1/util/template/template.go#L33), 

I guess `simpleReplace` searches flattened `replaceMap` and good, but `expressionReplace` has a "nested" replaceMap, as `env`,
so the key `workflow.creationTimestamp` becomes a map[string]interface{}.

I'd like to get a formatted string value or time.Time instance to send sprig.dateModify like: 

```
{{= sprig.dateModify("-24h", sprig.toDate('2006-01-02T15:04:05Z07:00', workflow.creationTimestamp)) }}
```

Or more simply to send to dateModify,
I would appreciate if Argo WF has `workflow.creationTimestamp.time` or `asTime(workflow.creationTimestamp)`.

### What version of Argo Workflows are you running?

v3.1.8

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello

  templates:
  - name: hello
    steps:
    - - name: h1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "1: {{ workflow.creationTimestamp }}"
    - - name: h2
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "2: {{= workflow.creationTimestamp }}"
    - - name: h3
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "3: {{= string(workflow.creationTimestamp) }}"

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

What Kubernetes provider are you using?

Amazon EKS

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
