### ISSUE TITLE
Cannot refer to some parameters from expression template

### ISSUE THREAD

**Issue by nomeaning777** [argoproj/argo-workflows#6909]
## Summary

What happened/what you expected to happen?

If `PARAMETER-NAME` is a prefix of another parameter, `{{=inputs.parameters.PARAMETER-NAME}}` will fail to resolve.
This is probably due to `Expand` function in util/expand/expand.go.

What version is it broken in?
v3.1.13

What version was it working in?
v3.1.12

## Diagnostics

```yaml
kind: Workflow
metadata:
  generateName: parameter-expand-
  annotations:
    workflows.argoproj.io/version: ">= 3.1.0"
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: a
            value: A
          - name: a2
            value: A2
      script:
        env:
          - name: A
            value: "{{=inputs.parameters.a}}"
          - name: A2
            value: "{{=inputs.parameters.a2}}"
        image: debian:9.4
        command: [bash]
        source: |
          echo "$A / $A2"
```

Workflow stdout of v3.1.13
```
{{=inputs.parameters.a}} / A2
```

Workflow stdout of v3.1.12
```
A / A2
```

What Kubernetes provider are you using? GKE v1.20

What executor are you running? Emissary

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
