### ISSUE TITLE
Migration error on new database

### ISSUE THREAD

**Issue by kmcrawford** [argoproj/argo-workflows#6915]
## Summary

When creating a new argo-workflow deployment using a empty database I get the following error in the logs:
```
time="2021-10-12T16:31:49.105Z" level=info msg="Persistence Session created successfully"
time="2021-10-12T16:31:49.109Z" level=info msg="Migrating database schema" clusterName=default dbType=postgres
time="2021-10-12T16:31:49.139Z" level=info msg="applying database change" change="alter table argo_workflows drop constraint argo_workflows_pkey" changeSchemaVersion=6
time="2021-10-12T16:31:49.154Z" level=fatal msg="Failed to update config: pq: constraint \"argo_workflows_pkey\" of relation \"argo_workflows\" does not exist"
```

Using image:
```
quay.io/argoproj/workflow-controller:v3.1.8
```

## Diagnostics

Using helm chart:
`helm install -n argo argo-workflows argo/argo-workflows --values=values.yaml`
```
controller:
  containerRuntimeExecutor: pns
  persistence:
     connectionPool:
       maxIdleConns: 100
       maxOpenConns: 0
     # save the entire workflow into etcd and DB
     nodeStatusOffLoad: false
     # enable archiving of old workflows
     archive: false
     postgresql:
       host: my-database
       port: 26257
       database: argo
       tableName: argo_workflows
       # the database secrets must be in the same namespace of the controller
       userNameSecret:
         name: argo-postgres-config
         key: username
       passwordSecret:
         name: argo-postgres-config
         key: password
  ```

What Kubernetes provider are you using?
GKE

What executor are you running? PNS

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
