### ISSUE TITLE
[Regression] Argo v3.2.0 UI ignores BASE_HREF

### ISSUE THREAD

**Issue by rijos** [argoproj/argo-workflows#6923]
Argo has the ability to set the base href using the BASE_HREF environment variable in argo-server.
This value is ignored in Argo v3.2.0

Argo v3.2.0
![image](https://user-images.githubusercontent.com/23135242/137121471-3d9e5527-a08c-4f63-b64a-bb68a0446b7d.png)

![image](https://user-images.githubusercontent.com/23135242/137120280-f84f1ccb-3c37-4fac-bc21-ac0ce46c5467.png)

Argo v3.1.13
![image](https://user-images.githubusercontent.com/23135242/137120982-6382736b-b97c-4fc6-8b4e-d1595fd7a4fb.png)

Part of the kustomization config:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - name: argo-server
        env:
          - name: BASE_HREF
            value: /argo/
```
