### ISSUE TITLE
support HTTP template with artifact in body

### ISSUE THREAD

**Issue by ptitpoulpe** [argoproj/argo-workflows#6924]
# Summary

Support artifacts HTTP template bodies

# Use Cases

Send a generated artifact to a rest api via a HTTP template.

```yaml
bodyFrom:
  artifact:
    name: …
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
