### ISSUE TITLE
Argo Workflows always adds `capabilities: drop: ALL` to container spec

### ISSUE THREAD

**Issue by droctothorpe** [argoproj/argo-workflows#6933]
## Summary
Argo Workflows always adds `capabilities: drop: ALL` to container spec.

I've tried setting capabilities to `[]`, `drop` to `[]`, `drop` to a single capability (the resulting container included the single capability _and_ `ALL`), setting `securityContext` at the workflow spec level rather than the container spec level, fiddling with the Default Workflow via the relevant configMap, and more.

None of it -- none of it -- disabled `drop: ALL`. 

We need to disable `drop: ALL` in order for our DAC_OVERRIDE psp / rolebinding to work so that the root user can write to a particular directory that's not owned by root. 

What happened/what you expected to happen?
My expectation is that this can be toggled off.

What version of Argo Workflows are you running?
v3.18

## Diagnostics
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: foo
  namespace: <foo>
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  entrypoint: run-script
  serviceAccountName: argo-workflows
  ttlStrategy:
    secondsAfterCompletion: 10000
  podMetadata:
    annotations:
      kubernetes.io/psp: jupyterhub
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
  arguments:
    parameters:
      - name: script_url
        value: <foo>
      - name: image_url
        value: <foo>
      - name: job_type
        value: Other
      - name: job_description
        value: "This is an example"
  templates:
    - name: run-script
      inputs:
        parameters:
          - name: script_url
          - name: image_url
          - name: job_type
          - name: job_description
      container:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          readOnlyRootFilesystem: false
        imagePullPolicy: Always
        image: "{{workflow.parameters.image_url}}"
        command: ["/bin/sleep"]
        args: ["10000"]
```

What Kubernetes provider are you using?
Kops provisioned v1.19.13.

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
K8SAPI

# Logs from the workflow controller:
Nothing relevant. The workflow controller doesn't report any issues. The issues happen once the container is already running -- it's unable to write a file to a directory even though it's root. 

# The workflow's pods that are problematic:
```
main /app/entrypoint-secrets.sh: line 30: /app/secrets.yaml: Permission denied
main Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
```

# Logs from in your workflow's wait container, something like:
No issues with this.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
