### ISSUE TITLE
Cannot use parameters in container resource limits

### ISSUE THREAD

**Issue by butzist** [argoproj/argo-workflows#6939]
## Summary

What happened/what you expected to happen?

When creating a Workflow that uses workflow parameters for setting resource limits of a container, the Workflow fails after submitting with message:

```
cannot unmarshall spec: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```
Btw. using the same expression in an env variable works fine (see below).

What version of Argo Workflows are you running?

3.1.8, 3.2.0

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
spec:
  arguments:
    parameters:
      - name: resources
        value: '{"limits":{"cpu":"100m"}}'
  entrypoint: main
  templates:
    - name: main
      container:
        env:
          - name: TEST
            value: '{{= jsonpath(workflow.parameters.resources, "$.limits.cpu") }}'
        image: alpine:latest
        command: ["sh", "-c", "echo TEST"]
        resources:
          limits:
            cpu: '{{= jsonpath(workflow.parameters.resources, "$.limits.cpu") }}'
```

What Kubernetes provider are you using?

K3S, AKS

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

PNS

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
