### ISSUE TITLE
From where does Argo determine the user if not specified explicitly?

### ISSUE THREAD

**Issue by wdma** [argoproj/argo-workflows#6942]
I am running a workflow with the serviceaccount dma. No matter what I do, Argo thinks that I am using the Argo user.
How do I specify that Argo should run with the user dma?

```
 User "system:serviceaccount:argo:argo"
```

Here is the "--watch" output
```
Name:                memoized-simple-workflow-jwct9
Namespace:           argo
ServiceAccount:      dma
Status:              Error
Message:             error in entry template execution: error updating last hit timestamp on cache: configmaps "my-config" is forbidden: User "system:serviceaccount:argo:argo" cannot update resource "configmaps" in API group "" in the namespace "argo"
Conditions:
 Completed           True
Created:             Fri Oct 15 12:33:40 +0000 (now)
Started:             Fri Oct 15 12:33:40 +0000 (now)
Finished:            Fri Oct 15 12:33:40 +0000 (now)
Duration:            0 seconds
Progress:            0/0
Parameters:
  message:           test-6

STEP                               TEMPLATE  PODNAME  DURATION  MESSAGE
 ⚠ memoized-simple-workflow-jwct9  whalesay                     error updating last hit timestamp on cache: configmaps "my-config" is forbidden: User "system:serviceaccount:argo:argo" cannot update resource "configmaps" in API group "" in the namespace "argo"
```

and the yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: memoized-simple-workflow-
spec:
  entrypoint: whalesay
  serviceAccountName: dma
  arguments:
    parameters:
    - name: message
      value: test-6
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    memoize:
      key: whalesay-cache
      maxAge: "10s"
      cache:
        configMap:
          name: my-config
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay {{inputs.parameters.message}} > /tmp/hello_world.txt"]
    outputs:
      parameters:
      - name: hello
        valueFrom:
          path: /tmp/hello_world.txt
```

The workflow-controller shows the same problem
```
time="2021-10-15T12:33:40.701Z" level=info msg="Processing workflow" namespace=argo workflow=memoized-simple-workflow-jwct9
time="2021-10-15T12:33:40.872Z" level=info msg="Get configmaps 200"
time="2021-10-15T12:33:40.872Z" level=info msg="resolved artifact repository" artifactRepositoryRef="argo/my-config#whalesay-cache"
time="2021-10-15T12:33:40.873Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=memoized-simple-workflow-jwct9
time="2021-10-15T12:33:40.879Z" level=info msg="Get configmaps 200"
time="2021-10-15T12:33:40.879Z" level=info msg="config map cache loaded" name=my-config namespace=argo
time="2021-10-15T12:33:40.882Z" level=info msg="Update configmaps 403"
time="2021-10-15T12:33:40.882Z" level=info msg="Skipped node memoized-simple-workflow-jwct9 initialized Error (message: error updating last hit timestamp on cache: configmaps \"my-config\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot update resource \"configmaps\" in API group \"\" in the namespace \"argo\")" namespace=argo workflow=memoized-simple-workflow-jwct9
time="2021-10-15T12:33:40.882Z" level=error msg="error in entry template execution" error="error updating last hit timestamp on cache: configmaps \"my-config\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot update resource \"configmaps\" in API group \"\" in the namespace \"argo\"" namespace=argo workflow=memoized-simple-workflow-jwct9
time="2021-10-15T12:33:40.883Z" level=warning msg="Non-transient error: error updating last hit timestamp on cache: configmaps \"my-config\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot update resource \"configmaps\" in API group \"\" in the namespace \"argo\""
time="2021-10-15T12:33:40.883Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=memoized-simple-workflow-jwct9
time="2021-10-15T12:33:40.883Z" level=info msg="Updated message  -> error in entry template execution: error updating last hit timestamp on cache: configmaps \"my-config\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot update resource \"configmaps\" in API group \"\" in the namespace \"argo\"" namespace=argo workflow=memoized-simple-workflow-jwct9
time="2021-10-15T12:33:40.883Z" level=info msg="Marking workflow completed" namespace=argo workflow=memoized-simple-workflow-jwct9
time="2021-10-15T12:33:40.883Z" level=info msg="Checking daemoned children of " namespace=argo workflow=memoized-simple-workflow-jwct9
time="2021-10-15T12:33:40.888Z" level=info msg="Create events 201"
time="2021-10-15T12:33:40.897Z" level=info msg="Create events 201"
```

Here are my serviceaccounts
```
kubectl get serviceaccounts -n argo
NAME          SECRETS   AGE
argo          1         52m
argo-server   1         52m
default       1         52m
dma           1         37m
```
I am running
Argo version 3.2.0
Kubernetes version 1.22.2
Ubuntu 20.04
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
