### ISSUE TITLE
label inheritance from cronwf

### ISSUE THREAD

**Issue by Guillermogsjc** [argoproj/argo-workflows#6952]
hi, could workflows generated frorm cronwf inherrit labels from the cronwf? 

the inheritance could be direct or namespaced (at least changing namespace (prefixing them or something like that) 

for example: 

if cronwf has label: `a : foo`, then workflows generrated by this cronwf could have
`workflows.argoproj/cron-workflow-label/a : foo ` or something similar to facilitate the filtering by labels of them.

The main use case is to recover by labels in such a way they could be several cronwf generating workflows shaaring an specific label, and you want to know if any of the workflows with that generrated label is alive, etc...

**Comment by terrytangyuan** [comment]
You can use WorkflowMetadata on your WorkflowSpec? 

Also since the CronWorkflow name is also available in the annotations of the workflows already, you can easily find the labels from the original CronWorkflow.

**Comment by Guillermogsjc** [comment]
Yes, thank you @terrytangyuan , it was more like etcd queries are optimal against `metadata.labels` fields as far as I know because they are the indexers of Kubernetes objects.

The use case: You have a controller daemon to launch tasks, but you need to monitor current alive ones and launch depending on alive workflow `metadata.labels`. You need to periodically query K8S objects to get this information, so it would be optimal to perform the queries directly against `metadata.labels` fields, right? (I do not know if I am  in a big mess with this idea)

**Comment by terrytangyuan** [comment]
Yes, there are indeed some performance benefits. So what I suggested was the following:

```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf-basic
  labels:
    argo-e2e: "true"
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Allow"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 2
  workflowMetadata:
    labels:
      argo-e2e: "true"
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: python:alpine3.6
          command: ["sh", -c]
          args: ["echo hello"]
```

The labels in `workflowMetadata` will be available in the child workflows of the CronWorkflow so you can query directly from the workflows' `metadata.labels`.
