### ISSUE TITLE
Git Output Artifacts

### ISSUE THREAD

**Issue by Asherslab** [argoproj/argo-workflows#6986]
# Summary

Currently Git Artifact only supports input, providing support for output would be great. I can see this providing credentials is already supported via secrets, theoretically the minimum extra field required would be a commit message

# Use Cases

Easy workflows that needs to update remote git repositories, such as argocd configuration repos.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by nice-pink** [comment]
I like the idea very much.

In my opinion the code would look something like:
```
    outputs:
      artifacts:
      - name: src
        path: /src/example
        git:
          repo: https://github.com/golang/example.git
          message: Add git push artifact.
          retries: 2
```

But I think it will be a great pain, as go-git still doesn't work properly with shallow clones. So if the repo is updated concurrently, a pull and push will lead to "non-fast-forward update" (pull) and "object not found" (push) errors.
