### ISSUE TITLE
UI logs for multi-step workflows with templateRef still missing in v3.2.1

### ISSUE THREAD

**Issue by kruegener** [argoproj/argo-workflows#6989]
## Summary

Version 3.2.0 introduced a bug regarding logs in the UI for multi-step workflows https://github.com/argoproj/argo-workflows/issues/6947.
This was mostly fixed with version 3.2.1 via https://github.com/argoproj/argo-workflows/pull/6925, however some edge cases still fail.

In our case, a step using `templateRef` still does not work. The pod name in the UI for this step contains `undefined`, where according to the new pod naming scheme the step name should be.
The same config used to work in 2.x.x and 3.1.8.

The workflow actually runs the step/pod completely ok, just the logs are still missing.

## Diagnostics

Setup of issue.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: component-workflow
spec:
  templates:
  - name: entry
    inputs:
      parameters:
      - name: component
    steps:
    - - name: some-other-step
           template: ....
    - - name: run-tests
           templateRef:
             name: tests-{{inputs.parameters.component}}
             template: tests
     - - name: some-other-step
           template: ....
```

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary:
Docker

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
