### ISSUE TITLE
HTTP template agent does not perform requests in parallel

### ISSUE THREAD

**Issue by iatzmon** [argoproj/argo-workflows#6994]
## Summary

I'm testing the HTTP template feature in v3.2 and I'm not sure if this is the intended behavior or not, but it looks like the HTTP agent performs requests sequentially and not in parallel.

## Diagnostics

I've created an API endpoint that receives a delay parameter and sleeps before returning a response.
I would expect all the steps in this workflow to complete at about the same time, at around the 10 second mark, but in actuality the workflow takes around 50 seconds to complete.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: workflows
  generateName: http-template-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: one
            template: http
            arguments:
              parameters: [{name: url, value: "https://us-central1-deep-knowledge-263911.cloudfunctions.net/argo-test?delay=10000"}]
          - name: two
            template: http
            arguments:
              parameters: [{name: url, value: "https://us-central1-deep-knowledge-263911.cloudfunctions.net/argo-test?delay=10000"}]
          - name: three
            template: http
            arguments:
              parameters: [{name: url, value: "https://us-central1-deep-knowledge-263911.cloudfunctions.net/argo-test?delay=10000"}]
          - name: four
            template: http
            arguments:
              parameters: [{name: url, value: "https://us-central1-deep-knowledge-263911.cloudfunctions.net/argo-test?delay=10000"}]
          - name: five
            template: http
            arguments:
              parameters: [{name: url, value: "https://us-central1-deep-knowledge-263911.cloudfunctions.net/argo-test?delay=10000"}]
    - name: http
      inputs:
        parameters:
          - name: url
      http:
       url: "{{inputs.parameters.url}}"
```

What Kubernetes provider are you using?
GKE

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
PNS

Thanks!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
