### ISSUE TITLE
Readiness Probe never successful for short-lived tasks

### ISSUE THREAD

**Issue by SunSparc** [argoproj/argo-workflows#7004]
## Summary

What happened/what you expected to happen?
> I have an Argo Workflow that is run once a month. The workflow contains many tasks, each in their own container. The tasks are often very short-lived. Last month when the Workflow was run we did not have any problems. Today we ran it and the workflow would not complete. All the task containers are running but "NotReady". Apparently a new "feature" of Argo seems to require that all tasks have a "readinessProbe" to indicate if the container is "Ready". We added a probe like this:

```
      readinessProbe:
        exec:
          command: ["ls", "/main.sh"]
        periodSeconds: 1
```

The probe always fails because by the time the probe runs, the tasks are already complete. As can be seen in the Diagnostics section below, the `State` of the containers is `Terminated` and the `Reason` is `Completed`. If the containers are "Completed", there is no need for readiness checks.

```
$ argo version
argo: v3.2.1+74182fb.dirty
  BuildDate: 2021-10-20T04:43:59Z
  GitCommit: 74182fb9017e0f05c0fa6afd32196a1988423deb
  GitTreeState: dirty
  GitTag: v3.2.1
  GoVersion: go1.17.2
  Compiler: gc
  Platform: darwin/amd64
```

## Diagnostics

`$kubectl describe pod custom-application-abcd0-workflow-tasks-12345678`:

```yaml
Containers:
  wait:
    Image:         quay.io/argoproj/argoexec:latest
    Command:
      argoexec
      wait
      --loglevel
      info
    State:          Running
    Ready:          True
    Restart Count:  0
  main:
    Image:         custom.build.com/project/workflow-tasks:1.2.3
    Command:
      /main.sh
      custom-application
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 20 Oct 2021 16:37:09 -0600
      Finished:     Wed, 20 Oct 2021 16:37:10 -0600
    Ready:          False
    Restart Count:  0
    Readiness:      exec [ls /main.sh] delay=0s timeout=1s period=1s #success=1 #failure=3
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
```

What Kubernetes provider are you using? **GKE**

What executor are you running?

```bash
$ kubectl get configmap workflow-controller-configmap -o yaml|grep containerRuntimeExecutor
[empty result]
```
`argo` shows the tasks running:

```
$ argo get custom-application-zbv4t
Name:                custom-application-zbv4t
Namespace:           custom-application
ServiceAccount:      custom-application-sa
Status:              Running
Conditions:
 PodRunning          True
Created:             Wed Oct 20 20:39:35 -0600 (4 minutes ago)
Started:             Wed Oct 20 20:39:35 -0600 (4 minutes ago)
Duration:            4 minutes 24 seconds
Progress:            0/10

STEP             TEMPLATE          PODNAME                             DURATION  MESSAGE
 ● custom-application-zbv4t      main
 ├─● task-01     workflow-tasks   custom-application-zbv4t-245695269   4m
 ├─● task-02     workflow-tasks   custom-application-zbv4t-1643989935  4m
 ├─● task-03     workflow-tasks   custom-application-zbv4t-905865205   4m
 ├─● task-04     workflow-tasks   custom-application-zbv4t-2203285334  4m
 ├─● task-05     workflow-tasks   custom-application-zbv4t-685602967   4m
 ├─● task-06     workflow-tasks   custom-application-zbv4t-1168873408  4m
 ├─● task-07     workflow-tasks   custom-application-zbv4t-1423062699  4m
 ├─● task-08     workflow-tasks   custom-application-zbv4t-1931424466  4m
 ├─● task-09     workflow-tasks   custom-application-zbv4t-3261118027  4m
 └─● task-10     workflow-tasks   custom-application-zbv4t-1872854830  4m
```

`kubectl` shows the tasks running but "NotReady":

```
$ kubectl get pods -o wide
NAME                                                         READY   STATUS     RESTARTS   AGE     IP           NODE                                                  NOMINATED NODE   READINESS GATES
argo-server-d5fd6d4b8-49ppf                                  1/1     Running    0          5h58m   10.52.9.25   workflow-pool-4443cd80-z7p2   <none>           <none>
custom-application-zbv4t-workflow-tasks-1168873408   1/2     NotReady   0          7m21s   10.52.11.2   argo-nodes-cf79a8fe-mrgb   <none>           <none>
custom-application-zbv4t-workflow-tasks-1423062699   1/2     NotReady   0          7m21s   10.52.2.2    argo-nodes-cf79a8fe-kc4l   <none>           <none>
custom-application-zbv4t-workflow-tasks-1643989935   1/2     NotReady   0          7m21s   10.52.15.2   argo-nodes-396e4c1a-9fmb   <none>           <none>
custom-application-zbv4t-workflow-tasks-1872854830   1/2     NotReady   0          7m21s   10.52.13.2   argo-nodes-8c5e681a-m96s   <none>           <none>
custom-application-zbv4t-workflow-tasks-1931424466   1/2     NotReady   0          7m21s   10.52.1.2    argo-nodes-cf79a8fe-b2nm   <none>           <none>
custom-application-zbv4t-workflow-tasks-2203285334   1/2     NotReady   0          7m21s   10.52.3.2    argo-nodes-8c5e681a-g8m5   <none>           <none>
custom-application-zbv4t-workflow-tasks-245695269    1/2     NotReady   0          7m21s   10.52.16.2   argo-nodes-396e4c1a-lpn5   <none>           <none>
custom-application-zbv4t-workflow-tasks-3261118027   1/2     NotReady   0          7m21s   10.52.12.2   argo-nodes-8c5e681a-hst8   <none>           <none>
custom-application-zbv4t-workflow-tasks-685602967    1/2     NotReady   0          7m21s   10.52.0.2    argo-nodes-cf79a8fe-wgzh   <none>           <none>
custom-application-zbv4t-workflow-tasks-905865205    1/2     NotReady   0          7m21s   10.52.14.2   argo-nodes-396e4c1a-fk5s   <none>           <none>
workflow-controller-558db44f7-czmvp                          1/1     Running    0          5h58m   10.52.9.26   workflow-pool-4443cd80-z7p2   <none>           <none>
```

It would be nice if we could opt out of Readiness checks.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
