### ISSUE TITLE
with podname v2, pod.name resolves to incorrect name when using specpatch or retry

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#7007]
when setting podname to v2, the resolved pod.name should contain template

```
metadata:
  namespace: argo
  name: steps-xl8h62
spec:
  templates:
    - name: hello-hello-hello
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: hello1
            template: whalesay
            arguments:
              parameters:
                - name: message
                  value: hello1
        - - name: hello2a
            template: whalesay2
            arguments:
              parameters:
                - name: message
                  value: hello2a
          - name: hello2b
            template: whalesay
            arguments:
              parameters:
                - name: message
                  value: hello2b
    - name: whalesay
      inputs:
        parameters:
          - name: message
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: docker/whalesay
        command:
          - cowsay
        args:
          - '{{pod.name}}'
        resources: {}
    - name: whalesay2
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker/whalesay:latest'
        command:
          - cowsay
        args:
          - '{{pod.name}}'
        resources: {}
      podSpecPatch: >-
        {"containers":[{"name":"main", "resources":{"limits":{"cpu":
        "{{workflow.parameters.cpu-limit}}" }}}]}
  entrypoint: hello-hello-hello
  arguments:
    parameters:
      - name: cpu-limit
        value: 100m
  ttlStrategy:
    secondsAfterCompletion: 600
  activeDeadlineSeconds: 300
  podSpecPatch: |
    terminationGracePeriodSeconds: 3

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
