### ISSUE TITLE
Pods created by Argo Workflows don't have the desired labels defined by the podMetadata field

### ISSUE THREAD

**Issue by alexglatt** [argoproj/argo-workflows#7013]
## Summary

I need to submit Argo Workflows to create pods that have specific labels. However, most of the time when I use the podMetadata field in the WorkflowSpec, the pods don't have the defined labels. In some rare submission attempts, the created pods do have the specified labels but when I submit the exact same Workflow once again, the created pods don't have them again.
When I submit a Workflow with multiple steps, the created pods for each step randomly have the labels. Sometimes one pod has it, sometimes two, sometimes all of them, but most of the time no created pod has the label.

I actually even want to define the pod label using the podMetadata Field in a WorkflowTemplate. However, when I specify it in the WorkflowTemplate, the created pods using a Workflow that references this WorkflowTemplate never get the labels.

For now, it would work for me if I can't specify the labels in the WorkflowTemplate. However, I need to be sure that the pods definitely receive their labels when I specify them in the Workflow.

Argo Version: v3.1.14
Kubectl Version: v1.22.2

## Diagnostics

Bug can be reproduced easily with the HelloWorld example:
(For me this example produces 3 pods where all 3 almost never receive the label. Most of the time even no pod gets the label. Especially when submitting the Workflow multiple times.)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  
  podMetadata:
    labels:
      test: label
  
  templates:
  - name: whalesay
    steps:                          
      - - name: whalesay-english
          template: whalesay-english
        - name: whalesay-spanish
          template: whalesay-spanish
      - - name: whalesay-french
          template: whalesay-french
          
  - name: whalesay-english 
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
  
  - name: whalesay-spanish
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hola mundo"]
      
  - name: whalesay-french
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["bonjour le monde"]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
