### ISSUE TITLE
Submit Workflow via `argo submit $file` Failed. 

### ISSUE THREAD

**Issue by duwanqiebi** [argoproj/argo-workflows#7030]
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: order-summary-uwt-trigger-
spec:
  workflowTemplateRef:
    name: order-summary-uwt
  arguments:
    parameters:
      - name: 'from'
        value: '2021-10-10'
      - name: 'to'
        value: '2021-10-10'
````

I want to submit this workflow via `argo sumit` command, but I got this error:
` Failed to submit workflow: templates.main-step.steps[1].order-summary-uwt-calcute templates.main.steps[0].order-summary-uwt-delete templates.run-query-script inputs.parameters.host was not supplied`. But this parameter is configured to read from configmap.

```
- name: run-query-script
  inputs:
    parameters:
      - name: script
      - name: host
        valueFrom:
          configMapKeyRef:
            name: global-param
            key: clickhouse.host
  container:
    image: 'yandex/clickhouse-client:21.9.2.17'
    command:
      - clickhouse-client
    args:
      - '--host={{inputs.parameters.host}}'
      - '--query= {{inputs.parameters.script}}'
``` 

But when I submit the same workflow via web UI, it can be submitted and executed successfully.

![image](https://user-images.githubusercontent.com/15633399/138387417-d1f6b681-ad57-496d-a546-be296c43e965.png)
