### ISSUE TITLE
Workflow is stuck at the "Running" state even after the main container is terminated.

### ISSUE THREAD

**Issue by swen128** [argoproj/argo-workflows#7047]
## Summary

> What happened/what you expected to happen?

Any workflow submitted gets forever stuck at the "Running" state even though the main container is finished.
Pressing the "Terminate" button does nothing either.

> What version is it broken in?

v3.1.0 -- v3.2.2

> What version was it working in?

v3.0.10

## Diagnostics

I deployed Argo to minikube using Kustomize and [these YAML files](https://gist.github.com/swen128/6e37f6ac17ea7b2c98c3ede1265344c7).

I thinks the problem is caused by the `latest` image tags in [the v3.2 install manifest](https://github.com/argoproj/argo-workflows/blob/v3.2.2/manifests/install.yaml#L652), and recently introduced emissary executor.

When I pressed the "Terminate" button on the UI, the wait container gave the following logs:

```
hello-world: time="2021-10-24T05:08:52.748Z" level=info msg="Step terminated"
hello-world: time="2021-10-24T05:08:52.748Z" level=info msg="Killing containers"
hello-world: time="2021-10-24T05:08:52.796Z" level=info msg="Get pods 200"
hello-world: time="2021-10-24T05:08:52.807Z" level=warning msg="Failed to kill [\"main\"]: open /var/run/argo/ctr/main/signal: no such file or directory"
```

The error seems to be related to emissary, though I didn't explicitly configure the executor. I guess it pulled latest, incompatible set of argo images where the emissary executor was default. Indeed, I was able to work around the problem by either:

- explicitly specifying the `emissary` executor.
- fixing the `argoexec` image tag to `v3.2.2` by the following patch:

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
        - name: workflow-controller
          args:
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            - quay.io/argoproj/argoexec:v3.2.2
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
