### ISSUE TITLE
Variable substitution does not work for `ConfigMapKeySelector` at global `Workflow` or `Step` level

### ISSUE THREAD

**Issue by htouloupas** [argoproj/argo-workflows#7061]
### Environment

* Latest `argo-workflows` from `master` installed from https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml
* Kubernetes version: `v1.22.2`
* Minikube version: `v1.23.2`
* Mac OS X 11.6

Given the instructions defined here https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md I expect that variables work in every field of a `Workflow` resource. I am using a `ConfigMapKeySelector` which has a key that references a global or local step variable. The expansion does not work and the following template is parsed as a string:
`{{ workflow.parameters.var }}`

## Diagnostics

Example `ConfigMap` applied on the `argo` namespace:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-template-bug
  namespace: argo
  labels:
    # Note that this label is required for the informer to detect this ConfigMap.
    workflows.argoproj.io/configmap-type: Parameter
data:
  testKey: 'testValue'
```

Applied `Workflow`s:

```yaml
metadata:
  name: delightful-python
  namespace: argo
spec:
  arguments:
    parameters:
      - name: reference
        value: testKey
      - name: message
        valueFrom:
          configMapKeyRef:
            name: workflow-template-bug
            key: '{{ workflow.parameters.reference }}'
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'

# or 

metadata:
  name: delightful-python
  namespace: argo
  labels:
    example: 'true'
spec:
  arguments:
    parameters:
      - name: reference
        value: testKey
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            valueFrom:
              configMapKeyRef:
                name: workflow-template-bug
                key: '{{ workflow.parameters.reference }}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'

```

The error messages I get when submitting this `Workflow` from the UI are:

> Failed: failed to set global parameters: failed to set global parameter message from configmap with name workflow-template-bug and key {{workflow.parameters.reference}}: ConfigMap 'workflow-template-bug' does not have the key '{{workflow.parameters.reference}}'

and for the second `Workflow`:

> unable to retrieve inputs.parameters.message from ConfigMap: ConfigMap 'workflow-template-bug' does not have the key '{{ workflow.parameters.reference }}'

Is this a problem with nested fields or doesn't the `ConfigMapKeySelector` work with dynamic variable substitution?

Linking to argoproj/argo-workflows#6869

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
