### ISSUE TITLE
http prevents next steps to appear in web ui

### ISSUE THREAD

**Issue by yoandl** [argoproj/argo-workflows#7072]
## Summary

What happened/what you expected to happen?
When you start workflow with multiple http steps (with new http template), nothings appears after the first http step.

What version of Argo Workflows are you running?
3.2.2
## Diagnostics

example workflow : 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-template-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: good
            template: http
            arguments:
              parameters: [{name: url, value: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"}]
        - - name: bad-url
            template: http
            arguments:
              parameters: [{name: url, value: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.j"}]

    - name: http
      inputs:
        parameters:
          - name: url
      http:
       # url: http://dummy.restapiexample.com/api/v1/employees
       url: "{{inputs.parameters.url}}"
```

What Kubernetes provider are you using?

AWS Eks 1.18

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
