### ISSUE TITLE
Use Configmap as temporary artifact repository  for big parameters

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#7076]
# Summary
Current Workflow has a limitation of passing big parameters between steps because of `annotation` max length. Suggest using artifacts to overcome this limitation. Users should have some cloud storage infrastructure to achieve this.

I am proposing to use k8s configmap as temporary storage for transferring big parameters or simple contents which are less than 1 MB. 

```yaml
 inputs:
      artifacts:
      - name: argo-source
        path: /src
        configMapKeyRef:
            name: workflow-template-bug
            key: '{{ workflow.parameters.reference }}'
```

```yaml
 output:
      artifacts:
      - name: argo-source
        path: /src
        configMapKeyRef:
            name: workflow-template-bug
            key: '{{ workflow.parameters.reference }}'
```

What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
