### ISSUE TITLE
multiple http steps in DAG run indefinitely

### ISSUE THREAD

**Issue by mickj74** [argoproj/argo-workflows#7079]
## Summary

What happened/what you expected to happen?
besides the UI issue mentioned in issue #7072 if there are multiple http steps in a DAG, the workflow never completes.

What version of Argo Workflows are you running?
v3.2.0

## Diagnostics

example

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-template-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: good1
            template: http
            arguments:
              parameters: [{name: url, value: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"}]
          - name: good2
            dependencies: [good1]
            template: http
            arguments:
              parameters: [{name: url, value: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"}]
          - name: good3
            dependencies: [good2]
            template: http
            arguments:
              parameters: [{name: url, value: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"}]
    - name: http
      inputs:
        parameters:
          - name: url
      http:
       # url: http://dummy.restapiexample.com/api/v1/employees
       url: "{{inputs.parameters.url}}"
```

What Kubernetes provider are you using?
AKS

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
PNS

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
