### ISSUE TITLE
Unable to view log if pod get killed due activeDeadlineSeconds

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#7081]
## Summary

What happened/what you expected to happen?

With emissary
If a pod error exit due workflow activeDeadlineSeconds, log is saved.
However, because the output artifact does not appear in workflow.status.nodeid, users are not able to view log from UI `artifact not found`

Viewing log works If a pod error exit due program error, container log is saved and output field are added in workflow.status.nodeid

What version of Argo Workflows are you running?

~v3.2.1

## Diagnostics

Workflow
```
metadata:
  name: omniscient-bear2
  namespace: default
  labels:
    example: 'true'
spec:
  activeDeadlineSeconds: 100
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - bash
          - -c
        args:
          - 'echo 123; sleep 10000'

```

Wait container log
```
time="2021-10-27T10:46:01.788Z" level=info msg="Starting Workflow Executor" executorType=emissary version=latest+bd4e68a.dirty
time="2021-10-27T10:46:01.794Z" level=info msg="Creating a emissary executor"
time="2021-10-27T10:46:01.794Z" level=info msg="Executor initialized" deadline="2021-10-27 10:47:39 +0000 UTC" includeScriptOutput=false namespace=default podName=omniscient-bear2 template="{\"n
ame\":\"argosay\",\"inputs\":{\"parameters\":[{\"name\":\"message\",\"value\":\"hello argo\"}]},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"main\",\"image\":\"argoproj/argosay:v2\",
\"command\":[\"bash\",\"-c\"],\"args\":[\"sleep 10000\"],\"resources\":{}},\"archiveLocation\":{\"archiveLogs\":true,\"gcs\":{\"bucket\":\"wx-57a8a73b-9e03-4f1d-9349-bf67bf6d9c2c\",\"serviceAcco
untKeySecret\":{\"name\":\"service-ac-key\",\"key\":\"service-ac-key.json\"},\"key\":\"pipeline/log/omniscient-bear2/omniscient-bear2\"}}}" version="&Version{Version:latest+bd4e68a.dirty,BuildDa
te:2021-10-24T23:52:23Z,GitCommit:bd4e68a5e2013987ceadc089269f7d0cf61f2cb6,GitTag:untagged,GitTreeState:dirty,GoVersion:go1.16.9,Compiler:gc,Platform:linux/amd64,}"
time="2021-10-27T10:46:01.794Z" level=info msg="Starting deadline monitor"
time="2021-10-27T10:47:39.000Z" level=info msg="Step exceeded its deadline"
time="2021-10-27T10:47:39.035Z" level=info msg="Killing containers"
time="2021-10-27T10:47:39.047Z" level=info msg="Get pods 200"
time="2021-10-27T10:47:39.827Z" level=info msg="Main container completed"
time="2021-10-27T10:47:39.827Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-10-27T10:47:39.827Z" level=info msg="Saving logs"
time="2021-10-27T10:47:39.828Z" level=info msg="GCS Save path: /tmp/argo/outputs/logs/main.log, key: pipeline/log/omniscient-bear2/omniscient-bear2/main.log"
time="2021-10-27T10:47:40.081Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2021-10-27T10:47:40.081Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2021-10-27T10:47:40.081Z" level=info msg="No output parameters"
time="2021-10-27T10:47:40.081Z" level=info msg="No output artifacts"
time="2021-10-27T10:47:40.081Z" level=info msg="Annotating pod with output"
time="2021-10-27T10:47:40.096Z" level=info msg="Patch pods 200"
time="2021-10-27T10:47:40.097Z" level=info msg="Killing sidecars []"
time="2021-10-27T10:47:40.097Z" level=info msg="Alloc=26922 TotalAlloc=33488 Sys=74321 NumGC=5 Goroutines=8"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
