### ISSUE TITLE
Allow argument parameters from expressions

### ISSUE THREAD

**Issue by Guillermogsjc** [argoproj/argo-workflows#7090]
Hi, 

struggling trying to feed  a conditional value into a  task  with `argument.parameters`

Is there any current way to feed it as:

```yaml
arguments:
  parameters:
    - name: LOADING_QUEUE_NAME
      valueFrom:
        expression: "foo in tasks['previous-dag-task'].outputs.parameters.favourite-output-tuple ? {{workflow.name}}-a : {{workflow.name}}-b"
```

If there is any current way to perform this, It is on the road map the idea of allowing too feed argment parameters taken with `valueFrom.expression` ?

The idea would be to allow things like https://github.com/argoproj/argo-workflows/blob/master/examples/dag-conditional-artifacts.yaml#L37 on  `arguments.parameters`  also
