### ISSUE TITLE
k8sapi/pns executor should be able to save log when deadlineExceeded

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#7092]
k8s/pns executor should be able to save log when deadlineExceeded

related #7081 but different executor

```yaml
metadata:
  name: omniscient-bear2
  namespace: default
  labels:
    example: 'true'
spec:
  activeDeadlineSeconds: 100
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - bash
          - -c
        args:
          - 'echo 123; sleep 10000'

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
