### ISSUE TITLE
v3.2.3 daemon steps are not restarted when you retry a failed workflow

### ISSUE THREAD

**Issue by yoandl** [argoproj/argo-workflows#7095]
## Summary

What happened/what you expected to happen?

When you retry a failed workflow with a daemon step, the workflow does not re-start the daemon step.
You should be able to retry a failed workflow and have the previous database up for debuging process if you have idempotent steps.

What version of Argo Workflows are you running?
3.2.3
## Diagnostics

This yaml contain an error to try the retry feature.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: daemon-step-
spec:
  entrypoint: daemon-example
  templates:
  - name: daemon-example
    steps:
    - - name: influx
        template: influxdb

    - - name: init-database
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: curl -XPOST 'http://{{steps.influx.ip}}:8086/query' --data-urlencode "q=CREATE DATABASE mydb"

    - - name: producer-1
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: for i in $(seq 1 20); do curl -XPOST 'http://{{steps.influx.ip}}:8086/write?db=mydb' -d "cpu,host=server01,region=uswest load=$i" ; sleep .5 ; done
      - name: producer-2
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: for i in $(seq 1 20); do curl -XPOST 'http://{{steps.influx.ip}}:8086/write?db=mydb' -d "cpu,host=server02,region=uswest load=$((RANDOM % 100))" ; sleep .5 ; done
      - name: producer-3
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: curl -XPOST 'http://{{steps.influx.ip}}:8086/write?db=mydb' -d 'cpu,host=server03,region=useast load=15.4'

    - - name: consumer
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: curls --silent -G http://{{steps.influx.ip}}:9999/query?pretty=true --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM cpu" 

  - name: influxdb
    daemon: true
    container:
      image: influxdb:1.2
      readinessProbe:
        httpGet:
          path: /ping
          port: 8086
        initialDelaySeconds: 5
        timeoutSeconds: 1
      command: ["/entrypoint.sh", "influxd"]

  - name: influxdb-client
    inputs:
      parameters:
      - name: cmd
    container:
      image: appropriate/curl:latest
      command: ["sh", "-c"]
      args: ["{{inputs.parameters.cmd}}"]
```

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
kub 1.18 eks on aws 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
