### ISSUE TITLE
WorkflowTemplate should accept arguments.parameters without providing a "value"

### ISSUE THREAD

**Issue by sappier** [argoproj/argo-workflows#7128]
## Summary

What happened/what you expected to happen?

WorkflowTemplate with ``arguments.paramters`` without a value should be created:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: parameterflow
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: alpha
  templates:
    - name: whalesay
      container:
        image: docker/whalesay
        command: ["cowsay"]
        args: ["{{workflow.parameters.alpha}}"]
```

But instead it returns an error:
```bash
$ argo template create param-flow.yaml
2021/11/02 13:59:45 Failed to create workflow template: spec.arguments.alpha.value is required
```

Earlier it was possible to create a WorkflowTemplate with a parameter without providing a default value.
Only Workflows submitted from such template, would fail when the parameter wouldn't be provided and require to pass a parameter explicitly.

Even more, I still can successfully create the WorkflowTemplate directly with ``kubectl`` and then submit a Workflow from it, works as expected:

```bash
$ kubectl apply -f param-flow.yaml
workflowtemplate.argoproj.io/parameterflow created
```

```bash
$ argo submit --from wftmpl/parameterflow -p alpha=100
Name:                parameterflow-xbvkx
Namespace:           default
ServiceAccount:      default
Status:              Pending
Created:             Tue Nov 02 14:47:32 +0100 (now)
Progress:            
Parameters:          
  alpha:             100
```

What version is it broken in?
I'm observing it on 3.0.3, 3.2.0 and the latest 3.2.3

What version was it working in?
1 year ago this functionality definitely worked.
May be 2.x?

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```
See an example yaml above
```

What Kubernetes provider are you using?

Minikube on Linux and "Docker Desktop" on MacOS

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
