### ISSUE TITLE
Git Artifact does not support relative submodules (fixed in go-git v5.3.0)

### ISSUE THREAD

**Issue by valorl** [argoproj/argo-workflows#7141]
## Summary

Using GitArtifact to clone a Git repository with a submodule specified as a relative path, argoexec init fails with `executor error: repository not found`.

The error comes from go-git (my guess would be [during the initial clone](https://github.com/argoproj/argo-workflows/blob/master/workflow/artifacts/git/git.go#L127)). See 

As mentioned there, it has been fixed in [v5.3.0](https://github.com/go-git/go-git/releases/tag/v5.3.0.).

## Diagnostics

You can use the following workflow to reproduce. It tries to clone [this example repo](https://github.com/valorl/repository-with-relative-submodule) to which I added a submodule with a relative path (`../argo-workflows`).
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: clone-relative-submodule
spec:
  entrypoint: clone
  templates:
  - name: clone
    inputs:
      artifacts:
      - name: repo
        path: /repo
        git:
          repo: https://github.com/valorl/repository-with-relative-submodule.git
          revision: main
    script:
      image: alpine/git:latest
      command: [sh]
      workingDir: /repo
      source: |
        git status
```
For me on 3.0.7, this results in the following error in init log:
```
time="2021-11-03T13:40:45.372Z" level=info msg="Starting Workflow Executor" version="{v3.0.7 2021-05-25T19:03:05Z e79e7ccda747fa4487bf889142c744457c26e9f7 v3.0.7 clean go1.15.7 gc linux/amd64}"
time="2021-11-03T13:40:45.375Z" level=info msg="Creating a docker executor"
time="2021-11-03T13:40:45.375Z" level=info msg="Executor (version: v3.0.7, build_date: 2021-05-25T19:03:05Z) initialized (pod: ci-main/clone-relative-submodule) with template:\n{\"name\":\"clone\",\"inputs\":{\"artifacts\":[{\"name\":\"repo\",\"path\":\"/repo\",\"git\":{\"rep
o\":\"github.com/valorl/repository-with-relative-submodule\",\"revision\":\"main\"}}]},\"outputs\":{},\"metadata\":{},\"script\":{\"name\":\"\",\"image\":\"alpine/git:latest\",\"command\":[\"sh\"],\"workingDir\":\"/repo\",\"resources\":{},\"source\":\"git status\\n\"},\"archi
veLocation\":{\"archiveLogs\":true,\"s3\":{\"endpoint\":\"s3.amazonaws.com\",\"bucket\":\"*****\",\"region\":\"*****\",\"insecure\":false,\"useSDKCreds\":true,\"key\":\"*****\"}}}"
time="2021-11-03T13:40:45.375Z" level=info msg="Loading script source to /argo/staging/script"
time="2021-11-03T13:40:45.375Z" level=info msg="Start loading input artifacts..."
time="2021-11-03T13:40:45.375Z" level=info msg="Downloading artifact: repo"
time="2021-11-03T13:40:45.377Z" level=error msg="executor error: repository not found"
time="2021-11-03T13:40:45.377Z" level=info msg="Alloc=4721 TotalAlloc=8931 Sys=73297 NumGC=3 Goroutines=3"
time="2021-11-03T13:40:45.377Z" level=fatal msg="repository not found"
```

What Kubernetes provider are you using?
EKS

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
