### ISSUE TITLE
Support more path syntax for `successCondition` and `failureCondition` on `resource` templates

### ISSUE THREAD

**Issue by jazka** [argoproj/argo-workflows#7143]
## Summary

Support more syntax for successCondition and failureCondition like [gjson](https://github.com/tidwall/gjson).  The guide doc tells us the two fields use kubernetes label selection syntax and can be applied against any field of the resource (not just labels). But how to check the value of the field in set? 

## Use Cases

For PytorchJob, the status section will be used to check the job status. That means the successCondition should be set like `successCondition=status.conditions.#(type="Created").status="True"`, but this syntax is not supported. Any way to deal with the case with array struct?

```yaml
 status:
    completionTime: 2019-01-11T01:03:15Z
    conditions:
    - lastTransitionTime: 2019-01-11T00:51:48Z
      lastUpdateTime: 2019-01-11T00:51:48Z
      message: PyTorchJob pytorch-dist-mnist-gloo is created.
      reason: PyTorchJobCreated
      status: "True"
      type: Created
    - lastTransitionTime: 2019-01-11T00:57:22Z
      lastUpdateTime: 2019-01-11T00:57:22Z
      message: PyTorchJob pytorch-dist-mnist-gloo is running.
      reason: PyTorchJobRunning
      status: "False"
      type: Running
    - lastTransitionTime: 2019-01-11T01:03:15Z
      lastUpdateTime: 2019-01-11T01:03:15Z
      message: PyTorchJob pytorch-dist-mnist-gloo is successfully completed.
      reason: PyTorchJobSucceeded
      status: "True"
      type: Succeeded
    replicaStatuses:
      Master:
        succeeded: 1
      Worker:
        succeeded: 1
    startTime: 2019-01-11T00:57:22Z
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
