### ISSUE TITLE
custom root CA for argo-server SSO

### ISSUE THREAD

**Issue by thesuperzapper** [argoproj/argo-workflows#7198]
# Summary

Continuing on from https://github.com/argoproj/argo-workflows/pull/6978, we should also add a config to provide a custom root CA, (rather than encouraging users to blindly trust all certs).

Here is an example config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  sso: |
    ...
    ## `rootCaFile` is just an example name
    rootCaFile: "/etc/oauth2-proxy/certs/ca.crt"
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
