### ISSUE TITLE
cannot resolve HTTP template's outputs.parameters.result

### ISSUE THREAD

**Issue by book987** [argoproj/argo-workflows#7199]
> base on v3.2.3
1. looks like we cannot get HTTP template's result, validation will failed
2. ~other nodes cannot connect to HTTP node in DAG, because they got empty HTTP node's outbound nodes~ ( already fix in #7082 )
3. result should put in outputs.result instead of outputs.parameters.result I think ( this isn't a bug

tested with this workflow, submit failed with `Internal Server Error: templates.main.tasks.echo failed to resolve {{tasks.good.outputs.parameters.result}}`, that's problem 1
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-template-
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: http
      inputs:
        parameters:
          - name: url
      http:
        # url: http://dummy.restapiexample.com/api/v1/employees
        url: "{{inputs.parameters.url}}"
    - name: echo
      inputs:
        parameters:
        - name: msg
      container:
        image: alpine:latest
        command:
        - echo
        args:
        - "{{inputs.parameters.msg}}"
    - name: main
      dag:
        tasks:
        - name: good
          template: http
          arguments:
            parameters: [{name: url, value: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"}]
        - name: echo
          template: echo
          dependencies: [ good ]
          arguments:
            parameters:
            - name: msg
              value: "{{tasks.good.outputs.parameters.result}}"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
