### ISSUE TITLE
Argo SSO RBAC Namespace delegation is not working

### ISSUE THREAD

**Issue by surajnarwade** [argoproj/argo-workflows#7202]
## Summary

* details

```
Argo workflow version: v3.2.3
Kubernetes version: v1.18.20 (on EKS)
AD provider: Azure AD
```
* argo server manifest:

```
      containers:
      - args:
        - server
        - --auth-mode=sso
        - --secure=false
        image: quay.io/argoproj/argocli:v3.2.3
        name: argo-server
        env:
        - name: SSO_DELEGATE_RBAC_TO_NAMESPACE
          value: "true"
```

* configmap snippet:

```
  sso: |
    issuer: https://login.microsoftonline.com/random-hash/v2.0
    sessionExpiry: 10h
    clientId:
      name: argo-sso
      key: client-id
    clientSecret:
      name: argo-sso
      key: client-secret
    redirectUrl: https://argo-workflows.mydomain.com/oauth2/callback
    scopes:
      - groups
      - email
    rbac:
      enabled: true
```

When I try to log into argo server, I see the following error in the browser:

```
failed to exchange token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'code'.\r\nTrace ID: xxx-xxxx-xxxx\r\nCorrelation ID: xxx-xxxx-xxx\r\nTimestamp: 2021-11-11 07:43:49Z","error_codes":[900144],"timestamp":"2021-11-11 07:43:49Z","trace_id":"xxx-xxxx-xxx","correlation_id":"xxxxx-xxxx-xxx","error_uri":"https://login.microsoftonline.com/error?code=900144"}
```

& I see the following error in Argo-server logs:

```
time="2021-11-10T18:23:59.109Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-11-10T18:23:59Z" grpc.time_ms=0.041 span.kind=server system=grpc
```

If I don't use `groups` in scopes, it all works fine and it fall back to readonly serviceaccount but not use serviceaccount from any other namespace.
but AFAIK, I need to have groups for SSO RBAC.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by whynowy** [comment]
This is a new feature only works for `v3.3 and after`.

https://github.com/argoproj/argo-workflows/blob/390e220c0871a54eba9d10a9322997e40dab68e9/docs/argo-server-sso.md#sso-rbac-namespace-delegation

You can try it with latest build.

**Comment by surajnarwade** [comment]
@whynowy @alexec I've tried `latest` tag in my image (assuming latest tag points to latest build), it's the same error

**Comment by alexec** [comment]
Given we do not have any reports from other users, I think this is most likely an issue with your OIDC provider. Can you please reach out to them for help?

**Comment by surajnarwade** [comment]
@alexec got it working, though the document is bit misleading `scopes: groups` was not needed with my azure OIDC setup as groups claim present in the token.

and also `groups` scope is not standard OIDC scope, hence we can add few lines which are bit generic & provider specific that would be nice or one note about what provider argo-workflows devs are using for development & testing.

Thanks for the awesome project :)

**Comment by alexec** [comment]
> hence we can add few lines which are bit generic & provider specific that would be nice or one note about what provider argo-workflows devs are using for development & testing.

Would you like to submit a PR to add that?

**Comment by IvanKolbasiuk** [comment]
> @alexec got it working, though the document is bit misleading `scopes: groups` was not needed with my azure OIDC setup as groups claim present in the token.
> 
> and also `groups` scope is not standard OIDC scope, hence we can add few lines which are bit generic & provider specific that would be nice or one note about what provider argo-workflows devs are using for development & testing.
> 
> Thanks for the awesome project :)

Hi @surajnarwade, Could you give a hint? How to correctly setup integration with Azure AD and app roles. faced with the same issue scope groups doesn't exist

**Comment by surajnarwade** [comment]
@IvanKolbasiuk here's the configmap snippet:

```
  sso: |
    issuer: https://login.microsoftonline.com/random-hash/v2.0
    sessionExpiry: 10h
    clientId:
      name: argo-sso
      key: client-id
    clientSecret:
      name: argo-sso
      key: client-secret
    redirectUrl: https://argo-workflows.mydomain.com/oauth2/callback
    scopes:
      - email
      - profile
    rbac:
      enabled: true
```


default serviceaccount in namespace

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    workflows.argoproj.io/rbac-rule: '''<group id>'' in groups'
    workflows.argoproj.io/rbac-rule-precedence: "1"
  name: mynamespace-argo-workflows-user-default-login
  namespace: mynamespace
```
