### ISSUE TITLE
Failed to load git artifacts in istio-enabled namespace (only in init container phase)

### ISSUE THREAD

**Issue by zsolt-keseru-epam** [argoproj/argo-workflows#7209]
## Summary

What happened/what you expected to happen?
- Successful GitHub connection was expected to load the
- When executing a workflow with git input artifact the artifact loading happens in the init container phase, when istio proxy is not yet running and not even intended to do.
- (It's independent from the usual race condition issue which happens in the main container phase, that's already solved by `holdApplicationUntilProxyStarts` istio configuration)

What version of Argo Workflows are you running?
- v3.2.2

## Diagnostics
- Istio injection is enabled in the namespace where the workflow runs
- GitHub connections work fine in other istio-injected pods
- GitHub connections work fine in a container/script wrokflow step (in main container)

Example workflow-template part:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pipeline-kaniko
spec:
  entrypoint: main
  podMetadata:
    annotations:
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
  serviceAccountName: workflow
  templates:
  - name: main
    inputs:
      parameters:
        - name: repo
        - name: revision
        - name: container_image_name
    dag:
      tasks:
      - name: build
        templateRef:
          name: common-container-image
          template: build-kaniko-artifact
        arguments:
          artifacts:
            - name: build_context
              path: /workspace
              git:
                repo: "{{inputs.parameters.repo}}"
                revision: "{{inputs.parameters.revision}}"
          parameters:
          - name: target_image_name
            value: "{{inputs.parameters.container_image_name}}"
          - name: target_image_tag
            value: "{{inputs.parameters.revision}}"
```
What Kubernetes provider are you using?
- AKS

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
- PNS

```bash
# Workflow Init container logs

time="2021-11-11T22:49:11.530Z" level=info msg="Starting Workflow Executor" executorType=pns version=v3.2.2
time="2021-11-11T22:49:11.536Z" level=info msg="Creating a pns executor"
time="2021-11-11T22:49:11.536Z" level=info msg="Initialized PNS executor (namespace: argo-managed, pod: pipeline-kaniko-5ttgv-4212080228, pid: 6)"
time="2021-11-11T22:49:11.536Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo-managed podName=pipeline-kaniko-5ttgv-4212080228 template="{\"name\":\"build-kaniko-artifact\",\"inputs\":{\"parameters\":[{\"name\":\"target_image_name\",\"value\":\"hello\"},{\"name\":\"target_image_tag\",\"value\":\"master\"}],\"artifacts\":[{\"name\":\"build_context\",\"path\":\"/workspace\",\"git\":{\"repo\":\"https://github.com/zsolt-keseru-epam/argo-combined-app\",\"revision\":\"master\"}}]},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"gcr.io/kaniko-project/executor:debug\",\"args\":[\"--context=dir:///workspace\",\"--destination=hello:master\"],\"resources\":{}}}" version="&Version{Version:v3.2.2,BuildDate:2021-10-21T17:18:52Z,GitCommit:8897fff15776f31fbd7f65bbee4f93b2101110f7,GitTag:v3.2.2,GitTreeState:clean,GoVersion:go1.16.9,Compiler:gc,Platform:linux/amd64,}"
time="2021-11-11T22:49:11.536Z" level=info msg="Start loading input artifacts..."
time="2021-11-11T22:49:11.536Z" level=info msg="Downloading artifact: build_context"
time="2021-11-11T22:49:41.539Z" level=error msg="executor error: artifact build_context failed to load: Get \"https://github.com/zsolt-keseru-epam/argo-combined-app/info/refs?service=git-upload-pack\": dial tcp 140.82.113.4:443: i/o timeout"
time="2021-11-11T22:49:41.539Z" level=info msg="Alloc=4840 TotalAlloc=9731 Sys=73297 NumGC=3 Goroutines=3"
time="2021-11-11T22:49:41.539Z" level=fatal msg="artifact build_context failed to load: Get \"https://github.com/zsolt-keseru-epam/argo-combined-app/info/refs?service=git-upload-pack\": dial tcp 140.82.113.4:443: i/o timeout"
stream closed
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by whynowy** [comment]
@zsolt-keseru-epam - can you try by disabling istio?

https://github.com/argoproj/argo-workflows/blob/master/docs/sidecar-injection.md

**Comment by zsolt-keseru-epam** [comment]
> @zsolt-keseru-epam - can you try by disabling istio?
> 
> https://github.com/argoproj/argo-workflows/blob/master/docs/sidecar-injection.md

@whynowy - Unfortunately it's a must-have requirement in my case to have istio, it's a company security constraint.

Otherwise it has been tested with istio turned off, and in that case loading the git artifact works fine.

I have went through the istio-related workflow documentations earlier, including the sidecar-injection.md and I was able to solve all other problems istio caused, except this one.

Is it possible to somehow do the artifact loading in the main container or in a sidecar, instead of the init container?

**Comment by alexec** [comment]
It could be. I'm not familiar with how ISTIO and init containers work. It could be that the `init` container starts before ISTIO. Can you look at the pod status?

**Comment by zsolt-keseru-epam** [comment]
> It could be. I'm not familiar with how ISTIO and init containers work. It could be that the `init` container starts before ISTIO. Can you look at the pod status?

As to my knowledge istio injects an init container which reconfigures the network stack to redirect all network traffic to the proxy, but the proxy sidecar container only starts when all the init containers have completed.

Here is the pod status of a failed run:
```.yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-11-15T10:42:57Z"
    message: 'containers with incomplete status: [init istio-init]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-11-15T10:42:57Z"
    message: 'containers with unready status: [istio-proxy wait main]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-11-15T10:42:57Z"
    message: 'containers with unready status: [istio-proxy wait main]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-11-15T10:42:56Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: ***.azurecr.io/istio/proxyv2:1.8.6
    imageID: ""
    lastState: {}
    name: istio-proxy
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
  - image: gcr.io/kaniko-project/executor:debug
    imageID: ""
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
  - image: ***.azurecr.io/argoproj/argoexec:v3.2.2
    imageID: ""
    lastState: {}
    name: wait
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
  hostIP: 10.99.1.82
  initContainerStatuses:
  - containerID: containerd://e4c31a8092ad35556702b7de19348290f65cc19af9cbbf5107bf59002c9c7dcb
    image: ***.azurecr.io/argoproj/argoexec:v3.2.2
    imageID: ***.azurecr.io/argoproj/argoexec@sha256:bd8ce56bb9dbe7dc641f8d3a605c0e3c508b9efea732aee612549d143dd07c3a
    lastState: {}
    name: init
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: containerd://e4c31a8092ad35556702b7de19348290f65cc19af9cbbf5107bf59002c9c7dcb
        exitCode: 1
        finishedAt: "2021-11-15T10:43:29Z"
        message: 'artifact build_context failed to load: Get "https://github.com/zsolt-keseru-epam/argo-combined-app/info/refs?service=git-upload-pack":
          dial tcp 140.82.112.3:443: i/o timeout'
        reason: Error
        startedAt: "2021-11-15T10:42:59Z"
  - image: ***.azurecr.io/istio/proxyv2:1.8.6
    imageID: ""
    lastState: {}
    name: istio-init
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: PodInitializing
  phase: Failed
  podIP: 10.99.1.136
  podIPs:
  - ip: 10.99.1.136
  qosClass: Burstable
  startTime: "2021-11-15T10:42:57Z"
```

**Comment by alexec** [comment]
I also wonder why other users don't have this problem? Have you tried reming Argo from the loop? I.e. just running a pod with an init container that checks out the files using `git clone`?

**Comment by zsolt-keseru-epam** [comment]
It's reproducible without argo as well:
```
$ k logs -n argo-managed clone-vbj62 init-clone
Cloning into '/tmp/clone'...
fatal: unable to access 'https://github.com/argoproj/argo-workflows/': Failed to connect to github.com port 443: Connection timed out
```
While the same succeeds as normal container in the pod.

In the meantime I've seen that the init containers are executed sequentially while I believed they are running in parallel...
The order is:
First my init container (or workflow init-container), then when it's finished `istio-init` which does the iptables changes.

This would mean from istio side: If there is no egress limitation on the cluster and containers are allowed to connect directly to external addresses, then all init-container before `istio-init` has connectivity just like without istio (this would be no longer true with istio-cni setup, I think it's not).
So probably that's why it could work for others (who's not using istio-cni yet).
Unfortunately we have egress limitation, so the only way to connect to external addresses is through istio...


Pod description I used for reproducing:
```
apiVersion: v1
kind: Pod
metadata:
  generateName: clone-
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
spec:
  initContainers:
  - args:
    - sh
    - -c
    - "git clone https://github.com/argoproj/argo-workflows /tmp/clone && find /tmp/clone"
    image: acraksdanasdeveastus2wi7f.azurecr.io/bitnami/git:2.33.0
    name: init-clone
  containers:
  - args:
    - sh
    - -c
    - "git clone https://github.com/argoproj/argo-workflows /tmp/clone && find /tmp/clone"
    image: acraksdanasdeveastus2wi7f.azurecr.io/bitnami/git:2.33.0
    name: clone
  restartPolicy: Never
```
