### ISSUE TITLE
Prevent users from overriding automatically set labels

### ISSUE THREAD

**Issue by ThSchrad** [argoproj/argo-workflows#7215]
# Summary

First, thank you very much for creating and maintaining such a useful tool.

When a workflow is submitted, argo workflows adds various labels to the workflow resource, for example `workflows.argoproj.io/creator-email`.
Users are able to set labels via the cli when submitting a workflow. This is to be expected.
What I did not expect is that users are able to also change the labels set by argo workflows.

Example, but any workflow will work.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
```

Submit the workflow.
```
argo submit hello-world.yml
```

The resulting label contains the users' email address (expected).
```
workflows.argoproj.io/creator-email=foo@example.com
```

Submit again and set the label.
```
argo submit hello-world.yml -l "workflows.argoproj.io/creator-email=somethingelse"
```

The label was overridden. Here I would expect the value of the label to be `foo@example.com`.
```
workflows.argoproj.io/creator-email=somethingelse
```

Is it possible to prevent the user from overriding the labels set by the workflow controller?

# Use Cases

A use case would be to validate the input parameters of a workflow based on who submitted it (username, email, maybe groups).
An example would be an image promotion workflow. The user passes the image to be promoted and the first step checks if the user has permissions to promote this particular image.
This is not possible as long as users are able to freely change the labels set by the workflow controller.

If the described behaviour is desired, how is one able to implement this use case as it seems there is no workflow parameter which contains the submitting user?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
