### ISSUE TITLE
I can't get outputs, when the step is failed.

### ISSUE THREAD

**Issue by wanshicheng** [argoproj/argo-workflows#7217]
## Summary

What happened/what you expected to happen?
I start a sparkapplication(spark-on-k8s-operator) , and set up successCondition, failureCondition, outputs. I can't get outputs, when the step is failed trigger by the failureCondition. I want to get some outputs, so that I can use these outputs to do next step.
What version of Argo Workflows are you running?
v3.2.3
## Diagnostics
Sorry, I can't copy any data from our VDI.  The yaml is like this:
```yaml
metadata:
...
spec:
  templates:
    - name: start
      steps:
       - - name: a
       ...
    - name:  a
      outputs:
         parameters:
         - naem: appName
            valueFrom:
               jsonPath: '{{.metadata.name}}'
      resource:
        action: create
        manifest: |
           ...
     successCondition: status.applicationsState.state = COMPLETED
     failureCondition: status.applicationsState.state = FAILED
    - name:  b
    - name: c
```

What Kubernetes provider are you using?
1.21.5
What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Kubelet
