### ISSUE TITLE
Windows step fails to init due to failure to load artifact

### ISSUE THREAD

**Issue by tachyus-ryan** [argoproj/argo-workflows#7227]
## Summary

What happened/what you expected to happen?

I expected Argo to successfully mount the output artifact from step1 as the input artifact for step2.

Instead, the init container failed to load the path from GCS. See init_logs.txt, attached.

What version of Argo Workflows are you running? v3.2.3

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
# Combining hybrid and artifact examples from https://argoproj.github.io/argo-workflows/windows/
# Artifact repository set up using Google Cloud Storage
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-hybrid-
spec:
  entrypoint: mytemplate
  templates:
    - name: mytemplate
      steps:
        - - name: step1
            template: hello-linux
        - - name: step2
            template: print-message
            arguments:
              artifacts:
                - name: message
                  from: "{{steps.step1.outputs.artifacts.output}}"

    - name: hello-linux
      outputs:
        artifacts:
          - name: output
            path: /out
            s3:
              key: "demo/test/out"
            archive:
              none: {}
      nodeSelector:
        kubernetes.io/os: linux
      script:
        image: alpine
        command: [/bin/sh]
        source: >
          echo "Hello from Linux Container!" > /out/message
        volumeMounts:
          - name: output
            mountPath: "/out"
      volumes:
        - name: output
          emptyDir: {}
    - name: print-message
      inputs:
        artifacts:
          # unpack the message input artifact
          # and put it at C:\message
          - name: message
            path: "/message" # gets mapped to C:\message
      nodeSelector:
        kubernetes.io/os: windows
      container:
        image: mcr.microsoft.com/windows/nanoserver:1809
        command: ["cmd", "/c"]
        args: ["dir C:\\message"] # List the C:\message directory
```

What Kubernetes provider are you using? GKE

What executor are you running? K8SAPI

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
# workflow-controller.txt

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
# workflow.yaml.txt

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
# wait_logs.txt

# Logs from in your workflow's init container:
argo logs ${workflow} -c init
# init_logs.txt
```
[workflow-controller.txt](https://github.com/argoproj/argo-workflows/files/7550156/workflow-controller.txt)
[workflow.yaml.txt](https://github.com/argoproj/argo-workflows/files/7550167/workflow.yaml.txt)
[init_logs.txt](https://github.com/argoproj/argo-workflows/files/7550159/init_logs.txt)
[wait_logs.txt](https://github.com/argoproj/argo-workflows/files/7550157/wait_logs.txt)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
