### ISSUE TITLE
Add support for more granular and flexible synchronization mechanism of the workflows

### ISSUE THREAD

**Issue by denis-codefresh** [argoproj/argo-workflows#7272]
# Summary

Add support for more granular and flexible synchronization mechanism of the workflow

# Use Cases

Today you can enforce your workflow concurrency only by 2 levels: workflow or template.
The proposal is to add an ability to create custom levels of synchronization based on workflow fields like labels or parameter values. It would be great to have an ability to enforce concurrently by some workflow specific fields like labels or params.

The interface can be the following: 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: synchronization-wf-level-
spec:
  entrypoint: whalesay
  synchronization:
    semaphore:
      configMapKeyRef:
        name: my-config
        key: workflow
        parameters:
          - name: repo
            value: '{{ workflow.parameters.GIT_REPO }}'
          - name: sensor
            value: '{{ workflow.lables.events.argoproj.io/sensor }}'
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

It should also fit well into the current implementation of semaphore synchronization.
I have checked and it looks like currently semaphore lock names are created in this way:
```go
fmt.Sprintf("%s/%s/%s/%s", ln.Namespace, ln.Kind, ln.ResourceName, ln.Key)
```
We can add an additional variable here that will hold the value of provided parameters concatenated together:
```go
// ln.Parameters = "repo=argoproj/argo-workflows&sensor=sensor-name"
fmt.Sprintf("%s/%s/%s/%s/%s", ln.Namespace, ln.Kind, ln.ResourceName, ln.Key, ln.Parameters)
```

I would like to submit a PR if you think it's good to have these synchronization capabilities.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
