### ISSUE TITLE
Default values for inputs parameters in WorkflowTemplate not working

### ISSUE THREAD

**Issue by yoshina9a** [argoproj/argo-workflows#7275]
## Summary

What happened/what you expected to happen?

Previously (at least in v3.1.13), we can use default values for input parameters in a template in WorkflowTemplate. But now it's broken in v3.2.4.
Maybe It's like this issue #2305 

What version of Argo Workflows are you running?
**v3.2.4**

## Diagnostics

workflow-template 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: job-sample
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: date
  templates:
    - name: main
      inputs:
        parameters:
          - name: date
            value: "{{inputs.parameters.date}}"
            default: yesterday
      container:
        image: docker/whalesay:latest
        command:
          - cowsay
        args:
          - "{{inputs.parameters.date}}"
```

workflow 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: yesterday-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: day
            templateRef:
              name: job-sample
              template: main
```

What Kubernetes provider are you using? **GKE**

What executor are you running? **Docker**

Main container logs in v3.1.13 
```bash
 ___________
< yesterday >
 -----------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

Main container logs in v3.2.4
```bash
 ____________________________
< {{inputs.parameters.date}} >
 ----------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@yoshina9a it is a wrong way to refer the `parameter`
```
      inputs:
        parameters:
          - name: date
            value: "{{inputs.parameters.date}}" <--- it is refering itself. so controller is not able to resolve it
            default: yesterday
```

**Comment by jackivanov** [comment]
@sarabala1979 then what should it be referring to?

**Comment by mattskone** [comment]
OP's steps to reproduce show that the behavior worked as expected in v3.1.13 but _does not work_ in v3.2.4.  I have encountered this identical problem moving from v2.9.3 to v3.2.4, so this seems to be either a bug or deliberate behavior change in v3.2.4.

**Comment by terrytangyuan** [comment]
@mattskone Could you try v3.2.7?

**Comment by mattskone** [comment]
I can confirm through testing on a GKE v1.21 cluster that OP's steps to reproduce result in the expected behavior on Argo v.3.2.3 but not on v3.2.4 (or v3.2.7), so this change in behavior seems to have been introduced in v3.2.4.

My testing process has simply been:

```
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/[version]/install.yaml
(wait for healthy pods)
argo template create -n argo [OP's workflow template YAML]
argo submit -n argo --from workflowtemplate/job-sample [OP's workflow YAML]
(wait for workflow to finish)
argo logs -n argo @latest
kubectl delete -n argo -f https://github.com/argoproj/argo-workflows/releases/download/[version]/install.yaml
```

**Comment by terrytangyuan** [comment]
@sarabala1979 Noticed that you marked this as "invalid". Now looks like this is regression?

**Comment by alexec** [comment]
Probably introduced by fix: Parameter with Value and Default #6887

**Comment by alexec** [comment]
Maybe workaround:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: job-sample
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: date
  templates:
    - name: main
      inputs:
        parameters:
          - name: date
            value: '{{=inputs.parameters.date != nil ? inputs.parameters.date : "yesterday"}}'
      container:
        image: docker/whalesay:latest
        command:
          - cowsay
        args:
          - "{{inputs.parameters.date}}"
```
