### ISSUE TITLE
POD_NAMES v2 as Default

### ISSUE THREAD

**Issue by guillaumBrisard** [argoproj/argo-workflows#7279]
# Summary

Set POD_NAMES v2 as default.
Now it seems fixed
[7221](https://github.com/argoproj/argo-workflows/issues/7221)
[7007](https://github.com/argoproj/argo-workflows/issues/7007)

Firsts proposals
[1319](https://github.com/argoproj/argo-workflows/issues/1319)
[6712](https://github.com/argoproj/argo-workflows/pull/6712)

# Use Cases

It's just better, specially for tracing, debugging

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
To fix this, change the default here:

https://github.com/argoproj/argo-workflows/blob/1159afc3c082c62f6142fad35ba461250717a8bb/workflow/util/pod_name.go#L37

**Comment by juliev0** [comment]
> 

Thanks for thinking of the possibility of pods having V1 names during the upgrade. I think this will in fact create additional challenges if the code is looking for pods with the V2 name but they don't have that name. I've noticed some of the code is looking for the Workflow annotation _workflows.argoproj.io/pod-name-format_ which indicates V1 or V2, which can override the environment variable setting. I'm thinking I need to make it so that for _all_ code which is looking for a pod, we are using that annotation to determine the right pod name to look for.

**Comment by juliev0** [comment]
Hi @JPZ13 I'm wondering if you can help me understand the code. Why do we use the environment variable rather than the Workflow annotation in [wfOperationCtx.getPodName](https://github.com/argoproj/argo-workflows/blame/master/workflow/controller/operator.go#L3638)()?

I am thinking that if we're looking for existing pods we should use the annotation on the Workflow as opposed to the environment variable (thinking about the case where there are pods running and we upgrade the Workflow Controller to change the default value of the environment variable, we want to still be able to look for pods with the v1 name even if the environment variable has been changed to v2)

I am new to Workflows, so forgive me if I'm ignorant. :)

**Comment by JPZ13** [comment]
Hi @juliev0 - sorry for the tardy response. At Kubecon right now with quite a busy schedule

The environment variable is used to determine what annotation we should set for newly generated workflows. For workflows that have already been created, we refer to the annotation to determine how exactly to handle the pod names. This allows for reverse compatibility when upgrading from v1 pod names to v2

The function that we use for determining how to handle existing workflows is here: https://github.com/argoproj/argo-workflows/blob/master/workflow/util/pod_name.go#L77

Does that help clarify things? Also happy to provide more detail on specific things if needed. Let me know

**Comment by JPZ13** [comment]
@juliev0 Any time! I think the comment at [wfOperationCtx.getPodName](https://github.com/argoproj/argo-workflows/blame/master/workflow/controller/operator.go#L3638) is actually wrong. We don't get the version from the environment variable in that function. We actually get it from the workflow itself. `wfOperationCtx.getPodName` invokes [wfutil.GetPodNameVersion()](https://github.com/argoproj/argo-workflows/blob/master/workflow/util/pod_name.go#L77), which gets the version from a workflow's annotation. Sorry for the confusion, and feel free to update that comment in your PR 💪

**Comment by juliev0** [comment]
@JPZ13 getPodName() is actually calling wfutil.GetPodNameVersion(), not wfutil.GetWorkflowPodNameVersion(), the former of which uses the environment variable and the latter of which uses the annotation - no?

**Comment by JPZ13** [comment]
@JPZ13 - yeah you're right. My apologies for the confusion. That should probably be changed

**Comment by roofurmston** [comment]
Hi, 

I'm not sure if this is the correct place to raise this point. Happy to open a separate issue, if it is more appropriate. 

However, we tried to rollout POD_NAMES v2 on our install last week (v3.3.2) and found that it resulted in the UI not being able to retrieve the log archives from our S3 buckets. So the logs were still archived to S3 correctly and under the new pod names, but when we tried to open them from the UI it gave `artefact not found`. 

Is this a known issue? If not, I am happy to open a issue for it.

**Comment by juliev0** [comment]
@roofurmston that would be great if you could open an issue. Thanks for pointing it out. It sounds like we should block this PR from being merged until that one is resolved, so I'll put the PR back in "draft" I guess.

**Comment by juliev0** [comment]
@roofurmston I wasn't able to reproduce your issue - tried with v3.3.2. What did your install yaml file look like by chance? Did you add POD_NAMES as an environment variable to both the argo server and workflow controller? 

I am running with minio but I don't think the result should be different. I used the UI to click on my pod, select "Inputs/Outputs", and then select the log file. Is this what you did?

**Comment by roofurmston** [comment]
@juliev0 Ah, ok. It might be an issue on our side then. 

So our kustomize install looks something like the following:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.3.1/install.yaml
patches:
  - target:
      kind: Deployment
      name: argo-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --auth-mode=server
  - target:
      kind: Deployment
      name: workflow-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ARGO_EXECUTOR_PLUGINS
          value: "true"
  - target:
      kind: Deployment
      name: workflow-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: POD_NAMES
          value: "v2"
```

As you can see, we only added the env var to the workflow controller and not the server. Adding it to both makes complete sense now. 

Let me try it and see if it solves our issue. 

For reference, when on the log page for a particular step we were using the button at the bottom of the page to load the logs from S3.
