### ISSUE TITLE
Add empty env for argo-server and argo-workflow Deployment

### ISSUE THREAD

**Issue by guillaumBrisard** [argoproj/argo-workflows#7285]
# Summary

Add empty `env` field for argo-server Deployment and workflow-controller Deployment 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - args:
        - server
        - --namespaced
        env: []
        image: quay.io/argoproj/argocli:v3.2.4
        name: argo-server
```
Same thing for workflow-controller

# Use Cases

With kustomize, apply a json patch without overwrite all the env.
Righ now I need to add env before adding my envs (like POD_NAMES), 
If you decide to add some default envs, we will overwrite it if we don't have close look. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
