### ISSUE TITLE
Expressions don't work when creating a runtime generated workflow

### ISSUE THREAD

**Issue by louisnow** [argoproj/argo-workflows#7287]
# Summary
Inside the `resource.manifest` expressions don't seem to work. 
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: louis-init
spec:
  entrypoint: seed
  retryStrategy:
    limit: "3"
  templates:
    - name: seed
      dag:
        tasks:
          - name: typedefs
            template: trigger-seeder
    - name: trigger-seeder
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: louis-seeder-init-
            labels:
              workflows.argoproj.io/creator: {{=sprig.dig('workflows', 'argoproj', 'io\/creator', '', workflow.labels)}}
          spec:
            ttlStrategy:
                secondsAfterSuccess: 120
                secondsAfterFailure: 120
                secondsAfterCompletion: 120
            workflowTemplateRef:
              name: test-louis-atlas
              clusterScope: false
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
```

I currently get this error
```
 Internal Server Error: templates.seed.tasks.typedefs templates.trigger-seeder.resource.manifest must be a valid yaml
```

It works fine when I use the same sprig expression in a regular template input parameter. 

# Use Cases

When would you use this?
While running is SSO mode, sometime the creator label is not always present. I want to conditionally interpolate it to an empty string if it isn't there.
https://github.com/argoproj/argo-workflows/issues/7286#issuecomment-979764067

But regardless of this usecase, I think it makes sense to have this feature.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
