### ISSUE TITLE
Workflow labels for runtime generated workflows seems be nil at the start but UI says otherwise

### ISSUE THREAD

**Issue by louisnow** [argoproj/argo-workflows#7288]
## Summary

What happened/what you expected to happen?
When creating a workflow at runtime, `workflow.labels` exists according to the UI but the dig expression fails.

Whalesay template with the DIG expression.
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: louis-whalesay
spec:
  entrypoint: whalesay
  templates:    
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{=sprig.dig('workflows', 'argoproj', 'io/testlabel', 'default-value', workflow.labels)}}"]

```

Ref Runner Template that has no labels in the created workflow
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: louis-ref-runner
spec:
  entrypoint: seed
  retryStrategy:
    limit: "1"
  templates:
    - name: seed
      dag:
        tasks:
          - name: hello
            template: create-whalesay
    - name:  create-whalesay
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: louis-whalesay-
          spec:
            ttlStrategy:
              secondsAfterSuccess: 120
              secondsAfterFailure: 120
              secondsAfterCompletion: 120
            workflowTemplateRef:
              name: louis-whalesay
              clusterScope: false
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
```
The output after running this is
```
louis-whalesay-5mld7:  _______________________________________
louis-whalesay-5mld7: / {{=sprig.dig('workflows', 'argoproj', \
louis-whalesay-5mld7: | 'io/testlabel', 'default-value',      |
louis-whalesay-5mld7: \ workflow.labels)}}                    /
louis-whalesay-5mld7:  ---------------------------------------
louis-whalesay-5mld7:     \
louis-whalesay-5mld7:      \
louis-whalesay-5mld7:       \
louis-whalesay-5mld7:                     ##        .
louis-whalesay-5mld7:               ## ## ##       ==
louis-whalesay-5mld7:            ## ## ## ##      ===
louis-whalesay-5mld7:        /""""""""""""""""___/ ===
louis-whalesay-5mld7:   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
louis-whalesay-5mld7:        \______ o          __/
louis-whalesay-5mld7:         \    \        __/
louis-whalesay-5mld7:           \____\______/
```

I can fix it by changing the expression to
```
args: ["{{=sprig.dig('labels', 'workflows', 'argoproj', 'io/testlabel', 'default-value', workflow)}}"]
```
I don't get why I need to do this though as `workflow.labels` does seem to exist in the UI. 

![Screenshot 2021-11-26 at 10 17 41 PM](https://user-images.githubusercontent.com/6024271/143611647-9a60b889-adb0-412e-9cbd-e32f1061a387.png)

[The docs](https://argoproj.github.io/argo-workflows/variables/) seem to imply that `workflow.labels` will exist when a workflow is running though it can be empty instead of nil at the start.

What version of Argo Workflows are you running?

## Diagnostics
What executor are you running? 
Docker

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
