### ISSUE TITLE
Support retry stratagy for containers in containerSet

### ISSUE THREAD

**Issue by frimuchkov** [argoproj/argo-workflows#7290]
# Summary

Support retry strategy for containers:
```
      containerSet:
        containers:
          - name: a-transform
            image: 'argoproj/argosay:v2'
            retryStrategy:
              limit: "3"
            command:
              - cowsay
```
# Use Cases

In huge container sets, we have to retry every container, not the container set
<img width="525" alt="image" src="https://user-images.githubusercontent.com/19934346/143675550-0a51629b-08f9-47b9-ba82-ee5cd498ce21.png">
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
