### ISSUE TITLE
Circuit Breakers for CronWorkflows

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#7291]
# Summary

What change needs making?

Implement a circuit breaker for cron workflows. For example, if a workflow has had multiple failures in a row, pause the workflow automatically. Or pause the workflow after a certain number of executions (https://github.com/argoproj/argo-workflows/issues/7201).

Either an expression:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "* * * * *"
  pauseExpression: "{{cronworkflow.failures}} > 3"
```

Or a field:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "* * * * *"
  pauseWhen:
    failures: 2
```

# Use Cases

When would you use this?

Cron workflows are the only CRD that act on their own (i.e. no explicit action is needed to spawn workflows from cron workflows), so a circuit breaker could be useful.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
