### ISSUE TITLE
Workflow parameter not passable anymore after changing default entrypoint

### ISSUE THREAD

**Issue by nielstenboom** [argoproj/argo-workflows#7294]
## Summary

Previously you could submit a workflowtemplate in the UI by passing a parameter manually, it would not matter which entrypoint of the workflow you chose. Now in version v3.2.4, you can only submit a parameter to the workflow if you choose the default entrypoint.

Default entrypoint -> able to pass the workflow parameter
![image](https://user-images.githubusercontent.com/6594531/143880829-a20753e7-8114-4207-b7f5-30e24b7285e4.png)

Picked different entrpoint -> not able to pass the workflow parameter any longer
![image](https://user-images.githubusercontent.com/6594531/143880937-e0eb59bc-6950-4dee-add4-8666f735a8a9.png)

**What happened/what you expected to happen?**
I expect to always be able to pass a parameter via the UI, even when selecting another entrypoint. 

**What version is it broken in?**
v3.2.4

**What version was it working in?**
v3.1.8

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

Relevant part of workflow: 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cbct-evaluation
  namespace: argo
spec:
  entrypoint: cbct-evaluation-pipeline
  # branch parameter so this workflow can be dynamically called for different PRs
  arguments:
    parameters:
    - name: branch
  
  templates:
  - name: cbct-evaluation-pipeline
    retryStrategy:
      limit: "0"
    steps:
    - - name: git-pull-data-and-src
        template: git-pull-data-and-src # also outputs commit-sha
    - - name: install-env
        template: install-env
      - name: generate-path-list
        template: generate-path-list
    - - name: run-evaluation
        template: run-evaluation
        arguments:
          parameters:
          - name: path
            value: "{{item}}"
        withParam: "{{steps.generate-path-list.outputs.result}}" # json list containing the paths
    - - name: aggregate-results
        template: aggregate-results
        arguments:
          parameters:
            - name: commit-sha
              value: "{{steps.git-pull-data-and-src.outputs.parameters.result}}"
    - - name: copy-results-to-s3
        template: copy-results-to-s3
        arguments:
          parameters:
            - name: commit-sha
              value: "{{steps.git-pull-data-and-src.outputs.parameters.result}}"
    - - name: visual-evaluation
        template: visual-evaluation
      - name: write-result-to-github
        template: write-result-to-github

....
```

What Kubernetes provider are you using?
EKS

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.
