### ISSUE TITLE
Allow to always pass workflow scoped variable via UI

### ISSUE THREAD

**Issue by nielstenboom** [argoproj/argo-workflows#7311]
# Summary

Previously you could submit a workflowtemplate in the UI by passing a parameter manually, it would not matter which entrypoint of the workflow you chose. Now you can only submit a parameter to the workflow if you choose the default entrypoint. If the parameter is workflow scoped, then it should be always possible to pass it regardless of which entrypoint you choose.

Default entrypoint -> able to pass the workflow parameter
![image](https://user-images.githubusercontent.com/6594531/144126740-8926d8c1-3439-4316-b68f-b63d04866fc1.png)

Picked different entrypoint -> not able to pass the workflow parameter any longer
![image](https://user-images.githubusercontent.com/6594531/144126761-5c59b93a-7179-4b3b-bf2a-f2c7a55af3f2.png)

First discussed in https://github.com/argoproj/argo-workflows/issues/7294.

# Use Cases

Within our company we use argo workflows to trigger evaluations of our ML models manually from the UI. We have a workflow with different entrypoints based on the input you want to supply to the ML model. The workflow parameter is always the same and it would be redundant to add this parameter to each entrypoint individually.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by jfb74** [comment]
@nielstenboom How are you solving this in the interim? We have the same use case as you and just recently upgraded to argo workflows version 3 not knowing we'd lose this functionality.

**Comment by nielstenboom** [comment]
Hi @jfb74. We've managed by rolling back to a version where this functionality has not been altered yet: `v3.1.8`

**Comment by jfb74** [comment]
@nielstenboom Appreciate the input, we will have to do the same. I am surprised this wasn't a larger breaking change for more people, but perhaps you and I were the only ones who used this functionality in this way. I definitely could imagine a UI enhancement could be put in place where to clearly display which parameter was a workflow level parameter and which was a parameter local to the template then things could live in harmony. 

In [#7294#issuecomment-982734306](https://github.com/argoproj/argo-workflows/issues/7294#issuecomment-982734306), @kennytrytek mentioned some concerns with this potential approach. Their comment about "the server does not support two sets of parameters" is one that I am not sure of the implication/meaning of as I am not aware of the way the argo code works on the backend. Purely speculating here but if it is the case that perhaps the local and global parameters must be combined when submitting in the UI then I could understand where collision and inability to clearly distinguish between the two could be an issue. Ultimately though it seems if this is functionality that we want to maintain it would be on us to put work towards creating the PR with a solution.

**Comment by kennytrytek** [comment]
Hello, I just wanted to follow up and give a little more context. My understanding may also be incomplete, so let me know if I'm missing something.

When a workflow is submitted to Argo, parameters can be supplied to the workflow, along with an entrypoint to use. A default entrypoint can also be configured. Here is an example workflow that I think represents your use case, slightly modified [from the documentation](https://argoproj.github.io/argo-workflows/workflow-inputs/).

<details><summary>example.yaml</summary>
<p>

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: workflow-param-1
  templates:
  - name: main
    dag:
      tasks:
      - name: step-A 
        template: step-template-A
        arguments:
          parameters:
          - name: template-param-1
            value: 5
          - name: template-param-2
            value: "{{workflow.parameters.workflow-param-1}}"

  - name: step-template-A
    inputs:
      parameters:
        - name: template-param-1
        - name: template-param-2
    script:
      image: alpine
      command: [/bin/sh]
      source: |
          echo "{{inputs.parameters.template-param-1}}"
          echo "{{inputs.parameters.template-param-2}}"

  - name: step-template-B
    script:
      image: alpine
      command: [/bin/sh]
      source: |
          echo "{{workflow.parameters.workflow-param-1}}"
```

</p>
</details>

By default, this workflow will execute the `main` entrypoint. On workflow submission, if I select `step-template-B` as an entrypoint, the UI will not give any options to provide inputs because that template step doesn't accept any; however, this step will break on execution because the workflow parameter input was not given.

A simple solution is to pass the workflow input to the template step, as is done in `step-template-A`. I can understand this may be undesirable, particularly if it was working differently before.

A second solution would be to pass the template name to execute in as a workflow parameter, and only use the default template so you only specify workflow parameters. I can give more details on that if needed.

A third solution would be to use the Argo CLI instead of the UI, but that's a pretty big change for a small problem.

Finally, we can modify the Argo UI to always accept workflow parameters regardless of which entrypoint is chosen. This would introduce the possibility of a name collision between the workflow input parameters and template input parameters, but making that change wouldn't remove any features from the UI, only add one; if somebody had a problem with the change, they would be in a subset of the group already having problems.

**Comment by jfb74** [comment]
Appreciate you taking the time to respond and address our concerns. Your example accurately depicts my use case which was previously working. Spelled out my comments below, but TLDR; I like your "Finally..." proposed option. I will admit there could be technical limitations that I am not aware of due to my lack of knowledge, but otherwise I believe a clear solution could be developed that would allow the workflow parameter functionality to continue to function for folks like us who use it this way. 

> A simple solution is to pass the workflow input to the template step, as is done in step-template-A. I can understand this may be undesirable, particularly if it was working differently before.

I agree here that this would be a simple solution, which works when the template is a simplified example but gets much more complicated when things are nested. Unless this is the truly intended behavior directionally, I would hate to need to introduce many unneeded input parameters and complicate passing them throughout my workflow when the workflow parameters at the global level would be perfect and I believe is made for this purpose.

> A second solution would be to pass the template name to execute in as a workflow parameter, and only use the default template so you only specify workflow parameters. I can give more details on that if needed.

This is an interesting idea, but wouldn't you basically then be maintaining 2 workflow templates. One which would just be responsible for calling the other with the right global parameters, and the second is just our existing workflows which worked previously. Admittedly the first one would be quite simple to maintain. Also on this (perhaps I missed the functionality) in the UI would this be seen as 2 workflow executions? Or is there a way that you could do this in a single workflow execution where the second one would spawn off the first but in the same visual DAG? Also I guess you must have the option to set the global workflow parameters when you call one template from another, perhaps I should look into that. 

> A third solution would be to use the Argo CLI instead of the UI, but that's a pretty big change for a small problem.

I agree it is a big change for a small problem, and also it is much easier to give our people who are responsible for execution access to the web UI versus a terminal where they need to execute commands.


> Finally, we can modify the Argo UI to always accept workflow parameters regardless of which entrypoint is chosen. This would introduce the possibility of a name collision between the workflow input parameters and template input parameters, but making that change wouldn't remove any features from the UI, only add one; if somebody had a problem with the change, they would be in a subset of the group already having problems.

I like this idea as the truly optimal solution. In regards to name collisions, there is already the possibility of those when you define a workflow via YAML/JSON, and it handles them fine. It just requires you to specify `input.parameters` versus `workflow.parameters` as you are aware. Perhaps you can give a bit more detail on where your potential concerns comes from. I totally understand if it is a technical limitation, for example if the parameters must be sent as a single dictionary then collisions between input and workflow would pose an issue as they would overwrite each other. If it is purely just a clarity concern, I imagine a solution could be developed so that in the UI the workflow parameters and input parameters are clearly labeled accordingly so you could define each one appropriately when submitting.

**Comment by nielstenboom** [comment]
Hey @kennytrytek, thanks for working on a solution for this! Unfortunately on v3.3.9 this does not seem to work properly yet.

Given this example workflowtemplate:

```yaml

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: arguments
spec:
  entrypoint: whalesay
  # Parameters can be passed/overridden via the argo CLI.
  # To override the printed message, run `argo submit` with the -p option:
  # $ argo submit examples/arguments-parameters.yaml -p message="goodbye world"
  arguments:
    parameters:
    - name: message
      value: hello world

  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]

  - name: whalesay2
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

When trying to submit this from the UI with a different entrypoint, the workflow parameter still disappears: 

![Nov-01-2022 09-35-03](https://user-images.githubusercontent.com/6594531/199192922-d8b20a15-98a8-45d4-8292-a81bec96d77e.gif)
