### ISSUE TITLE
Python SDK - Steps Template not serialized correctly with `model_to_dict`

### ISSUE THREAD

**Issue by samuelBB** [argoproj/argo-workflows#7374]
## Summary

**Version.** I am using the Python SDK on `master:latest` which at the moment corresponds to commit `22b0326` (though the last commit to actually modify the `sdks` folder appears to be `aba6599`).

Briefly, I am constructing a Workflow using the objects in the Python SDK which includes a `steps` template. When I try to serialize the object using the `model_to_dict` function, it appears that the `steps` template is not properly serialized to a `dict` but instead remains in its unserialized object form.

## Reproducible Example

```python
import yaml

from argo_workflows.model.container import Container
from argo_workflows.model.object_meta import ObjectMeta
from argo_workflows.model.io_argoproj_workflow_v1alpha1_template import \
    IoArgoprojWorkflowV1alpha1Template
from argo_workflows.model.io_argoproj_workflow_v1alpha1_workflow import \
    IoArgoprojWorkflowV1alpha1Workflow
from argo_workflows.model.io_argoproj_workflow_v1alpha1_workflow_spec import \
    IoArgoprojWorkflowV1alpha1WorkflowSpec
from argo_workflows.model.io_argoproj_workflow_v1alpha1_metadata import \
    IoArgoprojWorkflowV1alpha1Metadata
from argo_workflows.model.io_argoproj_workflow_v1alpha1_parallel_steps import \
    IoArgoprojWorkflowV1alpha1ParallelSteps
from argo_workflows.model.io_argoproj_workflow_v1alpha1_workflow_step import \
    IoArgoprojWorkflowV1alpha1WorkflowStep

from argo_workflows.model_utils import model_to_dict

manifest = IoArgoprojWorkflowV1alpha1Workflow(
    metadata=ObjectMeta(generate_name='myApp-'),
    spec=IoArgoprojWorkflowV1alpha1WorkflowSpec(
        entrypoint='myTemplate',
        templates=[
            IoArgoprojWorkflowV1alpha1Template(
                name="myTemplate",
                metadata=IoArgoprojWorkflowV1alpha1Metadata(
                    labels={"app": "myApp"}
                ),
                steps=[
                    IoArgoprojWorkflowV1alpha1ParallelSteps(
                        [
                            IoArgoprojWorkflowV1alpha1WorkflowStep(
                                name="mySteps",
                                template="whalesay",
                            )
                        ]
                    )
                ]
            ),
            IoArgoprojWorkflowV1alpha1Template(
                name='whalesay',
                container=Container(
                    image='docker/whalesay:latest',
                    command=['cowsay'],
                    args=['hello world']
                )
            )
        ]
    )
)

print(yaml.dump(model_to_dict(manifest)))
```

Output:
```yaml
metadata:
  generateName: myApp-
spec:
  entrypoint: myTemplate
  templates:
  - metadata:
      labels:
        app: myApp
    name: myTemplate
    steps:
    - - !!python/object:argo_workflows.model.io_argoproj_workflow_v1alpha1_workflow_step.IoArgoprojWorkflowV1alpha1WorkflowStep
        _check_type: true
        _configuration: null
        _data_store:
          name: mySteps
          template: whalesay
        _path_to_item: !!python/tuple []
        _spec_property_naming: false
        _visited_composed_classes: !!python/tuple
        - !!python/name:argo_workflows.model.io_argoproj_workflow_v1alpha1_workflow_step.IoArgoprojWorkflowV1alpha1WorkflowStep ''
  - container:
      args:
      - hello world
      command:
      - cowsay
      image: docker/whalesay:latest
    name: whalesay
```

## Hack to temporarily fix the issue

On the other hand, when I add a custom YAML representer to again apply `model_to_dict` whenever the YAML dumper sees a WorkflowStep type, I do get the correct result. To expand, this is just adding the following before the `yaml.dump` call:
```python
def representer(dumper, data): 
     return dumper.represent_dict(model_to_dict(data))
yaml.add_representer(IoArgoprojWorkflowV1alpha1WorkflowStep, representer)
```

Now output is correct:
```yaml
metadata:
  generateName: myApp-
spec:
  entrypoint: myTemplate
  templates:
  - metadata:
      labels:
        app: myApp
    name: myTemplate
    steps:
    - - name: mySteps
        template: whalesay
  - container:
      args:
      - hello world
      command:
      - cowsay
      image: docker/whalesay:latest
    name: whalesay
```

## Hypotheses Regarding the Issue

While it's possible I am not specifying the Steps/WorkflowSteps correctly, I doubt this, as the type checking valdiation is not producing any error messages from this. I tried fiddling with this (removing the objects from a list, specifying as kwargs instead of args, etc) but to no avail.

As such, my hypothesis is that the recursive serialization in `model_to_dict` fails on the fact that Steps is specified with a nested list, so maybe it bottoms out before actually reaching the nested WorkflowStep object to serialize. Haven't traced exactly how, but thats my guess.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
