### ISSUE TITLE
Show values set in templateDefaults in UI

### ISSUE THREAD

**Issue by nielstenboom** [argoproj/argo-workflows#7378]
# Summary

It would be nice if values that are set in the `templateDefaults` are also shown in the UI. Take the following example: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templateDefaults: 
    container:
      env: 
      - name: TEST_VARIABLE
        value: "hi"
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [bash]
      args: ["-c", "echo $TEST_VARIABLE"]
```

The container is given the `TEST_VARIABLE` by default, but the UI is showing there are no ENV variables for this container:

![image](https://user-images.githubusercontent.com/6594531/145552333-22bc64d3-d36f-4949-9e3f-d11d6d7a2e6d.png)

It would be nice if the variable set in the defaults also shows up there.

# Use Cases

We use the `templateDefaults` regularly in our workflows to set env variables. It would be more clear if these env variables also show up in the UI.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
