### ISSUE TITLE
Artifact reference doesn't resolve in looped steps/tasks when any condition is false

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-workflows#7385]
## Summary

A looped step, which references the step template's input artifact, fails to resolve the artifact when a `when` evaluates to "false". Simply removing the `when` expression allows the looped step to access the template's input artifact. Changing the `when` expression (or the `{{item}}`s) so that it always evaluates to "true" allows the looped step to access the template's input artifact.

The error looks like this: `failed to resolve {{steps.generate-artifact.outputs.artifacts.hello-art}}`.

The bug only occurs in a
1) looped task/step
2) with a condition
3) which evaluates to "false" at least once

Happy Halloween. :-)

I'm using the [release-3.2 branch's quick-start-minimal](https://raw.githubusercontent.com/argoproj/argo-workflows/release-3.2/manifests/quick-start-minimal.yaml) manifests with manual edits to the controller deployment to use the 3.2.4 exec and controller images. (There's no easy way to get a versioned quick start manifest any more, is there?)

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
    - name: artifact-example
      inputs:
        parameters:
          - name: things
            value: '["A", "B"]'  # Changing the B to A fixes the workflow.
      steps:
        - - name: generate-artifact
            template: whalesay
        - - name: consume-artifact
            template: print-message
            when: "'{{item}}' == 'A'"  # Removing this line fixes the workflow. Changing {{item}} to simply A fixes the workflow.
            arguments:
              artifacts:
                - name: message
                  from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"
            withParam: "{{inputs.parameters.things}}"  # Or remove this line to fix everything.
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [sh, -c]
        args: ["sleep 1; cowsay hello world | tee /tmp/hello_world.txt"]
      outputs:
        artifacts:
          - name: hello-art
            path: /tmp/hello_world.txt
    - name: print-message
      inputs:
        artifacts:
          - name: message
            path: /tmp/message
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["cat /tmp/message"]
```

What Kubernetes provider are you using?

docker-desktop

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

The default, I forget what that is.

```bash
# Logs from the workflow controller:
time="2021-12-11T17:28:39.264Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:39.273Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:39.273Z" level=info msg="Steps node artifact-passing-c99wx initialized Running" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:39.273Z" level=info msg="StepGroup node artifact-passing-c99wx-332964174 initialized Running" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:39.273Z" level=info msg="Pod node artifact-passing-c99wx-2373177028 initialized Pending" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:39.282Z" level=info msg="Created pod: artifact-passing-c99wx[0].generate-artifact (artifact-passing-c99wx-2373177028)" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:39.282Z" level=info msg="Workflow step group node artifact-passing-c99wx-332964174 not yet completed" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:39.282Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:39.282Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:39.300Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1193071 workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.265Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.265Z" level=info msg="Updating node artifact-passing-c99wx-2373177028 exit code 0" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.265Z" level=info msg="Setting node artifact-passing-c99wx-2373177028 outputs: {\"artifacts\":[{\"name\":\"hello-art\",\"path\":\"/tmp/hello_world.txt\",\"s3\":{\"key\":\"artifact-passing-c99wx/artifact-passing-c99wx-2373177028/hello-art.tgz\"}},{\"name\":\"main-logs\",\"s3\":{\"key\":\"artifact-passing-c99wx/artifact-passing-c99wx-2373177028/main.log\"}}]}" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.265Z" level=info msg="Updating node artifact-passing-c99wx-2373177028 status Pending -> Succeeded" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="Step group node artifact-passing-c99wx-332964174 successful" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="node artifact-passing-c99wx-332964174 phase Running -> Succeeded" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="node artifact-passing-c99wx-332964174 finished: 2021-12-11 17:28:49.266146604 +0000 UTC" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="StepGroup node artifact-passing-c99wx-3486906283 initialized Running" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="SG Outbound nodes of artifact-passing-c99wx-2373177028 are [artifact-passing-c99wx-2373177028]" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=error msg="Mark error node" error="failed to resolve {{steps.generate-artifact.outputs.artifacts.hello-art}}" namespace=argo nodeName="artifact-passing-c99wx[1]" workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="node artifact-passing-c99wx-3486906283 phase Running -> Error" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="node artifact-passing-c99wx-3486906283 message: failed to resolve {{steps.generate-artifact.outputs.artifacts.hello-art}}" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="node artifact-passing-c99wx-3486906283 finished: 2021-12-11 17:28:49.266506314 +0000 UTC" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="step group artifact-passing-c99wx-3486906283 was unsuccessful: failed to resolve {{steps.generate-artifact.outputs.artifacts.hello-art}}" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="Outbound nodes of artifact-passing-c99wx is []" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="node artifact-passing-c99wx phase Running -> Failed" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="node artifact-passing-c99wx message: failed to resolve {{steps.generate-artifact.outputs.artifacts.hello-art}}" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="node artifact-passing-c99wx finished: 2021-12-11 17:28:49.266659234 +0000 UTC" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="Checking daemoned children of artifact-passing-c99wx" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg=reconcileAgentPod namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="Updated message  -> failed to resolve {{steps.generate-artifact.outputs.artifacts.hello-art}}" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="Marking workflow completed" namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.266Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.273Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=1193102 workflow=artifact-passing-c99wx
time="2021-12-11T17:28:49.279Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artifact-passing-c99wx-2373177028/labelPodCompleted

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
The pods aren't really problematic here.

# Logs from in your workflow's wait container, something like:
Again, not really a wait container problem.
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by crenshaw-dev** [comment]
Aside: I tried to work around the issue by trying to sneak the artifact past the loop logic before evaluating the `when` condition. But I'm getting an error that makes no sense to me.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: artifact-passing-1
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    inputs:
      parameters:
        - name: things
          value: '["A", "B"]'
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message-shim
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"
          parameters:
          - name: thing
            value: "{{item}}"
        withParam: "{{inputs.parameters.things}}"
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt
  - name: print-message-shim
    inputs:
      artifacts:
      - name: message
      parameters:
      - name: thing
    steps:
    - - name: print-message
        when: "'{{inputs.parameters.thing}}' == 'A'"
        template: print-message
        arguments:
          parameters:
          - name: message
            from: "{{inputs.artifacts.message}}"
  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```

Error:

```
Failed to submit workflow: templates.artifact-example.steps[1].consume-artifact templates.print-message-shim.steps[0].print-message.arguments.message.value is required
```

What does it mean the value is required? Do artifacts _have_ values? Seems like that message should apply only to parameters, not artifacts.
