### ISSUE TITLE
Cronwf concurrency watching only the label `workflows.argoproj.io/cron-workflow`

### ISSUE THREAD

**Issue by Guillermogsjc** [argoproj/argo-workflows#7389]
Hi, CronWf concurrency policy could be enhanced in some way to avoid concurrency of the workflow with another workflows?

For example, if I put this minutal `cronwf/concurrency-test` where every launch lasts 90 seconds, it respects the launchs against himself in such a way it is only launched every two minutes, as expected:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: concurrency-test
  namespace: argo
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Forbid"
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: alpine:3.12
          command: [/bin/sh]
          args: ["-c", "echo ALLO && sleep 90"]
```

But, if I set a workflow with the label: `workflows.argoproj.io/cron-workflow: concurrency-test`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wait-sh-
  namespace: argo
  labels:
    workflows.argoproj.io/cron-workflow: concurrency-test
spec:
  entrypoint: wait
  templates:
  - name: wait
    script:
      image: alpine:3.12
      command: [ sh ]
      source: |
        echo "Waiting" && sleep 120
```
the cronwf `cronwf/concurrency-test`  concurrency policy does not take into account this alive workflow, despite it has `workflows.argoproj.io/cron-workflow: concurrency-test` as label (here I suppose this is the expected behaviour).

The question is, could be this updated in such a way the cronwf `foo` would take into account concurrency against every workflow with label `workflows.argoproj.io/cron-workflow: foo`? or something similar using a workflow label?

The use case is pretty clear: you have several kind of workflows pointing to the same dataset, and being triggered by different controllers (cronwf controller, or a custom one launching workflows), and you want  Argo `cronwf` builtin `concurrency` policy, to take into account the workflows generated for this same dataset from other sources than Argo cronwf controller.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
