### ISSUE TITLE
 TLS config for the HTTP workflow trigger

### ISSUE THREAD

**Issue by jackivanov** [argoproj/argo-workflows#7390]
# Summary

TLS config options for HTTP workflow trigger

# Use Cases

Endpoints with self signed certificate

```
    - name: check-http
      http:
        successCondition: "response.statusCode == 200"
        url: "https://xxx.example"
```

```
Get "https://xxx.example": x509: certificate signed by unknown authority
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
