### ISSUE TITLE
inputs.parameters.<name> was not supplied for `onExit` template

### ISSUE THREAD

**Issue by chensun** [argoproj/argo-workflows#7424]
## Summary

What happened/what you expected to happen?

Argo validation for the following workflow yaml failed

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-pipeline-
spec:
  entrypoint: test-pipeline
  templates:
  - name: exit
    container:
      args: ['echo {{inputs.parameters.task_id}}']
      command: [/bin/sh, -c]
      image: busybox
    inputs:
      parameters:
      - {name: task_id}
  - name: exit-handler-1
    dag:
      tasks:
      - {name: start, template: start}
  - name: start
    container:
      args: [echo pipeline start]
      command: [/bin/sh, -c]
      image: busybox
  - name: test-pipeline
    dag:
      tasks:
      - {name: exit-handler-1, template: exit-handler-1}
  arguments:
    parameters:
    - name: task_id
#     if I add `value` for the parameter, then it can pass validation
#     value: something
  serviceAccountName: pipeline-runner
  onExit: exit
```
  
>  templates.exit inputs.parameters.task_id was not supplied\ngithub.com/argoproj/argo-workflows/v3/errors.New\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.5/errors/errors.go:49\ngithub.com/argoproj/argo-workflows/v3/errors.Errorf\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.5/errors/errors.go:55\ngithub.com/argoproj/argo-workflows/v3/workflow/validate.(*templateValidationCtx).validateTemplate\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.5/workflow/validate/validate.go:340\ngithub.com/argoproj/argo-workflows/v3/workflow/validate.(*templateValidationCtx).validateTemplateHolder\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.5/workflow/validate/validate.go:454\ngithub.com/argoproj/argo-workflows/v3/workflow/validate.ValidateWorkflow\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.5/workflow/validate/validate.go:210\ngithub.com/kubeflow/pipelines/backend/src/common/util.ValidateWorkflow
...

What version of Argo Workflows are you running?

3.1.5

## Diagnostics

The issue applies to template used after `onExit`. The issue is also reproducible using the latest argo cli (3.2.5).
Calling `argo lint` on the above yaml results a lint error with the same error message:

   ✖ in "test-pipeline-" (Workflow): templates.exit inputs.parameters.task_id was not supplied

✖ 1 linting errors found!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
