### ISSUE TITLE
Unable to use `steps.*.outputs.parameters.count` from another subgroup

### ISSUE THREAD

**Issue by RobinDong** [argoproj/argo-workflows#7425]
## Summary

Unable to get `steps.*.outputs.parameters.count` from a step of another sub-group

Both v3.2.0 and v3.2.4 has this problem

## Diagnostics

The example YAML could pass lint:
```
$ argo lint example.yaml
example.yaml is valid
Workflow manifests validated
```

The content of `example.yaml`:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello

  templates:
  - name: hello-hello-hello
    steps:
    - - name: section1
        template: section-1
    - - name: section2
        template: section-2

  - name: section-1
    steps:
    - - name: hello1           
        template: whalesay

  - name: section-2
    steps:
    - - name: hello2          
        template: hello-2
        arguments:
          parameters:
          - name: count
            value: '{{item}}'
        withSequence:
          count: '{{hello-hello-hello.steps.section1.steps.hello1.outputs.parameters.count}}'

  - name: hello-2
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["echo hello-2"]

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["echo hello; echo 10 > /tmp/message"]
    outputs:
      parameters:
      - name: count
        valueFrom:
          path: '/tmp/message'
```
The error reported by Argo:
```
strconv.Atoi: parsing "{{hello-hello-hello.steps.section1.steps.hello1.outputs.parameters.count}}": invalid syntax
```

What Kubernetes provider are you using? GKE

What executor are you running? Docker
