### ISSUE TITLE
can not reference variable in inline template

### ISSUE THREAD

**Issue by liuzqt** [argoproj/argo-workflows#7432]
## Summary

```
  templates:
    - name: main
      dag:
        tasks:
          - name: dummy
            inline:
              container:
                image: docker/whalesay:latest
                command: [sh, -c]
                args: ["echo {{inputs.parameters.dummy-input}}"]
              inputs:
                parameters:
                  - name: dummy-input
                    value: 0
```
I had an inline template in dag tasks, but failed to reference the input parameters.

got this error: `failed to resolve {{inputs.parameters.series}}`

## Diagnostics

What Kubernetes provider are you using? aws eks

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
