### ISSUE TITLE
Running Locally - Permission Denied error

### ISSUE THREAD

**Issue by adilfulara** [argoproj/argo-workflows#7443]
## Summary

Trying to setup Argo Worflow for local development. Cannot run any workflow. Attempts to set securityContext was not successful.

What happened/what you expected to happen?

```
standard_init_linux.go:228: exec user process caused: permission denied
```

What version of Argo Workflows are you running?
```
adil@adil-ubuntu:~/go/src/github.com/argoproj/argo-workflows$ git log -n 1 --oneline
3efe2b856 (HEAD -> master, origin/master, origin/HEAD) docs: updated CHANGELOG.md (#7421)
```

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

What Kubernetes provider are you using?

Kind

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Dont know. But i followed [this](https://argoproj.github.io/argo-workflows/running-locally/)

```bash
# Setup argo locally to run

# setup kind cluster
kind cluster create 
docker pull docker/whalesay:latest
kind load docker-image docker/whalesay:latest

# run argo
make clean start API=true UI=true

# submit hello-workd as per quickstart docs
argo submit -n argo --watch https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/hello-world.yaml

# Logs from the workflow pod
adil@adil-ubuntu:~$ k logs hello-world-wrdtc
standard_init_linux.go:228: exec user process caused: permission denied

```

Adding a security context as follows 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

yields the same result.
```
adil@adil-ubuntu:~$ argo submit -n argo hello-world.yaml 
standard_init_linux.go:228: exec user process caused: permission denied 
```

Tried to build the dockerexec-image in case the latest tag is the one needed but that does not build on ubuntu 21.04
```
adil@adil-ubuntu:~/go/src/github.com/argoproj/argo-workflows$ make argoexec-image
GIT_COMMIT=3efe2b8568842a4f9f45ea2df228dc8f310bc947 GIT_BRANCH=master GIT_TAG=untagged GIT_TREE_STATE=dirty RELEASE_TAG=false DEV_BRANCH=false VERSION=latest
KUBECTX=k3d-k3s-default DOCKER_DESKTOP=false K3D=true DOCKER_PUSH=false
RUN_MODE=local PROFILE=minimal AUTH_MODE=hybrid SECURE=false STATIC_FILES=true ALWAYS_OFFLOAD_NODE_STATUS=false UPPERIO_DB_DEBUG=0 LOG_LEVEL=debug NAMESPACED=true
[ ! -e dist/argoexec ] || mv dist/argoexec .
docker buildx install
docker build \
        -t quay.io/argoproj/argoexec:latest \
        --target argoexec \
        --cache-from "type=local,src=/tmp/.buildx-cache" \
        --cache-to "type=local,dest=/tmp/.buildx-cache" \
        --output=type=docker .
[+] Building 0.0s (0/0)                                                                                                                                                         
error: cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
make: *** [Makefile:222: argoexec-image] Error 1
```

OS Information
```
adil@adil-ubuntu:~/go/src/github.com/argoproj/argo-workflows$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
