### ISSUE TITLE
HTTP Template errors with required value spec.containers[1].image

### ISSUE THREAD

**Issue by cehoffman** [argoproj/argo-workflows#7449]
## Summary

Created a ClusterWorkflowTemplate that had a single template defined to abstract aways the specific to posting to an endpoint with taking a few inputs for the workflow. When using the template through a templateRef the workflow would fail on nodes that use the templateRef with

```
step group deemed errored due to child multi-ax-12081-root-setup-09d5fff-postsync-1639989015[0].advertise[0].post error: Pod "multi-ax-12081-root-setup-09d5fff-postsync-1639989015-1995062416" is invalid: spec.containers[1].image: Required value
```

## Diagnostics

Either a workflow that reproduces the bug, or paste your whole workflow YAML, including status, something like:

The workflow template

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: slack-post
spec:
  templates:
    - name: post
      inputs:
        parameters:
          - name: channel
          - name: message
      http:
        url: "http://slack-output-eventsource-svc.argo-events.svc"
        method: POST
        headers:
          - name: Content-Type
            value: application/json
        body: |
          {
            "channel": {{=sprig.quote(inputs.parameters.channel)}},
            "message": {{=sprig.quote(inputs.parameters.message)}}
          }
```

Usage of the workflow template

```
    - name: report-status
      inputs:
        parameters:
          - name: message
          - name: emoji
      steps:
        - - name: post
            templateRef:
              name: slack-post
              template: post
              clusterScope: true
            arguments:
              parameters:
                - name: message
                  value: '<https://our.domain/workflows/orch/{{workflow.name}}|CD> :{{inputs.parameters.emoji}}: *environment*: {{inputs.parameters.message}}'
                - name: channel
                  value: dev-deploy

```

What Kubernetes provider are you using?

GKE

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Tried with Emissary and PNS. Emissary errors on requiring a command for image, so errors earlier. Both with v3.2.6.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
