### ISSUE TITLE
Parameter not sent when switching between entrypoints

### ISSUE THREAD

**Issue by Pluggi** [argoproj/argo-workflows#7453]
### What happened/what you expected to happen?

When trying to submit a workflow template that does not define a default entrypoint, argowf indicates `<default>` :

![image](https://user-images.githubusercontent.com/1277836/146914807-5587940b-f06f-464c-99f2-06fd2c93debd.png)

This leads to a first bug where if you press submit, it indicates that you indeed did not select an entrypoint.

![2021-12-21-112457_1727x562_scrot](https://user-images.githubusercontent.com/1277836/146944232-34240101-eabc-48c0-ae48-2d7997d962e5.png)

This is a regression compared to v3.1.3 where it would simply pick the first template :

![2021-12-21-151704_1249x525_scrot](https://user-images.githubusercontent.com/1277836/146944640-1352a731-7949-4d32-93e0-037f8d0c2bbb.png)

Then, if you select the entrypoint you wanted, in this case `custom-command`, the `command` parameter is not sent in the request to argo :

![2021-12-21-112639_1738x752_scrot](https://user-images.githubusercontent.com/1277836/146944819-105980aa-ca73-403a-99bc-faa458ab60ec.png)

All of this does NOT happen if you select an entrypoint the first time.

### What version of Argo Workflows are you running?

v3.2.6

## Diagnostics

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mywf
spec:
  templates:
    - name: custom-action
      inputs:
        parameters:
          - name: command
          - name: dummy
            default: 'xxx'
      container:
        image: 'alpine'
        command:
          - bash
          - '-c'
          - '{{inputs.parameters.command}}'
  arguments:
    parameters:
      - name: command
```

### What Kubernetes provider are you using?

Azure Kubernetes Service (AKS)

### What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

PNS

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
