### ISSUE TITLE
failed to create new S3 client: NoCredentialProviders: no valid providers in chain

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#7462]
run the below workflow

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: auth
  generateName: s3ls-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
    workflows.argoproj.io/container-runtime-executor: pns
  annotations:
    workflows.argoproj.io/description: |
      This is a s3ls
spec:
  serviceAccountName: argo-workflows-server
  securityContext:
  entrypoint: sumting
  templates:
  - name: sumting
    inputs:
      artifacts:
      - name: my-art
        path: /my-artifact
        s3:
          endpoint: s3.amazonaws.com
          bucket: mybuc
          key: sumfolder/mykey
          roleARN: arn:aws:iam::redact:role/redact.workerrole
          useSDKCreds: true #comment this out or not gives same error
    container:
      image: redact/awscli:2
      command: [sh, -c]
      args: ["ls -l"]
      resources:
        limits:
          memory: 512Mi
          cpu: 500m
        requests:
          cpu: "0"
          memory: "0"
```

error is:

Message:             Error (exit code 1): artifact my-art failed to load: failed to create new S3 client: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

slightly related to https://github.com/argoproj/argo-workflows/discussions/7461 as in i am looking for general purpose s3 interaction (not just download/upload artifact) but using https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

i am using argowf v3.2.6
