### ISSUE TITLE
The workflow-controller evicts the task pod too soon after completion and has no pod to read to update its workflow status 

### ISSUE THREAD

**Issue by stephpalis** [argoproj/argo-workflows#7466]
## Summary

What happened/what you expected to happen?
The PDB on the workflow doesn't wait long enough before evicting the task pod. The PDB for the workflow is working correctly, protecting the pod while it’s running, but after that, the pod is deleted, and the workflow-controller has no pod to read to update its workflow status

What version of Argo Workflows are you running?
argo: v3.1.0-rc13

## Diagnostics
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-failed-pdb-
spec:
  entrypoint: test-failed-pdb
  podDisruptionBudget:
    minAvailable: "100%"

  templates:
  - name: test-failed-pdb
    steps:
    - - name: test-pdb
        template: wait-for-pdb

  - name: wait-for-pdb
    container:
      image: alpine
      command: ["sh", "-c"]
      args: ["sleep 60"]
```
Run
```
kubectl get pods <workflow_pod_name> -o wide
```
and drain the node on which it is running
```
kubectl drain <node>
```

Draining the node will result in a "pod deleted" message on the workflow because the task pod was evicted too soon after completion
```
STEP                      TEMPLATE         PODNAME                           DURATION  MESSAGE
 ✖ test-failed-pdb-v2lhc  test-failed-pdb                                              child 'test-failed-pdb-v2lhc-1663076301' failed
 └───⚠ test-pdb           wait-for-pdb     test-failed-pdb-v2lhc-1663076301  1m        pod deleted
```

What Kubernetes provider are you using? EKS

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
