### ISSUE TITLE
I would like a mentor 

### ISSUE THREAD

**Issue by thatGreekGuy96** [argoproj/argo-workflows#7471]
Hey everyone! 
I'm trying to start contributing to the argo workflows codebase and I think i might need a bit of help. 
I've been trying to resolve #7372 but I cannot reproduce it locally. 

I have followed the instructions on https://argoproj.github.io/argo-workflows/running-locally/ and gotten workflows to run successfully on my local machine (Macbook pro with MacOS Monterey). However it seems like artefact storage is configured automatically when running `make start`. I've tried deleting the `artifact-repositories` configmap but this hasn't helped either. 

Any clues on what I should try here? I already implemented a fix and I am eager to test it to see if it works :D

**Comment by sarabala1979** [comment]
@thatGreekGuy96 I can mentor you.  you  should remove the below configuration from `workflow-controller-configmap`
```yaml
  artifactRepository: |
    s3:
      bucket: my-bucket
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
 ```
