### ISSUE TITLE
Allow variable interpolation in ResourceTemplate manifest

### ISSUE THREAD

**Issue by rossigee** [argoproj/argo-workflows#7483]
# Summary

I was expecting this to work.

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test1-role
  namespace: default
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "secrets"]
  verbs: ["create", "get", "watch", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test1-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: test1-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test1
  namespace: default
spec:
  entrypoint: test-patch
  templates:
  - name: test-patch
    steps:
    - - name: create-test-secret
        template: create-test-secret

    - - name: patch-test-secret
        template: patch-test-secret
        arguments:
          parameters:
          - name: newuser
            value: "testuser"
          - name: newpass
            value: "testpass"

  - name: create-test-secret
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Secret
        metadata:
          name: test1
          namespace: default
        data:
          user: b2xkdXNlcg==
          pass: b2xkcGFzcw==

  - name: patch-test-secret
    inputs:
      parameters:
      - name: newuser
      - name: newpass
    resource:
      action: patch
      mergeStrategy: json
      flags:
      - secret
      - test1
      manifest: |
        - op: replace
          path: /data/user
          value: "{{ inputs.parameters.newuser | b64enc }}"
        - op: replace
          path: /data/pass
          value: "{{ inputs.parameters.newpass | b64enc }}"

```

It fails with:

```
Error (exit code 1): no more retries The request is invalid: patch: Invalid value: "{\"apiVersion\":\"v1\",\"data\":{\"pass\":\"{{ inputs.parameters.newpass | b64enc }}\",\"user\":\"{{ inputs.parameters.newuser | b64enc }}\"},\"kind\":\"Secret\",\"metadata\":{\"name\":\"test1\",\"namespace\":\"default\",\"uid\":\"b574678d-773a-4f6a-ade2-c8cb7dbf7611\",\"resourceVersion\":\"134595861\",\"creationTimestamp\":\"2022-01-02T01:30:02Z\",\"managedFields\":[{\"manager\":\"kubectl-create\",\"operation\":\"Update\",\"apiVersion\":\"v1\",\"time\":\"2022-01-02T01:30:02Z\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:data\":{\".\":{},\"f:pass\":{},\"f:user\":{}},\"f:type\":{}}}]},\"type\":\"Opaque\"}": illegal base64 data at input byte 0
```

# Use Cases

When would you use this?

To update a resource with values provided as input parameters to the workflow.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
