### ISSUE TITLE
Confusing expression evaluation behavior

### ISSUE THREAD

**Issue by liuzqt** [argoproj/argo-workflows#7509]
## Summary

What happened/what you expected to happen?

This might be a bug or just expected behavior. But generally speaking, I'm very confused about when the expression will be evaluated, below is a small example

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: runner1-
spec:
  entrypoint: runner1
  arguments:
    parameters:
      - name: param1
        value: "val1"
      - name: param2
        value: "val2"
      - name: concat-param
        value: "{{=workflow.parameters.param1 + workflow.parameters.param2}}"
  templates:
    - name: runner1
      inputs:
        parameters:
          - name: global-cancat-param
            value: "{{workflow.parameters.concat-param}}"
          - name: local-concat-param
            value: "{{=workflow.parameters.param1 + workflow.parameters.param2}}"
      container:
        image: docker/whalesay:latest
        command: [sh, -c]
        args: ["echo this is runner1 {{inputs.parameters.global-cancat-param}} {{workflow.parameters.concat-param}} {{inputs.parameters.local-concat-param}}"]


```

<img width="641" alt="截屏2022-01-05 下午12 21 30" src="https://user-images.githubusercontent.com/22358241/148284037-774141c0-c698-48ef-8f83-4315e42be29c.png">
<img width="645" alt="截屏2022-01-05 下午12 21 37" src="https://user-images.githubusercontent.com/22358241/148284056-a29bdbee-4ebd-44c4-9e8b-2c6820f67c61.png">

As you can see in the screenshot, the `global-concat-param` is not evaluated in the UI, the `local-concat-param` is evaluated. 
However, in the log, both are evaludated.

I didn't find a clear rule in the document regarding when the expression will be evaluated.

What version of Argo Workflows are you running?
3.2.2

## Diagnostics

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
