### ISSUE TITLE
artifacts/auth/ UI path pointing to s3 can't retrieve 'main' logs when using IRSA sessiontoken

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#7513]
## Summary

What happened/what you expected to happen? 

when i click main logs of completed workflow in the ui it shows 'failed to create new S3 client: NoCredentialProviders: no valid providers in chain. Deprecated.	For verbose messaging see aws.Config.CredentialsChainVerboseErrors'

![image](https://user-images.githubusercontent.com/33283496/148397631-5c9b4ddb-7af4-4a3e-99f1-5a0ddbfb8b4e.png)

my impression on the cause is that the s3 session tokens are not being fed into the code that reads logs on the ui from s3.
note that the logs are successfully written to s3 (i think because the pod running the workflow knows about the sts session tokens)

What version of Argo Workflows are you running? 

3.2.6

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: auth
  generateName: s3ls-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
    workflows.argoproj.io/container-runtime-executor: pns
  annotations:
    workflows.argoproj.io/description: |
      This is a s3ls
spec:
  serviceAccountName: argo-workflows-server
  securityContext:
    #runAsNonRoot: true
  entrypoint: sumting
  templates:
  - name: sumting
    volumes:
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
    container:
      image: argoproj/argosay:v2
      command: [cowsay]
      args: ["hello world"]
      env:
        - name: AWS_ROLE_ARN
          value: "arn:aws:iam::redact:role/redact"
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      volumeMounts:
      - name: aws-iam-token
        mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      resources:
        limits:
          memory: 512Mi
          cpu: 500m
        requests:
          cpu: "0"
          memory: "0"
```

helm settings:

```
artifactRepository:
  archiveLogs: true
  s3:
    insecure: false
    bucket: redact
    keyFormat: argo_logs/{{workflow.creationTimestamp.Y}}/{{workflow.name}}/{{pod.name}}
    endpoint: s3.amazonaws.com
    region: eu-west-1
    useSDKCreds: true
```

```
# executor controls how the init and wait container should be customized
executor:
  image:
    # -- Registry to use for the Workflow Executors
    registry: quay.io
    # -- Repository to use for the Workflow Executors
    repository: argoproj/argoexec
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: ""
  # -- Resource limits and requests for the Workflow Executors
  resources:
    limits:
      memory: "1Gi"
      cpu: 1
    requests:
      cpu: "100m"
      memory: "100Mi"

  # -- Adds environment variables for the executor.
  env:
    - name: AWS_ROLE_ARN
      value: "arn:aws:iam::redact:role/redact"
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /mainctrfs/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

What Kubernetes provider are you using? eks

What executor are you running? PNS

raised off https://github.com/argoproj/argo-workflows/discussions/7495
