### ISSUE TITLE
argo controller panic several times

### ISSUE THREAD

**Issue by henrywangx** [argoproj/argo-workflows#7518]
We faced the argo controller panic, version: 3.2.6，k8s version: 1.20
![image](https://user-images.githubusercontent.com/10096800/148505841-af8770d7-6585-4260-a28f-b95730488588.png)

Panic log:

```bash
time="2022-01-07T02:26:14.916Z" level=info msg="Workflow step group node annotation-resource-package-wf-af0ffa7e-7352-420f-a5-2384831111 not yet completed" namespace=argo-hubble workflow=annotation-resource-package-wf-af0ffa7e-7352-420f-a5
time="2022-01-07T02:26:14.916Z" level=debug msg="Evaluating node annotation-resource-package-wf-af0ffa7e-7352-420f-a5[1].moment-data-prepare-step(113:id:387271,pack_type:JPG,resource_id:3a553c36-316a-4296-915e-8b452ded0af2,resource_type:MOMENT): template: *v1alpha1.WorkflowStep (moment-data-prepare), boundaryID: annotation-resource-package-wf-af0ffa7e-7352-420f-a5" namespace=argo-hubble workflow=annotation-resource-package-wf-af0ffa7e-7352-420f-a5
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x166142e]

goroutine 229 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x2b})
	/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x1bb7b60, 0x3151fd0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/shared_informer.go:776 +0x8e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fbceac4b738)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0005a8738, {0x2105d00, 0xc000186180}, 0x1, 0xc00076c000)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00099f880)
	/go/pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/shared_informer.go:771 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:71 +0x88
```

**Comment by sarabala1979** [comment]
@henrywangx it looks like panic is happening on k8s client code. Can you provide your configuration(workflow-controller-config) and env (os, k8s  provider )details?

**Comment by henrywangx** [comment]
@sarabala1979 
```yaml
apiVersion: v1
data:
  config: |
    instanceID: kraken
    parallelism: 5000
    containerRuntimeExecutor: k8sapi
    containerRuntimeExecutors:
    - name: emissary
      selector:
        matchLabels:
          workflows.argoproj.io/container-runtime-executor: emissary

    executor:
      env:
        - name: aliyun_logs_workflow
          value: stdout
    resourceRateLimit:
      limit: 200
      burst: 400
    nodeEvents:
      enabled: false

    artifactRepository:
      s3:
        accessKeySecret:
          key: accesskey
          name: new-argo-secret
        secretKeySecret:
          key: secretkey
          name: new-argo-secret
        bucket: inceptio-argo-logs-prod
        endpoint: xxxx
        insecure: true
    metricsConfig:
      enabled: true
      path: /metrics
      port: 8080
    persistence:
      archive: true
      clusterName: infra-prod2-hangzhou
      connectionPool:
        maxIdleConns: 20
        maxOpenConns: 0
      nodeStatusOffLoad: true
      postgresql:
        database: krakenargodb
        host: xxxx
        passwordSecret:
          key: krakenpassword
          name: new-argo-secret
        port: 3433
        tableName: argo_workflows
        userNameSecret:
          key: krakenuser
          name: new-argo-secret
```
