### ISSUE TITLE
Allow field runtimeClassName in argo workflows spec for gpu usage 

### ISSUE THREAD

**Issue by FischerLGLN** [argoproj/argo-workflows#7519]
# Summary

Several fields are supported in argo workflows template and the argo workflow crd like the field imagePullSecrets.
If adding the containerd plugin field runtimeClassName: nvidia

```yaml
spec:
  runtimeClassName: nvidia
  containers:
  - ...
```

to the specs section, gpu usage in argo workflows pod is working for kubernetes with containerd backend.
# Use Cases

This would allow us to use argo-workflows natively for our deep learning workloads.
