### ISSUE TITLE
WebUI fetches artifacts from a default source even though workflow has a different configuration

### ISSUE THREAD

**Issue by danmx** [argoproj/argo-workflows#7531]
## Summary

What happened/what you expected to happen?

I'm running a workflow with `artifactRepositoryRef.key` configured to use non-default artifact store. In WebUI, when trying to fetch archived logs I get a message `The specified key does not exist.`. In logs I can see it's calling a default artifact configuration instead the one used in the workflow. 

I expected that the artifact configuration reference in the WebUI will be inherited from the workflow 

Workflow runs in a different namespace (`development`) than Argo Workflows (`argo-workflows`). That namespace has MinIO credentials and artifact configuration ConfigMap (identical that the one used in Argo Workflow namespace).

Error is happening when I'm following the link to the artifact:

`http://192.168.200.20:30080/argo-workflows/artifacts/development/video-processing-bqxtd/video-processing-bqxtd-809555528/main-logs`

or when I can click at a specific graph node and try to see its logs.

When I go directly to logs (via top `logs` button) in a workflow view I can see and pick all the logs.

What version of Argo Workflows are you running?
 
`3.2.6`

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: video-processing
spec:
  artifactRepositoryRef:
    key: location-0_v1.yaml
  archiveLogs: true
  volumes:
    - name: input-videos
      persistentVolumeClaim:
        claimName: data
        readOnly: true
    - name: dewarped-videos
      persistentVolumeClaim:
        claimName: dewarp
  entrypoint: etl
  arguments:
    parameters:
      - name: input-video-relative-path
        value: video.mp4
  templates:
    - name: dewarping
      inputs:
        parameters:
          - name: input-video-relative-path
      container:
        image: busybox
        command:
          - "sh"
          - "-cx"
          - "ls -la /mnt/input/{{inputs.parameters.input-video-relative-path}} > /mnt/output/test"
        volumeMounts:
          - name: input-videos
            mountPath: /mnt/input
            readOnly: true
          - name: dewarped-videos
            mountPath: /mnt/output
      outputs:
        artifacts:
        - name: dewarped-videos
          path: /mnt/output/
    - name: inference-engine
      container:
        image: busybox
        command:
          - "sh"
          - "-cx"
          - "ls /mnt/input/; sleep 100; ls /mnt/input/test"
        volumeMounts:
          - name: dewarped-videos
            mountPath: "/mnt/input"
            readOnly: true
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: '1'
        resources:
          limits:
            nvidia.com/gpu: '1'
          requests:
            nvidia.com/gpu: '1'
    - name: etl
      dag:
        tasks:
        - name: dewarping
          template: dewarping
          arguments:
            parameters:
            - name: input-video-relative-path
              value: "{{workflow.parameters.input-video-relative-path}}"
        - name: inference-engine
          dependencies:
            - dewarping
          template: inference-engine
```

What Kubernetes provider are you using?

`k0s`

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

`k8sapi`

```
time="2022-01-09T12:03:35.703Z" level=info msg="resolved artifact repository" artifactRepositoryRef="development/#" 
[...]
time="2022-01-09T11:35:30.821Z" level=info msg="Getting file from s3" bucket=argo-workflows endpoint="location-1-minio.minio:9000" key=video-processing-4tgqb/video-processing-4tgqb-2351348489/main.log path=/tmp/artifact626116452                                                                                                                                                                                  
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
