### ISSUE TITLE
v3.2.6 'expression' in RetryStrategy (conditional retry) is Broken

### ISSUE THREAD

**Issue by kennytrytek** [argoproj/argo-workflows#7539]
## Summary
Submitting this example workflow results in an error.
https://github.com/argoproj/argo-workflows/blob/master/examples/retry-conditional.yaml
```
$ argo submit ./retries.yaml
Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "expression"
```

What version is it broken in?
v3.2.6

What version was it working in?
v3.1.2

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
# Only retry if the retryStrategy.when condition is satisfied. In this example, retries will be made until a pod has
# exit code 2 or the limit of 10 is reached, whichever happens first.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-script-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: safe-to-retry
            template: safe-to-retry
        - - name: retry
            template: retry-script
            arguments:
              parameters:
                - name: safe-to-retry
                  value: "{{steps.safe-to-retry.outputs.result}}"

    - name: safe-to-retry
      script:
        image: python:alpine3.6
        command: ["python"]
        source: |
          print("true")

    - name: retry-script
      inputs:
        parameters:
            - name: safe-to-retry
      retryStrategy:
        limit: "3"
        # Only continue retrying if the last exit code is greater than 1 and the input parameter is true
        expression: "asInt(lastRetry.exitCode) > 1 && {{inputs.parameters.safe-to-retry}} == true"
      script:
        image: python:alpine3.6
        command: ["python"]
        # Exit 1 with 50% probability and 2 with 50%
        source: |
          import random;
          import sys;
          exit_code = random.choice([1, 2]);
          sys.exit(exit_code)
```

What Kubernetes provider are you using?
Docker Desktop

What executor are you running?
Emissary

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.
