### ISSUE TITLE
Errors when trying to use templateRef on hooks.exit

### ISSUE THREAD

**Issue by amithi-cider** [argoproj/argo-workflows#7558]
## Summary

What happened/what you expected to happen?

When trying to use hooks.exit similar to [this example](https://github.com/argoproj/argo-workflows/blob/master/examples/exit-handler-with-param.yaml), but replacing template with templateRef - getting a runtime error on the exit step with a message: "failed to get a template".

Also, when opening the manifest of the exit step there is a weird exception:

![image](https://user-images.githubusercontent.com/90134772/149396603-87d7957c-5b5c-420e-a77b-36e65f2f5d2a.png)

The workflow hangs on running state.

The manifest for the top level node shows that the template on the hooks.exit level is empty.

**What version of Argo Workflows are you running?**

V3.2.4

**What Kubernetes provider are you using?**

minikube

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by dinever** [comment]
Hi @amithi-cider, thanks for reporting this!

I tried to reproduce this with v3.2.4 but had no luck.

Here's my workflow:

<details>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: exit-handlers-
spec:
  entrypoint: intentional-fail
  onExit: exit-handler
  templates:
  # primary workflow template
  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]

  - name: exit-handler
    steps:
    - - name: call-whalesay-template
        templateRef:
          name: workflow-template-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
            - name: message
              value: "hello world"
```

Here's the workflow template I'm using:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

</details>

The above workflow works with Argo v3.2.4 on my end. The exit handler was successfully triggered. Could you try these? If the example fails on your end could you also share the logs of the workflow controller? Thanks!

**Comment by amithi-cider** [comment]
Hi @dinever - sorry I wasn't clear on the issue description, but I am having the issues on [hooks.exit ](https://argoproj.github.io/argo-workflows/fields/#workflowstep) as part of a specific step. (onExit is deprecated for a single step) 

So continuing on your example the template should look like :


```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-with-steps-
spec:
  entrypoint: retry-with-steps
  templates:
  - name: retry-with-steps
    steps:
    - - name: hello1
        template: intentional-fail
        hooks:
          exit:
            templateRef:
              name: workflow-template-whalesay-template
              template: whalesay-template
            arguments:
              parameters:
                - name: message
                  value: "hello world"
        
  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]

```

**Comment by dinever** [comment]
@amithi-cider Thanks for sharing the workflow! I was able to reproduce this with the latest code. Looks like `LifecycleHook` currently doesn't support `templateRef` at all: https://argoproj.github.io/argo-workflows/fields/#lifecyclehook
I'll make a quick PR to support this and see what others think.

For now, the workaround is to call a local template and then call a workflow template from there, like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hooks-exit-test-
spec:
  entrypoint: hooks-exit-test
  templates:
    - name: hooks-exit-test
      steps:
        - - name: hello1
            template: intentional-fail
            hooks:
              exit:
                template: exit-handler

    - name: intentional-fail
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo intentional failure; exit 1"]

    - name: exit-handler
      steps:
        - - name: call-whalesay
            templateRef:
              name: workflow-template-whalesay-template
              template: whalesay-template
            arguments:
              parameters:
              - name: message
                value: "hello world"
```

Thanks!
