### ISSUE TITLE
workflow parameter `valueFrom: supplied: {}` fails to resolve

### ISSUE THREAD

**Issue by scott-grimes** [argoproj/argo-workflows#7563]
A workflow template fails to resolve a parameter supplied through the UI 

A workflow template using valueFrom generates an error
```yaml
  arguments:
    parameters:
      - name: name
        valueFrom:
          supplied: {}
```
Changing the parameter definition to an empty `value` works correctly however:

```yaml
  arguments:
    parameters:
      - name: name
        value: ""
```

UI screen:
<img width="376" alt="Screen Shot 2022-01-14 at 11 03 34 AM" src="https://user-images.githubusercontent.com/6396416/149550814-e83b7aed-6b09-4562-aa96-a55fc38f092d.png">

Inputs/Outputs with `valueFrom: supplied {}`
<img width="852" alt="Screen Shot 2022-01-14 at 11 03 46 AM" src="https://user-images.githubusercontent.com/6396416/149550905-55e2f7b3-002f-4cae-9055-e5e07abff011.png">

Inputs/Outputs with `value: ""`
<img width="843" alt="Screen Shot 2022-01-14 at 11 08 42 AM" src="https://user-images.githubusercontent.com/6396416/149550938-bc8d088f-886a-4648-90c0-d43cbdf6f058.png">

## Summary
We want to force a user to enter a string in the UI for a parameter. Prior to yesterday (Jan 13) our workflowtemplates were functioning correctly. No change has been made to our argo installation (we are using the 3.2 install manifest from https://raw.githubusercontent.com/argoproj/argo-workflows/release-3.2/manifests/install.yaml), and the workflowtemplates have not been modified in weeks.

What happened/what you expected to happen?

`"{{workflow.parameters.name}}"` should resolve to `"bob"`

What version of Argo Workflows are you running?
3.2

Unfortunately the manifest defines the workflow image as `quay.io/argoproj/workflow-controller:latest`, see below for container information

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: start
  namespace: argo
spec:
  arguments:
    parameters:
      - name: name
        # does not work!
        valueFrom:
          supplied: {}
        # this does work
        # value:
        # name: ""
      - name: region
        value: us-east-1
        enum:
          - us-east-1
          - ap-southeast-2
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      steps:
        - - name: create
            arguments:
              parameters:
              - name: greeting
                value: "my name is {{workflow.parameters.name}}"
              - name: region
                value: "{{workflow.parameters.region}}"
            templateRef:
              name: create-start
              template: entrypoint
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-start
  namespace: argo
spec:
  arguments:
    parameters:
    - name: greeting
      valueFrom:
        supplied: {}
    - name: region
      valueFrom:
        supplied: {}
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    inputs:
      parameters:
      - name: greeting
      - name: region
    steps:
      - - name: print
          templateRef:
            name: greet
            template: entrypoint
          arguments:
            parameters:
              - name: greeting
                value: '{{inputs.parameters.greeting}}'
              - name: region
                value: '{{inputs.parameters.region}}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: greet
  namespace: argo
spec:
  arguments:
    parameters:
    - name: greeting
      valueFrom:
        supplied: {}
    - name: region
      valueFrom:
        supplied: {}
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    inputs:
      parameters:
      - name: greeting
      - name: region
    script:
      image: ubuntu
      command:
      - bash
      source: |
        set -ex;

        # Fetch Arguments
        DESTINATION="{{inputs.parameters.greeting}}";
        CREATOR="{{inputs.parameters.region}}";
        echo "hello ${GREETING}."
        echo "i am from ${REGION}"
```

What Kubernetes provider are you using?
AWS EKS 1.19.13-eks-8df270

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

pns

Other information:
As of this morning (Jan 14) when running the workflow there are no error messages in the workflow-controller logs. We have two workflow-controller containers running right now with sha 

```workflow-controller@sha256:5027a61dd9c6b47a97b633f896f9d6489b6cd247815b4650951ea2e51333c2cb
workflow-controller@sha256:f9e048f2b4fc7b369ec7566793108137e1af6c8af34a1f3331abcf72ae646009
```

I do not have the sha of the container which was giving error logs yesterday unfortunately

One other possibly related issue: I'm 99% sure that when submitting via the ui using 
```yaml
  arguments:
    parameters:
      - name: namespace
        valueFrom:
          supplied: {}
```

If a user leaves the form blank an error message is supposed to pop up saying that a value must be supplied. This appears to no longer be the case, I can submit the above workflow without entering a `name`. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
