### ISSUE TITLE
Confusingly, `when` _kind of_ supports expr expressions

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-workflows#7576]
## Summary

My workflow worked. I expected it to not work. I used the following when expression:

```yaml
when: "{{=jsonpath(inputs.parameters.json, '$.a') == 'b'}}"
```
I expected to get an error like this: `Failed to submit workflow: templates.top when expression doesn't support 'expr' format '{{='. 'When' expression is only support govaluate format {{ `.

But instead, the workflow ran! However, if I introduce a typo to the expression:

```yaml
when: "{{=jsonpath(inputs.parameters.json, '.a') == 'b'}}"
```

I get the above error message as expected. Presumably because the failed expression was not substituted, so the `when` validation logic actually caught its presence.

What version of Argo Workflows are you running?

Controller: 3.2.6
CLI: 3.2.3

## Diagnostics

This workflow runs without error, even though it seems like it should fail with a validation error.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: should-not-work-
spec:
  arguments:
    parameters:
      - name: json
        value: >-
          {"a": "b"}
  entrypoint: top
  templates:
  - name: top
    inputs:
      parameters:
        - name: json
    steps:
      - - name: whalesay
          when: "{{=jsonpath(inputs.parameters.json, '$.a') == 'b'}}"
          template: whalesay
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]

```

I'm using docker-desktop k8s with the default executor.

Here's my guess: when the expr expression is valid, it gets executed, and the result is dropped into the `when` field. If the output is a valid govaluate expression, the `when` logic just treats it as a hard-coded govaluate expression. 

I'm not really sure how this should be fixed. You could just drop the warning. But an expr expression that doesn't produce a govaluate expression is still invalid. You could document the behavior, but it's really weird to explain. You could add first-class expr support for `when` conditions, but that's a lot of work.

Or nothing, and this ticket could serve as documentation of this weird edge case. :-P

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
