### ISSUE TITLE
Backoff is applied even when `retryStrategy.limit` has been reached

### ISSUE THREAD

**Issue by dimitri-fert** [argoproj/argo-workflows#7588]
## Summary

What happened/what you expected to happen?

When using `retryStrategy.backoff.limit: 2` and all child nodes (0 ; 1 and 2) already failed, I am expecting the parent node to fail immediatly as no more retries are allowed. Instead, after node 2 fails, new backoff is still applied (12mn in my case) and parent node fails later than expected.

![image](https://user-images.githubusercontent.com/18677414/150172871-d9fdbcf1-c623-4462-9f5a-1d0fda653df6.png)

What version of Argo Workflows are you running?
v3.2.4

## Diagnostics

I used this ClusterWorkflowTemplate (truncated) to emulate node durations on a failing `terraform apply` step. To be close to my use case, it takes longer on the first run (21mn) that on retries (5mn).

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: bootstrap-sandbox-infrastructure
spec:
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  securityContext:
    fsGroup: 1001
  templates:
    - name: terraform-apply-infrastructure
      retryStrategy:
        limit: 2
        backoff:
          duration: 3m
          factor: 2
          maxDuration: 60m
      container:
        image: hashicorp/terraform:v1.0.9
        imagePullPolicy: IfNotPresent
        workingDir: /sources/k8s-apps-descriptors/terraform
        command:
          - sh
        args:
          - -c
          - |
            set -eo pipefail
            mkdir -p /sources/tmp

            if [[ -f /sources/tmp/duration ]]; then
              duration="$(cat /sources/tmp/duration)"
            else
              duration="21m"
            fi
            sleep "${duration}"

            echo "5m" > /sources/tmp/duration
            exit 1
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false  # terraform needs /tmp
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - name: workdir
            mountPath: /sources
```

What Kubernetes provider are you using?
GKE v1.20.11-gke.1300

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker

```bash
# Logs from the workflow controller:

time="2022-01-19T15:25:24.189Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 message: Backoff for 3 minutes 0 seconds" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:33:56.542Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 message: Backoff for 6 minutes 0 seconds" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:45:28.966Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 message: Backoff for 12 minutes 0 seconds" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
[...]
time="2022-01-19T15:57:39.032Z" level=info msg="node has maxDuration set, setting executionDeadline to: Wed Jan 19 16:04:02 +0000 (6 minutes from now)" namespace=apps-sbx-qo-pr-4337 node="bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2[0].main.terraform-apply-infrastructure" workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:57:39.032Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 message: " namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:57:39.032Z" level=info msg="No more retries left. Failing..." namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:57:39.032Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 phase Running -> Failed" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:57:39.032Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 message: No more retries left" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
time="2022-01-19T15:57:39.032Z" level=info msg="node bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2-3538259764 finished: 2022-01-19 15:57:39.032781319 +0000 UTC" namespace=apps-sbx-qo-pr-4337 workflow=bootstrap-sandbox-infrastrucuture-sbx-qo-pr-4337-d29n2
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@dimitri-fert are you submitting clustertemplate directly or referring templateRef in workflow?

**Comment by dimitri-fert** [comment]
@sarabala1979 I'm referring templateRef in workflow

**Comment by alexec** [comment]
It seems to me that the limit is 1 off. Can you confirm?

**Comment by dimitri-fert** [comment]
Performed a 2nd test with a simple `exit 1`.I confirm the diagnosis, my limit is set to 2 but back-off is applied even this limit is reached

```
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-backoff
  namespace: argo-events
  # labels:
  #   workflows.argoproj.io/container-runtime-executor: emissary
spec:
  securityContext:
    fsGroup: 1001
  serviceAccountName: workflow-executor
  entrypoint: main
  templates:
    - name: main
      retryStrategy:
        limit: 2
        backoff:
          duration: 2m
          factor: 2
          maxDuration: 60m
      container:
        image: hashicorp/terraform:1.0.9
        imagePullPolicy: IfNotPresent
        workingDir: /sources/k8s-apps-descriptors/terraform
        command:
          - sh
        args:
          - -c
          - |
            exit 1

```
