### ISSUE TITLE
Non-standard git username

### ISSUE THREAD

**Issue by jwjs36987** [argoproj/argo-workflows#7593]
When working with AWS CodeCommit a non-standard username is required, which is generated by AWS. In theory this is supported but I believe there is a bug.

Currently the artifact path is passed into the function that extracts the username (this is a value like `/tmp/artifact`) rather than the Git repo url (e.g. `ssh://user@host/path/to/repo`) which means it is impossible to actually change the username.

https://github.com/argoproj/argo-workflows/blob/db7d90a1f609685cfda73644155854b06fa5d28b/workflow/artifacts/git/git.go#L115

**Comment by jwjs36987** [comment]
Of course.

I am trying to use a configuration like:

```
artifacts:
  - name: some-name
    path: /tmp/git-clone
    git:
      repo: ssh://APLONGUSERNAME@git-codecommit.us-east-1.amazonaws.com
      sshPrivateKeySecret:
         name: codecommit-creds
         key: ssh-private-key
```

I am expecting Argo to run the equivalent of `git clone ssh://APLONGUSERNAME@git-codecommit.us-east-1.amazonaws.com` with the appropriate private key, however, I believe it ends up running `git clone ssh://git@git-codecommit.us-east-1.amazonaws.com`. I couldn't find any appropriate logging to turn on to confirm this suspicion.

I believe the relevant code is:
https://github.com/argoproj/argo-workflows/blob/db7d90a1f609685cfda73644155854b06fa5d28b/workflow/artifacts/git/git.go#L114-L128

where `path` gets mapped to the path argument and the git specific parameters get passed in via `inputArtifact`. The path gets passed to `GetUser` which is supposed to extract the git username (and there are tests to check this function works). However, the path variable is set to `/tmp/git-clone` not `ssh://APLONGUSERNAME@git-codecommit.us-east-1.amazonaws.com` and so it could never extract the correct value.

I think the correct fix is to change this to:
```
sshUser := GetUser(inputArtifact.Git.Repo)
```

This is all based against v3.2.6.
