### ISSUE TITLE
Failed to resolve global parameters in WorkflowTemplate

### ISSUE THREAD

**Issue by eferos93** [argoproj/argo-workflows#7608]
## Summary

What happened/what you expected to happen?
I am building a `WorkflowTemplate` in order then to produce a test and a production `Workflow` that use the same template but with different parameters. This is work is for my master thesis, therefore I am not an expert with Argo.
When I try to create the below `WorkflowTemplate` I receive the following error:
```
2022/01/21 12:24:41 Failed to create workflow template: templates.data-handling templates.data-handling: failed to resolve {{workflow.parameters.input-path}}
```
According to the [documentation](https://argoproj.github.io/argo-workflows/workflow-templates/#:~:text=label%3A%20example%2Dvalue-,Working%20with%20parameters,-%C2%B6) and from what I understood from it, in a workflow template, it is possible to reference to global parameters later defined in the workflow.
I looked for similar issues and I found #6036 #2634 #2590 that had related problems and they have been fixed and closed.
I was wondering, shall I just define the template without `args` and then specify them directly in the workflow implementation? Or is this a bug?

What version of Argo Workflows are you running? 
argo: v3.2.6+db7d90a.dirty
  BuildDate: 2021-12-18T04:36:35Z
  GitCommit: db7d90a1f609685cfda73644155854b06fa5d28b
  GitTreeState: dirty
  GitTag: v3.2.6
  GoVersion: go1.17.5
  Compiler: gc
  Platform: linux/amd64

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: genomic-workflow
spec:
  templates:
  - name: data-handling
    container:
      image: eferos93/data-handling
      args: ["{{workflow.parameters.input-path}}", "{{workflow.parameters.output-path}}"]
  - name: bcl2fastq
    container:
      image: umccr/bcl2fastq
      args: ["{{workflow.parameters.test-parameters}}", "{{workflow.parametes.production-parameters}}"]
  - name: fastqc
    container:
      image: biocontainers/fastqc
      args: ["{{workflow.parameters.test-parameters}}", "{{workflow.parameters.production-parameters}}"]
  - name: multiqc
    container:
      image: eferos93/multiqc
      args: ["{{workflow.parameters.test-parameters}}", "{{workflow.parameters.production-parameters}}"]
```

What Kubernetes provider are you using? None, installed directly in an HPC cluster..

What executor are you running? Docker

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tooptoop4** [comment]
maybe related to https://github.com/argoproj/argo-workflows/discussions/7584

**Comment by alexec** [comment]
I think you need to specify the input parameters, something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: genomic-workflow
spec:
  templates:
  - name: data-handling
    inputs: 
      parameters: 
      - name: input-part
    container:
      image: eferos93/data-handling
      args: ["{{workflow.parameters.input-path}}", "{{workflow.parameters.output-path}}"]
  - name: bcl2fastq
    container:
      image: umccr/bcl2fastq
      args: ["{{workflow.parameters.test-parameters}}", "{{workflow.parametes.production-parameters}}"]
  - name: fastqc
    container:
      image: biocontainers/fastqc
      args: ["{{workflow.parameters.test-parameters}}", "{{workflow.parameters.production-parameters}}"]
  - name: multiqc
    container:
      image: eferos93/multiqc
      args: ["{{workflow.parameters.test-parameters}}", "{{workflow.parameters.production-parameters}}"]
```
