### ISSUE TITLE
`onExit` handler didn't support access `{{workflow.status}}` at step level

### ISSUE THREAD

**Issue by Colstuwjx** [argoproj/argo-workflows#7616]
## Summary

What happened/what you expected to happen?
Argo Should render workflow.status as usual, but it didn't, and I got an error in console: ` Failed: invalid spec: templates.exit-handler templates.exit-handler.steps failed to resolve {{workflow.status}}`.

What version of Argo Workflows are you running?
argo: v3.2.6

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: good-workflow
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: step1
        onExit: exit-handler
        template: cry

  - name: exit-handler
    steps:
    - - name: notify
        template: send-email
      - name: celebrate
        template: celebrate
        when: "{{workflow.status}} == Succeeded"
      - name: cry
        template: cry
        when: "{{workflow.status}} != Succeeded"
  - name: send-email
    container:
      image: alpine:latest
      command: [sh, -c]
      # Tip: {{workflow.failures}} is a JSON list. If you're using bash to read it, we recommend using jq to manipulate
      # it. For example:
      #
      # echo "{{workflow.failures}}" | jq -r '.[] | "Failed Step: \(.displayName)\tMessage: \(.message)"'
      #
      # Will print a list of all the failed steps and their messages. For more info look up the jq docs.
      # Note: jq is not installed by default on the "alpine:latest" image, however it can be installed with "apk add jq"
      # args: ["echo send e-mail: {{workflow.name}} {{workflow.status}} {{workflow.duration}}. Failed steps {{workflow.failures}}"]
      args: ["echo send e-mail"]
  - name: celebrate
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo hooray!"]
  - name: cry
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo boohoo!"]
```

What Kubernetes provider are you using?
Minikube v1.23.2

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
K8s.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
