### ISSUE TITLE
Dedicated dex for argo-workflows in argocd-style

### ISSUE THREAD

**Issue by barektui** [argoproj/argo-workflows#7624]
# Summary
Make argo-workflows sso independent from argocd dex

What change needs making?
Parhaps argo-workflows should have it's own deployment of dex since one may want to run both argocd and workflows on different clusters.

# Use Cases

Running smaller infra you will likely don't have dedicated cluster for your tools. Argocd on production cluster and argo-workflows on development cluster can be considered as a common pattern in such case.

##Details

Argocd own implementation of sso (f.e. Github) seems much more straightforward than using dex from another application. As far as i understand argocd dex it is embedded into argocd or at least provides some redirect. I am running AWS ALB in the front of Argocd (with grpc working) but i can't specify healthcheck per ingress path like that:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: argo-workflows
    alb.ingress.kubernetes.io/inbound-cidrs:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/conditions.argo-server-grpc: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-FS-1-2-Res-2020-10"
    alb.ingress.kubernetes.io/certificate-arn: 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    # applies to any path within the ingress, breaks grpc!
    # alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '8'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  labels:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/name: argo-server
    app.kubernetes.io/part-of: argo
  name: argo-server
spec:
  rules:
  - host: argo-workflows.example.com
    http:
      paths:
      - backend:
          service:
            name: argo-server-grpc
            port:
              number: 2746
        pathType: ImplementationSpecific
      - backend:
          service:
            name: argo-server
            port:
              number: 2746
        pathType: ImplementationSpecific
      - backend:
          service:
            name: argo-workflows-dex-server
            port:
              number: 5556
        path: /api/dex
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - argo-workflows.example.com
```

Don't know the magic behing argocd dex and github integration yet it seem much more straightforward to me. Mitigates problem of healthcheck path on alb very well. I believe you may be willing to call it an 'edge case' yet architecture of Argo stack is modular while having argo-workflows dependant on argocd-dex seem to be going in quite opposite way.

PS. Thank you for amazing software!

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
