### ISSUE TITLE
Quickstart: transport: authentication handshake failed

### ISSUE THREAD

**Issue by jmclean-starburst** [argoproj/argo-workflows#7632]
## Summary

What happened/what you expected to happen?
When connecting to the UI of Argo Workflows (after port forwarding), I receive this message and virtually no components load:
```
Service Unavailable: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```

What version of Argo Workflows are you running?
latest (ie 3.2.6)

## Diagnostics
Quickstart Guide - follow steps in guide to reproduce

What Kubernetes provider are you using?
EKS/Minikube

Configuration:
```yaml
    spec:
      containers:
      - args:
        - server
        - --namespaced
        - --auth-mode
        - server
        - --auth-mode
        - client
        - --insecure-skip-verify
        - "true"
```

kustomization.yaml
```yaml
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-workflows/v3.2.6/manifests/quick-start-minimal.yaml

namespace: argo-workflows
```

![image](https://user-images.githubusercontent.com/72760973/150980729-23a15247-ddea-4ddd-bfff-c13a9a5d4934.png)

> Note: This is reproducible w/ the minimal quickstart via minikube as well
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by materkey** [comment]
I also have this issue

**Comment by materkey** [comment]
argo-server seems to respond with 503 but can't see it in argo-server pod logs even with -v flag

**Comment by materkey** [comment]
I've ended up by using `--secure=false`as a workaround. Also deleted `nginx.ingress.kubernetes.io/backend-protocol: https`

**Comment by jmclean-starburst** [comment]
@materkey I have done this in the past...its just kind of annoying to update the readiness probe, add a new flag to server start, update ingress; This definitely needs to be resolve by the Argo team bc any new user of workflows is going to be put off by these errors. I have used the quickstart it he past without any issues...so this seems a bit wonky.

**Comment by jmclean-starburst** [comment]
I believe I found the issue; the argo CLI is using `latest` for the image tag, instead of specifying the version tag (ie `v3.2.6`). I have tested this w/ v3.1.15 and after changing the image tag, it works. I will now validate same for version 3.2.6

**Comment by jmclean-starburst** [comment]
I was able to fix this by patching the image off of `latest`
```yaml
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-workflows/v3.2.6/manifests/quick-start-minimal.yaml

images:
- name: quay.io/argoproj/argocli
  newTag: v3.2.6

namespace: argo-workflows
```
