### ISSUE TITLE
Variable for DAG task name (or step name)

### ISSUE THREAD

**Issue by neilharris123** [argoproj/argo-workflows#7698]
# Summary

It would be useful to have a way of retrieving the task name of a DAG task. For all of the DAG template variables in the documentation, the TASKNAME is required before they can be accessed. But there is no way of referencing the TASKNAME; it's presumed it is known beforehand.  

# Use Cases

When would you use this?

For example, let's say I've got several different volumes and I want to mount each in a different task in my DAG. But everything else in the template used for each task is the same. IN the template, it would be useful to add a placeholder in volumeMounts referencing the task.name, like this:

```
  templates:
  - name: myscript
    inputs:
      parameters:
        - name: task
        - name: script
    container:
      image: alpine:v3.14
      imagePullPolicy: Never
      command: [sh, -c]
      args: ["echo 'test' > /mnt/myvolume/file.txt"]
      volumeMounts:
      - name: "{tasks.name}"
        mountPath: /mnt/myvolume

  - name: processing-tasks
    dag:
      tasks:
        - name: task1
          template: myscript
        - name: task2
          template: myscript

```

This way I only need to have one template which allows me to dynamically reference different volumes based on the name of the task. Currently, (as far as I can tell), I have to create a different template referencing a different volume for each dag task. This seems very inefficient. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
