### ISSUE TITLE
v3.2.6 Error when using PodSpecPatch to add resource requests to wait container on resource template type

### ISSUE THREAD

**Issue by dmegyesi** [argoproj/argo-workflows#7725]
### What happened/what you expected to happen?

I have some Workflows that have regular `container` type templates and `resource` type templates defined in the same file.

I have a `PodSpecPatch` defined on the Workflow level that adds a `resources` section to every `wait` and `main` container for every workflow Pod:

```yaml
podSpecPatch: |
  containers:
    - name: wait
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
    - name: main
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
```

This is something that has been working for a long time, using Argo v2.12.5. Now when upgrading to Argo v3.2.6, this has stopped working when using `resource:` type of templates.

```yaml
[...]
resource:
  action: create
  manifest: |
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx
[...]
```

Apparently the root cause is that these Pods created by `resource` templates don't have a `wait` container in their manifest, so when you try to patch it, you end up with some random errors coming from the K8s API:

```
type: 'Warning' reason: 'WorkflowNodeError' Error node sparkly-rhino: Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value"
```

This is how the Pod looks like: you can see there's only a `main` container defined, there is no `wait`:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sparkly-rhino
spec:
  containers:
  - command:
    - argoexec
    - resource
    - create
    [...]
    image: argoproj/argoexec:v3.2.6
    name: main
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    [...]
  dnsPolicy: ClusterFirst
  [...]
```

In Argo v2, the `resource` template Pod had both containers created, therefore the `PodSpecPatch` never failed:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sparkly-rhino
spec:
  containers:
  - command:
    - argoexec
    - resource
    - create
    [...]
    image: argoproj/argoexec:v2.12.5
    name: wait
    resources:
      limits:
        cpu: 50m
        memory: 32Mi
      requests:
        cpu: 50m
        memory: 32Mi
    [...]
  - command:
    - argoexec
    - resource
    - create
    [...]
    image: argoproj/argoexec:v2.12.5
    name: main
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    [...]
  dnsPolicy: ClusterFirst
  [...]
```

### What version of Argo Workflows are you running?

v3.2.6

## Questions

- Is this a bug or it "works as designed"?
  - If it's expected behaviour, what are the best practices to use `PodSpecPatch` to add `resources` to **both** the `main` and `wait` container to every template in the Workflow?
    
  I would prefer not to copy-paste the patch section to every other step that is not a `resource` template.

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
metadata:
  name: sparkly-rhino
spec:
  entrypoint: resource-create
  podSpecPatch: |
    containers:
      - name: wait
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "50m"
            memory: "32Mi"
      - name: main
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
  templates:
    - name: resource-create
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            labels:
              app: nginx
          spec:
            ports:
              - port: 80
                name: web
            clusterIP: None
            selector:
              app: nginx
```

### What Kubernetes provider are you using?

```
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.15-eks-9c63c4", GitCommit:"9c63c4037a56f9cad887ee76d55142abd4155179", GitTreeState:"clean", BuildDate:"2021-10-20T00:21:03Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

### What executor are you running?

Docker

### Logs

```bash
time="2022-02-01T19:17:05.489Z" level=info msg="Processing workflow" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.489Z" level=debug msg="Getting the template by name"
time="2022-02-01T19:17:05.489Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=redacted,name=sparkly-rhino)" depth=0 tmpl="*v1alpha1.WorkflowStep (resource-create)"
time="2022-02-01T19:17:05.489Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=redacted,name=sparkly-rhino)" depth=0 tmpl="*v1alpha1.WorkflowStep (resource-create)"
time="2022-02-01T19:17:05.489Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=redacted,name=sparkly-rhino)" depth=0 tmpl="*v1alpha1.WorkflowStep (resource-create)"
time="2022-02-01T19:17:05.489Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=redacted,name=sparkly-rhino)" depth=0 tmpl="*v1alpha1.WorkflowStep (resource-create)"
time="2022-02-01T19:17:05.489Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=redacted,name=sparkly-rhino)" depth=0 tmpl="*v1alpha1.WorkflowStep (resource-create)"
time="2022-02-01T19:17:05.489Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=redacted,name=sparkly-rhino)" depth=0 tmpl="*v1alpha1.WorkflowStep (resource-create)"
time="2022-02-01T19:17:05.489Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=redacted,name=sparkly-rhino)" depth=0 tmpl="*v1alpha1.WorkflowStep (resource-create)"
time="2022-02-01T19:17:05.494Z" level=info msg="Get configmaps 404"
time="2022-02-01T19:17:05.494Z" level=warning msg="Non-transient error: configmaps \"artifact-repositories\" not found"
time="2022-02-01T19:17:05.494Z" level=info msg="resolved artifact repository" artifactRepositoryRef=default-artifact-repository
time="2022-02-01T19:17:05.494Z" level=info msg="Updated phase  -> Running" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.494Z" level=debug msg="Evaluating node sparkly-rhino: template: *v1alpha1.WorkflowStep (resource-create), boundaryID: " namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.495Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=redacted,name=sparkly-rhino)" depth=0 tmpl="*v1alpha1.WorkflowStep (resource-create)"
time="2022-02-01T19:17:05.495Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=redacted,name=sparkly-rhino)" depth=0 tmpl="*v1alpha1.WorkflowStep (resource-create)"
time="2022-02-01T19:17:05.495Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=redacted,name=sparkly-rhino)" depth=0 tmpl="*v1alpha1.WorkflowStep (resource-create)"
time="2022-02-01T19:17:05.495Z" level=debug msg="Initializing node sparkly-rhino: template: *v1alpha1.WorkflowStep (resource-create), boundaryID: " namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.495Z" level=info msg="Pod node sparkly-rhino initialized Pending" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.495Z" level=debug namespace=redacted needLocation=true workflow=sparkly-rhino
time="2022-02-01T19:17:05.495Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"redacted\", Name:\"sparkly-rhino\", UID:\"15f9a220-e523-4923-9214-1c5a994f627c\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"473589948\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowRunning' Workflow Running"
time="2022-02-01T19:17:05.496Z" level=debug msg="Creating Pod: sparkly-rhino (sparkly-rhino)" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.499Z" level=debug msg="received config map kube-system/eks-certificates-controller update"
time="2022-02-01T19:17:05.506Z" level=info msg="Create events 201"
time="2022-02-01T19:17:05.522Z" level=info msg="Create pods 422"
time="2022-02-01T19:17:05.522Z" level=warning msg="Non-transient error: Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value"
time="2022-02-01T19:17:05.522Z" level=info msg="Failed to create pod sparkly-rhino (sparkly-rhino): Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.523Z" level=warning msg="Non-transient error: Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value"
time="2022-02-01T19:17:05.523Z" level=error msg="Mark error node" error="Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value" namespace=redacted nodeName=sparkly-rhino workflow=sparkly-rhino
time="2022-02-01T19:17:05.523Z" level=info msg="node sparkly-rhino phase Pending -> Error" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.523Z" level=info msg="node sparkly-rhino message: Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.523Z" level=info msg="node sparkly-rhino finished: 2022-02-01 19:17:05.523060324 +0000 UTC" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.523Z" level=error msg="error in entry template execution" error="Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.523Z" level=warning msg="Non-transient error: Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value"
time="2022-02-01T19:17:05.523Z" level=info msg="Updated phase Running -> Error" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.523Z" level=info msg="Updated message  -> error in entry template execution: Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.523Z" level=info msg="Marking workflow completed" namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.523Z" level=info msg="Checking daemoned children of " namespace=redacted workflow=sparkly-rhino
time="2022-02-01T19:17:05.523Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"redacted\", Name:\"sparkly-rhino\", UID:\"15f9a220-e523-4923-9214-1c5a994f627c\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"473589948\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowFailed' error in entry template execution: Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value"
time="2022-02-01T19:17:05.524Z" level=debug msg="Log changes patch: {\"metadata\":{\"annotations\":{\"workflows.argoproj.io/pod-name-format\":\"v1\"},\"labels\":{\"workflows.argoproj.io/completed\":\"true\",\"workflows.argoproj.io/phase\":\"Error\"}},\"status\":{\"artifactRepositoryRef\":{\"artifactRepository\":{\"archiveLogs\":true,\"s3\":{\"accessKeySecret\":{\"key\":\"accesskey\",\"name\":\"argo-secrets\"},\"bucket\":\"redacted-my-bucket-name\",\"endpoint\":\"s3.amazonaws.com\",\"insecure\":false,\"keyFormat\":\"artifacts/{{workflow.name}}/{{pod.name}}\",\"region\":\"eu-west-1\",\"secretKeySecret\":{\"key\":\"secretkey\",\"name\":\"argo-secrets\"}}},\"default\":true},\"conditions\":[{\"status\":\"True\",\"type\":\"Completed\"}],\"finishedAt\":\"2022-02-01T19:17:05Z\",\"message\":\"error in entry template execution: Pod \\\"sparkly-rhino\\\" is invalid: spec.containers[0].image: Required value\",\"nodes\":{\"sparkly-rhino\":{\"displayName\":\"sparkly-rhino\",\"finishedAt\":\"2022-02-01T19:17:05Z\",\"id\":\"sparkly-rhino\",\"message\":\"Pod \\\"sparkly-rhino\\\" is invalid: spec.containers[0].image: Required value\",\"name\":\"sparkly-rhino\",\"phase\":\"Error\",\"startedAt\":\"2022-02-01T19:17:05Z\",\"templateName\":\"resource-create\",\"templateScope\":\"local/sparkly-rhino\",\"type\":\"Pod\"}},\"phase\":\"Error\",\"startedAt\":\"2022-02-01T19:17:05Z\"}}"
time="2022-02-01T19:17:05.528Z" level=info msg="Create events 201"
time="2022-02-01T19:17:05.542Z" level=info msg="Update workflows 200"
time="2022-02-01T19:17:05.542Z" level=info msg="Workflow update successful" namespace=redacted phase=Error resourceVersion=473589952 workflow=sparkly-rhino
time="2022-02-01T19:17:05.542Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"redacted\", Name:\"sparkly-rhino\", UID:\"15f9a220-e523-4923-9214-1c5a994f627c\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"473589952\", FieldPath:\"\"}): type: 'Normal' reason: 'WorkflowNodeRunning' Running node sparkly-rhino: Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value"
time="2022-02-01T19:17:05.542Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Workflow\", Namespace:\"redacted\", Name:\"sparkly-rhino\", UID:\"15f9a220-e523-4923-9214-1c5a994f627c\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"473589952\", FieldPath:\"\"}): type: 'Warning' reason: 'WorkflowNodeError' Error node sparkly-rhino: Pod \"sparkly-rhino\" is invalid: spec.containers[0].image: Required value"
time="2022-02-01T19:17:05.549Z" level=info msg="Create events 201"
time="2022-02-01T19:17:05.554Z" level=info msg="Create events 201"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This behaviour seems correct to me. You don't need to use `podSpecPatch` to patch wait container resources. Instead, you can set this it in `configmaps/workflow-controller-configmap`.

**Comment by sarabala1979** [comment]
@dmegyesi This is expected behavior.  I  think `rescource  template` doesn't have `wait` container. Can you  remove  wait container resource request from podpatch?

**Comment by alexec** [comment]
I found fix for this:

```yaml
executor: |
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
```
