### ISSUE TITLE
artifact repo failed to load: parse first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by Hunter-Thompson** [argoproj/argo-workflows#7736]
## Summary

I expected to clone a repo using SSH.

```
→ time="2022-02-02T18:15:13.389Z" level=fatal msg="artifact repo failed to load: parse \"git@github.com:valorl/repository-with-relative-submodule.git\": first path segment in URL cannot contain colon"
```

What version is it broken in?

v3.2.6

What version was it working in?

v3.0.7

## Diagnostics

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: clone-relative-submodule-asdasd
spec:
  entrypoint: clone
  templates:
  - name: clone
    inputs:
      artifacts:
      - name: repo
        path: /repo
        git:
          repo: git@github.com:valorl/repository-with-relative-submodule.git
          revision: main
          sshPrivateKeySecret:
            name: github-ssh-key
            key: ssh-privatekey
          insecureIgnoreHostKey: true
    script:
      image: alpine/git:latest
      command: [sh]
      workingDir: /repo
      source: |
        git status
```
```
time="2022-02-02T18:15:13.389Z" level=fatal msg="artifact repo failed to load: parse \"git@github.com:valorl/repository-with-relative-submodule.git\": first path segment in URL cannot contain colon"
```
What Kubernetes provider are you using?

AWS EKS, v1.18

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

K8SAPI

N/A cause artifact failed to clone.

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.
