### ISSUE TITLE
Workflow that calls a workflow template POSTed to the API returns "workflow body not specified"

### ISSUE THREAD

**Issue by chriswilley** [argoproj/argo-workflows#7737]
## Summary

What happened/what you expected to happen?
Calling `https://<host>/api/v1/workflows/<namespace>` with a workflow file that uses `templateRef` to call a workflow template fails with "workflow body not specified". Submitting the same workflow through the CLI works as expected. I am also able to submit workflow templates using the `/submit` endpoint successfully.

What version of Argo Workflows are you running?
3.1.12

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

Workflow template being referenced:
```yaml
# hello-workflow-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: name
        value: "argo"
  templates:
    - name: main
      steps:
        - - name: a
            template: whalesay
            arguments:
              parameters:
                - name: name
                  value: "{{workflow.parameters.name}}"
    - name: whalesay
      inputs:
        parameters:
          - name: name
      container:
        image: docker/whalesay:latest
        command: ["cowsay"]
        args: ["hello {{inputs.parameters.name}}"]
```

Workflow calling the template:

```yaml
# hello-workflow-from-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-wf-template-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: name
        value: "argo"
  templates:
  - name: whalesay
    steps:
      - - name: do-whalesay
          arguments:
            parameters:
              - name: name
                value: "{{workflow.parameters.name}}"
          templateRef:
            name: hello-argo
            template: main
```

Python code used to call the API:

```python
import json
import os
import requests
import yaml

url = 'https://HOSTNAME/api/v1/workflows/NAMESPACE'
headers = {'Authorization': os.environ['ARGO_TOKEN']}
with open('hello-workflow-from-template.yaml', 'r') as f:
    wf = yaml.safe_load(f)
data = json.dumps(wf)
resp = requests.post(url, data, headers=headers)
resp.content
>>> b'{"code":2,"message":"workflow body not specified"}'
```

Using the CLI

```bash
$ argo submit hello-workflow-from-template.yaml --watch
Name:                hello-world-wf-template-rxrlv
Namespace:           default
ServiceAccount:      argo-runner
Status:              Succeeded
Conditions:          
 PodRunning          False
 Completed           True
Created:             Wed Feb 02 15:01:08 -0500 (10 seconds ago)
Started:             Wed Feb 02 15:01:08 -0500 (10 seconds ago)
Finished:            Wed Feb 02 15:01:18 -0500 (now)
Duration:            10 seconds
Progress:            1/1
ResourcesDuration:   3s*(100Mi memory),3s*(1 cpu)
Parameters:          
  name:              chris

STEP                              TEMPLATE         PODNAME                                  DURATION  MESSAGE
 ✔ hello-world-wf-template-rxrlv  whalesay                                                              
 └───✔ do-whalesay                hello-argo/main                                                       
     └───✔ a                      whalesay         hello-world-wf-template-rxrlv-847164517  4s          
```

What Kubernetes provider are you using?
EKS

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
PNS

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
