### ISSUE TITLE
bug(argo-ui): e.TemplateRef is undefined when using inline template

### ISSUE THREAD

**Issue by Hunter-Thompson** [argoproj/argo-workflows#7749]
### What happened/what you expected to happen?

When clicking on my workflow name on the argo dashboard, or clicking on the logs button. The UI crashes.

This workflow uses an inline template.

### What version of Argo Workflows are you running?

v3.2.6

## Diagnostics

[Example Inline Template Workflow taken from argo github](https://github.com/argoproj/argo-workflows/blob/master/examples/dag-inline-workflow.yaml)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-inline-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      This example demonstrates running a DAG with inline templates.
    workflows.argoproj.io/version: ">= 3.2.0"
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: a
            inline:
              container:
                image: argoproj/argosay:v2
```

Crash:
```
t.getTemplateNameFromNode@https://..com/argo/main.50457fd4714d6e3e36c4.js:49:148403
t.WorkflowLogsViewer/H<@https://..com/argo/main.50457fd4714d6e3e36c4.js:225:76467
t.WorkflowLogsViewer@https://..com/argo/main.50457fd4714d6e3e36c4.js:225:76411
$i@https://argoworkflow..com/argo/main.50457fd4714d6e3e36c4.js:516:52993
Io@https://argoworkflow..com/argo/main.50457fd4714d6e3e36c4.js:516:65197
qa@https://argoworkflow..com/argo/main.50457fd4714d6e3e36c4.js:516:90554
Ga@https://argoworkflow..com/argo/main.50457fd4714d6e3e36c4.js:516:90936
Os@https://argoworkflow..com/argo/main.50457fd4714d6e3e36c4.js:516:97823
ks@https://argoworkflow..com/argo/main.50457fd4714d6e3e36c4.js:516:97205
Rs@https://argoworkflow..com/argo/main.50457fd4714d6e3e36c4.js:516:98578
Tn@https://argoworkflow..com/argo/main.50457fd4714d6e3e36c4.js:516:30571
```

### Possible culprit:

https://github.com/argoproj/argo-workflows/blob/93c9c613d4759865eeacb5aedabe3015bf31b8bd/workflow/common/util.go#L371-L373

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
