### ISSUE TITLE
Incompatibility with PSPs using read-only allowed host paths

### ISSUE THREAD

**Issue by louisblin** [argoproj/argo-workflows#7755]
## Summary

Argo Workflows seems to be incompatible with Pod Security Policies (PSPs) specifying read-only allowed host paths. [As mentioned in this thread](https://github.com/argoproj/argo-workflows/pull/1214#discussion_r789865942), the `init` / `wait` containers surrounding a workflow container mount the same volumes as the main container, but without respecting their read/write mode. For environments using PSPs with read-only allowed host paths, it becomes impossible to run workflows that use volume mounts (as sidecar containers will violate the PSP).

[Looking at the code mentioned above](https://github.com/argoproj/argo-workflows/blob/v3.3.0-rc2/workflow/controller/workflowpod.go#L1027-L1028), the author claims that mounts need to be read/write to allow overlapping mount paths. However, the `main` container will already need to mount paths in read/write mode if they overlap, so I don't see why the sidecar containers needs to modify this setting. Am I missing something or could we simply remove this override? 

**Argo Workflows install**: version v3.2.6, on a vanilla k8s cluster with the K8SAPI executor.

## Diagnostics

To replicate the issue, here's a sample PSP with a read-only allowed host path:
```yaml
$ kubectl apply -f - <<EOF
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: readonly-hostpaths
spec:
  allowedHostPaths:
  - pathPrefix: /etc/ssl/certs/
    readOnly: true
  volumes:
  - '*'

  runAsUser:
    rule: RunAsAny
  runAsGroup:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
EOF
```

And a workflow that will violate it:
```shell
$ argo submit - <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    script:
      image: alpine
      source: |
        ls -lha /etc/ssl/certs/
      volumeMounts:
      - mountPath: /etc/ssl/certs/
        name: ssl-certs
        readOnly: true
    volumes:
    - hostPath:
        path: /etc/ssl/certs/
      name: ssl-certs
EOF
```

After inspecting the workflow in the UI, you get the following message, which indicates that the sidecar container is trying to mount the `ssl-certs` volume in write mode.
```
pods "hello-world-bq8pl" is forbidden: unable to validate against any pod security policy: [spec.containers[0].volumeMounts[0].readOnly: Invalid value: false: must be read-only]
```

This can be confirmed by disabling the PSP and inspecting the pod spec that is created.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
