### ISSUE TITLE
Make POD_NAMES configurable via configmap instead of environment variable

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#7762]
The [v3.3 blog](https://blog.argoproj.io/whats-new-in-argo-workflows-v3-3-dd051d2f1c7) mentions to

> Start your controller with POD_NAMES=v2

It was a little unclear where to do this.

At first, I tried running the controller container with a "-h" flag, but did not see any mention of POD_NAMES.

My next thought was an environment variable which @crenshaw-dev pointed out
> looks like it bypasses cobra and uses the env var directly os.Getenv("POD_NAMES")

I got it working with a kustomize overlay (and it works great!), but it would be more accessible if there was a configmap option to control this.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
      - name: workflow-controller
        env:
        - name: POD_NAMES
          value: v2
```
