### ISSUE TITLE
Emissary no command error

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#7780]
When using emissary executor, if command is not passed in template or configmap, it will fail. Improve the error message by indicating which step & container failed.

@alexec 
[Alex Collins](https://app.slack.com/team/ULZF02TME)  [3 days ago](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1644004316633359?thread_ts=1644000559.222279&cid=C01QW9QSSSK)
> can someone raise an bug to improve the diagnostics?

@crenshaw-dev
[Michael Crenshaw](https://app.slack.com/team/U02J8AUKJAC)  [3 days ago](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1644001742209989?thread_ts=1644000559.222279&cid=C01QW9QSSSK)
> I wish the error message would also include the name of the container which is missing a command.

> when using the emissary executor you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary

```yaml
templates:
  container:
    - name: curl
      image: curlimages/curl:latest
      args: ["https://google.com"]
```
