### ISSUE TITLE
Inconsistency of parsing the realtime metric value.

### ISSUE THREAD

**Issue by olegmayko** [argoproj/argo-workflows#7819]
## Summary
During the definition of real time metric in a workflow, the value of metric is not parsed correctly when defined 
using valid go template syntax
What happened/what you expected to happen?
if value in real time metric is defined like this ` {{ workflow.duration }}`. The next error shown in the log

 However it works correctly like this `{{workflow.duration}}`  

I'd expect that it works correctly if either valid go template syntax is applied. 
It's minor issue. The custom parsing of the value doesn't trim suffix and leading white spaces. See [here](https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/operator.go#L3209).
If you think the  fix is good idea, i can submit a PR.

What executor are you using? PNS/Emissary
N/A

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
# For complete documentation please see:
#
#   docs/metrics.md
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: steps
  metrics:
    prometheus:
      - name: duration_gauge
        labels:
          - key: name
            value: workflow
        help: "Duration gauge by name"
        gauge:
          realtime: true                  # This metric will be emitted in real time. For more info see: docs/metrics.md
          value: "{{ workflow.duration }}"  # Use {{workflow.duration}} in workflow-level and {{duration}} in template-level
```

What executor are you running? PNS/Emissary

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
 ' workflow.duration ' is not available as a real time metric
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
