### ISSUE TITLE
make container template resources configurable thru parameters

### ISSUE THREAD

**Issue by trondhindenes** [argoproj/argo-workflows#7836]
# Summary

I'm trying to dynamically send container resources using parameters, so that I can submit a job using the same container template with different resources.

Pseudocode:
```yaml
  - container:
      args:
      - "hello"
      image: hello
      resources:
        requests:
          memory: '{{inputs.parameters.mem_requests}}'
```

# Use Cases

We'd like to dynamically set container resources

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
