### ISSUE TITLE
workflow-controller deployment liveness probe fails

### ISSUE THREAD

**Issue by TakuKaneda** [argoproj/argo-workflows#7845]
## Summary

The workflow-controller deployment continues to restart due to CrashLoopBackOff.

Our environment:

- Argo workflow: `v3.2.7`
- GKE: `v1.19.15-gke.1801`

## Diagnostics

We have three GKE envs, `dev/stg/prd` and  try to update Argo workflow from v2.10.12 to v3.2.7.
When we deployed the v3 to `dev`, it works fine. However, after applying to `stg`, we encounter this issue.

> note: We notice that the amount of workflows are much higher in `stg` compared to `dev`.

Here is the manifest we use:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: argo-workflow
spec:
  selector:
    matchLabels:
      app: workflow-controller
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        # some annotattions
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        # specify the version
        - quay.io/argoproj/argoexec:v3.2.7
        command:
        - workflow-controller
        env:
        - name: LEADER_ELECTION_IDENTITY
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        # specify the version
        image: quay.io/argoproj/workflow-controller:v3.2.7
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6060
          initialDelaySeconds: 90
          periodSeconds: 60
          timeoutSeconds: 30
        name: workflow-controller
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 6060
        resources:
          limits:
            cpu: 6
            memory: 16G
          requests:
            cpu: 3
            memory: 16G
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: argo
```
### What we tried

We found that the controller used up memory thus we increase it to 16G->32G. But the problem remains.
```bash
$ kubectl top pod
NAME                                   CPU(cores)   MEMORY(bytes)
workflow-controller-6484b5d48b-brltd   99m          9390Mi
workflow-controller-6484b5d48b-wxsvb   1004m        14439Mi
```

our patch:
```yaml
- op: add	- op: add
  path: /spec/template/spec/containers/0/resources	  path: /spec/template/spec/containers/0/resources
  value: {	  value: {
    "limits": {	    "limits": {
      "cpu": 6,	      "cpu": 6,
      "memory": "16G"	      "memory": "32G"
    },	    },
    "requests": {	    "requests": {
      "cpu": 3,	      "cpu": 3,
      "memory": "16G"	      "memory": "32G"
    }	    }
  }
```

#### 1. `healthz/` path repsponds 500

The healthz/ path responds 500 after 60s (seems timeout).

```bash
$ kubectl describe pod workflow-controller-6484b5d48b-brltd                                                                                                             
....
Status:       Running
IP:           10.40.12.164
IPs:
  IP:           10.40.12.164
Controlled By:  ReplicaSet/workflow-controller-6484b5d48b
Containers:
  workflow-controller:
    Container ID:  docker://aef63e488ef6d3cbfd188efa74c40b88ed4b52b71d899bcf69e33ab4a291a718
    Image:         quay.io/argoproj/workflow-controller:v3.2.7
    Image ID:      docker-pullable://quay.io/argoproj/workflow-controller@sha256:0640999a1be3a1817e6973fc0af7b669603aeca538be4b14767290437dafaebe
    Ports:         9090/TCP, 6060/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      workflow-controller
    Args:
      --configmap
      workflow-controller-configmap
      --executor-image
      quay.io/argoproj/argoexec:v3.2.7
    State:          Running
      Started:      Wed, 09 Feb 2022 17:51:36 +0900
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 09 Feb 2022 17:46:36 +0900
      Finished:     Wed, 09 Feb 2022 17:51:35 +0900
    Ready:          True
    Restart Count:  11
    Limits:
      cpu:     6
      memory:  32G
    Requests:
      cpu:     3
      memory:  32G
    Liveness:  http-get http://:6060/healthz delay=90s timeout=30s period=60s #success=1 #failure=3
    Environment:
      LEADER_ELECTION_IDENTITY:  workflow-controller-6484b5d48b-brltd (v1:metadata.name)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from argo-token-sj45m (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  argo-token-sj45m:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  argo-token-sj45m
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  56m                   default-scheduler  Successfully assigned ks-argo-workflow/workflow-controller-6484b5d48b-brltd to gke-backyard-n1-highmem-32-pr-1133-15f6cbca-lgg0
  Normal   Pulled     41m (x4 over 56m)     kubelet            Container image "quay.io/argoproj/workflow-controller:v3.2.7" already present on machine
  Normal   Created    41m (x4 over 56m)     kubelet            Created container workflow-controller
  Normal   Started    41m (x4 over 56m)     kubelet            Started container workflow-controller
  Normal   Killing    36m (x4 over 51m)     kubelet            Container workflow-controller failed liveness probe, will be restarted
  Warning  Unhealthy  3m11s (x31 over 53m)  kubelet            Liveness probe failed: Get "http://10.40.12.164:6060/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

We tried to run curl from a pod and it actually failed.
```bash
$  kubectl run -it curl --image=curlimages/curl --rm --restart=Never -- /bin/sh                                                                                      
If you don't see a command prompt, try pressing enter.
$ curl -i http://10.40.12.164:6060/healthz
HTTP/1.1 500 Internal Server Error
Date: Wed, 09 Feb 2022 09:09:45 GMT
Content-Length: 132
Content-Type: text/plain; charset=utf-8

the server was unable to return a response in the time allotted, but may still be processing the request (get workflows.argoproj.io)/ 
```

However in `dev` env we scucceded.
```
# in dev env
$ kubectl describe pod workflow-controller-567f649df4-qr6qp                                                                                                               
....
Controlled By:  ReplicaSet/workflow-controller-567f649df4
Containers:
  workflow-controller:
    Container ID:  docker://5830605d87634b7ae6d4c31fdcd75bd46d255dd73410ed37794b3e51c4ddd411
    Image:         quay.io/argoproj/workflow-controller:v3.2.7
    Image ID:      docker-pullable://quay.io/argoproj/workflow-controller@sha256:0640999a1be3a1817e6973fc0af7b669603aeca538be4b14767290437dafaebe
    Ports:         9090/TCP, 6060/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      workflow-controller
    Args:
      --configmap
      workflow-controller-configmap
      --executor-image
      quay.io/argoproj/argoexec:v3.2.7
    State:          Running
      Started:      Wed, 09 Feb 2022 16:55:05 +0900
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     6
      memory:  32G
    Requests:
      cpu:     3
      memory:  32G
    Liveness:  http-get http://:6060/healthz delay=90s timeout=30s period=60s #success=1 #failure=3
    Environment:
      LEADER_ELECTION_IDENTITY:  workflow-controller-567f649df4-qr6qp (v1:metadata.name)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from argo-token-6wkcv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  argo-token-6wkcv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  argo-token-6wkcv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  13m   default-scheduler  Successfully assigned ks-argo-workflow/workflow-controller-567f649df4-qr6qp to gke-backyard-n1-highmem-8-pr-1133-d3fe77d1-5yej
  Normal  Pulling    13m   kubelet            Pulling image "quay.io/argoproj/workflow-controller:v3.2.7"
  Normal  Pulled     13m   kubelet            Successfully pulled image "quay.io/argoproj/workflow-controller:v3.2.7" in 5.34194049s
  Normal  Created    13m   kubelet            Created container workflow-controller
  Normal  Started    13m   kubelet            Started container workflow-controller

$ kubectl run -it curl --image=curlimages/curl --rm --restart=Never -- /bin/sh                                                               
If you don't see a command prompt, try pressing enter.
/ $ curl http://10.40.0.123:6060/healthz
/ $ curl -i http://10.40.0.123:6060/healthz
HTTP/1.1 200 OK
Date: Wed, 09 Feb 2022 09:01:58 GMT
Content-Length: 2
Content-Type: text/plain; charset=utf-8

ok/ $
```

#### 2. subumitted workflows appear to be working fine

From argo-server UI and logs, the workflow it self seems workling well in `stg`.

```bash
$  kubectl logs workflow-controller-6484b5d48b-brltd
# some of logs (with masking)
time="2022-02-10T03:13:06.950Z" level=info msg="Queueing Succeeded workflow xxxxxx for delete in 20h59m6s"
time="2022-02-10T03:13:06.967Z" level=info msg="Get leases 200"
time="2022-02-10T03:13:06.973Z" level=info msg="Queueing Succeeded workflow yyyyyyy for delete in 46h47m14s"
time="2022-02-10T03:13:06.977Z" level=info msg="Queueing Succeeded workflow zzzzzzz for delete in 99h47m15s"
time="2022-02-10T03:13:06.980Z" level=info msg="Update leases 200"
```

### Ref

Here are some issues that may be relevant to this case (at least I found)
- https://github.com/argoproj/argo-workflows/issues/6351
- https://github.com/argoproj/argo-workflows/issues/6002
- https://github.com/argoproj/argo-workflows/issues/5525

stackoverflow
- https://stackoverflow.com/questions/67768215/argo-workflow-stuck-in-pending-due-to-liveness-probe-fail

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
