### ISSUE TITLE
Resources plugin

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7860]
# Summary

Today - the resources template has two downsides:

* It is expensive as it requires one pod per resource.
* It only supports a single resource.
* Resource manifests must come from the workflow.
* Resources are strings, not structured YAML

It would also be an opportunity to complete this:

* #7725
* #7179 
* #7143
* #6862

I propose a new plugin:

```yaml
plugins:
  resources:
    -  manifest:
          value: 
          valueFrom: 
            url: ...
       wait:
          for: condition=Ready
          status:
            phase: Running
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
