### ISSUE TITLE
A memoized steps hit, the following nodes not displayed in the UI

### ISSUE THREAD

**Issue by zjgemi** [argoproj/argo-workflows#7873]
## Summary

When a memoized step with steps template is hit by a ConfigMap record, the nodes following this step are not displayed in the UI (despite they run expectedly). The behavior might result from that the memoized step has no children.

## Diagnostics

The smallest workflow that reproduces the bug looks like

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: memoized-bug-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: hello-steps
        template: memoized
    - - name: whatever
        template: hello

  - name: memoized
    outputs:
      parameters:
      - name: msg
        valueFrom:
          parameter: "{{steps.hello-step.outputs.result}}"
    steps:
    - - name: hello-step
        template: hello
    memoize:
      key: "memoized-bug-steps-0"
      cache:
        configMap:
          name: my-config

  - name: hello
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo Hello"]
```

When the workflow is submitted for the first time, the step `hello-steps` is stored in the ConfigMap. And in the UI, the workflow looks like
<img width="253" alt="workflow-1" src="https://user-images.githubusercontent.com/27884723/153741081-b1d2eb53-736c-405a-a52c-f47261e7b397.png">
Everything is OK. But when the workflow is submitted for the second time, the step `hello-steps` is loaded from the ConfigMap, the following step `whatever` is not displayed in the UI
<img width="130" alt="workflow-2" src="https://user-images.githubusercontent.com/27884723/153741118-aacdbd73-9c69-4d2e-a98b-67bbac828a27.png">

In the detail of the second workflow
```bash
$ argo get memoized-bug-nmvgq -n argo -o yaml
...
    memoized-bug-nmvgq-667942788:
      boundaryID: memoized-bug-nmvgq
      displayName: hello-steps
      finishedAt: "2022-02-13T05:32:52Z"
      id: memoized-bug-nmvgq-667942788
      memoizationStatus:
        cacheName: my-config
        hit: true
        key: memoized-bug-steps-0
      name: memoized-bug-nmvgq[0].hello-steps
      outputs:
        parameters:
        - name: msg
          value: Hello
      phase: Succeeded
      startedAt: "2022-02-13T05:32:52Z"
      templateName: memoized
      templateScope: local/memoized-bug-nmvgq
      type: Steps
...
    memoized-bug-nmvgq-2677016171:
      boundaryID: memoized-bug-nmvgq
      displayName: whatever
      finishedAt: "2022-02-13T05:33:05Z"
      hostNodeName: minikube
      id: memoized-bug-nmvgq-2677016171
      name: memoized-bug-nmvgq[1].whatever
      outputs:
        artifacts:
        - name: main-logs
          s3:
            key: memoized-bug-nmvgq/memoized-bug-nmvgq-2677016171/main.log
        exitCode: "0"
      phase: Succeeded
      progress: 1/1
      resourcesDuration:
        cpu: 4
        memory: 2
      startedAt: "2022-02-13T05:32:52Z"
      templateName: hello
      templateScope: local/memoized-bug-nmvgq
      type: Pod
```
The step `hello-steps` does not have children which may cause the step `whatever` not displayed in the UI, despite the step `whatever` succeeded.

---
Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
