### ISSUE TITLE
Limited character support in workflow.creationTimestamp.<STRFTIMECHAR>

### ISSUE THREAD

**Issue by cjvirtucio87** [argoproj/argo-workflows#7893]
## Summary

The [docs](https://argoproj.github.io/argo-workflows/variables/) mention that we can
reference `workflow.creationTimestamp.<STRFTIMECHAR>` to get the value of a
[strftime format character](http://strftime.org/). However, it seems only a few characters
are supported. Using `workflow.creationTimestamp.d` and `workflow.creationTimestamp.Y`
works for getting the day and year, but `workflow.creationTimestamp.U` isn't formatted to
the week number of the year.

## Diagnostics

Our argo version:

```txt
argo: v2.12.7
  BuildDate: 2021-02-01T22:08:27Z
  GitCommit: 5f5150730c644865a5867bf017100732f55811dd
  GitTreeState: clean
  GitTag: v2.12.7
  GoVersion: go1.13
  Compiler: gc
  Platform: linux/amd64
```

Our template:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: strftime-test
  labels:
    test: strftime-test
spec:
  entrypoint: entrypoint
  arguments:
    parameters:
    - name: day
      value: "{{ workflow.creationTimestamp.d }}"
    - name: year
      value: "{{ workflow.creationTimestamp.Y }}"
    - name: week_in_year
      value: "{{ workflow.creationTimestamp.U }}"
  metadata:
    generateName: strftime-test-
  serviceAccountName: "argo-workflow-controller"
  templates:
  - name: entrypoint
    steps:
    - - name: check-timestamp-step
        template: check-timestamp
        arguments:
          parameters:
          - name: day
            value: "{{ workflow.parameters.day }}"
          - name: year
            value: "{{ workflow.parameters.year }}"
          - name: week_in_year
            value: "{{ workflow.parameters.week_in_year }}"

  - name: check-timestamp
    inputs:
      parameters:
      - name: day
      - name: year
      - name: week_in_year
    container:
      image: docker-registry.pd.labs.mitre.org/asias-etl/docker-base-rocky8:latest
      command:
      - '/bin/bash'
      - '-c'
      args:
      - |
        echo "day: {{ inputs.parameters.day }}"
        echo "year: {{ inputs.parameters.year }}"
        echo "week_in_year: {{ inputs.parameters.week_in_year }}"
      resources:
        limits:
          memory: 100M
        requests:
          cpu: 100m
          memory: 100M
```

When a workflow is submitted from the above template, we
expect the workflow log to have:

```txt
day: 16
year: 2022
week_in_year: 07
```

Instead, we get:

```txt
day: 16
year: 2022
week_in_year: {{ workflow.creationTimestamp.U }}
```

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think you might be able to use `{{=sprig.date(workflow.creationTimestamp, "2006")}}`

You'll need to dive into the docs to get the right expression:

https://argoproj.github.io/argo-workflows/variables/#expression

**Comment by gai6948** [comment]
The documentation is not very helpful when it comes to template variables, especially use of `sprig`, can we have more practical examples of how they work?

**Comment by lucastheisen** [comment]
@alexec , there is definitely a shortcoming in documentation on the sprig support. It primarily links to the sprig doc's which use pipeline syntax, but the expression parser in argo uses function syntax.  To that end, its not immediately clear whether the values piped in would be the first or last and whether you pipe calls together or nest functions.  Even [your comment here](https://github.com/argoproj/argo-workflows/issues/7893#issuecomment-1041860365) disagrees with the [documented example using sprig](https://github.com/argoproj/argo-workflows/blob/master/examples/expression-tag-template-workflow.yaml#L35).  Experimentally, i got my answers:

```yaml
  templates:
  - name: entrypoint
    container:
      image: rockylinux/rockylinux:8
      command:
      - '/bin/bash'
      - '-c'
      args:
      - |
        echo "---"
        echo "creation timestamp: {{workflow.creationTimestamp}}"
        echo "format_first:       {{=sprig.date('2006-01-02 03:04:05 -0700', sprig.toDate('2006-01-02T03:04:05Z', '2021-01-01T00:00:00Z'))}}"
        echo "format_last:        {{=sprig.date(sprig.toDate('2006-01-02T03:04:05Z', '2021-01-01T00:00:00Z'), '2006-01-02 03:04:05 -0700')}}"
        echo "format_first_pipe:  {{=sprig.toDate('2006-01-02T03:04:05Z', '2021-01-01T00:00:00Z') | sprig.date('2006-01-02 03:04:05 -0700')}}"
        echo "format_last_pipe:   {{=sprig.date('2006-01-02 03:04:05 -0700') | sprig.toDate('2006-01-02T03:04:05Z', '2021-01-01T00:00:00Z')}}"

```

I get:

```console
cluster-argo-integration-hsrsd: creation timestamp: 2022-03-05T18:17:00Z
cluster-argo-integration-hsrsd: format_first:       2021-01-01 12:00:00 +0000
cluster-argo-integration-hsrsd: format_last:        {{=sprig.date(sprig.toDate('2006-01-02T03:04:05Z', '2021-01-01T00:00:00Z'), '2006-01-02 03:04:05 -0700')}}
cluster-argo-integration-hsrsd: format_first_pipe:  {{=sprig.toDate('2006-01-02T03:04:05Z', '2021-01-01T00:00:00Z') | sprig.date('2006-01-02 03:04:05 -0700')}}
cluster-argo-integration-hsrsd: format_last_pipe:   {{=sprig.date('2006-01-02 03:04:05 -0700') | sprig.toDate('2006-01-02T03:04:05Z', '2021-01-01T00:00:00Z')}}
```

So, to answer my own confusion use nesting function call syntax, and the _piped_ in value from the sprig syntax is the _last_ argument in the function call syntax.  Also definitely worth remembering errors in parsing are essentially disregarded.
