### ISSUE TITLE
Get command-line/environment information/data from within a Workflow Template

### ISSUE THREAD

**Issue by alexglatt** [argoproj/argo-workflows#7894]
## Summary
In my Workflow Template, I want to include a parameter that, whenever the Workflow that uses this Workflow Template does not specify a value for that parameter, pulls the information from the command line where the Workflow is submitted on.
Specifically, I want to execute a command line command and need the result of that command inside the Workflow Template and, therefore, in the Workflow that uses the Workflow Template (More details in the use case).
However, I can not find a way to implement that.

I found the possibility to pull secrets from the environment via:

```yaml
env:
- name: SECRET
  valueFrom:
    secretKeyRef:
      name: secret-name
      key: secret-token
```

This way works and successfully provides a variable with information from the environment, but it only pulls secrets.
I can't find a way to pull other information into the Workflow Template.
Possibilities, like:

```yaml
env:
- name: VARIABLENAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
```
do not work, since it only pulls information about the pod that is created by the Workflow.

Thank you in advance for your help.

## Use Case
I want to execute a kubectl command on the command line from within the Workflow Template and then use the result as parameter value.
The exact kubectl command would be: kubectl get ...
For example, if it was `kubectl get pods -o custom-columns=:metadata.name --no-headers` I would want the resulting names of all pods, that the command line returns, as a parameter value in my Workflow Template, freshly pulled whenever it is used by an Argo Workflow.
