### ISSUE TITLE
metadata.generateName or metadata.name should allow variables in their definition

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#7900]
if I try some variable within these values they complain about { is not a valid alphanumeric

**Comment by terrytangyuan** [comment]
I don’t think you can substitute these.

**Comment by tooptoop4** [comment]
@alexec does your example work in released version or is it a proposal?

**Comment by alexec** [comment]
It is proposal.

**Comment by tooptoop4** [comment]
any workarounds? as workflow that runs often is getting name collisions so it can't be archived

**Comment by raven-wing** [comment]
there is workaround:
```
            - src:
                dependencyName: test-dep
                dataTemplate: "{{ .Input.body.pull_request.number }}-{{ .Input.body.pull_request.head.sha | substr 0 7 }}"
              dest: metadata.name
```


from [here](https://github.com/argoproj/argo-events/blob/master/examples/sensors/github.yaml)
