### ISSUE TITLE
Tighten up agent pod spec

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7914]
The agent pod spec allows the agent to do things we should fix:

```yaml
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
