### ISSUE TITLE
Input and output artifacts support artifactRepositoryRef

### ISSUE THREAD

**Issue by RifeWang** [argoproj/argo-workflows#7917]
# Summary And Use Cases

We have multiple artifact repositories and have them configured in the configMap, like:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
data:
  art-s3: |
    s3:
      endpoint: ...
      bucket: ...
      accessKeySecret: ...
      secretKeySecret: ...

  art-minio: |
    minio:
      endpoint: ...
      bucket: ...
      accessKeySecret: ...
      secretKeySecret: ...
```

And then we can reference them in a key-only way in a same workflow ：
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-
spec:
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: art-s3

  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: step1
        template: step1
    - - name: step2
        template: step2

  - name: step1
    container: ...
    outputs:
      artifacts:
        - name: step1-output
          path: /tmp/s1.txt 
          s3:   
            key: ...   # key only


  - name: step2
    container: ...
    outputs:
      artifacts:
        - name: step2-output
          artifactRepositoryRef:  # we want to use another artifact repository in a key-only way
            configMap: artifact-repositories
            key: minio
          minio:
            key: ... 
```

Since `workflow.spec.artifactRepositoryRef` can only refer to one artifact repository, it is not very convenient and concise when we need to use multiple artifact repositories.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
