### ISSUE TITLE
Unable to set parallelism for DAG at template level from another DAG

### ISSUE THREAD

**Issue by louisnow** [argoproj/argo-workflows#7936]
### What happened?
I can't set the parallelism value for a part of a DAG from another DAG. I've attached the workflow. 

https://user-images.githubusercontent.com/6024271/154862771-e4426396-490f-449e-9435-aafbab0aed63.mov

### What you expected to happen?
I expected to be able to control the parallelism factor. If I set the root template's parallelism, it works.

#### Unrelated question: 
When it skips a loop, it produces three skipped nodes`[0, -1, -2,]` instead of one, it consistently does this irrespective of semaphores or parallelism. I've ignored it but maybe there's some underlying bug hidden there? You can see the three skipped nodes in the video in grey.
```
  templates:
    - name: main
      parallelism: 2
```

https://user-images.githubusercontent.com/6024271/154862750-c4b4464d-905a-4426-887d-3e926fe1bac3.mov

What executor are you using? PNS/Emissary
Emissary

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

I tried placing the parallelism value almost everywhere and every combination in the workflow but it didn't help unless I place it for the root template. In the template below, I've put the value in all the place that I've individually tried and it failed for all.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: retry
spec: 
  entrypoint: main
  
  templates:
    - name: main
      dag:
        tasks:
          - name: say
            template: whalesay-template
            arguments:
              parameters:
                - name: message
                  value: "5"

          - name: say-minus
            template: whalesay-template
            arguments:
              parameters:
                - name: message
                  value: "-1"

          - name: param-say
            parallelism: 2
            when: "{{tasks.say.outputs.parameters.output}} != -1"
            withSequence:
              count: "{{tasks.say.outputs.parameters.output}}"
            dependencies:
              - say
            template: dag-task
            arguments:
              parameters:
                - name: message
                  value: "{{tasks.say.outputs.parameters.output}}"

          - name: param-say-minus
            parallelism: 2
            when: "{{tasks.say-minus.outputs.parameters.output}} != -1"
            withSequence:
              count: "{{tasks.say-minus.outputs.parameters.output}}"
            dependencies:
              - say-minus
            template: dag-task
            arguments:
              parameters:
                - name: message
                  value: "{{tasks.say-minus.outputs.parameters.output}}"

    - name: dag-task
      parallelism: 3
      inputs:
        parameters:
          - name: message
      dag:
        tasks:
          - name: say
            parallelism: 3
            template: whalesay-template
            arguments:
              parameters:
                - name: message
                  value: "{{inputs.parameters.message}}"

          

    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      outputs:
        parameters:
          - name: output
            value: "{{inputs.parameters.message}}"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]

    - name: exit-dag
      dag: 
        tasks:
          - name: exit-msg
            template: exit-msg

    - name: exit-msg
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["goodbye world"]
```

What executor are you running? PNS/Emissary
Emissary
```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
