### ISSUE TITLE
workflow failed when `withSequence` is used and `when` evaluated to false

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#7940]
## Summary

When trying to use `when` condition in combination with `withSequence`,
if `when` is evaluated to false, the workflow fails with error
`failed to resolve {{tasks.get-items.outputs.artifacts.items}}`

Expect:
We expect the step/task to skip when `when` evaluated to false and workflow succeed

Version:
Lastest Master [ad31267](https://github.com/argoproj/argo-workflows/commit/ad312674a0bbe617d199f4497e79b3e0fb6d64a8)
Emissary executor

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: handle-large-output-results-
spec:
  entrypoint: handle-large-output-results
  templates:
    - name: handle-large-output-results
      dag:
        tasks:
        - name: get-items
          template: get-items
        - name: sequence-param
          template: echo
          dependencies: [get-items]
          when: 1 != 1
          arguments:
            parameters:
              - name: index
                value: "{{item}}"
            artifacts:
              - name: items
                from: "{{tasks.get-items.outputs.artifacts.items}}"
          withSequence:
            count: "{{tasks.get-items.outputs.parameters.count}}"
    - name: get-items
      container:
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        # This small array is just for an example. Make sure the count matches the actual size of
        # your JSON array.
        args: ["echo '[\"a\", \"b\", \"c\"]' > /tmp/items && echo '3' > /tmp/count"]
      outputs:
        artifacts:
          - name: items
            path: /tmp/items
        parameters:
          - name: count
            valueFrom:
              path: /tmp/count
    - name: echo
      inputs:
        parameters:
          - name: index
        artifacts:
          - name: items
            path: /tmp/items
      container:
        image: stedolan/jq:latest
        command: [sh, -c]
        # jq is just one way to get the appropriate item.
        args: ["cat /tmp/items | jq '.[{{inputs.parameters.index}}]'"]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
