### ISSUE TITLE
Panic when injecting arguments.parameters in a DAG if the value comes from an expression

### ISSUE THREAD

**Issue by Alfablos** [argoproj/argo-workflows#7945]
## Summary

What happened/what you expected to happen?
I'm learning about workflows' conditionals and it should be possibile to inject an input conditionally; however if I use valueFrom.expression in the arguments.parameters of the template argo panics with `argo lint` and `argo submit`

What executor are you using?
Emissary

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-parameter-env-diff-
spec:
  serviceAccountName: argo-workflow   # has the proper role
  entrypoint: env-diff
  templates:
  - name: env-diff
    dag:
      tasks:
        - name: get-env
          template: alpine-get-env
        - name: diff-env
          dependencies: [get-env]
          template: perform-diff
          arguments:
            parameters:
              - name: workdir
                value: "{{tasks.get-env.outputs.parameters.first_workdir}}"
        # - name: responseok          # Working, let's step up the game!
        #   template: response-true
        #   dependencies: ["diff-env"]
        #   arguments:
        #     parameters:
        #       - name: verdict
        #         value: "SAME!"
        #   when: >-                                                      # Govaluate: https://github.com/Knetic/govaluate  !!!
        #     "{{ tasks.diff-env.outputs.result }}" =~ "no differences"

        - name: conditional-value-response
          template: response
          dependencies: ["diff-env"]
          arguments:
            parameters:
              - name: verdict
                valueFrom:
                  # Expression syntax: https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md
                  # expression: "tasks.diff-env.outputs.result =~ 'no differences' ? 'ok': 'ko'"    # this panics
                  expression: "tasks.diff-env.outputs.result contains 'no differences' ? 'ok': 'ko'"    # this panics as well
                # value: "{{ tasks.diff-env.outputs.result }}"    # this works, of course



  - name: alpine-get-env
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo $PWD > /tmp/workdir.txt"]
    outputs:
      parameters:
      - name: first_workdir
        valueFrom:
          path: /tmp/workdir.txt

  - name: perform-diff
    inputs:
      parameters:
      - name: workdir
    script:
      image: nextcloud:latest
      command: [bash]
      source: |
        echo "workdir={{ inputs.parameters.workdir }} and here_workdir=$PWD"
        [[ "{{ inputs.parameters.workdir }}" == "$PWD" ]] && \
        echo no differences between {{ inputs.parameters.workdir }} and $PWD || \
        echo "here_workdir ($PWD) differs from remote ({{ inputs.parameters.workdir }})"
  
  - name: response
    inputs:
      parameters:
        - name: verdict
    script:
      image: busybox:latest
      command: [sh]
      source:
        echo "{{ inputs.parameters.verdict }}"

```
The workflow is pretty simple: the first step uses a container to output the value of the $PWD variable;
the second steps uses another container and echoes a sentence based on the fact that the working directory is the same as the one in the first container.
What I want is echo 'ok' in a third container if the workdirs match, 'ko' otherwise.
So the value of the 'verdict' input should be injected in the third step conditionally.

Whenever I run `argo lint`, and of course `argo submit`, I get:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d0d59e]

goroutine 1 [running]:
github.com/argoproj/argo-workflows/v3/workflow/validate.validateDAGTaskArgumentDependency(0xc000203a40, 0x1, 0x4, 0x0, 0x0, 0x0, 0xc000b80320, 0x2, 0x2, 0x0, ...)
        /home/runner/work/argo-workflows/argo-workflows/workflow/validate/validate.go:1322 +0x11e
github.com/argoproj/argo-workflows/v3/workflow/validate.(*templateValidationCtx).validateDAG(0xc000aad840, 0xc000a35230, 0xc000aad8c0, 0xc000b06000, 0xc000a554f8, 0x0)
        /home/runner/work/argo-workflows/argo-workflows/workflow/validate/validate.go:1301 +0x134c
github.com/argoproj/argo-workflows/v3/workflow/validate.(*templateValidationCtx).validateTemplate(0xc000aad840, 0xc000a598c0, 0xc000aad8c0, 0x382ef08, 0xc000a35110, 0xc000a598c0, 0x0)
        /home/runner/work/argo-workflows/argo-workflows/workflow/validate/validate.go:396 +0xb75
github.com/argoproj/argo-workflows/v3/workflow/validate.(*templateValidationCtx).validateTemplateHolder(0xc000aad840, 0x3856080, 0xc000209d40, 0xc000a9f238, 0x382ef08, 0xc000a35110, 0x0, 0x0, 0xc00077c000)
        /home/runner/work/argo-workflows/argo-workflows/workflow/validate/validate.go:480 +0x15f
github.com/argoproj/argo-workflows/v3/workflow/validate.ValidateWorkflow(0x3816b20, 0xc000a2b890, 0x3816b00, 0xc000a2b8b0, 0xc000500400, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/argo-workflows/argo-workflows/workflow/validate/validate.go:205 +0x12fc
github.com/argoproj/argo-workflows/v3/server/workflow.(*workflowServer).CreateWorkflow(0xc0004ca3c0, 0x386f390, 0xc0004ca390, 0xc00013f800, 0x0, 0x7fea1a8776f0, 0x40)
        /home/runner/work/argo-workflows/argo-workflows/server/workflow/workflow_server.go:65 +0x2c5
github.com/argoproj/argo-workflows/v3/pkg/apiclient.(*argoKubeWorkflowServiceClient).CreateWorkflow(0xc000aa68b0, 0x386f390, 0xc0004ca390, 0xc00013f800, 0x0, 0x0, 0x0, 0x58, 0x28bd720, 0x1)
        /home/runner/work/argo-workflows/argo-workflows/pkg/apiclient/argo-kube-workflow-service-client.go:20 +0x51
github.com/argoproj/argo-workflows/v3/pkg/apiclient.(*errorTranslatingWorkflowServiceClient).CreateWorkflow(0xc000aa68c0, 0x386f390, 0xc0004ca390, 0xc00013f800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/argo-workflows/argo-workflows/pkg/apiclient/error-translating-workflow-service-client.go:20 +0x69
github.com/argoproj/argo-workflows/v3/cmd/argo/commands.submitWorkflows(0x386f390, 0xc0004ca390, 0x389aeb8, 0xc000aa68c0, 0xc00050c6a0, 0x19, 0xc000101c00, 0x1, 0x1, 0xc000aa28c0, ...)
        /home/runner/work/argo-workflows/argo-workflows/cmd/argo/commands/submit.go:222 +0x30b
github.com/argoproj/argo-workflows/v3/cmd/argo/commands.submitWorkflowsFromFile(0x386f390, 0xc0004ca390, 0x389aeb8, 0xc000aa68c0, 0xc00050c6a0, 0x19, 0xc000520110, 0x1, 0x1, 0xc000aa28c0, ...)
        /home/runner/work/argo-workflows/argo-workflows/cmd/argo/commands/submit.go:122 +0x296
github.com/argoproj/argo-workflows/v3/cmd/argo/commands.NewSubmitCommand.func1(0xc000ab8000, 0xc000520110, 0x1, 0x1)
        /home/runner/work/argo-workflows/argo-workflows/cmd/argo/commands/submit.go:86 +0x2c5
github.com/spf13/cobra.(*Command).execute(0xc000ab8000, 0xc0005200d0, 0x1, 0x1, 0xc000ab8000, 0xc0005200d0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009c8a00, 0xc000094778, 0xc000a9ff78, 0x406365)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /home/runner/work/argo-workflows/argo-workflows/cmd/argo/main.go:14 +0x2b
```

I'm running Garuda Linux:
```bash
Linux garanto 5.16.10-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 16 Feb 2022 19:35:21 +0000 x86_64 GNU/Linux

# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

# argo version
argo: v3.2.7
  BuildDate: 2022-01-28T02:12:09Z
  GitCommit: bdc14b0d2e50b6d3b30f7b6ffbfd8ceae3214413
  GitTreeState: clean
  GitTag: v3.2.7
  GoVersion: go1.16.13
  Compiler: gc
  Platform: linux/amd64
```

```bash
# Logs from the workflow controller: no logs since the workflow can't be submitted

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.
# The workflow's pods that are problematic: # skipped
# Logs from in your workflow's wait container, something like: # skipped
```

Thank you,
Antonio

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I'm afraid you cannot use `valueFrom` in this context. Try using expression tag template instead:

```
          arguments:
            parameters:
              - name: verdict
                value:
                  expression: "{{=tasks.diff-env.outputs.result contains 'no differences' ? 'ok': 'ko'}"
```

**Comment by Alfablos** [comment]
> I'm afraid you cannot use `valueFrom` in this context. Try using expression tag template instead:
> 
> ```
>           arguments:
>             parameters:
>               - name: verdict
>                 value:
>                   expression: "{{=tasks.diff-env.outputs.result contains 'no differences' ? 'ok': 'ko'}"
> ```

This way It doesn't panic, but the string is neither ok or ko. The last container echoes nothing.
Also, reading the [documentation for the parameters field](https://argoproj.github.io/argo-workflows/fields/#parameter) under DAGtemplate - DAG Task - arguments - parameters I understand that `value` only accepts a string as a value and `expression` is only to be under the `valueFrom` key.
Also expressions should follow the [expr](https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md#string-operators) syntax but if I replace `=~` with `contains` it panics again.
As far as I've understood the `=~` operator is used in conditionals under the `when` key.

But maybe I'm doing something wrong.

**Comment by alexec** [comment]
Sorry - wrong syntax:

```
          arguments:
            parameters:
              - name: verdict
                value: "{{=tasks.diff-env.outputs.result contains 'no differences' ? 'ok': 'ko'}"
```
