### ISSUE TITLE
Cannot pass input parameters to volumeClaimTemplate resource.requests.storage

### ISSUE THREAD

**Issue by neilharris1** [argoproj/argo-workflows#7956]
It appears it's not possible to pass input parameters as volumeClaimTemplate storage values. 

I'm receiving the following error when attempting to execute a workflow with the below configuration. 

`quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'`

```
    container:
      image: alpine:latest
      volumeMounts:
      - mountPath: "/tmp/test"
        name: test-volume
    volumes:
      - name: test-volume
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "gp2"
              resources:
                requests:
                  storage: '{inputs.parameters.storage}'

  - name: test
    inputs:
      parameters:
        - name: storage
    dag:
      tasks:
        - name: task1
          template: test-template
          arguments:
            parameters:
              - name: storage
                value: 1Gi
```

argo-workflow version: 3.1.6
K8s: v1.21
