### ISSUE TITLE
Ability to set default container security context

### ISSUE THREAD

**Issue by gavinclarkeuk** [argoproj/argo-workflows#7962]
# Summary

Currently you can only set the default pod security context as part of `workflowDefaults`. It would be good to be able to set a default container security context as well. At the moment there doesn't seem to be a good way to do this, as the container securityContext can only be set in the container template definition in a workflow/workflowTemplate.

Moving this to defaults would potentially DRY up a lot of code, and make it easier to tighten up security across all workflows

Something like this:

```yaml
  workflowDefaults:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 8737 #any non-root user
      containerSecurityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - all
```

# Use Cases

The main use for us is to avoid workflow/template authors needing to specify securityContexts to ensure their pods meet basic security requirements. It would also significantly reduce the amount of boilerplate yaml code in workflows.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
