### ISSUE TITLE
sprig in manifest validation problem.

### ISSUE THREAD

**Issue by berlinsaint** [argoproj/argo-workflows#7981]
## Summary

i

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
    - name: horovod-cpu
      retryStrategy:
        limit: "3"
        backoff:
          duration: "1"
          maxDuration: "1m"
      inputs:
        parameters:
          - name: command
            value: "python /work/code/horovod_test/train_atp_day_cal_ad_horovod.py --data_path /work/data/tfrecords_ad_infoflow_v1/data --featmap_path /work/data/tfrecords_ad_infoflow_v1/featMap/part-00000  --checkpoint_path /work/model/deepfm_v1 --start_date ${CURRENT} --embed_dim 8 --input_length 30 --learning_rate 0.0004 --decay_steps 5000 --embedding_length 150 --cache 0 --end_delta 2 --epochs 1 --test_rate 0.1"
          - name: image
            value: "docker-private/atp/horovod-cpu:master"
          - name: workers
            value: 2
          - name: masters
            value: 1
          - name: train_type
            value: "cpu"
          - name: cpu_num
            value: "32"
          - name: job_name
            value: "{{workflow.name}}-{{retries}}"
      resource:
        action: create            # can be any kubectl action (e.g. create, delete, apply, patch)
        # The successCondition and failureCondition are optional expressions.
        # If failureCondition is true, the step is considered failed.
        # If successCondition is true, the step is considered successful.
        # They use kubernetes label selection syntax and can be applied against any field
        # of the resource (not just labels). Multiple AND conditions can be represented by comma
        # delimited expressions.
        # For more details: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
        successCondition: status.state.phase = Completed
        failureCondition: tatus.conditions.2.type = Failed
        setOwnerReference: true
        manifest: |               #put your kubernetes spec here
          apiVersion: batch.volcano.sh/v1alpha1
          kind: Job
          metadata:
            name: {{inputs.parameters.job_name}}
            labels:
              "volcano.sh/job-type": Horovod
          spec:
            minAvailable: {{= sprig.addf(inputs.parameters.workers,inputs.parameters.masters)}}
            schedulerName: volcano
```

What executor are you running?  k8s

in the yaml, minAvailable is a int value; i can't submit it because it will say 

"templates.horovod-cpu templates.horovod-cpu.resource.manifest must be a valid yaml"

how can i avoid this.
