### ISSUE TITLE
UI: Custom icon url support per step

### ISSUE THREAD

**Issue by trondhindenes** [argoproj/argo-workflows#8016]
# Summary

Allow specifying custom icon sets in the workflow definition that would be rendered by the server when vieweing a workflow

# Use Cases

We have some workflows that can be quite busy, with 60-70 steps or more. It would be good if we were able to "categorize" steps by supplying a custom icon set for some of the steps, and have the "workflow view" use those instead of the standard green/yellow/red circles. It would allow us to infuse a lot of "meaning" into the workflow overview.

The implementation could be something like 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    customIcons:
      success: https://mycusttomthing.stuff.com/success.svg
      inProgress: https://mycusttomthing.stuff.com/success.svg
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
```
I don't know how many different icon statuses there are, but I guess "not started, skipped, success, in progress, error" and maybe a few more?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
