### ISSUE TITLE
Feature Request: support `skip` action for skipping an action

### ISSUE THREAD

**Issue by Colstuwjx** [argoproj/argo-workflows#8031]
# Summary

What change needs making?

For an instantiated workflow, we'd already support `resume`, `suspend`, `stop` such actions, but for a complete workflow engine, we also need to support `skip` action for allowing to skip an action.

# Use Cases

When would you use this?

When we submitted a workflow, and it's running a specific step, which is optional and could be skip, e.g. send a message to say it's doing the task. If we disallow to skip an action, we had to stop this workflow and remove that step if the message system broken and we couldn't run the same workflow anymore.

If we could support `skip`, life becomes more easier, and we can just skip that action!

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by NikeNano** [comment]
@Colstuwjx could you elaborate on how you see the `skip` functionality to work? Would this be something that is similar to suspend or manual approve where a yes/no would result in that the step is skipped or not? How do you see outputs being handled if they are required as input in downstream steps? Thanks.

**Comment by NikeNano** [comment]
@alexec would it make sens to extend the "TemplateTypeSuspend" to allow for inputs from the user and propagate as output, this would allow the use of conditionals for to skip actions?

**Comment by NikeNano** [comment]
> @alexec would it make sens to"TemplateTypeSuspend" allow for inputs from users and propagate as output, this would allow the use of conditionals for to skip actions?

I realised that this is already available example [here]( https://github.com/argoproj/argo-workflows/blob/master/examples/suspend-template-outputs.yaml)

**Comment by NikeNano** [comment]
I think the `skip` functionality can be achieved combining `suspend` with outputs and conditionals, will try it out see if I can create an example.

**Comment by Colstuwjx** [comment]
Here are two questions that I'm concerning about:

1. If we suspend a workflow and resume it, argo would skip the current action and just set it as succeed, and turn to the next step, right? Why? It looks weird! The general workflows which I've seen are all default to stay with the same action and suspend-resume did same work like `retry`.
 
2. As the general workflows design to `retry` rather than `skip` in the previous case, they need separate `skip` primitive to skip a specific step. If argo said that we could achieve that goal by `suspend-and-resume` it, yes, it works, but I still wonder if it's a standardized design pattern.

> I think the skip functionality can be achieved combining suspend with outputs and conditionals, will try it out see if I can create an example.

As I mentioned before, I don't think it's an elegant way to implement this feature, it might work, but on the other hand, it would make our workflow yaml becomes even more complicated.

Let's say a scenario for illustrating it: we have a workflow for CI/CD pipeline, and it would do `build`, `unit-test`, `integration-test`, `security-scan`, `package` and finally `deploy`. If something wrong with a specific action while instantiated a workflow, I'd like to check or skip it according the action details, and the choice should be user's.

It's hard to write these exception cases into our workflow, even though we could make this, it's still a problem to make different action according to the real run details.

Thanks!

**Comment by NikeNano** [comment]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: suspend-outputs-
spec:
  entrypoint: suspend
  templates:
  - name: suspend
    steps:
    - - name: approve
        template: approve
    - - name: release
        template: whalesay
        arguments:
          parameters:
            - name: message
              value: "{{steps.approve.outputs.parameters.message}}"
        when: "{{steps.approve.outputs.parameters.message}} == approve"

  - name: approve
    suspend: {}
    outputs:
      parameters:
        - name: message
          valueFrom:
            supplied: {}

  - name: whalesay
    inputs:
      parameters:
        - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

To run it: 

```bash
argo submit -n argo
```

then user eaither 
```bash
argo node set suspend-outputs-GENERATE-NAME --output-parameter message="no" --node-field-selector displayName=approve -n argo
```
or 
```
argo node set suspend-outputs-GENERATE-NAME --output-parameter message="approve" --node-field-selector displayName=approve -n argo
```

and resume it. 

```
argo resume suspend-GENERATE-NAME -n argo
```

I don fully follow on what you refer to with 

>
> If something wrong with a specific action while instantiated a workflow, I'd like to check or skip it according the action details, and the choice should be user's

I think this will give the user the possibility do decide it or not. @Colstuwjx.  Concerning if retry don't work in this conext I will have to verify that.  

I would be interested to get your opinion about having a dedicate template for this or relying on the current features @alexec. Thanks
