### ISSUE TITLE
Can't see anything in WORKFLOW DETAILS

### ISSUE THREAD

**Issue by SeibertronSS** [argoproj/argo-workflows#8046]
## Summary

What happened/what you expected to happen?

I deployed an argo workflow and reverse proxyed its ui using nginx. After I submit a `helloworld` workflow, I can't view its details in WORKFLOW DETAILS. After I click on `helloworld` workflow nothing is displayed in the page.

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
