### ISSUE TITLE
Not able to view workflow logs from s3 / minio for deleted pods

### ISSUE THREAD

**Issue by iamdinesh** [argoproj/argo-workflows#8057]
## Summary

What happened/what you expected to happen?

When pod is deleted not able to view workflow logs. But I can view individual node logs.

Get Workflow Log API (Returns Empty): 

http://localhost:2746/api/v1/workflows/<namespace>/<workflowname>/log?logOptions.container=main&grep=&logOptions.follow=true

Individual Node / Step API (Returns full log):

http://localhost:2746/artifacts/<namespace>/<workflowname>/<podname>/main-logs

Expectation:
http://localhost:2746/api/v1/workflows/<namespace>/<workflowname>/log?logOptions.container=main&grep=&logOptions.follow=true 

API must return all steps logs from minio / s3

What executor are you using? PNS/Emissary
Executor: Emissary

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  serviceAccountName: tc-tenant-workflows
  entrypoint: test
  templates:
  - name: test
    steps:
    - - name: step1
        template: node-template
        arguments:
          parameters:
          - name: a
            value: 15
          - name: b
            value: 25
          - name: name
            value: step1
    - - name: step2
        template: node-template
        arguments:
          parameters:
          - name: a
            value: 25
          - name: b
            value: 35
          - name: name
            value: step2
  - name: node-template
    inputs:
      parameters:
        - name: a
        - name: b
        - name: name
    script:
      image: node:12.22.5-alpine3.12
      command: [node]
      source: |
        var a = {{inputs.parameters.a}};
        var b = {{inputs.parameters.b}};
        var name = "{{inputs.parameters.name}}";
        console.log(`out from ${name} = `, a + b);
```

Steps to reproduce

1. Submit workflow (argo submit hello-world.yaml)
2. Delete the pods
3. Get workflow level logs from header (It will be empty)
4. Get node / step level logs

Note: I don't see any error from worklow server or controller

```bash
kubectl logs -f argo-workflows-server-7c58648b7c-g7ml

time="2022-03-02T21:18:17.663Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2022-03-02T21:18:17Z" grpc.time_ms=6.735 span.kind=server system=grpc
time="2022-03-02T21:18:17.741Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WorkflowLogs grpc.service=workflow.WorkflowService grpc.start_time="2022-03-02T21:18:17Z" grpc.time_ms=24.447 span.kind=server system=grpc
time="2022-03-02T21:18:17.839Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2022-03-02T21:18:17Z" grpc.time_ms=6.285 span.kind=server system=grpc

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
