### ISSUE TITLE
"This does not look like a tar archive tar"

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8059]
Getting this error on the 1st try of the pod (but 2nd auto retry succeeds):

```
MESSAGE
Error (exit code 1): Error response from daemon: mount /var/lib/kubelet/pods/ebcc76c8-d5e0-48d7-9150-d5667b72bef0/containers/main/3b28347c:/var/lib/docker/overlay2/0c3e32d505de9991a33281fbdb860335cbe971e6c38e305258fc9f6d8426303f/merged/dev/termination-log, flags: 0x5000: not a directory tar: This does not look like a tar archive tar: Exiting with failure status due to previous errors
```

yaml is:
```
- name: process-message-flow
  inputs: {}
  outputs: {}
  metadata: {}
  steps:
    - - name: fetch-messages
        template: fetch-message
        arguments: {}
    - - name: parse-messages
        template: parse-message
        arguments:
          parameters:
            - name: template-message
              value: '{{workflow.parameters.changes}}'     
- name: fetch-message
  inputs: {}
  outputs: {}
  metadata: {}
  container:
    name: ''
    image: 'docker/whalesay:latest'
    command:
      - cowsay
    args:
      - '{{workflow.parameters.changes}}'
    resources: {}
    volumeMounts:
      - name: aws-iam-token
        mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
- name: parse-message
  inputs: {}
  outputs:
    parameters:
      - name: git-repo
        valueFrom:
          path: /tmp/gitrepo.txt
      - name: git-commit-id
        valueFrom:
          path: /tmp/gitcommit.txt
      - name: git-branch
        valueFrom:
          path: /tmp/gitbranch.txt
  metadata: {}
  container:
    name: ''
    image: >-
      mypython
    command:
      - bash
      - '-c'
    args:
      - >-
        export msg='{{workflow.parameters.changes}}';git_repo=$(echo
        'ssh://git@redact.com/redact/redact.git' >
        /tmp/gitrepo.txt);git_commit_id=$(echo
        'redact' >
        /tmp/gitcommit.txt);git_branch=$(echo 'master' > /tmp/gitbranch.txt);
    resources: {}
    volumeMounts:
      - name: aws-iam-token
        mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
  volumes:
    - name: volume-ca-bundle
      configMap:
        name: ca-bundle
    - name: aws-iam-token
      projected:
        sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token
        defaultMode: 420
```

using v3.2.8 and pns exec
