### ISSUE TITLE
workflowtaskresults doesn't exists in namespace install

### ISSUE THREAD

**Issue by wurstbrot** [argoproj/argo-workflows#8068]
## Summary

Workflowtaskresults are not installed within namespace install.

## Diagnostics

I am using 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argocd
spec:
  destination:
    namespace: clusterscanner
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/argoproj/argo-workflows.git
    targetRevision: v3.2.9
    path: manifests/namespace-install
  project: clusterscanner
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
```
to install argo worklows (see https://github.com/SDA-SE/cluster-image-scanner/blob/master/test/argowf/argoworkflow.yml). I have tried multiple 3.2.X versions, which all result in a missing permission for the SA argo to access workflowtaskresults. Logs:
```
W0303 15:53:10.028391       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1alpha1.WorkflowTaskResult: workflowtaskresults.argoproj.io is forbidden: User "system:serviceaccount:clusterscanner:argo" cannot list resource "workflowtaskresults" in API group "argoproj.io" in the namespace "clusterscanner"
E0303 15:53:10.028425       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskResult: failed to list *v1alpha1.WorkflowTaskResult: workflowtaskresults.argoproj.io is forbidden: User "system:serviceaccount:clusterscanner:argo" cannot list resource "workflowtaskresults" in API group "argoproj.io" in the namespace "clusterscanner"
```

When I create the permission in my test env. (https://github.com/SDA-SE/cluster-image-scanner/blob/master/test/argowf/role-binding.yml), I get this:
```
│ time="2022-03-03T15:56:56.707Z" level=info msg="List workflowtaskresults 404"                                                                                                                                                                                                          
│ W0303 15:56:56.707926       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1alpha1.WorkflowTaskResult: the server could not find the requested resource (get workflowtaskresults.argoproj.io)                                     
│ E0303 15:56:56.707941       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskResult: failed to list *v1alpha1.WorkflowTaskResult: the server could not find the requested resource (get workflowtaskresults.ar │
│ goproj.io)
```
To overcome it, I create the CRD https://github.com/SDA-SE/cluster-image-scanner/blob/master/test/argowf/workflowtaskresults.yml. 




---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This feature is not available in v3.2. You're running the `latest` image, not the versioned images.

Do not install using Kustomize. Instead, install using the manifest attached to the release:

https://github.com/argoproj/argo-workflows/releases/download/v3.2.9/namespace-install.yaml

**Comment by wurstbrot** [comment]
@alexec Thank you for the quick response.
That means this https://github.com/argoproj/argo-workflows/tree/master/manifests#kustomize is outdated?

**Comment by alexec** [comment]
Yes. This guide is incorrect. Would you like to submit a PR to correct it?

**Comment by wurstbrot** [comment]
https://github.com/argoproj/argo-workflows/compare/master...wurstbrot:patch-1

**Comment by alexec** [comment]
Maybe we should warn people about Kustomize?

**Comment by wurstbrot** [comment]
>Installation with kustomize is not supported.
It would work with some customization. You think this is not offensive enough?

**Comment by alexec** [comment]
I think is frustrating to see kustomize.yaml files, but then not be able to use them. It looks like it is supported, but is not.

I _think_ you could use Kustomize, but you must set `kustomize edit set image` to set the argo-server and workflow-controller image tags. Additionally, you must patch the executor version, by patching the workflow-controller deployment with the correct env var (I think it is something like ARGO_EXECUTER_IMAGE, but you’d need to check).

**Comment by wurstbrot** [comment]
I think we are having a missunderstanding here, I understood that it is not supported. 
Let is continue in the PR https://github.com/argoproj/argo-workflows/pull/8095.

**Comment by vatine** [comment]
Well, having just been bitten by the same problem, it seems I am running ":latest" because that's what the default install manifests actually have in them. I probably should've noticed that it said ":latest", but there's an argument to be made that ":latest" is a somewhat dangerous thing to leave in the "this is how you install it quickly" manifest(s).

**Comment by nice-pink** [comment]
Is there a reason why the yaml files from the releases are not moved to the manifests folder and you continue to support kustomize? I maintain all the argo components incl versions using kustomize so far by just defining the images. To add sso support e.g. the manifest needs to be patched anyways, which is pretty handy with kustomize.

```
# image version patch

images:
- name: quay.io/argoproj/workflow-controller:latest
  newName: quay.io/argoproj/workflow-controller
  newTag: v3.3.1
- name: quay.io/argoproj/argocli:latest
  newName: quay.io/argoproj/argocli
  newTag: v3.3.1
```

Further it seams like the version in the `namespace-install.yaml` within the release are not up to date.
**Release 3.3.1**: `image: quay.io/argoproj/workflow-controller:v3.2.9`
https://github.com/argoproj/argo-workflows/releases/tag/v3.3.1
