### ISSUE TITLE
getaddrinfo EAI_AGAIN inside pods

### ISSUE THREAD

**Issue by frimuchkov** [argoproj/argo-workflows#8083]
Hi!

During the migration into the new Argo Cluster we found a problem with DNS. Do you know, what can be the reason for it?
Argo version: v3.3.0-rc8

```
metadata:
  name: sparkly-dragon
  namespace: default
  labels:
    example: 'true'
spec:
  entrypoint: curl
  templates:
    - name: curl
      container:
        name: main
        image: 'curlimages/curl:latest'
        command:
          - curl
        args:
          - '-v'
          - 'https://google.com/'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

Result:
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/19934346/156884234-e2513a91-21a4-4a43-af41-9688a40b7d86.png">

I understand, there is not much info and if it's not familiar, just close it :)
