### ISSUE TITLE
Workflows UI: Cannot read properties of undefined (reading 'template')

### ISSUE THREAD

**Issue by vermaxik** [argoproj/argo-workflows#8102]
## Summary

I submitted DAG workflow with inline template. The workflow is successfully run, but when I click on any task `task` for details/logs I got the error `Cannot read properties of undefined (reading 'template')`.

With DAG yaml and separate template approach like in [multiroot example](https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/dag-multiroot.yaml) it works, but not with inline.

<img width="1004" alt="agro-workflow-issue" src="https://user-images.githubusercontent.com/2705386/157211637-8cdd6b3d-1e0f-4052-9577-72ed38ed74ab.png">

**What happened/what you expected to happen?**
I expect to see sidebar menu with logs when I click on a task.

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-3-
spec:
  entrypoint: root
  templates:
    - dag:
        tasks:
          - arguments:
              parameters:
                - name: message
                  value: Hello from B
            depends: A
            inline:
              container:
                command:
                  - echo
                  - '{{inputs.parameters.message}}'
                image: alpine:3.7
              inputs:
                parameters:
                  - name: message
            name: B
          - arguments:
              parameters:
                - name: message
                  value: Hello from A
            inline:
              container:
                command:
                  - echo
                  - '{{inputs.parameters.message}}'
                image: alpine:3.7
              inputs:
                parameters:
                  - name: message
            name: A
      name: root
```

I use the argo `3.2.9` and tried to downgrade to `3.2.6` got the same issue.

Thank you for your help 🙏 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
