### ISSUE TITLE
Specify container resources dynamically for containerSet.

### ISSUE THREAD

**Issue by MagicFrogSJTU** [argoproj/argo-workflows#8103]
# Summary
Currently there's no way to specify container resources dynamically for containerSet.
For normal template, we can use podSpecPatch which is absent when it comes to containerSet.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
Can't you use `podSpecPatch`? I think it should work.

**Comment by MagicFrogSJTU** [comment]
Sorry my bad.
For those having the question:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-spec-patch-
  labels:
    workflows.argoproj.io/container-runtime-executor: emissary
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: cpu-limit1
        value: 1.0
      - name: cpu-limit2
        value: 2.0
  templates:
  - name: whalesay
    podSpecPatch: |
      containers:
        - name: step0
          resources:
            limits:
              cpu: "{{workflow.parameters.cpu-limit1}}"
        - name: main
          resources:
            limits:
              cpu: "{{workflow.parameters.cpu-limit2}}"
    containerSet:
      containers:
        - name: step0
          image: whalesay
          command:
            - bash
            - -c
            - |
              for i in `seq 20`
              do
                yes > /dev/null &
              done
              sleep 10s
              pkill yes
              cat /sys/fs/cgroup/cpuacct/cpuacct.usage
          resources:
            limits:
              cpu: "0.5"
        - name: main
          image: whalesay
          dependencies: ["step0"]
          command:
            - bash
            - -c
            - |
              for i in `seq 20`
              do
                yes > /dev/null &
              done
              sleep 10s
              pkill yes
              cat /sys/fs/cgroup/cpuacct/cpuacct.usage
          resources:
            limits:
              cpu: "0.5"
```
