### ISSUE TITLE
Failed to acquire template-level semaphore even if there are available locks

### ISSUE THREAD

**Issue by djshen** [argoproj/argo-workflows#8109]
## Summary

What happened/what you expected to happen?

When there are two (or more) workflows and the nodes in both of the workflows share the same template-level semaphore, the nodes in the second workflow cannot acquire any lock until the first workflow completes.

What executor are you using? Emissary

Version: v3.2.9

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
 name: my-config
data:
 template2: "2"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-lock
  namespace: argo
spec:
  arguments:
    parameters:
    - name: durations
      value: '[10,10,10,10,10,3600]'
  entrypoint: main
  templates:
  - inputs:
      parameters:
      - name: durations
    metadata: {}
    name: main
    outputs: {}
    steps:
    - - arguments:
          parameters:
          - name: duration
            value: '{{item}}s'
        name: sleep
        template: sleep
        withParam: '{{inputs.parameters.durations}}'
  - inputs:
      parameters:
      - name: duration
    metadata: {}
    name: sleep
    outputs: {}
    suspend:
      duration: '{{inputs.parameters.duration}}'
    synchronization:
      semaphore:
        configMapKeyRef:
          key: template2
          name: my-config
  ttlStrategy:
    secondsAfterCompletion: 300
```

Submit the first workflow with durations `[10,10,10,10,10,3600]` and the second workflow with durations `[10,10,10,10]`. The second workflow cannot acquire any lock for 3600 seconds.

### Workflow controller log
```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep test-lock
```
[argo.log](https://github.com/argoproj/argo-workflows/files/8215806/argo.log)

### Step-by-step explanation with the visualization of the pending priority queue:
At the beginning (2022-03-09T13:47:12):
- wf 1 is submitted
- child 0 `addToQueue`, `tryAcquire`, and its `holderKey` is popped
- child 1 `addToQueue`, `tryAcquire`, and its `holderKey` is popped
- child 2 to 5 `addToQueue`, `tryAcquire`
- wf 2 is submitted
- child 0 to 3 `addToQueue`, `tryAcquire`
```mermaid
flowchart TD
    WF1C2["wf1.sleep[2]"] --> WF1C3["wf1.sleep[3]"];
    WF1C2 --> WF1C4["wf1.sleep[4]"];
    WF1C3 --> WF1C5["wf1.sleep[5]"];
    WF1C3 --> WF2C0["wf2.sleep[0]"];
    WF1C4 --> WF2C1["wf2.sleep[1]"];
    WF1C4 --> WF2C2["wf2.sleep[2]"];
    WF1C5 --> WF2C3["wf2.sleep[3]"];
```

After 10 seconds (2022-03-09T13:47:22):
- child 0 and 1 of wf 1 succeed, but not calling `release` (don't know why)

After 10 seconds (2022-03-09T13:47:32):
- child 0 and 1 of wf 1 `release`
- child 2 of wf 1 `addToQueue` (already in `pending`)
- child 2 `tryAcquire`, and its `holderKey` is popped
```mermaid
flowchart TD
    WF1C3["wf1.sleep[3]"] --> WF1C5["wf1.sleep[5]"];
    WF1C3 --> WF1C4["wf1.sleep[4]"];
    WF1C5 --> WF2C3["wf2.sleep[3]"];
    WF1C5 --> WF2C0["wf2.sleep[0]"];
    WF1C4 --> WF2C1["wf2.sleep[1]"];
    WF1C4 --> WF2C2["wf2.sleep[2]"];
```
- child 3 of wf 1 `addToQueue` (already in `pending`)
- child 3 acquires the lock and its `holderKey` is popped
```mermaid
flowchart TD
    WF1C5["wf1.sleep[5]"] --> WF2C2["wf2.sleep[2]"];
    WF1C5 --> WF1C4["wf1.sleep[4]"];
    WF2C2 --> WF2C3["wf2.sleep[3]"];
    WF2C2 --> WF2C0["wf2.sleep[0]"];
    WF1C4 --> WF2C1["wf2.sleep[1]"];
```
- child 4 and 5 of wf 1 `addToQueue` (already in `pending`), `tryAcquire`

After 10 seconds (2022-03-09T13:47:42):
- child 2 and 3 of wf 1 `release`
- child 4 of wf 1 `addToQueue` (already in `pending`)
- child 4 `tryAcquire`, and the `holderKey` of **child 5** is popped
```mermaid
flowchart TD
    WF1C4["wf1.sleep[4]"] --> WF2C2["wf2.sleep[2]"];
    WF1C4 --> WF2C1["wf2.sleep[1]"];
    WF2C2 --> WF2C3["wf2.sleep[3]"];
    WF2C2 --> WF2C0["wf2.sleep[0]"];
```
- child 5 of wf 1 `addToQueue` **again** (not in `pending`)
```mermaid
flowchart TD
    WF1C4["wf1.sleep[4]"] --> WF2C2["wf2.sleep[2]"];
    WF1C4 --> WF1C5["wf1.sleep[5]"];
    WF2C2 --> WF2C3["wf2.sleep[3]"];
    WF2C2 --> WF2C0["wf2.sleep[0]"];
    WF1C5 --> WF2C1["wf2.sleep[1]"];
```
- child 5 `tryAcquire`, and the `holderKey` of **child 4** is popped
```mermaid
flowchart TD
    WF1C5["wf1.sleep[5]"] --> WF2C2["wf2.sleep[2]"];
    WF1C5 --> WF2C1["wf2.sleep[1]"];
    WF2C2 --> WF2C3["wf2.sleep[3]"];
    WF2C2 --> WF2C0["wf2.sleep[0]"];
```

After 10 seconds (2022-03-09T13:47:52):
- child 4 of wf 1 `release`
- child 5 of wf 1 `addToQueue` (already in `pending`)
- child 5 of wf 1 `tryAcquire`, but it has acquired a lock and its `holderKey` is not popped
- does not call `nextWorkflow` to schedule wf 2

After ~20 (`workflowResyncPeriod`) minutes (2022-03-09T14:07:52):
- child 0 of wf 2 `addToQueue` (already in `pending`)
- child 0 of wf 2 `tryAcquire`, but `pending.peek()` is the `holderKey` of child 5 of wf 1
- call `nextWorkflow` to schedule wf 1
- child 5 of wf 1 `addToQueue` (already in `pending`)
- child 5 of wf 1 `tryAcquire`, but it is holding a lock and its `holderKey` is not popped
(repeat several times)

After 40 minutes (2022-03-09T14:47:12):
- child 5 of wf 1 `release` (its `holderKey` is still in `pending`)
- call `nextWorkflow` to schedule wf 1 and wf 2 (the number of available locks is 2)
- wf 1 succeeds
- schedule wf 1 for delete in 5 minutes
- wf 1 `ReleaseAll` (does not clear the `holderKey` in `pending`)

After 10 seconds (2022-03-09T14:47:22):
- the nodes of wf 2 still cannot acquire the lock since `pending.peek()` is child 5 of wf 1

After 5 minutes (2022-03-09T14:52:13):
- wf 1 is deleted
- `CheckWorkflowExistence` finds that wf 1 is deleted and call `removeFromQueue`

After 15 minutes (2022-03-09T15:07:32, 20 minutes since the last time wf 2 was scheduled):
- finally wf 2 can acquire the lock

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
