### ISSUE TITLE
The workflow can't stop when an error occurs in a node

### ISSUE THREAD

**Issue by SeibertronSS** [argoproj/argo-workflows#8119]
## Summary

I built a CI pipeline, but an error occurred while building the docker image. I found that the workflow did not stop, but continued with subsequent tasks.

The error log is
```
...
...
main cp: cannot stat 'msyh.ttc': No such file or directory                                                                                                                                     
main The command '/bin/sh -c mkdir /usr/share/fonts/ && cp msyh.ttc /usr/share/fonts/' returned a non-zero code: 1                                                                             
main The push refers to repository [easyx/backend-test]                                                                                              
main An image does not exist locally with the tag: easyx/backend-test                                                                                
main Error: No such image: easyx/backend-test:1.0.1                         
```
Clearly the image build failed, but still passed the workflow.

![image](https://user-images.githubusercontent.com/69496864/157569559-68f449bb-5197-497c-bcf7-8a4cf6642ba8.png)

**Comment by alexec** [comment]
Please share workflow.

**Comment by SeibertronSS** [comment]
> Please share workflow.

Due to company security regulations, I cannot give specific docker repositories and git repositories.
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: |
      Checkout out from Git, build and deploy application.
    workflows.argoproj.io/maintainer: '@pxy'
    workflows.argoproj.io/tags: python, git
    workflows.argoproj.io/version: '>= 3.2.9'
  name: backend-test-cluster 
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: src-repo
        value: git@xxx/Backend.git
      - name: src-branch
        value: dev-1.0.0-test
      - name: image
        value: xxx/backend-test
      - name: dockerfile
        value: Dockerfile
      - name: deploy-repo
        value: git@xxx/Deploy.git
      - name: deploy-branch
        value: dev-2.0-test-cluster
      - name: microservices
        value: Backend
      - name: 
  templates:
    - name: main
      steps:
        - - name: Checkout
            template: Checkout
        - - name: BuildImage
            template: BuildImage
            arguments:
              parameters:
              - name: version-message-1
                value: "{{steps.Checkout.outputs.parameters.version}}"
              - name: timestemp-message-1
                value: "{{steps.Checkout.outputs.parameters.timestemp}}"
        - - name: Deploy
            template: Deploy
            arguments:
              parameters:
              - name: version-message-2
                value: "{{steps.Checkout.outputs.parameters.version}}"
              - name: timestemp-message-2
                value: "{{steps.Checkout.outputs.parameters.timestemp}}"

    - name: Checkout
      script:
        image: xxx/git-image:v1
        workingDir: /work
        command:
        - sh
        source: |
          export TIMESTEMP=`date +%s`
          echo $TIMESTEMP > /tmp/timestemp.txt
          git clone --branch {{workflow.parameters.src-branch}} {{workflow.parameters.src-repo}} /work/$TIMESTEMP
          cd $TIMESTEMP
          cp version.txt /tmp
        volumeMounts:
          - mountPath: /work
            name: work
      volumes:
      - name: work
        persistentVolumeClaim:
          claimName: argo-test
      outputs:
        parameters:
        - name: version
          valueFrom:
            path: /tmp/version.txt
        - name: timestemp
          valueFrom:
            path: /tmp/timestemp.txt

    - name: BuildImage
      inputs:
        parameters:
        - name: version-message-1
        - name: timestemp-message-1
      volumes:
      - name: docker-config
        hostPath:
          path: /var/run
      - name: work
        persistentVolumeClaim:
          claimName: argo-test
      script:
        image: xxx/docker:18.09
        workingDir: /work
        command:
        - sh
        source: |
          cd {{inputs.parameters.timestemp-message-1}}
          docker build -t {{workflow.parameters.image}}:{{inputs.parameters.version-message-1}} . -f {{workflow.parameters.dockerfile}} --network=host
          docker push {{workflow.parameters.image}}:{{inputs.parameters.version-message-1}}
          docker rmi {{workflow.parameters.image}}:{{inputs.parameters.version-message-1}}
          cd /work
          rm -rf {{inputs.parameters.timestemp-message-1}}
        volumeMounts:
          - name: work
            mountPath: /work
          - name: docker-config
            mountPath: /var/run
            
    - name: Deploy
      inputs:
        parameters:
        - name: version-message-2
        - name: timestemp-message-2
      script:
        image: xxx/kustomize:v3.2.0
        workingDir: /work-cd
        command:
        - sh
        source: |
          git clone --branch {{workflow.parameters.deploy-branch}} {{workflow.parameters.deploy-repo}}} /work-cd/{{inputs.parameters.timestemp-message-2}}
          cd {{inputs.parameters.timestemp-message-2}}/{{workflow.parameters.microservices}}/base
          kustomize edit set image {{workflow.parameters.image}}:{{inputs.parameters.version-message-2}}
          cd /work-cd/{{inputs.parameters.timestemp-message-2}}
          git add .
          git commit -m "doc: image update {{workflow.parameters.image}}:{{inputs.parameters.version-message-2}}"
          git push origin dev-2.0-test-cluster
          cd /work-cd
          rm -rf {{inputs.parameters.timestemp-message-2}}
        volumeMounts:
          - mountPath: /work-cd
            name: work-cd
      volumes:
        - name: work-cd
          persistentVolumeClaim:
            claimName: argo-test-cd
```
