### ISSUE TITLE
Workflow security context not set when creating workflow from workflowtemplate with workflowDefaults and argo cli

### ISSUE THREAD

**Issue by jribmartins** [argoproj/argo-workflows#8123]
## Checklist

 

* [ x ] Double-checked my configuration.
* [ x ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

when I submit a workflow from a template using the argo cli:
`argo submit --from workflowtemplate/my-template`

the cli outputs: `This workflow does not have security context set.`

This is wrong because when I describe the created workflow I see:

```
...
Stored Workflow Template Spec:
    ...
    Entrypoint:  full
    Security Context:
      Run As Non Root:     true
      Run As User:         1000
```

This is happening maybe because of a merge with `workflowDefaults` and this might be the reason why the cli don't check this?

What version are you running?
3.2.6

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
spec:
  entrypoint: argosay
  templates:
    - name: argosay
      container:
        name: main
        image: 'nexus.bmwgroup.net/argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - 'hello'
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argowf-workflow-controller-configmap
data:
  config: |
    workflowDefaults:
      spec:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
```

1) apply the workflow and workflowDefaults described.

2) Start the workflow from the template using the cli:
```bash
argo submit --log --from workflowtemplate/test
```

- you ill see that the warning is comig: `This workflow does not have security context set.`

3) Check that the security context is set
```bash
kubectl describe workflow -l workflows.argoproj.io/workflow-template=test | grep "Security Context:
      Run As Non Root"
```
```
Security Context:
      Run As Non Root:     true
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
