### ISSUE TITLE
Workflow killed by ttl strategy

### ISSUE THREAD

**Issue by AgricaSopraSteria** [argoproj/argo-workflows#8146]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

Launch a workflow with a duration longer than ttl strategy
Example with a ttl set to 300 secs :

1st Run : 
One Workflow with followings sequential steps :
step 1 : sleep 60
step 2 : sleep 240
step 3 : sleep 60
All steps are completed.

2nd Run (just after completed 1st Run) :
Launched the same workflow, and during the step 2, the workflow was killed (because the ttl get the 300 seconds expiration from the 1st RUN)

What happened/what you expected to happen?

The workflow should not be deleted in the 2nd Run.

What version are you running?

v3.0.3

PipelineTestTTL.yaml :

```
apiVersion: [argoproj.io/v1alpha1](http://argoproj.io/v1alpha1)
kind: WorkflowTemplate
metadata:
  name: pipeline-test-argo-ttl-template
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: sleep-60-1
            template: sleep-60-1
            arguments:
              parameters:
                - name: workflowtemplate
                  value: "sleep-60-1-template"
          - name: sleep-240-2
            template: sleep-240-2
            arguments:
              parameters:
                - name: workflowtemplate
                  value: "sleep-240-2-template"
            dependencies: [ sleep-60-1 ]
          - name: sleep-60-3
            template: sleep-60-3
            arguments:
              parameters:
                - name: workflowtemplate
                  value: "sleep-60-3-template"
            dependencies: [ sleep-240-2 ]
    - name: sleep-60-1
      inputs:
        parameters:
          - name: workflowtemplate
      resource:
        action: apply
        manifest: |
          apiVersion: [argoproj.io/v1alpha1](http://argoproj.io/v1alpha1)
          kind: Workflow
          metadata:
            name: sleep-60-1-task
          spec:
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
    - name: sleep-240-2
      inputs:
        parameters:
          - name: workflowtemplate
      resource:
        action: apply
        manifest: |
          apiVersion: [argoproj.io/v1alpha1](http://argoproj.io/v1alpha1)
          kind: Workflow
          metadata:
            name: sleep-240-2-task
          spec:
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
    - name: sleep-60-3
      inputs:
        parameters:
          - name: workflowtemplate
      resource:
        action: apply
        manifest: |
          apiVersion: [argoproj.io/v1alpha1](http://argoproj.io/v1alpha1)
          kind: Workflow
          metadata:
            name: sleep-60-3-task
          spec:
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
```

SleepTemplates.yaml :

```
apiVersion: [argoproj.io/v1alpha1](http://argoproj.io/v1alpha1)
kind: WorkflowTemplate
metadata:
  name: sleep-60-1-template
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: sleep-60-1
        template: sleep-60-1
        archiveLocation:
          archiveLogs: true
  - name: sleep-60-1
    container:
      image: busybox
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh","-c" ]
      args: [ "echo 'start'; echo 'proceed'; sleep 60; echo 'end proceed'; echo 'stop'" ]
---
apiVersion: [argoproj.io/v1alpha1](http://argoproj.io/v1alpha1)
kind: WorkflowTemplate
metadata:
  name: sleep-240-2-template
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: sleep-240-2
            template: sleep-240-2
            archiveLocation:
              archiveLogs: true
    - name: sleep-240-2
      container:
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh","-c" ]
        args: [ "echo 'start'; echo 'proceed'; sleep 240; echo 'end proceed'; echo 'stop'" ]
---
apiVersion: [argoproj.io/v1alpha1](http://argoproj.io/v1alpha1)
kind: WorkflowTemplate
metadata:
  namespace: wf-val
  name: sleep-60-3-template
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: sleep-60-3
            template: sleep-60-3
            archiveLocation:
              archiveLogs: true
    - name: sleep-60-3
      container:
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh","-c" ]
        args: [ "echo 'start'; echo 'proceed'; sleep 60; echo 'end proceed'; echo 'stop'" ]
```
