### ISSUE TITLE
Logs from s3 / min.io is not in order

### ISSUE THREAD

**Issue by iamdinesh** [argoproj/argo-workflows#8159]
## Summary

What happened/what you expected to happen?

When i view the workflow logs from s3 / minio, it is not in proper order. First few seconds workflow logs are available in the bottom of the file and the last part available in the top. But we i get the logs from pods, it is proper order. Same happening in argo ui as well.

APIs from argo UI:

/api/v1/workflows/<namespace>/<workflowname>/log?logOptions.container=main&grep=&logOptions.follow=true - working as expected

/artifacts/<namespace>/<workflowname>/<pod-name>/main-logs - Log is not in order.

What version are you running?

Executor: emissary
Argo workflow helm version - 0.9.3
Argo workflow version - 3.2.4

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deno-workflow
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  nodeSelector:
    maglev.io/node-type: stateless
  serviceAccountName: tc-tenant-workflows
  entrypoint: main
  templates:
    - name: main
      container:
        image: denoland/deno:latest
        command: [deno]
        args: [run, --unstable, --allow-all, "https://raw.githubusercontent.com/iamdinesh/deno-template/main/index.ts"]
```
Note: This is happening only when we have large log output.

I have attached the pod log as well as log from s3.
[pod-log-working-as-expected.log](https://github.com/argoproj/argo-workflows/files/8256208/pod-log-working-as-expected.log)
[s3-minio.log](https://github.com/argoproj/argo-workflows/files/8256209/s3-minio.log)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
