### ISSUE TITLE
Namespace Delegation Failing v3.3.0

### ISSUE THREAD

**Issue by hbrewster-splunk** [argoproj/argo-workflows#8167]
## Checklist

 

* [X] Double-checked my configuration.
* [X] Tested using the latest version.
* [X] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

I have configured namespace delegation via this doc: https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac-namespace-delegation

I can confirm that SSO_DELEGATE_RBAC_TO_NAMESPACE=true is correctly set on the argo-server and I have defined the service-account to follow the documented format:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sa
  namespace: <some-namespace-but-not-where-argo-is>
  annotations:
    workflows.argoproj.io/rbac-rule: "'sg-okta-group' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
```

I can see failed to perform RBAC authorization" error="no service account rule matches" in the argo-server logs. This app is integrated with okta. Exisitng service accounts reasiding in the `argo` namespace work with the rbac annotations, which validates the okta integration.

What version are you running? v3.3.0. **Not** a namespaced installation of argo-workflows. 

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml

```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
