### ISSUE TITLE
Broken manifests

### ISSUE THREAD

**Issue by allemp** [argoproj/argo-workflows#8188]
## Checklist

 

* [X] Double-checked my configuration.
* [X] Tested using the latest version.
* [X] Used the Emissary executor.

### What happened/what you expected to happen?

I want to run hello-world and expect it to successfully complete

Instead when describing the pod I get "failed to resolve reference "quay.io/argoproj/argoexec:untagged"

### What version are you running?

I use the latest cluster-install manifests rolled out by argo-cd

This bug does not occur if I pin version to before the following commit [2b5e4a1d2df7877d9b7b7fbedd7136a125a39c8d](https://github.com/argoproj/argo-workflows/commit/2b5e4a1d2df7877d9b7b7fbedd7136a125a39c8d)

It would seem that the above commit broke the manifests.

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
