### ISSUE TITLE
argo logs is truncating the pod logs

### ISSUE THREAD

**Issue by ankushagarwal** [argoproj/argo-workflows#819]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
`argo logs <podname>` truncating the logs

**What you expected to happen**:
`argo logs <podname>` should not truncate the logs

**How to reproduce it (as minimally and precisely as possible)**:
I ran a workflow whose logs are 5067 lines (using kubectl logs). When I use argo logs to fetch the pod logs, I only see 3395 lines.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
% argo version
argo: v2.1.0-beta2
  BuildDate: 2018-03-29T20:49:33Z
  GitCommit: fe23c2f651a61a2d7aa877a86edff9802d7b5b47
  GitTreeState: clean
  GitTag: v2.1.0-beta2
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```

- Kubernetes version :
```
% kubectl version -o yaml
clientVersion:
  buildDate: 2018-02-09T21:51:54Z
  compiler: gc
  gitCommit: d2835416544f298c919e2ead3be3d0864b52323b
  gitTreeState: clean
  gitVersion: v1.9.3
  goVersion: go1.9.4
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-01-31T21:39:04Z
  compiler: gc
  gitCommit: 192ccad06d24af9828cbf42330e1d915cb586406
  gitTreeState: clean
  gitVersion: v1.8.7-gke.1
  goVersion: go1.8.3b4
  major: "1"
  minor: 8+
  platform: linux/amd64
```

**Comment by jessesuen** [comment]
`argo logs` used to be just a convenience wrapper on top of `kubectl logs`, so the truncation wasn't happening before. But this changed recently with the new feature to stream logs of an entire workflow. @alexmt can you take this?

**Comment by alexmt** [comment]
hello @ankushagarwal ,

I'm unable to reproduce the issue. Tried to submit workflow belong and `argo logs` correctly printed all 5067 lines. I've tried to introduce new line characters, used `-f` `-w` flags, but still unable to reproduce it. Is there anything special in your workflow output (unprinted characters etc)? 


```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: ["bash", "-c"]
      args: ["for i in {1..5067}; do echo \"${i} Long Long Long Long Long Long Text Text Text Text Text Text Text Text Text Long Long Long Long Long Long Text Text Text Text Text Text Text Text Text Long Long Long Long Long Long Text Text Text Text Text Text Text Text Text Long Long Long Long Long Long Text Text Text Text Text Text Text Text Text \"; done"]

```
