### ISSUE TITLE
I think my Artifact repository is being interpreted as a volume(?)

### ISSUE THREAD

**Issue by wdma** [argoproj/argo-workflows#8197]
## Checklist

 

* [ ] Double-checked my configuration.
* [ ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary
This is a follow-on to this issue (https://github.com/argoproj/argo-workflows/issues/8168). 

I have implemented my artifact repository per these instructions (https://argoproj.github.io/argo-workflows/configure-artifact-repository/).  Here is my abstracted implementation

```
  artifactRepository: |
    gcs:
      bucket: my-bucket
      region: us-east-1

      keyFormat: /tmp/      
      serviceAccountKeySecret: 
        name: account@developer.gserviceaccount.com
        key: my-64bit encoded-key
```

I expect that the following workflow should save the output of whalesay to the repository so that it is available for the print pod. 

```
---
{
   "apiVersion": "argoproj.io/v1alpha1",
   "kind": "Workflow",
   "metadata": {
      "annotations": {
         "workflows.argoproj.io/description": "testing a linter",
         "workflows.argoproj.io/version": ">= 3.1.0"
      },
      "labels": {
         "workflows.argoproj.io/archive-strategy": "false"
      },
      "name": "hello-world",
   },
   "spec": {
      "serviceaccount": "725104128071-compute@developer.gserviceaccount.com ",
      "arguments": {
         "parameters": [
            {
               "name": "msg",
               "value": "Hello there"
            }
         ]
      },
      "entrypoint": "entrypoint",
      "securityContext": {
         "fsGroup": 2000,
         "fsGroupChangePolicy": "OnRootMismatch",
         "runAsGroup": 3000,
         "runAsNonRoot": true,
         "runAsUser": 1000
      },
      "templates": [
         {
            "container": {
               "args": [
                  "cowsay Hello Test >> /tmp/output"
               ],
               "command": [
                  "sh",
                  "-c"
               ],
               "image": "docker/whalesay:latest",
               "imagePullPolicy": "IfNotPresent",
            },
            "name": "whalesay",
            "outputs": {
               "artifacts": [
                  {
                     "name": "message",
                     "path": "/tmp/output",
                     "s3": {
                        "key": "whalesay",
                     }
                  }
               ]
            },
            "retryStrategy": {
               "limit": "10"
            },
            "securityContext": {
               "fsGroup": 2000,
               "fsGroupChangePolicy": "OnRootMismatch",
               "runAsGroup": 3000,
               "runAsNonRoot": true,
               "runAsUser": 1000
            }
         },
         {
            "inputs": {
               "artifacts": [
                  {
                     "s3": {
                        "key": "whalesay",
                     },
                     "name": "data",
                     "path": "/tmp/input"
                  }
               ]
            },
            "name": "print",
            "retryStrategy": {
               "limit": "10"
            },
            "script": {
               "command": [
                  "python"
               ],
               "image": "python:alpine3.6",
               "imagePullPolicy": "IfNotPresent",
               "source": "import sys \nsys.stdout.write(\"{{inputs.artifacts.data}}\")\n\n"
            },
            "securityContext": {
               "fsGroup": 2000,
               "fsGroupChangePolicy": "OnRootMismatch",
               "runAsGroup": 3000,
               "runAsNonRoot": true,
               "runAsUser": 1000
            }
         },
         {
            "dag": {
               "tasks": [
                  {
                     "name": "whalesay",
                     "template": "whalesay"
                  },
                  {
                     "arguments": {
                        "artifacts": [
                           {
                              "from": "{{whalesay.outputs.artifacts.message}}",
                              "name": "data"
                           }
                        ]
                     },
                     "dependencies": [
                        "whalesay"
                     ],
                     "name": "print",
                     "template": "print"
                  }
               ]
            },
            "name": "entrypoint"
         }
      ]
   }
}
...
```
Instead, I am getting an error which suggests it is expecting a volumeClaim

```
Pod "hello-world2xr6z-2749602831" is invalid: [spec.volumes[1].name: Invalid value: "725104128071-compute@developer.gserviceaccount.com": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regexused for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?'), spec.containers[0].volumeMounts[0].name: Not found: "725104128071-compute@developer.gserviceaccount.com", spec.initContainers[0].volumeMounts[0].name: Not found: "725104128071-compute@developer.gserviceaccount.com"]
```

What version are you running?
Argo 3.3.0

I am able to successfully run the quickstart example, so I think it is the artifact repository implementation. i.e. Argo itself is working ok.
No pods are generated in the case of the problematic workflow (above)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by wdma** [comment]
Hypothesis: you have executor set in your config map. Can you please confirm?

Yes.
```
  containerRuntimeExecutor: emissary
```

**Comment by alexec** [comment]
sorry. I meant the specifically `data.executor`.

**Comment by wdma** [comment]
Here you go!
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
    gcs:
      endpoint: storage.googleapis.com
      bucket: my-bucket
      region: us-east-1
      serviceAccountKeySecret: 
        name: ''
        key: ''              
      useSDKCreds: false
  containerRuntimeExecutor: emissary
  workflowDefaults: |
    spec:
      ttlStrategy:
        secondsAfterSuccess: 5
      parallelism: 3
      entrypoint: 'entrypoint'
      securityContext: 
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
        runAsGroup: 3000
        fsGroupChangePolicy: "OnRootMismatch"
```

**Comment by alexec** [comment]
You're configuration is incorrect. It is impossible for there to be a secret with an @ in the name. Fix this

```yaml
      serviceAccountKeySecret: 
        name: name-of-secret
        key: key-within-secret
```
