### ISSUE TITLE
script args order is broken after v3

### ISSUE THREAD

**Issue by ekesken** [argoproj/argo-workflows#8199]
## Summary

Breaking non-documented change causing failures during Argo v2 -> v3 switch due to order change in container args in Pod manifest for script templates.

in Argo v2 `script.args` values were reflecting to Pod manifest so:

```yaml
spec:
  containers:
  - args:
    - /argo/staging/script
    - some-value
    command:
    - python3
```

and in Argo v3, reflects like this:
```yaml
spec:
  containers:
  - args:
    - some-value
    - /argo/staging/script
    command:
    - python3
```

This order change causes an error like this at the end in Argo v3:
```
python3: can't open file 'some-value': [Errno 2] No such file or directory
````

We observed this problem during Argo v2.12.5 -> v3.1.5 upgrade, but I tested it in Argo v3.3.1 as well and hit the same issue.

## Diagnostics

The workflow that reproduces the problem:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: script-args-broken-in-v3.3.1
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: test-script-call
            template: tmpl-script-with-args
            arguments:
              parameters:
                - name: some-param
                  value: "some-value"
    - name: tmpl-script-with-args
      inputs:
        parameters:
        - name: some-param
      script:
        image: python:3.8
        command: ["python3"]
        args:
         - "{{inputs.parameters.some-param}}"
        source: |
          import sys
          print(f"argv: '{sys.argv}'")
          print(f"stdin: '{sys.stdin.read()}'")
          print("some-param: '{{inputs.parameters.some-param}}'")
  
```

If you try it on v2, you'll see it succeeds and on v3 it will fail.

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.
