### ISSUE TITLE
"runtime error: invalid memory address or nil pointer dereference" when retrying failed workflows with onExit and semaphore

### ISSUE THREAD

**Issue by kulinskyvs** [argoproj/argo-workflows#8203]
## Summary

**What happened/what you expected to happen?**

When retrying failed workflow with `onExit` handler and `semaphores`  the workflow is failing again with `runtime error: invalid memory address or nil pointer dereference` workflow controller log message (see below the full stack trace). The issue seems similar to #7934 and #7888 but is still reproduced with `3.3.1` version.

Also, I'm observing a similar issue with resubmitting failed workflows launched from `workflowtemplate`. But in this case, the issue is not 100% always reproducible > hard to detect the exact cause since this is a floating issue. 

**What version are you running?**
**3.3.1** with Emissary as the executor.

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

Workflows configmap: 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-argo-panic
data:
  limit: "2"
```

Workflows manifest: 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-panic-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: info
            template: echo
            arguments:
              parameters:
                - name: message
                  value: info
        - - name: run
            template: run

    - name: run
      dag:
        tasks:
          - name: run-dag-1
            template: echo
            arguments:
              parameters:
                - name: message
                  value: run-dag-1
          - name: run-nested
            dependencies: [ run-dag-1 ]
            template: run-dag-nested
            onExit: finalize-run-nested

    - name: run-dag-nested
      dag:
        tasks:
          - name: run-dag-nested-1
            template: echo
            arguments:
              parameters:
                - name: message
                  value: run-dag-nested-1
          - name: run-dag-nested-sync-1
            dependencies: [ run-dag-nested-1 ]
            template: echo-sync
            arguments:
              parameters:
                - name: message
                  value: run-dag-nested-sync-1
          - name: run-dag-nested-sync-2
            dependencies: [ run-dag-nested-1 ]
            template: echo-sync
            arguments:
              parameters:
                - name: message
                  value: run-dag-nested-sync-2
          - name: run-dag-nested-sync-skipped
            when: >-
              "false" == "true"
            dependencies: [ run-dag-nested-1 ]
            template: echo-sync
            arguments:
              parameters:
                - name: message
                  value: run-dag-nested-sync-2
          - name: run-dag-nested-fail
            dependencies: [ run-dag-nested-1 ]
            template: fail
          - name: run-dag-final
            dependencies:
              - run-dag-nested-sync-1
              - run-dag-nested-sync-2
              - run-dag-nested-fail
              - run-dag-nested-sync-skipped
            template: echo-sync
            arguments:
              parameters:
                - name: message
                  value: run-dag-final

    - name: finalize-run-nested
      retryStrategy:
        limit: 3
        retryPolicy: "Always"
      steps:
        - - name: do-finalize
            template: echo
            arguments:
              parameters:
                - name: message
                  value: do-finalize-run-nested

    - name: echo
      inputs:
        parameters:
          - name: message
      script:
        name: main
        image: alpine:latest
        command: [ sh ]
        source: |
          echo "{{ "{{" }}inputs.parameters.message{{ "}}" }}"

    - name: echo-sync
      synchronization:
        semaphore:
          configMapKeyRef:
            name: test-argo-panic
            key: limit
      inputs:
        parameters:
          - name: message
      script:
        name: main
        image: alpine:latest
        command: [ sh ]
        source: |
          echo "{{ "{{" }}inputs.parameters.message{{ "}}" }}"

    - name: fail
      script:
        name: main
        image: alpine:latest
        command: [ sh ]
        source: |
          echo "I'm failing!!!"
          exit 1
```

**Steps to reproduce:**

1. Submit new workflow from the snippet above > workflow must fail as expected

![image](https://user-images.githubusercontent.com/876601/159363142-bdc07e72-892a-4944-a9a7-e5d41d111add.png)

2. Retry the failed workflow from Argo UI

![image](https://user-images.githubusercontent.com/876601/159363202-0ae99907-4859-4757-8e98-fb12ab94434d.png)

**Expected result**
The workflow must be retried and failed again on the same step (`run-dag-nested-fail`).

**Actual result**

- failed step (`run-dag-nested-fail`) disappeared 
- some of workflows steps are marked as still running
![image](https://user-images.githubusercontent.com/876601/159363702-7f4e160d-0cd7-458f-a978-f6379c667f8c.png)
- the workflow itself is marked as failed with `runtime error: invalid memory address or nil pointer dereference` message
![image](https://user-images.githubusercontent.com/876601/159363812-91f93a45-bc0f-47e1-a7bc-1b073f1593db.png)

Logs from Argo Workflows Controller pod:
```
time="2022-03-21T21:04:10.947Z" level=info msg="Update leases 200"
time="2022-03-21T21:04:14.206Z" level=info msg="Processing workflow" namespace=usr-p-vku workflow=argo-panic-7r4vs
time="2022-03-21T21:04:14.207Z" level=info msg="SG Outbound nodes of argo-panic-7r4vs-555401879 are [argo-panic-7r4vs-555401879]" namespace=usr-p-vku workflow=argo-panic-7r4vs
time="2022-03-21T21:04:14.208Z" level=error msg="Recovered from panic" namespace=usr-p-vku r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 197 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:194 +0xd4\npanic({0x1cde920, 0x336e400})\n\t/usr/local/go/src/runtime/panic.go:1047 +0x266\ngithub.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.(*SynchronizationStatus).GetStatus(...)\n\t/go/src/github.com/argoproj/argo-workflows/pkg/apis/workflow/v1alpha1/workflow_types.go:3272\ngithub.com/argoproj/argo-workflows/v3/workflow/sync.(*Manager).Release(0xc0006e8e70, 0xc000755b00, {0xc003090740, 0x0}, 0xc000b4b1e0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/sync/sync_manager.go:195 +0x2cb\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc000eeba40, {0x22ade28, 0xc00005c018}, 0xc00049ab60, {0xc0018bc381, 0x15})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:373 +0x6c6\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc000eeba40, {0x22ade28, 0xc00005c018}, 0xc00049ab60, {0xc001f53720, 0xd})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:438 +0x1f25\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc000eeba40, {0x22ade28, 0xc00005c018}, {0xc002448a20, 0x756f724770657400}, 0xc000af62c0, {0xc000c07728, 0x16}, 0xc00059c6c0, {0x228ea50, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x433\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000eeba40, {0x22ade28, 0xc00005c018}, {0xc002448a20, 0x22}, {0x228ea50, 0xc0003eef00}, 0x1, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1897 +0x232c\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc000eeba40, {0x22ade28, 0xc00005c018}, 0xc00049a8c0, {0xc001f53440, 0xa})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:513 +0x1888\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc000eeba40, {0x22ade28, 0xc00005c018}, {0xc000c075a8, 0x0}, 0xc000af6080, {0xc000c075c0, 0x16}, 0xc00117a6c0, {0x228fce0, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x433\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000eeba40, {0x22ade28, 0xc00005c018}, {0xc000c075a8, 0x17}, {0x228fce0, 0xc001300a80}, 0xc003983f00, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1897 +0x232c\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc000eeba40, {0x22ade28, 0xc00005c018}, {0xc003fe3800, 0x1, 0x4}, {0xc000c07548, 0x13}, 0xc000b12a78)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:247 +0x606\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc000eeba40, {0x22ade28, 0xc00005c018}, {0xc00217f060, 0x10}, 0xc003983f00, {0xc000c07458, 0x16}, 0xc000b51200, {0x228fce0, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:95 +0xcc5\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000eeba40, {0x22ade28, 0xc00005c018}, {0xc00217f060, 0x10}, {0x228fce0, 0xc000205a40}, 0xc003983ec0, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1891 +0x246c\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc000eeba40, {0x22ade28, 0xc00005c018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:349 +0x16a8\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc00007d800, {0x22ade28, 0xc00005c018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:749 +0x8ee\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0x0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:671 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f24b8c37d10)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x226b540, 0xc0007df890}, 0x1, 0xc0000b0720)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:295 +0x1a8c\n" workflow=argo-panic-7r4vs
time="2022-03-21T21:04:14.209Z" level=info msg="Updated phase Running -> Error" namespace=usr-p-vku workflow=argo-panic-7r4vs
time="2022-03-21T21:04:14.209Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=usr-p-vku workflow=argo-panic-7r4vs
time="2022-03-21T21:04:14.209Z" level=info msg="Marking workflow completed" namespace=usr-p-vku workflow=argo-panic-7r4vs
time="2022-03-21T21:04:14.209Z" level=info msg="Checking daemoned children of " namespace=usr-p-vku workflow=argo-panic-7r4vs
time="2022-03-21T21:04:14.214Z" level=info msg="cleaning up pod" action=deletePod key=usr-p-vku/argo-panic-7r4vs-1340600742-agent/deletePod
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
