### ISSUE TITLE
Semaphores do not respect the `configMapKeyRef.optional` flag

### ISSUE THREAD

**Issue by ebr** [argoproj/argo-workflows#8209]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

When setting a semaphore on a template, the `optional` flag has no effect. However, the [documentation]() the `semaphore` takes a `configMapKeyRef`. Thus my expectation was that the `optional` flag should be respected, and the semaphore to be ignored if the configmap or key do not exist.

What version are you running?

v3.3.1

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: semaphore-test-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: valid
            template: key-exists
          - name: invalid
            template: key-missing

    - name: key-exists
      synchronization:
        semaphore:
          configMapKeyRef:
            name: argo-sync
            # this key exists
            key: global-max-pods
            optional: true
      container:
        image: argoproj/argosay:v2
        command: ["cowsay"]
        args:
          - |
            this works

    - name: key-missing
      synchronization:
        semaphore:
          configMapKeyRef:
            name: sploosh
            key: this-key-does-not-exist
            optional: true
      container:
        image: argoproj/argosay:v2
        command: ["cowsay"]
        args:
          - |
            this doesn't work
```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

time="2022-03-22T14:45:26.075Z" level=info msg="Watch workflowtemplates 200"
time="2022-03-22T14:45:28.064Z" level=info msg="Processing workflow" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.073Z" level=info msg="Updated phase  -> Running" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.088Z" level=info msg="Created PDB resource for workflow." namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.088Z" level=info msg="Retry node semaphore-test-bgljv initialized Running" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.088Z" level=info msg="DAG node semaphore-test-bgljv-3136812531 initialized Running" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.089Z" level=info msg="All of node semaphore-test-bgljv(0).invalid dependencies [] completed" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.092Z" level=info msg="Skipped node semaphore-test-bgljv-995269934 initialized Error (message: Sync configuration key 'this-key-does-not-exist' not found in ConfigMap)" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.092Z" level=error msg="Mark error node" error="task 'semaphore-test-bgljv(0).invalid' errored: Sync configuration key 'this-key-does-not-exist' not found in ConfigMap" namespace=sandbox nodeName="semaphore-test-bgljv(0).invalid" workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.092Z" level=info msg="node semaphore-test-bgljv-995269934 message: task 'semaphore-test-bgljv(0).invalid' errored: Sync configuration key 'this-key-does-not-exist' not found in ConfigMap" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.092Z" level=info msg="All of node semaphore-test-bgljv(0).valid dependencies [] completed" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.095Z" level=info msg="Node semaphore-test-bgljv(0).valid acquired synchronization lock" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.095Z" level=info msg="Retry node semaphore-test-bgljv-1503598179 initialized Running" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.096Z" level=info msg="Pod node semaphore-test-bgljv-4139481134 initialized Pending" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.177Z" level=info msg="Created pod: semaphore-test-bgljv(0).valid(0) (semaphore-test-bgljv-4139481134)" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.177Z" level=info msg="TaskSet Reconciliation" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.177Z" level=info msg=reconcileAgentPod namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:28.190Z" level=info msg="Update workflows 200"
time="2022-03-22T14:45:28.191Z" level=info msg="Workflow update successful" namespace=sandbox phase=Running resourceVersion=377087398 workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.162Z" level=info msg="Processing workflow" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.174Z" level=info msg="Node semaphore-test-bgljv(0).valid acquired synchronization lock" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.174Z" level=info msg="node semaphore-test-bgljv-1503598179 phase Running -> Succeeded" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.174Z" level=info msg="node semaphore-test-bgljv-1503598179 finished: 2022-03-22 14:45:38.174489916 +0000 UTC" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.174Z" level=info msg="Outbound nodes of semaphore-test-bgljv-3136812531 set to [semaphore-test-bgljv-995269934 semaphore-test-bgljv-4139481134]" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.174Z" level=info msg="node semaphore-test-bgljv-3136812531 phase Running -> Error" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.174Z" level=info msg="node semaphore-test-bgljv-3136812531 finished: 2022-03-22 14:45:38.174560207 +0000 UTC" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.174Z" level=info msg="Checking daemoned children of semaphore-test-bgljv-3136812531" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.174Z" level=info msg="1 child nodes of semaphore-test-bgljv failed. Trying again..." namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.174Z" level=info msg="DAG node semaphore-test-bgljv-3740953910 initialized Running" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.174Z" level=info msg="All of node semaphore-test-bgljv(1).invalid dependencies [] completed" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.179Z" level=info msg="Skipped node semaphore-test-bgljv-2255972131 initialized Error (message: Sync configuration key 'this-key-does-not-exist' not found in ConfigMap)" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.179Z" level=error msg="Mark error node" error="task 'semaphore-test-bgljv(1).invalid' errored: Sync configuration key 'this-key-does-not-exist' not found in ConfigMap" namespace=sandbox nodeName="semaphore-test-bgljv(1).invalid" workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.179Z" level=info msg="node semaphore-test-bgljv-2255972131 message: task 'semaphore-test-bgljv(1).invalid' errored: Sync configuration key 'this-key-does-not-exist' not found in ConfigMap" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.179Z" level=info msg="All of node semaphore-test-bgljv(1).valid dependencies [] completed" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.183Z" level=info msg="Node semaphore-test-bgljv(1).valid acquired synchronization lock" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.183Z" level=info msg="Retry node semaphore-test-bgljv-907035194 initialized Running" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.183Z" level=info msg="Pod node semaphore-test-bgljv-1984551009 initialized Pending" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.212Z" level=info msg="Created pod: semaphore-test-bgljv(1).valid(0) (semaphore-test-bgljv-1984551009)" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.212Z" level=info msg="TaskSet Reconciliation" namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.212Z" level=info msg=reconcileAgentPod namespace=sandbox workflow=semaphore-test-bgljv
time="2022-03-22T14:45:38.226Z" level=info msg="Update workflows 200"

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by ebr** [comment]
Would it be possible to consider respecting this `optional`? If so, I can make it a feature request, as it would be quite useful for us. Current use case is that we have a template whose concurrency must be limited in some cases but not others. So we are parametrizing the `key:` as an input param, e.g.:

```
    - name: large-template-sometimes-limited
      synchronization:
        semaphore:
          configMapKeyRef:
            name: argo-sync
            key: "{{inputs.parameters.collection-name}}"
            optional: true            #doesn't work
      inputs:
        parameters:
          - name: collection-name
```

This way if `collection-name` key exists in the `argo-sync` configmap, we can limit the concurrency of this template for that "collection" only, and ignore it in other cases (run unconstrained). As a workaround instead we have to either:

- A: duplicate the template and call different templates based on whether it needs to be concurrency-limited, which is terrible for maintainability
- B: create some "catch-all" entry in the configmap with a "very large" value, and use it as a default, which is not the end of the world, but a bit of a code smell... and also potentially causes unnecessary work having to track lock holders on a "fake" semaphore?

**Comment by sarabala1979** [comment]
> I think this is expected behaviour, that optional is ignored. I'll let @sarabala1979 confirm.

yes. Optional will be ignored.  key has to be defined in configmap for the semaphore.
you can achieve your usecase using `when` condition  in step template to execute the `semaphore` template or   or  non `semaphore` template.

**Comment by ebr** [comment]
> you can achieve your usecase using when condition

Thank you - I realize that, but as I mentioned, that would require duplicating the entire template. For now I've found a workaround using conditional expressions:

```
synchronization:
    semaphore:
        configMapKeyRef:
            name: argo-sync
            key: |-
              {{=(inputs.parameters["collection"] startsWith "resticted-" && inputs.parameters["license-type"] != "demo-license" ) ? "max-licenses" : "sem-fallback"}}
```

and  `sem-fallback: "9999999"` is set in the `argo-sync` configmap.

Which technically works, but is kind of a hack :)
