### ISSUE TITLE
key unsupported: cannot get key for artifact location, because it is invalid even if artifact location is configured

### ISSUE THREAD

**Issue by gai6948** [argoproj/argo-workflows#8219]
## Checklist

 

* [X] Double-checked my configuration.
* [X] Tested using the latest version.
* [X] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Even if s3 artifact location is configured, error is shown:
```
Error (exit code 1): key unsupported: cannot get key for artifact location, because it is invalid
```

What version are you running?
3.2.7

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: blog-analysis-scraping-workflow
  namespace: blog-analysis
spec:
  entrypoint: scrap
  templates:
    - name: scrap
      container:
        image: gc6948/elloh:latest
        command: [sh, ./docker-entrypoint.sh]
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: access-key-id
                name: vyon--s3-credentials
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: secret-access-key
                name: vyon--s3-credentials
      outputs:
        artifacts:
          - name: crawled-websites
            path: /home/appuser/blog-crawler/output
            archive:
              none: {}
            s3:
              bucket: vyon--backup-vpg64naw
              insecure: false
              accessKeySecret:
                name: vyon--s3-credentials
                key: access-key-id
              secretKeySecret:
                name: vyon--s3-credentials
                key: secret-access-key

```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
