### ISSUE TITLE
python sdk auth bug

### ISSUE THREAD

**Issue by chunyang-wen** [argoproj/argo-workflows#8230]
Try to use `BearerToken` as the authentication method, but it seems that there are bugs here.
## Argo-workflows version
```yaml
Name: argo-workflows
Version: 6.3.1
Summary: Argo Workflows API
Home-page:
Author: OpenAPI Generator community
Author-email: team@openapitools.org
License: UNKNOWN
Location: /Users/chunyang/anaconda3/envs/py38/lib/python3.8/site-packages
Requires: python-dateutil, urllib3
Required-by:
```

## Reproduce code
```python
import os
from pprint import pprint

import yaml

import argo_workflows
from argo_workflows.api import workflow_service_api


os.environ["ARGO_TOKEN"] = "ZZZ"

api_key = {"BearerToken": os.environ["ARGO_TOKEN"]}
api_key_prefix = {"BearerToken": "Bearer"}
host = "https://localhost:2746" # url of argo server
namespace = "argo"
configuration = argo_workflows.Configuration(
    host=host,
    api_key=api_key,
    api_key_prefix=api_key_prefix,
)
configuration.verify_ssl = False

api_client = argo_workflows.ApiClient(configuration)
api_instance = workflow_service_api.WorkflowServiceApi(api_client)
resp = api_instance.list_workflows(namespace, async_req=False)
pprint(resp)
```

### Token from here

https://argoproj.github.io/argo-workflows/access-token/#token-creation

curl got correct results.

```bash
curl --request GET --url https://localhost:2746/api/v1/workflows/default -H "Authorization: Bearer ${TOKEN}"

{"metadata":{"resourceVersion":"80426099"},"items":null}%
```

### No auth is passed in
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/2911134/159835895-b88c0710-feee-4e08-9850-3f325f6accee.png">

### When no workflows executed, list_workflows fails

By manually passed `auth = ["BearerToken"]` to fix previous bug, I got following error. Argo server is deployed from ground up before accessing it. No workflows have been executed.

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/2911134/159835964-11233ca5-e75a-400a-b41a-215a92d6ce6a.png">
