### ISSUE TITLE
Outputs are not available unless you have a dag or steps in the workflow

### ISSUE THREAD

**Issue by lucastheisen** [argoproj/argo-workflows#8236]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

I created a workflow that has an `entrypoint` that is a `container` template and an `onExit` that is also a `container` template.  The `entrypoint` generates a report that the `onExit` sends out as notification.

What version are you running?

`github.com/argoproj/argo-workflows/manifests/cluster-install?ref=v3.2.8`

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    debug: yup
  name: global-outputs-for-onexit
spec:
  entrypoint: entry
  onExit: notify

  templates:

  - container:
      args:
      - |
        cat > /tmp/output/links <<EOF
        * [foo](https://foo.com)
        * [bar](https://bar.com)
        EOF
      command:
      - bash
      - -c
      image: 'centos:7'
      volumeMounts:
      - name: output
        mountPath: /tmp/output
    name: entry
    outputs:
      parameters:
      - globalName: links
        name: links
        valueFrom:
          path: /tmp/output/links
    volumes:
    - name: output
      emptyDir: {}

  - container:
      command:
      - printf
      - "links are:\n<<%s>>\n"
      - "{{workflow.outputs.parameters.links}}"
      image: 'centos:7'
    name: notify
```

I dont have access to workflow controller logs but the client shows:

```bash
FATA[2022-03-24T11:35:50.987Z] Failed to submit workflow: templates.notify: failed to resolve {{workflow.outputs.parameters.links}}
FATA[2022-03-24T11:35:51.124Z] rpc error: code = NotFound desc = workflows.argoproj.io "ltheisen-tester" not found
```

As a workaround, if I add a `steps` template and use that as `entry` and only call my other template, this does indeed work:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    debug: yup
  name: global-outputs-for-onexit
spec:
  entrypoint: entry
  onExit: notify

  templates:

  - name: entry
    steps:
    - - name: generate
        template: generate

  - container:
      args:
      - |
        cat > /tmp/output/links <<EOF
        * [foo](https://foo.com)
        * [bar](https://bar.com)
        EOF
      command:
      - bash
      - -c
      image: 'centos:7'
      volumeMounts:
      - name: output
        mountPath: /tmp/output
    name: generate
    outputs:
      parameters:
      - globalName: links
        name: links
        valueFrom:
          path: /tmp/output/links
    volumes:
    - name: output
      emptyDir: {}

  - container:
      command:
      - printf
      - "links are:\n<<%s>>\n"
      - "{{workflow.outputs.parameters.links}}"
      image: 'centos:7'
    name: notify
```

Gives:

```console
Name:                global-outputs-for-onexit
Namespace:           pd-auto
ServiceAccount:      argo-workflow-controller
Status:              Succeeded
Conditions:
 PodRunning          False
 Completed           True
Created:             Thu Mar 24 11:42:21 -0400 (19 seconds ago)
Started:             Thu Mar 24 11:42:21 -0400 (19 seconds ago)
Finished:            Thu Mar 24 11:42:41 -0400 (now)
Duration:            20 seconds
Progress:            2/2
ResourcesDuration:   8s*(100Mi memory),4s*(1 cpu)
Output Parameters:
  links:             * [foo](https://foo.com)
* [bar](https://bar.com)

STEP                                 TEMPLATE  PODNAME                               DURATION  MESSAGE
 ✔ global-outputs-for-onexit         entry
 └───✔ generate                      generate  global-outputs-for-onexit-1046070556  5s

 ✔ global-outputs-for-onexit.onExit  notify    global-outputs-for-onexit-1423525930  4s
```

I believe that this may have been a design decision in that if you dont have at least 2 templates, what good is an output (no consumer).  But it is surprising to see that `onExit` appears to not be considered a second template.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
