### ISSUE TITLE
CronWorkflow not starting - error in entry template execution Pod is invalid [spec.containers[0].image: Required value.

### ISSUE THREAD

**Issue by p-glomski** [argoproj/argo-workflows#8244]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
I've tried to run example CronWorkflow from your repository to see how it works before deploying anything more advanced:
https://github.com/argoproj/argo-workflows/blob/master/examples/cron-workflow.yaml

What version are you running?
Argo-Workflows version: v.3.3.1
Kubernetes version: v1.22.7 and v1.20.15

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "* * * * *"
  timezone: "America/Los_Angeles"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: docker/whalesay:latest
          command: [cowsay]
          args: ["🕓 hello world. Scheduled on: {{workflow.scheduledTime}}"]
```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 
time="2022-03-25T08:31:00.000Z" level=info msg="Running hello-world" namespace=argo workflow=hello-world
time="2022-03-25T08:31:00.013Z" level=info msg="Create workflows 201"
time="2022-03-25T08:31:00.014Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.018Z" level=info msg="Get configmaps 404"
time="2022-03-25T08:31:00.018Z" level=warning msg="Non-transient error: configmaps \"artifact-repositories\" not found"
time="2022-03-25T08:31:00.019Z" level=info msg="resolved artifact repository" artifactRepositoryRef=default-artifact-repository
time="2022-03-25T08:31:00.019Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.019Z" level=info msg="Pod node hello-world-1648197060 initialized Pending" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.020Z" level=info msg="Patch cronworkflows 200"
time="2022-03-25T08:31:00.021Z" level=info msg="Processing argo/hello-world" cronWorkflow=argo/hello-world
time="2022-03-25T08:31:00.021Z" level=info msg="CronWorkflow argo/hello-world added" cronWorkflow=argo/hello-world
time="2022-03-25T08:31:00.031Z" level=info msg="Create events 201"
time="2022-03-25T08:31:00.031Z" level=info msg="Create pods 422"
time="2022-03-25T08:31:00.031Z" level=warning msg="Non-transient error: Pod \"hello-world-1648197060\" is invalid: [spec.containers[0].image: Required value, spec.initContainers[0].image: Required value]"
time="2022-03-25T08:31:00.032Z" level=info msg="Failed to create pod hello-world-1648197060 (hello-world-1648197060): Pod \"hello-world-1648197060\" is invalid: [spec.containers[0].image: Required value, spec.initContainers[0].image: Required value]" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.032Z" level=warning msg="Non-transient error: Pod \"hello-world-1648197060\" is invalid: [spec.containers[0].image: Required value, spec.initContainers[0].image: Required value]"
time="2022-03-25T08:31:00.032Z" level=error msg="Mark error node" error="Pod \"hello-world-1648197060\" is invalid: [spec.containers[0].image: Required value, spec.initContainers[0].image: Required value]" namespace=argo nodeName=hello-world-1648197060 workflow=hello-world-1648197060
time="2022-03-25T08:31:00.032Z" level=info msg="node hello-world-1648197060 phase Pending -> Error" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.032Z" level=info msg="node hello-world-1648197060 message: Pod \"hello-world-1648197060\" is invalid: [spec.containers[0].image: Required value, spec.initContainers[0].image: Required value]" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.032Z" level=info msg="node hello-world-1648197060 finished: 2022-03-25 08:31:00.032455969 +0000 UTC" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.032Z" level=error msg="error in entry template execution" error="Pod \"hello-world-1648197060\" is invalid: [spec.containers[0].image: Required value, spec.initContainers[0].image: Required value]" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.032Z" level=warning msg="Non-transient error: Pod \"hello-world-1648197060\" is invalid: [spec.containers[0].image: Required value, spec.initContainers[0].image: Required value]"
time="2022-03-25T08:31:00.032Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.032Z" level=info msg="Updated message  -> error in entry template execution: Pod \"hello-world-1648197060\" is invalid: [spec.containers[0].image: Required value, spec.initContainers[0].image: Required value]" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.033Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.033Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hello-world-1648197060
time="2022-03-25T08:31:00.036Z" level=info msg="Create events 201"
time="2022-03-25T08:31:00.039Z" level=info msg="cleaning up pod" action=deletePod key=argo/hello-world-1648197060-1340600742-agent/deletePod
time="2022-03-25T08:31:00.044Z" level=info msg="Delete pods 404"
time="2022-03-25T08:31:00.044Z" level=info msg="Update workflows 200"
time="2022-03-25T08:31:00.046Z" level=info msg="Workflow update successful" namespace=argo phase=Error resourceVersion=171698488 workflow=hello-world-1648197060
time="2022-03-25T08:31:00.051Z" level=info msg="DeleteCollection workflowtaskresults 200"

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
