### ISSUE TITLE
Groups are not working with AWS Cognito sso integration

### ISSUE THREAD

**Issue by dribeiro-eTF1** [argoproj/argo-workflows#8247]
## Summary

We are running Argo Workflow with the latest version and using AWS Cognito as our identity provider.

The SSO authentication works nicely, but we do not see the users's groups. Thing is, we are using the same Cognito with Argo CD and there, groups are correctly seen.

We have seen that others have similar issues and tried to use `customGroupClaimName` or `userInfoPath`, but without success.

Researches indicates that others seems to get the groups without any particular configuration.

Is there a way to display more logs to investigate on the SSO and RBAC aspects?

## Diagnostics

The patch adding the SSO configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  sso: |
    issuer: https://cognito-idp.eu-west-3.amazonaws.com/<our cognito pool id>
    sessionExpiry: 240h
    clientId:
      name: workflow-sso
      key: client-id-key
    clientSecret:
      name: workflow-sso
      key: client-secret-key
    redirectUrl: https://<our argo server URL>/oauth2/callback
    scopes:
    - openid
    - profile
    - email
    rbac:
      enabled: true
```

There is this line in argo server logs (but not sure if it is useful):
```
time="2022-03-25T10:27:41.629Z" level=info msg="SSO configuration" clientId="{{workflow-sso} client-id-key <nil>}" insecureSkipVerify=false issuer="https://cognito-idp.eu-west-3.amazonaws.com/<our cognito pool id>" issuerAlias=DISABLED redirectUrl="https://<our argo server URL>/oauth2/callback" scopes="[openid profile email openid]"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
