### ISSUE TITLE
Hardcoded namespaces in crb for kustomize cluster-install

### ISSUE THREAD

**Issue by tiwarisanjay** [argoproj/argo-workflows#8250]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary
Following file has hardcoded namespaces in clusterrolebinding which is holding us to change namespace when we call the module with new namespace : 
[manifestesworkflow-controller-clusterrolebinding.yaml ](https://github.com/argoproj/argo-workflows/blob/v3.3.1/manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrolebinding.yaml)

[argo-server-clusterolebinding.yaml ](https://github.com/argoproj/argo-workflows/blob/v3.3.1/manifests/cluster-install/argo-server-rbac/argo-server-clusterolebinding.yaml)

What happened/what you expected to happen?
Issue : 
Following Code should change all namsepaces to argoworkflow namespace : 
```yaml  
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-workflows.git/manifests/cluster-install/?ref=v3.2.4

namespace: argoworkflow
```
But I still see clusterrolebinding has namespaces as argo : 
```yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cluster-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-server-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-server
  namespace: argo
``` 
What version are you running?
3.3.1
## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-workflows.git/manifests/cluster-install/?ref=v3.2.4

namespace: argoworkflow
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
