### ISSUE TITLE
New Configmaps needs to have configmapType: Parameter to be usable

### ISSUE THREAD

**Issue by louisnow** [argoproj/argo-workflows#8261]
## Checklist

 

* [x] Double-checked my configuration.
* [ ] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

1. I have configmaps from before 3.2.9
2. I can reference them in my input parameters though they lack `configmap-type` 
3. New Configmaps without `workflows.argoproj.io/configmap-type: Parameter` don't interpolate.

What version are you running?
v3.2.9
Emissary Executor

## Diagnostics
<img width="324" alt="Screenshot 2022-03-28 at 10 20 09 AM" src="https://user-images.githubusercontent.com/6024271/160331545-20a7205d-0ee3-4e3f-8109-8ca7832ad913.png">

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

Configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: retry-sample
data:
  dummy: "{}"
  dummy1: ""
```
Workflow
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: retry-sample
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: message
            valueFrom:
              default: "hello"
              configMapKeyRef:
                name: retry-sample
                key: dummy
                optional: true
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

Referencing older configmaps that were created before 3.2.9 works but not new ones unless they have the label `workflows.argoproj.io/configmap-type: Parameter`

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.
