### ISSUE TITLE
ConfigmapRef does not respect optional and default keyword

### ISSUE THREAD

**Issue by louisnow** [argoproj/argo-workflows#8262]
## Checklist

 

* [x] Double-checked my configuration.
* [ ] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
`Optional` and `default` keywords are not respected when using  `configMapKeyRef`.
Workflow errors while trying to reference a key that does not exist.

What version are you running?
v3.2.9
Emissary Executor

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: retry-sample
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  dummy: "{}"
  dummy1: ""
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: retry-sample
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: message
            valueFrom:
              default: "hello"
              configMapKeyRef:
                name: retry-sample
                key: dummy-missing
                optional: true
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
