### ISSUE TITLE
Workflow with Http call stuck  on Pending State

### ISSUE THREAD

**Issue by srajeev** [argoproj/argo-workflows#8300]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

I was trying to do an Http Call from Workflow. But workflow got stuck in Pending State. 
I noticed this bug - https://github.com/argoproj/argo-workflows/pull/7084 
Thought this is fixed. But I am seeing that now also. I am on v3.3.0

What version are you running?
v3.3.0

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml

metadata:
  name: delightful-python
  namespace: default
  labels:
    example: 'true'
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: get-google-homepage
            template: http
            arguments:
              parameters: [{name: url, value: "https://www.google.com"}]
    - name: http
      inputs:
        parameters:
          - name: url
      http:
        timeoutSeconds: 20 # Default 30
        url: "{{inputs.parameters.url}}"
        method: "GET" 
        headers:
          - name: "x-header-name"
            value: "test-value"
        successCondition: "response.body contains \"google\""  
        body: "test body"  

```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

time="2022-04-01T09:29:28.761Z" level=info msg="Processing workflow" namespace=default workflow=delightful-python
time="2022-04-01T09:29:28.762Z" level=info msg=updateAgentPodStatus namespace=default workflow=delightful-python
time="2022-04-01T09:29:28.763Z" level=info msg=assessAgentPodStatus namespace=default podName=delightful-python-1340600742-agent
time="2022-04-01T09:29:28.764Z" level=info msg="Workflow step group node delightful-python-4228632240 not yet completed" namespace=default workflow=delightful-python
time="2022-04-01T09:29:28.764Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=delightful-python
time="2022-04-01T09:29:28.764Z" level=info msg=reconcileAgentPod namespace=default workflow=delightful-python

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${delightful-python},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by srajeev** [comment]
kubectl get pods - list this pod that is pending with failure status **CrashLoopBackOff**. Also  Sharing  **logs from  that  pod** below:

time="2022-04-04T13:47:10.429Z" level=info msg="Starting Workflow Executor" version=v3.3.0
time="2022-04-04T13:47:10.430Z" level=info msg="Starting Agent" requeueTime=10s taskWorkers=16 workflow=daqe-midas-dailyrun-qcprocess-sensor-workflowd869b
time="2022-04-04T13:47:10.458Z" level=info msg="Watch workflowtasksets 403"
Error: unknown (get workflowtasksets.argoproj.io)
unknown (get workflowtasksets.argoproj.io)

**Comment by alexec** [comment]
You`ve installed `workflowtaskset` CRD, but you can see you're getting a 403 error. Please add the permissions to the executor role. 

https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start/base/agent-role.yaml

**Comment by yeongu-dev** [comment]
The same error as above occurs in the part using http in the workflow I am using. I think I'm in the same situation, so I used srajeev's workflow as is. The minimum privileges to run on the Agent are thought to be set. Role and RoleBinding are as follows.

Is there something I'm missing out on?

* I use argo-workflow v3.3.8 (Helm chart v0.16.6)

* Role is ...

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-workflow
  namespace: argo-workflows
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: argo-workflows
    meta.helm.sh/release-namespace: argo-workflows
rules:
  - verbs:
      - get
      - watch
      - patch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
  - verbs:
      - create
    apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
  - verbs:
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
  - verbs:
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
      - workflowtasksets
```

* RoleBinding is ...
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-workflow
  namespace: argo-workflows
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: argo-workflows
    meta.helm.sh/release-namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-workflow
```
