### ISSUE TITLE
Ask for help! I want to get the state of each step using hooks onExit.

### ISSUE THREAD

**Issue by LingClassmate** [argoproj/argo-workflows#8305]
Ask for help! I want to get the status of each step using the hooks configuration as follows:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: container-on-exit-
spec:
  entrypoint: step-template
  templates:
    - name: step-template
      steps:
        - - name: stepA
            template: echo1
            hooks: 
              exit:
                template: exitContainer
                arguments:
                    parameters:
                      - name: Containerstatus
                        value: "{{steps.stepA.status}}"
        - - name: stepB
            template: echo2
            hooks: 
              exit:
                template: exitContainer
                arguments:
                    parameters:
                      - name: Containerstatus
                        value: "{{steps.stepB.status}}"
            
    - name: echo1
      container:
        image: alpine:3.15
        command: [sh, -c]
        args: ["echo \"stepA\""]
    - name: echo2
      container:
        image: alpine:3.15
        command: [sh, -c]
        args: ["echo \"stepB\" ;exit 1"]

    - name: exitContainer
      inputs:
        parameters:
          - name: Containerstatus
      container:
        image: alpine:3.15
        command: [sh, -c]
        args: ["echo  ContainerStatus: {{inputs.parameters.Containerstatus}}"]
```

OnExit output:
```
ContainerStatus: {{steps.stepA.status}}
ContainerStatus: {{steps.stepB.status}}
```

But I can't get the step state, I can only get the strings, is there any other way to solve my problem?
