### ISSUE TITLE
Bitbucket webhook test connection fails with HTTP 401 and "token not valid for running mode"

### ISSUE THREAD

**Issue by sandeepitachi** [argoproj/argo-workflows#8330]
## Summary

I'm trying to trigger the workflows using webhooks and followed this link [webhooks](https://argoproj.github.io/argo-workflows/webhooks/) 
But bitbucket webhook test connection fails with "token not valid for running mode"

Argo server - v3.3.1 and this argo-server is managed by ArgoCD running v2.2.3
Installation - Cluster-install
Auth-modes - SSO and client

Overlays of argo-server deployment is below
```sh
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --auth-mode=client
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --auth-mode=sso
```

# Logs from the argo-server:
```sh
"finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2022-04-07T15:49:19Z" grpc.time_ms=0.074 span.kind=server system=grpc
15
time="2022-04-07T15:49:29.487Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2022-04-07T15:49:29Z" grpc.time_ms=0.077 span.kind=server system=grpc
14
time="2022-04-07T15:49:30.082Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2022-04-07T15:49:30Z" grpc.time_ms=0.085 span.kind=server system=grpc
13
time="2022-04-07T15:49:30.534Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2022-04-07T15:49:30Z" grpc.time_ms=0.049 span.kind=server system=grpc
12
time="2022-04-07T15:49:30.881Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2022-04-07T15:49:30Z" grpc.time_ms=0.058 span.kind=server system=grpc
11
time="2022-04-07T15:49:31.047Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2022-04-07T15:49:31Z" grpc.time_ms=0.049 span.kind=server system=grpc
10
time="2022-04-07T15:49:31.219Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2022-04-07T15:49:31Z" grpc.time_ms=0.048 span.kind=server system=grpc
9
time="2022-04-07T15:49:31.364Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2022-04-07T15:49:31Z" grpc.time_ms=0.059 span.kind=server system=grpc
8
time="2022-04-07T15:49:31.534Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2022-04-07T15:49:31Z" grpc.time_ms=0.049 span.kind=server system=grpc
7
time="2022-04-07T15:49:31.689Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2022-04-07T15:49:31Z" grpc.time_ms=0.059 span.kind=server system=grpc
# If the workflow's pods have not been created, you can skip the rest of the diagnostics.


```

Note: The test connection works successfully if I use `auth-mode=server` with SSO. But that makes server open for all in the org. Would like to use just SSO and client mode

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sandeepitachi** [comment]
I was careful about that!
In secret, used bitbucket-sa with type 'bitbucketserver' and secret 'abc'. Used same 'abc' in the webhook test connection
```sh
data:
  bitbucket-sa: ++++++++
kind: Secret
```
Service account used
```sh
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: argo-workflows
  name: bitbucket-sa
  namespace: argo
```
Note:
It's weird - we have another argo-server (just namespace install) without managed by argocd - it works smoothly on that. Used same sa and secret name **argo-workflows-webhook-clients** value 'abc'

**Comment by alexec** [comment]
These are the values from the quick-start:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github.com
---
# Just enough permissions to submit a workflow template.
# You could tighten this further (but perhaps impractically) by using `resourceNames`
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: submit-workflow-template
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workfloweventbindings
    verbs:
      - list
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtemplates
    verbs:
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github.com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submit-workflow-template
subjects:
  - kind: ServiceAccount
    name: github.com
    namespace: argo
---
kind: Secret
apiVersion: v1
metadata:
  name: argo-workflows-webhook-clients
# The data keys must be the name of a service account.
stringData:
  # https://support.atlassian.com/bitbucket-cloud/docs/manage-webhooks/
  bitbucket.org: |
    type: bitbucket
    secret: "my-uuid"
  # https://confluence.atlassian.com/bitbucketserver/managing-webhooks-in-bitbucket-server-938025878.html
  bitbucketserver: |
    type: bitbucketserver
    secret: "shh!"
  # https://developer.github.com/webhooks/securing/
  github.com: |
    type: github
    secret: "shh!"
  # https://docs.gitlab.com/ee/user/project/integrations/webhooks.html
  gitlab.com: |
    type: gitlab
    secret: "shh!"
```
