### ISSUE TITLE
I want to get the NAME of the last step, not the POD NAME. Is this possible?

### ISSUE THREAD

**Issue by LingClassmate** [argoproj/argo-workflows#8349]
I want to get the NAME of the last step, not the POD NAME. Is this possible?
How do I get the `step1` name?

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: step1
            template: echo1
        - - name: step2
            template: echo2
            arguments:
              parameters:
                - name: status
                  value: "{{steps.step1.status}}"
                - name: node_name
                  value: "{{steps.step1.name}}"
    
    - name: echo1
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo hello"]

    - name: echo2
      inputs:
        parameters:
        - name: node_name
        - name: status
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"step1 status : {{inputs.parameters.node_name}}\" ;
                echo \"step1 name : {{inputs.parameters.status}}\" 
              "]
```

The output:
```
step1 status : lifecycle-hook-tmpl-level-q949k-1951102024
step1 name : Succeeded
```
