### ISSUE TITLE
Authentication Failure with Git Artifacts Inputs

### ISSUE THREAD

**Issue by tacf** [argoproj/argo-workflows#8380]
## Checklist

 

* [X] Double-checked my configuration.
* [X] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

Using git artifacts as input throws 'authentication error' in latest version. This started happening last week with local setup that i was testing. The solution was to move to the comunity helm chart (i wasn't able to easily bump down the controller version without additional weird errors) and forcing controller to version 'v3.3.1' instead of latest.

During the whole process nothing was changed with PAT or it's access to the repo. The same PAT used (and which worked) and te beginning, stopped working and then worked again after the downgrade to older container version. 

What version are you running?

I'm runing the quick postgress example in the docs. Kubernetes v1.19.16

## Diagnostics

1. Create a valida PAT on github
2. Configure simple workflow that inputs with PAT from that repo

Please let me know what other details i can provide ir order to allow for reproducibility.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Do not run `:latest` except for development. It is the bleeding edge. This is most likely caused by #7486 .

**Comment by alexec** [comment]
I don't have enough information it this PR to reproduce the issue. I know you cannot share your PAT. Instead, what about spending 30m on a Zoom?

https://bit.ly/book-30m-with-argo-team

**Comment by mgoodness** [comment]
I'm getting this with `:latest` as well, when `git.revision` is a specific commit hash. See also [this comment](https://github.com/argoproj/argo-workflows/issues/1428#issuecomment-1111100783) from @auswells.

**Comment by alexec** [comment]
The bug is in this line of code:

https://github.com/argoproj/argo-workflows/blob/master/workflow/artifacts/git/git.go#L155

It is missing auth. It should look more like this:

https://github.com/argoproj/argo-workflows/blob/16fef4e5498fac88dc80d33d653c99fec641150d/workflow/artifacts/git/git.go#L137

@mgoodness would you like to submit a PR to fix?

**Comment by mgoodness** [comment]
Woot! Sure, PR incoming.

**Comment by yeongsheng-tan** [comment]
I'm still getting the error on argo-workflows master branch from commit hash [61211f9d](https://github.com/argoproj/argo-workflows/commit/61211f9db1568190dd46b7469fa79eb6530bba73). Plus `singleBranch` with `branch` throws workflow json error:
```
❯ argo submit -n argo --watch ms-auth-git.yaml
FATA[2022-06-30T22:49:51.704Z] Failed to parse workflow: json: unknown field "branch"
```

My workflow is a modified version from [input-artifact-git.yaml](https://github.com/argoproj/argo-workflows/blob/master/examples/input-artifact-git.yaml)

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ms-auth-git-
spec:
  entrypoint: git-clone
  templates:
  - name: git-clone
    inputs:
      artifacts:
      - name: ms-auth-source
        path: /src
        git:
          repo: https://gitlab.com/yeong.sheng1/ms-auth.git
          usernameSecret:
            name: gitlab-access
            key: username
          passwordSecret:
            name: gitlab-access
            key: password
          singleBranch: true
          branch: "develop"
    container:
      image: alpine/git:latest
      command: [sh, -c]
      args: ["git status && ls && cat README.md"]
      workingDir: /src
```
