### ISSUE TITLE
Enhanced depends logic not working with nested dags

### ISSUE THREAD

**Issue by gandeevan** [argoproj/argo-workflows#8410]
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
    - name: diamond
      dag:
        tasks:
          - name: A
            template: nested-dag
          - name: B-should-execute
            depends: A.Succeeded || A.Skipped || A.Daemoned || A.Failed || A.Errored
            template: pass

    - name: nested-dag
      dag:
        tasks:
        - name: A-nested
          template: fail
        - name: B-nested
          depends: "A-nested"
          template: pass

    - name: pass
      container:
        image: alpine:3.7
        command:
          - sh
          - -c
          - exit 0
    - name: fail
      container:
        image: alpine:3.7
        command:
          - sh
          - -c
          - exit 1
```

I expect the "B-should-execute" task to run in this workflow. However, looks like that's not happening. I'm not sure if I'm missing something here. Would appreciate any help! Thanks :)

Version: 3.2.9
Executor: emissary
