### ISSUE TITLE
Determine the original file type and name from an artifact

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8435]
Artifacts go through a complex process when being saved. Can we figure out what the original artifact was from the artifact+tgz file?

By default, `tar` is used. `zip` is either broken, or meaningless for uploads.

```yaml
        - archive:
            none: {}
          name: none-file
          path: /tmp/message
          s3:
            # file
            key: both-dwg4w/both-dwg4w/message
        - archive:
            none: {}
          name: none-dir
          path: /tmp
          s3:
            # directory
            key: both-dwg4w/both-dwg4w/tmp
```

```yaml
        - archive:
            tar: {}
          name: tar-file
          path: /tmp/message
          s3:
            # archive containing only one file, which is the `message`
            key: both-dwg4w/both-dwg4w/tar-file.tgz
        - archive:
            tar: {}
          name: tar-dir
          path: /tmp
          s3:
            # archive containing at least 2 files, the first file is a directory
            key: both-dwg4w/both-dwg4w/tar-dir.tgz
```

So:

```golang
isNone :=  filepath.Base(a.Path) == filepath.Base(a.Key)
```

It is *possible* they uploaded a `.tgz`, so I don't think you can only check suffix
