### ISSUE TITLE
When I changed steps to DAg, STEP-1 did not implement hooks for "Running" state, why?

### ISSUE THREAD

**Issue by LingClassmate** [argoproj/argo-workflows#8449]
When I changed steps to DAg, STEP-1 did not implement hooks for "Running" state, why?

**life-cycle-hooks-tmpl-level.yaml**

https://github.com/argoproj/argo-workflows/blob/45730a9cdeb588d0e52b1ac87b6e0ca391a95a81/examples/life-cycle-hooks-tmpl-level.yaml

I changed steps to daG YAML configuration:

```yaml
    apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    metadata:
      generateName: lifecycle-hook-tmpl-level-
    spec:
      entrypoint: main
      templates:
        - name: main
          dag:
            tasks:
            - name: step-1
              hooks:
                exit:
                  expression: tasks["step-1"].status == "Running"
                  template: http
                success:
                  expression: tasks["step-1"].status == "Succeeded"
                  template: http
              template: echo
            - name: step2
              dependencies: [step-1]
              hooks:
                exit:
                  expression: tasks.step2.status == "Running"
                  template: http
                success:
                  expression: tasks.step2.status == "Succeeded"
                  template: http
              template: echo
        
        - name: echo
          container:
            image: alpine:3.6
            command: [sh, -c]
            args: ["echo \"it was heads\"; sleep 10s"]
        
        - name: http
          http:
            url: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"
```

![image-20220422172237497](https://s2.loli.net/2022/04/22/UYNwpEdh819Qe73.png)

**Comment by terrytangyuan** [comment]
Could you attach necessary debugging information as requested in the issue template? Could you confirm that this is working for DAG?

**Comment by sarabala1979** [comment]
Running hook’s name is exit. Exit is a reserved name for exit handler. Can you change the name and execute it?

**Comment by sarabala1979** [comment]
@LingClassmate try below spec

```yaml
apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    metadata:
      generateName: lifecycle-hook-tmpl-level-
    spec:
      entrypoint: main
      templates:
        - name: main
          dag:
            tasks:
            - name: step-1
              hooks:
                running:
                  expression: tasks["step-1"].status == "Running"
                  template: http
                success:
                  expression: tasks["step-1"].status == "Succeeded"
                  template: http
              template: echo
            - name: step2
              dependencies: [step-1]
              hooks:
                running:
                  expression: tasks.step2.status == "Running"
                  template: http
                success:
                  expression: tasks.step2.status == "Succeeded"
                  template: http
              template: echo
        
        - name: echo
          container:
            image: alpine:3.6
            command: [sh, -c]
            args: ["echo \"it was heads\"; sleep 10s"]
        
        - name: http
          http:
            url: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"

```

**Comment by LingClassmate** [comment]
@sarabala1979 Please have a look.

Dag still doesn't work. If I change it to Steps running, it will work.

![image-20220423130919690](https://s2.loli.net/2022/04/23/e4XDv5BbGPNu9Ro.png)

Steps YAML configuration，Steps YAML configuration, running can be run.

![image-20220423132045582](https://s2.loli.net/2022/04/23/9jseZfkILJa7V3p.png)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: step-1
            hooks:
              running:
                expression: steps["step-1"].status == "Running"
                template: http
              success:
                expression: steps["step-1"].status == "Succeeded"
                template: http
            template: echo
        - - name: step2
            hooks:
              running:
                expression: steps.step2.status == "Running"
                template: http
              success:
                expression: steps.step2.status == "Succeeded"
                template: http
            template: echo
    
    - name: echo
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"it was heads\"; sleep 10s"]
    
    - name: http
      http:
        url: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"
```

In daG, I found that "dependencies" caused the running HTTP request not to run. When I added three tasks, only the last one ran.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-tmpl-level-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
        - name: step-1
          hooks:
            running:
              expression: tasks["step-1"].status == "Running"
              template: http
            success:
              expression: tasks["step-1"].status == "Succeeded"
              template: http
          template: echo
        - name: step2
          dependencies: [step-1]
          hooks:
            running:
              expression: tasks.step2.status == "Running"
              template: http
            success:
              expression: tasks.step2.status == "Succeeded"
              template: http
          template: echo
        - name: step3
          dependencies: [step2]
          hooks:
            running:
              expression: tasks.step3.status == "Running"
              template: http
            success:
              expression: tasks.step3.status == "Succeeded"
              template: http
          template: echo
    
    - name: echo
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"it was heads\"; sleep 10s"]
    
    - name: http
      http:
        url: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"
```

![image-20220423133653585](https://s2.loli.net/2022/04/23/OI9vtyXlPqFd5Mj.png)
