### ISSUE TITLE
LifeCycle hooks phase not updated at workflow level

### ISSUE THREAD

**Issue by Piroddi** [argoproj/argo-workflows#8529]
## Summary

The phase of LifeCycle hooks configured at a workflows level are not updated once complete. They are stuck in 'pending' state forever. 

This prevents workflows from being retried, which negatively impacts long running workflows with lots of steps 

What happened/what you expected to happen?

Lifecycle hook phase should change to 'Completed' once completed

What version are you running?

v3.3.3

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
it is know bug, in hooks, the workflow will not be reconciled if it is already completed.  I will try to come up with fix.

**Comment by alexec** [comment]
@sarabala1979 this is not a popular bug. I'd like someone from the community to try and fix this, rather than the core team, as our goal should always to make the greatest positive impact for our customers.

Could I ask you to add some guidance for the engineer trying to fix this?

Specifically, link to the exact line of code where you think changes need making.

**Comment by alexec** [comment]
@sarabala1979 please ignore my last comment. You have done this already with the linked PR.

@Piroddi would you be willing to complete @sarabala1979 PoC PR?

**Comment by sandeepitachi** [comment]
Hi @alexec - when can we expect the changes made in #8586 to get merged. Thanks 😄

**Comment by sandeepitachi** [comment]
We are affected by this bug I guess! Using HTTP templates with lifecycle hooks to send our CI workflows build status to bitbucket builds. All the hooks are custom. 
```
hooks:
    failed:
      template: notify
      arguments:
        parameters:
          - name: state
            value: FAILED
          - name: tohash
            value: '{{workflow.parameters.tohash}}'
      expression: workflow.status == "Failed"
    running:
      template: notify
      arguments:
        parameters:
          - name: state
            value: INPROGRESS
          - name: tohash
            value: '{{workflow.parameters.tohash}}'
      expression: workflow.status == "Running"
    success:
      template: notify
      arguments:
        parameters:
          - name: state
            value: SUCCESSFUL
          - name: tohash
            value: '{{workflow.parameters.tohash}}'
      expression: workflow.status == "Succeeded"
```
We have multiple apps and repos - use only CI workflows pipepine for all. When the wfs take more than 2 minutes - it is affecting and showing the wrong status.
**Expected Result:**
![image](https://user-images.githubusercontent.com/25717719/170351697-fc72fca1-f63f-413e-9e17-4289d8948bd5.png)

**Actual Result:**
![image](https://user-images.githubusercontent.com/25717719/170351657-cfd75990-d49a-48aa-9f62-a2faa4e14df8.png)

**Comment by alexec** [comment]
@sandeepitachi someone needs to take over #8586. Would you like to?

**Comment by sandeepitachi** [comment]
I'd love to but I'm not great at coding. 😄 Also not much familiar with Go.

**Comment by sandeepitachi** [comment]
Thank you @alexec 😄 Will spend some time this weekend for sure! Would like to contribute!

Also spoke to my architect @brgoode too (he's good at go) BUT like you - he's super BUSY working with different teams in our org. If he got some time - he's happy to look at it too

**Comment by roofurmston** [comment]
I believe this is still a known bug, so I don't think it should be closed.

**Comment by roofurmston** [comment]
I believe this is still a known bug, so I don't think it should be closed. Would be good to know if this is not the case. Otherwise, I think it should stay open.

**Comment by bencompton** [comment]
I'm seeing this issue, and I also notice when bringing up the logs for the hook that the logs UI continuously appends the same logs to the displayed log output every second. Closing the logs window and re-opening it clears the logs and then starts continuously appending the same logs once again.

**Comment by jackivanov** [comment]
> Lifecycle hook phase should change to Succeeded once completed

We're seeing the same behavior for `workflow.status == "Failed"`

**Comment by ezk84** [comment]
This has been affecting our team also. Seems like a fix is in, thanks @sarabala1979. Will it make 3.4?

**Comment by ese** [comment]
I still have the issue testing in `v3.4.0-rc4` where it's supposed to have included the fix. cc: @sarabala1979  
![image](https://user-images.githubusercontent.com/755174/190148104-253cdd53-8e53-4598-9f31-426ab13546f5.png)

**Comment by ese** [comment]
As workaround you can use exit handlers https://argoproj.github.io/argo-workflows/walk-through/exit-handlers/ instead hooks for failed and succeeded which works fine updating phase after workflow ends:
example:
```
spec:
  onExit: exit-handler
  templates:
    - name: exit-handler
      steps:
        - - name: succeeded
            templateRef:
              name: notifier
              template: notifier-succeed
            when: '{{workflow.status}} == Succeeded'
          - name: failed
            templateRef:
              name: notifier
              template: notifier-failed
            when: '{{workflow.status}} != Failed'
```

**Comment by cheery550** [comment]
> 



> As workaround you can use exit handlers https://argoproj.github.io/argo-workflows/walk-through/exit-handlers/ instead hooks for failed and succeeded which works fine updating phase after workflow ends: example:
> 
> ```
> spec:
>   onExit: exit-handler
>   templates:
>     - name: exit-handler
>       steps:
>         - - name: succeeded
>             templateRef:
>               name: notifier
>               template: notifier-succeed
>             when: '{{workflow.status}} == Succeeded'
>           - name: failed
>             templateRef:
>               name: notifier
>               template: notifier-failed
>             when: '{{workflow.status}} != Succeeded'
> ```

it also do not work.

**Comment by Piroddi** [comment]
@sarabala1979 I have just upgraded to 3.4.2. However this bug is not resolved. Experiencing the same behaviour

**Comment by Piroddi** [comment]
Still an issue. Simple example:

````
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-
spec:
  entrypoint: main
  hooks:
      failure:
        expression: workflow.status == "Failed"
        template: heads
  templates:
    - name: main
      steps:
      - - name: step1
          template: fail
    
    - name: fail
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["exit 1"]

    - name: heads
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"running hook\""]
  ````

**Comment by Piroddi** [comment]
Hi @alexec @sarabala1979 I have time to look into this issue. It's really effecting us, as we cant retry long running workflows. 

Should I create a new issue or can you reopen this one?

**Comment by elim19** [comment]
I believe this is still a known bug, so I don't think it should be closed.

**Comment by ese** [comment]
I can confirm is still an issue in v3.4.5

**Comment by capacman** [comment]
I can confirm as well. v3.4.5

**Comment by Mastergalen** [comment]
This is still an issue in v3.4.8

**Comment by Piroddi** [comment]
The issue got resolved for me in v3.4.7, from the following fix:

https://github.com/argoproj/argo-workflows/pull/10307

**Comment by Mastergalen** [comment]
Strange, using the workflow level example I am still seeing the hooks stuck in the `Pending` state.

<img width="131" alt="image" src="https://github.com/argoproj/argo-workflows/assets/1261152/78906d39-117d-49f2-af4d-c1a66a67a36a">

## Workflow YAML

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lifecycle-hook-
spec:
  entrypoint: main
  hooks:
    exit: # Exit handler
      template: http
    running:
      expression: workflow.status == "Running"
      template: http
  templates:
    - name: main
      steps:
      - - name: step1
          template: heads
    
    - name: heads
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"it was heads\""]
    
    - name: http
      http:
        # url: http://dummy.restapiexample.com/api/v1/employees
        url: "https://raw.githubusercontent.com/argoproj/argo-workflows/4e450e250168e6b4d51a126b784e90b11a0162bc/pkg/apis/workflow/v1alpha1/generated.swagger.json"
```

**Comment by Piroddi** [comment]
So looks like the above issue is related to http templates. As it works for non http templates:

````
metadata:
  generateName: lifecycle-hook-
spec:
  entrypoint: main
  hooks:
    exit: # Exit handler
      template: tails
    running:
      expression: workflow.status == "Running"
      template: tails
  templates:
    - name: main
      steps:
      - - name: step1
          template: heads
    
    - name: heads
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"it was heads\""]
    
    - name: tails
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"it was tails\""]
````
![image](https://github.com/argoproj/argo-workflows/assets/24908789/aab6d08e-7d2e-42ea-aabd-1ce253ea4b53)

I think the issue is related to:

https://github.com/GeunSam2/argo-workflows/blob/master/workflow/controller/hooks.go#L34

Which needs to be investigated. 

Since this issue is already closed. I would recommend opening a new one, specifically for http so it can get more eyes
