### ISSUE TITLE
Memoization not work on plugin node.

### ISSUE THREAD

**Issue by wujayway** [argoproj/argo-workflows#8553]
## Summary
Memoization cache is not generated on plugin node.
## Diagnostics
Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.
Try to give an example below. We use an inner plugin, here gives a mock plugin.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-plugin-demo
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: hello1
            template: hello1
    - name: hello1
      plugin:
        hello: { }
      memoize:
        key: "hello-plugin-demo-hello1"
        maxAge: "3600s"
        cache:
          configMap:
            name: hello-plugin-demo-hello1
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
