### ISSUE TITLE
Workflow OpenAPI validation

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo-workflows#859]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

Do you have plans to support validation of the Argo workflow spec? 

It should be added here: 

https://github.com/argoproj/argo/blob/06c0d324bf93a037010186fe54e40590ea39d92c/install/manifests/01_workflow-crd.yaml

Here is the documentation: 

https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/

Here is a sample: 

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cronSpec:
              type: string
              pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
            replicas:
              type: integer
              minimum: 1
              maximum: 10
```
