### ISSUE TITLE
podSpecPatch in template not compatible with Emmisary

### ISSUE THREAD

**Issue by bkanuka** [argoproj/argo-workflows#8631]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

### What happened/what you expected to happen?

Emmisary complains that my workflow "does not have the command specified", when using a WorkflowTemplate and podSpecPatch.  This only happens when using a `podSpecPatch`. Removing the `podSpecPatch` in the WorkflowTemplate below allows everything to complete succesfully.

### What version are you running?
3.3.5

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-template
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    inputs:
      parameters:
        - name: mem-request
          value: 256Mi
        - name: cpu-request
          value: 1000m
    podSpecPatch: |
      containers:
        - name: whalesay
          resources:
            requests:
              memory: "{{inputs.parameters.mem-request}}"
              cpu: "{{inputs.parameters.cpu-request}}"
    container:
      name: whalesay
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: "simple-cronworkflow"
spec:
  schedule: "0 8 1-7 * 4"  
  suspend: true
  workflowSpec:
    workflowTemplateRef:
      name: hello-template
```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

time="2022-05-05T15:36:55.554Z" level=error msg="Mark error node" error="container \"whalesay\" in template \"whalesay\", does not have the command specified: when using the emissary executor you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary" namespace=argo nodeName=simple-cronworkflow-r24vg workflow=simple-cronworkflow-r24vg

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
The clue is in this error message:

```
failed to look-up entrypoint/cmd for image ""
```

The `podSpecPatch` misses the `image`. Question is why does `podSpecPatch` erase this.

**Comment by alexec** [comment]
See #5897

**Comment by bkanuka** [comment]
Ahh thanks for the tip about the missing image.  If I add `image:` *and* `command:` to the `podSpecPatch`, things seem to work!

Of course this is only a workaround, but worth pointing out until the bug is fixed.  Thanks!

**Comment by alexec** [comment]
This is user error. You cannot name your container `whalesay`. It must either be unnamed, or named `main`.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-template
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    inputs:
      parameters:
        - name: mem-request
          value: 256Mi
        - name: cpu-request
          value: 1000m
    podSpecPatch: |
      containers:
        - name: main
          resources:
            requests:
              memory: "{{inputs.parameters.mem-request}}"
              cpu: "{{inputs.parameters.cpu-request}}"
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```


We could do a better job of reporting this error.
