### ISSUE TITLE
OOM error not caught by the `emissary` executor forcing the workflow to hang in "Running" state

### ISSUE THREAD

**Issue by hadim** [argoproj/argo-workflows#8680]
_I am opening a new issue, but you can check https://github.com/argoproj/argo-workflows/issues/8456#issuecomment-1120206141 for context._

---

The below error has been reproduced on `master` (07/05/2022), `3.3.5` and `3.2.11`.

When a workflow get OOM killed by K8s, the `emissary` executor sometime **can't detect it**. In consequence, the workflow **hangs in "Running" state forever**.

The error **does not happen** when using the `pns` or `docker` executor. This is a major regression for us since the previous executors were working just fine. For now, we are falling back to `docker`.

I have been able to make Argo detect the killed process by manually sshing to the pod and killing the `/var/run/argo/argoexec emissary -- bash --login /argo/staging/script` process (sending a `SIGTERM` signal). When doing that the `main` container get immediately killed, as well as the workflow. The workflow is correctly marked as failed with the correct `OOMKilled (exit code 137)` error (the same error when using the `pns` and `docker` executors).

**Unfortunately**, so far all my attempts to reproduce it using openly available code, images and packages has been **unsuccessful** (I'll keep trying). I can only reproduce it using our private internal stack and images.

The workload is a deeply nested machine learning code that rely a lot on the python and pytorch `multiprocessing` and `distributed` module. My guess is that some zombie child processes prevent the argo executor or workflow controller to detect the `main` container as completed.

I will be happy to provide you more information, logs or config if it can help you to make sense of this (while on my side I'll keep trying to make a workflow reproducing the bug that I can share).

While this bug affects us, I am quite confident other people running ML workload with Python on Argo will get that bug at some point.

**Comment by hadim** [comment]
It might be important to say that in the logs of the `main` container I can see `/argo/staging/script: line 60:   854 Killed  ` (while the workflow is stick in "Running" phase).

As said above, manually sshing into the `main` container, I can reestablish the correct behaviour with `kill -15 1` (not that `kill -9 1` **does not work**).

**Comment by alexec** [comment]
Does running ps confirm show the process as zombie?

**Comment by hadim** [comment]
Running `ps aux` shows 2 zombie processes (both python and related to the workload of interest). There are other children processes related to the workload but those are not in `Z` state but they are in `Sl` state.

**Comment by alexec** [comment]
https://github.com/pablo-ruth/go-init/blob/30e47fe6f58c0e7fb5dfd12525b583639c7bda92/main.go#L94

**Comment by alexec** [comment]
To repro, if the problem is zombies, then we need to create a zombie. How to do that I wonder?

**Comment by alexec** [comment]
See #7259

**Comment by alexec** [comment]
Tekton and go-init do this:

https://github.com/tektoncd/pipeline/blob/6cb0f4ccfce095495ca2f0aa20e5db8a791a1afe/cmd/entrypoint/runner.go#L79

But we do this:

https://github.com/argoproj/argo-workflows/blob/92b3ef27af7a7e6b930045e95072a47c8745b1d3/cmd/argoexec/commands/emissary.go#L70

**Comment by alexec** [comment]
@hadim would you please be able to run a new version of the executor? `dev-zombie`. I don't know if this is the right fix, but it maybe.

**Comment by hadim** [comment]
Should I also set the controller image to `dev-zombie`? Because I only set `--executor-image=quay.io/argoproj/argoexec:dev-zombie` (controller args) and running as a sanity check the argosay workflow from the UI, the workflow never terminates.

**Comment by hadim** [comment]
Nevermind about my last message. Setting the `workflow-controller` image to use `dev-zombie` makes it work. Trying to reproduce the bug now (not that I haven't modified the `argo-server` image).

**Comment by hadim** [comment]
I just tested it again with our problematic workflow and everything is the same as before. Logs show the script has been killed but the workflow is stuck in "Running" phase.

**Comment by hadim** [comment]
I have been able to reproduce the bug at a smaller scale with less child processes, so it's easier to show an `htop` output:

```bash
 PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
      1 root       20   0  740M 38544 29104 S  0.0  0.5  0:00.18 /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
    697 root       20   0 5492M  544M  2576 S  0.0  7.3  0:00.02 ├─ /opt/conda/envs/xxxx/bin/python /opt/conda/envs/xxxx/bin/xxxxx train --setup xxxx
    698 root       20   0 5492M  544M  2576 S  0.0  7.3  0:00.00 │  └─ /opt/conda/envs/xxxx/bin/python /opt/conda/envs/xxxxx/bin/xxxx train --setup xxxx
     16 root       20   0  740M 38544 29104 S  0.0  0.5  0:00.00 ├─ /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
     15 root       20   0  740M 38544 29104 S  0.0  0.5  0:00.02 ├─ /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
     14 root       20   0  740M 38544 29104 S  0.0  0.5  0:00.00 ├─ /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
     10 root       20   0  740M 38544 29104 S  0.0  0.5  0:00.01 ├─ /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
      9 root       20   0  740M 38544 29104 S  0.0  0.5  0:00.01 ├─ /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
      8 root       20   0  740M 38544 29104 S  0.0  0.5  0:00.01 ├─ /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
      7 root       20   0  740M 38544 29104 S  0.0  0.5  0:00.02 └─ /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
    721 root       20   0  6128  3892  3184 S  0.0  0.1  0:00.01 bash
    743 root       20   0  5460  3896  2960 R  0.0  0.1  0:00.01 └─ htop
```

During this run, you will notice that there is no zombie processes anymore, making me think that the zombie processes wasn't the culprit.

(we are actively trying to get you a workflow you can use to reproduce the bug, it might take of time but I will update here as soon as we get it)

**Comment by alexec** [comment]
The process should only fork one sub-process. Are you using any kind of retry?

**Comment by hadim** [comment]
> The process should only fork one sub-process. Are you using any kind of retry?

No the workflow is a very regular single node one without any retry strategy set (neither other argo features beside all the `ttlStrategy` keys set to 3h).

**Comment by hadim** [comment]
FYI: I did try with `dev-kill-linux-amd64` (your latest PR) but still see the same bug as before.

**Comment by hadim** [comment]
I did some progress that might help you.

See below the "anatomy" of the bash script we execute and that trigger the bug that prevent argo to detect that the script has been killed.

```bash
# container command is `[bash, --login]`
set -e

conda activate $CONDA_ENV_NAME

# do some apt/pip/conda installation
# download some data from a GCP bucket

# the below python worload will spawn child processes
execute_python_workload_that_trigger_the_OOM_error
```

Now if I put the python workload script into a child `bash` process with:

```bash
( execute_python_workload_that_trigger_the_OOM_error )

# instead of `execute_python_workload_that_trigger_the_OOM_error`
```

then the script runs, OOM kills the script and argo can properly detect it and mark it as Completed and Failed with the appropriate `OOMKilled (exit code 137)` error.

**Comment by alexec** [comment]
So you create as sub-shell, perhaps the sub-shell does not become part of the process group.

**Comment by hadim** [comment]
The bug only happens when I run the workload (`execute_python_workload_that_trigger_the_OOM_error`) **not** in a sub-shell (without the `( xxx )`).

When using a sub-shell then argo behaves as excepted.

In terms of processes hierarchy using `htop`, I haven't spotted any obvious difference.

**Comment by hadim** [comment]
Sorry for the noise around sub-shell, it has nothing to do (I got confused with some new git commits I haven't noticed in our internal stack).

We have been able to narrow down the python module that seems to trigger the bug. It seems to be caused by `torch.multiprocessing.Manager()`. We are getting closer to be able to provide you something to reproduce.

**Comment by hadim** [comment]
I have been able to reproduce the bug.

Here is the template to use:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-oom-reproduce-
  labels:
    organization: internal
    project: debug-emissary-oom
    "workflows.argoproj.io/container-runtime-executor": "emissary"

spec:
  entrypoint: entrypoint

  templates:
    - name: entrypoint
      script:
        image: mambaorg/micromamba:0.23.0

        command: ["bash", "--login"]
        source: |
          set -e

          # Init the bash
          eval "$(micromamba shell hook --shell=bash)"
          micromamba activate

          echo "Installing packages"
          micromamba create -n conda_env -y -c conda-forge \
            pip \
            "python=3.8" \
            "pytorch=1.10" \
            "pandas=1.4" \
            "pyarrow=7" \
            "fsspec=2022.3" \
            "gcsfs=2022.3"
          micromamba activate conda_env

          # Python script
          PYTHON_CODE=$(cat <<END

          import pandas as pd
          import torch.multiprocessing as mp

          print("mp_manager (SEEMS IMPORTANT TO TRIGGER THE BUG)")
          mp_manager = mp.Manager()

          print("read_parquet (a 2GB dataset with 8.5M rows, 2 columns and one index)")
          data_path = "gs://hadrien-public-sandbox/argo/fake_dataset.parquet"
          dataset = pd.read_parquet(data_path)

          END
          )
          echo "$PYTHON_CODE" > /tmp/python_code.py

          echo "START"
          python /tmp/python_code.py
          echo "DONE"

      # The k8s node used is a GCP VM with 2 vCPUs and 8 GiB of RAM.
      resources:
        limits:
          cpu: 1280m
          memory: 4864Mi
        requests:
          cpu: 1280m
          memory: 4864Mi

  # The below is specific to our k8s cluster in order to
  # run the workflows on a specific k8s node.
  tolerations:
    - key: reserved-pool
      operator: Equal
      value: "true"
      effect: NoSchedule
  nodeSelector:
    pool-name: greedy-pool-2
```

Note that the bug **does not always** happens. Sometime argo correctly mark the workflow as Completed and Failed. When executing 15 time the same above workflow, argo is able to correctly detect the OOM error for 5/15 workflows.

Every workflow are executed on a Kubernetes nodes with 2 vCPUs and 8GiB of memory (I am not sure but it might be an important detail).

**Comment by alexec** [comment]
@hadim would you available for a video call this week so I can see this in action?

**Comment by hadim** [comment]
Sure that would probably be the most efficient. I am a bit busy this week. Would next Monday works for you? My timezone is EST (Montreal).

Have you been able to reproduce the error with the above workflow?

**Comment by alexec** [comment]
Pacific Time. I don't have ready access to large clusters.

**Comment by alexec** [comment]
I want to dig into some things:

* Is it definately OOM? 
* What happens to the processes? Do you see zombies?

**Comment by hadim** [comment]
> Is it definately OOM?

It's clearly OOM:

- Verified by checking memory usage with `htop`.
- Also when I kill PID 1, argo can detect it and show the OOM Error in the UI.

> What happens to the processes? Do you see zombies?

I don't see any zombie in the workflows I have shared above.

> Conversely, did you see orphans?

Don't think so from the tree but I am not sure the best way to check for orphans.

Here the output of `htop` after the script got killed (but still in "Running" state):

```bash
  PID-USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
   3020 root       20   0  4616  3764  3220 S  0.0  0.0  0:00.00 bash
   3029 root       20   0  5380  3988  3096 R  0.0  0.1  0:00.03 `- htop
   2985 root       20   0  2880   968   876 S  0.0  0.0  0:00.00 sh -c clear; (bash || ash || sh)
   2993 root       20   0  2880   104     0 S  0.0  0.0  0:00.00 `- sh -c clear; (bash || ash || sh)
   2994 root       20   0  4616  3816  3220 S  0.0  0.0  0:00.01    `- bash
   3011 root       20   0  5336  4092  3040 S  0.0  0.1  0:00.09       `- htop
      1 root       20   0  740M 13968  3972 S  0.0  0.2  0:00.83 /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
   2974 root       20   0  644M  106M  1140 S  0.0  1.4  0:00.02 `- python /tmp/python_code.py
   2975 root       20   0  644M  106M  1140 S  0.0  1.4  0:00.00 |  `- python /tmp/python_code.py
     18 root       20   0  740M 13968  3972 S  0.0  0.2  0:00.00 `- /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
     17 root       20   0  740M 13968  3972 S  0.0  0.2  0:00.00 `- /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
     16 root       20   0  740M 13968  3972 S  0.0  0.2  0:00.09 `- /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
     15 root       20   0  740M 13968  3972 S  0.0  0.2  0:00.00 `- /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
     11 root       20   0  740M 13968  3972 S  0.0  0.2  0:00.01 `- /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
     10 root       20   0  740M 13968  3972 S  0.0  0.2  0:00.03 `- /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
      9 root       20   0  740M 13968  3972 S  0.0  0.2  0:00.03 `- /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
      8 root       20   0  740M 13968  3972 S  0.0  0.2  0:00.57 `- /var/run/argo/argoexec emissary -- bash --login /argo/staging/script
```

**Comment by alexec** [comment]
I'm out of office next week. Can you do this week? Pacific Time.

**Comment by hadim** [comment]
Friday 15h EST?

**Comment by alexec** [comment]
That works. Can you send invite to alex_collins@intuit.com

**Comment by hadim** [comment]
I have edited the workflow to reproduce the bug above. It is now 100% reproducible and also does not require `pytorch` but only `multiprocessing` (python stdlib) to reproduce. The previous template had a wrong `ressources` block indentation.

**Comment by hadim** [comment]
Still investigating here. The bug is not tight to any specific node configuration (I thought it was originally). I have been able to reproduce it without any `tolerations`/`nodeSelector` keys. See the latest workflow below:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-oom-reproduce-emissary-
  labels:
    organization: internal
    project: debug-emissary-oom
    "workflows.argoproj.io/container-runtime-executor": "emissary"

spec:
  entrypoint: entrypoint

  templates:
    - name: entrypoint
      script:
        image: ubuntu:22.04

        command: ["bash", "--login"]
        source: |
          set -e

          apt-get update
          apt-get install -y wget bzip2 htop psmisc
          rm -rf /var/lib/apt/lists/*

          # Install and enable micromamba
          wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          export MAMBA_ROOT_PREFIX=~/micromamba
          mkdir -p $MAMBA_ROOT_PREFIX
          eval "$(./bin/micromamba shell hook --shell=posix)"
          micromamba activate

          echo "Installing packages"
          micromamba create -n conda_env -y -c conda-forge \
            pip \
            "python=3.8" \
            "pandas=1.4" \
            "pyarrow=7" \
            "fsspec=2022.3" \
            "gcsfs=2022.3"
          micromamba activate conda_env

          # Python script
          PYTHON_CODE=$(cat <<END

          import pandas as pd
          import multiprocessing as mp

          print("mp_manager (SEEMS IMPORTANT TO TRIGGER THE BUG)")
          mp_manager = mp.Manager()

          print("read_parquet (a 2GB dataset with 8.5M rows, 2 columns and one index)")
          data_path = "gs://hadrien-public-sandbox/argo/fake_dataset.parquet"
          dataset = pd.read_parquet(data_path)

          END
          )
          echo "$PYTHON_CODE" > /tmp/python_code.py

          echo "START"
          python /tmp/python_code.py
          echo "DONE"

        # The k8s node used is a GCP VM with 2 vCPUs and 8 GiB of RAM.
        resources:
          limits:
            cpu: 1280m
            memory: 4864Mi
          requests:
            cpu: 1280m
            memory: 4864Mi
```

**Comment by hadim** [comment]
My last hypothesis is that the bug itself is not related to the OOM error. It's simply that whenever the workflow process is being abruptly killed (because of an OOM error or something else), the workflow process (in that case a python script) does not have the time to clean its child processes (or threads) properly. In consequence, the main process is correctly terminated but since there is still a child process running, argo cannot detect it.

I am not sure if I fully understand why the error is not happening with the `docker` executor (tested with the above template and indeed I don't see the bug with `docker`). Could it be possible that `emissary` and `docker` are not propagating or catching the exact same type of signals?

**Comment by hadim** [comment]
I think the above hypothesis is confirmed by the following simpler (and faster to run) workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-oom-reproduce-simple-emissary-
  labels:
    organization: internal
    project: debug-emissary-oom
    "workflows.argoproj.io/container-runtime-executor": "emissary"

spec:
  entrypoint: entrypoint

  templates:
    - name: entrypoint
      script:
        image: ubuntu:22.04

        command: ["bash", "--login"]
        source: |
          set -e

          apt-get update
          apt-get install -y python3 wget bzip2 htop psmisc
          rm -rf /var/lib/apt/lists/*

          # Python script
          PYTHON_CODE=$(cat <<END

          import subprocess

          print("Spawn a subprocess that will terminate in 60s")
          subprocess.Popen(["sleep", "60s"])

          do_something_that_will_fail()

          END
          )
          echo "$PYTHON_CODE" > /tmp/python_code.py

          echo "START"
          python3 /tmp/python_code.py
          echo "DONE"

        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 1000m
            memory: 500Mi
```

Here I simply trigger a python error (instead of an OOM error). Before that, I execute a python sub process (`sleep 60s`). What I notice is that argo does not detect the python error before the subprocess terminates (after 60s in that case).

**Comment by alexec** [comment]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: subprocess-
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: argoproj/argosay:v1
        command: [ sh, -c ]
        args:
          - |
            sleep 60 &
```

**Comment by alexec** [comment]
```
       logs | subprocess-7m8nf main UID        PID  PPID  C STIME TTY          TIME CMD
       logs | subprocess-7m8nf main root         1     0  0 19:31 ?        00:00:00 /var/run/argo/argoexec emissary -- sh -c sleep 60 &  ps -aef
       logs | subprocess-7m8nf main root        19     1  0 19:31 ?        00:00:00 /bin/sh -c sleep 60 &  ps -aef
       logs | subprocess-7m8nf main root        20    19  0 19:31 ?        00:00:00 sleep 60
       logs | subprocess-7m8nf main root        21    19  0 19:31 ?        00:00:00 ps -aef
```

```
root         1     0  0 19:33 ?        00:00:00 /var/run/argo/argoexec emissary -- sh -c sleep 60 &  ps -aef
root        20     1  0 19:33 ?        00:00:00 sleep 60
root        22     0  0 19:33 ?        00:00:00 ps -aef
```

**Comment by hadim** [comment]
> When sh process exits, sleep parent changes to 1.

It was so fast that I couldn't show it during the call but by observing `htop`, this is also what I observed with all the examples (OOM or the simpler one with `sleep 60s`).

**Comment by alexec** [comment]
Hi. I’ve pushed a new version which I hope/expect to fix the issue. Would you test please?

**Comment by hadim** [comment]
Using `dev-kill` (versus `v3.3.5`) seems to fix the bug indeed.

I tested with this simple workflow and the controller correctly marks it as failed without waiting for the `sleep` subprocess to finish:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-oom-reproduce-simple-emissary-
  labels:
    organization: internal
    project: debug-emissary-oom

spec:
  entrypoint: entrypoint

  templates:
    - name: entrypoint
      script:
        image: ubuntu:22.04

        command: ["bash", "--login"]
        source: |
          set -e

          apt-get update
          apt-get install -y python3 wget bzip2 htop psmisc
          rm -rf /var/lib/apt/lists/*

          # Python script
          PYTHON_CODE=$(cat <<END

          import subprocess

          print("Spawn a subprocess that will terminate in 600s")
          subprocess.Popen(["sleep", "600s"])

          do_something_that_will_fail()

          END
          )
          echo "$PYTHON_CODE" > /tmp/python_code.py

          echo "START"
          python3 /tmp/python_code.py
          echo "DONE"
```

I also tested with a workflow spawning a never-ending subprocess and also triggering an OOM error in the main process (see above in the thread) and I confirm the controller can detect it, terminate the workflow and mark it as failed + showing the correct error `OOMKilled (exit code 137)`.
