### ISSUE TITLE
emissary workflow examples

### ISSUE THREAD

**Issue by cipribucur** [argoproj/argo-workflows#8694]
# Summary
Since from version 3.3 the default executor is emissary, can you please update more examples to work with it. 

# Use Cases

Upgrading to latest version and trying to find the proper example to work with emissary executor. 

In your examples, and of course in many cases, the images have both entrypoint and cmd. Can you please provide some working examples where these cases are supported. Influx db has such case and I can't find any example in your documentation.

In my case daemon doesn't work with emissary executor together with containers with entrypoint and cmd. I don't know if it's a bug or i'm miss configuring something. 

Thanks, guys.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
All examples should work with the emissary. If you find ones that don’t, then please raise an issue.

**Comment by demonkoryu** [comment]
@cipribucur In my case, it wouldn't call the Docker `ENTRYPOINT` (since I have to provide a `command`).
My solution was to call the entrypoint manually:
```yaml
      container:
        image: sonarsource/sonar-scanner-cli:latest
        command:
          - /usr/bin/entrypoint.sh
        args:
          - "sonar-scanner"
          - "-X"
```
