### ISSUE TITLE
Input Parameter Confusion and Differences Between WorkflowTemplate and Workflows

### ISSUE THREAD

**Issue by luke-hemisphere** [argoproj/argo-workflows#8704]
## Summary

**What happened?**
Trying to submit a workflow template results in an error. The equivalent non-template workflow succeeds

```
argo -n argo template delete broken-template-inputs
> WorkflowTemplate 'broken-template-inputs' deleted

argo -n argo template create broken-template-inputs.yml
> Name:                broken-template-inputs
Namespace:           argo
Created:             Wed May 11 18:39:42 +1000 (now)

argo -n argo submit --from workflowtemplate/broken-template-inputs --watch 
> Failed to submit workflow: templates.main.tasks.A templates. inputs.parameters.px was not supplied`  
```

**What version are you running?** 
3.3.2

## Diagnostics

The following workflows are equivalent - one is a template and one is not.  
running the template version will fail  
running the non-template version will succeed  

### Template Version
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: broken-template-inputs
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: p1
        value: "1"
      - name: p2
        value: "2"
  templates:
    - name: main
      inputs:
        parameters:
          - name: p1
          - name: p2
      dag:
        tasks:
          - name: B
            arguments:
              parameters:
              - name: px
                value: "4"
            inline:
              inputs:
                parameters:
                  - name: px
              container:
                image: alpine:3.7
                command:
                  - sh
                  - -c
                  - exit 0
                
          - name: A
            arguments:
              parameters:
                - name: p1
                  value: "{{ inputs.parameters.p1 }}"
                - name: p2
                  value: "{{ inputs.parameters.p2 }}"
            inline:
              inputs:
                parameters:
                  - name: p1
                  - name: p2
              container:
                image: alpine:3.7
                command:
                  - sh
                  - -c
                  - exit 0
```

### Workflow Version
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: broken-template-inputs-
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: p1
        value: "1"
      - name: p2
        value: "2"
  templates:
    - name: main
      inputs:
        parameters:
          - name: p1
          - name: p2
      dag:
        tasks:
          - name: B
            arguments:
              parameters:
              - name: px
                value: "4"
            inline:
              inputs:
                parameters:
                  - name: px
              container:
                image: alpine:3.7
                command:
                  - sh
                  - -c
                  - exit 0
                
          - name: A
            arguments:
              parameters:
                - name: p1
                  value: "{{ inputs.parameters.p1 }}"
                - name: p2
                  value: "{{ inputs.parameters.p2 }}"
            inline:
              inputs:
                parameters:
                  - name: p1
                  - name: p2
              container:
                image: alpine:3.7
                command:
                  - sh
                  - -c
                  - exit 0
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
