### ISSUE TITLE
error with @ character in gjson expression

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8734]
a param to my workflow is a payload like:
https://github.com/LeidosLabs/holeshot/blob/b3aa04a84059e3a4c07d42ff9a46cc37f443eb3d/ingest-service/src/test/resources/sample-notification.json#L1-L12

ie
```  
               arguments:
                  parameters:
                    - name: message
```

i try to extract the 'key' from the partially stringified json (which works on https://gjson.dev/):

```
                workflowMetadata:
                  labelsFrom:
                    s3path:
                      expression: workflow.parameters.message.@fromstr.Records.0.s3.object.key
```

but argo gives this error:
```
Error: failed to evaluate label "s3path" expression "workflow.parameters.message.@fromstr.Records.0.s3.object.key": unrecognized character: U+0040 '@' (1:30) | workflow.parameters.message.@fromstr.Records.0.s3.object.key | .............................^
```

**Comment by sandeepitachi** [comment]
I was facing a similar issue when I tried to a label using payload emailAddress

`
arguments:
    parameters:
       - name: submitted-by
         valueFrom:
           event: payload.actor.emailAddress
`

Tried to add the param to the labels
`
workflowMetadata:
    labels:
      submitted_by: "{{workflow.parameters.submitted-by}}"
`

Workflow is not getting submitted with the above labels and then tried labelsFrom - see below
`
workflowMetadata:
    labelsFrom:
      submitted-by:
         expression: "{{workflow.parameters.submitted-by}}"
`
I'm getting an error as below screenshot
![image](https://user-images.githubusercontent.com/25717719/169099769-9fd35cc7-9c78-451f-a1f3-ea2cda816cf8.png)

**Comment by sandeepitachi** [comment]
@tooptoop4 Hey found an easy way - use below sprig function
```
workflowMetadata:
    labelsFrom:
      s3path:
         expression: '{{=sprig.replace("@", ".at.", workflow.parameters.s3path)}}'
```

``
