### ISSUE TITLE
create invalid workflowtemplate in ui does not show error but creates default

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8737]
when you paste below into a new workflowtemplate in UI it does not show any error, discards what u pasted in but creates a default workflowtemplate

```
container:
  image: x
  command: [bash, -c]
  args: ["bash script.sh "{{inputs.parameters.x}}""]
```
