### ISSUE TITLE
GCS artifact repository archiveLogs error

### ISSUE THREAD

**Issue by maven2016** [argoproj/argo-workflows#8746]
## Checklist

* [ x] Double-checked my configuration.
* [ x] Tested using the latest version.
* [ x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Used this for reference: 
https://argoproj.github.io/argo-workflows/configure-artifact-repository/#configure-the-default-artifact-repository

My configuration: (I've tried with and without keyFormat)

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  artifactRepository: |
    archiveLogs: true
    gcs:
      bucket: test
```

Workflow logs are saved in the GCS bucket, I'm able to see the workflow file logs via GCP console and access them.
However when I try to click on 'logs from the artifacts' through argo i get an error message 'internal server error'

<img width="868" alt="image" src="https://user-images.githubusercontent.com/20874387/168101713-f5a3c2bc-7719-4017-9b98-82c914d24e21.png">

What version are you running?
v3.3.5

## Diagnostics
In argo server logs I see the following error:
level=error msg="Artifact Server returned internal error" error="IsDirectory currently unimplemented for GCS"

Please advise.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
