### ISSUE TITLE
PodSpecPatch cannot patch `env` variables

### ISSUE THREAD

**Issue by alexrosenfeld10** [argoproj/argo-workflows#8754]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

PodSpecPatch should work for env vars. I want all my pods to be configured the same way, but this doesn't work so I have to resort to copying the `env` block into each template.

What version are you running?

## Diagnostics

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-template
  generateName: my-template-
spec:  
  podSpecPatch: |
    containers:
      - name: main
        env:
          - name: FOO
            valueFrom:
              configMapKeyRef:
                name: "my-config"
                key: foo_key
```

Any pod inside this template will not have the `env` values set from the patch.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@alexrosenfeld10 you can use the above definition without `podSpecPatch`. Can you provide more information on what you are trying to do?

**Comment by alexrosenfeld10** [comment]
Thanks for the quick reply @sarabala1979 . What I'm trying to do here is define a `WorkflowTemplate` in a common way such that I can instantiate it as a step in a DAG, and trust that every pod in the worfklow template is configured the same way. Ideally I'd use `workflow` level params, but that's not working for me either (see https://github.com/argoproj/argo-workflows/discussions/8753 for some context on my wider approach here. If there's a better way to do one or both of these things, I'm all ears! I'm brand new to argo workflows).

Here's my "workaround" (basically just copying that spec into every single template):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: domain-templates
  generateName: domain-templates-
spec:
  # TODO switch to a patch when https://github.com/argoproj/argo-workflows/issues/8754 is resolved.
  # Until then, we'll have to copy this into each template :(
  # podSpecPatch: |
  #   containers:
  #     - name: main
  #       env:
  #         - name: SNOWFLAKE_ENV
  #           valueFrom:
  #             configMapKeyRef:
  #               name: "{{inputs.parameters.snowflake-env}}"
  #               key: SNOWFLAKE_ENV
  #         - name: SNOWFLAKE_PASSWORD
  #           valueFrom:
  #             secretKeyRef:
  #               name: "secret-{{inputs.parameters.snowflake-env}}"
  #               key: "{{inputs.parameters.domain}}_snowflake_password"
  templates:
    - name: domain-main
      inputs:
        parameters:
          - name: domain
          - name: snowflake-env
      dag:
        tasks:
          - name: run-private
            template: run-private-template
            arguments:
              parameters:
                - name: domain
                  value: "{{inputs.parameters.domain}}"
                - name: snowflake-env
                  value: "{{inputs.parameters.snowflake-env}}"
          - name: test-private
            template: test-private-template
            depends: run-private.Succeeded
            arguments:
              parameters:
                - name: domain
                  value: "{{inputs.parameters.domain}}"
                - name: snowflake-env
                  value: "{{inputs.parameters.snowflake-env}}"

    - name: run-private-template
      metadata:
        labels:
          domain: "{{inputs.parameters.domain}}"
          snowflake-env: "{{inputs.parameters.snowflake-env}}"
      inputs:
        parameters:
          - name: domain
          - name: snowflake-env
      script:
        image: python:alpine3.6
        command: [python]
        env:
          - name: SNOWFLAKE_ENV
            valueFrom:
              configMapKeyRef:
                name: "{{inputs.parameters.snowflake-env}}"
                key: SNOWFLAKE_ENV
          - name: SNOWFLAKE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "secret-{{inputs.parameters.snowflake-env}}"
                key: "{{inputs.parameters.domain}}_snowflake_password"
        source: |
          import os
          print("foo " + os.environ[SNOWFLAKE_ENV])
    - name: test-private-template
      metadata:
        labels:
          domain: "{{inputs.parameters.domain}}"
          snowflake-env: "{{inputs.parameters.snowflake-env}}"
      inputs:
        parameters:
          - name: domain
          - name: snowflake-env
      script:
        image: python:alpine3.6
        command: [python]
        env:
          - name: SNOWFLAKE_ENV
            valueFrom:
              configMapKeyRef:
                name: "{{inputs.parameters.snowflake-env}}"
                key: SNOWFLAKE_ENV
          - name: SNOWFLAKE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "secret-{{inputs.parameters.snowflake-env}}"
                key: "{{inputs.parameters.domain}}_snowflake_password"
        source: |
          import os
          print("foo " + os.environ[SNOWFLAKE_ENV])
```

**Comment by alexrosenfeld10** [comment]
You can see there that I have duplication in two places:
1. having to configure the env for each template, instead of at the top level as a patch
2. having to pass inputs from task to task and template to template, instead of being able to use workflow level parameters (again, see https://github.com/argoproj/argo-workflows/discussions/8753)


Neither of these are ideal, and overall it just feels a bit kludgy. Maybe I'm missing something about how Argo Workflows works that would help me do all this in a cleaner way?

**Comment by alexec** [comment]
The spec looks invalid to me. WorkflowSpec does not have a PodSpecPatch field.

**Comment by alexrosenfeld10** [comment]
@alexec It shows up in my ide using the json schema for workflows. Perhaps there's a bug ij the schema then?

Regardless of that, if this is the case how do you recommend I go about structuring these workflow templates?

**Comment by alexec** [comment]
Is this just env vars, or other fields too?

**Comment by alexrosenfeld10** [comment]
I'm just trying to configure things so all my pods in the workflow get the same env vars, both from config maps and secrets, without having to copy the env section into every template (there are many, omitted here for brevity)

**Comment by alexec** [comment]
Let me re-phase. I'm trying to understand if this is a bug with `podSpecPatch`, or just with env vars in `podSpecPatch`.

**Comment by alexrosenfeld10** [comment]
Ah, gotcha. I have not tested other fields.

**Comment by alexrosenfeld10** [comment]
I am wondering if this is an issue with the way I'm using `WorkflowTemplate`s, because I have a similar problem getting this to stick as well:

```yaml
 podMetadata:
   labels:
       domain: "{{inputs.parameters.domain}}"
       snowflake-env: "{{inputs.parameters.snowflake-env}}"
```

I'm using a `WorkflowTemplate`, but I instantiate it from a DAG so I actually just reference the `template` directly, using a `templateRef` instead of a `workflowTemplateRef`. Could that be the problem?
