### ISSUE TITLE
Argo WorkflowTemplate Now has a   limit about integer parameters?

### ISSUE THREAD

**Issue by berlinsaint** [argoproj/argo-workflows#8777]
## workflow

Now i have a workflow like: 

```yaml
    - name: horovod-cpu-agent
      executor: 
        serviceAccountName: volcano-executor-plugin
      inputs:
        parameters:
          - name: command
            value: "python /work/code/horovod_test/train_atp_day_cal_ad_horovod.py --data_path /work/data/tfrecords_ad_infoflow_v1/data --featmap_path /work/data/tfrecords_ad_infoflow_v1/featMap/part-00000  --checkpoint_path /work/model/deepfm_v1 --start_date ${CURRENT} --embed_dim 8 --input_length 30 --learning_rate 0.0004 --decay_steps 5000 --embedding_length 150 --cache 0 --end_delta 2 --epochs 1 --test_rate 0.1"
          - name: image
            value: "horovod-cpu:master"
          - name: workers
            value: 2
          - name: masters
            value: 1
          - name: train_type
            value: "cpu"
          - name: cpu_num
            value: "32"
          - name: job_name
            value: "{{workflow.name}}"
          - name: log_level
            value: "INFO"
      plugin:
        volcano:
          job:
              apiVersion: batch.volcano.sh/v1alpha1
              kind: Job
              metadata:
                name: "{{workflow.name}}"
                namespace: "{{workflow.namespace}}"
                ownerReferences:
                  - apiVersion: argoproj.io/v1alpha1
                    blockOwnerDeletion: true
                    controller: true
                    kind: Workflow
                    name: "{{workflow.name}}"
                    uid: "{{workflow.uid}}"
              spec:
                minAvailable: {{= sprig.int(inputs.parameters.workers) + sprig.int(inputs.parameters.masters)}}
                replicas: {{inputs.parameters.workers}}
                schedulerName: volcano
                queue: default
                plugins:
                  ssh: []
                  svc: []

```

## Summary

The problem is the  `minAvalible` field and `replicas` field. (or  other int field is  the same), here i 'm using sprig function to caluclate. however , we can't submit this  workflowtemplate because of validation problems. so we need change  add  double quotes. to became  `"{{= sprig.int(inputs.parameters.workers) + sprig.int(inputs.parameters.masters)}}"` ， This will solve the validation problem.. but , when plugin 
doing creating vcjob, this field will be a string and will cause vcjob validation problem. is there some good ways to define a  int  parameters and pass it to the plugin  （i don't want to check it in plugin ...）
