### ISSUE TITLE
Job template 

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8786]
# Summary

Workflows is used by some as a CI solution. Yet it is really needs a new template type to be comparable to GitHub Actions. 

The template type could be called “job”. A job runs a series of steps. Each step runs a command (including a shell script) and the job fails if the command fails. Steps execute in sequence. The job fails if any step fails. Steps execute conditionally, usually only if the job is passing. 

How’s this different to a steps template? Each step of a job runs in the same container. This makes storing and restoring build and caches faster and simpler. 

It also allows users to visualise steps within a container. 

Code changes will be similar to adding the container-set template. 

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by or-shachar** [comment]
@alexec I like the direction! 

I think we need to also enhance the cache restore/save to be according to files:
```yaml
      job:
        image: golang:1.18
        workingDir: /go/src/github.com/golang/example
        steps:
          - run: git clone -v -b "{{workflow.parameters.branch}}" --single-branch --depth 1 https://github.com/golang/example.git .
          - get_artifact:
              name: GOMODCACHE
              path: /go/pkg/mod
              optional: true
              s3:
                key: "github.com/golang/examples/{{ hash 'go.mod' }}/GOMODCACHE"
          - run: go mod download -x
          - save_artifact:
              name: GOMODCACHE
              path: /go/pkg/mod
              optional: true
              s3:
                key: "github.com/golang/examples/{{ hash 'go.mod' }}/GOMODCACHE"
          - run: go build ./...
          - run: |
              go install github.com/jstemmer/go-junit-report@latest
              go install github.com/alexec/junit2html@latest
              
              trap 'cat test.out | go-junit-report | junit2html > test-report.html' EXIT
              
              go test -v ./... 2>&1 > test.out

```
