### ISSUE TITLE
Output parameter not recognized in metric label in template step

### ISSUE THREAD

**Issue by AmineAServier** [argoproj/argo-workflows#8809]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

Hi there, i hope you are doing good.
When applying this wf : https://github.com/argoproj/argo-workflows/blob/master/examples/custom-metrics.yaml
I've noticed that it's not working cause argo is not able to recognize the output in its metrics block. Do you have any ideas how to fix this ? Many thanks in advance !

What version are you running?
Tested with Argo 3.3.5

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: steps
  metrics:
    prometheus:
      - name: duration_gauge
        labels:
          - key: name
            value: workflow
        help: "Duration gauge by name"
        gauge:
          realtime: true                  # This metric will be emitted in real time. For more info see: docs/metrics.md
          value: "{{workflow.duration}}"  # Use {{workflow.duration}} in workflow-level and {{duration}} in template-level

  templates:
    - name: steps
      metrics:
        prometheus:
          - name: duration_gauge
            labels:
              - key: name
                value: steps
            help: "Duration gauge by name"
            gauge:
              realtime: true
              value: "{{duration}}"       # Use {{duration}} in template-level and {{workflow.duration}} in workflow-level
      steps:
        - - name: random-int
            template: random-int
        - - name: flakey
            template: flakey

    - name: random-int
      metrics:
        prometheus:
          - name: random_int_step_histogram
            help: "Value of the int emitted by random-int at step level"
            when: "{{status}} == Succeeded"    # Only emit metric when step succeeds
            histogram:
              buckets:
                - 2.01
                - 4.01
                - 6.01
                - 8.01
                - 10.01
              value: "{{outputs.parameters.rand-int-value}}"
          - name: duration_gauge
            labels:
              - key: name
                value: random-int
            help: "Duration gauge by name"
            gauge:
              realtime: true
              value: "{{duration}}"
      outputs:
        parameters:
          - name: rand-int-value
            globalName: rand-int-value
            valueFrom:
              path: /tmp/rand_int.txt
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["RAND_INT=$((1 + RANDOM % 10)); echo $RAND_INT; echo $RAND_INT > /tmp/rand_int.txt"]

    - name: flakey
      metrics:
        prometheus:
          - name: result_counter
            help: "Count of step execution by result status"
            labels:
              - key: name
                value: flakey
              - key: status
                value: "{{status}}"
            counter:
              value: "1"
      container:
        image: python:alpine3.6
        command: ["python", -c]
        # fail with a 66% probability
        args: ["import random; import sys; exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)"]
```

Error message : 
```
MetricsError: unable to substitute parameters for metric 'random_int_step_histogram': failed to resolve {{outputs.parameters.rand-int-value}}
```
```
    hello-world-bvfm9-4214510328:
      id: hello-world-bvfm9-4214510328
      name: 'hello-world-bvfm9[0].random-int'
      displayName: random-int
      type: Pod
      templateName: random-int
      templateScope: local/hello-world-bvfm9
      phase: Error
      boundaryID: hello-world-bvfm9
      message: >-
        Error (exit code 1): pods "hello-world-bvfm9-4214510328" is forbidden:
        User "system:serviceaccount:extractload:default" cannot patch resource
        "pods" in API group "" in the namespace "extractload"
      startedAt: '2022-05-19T15:55:36Z'
      finishedAt: '2022-05-19T15:55:40Z'
      progress: 1/1
      resourcesDuration:
        cpu: 2
        memory: 2
      outputs:
        exitCode: '0'
      hostNodeName: gke-local-vpc-gke-default-node-pool-ec12fcea-jqz9
  conditions:
    - type: PodRunning
      status: 'False'
    - type: MetricsError
      status: 'True'
      message: >-
        unable to substitute parameters for metric 'random_int_step_histogram':
        failed to resolve {{outputs.parameters.rand-int-value}}
    - type: Completed
      status: 'True'
  resourcesDuration:
    cpu: 2
    memory: 2
  artifactRepositoryRef:
    default: true
    artifactRepository: {}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
