### ISSUE TITLE
Error when trying to pass Env Vars as a parameter to a template: `cannot unmarshal object into Go struct`

### ISSUE THREAD

**Issue by RoryDoherty** [argoproj/argo-workflows#8827]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Tried to pass a parameter as a json/list of env vars but get the following error when submitting the workflow:
```
 Unsuccessful HTTP response: json: cannot unmarshal object into Go struct field ScriptTemplate.workflow.spec.templates.script.env of type []v1.EnvVar
```
I have tried various assortments of quotes, yaml continuation using | and >

According to this thread on slack it did work at some stage so this may be a regression:
https://cloud-native.slack.com/archives/C01QW9QSSSK/p1628785975367900

What version are you running?
v3.3.5
## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
  namespace: argoci
spec:
  entrypoint: demo
  templates:
    - name: demo
      dag:
        tasks:
          - name: env-var-test
            template: run-test
            arguments:
              parameters:
                - name: vars
                  value: |
                    [
                      {name: "Foo", value: "bar"},
                      {name: "Bar", value: "foo"},
                      {name: "zoo", value: "animal"}
                    ]

    - name: run-test
      inputs:
        parameters:
          - name: vars
      script:
        image: ubuntu:18.04
        imagePullPolicy: Always
        command: [bash]
        workingDir: "/src"
        env: {{inputs.parameters.vars}}
        source: |
          env
```

# Logs from the workflow controller:
There were no logs in the workflow controller when I submitted the workflow via the UI
Is there a trace logs setting I can enable?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sandeepitachi** [comment]
@RoryDoherty  Try this 
`script:
        image: ubuntu:18.04
        command:
          - bash
        workingDir: /src
        env:
          - name: a
            value: '{{inputs.parameters.vars}}'
        source: |
          echo $a`

**Comment by RoryDoherty** [comment]
I can work around this for now using the following:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
spec:
  entrypoint: demo
  templates:
    - name: demo
      dag:
        tasks:
          - name: env-var-test
            template: run-test
            arguments:
              parameters:
                - name: vars
                  value: |
                    export Foo="bar"
                    export Bar="Foo"

    - name: run-test
      inputs:
        parameters:
          - name: vars
      script:
        image: ubuntu:18.04
        imagePullPolicy: Always
        command: [bash]
        workingDir: "/src"
        env: 
          - name: vars
            value: '{{inputs.parameters.vars}}'
        source: |
          echo $vars > /tmp/vars
          source /tmp/vars
          env
```

But it would definitely be good if we could set environment variables from the task and not just in the template

**Comment by RoryDoherty** [comment]
This issue still exists

**Comment by RoryDoherty** [comment]
issue still exists

**Comment by ddemydenko** [comment]
the same problem

**Comment by sarabala1979** [comment]
@RoryDoherty  This is by design this is not a bug. Script Template is using `v1.container` spec. if v1.container will accept the array of EnvVar.
We can enhance the controller to parse the JSON and convert []envVar.

**Comment by RoryDoherty** [comment]
Thanks @sarabala1979 , I had seen a similar snippet in a slack thread as a working example in an earlier release which is why I opened it as a bug! 
I'm happy for it to be converted to an enhancement though, if you want to point me in the right direction of where the processing is I'd be happy to take a crack at it

**Comment by tooptoop4** [comment]
any fix?

**Comment by alexec** [comment]
I don’t believe it is possible to change this behavior The templating merging works by marshaling the string into a struct. It cannot cater for arbitrary string due to whitespacing. Even if you managed to get it to work, any small change to white space would break it.

@RoryDoherty suggestion is looks like a good work-around.

**Comment by usamaB** [comment]
```
- name: Generate argo workflow yaml file
        run: |
          helm template  \
            --set image.repository=${{ env.DOCKER_REPOSITORY }} \
            --set image.tag=${TAG} \
            --set env.TEST="TEST" \
            -f backfill/helm/values.yaml $APP_NAME charts/job > workflow-dev.yaml
```
I'm deploying the workflow via GH actions. I'm facing the problem as well.  if I remove the env.TEST line the workflow is deployed and works. Also I can set env.vars using the values file but if I try to set env.var in the GH actions workflow it gives error. 

**msg="Failed to parse workflow: json: cannot unmarshal object into Go struct field Container.spec.templates.container.env of type []v1.EnvVar"**

any idea?  I'm stuck on this for some time.

**Comment by chrisfregly** [comment]
Here is a hacky workaround that worked for me. Not a huge fan of this approach but works in a pinch.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
  namespace: argoci
spec:
  entrypoint: demo
  templates:
    - name: demo
      dag:
        tasks:
          - name: env-var-test
            template: run-test
            arguments:
              parameters:
                - name: vars
                  value: | # NOTE: quotes required around all json keys and values
                    [
                      {"name": "Foo", "value": "bar"},
                      {"name": "Bar", "value": "foo"},
                      {"name": "zoo", "value": "animal"}
                    ]

    - name: run-test
      inputs:
        parameters:
          - name: vars
      podSpecPatch: '{"containers":[{"name":"main", "env":{{inputs.parameters.vars}}}]}' # hack - patch spec manually
      script:
        image: ubuntu:18.04
        imagePullPolicy: Always
        command: [bash]
        workingDir: "/src"
        # env: {{inputs.parameters.vars}} # remove this
        source: |
          env

```
