### ISSUE TITLE
Child workflows should be visible from the parent workflow in the UI

### ISSUE THREAD

**Issue by alexrosenfeld10** [argoproj/argo-workflows#8833]
# Summary

When I kick off a child workflow using a WorkflowTemplate, like this:

```yaml
    - name: create-and-trigger-workflow-template
      serviceAccountName: foo
      inputs:
        parameters:
          - name: domain
          - name: snowflake-env
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: "{{inputs.parameters.domain}}-domain-{{inputs.parameters.snowflake-env}}-workflow-"
          spec:
            serviceAccountName: foo
            arguments:
              parameters:
              - name: domain
                value: "{{inputs.parameters.domain}}"
              - name: snowflake-env
                value: "{{inputs.parameters.snowflake-env}}"
            workflowTemplateRef:
              name: foo-domain-templates
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
```

I should be able to see the child workflow and all that goes on inside of it from the parent level workflow in the UI. Instead, I can only see the status / exit code of the child workflow:

![Screen Shot 2022-05-24 at 1 35 14 PM](https://user-images.githubusercontent.com/12940966/170097858-e56252b3-78a5-4592-8d92-8f87e130c1ee.png)

# Use Cases

When would you use this?

Any time someone wants to use a WorkflowTemplate from within a `dag` or `steps`, they must instantiate a child workflow in this fashion.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
