### ISSUE TITLE
cannot submit WorkflowTemplate with `{{workflow.labels.xxxx}}` values from v3.3.0

### ISSUE THREAD

**Issue by yu-croco** [argoproj/argo-workflows#8837]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary
What happened/what you expected to happen?
When I submit WorkflowTemplate with `{{workflow.labels.workflow-name}}` , I get status 500, `templates.argosay: failed to resolve {{workflow.labels.workflow-name}}` though the attribute is set on `.metadata.labels` below `Diagnostics` .

It does not happen on v3.2.11, but it happens from v3.3.0 to v3.3.5 . 
I couldn't find this kind of breaking change on [Upgrading to v3.3](https://argoproj.github.io/argo-workflows/breaking-changes/#upgrading-to-v33), so I am wondering if this is a bug. 🤔 

<img width="577" alt="evidence" src="https://user-images.githubusercontent.com/30188755/170266883-2e49a49b-bb6a-42b4-ad92-deb96815acef.png">

What version are you running?

v3.3.5

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
metadata:
  name: sparkly-rhino
  namespace: foo
  labels:
    example: 'true'
    workflow-name: hello-world
spec:
  templates:
    - name: argosay
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{workflow.labels.workflow-name}}'
        resources: {}
  entrypoint: argosay
  arguments: {}
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
  workflowMetadata:
    labels:
      example: 'true'
      workflow-name: hello-world
```

```bash
# Logs from workflow server when I submitted WorkflowTemplate:
time="2022-05-25T11:37:29.175Z" level=error msg="finished unary call with code Unknown" error="templates.argosay: failed to resolve {{workflow.labels.workflow-name}}" grpc.code=Unknown grpc.method=SubmitWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2022-05-25T11:37:29Z" grpc.time_ms=29.021 span.kind=server system=grpc

# response on Google Chrome developer tool when I submitted WorkflowTemplate:
{
  code: 2,
  message: "templates.argosay: failed to resolve {{workflow.labels.workflow-name}}"
}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
