### ISSUE TITLE
imagePullSecret not working when defined in ServiceAccount

### ISSUE THREAD

**Issue by jrowinski3d** [argoproj/argo-workflows#8855]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

Setting `imagePullSecret` in a Service Account results in private image not being pulled.

## Diagnostics

Create a secret with your private registry key, append that to your SA and set the SA in your workflow

```yaml

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  serviceAccountName: argo
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest. <--- must be private
      command: [cowsay]
      args: ["hello world"]
      
      
      
apiVersion: v1
imagePullSecrets:
- name: my-private-registry
kind: ServiceAccount
metadata:
  name: argo
  namespace: argo


```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
