### ISSUE TITLE
Container json schema should have `image` be optional

### ISSUE THREAD

**Issue by alexrosenfeld10** [argoproj/argo-workflows#8866]
As per the title, the container json schema should allow `image` to be optional. It's perfectly reasonable to set some `templateDefaults` that look like this:

```yaml
  templateDefaults:
    container:
      name: main
      image: my-company-docker.jfrog.io/my-company/my-container:0.1.2
      env:
        - name: FOO
          value: "BAR"
```

and then _omit_ the `image` from each template, to DRY the yaml schema. However, that's not possible because it results in an error:
![Screen Shot 2022-05-26 at 4 26 23 PM](https://user-images.githubusercontent.com/12940966/170574364-3ff371a8-5964-483b-8f49-db0d83bb0ed9.png)
