### ISSUE TITLE
add .netrc support for git artifacts

### ISSUE THREAD

**Issue by larrycai** [argoproj/argo-workflows#8879]
# Summary

workflow/artifacts/git/git.go it support private key and passwd, it will be good to support .netrc as well

# Use Cases

When would you use this? normally we store all related passwd into one `.netrc` to access different repo, it will be good to support it directly.

It could work like below

````
  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: /src
        git:
          repo: https://github.com/argoproj/argo-workflows.git
          revision: "v2.1.1"
          # netrcSecret:
          #   name: github-creds
          #   key: netrc
`````

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
