### ISSUE TITLE
Long container args and/or script source overflows in UI

### ISSUE THREAD

**Issue by dakotalillie** [argoproj/argo-workflows#8916]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

Providing a lengthy argument to a container template, or a lengthy source to a script template, causes the provided argument/source to visually overflow in the UI.

I have observed this issue in multiple versions, including:

- v3.3.6
- "latest" (master branch)

## Diagnostics

Here are two YAML examples which can be used to reproduce this issue, along with screenshots of the UI for each:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-
spec:
  entrypoint: example
  templates:
  - name: example
    container:
      image: ubuntu:latest
      command: [bash]
      args:
        - -c
        - |-
          # The exact contents of this script don't matter.
          # All that matters for this example is that the line is sufficiently long.
          if [ "$EXAMPLE_ENV_VAR" == "hello darkness my old friend" ]; then
            echo "Hello world!"
          fi
```

<img width="569" alt="Screen Shot 2022-06-04 at 6 12 40 PM" src="https://user-images.githubusercontent.com/20373585/172030792-1c4dd580-632a-48fc-92e7-d018dafe73fb.png">

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-
spec:
  entrypoint: example
  templates:
  - name: example
    script:
      image: ubuntu:latest
      command: [bash]
      source: |-
        # The exact contents of this script don't matter.
        # All that matters for this example is that the line is sufficiently long.
        if [ "$EXAMPLE_ENV_VAR" == "hello darkness my old friend" ]; then
          echo "Hello world!"
        fi
```

<img width="569" alt="Screen Shot 2022-06-04 at 6 14 00 PM" src="https://user-images.githubusercontent.com/20373585/172030815-df8d3ef5-9081-46c6-992d-b76fe5168963.png">

It looks like a similar issue was addressed in #7876. Adopting the same fix for this should be straightforward. However, I wanted to check first to see whether an alternative solution might be preferable, such as using a scrollbar. Here's what two potential solutions might look like:

<img width="569" alt="Screen Shot 2022-06-04 at 6 21 23 PM" src="https://user-images.githubusercontent.com/20373585/172030951-3daeca9d-c879-4eef-8c93-d041c5eb017e.png">

https://user-images.githubusercontent.com/20373585/172031016-3c0ba8b4-2d61-4a5f-b4e5-9a61abe1d76b.mov

Either way, I'm happy to submit a PR.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
