### ISSUE TITLE
Cannot schedule/dispatch to new node

### ISSUE THREAD

**Issue by forcemeter** [argoproj/argo-workflows#8932]
![image](https://user-images.githubusercontent.com/56063441/172643712-e5170b20-3e6e-494f-96dd-f0b877b9ff22.png)

We submitted 10k `Pending` jobs 5 hours ago, and then join 4 new k3s nodes.

now all the `Pending` jobs just only schedule to the older nodes (in the red box), 
and never schedule to the `4 new k3s nodes`.

is there any config parameter can refetch and schedule to all nodes of k3s cluster?

Kubernetes gitVersion: v1.23.6+k3s1
argo workflow version:  3.3.1

**Comment by botsphp** [comment]
update:

force `podAntiAffinity` to can solve our needs, and i think this may is not a bug.
```
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: workflows.argoproj.io/workflow
                  operator: Exists
            topologyKey: kubernetes.io/hostname
          weight: 100
```
