### ISSUE TITLE
Error to use outputs parameters as a name of template

### ISSUE THREAD

**Issue by DiegoFlop** [argoproj/argo-workflows#8938]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

I use gitArtifact for clone a git repository at the first step, On this step it reads a config json file for select that will happen with the next steps, for example omit one step, when I use outputs with a values parameters on other step It works correctly, how ever when I want to use outputs parameters as a name of template, I get an error. ` Failed: invalid spec: templates.main.tasks.build-image template reference build-image.{{= jsonpath(tasks.checkout.outputs.parameters.custom_config, '$.image_builder'}} not found` also I try with ` Failed: invalid spec: templates.main.tasks.build-image template reference build-image.{{tasks.checkout.outputs.parameters.custom_config}} not found` but I get the same result.
 With the inputs or workflow parameters It works correctly. 

I would like to use output parameters in others fields than anyhow value parameters on steps

What version are you running?

Kubernetes: 1.22.9
Argo workflows: 3.3.6

## Diagnostics

*First step*
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: checkout
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        artifacts:
          - name: git-clone
            path: "XXXXXXXX"
            git:
              branch: "XXXXXXXX"
              depth: 1
              repo: "XXXXXXXX"
              singleBranch: true
              sshPrivateKeySecret:
                name: github
                key: id_rsa
              insecureIgnoreHostKey: true
      outputs:
        parameters:
          - name: custom_config
            valueFrom:
              path: "PATH_OUTPUT_FILE"
      container:
        image: python:latest
        command:
          - "python"
        args:
          - "/utils/script.py"
```
*main template*
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: main
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: URL
          - name: BRANCH 
      dag:
        tasks:
        - name: checkout
          templateRef:
            name: checkout
            template: main
        - name: build-image
          templateRef:
            name: build-image
            template: "{{= jsonpath(tasks.checkout.outputs.parameters.custom_config, '$.image_builder') }}"
          depends: "checkout"
```

I don't get any logs, because the workflow doesn't start

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by CRASH-Tech** [comment]
Also have this issue:
```
            templateRef:
              name: argocd-publish
              template: "{{ item.syncPolicy }}"
              clusterScope: true
```

`Failed: invalid spec: templates.ci-pipeline-git-tag.tasks.publish template reference argocd-publish.{{ item.syncPolicy }} not found`
