### ISSUE TITLE
MetricsError: 'workflow.duration' is not available as a real time metric

### ISSUE THREAD

**Issue by frimuchkov** [argoproj/argo-workflows#8997]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
I expect to see workflow.duration in real time, but I see an error

What version are you running?
3.3.6

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
metadata:
  name: awesome-poochenheimer
  namespace: default
  labels:
    example: 'true'
spec:
  metrics:
    prometheus:
      - name: workflow_duration_gauge
        help: Workflow duration
        gauge:
          value: '{{workflow.duration}}'
          realtime: true
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
