### ISSUE TITLE
Improve wait container

### ISSUE THREAD

**Issue by kaiyuanlim-adh** [argoproj/argo-workflows#9007]
# Summary
- Currently, we have a problem whereby our linkerd-proxy container which runs as a multi-container pod comes up slower than the main container in our argoworkflow step.
- This means that the main container will not have access to the network like the internet and thus the job will fail.
- Currently we used a sleep command in the main container but that is hacky.
- We also tried using a container set with a dependency on another container that waits for linkerd-proxy to be ready.
- This was added into the workflowDefaults in the helm chart for argoworkflow but this can easily also be overwritten or will be ignored if user submitted a workflow without a containerset:

```
containerSet:
          containers:
            - name: wait-linkerd-container
              image: curlimages/curl:7.83.0'
              command:
                - sh
                - '-c'
              args:
                - >-
                  until curl --silent --head localhost:4191 ; do echo Waiting for
                  linkerd-proxy; sleep 3 ; done ; echo linkerd-proxy available;
              resources: {}
              imagePullPolicy: Always
            - name: r-container
              resources: {}
              dependencies:
                - wait-linkerd-container
```

What change needs making?
- Perhaps a new field to input a container name that has to be ready before starting the main container?
- Or even better would be a field that allows multiple container names that have to be in a ready state before starting the other containers in a multi-container setup?

# Use Cases
- Sidecars such as linkerd-proxy or storage API containers that needs to be ready before running the main container.

When would you use this?
- In my use case, very often as we use linkerd-proxy for service mesh.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
