### ISSUE TITLE
failed to resolve inputs.parameters

### ISSUE THREAD

**Issue by ZPerling** [argoproj/argo-workflows#9015]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

 when I submit a workflow ,it return error,  failed to resolve {{inputs.parameters.path}}, 
I confirm the yaml is valid, I don know what happend

**argo client version:**
argo: v3.3.6
  BuildDate: 2022-05-26T01:07:24Z
  GitCommit: 2b428be8001a9d5d232dbd52d7e902812107eb28
  GitTreeState: clean
  GitTag: v3.3.6
  GoVersion: go1.17.10
  Compiler: gc
  Platform: darwin/amd64

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: java-gitops-flow-
spec:
  entrypoint: gitops-flow
  volumes:
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 10Gi

  templates:
  - name: gitops-flow
    steps:
      - - name: git-clone
          template: git-clone
          arguments:
            parameters:
            - name: revision
              value: "{{item.revision}}"
            - name: path
              value: "{{item.path}}"
            - name: repo
              value: "{{item.repo}}"
          withItems:
          - { repo: 'git@git.xx.com:/sample.git', revision: 'master', path: 'springboot-sample' }
          - { repo: 'git@git.xx.com:/xxx.git', revision: 'main', path: 'springboot-build' }

  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: "{{inputs.parameters.path}}"
        git:
          repo: "{{inputs.parameters.repo}}"
          revision: "{{inputs.parameters.revision}}"
          insecureIgnoreHostKey: true
          sshPrivateKeySecret:
            name: ssh
            key: ssh-privatekey
    container:
      image: bitnami/git:2.36.1-debian-10-r28
      command: [sh, -c]
      args: ["git status && git --no-pager log -1 && ls"]
      workingDir: "/src/{{inputs.parameters.path}}"
      volumeMounts:
      - name: work
        mountPath: /src
```

```bash
➜  argo submit ./gitops-flow.yaml
FATA[2022-06-21T14:20:48.655Z] Failed to submit workflow: templates.gitops-flow.steps[0].git-clone templates.git-clone: failed to resolve {{inputs.parameters.path}} 
```
