### ISSUE TITLE
Dag and Steps unsual behaviour for loop with withParams

### ISSUE THREAD

**Issue by ldejuan** [argoproj/argo-workflows#9018]
## Checklist

 

* [x ] Double-checked my configuration.
* [x ] Tested using the latest version.
* [x ] Used the Emissary executor. (:latest)

## Summary

What happened/what you expected to happen?
The behavior of a workflow with **DAG** and **STEPS** is different in loops with **withParam**

What version are you running?
**argo version**
argo: v3.3.5
  BuildDate: 2022-05-04T00:58:31Z
  GitCommit: eefc60b155c4011a3706d2e3cba90f099ee93b39
  GitTreeState: clean
  GitTag: v3.3.5
  GoVersion: go1.17.9
  Compiler: gc
  Platform: linux/amd64

**Kubernetes Version** 
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.23.6

### With a DAG Workflow

```yaml
# This workflow demonstrates the use of a generator step which produces a list of items as a result.
# This list is subsequently used for expanding the next step into multiple parallel steps.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-result-
spec:
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    dag:
      tasks:
      - name: generate
        template: gen-number-list
      - name: sleep
        template: sleep-n-sec
        withParam: "{{tasks.generate.outputs.parameters.values}}"
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
  - name: gen-number-list
    outputs:
      parameters:
      - name: values
        valueFrom:
          path: /tmp/values.txt  
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        values=['{0}'.format(i) for i in range(20, 31)]  
        json.dump(values,sys.stdout)
        f=open('/tmp/values.txt', 'w')
        json.dump(values, f)
        f.close()
  - name: sleep-n-sec
    inputs:
      parameters:
      - name: seconds
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo value in seconds :{{inputs.parameters.seconds}}"]
```
The logs are: 
```bash
Name:                loops-param-result-7kt7b
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Error
Conditions:
 PodRunning          False
 Completed           True
Created:             Tue Jun 21 15:01:56 +0000 (17 seconds ago)
Started:             Tue Jun 21 15:01:56 +0000 (17 seconds ago)
Finished:            Tue Jun 21 15:02:06 +0000 (7 seconds ago)
Duration:            10 seconds
Progress:            1/1
ResourcesDuration:   4s*(1 cpu),2s*(100Mi memory)

STEP                         TEMPLATE                   PODNAME                                              DURATION  MESSAGE
 ⚠ loops-param-result-7kt7b  loop-param-result-example                                                                                                                                                                                          
 ├─✔ generate                gen-number-list            loops-param-result-7kt7b-gen-number-list-1492933679  6s                                                                                                                                 
 └─⚠ sleep                   sleep-n-sec                                                                               withParam value could not be parsed as a JSON list: {{tasks.generate.outputs.parameters.values}}: invalid character '{' looking for beginning of object key string
```

### Workflow with a  STEPS 
However with the following STEPS workflow : 
```yaml
# This workflow demonstrates the use of a generator step which produces a list of items as a result.
# This list is subsequently used for expanding the next step into multiple parallel steps.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-result-
spec:
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    steps:
    - - name: generate
        template: gen-number-list
    - - name: sleep
        template: sleep-n-sec
        withParam: "{{steps.generate.outputs.parameters.values}}"
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
  - name: gen-number-list
    outputs:
      parameters:
      - name: values
        valueFrom:
          path: /tmp/values.txt  
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        values=['{0}'.format(i) for i in range(20, 31)]  
        json.dump(values,sys.stdout)
        f=open('/tmp/values.txt', 'w')
        json.dump(values, f)
        f.close()

  - name: sleep-n-sec
    inputs:
      parameters:
      - name: seconds
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo value in seconds :{{inputs.parameters.seconds}}"]
```
```bash
Name:                loops-param-result-nxjq8
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Running
Conditions:
 PodRunning          False
Created:             Tue Jun 21 14:56:11 +0000 (25 seconds ago)
Started:             Tue Jun 21 14:56:11 +0000 (25 seconds ago)
Duration:            25 seconds
Progress:            1/12
ResourcesDuration:   3s*(1 cpu),2s*(100Mi memory)

STEP                         TEMPLATE                   PODNAME                                              DURATION  MESSAGE
 ● loops-param-result-nxjq8  loop-param-result-example                                                                  
 ├───✔ generate              gen-number-list            loops-param-result-nxjq8-gen-number-list-1492933679  5s         
 └─┬─◷ sleep(0:20)           sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-3410121937      15s       PodInitializing
   ├─◷ sleep(1:21)           sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-1843571807      15s       PodInitializing
   ├─◷ sleep(2:22)           sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-3326085877      15s       PodInitializing
   ├─◷ sleep(3:23)           sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-413280631       15s       PodInitializing
   ├─◷ sleep(4:24)           sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-2596170073      14s       PodInitializing
   ├─◷ sleep(5:25)           sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-1631419543      14s       PodInitializing
   ├─◷ sleep(6:26)           sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-593953141       14s       PodInitializing
   ├─◷ sleep(7:27)           sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-753577647       14s       PodInitializing
   ├─◷ sleep(8:28)           sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-2918238593      14s       PodInitializing
   ├─◷ sleep(9:29)           sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-1351688463      14s       PodInitializing
   └─◷ sleep(10:30)          sleep-n-sec                loops-param-result-nxjq8-sleep-n-sec-3476527655      13s       PodInitializing
```
Everything seems to work as expected

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
