### ISSUE TITLE
Cannot connect Argo Workflow with a local Nvidia GPU.

### ISSUE THREAD

**Issue by sebastian-sz** [argoproj/argo-workflows#9066]
## Checklist
* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary
I am trying to expose my GPU to Argo Workflow.

* I am running Minikube with `driver=None`
* I have followed and completed the steps in [Nvidia's repo](https://github.com/NVIDIA/k8s-device-plugin#quick-start)
* I am successfully able to access GPU running [Nvidia's Example](https://github.com/NVIDIA/k8s-device-plugin#running-gpu-jobs)

Yet when trying to use a GPU with Argo workflow (in the `argo` namespace), the workflow is stuck with a message:  
`Unschedulable: 0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector.`

## Diagnostics
My workflow:  
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow            
metadata:
  generateName: gpu-check-
spec:
  entrypoint: simple-check
  templates:
    - name: simple-check
      nodeSelector:
        nvidia.com/gpu: "true"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"

      container:
        image: nvidia/cuda:11.0-base
        command: [ nvidia-smi ]
        resources:
          limits:
            nvidia.com/gpu: 1
```
My command:
```bash
# Setup argo
kubectl create ns argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml

# Run
argo submit -n argo --watch above_file.yaml
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Is it working with a standalone pod?

**Comment by sebastian-sz** [comment]
@terrytangyuan Yes, running from Nvidia example:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
EOF
```
Inspecting logs:  
```
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```
