### ISSUE TITLE
Unable to load the root of s3 bucket path as an artifact on argo

### ISSUE THREAD

**Issue by louisnow** [argoproj/argo-workflows#9077]
## Summary

What happened/what you expected to happen?

Unable to load the root path of the s3 bucket in argo. Attaching sample workflow where I've tried specifying the key as `/`
I expect to be able to load the bucket as an artifacts.

Use Case: We have multiple buckets for different data resources/projects. All of the data needed is at the root of the bucket and it seems to be impossible to load the entire bucket from argo.

Argo just ignores the key which is just `/` which is the path to the entire bucket

What version are you running?
v3.2.9
Emissary Executor

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: retry
spec:
  entrypoint: start
  templates:
    - name: start
      inputs:
        parameters:  
          # s3 bucket details
          - name: s3-bucket
            value: "<BUCKET_NAME>"
          - name: s3-prefix
            value: "/"

      dag:
        tasks:
          - name: say-something
            template: something
            arguments:
              parameters:
                - name: s3-bucket
                  value: "{{inputs.parameters.s3-bucket}}"
                - name: s3-prefix
                  value: "{{inputs.parameters.s3-prefix}}"
              artifacts:
                - name: input
                  s3:
                    bucket: "{{inputs.parameters.s3-bucket}}"
                    key: "{{inputs.parameters.s3-prefix}}"
                  optional: true

    - name: something
      inputs:
        parameters:
          - name: s3-bucket
            value: "{{inputs.parameters.s3-bucket}}"
          - name: s3-prefix
            value: "{{inputs.parameters.s3-prefix}}"
        artifacts:
          - name: input
            path: /tmp/input
      script:
        image: python:alpine
        imagePullPolicy: IfNotPresent
        command: [ python ]
        source: |
            import os
            import time
            print("hello")
            
            print(os.listdir(path='/tmp'))
            print("\n listing files for tmp/input: \n")

            if os.path.isfile('/tmp/input'):
              print(os.listdir(path='/tmp/input'))
```

Logs from argo
```
time="2022-06-29T13:43:51.546Z" level=info msg="Loading script source to /argo/staging/script"
time="2022-06-29T13:43:51.547Z" level=info msg="Start loading input artifacts..."
time="2022-06-29T13:43:51.547Z" level=info msg="Downloading artifact: input"
time="2022-06-29T13:43:51.547Z" level=info msg="S3 Load path: /argo/inputs/artifacts/input.tmp, key: /"
time="2022-06-29T13:43:51.547Z" level=info msg="Creating minio client using AWS SDK credentials"
time="2022-06-29T13:43:54.706Z" level=info msg="Getting file from s3" bucket=<BCUKET_NAME>endpoint=s3.ap-south-1.amazonaws.com key=/ path=/argo/inputs/artifacts/input.tmp
time="2022-06-29T13:43:54.849Z" level=info msg="Skipping optional input artifact that was not found: input"
```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
