### ISSUE TITLE
Runtime error on missing logs for Argo Workflows configured with S3 bucket

### ISSUE THREAD

**Issue by sarasensible** [argoproj/argo-workflows#9080]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor - I used the default of `containerRuntimeExecutor: emissary` in my helm chart

## Summary

What happened/what you expected to happen?
I looked for logs to show up under a sample workflow configured with a service account that has S3 access with an S3 bucket as an artifact repository, and there were no logs either in the UI or in the bucket.  The logs don't have a clear error but a traceback with a runtime error, which seems like a bug.  In the UI it just says "Unsuccessful HTTP response" which seems like a catchall when the server is confused.  

In the developer console I can see this request:
https://workflows.dev.tools.sw.io/artifacts-by-uid/90c5970a-e9f2-416e-b26b-331485dc044a/delightful-octopus/main-logs
came back with a 502.

What version are you running?
3.3.8

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
metadata:
  namespace: tools
  name: delightful-octopus
spec:
  serviceAccountName: argo
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      outputs: {}
      metadata: {}
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
        resources: {}
  entrypoint: argosay
  arguments:
    parameters:
      - name: message
        value: hello argo
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

This is running under the "argo" service account which has the following yaml

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT}:role/S3ForArgoWorkflows
```

The role contains a policy which gives it access to the S3 bucket it should be able to populate, using a more permissive one for now while testing.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucket*"
            ],
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject*",
                "s3:PutObject*",
                "s3:DeleteObject*",
                "s3:RestoreObject*"
            ],
            "Resource": "arn:aws:s3:::*"
        }
    ]
}
```

# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller

```
time="2022-06-29T17:52:33.955Z" level=info msg="Download artifact" artifactName=main-logs isInput=false nodeId=delightful-octopus uid=90c5970a-e9f2-416e-b26b-331485dc044a
2022/06/29 17:52:33 http: panic serving 10.0.23.42:47734: runtime error: invalid memory address or nil pointer dereference
goroutine 2481 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x2416760, 0x4c79000})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/argoproj/argo-workflows/v3/workflow/artifactrepositories.(*artifactRepositories).get(0xf80000000040b185, {0x36e0fa8, 0xc00097e1e0}, 0xc0046a5e10)
	/go/src/github.com/argoproj/argo-workflows/workflow/artifactrepositories/artifactrepositories.go:76 +0x39
github.com/argoproj/argo-workflows/v3/workflow/artifactrepositories.(*artifactRepositories).Get(0xc004492e00, {0x36e0fa8, 0xc00097e1e0}, 0xc0045642ee)
	/go/src/github.com/argoproj/argo-workflows/workflow/artifactrepositories/artifactrepositories.go:68 +0x25
github.com/argoproj/argo-workflows/v3/server/artifacts.(*ArtifactServer).returnArtifact(0xc0003e7c20, {0x36e0fa8, 0xc00097e1e0}, {0x36cc6e0, 0xc00087ea80}, 0x12, 0xc0009dc900, {0xc0045642db, 0x12}, {0xc0045642ee, ...}, ...)
	/go/src/github.com/argoproj/argo-workflows/server/artifacts/artifact_server.go:176 +0x1fc
github.com/argoproj/argo-workflows/v3/server/artifacts.(*ArtifactServer).getArtifactByUID(0xc0003e7c20, {0x36cc6e0, 0xc00087ea80}, 0xc000ae6100, 0x0)
	/go/src/github.com/argoproj/argo-workflows/server/artifacts/artifact_server.go:130 +0x41b
github.com/argoproj/argo-workflows/v3/server/artifacts.(*ArtifactServer).GetOutputArtifactByUID(...)
	/go/src/github.com/argoproj/argo-workflows/server/artifacts/artifact_server.go:92
net/http.HandlerFunc.ServeHTTP(0x0, {0x36cc6e0, 0xc00087ea80}, 0xc00087ea80)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0x36cc6e0, 0xc00087ea80}, 0xc000ae6100)
	/usr/local/go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc00494e8a0}, {0x36cc6e0, 0xc00087ea80}, 0xc000ae6100)
	/usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc004b44000, {0x36e0fa8, 0xc0043c0f00})
	/usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8
```

Skipping the logs output since the workflow was successful and was not the source of the issue.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
