### ISSUE TITLE
Argo CronWorkflow unknown time zone 

### ISSUE THREAD

**Issue by leonidas-o** [argoproj/argo-workflows#9091]
## Summary

As soon as I add `timezone: "Europe/Zurich"` the workflow is not generated out of the cron workflow. When I remove it, all works fine, then I add back the timezone, it shows and also counts (countdown) correctly inside the UI, but it is not creating a workflow.
Should be resolved according to: https://github.com/argoproj/argo-workflows/issues/5653

Running on Argo Workflows 3.3.8 deployed via bitnami helm chart

## Diagnostics

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: my-cron-workflow
  namespace: MYNAMESPACE
spec:
  schedule: "0 10 * * *"
  timezone: "Europe/Zurich"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    serviceAccountName: MYSERVICEACCOUNTNAME
    entrypoint: main

    templates:
    - name: main
      steps:
      - - name: setup-env
          template: setup-env-tmpl

    - name: setup-env-tmpl
      script:
        image: alpine:latest
        command: [bash]
        source: |
          echo "foo"
```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep error
time="2022-07-01T13:43:18.420Z" level=error msg="could not schedule CronWorkflow" cronWorkflow=MYNAMESPACE/MY-cron-workflow error="provided bad location Europe/Zurich: unknown time zone Europe/Zurich"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
