### ISSUE TITLE
wait container doesn't update Artifact location in Workflow Status if Template.ArchiveLocation is specified

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-workflows#9092]
If I set Template.ArchiveLocation, the wait container doesn't seem to reflect that location in the NodeStatus. I believe it is a change that needs to be made in executor.go on this [line](https://github.com/argoproj/argo-workflows/blob/master/workflow/executor/executor.go#L342).

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-gc-
spec:
  entrypoint: main
  artifactGC:
    strategy: OnWorkflowDeletion
  podGC:
    strategy: ""
  templates:
    - name: main
      archiveLocation:
        s3:
          key: on-deletion-key
          bucket: my-bucket-2
          endpoint: minio:9000
          insecure: true
          accessKeySecret:
            name: my-minio-cred
            key: accesskey
          secretKeySecret:
            name: my-minio-cred
            key: secretkey
      container:
        image: argoproj/argosay:v2
        command:
          - sh
          - -c
        args:
          - |
            echo "hello world" > /tmp/message
      outputs:
        artifacts:
          - name: on-deletion
            path: /tmp/message
```
