### ISSUE TITLE
Support mounting `workflow-controller-configmap` as a volume to prevent need for manual restarts 

### ISSUE THREAD

**Issue by agrvu** [argoproj/argo-workflows#9123]
# Summary
Currently the `workflow-controller-configmap` reference is passed in as a CLI argument to both the argo server and workflow-controller. As such, when the configmap is updated it does not automatically trigger a restart of workflow controller's pods which means the pods have to manually bounced in order for the new config to be picked up by the controller. 

# Use Cases
To avoid the need for manual restarts of pods the workflow controller could support loading the configmap from disk. That way the configmap could be mounted as a volume and the versioning functionality of [kustomize's configmapgenerator](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/) used to trigger a name change to the configmap when the content changes which in turn would trigger an update to the deployment and a restart of pods which would then pick up the new configuration. eg:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - name: workflow-controller
        [ ... ]
        volumeMounts:
        - name: workflow-controller-configmap
          path: /opt
          subPath: workflow-controller-configmap.yaml
      [ ... ]
      volumes:
      - name: workflow-controller-configmap
        configMap:
          name: workflow-controller-configmap-34324 # versioned using kustomize's configmapgenerator functionality
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
