### ISSUE TITLE
sprig functions are re-evaluated when passed as a parameter, expect them to be evaluated once then set for rest of workflow

### ISSUE THREAD

**Issue by RoryDoherty** [argoproj/argo-workflows#9166]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Used a sprig function to generate a random variable name that I want all tasks to have access to however the random string is regenerated for each step in the dag. In the below example the input for both run-test templates is different even though it is passed from the same initial variable

What version are you running?
3.3.8

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
spec:
  entrypoint: dag-of-dags
  templates:
    - name: dag-of-dags
      dag:
        tasks:
          - name: test
            template: dag-test
            arguments:
              parameters:
                - name: var
                  value: "name-{{=sprig.randAlphaNum(5)}}"

    - name: dag-test
      inputs:
        parameters:
          - name: var
      dag:
        tasks:
          - name: test
            template: run-test
            arguments:
              parameters:
                - name: var
                  value: "{{inputs.parameters.var}}"
          - name: test-2
            depends: test
            template: run-test-2
            arguments:
              parameters:
                - name: var
                  value: "{{inputs.parameters.var}}"

    - name: run-test
      inputs:
        parameters:
          - name: var
      script:
        image: ubuntu:18.04
        imagePullPolicy: Always
        command: [bash]
        workingDir: "/src"
        env: 
          - name: var_test
            value: "{{inputs.parameters.var}}"
        source: |
          echo $var_test

    - name: run-test-2
      inputs:
        parameters:
          - name: var
      script:
        image: ubuntu:18.04
        imagePullPolicy: Always
        command: [bash]
        workingDir: "/src"
        env: 
          - name: var_test
            value: "{{inputs.parameters.var}}"
        source: |
          echo $var_test

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
