### ISSUE TITLE
UI: `e.templateRef is undefined` when using inline template

### ISSUE THREAD

**Issue by antoinetran** [argoproj/argo-workflows#9167]
## Checklist

 

* [ ] Double-checked my configuration.
* [ ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Creates a simple workflow with inline template. It should succeed.

What version are you running?
Argo v3.2.11

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

From https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/steps-inline-workflow.yaml:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-inline-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      This workflow demonstrates running a steps with inline templates.
    workflows.argoproj.io/version: ">= 3.2.0"
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: a
            inline:
              container:
                image: argoproj/argosay:v2
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
