### ISSUE TITLE
`backoff` under `retryStrategy` does not work as expected for version 3.3.8

### ISSUE THREAD

**Issue by Ali-RT** [argoproj/argo-workflows#9170]
The `backoff` feature for `retryStrategy` does not behave as expected under version `3.3.8`. 
```
      retryStrategy:
        limit: "10"
        backoff:
          duration: "30m"   
```
The workflow was retried 10 times, but the wait time between each retry call was about 21 seconds. 

Tested under version `3.2.4`, and it worked as expected.

**Comment by sarabala1979** [comment]
@dpadhiar Can you try to reproduce this issue?

**Comment by dpadhiar** [comment]
@sarabala1979 Yes.

**Comment by dpadhiar** [comment]
@sarabala1979 Confirmed backoff duration isn't working on 3.3.8.

**Comment by raafatseif** [comment]
Hi @sarabala1979 @dpadhiar ! Do you think this can be fixed in a new release soon? It's the only thing preventing us from deploying to production so far.

**Comment by dpadhiar** [comment]
@raafatseif Yes, we will look into getting this fixed before 3.3.9/3.4 is released.

**Comment by HRusby** [comment]
To add to this, I've tested against v3.3.7 where the Backoff duration is working. This issue must have been introduced between v3.3.7 and v3.3.8

**Comment by raafatseif** [comment]
@HRusby I was able to reproduce the issue in v3.3.7

**Comment by HRusby** [comment]
> @HRusby I was able to reproduce the issue in v3.3.7

Interesting, I've been using the following to test which is working in v3.3.7, perhaps it's too naive a test.

```yaml
metadata:
  name: retry-backoff-test
spec:
  entrypoint: test
  templates:
  - name: test
    retryStrategy:
      limit: 3
      backoff:
        duration: 1m
    dag:
      tasks:
        - name: Succeed
          template: success-step
        - name: Fail
          template: fail-step
  - name: success-step
    script:
        image: 'bash'
        command: [bash]
        source: |
          echo "Some Succeeding Logic"
          exit 0
  - name: fail-step
    retryStrategy:
      limit: 2
      backoff:
        duration: 30s
    script:
        image: 'bash'
        command: [bash]
        source: |
          echo "Some Failing Logic"
          exit 1
```
