### ISSUE TITLE
Support ValueFrom.Expression on Workflow level argument

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#9172]
# Summary

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
spec:
  arguments:
    parameters:
      - name: var
        valueFrom:
          expression: "name-{{=sprig.randAlphaNum(5)}}"

```

What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
