### ISSUE TITLE
Specifying tty and stdin as true but still not getting a tty in the container

### ISSUE THREAD

**Issue by RoryDoherty** [argoproj/argo-workflows#9179]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Ran the below workflow expecting the container to have a tty but when I run the `tty` command I get `not a tty`

What version are you running?
3.3.8

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
spec:
  entrypoint: run-test
  templates:
    - name: run-test
      container:
        image: ubuntu:18.04
        imagePullPolicy: Always
        command: ["tty"]
        tty: true
        stdin: true
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@RoryDoherty Can you try the above `image` and command create POD?

**Comment by RoryDoherty** [comment]
> @RoryDoherty Can you try the above `image` and command create POD?

I'm not sure what you mean by this, di you mean the following?:
```
rory@laptop:/$ docker run -it ubuntu:18.04 tty
/dev/pts/0
```

but if I run this then I get the `not a tty` output:
```
rory@laptop:/$ docker run ubuntu:18.04 tty
not a tty
```

**Comment by RoryDoherty** [comment]
@sarabala1979 let me know if the above is not correct and there was something else you wanted me to try, happy to help try debug this

**Comment by RoryDoherty** [comment]
@sarabala1979 did some more testing:

Without tty and stdin set to true:
```
rory@laptop:~$ cat testnotty.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: pod-no-tty-test
  namespace: argoci
spec:
  restartPolicy: Never
  containers:
  - name: pod-no-tty
    image: ubuntu:18.04
    command: [tty]
rory@laptop:~$ k apply -n argoci -f testnotty.yaml
pod/pod-no-tty-test created
rory@laptop:~$ k logs -n argoci pod-no-tty-test
not a tty
```

With tty and stdin set to true:
```
rory@laptop:~$ cat testwithtty.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: pod-tty-test
  namespace: argoci
spec:
  restartPolicy: Never
  containers:
  - name: pod-tty
    image: ubuntu:18.04
    command: [tty]
    stdin: true
    tty: true
rory@laptop:~$ k apply -n argoci -f testwithtty.yaml
pod/pod-tty-test created
rory@laptop:~$ k logs -n argoci pod-tty-test
/dev/pts/0
```

I'm assuming the issue lies in this line: 
https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/workflowpod.go#L388

argoexec is using `os.exec` to call the original command so we lose the tty status here
https://github.com/argoproj/argo-workflows/blob/master/cmd/argoexec/commands/emissary.go#L212

Would it be possible to add an option to the argoexec emissary command e.g. -tty to use something like https://github.com/creack/pty to make the command believe it is running in a tty
