### ISSUE TITLE
Parameter field `description` not recognized

### ISSUE THREAD

**Issue by sakvaka** [argoproj/argo-workflows#9187]
## Checklist

 

* [X] Double-checked my configuration.
* [X] Tested using the latest version.
* [X] Used the Emissary executor.

## Summary

`WorkflowTemplate`s do not actually support the field `description` in a `parameter`. However, I would expect the `description` field to work since it is listed [here](https://argoproj.github.io/argo-workflows/fields/#fields_28) as one of possible attributes to a `parameter` object.

I am using Argo Workflows 3.3.8 on EKS 1.22.

## Diagnostics

When I define the following WorkflowTemplate in a file named `test.yaml`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-template
spec:
  arguments:
    parameters:
      - name: message
        value: hello world
        description: something to say
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```
and submit it with `argo template create -n argo test.yaml`, it gives the following error message: `Failed to parse workflow template: json: unknown field "description"`.

The `description` field is not supported in a template's input, either, so the following `yaml` fails too:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-template
spec:
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
            value: hello world
            description: something to say
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
