### ISSUE TITLE
`retryStrategy` with `nodeAntiAffinity` is not working as expected.

### ISSUE THREAD

**Issue by cwichka** [argoproj/argo-workflows#9193]
## Summary

What happened/what you expected to happen?

I wanted to use `retryStrategy` with `nodeAntiAffinity` in order to prevent retrials from running on the same hosts. I was using the following small workflow for testing, but what happens is all retrials were started on the same host (node).
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: random-fail-
spec:
  entrypoint: random
  templates:
  - name: random
    retryStrategy:
      limit: 10
      retryPolicy: "Always"
      affinity:
        nodeAntiAffinity: {}
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        import time
        random.seed(time.time())
        i = random.randint(0, 10)
        print(i)
        exit(i)`
```
Not sure if this is an expected behavior and in my case i should use `RetryNodeAntiAffinity` which is, as mentioned in the documentation, is a placeholder for future expansion.

What version are you running?
Tested with v3.2.9 and v3.3.3

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
