### ISSUE TITLE
Error: runtime error: invalid memory address or nil pointer dereference (3.3.8)

### ISSUE THREAD

**Issue by Siebjee** [argoproj/argo-workflows#9269]
## Summary

When a `valueFrom` is used in a workflow parameter (`arguments.parameters`) it produces a:

```
Error: runtime error: invalid memory address or nil pointer dereference
```

What version are you running?

3.3.8

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-secret
data:
  test: changeme

---
# The coinflip example combines the use of a script result,
# along with conditionals, to take a dynamic path in the
# workflow. In this example, depending on the result of the
# first step, 'flip-coin', the template will either run the
# 'heads' step or the 'tails' step.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-workflow-parameters-1
  annotations:
    workflows.argoproj.io/description: |
      This is an example of coin flip defined as a sequence of conditional steps.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#coin-flip
spec:
  entrypoint: coinflip
  arguments:
    parameters:
    - name: foobar
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: test

  templates:
  - name: coinflip
    steps:
    - - name: flip-coin
        template: flip-coin
    - - name: heads
        template: heads
        when: "{{steps.flip-coin.outputs.result}} == heads"
      - name: tails
        template: tails
        when: "{{steps.flip-coin.outputs.result}} == tails"

  - name: flip-coin
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)
  - name: heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\""]

  - name: tails
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was tails\""]

```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

time="2022-08-01T12:12:03.772Z" level=info msg="Processing workflow" namespace=siebren workflow=test-workflow-parameters-1
time="2022-08-01T12:12:03.774Z" level=error msg="Recovered from panic" namespace=siebren r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 302 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:194 +0xd4\npanic({0x1ce07c0, 0x33713e0})\n\t/usr/local/go/src/runtime/panic.go:1047 +0x266\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).setGlobalParameters(0xc001362d80, {{0xc000371ec0, 0x1, 0x1}, {0x0, 0x0, 0x0}})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:571 +0xf22\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).setExecWorkflow(0xc001362d80, {0x22b0668, 0xc000058018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3527 +0x726\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc001362d80, {0x22b0668, 0xc000058018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:208 +0x209\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc00008dc00, {0x22b0668, 0xc000058018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:756 +0x8ee\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0x0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:678 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f6812210978)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x226dbe0, 0xc003340a50}, 0x1, 0xc00043b4a0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:294 +0x1a6c\n" workflow=test-workflow-parameters-1
time="2022-08-01T12:12:03.774Z" level=info msg="Updated phase  -> Error" namespace=siebren workflow=test-workflow-parameters-1
time="2022-08-01T12:12:03.774Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=siebren workflow=test-workflow-parameters-1
time="2022-08-01T12:12:03.774Z" level=info msg="Marking workflow completed" namespace=siebren workflow=test-workflow-parameters-1
time="2022-08-01T12:12:03.774Z" level=info msg="Checking daemoned children of " namespace=siebren workflow=test-workflow-parameters-1
time="2022-08-01T12:12:03.780Z" level=info msg="cleaning up pod" action=deletePod key=siebren/test-workflow-parameters-1-1340600742-agent/deletePod
time="2022-08-01T12:12:03.788Z" level=info msg="Workflow update successful" namespace=siebren phase=Error resourceVersion=164853863 workflow=test-workflow-parameters-1
time="2022-08-01T12:12:03.789Z" level=info msg="Queueing Error workflow siebren/test-workflow-parameters-1 for delete in 24h0m0s due to TTL"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
