### ISSUE TITLE
Bugs in UI Error Notice/Popup 

### ISSUE THREAD

**Issue by sid8489** [argoproj/argo-workflows#9274]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Issues:
1. **Error Notice/Popup does not render again after closing.**
  Steps to Reproduce:
-  Run argo server in sso mode.
- Associate a service account for user such that user does not have delete  permission
- Submit any workflow and open it
- Press Delete Button. You will get a **Forbidden** Error Notice.
![image](https://user-images.githubusercontent.com/85802930/182431731-1001a02a-5918-4e31-9502-bbdab3f80586.png)
- Close the error notice
- Press Delete Button Again. You won't see any error Notice this time.
![image](https://user-images.githubusercontent.com/85802930/182431820-539ad33a-14c8-4926-aff0-54a4830924b7.png)

Expected:
Error Notice should render each time user performs action which leads to error.

2. **Stale Error Notice/Popup is being rendered.**
  Steps to Reproduce:

- Run argo server in sso mode.
- Associate a service account for user such that user does not have delete and Patch permission
- Submit any workflow and open it
- Press Delete Button. You will get a **Forbidden** Error Notice.
![image](https://user-images.githubusercontent.com/85802930/182432462-2c76da5f-3f82-4e7a-abf7-bc57f63e0b37.png)
- Press Stop Button. You won't recieve the new error forbidden message(insufficient patch permission), instead the previous error notice is being rendered.
![image](https://user-images.githubusercontent.com/85802930/182432739-4e49ded3-4504-42c4-966d-153a0805275c.png)

Expected:
Error Notice should contain the latest error occurred.

What version are you running?
v3.3.8
## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

Any workflow will do, attaching the workflowTemplate for which above screenshots are pasted
```yaml
metadata:
  name: rbac-testing
  namespace: argo
spec:
  templates:
    - name: hello-hello-hello
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: hello1
            arguments:
              parameters:
                - name: message
                  value: hello1
            templateRef:
              name: workflow-template-whalesay-template
              template: whalesay-template
        - - name: approval
            template: approval
            arguments: {}
        - - name: hello2a
            arguments:
              parameters:
                - name: message
                  value: hello2a
            templateRef:
              name: workflow-template-inner-steps
              template: inner-steps
            when: '{{steps.approval.outputs.parameters.approve}} == YES'
          - name: hello2b
            arguments:
              parameters:
                - name: message
                  value: hello2b
            templateRef:
              name: workflow-template-whalesay-template
              template: whalesay-template
    - name: approval
      inputs:
        parameters:
          - name: approve
            default: 'NO'
            enum:
              - 'YES'
              - 'NO'
      outputs:
        parameters:
          - name: approve
            valueFrom:
              supplied: {}
      metadata: {}
      suspend: {}
  entrypoint: hello-hello-hello
  arguments: {}

```
Rbac config 
``` yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-siddharth
  namespace: argo
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workfloweventbindings
      - cronworkflows
      - cronworkflows/finalizers
      - workflowtemplates
    verbs:
      - get
      - list
      - watch
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-siddharth
  namespace: argo
subjects:
- kind: ServiceAccount
  name: argo-workflow-siddharth
roleRef:
  kind: Role
  name: argo-workflow-siddharth
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-siddharth
  namespace: argo
  annotations:
    workflows.argoproj.io/rbac-rule: "'<user email>' matches email"
    workflows.argoproj.io/rbac-rule-precedence: "0"

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
