### ISSUE TITLE
Artifact location in UI shown has incorrect repository location information if Template.ArchiveLocation is defined

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-workflows#9277]
When Template.ArchiveLocation defines the location of the artifact, the UI doesn't seem to be using that.

Note below that second-on-deletion.txt should be in _my-bucket-3_ but the UI thinks _my-bucket_.

![Screen Shot 2022-08-02 at 3 21 19 PM](https://user-images.githubusercontent.com/17830711/182483546-8dc79597-57e6-4e0f-927b-2aedd574d9f6.png)

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: two-artgc-
  #finalizers:
  #  - "blah"
spec:
  entrypoint: entrypoint
  artifactGC:
    strategy: OnWorkflowCompletion
  podGC:
    strategy: ""
  templates:
    - name: entrypoint
      steps:
      - - name: call-first
          template: first
      - - name: call-second
          template: second
    - name: first
      container:
        image: argoproj/argosay:v2
        command:
          - sh
          - -c
        args:
          - |
            echo "hello world" > /tmp/message
      outputs:
        artifacts:
          - name: first-on-completion-1
            path: /tmp/message
            s3:
              key: first-on-completion-1.txt
              bucket: my-bucket-2
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
            artifactGC:
              strategy: OnWorkflowCompletion
              serviceAccountName: default
              podMetadata:
                annotations:
                  annotation-key-1: annotation-value-1
                  annotation-key-2: annotation-value-2
          - name: first-on-completion-2
            path: /tmp/message
            s3:
              key: first-on-completion-2.txt
              bucket: my-bucket-3
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
          - name: first-no-deletion 
            path: /tmp/message
            s3:
              key: first-no-deletion.txt
              bucket: my-bucket-3
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
            artifactGC:
              strategy: Never

    - name: second
      archiveLocation:
        s3:
          key: default-to-be-overridden
          bucket: my-bucket-3
          endpoint: minio:9000
          insecure: true
          accessKeySecret:
            name: my-minio-cred
            key: accesskey
          secretKeySecret:
            name: my-minio-cred
            key: secretkey
      container:
        image: argoproj/argosay:v2
        command:
          - sh
          - -c
        args:
          - |
            echo "hello world" > /tmp/message
      outputs:
        artifacts:
          - name: second-on-deletion
            s3:
              key: second-on-deletion.txt
            path: /tmp/message
            artifactGC:
              strategy: OnWorkflowDeletion
          - name: second-on-completion
            path: /tmp/message
            s3:
              key: second-on-completion.txt
              bucket: my-bucket-2
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
            artifactGC:
              strategy: OnWorkflowCompletion
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
