### ISSUE TITLE
Allow `dependencies` to be templated

### ISSUE THREAD

**Issue by DjokerR** [argoproj/argo-workflows#9297]
## Checklist

 

* [ ] Double-checked my configuration.
* [ ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

how to use loops  dags   dependency, its not to unmashl 

What version are you running?
argo: v3.3.7
kubernetes: v1.21.6
## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  templates:
  - name: loop-example
    steps:
    - - name: print-message
        template: whalesay
        arguments:
          parameters:
          - name: tag
            value: "{{item.tag}}"
          - name: image
            value: "{{item.image}}"
          - name: dependen
            value: "{{item.dependencies}}"  
          # WithParam: "{{steps.cat.outputs.result}}"
        withItems:   [ { image: 'debian', tag: '11111' ,dependencies: 'debian'   },{ image: 'centos', tag: 'tag222',dependencies:  'debian' },{ image: 'alpine', tag: 'tag333',dependencies:  'centos' }    ]           # invoke whalesay once for each item in parallel
  - name: whalesay
    inputs:
      parameters:
      - name: tag
      - name: image
      - name: dependen
    dag:
      tasks:
        - name: "{{inputs.parameters.image}}"
          template: at-tempalte
          # dependencies: ["{{inputs.parameters.dependen}}"]    
          dependencies: 
          - "{{inputs.parameters.dependen}}"                  #two ways is invalid
          arguments:
            parameters:
              - name: tag
                value: "{{inputs.parameters.tag}}"
              - name: image
                value: "{{inputs.parameters.image}}"
              - name: dependen
                value: "{{inputs.parameters.dependen}}"
  - name: at-tempalte
    inputs:
      parameters:
      - name: tag
      - name: image
      - name: dependen
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.dependen}}"]
 


```

```bash
 Failed to submit workflow: templates.loop-example.steps[0].print-message templates.whalesay sorting failed: invalid dependency placeholder-9

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
