### ISSUE TITLE
Use workflowTemplateRef in steps to load workflow template incl. parameters

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-workflows#9313]
# Summary

We have a base repo and X apps building when changing this base repo. Currently there is a workflow started for each one of these apps. As they have the same code base the checkout step is doing exactly the same (and some preparation steps following are equal as well). My idea was to setup a single `Workflow` for building all the apps. After the checkout and preparation steps, a `WorkflowTemplate` starts for app A, app B, ... That's fine so far, but each app has it's own parameters. It would be nice to use the `WorkflowTemplate` parameters for each app. To do so the workflow would need to use `workflowTemplateRef` from within the steps, as the parameters of the `WorkflowTemplate` are ignored if just adding a `templateRef` from the `WorkflowTemplate`.

I know that I could add list parameters, but it is not very readable when there are 20 parameters in each list.

# Example

Sensor containing shared workflow steps:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test
  namespace: argo
spec:
  dependencies:
  - name: github
    eventSourceName: github
    eventName: test
    filters:
      data:
        - path: body.X-GitHub-Event
          type: string
          value:
            - push
        - path: body.ref
          type: string
          value:
            - "refs/heads/main"
  template:
    serviceAccountName: argo-events-sa
  triggers:
  - template:
      name: test
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: test-
              namespace: argo
            spec:
              entrypoint: main
              serviceAccountName: workflow
              arguments:
                parameters:
                - name: repo
                  value: git@blabla.git
                - name: image-lib
                  value: https://images.blabla.com/lib
              templates:
              - name: main
                dag:
                  tasks:
                  - name: checkout
                    templateRef:
                      name: checkout
                      template: main
                    arguments:
                      parameters:
                      - name: repo
                        value: "{{workflows.parameters.repo}}"
                    workflowTemplateRef:
                      name: app-checkout
                  - name: prepare
                    depends: "checkout"
                    templateRef:
                      name: prepare
                      template: main
                    arguments:
                      parameters:
                      - name: image-lib
                        value: "{{workflows.parameters.image-lib}}"
                    workflowTemplateRef:
                      name: app-checkout
                  - name: app-a
                    depends: "prepare"
                    workflowTemplateRef:
                      name: build-app
                  - name: app-b
                    depends: "prepare"
                    workflowTemplateRef:
                      name: build-app
                  - name: app-c
                    depends: "prepare"
                    workflowTemplateRef:
                      name: build-app
```

Workflow for building each app:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-app
  namespace: argo
spec:
  serviceAccountName: workflow
  arguments:
    parameters:
    - name: app-name
      value: app-a
  templates:
  - name: main
    inputs:
      parameters:
      - name: app-name
    steps:
    - - name: build
        templateRef:
          name: builder
          template: main
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.app-name}}"
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
