### ISSUE TITLE
UI returns 500 on WorkflowTemplates tap if one WorkflowTemplate is invalid

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-workflows#9316]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

I pushed a broken version of a WorkflowTempate to the cluster. Clicking on the WorkflowTemplates tap in the argo-workflows UI returns 500 and I can't see any WorkflowTemplates.

The error message is:
"Unsuccessful HTTP response: json: cannot unmarshal object into Go struct field DAGTask.items.spec.templates.dag.tasks.template of type string"

I understand the behavior, it would still be nice to get a list of valid WorkflowTemplates.

What version are you running?

v3.3.8

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: check-cond
spec:
  serviceAccountName: workflow
  templates:
    dag:
      tasks:
        - name: print
          template:
            name: go-print
            container:
              image: docker/whalesay:latest
              command: [cowsay]
              args: ["printed"]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
