### ISSUE TITLE
Workflow Failed: wait container is forcefully stopped

### ISSUE THREAD

**Issue by dacamposol** [argoproj/argo-workflows#9328]
## Checklist

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

We have updated Argo Workflow to the version 3.3.8 and lately, we noticed some of the Workflows are failing due to the Pods being terminated.

When I analyse the Pod, I noticed the following:

```yaml
- containerID: containerd://d10fcac735c905dc65717148e04437e32148bea560bb66e9ed35d718471f1bf8
   image: argoproj/workflow-controller:v3.3.8-linux-amd64
   imageID: argoproj/workflow-controller:v3.3.8-linux-amd64@sha256:1ecc5b305fb784271797c14436c30b4b6d23204d603d416fdb0382f62604325f
   lastState: {}
   name: wait
   ready: false
   restartCount: 0
   started: false
   state:
     terminated:
       containerID: containerd://d10fcac735c905dc65717148e04437e32148bea560bb66e9ed35d718471f1bf8
       exitCode: 2
       finishedAt: "2022-08-10T07:06:08Z"
       reason: Error
       startedAt: "2022-08-10T07:06:07Z"
```

Also, when I check the logs of the aforementioned `wait` container, I don't see anything else than the following two lines:

```yaml
fatal: bad g in signal handler
fatal: bad g in signal handler
```

It's not a consistent error, and I have checked that it happens around 1/12 times, but it's weird and I don't see the way of fixing it.

### What version are you running?

I'm running Argo Workflows 3.3.8, deployed by Helm in our cluster.

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

> Any Workflow can reproduce this bug on our cluster at a point. Even [the one in the examples](https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml).

```bash
# Logs from the workflow controller:
time="2022-08-10T08:51:07.741Z" level=info msg="Queueing Failed workflow metadata/metadata-process-6phwc for delete in 2m57s due to TTL"

# Logs from in your workflow's wait container, something like:
fatal: bad g in signal handler
fatal: bad g in signal handler
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@dacamposol can you provide the minimum reproducible workflow and controller logs for this workflow?

**Comment by sarabala1979** [comment]
@dacamposol thanks for your response. Are you using `emissary` executor or other?

**Comment by dacamposol** [comment]
> @dacamposol thanks for your response. Are you using `emissary` executor or other?

Thank you for checking the issue so fast.

I'm using `emissary`.

**Comment by alexec** [comment]
Can you see if this happens on `:latest`?

**Comment by juliev0** [comment]
Hi @dacamposol in your Pod status that you show above, are you sure that's the Workflow Pod? Or is it the Workflow Controller Pod? Your image is: argoproj/workflow-controller:v3.3.8-linux-amd64 but that image should only be for the Controller, not for a Workflow Pod.

**Comment by dacamposol** [comment]
> Hi @dacamposol in your Pod status that you show above, are you sure that's the Workflow Pod? Or is it the Workflow Controller Pod? Your image is: argoproj/workflow-controller:v3.3.8-linux-amd64 but that image should only be for the Controller, not for a Workflow Pod.

Do you mean in the initial message? Yes, I took it from the status of the Pod spammed from the corresponding Workflow.

> Can you see if this happens on `:latest`?

Do you mean with the version 3.4.0?

We have some breaking changes there, so I cannot safely test it right now. Let me the day and I'll take a look.

**Comment by alexec** [comment]
> Do you mean with the version 3.4.0?

no. I mean the :latest image tag

**Comment by juliev0** [comment]
I tend to wonder if things were configured strangely. You shouldn't be seeing a Workflow Pod using a workflow-controller Image. You should have 3 containers, "main" using the image in your spec, "wait" using quay.io/argoproj/argoexec image, and an initcontainer "init" also using quay.io/argoproj/argoexec.

**Comment by dacamposol** [comment]
> I tend to wonder if things were configured strangely. You shouldn't be seeing a Workflow Pod using a workflow-controller Image. You should have 3 containers, "main" using the image in your spec, "wait" using quay.io/argoproj/argoexec image, and an initcontainer "init" also using quay.io/argoproj/argoexec.

That was my bad writing the OP. Since we have the images passing through a proxy registry in order to scan them and use them within our intranet, I just replaced the name of it for the public one, and it seems that I replaced it wrongly. Effectively the workflow Pod is using the executor image in `wait` and `init`.

The real log line from the initial message (concealing the GCR Project) is the following.

```yaml
- containerID: containerd://d10fcac735c905dc65717148e04437e32148bea560bb66e9ed35d718471f1bf8
   image: eu.gcr.io/XXXXXXX/com.dacamposol/dockerhub/argo-workflow-executor:3.3.8
   imageID: eu.gcr.io/XXXXXXX/com.dacamposol/dockerhub/argo-workflow-executor@sha256:1ecc5b305fb784271797c14436c30b4b6d23204d603d416fdb0382f62604325f
   lastState: {}
   name: wait
   ready: false
   restartCount: 0
   started: false
   state:
     terminated:
       containerID: containerd://d10fcac735c905dc65717148e04437e32148bea560bb66e9ed35d718471f1bf8
       exitCode: 2
       finishedAt: "2022-08-10T07:06:08Z"
       reason: Error
       startedAt: "2022-08-10T07:06:07Z"
```
Sorry for the inconveniences 😅 

----

> no. I mean the :latest image tag

It doesn't do **anything** for any Workflow. It doesn't show any event on the Workflow resource and the logs of the `workflow-controller` Pod show the following error:

```yaml
time="2022-09-09T15:45:06.300Z" level=info msg=healthz age=5m0s err="workflow never reconciled: workflow-template-hello-world-2gqkh" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=
```

I just replaced the image of the related containers to use `:latest` and also removed the `containerRuntimeExecutor` key from the config, as it seems it wasn't recognised in that version (`3.3.9` I assume?)

**Comment by dacamposol** [comment]
@alexec just for including more info:

At the moment I downgraded again to the previous image I had `:v3.3.8-linux-amd64`, all the stagnant Workflows (20) started again, with 17 successes and 3 failed with the initially mentioned error.

With the `:latest-linux-amd64` tag, only the behaviour from the previous comment could be seen.

**Comment by juliev0** [comment]
I see you're using your own copy of our Docker image. I wonder if there is any potential that that somehow got corrupted. Are you able to try removing "--executor-image" from your workflow controller configuration and try using the standard image?

**Comment by juliev0** [comment]
Out of curiosity, which version of Argo Workflows were you using before, and were you using the emissary executor or a different one?

**Comment by dacamposol** [comment]
> I see you're using your own copy of our Docker image. I wonder if there is any potential that that somehow got corrupted. Are you able to try removing "--executor-image" from your workflow controller configuration and try using the standard image?

I don't know which is what `:latest` is pointing to, but for the tag `:v3.3.8` I compared the digests of the image and they're the same one. Any corruption should have been reflected there.

> Based on somebody else who got the same "bad g in signal handler" error https://github.com/loft-sh/devspace/issues/1334 (not Argo Workflows) I am wondering if it's something particular to your environment. You're running in Google Cloud, right? Using Linux AMD 64 machines? Anything else to clarify?

The error `bad g in signal handler` is actually an error from the `signal_unix` library of Golang, so probably there are different combinations of people with this issue.

Concretely the tests mentioned in this thread are in a cluster in GCP, in the `europe-west3` zone. The Kubernetes version of the cluster is `1.23.8` and the machines are Linux AMD 64 machines.

> Out of curiosity, which version of Argo Workflows were you using before, and were you using the emissary executor or a different one?

We were using an old version, `v2.11.7`.

**Comment by juliev0** [comment]
Thanks for the information.

Can you provide the main container log together with the wait container and Controller logs (full logs)?

**Comment by juliev0** [comment]
> @alexec just for including more info:
> 
> At the moment I downgraded again to the previous image I had (`:v3.3.8-linux-amd64`), all the stagnant Workflows (20) started. Result after all of them ran: 17 successes and 3 failed with the initially mentioned error.
> 
> With the `:latest-linux-amd64` tag, only the behaviour from the previous comment could be seen.

Sorry, can you clarify what you mean by "only the behaviour from the previous comment could be seen"? Which previous comment? (Trying to figure out if something has been resolved between 3.3.8 and latest.)

**Comment by dacamposol** [comment]
> Can you provide the main container log together with the wait container and Controller logs (full logs)? Also, would you mind providing your workflow-controller-config?

Sure. They fail in the `init` container, so there is not much in the logs:

```shell
fatal: bad g in signal handler
fatal: bad g in signal handler
Stream closed EOF for argo/hello-world-8gbgf-560498845 (init)
```

The `main` and `wait` containers are stuck in `PodInitializing`.

In the Controller, it only shows this after few minutes:

```shell
time="2022-09-14T06:55:19.001Z" level=info msg="Deleting garbage collected workflow 'argo/hello-world-8gbgf
time="2022-09-14T06:55:19.028Z" level=info msg="Successfully deleted 'argo/hello-world-8gbgf'"
```

Also, the config-map of the controller, as required:

```yaml
Name:         argo-workflow-controller-configmap
Namespace:    argo
Labels:       app.kubernetes.io/component=workflow-controller
              app.kubernetes.io/instance=dxp-argo-987lx-dxp-dev
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=argo-cm
              app.kubernetes.io/part-of=argo-workflows
              helm.sh/chart=argo-1662030514699
Annotations:  <none>

Data
====
config:
----
containerRuntimeExecutor: emissary
artifactRepository:
  gcs:
    bucket: dxp-argo-artifacts
    keyFormat: '{{workflow.namespace}}/{{workflow.name}}/'
    serviceAccountKeySecret:
      key: serviceAccountKey
      name: argo-artifacts-gcs
```

> Sorry, can you clarify what you mean by "only the behaviour from the previous comment could be seen"? Which previous comment? (Trying to figure out if something has been resolved between 3.3.8 and latest.)

I mean that it doesn't do anything, the workflows just don't run.

I refer to [this comment](https://github.com/argoproj/argo-workflows/issues/9328#issuecomment-1242155821):

> It doesn't do anything for any Workflow. It doesn't show any event on the Workflow resource and the logs of the workflow-controller Pod show the following error...
