### ISSUE TITLE
invalid character '{' after top-level value" when running pod as resource

### ISSUE THREAD

**Issue by sivaguru-pat** [argoproj/argo-workflows#9341]
hey i am trying to run a pod in the workflow using kubernetes resource
where i am facing this error 
![image](https://user-images.githubusercontent.com/46225496/184175837-f2a19f3c-d311-443f-b6aa-1ef2f5744ed5.png)
pod is getting deployed but workflow is getting failed
```
name: tensorboard-template
inputs:
  parameters:
    - name: action
    - name: job_id
    - name: data_storage
outputs: {}
metadata: {}
daemon: true
resource:
  action: '{{inputs.parameters.action}}'
  manifest: |
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: 'tb-{{inputs.parameters.job_id}}'
      name: 'tb-{{inputs.parameters.job_id}}'
    spec:
      ports:
      - port: 80
        targetPort: 6006
      selector:
        app: tb-{{inputs.parameters.job_id}}
      type: ClusterIP
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        app: 'tb-{{inputs.parameters.job_id}}'
      name: 'tb-{{inputs.parameters.job_id}}'
    spec:
      
      
      containers:
      - name: tensorboard
        command: ["/bin/sh", "-c"]
        args: ["tensorboard --logdir {{inputs.parameters.data_storage}}/tensorboard"]
        image: tensorflow/tensorflow:2.5.1
        ports:
        - containerPort: 6006
       
        resources: 
          requests:
            cpu: 500m
            memory: 500Mi
            
          limits:
            
            cpu: 500m
            memory: 500Mi
                 

```
