### ISSUE TITLE
Context Deadline Exceeded error message

### ISSUE THREAD

**Issue by AbdAlRahman-Odeh-99** [argoproj/argo-workflows#9361]
Environment:
- Ubuntu 20.04
- Minikube: 1.26.1
- Kubernetes Version: 1.24.3
- Docker: 20.10.17
Issue:
- I am trying to run my workflow, but the pod won't start and gives me ErrImagePull and ImagePullBackOff when trying to pull "reanahub/reana-demo-bsm-search" image. I have tried pulling it locally and it was pulled successfully, so the image actually exists.
- The error message is: ```Failed to pull image "reanahub/reana-demo-bsm-search": rpc error: code = Unknown desc = context deadline exceeded```
Pod Describtion:
```
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  25m                   default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
  Normal   Scheduled         25m                   default-scheduler  Successfully assigned argo/bsm-search-xfrs2-cleanup-recreate-dir-3975220683 to minikube
  Normal   Pulling           25m                   kubelet            Pulling image "quay.io/argoproj/argoexec:latest"
  Normal   Pulled            25m                   kubelet            Successfully pulled image "quay.io/argoproj/argoexec:latest" in 28.688209447s
  Normal   Created           25m                   kubelet            Created container init
  Normal   Started           25m                   kubelet            Started container init
  Normal   Pulling           24m                   kubelet            Pulling image "quay.io/argoproj/argoexec:latest"
  Normal   Pulled            24m                   kubelet            Successfully pulled image "quay.io/argoproj/argoexec:latest" in 2.350145134s
  Normal   Created           24m                   kubelet            Created container wait
  Normal   Started           24m                   kubelet            Started container wait
  Normal   Pulling           20m (x3 over 24m)     kubelet            Pulling image "reanahub/reana-demo-bsm-search"
  Warning  Failed            18m (x3 over 22m)     kubelet            Error: ErrImagePull
  Warning  Failed            17m (x4 over 22m)     kubelet            Error: ImagePullBackOff
  Normal   BackOff           5m21s (x31 over 22m)  kubelet            Back-off pulling image "reanahub/reana-demo-bsm-search"
  Warning  Failed            7s (x7 over 22m)      kubelet            Failed to pull image "reanahub/reana-demo-bsm-search": rpc error: code = Unknown desc = context deadline exceeded
```

**Comment by sarabala1979** [comment]
@AbdAlRahman-Odeh-99 looks like your cluster is not able to pull `reanahub/reana-demo-bsm-search` Can you just create test pod with this image to check whether it is able to pull it?  Do you have duration or activedeadlineSeconds on your workflow?

**Comment by AbdAlRahman-Odeh-99** [comment]
Thank you @sarabala1979 for looking into this.

I have created a test pod as following which runs into the same error, furthermore I haven't specified a duration for it:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bsm-search-
spec:
  volumeClaimTemplates:
  - metadata:
      name: vol-cephfs-bsm
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi

  arguments:
    parameters:
    - name: base-dir                                  
      value: "/data/bsm-search/"

  entrypoint: databkgmc
  templates:
  - name: databkgmc
    inputs:
      parameters:
      - name: base-dir
    dag:
      tasks:
      - name: prepare-dir
        template: cleanup-recreate-dir
        arguments:
          parameters:
          - name: base-dir
            value: "{{inputs.parameters.base-dir}}"

  - name: cleanup-recreate-dir
    inputs:
      parameters:
      - name: base-dir
    script:
      image: reanahub/reana-demo-bsm-search
      command: [bash]
      source: |
        set -x
        rm -rf {{inputs.parameters.base-dir}}
        mkdir -p {{inputs.parameters.base-dir}}
      volumeMounts:
        - mountPath: /data/
          name: vol-cephfs-bsm
```
