### ISSUE TITLE
Panic on nill pointer when running a workflow with restricted parallelism

### ISSUE THREAD

**Issue by ezk84** [argoproj/argo-workflows#9363]
## Checklist

 

* [✔] Double-checked my configuration.
* [✔] Tested using the latest version.
* [✔] Used the Emissary executor.

## Summary

Running a workflow with mutliple parallel steps, where the `parallelism` flag is set lower than the number of parallel steps.

What happened/what you expected to happen?
A nill pointer dereference panic is thrown by the workflow controller.
Expected the tasks run to completion, same as if there had been no `parallelism` set. 

What version are you running?
3.4.0-rc1

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-parallelism
  namespace: argo
spec:
  entrypoint: main
  parallelism: 2
  templates:
    - name: main
      dag:
        tasks:
          - name: do-it-once
            template: do-it
            arguments:
              parameters:
                - name: thing
                  value: 1
          - name: do-it-twice
            template: do-it
            arguments:
              parameters:
                - name: thing
                  value: 2
          - name: do-it-thrice
            template: do-it
            arguments:
              parameters:
                - name: thing
                  value: 3
    - name: do-it
      inputs:
        parameters:
          - name: thing
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["I have a {{inputs.parameters.thing}}"]
```

Panic message from the workflow-controller logs
```
runtime error: invalid memory address or nil pointer dereference
goroutine 239 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:190 +0xbc
panic({0x1e5d4e0, 0x34af330})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc000908fd0, {0x24bc540, 0xc0000b6000}, 0xc000497b90, {0xc0016f8980, 0xb})
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:527 +0x13f9
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc000908fd0, {0x24bc540, 0xc0000b6000}, {0xc0016a3a10, 0x10}, 0xc00166db40, {0xc0010213e0, 0x16}, 0xc0000ec900, {0x24aa948, ...}, ...)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0xf25
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000908fd0, {0x24bc540, 0xc0000b6000}, {0xc0016a3a10, 0x10}, {0x24aa948, 0xc0006df500}, 0xc0013a1f68?, {{0x0, 0x0, ...}, ...}, ...)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1891 +0x22ec
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc000908fd0, {0x24bc540, 0xc0000b6000})
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:344 +0x16ed
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc00052c000, {0x24bc540, 0xc0000b6000})
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:752 +0x759
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0009c3ea0?)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:674 +0x9e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x61746e6f63?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x656c69662d736367?, {0x249a840, 0xc000aa34d0}, 0x1, 0xc00002bc80)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x6573616261746164?, 0x3b9aca00, 0x0, 0x61?, 0x617461646174656d?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x656d616e78657475?, 0x6e6f7268636e7973?, 0x6e6f6974617a69?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:90 +0x25
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:308 +0x19c5
```

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.
