### ISSUE TITLE
input parameter value condition doesn't work as expected

### ISSUE THREAD

**Issue by Izvi-digibank** [argoproj/argo-workflows#9367]
Argo workflows v3.3.6

Hi all,

I wrote a template with input parameter named `image`. The value of `image` is depended on `buildcntr`, which arrives from a previous template (`templateRef`).

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: argo-events
  name: my-workflow
spec:
  entrypoint: step1
  templates:
    - name: snyk
      inputs:
        parameters:
          - name: buildcntr
          - name: image
            value: "{{= buildcntr == 'default-image:0.0.1' ? 'snyk/snyk:gradle-6.4-jdk14' : snyk/snyk:gradle-jdk11' }}"
      metadata:
```

For some reason the value of `image` always go to the else condition ("snyk/snyk:gradle-jdk11"), even when the condition is true (i.e `buildcntr == 'default-image:0.0.1' ? 'snyk/snyk:gradle-6.4-jdk14'`).

Am I missing something in my logic implementation?
