### ISSUE TITLE
How run docker in workflow?

### ISSUE THREAD

**Issue by AndriySidliarskiy** [argoproj/argo-workflows#9416]
Previously i run step with docker image for build docker image in container. And have error` ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` How fix this? 
MY CONFIGURATION 
```
    container:
      securityContext:
        privileged: true
      image: docker:latest
      command: [sh, -c]
```
