### ISSUE TITLE
Resource template with action delete now requires manifest or manifestFrom

### ISSUE THREAD

**Issue by tomjo** [argoproj/argo-workflows#9418]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

**What happened/what you expected to happen?**

Trying to run following example: https://github.com/argoproj/argo-workflows/blob/master/examples/resource-delete-with-flags.yaml

It fails with:  Internal Server Error: templates.main.steps[1].delete-resource either templates.delete-resource.resource.manifest or templates.delete-resource.resource.manifestFrom must be specified

I assume following commit broke this functionality: https://github.com/argoproj/argo-workflows/commit/6106ac7229eeaac9132f8df595b569de2bc68ccf in validate.go

**What version are you running?**

v3.4.0-rc1

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

Below is the content of: https://github.com/argoproj/argo-workflows/blob/master/examples/resource-delete-with-flags.yaml

```yaml
# This example shows a Workflow which creates and deletes a resource
# using flags. This might be useful in circumstances when there is a
# need to delete a resource using label selectors w/o providing a manifest.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: resource-delete-with-flags-
spec:
  entrypoint: main

  templates:
  - name: main
    steps:
    - - name: submit-resource
        template: create-configmap

    - - name: delete-resource
        arguments:
          parameters:
          - name: selector
            value: cleanup=true
        template: delete-resource

  - name: create-configmap
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: resource-delete-with-flags
          labels:
            cleanup: "true"
        data:
          key: value

  - name: delete-resource
    inputs:
      parameters:
      - name: selector
    resource:
      action: delete
      flags: [
        "configmap", "--selector", "{{inputs.parameters.selector}}"
      ]
```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

No output from workflow-controller logs and no pod created.

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.
