### ISSUE TITLE
MetricsError: unable to compute workflow.status in metrics block with 'when' clause

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argo-workflows#9424]
Related to #8939

## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

Expected:

Conditional metrics based on workflow status work with usage of a `when` clause

Actual:

Received following error

```
MetricsError: unable to compute 'when' clause for metric 'jm-metrics-error-test-njwnb': 
Invalid 'when' expression ' == Succeeded': Cannot transition token types from 
UNKNOWN [<nil>] to COMPARATOR [==], unable to compute 'when' clause for metric 
'jm-metrics-error-test-njwnb': Invalid 'when' expression ' == Failed': 
Cannot transition token types from UNKNOWN [<nil>] to COMPARATOR [==]
```

What version are you running?

v3.3.9

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: jm-metrics-error-test-
spec:
  serviceAccountName: my-workflow-executor
  entrypoint: hello-world
  metrics:
    prometheus:
      - help: "Success Counter"
        name: "success_count"
        labels:
          - key: name
            value: "my-workflow"
        when: "{{workflow.status}} == Succeeded"
        counter:
          value: "1"
      - help: "Fail Counter"
        name: "fail_count"
        labels:
          - key: name
            value: "my-workflow"
        when: "{{workflow.status}} == Failed"
        counter:
          value: "1"
  templates:
  - name: hello-world
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 
```

<details>
  <summary>Logs</summary>

  ```bash
  Found 2 pods, using pod/-argo-workflows-workflow-controller-796f98b5f-fnrcx
  time="2022-08-24T13:19:58.806Z" level=info msg="Processing workflow" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:19:58.829Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:19:58.829Z" level=info msg="Pod node jm-metrics-error-test-njwnb initialized Pending" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:19:58.886Z" level=info msg="Created pod: jm-metrics-error-test-njwnb (jm-metrics-error-test-njwnb)" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:19:58.886Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:19:58.886Z" level=info msg=reconcileAgentPod namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:19:58.897Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=212383170 workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.887Z" level=info msg="Processing workflow" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.888Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.888Z" level=info msg="node changed" new.message= new.phase=Succeeded new.progress=0/1 nodeID=jm-metrics-error-test-njwnb old.message= old.phase=Pending old.progress=0/1
  time="2022-08-24T13:20:08.888Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.888Z" level=info msg=reconcileAgentPod namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.888Z" level=info msg="Steps node jm-metrics-error-test-njwnb-2532039137 initialized Running" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.889Z" level=info msg="StepGroup node jm-metrics-error-test-njwnb-2531805317 initialized Running" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.889Z" level=info msg="Pod node jm-metrics-error-test-njwnb-158365993 initialized Pending" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.952Z" level=info msg="Created pod: jm-metrics-error-test-njwnb.onExit[0].publish-analytics-metrics (jm-metrics-error-test-njwnb-158365993)" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.952Z" level=info msg="Container node jm-metrics-error-test-njwnb-469639070 initialized Pending" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.952Z" level=info msg="Container node jm-metrics-error-test-njwnb-3917391688 initialized Pending" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.952Z" level=info msg="Workflow step group node jm-metrics-error-test-njwnb-2531805317 not yet completed" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:08.968Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=212383292 workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:13.969Z" level=info msg="cleaning up pod" action=deletePod key=argo/jm-metrics-error-test-njwnb/deletePod
  time="2022-08-24T13:20:18.954Z" level=info msg="Processing workflow" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="node jm-metrics-error-test-njwnb-469639070 phase Pending -> Succeeded" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="node jm-metrics-error-test-njwnb-469639070 finished: 2022-08-24 13:20:18.95522432 +0000 UTC" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="node jm-metrics-error-test-njwnb-3917391688 phase Pending -> Succeeded" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="node jm-metrics-error-test-njwnb-3917391688 finished: 2022-08-24 13:20:18.955244462 +0000 UTC" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="node changed" new.message= new.phase=Succeeded new.progress=0/1 nodeID=jm-metrics-error-test-njwnb-158365993 old.message= old.phase=Pending old.progress=0/1
  time="2022-08-24T13:20:18.955Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg=reconcileAgentPod namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="Step group node jm-metrics-error-test-njwnb-2531805317 successful" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="node jm-metrics-error-test-njwnb-2531805317 phase Running -> Succeeded" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="node jm-metrics-error-test-njwnb-2531805317 finished: 2022-08-24 13:20:18.955807957 +0000 UTC" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="Outbound nodes of jm-metrics-error-test-njwnb-158365993 is [jm-metrics-error-test-njwnb-3917391688]" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="Outbound nodes of jm-metrics-error-test-njwnb-2532039137 is [jm-metrics-error-test-njwnb-3917391688]" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="node jm-metrics-error-test-njwnb-2532039137 phase Running -> Succeeded" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="node jm-metrics-error-test-njwnb-2532039137 finished: 2022-08-24 13:20:18.955920214 +0000 UTC" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="Checking daemoned children of jm-metrics-error-test-njwnb-2532039137" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="Marking workflow completed" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.955Z" level=info msg="Marking workflow as pending archiving" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.956Z" level=error msg="unable to compute 'when' clause for metric 'jm-metrics-error-test-njwnb': Invalid 'when' expression ' == Succeeded': Cannot transition token types from UNKNOWN [<nil>] to COMPARATOR [==]" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.956Z" level=error msg="unable to compute 'when' clause for metric 'jm-metrics-error-test-njwnb': Invalid 'when' expression ' == Failed': Cannot transition token types from UNKNOWN [<nil>] to COMPARATOR [==
  ]" namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.956Z" level=info msg="Checking daemoned children of " namespace=argo workflow=jm-metrics-error-test-njwnb
  time="2022-08-24T13:20:18.961Z" level=info msg="cleaning up pod" action=deletePod key=argo/jm-metrics-error-test-njwnb-1340600742-agent/deletePod
  time="2022-08-24T13:20:18.972Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=212383427 workflow=jm-metrics-error-test-njwnb
  ```
</details>

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jmeridth** [comment]
Fully aware that `PRs are welcome` but wanted to put this here and ping @dpadhiar to gauge my situation.  Thanks. :smile:

**Comment by dpadhiar** [comment]
@jmeridth I ran your workflow and it completed. Where are you seeing the error and is this the same behavior?

**Comment by jmeridth** [comment]
@dpadhiar this error is occurring in 2 remote environments and also locally with a brand new, clean argo-workflows setup.

NOTE: This is not to say all of our setups are wrong in some way. I'm looking :smile:

On the UI I see the error here:

![Screen Shot 2022-08-27 at 10 57 39 PM](https://user-images.githubusercontent.com/35014/187056732-11e9569a-dc23-4ee0-bf08-f1952fef39ff.png)

and then

![Screen Shot 2022-08-27 at 10 57 47 PM](https://user-images.githubusercontent.com/35014/187056744-b83f2a92-e0b0-4e4b-9718-d494421177d2.png)

Same as the controller logs in the Issue description above

```bash
time="2022-08-24T13:20:18.956Z" level=error msg="unable to compute 'when' 
clause for metric 'jm-metrics-error-test-njwnb': Invalid 'when' expression ' 
== Succeeded': Cannot transition token types from UNKNOWN [<nil>] to 
COMPARATOR [==]" namespace=argo workflow=jm-metrics-error-test-njwnb
```

**Comment by jmeridth** [comment]
@dpadhiar I've confirmed with a brand new, fresh helm chart install of argo-workflows, that this is still occurring

I used the base workflow from the UI and added my metrics section

<details>
  <summary>Workflow</summary>
  
  ```yaml
  metadata:
    name: wonderful-rhino
    namespace: jm-test
    labels:
      example: 'true'
  spec:
    arguments:
      parameters:
        - name: message
          value: hello argo
    entrypoint: argosay
    metrics:
      prometheus:
        - help: "Test Build Workflow Duration"
          name: "exec_duration"
          labels:
            - key: name
              value: "{{workflow.name}}"
          gauge:
            value: "{{workflow.duration}}"
            realtime: false
        - help: "Success Counter"
          name: "success_count"
          labels:
            - key: name
              value: "test-build-workflow"
          when: "{{workflow.status}} == Succeeded"
          counter:
            value: "1"
        - help: "Fail Counter"
          name: "fail_count"
          labels:
            - key: name
              value: "test-build-workflow"
          when: "{{workflow.status}} == Failed"
          counter:
            value: "1"
    templates:
      - name: argosay
        inputs:
          parameters:
            - name: message
              value: '{{workflow.parameters.message}}'
        container:
          name: main
          image: 'argoproj/argosay:v2'
          command:
            - /argosay
          args:
            - echo
            - '{{inputs.parameters.message}}'
    ttlStrategy:
      secondsAfterCompletion: 300
    podGC:
      strategy: OnPodCompletion
  ```
</details>

How I installed the helm chart:

**NOTE:** using K8S 1.24 locally, so [have to generate the server token manually](https://github.com/argoproj/argo-workflows/issues/8320#issuecomment-1089352006)

Chart.yaml

```yaml
apiVersion: v2
appVersion: 1.1.0
description: A Helm chart to test argo-workflows MetricsError
name: helmtest
version: 3.8.5
keywords:
  - helm
  - test
maintainers:
  - name: JM
dependencies:
  - name: argo-workflows
    version: 0.17.1
    repository: https://argoproj.github.io/argo-helm
```

```bash
helm repo add argo https://
helm install --namespace jm-test argo .
```

Result

```bash
NAME: argo
LAST DEPLOYED: Tue Sep  6 08:52:27 2022
NAMESPACE: jm-test
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

Create token

```bash
kubectl apply -f - <<EOF                                                                                                                                                                                           
apiVersion: v1
kind: Secret
metadata:
  name: aw-token-secret
  namespace: jm-test
  annotations:
    kubernetes.io/service-account.name: argo-argo-workflows-server
type: kubernetes.io/service-account-token
EOF
```

Get token

```bash
ARGO_TOKEN="Bearer $(kubectl get secret aw-token-secret -n jm-test -o=jsonpath='{.data.token}' | base64 --decode)"                                                                                             
echo $ARGO_TOKEN
```

Paste that token into https://localhost:2746 after port forwarding on the pod.

Run the workflow

Successful run:

![Screen Shot 2022-09-06 at 8 55 03 AM](https://user-images.githubusercontent.com/35014/188654105-4f2662cb-7c31-40f6-997a-26b4692a0df4.png)

MetricsError still occurs:

![Screen Shot 2022-09-06 at 8 55 12 AM](https://user-images.githubusercontent.com/35014/188654308-b5521400-ddc6-4eb7-85fe-59478d75b995.png)
