### ISSUE TITLE
retryStrategy when not all fields are specified

### ISSUE THREAD

**Issue by cjyar** [argoproj/argo-workflows#9425]
## Checklist

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

When `retryStrategy` doesn't have all its fields set, Argo's behavior doesn't seem consistent with the settings.

What version are you running?

3.3.9

## Diagnostics

These minimal Workflows test the combinations that seem most interesting; I haven't tested all 16 combinations. The name of each Workflow contains the letters `l`, `d`, `f`, and `m` to indicate if it has fields `limit`, `backoff.duration`, `backoff.factor`, `backoff.maxDuration`, respectively. Here's a table summarizing the experiments and observations; did it actually retry, and did it apply backoff?

| `limit` | `duration` | `factor` | `maxDuration` | retries | backoff |
| --- | --- | --- | --- | --- | --- |
| 10 | | | | yes ✅ | no ✅ |
| 10 | 15s | 2 | | yes ✅ | yes ✅ |
| 10 | 15s | 2 | 5m | yes ✅ | yes ✅ |
| | 15s | | | yes ❌ | no ✅ |
| | 15s | 2 | | yes ❌ | no ❌ |
| | 15s | 2 | 5m | yes ❌ | no ❌ |
| 0 | | | | no, but created Retry node | no ✅ |
| 0 | 15s | 2 | 5m | no, but created Retry node | no ✅ |

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-retry-l-
  namespace: workflows
spec:
  entrypoint: main
  retryStrategy:
    limit: 10
  templates:
  - name: main
    container:
      image: alpine
      command: [ "false" ]

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-retry-ldf-
  namespace: workflows
spec:
  entrypoint: main
  retryStrategy:
    limit: 10
    backoff:
      duration: 15s
      factor: 2
  templates:
  - name: main
    container:
      image: alpine
      command: [ "false" ]

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-retry-ldfm-
  namespace: workflows
spec:
  entrypoint: main
  retryStrategy:
    limit: 10
    backoff:
      duration: 15s
      factor: 2
      maxDuration: 5m
  templates:
  - name: main
    container:
      image: alpine
      command: [ "false" ]

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-retry-d-
  namespace: workflows
spec:
  entrypoint: main
  retryStrategy:
    backoff:
      duration: 15s
  templates:
  - name: main
    container:
      image: alpine
      command: [ "false" ]

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-retry-df-
  namespace: workflows
spec:
  entrypoint: main
  retryStrategy:
    backoff:
      duration: 15s
      factor: 2
  templates:
  - name: main
    container:
      image: alpine
      command: [ "false" ]

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-retry-dfm-
  namespace: workflows
spec:
  entrypoint: main
  retryStrategy:
    backoff:
      duration: 15s
      factor: 2
      maxDuration: 5m
  templates:
  - name: main
    container:
      image: alpine
      command: [ "false" ]

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-retry-l0-
  namespace: workflows
spec:
  entrypoint: main
  retryStrategy:
    limit: 0
  templates:
  - name: main
    container:
      image: alpine
      command: [ "false" ]

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-retry-l0dfm-
  namespace: workflows
spec:
  entrypoint: main
  retryStrategy:
    limit: 0
    backoff:
      duration: 15s
      factor: 2
      maxDuration: 5m
  templates:
  - name: main
    container:
      image: alpine
      command: [ "false" ]
```

Logs are attached.
[logs.txt](https://github.com/argoproj/argo-workflows/files/9419593/logs.txt)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
