### ISSUE TITLE
GCS Directory output Artifact Visualization

### ISSUE THREAD

**Issue by omriarieli** [argoproj/argo-workflows#9429]
What happened/what you expected to happen?
Trying to display mochawesome tests report on the UI using a folder in a gcs bucket [Through Native GCS APIs](https://argoproj.github.io/argo-workflows/configure-artifact-repository/#through-native-gcs-apis) the [documentation](https://argoproj.github.io/argo-workflows/artifact-visualization/#directory) states "To view a directory, add a trailing-slash", the directory contains an index.html and some assets folder with css and js files

What version are you running?
3.3.8

bucket folder structure:
```
Reports
├── assets
│   └── app.css
│   └── app.js
│   └── screeshots
│       │ 
│       ├──screeshots_1.png
│   └── videos
│       │ 
│       ├──video_1.mp4
├── specs
│   └── mochawesome.json
│   └── mochawesome_001.json
└── index.html
└── cypress-tests-report.json
```

when clicking on the report link from the step's input/outputs i see a blank screen with:
```
mkdir /tmp/artifact2817203567/assets/: mkdir /tmp/artifact2817203567: not a directory
```

## Diagnostics

```yaml
      outputs:
        artifacts:
          - name: report
            path: /tmp
            archive:
              none: {}
            gcs:
              bucket: my-bucket
              key: "{{workflow.parameters.ticket}}/"

```

argo workflow server log shows:
```
time="2022-08-25T05:45:28.580Z" level=info msg="Download artifact" artifactName=report isInput=false namespace=argocd nodeId=env-l9wkn-755917634 workflowName=env-l9wkn
time="2022-08-25T05:45:28.588Z" level=info msg="GCS Load path: /tmp/artifact1928456982, key: POP-1103"
time="2022-08-25T05:45:28.722Z" level=warning msg="Failed to download objects from GCS: mkdir /tmp/artifact1928456982/assets/: mkdir /tmp/artifact1928456982: not a directory"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
