### ISSUE TITLE
3.4-rc2 - Links defined in configmaps have changed (so are broken)

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#9435]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

Insert the following into your workflow configmap:

```yaml
  links: |
    # Adds a button to the workflow page. E.g. linking to you logging facility.
    - name: Workflow logs (Loki)
      scope: workflow
      url: https://grafana.mycompany.biz/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bjob%3D%5C%22${metadata.namespace}%2F${metadata.name}%5C%22,container%3D%5C%22main%5C%22%7D%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D
```

On Workflows 3.3.9, when the link is clicked, this correctly renders as:
`https://grafana.mycompany.bizt/explore?orgId=1&amp;left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bjob%3D%5C%22namespacename%2Fmy-wf-name-1661418000%5C%22,container%3D%5C%22main%5C%22%7D%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D`

On workflows 3.4, this renders as:
`https://grafana.mycompany.biz/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bjob%3D%5C%22namespacename%2Fmy-wf-name-1661418000%5C%22,container%3D%5C%22main%5C%22%7D%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D`

This breaks our loki view of logs.

At first glance, the issue appears to be to do with how it's html encoding certain chars. For example, `orgId=1&` becomes `orgId=1&amp;` in 3.4.

What version are you running? 3.4-rc2

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.
