### ISSUE TITLE
Approval step example from the Intermediate Parameters documentation is giving me an error.

### ISSUE THREAD

**Issue by jpdoria** [argoproj/argo-workflows#9441]
## Summary

What happened/what you expected to happen?

I'm trying to implement the approval step in our workflow by following the simple guide [here](https://argoproj.github.io/argo-workflows/intermediate-inputs/). Unfortunately, it doesn't work as expected.

In the video, it asked for an input, but in my workflow, it didn't so the default `NO` value is not overridden.

Another issue is that after the workflow has finished running, it returned the error below which is also not present in the video. I wasn't able to get the logs from the pods. This is the only message that I got.

```
Invalid 'when' expression '{{steps.approval.outputs.parameters.approve}} == YES': Invalid token: '{{' (hint: try wrapping the affected expression in quotes ("))
```

![image](https://i.imgur.com/Ka9jSNd.jpg)
![image](https://i.imgur.com/V8QxeLD.jpg)

What version are you running?

v3.3.0

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: approval-example-
  namespace: argo
spec:
  entrypoint: cicd-pipeline
  templates:
    - name: cicd-pipeline
      steps:
        - - name: deploy-pre-prod
            template: deploy
        - - name: approval
            template: approval
        - - name: deploy-prod
            template: deploy
            when: "{{steps.approval.outputs.parameters.approve}} == YES"
    - name: approval
      suspend: {}
      inputs:
        parameters:
          - name: approve
            default: "NO"
            enum:
              - "YES"
              - "NO"
      outputs:
        parameters:
          - name: approve
            valueFrom:
              supplied: {}
    - name: deploy
      container:
        image: "argoproj/argosay:v2"
        command:
          - /argosay
        args:
          - echo
          - deploying
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
