### ISSUE TITLE
Introduce `withSequence` to iterate a range of numbers

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#945]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**:

For simple use cases, it'd be useful to iterate a range of numbers. Ansible has a `with_sequence` that we could adopt in Argo workflows. Something like:

```
        withSequence:
          start: 0
          end: 100
          format: "testuser%02x"
```

See:
https://docs.ansible.com/ansible/2.5/plugins/lookup/sequence.html
