### ISSUE TITLE
Argo Workflows UI Crashes when having a misconfigured Sensor

### ISSUE THREAD

**Issue by christophercutajar** [argoproj/argo-workflows#9451]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

A new sensor was deployed with a typo having `argument` instead of `arguments`. When trying to load Argo Workflows UI, the UI was completely stuck highlighting the HTTP error response as be illustrated below:

<img width="2550" alt="Screenshot 2022-08-24 at 18 08 44" src="https://user-images.githubusercontent.com/60098546/186936079-40360a50-8d26-4f58-b94d-92d3e635173d.png">

From the workflow controller logs I could see that there are some `healtz` error logs:

```
level=info msg=healthz age=5m0s err="json: unknown field \"argument\"" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=
```

The sensor was updated to remove the typo and was re-deployed. Argo Workflows UI was still broken. Using `kubectl get wf -n default`, it was noticed that these are failed workflows. After deleting such workflows, Argo Workfows UI came back to life.

What version are you running?

Argo Workflows v3.3.9.

The above scenario was tested also on Argo Workflows v3.3.7.  With this version, as expected Argo UI loaded and showed the respective workflow in error state.

<img width="890" alt="Screenshot 2022-08-24 at 18 07 55" src="https://user-images.githubusercontent.com/60098546/186935343-67237bfb-385e-4473-adde-8948314d5dc7.png">

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

Notice that it's reading `argument` and not `arguments`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: whalesay
                argument:
                  parameters:
                    - name: message
                      # the value will get overridden by event payload from test-dep
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                contextKey: type
              dest: spec.arguments.parameters.0.value
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
