### ISSUE TITLE
Argo Workflow server does not support slash symbol for label value from workflow

### ISSUE THREAD

**Issue by uhlajs** [argoproj/argo-workflows#9460]
## Checklist

-  [x] Double-checked my configuration.
-  [x] Tested using the latest version.
-  [x] Used the Emissary executor.

## Summary
What happened/what you expected to happen?
When running modified version of [label-value-from-workflow.yaml](https://github.com/argoproj/argo-workflows/blob/master/examples/label-value-from-workflow.yaml) everything works as expected.

```kubernetes
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: label-value-from-
  annotations:
    workflows.argoproj.io/version: ">= v3.3.0"
    workflows.argoproj.io/description: |
      This examples show you how to add labels based on an expression.
      You can then query workflows based on the parameters they were invoked with.
      In this specific case, the value of foo will set as a label on the workflow.
spec:
  arguments:
    parameters:
      - name: foo
        value: bar
  workflowMetadata:
    labelsFrom:
      foo:
        expression: workflow.parameters.foo
  entrypoint: main
  templates:
    - name: main
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "{{workflow.parameters.foo}}" ]
```

However, when the value for `foo` parameter contains slash symbol the Argo Workflows Sever UI does not show the workflow properly.

![image](https://user-images.githubusercontent.com/13243167/187162641-d65399d9-2ee9-4a30-8ab3-57e8a78b2600.png)

What version are you running?
v3.3.9

## Diagnostics

Changed value for `foo` parameter.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: label-value-from-
  annotations:
    workflows.argoproj.io/version: ">= v3.3.0"
    workflows.argoproj.io/description: |
      This examples show you how to add labels based on an expression.
      You can then query workflows based on the parameters they were invoked with.
      In this specific case, the value of foo will set as a label on the workflow.
spec:
  arguments:
    parameters:
      - name: foo
        value: "https://github.com"
  workflowMetadata:
    labelsFrom:
      foo:
        expression: workflow.parameters.foo
  entrypoint: main
  templates:
    - name: main
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "{{workflow.parameters.foo}}" ]
```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
