### ISSUE TITLE
[Feature request] Resource template support for multi-manifest file

### ISSUE THREAD

**Issue by or-shachar** [argoproj/argo-workflows#9463]
## Summary

What version are you running? latest / 3.3.9

## Diagnostics

- The wonderful Resource Template allows creating objects using inline file or manifest from artifact.
- Sometimes we need to apply multiple objects in the same file using the `---` separator.

I tried to manipulate [the example from the e2e](https://github.com/argoproj/argo-workflows/blob/6106ac7229eeaac9132f8df595b569de2bc68ccf/test/e2e/resource_template_test.go#L102) test to apply two objects:
<details>
<summary>
<b>Sample failing workflow</b>
</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: k8s-resource-tmpl-with-artifact
spec:
  serviceAccount: argo
  entrypoint: main
  templates:
    - name: main
      serviceAccountName: argo
      inputs:
        artifacts:
        - name: manifest
          path: /tmp/manifestfrom-path.yaml
          raw:
            data: |
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: k8s-pod-resource-
              spec:
                serviceAccountName: argo
                containers:
                - name: argosay-container
                  image: argoproj/argosay:v2
                  command: ["/argosay"]
                restartPolicy: Never
              ---
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: k8s-pod-resource2-
              spec:
                serviceAccountName: argo
                containers:
                - name: argosay-container
                  image: argoproj/argosay:v2
                  command: ["/argosay"]
                restartPolicy: Never
      resource:
        action: create
        successCondition: status.phase == Succeeded
        failureCondition: status.phase == Failed
        manifestFrom:
          artifact:
            name: manifest
```
</details>

- The resources are actually created but the execution fails because it fails to parse json.

<details>
<summary>
<b>Logs from the workflow controller</b>
</summary>

```bash
# Logs from the workflow controller:
time="2022-08-29T14:54:10.975Z" level=info msg="Processing workflow" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:10.983Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:10.983Z" level=info msg="Pod node k8s-resource-tmpl-with-artifact96kcf initialized Pending" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:11.029Z" level=info msg="Created pod: k8s-resource-tmpl-with-artifact96kcf (k8s-resource-tmpl-with-artifact96kcf)" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:11.029Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:11.029Z" level=info msg=reconcileAgentPod namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:11.041Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=5628467 workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.976Z" level=info msg="Processing workflow" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.976Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.976Z" level=info msg="node changed" namespace=argo new.message="Error (exit code 1): invalid character '{' after top-level value" new.phase=Failed new.progress=0/1 nodeID=k8s-resource-tmpl-with-artifact96kcf old.message= old.phase=Pending old.progress=0/1 workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.976Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.976Z" level=info msg=reconcileAgentPod namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.976Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.976Z" level=info msg="Updated message  -> Error (exit code 1): invalid character '{' after top-level value" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.976Z" level=info msg="Marking workflow completed" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.976Z" level=info msg="Marking workflow as pending archiving" namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.976Z" level=info msg="Checking daemoned children of " namespace=argo workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:20.981Z" level=info msg="cleaning up pod" action=deletePod key=argo/k8s-resource-tmpl-with-artifact96kcf-1340600742-agent/deletePod
time="2022-08-29T14:54:20.990Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=5628532 workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:21.024Z" level=info msg="archiving workflow" namespace=argo uid=ba45db45-9416-4461-95d7-a5075c334db2 workflow=k8s-resource-tmpl-with-artifact96kcf
time="2022-08-29T14:54:21.029Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/k8s-resource-tmpl-with-artifact96kcf/labelPodCompleted
```

</details>

IIUC - something is expecting to find valid json as response from running `kubectl create -f $f -out json`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
