### ISSUE TITLE
Suspend a step but resume the workflow?

### ISSUE THREAD

**Issue by johnzhangchangshan** [argoproj/argo-workflows#9479]
### Discussed in https://github.com/argoproj/argo-workflows/discussions/9477

<div type='discussions-op-text'>

<sup>Originally posted by **johnzhangchangshan** August 31, 2022</sup>
I was wondering is there a way to resume a specific step/template as  I do not want to resume the entire workflow?
To elaborate,  I have two suspend steps in my workflow.yaml which are running in parallel, however I can only resume the workflow instead of the step that was suspended explicitly.</div>

Here is my template
```
- name: myTemplate
    dag:
      tasks:
        - name: task1
          templateRef:
            name: myTemp
            template: myTemp-temp
          arguments:
            parameters:
            - name: data
              value: myData
              
        - name: task2-approve
          template: approve
          depends: task1

        - name: task3
          depends: task2-approve
          templateRef:
            name: myTemp
            template: myTemp-temp
          arguments:
            parameters:
            - name: data
              value: myData

        - name : task4
          templateRef:
            name: myTemp
            template: myTemp-temp
          arguments:
            parameters:
            - name: data
              value: myData
              
        - name: task5-approve
          template: approve
          depends: task4

        - name : task6
          depends: task5-approve && task4
          templateRef:
            name: myTemp
            template: myTemp-temp
          ### arguments:
            parameters:
            - name: data
              value: myData
              
  - name: approve
    suspend: {}
```
