### ISSUE TITLE
k8s 1.24 service account changes cause workflows to fail with executor plugin

### ISSUE THREAD

**Issue by jrhoward** [argoproj/argo-workflows#9501]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary
Changes in how service account tokens are accessed is causing workflows using the executor plugin to fail in k8s 1.24

What happened/what you expected to happen?

I submitted a workflow using the example here https://argoproj.github.io/argo-workflows/executor_plugins/

and workflow failed immediately, no container created with following message.

failed to get token volumes: service account argoworkflows/uber-argo does not have any secrets

Same code worked on k8s 1.22 and 1.23

What version are you running?
v3.3.9
k8s 1.24
## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-example-
spec:
  entrypoint: main
  serviceAccountName: uber-argo
  templates:
    - name: main
      plugin:
        hello: { }
```
status in workflow:

```yaml
status:
  artifactRepositoryRef:
    artifactRepository: {}
    default: true
  conditions:
    - status: 'True'
      type: Completed
  finishedAt: '2022-09-03T02:42:26Z'
  message: >-
    failed to get token volumes: service account argoworkflows/uber-argo does
    not have any secrets
```
service account created using the 1.24 k8s way

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: uber-argo
  namespace: argoworkflows
  annotations:
    kubernetes.io/service-account.name: "uber-argo"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: uber-argo
  namespace: argoworkflows

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-uber-argo
subjects:
  - kind: ServiceAccount
    name: uber-argo
    namespace: argoworkflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```
The secret exists however changes in k8s 1.24 where the ServiceAccount manifest doesn’t have a Secret section any longer may be causing this to fail if the code is using the Secret section to get the name of the servcie account secret

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

time="2022-09-03T02:42:26.556Z" level=info msg="Processing workflow" namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.562Z" level=info msg="Updated phase  -> Running" namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.562Z" level=info msg="Plugin node hello-example-zmtxz initialized Pending" namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.562Z" level=info msg="TaskSet Reconciliation" namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.562Z" level=info msg="Creating TaskSet" namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.569Z" level=info msg=reconcileAgentPod namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.576Z" level=error msg="error in agent pod reconciliation" error="failed to get token volumes: service account argoworkflows/uber--argo does not have any secrets" namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.576Z" level=info msg="Updated phase Running -> Error" namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.576Z" level=info msg="Updated message  -> failed to get token volumes: service account argoworkflows/uber--argo does not have any secrets" namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.576Z" level=info msg="Marking workflow completed" namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.576Z" level=info msg="Checking daemoned children of " namespace=argoworkflows workflow=hello-example-zmtxz
time="2022-09-03T02:42:26.581Z" level=info msg="cleaning up pod" action=deletePod key=argoworkflows/hello-example-zmtxz-1340600742-agent/deletePod
time="2022-09-03T02:42:26.587Z" level=info msg="Workflow update successful" namespace=argoworkflows phase=Error resourceVersion=1932 workflow=hello-example-zmtxz



# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
