### ISSUE TITLE
unknown field "artifactGC" 

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-workflows#9524]
## Checklist

* [x] Double-checked my configuration.
* [x] Tested using `:latest` images.
* [ ] Used the Emissary executor.

## Summary

Submitting a sample workflow with artifactGC field fails with the below error

**unknown field "artifactGC"**

Fresh install of v3.3.9. 

```
argo version
argo: v3.3.9+5db53aa.dirty
  BuildDate: 2022-08-10T02:08:30Z
  GitCommit: 5db53aa0ca54e51ca69053e1d3272e37064559d7
  GitTreeState: dirty
  GitTag: v3.3.9
  GoVersion: go1.19
  Compiler: gc
  Platform: darwin/amd64
```

## Diagnostics

Using your sample from https://github.com/argoproj/argo-workflows/blob/master/examples/artifact-gc-workflow.yaml

```yaml
# This example shows how you can configure Artifact Garbage Collection for your Workflow.
# Here there are two artifacts - one is automatically deleted when the Workflow completes, and the other
# is deleted when the Workflow gets deleted.
# In this case, "OnWorkflowDeletion" is defined for all artifacts by default, but the "on-completion" artifact
# overrides that default strategy.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-gc-
spec:
  entrypoint: main
  artifactGC:
    strategy: OnWorkflowDeletion # the overall strategy, which can be overridden
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2
        command:
          - sh
          - -c
        args:
          - |
            echo "hello world" > /tmp/on-completion.txt
            echo "hello world" > /tmp/on-deletion.txt
      outputs:
        artifacts:
          - name: on-completion
            path: /tmp/on-completion.txt
            s3:
              key: on-completion.txt
            artifactGC:
              strategy: OnWorkflowCompletion # overriding the default strategy for this artifact
          - name: on-deletion
            path: /tmp/on-deletion.txt
            s3:
              key: on-deletion.txt

```

# Logs from the workflow controller:
See attached 
[workflow-controller.logs.gz](https://github.com/argoproj/argo-workflows/files/9492347/workflow-controller.logs.gz)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
