### ISSUE TITLE
forbidden: User "system:anonymous" cannot list resource "workflows"

### ISSUE THREAD

**Issue by ElhamAhmadlou** [argoproj/argo-workflows#9526]
What version are you running?
v3.3.6 

After loging into argo workflows UI,  i see this  error in workflows tab :
```
Forbidden: [workflows.argoproj.io](http://workflows.argoproj.io/) is forbidden: User "system:anonymous" cannot list resource "workflows" in API group "[argoproj.io](http://argoproj.io/)" in the namespace=...
```
I am sure that the rolebinding for SSO SA has been defined properly , because i also tried to login with SA's token , and it works and it has proper access to workflows.

# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

```
age=5m0s err="<nil>" instanceID= labelSelector="![workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid](http://workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid)"
```
# Logs from the workflow server:
```
level=info msg="selected SSO RBAC service account for user" email="" loginServiceAccount=argo-admin-user serviceAccount=argo-admin-user ssoDelegated=false ssoDelegationAllowed=false subject=e2jyg5bf3-7ec6-0005-acf7-69332gg98626
level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=info.InfoService grpc.start_time="2022-09-06T13:29:57Z" grpc.time_ms=2.585 span.kind=server system=grpc
```

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Check your anonymous SA's permissions on workflows.

**Comment by ElhamAhmadlou** [comment]
But i got the correct serviceaccount after loging into argo with cloudidp , so why it checks the SA's permissions and not argo-admin-user (my SA)?

**Comment by ElhamAhmadlou** [comment]
hello @alexec 

About my SSO serviceaccount issue , i mentioned that in UI user info i see the correct SA (which in my case is argo-admin-user) so i got the correct SA , so i don't login anonymously. If i login with argo-admin-user bearer token , i have correct access without mentioned error. 

My SSO and SAs configuration is like [this](https://github.com/argoproj/argo-workflows/issues/3525#issuecomment-701750311) but i get this error in UI when i login with SSO:

```
forbidden: [workflows.argoproj.io](http://workflows.argoproj.io/) is forbidden: User "system:anonymous" cannot list resource "workflows" in API group "[argoproj.io](http://argoproj.io/)" in the namespace ""
```
This is part of the role which binded to my SA:

```
- verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - deletecollection
      - delete
    apiGroups:
      - [argoproj.io](http://argoproj.io/)
    resources:
      - workflows
      - workflows/finalizers
      - cronworkflows
      - cronworkflows/finalizers
      - workfloweventbindings
      - workfloweventbindings/finalizers
      - workflowtaskresults
      - workflowtaskresults/finalizers
      - workflowtasksets
      - workflowtasksets/finalizers
      - workflowtasksets/status
      - workflowtemplates
      - workflowtemplates/finalizers
      - eventsources
      - sensors
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - [argoproj.io](http://argoproj.io/)
    resources:
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers
```
I also defined read-only default SA like bellow (i think @terrytangyuan meant this by anonymous SA ) and related RB, but was not helpful:
```
  name: user-default-login
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
```
Do you have any idea to fix it?
