### ISSUE TITLE
forbidden: User "system:anonymous" 

### ISSUE THREAD

**Issue by ElhamAhmadlou** [argoproj/argo-workflows#9536]
hello @alexec 

About my SSO serviceaccount issue , i mentioned that in UI user info i see the correct SA (which in my case is argo-admin-user) so i got the correct SA , so i don't login anonymously. If i login with argo-admin-user bearer token , i have correct access without mentioned error. 

My SSO and SAs configuration is like [this](https://github.com/argoproj/argo-workflows/issues/3525#issuecomment-701750311) but i get this error in UI when i login with SSO:

```
forbidden: [workflows.argoproj.io](http://workflows.argoproj.io/) is forbidden: User "system:anonymous" cannot list resource "workflows" in API group "[argoproj.io](http://argoproj.io/)" in the namespace ""
```
This is part of the role which binded to my SA:

```
- verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - deletecollection
      - delete
    apiGroups:
      - [argoproj.io](http://argoproj.io/)
    resources:
      - workflows
      - workflows/finalizers
      - cronworkflows
      - cronworkflows/finalizers
      - workfloweventbindings
      - workfloweventbindings/finalizers
      - workflowtaskresults
      - workflowtaskresults/finalizers
      - workflowtasksets
      - workflowtasksets/finalizers
      - workflowtasksets/status
      - workflowtemplates
      - workflowtemplates/finalizers
      - eventsources
      - sensors
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - [argoproj.io](http://argoproj.io/)
    resources:
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers
```
I also defined read-only default SA like bellow (i think @terrytangyuan meant this by anonymous SA ) and related RB, but was not helpful:
```
  name: user-default-login
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
```
Do you have any idea to fix it?

_Originally posted by @ElhamAhmadlou in https://github.com/argoproj/argo-workflows/issues/9526#issuecomment-1239284387_
