### ISSUE TITLE
Changes are not applying in resource for azure blob storage in output artifacts section

### ISSUE THREAD

**Issue by richoku** [argoproj/argo-workflows#9547]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using `:latest` images.
* [x] Attached the smallest workflow that reproduces the issue.
* [ ] ~~Attached logs from the workflow controller.~~
* [ ] ~~Attached logs from the wait container.~~

Some points of above checklist are not necessary in this issue.

We want to use azure blob storage to store artifacts there from our argo-workflows.

**Issue:**
`kubectl apply -f my-resource-file.yaml --namespace=mynamespace` does not apply the changes to use azure blob storage. There is no error message. The output artifacts section does not contain the configured settings.

**Previous version of my-resource-file.yaml (outputs section):**
```yaml
      outputs:
        artifacts:
          - name: ids
            path: /tmp/image-ids.json
```

**New version of my-resource-file.yaml (outputs section):**
```yaml
      outputs:
        artifacts:
          - name: ids
            path: /tmp/image-ids.json
            azure:
              endpoint: https://myblobstorage.blob.core.windows.net/
              container: my-artifact-repository
              blob: /tmp/image-ids.json
              accountKeySecret:
                name: my-storage-account-name
                key: my-storage-account-key
```

**Used setup:**
- argo-workflows version: 3.3.9
- argo-workflows helm chart version: [0.17.1](https://github.com/argoproj/argo-helm/tree/master/charts/argo-workflows)
- Blob storage configured as described here: [Configuring Azure Blob Storage](https://argoproj.github.io/argo-workflows/configure-artifact-repository/#configuring-azure-blob-storage)
- double checked usage with this example: [output-artifact-azure.yaml](https://github.com/argoproj/argo-workflows/blob/master/examples/output-artifact-azure.yaml)

## Summary
It seems that only s3 object store and gcs object store are supported since azure is not available within artifactRepository in [values.yaml](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml) of the helm chart. Please enable/support this feature.

Thanks in advance
Richard

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
