### ISSUE TITLE
logs incomplete comparing `kubectl logs xxx`

### ISSUE THREAD

**Issue by jibuji** [argoproj/argo-workflows#9573]
## Summary

What happened/what you expected to happen?

Logs incomplete comparing `kubectl logs xxx`

What version are you running?

argo v3.2.9

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    test: "true"
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: hello
      value: world
  templates:
  - name: whalesay
    script:
      image: docker/whalesay:latest
      command: [bash]
      source: |
        echo "this will be shown"
        for((j=0;j<=10;j+=1))
        do
          b=""
          for((i=0;i<=100;i+=1))
          do
              printf "progress %3d: [%-100s] %3d%%\r" $j $b $i
              sleep 0.002
              b+='#'
          done
        done
        echo "this won't be shown in argo logs"
```
# Logs from the argo cli:
argo315 logs hello-world-ktfw4 -n argo
```
hello-world-ktfw4: time="2022-09-12T08:54:35.491Z" level=info msg="capturing logs" argo=true
hello-world-ktfw4: this will be shown
```
# Logs from in your kubectl logs:
kubectl logs hello-world-ktfw4 -n argo -c main
```
time="2022-09-12T08:54:35.491Z" level=info msg="capturing logs" argo=true
this will be shown
progress   1: [#####################2022-09-12T16:54:36.690118203+08:00 ############                                              progress   2: [#########################################################2022-09-12T16:54:37.181210511+08:00 #########             progress   3: [#############################################################################################2022-09-12T16:54:37.78progress   5: [#######2022-09-12T16:54:38.252760981+08:00 #########################                                               progress   6: [###########################################2022-09-12T16:54:38.732911680+08:00 ######################              progress   7: [###############################################################################2022-09-12T16:54:39.176877542+08:00 progress2022-09-12T16:54:39.627235787+08:00    9: [###############################                                                progress  10: [#############################2022-09-12T16:54:39.640302442+08:00 ###################################               this won't be shown in argo logs################################################################################################] 100%
```
<img width="942" alt="image" src="https://user-images.githubusercontent.com/5327597/189614762-1dcdf902-6887-41a5-a1c9-f9e5fa341d1e.png">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
