### ISSUE TITLE
WorkflowTemplate with http do not calculate expression properly

### ISSUE THREAD

**Issue by booknu** [argoproj/argo-workflows#9582]
Hi. 
I'm using v3.3.9 installed with [Argo helm chart](https://github.com/argoproj/argo-helm).

I wanted to use a dynamic URL in http, so I used the expression but operation did not work properly.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: http-with-global-variable-test
  namespace: main
  labels:
    project: 'test'
    type: 'test'

spec:
  arguments:
    parameters:
      - name: commonConfig
        value: >
          {
            "dev": {
              "host": "http://jsonplaceholder.typicode.com/posts/1"
            }
          }

  templates:
    - name: call-http
      inputs:
        parameters:
          - name: phase
            default: dev
            enum:
              - dev
              - test
      http:
#        url: "{{=jsonpath(workflow.parameters.commonConfig, '$.' + 'dev'+ '.host')}}" # http://jsonplaceholder.typicode.com/posts/1  requested properly
        url: "{{=jsonpath(workflow.parameters.commonConfig, '$.' + inputs.parameters.phase + '.host')}}" # {{=jsonpath(...)}}  (not caclulated)
#        url: "{{workflow.parameters.commonConfig}}" # {"dev": {...}}
#        url: "{{inputs.parameters.phase}}" # dev
        method: 'GET'

    - name: simple-echo
      inputs:
        parameters:
          - name: phase
            default: dev
            enum:
              - dev
              - test
      container:
        image: docker/whalesay
        command:
          - cowsay
        args: # "http://jsonplaceholder.typicode.com/posts/1" printed
          - "{{=jsonpath(workflow.parameters.commonConfig, '$.' + inputs.parameters.phase + '.host')}}"
```

When submit `call-http` with `url: {{=jsonpath(workflow.parameters.commonConfig, '$.' + 'dev'+ '.host')}` it works properly.
<img width="474" alt="스크린샷 2022-09-13 오후 9 14 18" src="https://user-images.githubusercontent.com/22257860/189898187-7373bdb7-b269-478f-a796-a9dd1e19b689.png">

Using `{{=jsonpath(workflow.parameters.commonConfig, '$.' + inputs.parameters.phase + '.host')}}` in container template(`simple-echo`) works fine either.
<img width="737" alt="스크린샷 2022-09-13 오후 9 13 17" src="https://user-images.githubusercontent.com/22257860/189897964-817ef9fd-a03d-4dd0-9e4f-0537e9d07b75.png">

But using `url: {{=jsonpath(workflow.parameters.commonConfig, '$.' + inputs.parameters.phase + '.host')}}`, expression did not calculated and the url was processed as {{=jsonpath(...)}}.
<img width="500" alt="스크린샷 2022-09-13 오후 9 13 40" src="https://user-images.githubusercontent.com/22257860/189898031-8b170ab7-e7d4-4be0-ba74-8b681248ae85.png">

Is this a bug or misuse?
