### ISSUE TITLE
Workflow Not Reconciled Causes Restart & CrashLoopBackOff

### ISSUE THREAD

**Issue by hbrewster-splunk** [argoproj/argo-workflows#9592]
## Checklist

 

* [X] Double-checked my configuration.
* [ ] Tested using `:latest` images.
* [X] Attached the smallest workflow that reproduces the issue.
* [X] Attached logs from the workflow controller.
* [ ] Attached logs from the wait container.

## Summary

What happened/what you expected to happen?

We are running a cluster level installation of Argo Workflows where teams are provided an isolated namespace to run their Workflows. 

I am writing to address the following error: `workflow never reconciled: <name>`. This causes the Argo Controller to restart, and over time to enter a CrashLoopBackOff. 

A workflow may not be reconciled for a number of reasons, the two I have become familiar with are: 
1. The controller does not have adequate permissions to service the workflow 
2. The workflow submitted has some invalid manifest.

In the case of (2) this has meant that an onboarded team submitting an invalid Workflow in their own isolated namespace has the capability to bring the entire controller down for everyone. 

What am I expecting to happen? 
1. The controller should not crash. It should acknowledge that a Workflow cannot be processed but not panic.
2. The Workflow object should be rejected with 400 error

What version are you running? v3.3.9

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

Using a hello argo template with some extra workflowMetadata

```yaml
metadata:
  name: workflow-not-reconciled
  namespace: admin
  labels:
    example: 'true'
spec:
  workflowMetadata:
    labelsFrom:
      execution_label:
        expression: workflow.parameters.execution_label # important
  entrypoint: argosay
  arguments:
    parameters:
      - name: message
        value: hello argo
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

Now if a user **submits this with a workflow parameter `execution_label` without quote marks**, for example, the manifest is invalid and hence crashes the controller 

```
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 
```
time="2022-09-15T01:13:12.759Z" level=info msg="Processing workflow" namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:12.807Z" level=info msg="Updated phase  -> Running" namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:12.866Z" level=info msg="Pod node workflow-not-reconciled-zdw8p initialized Pending" namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:12.866Z" level=info msg="TaskSet Reconciliation" namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:12.866Z" level=info msg=reconcileAgentPod namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:12.874Z" level=warning msg="Error updating workflow: Workflow.argoproj.io \"workflow-not-reconciled-zdw8p\" is invalid: metadata.labels: Invalid value: \"afgskldghsdklgjklsdg sfgsdfgs\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?') Invalid" namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:22.202Z" level=info msg="Processing workflow" namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:22.366Z" level=info msg="Updated phase  -> Running" namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:22.375Z" level=info msg="Pod node workflow-not-reconciled-zdw8p initialized Pending" namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:22.375Z" level=info msg="TaskSet Reconciliation" namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:22.375Z" level=info msg=reconcileAgentPod namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p
time="2022-09-15T01:13:22.383Z" level=warning msg="Error updating workflow: Workflow.argoproj.io \"workflow-not-reconciled-zdw8p\" is invalid: metadata.labels: Invalid value: \"afgskldghsdklgjklsdg sfgsdfgs\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?') Invalid" namespace=wfe-admin workflow=workflow-not-reconciled-zdw8p

< CONTINUES OVER 5 min period > 

![Screen Shot 2022-09-15 at 10 57 22 am](https://user-images.githubusercontent.com/86707578/190291146-0b28a888-e357-4e26-963f-87ffa239b741.png)

```
# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=workflow-not-reconciled-zdw8p,workflow.argoproj.io/phase!=Succeeded
```
N/A
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
