### ISSUE TITLE
WorkflowTemplate ‘s suspend field can not make affect to  those workflows which use it

### ISSUE THREAD

**Issue by wujunwei** [argoproj/argo-workflows#9593]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using `:latest` images.
* [x] Attached the smallest workflow that reproduces the issue.

## Summary

What happened/what you expected to happen?
I expected the  `Workflow.spec.suspend`  same with the `Workflowtemplate` in  `Workflow.spec.workflowTemplateRef.name`

Is it a feature and why?
What version are you running?
v3.3.9
## Diagnostics

template
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: coinflip-w6pq9
  namespace: default
spec:
  entrypoint: coin-flip
  suspend: true
  templates:
    - inputs: {}
      metadata: {}
      name: coin-flip
      outputs: {}
      steps:
        - - arguments: {}
            name: flip-coin
            template: flip-coin
    - inputs: {}
      metadata: {}
      name: flip-coin
      outputs: {}
      script:
        command:
          - python
        image: python:alpine3.6
        name: ''
        resources: {}
        source: |

          import random
          result = "heads" if random.randint(0,1) == 0 else "tails"
          print(result)
```

workflow
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: coin-mdzkb
  namespace: default
spec:
  arguments: {}
  workflowTemplateRef:
    name: coinflip-w6pq9
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
