### ISSUE TITLE
workflow not archived if a step's pod is deleted and workflow-controller restarts before archive time

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#9607]
my cronworkflow has:
```
metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
```

my controller has:
```
  workflowDefaults:
    spec:
      activeDeadlineSeconds: 21600
      #ttlStrategy needs to be few minutes otherwise prometheus workflow metrics show 0
      podGC:
        strategy: OnWorkflowCompletion
        #OnPodCompletion messes up wf that pass artifacts as input/output between pods
      templateDefaults:
        retryStrategy:
          limit: 1
          #see https://argoproj.github.io/argo-workflows/retries/
          retryPolicy: "OnError"
          backoff:
            duration: "10"
            factor: 1
            maxDuration: "60"
```

steps: 

1. my cronworkflow is running 
2. i roll my whole k8s stack onto new worker nodes (so EVERY container (from every pod) stops running on nodeX and then few minutes later starts running on nodeY)
3. even after 1 hour i observe that cronworkflow from step1 is still in Error state (step shows 'pod deleted') on the main 'workflows' ui page, it has not moved to the 'archived workflows' ui page

what i assume happens is that workflow-controller only archives pods (it knows about in memory) but if the workflow-controller is down at the time that the cronworkflow fails then when new workflow-controller instance starts it lacks a step to go back to archive workflows that ended while workflow-controller was down

v3.3.9
