### ISSUE TITLE
temaplateDefaults: container/script: image does nothing

### ISSUE THREAD

**Issue by Maciej-Zwolinski** [argoproj/argo-workflows#9633]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I wanted to set default image to use in `script` or `container` sections in templates using `templateDefault` feature on workflow(template). Instead of setting the default value I received an error message:

`
Internal Server Error: templates.default-workflow-template-poc.tasks.step-one templates.step-one.script.image may not be empty`

There is no mention in docs of this field being prohibited.

### Version

v3.3.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: default-workflow-template-poc
spec:
  entrypoint: mian-poc
  templateDefaults:
    script:
      image: my-private-repo/my_image:latest

  templates:
  - name: main-poc
    dag:
      tasks:
      - name: step-one
        template: step-one


  - name: step-one
    script:
      #image: my-private-repo/my_image:latest # <- commented out
      command: ["bash"]
      source: |
        set -euo pipefail
        echo "$PWD"
```

### Logs from the workflow controller

n/a

### Logs from in your workflow's wait container

n/a
