### ISSUE TITLE
Pod spec fields disallowed on v3.4.0

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#9649]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

@alexec and @sarabala1979 mentioned this at ArgoCon

Referencing [9417](https://github.com/argoproj/argo-workflows/issues/9417#issuecomment-1233874593) and [Practical Argo Workflows Hardening](https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce)

These fields do not work anymore in v3.4.0 and had to comment out these

- automountServiceAccountToken
- serviceAccountName (in executor/main. may not actually be an issue)
- privileged
- allowPrivilegeEscalation
- readOnlyRootFilesystem
- capabilities

Controller and server will crash loop with logs such as

```
error unmarshaling JSON: while decoding JSON: json: unknown field "serviceAccountName"
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  mainContainer: |
    # serviceAccountName: argo-read
    securityContext:
      runAsNonRoot: true
      runAsUser: 8737
      runAsGroup: 8737
      # privileged: false
      # allowPrivilegeEscalation: false
      # readOnlyRootFilesystem: true
      # capabilities:
      #   drop:
      #     - ALL
    volumeMounts:
      - name: tmp
        mountPath: /tmp
    terminationMessagePolicy: FallbackToLogsOnError
    # automountServiceAccountToken: false
  executor: |
    # serviceAccountName: argo-read
    securityContext:
      runAsNonRoot: true
      runAsUser: 8737
      runAsGroup: 8737
      # privileged: false
      # allowPrivilegeEscalation: false
      # capabilities:
      #   drop:
      #     - ALL
    volumeMounts:
      - name: tmp
        mountPath: /tmp
    terminationMessagePolicy: FallbackToLogsOnError
    # automountServiceAccountToken: false
  workflowDefaults: |
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 8737
        runAsGroup: 8737
        # privileged: false
        # allowPrivilegeEscalation: false
        # readOnlyRootFilesystem: true
        # capabilities:
        #   drop:
        #     - ALL
      serviceAccountName: argo-read
      # automountServiceAccountToken: false
      # executor:
      #   serviceAccountName: argo-read
      ttlStrategy:
        secondsAfterSuccess: 10800
        secondsAfterFailure: 259200
      templateDefaults:
        volumes:
          - name: tmp
            emptyDir: {}
```

### Version

v3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A, controller and server crash looping with above config uncommented
```

### Logs from the workflow controller

```
error unmarshaling JSON: while decoding JSON: json: unknown field "serviceAccountName"
```

### Logs from in your workflow's wait container

```
error unmarshaling JSON: while decoding JSON: json: unknown field "serviceAccountName"
```

**Comment by crenshaw-dev** [comment]
I'm curious if this is a reason to cut a CRD version (something we've generally avoided in the Argo projects). I assume the upstream CRD (Pod) was versioned for this change.

**Comment by alexec** [comment]
I've discussed this, I think the blog post is actually incorrect.

**Comment by rwong2888** [comment]
So what is the recommended way to secure the workflows in a generic way now @alexec ?

**Comment by alexec** [comment]
Let me figure out the correct settings and share them.

**Comment by alexec** [comment]
@rwong2888 can I ask you to test this? You need to perform three steps:

1. Configure the controller with secure defaults.
2. Run a workflow.
3. Verify pods were created with secure settings, e.g. using `kubectl get pods -l workflows.argoproj.io/workflow -o yaml | kube-linter lint -`.

**Comment by rwong2888** [comment]
@alexec , the controller does not even start once I enable those commented out settings

**Comment by alexec** [comment]
Let me run some tests. I think there maybe a bug where the init container does not get set.

**Comment by alexec** [comment]
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  workflowDefaults: |
    spec:
      executor:
        serviceAccountName: workflow
      securityContext:
        runAsNonRoot: true
        runAsUser: 8737
        runAsGroup: 8737
      serviceAccountName: workflow
      automountServiceAccountToken: false
  mainContainer: |
    resources:
      requests:
        cpu: 1m
        memory: 64M
      limits:
        cpu: 0.5
        memory: 128Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 8737
      runAsGroup: 8737
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  executor: |
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.1
        memory: 64Mi
      limits:
        cpu: 0.5
        memory: 128Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 8737
      runAsGroup: 8737
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
```
