### ISSUE TITLE
Priority not working when defined declaratively 

### ISSUE THREAD

**Issue by ppapasani1** [argoproj/argo-workflows#9671]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Priority is getting set when declared in the workflow yaml file. When I set it through CLI, then it is working fine.

Submitted workflow by defining priority in yaml file
```sh
> argo submit ~/test_priority.yaml 
Name:                test-priority-n7g4p
Namespace:           default
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Pending
Created:             Sat Sep 24 02:02:43 +0000 (now)
Progress:            
Parameters:          
  message:           hello argo

>argo list
NAME                                   STATUS    AGE   DURATION   PRIORITY   MESSAGE
test-priority-n7g4p                    Running   5s    5s         0          
```

Submitted workflow by defining priority through CLI
```sh   
>argo submit ~/test_priority.yaml --priority 1000
Name:                test-priority-hcm7c
Namespace:           default
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Pending
Created:             Sat Sep 24 02:02:57 +0000 (now)
Progress:            
Parameters:          
  message:           hello argo

> argo list
NAME                                   STATUS      AGE   DURATION   PRIORITY   MESSAGE
test-priority-hcm7c                    Running     2s    2s         1000       
test-priority-n7g4p                    Succeeded   16s   10s        0
```

### Version

v3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-priority-
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  priority: 1000
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

time="2022-09-24T02:02:43.697Z" level=info msg="Processing workflow" namespace=default workflow=test-priority-n7g4p
time="2022-09-24T02:02:43.698Z" level=info msg="Updated phase  -> Running" namespace=default workflow=test-priority-n7g4p
time="2022-09-24T02:02:43.699Z" level=info msg="Pod node test-priority-n7g4p initialized Pending" namespace=default workflow=test-priority-n7g4p
time="2022-09-24T02:02:43.705Z" level=info msg="Created pod: test-priority-n7g4p (test-priority-n7g4p)" namespace=default workflow=test-priority-n7g4p
time="2022-09-24T02:02:43.711Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=232904023 workflow=test-priority-n7g4p
time="2022-09-24T02:02:53.706Z" level=info msg="Processing workflow" namespace=default workflow=test-priority-n7g4p
time="2022-09-24T02:02:53.706Z" level=info msg="Updating node test-priority-n7g4p exit code 0" namespace=default workflow=test-priority-n7g4p
time="2022-09-24T02:02:53.706Z" level=info msg="Updating node test-priority-n7g4p status Pending -> Succeeded" namespace=default workflow=test-priority-n7g4p
time="2022-09-24T02:02:53.706Z" level=info msg="Updated phase Running -> Succeeded" namespace=default workflow=test-priority-n7g4p
time="2022-09-24T02:02:53.706Z" level=info msg="Marking workflow completed" namespace=default workflow=test-priority-n7g4p
time="2022-09-24T02:02:53.706Z" level=info msg="Checking daemoned children of " namespace=default workflow=test-priority-n7g4p
time="2022-09-24T02:02:53.711Z" level=info msg="Workflow update successful" namespace=default phase=Succeeded resourceVersion=232904075 workflow=test-priority-n7g4p
time="2022-09-24T02:02:53.712Z" level=info msg="Queueing Succeeded workflow default/test-priority-n7g4p for delete in 5m0s"
time="2022-09-24T02:02:53.712Z" level=info msg="Queueing Succeeded workflow default/test-priority-n7g4p for delete in 5m0s"
time="2022-09-24T02:02:53.717Z" level=info msg="cleaning up pod" action=deletePod key=default/test-priority-n7g4p/deletePod

### Logs from in your workflow's wait container

Succeeded
