### ISSUE TITLE
using Artifactory as an artifactRepository not working for v3.4.0.

### ISSUE THREAD

**Issue by MADJIYoucef** [argoproj/argo-workflows#9681]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

using Artifactory as an artifactRepository not working for v3.4.0 whereas it works for v3.3.9.

### Version

v3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: pipeline-1234564
  namespace: pf-compute-staging
spec:
  entrypoint: main
  serviceAccountName: pipeline-staging
  templates:
    - name: main
      dag:
        tasks:
          - name: step-export-model
            template: export-model
    - name: export-model
      container:
        image: your_image
        command:
          - bash
          - -c
        args:
          - echo "Hello world" > /tmp/file.txt
      outputs:
        artifacts:
          - name: test-artifactory
            path: /tmp/file.txt
            artifactory:
              url: artifactory_url/path
              usernameSecret:
                name: argo-workflows-artifactory-staging
                key: rt_user
              passwordSecret:
                name: argo-workflows-artifactory-staging
                key: rt_password
```

### Logs from the workflow controller

g="Processing workflow" namespace=pf-compute-staging workflow=pipeline-1234564-f6lzh                                                  │
│ g="Task-result reconciliation" namespace=pf-compute-staging numObjs=0 workflow=pipeline-1234564-f6lzh                                 │
│ g="node changed" namespace=pf-compute-staging new.message="Error (exit code 1): runtime error: invalid memory address or nil pointer  │
│ g="Outbound nodes of pipeline-1234564-f6lzh set to [pipeline-1234564-f6lzh-3323353729]" namespace=pf-compute-staging workflow=pipelin │
│ g="node pipeline-1234564-f6lzh phase Running -> Error" namespace=pf-compute-staging workflow=pipeline-1234564-f6lzh                   │
│ g="node pipeline-1234564-f6lzh finished: 2022-09-25 09:18:17.755900341 +0000 UTC" namespace=pf-compute-staging workflow=pipeline-1234 │
│ g="Checking daemoned children of pipeline-1234564-f6lzh" namespace=pf-compute-staging workflow=pipeline-1234564-f6lzh                 │
│ g="TaskSet Reconciliation" namespace=pf-compute-staging workflow=pipeline-1234564-f6lzh                                               │
│ g=reconcileAgentPod namespace=pf-compute-staging workflow=pipeline-1234564-f6lzh                                                      │
│ g="Updated phase Running -> Error" namespace=pf-compute-staging workflow=pipeline-1234564-f6lzh                                       │
│ g="Marking workflow completed" namespace=pf-compute-staging workflow=pipeline-1234564-f6lzh                                           │
│ g="Checking daemoned children of " namespace=pf-compute-staging workflow=pipeline-1234564-f6lzh                                       │
│ g="Workflow to be dehydrated" Workflow Size=2477                                                                                      │
│ g="cleaning up pod" action=deletePod key=pf-compute-staging/pipeline-1234564-f6lzh-1340600742-agent/deletePod                         │
│ g="Create events 201"                                                                                                                 │
│ g="Delete pods 404"                                                                                                                   │
│ g="Queueing Error workflow pf-compute-staging/pipeline-1234564-f6lzh for delete in 23h30m0s due to TTL"                               │
│ g="Update workflows 409"                                                                                                              │
│  msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"pipeline-1234564-f6lzh\": the object has been │
│ g="Re-applying updates on latest version and retrying update" namespace=pf-compute-staging workflow=pipeline-1234564-f6lzh            │
│ g="Get workflows 200"                                                                                                                 │
│ g="Failed to re-apply update" error="must never update completed workflows" namespace=pf-compute-staging workflow=pipeline-1234564-f6 │
│ g="Get leases 200"                                       

### Logs from in your workflow's wait container

W
time="2022-09-25T09:18:13.152Z" level=info msg="Staging artifact: test-artifactory"
time="2022-09-25T09:18:13.152Z" level=info msg="Copying /tmp/file.txt from container base image layer to /tmp/argo/outputs/artifacts
/test-artifactory.tgz"
time="2022-09-25T09:18:13.152Z" level=info msg="/var/run/argo/outputs/artifacts/tmp/file.txt.tgz -> /tmp/argo/outputs/artifacts/test
-artifactory.tgz"
time="2022-09-25T09:18:13.153Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-09-25T09:18:13.153Z" level=info msg="Deadline monitor stopped"
time="2022-09-25T09:18:13.153Z" level=info msg="Alloc=6894 TotalAlloc=12197 Sys=25042 NumGC=4 Goroutines=7"
time="2022-09-25T09:18:13.154Z" level=fatal msg="executor panic: runtime error: invalid memory address or nil pointer dereference\ng
oroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflow
s/v3/workflow/executor.(*WorkflowExecutor).HandleError(0xc0004ab880, {0x213c5c0?, 0x3d67d38?})\n\t/go/src/github.com/argoproj/argo-w
orkflows/workflow/executor/executor.go:150 +0xaf\npanic({0x225d920, 0x3dbdd30})\n\t/usr/local/go/src/runtime/panic.go:838 +0x207\nne
t/http.(*Client).deadline(0x7f5b470d2910?)\n\t/usr/local/go/src/net/http/client.go:189 +0x14\nnet/http.(*Client).do(0x0, 0xc000cbc00
0)\n\t/usr/local/go/src/net/http/client.go:611 +0x225\nnet/http.(*Client).Do(...)\n\t/usr/local/go/src/net/http/client.go:593\ngithu
b.com/argoproj/argo-workflows/v3/workflow/artifacts/http.(*ArtifactDriver).Save(0xc0009b0c30, {0xc000058870, 0x30}, 0xc000cb8000)\n\
t/go/src/github.com/argoproj/argo-workflows/workflow/artifacts/http/http.go:114 +0x2e5\ngithub.com/argoproj/argo-workflows/v3/workfl
ow/artifacts/logging.driver.Save({{0x2b37d18?, 0xc0009b0c30?}}, {0xc000058870, 0x30}, 0xc000cb8000)\n\t/go/src/github.com/argoproj/a
rgo-workflows/workflow/artifacts/logging/driver.go:49 +0xc6\ngithub.com/argoproj/argo-workflows/v3/workflow/executor.(*WorkflowExecu
tor).saveArtifactFromFile(0xc0004ab880, {0x2b34b70, 0xc000056050}, 0xc000b83b40, {0xc000000fd8, 0x14}, {0xc000058870, 0x30})\n\t/go/
src/github.com/argoproj/argo-workflows/workflow/executor/executor.go:350 +0x1c7\ngithub.com/argoproj/argo-workflows/v3/workflow/exec
utor.(*WorkflowExecutor).saveArtifact(0x260ae3e?, {0x2b34b70, 0xc000056050}, {0x25d9731, 0x4}, 0xc000b83b40)\n\t/go/src/github.com/a
rgoproj/argo-workflows/workflow/executor/executor.go:321 +0x296\ngithub.com/argoproj/argo-workflows/v3/workflow/executor.(*WorkflowE
xecutor).SaveArtifacts(0xc0004ab880, {0x2b34b70, 0xc000056050})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/executor/exec
utor.go:298 +0x199\ngithub.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.waitContainer({0x2b34b70, 0xc000056050})\n\t/go/src/
github.com/argoproj/argo-workflows/cmd/argoexec/commands/wait.go:59 +0x4b4\ngithub.com/argoproj/argo-workflows/v3/cmd/argoexec/comma
nds.NewWaitCommand.func1(0xc000132280?, {0x25d9625?, 0x4?, 0x4?})\n\t/go/src/github.com/argoproj/argo-workflows/cmd/argoexec/command
s/wait.go:20 +0x27\ngithub.com/spf13/cobra.(*Command).execute(0xc000132280, {0xc0009be980, 0x4, 0x4})\n\t/go/pkg/mod/github.com/spf1
3/cobra@v1.5.0/command.go:876 +0x67b\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc000126c80)\n\t/go/pkg/mod/github.com/spf13/cobra
@v1.5.0/command.go:990 +0x3b4\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.g
o:918\nmain.main()\n\t/go/src/github.com/argoproj/argo-workflows/cmd/argoexec/main.go:16 +0x25\n"
