### ISSUE TITLE
Global outputs not working

### ISSUE THREAD

**Issue by dkovalenko** [argoproj/argo-workflows#9695]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Tested global outputs from this example: https://github.com/argoproj/argo-workflows/blob/master/examples/global-outputs.yaml
Just removed global artifact and added /tmp dir mount. Tried on different versions but can't get global params working. Am I doing something wrong?

Expected result: 
`global-outputs-8gkf6-consume-global-param-3532040163: hello world`
Actual result: 
`global-outputs-8gkf6-consume-global-param-3532040163: {{workflow.outputs.parameters.my-global-param}}`

### Version

3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-outputs-
spec:
  entrypoint: generate-globals
  onExit: consume-globals

  templates:
  - name: generate-globals
    steps:
    - - name: generate
        template: global-output
    - - name: consume-globals
        template: consume-globals

  # Template which produces a global parameter and artifact
  - name: global-output
    container:
      image: alpine:3.7
      volumeMounts:
        - name: tmp
          mountPath: /tmp
      command: [sh, -c]
      args: ["sleep 1; echo -n hello world > /tmp/hello_world.txt"]
    outputs:
      parameters:
      # export a global parameter. The parameter will be programatically available in the completed
      # workflow object under: workflow.outputs.parameters
      - name: hello-param
        valueFrom:
          path: /tmp/hello_world.txt
        globalName: my-global-param

  # Once exported, global outputs are referenceable in later parts of the workflow.
  # In this example, the consume-globals template is invoked after the generate-globals step, as
  # well as in the onExit handler, and can reference the globals, my-global-param and my-global-art.
  - name: consume-globals
    steps:
    - - name: consume-global-param
        template: consume-global-param
      
  - name: consume-global-param
    inputs:
      parameters:
        - name: param
          value: "{{workflow.outputs.parameters.my-global-param}}"
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["echo {{inputs.parameters.param}}"]
  volumes:
    - name: tmp
      emptyDir:
        sizeLimit: 100Mi
```

### Logs from the workflow controller

global-outputs-8gkf6-global-output-2681383721: time="2022-09-27T15:17:35.773Z" level=info msg="sub-process exited" argo=true error="<nil>"
global-outputs-8gkf6-global-output-2681383721: time="2022-09-27T15:17:35.773Z" level=info msg="no need to save parameter - on overlapping volu
me: /tmp/hello_world.txt" argo=true
global-outputs-8gkf6-consume-global-param-3532040163: {{workflow.outputs.parameters.my-global-param}}
global-outputs-8gkf6-consume-global-param-3532040163: time="2022-09-27T15:17:44.873Z" level=info msg="sub-process exited" argo=true error="<ni
l>"

### Logs from in your workflow's wait container

global-outputs-s8twj-global-output-3142330931: time="2022-09-27T14:54:22.567Z" level=error msg="executor error: pods \"global-outputs-s8twj-gl
obal-output-3142330931\" is forbidden: User \"system:serviceaccount:rc-web:default\" cannot patch resource \"pods\" in API group \"\" in the n
amespace \"rc-web\""
global-outputs-s8twj-global-output-3142330931: time="2022-09-27T14:54:22.567Z" level=info msg="Deadline monitor stopped"
global-outputs-s8twj-global-output-3142330931: time="2022-09-27T14:54:22.567Z" level=info msg="stopping progress monitor (context done)" error
="context canceled"
global-outputs-s8twj-global-output-3142330931: time="2022-09-27T14:54:22.567Z" level=info msg="Alloc=6160 TotalAlloc=12280 Sys=23506 NumGC=4 G
oroutines=6"
global-outputs-s8twj-global-output-3142330931: time="2022-09-27T14:54:22.567Z" level=fatal msg="pods \"global-outputs-s8twj-global-output-3142
330931\" is forbidden: User \"system:serviceaccount:rc-web:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"rc-we
b\""
global-outputs-s8twj-consume-global-param-2387429297: time="2022-09-27T14:54:29.333Z" level=info msg="Starting Workflow Executor" version=v3.4
.0
global-outputs-s8twj-consume-global-param-2387429297: time="2022-09-27T14:54:29.336Z" level=info msg="Using executor retry strategy" Duration=
1s Factor=1.6 Jitter=0.5 Steps=5
global-outputs-s8twj-consume-global-param-2387429297: time="2022-09-27T14:54:29.336Z" level=info msg="Executor initialized" deadline="0001-01-
01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=rc-web podName=global-outputs-s8twj-consume-global-param-2387429297 template="{\"na
me\":\"consume-global-param\",\"inputs\":{\"parameters\":[{\"name\":\"param\",\"value\":\"{{workflow.outputs.parameters.my-global-param}}\"}]}
,\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:3.7\",\"command\":[\"sh\",\"-c\"],\"args\":[\"echo {{workflow.
outputs.parameters.my-global-param}}\"],\"resources\":{}}}" version="&Version{Version:v3.4.0,BuildDate:2022-09-19T03:47:58Z,GitCommit:047952af
d539d06cae2fd6ba0b608b19c1194bba,GitTag:v3.4.0,GitTreeState:clean,GoVersion:go1.18.6,Compiler:gc,Platform:linux/amd64,}"
global-outputs-s8twj-consume-global-param-2387429297: time="2022-09-27T14:54:29.336Z" level=info msg="Starting deadline monitor"
global-outputs-s8twj-consume-global-param-2387429297: time="2022-09-27T14:54:31.337Z" level=info msg="Main container completed" error="<nil>"
global-outputs-s8twj-consume-global-param-2387429297: time="2022-09-27T14:54:31.337Z" level=info msg="No Script output reference in workflow.
Capturing script output ignored"
global-outputs-s8twj-consume-global-param-2387429297: time="2022-09-27T14:54:31.337Z" level=info msg="No output parameters"
global-outputs-s8twj-consume-global-param-2387429297: time="2022-09-27T14:54:31.337Z" level=info msg="No output artifacts"
global-outputs-s8twj-consume-global-param-2387429297: time="2022-09-27T14:54:31.337Z" level=info msg="Alloc=6728 TotalAlloc=12122 Sys=19410 Nu
mGC=4 Goroutines=7"
