### ISSUE TITLE
Set wf.spec.affinity.nodeAffinity, but agent pod has no nodeAffinity

### ISSUE THREAD

**Issue by chenyangxueHDU** [argoproj/argo-workflows#9704]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Set wf.spec.affinity.nodeAffinity, but agent pod has no nodeAffinity. I expect to agent pod has the same affinity

### Version

v3.3.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hobot-dag-731187
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: argo-dag
            operator: In
            values:
            - "true"
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: hobot-dag-731187-1340600742-agent
  namespace: argo
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: hobot-dag-731187
    uid: a936dc85-2e54-44fb-ba47-820b75081ade
spec:

```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

### Logs from in your workflow's wait container

kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
