### ISSUE TITLE
WorkflowTemplate doesn't resolve global parameters

### ISSUE THREAD

**Issue by Rj7** [argoproj/argo-workflows#9711]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I am trying to pass a workflow parameter from `Workflow` to `WorkflowTemplate` as per the [docs](https://argoproj.github.io/argo-workflows/workflow-templates/#working-with-parameters). But it fails with error `Failed to create workflow template: templates.hello-world templates.hello-world: failed to resolve {{workflow.parameters.global-parameter}}`. 

### Version

v3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
YAML from the argo [docs](https://argoproj.github.io/argo-workflows/workflow-templates/#working-with-parameters):

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-global-arg
spec:
  serviceAccountName: argo
  templates:
    - name: hello-world
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{workflow.parameters.global-parameter}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-wf-global-arg-
spec:
  serviceAccountName: argo
  entrypoint: whalesay
  arguments:
    parameters:
      - name: global-parameter
        value: hello
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template-global-arg
              template: hello-world
```

`argo template create wf_params.yaml` fails with `2022/09/29 11:50:53 Failed to create workflow template: templates.hello-world templates.hello-world: failed to resolve {{workflow.parameters.global-parameter}}`

`argo submit wf_params.yaml` fails with `Failed to submit workflow: templates.whalesay.steps[0].hello-world template reference hello-world-template-global-arg.hello-world not found`
```


### Logs from the workflow controller

NA. Workflow did not get created

### Logs from in your workflow's wait container

NA. Workflow did not get created

**Comment by Rj7** [comment]
Same issue was reporter in https://github.com/argoproj/argo-workflows/issues/7608

**Comment by juliev0** [comment]
Do you think this is a regression from 3.3.9? Have you tried that version?

**Comment by juliev0** [comment]
Interestingly, this seems particular to using the Argo CLI (and maybe the UI but I haven't tried). If I do "kubectl create -f yourtemplate.yaml" it works.

**Comment by juliev0** [comment]
As a workaround, if you have kubectl access and you're able to "kubectl create" your workflow template, I've verified that your workflow will succeed.

**Comment by juliev0** [comment]
@sarabala1979 What if we remove the validation from creating the WorkflowTemplate? After all, I don't think there's any validation when you do "kubectl create", right? And in this case, there's no way for the Argo Server to be able to validate these parameters.

**Comment by juliev0** [comment]
I spoke to @sarabala1979. Currently, the workaround recommendation is to specify spec.arguments.parameters in your WorkflowTemplate, which should be overridden by your Workflow.

**Comment by Rj7** [comment]
@juliev0 Thanks for the suggestions. I haven't tried with kubectl. But I tried adding parameter in WorkflowTemplate, I receive the same error for the below YAML. `Failed to submit workflow: templates.whalesay.steps[0].hello-world template reference hello-world-template-global-arg.hello-world not found`

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template-global-arg-1
spec:
  arguments:
    parameters:
      - name: global-parameter
        value: hello
  templates:
    - name: hello-world
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{workflow.parameters.global-parameter}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-wf-global-arg-1-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: global-parameter
        value: wello
  templates:
    - name: whalesay
      steps:
        - - name: hello-world
            templateRef:
              name: hello-world-template-global-arg
              template: hello-world
```

But if I replace `Workflow` definition by the below, it works find.
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-wf-global-arg-1-
spec:
  arguments:
    parameters:
      - name: global-parameter
        value: "this works"
  entrypoint: hello-world
  workflowTemplateRef:
    name: hello-world-template-global-arg-1

```
