### ISSUE TITLE
default not respected in `configMapKeyRef` when used to set global parameters

### ISSUE THREAD

**Issue by phlax** [argoproj/argo-workflows#9745]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Allowing a default value for a `ConfigMapKeyRef` was added in #8271 (ref #8262)

It does not appear that this works for global workflow parameters https://github.com/argoproj/argo-workflows/blob/2f5e7534c44499a9efce51d12ff87f8c3f725a21/workflow/controller/operator.go#L578-L584

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow                                                                                                                                                                
metadata:                                                                                                                                                                     
  generateName: global-cm-param-default-                                                                                                                           
spec:                                                                                                                                                                         
  entrypoint: main                                                                                                                                                            
  arguments:                                                                                                                                                                  
    parameters:                                                                                                                                                                                                                                                                                                              
    - name: param-that-wants-a-default                                                                                                                                                        
      valueFrom:                                                                                                                                                              
        default: ""                                                                                                                                                           
        configMapKeyRef:                                                                                                                                                      
          name: "some-config-map"                                                                                                                           
          key: maybe-existing-key                                                                                                                                                     

      workflowTemplateRef:                                                                                                                                                        
        name: some-wf-template
```


### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

N/A

### Logs from in your workflow's wait container

kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

N/A
