### ISSUE TITLE
[bug] The command exit code always be '0' in windows container 

### ISSUE THREAD

**Issue by wsj0000** [argoproj/argo-workflows#9797]
The command exit code always be '0' in windows container. Because the wait function on windows only check the err but not with the exit code of the stat (The error might be redirect).
[https://github.com/argoproj/argo-workflows/blob/aa59b43748f78e599709add871af7ec14e1fd3c1/workflow/executor/os-specific/signal_windows.go#L29](url)

I tried to fix this by the code below:
``` go
func Wait(process *os.Process) error {
	stat, err := process.Wait()
	if stat.ExitCode() != 0 {
		var errStr string
		if err != nil {
			errStr = err.Error()
		} else {
			errStr = "<nil>"
		}

		return errors.New(fmt.Sprintf("Exited failed. Error:%s", errStr))
	}
	return nil
}

```
This is just a temporary fix, so I just show my code here. Hope helpful.

The yaml below will reproduce the issue.

``` yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: default
  name: mytemplate

spec:
  templates:
    - name: test
      template: test-main
          

    - name: test-main
      nodeSelector:
        kubernetes.io/os: windows
      container:
        - name: main
          image: mcr.microsoft.com/windows/nanoserver:ltsc2022 # I used the nanoserver-ltsc2022 but the issue should also exist on ltsc2019
          command: ["cmd", "/s", "/c"]
          args: ["call exit /b 1"]
```
