### ISSUE TITLE
YAML validator is allowing nulls to be supplied as defaults

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#98]
There was a yaml as follows:

```
inputs:
  parameters:
    NAME:
      default:
```

where nothing was supplied as a default. This ultimately made it's way into the embedded template as a null value for the default. Having null as a default value is not supported and needs to be prevented by the validator.
