### ISSUE TITLE
argo proxy failed to upload log to s3 with latest helm chart

### ISSUE THREAD

**Issue by xubofei1983** [argoproj/argo-workflows#9811]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

argo proxy failed to upload log to s3 

time="2022-10-13T08:42:56.387Z" level=info msg="Saving file to s3" bucket=argo-workflows.alpha.kariusdx.com endpoint=s3.amazonaws.com key=analysis-nc-26437-xafzn-1-demux/analysis-nc-26437-xafzn-1-demux-demux-batch-320366774/main.log path=/tmp/argo/outputs/logs/main.log
time="2022-10-13T08:42:57.388Z" level=warning msg="Non-transient error: Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded"
time="2022-10-13T08:42:57.388Z" level=info msg="Save artifact" artifactName=main-logs duration=1.00093245s error="failed to put file: Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded" key=analysis-nc-26437-xafzn-1-demux/analysis-nc-26437-xafzn-1-demux-demux-batch-320366774/main.log
time="2022-10-13T08:42:57.388Z" level=error msg="executor error: failed to put file: Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded"
time="2022-10-13T08:42:57.388Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-13T08:42:57.388Z" level=info msg="Deadline monitor stopped"
time="2022-10-13T08:42:57.388Z" level=info msg="Alloc=6313 TotalAlloc=12713 Sys=30930 NumGC=9 Goroutines=8"
time="2022-10-13T08:42:57.388Z" level=fatal msg="failed to put file: Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded"

It was working with helm chart '0.17.1'  but fail on '0.20.1', with exact same configuration.

### Version

v3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
We run on AWS. 
We set instance profile to worker node with full s3 access permission.
We use iamrole for argo-server, and it has s3 access permission.
Therefore, we do not use user/password for s3 configure.

It works with helm chart '0.17.1'  (3.3.9), but failed with helm chart '0.20.1' (3.4.1)


Helm configuration: 

     artifactRepository:
        archiveLogs: true
        s3:
          bucket: argo-workflows.{{ $env }}.kariusdx.com
          endpoint: s3.amazonaws.com       #AWS => s3.amazonaws.com; GCS => storage.googleapis.com
          insecure: true
```

### Logs from the workflow controller

not related

### Logs from in your workflow's wait container

time="2022-10-13T08:42:56.387Z" level=info msg="Main container completed" error="<nil>"
time="2022-10-13T08:42:56.387Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2022-10-13T08:42:56.387Z" level=info msg="No output parameters"
time="2022-10-13T08:42:56.387Z" level=info msg="No output artifacts"
time="2022-10-13T08:42:56.387Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: analysis-nc-26437-xafzn-1-demux/analysis-nc-26437-xafzn-1-demux-demux-batch-320366774/main.log"
time="2022-10-13T08:42:56.387Z" level=info msg="Creating minio client using IAM role"
time="2022-10-13T08:42:56.387Z" level=info msg="Saving file to s3" bucket=argo-workflows.alpha.kariusdx.com endpoint=s3.amazonaws.com key=analysis-nc-26437-xafzn-1-demux/analysis-nc-26437-xafzn-1-demux-demux-batch-320366774/main.log path=/tmp/argo/outputs/logs/main.log
time="2022-10-13T08:42:57.388Z" level=warning msg="Non-transient error: Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded"
time="2022-10-13T08:42:57.388Z" level=info msg="Save artifact" artifactName=main-logs duration=1.00093245s error="failed to put file: Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded" key=analysis-nc-26437-xafzn-1-demux/analysis-nc-26437-xafzn-1-demux-demux-batch-320366774/main.log
time="2022-10-13T08:42:57.388Z" level=error msg="executor error: failed to put file: Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded"
time="2022-10-13T08:42:57.388Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-13T08:42:57.388Z" level=info msg="Deadline monitor stopped"
time="2022-10-13T08:42:57.388Z" level=info msg="Alloc=6313 TotalAlloc=12713 Sys=30930 NumGC=9 Goroutines=8"
time="2022-10-13T08:42:57.388Z" level=fatal msg="failed to put file: Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded"
