### ISSUE TITLE
Artifact with compressionLevel:0 failed on v3.4.1

### ISSUE THREAD

**Issue by ntdt** [argoproj/argo-workflows#9818]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

With the setting `artifact.tar.compressionLevel: 0` and an artifact `test.tar`. I have this error `Error (exit code 1): gzip: invalid header`. 

It seems like argo-workflows is expecting a gzip file even the compressionLevel is 0.

The same code works fine with v3.3.9

### Version

v3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
spec:
  entrypoint: echo
  arguments:
    artifacts:
      - name: test
        archive:
          tar:
            compressionLevel: 0
        s3:
          bucket: test-bucket
          key: test.tar
          useSDKCreds: true
          endpoint: s3.amazonaws.com
          region: ca-central-1
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
        default: Bye
      artifacts:
        - name: test
          path: /tmp/test
    container:
      image: alpine:3.7
      command: [sh, '-c']
      args:
        - |
          echo "{{inputs.parameters.message}}-modified"
```

### Logs from the workflow controller

$ kubectl logs -n argo-workflows deploy/argo-workflows-workflow-controller |  grep test-pdrd5
Found 2 pods, using pod/argo-workflows-workflow-controller-74d976d56c-bfdt2

### Logs from in your workflow's wait container

Error from server (BadRequest): container "wait" in pod "test-pdrd5" is terminated
