### ISSUE TITLE
View Manifest error on inline node

### ISSUE THREAD

**Issue by ibotdotout** [argoproj/argo-workflows#9841]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

What happened:

Got error page when click view Manifest from inline node.

- ![Screen Shot 2565-10-16 at 18 24 58](https://user-images.githubusercontent.com/686676/196032917-21b81e69-82c7-48b1-8281-920ef9217275.png)
- ![Screen Shot 2565-10-16 at 18 26 24](https://user-images.githubusercontent.com/686676/196032923-ad188466-c7ea-4c38-9549-e837c87c1744.png)
- ![Screen Shot 2565-10-16 at 18 54 23](https://user-images.githubusercontent.com/686676/196034005-ced52d13-9193-422d-ac23-01d689ea2034.png)

Expected:
- able to view Manifest as normal

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# examples/dag-inline-workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-inline-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      This example demonstrates running a DAG with inline templates.
    workflows.argoproj.io/version: ">= 3.2.0"
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: a
            inline:
              container:
                image: argoproj/argosay:v2
```

### Logs from the workflow controller

N/A

### Logs from in your workflow's wait container

N/A
