### ISSUE TITLE
Upload/download artifact directly from/to cloud storage: Add ability to do these tasks with artifact's metadata

### ISSUE THREAD

**Issue by doanphihai** [argoproj/argo-workflows#9879]
# Summary
Downloading/Uploading artifacts from/to S3 or any cloud-storage is working perfectly, but in some scenario I'd like to do that with some metadata

What change needs making?
- Add `metadata` field to `outputs.artifacts` e.g.
```yaml
     outputs:
        artifacts:
          - name: test-data
            path: >-
              /tmp/test.data
            metadata:
              - name: mt-1
                value: vl-1
              - name: mt-2
                value: {{=sprig.trim(workflow.parameters.some_value)}}
            archive:
              none:
                {}
            s3:
              key: >-
                path/to/file
              region: >-
                ca-central-1
              bucket: >- 
                my-bucket
              endpoint: s3.amazonaws.com
              useSDKCreds: true

```
- Add `with-metadata` to `inputs.artifacts` as follow:
```yaml
     inputs:
        artifacts:
          - name: test-data
            path: >-
              /tmp/test.data
            with-metadata: "true"
            archive:
              none:
                {}
            s3:
              key: >-
                path/to/file
              region: >-
                ca-central-1
              bucket: >- 
                my-bucket
              endpoint: s3.amazonaws.com
              useSDKCreds: true

```
- Add a new variable to `inputs.artifacts.test-data.metadata` to allow access to metadata of `test-data`.
# Use Cases

When would you use this?
Some scenario needs more information from artifact's metadata rather than artifact's content. An ability to enrich data using metadata and pass them around argo workflow will ask more flexibility on handling complex use cases.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.
