### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by shiraOvadia** [argoproj/argo-workflows#9896]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

We upgrade argo to V3.4.2x
I run flow with 10000 sequence 
After few minutes we get errors 
fatal error: concurrent map read and map write

This bug happens also in previous version, the latest version we know that its was ok is : 3.2.9

### Version

V3.4.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-  # Name of this Workflow
spec:
  entrypoint: engine
  podGC:
    strategy: OnPodSuccess
  templates:
  - name: whalesay            # Defining the "whalesay" template
    container:
      image: docker/whalesay
      command: ['sh','-c']
      args: ["cowsay hello world && sleep 600"]   # This template runs "cowsay" in the "whalesay" image with arguments "hello world"
      resources:
        requests:
          memory: "3Gi"
          cpu: "2000m"
        limits:
          memory: "3Gi"
          cpu: "2000m"
  - name: engine
    parallelism: 7000
    steps:
      - - name: whalesay
          template: whalesay
          withSequence:
            count:  10000
```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
[log_controller.txt](https://github.com/argoproj/argo-workflows/files/9846823/log_controller.txt)

### Logs from in your workflow's wait container

kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
[wait.log](https://github.com/argoproj/argo-workflows/files/9846824/wait.log)
