### ISSUE TITLE
The "argo server" command fails since workflow-controller-configmap has modified

### ISSUE THREAD

**Issue by ognjen-it** [argoproj/argo-workflows#9905]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When I deployed custom *workflow-controller-configmap*, the `argo server --auth-mode server -n argo` command is falling with log:
`FATA[2022-10-25T15:50:26.920Z] dial tcp 10.0.0.114:5432: connect: operation timed out`

The IP address from the log is the IP address of PostgresDB (AWS RDS) which is accessible only from the k8s cluster (VPC).
Argo Workflow Controller has full privileged and it created tables as expected.

Output form Postgres:
```
I have no name!@debug-postgresql-0:/$ psql -h postgres-rds.1234456abcd.eu-central-1.rds.amazonaws.com -U argo -d argo
Password for user argo: 
psql (14.2, server 13.6)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

argo=> \dn
List of schemas
  Name  | Owner 
--------+-------
 public | argo
(1 row)

argo=> \dt
                    List of relations
 Schema |              Name              | Type  | Owner 
--------+--------------------------------+-------+-------
 public | argo_archived_workflows        | table | argo
 public | argo_archived_workflows_labels | table | argo
 public | argo_workflows                 | table | argo
 public | schema_history                 | table | argo
(4 rows)

argo=> 
```

### Version

v3.4.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# This file describes the config settings available in the workflow controller configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  persistence: |
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
      connMaxLifetime: 10s # 0 means connections don't have a max lifetime
    #  if true node status is only saved to the persistence DB to avoid the 1MB limit in etcd
    nodeStatusOffLoad: false
    # save completed workloads to the workflow archive
    archive: true
    # the number of days to keep archived workflows (the default is forever)
    archiveTTL: 180d
    # skip database migration if needed.
    skipMigration: true

    # LabelSelector determines the workflow that matches with the matchlabels or matchrequirements, will be archived.
    # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    archiveLabelSelector:
      matchLabels:
        workflows.argoproj.io/archive-strategy: "always"

    # Optional name of the cluster I'm running in. This must be unique for your cluster.
    # clusterName: thingsolver-common
    postgresql:
      host: postgres-rds.1234456abcd.eu-central-1.rds.amazonaws.com
      port: 5432
      database: argo
      tableName: argo_workflows
      # the database secrets must be in the same namespace of the controller
      userNameSecret:
        name: argo-postgres-config
        key: username
      passwordSecret:
        name: argo-postgres-config
        key: password
      ssl: false
      # sslMode must be one of: disable, require, verify-ca, verify-full
      # you can find more information about those ssl options here: https://godoc.org/github.com/lib/pq
      sslMode: disable
```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller

```
time="2022-10-25T13:48:29Z" level=info msg="index config" indexWorkflowSemaphoreKeys=true
time="2022-10-25T13:48:29Z" level=info msg="cron config" cronSyncPeriod=10s
time="2022-10-25T13:48:29Z" level=info msg="Memoization caches will be garbage-collected if they have not been hit after" gcAfterNotHitDuration=30s
time="2022-10-25T13:48:29.303Z" level=info msg="not enabling pprof debug endpoints"
time="2022-10-25T13:48:29.316Z" level=info msg="Get configmaps 200"
time="2022-10-25T13:48:29.320Z" level=info msg="Configuration:\nartifactRepository: {}\ninitialDelay: 0s\nmetricsConfig: {}\nnodeEvents: {}\npersistence:\n  archive: true\n  archiveLabelSelector:\n    matchLabels:\n      workflows.argoproj.io/archive-strategy: always\n  archiveTTL: 4320h0m0s\n  connectionPool:\n    connMaxLifetime: 10s\n    maxIdleConns: 100\n  postgresql:\n    database: argo\n    host: postgres-rds.1234456abcd.eu-central-1.rds.amazonaws.com\n    passwordSecret:\n      key: password\n      name: argo-postgres-config\n    port: 5432\n    sslMode: disable\n    tableName: argo_workflows\n    userNameSecret:\n      key: username\n      name: argo-postgres-config\n  skipMigration: true\npodSpecLogStrategy: {}\nsso:\n  clientId:\n    key: \"\"\n  clientSecret:\n    key: \"\"\n  issuer: \"\"\n  redirectUrl: \"\"\n  sessionExpiry: 0s\ntelemetryConfig: {}\n"
time="2022-10-25T13:48:29.320Z" level=info msg="Persistence configuration enabled"
time="2022-10-25T13:48:29.324Z" level=info msg="Get secrets 200"
time="2022-10-25T13:48:29.329Z" level=info msg="Get secrets 200"
time="2022-10-25T13:48:29.339Z" level=info msg="Persistence Session created successfully"
time="2022-10-25T13:48:29.339Z" level=info msg="DB migration is disabled"
time="2022-10-25T13:48:29.339Z" level=info msg="Node status offloading is disabled"
time="2022-10-25T13:48:29.339Z" level=info msg="Workflow archiving is enabled"
time="2022-10-25T13:48:29.339Z" level=info executorImage="quay.io/argoproj/argoexec:latest" executorImagePullPolicy= managedNamespace=argo
I1025 13:48:29.340235       1 leaderelection.go:248] attempting to acquire leader lease argo/workflow-controller...
time="2022-10-25T13:48:29.347Z" level=info msg="Get leases 200"
time="2022-10-25T13:48:29.347Z" level=info msg="new leader" leader=workflow-controller-75496b9cf9-jhr2b
time="2022-10-25T13:48:34.663Z" level=info msg="Get leases 200"
time="2022-10-25T13:48:42.323Z" level=info msg="Get leases 200"
time="2022-10-25T13:48:47.919Z" level=info msg="Get leases 200"
time="2022-10-25T13:48:47.928Z" level=info msg="Update leases 200"
I1025 13:48:47.928411       1 leaderelection.go:258] successfully acquired lease argo/workflow-controller
time="2022-10-25T13:48:47.928Z" level=info msg="new leader" leader=workflow-controller-75496b9cf9-mnmn7
time="2022-10-25T13:48:47.928Z" level=info msg="Starting Workflow Controller" defaultRequeueTime=10s version=untagged
time="2022-10-25T13:48:47.928Z" level=info msg="Current Worker Numbers" podCleanup=4 workflow=32 workflowTtl=4
time="2022-10-25T13:48:47.928Z" level=info msg="Watching task results" labelSelector="!workflows.argoproj.io/controller-instanceid,workflows.argoproj.io/workflow"
time="2022-10-25T13:48:47.928Z" level=info msg=Plugins executorPlugins=false
time="2022-10-25T13:48:47.934Z" level=info msg="Get leases 200"
time="2022-10-25T13:48:47.937Z" level=info msg="Create events 201"
time="2022-10-25T13:48:47.939Z" level=info msg="Update leases 200"
time="2022-10-25T13:48:47.950Z" level=info msg="List workflows 200"
time="2022-10-25T13:48:47.953Z" level=info msg="Manager initialized successfully"
time="2022-10-25T13:48:47.955Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2022-10-25T13:48:47.956Z" level=info msg="Watch configmaps 200"
time="2022-10-25T13:48:47.956Z" level=info msg="List workflowartifactgctasks 200"
time="2022-10-25T13:48:47.957Z" level=info msg="List workflowtaskresults 200"
time="2022-10-25T13:48:47.957Z" level=info msg="List workflowtasksets 200"
time="2022-10-25T13:48:47.958Z" level=info msg="List workflowtemplates 200"
time="2022-10-25T13:48:47.959Z" level=info msg="List pods 200"
time="2022-10-25T13:48:47.959Z" level=info msg="List configmaps 200"
time="2022-10-25T13:48:47.960Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2022-10-25T13:48:47.967Z" level=info msg="Watch workflowtasksets 200"
time="2022-10-25T13:48:47.967Z" level=info msg="Watch workflowartifactgctasks 200"
time="2022-10-25T13:48:47.968Z" level=info msg="Watch workflowtemplates 200"
time="2022-10-25T13:48:47.968Z" level=info msg="Watch configmaps 200"
time="2022-10-25T13:48:47.969Z" level=info msg="Watch pods 200"
time="2022-10-25T13:48:47.970Z" level=info msg="Create selfsubjectaccessreviews 201"
time="2022-10-25T13:48:47.970Z" level=warning msg="Controller doesn't have RBAC access for ClusterWorkflowTemplates"
time="2022-10-25T13:48:47.970Z" level=info msg="Watch workflowtaskresults 200"
time="2022-10-25T13:48:47.977Z" level=info msg="List workflows 200"
time="2022-10-25T13:48:47.998Z" level=info msg="Watch workflows 200"
time="2022-10-25T13:48:48.072Z" level=info msg="Performing periodic GC" periodicity=5m0s
time="2022-10-25T13:48:48.072Z" level=info msg="Performing archived workflow GC" periodicity=24h0m0s ttl=15552000000000000
time="2022-10-25T13:48:48.072Z" level=info msg="Starting CronWorkflow controller"
time="2022-10-25T13:48:48.072Z" level=info msg="Starting prometheus metrics server at localhost:9090/metrics"
time="2022-10-25T13:48:48.072Z" level=info msg="Starting workflow garbage collector controller (retentionWorkers 4)"
time="2022-10-25T13:48:48.072Z" level=info msg="Started workflow garbage collection"
W1025 13:48:48.072901       1 shared_informer.go:401] The sharedIndexInformer has started, run more than once is not allowed
time="2022-10-25T13:48:48.074Z" level=info msg="List workflows 200"
time="2022-10-25T13:48:48.074Z" level=info msg="List cronworkflows 200"
time="2022-10-25T13:48:48.077Z" level=info msg="Watch workflows 200"
time="2022-10-25T13:48:48.077Z" level=info msg="Watch cronworkflows 200"
time="2022-10-25T13:48:48.087Z" level=info msg="Queueing Succeeded workflow argo/A1-2c92p for delete in 52m36s due to TTL"
time="2022-10-25T13:48:48.087Z" level=info msg="Queueing Failed workflow argo/A2-j8mpc for delete in 19h49m46s due to TTL"
time="2022-10-25T13:48:48.087Z" level=info msg="Queueing Succeeded workflow argo/A3-bvv7s for delete in 1h14m21s due to TTL"
time="2022-10-25T13:48:52.946Z" level=info msg="Get leases 200"
time="2022-10-25T13:48:52.951Z" level=info msg="Update leases 200"
time="2022-10-25T13:48:57.957Z" level=info msg="Get leases 200"
time="2022-10-25T13:48:57.963Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:02.969Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:02.977Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:07.984Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:07.990Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:12.998Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:13.006Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:18.013Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:18.020Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:23.029Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:23.039Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:28.044Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:28.050Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:33.059Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:33.065Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:38.071Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:38.078Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:43.086Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:43.093Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:48.098Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:48.104Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:53.113Z" level=info msg="Get leases 200"
time="2022-10-25T13:49:53.118Z" level=info msg="Update leases 200"
time="2022-10-25T13:49:58.123Z" level=info msg="Get leases 200"
```

### Logs from in your workflow's wait container

There is no wait container since it's the controller
