### ISSUE TITLE
Malformed WorkflowTemplate and Workflow crashes related UI

### ISSUE THREAD

**Issue by pockyhe** [argoproj/argo-workflows#9947]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I tried to submit my workflowtemplate in Argo. And I'm supposed to set parameters for templateref in my workflow template like the following figure
![image](https://user-images.githubusercontent.com/64390829/199438357-cf751fe0-c059-4641-9c85-9898d35cd7b4.png)
However, I forgot to add parameters in arguments
![image](https://user-images.githubusercontent.com/64390829/199438437-f329ae35-039e-45e9-96a3-19f6e3b0d4ab.png)
When I submited it, Argo didn't mentioned malformat error. It directly crashed in UI like this. It cannot list all workflow templates
<img width="1868" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/64390829/199438675-a0b33259-f9c6-4e54-be87-679c2b27e5d6.png">
As situation in Workflow.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: buildkit
spec:
  arguments:
    parameters:
      - name: repo
        value: https://github.com/argoproj/argo-workflows
      - name: branch
        value: master
      - name: path
        value: test/e2e/images/argosay/v2
      - name: image
        value: alexcollinsintuit/argosay:v2
  entrypoint: main
  # We use a volume claim template so that we can have a shared workspace.
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 64Mi
  templates:
    - name: main
      dag:
        tasks:
          - name: clone
            template: clone
            arguments:
                - name: repo
                  value: "{{workflow.parameters.repo}}"
                - name: branch
                  value: "{{workflow.parameters.branch}}"
          - name: build
            template: build
            arguments:
              parameters:
                - name: path
                  value: "{{workflow.parameters.path}}"
            depends: "clone"
          - name: image
            template: image
            arguments:
                - name: path
                  value: "{{workflow.parameters.path}}"
                - name: image
                  value: "{{workflow.parameters.image}}"
            depends: "build"
    - name: clone
      inputs:
        parameters:
          - name: repo
          - name: branch
      container:
        volumeMounts:
          - mountPath: /work
            name: work
        image: alpine/git:v2.26.2
        workingDir: /work
        # Do a shallow clone, which is the fastest way to clone, by using the
        # --depth, --branch, and --single-branch options
        args:
          - clone
          - --depth
          - "1"
          - --branch
          - "{{inputs.parameters.branch}}"
          - --single-branch
          - "{{inputs.parameters.repo}}"
          - .
    - name: build
      inputs:
        parameters:
          - name: path
      container:
        image: golang:1.13
        volumeMounts:
          - mountPath: /work
            name: work
        workingDir: /work/{{inputs.parameters.path}}
        env:
          # Because this is not a Gomodule, we must turn modules off.
          - name: GO111MODULE
            value: "off"
        command:
          - go
        args:
          - build
          - -v
          - -o
          - argosay
          - ./...
    - name: image
      inputs:
        parameters:
          - name: path
          - name: image
      # Mount the configuration so we can push the image.
      # This should create the /.docker/config.json file.
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
      container:
        image: moby/buildkit:v0.9.3-rootless
        volumeMounts:
          - name: work
            mountPath: /work
          - name: docker-config
            mountPath: /.docker
        workingDir: /work/{{inputs.parameters.path}}
        env:
          - name: BUILDKITD_FLAGS
            value: --oci-worker-no-process-sandbox
          - name: DOCKER_CONFIG
            value: /.docker
        command:
          - buildctl-daemonless.sh
        args:
          - build
          - --frontend
          - dockerfile.v0
          - --local
          - context=.
          - --local
          - dockerfile=.
          - --output
          - type=image,name=docker.io/{{inputs.parameters.image}},push=true
```

### Logs from the workflow controller

kubectl logs -n argo time="2022-11-02T02:13:32.976Z" level=error msg="finished unary call with code Unknown" error="json: cannot unmarshal array into Go struct field Template.items.spec.templates.steps of type v1alpha1.Arguments" grpc.code=Unknown grpc.method=ListWorkflowTemplates deploy/workflow-controller | grep ${workflow}

### Logs from in your workflow's wait container

None
