### ISSUE TITLE
GCS Artifact path handling does not normalise the path. 

### ISSUE THREAD

**Issue by isubasinghe** [argoproj/argo-workflows#9958]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Paths with '..' in them are not currently handled in the GCS driver. We should not error out if a key contains '..' in its path, we should normalise that key first. 

### Version

4f1451e9c605b807a9a82c298b5d0b74c6ff9b4c

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-gcs-
spec:
  entrypoint: input-artifact-gcs-example
  templates:
    - name: input-artifact-gcs-example
      inputs:
        artifacts:
          - name: my-art
            path: /my-artifact
            gcs:
              bucket: relative-paths-gcs
              # key could be either a file or a directory.
              key: b/ba/../text_v2.txt
              # serviceAccountKeySecret is a secret selector.
              # It references the k8s secret named 'my-gcs-credentials'.
              # This secret is expected to have have the key 'serviceAccountKey',
              # containing the base64 encoded Google Cloud Service Account Key (json)
              # to the bucket.
              #
              # If it's running on GKE, and Workload Identity is used,
              # serviceAccountKeySecret is not needed.
              serviceAccountKeySecret:
                name: pipekit-gcs-creds
                key: serviceAccountKey
      container:
        image: debian:latest
        command: [sh, -c]
        args: ["ls -l /my-artifact"]
```

### Logs from the workflow controller

N/A I will supply the fix myself. 

### Logs from in your workflow's wait container

N/A I will supply the fix myself.
