### ISSUE TITLE
Cannot reference plugin's output parameters

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-workflows#9966]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I tried to reference the output of a plugin step. The output failed to resolve. 

```
$ argo submit test.yaml
FATA[2022-11-03T21:43:30.628Z] Failed to submit workflow: templates.bash-script-example.steps failed to resolve {{steps.generate.outputs.result}} 
# after changing the argument
$ argo submit test.yaml
FATA[2022-11-03T21:44:18.613Z] Failed to submit workflow: templates.bash-script-example.steps failed to resolve {{steps.generate.outputs.parameters.out}} 
```

### Version

v3.4.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scripts-bash-
spec:
  entrypoint: bash-script-example
  templates:
    - name: bash-script-example
      steps:
        - - name: generate
            template: gen-random-int
        - - name: print
            template: print-message
            arguments:
              parameters:
                - name: message
                  value: "{{steps.generate.outputs.result}}"
    - name: gen-random-int
      plugin:
        test: {}
    - name: print-message
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo result was: {{inputs.parameters.message}}"]
```

### Logs from the workflow controller

n/a, this error was from the CLI

### Logs from in your workflow's wait container

n/a, this error was from the CLI
