### ISSUE TITLE
OnExit doesn't work in WorkflowTemplate

### ISSUE THREAD

**Issue by pockyhe** [argoproj/argo-workflows#9988]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I tried to enable OnExit in Workflow Template. And wrote another workflow where includes this workflow template. However, On Exit didn't work.
![image](https://user-images.githubusercontent.com/64390829/200322213-86ad4410-b859-442d-aba1-e12209bca165.png)

### Version

v3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: exit-handlers
spec:
  entrypoint: intentional-fail
  onExit: exit-handler
  templates:
  # primary workflow template
  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]
  - name: exit-handler
    steps:
    - - name: celebrate
        template: celebrate
        when: "{{workflow.status}} == Succeeded"
      - name: cry
        template: cry
        when: "{{workflow.status}} != Succeeded"
  - name: celebrate
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo hooray!"]
  - name: cry
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo boohoo!"]


-----------------------------------

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: exit-workflow
spec:
  arguments:
    parameters:
    - name: scenario-id
      value: "9107fef0-7675-4a4a-93b9-5f8f19f15668"
  entrypoint: exit-workflow
  templates:
    - name: exit-workflow
      inputs:
        parameters:
        - name: scenario-id
      steps:
        - - name: workflow-exit
            templateRef: 
                name: exit-handlers
                template: intentional-fail
            arguments:
              parameters:
                - name: scenario-id
                  value: '{{inputs.parameters.scenario-id}}'
```

### Logs from the workflow controller

![image](https://user-images.githubusercontent.com/64390829/200322380-1ede16ff-0dba-40c5-8a69-343b3cb1f807.png)

### Logs from in your workflow's wait container

none
